### ISSUE TITLE
test/topology: let's not wait for schema agreement by default

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#11554] opened 2022-09-15 10:41 UTC
If we kill nodes and perform schema changes concurrently or in quick succession, schema agreement waits will fail due to https://github.com/scylladb/python-driver/issues/168.

In https://github.com/scylladb/scylladb/pull/11544 the limit for schema agreement wait in driver configuration in topology tests was set to `20` seconds. But that means in some situations the driver will sleep for no reason for `20` seconds, making the test run longer for no reason.

I propose we set the default wait time to `0`. If some test needs to wait e.g. because it plans to perform DMLs after the schema change, it can explicitly call for a wait.

cc @kostja @alecco @nyh

**Comment by nyh** [comment] 2022-09-15 10:54
@kbr- to make it easier to write tests, it would be good if each operation would simply wait for **this** operation to finish. In other words, I think:
1. A topology operation like removing a node should wait until the node node dies and **the driver** notices that it died.
2. A schema-modifying operation should wait until the modification is visible on all nodes ("schema agreement"). If I remember correctly this is what the driver already does - it waits for schema agreement before returning from a schema-modifying operation?

If I understand correctly, if we do both my suggestions above (I think suggestion 2 is already the default), the deadlock in https://github.com/scylladb/python-driver/issues/168 will be gone, because the "ondown" callback will be finished first, and only then will the caller do the schema operation.

I'm not a big fan about your suggestion where tests will needto explicitly call a function like wait_for_schema_agreement() after a CREATE TABLE. The problem is that if someone forgets to add that call, then on **most** runs, the wait is not needed because everything happens so fast, so nobody will notice the wait is missing. But I'm worried that then tests will start to fail randomly (or on very slow setups) because in some cases, we didn't wait enough.

**Comment by kbr-** [comment] 2022-09-15 11:00
>     1. A topology operation like removing a node should wait until the node node dies and **the driver** notices that it died.
> 
>     (...)
> 
> 
> If I understand correctly, if we do both my suggestions above (I think suggestion 2 is already the default), the deadlock in [scylladb/python-driver#168](https://github.com/scylladb/python-driver/issues/168) will be gone, because the "ondown" callback will be finished first, and only then will the caller do the schema operation.

I think the purpose of these tests is to see what happens when we perform these operations concurrently or in quick succession.

It wouldn't be good to wait after killing a node before we do anything else - that defeats the purpose completely; the purpose is to see whether we can continue working in this hostile environment when nodes are dying unexpectedly.

Note that by default it takes the Scylla cluster 20 seconds to notice that a node is unavailable (failure detector settings) so this is also how long it takes for the driver to notice (it receives a notification from Scylla). So we would just move the 20 second wait from one place to another.

**Comment by nyh** [comment] 2022-09-15 11:19
> I think the purpose of these tests is to see what happens when we perform these operations concurrently or in quick succession.

I guess you're right that there would be _some_ tests that have this purpose. You would still be able to do this by explicitly running the node kill and schema modification in parallel, without waiting for either. But I think the situation today - where the node kill **does wait**, but just doesn't wait enough (it doesn't wait for the driver to recognize the node was killed) - seems like a bug to me and not anything you'll ever want to keep. I think if we just fix this bug (and our node-kill code will wait for the driver to recognize the ondown event), the deadlock will immediately go away.
 
> It wouldn't be good to wait after killing a node before we do anything else - that defeats the purpose completely; the purpose is to see whether we can continue working in this hostile environment when nodes are dying unexpectedly.

So let's kill nodes in a background thread (or in your framework - a future without awaiting for it). If for some reason you really want to wait only for half of the job (kill the node) but not the other half (the driver notices the node died) then you can add a special option or operation to do that. I think 99% of the multi-node tests (a la dtest) will never want to use this option.

> Note that by default it takes the Scylla cluster 20 seconds to notice that a node is unavailable (failure detector settings) so this is also how long it takes for the driver to notice (it receives a notification from Scylla). So we would just move the 20 second wait from one place to another.

Needless to say, any test which needs to sleep 20 seconds is out of the question (this is exactly what I don't like about dtest). All 700 Alternator tests together,  17,000 lines of code - take 20 seconds together ;-)
Perhaps there is a way to "hack" the Python driver to retry the healthcheck test immediately (right after killing the node) instead of waiting 20 seconds? I'm not saying it is trivial, but maybe it isn't very difficult either. And I think it will make the lives of test developers easier (you don't need to remember to call wait_for_schema_agreement() in tests, and don't need to debug rare random failures caused by forgetting to call it).

**Comment by kbr-** [comment] 2022-09-15 11:24
> But I think the situation today - where the node kill does wait, 

I don't think it does wait for anything, it just sends the kill signal and proceeds - what wait are you speaking of?

**Comment by kbr-** [comment] 2022-09-15 11:25
Ah, it does wait for the process to finish, true.

**Comment by kbr-scylla** [comment] 2023-06-20 11:59
The solution is to fix the Python driver, not this. Disabling schema agreement wait will only introduce more flakiness. Closing.

**Closed by kbr-scylla** 2023-06-20 11:59 UTC
Labels: test, raft, test.py
