### ISSUE TITLE
Flaky ttl_test.py::TestDistributedTTL::test_ttl_is_respected_on_repair

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#12789] opened 2023-02-09 11:54 UTC
Failed once: https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4176/
then passed: https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4190/

Both report

```
[2023-02-03T23:14:14.450Z] >       assert list_res == expected, error
[2023-02-03T23:14:14.450Z] E       AssertionError: Expected [[1, 1, None, None], [2, 2, None, None]] from SELECT * FROM ttl_table;, but got [[1, 1, None, None]]
```

in logs

**Comment by nyh** [comment] 2023-02-09 17:05
Yet another duplicate of #11684

**Closed by nyh** 2023-02-09 17:05 UTC
Labels: CI-Stability
