### ISSUE TITLE
[dtest, tablets, hintedhandoffs] test_remove_node_during_index_build: Unexpected errors found: hints_manager - Exception when draining 127.0.13.2: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18007] opened 2024-03-25 15:30 UTC
Scylla version 5.5.0~dev-0.20240324.6bdb456fadfe
scylladb/scylla-dtest@8e3b9340

https://jenkins.scylladb.com/view/master/job/scylla-master/job/tablets/job/gating-dtest-release-with-tablets/12/testReport/secondary_indexes_test/TestSecondaryIndexes/FullDtest___full_split003___test_remove_node_during_index_build/
```
failed on teardown with "AssertionError: Unexpected errors found: [('node3', ['ERROR 2024-03-25 08:56:32,938 [shard 0:strm] hints_manager - Exception when draining 127.0.13.2: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/jenkins/workspace/scylla-master/tablets/gating-dtest-release-with-tablets/scylla/.dtest/dtest-v3sl8yub/test/node3/hints/0/127.0.13.2])']), ('node4', ['ERROR 2024-03-25 08:56:32,936 [shard 1:strm] hints_manager - Exception when draining 127.0.13.2: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/jenkins/workspace/scylla-master/tablets/gating-dtest-release-with-tablets/scylla/.dtest/dtest-v3sl8yub/test/node4/view_hints/1/127.0.13.2])', 'ERROR 2024-03-25 08:56:32,938 [shard 0:strm] hints_manager - Exception when draining 127.0.13.2: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/jenkins/workspace/scylla-master/tablets/gating-dtest-release-with-tablets/scylla/.dtest/dtest-v3sl8yub/test/node4/hints/0/127.0.13.2])'])]"
```

This doesn't happen without `--tablets` so we may not drain (view) hints properly with tablets.

Cc @ShlomiBalalis. You saw an issue on SCT with hintedhandoffs enabled where c-stress failed on "too many hints", right?

**Comment by bhalevy** [comment] 2024-03-25 15:30
@ptrsmrn / @dawmd can you please look into this issue?
Cc @kostja

**Comment by bhalevy** [comment] 2024-03-25 15:34
[logs.tar.gz](https://github.com/scylladb/scylladb/files/14746065/logs.tar.gz)

**Comment by mykaul** [comment] 2024-03-25 16:06
https://github.com/scylladb/scylladb/issues/17023#issuecomment-2017821709 perhaps?

**Comment by bhalevy** [comment] 2024-03-25 21:40
> [#17023 (comment)](https://github.com/scylladb/scylladb/issues/17023#issuecomment-2017821709) perhaps?

possibly.  cc @piodul @dawmd

**Comment by bhalevy** [comment] 2024-04-01 10:45
There's also #17209, we should close duplicates and leave only one issue to track if they are all caused by the same root cause.

**Comment by piodul** [comment] 2024-04-03 12:52
Closing this one as a duplicate of https://github.com/scylladb/scylladb/issues/17023

**Closed by piodul** 2024-04-03 12:52 UTC
Labels: area/hinted handoff, area/tablets
