### ISSUE TITLE
Possible bug related to GSI updates of range key

### ISSUE THREAD

**Issue by Zak-Kent** [scylladb/scylladb#17119] opened 2024-02-02 00:38 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): scylladb/scylla:5.1.9

Hello,

I'm wondering if I'm encountering an edge case related to #11801 which may indicate a possible bug with GSI updates when using the DynamoDB alternator. The test case below passes when I run the test against AWS but fails when I run the test against Scylladb.

I added the following test to [test/alternator/test_gsi.py](https://github.com/scylladb/scylladb/blob/master/test/alternator/test_gsi.py#L575) and ran the test with: `pytest -k test_11801 test_gsi.py`

``` python

# Test similar to test_11801 and test_11801_variant2. The main difference 
# being that this test updates the range key 'b' to a new value and then
# updates 'b' back to its original value. test_11801_variant2 did something
# similar but didn't switch 'b' back to its original value after changing it to 
# 'newb'. Seeing this fail when run against Scylladb's Alternator, but succeed 
# when run against AWS
def test_11801_variant5(test_table_gsi_3):
    p = random_string()
    a = random_string()
    b = random_string()
    item = {'p': p, 'a': a, 'b': b, 'd': random_string()}
    test_table_gsi_3.put_item(Item=item)
    assert_index_query(test_table_gsi_3, 'hello', [item],
        KeyConditions={'a': {'AttributeValueList': [a], 'ComparisonOperator': 'EQ'},
                       'b': {'AttributeValueList': [b], 'ComparisonOperator': 'EQ'}})

    # Change the GSI range key 'b' to a different value
    newb = random_string()
    item['b'] = newb
    test_table_gsi_3.update_item(Key={'p':  p}, AttributeUpdates={'b': {'Value': newb, 'Action': 'PUT'}})
    assert item == test_table_gsi_3.get_item(Key={'p': p}, ConsistentRead=True)['Item']
    assert_index_query(test_table_gsi_3, 'hello', [item],
        KeyConditions={'a': {'AttributeValueList': [a], 'ComparisonOperator': 'EQ'},
                       'b': {'AttributeValueList': [newb], 'ComparisonOperator': 'EQ'}})

    # Change the GSI range key 'b' back to its original value.
    # This results in the item being dropped out of the GSI but it's still in the table
    item['b'] = b
    test_table_gsi_3.update_item(Key={'p':  p}, AttributeUpdates={'b': {'Value': b, 'Action': 'PUT'}})
    assert item == test_table_gsi_3.get_item(Key={'p': p}, ConsistentRead=True)['Item']

    # The assertion below fails with the Scylladb and succeeds with AWS. The GSI doesn't find any items in the failing case
    assert_index_query(test_table_gsi_3, 'hello', [item],
        KeyConditions={'a': {'AttributeValueList': [a], 'ComparisonOperator': 'EQ'},
                       'b': {'AttributeValueList': [b], 'ComparisonOperator': 'EQ'}})
```

Please let me know if you want any additional information, or if I might be missing any important details. 

Also, many thanks for the alternator docs and test suite, they really helped make investigating this more approachable!

**Comment by nyh** [comment] 2024-02-05 14:08
Thanks for the great reproducing test. I can sadly confirm it does demonstrate a bug. I'll look into it.

**Comment by nyh** [comment] 2024-02-05 16:27
I'm still debugging this. I can confirm the bug only occurs when the GSI has **two** new key columns (which weren't keys in the base). The problem is in the timestamp calculation, which is wrong: All modifications get the **same** timestamp, so the second modification is ignored. The bug is in `view_updates::compute_row_marker()`, that the timestamp is taken from the first key column, which the update didn't modify and has an old timestamp, instead of from the second key column, which the update did modify and has a new timestamp on every modification.

Clearly the comment:
```
    // WARNING: The code assumes that if multiple regular base columns are present in the view key,
    // they share liveness information. It's true especially in the only case currently allowed by CQL,
    // which assumes there's up to one non-pk column in the view key. It's also true in alternator,
    // which does not carry TTL information.
```
is wrong. It is true Alternator doesn't have TTL, and if both GSI-key columns are set by the same command they will indeed have the same timestamp - but it's also possible to modify just one of the GSI-key columns, in which case the other one will still have the old timestamp!

I'm thinking that taking the **latest** timestamp from either key column will solve this bug, but I need to test this and also consider what else might break.

**Comment by nyh** [comment] 2024-02-05 16:54
I have a fix for this issue. I need to clean the patch up, and test it some more, and will hopefully submit it later tonight.

**Comment by nyh** [comment] 2024-02-05 16:57
I added the backport tags - the fix for this issue should be backported everywhere, it can be a serious bug for users who use this specific combination of features (Alternator with GSI that has two key columns that weren't key columns in the base).

**Comment by nyh** [comment] 2024-02-05 18:40
I created a fix, https://github.com/scylladb/scylladb/pull/17172. @Zak-Kent please review and/or test this on your workload.

**Comment by zak-kent-cog** [comment] 2024-02-07 04:28
@nyh thank you for such a quick response! 

I spent a bit of time today trying to get a dev build of your `fix-17119` branch following the [dev/building docs](https://github.com/scylladb/scylladb/blob/master/docs/dev/building.md), but the build was failing for me using dbuild. 

If I get more time later this week I'll try again. Alternatively, if there is an already built docker image for your PR that's available publicly I could use that to test the behavior on my end. I'm fairly confident that if the test passes it will fix the issue I was seeing. Thanks again!

**Comment by nyh** [comment] 2024-02-07 08:08
When https://github.com/scylladb/scylladb/pull/17172 is merged, the day afterwards you will be able to use the Scylla "nightly" docker image. Until then, there's probably a way to use the docker image generated by the CI system that tests each pull request, but I don't know what it is ;-)

**Closed** 2024-02-13 11:25 UTC
Labels: type/bug, user request, area/materialized views, area/alternator, backport/5.2, backport/5.4

**Comment by mykaul** [comment] 2024-03-13 12:16
@nyh - does this need to be backported? To which releases?

**Comment by nyh** [comment] 2024-03-13 12:22
> @nyh - does this need to be backported? To which releases?

As I justified above, https://github.com/scylladb/scylladb/issues/17119#issuecomment-1927473304, it should be backported to 5.2 and 5.4. I also added tags saying that.

I tried adding backport tags to the PR that fixed this, https://github.com/scylladb/scylladb/pull/17172, but nothing automagical happened. So I'll do the backports manually now.

**Comment by mykaul** [comment] 2024-03-13 12:39
@yaronkaikov - is the bot sleeping / on a strike?

**Comment by yaronkaikov** [comment] 2024-03-13 12:40
> @yaronkaikov - is the bot sleeping / on a strike?

Again , this is an issue. We need to get my patch review/merged before it will work
