### ISSUE TITLE
Collection column indexing

### ISSUE THREAD

**Issue by penberg** [scylladb/scylladb#2962] opened 2017-11-14 09:48 UTC
Add support for creating secondary indexes on collection type columns.

**Comment by penberg** [comment] 2018-04-18 14:09
The relevant Apache Cassandra issues are:

https://issues.apache.org/jira/browse/CASSANDRA-4511

https://issues.apache.org/jira/browse/CASSANDRA-6383

https://issues.apache.org/jira/browse/CASSANDRA-8473

**Comment by nyh** [comment] 2018-04-22 18:04
@duarten I think the answer is "frozen". If I understand correctly, when indexing either sets or lists, the key in the index table should be the individual values - not the entire set as a whole. So one row in the base table would be translated to many partitions in the index table, basically many copies of the same row under many keys. I think we'll need special support for MV doing that, that it doesn't currently have (?) and then the SI support will come automatically.

**Comment by duarten** [comment] 2018-04-22 18:34
We could represent this at the schema level by an MV whose partition key column name maps to a collection regular column in the base, and whose type is that of the collection's elements (might be tricker for maps). Then, when generating view updates, delete and insert N view rows based on the collection's contents. This would work both for frozen and unfrozen collections.

**Comment by nyh** [comment] 2018-04-29 23:02
According to https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlCreateIndex.html, Cassandra defaults to indexing the values of a map column, but if you use KEYS(column) as a "target", the keys are indexed instead. You also have the option to use ENTRIES(column) or FULL(column) for frozen collections.
It seems our code already has some support for this syntax, but I don't think it was ever tested, or even supposed to work. We definitely need to add tests for this syntax - even if it doesn't yet fully work - into the secondary_index unit test.

**Comment by duarten** [comment] 2018-08-03 16:20
I created https://github.com/scylladb/scylla/issues/3654 to track the support for indexing frozen collections. That issue is mostly about syntax and validation.

This issue should remain about indexing multi-cell collections, which means indexing their individual elements, which requires a bit more work.

**Comment by slivne** [comment] 2019-01-08 14:30
@psarna - you have added collection indexing - no ?

not clear to me what is left to close this issue

**Comment by psarna** [comment] 2019-01-08 14:50
That - no. There were patches that implemented filtering on collections,
but indexing them is still open, because it also depends on introducing
appropriatr collections support for mvs.

**Comment by slivne** [comment] 2019-01-08 19:42
Right my bad ...

**Comment by tcaxias-talkdesk** [comment] 2019-02-20 17:28
Well, great feature. Bumping the feature request!

**Comment by psarna** [comment] 2019-03-13 09:53
I gave some thought on this issue regarding unfrozen collections. If we were to start with solving https://github.com/scylladb/scylla/issues/3512 (`computed` column type), then the MV partition key could be a computed column too, and the computation would just extract the needed value from a collection. If we implement `computed` column type flexibly enough, it should be fairly easy to implement various kinds of indexing here - keys, entries, single value, etc. Thoughts?

**Comment by nyh** [comment] 2019-03-13 10:32
@psarna maybe this is somehow related to computed columns (although I don't think we really need any general support for "computed" columns just to get the specific feature discussed here), but there's an additional complication that there are multiple different values inside each collection, so each write now becomes N separate writes.

**Comment by duarten** [comment] 2019-03-13 10:34
I agree it's worth it to solve this with some structure and not in ad-hoc way.

**Comment by tesla3** [comment] 2019-05-08 00:12
Great feature! Bumping for feature request!

**Comment by zaddok** [comment] 2020-07-31 01:21
I receive this error upon doing the following (cut down) example.

```
create table if not exists person (
        site text,
        uuid text,
        first_name text,
        last_name text,
        email set<text>,
        phone set<text>,
        email_info set<frozen <email_info>>,
        password text,
        primary key ((site), uuid))
create index if not exists person_index1 on person (email)
```

This definitely works in cassandra. I am assuming Scylla doesn't support this, is that correct? (I just want to double check, It feels like this type of search is basic enough that it should be possible)

**Comment by avikivity** [comment] 2020-08-02 13:12
@psarna ^

**Comment by psarna** [comment] 2020-08-02 13:21
@zaddok yup, indexing collections by elements is not supported yet. Right now it's only possible to index a full collection (by calling `create index on person(full(email))` and it only works for frozen collections. That doesn't allow for searching for specific elements though, only the whole collections, e.g. `SELECT * FROM person WHERE email_info = {'a@b.c', 'd@e.f', 'g@h.i'}`

**Comment by zaddok** [comment] 2020-08-02 13:37
Thanks for the clarification.

Just to be clear, I am super pressed with the work being done on Scylla, (I've always thought to myself "how amazing would Cassandra be if it wasn't written in Java"), I'll am quite excited about the project. I am keenly looking forward until this feature is ready.

**Comment by dorlaor** [comment] 2020-08-03 06:30
@slivne @psarna worth to schedule it in the near future, for @zaddok's sake and for all the future followers

**Comment by nyh** [comment] 2021-03-10 08:49
Tests reproducing the missing support for indexing of unfrozen collection elements:
* In cql-pytest, translated from Cassandra's unit tests:  `cassandra_tests/validation/entities/secondary_index_on_map_entries_test.py`. The tests fail when trying to create the index, with the message "Cannot create secondary index on non-frozen collection or UDT column v".
* In C++ unit tests, `test/boost/secondary_index_test.cc`, the test function `test_secondary_index_collections` is hard-coded to assume this feature doesn't work. When we add this feature, we need to fix the test to test that it works, not that it doesn't work :-)

**Comment by horschi** [comment] 2021-04-06 13:59
Support for ENTRIES on frozen maps would be nice have.

**Comment by zaddok** [comment] 2021-05-10 11:19
I saw the tag for 4.5 and downloaded the 4.5 nightly via docker, to check if this made it into 4.5. It looks like it didn't, is that correct? (Not complaining, just excited to start using scylladb, and I index sets quite a lot)

**Closed** 2022-08-16 23:21 UTC
Labels: cassandra 2.2 compatibility, sec-index

**Comment by zaddok** [comment] 2022-08-23 08:32
This is amazing. Testing this out now.

**Comment by avikivity** [comment] 2022-08-23 08:41
Not a bug, not backporting.

**Comment by zaddok** [comment] 2022-08-23 09:02
Yes, I’m just awkwardly trying to express thanks for this :)

**Comment by avikivity** [comment] 2022-08-23 09:05
> Yes, I’m just awkwardly trying to express thanks for this :)

My comment wasn't a response to yours, just one of the chores we have to do (classify commits for  backporting if they are fixing bugs, or mark them as not needing backports).
