### ISSUE TITLE
topology_experimental_raft.test_tablets: test_tablet_split: Invalid tablet id: 2 >= 2

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#18085] opened 2024-03-28 11:48 UTC
Seen in: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7775/

```
terminate called after throwing an instance of 'std::logic_error'
  what():  Invalid tablet id: 2 >= 2
Aborting on shard 0.
Backtrace:
  0xd5c600a
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x492058c
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x49201e3
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x475b0c8
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x478bc95
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4886789
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4886ace
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x48868de
  /lib64/libc.so.6+0x3dbaf
  /lib64/libc.so.6+0x8e883
  /lib64/libc.so.6+0x3dafd
  /lib64/libc.so.6+0x2687e
  /lib64/libstdc++.so.6+0xa4d18
  /lib64/libstdc++.so.6+0xb4f4b
  /lib64/libstdc++.so.6+0xb4fb6
  0xd75e73a
  0xe891397
  0x129324a5
  0x12931ad4
  0x129bd3fb
  0x12b1da96
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x477dbfe
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4786120
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x478a142
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4787d63
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x42af28a
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x42ac82a
  0xd65fa09
  0xd65c8ef
  /lib64/libc.so.6+0x27b89
  /lib64/libc.so.6+0x27c4a
  0xd5808e4
------ Ending test debug/topology_experimental_raft.test_tablets.5::test_tablet_split ------
```

Logs:
[scylla-2665.log](https://github.com/scylladb/scylladb/files/14788931/scylla-2665.log)
[scylla-2666.log](https://github.com/scylladb/scylladb/files/14788933/scylla-2666.log)
[topology_experimental_raft.test_tablets.5.log](https://github.com/scylladb/scylladb/files/14788934/topology_experimental_raft.test_tablets.5.log)

**Comment by denesb** [comment] 2024-03-28 11:55
Resolved backtrace:
```
[Backtrace #0]
__interceptor_backtrace at ??:?
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x492058c 
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x49201e3 
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x475b0c8 
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x478bc95 
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x4886789 
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x4886ace 
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x48868de 
siginterrupt at ??:?
tr_where at ??:?
sigstack at ??:?
__GI_abort at :?
std::__throw_ios_failure(char const*) at ??:?
__gnu_cxx::__verbose_terminate_handler() at ??:?
__gnu_cxx::__verbose_terminate_handler() at ??:?
__clang_call_terminate at main.cc:?
replica::table::table_load_stats(std::function<bool (locator::global_tablet_id)>) const at ./replica/table.cc:2012
operator() at ./service/storage_service.cc:5864
seastar::future<locator::load_stats> std::__invoke_impl<seastar::future<locator::load_stats>, service::storage_service::load_stats_for_tablet_based_tables()::$_2 const&, replica::database&>(std::__invoke_other, service::storage_service::load_stats_for_tablet_based_tables()::$_2 const&, replica::database&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
 (inlined by) std::__invoke_result<service::storage_service::load_stats_for_tablet_based_tables()::$_2 const&, replica::database&>::type std::__invoke<service::storage_service::load_stats_for_tablet_based_tables()::$_2 const&, replica::database&>(service::storage_service::load_stats_for_tablet_based_tables()::$_2 const&, replica::database&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:96
 (inlined by) std::invoke_result<service::storage_service::load_stats_for_tablet_based_tables()::$_2 const&, replica::database&>::type std::invoke<service::storage_service::load_stats_for_tablet_based_tables()::$_2 const&, replica::database&>(service::storage_service::load_stats_for_tablet_based_tables()::$_2 const&, replica::database&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/functional:113
 (inlined by) operator() at ././seastar/include/seastar/core/sharded.hh:401
 (inlined by) seastar::future<locator::load_stats> seastar::futurize<seastar::future<locator::load_stats> >::invoke<seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&>(seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:2022
seastar::futurize<std::invoke_result<seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::type>::type seastar::smp::submit_to<seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::smp_submit_to_options, seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&&) at ././seastar/include/seastar/core/smp.hh:367
 (inlined by) seastar::futurize<std::invoke_result<seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::type>::type seastar::smp::submit_to<seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&&) at ././seastar/include/seastar/core/smp.hh:394
 (inlined by) operator() at ././seastar/include/seastar/core/sharded.hh:399
 (inlined by) seastar::future<locator::load_stats> seastar::futurize<seastar::future<locator::load_stats> >::invoke<seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}&, unsigned int>(seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}&, unsigned int&&) at ././seastar/include/seastar/core/future.hh:2022
 (inlined by) auto seastar::futurize_invoke<seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}&, unsigned int>(seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}&, unsigned int&&) at ././seastar/include/seastar/core/future.hh:2053
 (inlined by) seastar::future<locator::load_stats> seastar::map_reduce<boost::range_detail::integer_iterator<unsigned int>, seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}, locator::load_stats, std::plus<locator::load_stats> >(boost::range_detail::integer_iterator<unsigned int>, boost::range_detail::integer_iterator<unsigned int>, seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>)::{lambda(unsigned int)#1}&&, locator::load_stats, std::plus<locator::load_stats>) at ././seastar/include/seastar/core/map_reduce.hh:192
 (inlined by) seastar::future<locator::load_stats> seastar::sharded<replica::database>::map_reduce0<service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats> >(service::storage_service::load_stats_for_tablet_based_tables()::$_2, locator::load_stats, std::plus<locator::load_stats>) at ././seastar/include/seastar/core/sharded.hh:404
 (inlined by) service::storage_service::load_stats_for_tablet_based_tables() at ./service/storage_service.cc:5827
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<locator::load_stats>::promise_type>::resume() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/coroutine:240
 (inlined by) seastar::internal::coroutine_traits_base<locator::load_stats>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:83
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x477dbfe 
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x4786120 
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x478a142 
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x4787d63 
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x42af28a 
/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so 0x42ac82a 
scylla_main(int, char**) at ./main.cc:675
std::function<int (int, char**)>::operator()(int, char**) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
 (inlined by) main at ./main.cc:2158
__libc_start_main at ??:?
__libc_start_main at ??:?
_start at ??:?
```

**Comment by denesb** [comment] 2024-03-28 11:56
@benipeled why is there no coredump saved?

**Comment by benipeled** [comment] 2024-04-01 10:00
> @benipeled why is there no coredump saved?

@denesb is there a way to reproduce this or a similar case so we can check coredump saved as expected? 
I see no reason why it wasn't generated 
```
[2024-03-28T08:31:29.431Z] + ls -1 /jenkins/coredumps
[2024-03-28T08:31:29.431Z] + wc -l
[2024-03-28T08:31:29.805Z] [Pipeline] echo
[2024-03-28T08:31:29.810Z] No coredump files found in /jenkins/coredumps
```

**Comment by benipeled** [comment] 2024-04-01 10:01
btw, did you manage to see and use coredump files on other failures?

**Comment by raphaelsc** [comment] 2024-04-01 12:05
it seems to be a race between tablet load stats and split completion, will see what I can do to synchronize them in the replica side.

**Comment by denesb** [comment] 2024-04-02 10:43
> btw, did you manage to see and use coredump files on other failures?

I have used coredumps from crashes in CI, but not recently. So I have no idea if this is just an outlier of we have a regression.

**Comment by tchaikov** [comment] 2024-04-26 12:43
@benipeled a coredump was collected this time. see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8252/artifact/

**Comment by tchaikov** [comment] 2024-05-02 03:14
please note, we also have
```
terminate called after throwing an instance of 'std::logic_error'
  what():  Invalid tablet id: 3 >= 2
Aborting on shard 1.
Backtrace:
```

in https://github.com/scylladb/scylladb/issues/18492

**Comment by raphaelsc** [comment] 2024-05-02 11:38
> please note, we also have
> 
> ```
> terminate called after throwing an instance of 'std::logic_error'
>   what():  Invalid tablet id: 3 >= 2
> Aborting on shard 1.
> Backtrace:
> ```
> 
> in #18492 which turns out a dup of this issue.

yes, it's only a different manifestation of same bug

**Comment by tchaikov** [comment] 2024-05-05 23:25
```
terminate called after throwing an instance of 'std::logic_error'
  what():  Invalid tablet id: 1 >= 1
DEBUG 2024-05-05 19:25:54,682 [shard 1:strm] table - Memtable is empty
Aborting on shard 0.
```
[scylla-3223.log](https://github.com/scylladb/scylladb/files/15214904/scylla-3223.log)

**Comment by benipeled** [comment] 2024-05-08 08:08
Again on master https://jenkins.scylladb.com/job/scylla-master/job/next/7608/testReport/junit/(root)/test_tablets/Build___aarch64___Unit_Tests_aarch64___test_tablet_split/

**Comment by bhalevy** [comment] 2024-05-23 10:08
let's see if this reproduces now with dynamic allocation of storage groups.

**Comment by bhalevy** [comment] 2024-05-23 10:08
If not, I suggest we close the issue

**Comment by raphaelsc** [comment] 2024-05-23 10:39
> If not, I suggest we close the issue

PR to address it is still ongoing.

**Closed** 2024-05-27 18:18 UTC
Labels: P1, symptom/ci stability, status/release blocker, area/tablets
