### ISSUE TITLE
nodetool getsstables and /column_family/sstables/by_key/ can crash the server

### ISSUE THREAD

**Issue by shawjef3** [scylladb/scylladb#17232] opened 2024-02-08 15:11 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [✓] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.1.13-0.20230622.b635a30b59a9
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS Linux release 7.9.2009 (Core)

`nodetool getsstables` and `curl -s http://127.0.0.1:10000/column_family/sstables/by_key/...` can crash the Scylla server. This can be a server with load or no load. I also observed this on a larger cluster. Multiple servers can go down while others stay up. It doesn't correlate with the replication factor.

```
Feb 08 09:55:16 hostname scylla[26130]: scylla: ./seastar/src/core/fstream.cc:205: virtual seastar::file_data_source_impl::~file_data_source_impl(): Assertion `_reads_in_progress == 0' failed.
Feb 08 09:55:16 hostname scylla[26130]: Aborting on shard 4.
Feb 08 09:55:16 hostname scylla[26130]: Backtrace:
Feb 08 09:55:16 hostname scylla[26130]: 0x4d514a8
Feb 08 09:55:16 hostname scylla[26130]: 0x4d80bb2
Feb 08 09:55:16 hostname scylla[26130]: 0x7f6cd8213a1f
Feb 08 09:55:16 hostname scylla[26130]: /opt/scylladb/libreloc/libc.so.6+0x3d2a1
Feb 08 09:55:16 hostname scylla[26130]: /opt/scylladb/libreloc/libc.so.6+0x268a3
Feb 08 09:55:16 hostname scylla[26130]: /opt/scylladb/libreloc/libc.so.6+0x26788
Feb 08 09:55:16 hostname scylla[26130]: /opt/scylladb/libreloc/libc.so.6+0x35a15
Feb 08 09:55:16 hostname scylla[26130]: 0x4d1538d
Feb 08 09:55:16 hostname scylla[26130]: 0x4d15398
Feb 08 09:55:16 hostname scylla[26130]: 0x19c03d7
Feb 08 09:55:16 hostname scylla[26130]: 0x1acb019
Feb 08 09:55:16 hostname scylla[26130]: 0x4d60c34
Feb 08 09:55:16 hostname scylla[26130]: 0x4d62017
Feb 08 09:55:16 hostname scylla[26130]: 0x4d81065
Feb 08 09:55:16 hostname scylla[26130]: 0x4d349da
Feb 08 09:55:16 hostname scylla[26130]: /opt/scylladb/libreloc/libpthread.so.0+0x92a4
Feb 08 09:55:16 hostname scylla[26130]: /opt/scylladb/libreloc/libc.so.6+0x100322
Feb 08 09:55:16 hostname scylla[26130]: scylla: ./seastar/src/core/fstream.cc:205: virtual seastar::file_data_source_impl::~file_data_source_impl(): Assertion `_reads_in_progress == 0' failed
```

**Comment by shawjef3** [comment] 2024-02-08 15:25
`nodetool describecluster` show all servers have the same schema version.

**Comment by mykaul** [comment] 2024-02-08 15:34
We've had a bug there in the past - with a malfored sstable (https://github.com/scylladb/scylladb/issues/13836 ) - perhaps you are hitting it?
(also note that 5.1.x is end-of-life, you should probably upgrade to a newer release)

**Comment by shawjef3** [comment] 2024-02-08 17:59
@mykaul I ran `sstableverify` on the table and it didn't report any errors.

**Comment by shawjef3** [comment] 2024-02-09 16:50
@mykaul I'm able to reproduce this with `latest` and previous versions back to tag `5.1`. It doesn't happen 100% of the time. If it works once it keeps working, but usually it crashes as long as I'm inserting values.

```
docker run  --name=crash-test --expose=10000 -p 19042 --expose=22 --expose=7000 --expose=7001 -p 9042 --expose=9160 --expose=9180 scylladb/scylla:latest --smp 2
```

```
CREATE KEYSPACE tests WITH replication={'class':'SimpleStrategy','replication_factor':1};
CREATE TABLE tests.slow (
    key bigint PRIMARY KEY
);
```

Then from a session I start inserting sequential keys starting from 0. While that runs I do

```
docker exec -it crash-test nodetool getsstables tests slow 123
```

which usually prints

```
nodetool: Unable to connect to Scylla API server: java.net.ConnectException: Connection refused (Connection refused)
See 'nodetool help' or 'nodetool help <command>'.
```

If I don't insert anything, or just a couple of keys like `1` and `123`, `nodetool` has no output, but also the server remains running. Following is a crash log for `latest`, which right now is `5.4.2`. I don't know if the `Compacting` message is relevant.

```
INFO  2024-02-09 16:45:47,351 [shard 1:comp] compaction - [Compact tests.slow acbbbe70-c76a-11ee-b47d-4c2066908764] Compacting [/var/lib/scylla/data/tests/slow-990a3d70c76a11ee83f64c1f66908764/me-3gdh_1ak6_2w6002qt6ou5oae4bo-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/tests/slow-990a3d70c76a11ee83f64c1f66908764/me-3gdh_1ajw_4j3ww2qt6ou5oae4bo-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/tests/slow-990a3d70c76a11ee83f64c1f66908764/me-3gdh_1ak1_4pje82qt6ou5oae4bo-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/tests/slow-990a3d70c76a11ee83f64c1f66908764/me-3gdh_1ajs_273802qt6ou5oae4bo-big-Data.db:level=0:origin=memtable]
scylla: seastar/src/core/fstream.cc:230: virtual seastar::file_data_source_impl::~file_data_source_impl(): Assertion `_reads_in_progress == 0' failed.
Aborting on shard 1.
Backtrace:
  0x35b6bab
  0x35e6bef
  linux-vdso.so.1+0x79f
  /opt/scylladb/libreloc/libc.so.6+0x90a6f
  /opt/scylladb/libreloc/libc.so.6+0x44b3f
  /opt/scylladb/libreloc/libc.so.6+0x30287
  /opt/scylladb/libreloc/libc.so.6+0x3db93
  /opt/scylladb/libreloc/libc.so.6+0x3dc0f
  0x357c9bf
  0x357c9d3
  0x193cb5f
  0x193ca83
  0x19489ff
  0x19a43af
  0x19ccd2b
  0x15f4fd7
  0x35c56e7
  0x35c65ef
  0x35e70bf
  0x359c2c7
  /opt/scylladb/libreloc/libc.so.6+0x8edb3
  /opt/scylladb/libreloc/libc.so.6+0xfd55b
2024-02-09 16:46:02,957 INFO exited: scylla (terminated by SIGABRT; not expected)
```

**Comment by mykaul** [comment] 2024-02-11 08:09
I assume (but I'd be happy for you to verify) that you are not running out of storage space?

**Comment by shawjef3** [comment] 2024-02-11 16:21
It doesn't seem to be due to running out of disk space.

This time I was inserting rows more slowly. I had to wait a lot longer to be able to get `nodetool getsstables` to crash Scylla this time, so it seems that if it does work once, it might not work later. When I changed my program to insert rows quickly, `nodetool getsstables` crashes much sooner.

The scylla data dir in the container is `/var/lib/scylla/data`. It's mounted to `/var/lib/docker/volumes/fc598b1e234b861cde02a0ddfc77ee1f0676550c93f8f3505f2802e7f2348bb4/_data` on the host.

This is from the host before the crash.
```
Filesystem                Size      Used Available Use% Mounted on
/dev/vda1                58.4G     47.8G      7.6G  86% /var/lib
```

This is on the host after the crash.
```
Filesystem                Size      Used Available Use% Mounted on
/dev/vda1                58.4G     48.5G      6.9G  88% /var/lib
```

Something I didn't do before is allow the service to restart. This time I did and I looked at the log for the restart. It looks like the crash causes file corruption.
```
2024-02-11 16:11:34,925 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
WARN  2024-02-11 16:11:35,619 [shard 1] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-18014399321593430.log. 23461880 bytes skipped.
WARN  2024-02-11 16:11:40,305 [shard 0] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-812111467.log. 14155768 bytes skipped.
INFO  2024-02-11 16:11:48,046 [shard 0] commitlog_replayer - Log replay complete, 7979584 replayed mutations (0 invalid, 0 skipped)
```

**Comment by mykaul** [comment] 2024-02-12 07:38
Commit log corruption after a service crash is expected and is normal.

**Comment by mykaul** [comment] 2024-02-12 07:38
@denesb - who can look at this issue?

**Comment by denesb** [comment] 2024-02-13 08:14
@Deexie can you please try to reproduce and investigate?

**Comment by denesb** [comment] 2024-02-13 08:16
I tried to reproduce yesterday with an empty table on master, but it didn't reproduce.
Maybe we should start by decoding the trace at https://github.com/scylladb/scylladb/issues/17232#issuecomment-1936259689 and try to figure out possible failure scenarios.

**Comment by mykaul** [comment] 2024-02-13 08:32
@shawjef3 - can you share the build ID, so we'll be able to fully decode the trace?

**Comment by shawjef3** [comment] 2024-02-13 15:16
@mykaul how do I find the build id?

@denesb This morning I created a program to automate reproducing this. https://github.com/shawjef3/getsstables-crash I've had it only fail to reproduce the issue a couple times. Usually it fails within a minute of the Scylla container starting. You can change the docker image it runs on line 49 of the java file.

**Comment by mykaul** [comment] 2024-02-13 15:24
> @mykaul how do I find the build id?

It's in the logs - as Scylla starts, it prints the version and build ID.
> 
> @denesb This morning I created a program to automate reproducing this. https://github.com/shawjef3/getsstables-crash Sometimes it takes a few minutes for Scylla to crash. You can change the docker image it runs on line 49 of the java file.

**Comment by shawjef3** [comment] 2024-02-13 15:38
@mykaul here's two data points for you.

```
Scylla version 5.1.19-0.20231127.0f2269afbf9c with build-id d29d93a02b3c9e72dcf737fa7952a150f9d469f1 starting ...
...
scylla: ./seastar/src/core/fstream.cc:205: virtual seastar::file_data_source_impl::~file_data_source_impl(): Assertion `_reads_in_progress == 0' failed.
Aborting on shard 1.
Backtrace:
  0x27e1a7f
  0x280c8ef
  linux-vdso.so.1+0x79f
  /opt/scylladb/libreloc/libc.so.6+0x3874f
  /opt/scylladb/libreloc/libc.so.6+0x247db
  /opt/scylladb/libreloc/libc.so.6+0x319c7
  /opt/scylladb/libreloc/libc.so.6+0x31a3f
  0x27abf8b
  0x27abf9f
  0x117229f
  0x11709ff
  0x117f5fb
  0x11f1d23
  0x12208f7
  0x27eedef
  0x27efe37
  0x280cd13
  0x27c866f
  /opt/scylladb/libreloc/libpthread.so.0+0x8007
  /opt/scylladb/libreloc/libc.so.6+0xda5db
```


```
Scylla version 5.4.2-0.20240117.6c625e8cd3c6 with build-id b9cdd1c0bdb026ff8e3e2cc0174acaa3589b1ec2 starting ...
...
scylla: seastar/src/core/fstream.cc:230: virtual seastar::file_data_source_impl::~file_data_source_impl(): Assertion `_reads_in_progress == 0' failed.
Aborting on shard 1.
Backtrace:
  0x35b6bab
  0x35e6bef
  linux-vdso.so.1+0x79f
  /opt/scylladb/libreloc/libc.so.6+0x90a6f
  /opt/scylladb/libreloc/libc.so.6+0x44b3f
  /opt/scylladb/libreloc/libc.so.6+0x30287
  /opt/scylladb/libreloc/libc.so.6+0x3db93
  /opt/scylladb/libreloc/libc.so.6+0x3dc0f
  0x357c9bf
  0x357c9d3
  0x193cb5f
  0x193ca83
  0x19489ff
  0x19a43af
  0x19ccd2b
  0x15f4fd7
  0x35c56e7
  0x35c65ef
  0x35e70bf
  0x359c2c7
  /opt/scylladb/libreloc/libc.so.6+0x8edb3
  /opt/scylladb/libreloc/libc.so.6+0xfd55b
```

**Comment by greedygithubrequiresloginsnow** [comment] 2024-02-13 15:47
Reproduced, with the build info snippet
```
INFO  2024-02-13 15:35:12,859 [shard 0] init - Scylla version 5.2.1-0.20230508.f1c45553bc29 with build-id 88ac66b1719cc7c5b7e982aa34ba5dc95909b84a starting ...
 
...
BUILD SUCCESSFUL in 3m 58s
2 actionable tasks: 1 executed, 1 up-to-date
```


```
uname -a; cat /proc/cpuinfo | awk '/processor.*0/,/^$/'; free -hw
Linux jk-arch 6.7.3-arch1-2 #1 SMP PREEMPT_DYNAMIC Fri, 02 Feb 2024 17:03:55 +0000 x86_64 GNU/Linux
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 165
model name	: Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz
stepping	: 2
cpu MHz		: 2808.008
cache size	: 12288 KB
physical id	: 0
siblings	: 6
core id		: 0
cpu cores	: 6
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch tpr_shadow flexpriority ept vpid fsgsbase bmi1 avx2 bmi2 invpcid rdseed clflushopt arat vnmi md_clear flush_l1d arch_capabilities
vmx flags	: vnmi invvpid ept_x_only flexpriority tsc_offset vtpr vapic ept vpid unrestricted_guest ple
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs itlb_multihit srbds mmio_stale_data retbleed gds
bogomips	: 5618.01
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

               total        used        free      shared     buffers       cache   available
Mem:            22Gi        14Gi       7.0Gi       204Mi        23Mi       1.5Gi       8.0Gi
Swap:           23Gi        14Gi       9.9Gi

```


Which is arch linux virtualbox guest on windows 10 enterprise 22H2 host:
```
Processor	Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz   2.81 GHz
Installed RAM	32.0 GB (31.7 GB usable)
System type	64-bit operating system, x64-based processor 
```

**Comment by shawjef3** [comment] 2024-02-13 16:02
Here's with a nightly build.

```
Scylla version 5.5.0~dev-0.20240211.13e16475fabb with build-id 155eca419cef95b6429a4ad42483e828be0ba4dc starting ...
...
scylla: seastar/src/core/fstream.cc:230: virtual seastar::file_data_source_impl::~file_data_source_impl(): Assertion `_reads_in_progress == 0' failed.
Aborting on shard 1.
Backtrace:
  0x5ca5418
  0x5cdbac1
  /opt/scylladb/libreloc/libc.so.6+0x3dbaf
  /opt/scylladb/libreloc/libc.so.6+0x8e883
  /opt/scylladb/libreloc/libc.so.6+0x3dafd
  /opt/scylladb/libreloc/libc.so.6+0x2687e
  /opt/scylladb/libreloc/libc.so.6+0x2679a
  /opt/scylladb/libreloc/libc.so.6+0x36186
  0x5c50abb
  0x5c50ac8
  0x234478c
  0x23df995
  0x2423775
  0x1c3652a
  0x5cb704f
  0x5cb8337
  0x5cdc0b0
  0x5c7784a
  /opt/scylladb/libreloc/libc.so.6+0x8c946
  /opt/scylladb/libreloc/libc.so.6+0x112763
```

**Comment by mykaul** [comment] 2024-02-13 16:22
For Scylla version 5.5.0~dev-0.20240211.13e16475fabb with build-id 155eca419cef95b6429a4ad42483e828be0ba4dc , I get:
```
Backtrace:[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:826
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:856
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:868
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:4074
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4050
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:4046
/data/scylla-s3-reloc.cache/by-build-id/155eca419cef95b6429a4ad42483e828be0ba4dc/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f888be5f5e7d58e04cabb8c675c7ab94e77dd68c, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
__assert_fail_base.cold at ??:?
__assert_fail at ??:?
~file_data_source_impl at ./build/release/seastar/./seastar/src/core/fstream.cc:230
~file_data_source_impl at ./build/release/seastar/./seastar/src/core/fstream.cc:227
std::default_delete<seastar::data_source_impl>::operator()(seastar::data_source_impl*) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:99
 (inlined by) ~unique_ptr at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:404
 (inlined by) ~data_source at ././seastar/include/seastar/core/iostream.hh:68
 (inlined by) ~input_stream at ././seastar/include/seastar/core/iostream.hh:281
 (inlined by) ~continuous_data_consumer at ./sstables/consumer.hh:464
 (inlined by) ~index_consume_entry_context at ./sstables/index_reader.hh:148
 (inlined by) std::default_delete<sstables::index_consume_entry_context<sstables::index_consumer> >::operator()(sstables::index_consume_entry_context<sstables::index_consumer>*) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:99
 (inlined by) ~unique_ptr at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:404
 (inlined by) ~index_bound at ./sstables/index_reader.hh:411
~index_reader at ./sstables/index_reader.hh:452
std::default_delete<sstables::index_reader>::operator()(sstables::index_reader*) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:99
 (inlined by) ~unique_ptr at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:404
 (inlined by) sstables::sstable::has_partition_key(utils::hashed_key const&, dht::decorated_key const&) at ./sstables/sstables.cc:2782
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<bool>::promise_type>::resume() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/coroutine:240
 (inlined by) seastar::internal::coroutine_traits_base<bool>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:83
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2678
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:3141
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3317
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4554
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0>::_M_invoke(std::_Any_data const&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:290
std::function<void ()>::operator()() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:90
start_thread at ??:?
__GI___clone at :?

```

**Comment by shawjef3** [comment] 2024-02-13 17:25
@jkushmaul gave me the idea to add flushing to the program. I set it to run `nodetool flush` every 5 seconds, and now `nodetool getsstables` much more reliably crashes Scylla.

**Comment by Deexie** [comment] 2024-02-13 20:15
Looks like closing `index_reader` would be enough.
```
--- a/sstables/sstables.cc
+++ b/sstables/sstables.cc
@@ -2779,6 +2779,7 @@ future<bool> sstable::has_partition_key(const utils::hashed_key& hk, const dht::
     try {
         auto lh_index_ptr = std::make_unique<sstables::index_reader>(s, sem.make_tracking_only_permit(_schema, s->get_filename(), db::no_timeout, {}));
         present = co_await lh_index_ptr->advance_lower_and_check_if_present(dk);
+        co_await lh_index_ptr->close();
     } catch (...) {
         ex = std::current_exception();
     }
```
But I couldn't make a reproducer. I wanted to do that with injections, but unfortunately that would require changes in seastar. I will work on it later.

@shawjef3 please change `nodetool getendpoints` to `nodetool getsstables` in title and issue description to avoid confusion

**Comment by shawjef3** [comment] 2024-02-13 20:38
@Deexie done. Thanks for pointing that out.

**Comment by jarni-ua** [comment] 2024-02-13 21:00
@Deexie As you have control over index_reader, but not over underlying seastar's input_stream or file_data_source, I suggest creating an explicit destuctor for index_reader and calling close() there (with any checks required to make it a valid operation). Otherwise you might not cover all other hidden cases where this can happen.

**Comment by denesb** [comment] 2024-02-14 07:08
> @Deexie As you have control over index_reader, but not over underlying seastar's input_stream or file_data_source, I suggest creating an explicit destuctor for index_reader and calling close() there (with any checks required to make it a valid operation). Otherwise you might not cover all other hidden cases where this can happen. This also should cover the case when exception is thrown.

This unfortunately doesn't work because you cannot wait for futures in the constructor/destructor. Not being able to use RAII is one of the biggest drawbacks of asynchronous programming in C++.

Well, you can actually wait for futures in stackful coroutines, but those are expensive (have to allocate a stack for each fiber) so we use them sparingly.

**Comment by mykaul** [comment] 2024-02-14 13:00
> Thank you everyone for giving this issue attention.
> 
> @mykaul I see you marked this to be fixed for 6.0. Is there a chance the fix will be backported?

I have no idea - we'll need to get a fix first, then assess complexity, risk, etc.

**Closed** 2024-02-25 15:24 UTC
Labels: triage/oss, P1

**Comment by denesb** [comment] 2024-02-26 06:38
@Deexie can you please check if 5.2 and 5.4 are affected?

**Comment by Deexie** [comment] 2024-02-26 15:28
> @Deexie can you please check if 5.2 and 5.4 are affected?

They are. I opened https://github.com/scylladb/scylladb/pull/17532 and https://github.com/scylladb/scylladb/pull/17531
