### ISSUE TITLE
test_validation_compaction_detects_sstable_corruption crashes scylla: validator 0x600004f1ab20 for sstable writer: Unexpected mutation fragment: partition key

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13550] opened 2023-04-17 14:54 UTC
Seen since https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/230/artifact/logs-full.release.000/1681537018015_compaction_additional_test.py%3A%3ATestValidationCompaction%3A%3Atest_validation_compaction_detects_sstable_corruption/node1.log
```
Scylla version 5.3.0~dev-0.20230415.1da02706ddb8 with build-id f7ac5cd90e63ace5065c583d6d1d9c381f39b5c2 starting ...

INFO  2023-04-15 05:36:56,778 [shard 1] sstables_loader - Loading new SSTables for keyspace=ks, table=cf, load_and_stream=false, primary_replica_only=false
INFO  2023-04-15 05:36:56,781 [shard 1] database - Resharding 837 bytes for ks.cf
INFO  2023-04-15 05:36:56,781 [shard 0] compaction - [Reshard ks.cf 891fb7d0-db4f-11ed-99cf-9536bae64a2c] Resharding [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-pu5wtsvn/test/node1/data/ks/cf-86a716b0db4f11ed99cf9536bae64a2c/upload/mc-1-big-Data.db:level=0:origin=]
ERROR 2023-04-15 05:36:56,782 [shard 0] mutation_reader - [validator 0x600004eeeb20 for sstable writer /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-pu5wtsvn/test/node1/data/ks/cf-86a716b0db4f11ed99cf9536bae64a2c/upload/me-2-big-Data.db (ks.cf 86a716b0-db4f-11ed-99cf-9536bae64a2c)] Unexpected mutation fragment: partition key {key: pk{000406000000}, token:-5566252076597558760}: previous clustering row:{position: clustered, ckp{000400000005}, 0}, current clustering row:{position: clustered, ckp{000400000003}, 0}, at: 0x57d4dce 0x57d5380 0x57d5668 0x540ce77 0x1f25683 0x1f27033 0x24b70ce 0x2350fb4 0x234f41c 0x234e6b6 0x234d2fb 0x234c571 0x234c005 0x56b7576
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::async<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>(seastar::thread_attributes, sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>(seastar::thread_attributes, sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}&&)::{lambda()#2}, seastar::future<void> >(sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::async<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>(seastar::thread_attributes, auto:1&&)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<seastar::async<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>(seastar::thread_attributes, sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}&&)::{lambda()#3}, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::future<void>::finally_body<seastar::async<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>(seastar::thread_attributes, sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}&&)::{lambda()#3}, false> >(seastar::future<void>::finally_body<seastar::async<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>(seastar::thread_attributes, sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::finally_body<seastar::async<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>(seastar::thread_attributes, auto:1&&)::{lambda()#3}, false>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::parallel_for_each_state
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::(anonymous namespace)::thread_wake_task
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&)::{lambda()#2}, seastar::future<sstables::compaction_result> >(sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>(seastar::thread_attributes, auto:1&&)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&)::{lambda()#3}, false>, seastar::future<sstables::compaction_result>::then_wrapped_nrvo<seastar::future<sstables::compaction_result>, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&)::{lambda()#3}, false> >(seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>(seastar::thread_attributes, auto:1&&)::{lambda()#3}, false>&, seastar::future_state<sstables::compaction_result>&&)#1}, sstables::compaction_result>
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<std::optional<sstables::compaction_stats> >::promise_type
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::shared_future<std::optional<sstables::compaction_stats> >::shared_state::get_future(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(seastar::future<std::optional<sstables::compaction_stats> >&&)#1}, seastar::future<std::optional<sstables::compaction_stats> >::then_wrapped_nrvo<void, seastar::shared_future<std::optional<sstables::compaction_stats> >::shared_state::get_future(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(seastar::future<std::optional<sstables::compaction_stats> >&&)#1}>(seastar::shared_future<std::optional<sstables::compaction_stats> >::shared_state::get_future(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(seastar::future<std::optional<sstables::compaction_stats> >&&)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::shared_future<std::optional<sstables::compaction_stats> >::shared_state::get_future(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(seastar::future<std::optional<sstables::compaction_stats> >&&)#1}&, seastar::future_state<std::optional<sstables::compaction_stats> >&&)#1}, std::optional<sstables::compaction_stats> >
Aborting on shard 0.
Backtrace:
  0x542c698
  0x5460b72
  /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/1da02706ddb85667861a1ea7ab1bbea3cf4a7399/libreloc/libc.so.6+0x3cb1f
  /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/1da02706ddb85667861a1ea7ab1bbea3cf4a7399/libreloc/libc.so.6+0x8ce5b
  /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/1da02706ddb85667861a1ea7ab1bbea3cf4a7399/libreloc/libc.so.6+0x3ca75
  /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/1da02706ddb85667861a1ea7ab1bbea3cf4a7399/libreloc/libc.so.6+0x267fb
  0x540cf13
  0x1f25683
  0x1f27033
  0x24b70ce
  0x2350fb4
  0x234f41c
  0x234e6b6
  0x234d2fb
  0x234c571
  0x234c005
  0x56b7576
```

Decoded:
```
[Backtrace #0]
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_3>(seastar::current_backtrace_tasklocal()::$_3&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:60
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:137
seastar::current_backtrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:170
void log_error_and_backtrace<std::basic_string_view<char, std::char_traits<char> > >(seastar::logger&, std::basic_string_view<char, std::char_traits<char> > const&) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:38
 (inlined by) seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:42
(anonymous namespace)::on_validation_error(seastar::logger&, seastar::basic_sstring<char, unsigned int, 15u, true> const&) at ./readers/mutation_reader.cc:196
mutation_fragment_stream_validating_filter::operator()(mutation_fragment_v2::kind, position_in_partition_view, std::optional<tombstone>) at ./readers/mutation_reader.cc:290
sstables::sstable_writer::consume(clustering_row&&) at ./sstables/writer.cc:52
sstables::compacted_fragments_writer::consume(clustering_row&&, row_tombstone, bool) at ./compaction/compaction.cc:998
 (inlined by) sstables::compacted_fragments_writer::consume(clustering_row&&) at ./compaction/compaction.cc:339
flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer>::consume(clustering_row&&) at ././readers/flat_mutation_reader_v2.hh:274
 (inlined by) decltype(auto) mutation_fragment_v2::consume<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >(flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer>&) && at ././mutation/mutation_fragment_v2.hh:283
flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer>::operator()(mutation_fragment_v2&&) at ././readers/flat_mutation_reader_v2.hh:268
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > std::__invoke_impl<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> >, flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer>&, mutation_fragment_v2>(std::__invoke_other, flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer>&, mutation_fragment_v2&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61
 (inlined by) std::__invoke_result<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer>&, mutation_fragment_v2>::type std::__invoke<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer>&, mutation_fragment_v2>(flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer>&, mutation_fragment_v2&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:96
 (inlined by) std::result_of<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer>& (mutation_fragment_v2&&)>::type std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >::operator()<mutation_fragment_v2>(mutation_fragment_v2&&) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/refwrap.h:358
 (inlined by) operator() at ././readers/flat_mutation_reader_v2.hh:249
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<flat_mutation_reader_v2::impl::consume_pausable_in_thread<std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >, flat_mutation_reader_v2::no_filter>(std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >, flat_mutation_reader_v2::no_filter)::{lambda()#1}>(flat_mutation_reader_v2::impl::consume_pausable_in_thread<std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >, flat_mutation_reader_v2::no_filter>(std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >, flat_mutation_reader_v2::no_filter)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:1999
 (inlined by) auto seastar::futurize_invoke<flat_mutation_reader_v2::impl::consume_pausable_in_thread<std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >, flat_mutation_reader_v2::no_filter>(std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >, flat_mutation_reader_v2::no_filter)::{lambda()#1}>(flat_mutation_reader_v2::impl::consume_pausable_in_thread<std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >, flat_mutation_reader_v2::no_filter>(std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >, flat_mutation_reader_v2::no_filter)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2030
 (inlined by) void flat_mutation_reader_v2::impl::consume_pausable_in_thread<std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >, flat_mutation_reader_v2::no_filter>(std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<sstables::compacted_fragments_writer> >, flat_mutation_reader_v2::no_filter) at ././readers/flat_mutation_reader_v2.hh:248
 (inlined by) auto flat_mutation_reader_v2::impl::consume_in_thread<sstables::compacted_fragments_writer, flat_mutation_reader_v2::no_filter>(sstables::compacted_fragments_writer, flat_mutation_reader_v2::no_filter) at ././readers/flat_mutation_reader_v2.hh:335
auto flat_mutation_reader_v2::consume_in_thread<sstables::compacted_fragments_writer, flat_mutation_reader_v2::no_filter>(sstables::compacted_fragments_writer, flat_mutation_reader_v2::no_filter) at ././readers/flat_mutation_reader_v2.hh:473
 (inlined by) auto flat_mutation_reader_v2::consume_in_thread<sstables::compacted_fragments_writer>(sstables::compacted_fragments_writer) at ././readers/flat_mutation_reader_v2.hh:479
operator() at ./compaction/compaction.cc:729
void std::__invoke_impl<void, sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>(std::__invoke_other, sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61
 (inlined by) std::__invoke_result<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>::type std::__invoke<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>(sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}&&, (std::__invoke_result&&)...) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:96
 (inlined by) decltype(auto) std::__apply_impl<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}, std::tuple<>>(sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}&&, std::tuple<>&&, std::integer_sequence<unsigned long>) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/tuple:1852
 (inlined by) decltype(auto) std::apply<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}, std::tuple<> >(sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}&&, std::tuple<>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/tuple:1863
 (inlined by) seastar::future<void> seastar::futurize<void>::apply<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>(sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:1963
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:258
 (inlined by) seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<sstables::compaction::consume_without_gc_writer(std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >)::{lambda(flat_mutation_reader_v2)#1}::operator()(flat_mutation_reader_v2)::{lambda()#1}>(seastar::thread_attributes, seastar::futurize&&, (std::invoke_result&&)...)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././seastar/include/seastar/util/noncopyable_function.hh:124
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:210
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:299
```

Reloc package: http://downloads.scylladb.com/unstable/scylla/master/relocatable/2023-04-15T03:03:29Z/scylla-unstripped-5.3.0~dev-0.20230415.1da02706ddb8.x86_64.tar.gz
Coredump: https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/230/artifact/logs-full.release.000/1681537018015_compaction_additional_test.py%3A%3ATestValidationCompaction%3A%3Atest_validation_compaction_detects_sstable_corruption/node1-scylla.78770.1681537016.core.gz

**Comment by bhalevy** [comment] 2023-04-17 14:58
@denesb mind looking into this?
I'm not sure if this has been caused by f1bbf705f9b6faa406baac04f418a93b09a53c19 or not

**Comment by denesb** [comment] 2023-04-19 10:47
> @denesb mind looking into this? I'm not sure if this has been caused by [f1bbf70](https://github.com/scylladb/scylladb/commit/f1bbf705f9b6faa406baac04f418a93b09a53c19) or not

Yes, the crash is caused by https://github.com/scylladb/scylladb/commit/f1bbf705f9b6faa406baac04f418a93b09a53c19. The test loads corrupt sstables via `nodetool refresh` which now triggers a resharding and resharding steps on the out-of-order partitions in the corrupt sstables. The test disables autocompaction to avoid this, but the above PR circumvented this by triggering resharding on refresh.

**Comment by denesb** [comment] 2023-04-19 11:00
> In addition, I don't know if it's related to the same root cause but the following dtests failed to find the expected log messages:
> https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/230/testReport/nodetool_additional_test/TestNodetool/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_scrub_sstable_with_invalid_fragment/
> https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/230/testReport/nodetool_additional_test/TestNodetool/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_scrub_segregate_sstable_with_invalid_fragment/
> https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/230/testReport/nodetool_additional_test/TestNodetool/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_validate_sstable_with_invalid_fragment/

I think it is related to the above: resharding in some cases gets rid of the OOO partitions, so by the time validation runs, the expected errors are not hit.

**Comment by DoronArazii** [comment] 2023-05-31 10:34
@denesb then we can close it? or there's additional work to do?

**Comment by denesb** [comment] 2023-05-31 10:48
Yes, the root cause has been fixed since (in dtest), so we can close this.

**Closed by denesb** 2023-05-31 10:48 UTC
Labels: dtest
