### ISSUE TITLE
Need technical documentation for materialized views

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#19627] opened 2024-07-06 06:39 UTC
We should document how materialized views operate in scylla.

Some questions to answer:
- How views are generated?
- How does base/view pairing work?
  - Both with vnodes and with tablets.
- How views are updated?
  - Both on the normal write path,
  - and using view-update-generation after repairing the base table.
  - In particular, we need to document the subtleties of what to expect when the view primary key is the same as the base table's, and when it is different.
  - What happens when some columns are update and some aren't?
  - What happens when a regular column, which is part of the view primary key, is updated on the base table?
- What are shadowable tombstones?
  - How do we use them?
  - How do they work with data reconciliation (read repair)? 
  - How are they compacted and garbage-collected?
  - How are they treated by row-level repair?
- How repairing views work?

**Comment by bhalevy** [comment] 2024-07-06 06:40
Cc @avikivity @piodul @nyh @raphaelsc @denesb @kbr-scylla

**Comment by nyh** [comment] 2024-07-07 10:57
Duplicate of https://github.com/scylladb/scylladb/issues/16569

**Closed** 2024-07-07 12:47 UTC
Labels: area/materialized views, documentation
