### ISSUE TITLE
strange result on select query

### ISSUE THREAD

**Issue by somnevaetsya** [scylladb/scylladb#12766] opened 2023-02-07 12:39 UTC
Hello, there was some unexpected behavior when using scylla.
There are migrations.
```sql
CREATE TABLE IF NOT EXISTS staff
(
    name     text,
    box         text,
    version     text,

    number     smallint,
    id       text,
    type smallint,
    creation_date  timestamp,
    author text,

    PRIMARY KEY ((name, box), creation_date, version)
    ) WITH CLUSTERING ORDER BY (creation_date DESC);

CREATE MATERIALIZED VIEW IF NOT EXISTS materialized_item AS
SELECT * FROM staff
WHERE name IS NOT NULL AND box IS NOT NULL AND version IS NOT NULL AND creation_date IS NOT NULL
    PRIMARY KEY ((name, box, version), creation_date);

CREATE INDEX IF NOT EXISTS staff_by_author ON staff (author);
CREATE INDEX IF NOT EXISTS staff_by_box ON staff (box);
CREATE INDEX IF NOT EXISTS staff_by_id ON staff((name, box), id);
```

Insert some values:
```sql
insert into staff (name, box, version, number, id, type, creation_date)VALUES ('item', 'box', 'version-1', 1, 'id', 2, '2023-02-06 06:30:00.852');
insert into staff (name, box, version, number, id, type, creation_date)VALUES ('item', 'box', 'version-2', 2, 'id', 2, '2023-02-06 06:30:00.852');
insert into staff (name, box, version, number, id, type, creation_date)VALUES ('item', 'box', 'version-3', 3, 'id', 2, '2023-02-06 06:30:00.852');
insert into staff (name, box, version, number, id, type, creation_date)VALUES ('item', 'box', 'version-4', 4, 'id', 2, '2023-02-06 06:30:00.852');
insert into staff (name, box, version, number, id, type, creation_date)VALUES ('item', 'box', 'version-5', 5, 'id', 2, '2023-02-06 06:30:00.852');
```

If we select with additional conditions and set a limit, then the behavior will be different.
Query:
```sql
select *from staff WHERE name='item' AND box='box' and id ='id' and type =2 and number > 2 limit 1 ALLOW FILTERING
```
as a result, we will get 0 rows, although in the limit we expect 1.

If we increase limit to 3, we should get 1 row in result:

```sql
select *from staff WHERE name='item' AND box='box' and id ='id' and type =2 and number > 2 limit 3 ALLOW FILTERING
```

| name | box | creation\_date | version | author | id | number | type |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| item | box | 2023-02-06 06:30:00.852 | version-3 | null | id | 3 | 2 |

This behavior seems invalid because expect 3 rows in result.

**Comment by avikivity** [comment] 2023-02-07 13:00
@cvybhu please take a look

**Comment by cvybhu** [comment] 2023-02-07 16:26
Here's a simplified example:
```cql
CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
CREATE TABLE ks.tab (p1 int, p2 int, c1 int, c2 int, r1 int, r2 int, r3 int, r4 int,
                     PRIMARY KEY ((p1, p2), c1, c2));

CREATE INDEX on ks.tab ((p1, p2), r1);

INSERT INTO ks.tab (p1, p2, c1, c2, r1, r2, r3) VALUES (0, 0, 0, 1, 123, 1, 0);
INSERT INTO ks.tab (p1, p2, c1, c2, r1, r2, r3) VALUES (0, 0, 0, 2, 123, 2, 0);
INSERT INTO ks.tab (p1, p2, c1, c2, r1, r2, r3) VALUES (0, 0, 0, 3, 123, 3, 0);
INSERT INTO ks.tab (p1, p2, c1, c2, r1, r2, r3) VALUES (0, 0, 0, 4, 123, 4, 0);
INSERT INTO ks.tab (p1, p2, c1, c2, r1, r2, r3) VALUES (0, 0, 0, 5, 123, 5, 0);

SELECT * FROM ks.tab WHERE p1 = 0 AND p2 = 0 AND r1 = 123 AND r2 > 2 AND r3 = 0 LIMIT 1 ALLOW FILTERING;
```
The columns map like this:
```
p1 - name
p2 - box
c1 - creation_date
c2 - version
r1 - id
r2 - number
r3 - type
r4 - author
```

The local index table schema would look like this:
```
CREATE TABLE (p1 int, p2 int, r1 int, c1 int, c2 int, PRIMARY KEY ((p1, p2), r1, c1, c2);
```

The query works correctly without an index. To me it looks like an instance of #10649.

**Comment by cvybhu** [comment] 2023-02-07 16:39
@nyh this might be an interesting case to add to CQL index+limit tests.
It uses a local index, while all the tests added in https://github.com/scylladb/scylladb/issues/10649#issuecomment-1252158141 use a global one.

**Comment by cvybhu** [comment] 2023-02-07 16:47
@somnevaetsya thank you for reporting, sadly it looks like it's caused by a known issue where the fix requires some fundamental refactoring, so it will take a moment to fix.

In the meantime there might be some kind of a workaround. 
Maybe selecting without the `LIMIT` keyword, but with page size set to 1 would work?
I'm not sure what's your exact use case.

**Comment by nyh** [comment] 2023-02-08 13:19
> @nyh this might be an interesting case to add to CQL index+limit tests. It uses a local index, while all the tests mentioned in [#10649 (comment)](https://github.com/scylladb/scylladb/issues/10649#issuecomment-1252158141) use a global one.

Good idea, I'll create such a test. Although I think in practice the same broken code path is involved in both local and global indexes.

**Comment by nyh** [comment] 2023-02-08 13:22
Closing as a duplicate of #10649.
Unfortunately, fixing this bug is harder than it looks (I tried, and wasn't successful). But we're planning on going back to it - and solving it - soon.

**Closed by nyh** 2023-02-08 13:22 UTC
Labels: bug, CQL, sec-index

**Comment by nyh** [comment] 2023-02-08 14:04
> @nyh this might be an interesting case to add to CQL index+limit tests. It uses a local index, while all the tests mentioned in [#10649 (comment)](https://github.com/scylladb/scylladb/issues/10649#issuecomment-1252158141) use a global one.

Created a new test in https://github.com/scylladb/scylladb/pull/12783
