### ISSUE TITLE
test_view_tombstone: AssertionError: Expected [[1, 1, 'b', 3.0]] from SELECT * FROM t_by_v WHERE v = 1, but got []

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#19146] opened 2024-06-06 13:51 UTC
https://jenkins.scylladb.com/view/master/job/scylla-master/job/tablets/job/dtest-release-with-tablets/9/testReport/materialized_views_test/TestMaterializedViews/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split002___test_view_tombstone/

Scylla version 6.1.0~dev-0.20240604.01ff8108c1b0 with build-id 7c641530a4e630e25ce1a3c89aa738d93a7aaf75

LOGS_LINK
[logs-full.release.002](https://jenkins.scylladb.com/job/scylla-master/job/tablets/job/dtest-release-with-tablets/9/artifact/logs-full.release.002)
SPLIT_NAME
full.release.002
Error Message
AssertionError: Expected [[1, 1, 'b', 3.0]] from SELECT * FROM t_by_v WHERE v = 1, but got []

Stacktrace
```
Stacktrace
self = <materialized_views_test.TestMaterializedViews object at 0x7f7f5f883830>

    def test_view_tombstone(self):
        """
        Test that a materialized views properly tombstone
        @jira_ticket CASSANDRA-10261
        @jira_ticket CASSANDRA-10910
        """
    
        self.prepare(rf=3, options={"hinted_handoff_enabled": False, "cache_hit_rate_read_balancing": False})
        node1, node2, node3 = self.cluster.nodelist()
    
        session = self.patient_exclusive_cql_connection(node1)
        session.execute("USE ks")
    
        session.execute("CREATE TABLE t (id int PRIMARY KEY, v int, v2 text, v3 decimal)")
        session.execute("CREATE MATERIALIZED VIEW t_by_v AS SELECT * FROM t " "WHERE v IS NOT NULL AND id IS NOT NULL PRIMARY KEY (v,id) " "WITH read_repair_chance = 0.0 AND dclocal_read_repair_chance = 0.0 AND speculative_retry = 'none'")
    
        session.cluster.control_connection.wait_for_schema_agreement()
    
        # Set initial values TS=0, verify
        session.execute(SimpleStatement("INSERT INTO t (id, v, v2, v3) VALUES (1, 1, 'a', 3.0) USING TIMESTAMP 0", consistency_level=ConsistencyLevel.ALL))
    
        assert_one(session, "SELECT * FROM t_by_v WHERE v = 1", [1, 1, "a", 3.0])
        session.execute(SimpleStatement("INSERT INTO t (id, v2) VALUES (1, 'b') USING TIMESTAMP 1", consistency_level=ConsistencyLevel.ALL))
    
        assert_one(session, "SELECT * FROM t_by_v WHERE v = 1", [1, 1, "b", 3.0])
    
        # change v's value and TS=3, tombstones v=1 and adds v=0 record
        session.execute(SimpleStatement("UPDATE t USING TIMESTAMP 3 SET v = 0 WHERE id = 1", consistency_level=ConsistencyLevel.ALL))
        assert_none(session, "SELECT * FROM t_by_v WHERE v = 1")
    
        logger.debug("Shutdown nodes 2 and 3")
        self.cluster.stop_nodes([node2, node3], wait_other_notice=True)
    
        session.execute(SimpleStatement("UPDATE t USING TIMESTAMP 4 SET v = 1 WHERE id = 1", consistency_level=ConsistencyLevel.ONE))
>       assert_one(session, "SELECT * FROM t_by_v WHERE v = 1", [1, 1, "b", 3.0])

materialized_views_test.py:2912: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

session = <cassandra.cluster.Session object at 0x7f7f5c45a390>
query = 'SELECT * FROM t_by_v WHERE v = 1', expected = [1, 1, 'b', 3.0]
cl = None

    def assert_one(session, query, expected, cl=None):
        """
        Assert query returns one row.
        @param session Session to use
        @param query Query to run
        @param expected Expected results from query
        @param cl Optional Consistency Level setting. Default ONE
    
        Examples:
        assert_one(session, "LIST USERS", ['cassandra', True])
        assert_one(session, query, [0, 0])
        """
        simple_query = SimpleStatement(query, consistency_level=cl)
        res = session.execute(simple_query)
        list_res = _rows_to_list(res)
>       assert list_res == [expected], f"Expected {[expected]} from {query}, but got {list_res}"
E       AssertionError: Expected [[1, 1, 'b', 3.0]] from SELECT * FROM t_by_v WHERE v = 1, but got []

tools/assertions.py:146: AssertionError
```
logs:
[logs-full.release.002.zip](https://github.com/user-attachments/files/15631292/logs-full.release.002.zip)

**Comment by mykaul** [comment] 2024-06-06 13:55
@yarongilor : 
1. Does that happen only with Tablets? Please add a label.
2. I assume it is related to materialized views (I've already added a label)
3. Is it reproducible or flaky?

**Comment by yarongilor** [comment] 2024-06-06 14:08
> @yarongilor :
> 
> 1. Does that happen only with Tablets? Please add a label.
> 2. I assume it is related to materialized views (I've already added a label)
> 3. Is it reproducible or flaky?

Not reproduced (with tablets) locally.

**Comment by nyh** [comment] 2024-06-09 20:01
I think it's a faulty test that assumes the old "self pairing" that is no longer true with tablets:
This test has a three-node cluster with RF=3, so each node has all the base data and all the view data.

The test has
```
self.cluster.stop_nodes([node2, node3], wait_other_notice=True)
 session.execute(SimpleStatement("UPDATE t USING TIMESTAMP 4 SET v = 1 WHERE id = 1", consistency_level=ConsistencyLevel.ONE))
assert_one(session, "SELECT * FROM t_by_v WHERE v = 1", [1, 1, "b", 3.0])
```

Here, only node1 is alive, so it receives the CL=ONE base-table write, but if it's pair is node2, and node2 is dead, then no view replica is written - so the SELECT fails.

This sort MV "high availability" is precisely why we used to have the "self-pairing" in MV, although the usefulness of this definition of high availability is dubious (why should Scylla continue to work with two nodes dead, and why would SELECT with CL=ONE be expected to work after a write with CL=ONE?).

See also https://github.com/scylladb/scylladb/issues/17043 about the other case of self-pairing (where the key is the same in base and view) - although the case in this issue, of N=RF=3, is much more problematic: The reason why we can't keep the "self-pairing" is that it doesn't allow us to grow from N=RF=3 to, say, N=4 without losing the correct pairing. This is why we got rid of the self-pairing :-(

**Comment by yarongilor** [comment] 2024-06-27 14:52
> I think it's a faulty test that assumes the old "self pairing" that is no longer true with tablets: This test has a three-node cluster with RF=3, so each node has all the base data and all the view data.
> 
> The test has
> 
> ```
> self.cluster.stop_nodes([node2, node3], wait_other_notice=True)
>  session.execute(SimpleStatement("UPDATE t USING TIMESTAMP 4 SET v = 1 WHERE id = 1", consistency_level=ConsistencyLevel.ONE))
> assert_one(session, "SELECT * FROM t_by_v WHERE v = 1", [1, 1, "b", 3.0])
> ```
> 
> Here, only node1 is alive, so it receives the CL=ONE base-table write, but if it's pair is node2, and node2 is dead, then no view replica is written - so the SELECT fails.
> 
> This sort MV "high availability" is precisely why we used to have the "self-pairing" in MV, although the usefulness of this definition of high availability is dubious (why should Scylla continue to work with two nodes dead, and why would SELECT with CL=ONE be expected to work after a write with CL=ONE?).
> 
> See also #17043 about the other case of self-pairing (where the key is the same in base and view) - although the case in this issue, of N=RF=3, is much more problematic: The reason why we can't keep the "self-pairing" is that it doesn't allow us to grow from N=RF=3 to, say, N=4 without losing the correct pairing. This is why we got rid of the self-pairing :-(

IIUC it's not a faulty test but rather a scylla issue of not supporting MV and RF > 1.
for example, in case RF=3:
CL-1 fails where 2 (out of 3) nodes are down.
CL Quorum may fail where 1 (out of 3) nodes is down.

**Comment by nyh** [comment] 2024-06-27 15:20
> IIUC it's not a faulty test but rather a scylla issue of not supporting MV and RF > 1. for example, in case RF=3: CL-1 fails where 2 (out of 3) nodes are down. CL Quorum may fail where 1 (out of 3) nodes is down.

I discussed exactly these issues (in the context of other tests) in https://github.com/scylladb/scylladb/issues/17043.
I answered your QUORUM example, more or less - the case where we have 3 nodes one being down, without "self-pairing":

* Durability is not really reduced - although we have just one copy of the data (instead of two) in the view replica, we do have a second copy as a view hint in the base replica that is paired to the dead view replica. This copy is durable, and will be restored when the dead node comes back.
* Consistency is not really reduced: The consistency setting read=write=QUORUM will continue to work: The read quorum will contain the two live view nodes, and since one of them is up to date, the read will see the up-to-date data.

But, if I understand correctly, you hoped that QUORUM write followed by a CL=1 read (not QUORUM read!) would work on the view. It doesn't, and it's sad (Alternator especially wishes it work work - it often does CL=1 reads), but it's not really guaranteed by anything except that "eventually" (as the dead node is brought back) it will work.

**Comment by bhalevy** [comment] 2024-07-01 11:35
@yarongilor / @ShlomiBalalis the test seems to be at fault here.
It's just assuming certain pairing between base and view replicas that is not guaranteed.

```python
        session.execute(SimpleStatement("UPDATE t USING TIMESTAMP 4 SET v = 1 WHERE id = 1", consistency_level=ConsistencyLevel.ONE))
        assert_one(session, "SELECT * FROM t_by_v WHERE v = 1", [1, 1, "b", 3.0])
```

This assert is invalid with CL=1 since with a node down there is no guarantee that all the view replicas are updated.

Say we modify the test to take only 1 node down, then there should be a guarantee that at least one of the remaining view replicas will get updated, but still not both.\

I think this assert_one should be dropped.

Then, after restarting the stopped node, we current call `assert_none`  that is somewhat superfluous and too intrusive. I.e. it assumes too much about the implementation.

Reading in that state with cl=QUORUM us insufficient IIUC, since after stopping one node, only one of the view replicas is guaranteed to be updated, not both, so reading with quorum might miss the updated view replica, so we can proceed with:
```python
        # We should get a digest mismatch, and data should be repaired
        assert_one(session, "SELECT * FROM t_by_v WHERE v = 1", [1, 1, "b", 3.0], cl=ConsistencyLevel.ALL)

        assert_one(session2, "SELECT * FROM t_by_v WHERE v = 1", [1, 1, "b", 3.0], cl=ConsistencyLevel.ONE)
```

let's open an issue in scylla-dtest about that and fix it there.

**Comment by yarongilor** [comment] 2024-07-04 13:21
@bhalevy , @nyh 
ok, i can open a dtest issue to fix, but just for the record (correct me if it's wrong) -
This test should pass according to Cassandra definitions of RF and CL.
The test probably passes ok with a Cassandra version.
A Cassandra customer will probably see it as a Scylla issue.

**Comment by nyh** [comment] 2024-07-04 13:50
> @bhalevy , @nyh ok, i can open a dtest issue to fix, but just for the record (correct me if it's wrong) - This test should pass according to Cassandra definitions of RF and CL. The test probably passes ok with a Cassandra version. A Cassandra customer will probably see it as a Scylla issue.

If you can prove this statement, with a test that runs on both Cassandra and Scylla, and/or with a reference to some documentation, we may need to create an issue analogous to https://github.com/scylladb/scylladb/issues/17043 but about the N=RF=3 case. 

But, if I understand correctly, you are suggesting that in the special case of N=RF=3 (3 nodes, RF=3), writing to the base table with QUORUM write followed by a CL=1 read to the view should work - not immediately of course (that's not even true on the base), but "quickly". Even if two nodes are down. I'm not sure Cassandra guarantees that - in theory or even in practice. I don't remember if Cassandra had the "self-pairing" feature originally or we invented it in Scylla. I'll take a look now.

**Comment by nyh** [comment] 2024-07-04 14:11
Looking at the code, unfortunately Cassandra does seem to use "self pairing"... The comment (ViewUtils.java) says:
```
     * For a view whose base token is T1 and whose view token is T3, the pairings between the nodes would be:
     *  A writes to C (A's cardinality is 1 for T1, and C's cardinality is 1 for T3)
     *  B writes to A (B's cardinality is 2 for T1, and A's cardinality is 2 for T3)
     *  C writes to B (C's cardinality is 3 for T1, and B's cardinality is 3 for T3)
```
Which suggests there is no self-pairing, but the code has:
```java
       Optional<Replica> localReplica = Iterables.tryFind(naturalViewReplicas, Replica::isSelf).toJavaUtil();
        if (localReplica.isPresent())
            return localReplica;

        ...

        // We have to remove any endpoint which is shared between the base and the view, as it will select itself
        // and throw off the counts otherwise.
        EndpointsForToken baseReplicas = naturalBaseReplicas.filter(
                r -> !naturalViewReplicas.endpoints().contains(r.endpoint()) && isLocalDC.test(r)
        );
        EndpointsForToken viewReplicas = naturalViewReplicas.filter(
                r -> !naturalBaseReplicas.endpoints().contains(r.endpoint()) && isLocalDC.test(r)
        );
```

This is the "self pairing" we had, but got rid of, claiming it hurts consistency.

So we'll definitely be behaving differently than Cassandra here, and it should not be hard to write a test that demonstrates this. The question, is - does it matter? Does Cassandra document what happens when you write to a base while two nodes are down? Do we need to be compatible with Cassandra in such "bad" cases?

**Comment by bhalevy** [comment] 2024-07-14 12:50
@yarongilor with https://github.com/scylladb/scylla-dtest/issues/4552 now fixed, can this issue be closed?

**Comment by yarongilor** [comment] 2024-07-14 13:25
> @yarongilor with [scylladb/scylla-dtest#4552](https://github.com/scylladb/scylla-dtest/issues/4552) now fixed, can this issue be closed?

@bhalevy , if no need to document this non-self-pairing limitation, then yes.

**Comment by bhalevy** [comment] 2024-07-14 16:05
> > @yarongilor with [scylladb/scylla-dtest#4552](https://github.com/scylladb/scylla-dtest/issues/4552) now fixed, can this issue be closed?
> 
> @bhalevy , if no need to document this non-self-pairing limitation, then yes.

I'll defer that to @nyh.
In any case, this issue is about the test failing, not about need to change/add documentation.

**Comment by mykaul** [comment] 2024-07-16 10:44
I'm still seeing it - https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/627/testReport/materialized_views_test/TestMaterializedViews/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_view_tombstone/ - any idea why?

**Comment by yarongilor** [comment] 2024-07-16 13:49
> I'm still seeing it - https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/627/testReport/materialized_views_test/TestMaterializedViews/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_view_tombstone/ - any idea why?

it failed for `>       assert_one(session, "SELECT * FROM t_by_v WHERE v = 1", [1, 1, "b", 3.0], cl=ConsistencyLevel.ALL)`
with:
`E       AssertionError: Expected [[1, 1, 'b', 3.0]] from SELECT * FROM t_by_v WHERE v = 1, but got []`

So if non-self pairing causes an issue for CL ALL as well, then this assertion should be removed as well.

**Closed** 2024-07-16 14:08 UTC
Labels: area/materialized views, P1, symptom/ci stability, area/tablets
