### ISSUE TITLE
secondary_indexes_test.TestSecondaryIndexes.test_remove_node_during_index_build: Exception when draining [...] filesystem error: remove failed: Directory not empty

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#17774] opened 2024-03-13 08:05 UTC
Seen in https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/452/testReport/junit/secondary_indexes_test/TestSecondaryIndexes/FullDtest___full_split006___test_remove_node_during_index_build/

```
failed on teardown with "AssertionError: Unexpected errors found: [('node3', ['ERROR 2024-03-13 07:05:50,300 [shard 0:strm] hints_manager - Exception when draining 127.0.66.2: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/jenkins/workspace/scylla-master/gating-dtest-release-with-consistent-topology-changes/scylla/.dtest/dtest-jfoif0v4/test/node3/hints/0/127.0.66.2])'])]"
```

See node3.log below.

[node1.log](https://github.com/scylladb/scylladb/files/14584391/node1.log)
[node3.log](https://github.com/scylladb/scylladb/files/14584393/node3.log)
[node4.log](https://github.com/scylladb/scylladb/files/14584395/node4.log)
[node5.log](https://github.com/scylladb/scylladb/files/14584396/node5.log)

**Comment by dani-tweig** [comment] 2024-03-17 11:22
@dawmd , can you help figure out why after removing a node there is still hints.

**Comment by nyh** [comment] 2024-03-17 15:02
Please search the issue database for earlier duplicates of this issue. I created https://github.com/scylladb/scylladb/issues/17023 but there may be more, and we should leave just one.

**Comment by nyh** [comment] 2024-03-17 15:05
> Please search the issue database for earlier duplicates of this issue. I created #17023 but there may be more, and we should leave just one.

And that issue now says it's a duplicate of https://github.com/scylladb/scylladb/issues/17209.

Whoever analyzes or fixes this bug, please search for all the duplicates and close them all.

**Comment by mykaul** [comment] 2024-03-17 15:08
Hoping it's a dup - but clearly we need to fix the 1st one before attending others.

**Closed by mykaul** 2024-03-17 15:08 UTC
Labels: area/sec index, area/hinted handoff, symptom/ci stability
