### ISSUE TITLE
Could not create SSTable component due to filesystem_error (filesystem error: open failed: No such file or directory)

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylladb#21778] opened 2024-12-04 13:57 UTC
## Packages

Scylla version: `6.3.0~dev-20241129.65949ce60780` with build-id `d0921e78443678667ebaf5d8cdfda19428d03e6c`

Kernel Version: `6.8.0-1019-aws`

## Issue description

Not sure what sequence lead to such an errors, all nemeses passed successfully but scylla reported an error:
```
2024-11-30T20:20:56.001+00:00 longevity-mv-si-4d-master-db-node-d4a19da8-7      !ERR | scylla[5680]:  [shard  8:strm] sstable - Could not create SSTable component /var/lib/scylla/data/keyspace1/standard1-8f953e10af2811efa2abf63af30098af/me-3glo_14op_2q5y827bs2gmwxzh27-big-CRC.db. Found exception: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/keyspace1/standard1-8f953e10af2811efa2abf63af30098af/me-3glo_14op_2q5y827bs2gmwxzh27-big-CRC.db])
```

According to conversation  with @denesb it may be related to https://github.com/scylladb/scylladb/pull/21153

## Impact

Unclear, only one node reported it

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 5 nodes (i4i.8xlarge)

Scylla Nodes used in this run:
- longevity-mv-si-4d-master-db-node-d4a19da8-8 (34.250.206.139 | 10.4.8.149) (shards: 30)
- longevity-mv-si-4d-master-db-node-d4a19da8-7 (3.255.181.76 | 10.4.11.221) (shards: 30)
- longevity-mv-si-4d-master-db-node-d4a19da8-6 (3.249.94.103 | 10.4.10.110) (shards: 30)
- longevity-mv-si-4d-master-db-node-d4a19da8-5 (3.255.167.74 | 10.4.11.151) (shards: 30)
- longevity-mv-si-4d-master-db-node-d4a19da8-4 (34.245.49.212 | 10.4.8.118) (shards: 30)
- longevity-mv-si-4d-master-db-node-d4a19da8-3 (34.248.60.63 | 10.4.10.192) (shards: 30)
- longevity-mv-si-4d-master-db-node-d4a19da8-2 (63.33.49.128 | 10.4.9.236) (shards: 30)
- longevity-mv-si-4d-master-db-node-d4a19da8-1 (3.252.136.229 | 10.4.11.76) (shards: 30)

OS / Image: `ami-09d8c22a0006e46a8` (aws: undefined_region)

Test: `longevity-mv-si-4days-streaming-test`
Test id: `d4a19da8-c978-4a87-90f2-7d9950b31d90`
Test name: `scylla-master/tier1/longevity-mv-si-4days-streaming-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-mv-si-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/63b10fb84ca390399aeee6195e8051ebd5411ffe/test-cases/longevity/longevity-mv-si-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d4a19da8-c978-4a87-90f2-7d9950b31d90`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d4a19da8-c978-4a87-90f2-7d9950b31d90)
- Show all stored logs command: `$ hydra investigate show-logs d4a19da8-c978-4a87-90f2-7d9950b31d90`

## Logs:
- **longevity-mv-si-4d-master-db-node-d4a19da8-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_041012/longevity-mv-si-4d-master-db-node-d4a19da8-5-d4a19da8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_041012/longevity-mv-si-4d-master-db-node-d4a19da8-5-d4a19da8.tar.gz)
- **longevity-mv-si-4d-master-db-node-d4a19da8-3** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_041012/longevity-mv-si-4d-master-db-node-d4a19da8-3-d4a19da8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_041012/longevity-mv-si-4d-master-db-node-d4a19da8-3-d4a19da8.tar.gz)
- **longevity-mv-si-4d-master-db-node-d4a19da8-1** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_041012/longevity-mv-si-4d-master-db-node-d4a19da8-1-d4a19da8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_041012/longevity-mv-si-4d-master-db-node-d4a19da8-1-d4a19da8.tar.gz)
- **db-cluster-d4a19da8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_202346/db-cluster-d4a19da8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_202346/db-cluster-d4a19da8.tar.gz)
- **sct-runner-events-d4a19da8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_202346/sct-runner-events-d4a19da8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_202346/sct-runner-events-d4a19da8.tar.gz)
- **sct-d4a19da8.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_202346/sct-d4a19da8.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_202346/sct-d4a19da8.log.tar.gz)
- **loader-set-d4a19da8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_202346/loader-set-d4a19da8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_202346/loader-set-d4a19da8.tar.gz)
- **monitor-set-d4a19da8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_202346/monitor-set-d4a19da8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4a19da8-c978-4a87-90f2-7d9950b31d90/20241130_202346/monitor-set-d4a19da8.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-mv-si-4days-streaming-test/13/)
[Argus](https://argus.scylladb.com/test/f1ff65fd-8324-4264-8d28-8c7122fca836/runs?additionalRuns[]=d4a19da8-c978-4a87-90f2-7d9950b31d90)
</details>

**Comment by denesb** [comment] 2024-12-04 14:02
@ndragazis please have a look, seems to be a regression caused by https://github.com/scylladb/scylladb/pull/21153 (cc @paszkow).

**Comment by ndragazis** [comment] 2024-12-06 14:34
This error message must be coming from `sstable::read_checksum()` -> `sstable::new_sstable_component_file()`. We try to open the CRC file of some SSTable, but the file is not found. This happens during a reshape compaction:
> 2024-11-30T20:05:23.566+00:00 longevity-mv-si-4d-master-db-node-d4a19da8-7     !INFO | scylla[5680]:  [shard 11:strm] compaction - [Reshape keyspace1.standard1 6ecece70-af56-11ef-9367-8891aaece21f] Reshaping of 32 sstables interrupted due to: sstables::malformed_sstable_exception (/var/lib/scylla/data/keyspace1/standard1-8f953e10af2811efa2abf63af30098af/me-3glo_14oj_5oots28p4lxv6akgf3-big-CRC.db: file not found), at 0x626eb6e 0x626f190 0x626f498 0x25832ca 0x258161e 0x61439f6

However, in a previous stage this same SSTable has been scrubbed (as part of a Nemesis disruption):
> 2024-11-30T17:38:34.099+00:00 longevity-mv-si-4d-master-db-node-d4a19da8-7     !INFO | scylla[5680]:  [shard 11:strm] compaction - [Scrub keyspace1.standard1 ec0329a0-af41-11ef-9367-8891aaece21f] Scrubbing in abort mode [/var/lib/scylla/data/keyspace1/standard1-8f953e10af2811efa2abf63af30098af/me-3glo_14oj_5oots28p4lxv6akgf3-big-Data.db:level=0:origin=streaming]

The SSTable must have been deleted by the time the reshape compaction happens.

**Comment by denesb** [comment] 2024-12-06 14:38
I wonder if this is the same as https://github.com/scylladb/scylladb/issues/20030. The fix for that was merged 4 days ago.
The version this test was run on (65949ce60780) does not contain the fix for the above (https://github.com/scylladb/scylladb/commit/58baeac0ad01d7c09bc14329d0ea09f31f122cf9).

**Comment by lkshminarayanan** [comment] 2024-12-06 16:05
Scrub(`ec0329a0-af41-11ef-9367-8891aaece21f`) did complete much before the reshape but it did not remove the sstable :

> 2024-11-30T17:38:34.109+00:00 longevity-mv-si-4d-master-db-node-d4a19da8-7     !INFO | scylla[5680]:  [shard 11:strm] compaction - [Scrub keyspace1.standard1 ec0329a0-af41-11ef-9367-8891aaece21f] Finished scrubbing in abort mode 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-8f953e10af2811efa2abf63af30098af/me-3glo_1d09_5hm7428p4lxv6akgf3-big-Data.db:level=0]. 10kB to 9930 bytes (~96% of original) in 55ms = 187kB/s. ~128 total partitions merged to 19.

So this is same as #20030.

**Comment by raphaelsc** [comment] 2024-12-06 16:47
@timtimb0t please re-run the test on master to double check it's fixed.

**Comment by temichus** [comment] 2024-12-11 10:51
job was automatically [triggered](https://argus.scylladb.com/tests/scylla-cluster-tests/3864999a-8c3c-47f2-887a-63fefe2964a3) on 2024-12-07 with version 6.3.0~dev-20241206.7e2875d6489d(https://github.com/scylladb/scylladb/commit/7e2875d6489d2e6d4e22dce721f634bab79847bf ) that contains commit https://github.com/scylladb/scylladb/commit/58baeac0ad01d7c09bc14329d0ea09f31f122cf9. The issue was not reproduced.

**Closed by temichus** 2024-12-11 10:51 UTC
Labels: area/sstable, triage/master, P1, tests/longevity-tier1
