### ISSUE TITLE
[dtest] update_cluster_layout_tests.TestUpdateClusterLayout.test_simple_decommission_node_while_query_info failed on timeout

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#17346] opened 2024-02-14 20:25 UTC
Failed during https://jenkins.scylladb.com/job/scylla-master/job/next/7237/

Error 
```
cassandra.OperationTimedOut: errors={'127.0.68.3:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.68.3:9042
```
Stacktrace 
```
self = <update_cluster_layout_tests.TestUpdateClusterLayout object at 0x7f70b69d4250>
rf = 2

    @pytest.mark.required_features("!consistent-topology-changes")
    @pytest.mark.parametrize("rf", [1, 2])
    def test_simple_decommission_node_while_query_info(self, rf):
        """
        Test decommissioning node streams all data
        1. Create a cluster with a three nodes with rf, insert data
        2. Decommission node, while node is decommissioning query data
        3. Check that the cluster returns all
        """
        cluster = self.cluster
        consistency = {1: ConsistencyLevel.ONE, 2: ConsistencyLevel.TWO}[rf]
    
        # Disable hinted handoff and set batch commit log so this doesn't
        # interfer with the test (this must be after the populate)
        cluster.set_configuration_options(values=self.default_config_options(), batch_commitlog=True)
        cluster.populate(3).start()
        node1, node2, node3 = cluster.nodelist()
    
        session = self.patient_cql_connection(node1)
        create_ks(session, "ks", rf)
        create_cf(session, "cf", read_repair=0.0, columns={"c1": "text", "c2": "text"})
    
        num_keys = 2000
        insert_c1c2(session, keys=range(num_keys), consistency=consistency)
    
        def run(stop_run):
            logger.debug("Background SELECT loop starting")
            query = session.prepare("SELECT * FROM cf")
            query.consistency_level = consistency
            while not stop_run.is_set():
                result = list(session.execute(query))
                assert len(result) == num_keys
                time.sleep(0.01)
            logger.debug("Background SELECT loop done")
    
        executor = ThreadPoolExecutor(max_workers=1)
        stop_run = Event()
        t = executor.submit(run, stop_run)
    
        logger.debug("Decommissioning node2")
        node2.decommission()
    
        stop_run.set()
>       t.result()

update_cluster_layout_tests.py:1213: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.11/concurrent/futures/_base.py:456: in result
    return self.__get_result()
/usr/lib64/python3.11/concurrent/futures/_base.py:401: in __get_result
    raise self._exception
/usr/lib64/python3.11/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
update_cluster_layout_tests.py:1200: in run
    result = list(session.execute(query))
cassandra/cluster.py:2726: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'127.0.68.3:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.68.3:9042

cassandra/cluster.py:5085: OperationTimedOut
```

**Comment by nyh** [comment] 2024-02-20 09:10
Seen again in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6800/ - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6800/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_decommission_node_while_query_info_2_/

**Comment by nyh** [comment] 2024-02-20 22:01
Seen again in next promotion run, https://jenkins.scylladb.com/job/scylla-master/job/next/7267/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Build___x86___dtest___test_simple_decommission_node_while_query_info_2_/

**Comment by mykaul** [comment] 2024-02-22 11:47
Perhaps related to https://github.com/scylladb/python-driver/issues/275 ? Unsure.
The failure isn't too informative:
```
0:42:53,445 793     cassandra.protocol             WARNING  libevreactor.py     :371  | test_simple_decommission_node_while_query_info[2]: Server warning: Using Replication Factor replication_factor=2 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
20:42:56,536 793     update_cluster_layout_tests    DEBUG    update_cluster_layout_tests.py:1212 | test_simple_decommission_node_while_query_info[2]: Background SELECT loop starting
20:42:56,536 793     update_cluster_layout_tests    DEBUG    update_cluster_layout_tests.py:1225 | test_simple_decommission_node_while_query_info[2]: Decommissioning node2
20:42:56,539 793     ccm                            DEBUG    cluster.py          :762  | test_simple_decommission_node_while_query_info[2]: node2: nodetool cmd=-Dcom.scylladb.apiPort=10000 decommission wait=True timeout=None
20:43:06,924 793     cassandra.cluster              INFO     thread.py           :58   | test_simple_decommission_node_while_query_info[2]: Cassandra host 127.0.51.2:9042 removed
20:43:37,201 793     errors                         ERROR    conftest.py         :202  | test_simple_decommission_node_while_query_info[2]: test failed: 
self = <update_cluster_layout_tests.TestUpdateClusterLayout object at 0x7fbbd81b1750>
rf = 2

    @pytest.mark.required_features("!consistent-topology-changes")
    @pytest.mark.parametrize("rf", [1, 2])
    def test_simple_decommission_node_while_query_info(self, rf):
        """
        Test decommissioning node streams all data
        1. Create a cluster with a three nodes with rf, insert data
        2. Decommission node, while node is decommissioning query data
        3. Check that the cluster returns all
        """
        cluster = self.cluster
        consistency = {1: ConsistencyLevel.ONE, 2: ConsistencyLevel.TWO}[rf]
    
        # Disable hinted handoff and set batch commit log so this doesn't
        # interfer with the test (this must be after the populate)
        cluster.set_configuration_options(values=self.default_config_options(), batch_commitlog=True)
        cluster.populate(3).start()
        node1, node2, node3 = cluster.nodelist()
    
        session = self.patient_cql_connection(node1)
        create_ks(session, "ks", rf)
        create_cf(session, "cf", read_repair=0.0, columns={"c1": "text", "c2": "text"})
    
        num_keys = 2000
        insert_c1c2(session, keys=range(num_keys), consistency=consistency)
    
        def run(stop_run):
            logger.debug("Background SELECT loop starting")
            query = session.prepare("SELECT * FROM cf")
            query.consistency_level = consistency
            while not stop_run.is_set():
                result = list(session.execute(query))
                assert len(result) == num_keys
                time.sleep(0.01)
            logger.debug("Background SELECT loop done")
    
        executor = ThreadPoolExecutor(max_workers=1)
        stop_run = Event()
        t = executor.submit(run, stop_run)
    
        logger.debug("Decommissioning node2")
        node2.decommission()
    
        stop_run.set()
>       t.result()

update_cluster_layout_tests.py:1229: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.11/concurrent/futures/_base.py:456: in result
    return self.__get_result()
/usr/lib64/python3.11/concurrent/futures/_base.py:401: in __get_result
    raise self._exception
/usr/lib64/python3.11/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
update_cluster_layout_tests.py:1216: in run
    result = list(session.execute(query))
cassandra/cluster.py:2726: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'127.0.51.1:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.51.1:9042
```
node-1 was busy with reshaping, but that's about it:
```
INFO  2024-02-20 20:43:16,359 [shard 0:strm] compaction - [Reshape ks.cf ac46c1f0-d030-11ee-a2c1-f0ea4b5528e9] Reshaped 142 sstables to [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-flm3mzl9/test/node1/data/ks/cf-9fa6cb20d03011eeae6c05fb39ed2541/me-3gds_1lk4_1fva82h3psliqsyfvt-big-Data.db:level=0]. 757kB to 134kB (~17% of original) in 18ms = 42MB/s. ~18176 total partitions merged to 326.
INFO  2024-02-20 20:43:16,360 [shard 0:strm] compaction_manager - Done with off-strategy compaction for ks.cf compaction_group=0/1
INFO  2024-02-20 20:43:16,362 [shard 1:strm] compaction - [Reshape ks.cf ac46e900-d030-11ee-9873-f0eb4b5528e9] Reshaped 151 sstables to [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-flm3mzl9/test/node1/data/ks/cf-9fa6cb20d03011eeae6c05fb39ed2541/me-3gds_1lk4_1fva82bgmjbxpdtpt5-big-Data.db:level=0]. 803kB to 135kB (~16% of original) in 16ms = 50MB/s. ~19328 total partitions merged to 323.
INFO  2024-02-20 20:43:16,362 [shard 1:strm] compaction_manager - Done with off-strategy compaction for k
```

**Comment by Annamikhlin** [comment] 2024-02-26 07:30
seen again on https://jenkins.scylladb.com/job/scylla-master/job/next/7287/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Build___x86___dtest___test_simple_decommission_node_while_query_info_2_/

**Comment by avikivity** [comment] 2024-02-26 09:56
Raised to P0 as it's occuring too much.

**Comment by mykaul** [comment] 2024-02-26 10:38
@avikivity - it's possibly a dup of https://github.com/scylladb/scylladb/issues/17124 - which has some more progress than this one...

**Comment by avikivity** [comment] 2024-02-26 16:20
Seen again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/7291/console

**Comment by avikivity** [comment] 2024-02-26 16:22
Closing as a duplicate of #17124.

**Closed by avikivity** 2024-02-26 16:22 UTC
Labels: triage/master, P0, symptom/ci stability
