### ISSUE TITLE
Failure to start/compile in Nix development environment

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylladb#12259] opened 2022-12-10 22:20 UTC
There are currently 4 problems I encountered while trying out the Nix development environment. Those look like recent regressions, as I was successfully able to try the Nix development environment just a few weeks ago.

#### Problem 1: `'libdeflate.h' file not found`
```
./sstables/checksum_utils.hh:12:10: fatal error: 'libdeflate.h' file not found
#include <libdeflate.h>
         ^~~~~~~~~~~~~~
1 error generated.
```
This is a simple problem, `libdeflate` is missing from `buildInputs` in `default.nix`. I would send a patch myself, but the other problems prevent me from veryfing if `libdeflate` would actually work after a successful build.

Patch:
```diff
diff --git a/default.nix b/default.nix
index f54331f29..bee20602d 100644
--- a/default.nix
+++ b/default.nix
@@ -130,6 +130,7 @@ in derive ({
     hwloc
     icu
     jsoncpp
+    libdeflate
     libidn2
     libp11
     libsystemtap
```

#### Problem 2: `fatal error: 'crypt.h' file not found`
```
auth/passwords.cc:15:10: fatal error: 'crypt.h' file not found
#include <crypt.h>
         ^~~~~~~~~
1 error generated.
```
Similar simple problem, solved by adding `libxcrypt` (although this isn't the original "libcrypt", but it looks like "libcrypt" was removed from nixpkgs in https://github.com/NixOS/nixpkgs/pull/181764). Similar disclaimer about not sending a patch due to inability to verify the correctness of the change.

```diff
diff --git a/default.nix b/default.nix
index f54331f29..9ab9a1890 100644
--- a/default.nix
+++ b/default.nix
@@ -130,6 +130,8 @@ in derive ({
     hwloc
     icu
     jsoncpp
+    libxcrypt
+    libdeflate
     libidn2
     libp11
     libsystemtap
```

#### Problem 3: `no type named 'source_location' in namespace 'std'`
```
In file included from replica/distributed_loader.cc:13:
In file included from replica/distributed_loader.hh:22:
In file included from ./db/system_keyspace.hh:28:
In file included from ./service/raft/group0_fwd.hh:12:
./raft/raft.hh:298:30: error: no type named 'source_location' in namespace 'std'
    state_machine_error(std::source_location l = std::source_location::current())
                        ~~~~~^
./raft/raft.hh:298:55: error: no member named 'source_location' in namespace 'std'
    state_machine_error(std::source_location l = std::source_location::current())
                                                 ~~~~~^
2 errors generated.
```
For non-experimental `std::source_location` to compile correctly, you need Clang 15 and libstdc++12 (as far as I know). Unfortunately, Clang 15 is still not available in nixpkgs: https://github.com/NixOS/nixpkgs/pull/194634

#### Problem 4: Flake-based environment hash mismatch
All the previous problems were encountered in Nix developer environment started with `nix-shell .` (non-flake-based). The Flake-based environment doesn't start due to a hash mismatch:

```
error: hash mismatch in fixed-output derivation '/nix/store/cfvz4q94kmj01xdyljgkns0frda969vd-1c52ca4b27e93e1684c68eeaee44ca3e36648410.patch.drv':
         specified: sha256-3s3KvN70dHMdr7Sx1dtzbZ8S+MynPTN7yCocoGlea2Y=
            got:    sha256-MwhWu4mK0UoZM887fXeaPyNbRmP3Q4Ddq3f8224TELg=
error: 1 dependencies of derivation '/nix/store/31cmf4ijkxc41vzqwdy4dlzw9xmjyqcb-gdb-12.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pd0rndri9hjf9n9v4kpmvpcw6csfqwbz-scylla-env.drv' failed to build
```

This hash is of `https://github.com/cmm/gnu-binutils/commit/1c52ca4b27e93e1684c68eeaee44ca3e36648410.patch`. Since the commit still lives in `cmm/gnu-binutils` under the same commit hash, I assume that some GitHub formatting of `.patch` changed slightly. @cmm do you happen to have the original file cached on your system? - of course I assume the contents of the patch didn't change, but I am curious what changed around the formatting.

**Comment by nyh** [comment] 2022-12-11 10:35
As you noted, the missing libraries can and should easily be fixed for Nix.
The `source_location` thing bothers me much more. There is no reason why we had to have this very recent regression where Scylla no longer compiles with Clang 14 just because we were too purists to write code that works for both clang 14 and clang 15.  It's not like we need to spend hours to write  that code - it's just this one specific place that needs to be fixed.

Yes, I know, we have dbuild, yada, yada, yada, who cares about compatibility with more than one specific version of the build environment. Well, I do care. It's frustrating that because of puritanism, people that previously didn't need to use dbuild every time, now do.

**Comment by cmm** [comment] 2022-12-11 11:22
> do you happen to have the original file cached on your system? - of course I assume the contents of the patch didn't change, but I am curious what changed around the formatting.

Weirdly enough the `.drv` file is still cached for me but its the output `.patch` isn't, so I have nothing to diff against.

But: I haven't been able to see the problem with the original `flake.lock`, but it reproduced right after I did `nix flake update`.  If that's what you in fact did too, then the different hash could well be due to some recent change in `nixpkgs.fetchurl` itself and not due to anything nefarious on Github's part.

While at it, I don't remember why I haven't submitted the updated gdb patch to @denesb at the time (porting it from gdb 11 to 12 was just a matter of resolving a couple of conflicts with textually-adjacent but otherwise unrelated upstream changes) -- must just have forgotten, sorry about that!  I'm fine with keeping my stupid fork around as long needed though.

> There is no reason why we had to have this very recent regression where Scylla no longer compiles with Clang 14

Note that the Nix devenv still explicitly uses Clang 12, so I guess building with that version is now broken too?

**Comment by avikivity** [comment] 2022-12-11 11:27
> As you noted, the missing libraries can and should easily be fixed for Nix. The `source_location` thing bothers me much more. There is no reason why we had to have this very recent regression where Scylla no longer compiles with Clang 14 just because we were too purists to write code that works for both clang 14 and clang 15. It's not like we need to spend hours to write that code - it's just this one specific place that needs to be fixed.
> 
> Yes, I know, we have dbuild, yada, yada, yada, who cares about compatibility with more than one specific version of the build environment. Well, I do care. It's frustrating that because of puritanism, people that previously didn't need to use dbuild every time, now do.

We're not explicitly against building with an older version. If it's possible to support it, why not.

**Comment by nyh** [comment] 2022-12-11 13:08
> We're not explicitly against building with an older version. If it's possible to support it, why not.

It's not like we "accidentally" broke support for the old version - you did the change intentionally, in 6a5d9ff2610ecc9e5e2094fcf438acaf472ba386. I'll see what I can do that isn't too ugly to make the code work on both clang versions.

**Comment by avelanarius** [comment] 2022-12-11 13:40
> > do you happen to have the original file cached on your system? - of course I assume the contents of the patch didn't change, but I am curious what changed around the formatting.
> 
> Weirdly enough the `.drv` file is still cached for me but its output `.patch` isn't, so I have nothing to diff against.
> 
> But: I haven't been able to see the problem with the original `flake.lock`, but it reproduced right after I did `nix flake update`. If that's what you in fact did too, then the different hash could well be due to some recent change in `nixpkgs.fetchurl` itself and not due to anything nefarious on Github's part.

I also tried it on a fresh repo clone (and actually on another fresh OS with newly installed Nix) - got the same problem. If you manually download `.patch` file, sha256 it, convert sha256 to base64 you actually get the same "unexpected" hash Nix reports.

**Closed** 2022-12-20 10:46 UTC
Labels: low

**Comment by avikivity** [comment] 2022-12-28 12:56
build only, no backport.
