### ISSUE TITLE
TestReversedQueriesSelectorsDuringUpgrade.test_queries_during_upgrade fail to start node after upgrade

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylladb#16414] opened 2023-12-14 09:45 UTC
Full log https://jenkins.scylladb.com/job/scylla-enterprise/job/gating-dtest-release/1109/artifact/logs-full.release.005/dtest-gw1.log/*view*/

`ccmlib.node.NodeUpgradeError: Node node1 failed to start after upgrade. Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
`

```
    def test_queries_during_upgrade(self, dtest_config):
        """
        Test that reverse queries work on a mixed cluster
        1. Prepare data for selects
        2. For each version in the upgrade chain:
            2.1. For each node in the cluster
                2.1.1. Upgrade the node
                2.1.2. Check that selects work
        """
        self.clone_upgrade_path(dtest_config)
    
        logger.debug('Creating a 2-node cluster')
        self.init_cluster(nodes=2)
        session = self.patient_cql_connection(self.cluster.nodelist()[0], row_factory=dict_factory)
    
        logger.debug('Set up schema')
        BaseReversedQuerySelector.prepare_schema(self, session, rf=2)
    
        logger.debug('Populate the table')
        self.populate(session)
    
        logger.debug('Testing selects')
        self.run_selects(session)
    
        for version in self.current_upgrade_path:
            for node in self.cluster.nodelist():
                logger.debug(f"Upgrading node {node.name} from version {node.node_scylla_version} to {version}")
>               node.upgrade(upgrade_to_version=version)
.
.
.
.
    def upgrade(self, upgrade_version: str, recover_system_tables: bool = False):
        """
        :param upgrade_version: relocatables folder. Example: unstable/master:2020-11-18T08:57:53Z
        :param recover_system_tables: restore system tables during rollback (https://docs.scylladb.com/upgrade/
                                     upgrade-enterprise/upgrade-guide-from-2018.1-to-2019.1/
                                     upgrade-guide-from-2018.1-to-2019.1-rpm/#restore-system-tables)
        """
        # Part of the rollback procedure is to restore system tables.
        # For this goal a snapshot will be taken before downgrade and restore the system tables after downgrade
        self.scylla_version_for_upgrade = upgrade_version
        cdir = self._setup_relocatable_packages()
    
        self.node.nodetool("snapshot")
    
        self.node.stop(wait_other_notice=True)
        if self.node.status != Status.DOWN:
            raise NodeUpgradeError(f"Node {self.node.name} failed to stop before upgrade")
    
        self._import_executables(cdir)
        self.node.clean_runtime_file()
    
        if recover_system_tables:
            self._recover_system_tables()
    
        try:
            self.node.start(wait_other_notice=True, wait_for_binary_proto=True)
        except Exception as exc:
>           raise NodeUpgradeError(f"Node {self.node.name} failed to start after upgrade. Error: {exc}")
E           ccmlib.node.NodeUpgradeError: Node node1 failed to start after upgrade. Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:1792: NodeUpgradeError
```

**Comment by benipeled** [comment] 2023-12-14 09:47
I'm not sure if it's a core/ccm issue

**Comment by mykaul** [comment] 2023-12-14 09:56
Poor thing crashed (node 2):
```
ERROR 2023-12-14 08:47:12,601 [shard 0] database - Cannot apply atomically across commitlog domains: system.scylla_local, system_schema.keyspaces, at: 0x53e7cde 0x53e8290 0x53e8578 0x502b9a7 0x17fdebb 0x17fc75d 0x3254629 0x12113fa 0x505a384 0x505b607 0x505a949 0x5001375 0x50004e8 0x1158034 0x1159b40 0x115676a /jenkins/workspace/scylla-enterprise/gating-dtest-release/scylla/.ccm/scylla-repository/release/5.2.11/libreloc/libc.so.6+0x2750f /jenkins/workspace/scylla-enterprise/gating-dtest-release/scylla/.ccm/scylla-repository/release/5.2.11/libreloc/libc.so.6+0x275c8 0x1154924
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::do_with_state<std::tuple<std::vector<canonical_mutation, std::allocator<canonical_mutation> > >, seastar::future<void> >
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, service::migration_manager::do_merge_schema_from(netw::msg_addr)::$_11, seastar::future<void>::then_impl_nrvo<service::migration_manager::do_merge_schema_from(netw::msg_addr)::$_11, seastar::future<void> >(service::migration_manager::do_merge_schema_from(netw::msg_addr)::$_11&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, service::migration_manager::do_merge_schema_from(netw::msg_addr)::$_11&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, serialized_action::trigger(bool)::{lambda(auto:1&&)#1}, seastar::future<void>::then_wrapped_nrvo<void, serialized_action::trigger(bool)::{lambda(auto:1&&)#1}>(serialized_action::trigger(bool)::{lambda(auto:1&&)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, serialized_action::trigger(bool)::{lambda(auto:1&&)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Aborting on shard 0.
Backtrace:
  0x5049b08
  0x507bf42
  /jenkins/workspace/scylla-enterprise/gating-dtest-release/scylla/.ccm/scylla-repository/release/5.2.11/libreloc/libc.so.6+0x3cb1f
  /jenkins/workspace/scylla-enterprise/gating-dtest-release/scylla/.ccm/scylla-repository/release/5.2.11/libreloc/libc.so.6+0x8ce5b
  /jenkins/workspace/scylla-enterprise/gating-dtest-release/scylla/.ccm/scylla-repository/release/5.2.11/libreloc/libc.so.6+0x3ca75
  /jenkins/workspace/scylla-enterprise/gating-dtest-release/scylla/.ccm/scylla-repository/release/5.2.11/libreloc/libc.so.6+0x267fb
  0x502ba43
  0x17fdebb
  0x17fc75d
  0x3254629
  0x12113fa
  0x505a384
  0x505b607
  0x505a949
  0x5001375
  0x50004e8
  0x1158034
  0x1159b40
  0x115676a
  /jenkins/workspace/scylla-enterprise/gating-dtest-release/scylla/.ccm/scylla-repository/release/5.2.11/libreloc/libc.so.6+0x2750f
  /jenkins/workspace/scylla-enterprise/gating-dtest-release/scylla/.ccm/scylla-repository/release/5.2.11/libreloc/libc.so.6+0x275c8
  0x1154924
```

**Comment by mykaul** [comment] 2023-12-14 10:06
@elcallio - can you look at the coredump @ https://jenkins.scylladb.com/job/scylla-enterprise/job/gating-dtest-release/1109/artifact/logs-full.release.005/1702543636144_reversed_queries_test.py%3A%3ATestReversedQueriesSelectorsDuringUpgrade%3A%3Atest_queries_during_upgrade/ if it's related to commitlog?

**Comment by mykaul** [comment] 2023-12-14 10:10
@kbr-scylla - does the above sounds familiar? Some schema related bug?

**Comment by kbr-scylla** [comment] 2023-12-14 12:34
Hmm

> Cannot apply atomically across commitlog domains: system.scylla_local, system_schema.keyspaces

https://github.com/scylladb/scylladb/pull/16242 added a system.scylla_local mutation to schema changes.
But this is protected by a cluster feature so it should not happen until after the upgrade finishes fully.

The upgrade also migrates scylla_local from regular commitlog to schema commitlog. Maybe there's some problem with this migration.

I'll look into this.

**Comment by kbr-scylla** [comment] 2023-12-14 12:52
Ok I think I know what this is.

Creating the scylla_local mutation during schema changes is protected by a cluster feature.

However, during schema pull, we also attach scylla_local mutation, **even though it is empty**:
```
    _messaging.register_migration_request(std::bind_front(
            [] (migration_manager& self, const rpc::client_info& cinfo, rpc::optional<netw::schema_pull_options> options)
                -> future<rpc::tuple<std::vector<frozen_mutation>, std::vector<canonical_mutation>>> {
...
        cm.emplace_back(co_await self._sys_ks.local().get_group0_schema_version());
```
this attached mutation will be empty during upgrade. Still, it will trigger the above error (we could argue that the check is too strict and could simply ignore empty mutations, but I digress).

The fix is simple, I'll prepare it.

Interesting that we only catched it in enterprise upgrade test.
It is thanks to the upgraded enterprise node performing a schema change immediately when the node starts in new version:
```
INFO  2023-12-14 08:47:12,098 [shard 0:main] schema_tables - Creating system_replicated_keys.encrypted_keys id=f705e6dd-8cc5-378b-a7e9-aec38e033747 version=01b614dd-06ab-3ba3-add2-80e449ff446b
```
this schema change is then pulled by the non-upgraded node, and because of the attached system.scylla_local mutation, the pull triggers the assertion.

**Comment by kbr-scylla** [comment] 2023-12-14 13:23
Another ingredient required to reproduce is that the first upgraded node does the schema change early in startup procedure, before it notices that the second node is up, which causes the schema mutation not to be pushed to the second node immediately; but the second node only pulls it after a second, triggering the code path.

**Comment by kbr-scylla** [comment] 2023-12-14 14:01
Sent fix: https://github.com/scylladb/scylladb/pull/16416

**Comment by kbr-scylla** [comment] 2023-12-14 14:51
@benipeled I'm trying run this test on next-enterprise with my fix applied using the byo_enterprise_build_tests_dtest job:
https://jenkins.scylladb.com/job/scylla-enterprise/job/byo/job/byo_enterprise_build_tests_dtest/74/console
It builds Scylla and then runs scylla-enterprise/releng-testing/dtest-byo
https://jenkins.scylladb.com/job/scylla-enterprise/job/releng-testing/job/byo/job/dtest-byo/22/

Looks like this dtest-byo job is broken / outdated?
```
[2023-12-14T14:23:19.606Z] You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
[2023-12-14T14:23:21.051Z] Usage: python3 -m nose [options]
[2023-12-14T14:23:21.051Z] 
[2023-12-14T14:23:21.051Z] python3 -m nose: error: no such option: --scylla-version
[2023-12-14T14:23:21.051Z] Docker exitcode: 2
```

**Comment by kbr-scylla** [comment] 2023-12-14 14:53
cc @yaronkaikov ^

**Comment by kbr-scylla** [comment] 2023-12-14 14:59
Tried to run using scylla-master/releng-testing/dtest-byo (passing build artifact url), no luck, same error:
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/byo/job/dtest-byo/83/console

**Comment by benipeled** [comment] 2023-12-14 17:38
> @benipeled I'm trying run this test on next-enterprise with my fix applied using the byo_enterprise_build_tests_dtest job: https://jenkins.scylladb.com/job/scylla-enterprise/job/byo/job/byo_enterprise_build_tests_dtest/74/console It builds Scylla and then runs scylla-enterprise/releng-testing/dtest-byo https://jenkins.scylladb.com/job/scylla-enterprise/job/releng-testing/job/byo/job/dtest-byo/22/
> 
> Looks like this dtest-byo job is broken / outdated?
> 
> ```
> [2023-12-14T14:23:19.606Z] You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
> [2023-12-14T14:23:21.051Z] Usage: python3 -m nose [options]
> [2023-12-14T14:23:21.051Z] 
> [2023-12-14T14:23:21.051Z] python3 -m nose: error: no such option: --scylla-version
> [2023-12-14T14:23:21.051Z] Docker exitcode: 2
> ```

Seems like a bug `byo` triggering the `releng-testing > dtest-byo` instead of the regular `dtest-byo` which points to an old version- I'll check it,
Meanwhile, I manually trigger https://jenkins.scylladb.com/job/scylla-enterprise/job/byo/job/dtest-byo/68

PS> you can also use https://jenkins.scylladb.com/job/scylla-enterprise/job/scylla-ci for such a change (but it lacks the ability of specifying a test to run)

**Comment by benipeled** [comment] 2023-12-14 17:43
> Meanwhile, I manually trigger https://jenkins.scylladb.com/job/scylla-enterprise/job/byo/job/dtest-byo/68

brrrr, same ` python3 -m nose: error: no such option: --scylla-version` I'm not sure where it comes from, it shouldn't use nose - @fruch?

**Comment by benipeled** [comment] 2023-12-14 17:51
Found it - wrong dtest & ccm repo path
Retrigger https://jenkins.scylladb.com/job/scylla-enterprise/job/byo/job/dtest-byo/69/console

**Comment by benipeled** [comment] 2023-12-14 18:11
> Retrigger https://jenkins.scylladb.com/job/scylla-enterprise/job/byo/job/dtest-byo/69/console

Completed successfully 
```
19:58:02  reversed_queries_test.py::TestReversedQueriesSelectorsDuringUpgrade::test_queries_during_upgrade 
19:58:02  [gw0] PASSED reversed_queries_test.py::TestReversedQueriesSelectorsDuringUpgrade::test_queries_during_upgrade 
19:58:02  
19:58:02  =============================== warnings summary ===============================
19:58:02  repair_additional_test.py:87
19:58:02  repair_additional_test.py:87
19:58:02  repair_additional_test.py:87
19:58:02  repair_additional_test.py:87
19:58:02  repair_additional_test.py:87
19:58:02    /jenkins/workspace/scylla-enterprise/byo/dtest-byo/scylla-dtest/repair_additional_test.py:87: DeprecationWarning: invalid escape sequence '\d'
19:58:02      pattern = f'{key}=(\d+\.\d+|\d+)'
19:58:02  
19:58:02  -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
19:58:02  - generated xml file: /jenkins/workspace/scylla-enterprise/byo/dtest-byo/scylla-dtest.full.release.000.xml -
19:58:02  ======================== 1 passed, 5 warnings in 49.89s ========================
19:58:02  Docker exitcode: 0
19:58:02  pytest ended with status |0|
```

**Comment by kbr-scylla** [comment] 2023-12-15 08:40
Thank you @benipeled !

**Comment by kbr-scylla** [comment] 2023-12-15 09:10
So we shouldn't be using scylla-ccm-enterprise?

**Comment by kbr-scylla** [comment] 2023-12-15 13:32
6a4106edf348276296245e3dbef8440dba21ea20 was merged to `master`, I cherry-picked it into `next-enterprise`: https://github.com/scylladb/scylla-enterprise/commit/c7cdb16538f2bb7d154b7780c32a636b4a3e3406

**Comment by kbr-scylla** [comment] 2023-12-15 18:18
The fix ended up in enterprise. We can close the issue.

**Closed by kbr-scylla** 2023-12-15 18:18 UTC
Labels: Master/Triage

**Comment by benipeled** [comment] 2023-12-17 09:32
> So we shouldn't be using scylla-ccm-enterprise?

No. since scylla 2022.*
Same for dtest
