### ISSUE TITLE
maintenance socket: node hangs when multiple nodes try to bind to the same socket

### ISSUE THREAD

**Issue by margdoc** [scylladb/scylladb#16985] opened 2024-01-25 17:01 UTC
When multiple nodes try to bind to the same socket they could hang on the `::bind` system call.

It can be easily reproduced by deleting these lines:
https://github.com/scylladb/scylladb/blob/c67698ea0659cf7cc23ba39fca969ce482e4ed51/transport/controller.cc#L184-L188
and by running and restarting a single node.
After restart it tries to bind to the Unix domain socket that exists in the filesystem (created by the first run of this node) and hangs.

It should be investigated why `::bind` hangs instead of returning an error that this socket is already used.

cc @kbr-scylla

**Comment by muthu90tech** [comment] 2024-06-22 23:08
Hi I am new to the project, would like to pick this task up, I there a project tracker where issues get assigned to contributors ? Thanks

**Comment by mykaul** [comment] 2024-06-23 06:48
> Hi I am new to the project, would like to pick this task up, I there a project tracker where issues get assigned to contributors ? Thanks

Welcome! Just go ahead and send a patch.

**Comment by muthu90tech** [comment] 2024-11-11 21:48
Is this issue still relevant ? I tried to repro this by starting two scylladb process on the same `maintenance_socket`.
One succeeded and other failed with `ERROR 2024-11-11 13:46:09,425 [shard  0:main] init - Startup failed: std::system_error (error system:98, posix_listen failed for address 127.99.44.1:9180: Address already in use)`

**Comment by kbr-scylla** [comment] 2024-11-15 17:01
So you configured the `maintenance_socket` parameter to the same path?

It seems conflict happened when trying to bind a TCP socket which triggered an exception -- IP address clash. So try different nodes with different IP addresses, but using the same `maintenance_socket` path

**Comment by muthu90tech** [comment] 2024-11-22 05:24
Ok @kbr-scylla , I tried with different ip addresses, but using the same maintenance_socket path and the second server which tried to use the same socket path is failing with error:

```
ERROR 2024-11-21 21:18:28,475 [shard  0:main] init - Startup failed: std::runtime_error (CQLServer error while listening on /tmp/scylladb-1-test.py-zpry23rv/cql.m -> std::system_error (error system:98, posix_listen failed for address /tmp/scylladb-1-test.py-zpry23rv/cql.m: Address already in use)
```

**Comment by kbr-scylla** [comment] 2024-11-25 12:26
That's good news. Looks like the issue was accidentally fixed at some point.
So closing since it doesn't reproduce.
Thanks @muthu90tech !

**Closed by kbr-scylla** 2024-11-25 12:26 UTC
Labels: good first issue, P3
