### ISSUE TITLE
Support casting between types in CQL

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylladb#12920] opened 2023-02-17 20:34 UTC
Currently CQL has some basic support for type casting, but it's very minimal.
AFAIU "casting" is mostly used to specify the type of bind variables.

Trying to do anything more complicated doesn't work.
For example, trying to compare an `int` and `bigint` value doesn't work.

```cql
cqlsh:ks> CREATE TABLE tab (int_column int primary key);
cqlsh:ks> SELECT * FROM tab WHERE int_column = token(123);
InvalidRequest: "Type error: cannot assign result of function system.token (type bigint) to int_column (type int)"
```

Trying to perform a cast doesn't work.
```cql
cqlsh:ks> SELECT * FROM tab WHERE (bigint)int_column = token(123);
SyntaxException: line 1:32 no viable alternative at input 'int_column' (... FROM tab WHERE (bigint)[int_column]...)
cqlsh:ks> SELECT * FROM tab WHERE CAST(int_column as bigint) = token(123);
SyntaxException: line 1:28 no viable alternative at input '(' (SELECT * FROM tab WHERE [CAST](...)
```

I think it would be useful to support such type casts, at least as long as they are lossless. Casting bigint to int could lose data/cause an error, but casting an int to bigint is safe.

It might be hard to support type casts in query planning when they cast a primary key column, but for now we can just filter such cases.

**Comment by nyh** [comment] 2024-06-17 09:13
Closing this issue as a duplicate of the newer https://github.com/scylladb/scylladb/issues/14522 - that issue explains how that this feature was added in Cassandra 4.1. Not only is the CAST syntax supported in restrictions (as requested in this issue), it is also allowed in other places like INSERT.

**Closed** 2024-06-17 09:14 UTC
Labels: enhancement, area/cql
