### ISSUE TITLE
Segfault Issues while Upgrading from 5.0.5 to 5.0.9 or 5.1.3

### ISSUE THREAD

**Issue by tynli** [scylladb/scylladb#12703] opened 2023-02-01 23:03 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.0.9 and 5.1.3
Cluster size: 3x4
OS: Ubuntu 20.04

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets=1 cores=4 hyperthreading=yes memory=128G
Disks: (SSD/HDD, count): NVMe, 4, RAID-0

After upgrading from 5.0.5 to 5.0.9 I had an issue with the scylla server segfaulting, and then restarting. The symptoms seem similar to https://github.com/scylladb/scylladb/issues/9896 but with a different set of versions. I have included some coredump and log data below.

For a while I thought I had worked around the issue by restarting the service to force a compaction before the upgrade, but this just delayed the segfault. After I had upgraded my entire cluster, I had segfaults on 1 data center simultaneously. Reverting to 5.0.5 across the entire cluster has stopped the segfaults.

The segfault symptoms seemed the same after my upgrade from 5.0.5 to 5.0.9 or the upgrade I then attempted from 5.0.9 to 5.1.3.

Log data:
```
Jan 30 15:43:37 my_hostname scylla:  [shard 0] storage_service - Node X.Z.X.B state jump to normal
Jan 30 15:43:38 my_hostname scylla:  [shard 4] large_data - Writing large partition keyspace_name/table_name: 14563637-caf9-11ec-af17-3cecef5d1d06:aDDz_ura8GImKJrCA_yFvA:71869b30-a3
c8-11ec-9675-d0817adae455:-1 (11567479 bytes) to /var/lib/scylla/data/keyspace_name/table_name-d65ae390afa811eca37057bbddeca292/md-3242036-big-Data.db
Jan 30 15:43:38 my_hostname scylla:  [shard 0] storage_service - Node X.W.X.B state jump to normal
Jan 30 15:43:38 my_hostname kernel: [  495.413565] reactor-6[2407]: segfault at 8a ip 000000000447b5b4 sp 00007ff013bd3480 error 4 in scylla[fa4000+3e23000]
Jan 30 15:43:38 my_hostname kernel: [  495.413576] Code: 00 48 83 c4 08 5b 41 5e c3 0f 57 c0 0f 11 03 4d 85 c0 75 e7 0f 57 c0 41 0f 11 06 eb de 48 89 c7 e8 c1 8c b2 fc cc 53 48 89 fb <80>
7f 59 00 74 11 64 48 8b 3c 25 90 54 fe ff 48 89 de e8 d5 f9 fb
Jan 30 15:43:38 my_hostname scylla[2401]: Segmentation fault on shard 6.
Jan 30 15:43:38 my_hostname scylla[2401]: Backtrace:
Jan 30 15:43:38 my_hostname scylla[2401]:   0x4445718
Jan 30 15:43:38 my_hostname scylla[2401]:   0x44761f6
Jan 30 15:43:38 my_hostname scylla[2401]:   0x4ac5fd1
Jan 30 15:43:38 my_hostname scylla[2401]:   0x7ff018c0da1f
Jan 30 15:43:38 my_hostname scylla[2401]:   0x447b5b3
Jan 30 15:43:38 my_hostname scylla[2401]:   0x24c422b
Jan 30 15:43:38 my_hostname scylla[2401]:   0x2b715cb
Jan 30 15:43:38 my_hostname scylla[2401]:   0x4456674
Jan 30 15:43:38 my_hostname scylla[2401]:   0x4457a47
Jan 30 15:43:38 my_hostname scylla[2401]:   0x4476765
Jan 30 15:43:38 my_hostname scylla[2401]:   0x442a4ca
Jan 30 15:43:38 my_hostname scylla[2401]:   /opt/scylladb/libreloc/libpthread.so.0+0x9298
Jan 30 15:43:38 my_hostname scylla[2401]:   /opt/scylladb/libreloc/libc.so.6+0x100352
Jan 30 15:43:38 my_hostname systemd[1]: Started Scylla Housekeeping restart mode.
Jan 30 15:43:38 my_hostname systemd[1]: Started Process Core Dump (PID 2443/UID 0).
Jan 30 15:43:38 my_hostname systemd-coredump[2448]: Process 2401 (scylla) of user 111 dumped core.
Jan 30 15:43:38 my_hostname systemd[1]: systemd-coredump@3-2443-0.service: Succeeded.
Jan 30 15:43:38 my_hostname scylla-jmx[2424]: Connecting to http://127.0.0.1:10000/
Jan 30 15:43:38 my_hostname scylla-jmx[2424]: Starting the JMX server
Jan 30 15:43:38 my_hostname scylla-housekeeping[2447]: /opt/scylladb/scripts/libexec/scylla-housekeeping:183: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
Jan 30 15:43:38 my_hostname scylla-housekeeping[2447]:   config = configparser.SafeConfigParser()
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]: Traceback (most recent call last):
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]:   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]:     args.func(args)
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]:   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]:     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]:   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]:     return get_json_from_url("http://" + api_address + path)
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]:   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 69, in get_json_from_url
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]:     status, retval = result.get(timeout=5)
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]:   File "/opt/scylladb/python3/lib64/python3.9/multiprocessing/pool.py", line 767, in get
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]:     raise TimeoutError
Jan 30 15:43:43 my_hostname scylla-housekeeping[2447]: multiprocessing.context.TimeoutError
Jan 30 15:43:43 my_hostname systemd[1]: scylla-housekeeping-restart.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 15:43:43 my_hostname systemd[1]: scylla-housekeeping-restart.service: Failed with result 'exit-code'
```

And finally, here is the coredump information I was able to collect:
```
root@my_hostname2:~# coredumpctl list
TIME                            PID   UID   GID SIG COREFILE  EXE
Mon 2023-01-30 16:15:20 CST  1116706   111   118  11 present   /opt/scylladb/libexec/scylla
root@my_hostname2:~# coredumpctl dump 1116706
           PID: 1116706 (scylla)
           UID: 111 (scylla)
           GID: 118 (scylla)
        Signal: 11 (SEGV)
     Timestamp: Mon 2023-01-30 16:12:44 CST (3min 43s ago)
  Command Line: /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-7 --lock-memory=1
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
          Unit: scylla-server.service
         Slice: scylla-server.slice
       Boot ID: e4425173b2104a69a684597105e101ec
    Machine ID: 766bbe3f089f451b95f0f22bcb8de667
      Hostname: my_hostname2
       Storage: /var/lib/systemd/coredump/core.scylla.111.e4425173b2104a69a684597105e101ec.1116706.1675116764000000000000
       Message: Process 1116706 (scylla) of user 111 dumped core.

                Stack trace of thread 1116711:
                #0  0x000000000447b5b4 n/a (scylla + 0x427b5b4)
                #1  0x00000000024c422c n/a (scylla + 0x22c422c)
                #2  0x0000000002b715cc n/a (scylla + 0x29715cc)
                #3  0x0000000004456675 n/a (scylla + 0x4256675)
                #4  0x0000000004457a48 n/a (scylla + 0x4257a48)
                #5  0x0000000004476766 n/a (scylla + 0x4276766)
                #6  0x000000000442a4cb n/a (scylla + 0x422a4cb)
                #7  0x00007f7100373299 n/a (libpthread.so.0 + 0x9299)
                #8  0x00007f70ff885353 __clone (libc.so.6 + 0x100353)

                Stack trace of thread 1116712:
                #0  0x00000000013619e8 n/a (scylla + 0x11619e8)
                #1  0x0000000001358db0 n/a (scylla + 0x1158db0)
                #2  0x0000000001a83f68 n/a (scylla + 0x1883f68)
                #3  0x0000000001a755ff n/a (scylla + 0x18755ff)
                #4  0x0000000001a77092 n/a (scylla + 0x1877092)
                #5  0x0000000001a76a93 n/a (scylla + 0x1876a93)
                #6  0x0000000001b2ab5b n/a (scylla + 0x192ab5b)
                #7  0x0000000001b265cb n/a (scylla + 0x19265cb)
                #8  0x0000000001b24efe n/a (scylla + 0x1924efe)
                #9  0x0000000001b17510 n/a (scylla + 0x1917510)
                #10 0x0000000001b16db4 n/a (scylla + 0x1916db4)
                #11 0x00000000046c61d2 n/a (scylla + 0x44c61d2)

                Stack trace of thread 1116716:
                #0  0x00007f710037c94c read (libpthread.so.0 + 0x1294c)
                #1  0x0000000004498ba5 n/a (scylla + 0x4298ba5)
                #2  0x0000000004498f10 n/a (scylla + 0x4298f10)
                #3  0x000000000442a4cb n/a (scylla + 0x422a4cb)
                #4  0x00007f7100373299 n/a (libpthread.so.0 + 0x9299)
                #5  0x00007f70ff885353 __clone (libc.so.6 + 0x100353)

                Stack trace of thread 1116715:
                #0  0x00007f710037c94c read (libpthread.so.0 + 0x1294c)
                #1  0x0000000004498ba5 n/a (scylla + 0x4298ba5)
                #2  0x0000000004498f10 n/a (scylla + 0x4298f10)
                #3  0x000000000442a4cb n/a (scylla + 0x422a4cb)
                #4  0x00007f7100373299 n/a (libpthread.so.0 + 0x9299)
                #5  0x00007f70ff885353 __clone (libc.so.6 + 0x100353)

                Stack trace of thread 1116714:
                #0  0x00007f710037c94c read (libpthread.so.0 + 0x1294c)
                #1  0x0000000004498ba5 n/a (scylla + 0x4298ba5)
                #2  0x0000000004498f10 n/a (scylla + 0x4298f10)
                #3  0x000000000442a4cb n/a (scylla + 0x422a4cb)
                #4  0x00007f7100373299 n/a (libpthread.so.0 + 0x9299)
                #5  0x00007f70ff885353 __clone (libc.so.6 + 0x100353)

                Stack trace of thread 1116721:
                #0  0x00007f710037c94c read (libpthread.so.0 + 0x1294c)
                #1  0x0000000004498ba5 n/a (scylla + 0x4298ba5)
                #2  0x0000000004498f10 n/a (scylla + 0x4298f10)
                #3  0x000000000442a4cb n/a (scylla + 0x422a4cb)
                #4  0x00007f7100373299 n/a (libpthread.so.0 + 0x9299)
                #5  0x00007f70ff885353 __clone (libc.so.6 + 0x100353)

                Stack trace of thread 1116717:
                #0  0x00007f710037c94c read (libpthread.so.0 + 0x1294c)
                #1  0x0000000004498ba5 n/a (scylla + 0x4298ba5)
                #2  0x0000000004498f10 n/a (scylla + 0x4298f10)
                #3  0x000000000442a4cb n/a (scylla + 0x422a4cb)
                #4  0x00007f7100373299 n/a (libpthread.so.0 + 0x9299)
                #5  0x00007f70ff885353 __clone (libc.so.6 + 0x100353)

                Stack trace of thread 1116707:
                #0  0x0000000001218b60 n/a (scylla + 0x1018b60)
                #1  0x0000000004456675 n/a (scylla + 0x4256675)
                #2  0x0000000004457a48 n/a (scylla + 0x4257a48)
                #3  0x0000000004476766 n/a (scylla + 0x4276766)
                #4  0x000000000442a4cb n/a (scylla + 0x422a4cb)
                #5  0x00007f7100373299 n/a (libpthread.so.0 + 0x9299)
                #6  0x00007f70ff885353 __clone (libc.so.6 + 0x100353)

                Stack trace of thread 1116706:
                #0  0x0000000002d1a40f n/a (scylla + 0x2b1a40f)
                #1  0x0000000002d18002 n/a (scylla + 0x2b18002)
                #2  0x0000000002d16182 n/a (scylla + 0x2b16182)
                #3  0x0000000002cfaee1 n/a (scylla + 0x2afaee1)
                #4  0x0000000004456675 n/a (scylla + 0x4256675)
                #5  0x0000000004457a48 n/a (scylla + 0x4257a48)
                #6  0x0000000004456cad n/a (scylla + 0x4256cad)
                #7  0x00000000043fd039 n/a (scylla + 0x41fd039)
                #8  0x00000000043fc517 n/a (scylla + 0x41fc517)
                #9  0x0000000000fa78fe n/a (scylla + 0xda78fe)
                #10 0x0000000000fa51db n/a (scylla + 0xda51db)
                #11 0x00007f70ff7acb75 __libc_start_main (libc.so.6 + 0x27b75)
                #12 0x0000000000fa41ae n/a (scylla + 0xda41ae)

                Stack trace of thread 1116710:
                #0  0x00000000036c3103 n/a (scylla + 0x34c3103)
                #1  0x0000000001a6e7db n/a (scylla + 0x186e7db)
                #2  0x0000000001a72e60 n/a (scylla + 0x1872e60)
                #3  0x0000000001a73fa7 n/a (scylla + 0x1873fa7)
                #4  0x0000000001a75868 n/a (scylla + 0x1875868)
                #5  0x0000000001a77092 n/a (scylla + 0x1877092)
                #6  0x0000000001a76a93 n/a (scylla + 0x1876a93)
                #7  0x0000000001b2ab5b n/a (scylla + 0x192ab5b)
                #8  0x0000000001b265cb n/a (scylla + 0x19265cb)
                #9  0x0000000001b24efe n/a (scylla + 0x1924efe)
                #10 0x0000000001b17510 n/a (scylla + 0x1917510)
                #11 0x0000000001b16db4 n/a (scylla + 0x1916db4)
                #12 0x00000000046c61d2 n/a (scylla + 0x44c61d2)

                Stack trace of thread 1116720:
                #0  0x00007f710037c94c read (libpthread.so.0 + 0x1294c)
                #1  0x0000000004498ba5 n/a (scylla + 0x4298ba5)
                #2  0x0000000004498f10 n/a (scylla + 0x4298f10)
                #3  0x000000000442a4cb n/a (scylla + 0x422a4cb)
                #4  0x00007f7100373299 n/a (libpthread.so.0 + 0x9299)
                #5  0x00007f70ff885353 __clone (libc.so.6 + 0x100353)

                Stack trace of thread 1116708:
                #0  0x00000000016c0c09 n/a (scylla + 0x14c0c09)
                #1  0x00000000016bff28 n/a (scylla + 0x14bff28)
                #2  0x00000000016befdb n/a (scylla + 0x14befdb)
                #3  0x0000000001b24de4 n/a (scylla + 0x1924de4)
                #4  0x0000000001b17510 n/a (scylla + 0x1917510)
                #5  0x0000000001b16db4 n/a (scylla + 0x1916db4)
                #6  0x00000000046c61d2 n/a (scylla + 0x44c61d2)

                Stack trace of thread 1116719:
                #0  0x00007f710037c94c read (libpthread.so.0 + 0x1294c)
                #1  0x0000000004498ba5 n/a (scylla + 0x4298ba5)
                #2  0x0000000004498f10 n/a (scylla + 0x4298f10)
                #3  0x000000000442a4cb n/a (scylla + 0x422a4cb)
                #4  0x00007f7100373299 n/a (libpthread.so.0 + 0x9299)
                #5  0x00007f70ff885353 __clone (libc.so.6 + 0x100353)

                Stack trace of thread 1116713:
                #0  0x00007f7100bd6755 LZ4_compress_fast_extState (liblz4.so.1 + 0x6755)
                #1  0x00007f7100bd788f LZ4_compress_fast (liblz4.so.1 + 0x788f)
                #2  0x00000000017c33f6 n/a (scylla + 0x15c33f6)
                #3  0x0000000001ac8c57 n/a (scylla + 0x18c8c57)
                #4  0x0000000001265984 n/a (scylla + 0x1065984)
                #5  0x0000000001a765c9 n/a (scylla + 0x18765c9)
                #6  0x0000000001a75796 n/a (scylla + 0x1875796)
                #7  0x0000000001a77092 n/a (scylla + 0x1877092)
                #8  0x0000000001a76a93 n/a (scylla + 0x1876a93)
                #9  0x0000000001b2ab5b n/a (scylla + 0x192ab5b)
                #10 0x0000000001b265cb n/a (scylla + 0x19265cb)
                #11 0x0000000001b24efe n/a (scylla + 0x1924efe)
                #12 0x0000000001b17510 n/a (scylla + 0x1917510)
                #13 0x0000000001b16db4 n/a (scylla + 0x1916db4)
                #14 0x00000000046c61d2 n/a (scylla + 0x44c61d2)

                Stack trace of thread 1116718:
                #0  0x00007f710037c94c read (libpthread.so.0 + 0x1294c)
                #1  0x0000000004498ba5 n/a (scylla + 0x4298ba5)
                #2  0x0000000004498f10 n/a (scylla + 0x4298f10)
                #3  0x000000000442a4cb n/a (scylla + 0x422a4cb)
                #4  0x00007f7100373299 n/a (libpthread.so.0 + 0x9299)
                #5  0x00007f70ff885353 __clone (libc.so.6 + 0x100353)

                Stack trace of thread 1116709:
                #0  0x0000000002ba1008 n/a (scylla + 0x29a1008)
                #1  0x0000000001b16344 n/a (scylla + 0x1916344)
                #2  0x0000000001b2a2de n/a (scylla + 0x192a2de)
                #3  0x0000000001b265cb n/a (scylla + 0x19265cb)
                #4  0x0000000001b24efe n/a (scylla + 0x1924efe)
                #5  0x0000000001b17510 n/a (scylla + 0x1917510)
                #6  0x0000000001b16db4 n/a (scylla + 0x1916db4)
                #7  0x00000000046c61d2 n/a (scylla + 0x44c61d2)
```

**Comment by michoecho** [comment] 2023-02-04 17:39
Backtrace decoded:
```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:750
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:780
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:792
 (inlined by) seastar::sigsegv_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3668
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3654
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3650
wasmtime_runtime::traphandlers::unix::trap_handler at wasmtime_runtime.9xv9ixev-cgu.15:?
?? ??:0
~timer at ./build/release/seastar/./seastar/src/core/reactor.cc:579
seastar::basic_semaphore<seastar::semaphore_default_exception_factory, seastar::lowres_clock>::wait(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, unsigned long) at paxos_state.cc:?
 (inlined by) seastar::basic_semaphore<seastar::semaphore_default_exception_factory, seastar::lowres_clock>::wait(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, unsigned long) at ././seastar/include/seastar/core/semaphore.hh:197
seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> > seastar::get_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock>(seastar::basic_semaphore<seastar::semaphore_default_exception_factory, seastar::lowres_clock>&, unsigned long, seastar::basic_semaphore<seastar::semaphore_default_exception_factory, seastar::lowres_clock>::time_point) at ././seastar/include/seastar/core/semaphore.hh:455
 (inlined by) seastar::basic_rwlock<seastar::lowres_clock>::hold_write_lock(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >) at ././seastar/include/seastar/core/rwlock.hh:164
 (inlined by) operator()<seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> > at ./db/view/row_locking.cc:104
 (inlined by) seastar::future<row_locker::lock_holder> std::__invoke_impl<seastar::future<row_locker::lock_holder>, row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >(std::__invoke_other, row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::__invoke_result<row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >::type std::__invoke<row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >(row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
 (inlined by) std::invoke_result<row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >::type std::invoke<row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >(row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/functional:97
 (inlined by) auto seastar::internal::future_invoke<row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >(row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock>&&) at ././seastar/include/seastar/core/future.hh:1211
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1582
 (inlined by) void seastar::futurize<seastar::future<row_locker::lock_holder> >::satisfy_with_result_of<seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >::then_impl_nrvo<row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2, seastar::future<row_locker::lock_holder> >(row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&&)::{lambda(seastar::internal::promise_base_with_type<row_locker::lock_holder>&&, row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::future_state<seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >&&)#1}::operator()(seastar::internal::promise_base_with_type<row_locker::lock_holder>&&, row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::future_state<seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >&&) const::{lambda()#1}>(seastar::internal::promise_base_with_type<row_locker::lock_holder>&&, row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&&) at ././seastar/include/seastar/core/future.hh:2120
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1575
 (inlined by) seastar::continuation<seastar::internal::promise_base_with_type<row_locker::lock_holder>, row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2, seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >::then_impl_nrvo<row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2, seastar::future<row_locker::lock_holder> >(row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&&)::{lambda(seastar::internal::promise_base_with_type<row_locker::lock_holder>&&, row_locker::lock_ck(dht::decorated_key const&, clustering_key_prefix const&, bool, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, row_locker::stats&)::$_2&, seastar::future_state<seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >&&)#1}, seastar::semaphore_units<seastar::semaphore_default_exception_factory, seastar::lowres_clock> >::run_and_dispose() at ././seastar/include/seastar/core/future.hh:767
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2348
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2758
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2927
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4137
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:291
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:560
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
/data/scylla-s3-reloc.cache/by-build-id/520004ed6991c6969da975000ec4a2ea10defe99/extracted/scylla/libreloc/libpthread.so.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=219a7f6a92210920b2b6c86ef84d842b33324b0f, for GNU/Linux 3.2.0, not stripped

start_thread at ??:?
/data/scylla-s3-reloc.cache/by-build-id/520004ed6991c6969da975000ec4a2ea10defe99/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=9de0f6e78ec16db4c6c167efc6b37466705edeff, for GNU/Linux 3.2.0, not stripped

__GI___clone at :?
```

**Comment by michoecho** [comment] 2023-02-04 17:40
This is almost surely a duplicate of https://github.com/scylladb/scylladb/issues/12632.

**Comment by mykaul** [comment] 2023-04-16 15:03
> This is almost surely a duplicate of #12632.

#12632 seem to be fixed and backported to all branches - what else is needed here?

**Comment by DoronArazii** [comment] 2023-08-01 13:18
The fix is existing in all supported versions.
Closing.

**Closed by DoronArazii** 2023-08-01 13:18 UTC
