### ISSUE TITLE
Failed to start a Raft group in test_rolling_upgrade

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16937] opened 2024-01-23 10:38 UTC
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release-with-consistent-topology-changes/35/testReport/rolling_upgrade_test/TestRollingUpgrade/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split013___test_rolling_upgrade/
```
ccmlib.node.NodeUpgradeError: Node node1 failed to start after upgrade. Error: The process is dead, returncode=-6
```

https://jenkins.scylladb.com/job/scylla-master/job/dtest-release-with-consistent-topology-changes/35/artifact/logs-full.release.013/1705576191779_rolling_upgrade_test.py%3A%3ATestRollingUpgrade%3A%3Atest_rolling_upgrade/node1.log
```
INFO  2024-01-18 11:09:47,999 [shard 0:main] init - Scylla version 5.5.0~dev-0.20240117.3d76aefb98ef with build-id 2adb61695a2929d5af91320889aa27a5badcb6d6 starting ...

ERROR 2024-01-18 11:09:48,349 [shard 0:main] raft_group_registry - Failed to start a Raft group 05603bd0-b5f2-11ee-a6bd-38951f6a8ad9: missing_column (missing column: cleanup_status), at: 0x619012e 0x6190740 0x6190a28 0x5c4c177 0x484bd94 0x13b0cea 0x5c8c62f 0x5c8d917 0x5c8cc78 0x5c1bce7 0x5c1ae9c 0x1343f39 0x1345990 0x13425bc /jenkins/workspace/scylla-master/dtest-release-with-consistent-topology-changes/scylla/.ccm/scylla-repository/3d76aefb98ef2b49098ea9e890b4c3a82ffe2297/libreloc/libc.so.6+0x27b89 /jenkins/workspace/scylla-master/dtest-release-with-consistent-topology-changes/scylla/.ccm/scylla-repository/3d76aefb98ef2b49098ea9e890b4c3a82ffe2297/libreloc/libc.so.6+0x27c4a 0x133fe64
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::(anonymous namespace)::thread_wake_task
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#2}, seastar::future<int> >(scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#3}, false>, seastar::future<int>::then_wrapped_nrvo<seastar::future<int>, seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#3}, false> >(seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#3}, false>&, seastar::future_state<int>&&)#1}, int>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false>, seastar::future<int>::then_wrapped_nrvo<seastar::future<int>, seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false> >(seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false>&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false>&, seastar::future_state<int>&&)#1}, int>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}, seastar::future<int>::then_impl_nrvo<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}, seastar::future<void> >(seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}&, seastar::future_state<int>&&)#1}, int>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}, seastar::future<void>::then_wrapped_nrvo<void, seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}>(seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Aborting on shard 0.
Backtrace:
  0x5c7aa78
  0x5cb10a1
  /jenkins/workspace/scylla-master/dtest-release-with-consistent-topology-changes/scylla/.ccm/scylla-repository/3d76aefb98ef2b49098ea9e890b4c3a82ffe2297/libreloc/libc.so.6+0x3dbaf
  /jenkins/workspace/scylla-master/dtest-release-with-consistent-topology-changes/scylla/.ccm/scylla-repository/3d76aefb98ef2b49098ea9e890b4c3a82ffe2297/libreloc/libc.so.6+0x8e883
  /jenkins/workspace/scylla-master/dtest-release-with-consistent-topology-changes/scylla/.ccm/scylla-repository/3d76aefb98ef2b49098ea9e890b4c3a82ffe2297/libreloc/libc.so.6+0x3dafd
  /jenkins/workspace/scylla-master/dtest-release-with-consistent-topology-changes/scylla/.ccm/scylla-repository/3d76aefb98ef2b49098ea9e890b4c3a82ffe2297/libreloc/libc.so.6+0x2687e
  0x5c4c1f7
  0x484bd94
  0x13b0cea
  0x5c8c62f
  0x5c8d917
  0x5c8cc78
  0x5c1bce7
  0x5c1ae9c
  0x1343f39
  0x1345990
  0x13425bc
  /jenkins/workspace/scylla-master/dtest-release-with-consistent-topology-changes/scylla/.ccm/scylla-repository/3d76aefb98ef2b49098ea9e890b4c3a82ffe2297/libreloc/libc.so.6+0x27b89
  /jenkins/workspace/scylla-master/dtest-release-with-consistent-topology-changes/scylla/.ccm/scylla-repository/3d76aefb98ef2b49098ea9e890b4c3a82ffe2297/libreloc/libc.so.6+0x27c4a
  0x133fe64
```

Decoded:
```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:826
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:856
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:868
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:4062
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4038
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:4034
/data/scylla-s3-reloc.cache/by-build-id/2adb61695a2929d5af91320889aa27a5badcb6d6/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7026fe8c129a523e07856d7c96306663ceab6e24, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:57
service::raft_group_registry::start_server_for_group(service::raft_server_for_group) at ./service/raft/raft_group_registry.cc:367
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/coroutine:240
 (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:125
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2666
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:3129
```

Core dump: https://jenkins.scylladb.com/job/scylla-master/job/dtest-release-with-consistent-topology-changes/35/artifact/logs-full.release.013/1705576191779_rolling_upgrade_test.py%3A%3ATestRollingUpgrade%3A%3Atest_rolling_upgrade/node1-scylla.13606.1705576188.core.gz

**Comment by bhalevy** [comment] 2024-01-23 11:15
So let's add a `required_features("!consistent-topology-changes")` for the upgrade test and a comment mentioning #15008 so this dtest would be skipped accrodingly.

**Comment by kbr-scylla** [comment] 2024-01-23 11:19
cc @temichus @aleksbykov

**Comment by temichus** [comment] 2024-01-23 11:51
@kbr-scylla @bhalevy,  is it connected/duplicate of the issue  that I just created  https://github.com/scylladb/scylladb/issues/16941

**Comment by temichus** [comment] 2024-01-23 12:06
@kbr-scylla @bhalevy  there is pr https://github.com/scylladb/scylla-dtest/pull/3891 for disabling test from raft topology

**Comment by enaydanov** [comment] 2024-02-14 10:51
Same problem for `reversed_queries_test.py::TestReversedQueriesSelectorsDuringUpgrade::test_queries_during_upgrade` too. Upgrade path: 5.4.2-0.20240117.6c625e8cd3c6 -> 5.5.0~dev-0.20240211.13e16475fabb

**Comment by kbr-scylla** [comment] 2024-02-14 11:32
We need another report with set of logs testing upgrade on the new version.

**Comment by kbr-scylla** [comment] 2024-03-17 20:20
@temichus @aleksbykov The test needs to be adjusted.
If I understand correctly, it's currently starting node in previous version (5.4) with consistent-topology-changes experimental feature enabled, then upgrading to 6.0.
The 5.4 consistent-topology-changes feature is immature, there were many backward-incompatible changes -- so we don't support such upgrade path.

Instead, we should test upgrade path:
- from 5.4 with `consistent-topology-changes` **disabled**,
- to 6.0 with `consistent-topology-changes` **enabled**.

So we need the same adjustments as described in this issue: https://github.com/scylladb/scylladb/issues/17822

**Comment by kbr-scylla** [comment] 2024-03-17 20:21
Same for `reversed_queries_test.py::TestReversedQueriesSelectorsDuringUpgrade::test_queries_during_upgrade`

**Comment by temichus** [comment] 2024-03-28 17:30
@aleksbykov does this fixed in https://github.com/scylladb/scylla-dtest/pull/4066 ?

**Comment by aleksbykov** [comment] 2024-03-29 10:05
yes, it should  fixed it

**Comment by temichus** [comment] 2024-03-31 09:25
https://github.com/scylladb/scylla-dtest/pull/4066 - merged. Close the issue

**Closed by temichus** 2024-03-31 09:25 UTC
Labels: tests/dtest, area/topology changes, area/raft
