### ISSUE TITLE
[x86_64, debug] test_password_login_message.test_login_message_after_half_of_the_cluster_is_down Failed to add servers (need to add manager.servers_see_each_other() to the test)

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#17298] opened 2024-02-12 20:20 UTC
Seen in https://jenkins.scylladb.com/job/scylla-master/job/next/7226/testReport/(root)/test_password_login_message/Build___x86___Unit_Tests_x86___test_login_message_after_half_of_the_cluster_is_down_8/ 

```

21:46:03  =================================== FAILURES ===================================
21:46:03  _____________ test_login_message_after_half_of_the_cluster_is_down _____________
21:46:03  
21:46:03  self = <test.pylib.manager_client.ManagerClient object at 0x7fde09e51f90>
21:46:03  servers_num = 2, cmdline = None
21:46:03  config = {'authenticator': 'PasswordAuthenticator', 'authorizer': 'CassandraAuthorizer', 'failure_detector_timeout_in_ms': 2000, 'permissions_update_interval_in_ms': 0, ...}
21:46:03  property_file = None, start = True, expected_error = None
21:46:03  
21:46:03      async def servers_add(self, servers_num: int = 1,
21:46:03                            cmdline: Optional[List[str]] = None,
21:46:03                            config: Optional[dict[str, Any]] = None,
21:46:03                            property_file: Optional[dict[str, Any]] = None,
21:46:03                            start: bool = True,
21:46:03                            expected_error: Optional[str] = None) -> [ServerInfo]:
21:46:03          """Add new servers concurrently.
21:46:03          This function can be called only if the cluster uses consistent topology changes, which support
21:46:03          concurrent bootstraps. If your test does not fulfill this condition and you want to add multiple
21:46:03          servers, you should use multiple server_add calls."""
21:46:03          assert servers_num > 0, f"servers_add: cannot add {servers_num} servers, servers_num must be positive"
21:46:03      
21:46:03          try:
21:46:03              data = self._create_server_add_data(None, cmdline, config, property_file, start, expected_error)
21:46:03              data['servers_num'] = servers_num
21:46:03  >           server_infos = await self.client.put_json("/cluster/addservers", data, response_type="json",
21:46:03                                                        timeout=ScyllaServer.TOPOLOGY_TIMEOUT * servers_num)
21:46:03  
21:46:03  test/pylib/manager_client.py:283: 
21:46:03  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
21:46:03  
21:46:03  self = <test.pylib.rest_client.UnixRESTClient object at 0x7fde09e3aa50>
21:46:03  resource_uri = '/cluster/addservers'
21:46:03  data = {'config': {'authenticator': 'PasswordAuthenticator', 'authorizer': 'CassandraAuthorizer', 'failure_detector_timeout_in_ms': 2000, 'permissions_update_interval_in_ms': 0, ...}, 'servers_num': 2, 'start': True}
21:46:03  host = None, port = None, params = None, response_type = 'json', timeout = 2000
21:46:03  
21:46:03      async def put_json(self, resource_uri: str, data: Optional[Mapping] = None, host: Optional[str] = None,
21:46:03                         port: Optional[int] = None, params: Optional[dict[str, str]] = None,
21:46:03                         response_type: Optional[str] = None, timeout: Optional[float] = None) -> Any:
21:46:03  >       ret = await self._fetch("PUT", resource_uri, response_type = response_type, host = host,
21:46:03                                  port = port, params = params, json = data, timeout = timeout)
21:46:03  
21:46:03  test/pylib/rest_client.py:111: 
21:46:03  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
21:46:03  
21:46:03  self = <test.pylib.rest_client.UnixRESTClient object at 0x7fde09e3aa50>
21:46:03  method = 'PUT', resource = '/cluster/addservers', response_type = 'json'
21:46:03  host = None, port = None, params = None
21:46:03  json = {'config': {'authenticator': 'PasswordAuthenticator', 'authorizer': 'CassandraAuthorizer', 'failure_detector_timeout_in_ms': 2000, 'permissions_update_interval_in_ms': 0, ...}, 'servers_num': 2, 'start': True}
21:46:03  timeout = 2000
21:46:03  
21:46:03      async def _fetch(self, method: str, resource: str, response_type: Optional[str] = None,
21:46:03                       host: Optional[str] = None, port: Optional[int] = None,
21:46:03                       params: Optional[Mapping[str, str]] = None,
21:46:03                       json: Optional[Mapping] = None, timeout: Optional[float] = None) -> Any:
21:46:03          # Can raise exception. See https://docs.aiohttp.org/en/latest/web_exceptions.html
21:46:03          assert method in ["GET", "POST", "PUT", "DELETE"], f"Invalid HTTP request method {method}"
21:46:03          assert response_type is None or response_type in ["text", "json"], \
21:46:03                  f"Invalid response type requested {response_type} (expected 'text' or 'json')"
21:46:03          # Build the URI
21:46:03          port = port if port else self.default_port if hasattr(self, "default_port") else None
21:46:03          port_str = f":{port}" if port else ""
21:46:03          assert host is not None or hasattr(self, "default_host"), "_fetch: missing host for " \
21:46:03                  "{method} {resource}"
21:46:03          host_str = host if host is not None else self.default_host
21:46:03          uri = self.uri_scheme + "://" + host_str + port_str + resource
21:46:03          logging.debug(f"RESTClient fetching {method} {uri}")
21:46:03      
21:46:03          client_timeout = ClientTimeout(total = timeout if timeout is not None else 300)
21:46:03          async with request(method, uri,
21:46:03                             connector = self.connector if hasattr(self, "connector") else None,
21:46:03                             params = params, json = json, timeout = client_timeout) as resp:
21:46:03              if resp.status != 200:
21:46:03                  text = await resp.text()
21:46:03  >               raise HTTPError(uri, resp.status, params, json, text)
21:46:03  E               test.pylib.rest_client.HTTPError: HTTP error 500, uri: http+unix://api/cluster/addservers, params: None, json: {'start': True, 'config': {'failure_detector_timeout_in_ms': 2000, 'authenticator': 'PasswordAuthenticator', 'authorizer': 'CassandraAuthorizer', 'permissions_validity_in_ms': 0, 'permissions_update_interval_in_ms': 0}, 'servers_num': 2}, body:
21:46:03  E               failed to start the node, timeout reached, server_id 27, IP 127.98.112.2, workdir scylla-27, host_id a562822e-34a5-407a-8356-34bb0eefee8e, cql [not connected]
21:46:03  E               Check the log files:
21:46:03  E               /scylladir/testlog/x86_64/test.py.debug-release-dev.log
21:46:03  E               /scylladir/testlog/x86_64/debug/scylla-27.log
21:46:03  
21:46:03  test/pylib/rest_client.py:69: HTTPError
21:46:03  
21:46:03  The above exception was the direct cause of the following exception:
21:46:03  
21:46:03  manager = <test.pylib.manager_client.ManagerClient object at 0x7fde09e51f90>
21:46:03  
21:46:03      @pytest.mark.asyncio
21:46:03      async def test_login_message_after_half_of_the_cluster_is_down(manager: ManagerClient) -> None:
21:46:03          """Tests the error message after half of the cluster goes down"""
21:46:03          config = {
21:46:03              'failure_detector_timeout_in_ms': 2000,
21:46:03              'authenticator': 'PasswordAuthenticator',
21:46:03              'authorizer': 'CassandraAuthorizer',
21:46:03              'permissions_validity_in_ms': 0,
21:46:03              'permissions_update_interval_in_ms': 0,
21:46:03          }
21:46:03      
21:46:03  >       servers = await manager.servers_add(2, config=config)
21:46:03  
21:46:03  test/auth_cluster/test_password_login_message.py:34: 
21:46:03  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
21:46:03  
21:46:03  self = <test.pylib.manager_client.ManagerClient object at 0x7fde09e51f90>
21:46:03  servers_num = 2, cmdline = None
21:46:03  config = {'authenticator': 'PasswordAuthenticator', 'authorizer': 'CassandraAuthorizer', 'failure_detector_timeout_in_ms': 2000, 'permissions_update_interval_in_ms': 0, ...}
21:46:03  property_file = None, start = True, expected_error = None
21:46:03  
21:46:03      async def servers_add(self, servers_num: int = 1,
21:46:03                            cmdline: Optional[List[str]] = None,
21:46:03                            config: Optional[dict[str, Any]] = None,
21:46:03                            property_file: Optional[dict[str, Any]] = None,
21:46:03                            start: bool = True,
21:46:03                            expected_error: Optional[str] = None) -> [ServerInfo]:
21:46:03          """Add new servers concurrently.
21:46:03          This function can be called only if the cluster uses consistent topology changes, which support
21:46:03          concurrent bootstraps. If your test does not fulfill this condition and you want to add multiple
21:46:03          servers, you should use multiple server_add calls."""
21:46:03          assert servers_num > 0, f"servers_add: cannot add {servers_num} servers, servers_num must be positive"
21:46:03      
21:46:03          try:
21:46:03              data = self._create_server_add_data(None, cmdline, config, property_file, start, expected_error)
21:46:03              data['servers_num'] = servers_num
21:46:03              server_infos = await self.client.put_json("/cluster/addservers", data, response_type="json",
21:46:03                                                        timeout=ScyllaServer.TOPOLOGY_TIMEOUT * servers_num)
21:46:03          except Exception as exc:
21:46:03  >           raise Exception("Failed to add servers") from exc
21:46:03  E           Exception: Failed to add servers
21:46:03  
21:46:03  test/pylib/manager_client.py:286: Exception
21:46:03  ------------------------------ Captured log setup ------------------------------
21:46:03  20:30:53.718 DEBUG> Using selector: EpollSelector
21:46:03  20:30:53.719 DEBUG> Using selector: EpollSelector
21:46:03  20:30:53.720 DEBUG> before_test for test_login_message_after_half_of_the_cluster_is_down
21:46:03  20:30:53.720 DEBUG> RESTClient fetching GET http+unix://api/cluster/is-dirty
21:46:03  20:30:53.723 DEBUG> RESTClient fetching PUT http+unix://api/cluster/before-test/test_login_message_after_half_of_the_cluster_is_down
21:46:03  20:30:53.728 INFO> Using cluster: ScyllaCluster(name: da69bdd8-c9d4-11ee-b9ef-a8a159ead570, running: , stopped: ) for test test_login_message_after_half_of_the_cluster_is_down
21:46:03  20:30:53.728 DEBUG> RESTClient fetching GET http+unix://api/cluster/running-servers
21:46:03  ------------------------------ Captured log call -------------------------------
21:46:03  20:30:53.731 DEBUG> RESTClient fetching PUT http+unix://api/cluster/addservers
21:46:03  ---------------------------- Captured log teardown -----------------------------
21:46:03  20:47:34.558 DEBUG> after_test for test_login_message_after_half_of_the_cluster_is_down (success: False)
21:46:03  20:47:34.558 DEBUG> RESTClient fetching PUT http+unix://api/cluster/after-test/False
21:46:03  20:47:34.632 INFO> Cluster after test test_login_message_after_half_of_the_cluster_is_down: ScyllaCluster(name: da69bdd8-c9d4-11ee-b9ef-a8a159ead570, running: ScyllaServer(26, 127.98.112.11, 382d2f87-3137-4b9e-9ead-73f4529d8eaf), stopped: )
21:46:03  20:47:34.633 DEBUG> Using selector: EpollSelector
21:46:03  - generated xml file: /scylladir/testlog/x86_64/debug/xml/auth_cluster.test_password_login_message.3.xunit.xml -
21:46:03  ======================== 1 failed in 1000.93s (0:16:40) ========================

```

**Comment by mykaul** [comment] 2024-02-14 10:27
scylla-26 and -27 logs, test log
[auth_cluster.test_password_login_message.3.log](https://github.com/scylladb/scylladb/files/14278260/auth_cluster.test_password_login_message.3.log)

[scylla-26.log](https://github.com/scylladb/scylladb/files/14278250/scylla-26.log)
[scylla-27.log](https://github.com/scylladb/scylladb/files/14278251/scylla-27.log)

**Comment by mykaul** [comment] 2024-02-14 12:49
I have no idea what:
```
 20:30:53.723 DEBUG> RESTClient fetching PUT http+unix://api/cluster/before-test/test_login_message_after_half_of_the_cluster_is_down
```

means....

**Comment by nuivall** [comment] 2024-02-14 13:12
Yes looks like a duplicate. Currently we need to put 
```
    hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
    await manager.servers_see_each_other(servers)
```
everywhere, long term perhaps test api can be changed with some notion of "readiness", and a way to express in test that we want cql ready, normal state cluster (I guess typical case).

**Comment by mykaul** [comment] 2024-02-14 13:15
> Yes looks like a duplicate. Currently we need to put
> 
> ```
>     hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
>     await manager.servers_see_each_other(servers)
> ```
> 
> everywhere, long term perhaps test api can be changed with some notion of "readiness", and a way to express in test that we want cql ready, normal state cluster (I guess typical case).

When I said 'everywhere' someone (don't remember who) disagreed with me. I thought it should have been added as a parameter to wait_for_cql_and_get_hosts() to call manager.servers_see_each_other() inside.

**Comment by nuivall** [comment] 2024-02-14 13:19
yes, everywhere as in a metaphoric meaning :), it's about easy to use API, when common case is default and then specific usages can be easily unfolded. 

as for flakiness of test.py I am not sure how we currently solve it but there should be an automation which repeats many times new/altered tests before merging, don't see how else can we prevent it.

**Comment by mykaul** [comment] 2024-02-14 13:28
Ah - here's the discussion - https://github.com/scylladb/scylladb/pull/17040#issuecomment-1914793423

**Comment by nyh** [comment] 2024-02-20 09:07
Seen again in CI run https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6800/testReport/junit/(root)/test_password_login_message/Tests___Unit_Tests___test_login_message_after_half_of_the_cluster_is_down/

From the log (https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6800/artifact/testlog/x86_64/debug/scylla-27.log):
```
Scylla version 5.5.0~dev-0.20240220.f92a9cafef13 with build-id 9fae8b7d22a93c2424dd4d5633dcfb5a7f3237e9 starting ...
...
ERROR 2024-02-20 08:33:30,069 [shard 1:main] database - regular column id 3 >= 0, at: 0xd34414a /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5685f9c /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5685cf7 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5688075 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5688acf /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x44bb40e /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x44bafc6 0xeda5109 0xecb10f3 0xe8f75ca 0xe7e20d8 0xe5f61f4 0xe389ef2 0xe425bad 0xd595e46 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4715728 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x471dce8 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4721d80 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4821856 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x481fa00 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x481f8f0 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x481f05c /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x44c6518 /lib64/libc.so.6+0x8c946 /lib64/libc.so.6+0x11296f
```
So I think this may be a duplicate of the infamous https://github.com/scylladb/scylladb/issues/16821 - but note that because we changed this from a warning to an on_internal_error (which crashes Scylla in our tests) it's no longer visible that this is happening in a repair or of which table.

**Comment by mykaul** [comment] 2024-02-25 12:21
Closing as dup.

**Closed by mykaul** 2024-02-25 12:21 UTC
Labels: area/stability, symptom/ci stability
