### ISSUE TITLE
Coredump during a truncate operation

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylladb#18478] opened 2024-04-30 13:31 UTC
## Packages

Scylla version: `5.5.0~dev-20240411.0be61e51d329` with build-id `54e018bb43eb2ae707aac127097747cd39532532`

Kernel Version: `5.15.0-1055-gcp`

## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

This happened during no nemeses being executed while stress utility (scylla-bench in this case) was truncating a keyspace.

Coredump download link:
```
gs://upload.scylladb.com/core.scylla.113.15415ff89fbd4602b243621e6037cc57.8748.1712988412000000/core.scylla.113.15415ff89fbd4602b243621e6037cc57.8748.1712988412000000.gz
```

Trace:
```
Stack trace of thread 8762:
#0  0x00007f05ef377884 __pthread_kill_implementation (libc.so.6 + 0x8e884)
#1  0x00007f05ef326afe raise (libc.so.6 + 0x3dafe)
#2  0x00007f05ef30f87f abort (libc.so.6 + 0x2687f)
#3  0x00007f05ef30f79b __assert_fail_base.cold (libc.so.6 + 0x2679b)
#4  0x00007f05ef31f187 __assert_fail (libc.so.6 + 0x36187)
#5  0x0000000001bb0a45 _ZN7replica8database8truncateERN2db15system_keyspaceERNS_5tableERKNS0_20table_truncate_stateENSt6chrono10time_pointI8db_clockNS9_8durationIlSt5ratioILl1ELl1000EEEEEE.resume (scylla + 0x19b0a45)
#6  0x0000000001422a0b _ZN7seastar8internal21coroutine_traits_baseIvE12promise_type15run_and_disposeEv (scylla + 0x1222a0b)
#7  0x0000000005e43310 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x5c43310)
#8  0x0000000005e445f8 _ZN7seastar7reactor6do_runEv (scylla + 0x5c445f8)
#9  0x0000000005e68531 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x5c68531)
#10 0x0000000005e03c4b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x5c03c4b)
#11 0x00007f05ef375947 start_thread (libc.so.6 + 0x8c947)
#12 0x00007f05ef3fb970 __clone3 (libc.so.6 + 0x112970)
```

Log of the failed assertion:
```
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard  2:stmt] database - Truncating scylla_bench.test with auto-snapshot
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard  2:stmt] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for table scylla_bench.test compaction_group=0 due to user-triggered operation
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard  1:stmt] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for table scylla_bench.test compaction_group=0 due to user-triggered operation
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard 10:stmt] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for table scylla_bench.test compaction_group=0 due to user-triggered operation
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard  0:stmt] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for table scylla_bench.test compaction_group=0 due to user-triggered operation
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard  2:comp] compaction - [Compact scylla_bench.test d12495c0-f95b-11ee-a2c7-1c8ddabaa812] Compacting of 2 sstables interrupted due to: sstables::compaction_stopped_exception (Compaction for scylla_bench/test was stopped due to: user-triggered operation), at 0x634aa7e 0x634b090 0x634b378 0x262380c 0x6222546
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#2}, seastar::future<sstables::compaction_result> >(sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false>, seastar::future<sstables::compaction_result>::then_wrapped_nrvo<seastar::future<sstables::compaction_result>, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false> >(seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#3}, false>&, seastar::future_state<sstables::compaction_result>&&)#1}, sstables::compaction_result>
   --------
   seastar::internal::coroutine_traits_base<sstables::compaction_result>::promise_type
   --------
   seastar::internal::coroutine_traits_base<std::optional<sstables::compaction_stats> >::promise_type
   --------
   seastar::shared_future<std::optional<sstables::compaction_stats> >::shared_state
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard  2:comp] compaction_manager - Compaction task 0x602003169200 for table scylla_bench.test compaction_group=0 [0x602004b9a0e0]: Compaction for scylla_bench/test was stopped due to: user-triggered operation: stopping
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard  1:comp] compaction - [Compact scylla_bench.test f231e380-f95b-11ee-88b6-1c91dabaa812] Compacting of 2 sstables interrupted due to: sstables::compaction_stopped_exception (Compaction for scylla_bench/test was stopped due to: user-triggered operation), at 0x634aa7e 0x634b090 0x634b378 0x262380c 0x6222546
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#2}, seastar::future<sstables::compaction_result> >(sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false>, seastar::future<sstables::compaction_result>::then_wrapped_nrvo<seastar::future<sstables::compaction_result>, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false> >(seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#3}, false>&, seastar::future_state<sstables::compaction_result>&&)#1}, sstables::compaction_result>
   --------
   seastar::internal::coroutine_traits_base<sstables::compaction_result>::promise_type
   --------
   seastar::internal::coroutine_traits_base<std::optional<sstables::compaction_stats> >::promise_type
   --------
   seastar::shared_future<std::optional<sstables::compaction_stats> >::shared_state
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard  1:comp] compaction_manager - Compaction task 0x601004f7cf00 for table scylla_bench.test compaction_group=0 [0x601004b0d9e0]: Compaction for scylla_bench/test was stopped due to: user-triggered operation: stopping
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard 10:comp] compaction - [Compact scylla_bench.test f6fc3cd0-f95b-11ee-8025-1c92dabaa812] Compacting of 2 sstables interrupted due to: sstables::compaction_stopped_exception (Compaction for scylla_bench/test was stopped due to: user-triggered operation), at 0x634aa7e 0x634b090 0x634b378 0x262380c 0x6222546
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#2}, seastar::future<sstables::compaction_result> >(sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false>, seastar::future<sstables::compaction_result>::then_wrapped_nrvo<seastar::future<sstables::compaction_result>, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false> >(seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#3}, false>&, seastar::future_state<sstables::compaction_result>&&)#1}, sstables::compaction_result>
   --------
   seastar::internal::coroutine_traits_base<sstables::compaction_result>::promise_type
   --------
   seastar::internal::coroutine_traits_base<std::optional<sstables::compaction_stats> >::promise_type
   --------
   seastar::shared_future<std::optional<sstables::compaction_stats> >::shared_state
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard 10:comp] compaction_manager - Compaction task 0x60a00860f900 for table scylla_bench.test compaction_group=0 [0x60a004f10840]: Compaction for scylla_bench/test was stopped due to: user-triggered operation: stopping
2024-04-13T06:06:29.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard  0:comp] compaction - [Compact scylla_bench.test eac95fb0-f95b-11ee-8f61-1c98dabaa812] Compacting of 2 sstables interrupted due to: sstables::compaction_stopped_exception (Compaction for scylla_bench/test was stopped due to: user-triggered operation), at 0x634aa7e 0x634b090 0x634b378 0x262380c 0x6222546
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#2}, seastar::future<sstables::compaction_result> >(sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false>, seastar::future<sstables::compaction_result>::then_wrapped_nrvo<seastar::future<sstables::compaction_result>, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false> >(seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::future<sstables::compaction_result>::finally_body<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#3}, false>&, seastar::future_state<sstables::compaction_result>&&)#1}, sstables::compaction_result>
   --------
   seastar::internal::coroutine_traits_base<sstables::compaction_result>::promise_type
   --------
   seastar::internal::coroutine_traits_base<std::optional<sstables::compaction_stats> >::promise_type
   --------
   seastar::shared_future<std::optional<sstables::compaction_stats> >::shared_state
2024-04-13T06:06:29.234+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:  [shard  0:comp] compaction_manager - Compaction task 0x600018e57c00 for table scylla_bench.test compaction_group=0 [0x600004529440]: Compaction for scylla_bench/test was stopped due to: user-triggered operation: stopping
2024-04-13T06:06:41.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5   !NOTICE | sudo[12576]: scylla-test : PWD=/home/scylla-test ; USER=root ; COMMAND=/usr/bin/coredumpctl -q --json=short
2024-04-13T06:06:41.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | sudo[12576]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1001)
2024-04-13T06:06:41.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | sudo[12576]: pam_unix(sudo:session): session closed for user root
2024-04-13T06:06:46.730+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | sshd[12581]: Accepted publickey for scylla-test from 10.142.0.90 port 55030 ssh2: RSA SHA256:sP+kqWiBiVzCCBfMfZdytOLQyAMfZeEqkbmuQxAtjjM
2024-04-13T06:06:46.730+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | sshd[12581]: pam_unix(sshd:session): session opened for user scylla-test(uid=1001) by (uid=0)
2024-04-13T06:06:46.730+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | systemd-logind[1339]: New session 25 of user scylla-test.
2024-04-13T06:06:46.730+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | systemd[1]: Started Session 25 of User scylla-test.
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]: scylla: replica/database.cc:2573: future<> replica::database::truncate(db::system_keyspace &, column_family &, const table_truncate_state &, db_clock::time_point): Assertion `!st.did_flush || rp == db::replay_position() || (truncated_at <= st.low_mark_at ? rp <= st.low_mark : st.low_mark <= rp)' failed.
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]: Aborting on shard 13.
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]: Backtrace:
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   0x5e316d8
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   0x5e67f31
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   /opt/scylladb/libreloc/libc.so.6+0x3dbaf
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   /opt/scylladb/libreloc/libc.so.6+0x8e883
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   /opt/scylladb/libreloc/libc.so.6+0x3dafd
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   /opt/scylladb/libreloc/libc.so.6+0x2687e
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   /opt/scylladb/libreloc/libc.so.6+0x2679a
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   /opt/scylladb/libreloc/libc.so.6+0x36186
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   0x1bb0a44
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   0x1422a0a
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   0x5e4330f
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   0x5e445f7
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   0x5e68530
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   0x5e03c4a
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   /opt/scylladb/libreloc/libc.so.6+0x8c946
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | scylla[8748]:   /opt/scylladb/libreloc/libc.so.6+0x11296f
2024-04-13T06:06:53.230+00:00 longevity-large-partitions-200k-pks-db-node-eb00557b-0-5     !INFO | systemd[1]: Created slice Slice /system/systemd-coredump.
```

## Impact

The DB crashes.

## How frequently does it reproduce?

Happened again on [this build](https://argus.scylladb.com/test/996501ad-c137-40ef-8dcc-a7d12f0ba3b6/runs?additionalRuns[]=dc7d1fd9-7184-4303-b393-083d38347d28)

## Installation details

Cluster size: 5 nodes (n2-highmem-16)

Scylla Nodes used in this run:
- longevity-large-partitions-200k-pks-db-node-eb00557b-0-9 (34.73.89.152 | 10.142.0.30) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eb00557b-0-8 (35.231.21.217 | 10.142.0.5) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eb00557b-0-7 (35.185.52.50 | 10.142.0.4) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eb00557b-0-6 (35.185.52.140 | 10.142.0.35) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eb00557b-0-5 (34.138.236.116 | 10.142.15.203) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eb00557b-0-4 (34.73.89.152 | 10.142.15.199) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eb00557b-0-3 (35.237.202.170 | 10.142.15.197) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eb00557b-0-2 (34.75.212.214 | 10.142.0.127) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eb00557b-0-11 (35.231.21.217 | 10.142.0.2) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eb00557b-0-10 (34.148.160.163 | 10.142.0.31) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eb00557b-0-1 (35.229.59.148 | 10.142.0.120) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/scylla-5-5-0-dev-x86-64-2024-04-12t04-13-39` (gce: undefined_region)

Test: `longevity-large-partition-200k-pks-4days-gce-test`
Test id: `eb00557b-4c59-4bc9-aad2-04cab75b98f3`
Test name: `scylla-master/tier1/longevity-large-partition-200k-pks-4days-gce-test`
Test config file(s):

- [longevity-large-partition-200k_pks-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ead2529c1f5f3816f04e3b23de737a359134c053/test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor eb00557b-4c59-4bc9-aad2-04cab75b98f3`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=eb00557b-4c59-4bc9-aad2-04cab75b98f3)
- Show all stored logs command: `$ hydra investigate show-logs eb00557b-4c59-4bc9-aad2-04cab75b98f3`

## Logs:
- **db-cluster-eb00557b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/eb00557b-4c59-4bc9-aad2-04cab75b98f3/20240414_092057/db-cluster-eb00557b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/eb00557b-4c59-4bc9-aad2-04cab75b98f3/20240414_092057/db-cluster-eb00557b.tar.gz)
- **sct-runner-events-eb00557b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/eb00557b-4c59-4bc9-aad2-04cab75b98f3/20240414_092057/sct-runner-events-eb00557b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/eb00557b-4c59-4bc9-aad2-04cab75b98f3/20240414_092057/sct-runner-events-eb00557b.tar.gz)
- **sct-eb00557b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/eb00557b-4c59-4bc9-aad2-04cab75b98f3/20240414_092057/sct-eb00557b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/eb00557b-4c59-4bc9-aad2-04cab75b98f3/20240414_092057/sct-eb00557b.log.tar.gz)
- **loader-set-eb00557b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/eb00557b-4c59-4bc9-aad2-04cab75b98f3/20240414_092057/loader-set-eb00557b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/eb00557b-4c59-4bc9-aad2-04cab75b98f3/20240414_092057/loader-set-eb00557b.tar.gz)
- **monitor-set-eb00557b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/eb00557b-4c59-4bc9-aad2-04cab75b98f3/20240414_092057/monitor-set-eb00557b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/eb00557b-4c59-4bc9-aad2-04cab75b98f3/20240414_092057/monitor-set-eb00557b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-large-partition-200k-pks-4days-gce-test/9/)
[Argus](https://argus.scylladb.com/test/996501ad-c137-40ef-8dcc-a7d12f0ba3b6/runs?additionalRuns[]=eb00557b-4c59-4bc9-aad2-04cab75b98f3)
</details>

**Comment by mykaul** [comment] 2024-05-01 09:51
@bhalevy - dup of https://github.com/scylladb/scylladb/issues/18059#issuecomment-2022413552 ?

**Comment by bhalevy** [comment] 2024-05-01 11:13
Decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:825
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:855
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:867
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:4071
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4047
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:4043
/data/scylla-s3-reloc.cache/by-build-id/54e018bb43eb2ae707aac127097747cd39532532/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=70e92bb237883be3065a6afc9f0696aef2d068bf, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
__assert_fail_base.cold at ??:?
__assert_fail at ??:?
replica::database::truncate(db::system_keyspace&, replica::table&, replica::database::table_truncate_state const&, std::chrono::time_point<db_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at ./replica/database.cc:2573
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/coroutine:240
 (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:125
```

**Comment by nyh** [comment] 2024-05-01 11:24
May be the same problem (different reproducer) as #18059

**Comment by bhalevy** [comment] 2024-05-01 11:56
> May be the same problem (different reproducer) as #18059

Right.  It about time to fix this assertion.
Cc @elcallio 

Closing this issue as duplicate of #18059 as it provides no extra value

**Closed** 2024-05-02 10:59 UTC
Labels: triage/master
