### ISSUE TITLE
raft: test_topology.test_remove_node_add_column is flaky

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#11721] opened 2022-10-05 10:03 UTC
The just-added (c200ae222) test_remove_node_add_column is failing sometimes.

Example failure 1:
https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2546/testReport/junit/(root)/non-boost%20tests/test_topology_release_2414/

Example failure 2:
https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2547/testReport/junit/(root)/non-boost%20tests/test_topology_dev_2414/

Example non-failure (after c200ae222 as well):
https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2545/

The error:
```
manager = <test.pylib.manager_client.ManagerClient object at 0x7ff754f179a0>
random_tables = <test.pylib.random_tables.RandomTables object at 0x7ff754687be0>

    @pytest.mark.asyncio
    async def test_remove_node_add_column(manager, random_tables):
        """Add a node, remove an original node, add a column"""
        servers = await manager.running_servers()
        table = await random_tables.add_table(ncolumns=5)
        await manager.server_add()
        server_uuid = await manager.get_host_id(servers[1])              # get uuid [1]
        await manager.server_stop_gracefully(servers[1])                 # stop     [1]
>       await manager.remove_node(servers[0], servers[1], server_uuid)   # Remove   [1]

test/topology/test_topology.py:50: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/pylib/manager_client.py:152: in remove_node
    await self.client.get_text(
test/pylib/rest_client.py:75: in get_text
    return await self.session.get_text(self._resource_uri(resource))
test/pylib/rest_client.py:36: in get_text
    resp = await self.get(resource_uri)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.pylib.rest_client.RESTSession object at 0x7ff754f17b50>
resource_uri = 'http+unix://api/cluster/remove-node/127.103.161.10/127.103.161.14/8d065179-b58e-4942-85c9-12aad0445dbe'

    async def get(self, resource_uri: str) -> aiohttp.ClientResponse:
        """Fetch remote resource or raise"""
        # Can raise exception. See https://docs.aiohttp.org/en/latest/web_exceptions.html
        resp = await self.session.get(resource_uri)
        if resp.status != 200:
            text = await resp.text()
>           raise RuntimeError(f"status code: {resp.status}, body text: {text}")
E           RuntimeError: status code: 500, body text: Error removing 127.103.161.14 8d065179-b58e-4942-85c9-12aad0445dbe status code: 500, body text: {"message": "seastar::rpc::remote_verb_error (node_ops_cmd_check: Node 127.103.161.4 rejected node_ops_cmd=removenode_abort from node=127.103.161.10 with ops_uuid=180e1afb-14dc-4abc-9333-c6f3ce94b05e, pending_node_ops={}, the node ops is unknown)", "code": 500}, resource http://127.103.161.10:10000/storage_service/remove_node params {'host_id': '8d065179-b58e-4942-85c9-12aad0445dbe'}

test/pylib/rest_client.py:31: RuntimeError
```

**Comment by michoecho** [comment] 2022-10-05 10:03
cc @kbr- @alecco

**Comment by michoecho** [comment] 2022-10-05 10:06
The salient part of the error:
`seastar::rpc::remote_verb_error (node_ops_cmd_check: Node 127.103.161.4 rejected node_ops_cmd=removenode_abort from node=127.103.161.10 with ops_uuid=180e1afb-14dc-4abc-9333-c6f3ce94b05e, pending_node_ops={}, the node ops is unknown`

**Comment by alecco** [comment] 2022-10-05 10:26
It's a Python driver problem...

```
cassandra.connection.ConnectionShutdown: Connection <AsyncoreConnection(140700249366384) 127.103.161.11:9042 (closed)> is already closed
```

**Comment by kbr-** [comment] 2022-10-05 10:31
The test started with the cluster
```
{127.103.161.9, 127.103.161.10, 127.103.161.14}
```

Then it successfully added a new node: `127.103.161.4`
Then it shutdown node `127.103.161.14` and started to remove it using `127.103.161.10` as removal coordinator.

The `removenode` proceeded until the last step (logs from `10`), which tries to remove the node from group 0 configuration:
```
INFO  2022-10-05 03:10:30,815 [shard 0] storage_service - removenode[180e1afb-14dc-4abc-9333-c6f3ce94b05e]: Marked ops done from coordinator=127.103.161.10
INFO  2022-10-05 03:10:30,816 [shard 0] storage_service - removenode[180e1afb-14dc-4abc-9333-c6f3ce94b05e]: removing node 127.103.161.14 from group 0
INFO  2022-10-05 03:10:30,816 [shard 0] raft_group0 - remove_from_group0(127.103.161.14): found the node in group 0 configuration, Raft ID: e0240096-5da9-4c54-813b-7440d6a841ae. Proceeding with the remove...
INFO  2022-10-05 03:10:30,825 [shard 0] compaction - [Compact system.peers 1faa2cd0-4442-11ed-89ad-f019680bd25d] Compacted 2 sstables to [/jenkins/workspace/releng/Scylla-CI/scylla/testlog/x86_64/release/scylla-10/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-14-big-Data.db:level=0]. 81kB to 40kB (~50% of original) in 9ms = 4MB/s. ~256 total partitions merged to 1.
INFO  2022-10-05 03:10:30,825 [shard 1] compaction - [Compact system.peers 1faa53e0-4442-11ed-aeb0-f01a680bd25d] Compacted 2 sstables to [/jenkins/workspace/releng/Scylla-CI/scylla/testlog/x86_64/release/scylla-10/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-19-big-Data.db:level=0]. 114kB to 57kB (~50% of original) in 8ms = 7MB/s. ~256 total partitions merged to 2.
INFO  2022-10-05 03:10:31,754 [shard 0] storage_service - removenode[180e1afb-14dc-4abc-9333-c6f3ce94b05e]: Stopped heartbeat_updater
WARN  2022-10-05 03:10:31,754 [shard 0] storage_service - node_ops_cmd_check: Node 127.103.161.10 rejected node_ops_cmd=removenode_abort from node=127.103.161.10 with ops_uuid=180e1afb-14dc-4abc-9333-c6f3ce94b05e, pending_node_ops={}, the node ops is unknown
```

That step had to throw an exception, because the removenode procedure was aborted. The code is:
```cpp
                // Step 6: Finish
                req.cmd = node_ops_cmd::removenode_done;
                parallel_for_each(nodes, [&ss, &req, uuid] (const gms::inet_address& node) {
                    return ss._messaging.local().send_node_ops_cmd(netw::msg_addr(node), req).then([uuid, node] (node_ops_cmd_response resp) {
                        slogger.debug("removenode[{}]: Got done response from node={}", uuid, node);
                        return make_ready_future<>();
                    });
                }).get();

                slogger.info("removenode[{}]: removing node {} from group 0", uuid, endpoint);
                assert(ss._group0);
                ss._group0->remove_from_group0(endpoint).get();
                slogger.info("removenode[{}]: node {} removed from group 0", uuid, endpoint);

                slogger.info("removenode[{}]: Finished removenode operation, removing node={}, sync_nodes={}, ignore_nodes={}", uuid, endpoint, nodes, ignore_nodes);
            } catch (...) {
                // we need to revert the effect of prepare verb the removenode ops is failed
                req.cmd = node_ops_cmd::removenode_abort;
                parallel_for_each(nodes, [&ss, &req, &nodes_unknown_verb, &nodes_down, uuid] (const gms::inet_address& node) {
                    if (nodes_unknown_verb.contains(node) || nodes_down.contains(node)) {
                        // No need to revert previous prepare cmd for those who do not apply prepare cmd.
                        return make_ready_future<>();
                    }
                    return ss._messaging.local().send_node_ops_cmd(netw::msg_addr(node), req).then([uuid, node] (node_ops_cmd_response resp) {
                        slogger.debug("removenode[{}]: Got abort response from node={}", uuid, node);
                    });
                }).get();
                slogger.info("removenode[{}]: Aborted removenode operation, removing node={}, sync_nodes={}, ignore_nodes={}", uuid, endpoint, nodes, ignore_nodes);
                throw;
            }
```

We can see that the `removenode_abort` message is sent only if there's an exception. So there had to be an exception from `remove_from_group0`.

And now there's the funny thing:
the `removenode_abort` node_ops is bugged, because the nodes don't understand it :D cc @asias 

so there are two problems here:
1. for some reaosn, `remove_from_group0` has failed
2. `removenode_abort` doesn't work

**Comment by kbr-** [comment] 2022-10-05 10:32
It's sad that the exception is silenced by the `catch` clause...

**Comment by michoecho** [comment] 2022-10-05 10:35
@alecco The second failure does not have the "is already closed" error.

**Comment by michoecho** [comment] 2022-10-05 10:37
Though it does have others:
```
[2022-10-05T01:19:33.111Z] Traceback (most recent call last):
[2022-10-05T01:19:33.111Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/cluster.py", line 3727, in refresh_schema
[2022-10-05T01:19:33.111Z]     return self._refresh_schema(self._connection, force=force, **kwargs)
[2022-10-05T01:19:33.112Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/cluster.py", line 3751, in _refresh_schema
[2022-10-05T01:19:33.112Z]     self._cluster.metadata.refresh(connection, self._timeout, fetch_size=self._schema_meta_page_size, **kwargs)
[2022-10-05T01:19:33.112Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/metadata.py", line 149, in refresh
[2022-10-05T01:19:33.112Z]     meta = parse_method(self.keyspaces, **kwargs)
[2022-10-05T01:19:33.112Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/metadata.py", line 2585, in get_table
[2022-10-05T01:19:33.112Z]     table_result = self._handle_results(cf_success, cf_result, query_msg=cf_query)
[2022-10-05T01:19:33.112Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/metadata.py", line 1972, in _handle_results
[2022-10-05T01:19:33.112Z]     raise result
[2022-10-05T01:19:33.112Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/cluster.py", line 4016, in wait_for_schema_agreement
[2022-10-05T01:19:33.112Z]     peers_result, local_result = connection.wait_for_responses(
[2022-10-05T01:19:33.112Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/connection.py", line 1124, in wait_for_responses
[2022-10-05T01:19:33.112Z]     return waiter.deliver(timeout)
[2022-10-05T01:19:33.112Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/connection.py", line 1635, in deliver
[2022-10-05T01:19:33.112Z]     raise self.error
[2022-10-05T01:19:33.112Z] cassandra.connection.ConnectionShutdown: Connection to 127.132.128.7:9042 was closed
```

**Comment by kbr-** [comment] 2022-10-05 10:37
Those Python driver exceptions are perfectly normal.

**Comment by kbr-** [comment] 2022-10-05 10:42
>  the removenode_abort node_ops is bugged, because the nodes don't understand it :D ("the node ops is unknown") cc @asias

I know why this happens.

The removenode procedure starts by contacting every node in the cluster (except the removed one) and giving them an UUID for the operation, which they save in internal `_node_ops` data structure.

At the end it sends a `removenode_done` message:
```cpp
                // Step 6: Finish
                req.cmd = node_ops_cmd::removenode_done;
                parallel_for_each(nodes, [&ss, &req, uuid] (const gms::inet_address& node) {
                    return ss._messaging.local().send_node_ops_cmd(netw::msg_addr(node), req).then([uuid, node] (node_ops_cmd_response resp) {
                        slogger.debug("removenode[{}]: Got done response from node={}", uuid, node);
                        return make_ready_future<>();
                    });
                }).get();
```
this clears the `_node_ops` entry.

The `remove_from_group0` step happens **after** the clearing step. If it throws an exception, the handler will try to send a `removeonde_abort` message with the operation's UUID, but the other nodes no longer have it - they cleared it with the `removenode_done` message.

cc @kostja 

So we should do either:
- move the `remove_from_group0` step before the Finish step,
- or move it outside the `catch` clause and handle failures differently there.

That's one bug, but we still don't know why `remove_from_group0` failed in the first place.

**Comment by kbr-** [comment] 2022-10-05 10:47
@gusev-p do you know what the cause of `removenode` failing might be?

**Comment by kbr-** [comment] 2022-10-05 10:59
@gusev-p I'm guessing it may be caused by what you describe and fix in this PR: https://github.com/scylladb/scylladb/pull/11691
We should create issues for these things.

**Comment by gusev-p** [comment] 2022-10-05 11:08
> @gusev-p I'm guessing it may be caused by what you describe and fix in this PR: #11691
> We should create issues for these things.

It definitely is.

How issues would help here? I mentioned this issue and [another one](https://github.com/scylladb/scylladb/pull/11704) on the daily.

**Comment by kbr-** [comment] 2022-10-05 11:21
> How issues would help here? I mentioned this issue and https://github.com/scylladb/scylladb/pull/11704 on the daily.

They make it easier to find known problems for anyone - if I encounter a problem with removenode I can type removenode into issues search and maybe I'll save some time. Not everybody working on Scylla attends our team dailies, but everybody can be affected by the issues we find. And even me who attends the dailies gets lost because too many things are happening at once, I can't keep everything in my head.

**Comment by gusev-p** [comment] 2022-10-05 11:52
> They make it easier to find known problems for anyone - if I encounter a problem with removenode I can type removenode into issues search and maybe I'll save some time.

It [shows PRs](https://github.com/scylladb/scylladb/issues?q=removenode) as well.

There is already a lot of auxiliary "paper" work to be done for every code change (convoluted github workflow/PRs, commit comments, comments on daily chat etc), let's try to effectively use what we already have.

**Comment by kbr-** [comment] 2022-10-05 12:08
> It [shows PRs](https://github.com/scylladb/scylladb/issues?q=removenode) as well.

OK, good to know. But that only works for issues which already have fixes posted, and what about issues that someone knows about but didn't post a fix for yet? And there is no guarantee that the person is actually working on a fix, if they don't it's likely they'll forget. Even if they do, someone else might encounter the issue in the meantime - it will save them a lot of time if they have a way to learn that the issue exists and is already being worked on.

Also, as I said, backports tracking is done through issues. Maybe it could be done through PRs instead. Although probably not, because we still allow sending patchsets through mailing list. cc @avikivity 

If you want to change the processes we follow, I suggest you send an email to rnd-internal so we can discuss alternatives. Until now the process we followed was: if there's a known problem, we create an issue on GitHub, and PRs / ML patchsets are fixing those issues.

**Comment by kbr-** [comment] 2022-10-05 13:41
@gusev-p 
> It definitely is.

But now that I think of it - the node we're removing was stopped gracefully. And we know that at least the gossiper has noticed that it is DOWN (otherwise removenode would fail earlier). So I think it's very likely that Raft also noticed it. So it's very unlikely that the dead node is still considered the leader. So `remove_from_group0` shouldn't have attempted to RPC the dead node.

**Comment by gusev-p** [comment] 2022-10-05 13:48
> @gusev-p
> 
> > It definitely is.
> 
> But now that I think of it - the node we're removing was stopped gracefully. And we know that at least the gossiper has noticed that it is DOWN (otherwise removenode would fail earlier). So I think it's very likely that Raft also noticed it. So it's very unlikely that the dead node is still considered the leader. So `remove_from_group0` shouldn't have attempted to RPC the dead node.

Why don't just merge [the patch](https://github.com/scylladb/scylladb/pull/11691) and see if the problem goes away?

**Comment by denesb** [comment] 2022-10-13 04:18
Seen again in https://jenkins.scylladb.com/job/scylla-master/job/next/5343/.

**Comment by alecco** [comment] 2022-10-13 07:54
> Seen again in https://jenkins.scylladb.com/job/scylla-master/job/next/5343/.

https://jenkins.scylladb.com/job/scylla-master/job/next/5343/artifact/testlog/x86_64/debug/test_topology.7242.log

> 2022-10-12 21:39:53 DEBUG ManagerClient added 127.109.102.80
> 2022-10-12 21:39:53 DEBUG ManagerClient decommission node 127.109.102.90
...
> RuntimeError: status code: 500, body text: Error decommissioning 127.109.102.90: status code: 500, body text: {"message": "std::runtime_error (decommission[9ad946d9-5c7c-4ca6-9291-00c386a353e5]: Nodes={127.109.102.80} needed for decommission operation are down. It is highly recommended to fix the down nodes and try again.)", "code": 500}, resource http://127.109.102.90:10000/storage_service/decommission params None

```
async def test_decommission_node_add_column(manager, random_tables):
    """Add a node, remove an original node, add a column"""
    servers = await manager.running_servers()
    table = await random_tables.add_table(ncolumns=5)
    await manager.server_add()                                                  #  <--- this is 127.109.102.80
    await manager.decommission_node(servers[1])             # Decommission [1]  <--- this is 127.109.102.90
```

For some reason new server `127.109.102.80` is up but didn't want data or something.

@kbr-  do you know what could this be or how can we prevent it?

**Comment by gusev-p** [comment] 2022-10-13 08:06
> > Seen again in https://jenkins.scylladb.com/job/scylla-master/job/next/5343/.
> 
> https://jenkins.scylladb.com/job/scylla-master/job/next/5343/artifact/testlog/x86_64/debug/test_topology.7242.log
> 
> > 2022-10-12 21:39:53 DEBUG ManagerClient added 127.109.102.80
> > 2022-10-12 21:39:53 DEBUG ManagerClient decommission node 127.109.102.90
> > ...
> > RuntimeError: status code: 500, body text: Error decommissioning 127.109.102.90: status code: 500, body text: {"message": "std::runtime_error (decommission[9ad946d9-5c7c-4ca6-9291-00c386a353e5]: Nodes={127.109.102.80} needed for decommission operation are down. It is highly recommended to fix the down nodes and try again.)", "code": 500}, resource http://127.109.102.90:10000/storage_service/decommission params None
> 
> ```
> async def test_decommission_node_add_column(manager, random_tables):
>     """Add a node, remove an original node, add a column"""
>     servers = await manager.running_servers()
>     table = await random_tables.add_table(ncolumns=5)
>     await manager.server_add()                                                  #  <--- this is 127.109.102.80
>     await manager.decommission_node(servers[1])             # Decommission [1]  <--- this is 127.109.102.90
> ```
> 
> For some reason new server `127.109.102.80` is up but didn't want data or something.
> 
> @kbr- do you know what could this be or how can we prevent it?

Perhaps we should wait until `127.109.102.80` becomes active from the point of view of the node on which decomission will be perfromed (`127.109.102.90` ?). We can query the active nodes [through this method](https://github.com/scylladb/scylladb/blob/master/api/api-doc/gossiper.json#L30).

**Comment by kbr-** [comment] 2022-10-13 09:19
> For some reason new server 127.109.102.80 is up but didn't want data or something.

Deducing from the error message, not every node thinks that `80` is up:
```
 Nodes={127.109.102.80} needed for decommission operation are down. 
```
On the other hand, looking at the logs of `90` (which tried to do the decommission):
```
INFO  2022-10-12 21:39:24,384 [shard 0] gossip - InetAddress 127.109.102.80 is now UP, status = UNKNOWN
```
It does consider it UP. But it doesn't consider it NORMAL. Perhaps the status update didn't arrive to `90` yet - `80` has just finished bootstrapping. And perhaps the error message is misleading: "down" doesn't mean DOWN, in this case it means "not NORMAL"?
We need to look at the code to understand it.

**Comment by kbr-** [comment] 2022-10-13 09:19
> Seen again in https://jenkins.scylladb.com/job/scylla-master/job/next/5343/.

Fortunately, different test.

**Comment by kbr-** [comment] 2022-10-13 09:21
But it's weird that this test started failing now.
Regression?

**Comment by kbr-** [comment] 2022-10-13 09:59
> But it's weird that this test started failing now.
> Regression?

I have an idea:
in my recently merged "raft upgrade tests" PR, I changed the `cql_is_up` function used by the framework; it no longer creates and drops keyspaces, now it does a simple select from system.local. This shifts earlier the moment the framework considers a node to have finished bootstrap. If this problem is caused by other nodes not noticing that the bootstrapping node entered NORMAL status yet, then my change may have made this race more likely.

**Comment by kbr-** [comment] 2022-10-13 10:48
Nope, it seems something else is happening.

This message:
```
 Nodes={127.109.102.80} needed for decommission operation are down. 
```
happens when some node fails to answer the `node_ops_cmd::decommission_prepare` message:
```cpp
            std::unordered_set<gms::inet_address> nodes_down;
            auto req = node_ops_cmd_request{node_ops_cmd::decommission_prepare, uuid, ignore_nodes, leaving_nodes, {}};
            try {
                parallel_for_each(nodes, [&ss, &req, &nodes_unknown_verb, &nodes_down, uuid] (const gms::inet_address& node) {
                    return ss._messaging.local().send_node_ops_cmd(netw::msg_addr(node), req).then([uuid, node] (node_ops_cmd_response resp) {
                        slogger.debug("decommission[{}]: Got prepare response from node={}", uuid, node);
                    }).handle_exception_type([&nodes_unknown_verb, node, uuid] (seastar::rpc::unknown_verb_error&) {
                        slogger.warn("decommission[{}]: Node {} does not support decommission verb", uuid, node);
                        nodes_unknown_verb.emplace(node);
                    }).handle_exception_type([&nodes_down, node, uuid] (seastar::rpc::closed_error&) {
                        slogger.warn("decommission[{}]: Node {} is down for node_ops_cmd verb", uuid, node);
                        nodes_down.emplace(node);
                    });
                }).get();
                if (!nodes_unknown_verb.empty()) {
                    auto msg = format("decommission[{}]: Nodes={} do not support decommission verb. Please upgrade your cluster and run decommission again.", uuid, nodes_unknown_verb);
                    slogger.warn("{}", msg);
                    throw std::runtime_error(msg);
                }
                if (!nodes_down.empty()) {
                    auto msg = format("decommission[{}]: Nodes={} needed for decommission operation are down. It is highly recommended to fix the down nodes and try again.", uuid, nodes_down);
                    slogger.warn("{}", msg);
                    throw std::runtime_error(msg);
                }
```

So it means that `90` got `seastar::rpc::closed_error&` exception when it sent the message to `80`. Indeed we can see earlier in `90`'s logs:
```
WARN  2022-10-12 21:39:53,629 [shard 0] storage_service - decommission[9ad946d9-5c7c-4ca6-9291-00c386a353e5]: Node 127.109.102.80 is down for node_ops_cmd verb
```

However, looking at `80`'s logs... it did receive the message:
```
INFO  2022-10-12 21:39:53,475 [shard 0] storage_service - decommission[9ad946d9-5c7c-4ca6-9291-00c386a353e5]: Added node=127.109.102.90 as leaving node, coordinator=127.109.102.90
```
this log is printed when a node handles `decommission_prepare` message.

So the connection got closed for some reason after the RPC reached the destination but before it got answered? WHY?

**Comment by kbr-** [comment] 2022-10-13 12:32
I'm trying to reproduce this problem locally and I haven't managed to reproduce this exactly yet, but something similar: streaming started, but then randomly at some point there was an RPC error. In this run, node `54` was decommissioning and there was another node `63` in the cluster to which it streamed data. Then, on node `54`:
```
INFO  2022-10-13 14:04:13,696 [shard 0] stream_session - [Stream #2761bf71-4aef-11ed-b04e-2dc5d00cb525] Start sending ks=system_auth, cf=roles, estimated_partitions=128, with new rpc streaming
WARN  2022-10-13 14:04:13,699 [shard 0] stream_session - [Stream #2761bf71-4aef-11ed-b04e-2dc5d00cb525] stream_transfer_task: Fail to send to 127.175.208.63:0: seastar::rpc::stream_closed (rpc stream was closed by peer)
WARN  2022-10-13 14:04:13,699 [shard 0] stream_session - [Stream #2761bf71-4aef-11ed-b04e-2dc5d00cb525] Failed to send: seastar::rpc::stream_closed (rpc stream was closed by peer)
WARN  2022-10-13 14:04:13,699 [shard 0] stream_session - [Stream #2761bf71-4aef-11ed-b04e-2dc5d00cb525] Streaming error occurred, peer=127.175.208.63
WARN  2022-10-13 14:04:13,699 [shard 0] stream_session - [Stream #2761bf71-4aef-11ed-b04e-2dc5d00cb525] Streaming plan for Unbootstrap-system_auth-index-1 failed, peers={127.175.208.63}, tx=0 KiB, 8.79 KiB/s, rx=0 KiB, 0.00 KiB/s
WARN  2022-10-13 14:04:13,699 [shard 0] range_streamer - Unbootstrap with 127.175.208.63 for keyspace=system_auth failed, took 0.028812828 seconds: streaming::stream_exception (Stream failed)
WARN  2022-10-13 14:04:13,699 [shard 0] range_streamer - Unbootstrap failed, took 0 seconds, nr_ranges_remaining=95
WARN  2022-10-13 14:04:13,699 [shard 0] storage_service - stream_ranges failed: streaming::stream_exception (Stream failed)
WARN  2022-10-13 14:04:13,699 [shard 0] storage_service - unbootstrap fails to stream : streaming::stream_exception (Stream failed)
```

on node `63`:
```
INFO  2022-10-13 14:04:13,668 [shard 0] storage_service - decommission[7e09c51d-e184-4f55-952e-993324eafe43]: Added node=127.175.208.54 as leaving node, coordinator=127.175.208.54
INFO  2022-10-13 14:04:13,671 [shard 0] stream_session - [Stream #27619861-4aef-11ed-b04e-2dc5d00cb525] Executing streaming plan for Unbootstrap-system_auth-index-0 with peers=127.175.208.54, slave
INFO  2022-10-13 14:04:13,671 [shard 0] stream_session - [Stream #27619861-4aef-11ed-b04e-2dc5d00cb525] Streaming plan for Unbootstrap-system_auth-index-0 succeeded, peers={127.175.208.54}, tx=0 KiB, 0.00 KiB/s, rx=0 KiB, 0.00 KiB/s
INFO  2022-10-13 14:04:13,671 [shard 0] stream_session - [Stream #2761bf71-4aef-11ed-b04e-2dc5d00cb525] Executing streaming plan for Unbootstrap-system_auth-index-1 with peers=127.175.208.54, slave
INFO  2022-10-13 14:04:13,699 [shard 0] stream_session - [Stream #2761bf71-4aef-11ed-b04e-2dc5d00cb525] Write to sstable for ks=system_auth, cf=roles, estimated_partitions=128, received_partitions=1
INFO  2022-10-13 14:04:13,699 [shard 0] stream_session - [Stream #2761bf71-4aef-11ed-b04e-2dc5d00cb525] Received failed complete message, peer=127.175.208.54
WARN  2022-10-13 14:04:13,699 [shard 0] stream_session - [Stream #2761bf71-4aef-11ed-b04e-2dc5d00cb525] Streaming plan for Unbootstrap-system_auth-index-1 failed, peers={127.175.208.54}, tx=0 KiB, 0.00 KiB/s, rx=0 KiB, 8.69 KiB/s
INFO  2022-10-13 14:04:14,670 [shard 0] storage_service - decommission[7e09c51d-e184-4f55-952e-993324eafe43]: Removed node=127.175.208.54 as leaving node, coordinator=127.175.208.54

```

so apparently it did start streaming for this range:
```
INFO  2022-10-13 14:04:13,671 [shard 0] stream_session - [Stream #2761bf71-4aef-11ed-b04e-2dc5d00cb525] Executing streaming plan for Unbootstrap-system_auth-index-1 with peers=127.175.208.54, slave
```
but then the connection got closed. It's similar to the Jenkins failure.

@gleb-cloudius , do you have any idea what might cause these RPC failures? It looks weird, these nodes are running on the same machine, they manage to send some RPCs to each other but then one of the RPC fails to receive a response because a connection gets closed... And does `closed_error` actually mean that the TCP connection got closed, or can it also mean something else?

@asias , maybe we should make these operations more resilient to transient RPC errors? It's very non-robust now, a simple network hiccup causes the entire decommission operation to fail...

**Comment by kbr-** [comment] 2022-10-13 13:01
I wish `stream_closed` and `closed_error` gave a non-zero amount of details about what happened. It seems that these exceptions can be returned in a number of different error situations, but they don't say what the error was.

**Comment by kbr-** [comment] 2022-10-13 15:03
For some reason, while we're handling NORMAL status for a given node (`storage_service::handle_state_normal`), connections to the node are dropped. If we try to send the `node_ops` RPC *after* `handle_state_normal` finishes, it's fine: we will re-establish the connection (in `get_rpc_client`). However, the dropping of connections may race with the sending of the RPC. To send the node_ops RPC we may choose the connection which is going to be dropped in the next moment; the RPC will fail.

I must dig further to understand why the connection dropping happens at all.

**Comment by kbr-** [comment] 2022-10-13 15:15
Well, in any case, decommission should probably wait until all nodes are in NORMAL state. Not only that - it must wait until `handle_state_normal` finishes - there may be no mechanism implemented for that yet

**Comment by kbr-** [comment] 2022-10-13 15:19
But there's just so many things that could be improved:
- Some place in the code drops all connections, causing all in-flight RPCs to fail.
- RPCs are failing and not retrying. This fails a big administrative operation like `decommission`.
- Decommission can start in weird states where not every node is up/normal

**Comment by kbr-** [comment] 2022-10-13 15:22
@asias in 58c65954b8cedc498678e97027885aea1cad24f3 you made decommission fail if some nodes are dead.
Perhaps we should improve this and require something stronger - that every other node has been "fully joined"? (`handle_state_normal` finished)

**Comment by kbr-** [comment] 2022-10-13 15:29
Closing this issue because it's about another test.
Opened another where I described the root cause: https://github.com/scylladb/scylladb/issues/11780

**Closed by kbr-** 2022-10-13 15:29 UTC
