### ISSUE TITLE
raft: server error when table is dropped

### ISSUE THREAD

**Issue by Deexie** [scylladb/scylladb#13131] opened 2023-03-09 14:58 UTC
With scylla version 25cf325 test https://github.com/scylladb/scylladb/pull/13124, which drops tables during user requested repair and checks whether repair finishes successfully, fails with:

```
cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.131.80.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Raft instance is stopped, reason: "background error, std::_Nested_exception<raft::state_machine_error> (State machine error at raft/raft.hh:299): data_dictionary::no_such_column_family (Can't find a column family with UUID d8a1f3a0-bdc6-11ed-babe-e3f57a7964f0)"">})
```

The error comes from `raft::server_impl::applier_fiber()` in `raft/server.cc`:

https://github.com/scylladb/scylladb/blob/25cf3256743d98f1dd34ef0656ee7cc974f87249/raft/server.cc#L1217

https://github.com/scylladb/scylladb/blob/25cf3256743d98f1dd34ef0656ee7cc974f87249/raft/server.cc#L1345-L1351

**Comment by kostja** [comment] 2023-04-18 14:27
Isn't it a duplicate of https://github.com/scylladb/scylladb/issues/12863 ?

**Comment by margdoc** [comment] 2023-04-21 12:57
The problem is the usage of `replica::database::drop_table_on_all_shards` here (from https://github.com/scylladb/scylladb/pull/13124):
https://github.com/scylladb/scylladb/blob/5fe49a5023bb376ce6bc121c6537fe9543f02275/repair/repair.cc#L1084-L1088


When it is replaced by stopping the repair task for 5 seconds and the table is dropped by cql in the [test](https://github.com/scylladb/scylladb/pull/13124/commits/026f0974746580c87b16175b01642cb05e833c62), the test works (https://github.com/scylladb/scylladb/commit/25cf3256743d98f1dd34ef0656ee7cc974f87249 fails this test, but the current version on master passes). See commit https://github.com/margdoc/scylla/commit/37bd58e4894077f57aae5ef2d784168227f58b37.

I will investigate why `drop_table_on_all_shards` causes problems and I will propose a fix to https://github.com/scylladb/scylladb/pull/13124.

**Comment by margdoc** [comment] 2023-04-26 09:15
Some observations:
* The problem also occurs if the raft is disabled.
* After restarting crashed node, schema changes work correctly.

**Comment by gleb-cloudius** [comment] 2023-05-01 12:45
Ad far as I can tell you modify raft state machine outside of raft in your test. This cannot end well.

**Comment by kostja** [comment] 2023-05-02 08:56
Please do not open issues on unmerged code. It was unobvious from the report that the master branch is not having a failure. You should not modify the Raft state machine outside Raft. Starting from 5.2, schema state is part of Raft state machine. @gleb-cloudius will comment on the original pull request.

**Closed by kostja** 2023-05-02 08:56 UTC
Labels: raft
