### ISSUE TITLE
Unable to change RF more than once unless I specify the datacenter

### ISSUE THREAD

**Issue by igorribeiroduarte** [scylladb/scylladb#12543] opened 2023-01-17 13:33 UTC
Scylla version: `5.1.0-0.20221127.69e8fb997c7b`

The first time I try to change the replication factor for a keyspace using the keyword `replication_factor`, it works properly:
```
cqlsh> desc system_auth
CREATE KEYSPACE system_auth WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

cqlsh> ALTER KEYSPACE system_auth WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 3};

cqlsh> desc system_auth
CREATE KEYSPACE system_auth WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '3'}  AND durable_writes = true;
```

Now if I try to change it again for a different value with the same command, it doesn't:
```
cqlsh> ALTER KEYSPACE system_auth WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 2};
cqlsh> desc system_auth

CREATE KEYSPACE system_auth WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '3'}  AND durable_writes = true;
```
But if instead of using `replication_factor` I specify the datacenter, then it works:
```
cqlsh> ALTER KEYSPACE system_auth WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': 2};
cqlsh> desc system_auth

CREATE KEYSPACE system_auth WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '2'}  AND durable_writes = true;
```

This same problem doesn't happen for `SimpleStrategy`

**Comment by mykaul** [comment] 2023-01-17 13:43
Perhaps related to https://github.com/scylladb/scylla-enterprise/commit/9bf4fe669f1938cbd812e53092107c370f758b82 ?

**Comment by DoronArazii** [comment] 2023-01-18 12:13
@kbr- can you please have a look

**Comment by avikivity** [comment] 2023-01-18 14:22
IIRC it was intentional, I don't quite remember the reason. @nyh?

**Comment by mykaul** [comment] 2023-03-30 14:51
@igorribeiroduarte - does it happen with other tables, or just system_auth?
@eliransin has somewhere plans to move system_auth to Everywhere strategy, I assume it'll be handled with it (I hope).

**Comment by bhalevy** [comment] 2024-03-05 16:45
> IIRC it was intentional, I don't quite remember the reason. @nyh?

See https://opensource.docs.scylladb.com/stable/cql/ddl.html#networktopologystrategy
```
Note that when ALTER ing keyspaces and supplying replication_factor, auto-expansion will only add new datacenters for safety, it will not alter existing datacenters or remove any even if they are no longer in the cluster.
```

And (unresolved) discussion in https://github.com/scylladb/scylladb/pull/16115

**Comment by nyh** [comment] 2024-03-05 17:36
Indeed, this is how the strangely-named "auto-expand" option works, supposedly the same as in Cassandra (https://github.com/scylladb/scylladb/issues/4210), and @bhalevy posted above some useful links.

I have a vague recollection that we discussed in the past printing a warning when the "replication_factor" option ended up being ignored for some - or in this case all - of the data centers. @ptrsmrn maybe you remember if we have an issue about that? I couldn't find one.

@igorribeiroduarte if you're still looking for a solution a year later, you can specify the replication_factor separately for each DC, and then it won't be ignored. It is just the single-"replication_factor" option (so-called "auto expand") which has this strange behavior.

**Comment by ptrsmrn** [comment] 2024-03-05 20:08
> I have a vague recollection that we discussed in the past printing a warning when the "replication_factor" option ended up being ignored for some - or in this case all - of the data centers. @ptrsmrn maybe you remember if we have an issue about that? I couldn't find one.

@nyh I'm guessing you're thinking about https://github.com/scylladb/scylladb/issues/8881

**Comment by nyh** [comment] 2024-03-05 22:26
Yes, thanks @ptrsmrn I lost that issue ;-) I think this issue indeed a duplicate of #8881 so closing it as such (reopen the issue if someone disagrees it's a duplicate).

**Closed by nyh** 2024-03-05 22:26 UTC
