### ISSUE TITLE
`nodetool help resetlocalschema` isn't working as expected 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#16669] opened 2024-01-07 10:11 UTC
seems since we started using the `scylla nodetool` command, this command is failing and not implemented, nor falling back to java based nodetool as it should: 
```
2024-01-06 22:29:44.841: (DisruptionEvent Severity.ERROR) period_type=end event_id=3473f0e9-8693-4194-9969-7e53e1630d98 duration=2s: nemesis_name=Resetlocalschema target_node=Node longevity-large-partitions-200k-pks-db-node-16303bf6-0-4 [34.74.115.56 | 10.142.0.233] (seed: True) errors=Encountered a bad command exit code!
Command: '/usr/bin/nodetool  help resetlocalschema'
Exit code: 1
Stdout:
Stderr:
error processing arguments: unknown command resetlocalschema
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5072, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 832, in disrupt_resetlocalschema
result = self.target_node.run_nodetool(sub_cmd='help', args='resetlocalschema')
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2515, in run_nodetool
self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: '/usr/bin/nodetool  help resetlocalschema'
Exit code: 1
Stdout:
Stderr:
error processing arguments: unknown command resetlocalschema
```

**Comment by fruch** [comment] 2024-01-07 10:34
code is using the help command, but the help is going only to one of the tools, and not both.
so any logic like that in tests might be failing, since you can see the help of the old tool:
```python
    def disrupt_resetlocalschema(self):  # pylint: disable=invalid-name
        result = self.target_node.run_nodetool(sub_cmd='help', args='resetlocalschema')
        if 'Unknown command resetlocalschema' in result.stdout:
            raise UnsupportedNemesis("nodetool doesn't support resetlocalschema")

        rlocal_schema_res = self.target_node.follow_system_log(patterns=["schema_tables - Schema version changed to"])
        self.target_node.run_nodetool("resetlocalschema")
```

**Comment by denesb** [comment] 2024-03-13 12:22
Duplicate of https://github.com/scylladb/scylladb/issues/16622.

**Comment by denesb** [comment] 2024-04-19 12:43
This should be fixed now, with the native-nodetool being feature-complete.

**Closed by denesb** 2024-04-19 12:43 UTC
Labels: area/nodetool
