### ISSUE TITLE
When upgrading one node of the cluster, the CPU reaches 100% and there are YcsbStressEvent errors

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylladb#7161] opened 2020-09-02 16:07 UTC
*Installation details*
Scylla version (or git commit hash): https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/centos/branch-4.2/2020-08-25T19:05:23Z/scylla.repo)
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI):

There is an old test called "test_rolling_upgrade".
I am trying to upgrade the test and checking Alternator tables while upgrading each node of the cluster.
I notice, at the time the node upgrade, the CPU reaches 100%.
At the same time, I get YcsbStressEvent errors

Regular run without Alternator stress commands:
![image](https://user-images.githubusercontent.com/11705430/92007708-f2811800-ed4e-11ea-8af4-5ce18af68993.png)

Run with C-S and YCSB stress commands:
![image (1)](https://user-images.githubusercontent.com/11705430/92007712-f3b24500-ed4e-11ea-9b63-5cebe36ee652.png)

In both runs, the CPU reaches 100.
But, I notice that YCSB is more affected than C-S stress.

@nyh 
What do you think?

### Errors
```
ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.AmazonServiceException: Internal server error: exceptions::mutation_write_timeout_exception (Operation timed out for alternator_usertable.usertable - received only 1 responses from 2 CL=LOCAL_SERIAL.) (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: Internal Server Error; Request ID: null)

17:13:36  < t:2020-09-01 14:13:38,827 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 1257248 [Thread-27] ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.AmazonServiceException: Internal server error: exceptions::mutation_write_timeout_exception (Operation timed out for alternator_usertable.usertable - received only 0 responses from 2 CL=LOCAL_SERIAL.) (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: Internal Server Error; Request ID: null)


17:42:03  < t:2020-09-01 14:41:58,141 f:sct_events.py   l:906  c:sdcm.sct_events      p:INFO  > 177738 [Thread-34] ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.AmazonServiceException: Internal server error: exceptions::read_timeout_exception (Operation timed out for alternator_usertable.usertable - received only 1 responses from 2 CL=LOCAL_QUORUM.) (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: Internal Server Error; Request ID: null)

```

### Run Details
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                           Log links for testrun with test id 21f2d8f5-9612-4ff5-90d0-48a4eb3f0ab6                                            |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                         |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
| 20200901_171426 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/21f2d8f5-9612-4ff5-90d0-48a4eb3f0ab6/20200901_171426/db-cluster-21f2d8f5.zip  |
| 20200901_171426 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/21f2d8f5-9612-4ff5-90d0-48a4eb3f0ab6/20200901_171426/loader-set-21f2d8f5.zip  |
| 20200901_171426 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/21f2d8f5-9612-4ff5-90d0-48a4eb3f0ab6/20200901_171426/monitor-set-21f2d8f5.zip |
| 20200901_171426 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/21f2d8f5-9612-4ff5-90d0-48a4eb3f0ab6/20200901_171426/sct-runner-21f2d8f5.zip  |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by nyh** [comment] 2020-09-06 10:33
Unfortunately, I don't understand the setup of this issue at all so I don't know how to help. I would need you to explain to me the problem without assuming I know anything about your setup, and if possible help me zeroing in on what *really* is the problem in this complex setup:

Do I understand correctly, before the rolling upgrade, the workload was calibrated to drive the servers at some fixed CPU load which is < 100% (apparently 25%), and during the rolling upgrade you reboot and upgrade some of the nodes (which?) and CPU load goes to 100%.

My first question is whether this is really related to the **upgrade** or just the fact that nodes went down? If you reboot nodes *without* really upgrading them (this will be a trivial change to your test), do you see a similar problem? It's important to know if this is really an upgrade bug, or a nodes-going-down bug.

My second question is whether this is really an Alternator problem, or an LWT problem. To tell these two possibilities apart you have two options:
1. Instead of adding an Alternator load to your test, you could add an LWT load, and see if the same problem reproduces.
2. You can run the Alternator load without LWT (`--alternator-write-isolation=only_rmw_uses_lwt`).

If this is an LWT issue, not an Alternator issues (this is what I suspect...), this issue should be relabeled (LWT instead of Alternator) and probably reassigned.

**Comment by Orenef11** [comment] 2020-09-07 15:51
@nyh 
I am very sorry I missed many details on the description of the problem.
At the same time, you understood the problem I was trying to describe.
I have no answers to the questions you asked, I will have to check them out.
Therefore, I will try to check what you have suggested and got you an answer back in the next two days.

**Comment by fruch** [comment] 2020-09-08 08:54
> My first question is whether this is really related to the **upgrade** or just the fact that nodes went down? If you reboot nodes _without_ really upgrading them (this will be a trivial change to your test), do you see a similar problem? It's important to know if this is really an upgrade bug, or a nodes-going-down bug.
> 

We are doing a daily runs with all of our other longevity and we didn't noticed such issue. so I wouldn't think it have todo with mere reboots

> My second question is whether this is really an Alternator problem, or an LWT problem. To tell these two possibilities apart you have two options:
> 
> 1. Instead of adding an Alternator load to your test, you could add an LWT load, and see if the same problem reproduces.
> 2. You can run the Alternator load without LWT (`--alternator-write-isolation=only_rmw_uses_lwt`).

I think that option 2 here would be the easiest to test, (option one might be important, but in the context of testing LWT) 

@Orenef11 try reproducing with `only_rmw_uses_lwt`

**Comment by Orenef11** [comment] 2020-09-08 18:44
> > My first question is whether this is really related to the **upgrade** or just the fact that nodes went down? If you reboot nodes _without_ really upgrading them (this will be a trivial change to your test), do you see a similar problem? It's important to know if this is really an upgrade bug, or a nodes-going-down bug.
> 
> We are doing a daily runs with all of our other longevity and we didn't noticed such issue. so I wouldn't think it have todo with mere reboots, also we have seem more then one places the LWT introduces strict timeouts, which are visible to clients when using alternator as error, that in regular CQL would be just longer response times.
> 
> > My second question is whether this is really an Alternator problem, or an LWT problem. To tell these two possibilities apart you have two options:
> > 
> > 1. Instead of adding an Alternator load to your test, you could add an LWT load, and see if the same problem reproduces.
> > 2. You can run the Alternator load without LWT (`--alternator-write-isolation=only_rmw_uses_lwt`).
> 
> I think that option 2 here would be the easiest to test, (option one might be important, but in the context of testing LWT)
> 
> @Orenef11 try reproducing with `only_rmw_uses_lwt` to prove it LWT timeouts that are responsibly here.

After removing LWT, I did not get any YCSB errors.
At the same time, the CPU reaches to 100% while the node is being upgraded.

![image](https://user-images.githubusercontent.com/11705430/92515319-15fb0580-f21c-11ea-860d-02f92816ad7d.png)

**Comment by nyh** [comment] 2020-09-08 18:50
@Orenef11 what do I see in this graph? When does the upgrade happen, and where do I see there 100% CPU? I see the CPU load fluctuating all the time, I don't know how to make any sense of it.

Also, is "100% CPU" really bad? Is it really caused by the upgrade - or just the fact you just had the node down for presumably a couple of minutes (I don't know how much time it took...) so the other nodes were busier, AND, when the dead node came back, there were a lot of hints to be sent (was hinted-handoff enabled or disabled)?

I suggest you try the same run with a "do-nothing upgrade", i.e., "upgrade" version X to exactly the same version X. If you see exactly the same problems, you'll know upgrades have nothing to do with this problem, and it's just the issue of a node being down for some time. If you no longer have this problem, maybe the specific upgrade is really the problem. By the way, which version are you upgrading to which?

**Comment by Orenef11** [comment] 2020-09-09 06:42
@nyh 
There are 6 upgrades during the test.
Every rectangle you see in the top graph is an upgrade.
In this run, I upgraded the cluster from 4.1 to 4.2.
I will try to upgrade the cluster to the same version and I check if it happens because of the upgrade.

**Comment by nyh** [comment] 2020-09-09 07:27
@Orenef11 I'm still trying to reverse engineer what your test is doing because nobody ever explained it to me :-)
1. By "an upgrade" you mean upgrading a single node at a time, and "6 upgrades" you mean you have 6 nodes and upgrading one node at a time?
2. I see many "rectangles" in the graph so I don't know what you are referring to. If you are referring to the short periods of 100% CPU usage? Can you please zoom in on one short period, and tell me how it corresponds to the time of the upgrade? In other words, do we see 100% CPU usage while the node was down? *after* it came up with the new version? When did the 100% CPU usage stop - did it resolve naturally (e.g., some backlog cleared up) or did it stop at the same time when other things happen? So we see 100% CPU usage on all nodes, on a specific node, or what?

And thanks in advance for running again with "fake" upgrades (upgrading from 4.1 to 4.1). I think it will be really helpful to understand if this problem (which I am still not sure is a problem) is actually related to the upgrade between 4.1 to 4.2 specifically, or something much more general that has to do with bringing node down for some time one at a time.

**Closed** 2022-11-18 15:30 UTC
Labels: Alternator
