### ISSUE TITLE
test_gossip_boot timeout after 60 seconds

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#20214] opened 2024-08-20 06:19 UTC
Seen in ci where the test failed 3 times consecutively on timeout.
For example:

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10987/artifact/testlog/x86_64/dev/topology_custom.test_gossip_boot.1.log
```
=================================== FAILURES ===================================
______________________________ test_gossip_boot.1 ______________________________

self = <test.pylib.manager_client.ManagerClient object at 0x7fb10dad5820>
replace_cfg = None, cmdline = None
config = {'error_injections_at_startup': ['gossiper_replicate_sleep'], 'force_gossip_topology_changes': True}
property_file = None, start = True, expected_error = None, seeds = None
timeout = 60

    async def server_add(self, replace_cfg: Optional[ReplaceConfig] = None,
                         cmdline: Optional[List[str]] = None,
                         config: Optional[dict[str, Any]] = None,
                         property_file: Optional[dict[str, Any]] = None,
                         start: bool = True,
                         expected_error: Optional[str] = None,
                         seeds: Optional[List[IPAddress]] = None,
                         timeout: Optional[float] = ScyllaServer.TOPOLOGY_TIMEOUT) -> ServerInfo:
        """Add a new server"""
        try:
            data = self._create_server_add_data(replace_cfg, cmdline, config, property_file, start, seeds, expected_error)
    
            # If we replace, we should wait until other nodes see the node being
            # replaced as dead because the replace operation can be rejected if
            # the node being replaced is considered alive. However, we sometimes
            # do not want to wait, for example, when we test that replace fails
            # as expected. Therefore, we make waiting optional and default.
            if replace_cfg and replace_cfg.wait_replaced_dead:
                replaced_ip = await self.get_host_ip(replace_cfg.replaced_id)
                await self.others_not_see_server(replaced_ip)
    
>           server_info = await self.client.put_json("/cluster/addserver", data, response_type="json",
                                                     timeout=timeout)

test/pylib/manager_client.py:329: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/pylib/rest_client.py:114: in put_json
    ret = await self._fetch("PUT", resource_uri, response_type = response_type, host = host,
test/pylib/rest_client.py:65: in _fetch
    async with request(method, uri,
/usr/lib64/python3.12/site-packages/aiohttp/client.py:1246: in __aenter__
    self._resp = await self._coro
/usr/lib64/python3.12/site-packages/aiohttp/client.py:608: in _request
    await resp.start(conn)
/usr/lib64/python3.12/site-packages/aiohttp/client_reqrep.py:971: in start
    with self._timer:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <aiohttp.helpers.TimerContext object at 0x7fb10d7c28a0>
exc_type = <class 'asyncio.exceptions.CancelledError'>
exc_val = CancelledError(), exc_tb = <traceback object at 0x7fb10d7ba840>

    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> Optional[bool]:
        if self._tasks:
            self._tasks.pop()
    
        if exc_type is asyncio.CancelledError and self._cancelled:
>           raise asyncio.TimeoutError from None
E           TimeoutError

/usr/lib64/python3.12/site-packages/aiohttp/helpers.py:735: TimeoutError

The above exception was the direct cause of the following exception:

manager = <test.pylib.manager_client.ManagerClient object at 0x7fb10dad5820>

    @pytest.mark.asyncio
    @skip_mode('release', 'error injections are not supported in release mode')
    async def test_gossip_boot(manager: ManagerClient):
        """
        Regression test for scylladb/scylladb#17493.
        """
    
        cfg = {'error_injections_at_startup': ['gossiper_replicate_sleep'],
               'force_gossip_topology_changes': True}
    
>       servers = [await manager.server_add(config=cfg, timeout=60) for _ in range(3)]

test/topology_custom/test_gossip_boot.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.pylib.manager_client.ManagerClient object at 0x7fb10dad5820>
replace_cfg = None, cmdline = None
config = {'error_injections_at_startup': ['gossiper_replicate_sleep'], 'force_gossip_topology_changes': True}
property_file = None, start = True, expected_error = None, seeds = None
timeout = 60

    async def server_add(self, replace_cfg: Optional[ReplaceConfig] = None,
                         cmdline: Optional[List[str]] = None,
                         config: Optional[dict[str, Any]] = None,
                         property_file: Optional[dict[str, Any]] = None,
                         start: bool = True,
                         expected_error: Optional[str] = None,
                         seeds: Optional[List[IPAddress]] = None,
                         timeout: Optional[float] = ScyllaServer.TOPOLOGY_TIMEOUT) -> ServerInfo:
        """Add a new server"""
        try:
            data = self._create_server_add_data(replace_cfg, cmdline, config, property_file, start, seeds, expected_error)
    
            # If we replace, we should wait until other nodes see the node being
            # replaced as dead because the replace operation can be rejected if
            # the node being replaced is considered alive. However, we sometimes
            # do not want to wait, for example, when we test that replace fails
            # as expected. Therefore, we make waiting optional and default.
            if replace_cfg and replace_cfg.wait_replaced_dead:
                replaced_ip = await self.get_host_ip(replace_cfg.replaced_id)
                await self.others_not_see_server(replaced_ip)
    
            server_info = await self.client.put_json("/cluster/addserver", data, response_type="json",
                                                     timeout=timeout)
        except Exception as exc:
>           raise Exception("Failed to add server") from exc
E           Exception: Failed to add server
```

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10987/artifact/testlog/x86_64/dev/failed_test/test_gossip_boot.1/test_py.log
```
21:10:24.846 INFO> [dev/topology_custom.test_gossip_boot.1] Cluster ScyllaCluster(name: 428a7e28-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2138, 127.242.182.45, d12a20f1-1831-4fe3-9f19-976eb1a55241), ScyllaServer(2149, 127.242.182.31, 21d796c0-2100-4d89-b0a9-9281eff21046), stopped: ) adding server...
21:10:24.847 INFO> [dev/topology_custom.test_gossip_boot.1] installing Scylla server in /scylladir/testlog/x86_64/dev/scylla-2169...
...
21:11:25.172 INFO> [dev/topology_custom.test_gossip_boot.1] [ScyllaClusterManager][Task-186169] http://api/cluster/all-servers
21:11:25.176 INFO>  [19/Aug/2024:20:11:25 +0200] "GET /cluster/all-servers HTTP/1.1" 200 246 "-" "Python/3.12 aiohttp/3.9.5"
21:11:25.179 INFO> [dev/topology_custom.test_gossip_boot.1] [ScyllaClusterManager][Task-186170] http://api/cluster/server/2138/get_log_filename
21:11:25.183 INFO>  [19/Aug/2024:20:11:25 +0200] "GET /cluster/server/2138/get_log_filename HTTP/1.1" 200 205 "-" "Python/3.12 aiohttp/3.9.5"
21:11:25.184 INFO> [dev/topology_custom.test_gossip_boot.1] [ScyllaClusterManager][Task-186171] http://api/cluster/server/2149/get_log_filename
21:11:25.185 INFO>  [19/Aug/2024:20:11:25 +0200] "GET /cluster/server/2149/get_log_filename HTTP/1.1" 200 205 "-" "Python/3.12 aiohttp/3.9.5"
```

But the server is not started at 21:10:24.847, as expected, but after the test already times out.

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10987/artifact/testlog/x86_64/dev/scylla-2169.log
```
WARN  2024-08-19 21:11:27,789 seastar - Could not read cgroups v2 file (memory.max).
INFO  2024-08-19 21:11:27,791 seastar - Reactor backend: linux-aio
INFO  2024-08-19 21:11:27,792 seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
INFO  2024-08-19 21:11:27,796 [shard 0:main] seastar - updated: blocked-reactor-notify-ms=36000000000
INFO  2024-08-19 21:11:27,796 [shard 1:main] seastar - updated: blocked-reactor-notify-ms=36000000000
INFO  2024-08-19 21:11:27,799 [shard 0:main] init - installing SIGHUP handler
INFO  2024-08-19 21:11:27,803 [shard 0:main] init - Scylla version 6.2.0~dev-0.20240819.3792f861d8c5 with build-id 97c9126ce990ffe19ab1176d14452b91b29f6be0 starting ...
```

It joins the cluster and starts successfully, but it's too late:
```
INFO  2024-08-19 21:11:42,045 [shard 0:strm] storage_service - entering NORMAL mode
INFO  2024-08-19 21:11:42,045 [shard 0:strm] raft_group0 - finish_setup_after_join: group 0 ID present, loading server info.
INFO  2024-08-19 21:11:42,045 [shard 0:strm] raft_group0 - finish_setup_after_join: becoming a voter in the group 0 configuration...
INFO  2024-08-19 21:11:42,047 [shard 0:strm] raft_group0 - finish_setup_after_join: became a group 0 voter.
INFO  2024-08-19 21:11:42,047 [shard 0:strm] cdc - Latest generation seen during startup: (2024/08/19 18:11:38, 8b13d4fc-4753-4fb2-9772-e90782a7c8fc)
INFO  2024-08-19 21:11:42,049 [shard 0:strm] cdc - Starting to use generation (2024/08/19 18:11:38, 8b13d4fc-4753-4fb2-9772-e90782a7c8fc)
INFO  2024-08-19 21:11:42,052 [shard 0:strm] cdc - CDC description table successfully updated with generation (2024/08/19 18:11:38, 8b13d4fc-4753-4fb2-9772-e90782a7c8fc).
INFO  2024-08-19 21:11:42,052 [shard 0:strm] raft_topology - The cluster is ready to start upgrade to the raft topology. The procedure needs to be manually triggered. Refer to the documentation
INFO  2024-08-19 21:11:44,254 [shard 0:main] init - starting tracing
INFO  2024-08-19 21:11:44,254 [shard 0:main] init - SSTable data integrity checker is disabled.
INFO  2024-08-19 21:11:44,255 [shard 0:main] service_level_controller - start_legacy_update_from_distributed_data: starting configuration polling loop
INFO  2024-08-19 21:11:44,255 [shard 0:main] init - starting auth service
INFO  2024-08-19 21:11:44,255 [shard 0:main] migration_manager - Schema agreement check passed.
INFO  2024-08-19 21:11:44,256 [shard 0:main] init - starting batchlog manager
INFO  2024-08-19 21:11:44,256 [shard 0:main] init - starting load meter
INFO  2024-08-19 21:11:44,256 [shard 0:main] init - starting cf cache hit rate calculator
INFO  2024-08-19 21:11:44,257 [shard 0:main] init - starting view update backlog broker
INFO  2024-08-19 21:11:44,257 [shard 0:main] init - Waiting for gossip to settle before accepting client requests...
INFO  2024-08-19 21:11:44,257 [shard 0:main] init - allow replaying hints
INFO  2024-08-19 21:11:44,257 [shard 0:main] init - Launching generate_mv_updates for non system tables
INFO  2024-08-19 21:11:44,258 [shard 0:main] migration_manager - Schema agreement check passed.
INFO  2024-08-19 21:11:44,258 [shard 1:main] migration_manager - Schema agreement check passed.
INFO  2024-08-19 21:11:44,260 [shard 0:stmt] cql_server_controller - Starting listening for CQL clients on 127.242.182.32:9042 (unencrypted, non-shard-aware)
INFO  2024-08-19 21:11:44,260 [shard 0:stmt] cql_server_controller - Starting listening for CQL clients on 127.242.182.32:19042 (unencrypted, shard-aware)
------ Ending test dev/topology_custom.test_gossip_boot.1::test_gossip_boot.1 ------
```

I don't see why it takes so long to actually start the server.
Maybe the cluster manager or the test host are extremely busy?

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10987/artifact/testlog/x86_64/test.py.debug-release-dev.log:
```
21:10:24.847 INFO> [dev/topology_custom.test_gossip_boot.1] installing Scylla server in /scylladir/testlog/x86_64/dev/scylla-2169...
21:10:28.394 INFO> [dev/topology_custom.test_gossip_boot.2] started server at host 127.242.182.30 in scylla-2156, pid 283296
21:10:28.397 INFO> [dev/topology_custom.test_gossip_boot.2] Cluster ScyllaCluster(name: 44c10fea-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2151, 127.242.182.8, a213b46a-04b1-4339-b12b-06bcb7faed63), ScyllaServer(2156, 127.242.182.30, d5052134-8079-442a-9f42-4ef66c617582), stopped: ) added ScyllaServer(2156, 127.242.182.30, d5052134-8079-442a-9f42-4ef66c617582)
21:10:28.398 INFO>  [19/Aug/2024:20:10:13 +0200] "PUT /cluster/addserver HTTP/1.1" 200 239 "-" "Python/3.12 aiohttp/3.9.5"
21:10:28.415 INFO> [dev/topology_custom.test_gossip_boot.2] [ScyllaClusterManager][Task-186165] http://api/cluster/addserver
21:10:28.416 INFO> [dev/topology_custom.test_gossip_boot.2] Cluster 44c10fea-5e56-11ef-9da1-12a7ba74344b waiting for new IP...
21:10:28.417 INFO> [dev/topology_custom.test_gossip_boot.2] Cluster 44c10fea-5e56-11ef-9da1-12a7ba74344b obtained new IP: 127.242.182.9
21:10:28.418 INFO> [dev/topology_custom.test_gossip_boot.2] Cluster ScyllaCluster(name: 44c10fea-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2151, 127.242.182.8, a213b46a-04b1-4339-b12b-06bcb7faed63), ScyllaServer(2156, 127.242.182.30, d5052134-8079-442a-9f42-4ef66c617582), stopped: ) adding server...
21:10:28.420 INFO> [dev/topology_custom.test_gossip_boot.2] installing Scylla server in /scylladir/testlog/x86_64/dev/scylla-2170...
21:10:29.452 INFO> [dev/topology_custom.test_gossip_boot.3] started server at host 127.242.182.58 in scylla-2159, pid 283374
21:10:29.454 WARNING> An authentication challenge was not sent, this is suspicious because the driver expects authentication (configured authenticator = PlainTextAuthenticator)
21:10:29.456 INFO> [dev/topology_custom.test_gossip_boot.3] Cluster ScyllaCluster(name: 45a589e0-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2152, 127.242.182.77, 63ecb418-2307-43af-b915-2945f7cd0cc6), ScyllaServer(2159, 127.242.182.58, 7c4ca120-7474-4989-a584-b6ee4538946c), stopped: ) added ScyllaServer(2159, 127.242.182.58, 7c4ca120-7474-4989-a584-b6ee4538946c)
21:10:29.460 INFO>  [19/Aug/2024:20:10:15 +0200] "PUT /cluster/addserver HTTP/1.1" 200 239 "-" "Python/3.12 aiohttp/3.9.5"
21:10:29.466 INFO> [dev/topology_custom.test_gossip_boot.3] [ScyllaClusterManager][Task-186166] http://api/cluster/addserver
21:10:29.467 INFO> [dev/topology_custom.test_gossip_boot.3] Cluster 45a589e0-5e56-11ef-9da1-12a7ba74344b waiting for new IP...
21:10:29.467 INFO> [dev/topology_custom.test_gossip_boot.3] Cluster 45a589e0-5e56-11ef-9da1-12a7ba74344b obtained new IP: 127.242.182.2
21:10:29.471 INFO> [dev/topology_custom.test_gossip_boot.3] Cluster ScyllaCluster(name: 45a589e0-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2152, 127.242.182.77, 63ecb418-2307-43af-b915-2945f7cd0cc6), ScyllaServer(2159, 127.242.182.58, 7c4ca120-7474-4989-a584-b6ee4538946c), stopped: ) adding server...
21:10:29.472 INFO> [dev/topology_custom.test_gossip_boot.3] installing Scylla server in /scylladir/testlog/x86_64/dev/scylla-2171...
21:10:31.394 INFO> New Cassandra host <Host: 127.242.182.30:9042 datacenter1> discovered
21:10:32.907 INFO> New Cassandra host <Host: 127.242.182.58:9042 datacenter1> discovered
21:11:25.172 INFO> [dev/topology_custom.test_gossip_boot.1] [ScyllaClusterManager][Task-186169] http://api/cluster/all-servers
21:11:25.176 INFO>  [19/Aug/2024:20:11:25 +0200] "GET /cluster/all-servers HTTP/1.1" 200 246 "-" "Python/3.12 aiohttp/3.9.5"
21:11:25.179 INFO> [dev/topology_custom.test_gossip_boot.1] [ScyllaClusterManager][Task-186170] http://api/cluster/server/2138/get_log_filename
21:11:25.183 INFO>  [19/Aug/2024:20:11:25 +0200] "GET /cluster/server/2138/get_log_filename HTTP/1.1" 200 205 "-" "Python/3.12 aiohttp/3.9.5"
21:11:25.184 INFO> [dev/topology_custom.test_gossip_boot.1] [ScyllaClusterManager][Task-186171] http://api/cluster/server/2149/get_log_filename
21:11:25.185 INFO>  [19/Aug/2024:20:11:25 +0200] "GET /cluster/server/2149/get_log_filename HTTP/1.1" 200 205 "-" "Python/3.12 aiohttp/3.9.5"
21:11:25.189 INFO> [dev/topology_custom.test_gossip_boot.1] [ScyllaClusterManager][Task-186172] http://api/cluster/after-test/False
21:11:25.190 INFO> [dev/topology_custom.test_gossip_boot.1] Cluster_history
<Request GET /cluster/is-dirty >:		<Task finished name='Task-184524' coro=<RequestHandler._handle_request() done, defined at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:442> result=(<Response OK eof>, False)>
<Request PUT /cluster/before-test/test_gossip_boot.1 >:		<Task finished name='Task-184526' coro=<RequestHandler._handle_request() done, defined at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:442> result=(<Response OK eof>, False)>
<Request GET /cluster/running-servers >:		<Task finished name='Task-184527' coro=<RequestHandler._handle_request() done, defined at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:442> result=(<Response OK eof>, False)>
<Request PUT /cluster/addserver >:		<Task finished name='Task-184530' coro=<RequestHandler._handle_request() done, defined at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:442> result=(<Response OK eof>, False)>
<Request GET /cluster/running-servers >:		<Task finished name='Task-184704' coro=<RequestHandler._handle_request() done, defined at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:442> result=(<Response OK eof>, False)>
<Request PUT /cluster/addserver >:		<Task finished name='Task-184715' coro=<RequestHandler._handle_request() done, defined at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:442> result=(<Response OK eof>, False)>
<Request PUT /cluster/addserver >:		<Task pending name='Task-186164' coro=<RequestHandler._handle_request() running at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:452> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib64/python3.12/asyncio/futures.py:387, Task.task_wakeup()]> cb=[Task.task_wakeup()]>
<Request GET /cluster/all-servers >:		<Task finished name='Task-186169' coro=<RequestHandler._handle_request() done, defined at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:442> result=(<Response OK eof>, False)>
<Request GET /cluster/server/2138/get_log_filename >:		<Task finished name='Task-186170' coro=<RequestHandler._handle_request() done, defined at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:442> result=(<Response OK eof>, False)>
<Request GET /cluster/server/2149/get_log_filename >:		<Task finished name='Task-186171' coro=<RequestHandler._handle_request() done, defined at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:442> result=(<Response OK eof>, False)>
<Request PUT /cluster/after-test/False >:		<Task pending name='Task-186172' coro=<RequestHandler._handle_request() running at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:452> cb=[Task.task_wakeup()]>
21:11:25.192 INFO> [dev/topology_custom.test_gossip_boot.1] wait for task:<Task pending name='Task-186164' coro=<RequestHandler._handle_request() running at /usr/lib64/python3.12/site-packages/aiohttp/web_protocol.py:452> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib64/python3.12/asyncio/futures.py:387, Task.task_wakeup()]> cb=[Task.task_wakeup()]>, request:/cluster/addserver
21:11:27.223 INFO> [dev/topology_custom.test_hints.2] starting server at host 127.242.182.83 in scylla-2160...
21:11:27.278 INFO> [dev/topology_custom.test_hints.2] starting server at host 127.242.182.18 in scylla-2161...
21:11:27.325 INFO> [dev/topology_custom.test_hints.3] starting server at host 127.242.182.3 in scylla-2162...
21:11:27.368 INFO> [dev/topology_custom.test_hints.3] starting server at host 127.242.182.59 in scylla-2163...
21:11:27.410 INFO> [dev/topology_custom.test_initial_token.1] starting server at host 127.242.182.41 in scylla-2164...
21:11:27.453 INFO> [dev/topology_custom.test_hints.1] starting server at host 127.242.182.44 in scylla-2165...
21:11:27.496 INFO> [dev/topology_custom.test_tablets_migration.3] starting server at host 127.242.182.85 in scylla-2166...
21:11:27.537 INFO> [dev/topology_custom.test_tablets_migration.2] starting server at host 127.242.182.68 in scylla-2167...
21:11:27.581 INFO> [dev/topology_custom.test_tablets_migration.1] starting server at host 127.242.182.57 in scylla-2168...
21:11:27.617 INFO> [dev/topology_custom.test_gossip_boot.1] starting server at host 127.242.182.32 in scylla-2169...
...
21:11:44.407 INFO> [dev/topology_custom.test_gossip_boot.1] started server at host 127.242.182.32 in scylla-2169, pid 283789
21:11:44.407 WARNING> An authentication challenge was not sent, this is suspicious because the driver expects authentication (configured authenticator = PlainTextAuthenticator)
21:11:44.408 INFO> [dev/topology_custom.test_gossip_boot.1] Cluster ScyllaCluster(name: 428a7e28-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2138, 127.242.182.45, d12a20f1-1831-4fe3-9f19-976eb1a55241), ScyllaServer(2149, 127.242.182.31, 21d796c0-2100-4d89-b0a9-9281eff21046), ScyllaServer(2169, 127.242.182.32, f1805c3d-62e9-4e4b-bf78-b8a98827026b), stopped: ) added ScyllaServer(2169, 127.242.182.32, f1805c3d-62e9-4e4b-bf78-b8a98827026b)
21:11:44.410 INFO>  [19/Aug/2024:20:10:24 +0200] "PUT /cluster/addserver HTTP/1.1" 200 0 "-" "Python/3.12 aiohttp/3.9.5"
21:11:44.489 INFO> [dev/topology_custom.test_gossip_boot.2] started server at host 127.242.182.9 in scylla-2170, pid 283793
21:11:44.489 INFO> [dev/topology_custom.test_gossip_boot.2] Cluster ScyllaCluster(name: 44c10fea-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2151, 127.242.182.8, a213b46a-04b1-4339-b12b-06bcb7faed63), ScyllaServer(2156, 127.242.182.30, d5052134-8079-442a-9f42-4ef66c617582), ScyllaServer(2170, 127.242.182.9, fa225344-4a9d-43f0-9f97-bde96c54ce91), stopped: ) added ScyllaServer(2170, 127.242.182.9, fa225344-4a9d-43f0-9f97-bde96c54ce91)
21:11:44.490 INFO>  [19/Aug/2024:20:10:28 +0200] "PUT /cluster/addserver HTTP/1.1" 200 0 "-" "Python/3.12 aiohttp/3.9.5"
21:11:44.516 INFO> [dev/topology_custom.test_hints.1] gracefully stopped ScyllaServer(2184, 127.242.182.80, d2613a4f-ed77-4a2a-b83f-fdc1000cf772)
21:11:44.517 INFO>  [19/Aug/2024:20:11:42 +0200] "PUT /cluster/server/2184/stop_gracefully HTTP/1.1" 200 150 "-" "Python/3.12 aiohttp/3.9.5"
21:11:44.518 INFO> [dev/topology_custom.test_gossip_boot.1] Test dev/topology_custom.test_gossip_boot.1::test_gossip_boot.1 FAILED, cluster: ScyllaCluster(name: 428a7e28-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2138, 127.242.182.45, d12a20f1-1831-4fe3-9f19-976eb1a55241), ScyllaServer(2149, 127.242.182.31, 21d796c0-2100-4d89-b0a9-9281eff21046), ScyllaServer(2169, 127.242.182.32, f1805c3d-62e9-4e4b-bf78-b8a98827026b), stopped: )
21:11:44.519 INFO> [dev/topology_custom.test_gossip_boot.1] The cluster 428a7e28-5e56-11ef-9da1-12a7ba74344b is dirty, not checking keyspace count post-condition
21:11:44.520 INFO>  [19/Aug/2024:20:11:25 +0200] "PUT /cluster/after-test/False HTTP/1.1" 200 460 "-" "Python/3.12 aiohttp/3.9.5"
21:11:44.533 INFO> [dev/topology_custom.test_hints.1] [ScyllaClusterManager][Task-186801] http://api/cluster/server/2185/stop_gracefully
21:11:44.534 INFO> [dev/topology_custom.test_hints.1] Cluster ScyllaCluster(name: 78a4a024-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2183, 127.242.182.44, 8e1e4283-3913-47d7-90d3-176ade5469bc), ScyllaServer(2185, 127.242.182.41, eba4e46b-6b53-4ad8-b831-60683ecc3818), stopped: ScyllaServer(2184, 127.242.182.80, d2613a4f-ed77-4a2a-b83f-fdc1000cf772)) stopping server 2185
21:11:44.534 INFO> [dev/topology_custom.test_hints.1] gracefully stopping ScyllaServer(2185, 127.242.182.41, eba4e46b-6b53-4ad8-b831-60683ecc3818)
21:11:44.540 WARNING> Host 127.242.182.41:9042 has been marked down
21:11:44.614 INFO> [dev/topology_custom.test_gossip_boot.2] Test dev/topology_custom.test_gossip_boot.2::test_gossip_boot.2 FAILED, cluster: ScyllaCluster(name: 44c10fea-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2151, 127.242.182.8, a213b46a-04b1-4339-b12b-06bcb7faed63), ScyllaServer(2156, 127.242.182.30, d5052134-8079-442a-9f42-4ef66c617582), ScyllaServer(2170, 127.242.182.9, fa225344-4a9d-43f0-9f97-bde96c54ce91), stopped: )
21:11:44.615 INFO> [dev/topology_custom.test_gossip_boot.2] The cluster 44c10fea-5e56-11ef-9da1-12a7ba74344b is dirty, not checking keyspace count post-condition
21:11:44.616 INFO>  [19/Aug/2024:20:11:29 +0200] "PUT /cluster/after-test/False HTTP/1.1" 200 458 "-" "Python/3.12 aiohttp/3.9.5"
21:11:44.720 INFO> [dev/topology_custom.test_gossip_boot.1] Test topology_custom.test_gossip_boot.1 failed 
21:11:44.721 INFO> [dev/topology_custom.test_gossip_boot.1] ScyllaManager stopping for test dev/topology_custom.test_gossip_boot.1
21:11:44.721 INFO> [dev/topology_custom.test_gossip_boot.1] ScyllaManager: Scylla cluster ScyllaCluster(name: 428a7e28-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2138, 127.242.182.45, d12a20f1-1831-4fe3-9f19-976eb1a55241), ScyllaServer(2149, 127.242.182.31, 21d796c0-2100-4d89-b0a9-9281eff21046), ScyllaServer(2169, 127.242.182.32, f1805c3d-62e9-4e4b-bf78-b8a98827026b), stopped: ) is dirty after dev/topology_custom.test_gossip_boot.1, stopping it
21:11:44.722 INFO> [dev/topology_custom.test_gossip_boot.1] Cluster ScyllaCluster(name: 428a7e28-5e56-11ef-9da1-12a7ba74344b, running: ScyllaServer(2138, 127.242.182.45, d12a20f1-1831-4fe3-9f19-976eb1a55241), ScyllaServer(2149, 127.242.182.31, 21d796c0-2100-4d89-b0a9-9281eff21046), ScyllaServer(2169, 127.242.182.32, f1805c3d-62e9-4e4b-bf78-b8a98827026b), stopped: ) stopping
21:11:44.722 INFO> [dev/topology_custom.test_gossip_boot.1] stopping ScyllaServer(2138, 127.242.182.45, d12a20f1-1831-4fe3-9f19-976eb1a55241) in scylla-2138
21:11:44.723 INFO> [dev/topology_custom.test_gossip_boot.1] stopping ScyllaServer(2149, 127.242.182.31, 21d796c0-2100-4d89-b0a9-9281eff21046) in scylla-2149
21:11:44.724 INFO> [dev/topology_custom.test_gossip_boot.1] stopping ScyllaServer(2169, 127.242.182.32, f1805c3d-62e9-4e4b-bf78-b8a98827026b) in scylla-2169
21:11:44.778 INFO> [dev/topology_custom.test_gossip_boot.1] stopped ScyllaServer(2138, 127.242.182.45, d12a20f1-1831-4fe3-9f19-976eb1a55241) in scylla-2138
21:11:44.786 INFO> [dev/topology_custom.test_gossip_boot.1] stopped ScyllaServer(2149, 127.242.182.31, 21d796c0-2100-4d89-b0a9-9281eff21046) in scylla-2149
21:11:44.789 INFO> [dev/topology_custom.test_gossip_boot.1] stopped ScyllaServer(2169, 127.242.182.32, f1805c3d-62e9-4e4b-bf78-b8a98827026b) in scylla-2169
21:11:44.790 INFO> [dev/topology_custom.test_gossip_boot.1] Cluster ScyllaCluster(name: 428a7e28-5e56-11ef-9da1-12a7ba74344b, running: , stopped: ScyllaServer(2138, 127.242.182.45, d12a20f1-1831-4fe3-9f19-976eb1a55241), ScyllaServer(2149, 127.242.182.31, 21d796c0-2100-4d89-b0a9-9281eff21046), ScyllaServer(2169, 127.242.182.32, f1805c3d-62e9-4e4b-bf78-b8a98827026b)) releases ips {'127.242.182.45', '127.242.182.32', '127.242.182.31'}
```

[logs.tar.gz](https://github.com/user-attachments/files/16669860/logs.tar.gz)

**Comment by bhalevy** [comment] 2024-08-20 06:19
Cc @kostja @kbr-scylla

**Comment by kbr-scylla** [comment] 2024-08-20 08:25
Duplicate of https://github.com/scylladb/scylladb/issues/20116.

**Closed by kbr-scylla** 2024-08-20 08:25 UTC
Labels: symptom/ci stability
