### ISSUE TITLE
Coredump occurred after MV creation and during a member-node stop process

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylladb#14006] opened 2023-05-23 16:41 UTC
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

## Impact

MV creation fails

## How frequently does it reproduce?

Probably first time

## Installation details

Kernel Version: 5.15.0-1035-aws
Scylla version (or git commit hash): `2023.1.0~rc5-20230429.a47bcb26e42e` with build-id `d2644a8364f13d14d25be6b9d3c69f84612192bd`

Cluster size: 4 nodes (i3en.3xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-4d-2023--db-node-da817906-9 (3.251.82.133 | 10.4.0.118) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-8 (54.246.202.153 | 10.4.2.75) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-7 (3.252.123.16 | 10.4.1.81) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-6 (34.240.14.143 | 10.4.1.206) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-5 (3.252.189.146 | 10.4.2.59) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-4 (52.215.203.234 | 10.4.2.28) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-3 (52.17.133.79 | 10.4.3.170) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-2 (54.217.0.178 | 10.4.2.106) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-1 (3.253.28.40 | 10.4.2.12) (shards: 10)

OS / Image: `ami-05e7801837cea47d9` (aws: eu-west-1)

Test: `longevity-large-partition-4days-test`
Test id: `da817906-6710-4a13-b5d7-b4ee9ef7c87e`
Test name: `enterprise-2023.1/longevity/longevity-large-partition-4days-test`
Test config file(s):

- [longevity-large-partition-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1dafb96f428e2691c12e03508dc5024d85552043/test-cases/longevity/longevity-large-partition-4days.yaml)

## Details:
Following scenario (`add_remove_mv` nemesis) was executed:
- Stop 1 of 4 nodes
- Create Materialized view
- Start stopped node
- Repair started node
- Wait for the MV be built
- Delete MV

On the start of this scenario we had 4 following nodes running: `node-1`, `node-2` (stop target), `node-3` and `node-4` and on-going large-partitions load.
First step, stop of the target `node-2` node:
```
2023-05-16T23:53:29+00:00 longevity-large-partitions-4d-2023--db-node-da817906-2     !INFO | systemd[1]: Stopping Scylla Server...
```

Creation of the MV on the `node-1` node:
```
2023-05-16T23:54:50+00:00 longevity-large-partitions-4d-2023--db-node-da817906-1     !INFO | scylla[5423]:  [shard 0] migration_manager - Create new view: org.apache.cassandra.config.CFMetaData@0x600000532800[cfId=0bc5b320-f445-11ed-8494-933b6ae871b8,ksName=scylla_bench,cfName=test_view,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.UTF8Type),comment=test MV,readRepairChance=0,dcLocalReadRepairChance=0,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.BytesType,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=v, type=org.apache.cassandra.db.marshal.BytesType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=ck, type=org.apache.cassandra.db.marshal.LongType, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.LongType, kind=CLUSTERING_COLUMN, componentIndex=1, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.IncrementalCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,in_memory=false,version=0bc5b321-f445-11ed-8494-933b6ae871b8,droppedColumns={},collections={},indices={}, viewInfo=ViewInfo{baseTableId=01d129c0-f333-11ed-a8ee-eb9eee32fe75, baseTableName=test, includeAllColumns=false, whereClause=v IS NOT null AND ck IS NOT null AND pk IS NOT null}]
```

Then following happens on each of the alive nodes:
```
2023-05-16T23:54:50+00:00 longevity-large-partitions-4d-2023--db-node-da817906-1     !INFO | scylla[5423]: Reactor stalled for 97 ms on shard 4. Backtrace: 0x51b4d43 0x51b4130 0x51b5510 0x3cb1f 0x1d9fba1 0x1d6c438 0x1d8080a 0x1d80986 0x1d80986 0x1d80986 0x1d80986 0x1d80986 0x1d213b2 0x1bd7b9e 0x1c05b44 0x1908e25 0x19d7bc2 0x1962f66 0x195eed2 0x18aa887 0x403f48d 0x1267d3a 0x51c5624 0x51c68a7 0x51e7691 0x519797a 0x8b12c 0x10cbbf
2023-05-16T23:54:50+00:00 longevity-large-partitions-4d-2023--db-node-da817906-1     !INFO | scylla[5423]: kernel callstack:
2023-05-16T23:54:50+00:00 longevity-large-partitions-4d-2023--db-node-da817906-1     !INFO | scylla[5423]: kernel callstack:
2023-05-16T23:54:50+00:00 longevity-large-partitions-4d-2023--db-node-da817906-1     !INFO | scylla[5423]: kernel callstack:
2023-05-16T23:54:50+00:00 longevity-large-partitions-4d-2023--db-node-da817906-1     !INFO | scylla[5423]: kernel callstack:
2023-05-16T23:54:50+00:00 longevity-large-partitions-4d-2023--db-node-da817906-1     !INFO | scylla[5423]: kernel callstack: 0xffffffffffffff80 0xffffffff95e0006f 0xffffffff94ec5834 0xffffffff95bb46f3 0xffffffff95c00eeb
2023-05-16T23:54:50+00:00 longevity-large-partitions-4d-2023--db-node-da817906-1     !INFO | scylla[5423]: kernel callstack:
2023-05-16T23:54:50+00:00 longevity-large-partitions-4d-2023--db-node-da817906-1     !INFO | scylla[5423]: kernel callstack: 0xffffffffffffff80 0xffffffff959da538 0xffffffff959d4109 0xffffffff959d4897 0xffffffff959bb489 0xffffffff959bc2ba 0xffffffff959bc6dd 0xffffffff959fd033 0xffffffff958ce792 0xffffffff958ceb22 0xffffffff958d1a31 0xffffffff958d1af2 0xffffffff958d1b6d 0xffffffff95bb118c 0xffffffff95c00099
...
```

... right after the following message:
```
2023-05-16T23:54:53+00:00 longevity-large-partitions-4d-2023--db-node-da817906-1     !INFO | scylla[5423]:  [shard 0] raft_group_registry - marking Raft server c6e30351-065b-4d32-b20e-cd4f0d3fddfd as dead for raft groups
```

```
corefile_url=https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.97ae7e1470ee4dd28bbe044c71ef4070.5508.1684281316000000/core.scylla.112.97ae7e1470ee4dd28bbe044c71ef4070.5508.1684281316000000.gz
```
```
download_instructions=gsutil cp gs://upload.scylladb.com/core.scylla.112.97ae7e1470ee4dd28bbe044c71ef4070.5508.1684281316000000/core.scylla.112.97ae7e1470ee4dd28bbe044c71ef4070.5508.1684281316000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.112.97ae7e1470ee4dd28bbe044c71ef4070.5508.1684281316000000.gz
```

The coredump: 
[coredump-da817906-6710-4a13-b5d7-b4ee9ef7c87e.txt](https://github.com/scylladb/scylladb/files/11546560/coredump-da817906-6710-4a13-b5d7-b4ee9ef7c87e.txt)

Then we start the stopped node and trigger the `nodetool repair -pr` command:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2586, in run_nodetool
    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: '/usr/bin/nodetool  repair -pr '

Exit code: 2

Stdout:

[2023-05-16 23:56:23,395] Starting repair command #1, repairing 1 ranges for keyspace scylla_bench (parallelism=SEQUENTIAL, full=true)
[2023-05-17 00:38:35,739] Repair session 1 failed
[2023-05-17 00:38:35,739] Repair session 1 finished

Stderr:

error: Repair job has failed with the error message: [2023-05-17 00:38:35,739] Repair session 1 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2023-05-17 00:38:35,739] Repair session 1 failed
	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

## Monitoring:
- Restore Monitor Stack command: `$ hydra investigate show-monitor da817906-6710-4a13-b5d7-b4ee9ef7c87e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=da817906-6710-4a13-b5d7-b4ee9ef7c87e)
- Show all stored logs command: `$ hydra investigate show-logs da817906-6710-4a13-b5d7-b4ee9ef7c87e`

## Logs:
- **db-cluster-da817906.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/da817906-6710-4a13-b5d7-b4ee9ef7c87e/20230519_122313/db-cluster-da817906.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/da817906-6710-4a13-b5d7-b4ee9ef7c87e/20230519_122313/db-cluster-da817906.tar.gz)
- **sct-runner-events-da817906.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/da817906-6710-4a13-b5d7-b4ee9ef7c87e/20230519_122313/sct-runner-events-da817906.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/da817906-6710-4a13-b5d7-b4ee9ef7c87e/20230519_122313/sct-runner-events-da817906.tar.gz)
- **sct-da817906.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/da817906-6710-4a13-b5d7-b4ee9ef7c87e/20230519_122313/sct-da817906.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/da817906-6710-4a13-b5d7-b4ee9ef7c87e/20230519_122313/sct-da817906.log.tar.gz)
- **monitor-set-da817906.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/da817906-6710-4a13-b5d7-b4ee9ef7c87e/20230519_122313/monitor-set-da817906.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/da817906-6710-4a13-b5d7-b4ee9ef7c87e/20230519_122313/monitor-set-da817906.tar.gz)
- **loader-set-da817906.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/da817906-6710-4a13-b5d7-b4ee9ef7c87e/20230519_122313/loader-set-da817906.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/da817906-6710-4a13-b5d7-b4ee9ef7c87e/20230519_122313/loader-set-da817906.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-large-partition-4days-test/3/)
[Argus](https://argus.scylladb.com/test/a388b58f-ff99-4bdb-b813-d07a2111d1d1/runs?additionalRuns[]=da817906-6710-4a13-b5d7-b4ee9ef7c87e)

**Comment by michoecho** [comment] 2023-05-24 00:26
CC @tgrabiec This is a fun one.

The crash was caused by `_read_section` trying to reserve 8 GiB — more than the total possible size of cache.
As it turns out, this is a rare interplay of #2577, this test workload, and the implementation details of `allocating_section`.

Section reserve sizes are consecutive powers of 2.
Due to #2577, upgrading a partition entry requires allocating about as much memory (inside a section) as the size of the partition entry.

So, if:
1. The entire cache is occupied with a single partition entry.
2. The size of cache is slightly smaller than some power of 2.
3. Upgrading the entry requires slightly more memory than can be reclaimed from the entry.
4. A schema change happens.
then the upgrade will choke `allocating_section`.

For example, if cache is filled with a single 7.99 GiB entry, and a schema change happens, an upgrade will start.
A few times it will fail and allocating_section will increase reserves and evict parts of the entry.
Eventually the reserves will reach 4 GiB and the entry will be 3.99 GiB. If upgrading this 3.99 GiB entry requires 4.01 GiB, this too will fail and reserve will be increased to 8 GiB, killing the node. And that's what we see.

Condition 1 was fulfilled by the config of this test — the number of partitions is small enough that some shards only serve 1 partition, and the partitions are big enough to fill the entire cache.
Condition 2 was fulfilled by a stroke of bad luck with memtables being just the right size to reduce cache size to ~8GiB minus several megabytes.
I'm not sure why condition 3 is true, but apparently it is. Maybe upgrade not only allocates memory but also frees it? (And the freed memory can't be recycled inside a section).
Condition 4 was triggered by the MV nemesis.

**Comment by michoecho** [comment] 2023-05-24 00:31
I recommend closing this as a duplicate of #2577. This is a more severe manifestation than the usual stall, but it requires the entire cache to be filled with a single partition entry, which is presumably very rare in practice. If we haven't seen it in practice for this many years, this variant probably doesn't require special attention.

**Comment by tgrabiec** [comment] 2023-05-24 12:43
I saw something like that in https://github.com/scylladb/scylladb/issues/10059#issuecomment-1088012218

Upgrading actually makes two copies of the partition, so it can overshoot shard's capacity in such cases.

**Comment by michoecho** [comment] 2023-05-25 10:51
Closing as a duplicate of https://github.com/scylladb/scylladb/issues/10059 / https://github.com/scylladb/scylladb/issues/2577.

**Closed by michoecho** 2023-05-25 10:51 UTC
