### ISSUE TITLE
Upgrade sstables is not tablets aware (database - Tried to obtain per-keyspace effective replication map of ks but it's per-table)

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#16848] opened 2024-01-18 12:38 UTC
Stepped on by e.g. https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/110, test_migrate_sstable_with_cell_tombstone test cases (maybe more)

```
[Backtrace #0]
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_0>(seastar::current_backtrace_tasklocal()::$_0&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./seastar/src/util/backtrace.cc:97
seastar::current_tasktrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:148
seastar::current_backtrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:181
void log_error_and_backtrace<std::basic_string_view<char, std::char_traits<char> > >(seastar::logger&, std::basic_string_view<char, std::char_traits<char> > const&) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:51
 (inlined by) seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:55
replica::keyspace::get_effective_replication_map() const at ./replica/database.cc:414
 (inlined by) replica::database::get_keyspace_local_ranges(seastar::basic_sstring<char, unsigned int, 15u, true>) at ./replica/database.cc:2592
compaction::table_upgrade_sstables_compaction_task_impl::run() at ./compaction/task_manager_module.cc:509
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/coroutine:240
 (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:125
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2666
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:3129
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3305
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3188
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:276
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:167
scylla_main(int, char**) at ./main.cc:670
std::function<int (int, char**)>::operator()(int, char**) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
main at ./main.cc:2085
/data/scylla-s3-reloc.cache/by-build-id/d8bfecc2b8e4a591dfb30d01e5bfd664f7e7a9ef/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7026fe8c129a523e07856d7c96306663ceab6e24, for GNU/Linux 3.2.0, not stripped

__libc_start_call_main at ??:?
__libc_start_main_alias_2 at :?
_start at ??:?

```

**Comment by bhalevy** [comment] 2024-02-13 10:43
Cc @denesb @raphaelsc

**Comment by raphaelsc** [comment] 2024-02-13 10:50
Coincidentally, yesterday I opened the duplicate of this issue #17299.

merging its data here:

```
"SSTable upgrade uses keyspace local ranges, which clearly doesn't work with tablet replication map. 

future<> table_upgrade_sstables_compaction_task_impl::run() {
    co_await wait_for_your_turn(_cv, _current_task, _status.id);
    auto owned_ranges_ptr = compaction::make_owned_ranges_ptr(_db.get_keyspace_local_ranges(_status.keyspace));
    tasks::task_info info{_status.id, _status.shard};

I don't actually understand why it needs it. Looks like piggybacking on upgrade for cleanup. We can probably just remove this behavior from it."
```

**Comment by raphaelsc** [comment] 2024-02-13 10:51
@bhalevy do you remember why we filter out unowned tokens in upgrade? we don't have to right?

**Comment by raphaelsc** [comment] 2024-02-13 10:52
Ah IIRC that's part of your series, to piggyback on other compaction types for cleanup work.

**Comment by denesb** [comment] 2024-02-13 11:09
I think we only need this for vnodes, so for tablets, we can just pass empty owned ranges here.

**Closed** 2024-02-16 14:21 UTC
Labels: tests/dtest, area/tablets

**Comment by bhalevy** [comment] 2024-02-16 15:18
> Ah IIRC that's part of your series, to piggyback on other compaction types for cleanup work.

right



> I think we only need this for vnodes, so for tablets, we can just pass empty owned ranges here.

correct

**Comment by denesb** [comment] 2024-02-21 14:28
Tablets related change, no backports required.
