### ISSUE TITLE
Flaky dtest test_sstablelevelreset

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#17167] opened 2024-02-05 14:26 UTC
The dtest offline_tools_test.TestOfflineTools.test_sstablelevelreset failed in CI run https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6413/testReport/junit/offline_tools_test/TestOfflineTools/Tests___dtest___test_sstablelevelreset/:

```
self = <offline_tools_test.TestOfflineTools object at 0x7f3668ea7210>

    @pytest.mark.next_gating
    @pytest.mark.single_node
    @pytest.mark.cluster_options(uuid_sstable_identifiers_enabled=False)
    def test_sstablelevelreset(self):
        """
        Insert data and call sstablelevelreset on a series of
        tables. Confirm level is reset to 0 using its output.
        Test a variety of possible errors and ensure response is resonable.
        @since 2.1.5
        @jira_ticket CASSANDRA-7614
        """
        cluster = self.cluster
        cluster.populate(1).start(wait_for_binary_proto=True)
        node1 = cluster.nodelist()[0]
    
        # test by trying to run on nonexistent keyspace
        cluster.stop(gently=False)
        logger.debug("run sstablelevelreset on non-exitent keyspace")
        (output, error, rc) = node1.run_sstablelevelreset("keyspace1", "standard1", output=True)
>       assert "ColumnFamily not found: keyspace1/standard1" in error, "Message was not found in stderr"
E       AssertionError: Message was not found in stderr
E       assert 'ColumnFamily not found: keyspace1/standard1' in 'ERROR 12:49:31,153 No partition columns found for table system_auth.roles in system_schema.columns.  This may be due to corruption or concurrent dropping and altering of a table. If this table is supposed to be dropped, restart cassandra with -Dcassandra.ignore_corrupted_schema_tables=true and run the following query to cleanup: "DELETE FROM system_schema.tables WHERE keyspace_name = \'system_auth\' AND table_name = \'roles\'; DELETE FROM system_schema.columns WHERE keyspace_name = \'system_auth\' AND table_name = \'roles\';" If the table is not supposed to be dropped, restore system_schema.columns sstables from backups.\norg.apache.cassandra.schema.SchemaKeyspace$MissingColumns: Columns not found in schema table for system_auth.roles\n\tat org.apache.cassandra.schema.SchemaKeyspace.fetchColumns(SchemaKeyspace.java:1110)\n\tat org.apache.cassandra.schema.SchemaKeyspace.fetchTable(SchemaKeyspace.java:1056)\n\tat org.apache.cassandra.schema.SchemaKeyspace.fetchTables(SchemaKeyspace.java:1010)\n\tat org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspace(SchemaKeyspace.java:969)\n\tat org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspacesWithout(SchemaKeyspace.java:946)\n\tat org.apache.cassandra.schema.SchemaKeyspace.fetchNonSystemKeyspaces(SchemaKeyspace.java:934)\n\tat org.apache.cassandra.config.Schema.loadFromDisk(Schema.java:92)\n\tat org.apache.cassandra.config.Schema.loadFromDiskForTool(Schema.java:101)\n\tat org.apache.cassandra.tools.SSTableLevelResetter.main(SSTableLevelResetter.java:68)\n'

offline_tools_test.py:69: AssertionError
```

It seems that this test runs a single-node Scylla cluster, and then runs a Java Cassandra tool on it, and fails to read the `system_auth.roles` table. Could it be that this specific table takes time to create and we don't wait enough time before running the Cassandra code?
Is this a coincidence that the problem is in exactly the same table we had problems with in #16821?

If we do #15038 (replacing sstablelevelreset by a Scylla tool), it will make this issue moot.

**Comment by denesb** [comment] 2024-02-29 07:07
> Is this a coincidence that the problem is in exactly the same table we had problems with in https://github.com/scylladb/scylladb/issues/16821?

I think we can close this as a duplicate of https://github.com/scylladb/scylladb/issues/16821 and reopen if seen again.

> If we do https://github.com/scylladb/scylladb/issues/15038 (replacing sstablelevelreset by a Scylla tool), it will make this issue moot.

The native tool would hit the same problem. Actually, maybe not, because ScyllaDB's `tools/schema_loader.cc` doesn't read `auth` tables, only `system_schema` ones.

**Closed by denesb** 2024-02-29 07:07 UTC
Labels: tests/dtest, symptom/ci stability, area/scylla tools
