### ISSUE TITLE
3 times throughput drop when node restarted

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylladb#7760] opened 2020-12-06 10:31 UTC
*Installation details*
Scylla version (or git commit hash): `4.4.dev-0.20201127.4d0587ed1 with build-id 42ed24e11f982563131838a6dbadc61d15b73b8b (ami-04e59c57ffed6f653)`
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ` ami-04e59c57ffed6f653` [eu-north-1]
Test case: [longevity-50GB-3days-authorization-and-tls-ssl](https://github.com/scylladb/scylla-cluster-tests/blob/master/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

When [RestartThenRepairNode](https://github.com/scylladb/scylla-cluster-tests/blob/fc067ad7fe0b79cebb9696a1b3c90339d124c4f6/sdcm/nemesis.py#L375) restarted node 2 (longevity-tls-50gb-4d-master-db-node-45605e0a-2 [13.51.13.64 | 10.0.1.4] throughput dropped significantly
"Restarted" in this scenario means stop instance and then start causing data loss on the ephemeral local NVMe SSD data loss.

Live monitor [here](http://13.48.1.105:3000/d/ALTETAAGz/scylla-per-server-metrics-nemesis-master?orgId=1&from=1606897129451&to=1606898585058&var-by=instance&var-cluster=&var-dc=All&var-node=All&var-shard=All&var-sct_tags=CassandraStressEvent)
![image](https://user-images.githubusercontent.com/5269241/101277599-9f43b900-37c6-11eb-9ce9-a2bb7d1344d4.png)

Monitor:
`hydra investigate show-monitor 45605e0a-c0b9-4d97-b174-52fd3808b7cc`

Logs: 
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/45605e0a-c0b9-4d97-b174-52fd3808b7cc/20201204_011054/db-cluster-45605e0a.zip
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/45605e0a-c0b9-4d97-b174-52fd3808b7cc/20201204_011054/loader-set-45605e0a.zip
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/45605e0a-c0b9-4d97-b174-52fd3808b7cc/20201204_011054/monitor-set-45605e0a.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/45605e0a-c0b9-4d97-b174-52fd3808b7cc/20201204_011054/sct-runner-45605e0a.zip

**Comment by roydahan** [comment] 2020-12-07 12:12
@bentsi did the drop happened immediately when restarting or when the repair started?

**Comment by slivne** [comment] 2020-12-07 12:24
not clear this is a regression

potentially hints are being replayed. 

If this is not a regression -we should try and delay the repair after the hints are played.

**Comment by bentsi** [comment] 2020-12-13 19:34
@roydahan 
the repair ran at 09:24 
```
 < t:2020-12-02 09:24:18,712 f:remote_base.py  l:519  c:RemoteCmdRunner      p:DEBUG > Running command "/usr/bin/nodetool -u cassandra -pw cassandra  repair "...
```
but node was restarted at 
```
< t:2020-12-02 08:26:01,623 f:sct_events.py   l:968  c:sdcm.sct_events      p:INFO  > 2020-12-02 08:26:01.612: (DisruptionEvent Severity.NORMAL): type=start name=RestartThenRepairNode node=Node longevity-tls-50gb-4d-master-db-node-45605e0a-2 [13.51.13.64 | 10.0.1.4] (seed: False) duration=None
```

@slivne just to make sure what restart means here:
- stop the instance
- start the instance
this causes data loss on the ephemeral disk

**Comment by slivne** [comment] 2021-01-13 13:31
There is backpressure from MV - that seems to actually work - e.g. the overall traffic drops significantly - but I can;t figure out whas going on - CQL reads is higher while CQL updates is almost 0 ?


@psarna / @nyh its MV backpressure related - or seems to be - I'm assigning it to @eliransin - so one of you looks at this

**Comment by kostja** [comment] 2024-04-16 11:46
No traction since 2021, not clear if it's a bug - the MV backpressure has multiple issues in it fixed since then.

**Closed by kostja** 2024-04-16 11:46 UTC
Labels: area/materialized views
