### ISSUE TITLE
[Perf] Duration of manager repair is x4 time longer with master (~ 6h) that same scenario running Scylla enterprise (~ 1.5h)

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#21878] opened 2024-12-10 16:59 UTC
Manager repair duration takes long when running Scylla **master**. 
Using new `3.4.0` Scylla manager (instead of `3.2.8`) improves it, decreases duration, but not as it was improved with **enterprise** (https://github.com/scylladb/scylla-enterprise/issues/4937).

With Scylla **master** manager repair duration remains very long in **write** load test .

**Scylla master and write load test**

When tablets are **disabled**, the duration is decreased a little but still remains long (and significant longer than with Scylla enterprise):
| Tablets  | v3.2.8   | v3.4.0   |
|----------|----------|----------|
| Disabled | [06:32:48](https://argus.scylladb.com/tests/scylla-cluster-tests/72e42297-f83d-4226-a91d-c8cee86288ab) | [05:37:45](https://argus.scylladb.com/tests/scylla-cluster-tests/c0781a3c-b29f-4328-92c0-ae265063affb) |
| Scylla version | 6.3.0~dev-20241115 | 6.3.0~dev-20241115 |

When tablets are **enabled**, the duration is decreased significant, but still longer than with Scylla enterprise:
| Tablets  | v3.2.8   | v3.4.0   |
|----------|----------|----------|
| Enabled | [15:32:40](https://argus.scylladb.com/tests/scylla-cluster-tests/868c8813-076d-4582-a532-e86459da1ae0) | [03:40:45](https://argus.scylladb.com/tests/scylla-cluster-tests/fc96d315-3597-4847-9b61-c0926757d1e4) |
| Scylla version | 6.3.0~dev-20241030 | 6.3.0~dev-20241129 |

** _**Note**_: I have no example of runs with same Scylla version for tablets enabled. Let me know if it is needed.

**To compare with Scylla enterprise and  write load test**:

| Tablets  | v3.2.8   | v3.4.0   |
|----------|----------|----------|
| Disabled | [02:14:50](https://argus.scylladb.com/tests/scylla-cluster-tests/6f43e84a-288a-48f8-aa6a-772c60906d97) | [01:33:55](https://argus.scylladb.com/tests/scylla-cluster-tests/3a3abc2d-10ce-4800-9a55-84853f11aee8) |
| Scylla version | 2024.3.0~dev-20241115 | 2024.3.0~dev-20241120 |

| Tablets  | v3.2.8   | v3.4.0   |
|----------|----------|----------|
| Enabled  | [06:53:31](https://argus.scylladb.com/tests/scylla-cluster-tests/0ef12c18-69e4-49c1-8404-5c5fc942daf8) | [01:29:39](https://argus.scylladb.com/tests/scylla-cluster-tests/b283172e-a0d1-4601-b3cc-c0ef3a9129b1) |
| Scylla version | 2024.3.0~dev-20241030 | 2024.3.0~dev-20241030 |

### This is latest run of this test with 
- master
- tablets disabled
- Scylla manager version `3.4.0`
- write load test

Most of time repair runs with 100% CPU on all shards
![Image](https://github.com/user-attachments/assets/4ea894f1-6789-4749-be13-57e731fc6014)

## Packages

Scylla version: `6.3.0~dev-20241206.7e2875d6489d` with build-id `5227dd2a3fce4d2beb83ec6c17d47ad2e8ba6f5c`

Kernel Version: `6.8.0-1019-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- perf-latency-nemesis-ubuntu-db-node-deb4bd11-5 (34.241.19.96 | 10.4.5.247) (shards: 7)
- perf-latency-nemesis-ubuntu-db-node-deb4bd11-4 (54.154.126.90 | 10.4.6.252) (shards: 7)
- perf-latency-nemesis-ubuntu-db-node-deb4bd11-3 (63.35.181.51 | 10.4.4.35) (shards: 7)
- perf-latency-nemesis-ubuntu-db-node-deb4bd11-2 (54.154.235.147 | 10.4.7.111) (shards: 7)
- perf-latency-nemesis-ubuntu-db-node-deb4bd11-1 (3.254.193.99 | 10.4.4.249) (shards: -1)

OS / Image: `ami-0c7b4b0835c9342f7` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-650gb-with-nemesis`
Test id: `deb4bd11-05b7-41ed-a5c7-2526f2c5cb26`
Test name: `scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-with-nemesis`
Test method: `performance_regression_test.PerformanceRegressionTest.test_latency_write_with_nemesis`
Test config file(s):

- [perf-regression-latency-650gb-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5159e4f19dc11d7cd13699c909b72f4ee852bd0d/test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor deb4bd11-05b7-41ed-a5c7-2526f2c5cb26`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=deb4bd11-05b7-41ed-a5c7-2526f2c5cb26)
- Show all stored logs command: `$ hydra investigate show-logs deb4bd11-05b7-41ed-a5c7-2526f2c5cb26`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/perf-regression/job/scylla-master-perf-regression-latency-650gb-with-nemesis/36/)
[Argus](https://argus.scylladb.com/test/4f088858-cbf2-4984-9d44-d319c207f521/runs?additionalRuns[]=deb4bd11-05b7-41ed-a5c7-2526f2c5cb26)
</details>

**Comment by mykaul** [comment] 2024-12-11 09:30
I don't understand this bug. Is there an expectation they'd be running the same?

**Comment by mykaul** [comment] 2024-12-15 12:50
I don't see a problem here. @tzach ?

**Comment by mykaul** [comment] 2024-12-15 12:52
(Lastly, it'd be good to add some performance metrics, to show that the CQL workload performance remained similar between the runs)

**Comment by karol-kokoszka** [comment] 2024-12-18 09:59
```
------------------------------
Tablets | v3.2.8 | v3.4.0
------------------------------
Disabled | [06:32:48] | [05:37:45]
```
```
------------------------------
Tablets | v3.2.8 | v3.4.0
------------------------------
Disabled | [02:14:50] | [01:33:55] 
```

Explanation for the improvement in vnodes repair, must be the `ranges_parallelism` param added to repair API in scylla
PR in Scylla https://github.com/scylladb/scylladb/pull/14886

Scylla Manager 3.2.8 is already using the small_tables_optimization feature.

Changes to the repair introduced in SM > 3.2.8 are described here https://docs.google.com/document/d/1mBaufbomXU6hDO_25KkhC7CO65AbFgKpHVpB5Mei8xA/edit?tab=t.0#bookmark=id.drxr0un2cmsb

It's exactly the `ranges_parallelism` and support for tablets.

**Comment by mykaul** [comment] 2024-12-25 09:37
> I don't see a problem here. [@tzach](https://github.com/tzach) ?

Closing for the time being. 

@juliayakovlev - while it's not a bug, it's a great report - very useful to clearly see a comparison between different versions and tablets/vnodes!

**Closed by mykaul** 2024-12-25 09:37 UTC
Labels: area/repair, triage/master
