### ISSUE TITLE
[6.1.0~rc1] nodetool scrub --skip-corrupted failed with filesystem error: link failed: No such file or directory

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylladb#20030] opened 2024-08-05 15:27 UTC
## Packages

Scylla version: `6.1.0~rc1-20240726.97ae704f993c` with build-id `56df0cd0180f616ddf69aeab6263a87d9366a2a2`

Kernel Version: `6.8.0-1012-aws`

## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

CorruptThenScrub nemesis failed on node-7 in this run

```
Command: '/usr/bin/nodetool  scrub --skip-corrupted keyspace1'

Exit code: 4

Stdout:



Stderr:

error executing GET request to http://localhost:10000/storage_service/keyspace_scrub/keyspace1 with parameters {"scrub_mode": "SKIP"}: remote replied with status code 500 Internal Server Error:
std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: link failed: No such file or directory [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-TOC.txt] [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/snapshots/pre-scrub-1722042466796/me-3gi6_01m1_2xvq82lxjicx5boij1-big-TOC.txt.tmp])
```

grep node-7 log for `me-3gi6_01m1_2xvq82lxjicx5boij1`:

```
...
Jul 27 00:34:49.500403 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] sstable - Rebuilding bloom filter /var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-Filter.db: resizing bitset from 216 bytes to 40 bytes. sstable origin: streaming
Jul 27 01:07:19.412452 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] compaction - [Scrub keyspace1.standard1 9265db40-4bb4-11ef-ab93-cf1b23caa2cd] Scrubbing in skip mode [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-Data.db:level=0:origin=streaming]
Jul 27 01:38:16.820085 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] compaction - [Reshape keyspace1.standard1 e57fac30-4bb8-11ef-ab93-cf1b23caa2cd] Reshaping [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01lt_27axs2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ll_0pi7k2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ld_01aao2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01l4_3i11c2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ku_2pb342lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_04b0_0tktc2lxjicx5boij1-big-Data.db:level=0:origin=repair]
Jul 27 01:38:16.887069 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] sstable - Unable to delete /var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-TOC.txt because it doesn't exist.
```

## Impact

`nodetool scrub --skip-corrupted <ks>` command failed

## How frequently does it reproduce?

Next run of the same job with 6.1.0-20240804.abbf0b24a60c passed: https://argus.scylladb.com/test/2cca5979-f5f4-424b-9967-7f79e7d6be4c/runs?additionalRuns[]=17c85371-c29d-45c9-b373-ee4ab64cef74

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-6-1-db-node-7b6252df-9 (54.197.132.200 | 10.12.10.146) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-8 (18.212.202.75 | 10.12.8.200) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-7 (3.90.180.142 | 10.12.10.195) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-6 (3.91.58.31 | 10.12.8.103) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-5 (34.236.146.198 | 10.12.10.66) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-4 (54.226.152.70 | 10.12.9.70) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-3 (34.228.199.37 | 10.12.11.183) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-2 (18.234.226.132 | 10.12.8.40) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-1 (34.203.223.213 | 10.12.8.51) (shards: 14)

OS / Image: `ami-0b2b53e4d5c876e8d` (aws: undefined_region)

Test: `longevity-100gb-4h-test`
Test id: `7b6252df-9da0-4da6-ab26-d1c35806df1c`
Test name: `scylla-6.1/longevity/longevity-100gb-4h-test`

Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/79af70b59ed166b7764591522074edabd475eecb/test-cases/longevity/longevity-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7b6252df-9da0-4da6-ab26-d1c35806df1c`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7b6252df-9da0-4da6-ab26-d1c35806df1c)
- Show all stored logs command: `$ hydra investigate show-logs 7b6252df-9da0-4da6-ab26-d1c35806df1c`

## Logs:
- **db-cluster-7b6252df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/db-cluster-7b6252df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/db-cluster-7b6252df.tar.gz)
- **sct-runner-events-7b6252df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/sct-runner-events-7b6252df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/sct-runner-events-7b6252df.tar.gz)
- **sct-7b6252df.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/sct-7b6252df.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/sct-7b6252df.log.tar.gz)
- **loader-set-7b6252df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/loader-set-7b6252df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/loader-set-7b6252df.tar.gz)
- **monitor-set-7b6252df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/monitor-set-7b6252df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/monitor-set-7b6252df.tar.gz)
- **parallel-timelines-report-7b6252df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/parallel-timelines-report-7b6252df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/parallel-timelines-report-7b6252df.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-6.1/job/longevity/job/longevity-100gb-4h-test/6/)
[Argus](https://argus.scylladb.com/test/2cca5979-f5f4-424b-9967-7f79e7d6be4c/runs?additionalRuns[]=7b6252df-9da0-4da6-ab26-d1c35806df1c)
</details>

**Comment by denesb** [comment] 2024-08-07 06:46
@lkshminarayanan please have a look. The sstable is written by streaming, its filter is resized and looks like reshape and scrub potentially raced on processing it and scrub lost, (but reshape failed as well).
Maybe we have a missing exclusion of scrub with reshape? They should not be able to both pick the same sstable.

**Comment by fruch** [comment] 2024-09-12 09:19
Seen again tonight on master run:

## Packages

Scylla version: `6.2.0~dev-20240911.31ea74b96e11` with build-id `2c0644388bc491394d7f35af4a7242c7f60c7eec`

Kernel Version: `6.8.0-1015-aws`


## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-master-db-node-b86365f5-9 (98.80.69.69 | 10.12.11.199) (shards: 14)
- longevity-100gb-4h-master-db-node-b86365f5-8 (54.152.39.47 | 10.12.8.177) (shards: 14)
- longevity-100gb-4h-master-db-node-b86365f5-7 (54.196.184.13 | 10.12.8.228) (shards: 14)
- longevity-100gb-4h-master-db-node-b86365f5-6 (100.27.191.253 | 10.12.10.21) (shards: 14)
- longevity-100gb-4h-master-db-node-b86365f5-5 (18.209.47.19 | 10.12.11.96) (shards: 14)
- longevity-100gb-4h-master-db-node-b86365f5-4 (44.220.142.167 | 10.12.8.226) (shards: 14)
- longevity-100gb-4h-master-db-node-b86365f5-3 (54.152.35.181 | 10.12.11.229) (shards: 14)
- longevity-100gb-4h-master-db-node-b86365f5-2 (54.90.120.120 | 10.12.9.198) (shards: 14)
- longevity-100gb-4h-master-db-node-b86365f5-1 (3.88.152.188 | 10.12.9.147) (shards: 14)


OS / Image: `ami-09c2290dca4bd6c7a` (aws: undefined_region)

Test: `longevity-100gb-4h-test`
Test id: `b86365f5-0b4c-4455-a635-2e7047fe06ca`
Test name: `scylla-master/longevity/longevity-100gb-4h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/05d619dfa3056595edf9d8e9d2511316636dedfb/test-cases/longevity/longevity-100gb-4h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor b86365f5-0b4c-4455-a635-2e7047fe06ca`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b86365f5-0b4c-4455-a635-2e7047fe06ca)
- Show all stored logs command: `$ hydra investigate show-logs b86365f5-0b4c-4455-a635-2e7047fe06ca`


## Logs:
- **db-cluster-b86365f5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/db-cluster-b86365f5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/db-cluster-b86365f5.tar.gz)
- **sct-runner-events-b86365f5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/sct-runner-events-b86365f5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/sct-runner-events-b86365f5.tar.gz)
- **sct-b86365f5.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/sct-b86365f5.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/sct-b86365f5.log.tar.gz)
- **loader-set-b86365f5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/loader-set-b86365f5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/loader-set-b86365f5.tar.gz)
- **monitor-set-b86365f5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/monitor-set-b86365f5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/monitor-set-b86365f5.tar.gz)
- **parallel-timelines-report-b86365f5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/parallel-timelines-report-b86365f5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b86365f5-0b4c-4455-a635-2e7047fe06ca/20240912_040724/parallel-timelines-report-b86365f5.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h-test/917/)
[Argus](https://argus.scylladb.com/test/f05fea04-eb74-4961-94fb-f71c67df52cb/runs?additionalRuns[]=b86365f5-0b4c-4455-a635-2e7047fe06ca)
</details>

**Comment by lkshminarayanan** [comment] 2024-09-20 15:29
W.r.to the log mentioned in the bug description :

> grep node-7 log for `me-3gi6_01m1_2xvq82lxjicx5boij1`:
> 
> ```
> ...
> Jul 27 00:34:49.500403 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] sstable - Rebuilding bloom filter /var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-Filter.db: resizing bitset from 216 bytes to 40 bytes. sstable origin: streaming
> Jul 27 01:07:19.412452 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] compaction - [Scrub keyspace1.standard1 9265db40-4bb4-11ef-ab93-cf1b23caa2cd] Scrubbing in skip mode [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-Data.db:level=0:origin=streaming]
> Jul 27 01:38:16.820085 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] compaction - [Reshape keyspace1.standard1 e57fac30-4bb8-11ef-ab93-cf1b23caa2cd] Reshaping [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01lt_27axs2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ll_0pi7k2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ld_01aao2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01l4_3i11c2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ku_2pb342lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_04b0_0tktc2lxjicx5boij1-big-Data.db:level=0:origin=repair]
> Jul 27 01:38:16.887069 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] sstable - Unabl
> ```

I can see the scrub finishing successfully; grep node-7 log for compaction id : `9265db40-4bb4-11ef-ab93-cf1b23caa2cd`:

```
Jul 27 01:07:19.435137 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] compaction - [Scrub keyspace1.standard1 9265db40-4bb4-11ef-ab93-cf1b23caa2cd] Finished scrubbing in skip mode 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_0347_2gb0h2lxjicx5boij1-big-Data.db:level=0]. 11kB to 11kB (~95% of original) in 19ms = 622kB/s. ~128 total partitions merged to 24.
```

Here is a summary of events :
| Time | Event 
| --------|---------
| `01:07:11` | CorruptThenScrub nemesis sends the scrub request | 
| `01:07:19.412452` | Scrubbing starts for this particular sstable with id `me-3gi6_01m1_2xvq82lxjicx5boij1` </br></br> [Scrub keyspace1.standard1 9265db40-4bb4-11ef-ab93-cf1b23caa2cd] Scrubbing in skip mode [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/**me-3gi6_01m1_2xvq82lxjicx5boij1**-big-Data.db:level=0:origin=streaming] 
| `01:07:19.435137` | Scrubbing completes </br></br> [Scrub keyspace1.standard1 9265db40-4bb4-11ef-ab93-cf1b23caa2cd] Finished scrubbing in skip mode 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_0347_2gb0h2lxjicx5boij1-big-Data.db:level=0]. 11kB to 11kB (~95% of original) in 19ms = 622kB/s. ~128 total partitions merged to 24.
| `01:07:55` | CorruptThenScrub nemesis reports an error that occurred when the scrub was attempting to create a snapshot but failed due to a Data.db file missing. But infact the same Data.db file was scrubbed above <br/><br/> error executing GET request to http://localhost:10000/storage_service/keyspace_scrub/keyspace1 with parameters {"scrub_mode": "SKIP"}: remote replied with status code 500 Internal Server Error: <br/>std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: link failed: No such file or directory [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/**me-3gi6_01m1_2xvq82lxjicx5boij1**-big-TOC.txt] [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/snapshots/pre-scrub-1722042466796/**me-3gi6_01m1_2xvq82lxjicx5boij1**-big-TOC.txt.tmp])
| `01:38:16.820085` | A Reshape begins whose input sstable list includes the sstable which was scrubbed above. <br/><br/>compaction - [Reshape keyspace1.standard1 e57fac30-4bb8-11ef-ab93-cf1b23caa2cd] Reshaping [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01lt_27axs2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ll_0pi7k2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/**me-3gi6_01m1_2xvq82lxjicx5boij1**-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ld_01aao2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01l4_3i11c2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ku_2pb342lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_04b0_0tktc2lxjicx5boij1-big-Data.db:level=0:origin=repair]
| `01:38:16.887069` | The reshape fails as the sstable doesn't exist. <br/><br/> sstable - Unable to delete /var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/**me-3gi6_01m1_2xvq82lxjicx5boij1**-big-TOC.txt because it doesn't exist.

The issue here seems to be that the first scrub succeeds but a second scrub (is it intended?) and an other reshape end up trying to read the sstable that was previously scrubbed. I checked the code and ran some trials but I was never able to reproduce such a scenario. cc @raphaelsc I need some help with this. How does one end up with a scenario like the one I have explained above? Where should I look into and how can I try reproduce this locally?

@enaydanov Looking at the [CorruptThenScrub](https://github.com/scylladb/scylla-cluster-tests/blob/447dff1e56bebb0f37d42588a09d3f6e0b24a5f8/sdcm/nemesis.py#L4026) implementation, it doesn't seem to do much other than just issuing a scrub command and then clearing the snapshots once scrub succeeds. But, why doesn't it do any corruption before scrubbing? Is this another bug? (or) Do we load the corrupted sstables from somewhere and run the test on them?

**Comment by lkshminarayanan** [comment] 2024-10-07 06:52
> [@lkshminarayanan](https://github.com/lkshminarayanan) it might be a race between off-strategy compaction (see offstrategy_compaction_task_executor) and scrub. off-strategy is triggered by reshape. so it can be that reshape (part of off-strategy) and scrub working on the same files at the same time. can you verify that from the logs?

@raphaelsc Hi! The issue turned out to be with scrub. When scrub picks up an sstable that is in the maintenance_sstable_set, the sstable is never removed from the set once scrub completes. So when a reshape starts after sometime, the original sstable is still in maintenance set, so reshape picks it up but then fails to find the sstable on disk as it was already scrubbed. I'm working on a fix to ensure the original sstable gets removed from the maintenance_sstable_set once scrub completes.

**Comment by raphaelsc** [comment] 2024-10-07 14:29
> > [@lkshminarayanan](https://github.com/lkshminarayanan) it might be a race between off-strategy compaction (see offstrategy_compaction_task_executor) and scrub. off-strategy is triggered by reshape. so it can be that reshape (part of off-strategy) and scrub working on the same files at the same time. can you verify that from the logs?
> 
> [@raphaelsc](https://github.com/raphaelsc) Hi! The issue turned out to be with scrub. When scrub picks up an sstable that is in the maintenance_sstable_set, the sstable is never removed from the set once scrub completes. So when a reshape starts after sometime, the original sstable is still in maintenance set, so reshape picks it up but then fails to find the sstable on disk as it was already scrubbed. I'm working on a fix to ensure the original sstable gets removed from the maintenance_sstable_set once scrub completes.

nice. good catch.

**Comment by timtimb0t** [comment] 2024-11-18 11:48
issue reproduced on this run (# 10):    
https://argus.scylladb.com/tests/scylla-cluster-tests/830b7b67-6be3-4fd3-98b8-235e4c353b71

**Closed** 2024-12-02 19:48 UTC
Labels: area/nodetool, area/sstable, backport/6.1, backport/6.2
