### ISSUE TITLE
test_group0_schema_versioning seems to be flaky

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18882] opened 2024-05-27 06:55 UTC
At least locally for me, when I run ./test.py --mode=dev I see quite frequent failures of test_group0_schema_versioning.

For example:
```
=================================== FAILURES ===================================
_____________________ test_schema_versioning_with_recovery _____________________

manager = <test.pylib.manager_client.ManagerClient object at 0x7fafb3698550>

    @pytest.mark.asyncio
    async def test_schema_versioning_with_recovery(manager: ManagerClient):
        """
        Perform schema changes while mixing nodes in RECOVERY mode with nodes in group 0 mode.
        Schema changes originating from RECOVERY node use digest-based schema versioning.
        Schema changes originating from group 0 nodes use persisted versions committed through group 0.
    
        Verify that schema versions are in sync after each schema change.
        """
        cfg = {'enable_user_defined_functions': False,
               'force_gossip_topology_changes': True}
        logger.info("Booting cluster")
        servers = [await manager.server_add(config=cfg) for _ in range(3)]
        cql = manager.get_cql()
        hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
    
        logger.info("Creating keyspace and table")
        await cql.run_async("create keyspace ks with replication = "
                            "{'class': 'NetworkTopologyStrategy', 'replication_factor': 3}")
        await verify_table_versions_synced(cql, hosts)
        await cql.run_async("create table ks.t (pk int primary key)")
    
        logger.info("Waiting for driver")
        await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
    
        await verify_table_versions_synced(cql, hosts)
        ks_t_version = await get_scylla_tables_version(cql, hosts[0], 'ks', 't')
        assert ks_t_version
    
        logs = [await manager.server_open_log(srv.server_id) for srv in servers]
        marks = [await log.mark() for log in logs]
    
        logger.info("Altering table")
        await cql.run_async("alter table ks.t with comment = ''")
    
        await verify_table_versions_synced(cql, hosts)
        await verify_in_memory_table_versions(servers, logs, marks)
    
        new_ks_t_version = await get_scylla_tables_version(cql, hosts[0], 'ks', 't')
        assert new_ks_t_version
        assert new_ks_t_version != ks_t_version
        ks_t_version = new_ks_t_version
    
        # We still have a group 0 majority, don't do this at home.
        srv1 = servers[0]
        logger.info(f"Rebooting {srv1} in RECOVERY mode")
        h1 = next(h for h in hosts if h.address == srv1.ip_addr)
        await cql.run_async("update system.scylla_local set value = 'recovery' where key = 'group0_upgrade_state'", host=h1)
        await manager.server_restart(srv1.server_id)
    
        cql = await reconnect_driver(manager)
        logger.info(f"Waiting for driver")
        await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
    
        await verify_table_versions_synced(cql, hosts)
    
        # We're doing a schema change on RECOVERY node while we have two nodes running in group 0 mode.
        # Don't do this at home.
        #
        # Now, the two nodes are not doing any schema changes right now, so this doesn't actually break anything:
        # the RECOVERY node is operating using the old schema change procedure, which means
        # that it pushes the schema mutations to other nodes directly with RPC, modifying
        # the group 0 state machine on other two nodes.
        #
        # There is one problem with this however. If the RECOVERY node considers some other node
        # as DOWN, it will silently *not* push the schema change, completing the operation
        # "successfully" nevertheless (it will return to the driver without error).
        # Usually in this case we rely on eventual convergence of schema through gossip,
        # which will not happen here, because the group 0 nodes are not doing schema pulls!
        # So we need to make sure that the RECOVERY node sees the other nodes as UP before
        # we perform the schema change, so it pushes the mutations to them.
        logger.info(f"Waiting until RECOVERY node ({srv1}) sees other servers as UP")
        await manager.server_sees_others(srv1.server_id, 2)
    
        marks = [await log.mark() for log in logs]
        logger.info(f"Altering table on RECOVERY node ({srv1})")
        await cql.run_async("alter table ks.t with comment = ''", host=h1)
    
        await verify_table_versions_synced(cql, hosts)
        await verify_in_memory_table_versions(servers, logs, marks)
    
        new_ks_t_version = await get_scylla_tables_version(cql, hosts[0], 'ks', 't')
        assert not new_ks_t_version
        ks_t_version = new_ks_t_version
    
        logger.info(f"Stopping {srv1} gracefully")
        await manager.server_stop_gracefully(srv1.server_id)
    
        srv2 = servers[1]
        logger.info(f"Waiting until {srv2} sees {srv1} as dead")
        await manager.server_not_sees_other_server(srv2.ip_addr, srv1.ip_addr)
    
        # Now we modify schema through group 0 while the RECOVERY node is dead.
        # Don't do this at home.
        marks = [await log.mark() for log in logs]
        h2 = next(h for h in hosts if h.address == srv2.ip_addr)
        logger.info(f"Altering table on group 0 node {srv2}")
        await cql.run_async("alter table ks.t with comment = ''", host=h2)
    
        await manager.server_start(srv1.server_id)
        cql = await reconnect_driver(manager)
        logger.info(f"Waiting for driver")
        await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
    
        logger.info(f"Waiting until {srv2} sees {srv1} as UP")
        await manager.server_sees_other_server(srv2.ip_addr, srv1.ip_addr)
    
        # The RECOVERY node will pull schema when it gets a write.
        # The other group 0 node will do a barrier so it will also sync schema before the write returns.
        logger.info("Forcing schema sync through CL=ALL INSERT")
        await cql.run_async(SimpleStatement("insert into ks.t (pk) values (0)", consistency_level=ConsistencyLevel.ALL),
                            host=h2)
    
>       await verify_table_versions_synced(cql, hosts)

test/topology_custom/test_group0_schema_versioning.py:230: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology_custom/test_group0_schema_versioning.py:88: in verify_table_versions_synced
    await verify_local_schema_versions_synced(cql, hs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cql = <cassandra.cluster.Session object at 0x7fafb2bc9a90>
hs = [<Host: 127.173.226.17:9042 datacenter1>, <Host: 127.173.226.22:9042 datacenter1>, <Host: 127.173.226.25:9042 datacenter1>]

    async def verify_local_schema_versions_synced(cql: Session, hs: list[Host]) -> None:
        versions = {h: await get_local_schema_version(cql, h) for h in hs}
        logger.info(f"system.local schema_versions: {versions}")
        h1, v1 = next(iter(versions.items()))
        for h, v in versions.items():
            if v != v1:
>               pytest.fail(f"{h1}'s system.local schema_version {v1} is different than {h}'s version {v}")
E               Failed: 127.173.226.17:9042's system.local schema_version 6a685cd0-f95f-331a-ab70-f86e7e3716fb is different than 127.173.226.22:9042's version adbd78fe-1bf2-11ef-0a6c-6c2737c15055

test/topology_custom/test_group0_schema_versioning.py:61: Failed
```

[logs.tar.gz](https://github.com/scylladb/scylladb/files/15452007/logs.tar.gz)

**Comment by bhalevy** [comment] 2024-05-28 05:49
Cc @kostja

**Comment by kbr-scylla** [comment] 2024-09-20 10:21
Looks like a duplicate of https://github.com/scylladb/scylladb/issues/18156
Again -- is this vanilla, no local changes etc.?
Let's discuss it on the original issue if needed.
(But this issue was opened way back in May, and not attended since then, so it's probably irrelevant at this point.)

**Closed by kbr-scylla** 2024-09-20 10:21 UTC
