### ISSUE TITLE
`system_auth` repair constantly fails ad infinitum: `Semaphore timed out: _streaming_concurrency_sem`

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylladb#12320] opened 2022-12-14 17:41 UTC
## Installation details

Kernel Version: 5.15.0-1026-aws
Scylla version (or git commit hash): `5.2.0~dev-20221208.a076ceef97d5` with build-id `020ec076898a692651fd48edfb1920fc190cd81e`
### This run has raft enabled

Cluster size: 5 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-mv-si-4d-master-db-node-4707c79d-9 (176.34.92.232 | 10.4.0.209) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-8 (34.244.93.89 | 10.4.1.45) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-7 (52.50.69.186 | 10.4.1.90) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-6 (54.171.254.242 | 10.4.2.43) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-5 (52.214.128.170 | 10.4.2.65) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-4 (54.154.213.23 | 10.4.1.120) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-3 (54.194.17.190 | 10.4.2.132) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-2 (52.50.206.221 | 10.4.1.4) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-15 (18.202.225.236 | 10.4.2.60) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-14 (3.250.26.133 | 10.4.3.129) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-13 (3.250.82.39 | 10.4.1.58) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-12 (52.208.247.192 | 10.4.0.45) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-11 (34.247.167.26 | 10.4.2.143) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-10 (34.251.29.135 | 10.4.2.44) (shards: 14)
- longevity-mv-si-4d-master-db-node-4707c79d-1 (34.242.4.152 | 10.4.1.22) (shards: 14)

OS / Image: `ami-063cdd564cd2fbe46` (aws: eu-west-1)

Test: `longevity-mv-si-4days-test`
Test id: `4707c79d-336d-4d20-af8c-a7b3a0992a8d`
Test name: `scylla-master/raft/longevity-mv-si-4days-test`
Test config file(s):

- [longevity-mv-si-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9dd49aca98a05dcf3322aa525bd15abc2307f932/test-cases/longevity/longevity-mv-si-4days.yaml)

## Issue description

This issue seem to be a reappearing of https://github.com/scylladb/scylladb/issues/11552, https://github.com/scylladb/scylladb/issues/11223 and https://github.com/scylladb/scylladb/issues/9751.

At `2022-12-09 18:59:45.812`, a (manager) repair has been initiated. At the time, the living nodes were nodes 1-5. Nodes 2, 4 and 5 don't seem to have experienced any issue with the repair.
Node 1, however, constently fails with semaphore timeouts when trying to run a repair on the table `role_attributes` in the `system_auth` keyspace:
```
2022-12-09T19:32:24+00:00 longevity-mv-si-4d-master-db-node-4707c79d-1  !WARNING | scylla[5468]:  [shard 12] repair - Failed to read a fragment from the reader, keyspace=system_auth, table=role_attributes, range=[{6813710496591431170, end}, {6815627321135889364, end}]: seastar::named_semaphore_timed_out (Semaphore timed out: _streaming_concurrency_sem)
2022-12-09T19:32:24+00:00 longevity-mv-si-4d-master-db-node-4707c79d-1     !INFO | scylla[5468]:  [shard  2] reader_concurrency_semaphore - Semaphore _streaming_concurrency_sem with 10/10 count and 163840/170959831 memory resources: timed out, dumping permit diagnostics:
permits count   memory  table/description/state
6       6       96K     system_traces.sessions_time_idx/repair-meta/active/unused
4       4       64K     system_distributed.view_build_status/repair-meta/active/unused
2       0       0B      system_distributed.view_build_status/repair-meta/waiting
6       0       0B      system_auth.role_attributes/repair-meta/active/unused
2       0       0B      system_auth.role_attributes/shard-reader/waiting

20      10      160K    total

Total: 20 permits with 10 count and 160K memory resources
2022-12-09T19:32:24+00:00 longevity-mv-si-4d-master-db-node-4707c79d-1  !WARNING | scylla[5468]:  [shard  5] repair - Failed to read a fragment from the reader, keyspace=system_auth, table=role_attributes, range=[{6813710496591431170, end}, {6815627321135889364, end}]: seastar::named_semaphore_timed_out (Semaphore timed out: _streaming_concurrency_sem)
2022-12-09T19:32:24+00:00 longevity-mv-si-4d-master-db-node-4707c79d-1     !INFO | scylla[5468]:  [shard  5] reader_concurrency_semaphore - Semaphore _streaming_concurrency_sem with 10/10 count and 163840/170959831 memory resources: timed out, dumping permit diagnostics:
permits count   memory  table/description/state
6       6       96K     system_traces.sessions_time_idx/repair-meta/active/unused
4       4       64K     system_distributed.view_build_status/repair-meta/active/unused
1       0       0B      system_auth.role_attributes/shard-reader/waiting
2       0       0B      system_distributed.view_build_status/repair-meta/waiting
2       0       0B      system_auth.role_attributes/repair-meta/waiting
4       0       0B      system_auth.role_attributes/repair-meta/active/unused

19      10      160K    total

Total: 19 permits with 10 count and 160K memory resources
2022-12-09T19:32:24+00:00 longevity-mv-si-4d-master-db-node-4707c79d-1  !WARNING | scylla[5468]:  [shard  0] repair - Failed to read a fragment from the reader, keyspace=system_auth, table=role_attributes, range=[{6598709756370372952, end}, {6599723288536737603, end}]: seastar::named_semaphore_timed_out (Semaphore timed out: _streaming_concurrency_sem)
2022-12-09T19:32:24+00:00 longevity-mv-si-4d-master-db-node-4707c79d-1     !INFO | scylla[5468]:  [shard 13] reader_concurrency_semaphore - Semaphore _streaming_concurrency_sem with 10/10 count and 163840/170959831 memory resources: timed out, dumping permit diagnostics:
permits count   memory  table/description/state
5       5       80K     system_distributed.view_build_status/repair-meta/active/unused
5       5       80K     system_traces.sessions_time_idx/repair-meta/active/unused
1       0       0B      system_distributed.view_build_status/repair-meta/waiting
4       0       0B      system_auth.role_attributes/shard-reader/waiting
6       0       0B      system_auth.role_attributes/repair-meta/active/unused

21      10      160K    total
```

This error persists constantly, for 24 hours (at half hour intervals, since the repair has a 30m timeout). The only reason it has stopped is because node 3 was terminated (due to a different nemesis).

At the same time, node 3 failed fails with the same error:
```
2022-12-09T19:32:25+00:00 longevity-mv-si-4d-master-db-node-4707c79d-3  !WARNING | scylla[54637]:  [shard 12] repair - repair[36bc10cd-5e8c-44c4-b47f-36a825efc2b9]: shard=12, keyspace=system_auth, cf=role_attributes, range=(6813710496591431170, 6815627321135889364], got error in row level repair: seastar::rpc::remote_verb_error (Semaphore timed out: _streaming_concurrency_sem)
2022-12-09T19:32:25+00:00 longevity-mv-si-4d-master-db-node-4707c79d-3  !WARNING | scylla[54637]:  [shard  5] repair - repair[36bc10cd-5e8c-44c4-b47f-36a825efc2b9]: shard=5, keyspace=system_auth, cf=role_attributes, range=(6813710496591431170, 6815627321135889364], got error in row level repair: seastar::rpc::remote_verb_error (Semaphore timed out: _streaming_concurrency_sem)
2022-12-09T19:32:25+00:00 longevity-mv-si-4d-master-db-node-4707c79d-3  !WARNING | scylla[54637]:  [shard  0] repair - repair[36bc10cd-5e8c-44c4-b47f-36a825efc2b9]: shard=0, keyspace=system_auth, cf=role_attributes, range=(6598709756370372952, 6599723288536737603], got error in row level repair: seastar::rpc::remote_verb_error (Semaphore timed out: _streaming_concurrency_sem)
```
Similarly, the only reason the timeouts have stopped is because the node was terminated at `2022-12-10T19:12:16` (due to a different nemesis).

**It's imporant to note** that even after the nemesis timed out, the repair task was not killed, which is why the repair continues after `2022-12-10 19:00:23.105`. But since the nemesis threads keep running afterwards, node 3 was terminated, which leads to such errors:
```
2022-12-10T19:38:32+00:00 longevity-mv-si-4d-master-db-node-4707c79d-4  !WARNING | scylla[822]:  [shard  0] repair - repair[e7db93fb-c733-4627-8aca-4f95999f5d64]: Failed to process repair_flush_hints_batchlog_request from node=10.4.1.22, target_hosts=[10.4.2.132, 10.4.2.65, 10.4.1.22], seastar::timed_out_error (timedout)
2022-12-10T19:38:32+00:00 longevity-mv-si-4d-master-db-node-4707c79d-4  !WARNING | scylla[822]:  [shard  0] repair - repair[da4d9299-cc4b-4f2c-ade0-7c76f66901a8]: Failed to process repair_flush_hints_batchlog_request from node=10.4.1.22, target_hosts=[10.4.2.132, 10.4.2.65, 10.4.1.22], seastar::timed_out_error (timedout)
2022-12-10T19:38:32+00:00 longevity-mv-si-4d-master-db-node-4707c79d-4  !WARNING | scylla[822]:  [shard  0] repair - repair[2873cf45-3d27-438a-b906-1d60da5568f3]: Failed to process repair_flush_hints_batchlog_request from node=10.4.1.22, target_hosts=[10.4.2.132, 10.4.2.65, 10.4.1.22], seastar::timed_out_error (timedout)
```
Every error that appears after this point as part of this repair should be disregarded as a result of a probable nemesis.

Later in the run, at `2022-12-12 06:23:57.064`, an identical repair has started. It ended successfully in 17 minutes. At the time of this repair, the nodes that were alive are 1 (one of the faulty nodes from the previous repair), 7, 9, 10 and 11.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 4707c79d-336d-4d20-af8c-a7b3a0992a8d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=4707c79d-336d-4d20-af8c-a7b3a0992a8d)
- Show all stored logs command: `$ hydra investigate show-logs 4707c79d-336d-4d20-af8c-a7b3a0992a8d`

## Logs:
- **db-cluster-4707c79d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/db-cluster-4707c79d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/db-cluster-4707c79d.tar.gz)
- **monitor-set-4707c79d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/monitor-set-4707c79d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/monitor-set-4707c79d.tar.gz)
- **loader-set-4707c79d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/loader-set-4707c79d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/loader-set-4707c79d.tar.gz)
- **normal-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/normal-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/normal-4707c79d.log.tar.gz)
- **summary-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/summary-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/summary-4707c79d.log.tar.gz)
- **events-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/events-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/events-4707c79d.log.tar.gz)
- **output-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/output-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/output-4707c79d.log.tar.gz)
- **debug-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/debug-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/debug-4707c79d.log.tar.gz)
- **sct-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/sct-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/sct-4707c79d.log.tar.gz)
- **error-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/error-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/error-4707c79d.log.tar.gz)
- **critical-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/critical-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/critical-4707c79d.log.tar.gz)
- **raw_events-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/raw_events-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/raw_events-4707c79d.log.tar.gz)
- **warning-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/warning-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/warning-4707c79d.log.tar.gz)
- **email_data-4707c79d.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/email_data-4707c79d.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/email_data-4707c79d.json.tar.gz)
- **argus-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/argus-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/argus-4707c79d.log.tar.gz)
- **left_processes-4707c79d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/left_processes-4707c79d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4707c79d-336d-4d20-af8c-a7b3a0992a8d/20221213_061451/left_processes-4707c79d.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/raft/job/longevity-mv-si-4days-test/3/)

**Comment by eliransin** [comment] 2023-01-11 08:33
> 2022-12-09T19:32:24+00:00 longevity-mv-si-4d-master-db-node-4707c79d-1  !WARNING | scylla[5468]:  [shard 12] repair - Failed to read a fragment from the reader, keyspace=system_auth, table=role_attributes, range=[{6813710496591431170, end}, {6815627321135889364, end}]: seastar::named_semaphore_timed_out (Semaphore timed out: _streaming_concurrency_sem)
> 2022-12-09T19:32:24+00:00 longevity-mv-si-4d-master-db-node-4707c79d-1     !INFO | scylla[5468]:  [shard  2] reader_concurrency_semaphore - Semaphore _streaming_concurrency_sem with 10/10 count and 163840/170959831 memory resources: timed out, dumping permit diagnostics:
> permits count   memory  table/description/state
> 6       6       96K     system_traces.sessions_time_idx/repair-meta/active/unused
> 4       4       64K     system_distributed.view_build_status/repair-meta/active/unused
> 2       0       0B      system_distributed.view_build_status/repair-meta/waiting
> 6       0       0B      system_auth.role_attributes/repair-meta/active/unused
> 2       0       0B      system_auth.role_attributes/shard-reader/waiting
> 
> 20      10      160K    total

@denesb does it make any sense for the semaphore to timeout, it looks like the permit limit or memory haven't been reached.

**Comment by eliransin** [comment] 2023-01-11 08:34
@denesb scratch that, I see that this semaphore's limit is 10 and not 100

**Comment by eliransin** [comment] 2023-01-11 08:36
AFAICS there is a view_building table repair going on in parallel.
@denesb a new question, why did the unused readers weren't evicted in this case?

**Comment by denesb** [comment] 2023-01-11 08:41
Unused readers are not inactive readers. It just an unfortunate naming that is going to be fixed soon.

**Comment by denesb** [comment] 2023-01-11 08:41
Th real question here is why are auth queries executed in the streaming scheduling group?

**Comment by denesb** [comment] 2023-01-11 08:43
Notice how all other reads belong to repair (description = repair-meta), but the ones for auth are shard readers, meaning they are a regular range scan.

**Comment by denesb** [comment] 2023-01-11 08:44
Actually they can also be part of a multishard repair reader. Does the cluster has mismatching shard counts?

**Comment by fruch** [comment] 2023-02-01 22:35
> Actually they can also be part of a multishard repair reader. Does the cluster has mismatching shard counts?

No, you can see in the description that all nodes has 14 shards

**Comment by DoronArazii** [comment] 2023-05-09 16:24
@eliransin / @asias can you please assess if it's feasible to fix it for 5.3

**Comment by denesb** [comment] 2023-05-10 05:29
We first have to find out what the cause is.
My initial suspect is https://github.com/scylladb/scylladb/issues/12693. @ShlomiBalalis does this issue still reproduce with recent 5.2/master?

Another improvement that could help is https://github.com/scylladb/scylladb/issues/13547. The current count amount of 10 for repairs proved too restrictive over and over again.

**Comment by eliransin** [comment] 2023-06-11 08:49
@ShlomiBalalis ping :point_up_2:

**Comment by mykaul** [comment] 2023-06-27 12:37
> @denesb I examined several longevity jobs in master, 5.2 and 2023.1 and it was not reproduced again in any of them.

Closing - I think we've seen several times we have a problem with repairing system_auth (just found more of those). I'm unsure we need to keep this one opened if we don't have a reproduction in newer versions.

**Closed by mykaul** 2023-06-27 12:37 UTC
Labels: repair, Master/Triage, Pending-QA-Reproduction
