### ISSUE TITLE
[DTEST][DEBUG]: Error 'applier fiber stopped because of the error:  Operation failed for system.scylla_local'  found log for test_parallel_operations_create_list_clear_for_all_ks

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#20215] opened 2024-08-20 06:52 UTC
Dtest run: https://jenkins.scylladb.com/view/scylla-6.0/job/scylla-6.0/job/dtest-debug/24/testReport/snapshot_test/TestParallelSnapshotOperations/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split011___test_parallel_operations_create_list_clear_for_all_ks/ failed with error found in log on teardown:

```
failed on teardown with "AssertionError: Unexpected errors found:
node1: 2 errors
ERROR 2024-08-11 17:20:45,747 [shard 0: gms] storage_proxy - exception during mutation write to 127.0.15.1: utils::internal::nested_exception<std::runtime_error> (Could not write mutation system:scylla_local (pk{0010656e61626c65645f6665617475726573}) to commitlog): seastar::gate_closed_exception (gate closed)
ERROR 2024-08-11 17:20:45,748 [shard 0: gms] raft - [28fa36d8-fe84-4ee9-bf15-9cbf4641961a] applier fiber stopped because of the error: std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1339): exceptions::mutation_write_failure_exception (Operation failed for system.scylla_local - received 0 responses and 1 failures from 1 CL=ONE.)"
```
Scylla version 6.0.3-0.20240808.a56f7ce21ad4 with build-id 66a8b676ee9e21374a3b46538c930879e592260f 
[logs-full.debug.011.zip](https://github.com/user-attachments/files/16670222/logs-full.debug.011.zip)

**Comment by aleksbykov** [comment] 2024-08-20 07:25
Similar issue found in logs for test: [Run Dtest Parallel Cloud Machines / FullDtest / full-split003 / schema_test.TestSchema.test_restart_with_large_tables](https://jenkins.scylladb.com/view/scylla-6.0/job/scylla-6.0/job/dtest-debug/24/testReport/schema_test/TestSchema/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split003___test_restart_with_large_tables/)

**Comment by kostja** [comment] 2024-08-20 20:05
@kbr-scylla are we stopping raft first or commitlog first during shutdown?

**Comment by kbr-scylla** [comment] 2024-08-21 09:12
> @kbr-scylla are we stopping raft first or commitlog first during shutdown?

Answered by Piotr here:

https://github.com/scylladb/scylladb/issues/19665#issuecomment-2227915506

**Comment by kbr-scylla** [comment] 2024-08-21 09:14
Different test, but same root cause.
Closing as duplicate of https://github.com/scylladb/scylladb/issues/19665

**Closed by kbr-scylla** 2024-08-21 09:14 UTC
Labels: area/raft
