### ISSUE TITLE
test_auth_v2_migration is flaky

### ISSUE THREAD

**Issue by nuivall** [scylladb/scylladb#18931] opened 2024-05-28 09:47 UTC
```
    async def warmup_v1_static_values(manager: ManagerClient, hosts):
        # auth-v1 was using statics to cache internal queries
        # in auth-v2 those statics were removed but we want to
        # verify that it was effective so trigger here internal
        # call to potentially populate static storage and we'll
        # verify later that after migration properly formed query
        # executes (query has to change because keyspace name changes)
        cql = manager.get_cql()
>       await asyncio.gather(*(cql.run_async("LIST ROLES", host=host) for host in hosts))
E       cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Role deleted_user doesn't exist."
```

**Comment by nyh** [comment] 2024-06-18 10:13
Seen again in CI https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9724/testReport/junit/(root)/test_auth_v2_migration/Tests___Unit_Tests___test_auth_v2_migration_debug_1/
```
request = <FixtureRequest for <Function test_auth_v2_migration>>
manager = <test.pylib.manager_client.ManagerClient object at 0x7f5f9b8d31d0>

    @pytest.mark.asyncio
    async def test_auth_v2_migration(request, manager: ManagerClient):
        # First, force the first node to start in legacy mode
        cfg = {'force_gossip_topology_changes': True}
    
        servers = [await manager.server_add(config=cfg)]
        # Enable raft-based node operations for subsequent nodes - they should fall back to
        # using gossiper-based node operations
        del cfg['force_gossip_topology_changes']
    
        servers += [await manager.server_add(config=cfg) for _ in range(2)]
        cql = manager.cql
        assert(cql)
    
        logging.info("Waiting until driver connects to every server")
        hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
    
        logging.info("Checking the upgrade state on all nodes")
        for host in hosts:
            status = await manager.api.raft_topology_upgrade_status(host.address)
            assert status == "not_upgraded"
    
        await populate_auth_v1_data(manager)
>       await warmup_v1_static_values(manager, hosts)

test/auth_cluster/test_auth_v2_migration.py:153: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

manager = <test.pylib.manager_client.ManagerClient object at 0x7f5f9b8d31d0>
hosts = [<Host: 127.247.13.9:9042 datacenter1>, <Host: 127.247.13.10:9042 datacenter1>, <Host: 127.247.13.14:9042 datacenter1>]

    async def warmup_v1_static_values(manager: ManagerClient, hosts):
        # auth-v1 was using statics to cache internal queries
        # in auth-v2 those statics were removed but we want to
        # verify that it was effective so trigger here internal
        # call to potentially populate static storage and we'll
        # verify later that after migration properly formed query
        # executes (query has to change because keyspace name changes)
        cql = manager.get_cql()
>       await asyncio.gather(*(cql.run_async("LIST ROLES", host=host) for host in hosts))
E       cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Role deleted_user doesn't exist."

test/auth_cluster/test_auth_v2_migration.py:81: InvalidRequest
```

**Comment by mykaul** [comment] 2024-06-18 11:08
We've seen it few times in CI already - let's prioritize fixing this.

**Comment by nyh** [comment] 2024-06-18 11:25
> We've seen it few times in CI already - let's prioritize fixing this.

Also note that there are two more issues about the flakiness of this test - https://github.com/scylladb/scylladb/issues/18319 and https://github.com/scylladb/scylladb/issues/19039 - the error messages look different so I don't know if they are the same problem or different problems.

**Comment by ptrsmrn** [comment] 2024-07-05 09:55
We lack data to resolve this issue. https://github.com/scylladb/scylladb/commit/f9abe52d3bd8ad2c7f47031ce57773afb5d8367b should help us better understand what's the root cause. For now I'm closing the ticket, we can reopen if the failure reappears.

**Closed by ptrsmrn** 2024-07-05 09:55 UTC
Labels: area/test, P1, symptom/ci stability, area/authentication
