### ISSUE TITLE
test/boost/multishard_mutation_query_test: fuzzy_test failed: got 1 more partitions than expected, extra partitions

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#12944] opened 2023-02-21 07:38 UTC
Seen in https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4515.
Build types: release.
Randoms seed: 3159671744.
Reproduces with the above seed on master (d7b6cf045fbfcb75cee361fbb9466b5b60871029).

**Comment by denesb** [comment] 2023-02-21 08:49
The bug is in the test code. The scan includes an empty mutation, which the test code expects to not be in the result.
All this code is completely rewritten by https://github.com/scylladb/scylladb/pull/12574, so there is no point in trying to fix it.

**Comment by nyh** [comment] 2023-02-21 08:57
Reopening because the issue is still hopen and can happen again... Botond, if you believe that this test is fixed by #12574, please add a Fixes there instead of closing the issue before it's fixed.

**Comment by denesb** [comment] 2023-02-21 09:40
> Reopening because the issue is still open and can happen again... Botond, if you believe that this test is fixed by #12574, please add a Fixes there instead of closing the issue before it's fixed.

You are right, I added the Fixes tag to #12574 instead.

**Comment by DoronArazii** [comment] 2023-03-30 12:38
@denesb do we still need to track this?

**Comment by denesb** [comment] 2023-03-30 12:46
> @denesb do we still need to track this?

No, I have a fix for it already: https://github.com/scylladb/scylladb/pull/12574

**Closed** 2023-04-06 22:52 UTC
Labels: CI-Stability

**Comment by denesb** [comment] 2023-12-18 08:38
Test fix, not backporting.
