### ISSUE TITLE
Raft servers constantly switching between dead and alive (in high latency and/or % of packet loss between nodes topology)

### ISSUE THREAD

**Issue by Fornax96** [scylladb/scylladb#16410] opened 2023-12-13 15:48 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.4.0
Cluster size: 10
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 11 and Debian 12

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): Bare metal
Hardware: sockets=1 cores=16 hyperthreading=32 memory=128 GB
Disks: 2x 2 TB NVMe, RAID 1

I recently added a new DC in Tokyo, Japan to my cluster. Since I added the DC my nodes are constantly marking eachother as dead/alive every second. I think it's a latency issue.

I have three datacenters: Germany, Japan and Oregon. The latency between the nodes is as follows:

```
Oregon > Germany: 151ms
Germany > Japan: 230ms
Japan > Oregon: 125ms
```

The logs in Germany look like this:
```
Dec 13 15:43:08 de1 scylla[7521]:  [shard  0:main] raft_group_registry - marking Raft server eabec37b-2677-49e1-a9c8-f8d2e86e9798 as dead for raft groups
Dec 13 15:43:09 de1 scylla[7521]:  [shard  0:main] raft_group_registry - marking Raft server eabec37b-2677-49e1-a9c8-f8d2e86e9798 as alive for raft groups
Dec 13 15:43:11 de1 scylla[7521]:  [shard  0:main] raft_group_registry - marking Raft server eabec37b-2677-49e1-a9c8-f8d2e86e9798 as dead for raft groups
Dec 13 15:43:12 de1 scylla[7521]:  [shard  0:main] raft_group_registry - marking Raft server eabec37b-2677-49e1-a9c8-f8d2e86e9798 as alive for raft groups
Dec 13 15:43:13 de1 scylla[7521]:  [shard  0:main] raft_group_registry - marking Raft server eabec37b-2677-49e1-a9c8-f8d2e86e9798 as dead for raft groups
Dec 13 15:43:14 de1 scylla[7521]:  [shard  0:main] raft_group_registry - marking Raft server eabec37b-2677-49e1-a9c8-f8d2e86e9798 as alive for raft groups
Dec 13 15:43:16 de1 scylla[7521]:  [shard  0:main] raft_group_registry - marking Raft server eabec37b-2677-49e1-a9c8-f8d2e86e9798 as dead for raft groups
Dec 13 15:43:17 de1 scylla[7521]:  [shard  0:main] raft_group_registry - marking Raft server eabec37b-2677-49e1-a9c8-f8d2e86e9798 as alive for raft groups
Dec 13 15:43:19 de1 scylla[7521]:  [shard  0:main] raft_group_registry - marking Raft server eabec37b-2677-49e1-a9c8-f8d2e86e9798 as dead for raft groups
Dec 13 15:43:20 de1 scylla[7521]:  [shard  0:main] raft_group_registry - marking Raft server eabec37b-2677-49e1-a9c8-f8d2e86e9798 as alive for raft groups

eabec37b-2677-49e1-a9c8-f8d2e86e9798 is the node in Japan
```

The logs in Japan look like this:

```
Dec 13 15:44:54 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 237f6b24-cdfb-4688-846b-9d60f50e9b80 as dead for raft groups
Dec 13 15:44:55 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 60910215-705d-4ab5-a8c2-e3053dfe37e3 as alive for raft groups
Dec 13 15:44:55 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 0e4d0408-84c9-4b49-9333-5effce4b6b18 as dead for raft groups
Dec 13 15:44:55 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 237f6b24-cdfb-4688-846b-9d60f50e9b80 as alive for raft groups
Dec 13 15:44:56 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 0e4d0408-84c9-4b49-9333-5effce4b6b18 as alive for raft groups
Dec 13 15:44:56 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 49dd45cd-e3f9-47ef-80c6-13a9c8068583 as dead for raft groups
Dec 13 15:44:56 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 172080a7-a46e-43c7-b061-4fd1426fd2db as dead for raft groups
Dec 13 15:44:56 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 172080a7-a46e-43c7-b061-4fd1426fd2db as alive for raft groups
Dec 13 15:44:56 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 38d96866-2f62-4fa1-bc4c-2e891c509490 as dead for raft groups
Dec 13 15:44:57 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 60910215-705d-4ab5-a8c2-e3053dfe37e3 as dead for raft groups
Dec 13 15:44:57 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 237f6b24-cdfb-4688-846b-9d60f50e9b80 as dead for raft groups
Dec 13 15:44:57 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 60910215-705d-4ab5-a8c2-e3053dfe37e3 as alive for raft groups
Dec 13 15:44:58 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 49dd45cd-e3f9-47ef-80c6-13a9c8068583 as alive for raft groups
Dec 13 15:44:58 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 38d96866-2f62-4fa1-bc4c-2e891c509490 as alive for raft groups
Dec 13 15:44:59 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 49dd45cd-e3f9-47ef-80c6-13a9c8068583 as dead for raft groups
Dec 13 15:44:59 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 0e4d0408-84c9-4b49-9333-5effce4b6b18 as dead for raft groups
Dec 13 15:45:00 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 60910215-705d-4ab5-a8c2-e3053dfe37e3 as dead for raft groups
Dec 13 15:45:00 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 38d96866-2f62-4fa1-bc4c-2e891c509490 as dead for raft groups
Dec 13 15:45:00 jp01 scylla[21057]:  [shard  0:main] raft_group_registry - marking Raft server 60910215-705d-4ab5-a8c2-e3053dfe37e3 as alive for raft groups

These UUIDs are almost exclusively the nodes in Germany
```

The logs in Oregon look like this:
```
Dec 13 15:45:42 pddb-pdx001 scylla[221117]:  [shard  0:main] raft_group_registry - marking Raft server 60910215-705d-4ab5-a8c2-e3053dfe37e3 as dead for raft groups
Dec 13 15:45:43 pddb-pdx001 scylla[221117]:  [shard  0:main] raft_group_registry - marking Raft server 60910215-705d-4ab5-a8c2-e3053dfe37e3 as alive for raft groups
Dec 13 15:45:43 pddb-pdx001 scylla[221117]:  [shard  0:main] raft_group_registry - marking Raft server 172080a7-a46e-43c7-b061-4fd1426fd2db as dead for raft groups
Dec 13 15:45:43 pddb-pdx001 scylla[221117]:  [shard  0:main] raft_group_registry - marking Raft server 49dd45cd-e3f9-47ef-80c6-13a9c8068583 as dead for raft groups
Dec 13 15:45:43 pddb-pdx001 scylla[221117]:  [shard  0:main] raft_group_registry - marking Raft server 49dd45cd-e3f9-47ef-80c6-13a9c8068583 as alive for raft groups
Dec 13 15:45:44 pddb-pdx001 scylla[221117]:  [shard  0:main] raft_group_registry - marking Raft server 172080a7-a46e-43c7-b061-4fd1426fd2db as alive for raft groups
Dec 13 15:45:44 pddb-pdx001 scylla[221117]:  [shard  0:main] raft_group_registry - marking Raft server 49dd45cd-e3f9-47ef-80c6-13a9c8068583 as dead for raft groups
Dec 13 15:45:44 pddb-pdx001 scylla[221117]:  [shard  0:main] raft_group_registry - marking Raft server 49dd45cd-e3f9-47ef-80c6-13a9c8068583 as alive for raft groups
Dec 13 15:45:45 pddb-pdx001 scylla[221117]:  [shard  0:main] raft_group_registry - marking Raft server 60910215-705d-4ab5-a8c2-e3053dfe37e3 as dead for raft groups
Dec 13 15:45:45 pddb-pdx001 scylla[221117]:  [shard  0:main] raft_group_registry - marking Raft server 60910215-705d-4ab5-a8c2-e3053dfe37e3 as alive for raft groups

These happen much less frequently. Mostly with UUIDs from nodes in Germany.
```

Is this behaviour harmful? Is there a config option to tweak?

**Comment by kostja** [comment] 2023-12-22 17:43
This message is printed when the network connection between the two data centers is down and the failure detector can't reach the destination raft node for more than 10 pings.

**Comment by kostja** [comment] 2023-12-22 17:43
Please feel free to reopen if you're certain your network is stable and yet you get these messages.

**Comment by Fornax96** [comment] 2023-12-23 10:31
The network is stable @kostja. There is a little bit of packet loss, but that's to be expected from such a long distance connection. The ping deviation is only 1ms. There is something wrong with the way downtime is detected. The server gets marked down and up *every second*.

![image](https://github.com/scylladb/scylladb/assets/1247928/67125197-ef83-4f61-ae49-55e24dce08cc)

**Comment by mykaul** [comment] 2023-12-24 06:54
I'm not sure, but if I'm reading the packet loss %, they are substantial. Not that I'd trust ping to properly compensate (and therefore to report it), but the numbers are not what I'd expect (high 90's, these days, with TCP being able to recover mostly from simple drops).
Combining those numbers with the latency could explain some of this behavior.

**Comment by kostja** [comment] 2023-12-24 07:28
@Fornax96 It is always a trade off between the tolerance for a bad network and the speed of the failover in case of a real failure. Raft servers ping each other 10 times a second, and if they don't get a response for 10 pings straight, they declare a server down. In your case it's not only he packet loss issue, it's also 300+ms latency that is making a difference. 
Perhaps we could make the ping time and the reaction to latency spikes configurable. I gather it's a reasonable feature request.

@kbr-scylla ^^

However, I can't imagine we can precisely target/address your conditions without having access to your setup or a similar one. At this point I can't see how this set up could be reproduced in a lab.

Could you please tell a bit more about your set up?

And please feel free to reopen the issue as a feature, I'd then also suggest a title change to "Make the direct failure detector thresholds configurable"

**Comment by Fornax96** [comment] 2023-12-24 11:05
@mykaul mtr pings each router between the client and the host, but many routers are configured to only respond to a few percent of pings (usually 10%, but it also depends on load). That's why the routers in the middle show 90% packet loss. The number that matters the most is the last line, that's the host we're pinging. In this case the packet loss is only 3.5% which is actually fairly good. This amount of loss should not cause issues at all.

@kostja When you say 10 times per second, does the target node actually get time to reply? It's impossible to ping a server at the other side of the planet in 100ms. You're limited by the speed of light. The theoretical minimum round trip time for a trip around the earth is 134ms. Since routers add latency the number is always 200ms+ in practice.

What is the actual timeout value for those pings? I recommend setting it to at least 500ms to account for some jitter. If you set it lower than 300ms then scylla can simply not work on an international scale.

**Comment by kostja** [comment] 2023-12-24 11:08
@Fornax96 yes, of course we don't timeout on reply in 100ms, in order to declare a server dead we must have a reply to all pings (no matter when they were sent) missing for 1 second

**Comment by mykaul** [comment] 2023-12-24 11:29
> @mykaul mtr pings each router between the client and the host, but many routers are configured to only respond to a few percent of pings (usually 10%, but it also depends on load). That's why the routers in the middle show 90% packet loss. The number that matters the most is the last line, that's the host we're pinging. In this case the packet loss is only 3.5% which is actually fairly good. This amount of loss should not cause issues at all.

Yes, that's why I don't like ping as a measurement of packet loss :-/

**Comment by kbr-scylla** [comment] 2024-01-02 13:25
Timeout for each ping is 300ms.
We should indeed increase it, and preferably make it configurable, setting the default to 500ms or something.

**Comment by kbr-scylla** [comment] 2024-01-02 13:27
I opened https://github.com/scylladb/scylladb/issues/16607

**Comment by Fornax96** [comment] 2024-02-23 18:06
Is this swapping between raft states actually harmful for my cluster? I have three very expensive servers in Tokyo that I would really like to install Scylla on as soon as possible

**Comment by Fornax96** [comment] 2024-02-23 19:14
![image](https://github.com/scylladb/scylladb/assets/1247928/9fa8e97a-c97f-4dcc-abf2-7a593b091e0c)

This is all they're doing all day

**Comment by kbr-scylla** [comment] 2024-02-25 19:20
> Is this swapping between raft states actually harmful for my cluster?

@Fornax96 if you're not seeing a log message like "gaining leadership" or "losing leadership" appearing periodically on different nodes, then no.

You can also test on your staging cluster whether schema changes (which go through Raft) are working without availability issues -- perform a sequence of 100 schema changes or so (e.g. create and drop type in a loop, you can use a simple bash script which invokes `cqlsh -e 'create type ...'; cqlsh -e 'drop type ...'`), if they all succeed and in reasonable time (each should take probably around a second, up to few seconds, given your high latency environment), you're good to go.

But I believe we should fix the failure detector nevertheless.

**Comment by Fornax96** [comment] 2024-05-02 09:48
@kbr-scylla I do actually regularly see `gaining leadership` and `losing leadersip` messages in the logs regularly. About every 10 seconds on each one of my database servers.

I am also noticing that repairs simply never finish. I have a cron job which periodically runs repairs on all my nodes, but they just keep running indefinitely.

**Comment by kbr-scylla** [comment] 2024-05-06 11:29
@Fornax96 hanging repairs could be https://github.com/scylladb/scylladb/issues/17591, this is fixed in 5.4.5 https://github.com/scylladb/scylladb/commit/e868ade25831aee68da66f742395a96124ab8123 so upgrade your cluster (latest is 5.4.6) and check if repairs keep hanging.

The failure detector issue fix is in review: https://github.com/scylladb/scylladb/pull/18443 I hope it will end up in 5.4.7.

**Comment by Fornax96** [comment] 2024-05-13 08:49
> @Fornax96 hanging repairs could be #17591, this is fixed in 5.4.5 [e868ade](https://github.com/scylladb/scylladb/commit/e868ade25831aee68da66f742395a96124ab8123) so upgrade your cluster (latest is 5.4.6) and check if repairs keep hanging.

Upgrading fixed the issue with hanging repairs.

> The failure detector issue fix is in review: #18443 I hope it will end up in 5.4.7.

Thanks, I'll be keeping an eye out.

**Comment by mykaul** [comment] 2024-05-23 13:53
Why is this still open?

**Comment by kbr-scylla** [comment] 2024-05-23 14:08
I want to close it once @Fornax96 confirms that the issue is fixed, and that can only be done once we release 5.4.7 (we didn't yet -- why? There are many backports sitting on 5.4 branch waiting for release) and @Fornax96 upgrades.

**Comment by kbr-scylla** [comment] 2024-06-06 13:19
@mykaul do you know what's the status of 5.4.7? I see there's `tag: scylla-5.4.7-candidate` but is anything happening to it?

**Comment by mykaul** [comment] 2024-06-06 13:50
> @mykaul do you know what's the status of 5.4.7? I see there's `tag: scylla-5.4.7-candidate` but is anything happening to it?

Already built and will be released next week.

**Comment by kbr-scylla** [comment] 2024-06-12 09:48
@Fornax96 5.4.7 was released, can you upgrade and check if the issue keeps happening?
https://forum.scylladb.com/t/release-scylladb-5-4-7/2153

**Comment by Fornax96** [comment] 2024-06-12 17:02
Just finished upgrading. The issue seems to be resolved.

**Comment by kbr-scylla** [comment] 2024-06-12 17:04
Great, thanks! Closing the issue then.

**Closed by kbr-scylla** 2024-06-12 17:04 UTC
Labels: area/topology changes, area/raft

**Comment by mykaul** [comment] 2024-06-12 19:06
Dis we document this knob?

**Comment by kbr-scylla** [comment] 2024-06-13 09:07
https://opensource.docs.scylladb.com/stable/reference/configuration-parameters.html#confval-direct_failure_detector_ping_timeout_in_ms

This documentation is automatically generated from db/config.cc IIUC

**Comment by mykaul** [comment] 2024-06-13 11:19
> https://opensource.docs.scylladb.com/stable/reference/configuration-parameters.html#confval-direct_failure_detector_ping_timeout_in_ms

I don't think it's good enough, in the sense that no one, when facing the above issue, will be able to find this parameter. Should be somewhere around https://opensource.docs.scylladb.com/stable/troubleshooting/cluster/index.html

**Comment by kbr-scylla** [comment] 2024-06-13 11:21
> when facing the above issue

I expect that nobody will ever face this issue again because the default is now 600ms, not 300ms.

**Comment by mykaul** [comment] 2024-06-13 11:38
> > when facing the above issue
> 
> I expect that nobody will ever face this issue again because the default is now 600ms, not 300ms.

Clearly you've never deployed anything on ISS

**Comment by Fornax96** [comment] 2024-06-13 12:06
Very occasionally the message still appears in my logs, so I might bump it to 1 second later. I'll keep an eye on it.
