### ISSUE TITLE
random tests fail on failure to create inotify instances (Too many open files)

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#21199] opened 2024-10-20 14:52 UTC
https://github.com/scylladb/scylladb/pull/21191

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12561/testReport/junit/(root)/test_auth_v2_migration/Tests___Unit_Tests___test_auth_v2_migration_debug_3/

```
self = <test.pylib.manager_client.ManagerClient object at 0x7f9b0bd98e00>
replace_cfg = None, cmdline = None, config = {}, property_file = None
start = True, expected_error = None, seeds = None, timeout = 1000
server_encryption = 'none', expected_server_up_state = None

    async def server_add(self,
                         replace_cfg: Optional[ReplaceConfig] = None,
                         cmdline: Optional[List[str]] = None,
                         config: Optional[dict[str, Any]] = None,
                         property_file: Optional[dict[str, Any]] = None,
                         start: bool = True,
                         expected_error: Optional[str] = None,
                         seeds: Optional[List[IPAddress]] = None,
                         timeout: Optional[float] = ScyllaServer.TOPOLOGY_TIMEOUT,
                         server_encryption: str = "none",
                         expected_server_up_state: Optional[ServerUpState] = None) -> ServerInfo:
        """Add a new server"""
        try:
            data = self._create_server_add_data(
                replace_cfg,
                cmdline,
                config,
                property_file,
                start,
                seeds,
                expected_error,
                server_encryption,
                expected_server_up_state,
            )
    
            # If we replace, we should wait until other nodes see the node being
            # replaced as dead because the replace operation can be rejected if
            # the node being replaced is considered alive. However, we sometimes
            # do not want to wait, for example, when we test that replace fails
            # as expected. Therefore, we make waiting optional and default.
            if replace_cfg and replace_cfg.wait_replaced_dead:
                replaced_ip = await self.get_host_ip(replace_cfg.replaced_id)
                await self.others_not_see_server(replaced_ip)
    
            server_info = await self.client.put_json("/cluster/addserver", data, response_type="json",
                                                     timeout=timeout)
        except Exception as exc:
>           raise Exception("Failed to add server") from exc
E           Exception: Failed to add server

test/pylib/manager_client.py:354: Exception
```

**Comment by avikivity** [comment] 2024-10-20 15:08
inotify is used to listen for certificate files changing.

**Comment by avikivity** [comment] 2024-10-20 15:11
On my system I have

```
$ cat /proc/sys/fs/inotify/max_user_instances 
128
$ cat /proc/sys/fs/inotify/max_user_watches 
1003532
```

@elcallio could the recent TLS changes have caused more inotify watches to be used? 280cd23c130f670544378baf00a347a38c67ced2

If we have 10 clusters, each 3 nodes and 2 shard, each using 1 inotify instance, that's 60 inotifies. A factor of 2 away from exhaustion.


@yaronkaikov please set up the servers (local and remote) to have /proc/sys/fs/inotify/max_user_instances  10000

**Comment by nyh** [comment] 2024-10-20 15:11
> inotify is used to listen for certificate files changing.

Strange, I couldn't find "inotify" in our code base. Do we have a different name for it in Seastar?

Anyway, I would have guessed the problem isn't in this specific certificate files thing and we just ran out of open files because the test runner has a low limit and ran a bazillion processes, but on the other hand: Why do we consistently have this problem during the inotify and not the normal fopen? That's suspicous. I wonder if we "leak" inotify file descriptor, maybe creating them in a loop or something.

**Comment by avikivity** [comment] 2024-10-20 15:12
@elcallio we could consider running inotify only on shard 0 and broadcasing the results, though I can see it would take some juggling.

**Comment by nyh** [comment] 2024-10-20 15:13
> cat /proc/sys/fs/inotify/max_user_instances

Oh, nice, I didn't remember inotify had a separate limit. I believed the message "Too many open files" which was misleading in this case.

**Comment by avikivity** [comment] 2024-10-20 15:14
> > inotify is used to listen for certificate files changing.
> 
> Strange, I couldn't find "inotify" in our code base. Do we have a different name for it in Seastar?


```console
$ git grep inotify
include/seastar/core/fsnotify.hh:#include <sys/inotify.h>
include/seastar/core/fsnotify.hh:/// This is a thin wrapper around inotify(see http://man7.org/linux/man-pages/man7/inotify.7.html),
include/seastar/core/fsnotify.hh:    /// \note Note that the flags are bit-matched with inotify and they can
include/seastar/core/fsnotify.hh:    ///         inotify_add_watch(2) call completes.
include/seastar/core/fsnotify.hh:    /// \brief A wrapper around inotify_event.
include/seastar/core/posix.hh:    static file_desc inotify_init(int flags);
include/seastar/core/reactor.hh:    future<int> inotify_add_watch(int fd, std::string_view path, uint32_t flags);
src/core/fsnotify.cc:#include <sys/inotify.h>
src/core/fsnotify.cc:        : _fd(file_desc::inotify_init(IN_NONBLOCK | IN_CLOEXEC))
src/core/fsnotify.cc:        auto res = ::inotify_rm_watch(_fd, token);
src/core/fsnotify.cc:        throw_system_error_on(res == -1 && errno != EINVAL, "could not remove inotify watch");
src/core/fsnotify.cc:    return engine().inotify_add_watch(_fd, path, uint32_t(events));
src/core/fsnotify.cc:    auto buf = temporary_buffer<char>::aligned(std::max(alignof(::inotify_event), alignof(int64_t)), 4096);
src/core/fsnotify.cc:            auto ev = reinterpret_cast<const ::inotify_event*>(p);
src/core/fsnotify.cc:            p += sizeof(::inotify_event) + ev->len;
src/core/posix.cc:#include <sys/inotify.h>
src/core/posix.cc:file_desc::inotify_init(int flags) {
src/core/posix.cc:    int fd = ::inotify_init1(flags);
src/core/posix.cc:    throw_system_error_on(fd == -1, "could not create inotify instance");
src/core/reactor.cc:#include <sys/inotify.h>
src/core/reactor.cc:reactor::inotify_add_watch(int fd, std::string_view path, uint32_t flags) {
src/core/reactor.cc:            auto ret = ::inotify_add_watch(fd, path.c_str(), flags);
```

> 
> Anyway, I would have guessed the problem isn't in this specific certificate files thing and we just ran out of open files because the test runner has a low limit and ran a bazillion processes, but on the other hand: Why do we consistently have this problem during the inotify and not the normal fopen? That's suspicous. I wonder if we "leak" inotify file descriptor, maybe creating them in a loop or something.

inotify has its own limits

**Comment by avikivity** [comment] 2024-10-20 15:16
@xtrey since we run in namespaces, it would be enough to run each test (including its cluster) in its own user namespace, since each user namespace has its own limit.

**Comment by nyh** [comment] 2024-10-20 15:17
> > > inotify is used to listen for certificate files changing.
> > 
> > 
> > Strange, I couldn't find "inotify" in our code base. Do we have a different name for it in Seastar?
> 
> $ git grep inotify

This is all in Seastar. Where does Scylla use it inotify or fsnotify? git grep didn't yield anything except
```
dist/common/sysctl.d/99-scylla-inotify.conf:fs.inotify.max_user_instances = 1200
```
Why I guess the test machines didn't do, or 1200 was not enough?

**Comment by avikivity** [comment] 2024-10-20 15:19
> > > > inotify is used to listen for certificate files changing.
> > > 
> > > 
> > > Strange, I couldn't find "inotify" in our code base. Do we have a different name for it in Seastar?
> > 
> > 
> > $ git grep inotify
> 
> This is all in Seastar. Where does Scylla use it inotify or fsnotify? git grep didn't yield anything except

Via TLS.

> 
> ```
> dist/common/sysctl.d/99-scylla-inotify.conf:fs.inotify.max_user_instances = 1200
> ```
> 
> Why I guess the test machines didn't do, or 1200 was not enough?


This is for the packages, and our tests don't install the packages.

**Comment by yaronkaikov** [comment] 2024-10-20 19:52
> On my system I have
> 
> ```
> $ cat /proc/sys/fs/inotify/max_user_instances 
> 128
> $ cat /proc/sys/fs/inotify/max_user_watches 
> 1003532
> ```
> 
> [@elcallio](https://github.com/elcallio) could the recent TLS changes have caused more inotify watches to be used? [280cd23](https://github.com/scylladb/scylladb/commit/280cd23c130f670544378baf00a347a38c67ced2)
> 
> If we have 10 clusters, each 3 nodes and 2 shard, each using 1 inotify instance, that's 60 inotifies. A factor of 2 away from exhaustion.
> 
> [@yaronkaikov](https://github.com/yaronkaikov) please set up the servers (local and remote) to have /proc/sys/fs/inotify/max_user_instances 10000

All local nodes are now updated, i will update also the cloud tomorrow

**Comment by yaronkaikov** [comment] 2024-10-21 05:31
> > On my system I have
> > ```
> > $ cat /proc/sys/fs/inotify/max_user_instances 
> > 128
> > $ cat /proc/sys/fs/inotify/max_user_watches 
> > 1003532
> > ```
> > 
> > 
> >     
> >   
> > [@elcallio](https://github.com/elcallio) could the recent TLS changes have caused more inotify watches to be used? [280cd23](https://github.com/scylladb/scylladb/commit/280cd23c130f670544378baf00a347a38c67ced2)
> > If we have 10 clusters, each 3 nodes and 2 shard, each using 1 inotify instance, that's 60 inotifies. A factor of 2 away from exhaustion.
> > [@yaronkaikov](https://github.com/yaronkaikov) please set up the servers (local and remote) to have /proc/sys/fs/inotify/max_user_instances 10000
> 
> All local nodes are now updated, i will update also the cloud tomorrow

Also all cloud instances

**Comment by nyh** [comment] 2024-10-21 06:37
I think we should close this issue now that the test runner VMs use a higher /proc/sys/fs/inotify/max_user_instances (thanks @yaronkaikov). We should independently consider the Seastar question of whether fewer inotify instances can be used, or whether Seastar could be more resilient to lack of working inofiy, but it wouldn't be this issue, so I'll close this one.

**Closed by nyh** 2024-10-21 06:37 UTC
Labels: symptom/ci stability

**Comment by nyh** [comment] 2024-10-21 07:02
Opened Seastar issue https://github.com/scylladb/seastar/issues/2513
