### ISSUE TITLE
bootstrap new node failed with  raft operation [add_entry] timed out

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#19231] opened 2024-06-11 11:42 UTC
## Packages

Scylla version: `6.1.0~dev-20240610.55ed18db073e` with build-id `55a1143e2b8119673fa8d6a6851806ad8a143884`

Kernel Version: `5.15.0-1063-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Scale test try to bootstrap 100 nodes. After bootstrapping 10 nodes, 11th node start up failed with error:
```
2024-06-11T09:00:57.755+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-11     !INFO | scylla[6880]:  [shard 0:strm] raft_group0 - setup_group0: joining group 0...
2024-06-11T09:00:57.755+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-11     !INFO | scylla[6880]:  [shard 0:strm] raft_group0 - server c86f11ee-6041-4a25-b01d-18c4da29ae1e found no local group 0. Dis
covering...
2024-06-11T09:00:57.755+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-11     !INFO | scylla[6880]:  [shard 0:strm] raft_group0 - server c86f11ee-6041-4a25-b01d-18c4da29ae1e found group 0 with group id
 756cf020-27cc-11ef-b607-8dae8b7fe3ea, leader f4256c81-51c4-4090-b43f-3c57677a853a
2024-06-11T09:00:57.755+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-11     !INFO | scylla[6880]:  [shard 0:strm] raft_topology - join: sending the join request to 10.4.1.254
...
2024-06-11T09:01:59.767+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-11     !INFO | scylla[6880]:  [shard 0:main] init - Shutting down configurables was successful
2024-06-11T09:01:59.767+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-11      !ERR | scylla[6880]:  [shard 0:main] init - Startup failed: seastar::rpc::remote_verb_error (group [756cf020-27cc-11ef-b607-8dae8b7fe3ea] raft operation [add_entry] timed out)
```

looks like topology coordinator doesn't get the request:
```
2024-06-11T08:59:36.848+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | scylla[6953]:  [shard 1:comp] compaction - [Compact keyspace1.standard1 bd71d710-27d0-11ef-a503-8daf8b7fe3ea] Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-83792bb027cd11ef8af58dffae828b50/md-3ggw_0ox3_4jbmo2ic6nm4k3zqi2-big-Data.db:level=0]. 2GB to 2GB (~99% of original) in 80693ms = 33MB/s. ~20480 total partitions merged to 20294.
2024-06-11T08:59:41.598+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | sshd[7713]: Accepted publickey for scyllaadm from 10.4.3.83 port 52062 ssh2: RSA SHA256:1YmYWh7roz4Y3FSY7N8CetmQNlK/K5FeBPITC8KF0u8
2024-06-11T08:59:41.598+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | sshd[7713]: pam_unix(sshd:session): session opened for user scyllaadm(uid=1000) by (uid=0)
2024-06-11T08:59:41.598+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | systemd-logind[388]: New session 23 of user scyllaadm.
2024-06-11T08:59:41.598+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | systemd[1]: Started Session 23 of User scyllaadm.
2024-06-11T08:59:46.598+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1   !NOTICE | sudo[7726]: scyllaadm : PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/coredumpctl -q --json=short
2024-06-11T08:59:46.598+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | sudo[7726]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
2024-06-11T08:59:46.598+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | sudo[7726]: pam_unix(sudo:session): session closed for user root
2024-06-11T08:59:51.848+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | scylla[6953]:  [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC eu-west that has 10 endpoints
2024-06-11T09:00:16.598+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1   !NOTICE | sudo[7738]: scyllaadm : PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/coredumpctl -q --json=short
2024-06-11T09:00:16.598+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | sudo[7738]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
2024-06-11T09:00:16.598+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | sudo[7738]: pam_unix(sudo:session): session closed for user root
2024-06-11T09:00:21.348+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | scylla[6953]:  [shard 0:strm] compaction - [Split keyspace1.standard1 ebb80040-27d0-11ef-b607-8dae8b7fe3ea] Split 1 sstables to [/var/lib/scylla/data/keyspace1/standard1-83792bb027cd11ef8af58dffae828b50/md-3ggw_0oz9_1wl4w2rnjdk6yjkrmy-big-Data.db:level=0,/var/lib/scylla/data/keyspace1/standard1-83792bb027cd11ef8af58dffae828b50/md-3ggw_0ozx_1u0jk2rnjdk6yjkrmy-big-Data.db:level=0]. 1GB to 1GB (~100% of original) in 47686ms = 22MB/s. ~8448 total partitions merged to 8346.
2024-06-11T09:00:21.348+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | scylla[6953]:  [shard 0:strm] compaction - [Split keyspace1.standard1 082475b0-27d1-11ef-b607-8dae8b7fe3ea] Splitting [/var/lib/scylla/data/keyspace1/standard1-83792bb027cd11ef8af58dffae828b50/md-3ggw_0o87_4sbpc2rnjdk6yjkrmy-big-Data.db:level=0:origin=memtable]
2024-06-11T09:00:21.848+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | scylla[6953]:  [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC eu-west that has 10 endpoints
2024-06-11T09:00:46.848+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1   !NOTICE | sudo[7743]: scyllaadm : PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/coredumpctl -q --json=short
2024-06-11T09:00:46.848+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | sudo[7743]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
2024-06-11T09:00:46.848+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | sudo[7743]: pam_unix(sudo:session): session closed for user root
2024-06-11T09:00:51.848+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | scylla[6953]:  [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC eu-west that has 10 endpoints
2024-06-11T09:00:58.848+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | scylla[6953]:  [shard 0: gms] gossip - InetAddress c86f11ee-6041-4a25-b01d-18c4da29ae1e/10.4.0.242 is now UP, status = UNKNOWN
2024-06-11T09:01:08.848+00:00 cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1     !INFO | scylla[6953]:  [shard 0:strm] compaction - [Split keyspace1.standard1 082475b0-27d1-11ef-b607-8dae8b7fe3ea] Split 1 :
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 10 nodes (i4i.large)

Scylla Nodes used in this run:
- cluster-scale-40-60-test-scayle-t-db-node-661cbad0-9 (54.75.85.216 | 10.4.2.19) (shards: 2)
- cluster-scale-40-60-test-scayle-t-db-node-661cbad0-8 (52.51.147.15 | 10.4.1.254) (shards: 2)
- cluster-scale-40-60-test-scayle-t-db-node-661cbad0-7 (34.244.150.1 | 10.4.0.199) (shards: 2)
- cluster-scale-40-60-test-scayle-t-db-node-661cbad0-6 (52.212.222.76 | 10.4.1.26) (shards: 2)
- cluster-scale-40-60-test-scayle-t-db-node-661cbad0-5 (34.244.81.177 | 10.4.1.79) (shards: 2)
- cluster-scale-40-60-test-scayle-t-db-node-661cbad0-4 (54.194.152.63 | 10.4.0.187) (shards: -1)
- cluster-scale-40-60-test-scayle-t-db-node-661cbad0-3 (52.211.128.85 | 10.4.3.108) (shards: 2)
- cluster-scale-40-60-test-scayle-t-db-node-661cbad0-2 (34.253.200.27 | 10.4.2.86) (shards: -1)
- cluster-scale-40-60-test-scayle-t-db-node-661cbad0-11 (34.245.134.83 | 10.4.0.242) (shards: 2)
- cluster-scale-40-60-test-scayle-t-db-node-661cbad0-10 (54.217.50.33 | 10.4.2.62) (shards: 2)
- cluster-scale-40-60-test-scayle-t-db-node-661cbad0-1 (34.245.94.211 | 10.4.1.28) (shards: 2)

OS / Image: `ami-05b5faf260c296519` (aws: undefined_region)

Test: `scale-10-100-cluster-test`
Test id: `661cbad0-184e-420d-8c3f-9ff848c0db1d`
Test name: `scylla-staging/abykov/scale-10-100-cluster-test`
Test config file(s):

- [scale-cluster.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/582754aae0de7b28bef1b2b809df4659a8227e85/test-cases/scale/scale-cluster.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 661cbad0-184e-420d-8c3f-9ff848c0db1d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=661cbad0-184e-420d-8c3f-9ff848c0db1d)
- Show all stored logs command: `$ hydra investigate show-logs 661cbad0-184e-420d-8c3f-9ff848c0db1d`

## Logs:
- **db-cluster-661cbad0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/661cbad0-184e-420d-8c3f-9ff848c0db1d/20240611_091004/db-cluster-661cbad0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/661cbad0-184e-420d-8c3f-9ff848c0db1d/20240611_091004/db-cluster-661cbad0.tar.gz)
- **sct-runner-events-661cbad0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/661cbad0-184e-420d-8c3f-9ff848c0db1d/20240611_091004/sct-runner-events-661cbad0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/661cbad0-184e-420d-8c3f-9ff848c0db1d/20240611_091004/sct-runner-events-661cbad0.tar.gz)
- **sct-661cbad0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/661cbad0-184e-420d-8c3f-9ff848c0db1d/20240611_091004/sct-661cbad0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/661cbad0-184e-420d-8c3f-9ff848c0db1d/20240611_091004/sct-661cbad0.log.tar.gz)
- **loader-set-661cbad0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/661cbad0-184e-420d-8c3f-9ff848c0db1d/20240611_091004/loader-set-661cbad0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/661cbad0-184e-420d-8c3f-9ff848c0db1d/20240611_091004/loader-set-661cbad0.tar.gz)
- **monitor-set-661cbad0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/661cbad0-184e-420d-8c3f-9ff848c0db1d/20240611_091004/monitor-set-661cbad0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/661cbad0-184e-420d-8c3f-9ff848c0db1d/20240611_091004/monitor-set-661cbad0.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/scale-10-100-cluster-test/3/)
[Argus](https://argus.scylladb.com/test/2f0d730f-a1d9-43e0-bd2e-0c1070ae2ced/runs?additionalRuns[]=661cbad0-184e-420d-8c3f-9ff848c0db1d)
</details>

**Comment by aleksbykov** [comment] 2024-06-11 11:42
@kbr- FYI

**Comment by aleksbykov** [comment] 2024-06-11 11:44
Possible the same root cause: https://github.com/scylladb/scylladb/issues/19105

**Comment by kbr-scylla** [comment] 2024-06-11 11:44
cc @gleb-cloudius

**Comment by aleksbykov** [comment] 2024-06-12 09:42
Same happened but now during bootstrap 26th node:
logs: https://cloudius-jenkins-test.s3.amazonaws.com/e4e42bab-544e-4993-b02c-719b6702882a/20240611_135352/db-cluster-e4e42bab.tar.gz

**Comment by kbr-scylla** [comment] 2024-07-19 16:55
@aleksbykov please retest on latest build

**Comment by kbr-scylla** [comment] 2024-07-31 11:06
ping @aleksbykov

**Comment by aleksbykov** [comment] 2024-07-31 11:38
@kbr-scylla , i have triggered job. Waiting results

**Comment by aleksbykov** [comment] 2024-08-01 07:34
@kbr-scylla , the issue is not reproduced with latest scylla build. All 100 nodes were bootstrapped.

Scylla version: `6.2.0~dev-20240730.35394c3f9a1b` with build-id `9456cbcb77cea64755b52e34ec23d311788fa046`
Kernel Version: `6.8.0-1012-aws`

Unfortunately, log from nodes were not collected ( not enough space on runner). 
one huge reactor stall was detected:
```
Reactor stalled for 845 ms on shard 0, in scheduling group main. Backtrace: 0x5a77a52 0x5a36966 0x5a35dfd 0x5a370cf 0x40cff 0x1cd4867 0x1ed9bde 0x1ed7ef3 0x1ffacb0 0x5e19166
0x5a77a52
0x5a36966
0x5a35dfd
0x5a370cf
0x40cff
0x1cd4867
0x1ed9bde
0x1ed7ef3
0x1ffacb0
0x5e19166
```
Couldn't decode it yet, backtrace site is not available

**Comment by kbr-scylla** [comment] 2024-08-02 17:19
Thanks. So likely the same root cause as other reports in https://github.com/scylladb/scylladb/issues/19105 and fixed by https://github.com/scylladb/scylladb/pull/19469
Closing.

The decoded backtrace:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:839
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:861
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:1485
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:1222
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:1242
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:1523
?? ??:0
bound_view::tri_compare::operator()(clustering_key_prefix const&, int, clustering_key_prefix const&, int) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_iterator_base_funcs.h:?
partition_snapshot_row_cursor::version_heap_less_compare::operator()(partition_snapshot_row_cursor::position_in_version const&, partition_snapshot_row_cursor::position_in_version const&) at ./mutation/position_in_partition.hh:576
 (inlined by) bool __gnu_cxx::__ops::_Iter_comp_val<partition_snapshot_row_cursor::version_heap_less_compare>::operator()<partition_snapshot_row_cursor::position_in_version*, partition_snapshot_row_cursor::position_in_version>(partition_snapshot_row_cursor::position_in_version*, partition_snapshot_row_cursor::position_in_version&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/predefined_ops.h:196
 (inlined by) void std::__push_heap<partition_snapshot_row_cursor::position_in_version*, long, partition_snapshot_row_cursor::position_in_version, __gnu_cxx::__ops::_Iter_comp_val<partition_snapshot_row_cursor::version_heap_less_compare> >(partition_snapshot_row_cursor::position_in_version*, long, long, partition_snapshot_row_cursor::position_in_version, __gnu_cxx::__ops::_Iter_comp_val<partition_snapshot_row_cursor::version_heap_less_compare>&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_heap.h:140
 (inlined by) void std::push_heap<partition_snapshot_row_cursor::position_in_version*, partition_snapshot_row_cursor::version_heap_less_compare>(partition_snapshot_row_cursor::position_in_version*, partition_snapshot_row_cursor::position_in_version*, partition_snapshot_row_cursor::version_heap_less_compare) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_heap.h:216
 (inlined by) utils::small_vector<partition_snapshot_row_cursor::position_in_version, 2ul>& boost::range::push_heap<utils::small_vector<partition_snapshot_row_cursor::position_in_version, 2ul>, partition_snapshot_row_cursor::version_heap_less_compare>(utils::small_vector<partition_snapshot_row_cursor::position_in_version, 2ul>&, partition_snapshot_row_cursor::version_heap_less_compare) at /usr/include/boost/range/algorithm/heap_algorithm.hpp:51
 (inlined by) partition_snapshot_row_cursor::advance(bool) at ././partition_snapshot_row_cursor.hh:361
 (inlined by) partition_snapshot_row_cursor::next() at ././partition_snapshot_row_cursor.hh:533
seastar::noncopyable_function<seastar::bool_class<seastar::stop_iteration_tag> ()>::indirect_vtable_for<partition_entry::apply_to_incomplete(schema const&, partition_entry&&, mutation_cleaner&, logalloc::allocating_section&, logalloc::region&, cache_tracker&, unsigned long, real_dirty_memory_accounter&, basic_preemption_source&)::$_0>::call(seastar::noncopyable_function<seastar::bool_class<seastar::stop_iteration_tag> ()> const*) at ././mutation/partition_version.cc:578
seastar::noncopyable_function<seastar::bool_class<seastar::stop_iteration_tag> ()>::operator()() const at ././seastar/include/seastar/util/noncopyable_function.hh:215
 (inlined by) utils::coroutine::run() at ././utils/coroutine.hh:39
 (inlined by) row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda()#3}::operator()() const at ././row_cache.cc:1074
 (inlined by) decltype(auto) with_allocator<row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda()#3}>(allocation_strategy&, row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda()#3}&&) at ././utils/allocation_strategy.hh:346
 (inlined by) row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}::operator()() at ././row_cache.cc:1053
 (inlined by) void std::__invoke_impl<void, row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}>(std::__invoke_other, row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:61
 (inlined by) std::__invoke_result<row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}>::type std::__invoke<row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}>(row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:96
 (inlined by) _ZSt12__apply_implIZZN9row_cache9do_updateIZNS0_6updateENS0_16external_updaterERN7replica8memtableER23basic_preemption_sourceE3$_0EEN7seastar6futureIvEES2_S5_T_S7_ENKUlvE_clEvEUlvE0_St5tupleIJEETpTnmJEEDcOSC_OT0_St16integer_sequenceImJXspT1_EEE at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/tuple:2921
 (inlined by) _ZSt5applyIZZN9row_cache9do_updateIZNS0_6updateENS0_16external_updaterERN7replica8memtableER23basic_preemption_sourceE3$_0EEN7seastar6futureIvEES2_S5_T_S7_ENKUlvE_clEvEUlvE0_TkSt12__tuple_likeSt5tupleIJEEEDcOSC_OT0_ at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/tuple:2936
 (inlined by) seastar::future<void> seastar::futurize<void>::apply<row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}>(row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:1997
 (inlined by) seastar::async<row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}>(seastar::thread_attributes, row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}&&)::{lambda()#1}::operator()() const at ././seastar/include/seastar/core/thread.hh:260
 (inlined by) seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}>(seastar::thread_attributes, row_cache::do_update<row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0>(row_cache::external_updater, replica::memtable&, row_cache::update(row_cache::external_updater, replica::memtable&, basic_preemption_source&)::$_0, basic_preemption_source&)::{lambda()#1}::operator()() const::{lambda()#2}&&)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././seastar/include/seastar/util/noncopyable_function.hh:129
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:215
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/thread.cc:312
```

`row_cache::do_update`? `partition_snapshot_row_cursor`? `bound_view::tri_compare::operator`? wut.
cc @tgrabiec @denesb

**Closed by kbr-scylla** 2024-08-02 17:19 UTC
Labels: area/topology changes, tests/longevity-tier1
