### ISSUE TITLE
[Tablets] `Aborting on shard` and `coredump` building MV on a restarted and repaired DB node

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylladb#19872] opened 2024-07-24 18:24 UTC
## Packages

Scylla version: `6.2.0~dev-20240722.dfe3af40ed4c` with build-id `d1b6c10dec64712af1994b2f07d0858b5d309844`

Kernel Version: `6.8.0-1010-gcp`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

The failure happened during the `add_remove_mv` nemesis.
It's steps:
- Stop scylla on some of the DB nodes
- Create MV
- Start previously stopped Scylla
- Repair that DB node
- Wait for the MV building on that DB node
- Drop MV

```
2024-07-23 17:26:57,898 f:nemesis.py      l:4889 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: \
    Stopping Scylla on node longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5
...
2024-07-23 17:27:18,952 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-07-23 17:27:18.950: (InfoEvent Severity.NORMAL) period_type=not-set event_id=a762df7d-6cda-4b3f-8ab6-683ef3e5c6da: message=\
    Create a materialized-view for table scylla_bench.test
...
2024-07-23 17:27:20,986 f:nemesis.py      l:4904 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: \
    Starting Scylla on node longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5
...
2024-07-23 17:27:32,194 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.142.0.90>: \
    Running command "/usr/bin/nodetool  repair -pr "...
...
2024-07-23 20:29:17,872 f:cluster.py      l:2631 c:sdcm.cluster_gce     p:DEBUG > Node longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 [34.74.163.29 | 10.142.0.90]: \
    Command '/usr/bin/nodetool  repair -pr ' duration -> 10905.677535127998 s 
...
2024-07-23 20:29:19,358 f:cluster.py      l:2631 c:sdcm.cluster_gce     p:DEBUG > Node longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 [34.74.163.29 | 10.142.0.90]: \
    Command '/usr/bin/nodetool  viewbuildstatus scylla_bench.test_view ' duration -> 0.1936144700011937 s
...
2024-07-23 20:29:19,164 f:indexes.py      l:77   c:sdcm.utils.nemesis_utils.indexes p:INFO  > \
    waiting for view/index test_view to be built
```

After successful finish of the `repair` operation, waiting for the MV building, in 18 minutes the following error appears:
```
Jul 23 20:47:37.166979 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:  [shard  0: gms] table - Found that storage of group 66 for table 01cdd9f0-48f5-11ef-a1e1-4e92ad8f7f41 wasn't split correctly, therefore groups cannot be remapped with the new tablet count., at: 0x5e8458e 0x5e84ba0 0x5e84ea8 0x594ac47 0x1b40c7d 0x1b41f1a 0x1b42bd2 0x3db053f 0x3db007b 0x3dac568 0x5d493d6 0x5d4934f 0x3e14330 0x13d3a0a 0x5988eef 0x598a46a 0x598b657 0x598aa08 0x591ad03 0x591a063 0x137e885 0x1380240 0x137cca3 /opt/scylladb/libreloc/libc.so.6+0x2a087 /opt/scylladb/libreloc/libc.so.6+0x2a14a 0x137a324
                                                                                                  --------
                                                                                                  seastar::internal::coroutine_traits_base<void>::promise_type
                                                                                                  --------
                                                                                                  seastar::internal::coroutine_traits_base<void>::promise_type
                                                                                                  --------
                                                                                                  seastar::internal::coroutine_traits_base<void>::promise_type
                                                                                                  --------
                                                                                                  seastar::internal::coroutine_traits_base<void>::promise_type
                                                                                                  --------
                                                                                                  seastar::internal::coroutine_traits_base<void>::promise_type
                                                                                                  --------
                                                                                                  seastar::internal::coroutine_traits_base<void>::promise_type
                                                                                                  --------
                                                                                                  seastar::internal::coroutine_traits_base<void>::promise_type
                                                                                                  --------
                                                                                                  seastar::internal::coroutine_traits_base<void>::promise_type
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]: Aborting on shard 0, in scheduling group gossip.
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]: Backtrace:
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x59b9714
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x5978bbb
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x59ae4e6
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   /opt/scylladb/libreloc/libc.so.6+0x40cff
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   /opt/scylladb/libreloc/libc.so.6+0x994a3
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   /opt/scylladb/libreloc/libc.so.6+0x40c4d
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   /opt/scylladb/libreloc/libc.so.6+0x28901
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x594acc6
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x1b40c7d
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x1b41f1a
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x1b42bd2
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x3db053f
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x3db007b
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x3dac568
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x5d493d6
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x5d4934f
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x3e14330
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x13d3a0a
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x5988eef
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x598a46a
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x598b657
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x598aa08
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x591ad03
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x591a063
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x137e885
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x1380240
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x137cca3
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   /opt/scylladb/libreloc/libc.so.6+0x2a087
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   /opt/scylladb/libreloc/libc.so.6+0x2a14a
Jul 23 20:47:37.167143 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 scylla[25308]:   0x137a324
Jul 23 20:52:57.708766 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 systemd[1]: scylla-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 23 20:52:57.876651 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 systemd[1]: scylla-server.service: Failed with result 'core-dump'.
Jul 23 20:52:57.876928 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 systemd[1]: scylla-server.service: Consumed 1d 20h 1min 14.015s CPU time.
Jul 23 20:52:58.156684 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 systemd[1]: scylla-server.service: Scheduled restart job, restart counter is at 1.
Jul 23 20:52:58.165745 longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 systemd[1]: Starting scylla-server.service - Scylla Server...
```

```
[Backtrace #0]
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_0>(seastar::current_backtrace_tasklocal()::$_0&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:97
seastar::current_tasktrace() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:148
seastar::current_backtrace() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:181
void log_error_and_backtrace<std::basic_string_view<char, std::char_traits<char> > >(seastar::logger&, std::basic_string_view<char, std::char_traits<char> > const&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/on_internal_error.cc:50
 (inlined by) seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/on_internal_error.cc:54
replica::tablet_storage_group_manager::compaction_group_for_sstable(seastar::lw_shared_ptr<sstables::sstable> const&) const at ././replica/table.cc:1007
replica::table::table_state_for_sstable(seastar::lw_shared_ptr<sstables::sstable> const&) const at ././replica/database.hh:1222
 (inlined by) compaction::shard_reshaping_compaction_task_impl::run() at ././compaction/task_manager_module.cc:603
tasks::task_manager::task::impl::run_to_completion() at ././tasks/task_manager.cc:194
tasks::task_manager::task::start() at ././tasks/task_manager.cc:309
_ZN5tasks12task_manager6module19make_and_start_taskIN10compaction36shard_reshaping_compaction_task_implEJRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RN5utils11tagged_uuidINS_11task_id_tagEEERN8sstables17sstable_directoryERN7seastar7shardedIN7replica8databaseEEERNSH_12reshape_modeERSt8functionIFNSK_13lw_shared_ptrINSH_7sstableEEEjEERSS_IFbRKSV_EERmEQaasr3stdE12is_base_of_vINS0_4task4implET_ErQNSK_10shared_ptrIS1_EEDpOT0__XcvS17__fL0p_spclsr3stdE7forwardIS1A_EfL0p0_EERSt7same_asIS17_EEEENSK_6futureINST_IS15_EEEENS_9task_infoES1C_ at ././tasks/task_manager.hh:274
compaction::table_reshaping_compaction_task_impl::run()::$_0::operator()(sstables::sstable_directory&) const at ././compaction/task_manager_module.cc:585
seastar::future<unsigned long> std::__invoke_impl<seastar::future<unsigned long>, compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&>(std::__invoke_other, compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:61
 (inlined by) std::__invoke_result<compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&>::type std::__invoke<compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&>(compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:96
 (inlined by) std::invoke_result<compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&>::type std::invoke<compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&>(compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/functional:120
 (inlined by) seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}::operator()() const at ././seastar/include/seastar/core/sharded.hh:401
 (inlined by) seastar::future<unsigned long> seastar::futurize<seastar::future<unsigned long> >::invoke<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&>(seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:2032
 (inlined by) seastar::futurize<std::invoke_result<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::type>::type seastar::smp::submit_to<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::smp_submit_to_options, seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&&) at ././seastar/include/seastar/core/smp.hh:367
 (inlined by) seastar::futurize<std::invoke_result<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::type>::type seastar::smp::submit_to<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&&) at ././seastar/include/seastar/core/smp.hh:394
 (inlined by) seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const at ././seastar/include/seastar/core/sharded.hh:399
 (inlined by) seastar::future<unsigned long> seastar::futurize<seastar::future<unsigned long> >::invoke<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}&, unsigned int>(seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}&, unsigned int&&) at ././seastar/include/seastar/core/future.hh:2032
 (inlined by) auto seastar::futurize_invoke<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}&, unsigned int>(seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}&, unsigned int&&) at ././seastar/include/seastar/core/future.hh:2063
 (inlined by) _ZN7seastar10map_reduceIN5boost12range_detail16integer_iteratorIjEEZNS_7shardedIN8sstables17sstable_directoryEE11map_reduce0IZN10compaction36table_reshaping_compaction_task_impl3runEvE3$_0mSt4plusImEEENS_6futureIT0_EET_SG_T1_EUljE_mSE_QrQSI_SG_SJ_T2__XdeppfL0p_XnefL0p_fL0p_RSt14convertible_toIbEXclfL0p0_defL0p_EQsr9is_futureIDTclfL0p0_defL0p_EEEE5valueXclfL0p2_clsr3stdE4movefL0p1_EcldtclfL0p0_defL0p_E3getEERSM_ISJ_EEEENSF_ISJ_EESI_SI_OSG_SJ_SL_ at ././seastar/include/seastar/core/map_reduce.hh:192
 (inlined by) seastar::future<unsigned long> seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>) at ././seastar/include/seastar/core/sharded.hh:404
 (inlined by) compaction::table_reshaping_compaction_task_impl::run() at ././compaction/task_manager_module.cc:581
tasks::task_manager::task::impl::run_to_completion() at ././tasks/task_manager.cc:194
tasks::task_manager::task::start() at ././tasks/task_manager.cc:309
_ZN5tasks12task_manager6module19make_and_start_taskIN10compaction36table_reshaping_compaction_task_implEJN7seastar13basic_sstringIcjLj15ELb1EEES7_RNS5_7shardedIN8sstables17sstable_directoryEEERNS8_IN7replica8databaseEEERNS9_12reshape_modeESt8functionIFNS5_13lw_shared_ptrINS9_7sstableEEEjEESJ_IFbRKSM_EEEQaasr3stdE12is_base_of_vINS0_4task4implET_ErQNS5_10shared_ptrIS1_EEDpOT0__XcvSV__fL0p_spclsr3stdE7forwardISY_EfL0p0_EERSt7same_asISV_EEEENS5_6futureINSK_IST_EEEENS_9task_infoES10_ at ././tasks/task_manager.hh:274
replica::distributed_loader::reshape(seastar::sharded<sstables::sstable_directory>&, seastar::sharded<replica::database>&, sstables::reshape_mode, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, std::function<seastar::lw_shared_ptr<sstables::sstable> (unsigned int)>, std::function<bool (seastar::lw_shared_ptr<sstables::sstable> const&)>) at ././replica/distributed_loader.cc:133
replica::table_populator::populate_subdir(sstables::sstable_state, seastar::bool_class<replica::allow_offstrategy_compaction_tag>) at ././replica/distributed_loader.cc:388
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/coroutine:242
 (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:122
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:2651
seastar::reactor::run_some_tasks() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3121
seastar::reactor::do_run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3289
seastar::reactor::run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3179
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:276
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:167
scylla_main(int, char**) at ././main.cc:699
std::function<int (int, char**)>::operator()(int, char**) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591
main at ././main.cc:2208
/data/scylla-s3-reloc.cache/by-build-id/d1b6c10dec64712af1994b2f07d0858b5d309844/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=8f53abaad945a669f2bdcd25f471d80e077568ef, for GNU/Linux 3.2.0, not stripped

__libc_start_call_main at ??:?
__libc_start_main_alias_2 at :?
_start at ??:?
```

```
download_instructions: 
gsutil cp gs://upload.scylladb.com/core.scylla.107.8752cbfe892443ed85da308109ed8ec5.33226.1721767986000000./core.scylla.107.8752cbfe892443ed85da308109ed8ec5.33226.1721767986000000.zst .
unzstd core.scylla.107.8752cbfe892443ed85da308109ed8ec5.33226.1721767986000000.zst
```

After it Scylla service falls into an endless crash-loop.

## Impact

DB node falls into an endless crash-loop.

## How frequently does it reproduce?

Observed first time?

## Installation details

Cluster size: 5 nodes (n2-highmem-16)

Scylla Nodes used in this run:
- longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-5 (34.74.163.29 | 10.142.0.90) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-4 (35.237.243.131 | 10.142.0.53) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-3 (34.138.29.31 | 10.142.0.44) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-2 (35.237.71.69 | 10.142.0.8) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-eaffcd0a-0-1 (35.190.182.250 | 10.142.0.114) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/scylla-6-2-0-dev-x86-64-2024-07-23t01-49-22` (gce: undefined_region)

Test: `longevity-large-partition-200k-pks-4days-gce-test`
Test id: `eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f`
Test name: `scylla-master/tier1/longevity-large-partition-200k-pks-4days-gce-test`
Test config file(s):

- [longevity-large-partition-200k_pks-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2a8fda275fe4433c3e476c3ad47fd9e6c89ce69e/test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f)
- Show all stored logs command: `$ hydra investigate show-logs eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f`

## Logs:
- **db-cluster-eaffcd0a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f/20240724_132803/db-cluster-eaffcd0a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f/20240724_132803/db-cluster-eaffcd0a.tar.gz)
- **sct-runner-events-eaffcd0a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f/20240724_132803/sct-runner-events-eaffcd0a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f/20240724_132803/sct-runner-events-eaffcd0a.tar.gz)
- **sct-eaffcd0a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f/20240724_132803/sct-eaffcd0a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f/20240724_132803/sct-eaffcd0a.log.tar.gz)
- **loader-set-eaffcd0a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f/20240724_132803/loader-set-eaffcd0a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f/20240724_132803/loader-set-eaffcd0a.tar.gz)
- **monitor-set-eaffcd0a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f/20240724_132803/monitor-set-eaffcd0a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f/20240724_132803/monitor-set-eaffcd0a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-large-partition-200k-pks-4days-gce-test/26/)
[Argus](https://argus.scylladb.com/test/996501ad-c137-40ef-8dcc-a7d12f0ba3b6/runs?additionalRuns[]=eaffcd0a-05f3-4dfc-b737-c5ef3656fc3f)
</details>

**Comment by bhalevy** [comment] 2024-07-25 11:15
@denesb @raphaelsc @Deexie could this also be fallout from the rwlock elimination patch (53a6ec05ed311dfbdf04903e3bd5321c9261de59)?

**Comment by Deexie** [comment] 2024-07-25 12:06
> @denesb @raphaelsc @Deexie could this also be fallout from the rwlock elimination patch ([53a6ec0](https://github.com/scylladb/scylladb/commit/53a6ec05ed311dfbdf04903e3bd5321c9261de59))?

This is the `on_internal_error` that was hit:
```
on_internal_error(tlogger, format("Unable to load SSTable {} that belongs to tablets {} and {}",
                                          sst->get_filename(), first_id, last_id));
```

And in logs we have:
```
table - Found that storage of group 66 for table 01cdd9f0-48f5-11ef-a1e1-4e92ad8f7f41 wasn't split correctly, therefore groups cannot be remapped with the new tablet count.
```

So I would say it isn't the eliminated rwlock fault (at least not directly) but rather split failure

**Comment by raphaelsc** [comment] 2024-07-25 13:48
> Looks like this is maybe the known split vs. repair race, that is not yet fixed.

Looks like so. Tomorrow I will take a look.

**Comment by raphaelsc** [comment] 2024-07-27 17:17
Yes, I think it's a dup of https://github.com/scylladb/scylladb/issues/19378

**Comment by denesb** [comment] 2024-08-05 07:29
Closing as duplicate of https://github.com/scylladb/scylladb/issues/19378.

**Closed by denesb** 2024-08-05 07:29 UTC
Labels: area/materialized views, triage/master, P1, area/tablets, tests/longevity-tier1
