### ISSUE TITLE
reader_concurrency_semaphore - Semaphore _read_concurrency_sem: timed out, dumping permit diagnostics

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#9565] opened 2021-11-01 12:35 UTC
*Installation details*
Scylla version (or git commit hash): `4.4.6-0.20211028.dd018d4de with build-id dd698cb5d3877bc7da76fa690d484e1b8a20df96`
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0f16e55d34bb7eb72` (aws: eu-north-1)
Test: `longevity-100gb-4h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/bdfd7672d9e67151461ae016b66135f39f33035d/test-cases/longevity/longevity-100gb-4h.yaml)

**Issue description**
During job [longevity-100gb-4h-test](https://jenkins.scylladb.com/job/scylla-4.4/job/longevity/job/longevity-100gb-4h-test/68/)
nemesis ENOSPC was executed on node6. This nemesis emulate no space left on device with command
`2021-10-29T10:17:17+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !NOTICE  | sudo: scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/bin/fallocate -l 323323390K /var/lib/scylla/occupy_90percent.1635502637.0681465`

Scylla detect error: 
```
2021-10-29T10:17:33+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !WARNING | scylla: [shard 10] storage_service - Shutting down communications due to I/O errors until operator intervention
2021-10-29T10:17:33+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !WARNING | scylla: [shard 10] storage_service - Disk error: std::system_error (error system:28, No space left on device)
2021-10-29T10:17:33+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | scylla: [shard 0] storage_service - Stop transport: starts
2021-10-29T10:17:33+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | scylla: [shard 0] storage_service - Shutting down native transport
2021-10-29T10:17:33+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 10] table - failed to write sstable /var/lib/scylla/data/keyspace1/standard1-e7ffcc70389b11ec80da000000000006/md-486-big-Data.db: storage_io_error (Storage I/O error: 28: No space left on device)
2021-10-29T10:17:33+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | scylla: [shard 10] cql_server - exception while processing connection: seastar::nested_exception: std::system_error (error system:32, sendmsg: Broken pipe) (while cleaning up after std::system_error (error system:32, sendmsg: Broken pipe))
```

After that scylla was restarted. Scylla correctly started but then happened next on node6 and in 5 minutes on node5:
*node6*
```
2021-10-29T10:24:06+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | scylla: [shard 11] compaction - [Compact keyspace1.standard1 1a8d5490-38a2-11ec-88af-000000000008] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-e7ffcc70389b11ec80da000000000006/md-697-big-Data.db:level=0, ]. 6GB to 3GB (~59% of original) in 104409ms = 37MB/s. ~1262336 total partitions merged to 752267.
2021-10-29T10:24:07+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | scylla: [shard 11] compaction - [Compact keyspace1.standard1 597a2fc0-38a2-11ec-88af-000000000008] Compacting [/var/lib/scylla/data/keyspace1/standard1-e7ffcc70389b11ec80da000000000006/md-711-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-e7ffcc70389b11ec80da000000000006/md-683-big-Data.db:level=0, ]
2021-10-29T10:24:10+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | sshd[31478]: Accepted publickey for centos from 10.0.2.171 port 58060 ssh2: RSA SHA256:1YmYWh7roz4Y3FSY7N8CetmQNlK/K5FeBPITC8KF0u8
2021-10-29T10:24:10+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | systemd-logind: New session 839 of user scyllaadm.
2021-10-29T10:24:10+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | systemd: Started Session 839 of user scyllaadm.
2021-10-29T10:24:10+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | sshd[31478]: pam_unix(sshd:session): session opened for user centos by (uid=0)
2021-10-29T10:24:10+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | sshd[31478]: pam_unix(sshd:session): session closed for user centos
2021-10-29T10:24:10+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | systemd-logind: Removed session 839.
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !NOTICE  | sudo: scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/bin/coredumpctl --no-pager --no-legend
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | scylla: [shard 0] reader_concurrency_semaphore - Semaphore _read_concurrency_sem: timed out, dumping permit diagnostics:#012Permits with state active#012memory#011count#011name#0122603K#011100#011keyspace1.standard1:data-query#012#0122603K#011100#011total#012#012Permits with state waiting#012memory#011count#011name#0120B#0111268#011keyspace1.standard1:data-query#012#0120B#0111268#011total#012#012Total: permits: 1368, memory: 2603K
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !INFO    | sudo: pam_unix(sudo:session): session closed for user root
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.188, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:24:12+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-6 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 
```

*node5*
```
2021-10-29T10:27:10+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | scylla: [shard 5] compaction - [Compact keyspace1.standard1 c64daf00-38a2-11ec-8214-000000000004] Compacting [/var/lib/scylla/data/keyspace1/standard1-e7ffcc70389b11ec80da000000000006/md-663-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-e7ffcc70389b11ec80da000000000006/md-677-big-Data.db:level=0, ]
2021-10-29T10:27:10+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | sshd[23482]: Accepted publickey for centos from 10.0.2.171 port 36126 ssh2: RSA SHA256:1YmYWh7roz4Y3FSY7N8CetmQNlK/K5FeBPITC8KF0u8
2021-10-29T10:27:10+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | systemd-logind: New session 879 of user scyllaadm.
2021-10-29T10:27:10+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | systemd: Started Session 879 of user scyllaadm.
2021-10-29T10:27:10+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | sshd[23482]: pam_unix(sshd:session): session opened for user centos by (uid=0)
2021-10-29T10:27:11+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | sshd[23482]: pam_unix(sshd:session): session closed for user centos
2021-10-29T10:27:11+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | systemd-logind: Removed session 879.
2021-10-29T10:27:16+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | sshd[23496]: Accepted publickey for centos from 10.0.2.171 port 36146 ssh2: RSA SHA256:1YmYWh7roz4Y3FSY7N8CetmQNlK/K5FeBPITC8KF0u8
2021-10-29T10:27:16+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | systemd-logind: New session 880 of user scyllaadm.
2021-10-29T10:27:16+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | systemd: Started Session 880 of user scyllaadm.
2021-10-29T10:27:16+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | sshd[23496]: pam_unix(sshd:session): session opened for user centos by (uid=0)
2021-10-29T10:27:16+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | sshd[23496]: pam_unix(sshd:session): session closed for user centos
2021-10-29T10:27:16+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | systemd-logind: Removed session 880.
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !INFO    | scylla: [shard 0] reader_concurrency_semaphore - Semaphore _read_concurrency_sem: timed out, dumping permit diagnostics:#012Permits with state active#012memory#011count#011name#0122683K#011100#011keyspace1.standard1:data-query#012#0122683K#011100#011total#012#012Permits with state waiting#012memory#011count#011name#0120B#0111115#011keyspace1.standard1:data-query#012#0120B#0111115#011total#012#012Total: permits: 1215, memory: 2683K
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T10:27:21+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-5 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.0.206, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
```
This nemesis repeated in 30 minutes on node1 and node6 and info and error message were repeated:
```
2021-10-29T11:09:58+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | scylla: [shard 0] compaction - [Compact keyspace1.standard1 c0c85b60-38a8-11ec-a4f7-000000000000] Compacting [/var/lib/scylla/data/keyspace1/standard1-e7ffcc70389b11ec80da000000000006/md-9954-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-e7ffcc70389b11ec80da000000000006/md-9982-big-Data.db:level=0, ]
2021-10-29T11:09:58+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | sshd[45640]: Accepted publickey for centos from 10.0.2.171 port 55174 ssh2: RSA SHA256:1YmYWh7roz4Y3FSY7N8CetmQNlK/K5FeBPITC8KF0u8
2021-10-29T11:09:58+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | systemd-logind: New session 1321 of user scyllaadm.
2021-10-29T11:09:58+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | systemd: Started Session 1321 of user scyllaadm.
2021-10-29T11:09:58+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | sshd[45640]: pam_unix(sshd:session): session opened for user centos by (uid=0)
2021-10-29T11:09:58+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | sshd[45640]: pam_unix(sshd:session): session closed for user centos
2021-10-29T11:09:58+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | systemd-logind: Removed session 1321.
2021-10-29T11:10:01+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !NOTICE  | sudo: scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/bin/coredumpctl --no-pager --no-legend
2021-10-29T11:10:01+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
2021-10-29T11:10:01+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | sudo: pam_unix(sudo:session): session closed for user root
2021-10-29T11:10:03+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | scylla: [shard 12] reader_concurrency_semaphore - Semaphore _read_concurrency_sem: timed out, dumping permit diagnostics:#012Permits with state active#012memory#011count#011name#0122676K#011100#011keyspace1.standard1:data-query#012#0122676K#011100#011total#012#012Permits with state waiting#012memory#011count#011name#0120B#011604#011keyspace1.standard1:data-query#012#0120B#011604#011total#012#012Total: permits: 704, memory: 2676K
2021-10-29T11:10:03+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:03+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:03+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:03+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | dhclient[1207]: PRC: Renewing lease on eth0.
2021-10-29T11:10:03+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | dhclient[1207]: XMT: Renew on eth0, interval 9590ms.
2021-10-29T11:10:03+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | dhclient[1207]: RCV: Reply message on eth0 from fe80::4be:8fff:fef6:4fe0.
2021-10-29T11:10:03+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | sshd[45675]: Accepted publickey for centos from 10.0.2.171 port 55198 ssh2: RSA SHA256:1YmYWh7roz4Y3FSY7N8CetmQNlK/K5FeBPITC8KF0u8
2021-10-29T11:10:04+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:04+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:04+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:04+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:04+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:04+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:04+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:04+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !INFO    | systemd-logind: New session 1322 of user scyllaadm.
2021-10-29T11:10:04+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:04+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T11:10:04+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-1 !ERR     | scylla: [shard 12] storage_proxy - Exception when communicating with 10.0.3.172, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
```

Restore Monitor Stack command: `$ hydra investigate show-monitor 28ff234e-1a13-4652-93b7-af9d0ddb7956`
Show all stored logs command: `$ hydra investigate show-logs 28ff234e-1a13-4652-93b7-af9d0ddb7956`

Test id: `28ff234e-1a13-4652-93b7-af9d0ddb7956`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_134803/grafana-screenshot-longevity-100gb-4h-test-scylla-per-server-metrics-nemesis-20211029_135144-longevity-100gb-4h-4-4-monitor-node-28ff234e-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_134803/grafana-screenshot-longevity-100gb-4h-test-scylla-per-server-metrics-nemesis-20211029_135144-longevity-100gb-4h-4-4-monitor-node-28ff234e-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_134803/grafana-screenshot-overview-20211029_134803-longevity-100gb-4h-4-4-monitor-node-28ff234e-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_134803/grafana-screenshot-overview-20211029_134803-longevity-100gb-4h-4-4-monitor-node-28ff234e-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_135628/db-cluster-28ff234e.zip](https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_135628/db-cluster-28ff234e.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_135628/loader-set-28ff234e.zip](https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_135628/loader-set-28ff234e.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_135628/monitor-set-28ff234e.zip](https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_135628/monitor-set-28ff234e.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_135628/sct-runner-28ff234e.zip](https://cloudius-jenkins-test.s3.amazonaws.com/28ff234e-1a13-4652-93b7-af9d0ddb7956/20211029_135628/sct-runner-28ff234e.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.4/job/longevity/job/longevity-100gb-4h-test/68/)

**Comment by aleksbykov** [comment] 2021-11-01 12:37
This info message:`2021-10-29T12:02:38+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-7 !INFO    | scylla: [shard 4] reader_concurrency_semaphore - Semaphore _read_concurrency_sem: timed out, dumping permit diagnostics:#012Permits with state active#012memory#011count#011name#0123255K#011100#011keyspace1.standard1:data-query#012#0123255K#011100#011total#012#012Permits with state waiting#012memory#011count#011name#0120B#011626#011keyspace1.standard1:data-query#012#0120B#011626#011total#012#012Total: permits: 726, memory: 3255K`
periodically appeared during tests on each nodes and trigger the 
```
2021-10-29T12:02:38+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-7 !ERR     | scylla: [shard 4] storage_proxy - Exception when communicating with 10.0.3.173, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
2021-10-29T12:02:38+00:00  longevity-100gb-4h-4-4-db-node-28ff234e-7 !ERR     | scylla: [shard 4] storage_proxy - Exception when communicating with 10.0.3.173, to read from keyspace1.standard1: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
````
and could affect on payload.
such error tirgger to failed 2 c-s commands during nemesis NoCorruptRepair.

**Comment by slivne** [comment] 2022-04-05 20:09
the i/o scheduler in 5.0 should be better in handling this - e.g. ongoing read should not be "starved" because we have a background repair.

Lets see if this reproduces in 5.0 or not.

**Comment by DoronArazii** [comment] 2022-10-12 08:33
@aleksbykov /  @roydahan please try to reproduce it

**Comment by roydahan** [comment] 2022-11-06 18:24
Closing for now.
If we bump into this we'll reopen.

**Closed by roydahan** 2022-11-06 18:24 UTC
Labels: bug, high
