### ISSUE TITLE
test_change_ip.test_change_two fail on aarch64 on debug mode

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylladb#14257] opened 2023-06-15 09:12 UTC
Seen twice on master **aarch64 debug mode**, work as expected on x86 and aarch64 release/dev mode

- https://jenkins.scylladb.com/job/scylla-master/job/build/1491
- https://jenkins.scylladb.com/job/scylla-master/job/build/1490

Run on AWS im4gn.4xlarge (FC37)

```
manager = <test.pylib.manager_client.ManagerClient object at 0xffff79b0bc50>
random_tables = <test.pylib.random_tables.RandomTables object at 0xffff79affa90>

    @pytest.mark.asyncio
    async def test_change_two(manager, random_tables):
        """Stop two nodes, change their IPs and start, check the cluster is
        funcitonal"""
        servers = await manager.running_servers()
        table = await random_tables.add_table(ncolumns=5)
        s_1 = servers[1].server_id
        s_2 = servers[2].server_id
        logger.info("Gracefully stopping servers %s and %s to change ips", s_1, s_2)
        await manager.server_stop_gracefully(s_1)
        await manager.server_stop_gracefully(s_2)
        await manager.server_change_ip(s_1)
        await manager.server_change_ip(s_2)
        await manager.server_start(s_1)
        await manager.server_start(s_2)
        await table.add_column()
>       await random_tables.verify_schema()

test/topology/test_change_ip.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/pylib/random_tables.py:332: in verify_schema
    await read_barrier(cql, host)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cql = <cassandra.cluster.Session object at 0xffff79ac8dd0>
host = <Host: 127.89.30.35:9042 datacenter1>

    async def read_barrier(cql: Session, host: Host):
        """To issue a read barrier it is sufficient to attempt dropping a
        non-existing table. We need to use `if exists`, otherwise the statement
        would fail on prepare/validate step which happens before a read barrier is
        performed.
        """
>       await cql.run_async("drop table if exists nosuchkeyspace.nosuchtable", host = host)
E       cassandra.OperationTimedOut: errors={'127.89.30.35:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.89.30.35:9042

test/pylib/util.py:121: OperationTimedOut
```

**Comment by benipeled** [comment] 2023-06-15 09:25
```
[2023-06-15T04:45:38.245Z] 07:23:46.728 WARNING> Node 127.89.30.36:9042 is reporting a schema disagreement: {UUID('d110f0cf-6192-3229-8c4d-82b15caa4ba8'): [<DefaultEndPoint: 127.89.30.36:9042>, <DefaultEndPoint: 127.89.30.3:9042>], UUID('7a3ec328-219f-3ec3-a765-f674e213a4a8'): [<DefaultEndPoint: 127.89.30.35:9042>]}
[2023-06-15T04:45:38.245Z] 07:23:46.728 DEBUG> Skipping schema refresh due to lack of schema agreement
```

**Comment by kbr-scylla** [comment] 2023-06-16 13:36
There were 3 nodes:
- scylla-181, started with IP .3 and never changed it
- scylla-198, changed IP from .19 to .35
- scylla-207, changed IP from .23 to .36

The schema change
```
        await table.add_column()
```

happened on scylla-207
```
INFO  2023-06-15 07:23:24,141 [shard 0] migration_manager - Update table 'test_1686802689068.t_01' From org.apache.cassandra.config.CFMetaData@0xfffe57767c80[cfId=a5582900-0b33-11ee-8fa4-22b5d52904de,ksName=test_1686802689068,cfName=t_01,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.UUIDType,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.UUIDType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=c_01, type=org.apache.cassandra.db.marshal.UTF8Type, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_01, type=org.apache.cassandra.db.marshal.FloatType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_02, type=org.apache.cassandra.db.marshal.Int32Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_03, type=org.apache.cassandra.db.marshal.UUIDType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=e346679c-bf40-32a3-91ed-c59f60cb2c5a,droppedColumns={},collections={},indices={}] To org.apache.cassandra.config.CFMetaData@0xfffe5c433e80[cfId=a5582900-0b33-11ee-8fa4-22b5d52904de,ksName=test_1686802689068,cfName=t_01,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.UUIDType,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.UUIDType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=c_01, type=org.apache.cassandra.db.marshal.UTF8Type, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_01, type=org.apache.cassandra.db.marshal.FloatType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_02, type=org.apache.cassandra.db.marshal.Int32Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_03, type=org.apache.cassandra.db.marshal.UUIDType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_04, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=5e2ee2c0-0b34-11ee-a125-b350f3c656ff,droppedColumns={},collections={},indices={}]
INFO  2023-06-15 07:23:24,623 [shard 0] schema_tables - Altering test_1686802689068.t_01 id=a5582900-0b33-11ee-8fa4-22b5d52904de version=60ead58a-98d0-3f06-b0c0-661961f91cba
INFO  2023-06-15 07:23:24,664 [shard 0] query_processor - Column definitions for test_1686802689068.t_01 changed, invalidating related prepared statements
INFO  2023-06-15 07:23:24,679 [shard 1] query_processor - Column definitions for test_1686802689068.t_01 changed, invalidating related prepared statements
INFO  2023-06-15 07:23:26,632 [shard 0] schema_tables - Schema version changed to d110f0cf-6192-3229-8c4d-82b15caa4ba8
```

It also reached scylla-181
```
INFO  2023-06-15 07:23:24,440 [shard 0] schema_tables - Altering test_1686802689068.t_01 id=a5582900-0b33-11ee-8fa4-22b5d52904de version=60ead58a-98d0-3f06-b0c0-661961f91cba
INFO  2023-06-15 07:23:24,477 [shard 0] query_processor - Column definitions for test_1686802689068.t_01 changed, invalidating related prepared statements
INFO  2023-06-15 07:23:24,497 [shard 1] query_processor - Column definitions for test_1686802689068.t_01 changed, invalidating related prepared statements
INFO  2023-06-15 07:23:25,918 [shard 0] schema_tables - Schema version changed to d110f0cf-6192-3229-8c4d-82b15caa4ba8
```

However, it never reached scylla-198. This caused schema agreement to time out.

The read barrier which timed out was executed on scylla-198:
```
E       cassandra.OperationTimedOut: errors={'127.89.30.35:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.89.30.35:9042
```

So it looks like for some reason, scylla-198 completely lost group 0 connectivity to the other two nodes; it explains why the schema change didn't reach it (note that we no longer pull schemas outside Raft) and why the read barrier timed out (it needs 2 nodes, but scylla-198 was alone).

But it **did** see the other two nodes in gossip after restart:
```
INFO  2023-06-15 07:20:47,057 [shard 0] gossip - InetAddress 127.89.30.3 is now UP, status = NORMAL
...
INFO  2023-06-15 07:22:56,493 [shard 0] gossip - InetAddress 127.89.30.36 is now UP, status = NORMAL
```

so why wasn't group 0 able to connect?
Perhaps there are some (timing) conditions under which we don't update the address map properly?

cc @kostja

**Comment by kbr-scylla** [comment] 2023-06-16 13:51
Ah, the problem was on scylla-181 side, the one who didn't change its IP. It marked scylla-198 as alive after it restarted, but then for some reason, it marked it as dead again!
```
INFO  2023-06-15 07:20:49,881 [shard 0] raft_group_registry - marking Raft server fb307789-949a-4db0-a931-6d2d18345b0a as alive for raft groups
...
INFO  2023-06-15 07:22:55,063 [shard 0] raft_group_registry - marking Raft server fb307789-949a-4db0-a931-6d2d18345b0a as dead for raft groups
```

There was also a suspicious `connection_close` from `gossiper` to scylla-198's old IP...
```
WARN  2023-06-15 07:22:55,429 [shard 0] gossip - Fail to send EchoMessage to 127.89.30.19: seastar::rpc::closed_error (connection is closed)
```

Hmmm... could it be that scylla-181 got a notification from gossiper using scylla-198's old IP, and replaced the entry in raft_address_map with the old IP (i.e. .19 instead of .35)? That would explain the permanent loss of connectivity.

**Comment by tgrabiec** [comment] 2023-06-19 11:08
In https://github.com/scylladb/scylladb/issues/14274 I observe that only the coordinator didn't get the schema change. That can't be explained by connectivity problems, can it?

**Comment by tgrabiec** [comment] 2023-06-19 11:59
Should we log leader failover events to improve debuggability?

**Comment by kbr-scylla** [comment] 2023-06-19 12:01
> Should we log leader failover events to improve debuggability?

+1
I would support logging on INFO level when a node stops being a leader or becomes one.
@kostja ?

**Comment by kostja** [comment] 2023-06-19 13:12
* Kamil Braun ***@***.***> [23/06/19 15:02]:
> > Should we log leader failover events to improve debuggability?
> 
> +1
> I would support logging on INFO level when a node stops being a leader or becomes one.
> @kostja ?

This could flood the log on flaky network. But let's try.


-- 
Konstantin Osipov, Moscow, Russia

**Comment by kbr-scylla** [comment] 2023-06-20 12:13
Seen again: https://github.com/scylladb/scylladb/issues/14257

**Comment by kbr-scylla** [comment] 2023-06-20 12:15
And https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1949/

**Comment by kbr-scylla** [comment] 2023-06-20 12:16
And https://jenkins.scylladb.com/job/scylla-master/job/build/1500/

wow, this test is failing often.

**Comment by kbr-scylla** [comment] 2023-06-22 14:28
Reproducer: https://github.com/kbr-scylla/scylladb/commit/3853c9abf490b95696fe6c762a12022f1ed53d00
Run with `./test.py --mode dev ip_repro -s -v`

It starts two nodes. It introduces a sleep in `gossiper_state_change_subscriber_proxy::on_alive` (in raft_group_registry.cc) when receiving a gossip notification about HOST_ID update from the second node. Then it restarts the second node with a different IP. Due to the sleep, the old notification from the old IP arrives after the second node has restarted and overrides the address map entry.

**Closed** 2023-07-05 00:48 UTC
Labels: P1

**Comment by avikivity** [comment] 2023-09-18 18:41
@kbr-scylla please evaluate for backport

**Comment by kbr-scylla** [comment] 2023-09-19 09:14
Backported to 5.2 with the following note:
```
    Backport note: replaced `gms::generation_type` with `int64_t` because
    the branch is missing the refactor which introduced `generation_type`
    (7f04d8231df86ae4dda31318464fa0e8a100eaff)
```
