### ISSUE TITLE
Scylla sum function fails when used with case-sensitive column names.

### ISSUE THREAD

**Issue by SliverFang** [scylladb/scylladb#14307] opened 2023-06-20 05:42 UTC
Queries with sum function fails on scylla 5.2 when used with camelCase column names.

cqlsh> CREATE TABLE traffickeyspace.trip ("accountId" int, "groupId" int, "tOdo" double, sodo double, PRIMARY KEY ("accountId", "groupId")) WITH CLUSTERING ORDER BY ("groupId" DESC);
cqlsh> INSERT INTO traffickeyspace.trip ("accountId", "groupId", "tOdo", sodo) VALUES (113, 0, 5.0,1.2);
cqlsh> SELECT * from traffickeyspace.trip;

 accountId | groupId | sodo | tOdo
-----------+---------+------+------
       113 |       0 |  1.2 |    5

(1 rows)
cqlsh> SELECT "tOdo" from traffickeyspace.trip;

 tOdo
------
    5

(1 rows)
cqlsh> SELECT sum("tOdo") from traffickeyspace.trip;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Undefined name todo in selection clause"

**Comment by cvybhu** [comment] 2023-06-21 05:52
The error happens somewhere between the parser and `prepare_expression`.

It looks like the parser does the right thing, it should create a `raw_column_identifier` with `case_sensitive = true`, but then in `prepare_selectable/prepare_expression`, the name is sometimes lowercase, the case sensitivity gets lost.
```
unin.ident->_text: mycol
```

**Comment by cvybhu** [comment] 2023-06-21 09:22
Looks like the error is here:
https://github.com/scylladb/scylladb/blob/643e69af891c61af6ce75e55ffe9031295fdc20e/service/forward_service.cc#L334-L337

It creates a case-insensitive (lowercase) `column_identifier` from raw column name, and stuff breaks.
Flipping this to `true` fixes the problem.

**Comment by cvybhu** [comment] 2023-06-21 11:15
Curiously, it looks like in the meantime it has been fixed by 643e69af891c61af6ce75e55ffe9031295fdc20e 0_o

**Comment by cvybhu** [comment] 2023-06-21 11:19
Test case:
```cql
DROP KEYSPACE IF EXISTS ks;
CREATE KEYSPACE ks WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1};
CREATE TABLE ks.t ("myCol" int primary key);
SELECT SUM("myCol") FROM ks.t;
```

453bbc1115714390e08e68d1d7627a0ef7ee2c60: InvalidRequest: Error from server: code=2200 [Invalid query] message="Unrecognized name mycol"
643e69af891c61af6ce75e55ffe9031295fdc20e: works, no error

A bit weird, as 453bbc1115714390e08e68d1d7627a0ef7ee2c60 is about raft features.
Maybe enabling some of them caused us to stop using `forward_service.cc`, and the problem doesn't happen?

**Comment by avikivity** [comment] 2023-06-21 11:28
Probably. If so that's a big regression. @piodul

**Comment by piodul** [comment] 2023-06-21 12:14
> Test case:
> 
> ```sql
> DROP KEYSPACE IF EXISTS ks;
> CREATE KEYSPACE ks WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1};
> CREATE TABLE ks.t ("myCol" int primary key);
> SELECT SUM("myCol") FROM ks.t;
> ```
> 
> [453bbc1](https://github.com/scylladb/scylladb/commit/453bbc1115714390e08e68d1d7627a0ef7ee2c60): InvalidRequest: Error from server: code=2200 [Invalid query] message="Unrecognized name mycol" [643e69a](https://github.com/scylladb/scylladb/commit/643e69af891c61af6ce75e55ffe9031295fdc20e): works, no error
> 
> A bit weird, as [453bbc1](https://github.com/scylladb/scylladb/commit/453bbc1115714390e08e68d1d7627a0ef7ee2c60) is about raft features. Maybe enabling some of them caused us to stop using `forward_service.cc`, and the problem doesn't happen?

Doesn't reproduce for me. I built both versions and I get the error message with both. In both cases I set up a new single-node cluster on scratch.

My recent changes shouldn't affect anything, they only store supported cluster features in group 0 table but don't use this information to enable any of the `gms::feature` objects. This will be handled in later PRs.

**Comment by cvybhu** [comment] 2023-06-21 12:25
> Doesn't reproduce for me. I built both versions and I get the error message with both. In both cases I set up a new single-node cluster from scratch.

Looks like you're right.
I ran `ninja clean`, `rm -rf build`, `rm ninja.build`, `ccache -c`, built `master` again and the issue is present on `master` again -,-
Guess the build system ran into some bug and didn't notice a change in the file.

Well that's good news, it makes the change simpler.

**Closed** 2023-06-22 18:01 UTC
Labels: bug, User Request, CQL

**Comment by shantanugithub** [comment] 2023-07-09 19:49
We are at 5.2.3 version. In which minor version we can expect this fix to come ? @DoronArazii @cvybhu

**Comment by DoronArazii** [comment] 2023-07-10 08:40
@shantanugithub,
 
@scylladb/scylla-maint should consider the backport, and right after that I will be able to tell you where it will land.

**Comment by denesb** [comment] 2023-07-10 12:23
Backported to 5.3 and 5.2.

**Comment by denesb** [comment] 2023-07-10 12:23
@piodul please follow-up the fix with a PR adding a test, which catches the bug.

**Comment by cvybhu** [comment] 2023-07-10 12:29
> @piodul please follow-up the fix with a PR adding a test, which catches the bug.

It was my fix, and there was a cql-pytest that reproduces the issue in the PR.

**Comment by denesb** [comment] 2023-07-11 08:31
> > @piodul please follow-up the fix with a PR adding a test, which catches the bug.
> 
> It was my fix, and there was a cql-pytest that reproduces the issue in the PR.

Looks like the `Fixes` tag was added to just the commit and not the entire PR. So I only ended up backporting the fix itself.

**Comment by DoronArazii** [comment] 2023-07-11 08:37
> @shantanugithub,
> 
> @scylladb/scylla-maint should consider the backport, and right after that I will be able to tell you where it will land.

Fix was backported. thanks botond.

@shantanugithub you'll find the fix in the next open source release of 5.2 - "5.2.5".

**Comment by shantanugithub** [comment] 2023-07-11 10:49
Thanks @DoronArazii !

**Comment by DoronArazii** [comment] 2023-07-13 16:36
Backported.
Removing the label.
