### ISSUE TITLE
Increase max number of scheduling groups

### ISSUE THREAD

**Issue by Jadw1** [scylladb/scylladb#21051] opened 2024-10-10 14:13 UTC
Our docs states that user can create up to 7 service levels in enterprise.
However in https://github.com/scylladb/scylladb/pull/18715, we added new internal scheduling group thereby decreasing max number of service levels in enterprise.

`SCHEDULING_GROUPS_COUNT` should be adjusted to not affect service levels.

**Comment by piodul** [comment] 2024-10-10 16:13
In addition to doing this, we should have a regression test / static assertion / etc. that will prevent such regressions in the future.

**Comment by Jadw1** [comment] 2024-10-13 09:51
> I don't think it's necessary to test this in open source Scylla if the limitation doesn't exist there - you can check it where this limitation does exist.
 
I've opened this issue in open source repo to increase `SCHEDULING_GROUPS_COUNT` in open source Scylla and not increase differences between OSS and enterprise. But in theory OSS doesn't need more scheduling groups as it doesn't have workload prioritization feature.

So, should we increase `SCHEDULING_GROUPS_COUNT`:
- both in OSS and enterprise. If so, I think the regression test should be done in OSS
- only in enterprise. Then, the test can be only in enterprise, where it's easier to do it (service levels are creating scheduling groups)

?

**Comment by Jadw1** [comment] 2024-10-14 13:30
> So, should we increase `SCHEDULING_GROUPS_COUNT`:
> 
> * both in OSS and enterprise. If so, I think the regression test should be done in OSS
> * only in enterprise. Then, the test can be only in enterprise, where it's easier to do it (service levels are creating scheduling groups)
> 
> ?

@avikivity what do you think? We don't have to the regression test in OSS new internal scheduling groups are often added in OSS, which can lead to failed regression test during OSS->enterprise merge (which is mainly done by you ;) )
I'd like to solve this issue quickly as it's a blocker for a few of PRs.

**Comment by piodul** [comment] 2024-10-15 09:37
(moving my comment here from the seastar issue, I didn't notice that the discussion was moved)

> I don't think it's necessary to test this in open source Scylla if the limitation doesn't exist there - you can check it where this limitation does exist.

The problem is that introducing a new scheduling group in open source introduces a problem which is only noticed later when merging OSS -> Enterprise. I assume (maybe incorrectly) that we want to keep `SEASTAR_SCHEDULING_GROUPS_COUNT` in sync between two repos, so the fix in this case is to go back to open source and bump the value of the variable. Therefore we wanted to have a test which forces one to bump the variable in OSS when introducing a new scheduling group - to avoid a painful situation.

Having this API would make the test that we wanted to introduce slightly less cumbersome - we intended to have a test-only API that returns the number of available scheduling groups and run it on a real scylla node. The alternative would be to just try to see how many scheduling groups we can create and report that.

**Comment by Jadw1** [comment] 2024-10-28 11:57
After [Avi's comment](https://github.com/scylladb/scylladb/pull/21259#issuecomment-2440119639) I've opened [a mirror issue](https://github.com/scylladb/scylla-enterprise/issues/4864) in enterprise and I'll move [the PR](https://github.com/scylladb/scylladb/pull/21259) there.

I'll keep this issue opened until the decision whether should we add a regression test. After @avikivity's comment
> It's completely superfluous to OSS.
I guess enterprise test is enough. But could you confirm?

**Comment by piodul** [comment] 2024-10-29 10:22
@Jadw1 no need to add a regression test to open source, the scheduling group count in OSS is independent of the scheduling group count in enterprise.

There should be a regression test, but it should be enterprise only. It should be a part of https://github.com/scylladb/scylla-enterprise/pull/4764. If there is a new scheduling group introduced in open source, the test will catch this during merge and the SG count should be bumped in the merge commit.

If you agree, please close the issue.

**Comment by piodul** [comment] 2024-11-13 07:36
I'll close, @Jadw1 please reopen if you think it should be kept open.

**Closed by piodul** 2024-11-13 07:36 UTC
Labels: backport/6.1, backport/6.2

**Comment by Jadw1** [comment] 2024-11-13 09:17
> I'll close, [@Jadw1](https://github.com/Jadw1) please reopen if you think it should be kept open.

No, number of sheduling group is correct in enterprise and it already doesn't match OSS number. So, there is no reason to increase it in OSS for now.
