### ISSUE TITLE
Scylla was not started on new added node with bootstrappstd::runtime_error ({shard 0: std::runtime_error (get_repair_meta: repair_meta_id

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#7232] opened 2020-09-14 09:13 UTC
*Installation details*
Scylla version (or git commit hash): 4.2.rc4-0.20200912.338196eab with build-id 2810cfc346e1ebadd0921e145b8423cddb1466e2
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0a08ac3253b2ffb1b (eu-north-1)

During job https://jenkins.scylladb.com/job/scylla-4.2/job/longevity/job/longevity-cdc-100gb-4h-test/48/, nemesis TerminateAndReplaceNode terminates one node and  adds new one to cluster.
New node7 was adding, but scylla start failed with error:
```
2020-09-13T11:21:43+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 8] compaction - Compacted 746 sstables to [/var/lib/scylla/data/cdc_test/test_table_preimage_postimage_scylla_cdc_log-09c278d0f59a11ea8684000000000007/mc-60614-big-Data.db:level=0, ]. 10MB to 36kB (~0% of original) in 9275878ms = 3 bytes/s. ~95488 total partitions merged to 32.
2020-09-13T11:21:43+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 8] compaction - Compacted 19 sstables to []. 233kB to 0 bytes (~0% of original) in 506194ms = 0 bytes/s. ~2432 total partitions merged to 0.
2020-09-13T11:21:43+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 8] compaction - Compacted 427 sstables to [/var/lib/scylla/data/cdc_test/test_table_preimage_scylla_cdc_log-c1dda030f59911eabbfc000000000001/mc-28498-big-Data.db:level=0, ]. 5MB to 38kB (~0% of original) in 9362568ms = 4 bytes/s. ~54656 total partitions merged to 32.
2020-09-13T11:21:43+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 8] compaction_manager - Stopped
2020-09-13T11:21:48+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | sshd[71418]: Accepted publickey for centos from 10.0.2.207 port 55798 ssh2: RSA SHA256:g7OmDbWC8qLUZHxjMohQe3LsQHfcOJbG1ZHqodB6smc
2020-09-13T11:21:48+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | systemd-logind: New session 1804 of user centos.
2020-09-13T11:21:48+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | systemd: Started Session 1804 of user centos.
2020-09-13T11:21:48+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | sshd[71418]: pam_unix(sshd:session): session opened for user centos by (uid=0)
2020-09-13T11:21:48+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | sshd[71418]: pam_unix(sshd:session): session closed for user centos
2020-09-13T11:21:48+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | systemd-logind: Removed session 1804.
2020-09-13T11:21:49+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 0] init - Shutting down database: waiting for background jobs...
2020-09-13T11:21:49+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 0] init - Shutting down database was successful
2020-09-13T11:21:49+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 0] init - Shutting down migration manager notifier
2020-09-13T11:21:49+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 0] init - Shutting down migration manager notifier was successful
2020-09-13T11:21:49+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 0] init - Shutting down prometheus API server
2020-09-13T11:21:49+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 0] init - Shutting down prometheus API server was successful
2020-09-13T11:21:49+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 0] init - Shutting down sighup
2020-09-13T11:21:49+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !INFO    | scylla: [shard 0] init - Shutting down sighup was successful
2020-09-13T11:21:49+00:00  longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 !ERR     | scylla: [shard 0] init - Startup failed: std::runtime_error ({shard 0: std::runtime_error (get_repair_meta: repair_meta_id 34685 for node 10.0.2.82 does not exist), shard 1: std::runtime_error (get_repair_meta: repair_meta_id 39878 for node 10.0.2.82 does not exist), shard 2: std::runtime_error (get_repair_meta: repair_meta_id 32450 for node 10.0.2.82 does not exist), shard 3: std::runtime_error (get_repair_meta: repair_meta_id 33163 for node 10.0.2.82 does not exist), shard 4: std::runtime_error (get_repair_meta: repair_meta_id 34823 for node 10.0.2.82 does not exist), shard 5: seastar::rpc::closed_error (connection is closed), shard 6: seastar::rpc::closed_error (connection is closed), shard 7: std::runtime_error (get_repair_meta: repair_meta_id 34548 for node 10.0.2.82 does not exist), shard 8: std::runtime_error (get_repair_meta: repair_meta_id 34544 for node 10.0.2.82 does not exist), shard 9: seastar::rpc::closed_error (connection is closed), shard 10: seastar::rpc::closed_error (connection is closed), shard 11: std::runtime_error (get_repair_meta: repair_meta_id 34723 for node 10.0.2.82 does not exist), shard 12: std::runtime_error (get_repair_meta: repair_meta_id 34839 for node 10.0.2.82 does not exist), shard 13: std::runtime_error (get_repair_meta: repair_meta_id 34732 for node 10.0.2.82 does not exist)})
```
DB log:
[system.log.tar.gz](https://github.com/scylladb/scylla/files/5217339/system.log.tar.gz)

**Comment by asias** [comment] 2020-09-16 06:05
I need full logs of all nodes.

**Comment by asias** [comment] 2020-09-16 06:09
Looks like the same issue we saw that one repair follower removes repair instances with the replacing node because it thinks the replacing node is DOWN.

**Comment by asias** [comment] 2020-09-16 06:12
Similar errors:
```
Sep 13 11:06:14 longevity-cdc-100gb-4h-4-2-db-node-360918f5-7 scylla[3456]:  [shard 6] storage_proxy - Failed to apply mutation from 10.0.0.29#6: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 8->6 semaphore)
```
There were tons of such errors:

```
$ cat system.log|grep -v compaction|grep named_semaphore|wc -l
86169
```

**Comment by aleksbykov** [comment] 2020-09-16 06:30
All logs should be available by link https://cloudius-jenkins-test.s3.amazonaws.com/360918f5-fb68-4dba-9664-4cd1038913c2/20200913_133550/db-cluster-360918f5.zip

**Comment by asias** [comment] 2020-09-16 07:35
Duplication of issue: https://github.com/scylladb/scylla/issues/7025

**Comment by slivne** [comment] 2020-09-16 11:46
@asias I don't understand the issue fully and I don;t understand if repair based operations will work or not in 4.2 as well 

- If we would have used streaming would this work ?

- I thought this happens after the node finishes to replace the missing node - if thats not the case, does it happen while its still repairing/streaming the data ?

- We have the semaphore timeout errors - yet that does not clarify if this should fail the replace operation and the replacing node should crash or not ?

We did not see this outside of CDC - I know - yet I am concerned there is a bug here that we will have issues with with repair_based_operations (even if its not the fault of repair based operations to begin with).

So what is the bug (aside of the smp_service_group for HH) that eliran is fixing - and a client that is not shared aware that QA will fix ?

**Comment by asias** [comment] 2020-09-17 08:08
The issue is not related to repair based operation. The issue can happen even with regular repair. The issue is a node is overwhelmed by hinted-hand off and gossip heartbeat is not updated in a timely manner. As a result, this node is marked as down. 

With streaming based node operation, if a node is marked as down, the streaming will fail too.

The difference is that repair based node operation have more work to do compared to streaming based node operation. So it can make the overwhelm event more easily to happen. 

What is the bug:  Why HH dominate and starve other tasks like gossip so badly.

**Comment by slivne** [comment] 2020-09-17 11:08
@avikivity - we need to consider backporting eliran's fix to have HH use a different smp_serice group (and not use the regyular read/writes ones).

**Comment by avikivity** [comment] 2020-09-22 12:46
@slivne done

**Comment by slivne** [comment] 2020-12-20 20:31
repair-based-operations are not enabled by default in 4.3 - pushing this to 4.4

**Comment by DoronArazii** [comment] 2022-10-12 08:55
@eliransin / @roydahan i'm closing this case - we can always reopen

**Closed by DoronArazii** 2022-10-12 08:55 UTC
Labels: bug, high, repair-based-operations
