### ISSUE TITLE
Internode compression is broken

### ISSUE THREAD

**Issue by Laboltus** [scylladb/scylladb#14315] opened 2023-06-20 15:54 UTC
It was fixed in https://github.com/scylladb/scylladb/issues/5963  but now I'm running 5.1.11 and see the same symptom - plain text on port 7000.

**Comment by roydahan** [comment] 2023-06-20 20:57
@Laboltus, Do you see "ssl_storage_port" 7001 listening?

**Comment by Laboltus** [comment] 2023-06-20 21:02
No, I didn't enable ssl.

**Comment by DoronArazii** [comment] 2023-06-21 11:34
@gleb-cloudius please advise 
(I think rpc-compression it's your area of expertise)

**Comment by gleb-cloudius** [comment] 2023-06-21 11:39
> @gleb-cloudius please advise (I think rpc-compression it's your area of expertise)

@elcallio fixed it last time around. In https://github.com/scylladb/scylladb/issues/5963 there was a request to add a test for it. @roydahan was it done? If not this is the time to do it and bisect  where the problem started again.

**Comment by roydahan** [comment] 2023-06-21 13:39
The configuration was added during rolling upgrade as requested.
But please test if it works with the unittests you have for it.

**Comment by gleb-cloudius** [comment] 2023-06-21 13:45
> The configuration was added during rolling upgrade as requested.

So why it did not detect it? Does the test actually check that the data is compressed?

> But please test if it works with the unittests you have for it.

There is no unit test for it. One also is impossible to write. May be it is possible to write a cluster test in test.py.

**Comment by avikivity** [comment] 2023-06-21 15:19
@Laboltus are you sure it's broken? you often see plain text even in compressed messages, since compression is per-message, and for the first few bytes the compression algorithm quotes literal text.

**Comment by Laboltus** [comment] 2023-06-21 15:26
Yes, I see whole record's content.

**Comment by mykaul** [comment] 2023-06-29 14:11
@gleb-cloudius - can you please take a look?

**Comment by nyh** [comment] 2023-07-03 07:46
Unfortunately we have multiple discussion threads on this issue, with different observations made in different threads. In another thread, it was noted that the LZ4 compression algorithm which we use for internode compression only uses a sliding-window dictionary modeler, WITHOUT a second entropy-coding step. This means that a lot of the plain-text remains visible - only repetitions of the same long strings of characters are removed, but you see each of them in plain-text once.

@Laboltus said "Yes, I see whole record's content.". Are you sure about this? Can you please make extra sure that you don't see "a lot" of it, but not the entire uncompressed content?

If internode compression is actually working - but just offers lousy size reductions - we should close this issue and instead open a different issue asking to improve the compression, either by choosing a better compression algorithm (e.g., zstd instead of lz4) or perhaps by using longer history in the compression instead of just single packets as we do now.

@roydahan it should be possible to write a regression test that verifies that the internode compression still works and can't suddenly stop working.

**Comment by mykaul** [comment] 2023-07-03 08:32
> If internode compression is actually working - but just offers lousy size reductions - we should close this issue and instead open a different issue asking to improve the compression, either by choosing a better compression algorithm (e.g., zstd instead of lz4) or perhaps by using longer history in the compression instead of just single packets as we do now.

This is where we are at. I wouldn't close this issue - but refer to an OSS issue for the above. There are 2 different ideas that need to be looked at:
1. Different compressor (zstd vs. lz4)
2. Stream compression - not per packet.

**Comment by nyh** [comment] 2023-07-03 12:37
@mykaul opened https://github.com/scylladb/scylladb/issues/14491.
I think this issue should be closed **unless** internode_compression is _really_ broken, i.e., doesn't work at all. I don't think we have evidence that this is the case, and IIRC @michoecho checked and verified it isn't broken - it's just lousy at compression.

**Comment by mykaul** [comment] 2023-07-03 13:07
@Laboltus - I'm closing this. I was disappointed to see how bad LZ4 compression really did, but apparently, it's doing its job. :-/

**Closed by mykaul** 2023-07-03 13:07 UTC
Labels: OSS Release/Triage, P1

**Comment by gleb-cloudius** [comment] 2023-07-03 13:09
> @Laboltus - I'm closing this. I was disappointed to see how bad LZ4 compression really did, but apparently, it's doing its job. :-/

We still did not get tcpdump from @Laboltus to confirm that this is what he sees.

**Comment by nyh** [comment] 2023-07-03 13:31
> We still did not get tcpdump from @Laboltus to confirm that this is what he sees.

Right. In another thread, @michoecho checked similar "allegations" and proved conclusively that the LZ4 compression was working - badly, and leaving a lot of uncompressed chunks of plaintext - but it was working. If @Laboltus has more evidence that LZ4 is completely not working - not just bad - we should definitely reopen this issue.

**Comment by Laboltus** [comment] 2023-07-03 15:04
> @Laboltus said "Yes, I see whole record's content.". Are you sure about this? Can you please make extra sure that you don't see "a lot" of it, but not the entire uncompressed content?
> 

I've re-checked and yes, looks like some parts are encoded.

**Comment by mykaul** [comment] 2023-07-03 15:06
> > @Laboltus said "Yes, I see whole record's content.". Are you sure about this? Can you please make extra sure that you don't see "a lot" of it, but not the entire uncompressed content?
> 
> I've re-checked and yes, looks like some parts are encoded.

Thanks. One thing you could do is look at the first 8 bytes of a packet. first 4 (32 bit) should be the length of the following (compressed), then the next 4 should be (ignore the 0x80 - it's a flag) be the uncompressed size - which hopefully is larger than the former length.

**Comment by Laboltus** [comment] 2023-07-03 17:59
Should I see an LZ4 magic number in the data (0x184D2204)? In fact I see something like this:
```
15:30:25.854067 IP x.x.x.x.57692 > y.y.y.y.7000: Flags [.], seq 86901923:86903383, ack 1980869497, win 83, length 1460
	0x0000:  4500 05dc 93f3 4000 4006 846e c0a8 4dd5  E.....@.@..n..M.
	0x0010:  c0a8 4d94 e15c 1b58 052e 04a3 7611 ab79  ..M..\.X....v..y
	0x0020:  5010 0053 2289 0000 65ba 0110 616c 676f  P..S"...e...algo
	0x0030:  b500 f104 3a76 31ba 011e 6372 6561 7469  ....:v1...creati
	0x0040:  7665 2d73 656c 6591 00df 3a73 696e 676c  ve-sele...:singl
	0x0050:  652d 6974 656d eaf0 0003 1dea f000 1fea  e-item..
```

and I can't find the magic number or pattern you described.

**Comment by raphaelsc** [comment] 2023-07-03 18:05
> Should I see an LZ4 magic number in the data (0x184D2204)? In fact I see something like this:
> 
> ```
> 15:30:25.854067 IP x.x.x.x.57692 > y.y.y.y.7000: Flags [.], seq 86901923:86903383, ack 1980869497, win 83, length 1460
> 	0x0000:  4500 05dc 93f3 4000 4006 846e c0a8 4dd5  E.....@.@..n..M.
> 	0x0010:  c0a8 4d94 e15c 1b58 052e 04a3 7611 ab79  ..M..\.X....v..y
> 	0x0020:  5010 0053 2289 0000 65ba 0110 616c 676f  P..S"...e...algo
> 	0x0030:  b500 f104 3a76 31ba 011e 6372 6561 7469  ....:v1...creati
> 	0x0040:  7665 2d73 656c 6591 00df 3a73 696e 676c  ve-sele...:singl
> 	0x0050:  652d 6974 656d eaf0 0003 1dea f000 1fea  e-item..
> ```
> 
> and I can't find the magic number or pattern you described.

No, the magic number is not prepended to the frames. The same applies to SSTables compressed by lz4. For RPC, frames are implicitly compressed by lz4 if internode compression is enabled. For SSTables, that's described in schema. Note this can change in the future if we support multiple compression algorithms.

**Comment by nyh** [comment] 2023-07-03 20:10
> No, the magic number is not prepended to the frames. The same applies to SSTables compressed by lz4. For RPC, frames are implicitly compressed by lz4 if internode compression is enabled. For SSTables, that's described in schema. Note this can change in the future if we support multiple compression algorithms.

I hope that if we do begin to support multiple compression algorithms, we still won't send compression options again and again in every frame. We could negotiate a compression algorithm available on both sides, and then use it for all frames of this connection.

Or maybe - we don't even need to negotiate a compression algorithm for each connection: We can choose **one** internode compression algorithm for the **entire cluster**, based on the existing "cluster feature" negotiation protocol. Then all the nodes will know to use this algorithm for all internode communication. However, I'm not sure about the details on how this can work - how will the switchover happen when a cluster is upgraded to a new version with a new compression algorithm? Will we be stuck on the old algorithm until the entire cluster is shut down and restarted?

**Comment by gleb-cloudius** [comment] 2023-07-04 07:45
> > No, the magic number is not prepended to the frames. The same applies to SSTables compressed by lz4. For RPC, frames are implicitly compressed by lz4 if internode compression is enabled. For SSTables, that's described in schema. Note this can change in the future if we support multiple compression algorithms.
> 
> I hope that if we do begin to support multiple compression algorithms, we still won't send compression options again and again in every frame. We could negotiate a compression algorithm available on both sides, and then use it for all frames of this connection.

We already support two compression types (both LZ4 but encode frames differently). The algo is negotiated per connection.

**Comment by nyh** [comment] 2023-07-04 09:27
Thanks @gleb-cloudius, that's excellent. So we're well prepared to add a "third" (really second) compression algorithm.
