### ISSUE TITLE
Scylla really slow when using Golang client?

### ISSUE THREAD

**Issue by dancb10** [scylladb/scylladb#12688] opened 2023-01-31 21:01 UTC
I've been playing a bit with Scylla on a laptop but what I've seen is that if I execute a query on the cluster directly with cql shell the insert operation is fast:
```
cqlsh:messages> INSERT INTO messages.messages (mid,gid,created_at,cid,uid,message,attachments) VALUES (445716222470828594, 437407911753331250, 1675197176, 437407628419707442, 'wQ5v9Q2rA9VwOmaJozw3mAXjV1J3', 'Test message 03', []) ;

Tracing session: 2a3980f0-a1a9-11ed-8ece-5b81ec3d4253

 activity                                                                                             | timestamp                  | source       | source_elapsed | client
------------------------------------------------------------------------------------------------------+----------------------------+--------------+----------------+------------
                                                                                   Execute CQL3 query | 2023-01-31 20:52:24.837000 | 10.108.44.56 |              0 | 10.1.1.207
                                                                        Parsing a statement [shard 0] | 2023-01-31 20:52:24.837308 | 10.108.44.56 |             58 | 10.1.1.207
                                                                     Processing a statement [shard 0] | 2023-01-31 20:52:24.838000 | 10.108.44.56 |            750 | 10.1.1.207
 Creating write handler for token: -5254081436449826099 natural: {10.108.44.56} pending: {} [shard 0] | 2023-01-31 20:52:24.838834 | 10.108.44.56 |           1583 | 10.1.1.207
                                  Creating write handler with live: {10.108.44.56} dead: {} [shard 0] | 2023-01-31 20:52:24.838844 | 10.108.44.56 |           1593 | 10.1.1.207
                                                               Executing a mutation locally [shard 0] | 2023-01-31 20:52:24.838880 | 10.108.44.56 |           1629 | 10.1.1.207
                                                          Got a response from /10.108.44.56 [shard 0] | 2023-01-31 20:52:24.839474 | 10.108.44.56 |           2224 | 10.1.1.207
                               Delay decision due to throttling: do not delay, resuming now [shard 0] | 2023-01-31 20:52:24.839477 | 10.108.44.56 |           2226 | 10.1.1.207
                                                            Mutation successfully completed [shard 0] | 2023-01-31 20:52:24.839519 | 10.108.44.56 |           2268 | 10.1.1.207
                                                       Done processing - preparing a result [shard 0] | 2023-01-31 20:52:24.839581 | 10.108.44.56 |           2331 | 10.1.1.207
                                                                                     Request complete | 2023-01-31 20:52:24.839337 | 10.108.44.56 |           2337 | 10.1.1.207
```

But when I use the Golang client on the same cluster it takes more than 5-10 seconds to execute a simple insert:
```
retryPolicy := &gocql.ExponentialBackoffRetryPolicy{
Min:        time.Second,
Max:        10 * time.Second,
NumRetries: 5,
}
cluster := gocql.NewCluster(host1)
cluster.Keyspace = "messages"
cluster.Timeout = 5 * time.Second
cluster.RetryPolicy = retryPolicy
cluster.Consistency = gocql.One


// SLOW PART START
session, err := gocqlx.WrapSession(cluster.CreateSession())
if err != nil {
	c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
	return
}
// SLOW END

var replaysMetadata = table.Metadata{
	Name:    "replays",
	Columns: []string{"mrid", "smid", "created_at", "attachments", "cid", "gid", "message", "uid"},
	PartKey: []string{"mrid"},
	SortKey: []string{"created_at"},
}
var replaysTable = table.New(replaysMetadata)

q := session.Query(messagesTable.Insert()).BindStruct(finalMessage)
if err := q.ExecRelease(); err != nil {
	c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
	return
}
```
I'm running the setup on a local K8s cluster with a three nodes using the Scylla operator. It's weird that if I use the cql sh cli the insert is really fast but when using the above code it's really slow. Do you know what could it make it so slow? Does it take that long to initialize a session with? `session, err := gocqlx.WrapSession(cluster.CreateSession())`

**Comment by mykaul** [comment] 2023-02-01 08:06
@avelanarius - thoughts?

**Comment by nyh** [comment] 2023-02-01 09:07
@mykaul should we even have a "gocql-driver" tag in the main Scylla repository? Don't such issues belong in the gocql driver repository - I guess https://github.com/scylladb/gocqlx - and not here?

There is indeed no reason why making a connection to Scylla should take 5 seconds. It isn't Scylla slowness but something else, which will probably need to be debugged by people familiar with the driver, not Scylla, and what it tries to wait for when making a connection.

**Comment by mykaul** [comment] 2023-02-01 09:52
> @mykaul should we even have a "gocql-driver" tag in the main Scylla repository? Don't such issues belong in the gocql driver repository - I guess https://github.com/scylladb/gocqlx - and not here?

We probably shouldn't (I did not add it). The reason I keep it here:
1. Apparently, easier for users.
2. Until we 'prove' it's a driver issue, I prefer we keep it here and tag it somehow (we could use 'drivers' perhaps as a more general tag?)
As soon as we agree it's a driver-side issue (this is probably is, or env. issue on the driver side - DNS?), I'll transfer the issue. It's temporarily here.

> 
> There is indeed no reason why making a connection to Scylla should take 5 seconds. It isn't Scylla slowness but something else, which will probably need to be debugged by people familiar with the driver, not Scylla, and what it tries to wait for when making a connection.

Agreed.

**Comment by avikivity** [comment] 2023-02-01 13:35
Setting up a connection is slow, it involves many connections to all nodes, and many queries for system tables. It shouldn't take 5 seconds, but it should never be in the data path of your application either. Connect once during startup and run many queries over established sessions.

If you want to investigate it further, take a packet capture of port 9042.

**Comment by nyh** [comment] 2023-02-01 13:41
By the way, when you showed above a cqlsh command finished quickly, that wasn't the right comparison to the "slow part" you mentioned in the golang code. The slow part corresponds to cqlsh **starting**. How long does it take for cqlsh to start and run the first command? Is it also close to 5 seconds or much less?

**Comment by Lorak-mmk** [comment] 2023-02-03 11:40
> By the way, when you showed above a cqlsh command finished quickly, that wasn't the right comparison to the "slow part" you mentioned in the golang code. The slow part corresponds to cqlsh **starting**. How long does it take for cqlsh to start and run the first command? Is it also close to 5 seconds or much less?

This also wouldn't be a fair comparison - iiuc cqlsh connects to just one node: https://github.com/scylladb/scylla-tools-java/blob/1c4e1e7a7df633d1d57e07f762e181e6a14f88af/bin/cqlsh.py#L487-L491 (`WhiteListRoundRobinPolicy` prevents creating connections to other nodes: https://github.com/scylladb/python-driver/blob/9c50105aa38e14f9ba8a5ee7600875ea1ae15112/cassandra/policies.py#L413-L417 ).

**Comment by Gor027** [comment] 2023-03-04 00:32
I have tried reproducing the issue with the insert example and a simple [docker-compose](https://gist.github.com/Gor027/63aa22274a19e4daf8c6d5ccf9065efd) that creates a 3-node cluster with each node having 3 shards. The session object creation and the insert statement execution were done instantly without any delays. Perhaps the K8s cluster setup was the reason for the 5-10 seconds delay, although it is suspicious.

**Comment by Lorak-mmk** [comment] 2024-07-01 09:07
Can we close this? As was mentioned before, there is most likely no bug here, just benchmarking wrong things (session creation vs request execution), and the author is not responding.

**Comment by nyh** [comment] 2024-07-01 09:23
@Lorak-mmk I agree. @dancb10 if you have more information, or feel this is still a bug, feel free to reopen the issue (with an explanation please).

**Closed by nyh** 2024-07-01 09:23 UTC
Labels: area/drivers
