### ISSUE TITLE
[dtest] test_no_read_amplification_on_repair_with_mv: cassandra.WriteFailure: Error from server: code=1500 [Replica(s) failed to execute write] message="Operation failed for ks.cf - received 0 responses and 1 failures from 2 CL=QUORUM."

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18001] opened 2024-03-25 12:53 UTC
Failing since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/526/testReport/read_amplification_test/TestReadAmplification/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split011___test_no_read_amplification_on_repair_with_mv/
Scylla version 5.5.0~dev-0.20240321.900b56b117a1

https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/526/artifact/logs-full.release.011/dtest-gw0.log
```
23:24:39,581 976     conftest                       INFO     conftest.py         :229  | test_no_read_amplification_on_repair_with_mv: Starting execution of test_no_read_amplification_on_repair_with_mv at 2024-03-21 23:24:39.581193
23:24:39,581 976     dtest_setup                    INFO     dtest_setup.py      :858  | test_no_read_amplification_on_repair_with_mv: cluster ccm directory: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1
23:24:39,581 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: ScyllaCluster: cassandra_version=900b56b117a12550bebe5dc381f01739e72457df docker_image=None install_dir=None scylla_mode=None default_wait_other_notice_timeout=120 default_wait_for_binary_proto=420
23:24:39,582 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: ScyllaCluster: load_from_repository: install_dir=/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/900b56b117a12550bebe5dc381f01739e72457df scylla_mode=release default_wait_other_notice_timeout=120 default_wait_for_binary_proto=420
23:24:39,585 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: Started cluster 'test' version 5.5.0-dev installed in /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/900b56b117a12550bebe5dc381f01739e72457df
23:24:39,585 976     dtest_setup                    DEBUG    dtest_setup.py      :763  | test_no_read_amplification_on_repair_with_mv: Scylla mode is 'release'
23:24:39,585 976     dtest_setup                    DEBUG    dtest_setup.py      :764  | test_no_read_amplification_on_repair_with_mv: Cluster *_request_timeout_in_ms=10000, range_request_timeout_in_ms=30000, cql request_timeout=30
23:24:39,593 976     dtest_setup                    DEBUG    dtest_setup.py      :831  | test_no_read_amplification_on_repair_with_mv: Done setting configuration options:
{   'cas_contention_timeout_in_ms': 10000,
    'counter_write_request_timeout_in_ms': 20000,
    'initial_token': None,
    'num_tokens': 256,
    'phi_convict_threshold': 5,
    'range_request_timeout_in_ms': 30000,
    'read_request_timeout_in_ms': 10000,
    'request_timeout_in_ms': 10000,
    'ring_delay_ms': 10000,
    'skip_wait_for_gossip_to_settle': 0,
    'task_ttl_in_seconds': 0,
    'truncate_request_timeout_in_ms': 30000,
    'write_request_timeout_in_ms': 10000}
23:24:39,598 976     dtest_setup                    DEBUG    dtest_setup.py      :61   | test_no_read_amplification_on_repair_with_mv: Allocated cluster ID 13: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1
23:24:39,614 976     read_amplification_test        INFO     read_amplification_test.py:61   | test_no_read_amplification_on_repair_with_mv: Starting cluster..
23:24:39,817 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: start_nodes: no_wait=False wait_for_binary_proto=True wait_other_notice=True wait_normal_token_owner=True force_wait_for_cluster_start=True
23:24:39,821 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: node1: Starting scylla: args=['/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node1/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node1/conf/scylla.yaml', '--log-to-stdout', '1', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--api-address', '127.0.13.1', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--overprovisioned', '--prometheus-address', '127.0.13.1', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=True wait_for_binary_proto=True
23:24:40,188 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: node1: Starting scylla-jmx: args=['/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node1/bin/symlinks/scylla-jmx', '-Dapiaddress=127.0.13.1', '-Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder', '-Djava.rmi.server.hostname=127.0.13.1', '-Dcom.sun.management.jmxremote', '-Dcom.sun.management.jmxremote.host=127.0.13.1', '-Dcom.sun.management.jmxremote.port=7199', '-Dcom.sun.management.jmxremote.rmi.port=7199', '-Dcom.sun.management.jmxremote.local.only=false', '-Xmx256m', '-XX:+UseSerialGC', '-Dcom.sun.management.jmxremote.authenticate=false', '-Dcom.sun.management.jmxremote.ssl=false', '-jar', '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node1/bin/scylla-jmx-1.0.jar']
23:24:40,652 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: node2: Starting scylla: args=['/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node2/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node2/conf/scylla.yaml', '--log-to-stdout', '1', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--api-address', '127.0.13.2', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--overprovisioned', '--prometheus-address', '127.0.13.2', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=True wait_for_binary_proto=True
23:24:46,155 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: node2: Starting scylla-jmx: args=['/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node2/bin/symlinks/scylla-jmx', '-Dapiaddress=127.0.13.2', '-Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder', '-Djava.rmi.server.hostname=127.0.13.2', '-Dcom.sun.management.jmxremote', '-Dcom.sun.management.jmxremote.host=127.0.13.2', '-Dcom.sun.management.jmxremote.port=7199', '-Dcom.sun.management.jmxremote.rmi.port=7199', '-Dcom.sun.management.jmxremote.local.only=false', '-Xmx256m', '-XX:+UseSerialGC', '-Dcom.sun.management.jmxremote.authenticate=false', '-Dcom.sun.management.jmxremote.ssl=false', '-jar', '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node2/bin/scylla-jmx-1.0.jar']
23:24:46,566 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: node3: Starting scylla: args=['/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node3/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node3/conf/scylla.yaml', '--log-to-stdout', '1', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--api-address', '127.0.13.3', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--overprovisioned', '--prometheus-address', '127.0.13.3', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=True wait_for_binary_proto=True
23:24:54,190 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: node3: Starting scylla-jmx: args=['/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node3/bin/symlinks/scylla-jmx', '-Dapiaddress=127.0.13.3', '-Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder', '-Djava.rmi.server.hostname=127.0.13.3', '-Dcom.sun.management.jmxremote', '-Dcom.sun.management.jmxremote.host=127.0.13.3', '-Dcom.sun.management.jmxremote.port=7199', '-Dcom.sun.management.jmxremote.rmi.port=7199', '-Dcom.sun.management.jmxremote.local.only=false', '-Xmx256m', '-XX:+UseSerialGC', '-Dcom.sun.management.jmxremote.authenticate=false', '-Dcom.sun.management.jmxremote.ssl=false', '-jar', '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node3/bin/scylla-jmx-1.0.jar']
23:24:54,651 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: node4: Starting scylla: args=['/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node4/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node4/conf/scylla.yaml', '--log-to-stdout', '1', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--api-address', '127.0.13.4', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--overprovisioned', '--prometheus-address', '127.0.13.4', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=True wait_for_binary_proto=True
23:25:03,025 976     ccm                            DEBUG    cluster.py          :762  | test_no_read_amplification_on_repair_with_mv: node4: Starting scylla-jmx: args=['/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node4/bin/symlinks/scylla-jmx', '-Dapiaddress=127.0.13.4', '-Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder', '-Djava.rmi.server.hostname=127.0.13.4', '-Dcom.sun.management.jmxremote', '-Dcom.sun.management.jmxremote.host=127.0.13.4', '-Dcom.sun.management.jmxremote.port=7199', '-Dcom.sun.management.jmxremote.rmi.port=7199', '-Dcom.sun.management.jmxremote.local.only=false', '-Xmx256m', '-XX:+UseSerialGC', '-Dcom.sun.management.jmxremote.authenticate=false', '-Dcom.sun.management.jmxremote.ssl=false', '-jar', '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1/test/node4/bin/scylla-jmx-1.0.jar']
23:25:03,558 976     cassandra.policies             INFO     policies.py         :289  | test_no_read_amplification_on_repair_with_mv: Using datacenter 'datacenter1' for DCAwareRoundRobinPolicy (via host '127.0.13.1:9042'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
23:25:03,558 976     cassandra.cluster              INFO     dtest_setup.py      :496  | test_no_read_amplification_on_repair_with_mv: New Cassandra host <Host: 127.0.13.3:9042 datacenter1> discovered
23:25:03,558 976     cassandra.cluster              INFO     dtest_setup.py      :496  | test_no_read_amplification_on_repair_with_mv: New Cassandra host <Host: 127.0.13.4:9042 datacenter1> discovered
23:25:03,558 976     cassandra.cluster              INFO     dtest_setup.py      :496  | test_no_read_amplification_on_repair_with_mv: New Cassandra host <Host: 127.0.13.2:9042 datacenter1> discovered
23:25:03,607 976     cassandra.protocol             WARNING  libevreactor.py     :361  | test_no_read_amplification_on_repair_with_mv: Server warning: SimpleStrategy replication class is not recommended, but was used for keyspace ks. You may suppress this warning by delisting SimpleStrategy from replication_strategy_warn_list configuration option, or make it into an error by listing this replication strategy on replication_strategy_fail_list.
23:25:05,035 976     read_amplification_test        INFO     read_amplification_test.py:70   | test_no_read_amplification_on_repair_with_mv: CREATE MATERIALIZED VIEW ks.cf_mv AS SELECT * FROM ks.cf WHERE key is not null and c1 is not null PRIMARY KEY (c1, key)
23:25:08,038 976     read_amplification_test        INFO     read_amplification_test.py:80   | test_no_read_amplification_on_repair_with_mv: Stop node2
23:25:08,040 976     cassandra.cluster              WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Host 127.0.13.2:9042 has been marked down
23:25:09,042 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:11,040 976     read_amplification_test        INFO     read_amplification_test.py:89   | test_no_read_amplification_on_repair_with_mv: Insert data
23:25:11,048 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:15,231 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:19,276 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.6 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:22,933 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.8 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:26,810 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:30,898 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.88 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:34,879 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:38,957 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.8 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:42,788 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.52 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:46,395 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.96 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:51,606 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:55,616 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.72 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:25:59,422 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.84 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:03,329 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:07,336 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:11,341 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.76 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:15,146 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:19,152 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:23,157 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.8 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:26,963 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:30,969 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:34,974 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.4 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:38,379 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:42,384 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:46,389 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.84 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:50,295 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:54,301 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:26:58,306 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 3.52 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:27:01,911 976     cassandra.pool                 WARNING  thread.py           :58   | test_no_read_amplification_on_repair_with_mv: Error attempting to reconnect to 127.0.13.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.2', 9042)]. Last error: Connection refused
23:27:05,884 976     errors                         ERROR    conftest.py         :201  | test_no_read_amplification_on_repair_with_mv: test failed: 
self = <read_amplification_test.TestReadAmplification object at 0x7f161d6a6410>

    @unmark.next_gating  # tests are too heavy, and verifying wrong metrics for RBNO - https://github.com/scylladb/scylla-dtest/issues/3573
    def test_no_read_amplification_on_repair_with_mv(self):
        """
        Check total bytes read during streaming on repair corresponds to data size
        """
>       self.no_read_amplification_on_repair(with_mv=True)

read_amplification_test.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
read_amplification_test.py:90: in no_read_amplification_on_repair
    insert_c1c2(session, keys=range(1, cnt + 1), consistency=ConsistencyLevel.QUORUM, c1_values=cs_value, c2_values=cs_value)
tools/data.py:45: in insert_c1c2
    execute_concurrent_with_args(session, statement, map(lambda x, y, z: [f"k{x}", y, z], keys, c1_values, c2_values))
cassandra/concurrent.py:238: in cassandra.concurrent.execute_concurrent_with_args
    ???
cassandra/concurrent.py:94: in cassandra.concurrent.execute_concurrent
    ???
cassandra/concurrent.py:201: in cassandra.concurrent.ConcurrentExecutorListResults.execute
    ???
cassandra/concurrent.py:120: in cassandra.concurrent._ConcurrentExecutor.execute
    ???
cassandra/concurrent.py:215: in cassandra.concurrent.ConcurrentExecutorListResults._results
    ???
cassandra/concurrent.py:219: in cassandra.concurrent.ConcurrentExecutorListResults._results
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.WriteFailure: Error from server: code=1500 [Replica(s) failed to execute write] message="Operation failed for ks.cf - received 0 responses and 1 failures from 2 CL=QUORUM." info={'consistency': 'QUORUM', 'required_responses': 2, 'received_responses': 0, 'failures': 1}

cassandra/concurrent.py:167: WriteFailure
23:27:05,884 976     errors                         ERROR    conftest.py         :201  | test_no_read_amplification_on_repair_with_mv: test failed: 
self = <read_amplification_test.TestReadAmplification object at 0x7f161d6a6410>

    @unmark.next_gating  # tests are too heavy, and verifying wrong metrics for RBNO - https://github.com/scylladb/scylla-dtest/issues/3573
    def test_no_read_amplification_on_repair_with_mv(self):
        """
        Check total bytes read during streaming on repair corresponds to data size
        """
>       self.no_read_amplification_on_repair(with_mv=True)

read_amplification_test.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
read_amplification_test.py:90: in no_read_amplification_on_repair
    insert_c1c2(session, keys=range(1, cnt + 1), consistency=ConsistencyLevel.QUORUM, c1_values=cs_value, c2_values=cs_value)
tools/data.py:45: in insert_c1c2
    execute_concurrent_with_args(session, statement, map(lambda x, y, z: [f"k{x}", y, z], keys, c1_values, c2_values))
cassandra/concurrent.py:238: in cassandra.concurrent.execute_concurrent_with_args
    ???
cassandra/concurrent.py:94: in cassandra.concurrent.execute_concurrent
    ???
cassandra/concurrent.py:201: in cassandra.concurrent.ConcurrentExecutorListResults.execute
    ???
cassandra/concurrent.py:120: in cassandra.concurrent._ConcurrentExecutor.execute
    ???
cassandra/concurrent.py:215: in cassandra.concurrent.ConcurrentExecutorListResults._results
    ???
cassandra/concurrent.py:219: in cassandra.concurrent.ConcurrentExecutorListResults._results
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.WriteFailure: Error from server: code=1500 [Replica(s) failed to execute write] message="Operation failed for ks.cf - received 0 responses and 1 failures from 2 CL=QUORUM." info={'consistency': 'QUORUM', 'required_responses': 2, 'received_responses': 0, 'failures': 1}

cassandra/concurrent.py:167: WriteFailure
23:27:09,959 976     dtest_setup                    DEBUG    dtest_setup.py      :714  | test_no_read_amplification_on_repair_with_mv: removing ccm cluster test at: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1
23:27:10,169 976     dtest_setup                    DEBUG    dtest_setup.py      :717  | test_no_read_amplification_on_repair_with_mv: clearing ssl stores from [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-s33t9ar1] directory
23:27:10,169 976     dtest_setup                    DEBUG    dtest_setup.py      :85   | test_no_read_amplification_on_repair_with_mv: Freeing cluster ID 13: link /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/13
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/526/testReport/read_amplification_test/TestReadAmplification/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split011___test_no_read_amplification_on_repair_with_mv_2/
```
failed on teardown with "AssertionError: Unexpected errors found: [('node4', ['ERROR 2024-03-21 23:27:04,843 [shard 0:stmt] storage_proxy - exception during mutation write to 127.0.13.4: exceptions::overloaded_exception (Too many view updates started concurrently)'
...
```

**Comment by bhalevy** [comment] 2024-04-14 05:54
> @nyh can you please look into this issue?

ping @nyh

**Comment by nyh** [comment] 2024-04-14 09:48
This "Too many view updates started concurrently" thing is a new check added just last month by @wmitros in 59d5bfa742b. I have no idea what this test is doing or why this new check is failing with it, so either I or he will need to check this. It's important to understand because it might be a regression that that commit introduced.

**Comment by wmitros** [comment] 2024-04-15 10:07
This seems to be the same issue as https://github.com/scylladb/scylla-dtest/issues/4115 (which I duplicated after not seeing this one). That issue had more discussion already and a fix is pending, so I think we can close this one

**Closed by wmitros** 2024-04-15 10:07 UTC
Labels: status/regression, triage/master
