### ISSUE TITLE
scylla perf-simple-query shows 0 instructions_per_op on ARM platform

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#19227] opened 2024-06-11 08:46 UTC
Version: 6.1.0~dev
Build Date: 20240608 , Commit Id: f4706be8a8c4
test id: dd04ad9e-f1ad-45f0-877b-316752774cf5

In weekly perf test `instructions_per_op` result is 0 on ARM platform (x86 works).
See also `logallocs_per_op` shows `0` (but this happens in every test and never worked, possibly different issue).
```
Command "scylla perf-simple-query --json-result=perf-simple-query-result.txt --smp 1 -m 1G" finished with status 0
Running command "cat perf-simple-query-result.txt"...
{
	"parameters" : 
	{
		"concurrency" : 100,
		"concurrency,partitions,cpus,duration" : "100,10000,1,5",
		"cpus" : 1,
		"duration" : 5,
		"partitions" : 10000
	},
	"stats" : 
	{
		"allocs_per_op" : 63.068162025531556,
		"instructions_per_op" : 0.0,
		"logallocs_per_op" : 0.0,
		"mad tps" : 177.14822965944768,
		"max tps" : 94535.561971533942,
		"median tps" : 94145.963438574385,
		"min tps" : 93397.596656440772,
		"tasks_per_op" : 14.123462690371504
	},
	"test_properties" : 
	{
		"type" : "read"
	},
	"versions" : 
	{
		"scylla-server" : 
		{
			"commit_id" : "f4706be8a8c4",
			"date" : "20240608",
			"run_date_time" : "2024-06-09 06:14:38",
			"version" : "6.1.0~dev"
		}
	}
}

```
Links:
[Build URL](https://jenkins.scylladb.com/job/simple_query_weekly_microbenchmark/83/)
Logs:
[db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/dd04ad9e-f1ad-45f0-877b-316752774cf5/20240609_061703/db-cluster-dd04ad9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dd04ad9e-f1ad-45f0-877b-316752774cf5/20240609_061703/db-cluster-dd04ad9e.tar.gz)
[sct - https://cloudius-jenkins-test.s3.amazonaws.com/dd04ad9e-f1ad-45f0-877b-316752774cf5/20240609_061703/sct-runner-dd04ad9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dd04ad9e-f1ad-45f0-877b-316752774cf5/20240609_061703/sct-runner-dd04ad9e.tar.gz)

**Comment by michoecho** [comment] 2024-06-11 13:03
> See also logallocs_per_op shows 0 (but this happens in every test and never worked, possibly different issue).
>
> never worked

The test is performing reads from cache. It's not creating any new objects in LSA. So it's supposed to be 0.

> What instance type are you using?

They are using c7g.large. I think it's supposed to work.

Perhaps the process needs some additional privileges to access the PMU on that platform?

**Comment by soyacz** [comment] 2024-06-11 13:56
See that it works on scylla enterprise and worked a week before.

**Comment by avikivity** [comment] 2024-06-11 13:59
Maybe the AMI changed? It could have changed the defaults.

Alternatively, someone figured out how to steal your credentials if [some very unlikely scenario] using the PMU, so they disabled it.

**Comment by avikivity** [comment] 2024-06-13 11:17
Also, what scylla AMI did the test fail with?

**Comment by soyacz** [comment] 2024-06-13 11:29
I don't know if the base AMI changed and I don't know how to check it. @yaronkaikov can you help with that?
Besides, scylla ami test was running on: ami-0f8e2dbd725f06d01 (eu-west-1)

**Comment by michoecho** [comment] 2024-06-13 12:53
Old:
```
perf_event_open({type=PERF_TYPE_HARDWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_HW_INSTRUCTIONS, sample_period=0, sample_type=0, read_format=0, disabled=1, exclude_kernel=1, exclude_hv=1, exclude_idle=1, precise_ip=0 /* arbitrary skid */, ...}, 0, -1, -1, 0) = -1 EOPNOTSUPP (Operation not supported)
```

New:
```
55665.26 tps ( 63.2 allocs/op,   0.0 logallocs/op,  14.3 tasks/op,   50340 insns/op,        0 errors)
perf_event_open({type=PERF_TYPE_HARDWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_HW_INSTRUCTIONS, sample_period=0, sample_type=0, read_format=0, disabled=1, exclude_kernel=1, exclude_hv=1, precise_ip=0 /* arbitrary skid */, ...}, 0, -1, -1, 0) = 11
```

So apperently the cause is https://github.com/scylladb/seastar/commit/93f19d39526c68defac6860a15c77160da273606, because the platform doesn't support `exclude_idle`. cc @bhalevy

I see in kernel sources that this is true for ARM in general:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/arm64/kernel/perf_event.c?h=linux-5.15.y#n915.
(The EPERM is translated to EOPNOTSUPP by the caller).



I guess we can just `ifdef` it away for ARM.

**Comment by bhalevy** [comment] 2024-06-13 19:56
> Old vs new:
> 
> ```diff
> -perf_event_open({type=PERF_TYPE_HARDWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_HW_INSTRUCTIONS, sample_period=0, sample_type=0, read_format=0, disabled=1, exclude_kernel=1, exclude_hv=1, exclude_idle=1, precise_ip=0 /* arbitrary skid */, ...}, 0, -1, -1, 0) = -1 EOPNOTSUPP (Operation not supported)
> +perf_event_open({type=PERF_TYPE_HARDWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_HW_INSTRUCTIONS, sample_period=0, sample_type=0, read_format=0, disabled=1, exclude_kernel=1, exclude_hv=1, precise_ip=0 /* arbitrary skid */, ...}, 0, -1, -1, 0) = 11
> ```
> 
> So apperently the cause is [scylladb/seastar@93f19d3](https://github.com/scylladb/seastar/commit/93f19d39526c68defac6860a15c77160da273606), because the platform doesn't support `exclude_idle`. cc @bhalevy

Shame on them

> 
> I see in kernel sources that this is true for ARM in general: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/arm64/kernel/perf_event.c?h=linux-5.15.y#n915. (The EPERM is translated to EOPNOTSUPP by the caller).
> 
> I guess we can just `ifdef` it away for ARM.

yes

it would help if it weren't compile rather than doing the wrong thing at runtime... sigh

**Comment by mykaul** [comment] 2024-07-16 12:43
@bhalevy - can this be closed now?

**Comment by bhalevy** [comment] 2024-07-16 21:16
> @bhalevy - can this be closed now?

Only after the seastar submodule is updated to a version containing https://github.com/scylladb/seastar/commit/7c53043b046c1fd25ca7c9cbcbb1f8f1d145eacd

**Comment by bhalevy** [comment] 2024-07-18 15:35
> > @bhalevy - can this be closed now?
> 
> Only after the seastar submodule is updated to a version containing [scylladb/seastar@7c53043](https://github.com/scylladb/seastar/commit/7c53043b046c1fd25ca7c9cbcbb1f8f1d145eacd)

https://github.com/scylladb/scylladb/pull/19794

**Comment by bhalevy** [comment] 2024-07-21 07:56
Closing with 4fbfecbb3eb140f73aafd7a89ae0ca5115c6c730

Please reopen if needed.

**Closed by bhalevy** 2024-07-21 07:56 UTC
Labels: symptom/performance, platform/arm
