### ISSUE TITLE
No schema agreement after creating sequentially multiple keyspaces

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#19573] opened 2024-07-01 10:30 UTC
## Packages

Scylla version: `6.1.0~dev-20240625.c80dc5715668` with build-id `bf0032dbaafe5e4d3e01ece0dcb7785d2ec7a098`

Kernel Version: `5.15.0-1063-aws`

## Issue description

- [ ] This issue is a regression.
- [X] It is unknown if this issue is a regression.

`disrupt_no_corrupt_repair` nemesis at start prepopulates 10 keyspaces like `drop_table_during_repair_ks_{i}` sequentially with cassandra-stress tool (writing 400k rows). After each c-s run it waits for schema agreement with `check_schema_agreement_in_gossip_and_peers` run on all db nodes - always passing.
After creating successfully without problems 8 keyspaces, it failed command:
```
< t:2024-06-29 08:36:41,163 f:stress_thread.py l:334  c:sdcm.stress_thread   p:INFO  > cassandra-stress write no-warmup n=400000 cl=QUORUM -mode native cql3  user=cassandra password=cassandra -schema keyspace=drop_table_during_repair_ks_8 'replication(strategy=NetworkTopologyStrategy,replication_factor=6)' -log interval=5 -transport 'truststore=/etc/scylla/ssl_conf/truststore.jks truststore-password=cassandra' -node 10.4.21.83,10.4.23.195,10.4.22.222,10.4.22.193,10.4.22.96,10.4.22.189 -errors skip-unsupported-columns
```
with error:
```
WARN  08:36:55,244 Query '[0 bound values] CREATE KEYSPACE IF NOT EXISTS "drop_table_during_repair_ks_8" WITH replication = {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'replication_factor' : '6'} AND durable_writes = true;' generated server side warning(s): Tables in this keyspace will be replicated using tablets, and will not support the CDC feature (issue #16317) and LWT may suffer from issue #5251 more often. If you want to use CDC or LWT, please drop this keyspace and re-create it without tablets, by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.
WARN  08:37:05,310 No schema agreement from live replicas after 10 s. The schema may not be up to date on some nodes.
java.lang.RuntimeException: Encountered exception creating schema
Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.4.22.96:9042] Timed out waiting for server response
Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.4.22.96:9042] Timed out waiting for server response
```
Looking into that node (ip 10.4.22.96 is node-6) from given time period, logs show:
```
Jun 29 08:36:46.164381 longevity-tls-50gb-3d-master-db-node-04447069-6 scylla[7607]:  [shard  0: gms] schema_tables - Creating keyspace drop_table_during_repair_ks_8
Jun 29 08:36:49.303621 longevity-tls-50gb-3d-master-db-node-04447069-6 scylla[7607]:  [shard 13:comp] compaction - [Compact keyspace1.standard1 ba23a270-35f2-11ef-b700-55619ab55b24] Compacting [/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nxb_0z5fk2s6ovhc1hnwv8-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nq8_1jaqo2s6ovhc1hnwv8-big-Data.db:level=0:origin=memtable]
Jun 29 08:36:56.454225 longevity-tls-50gb-3d-master-db-node-04447069-6 scylla[7607]:  [shard 13:comp] compaction - [Compact keyspace1.standard1 ba23a270-35f2-11ef-b700-55619ab55b24] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nxd_1t5og2s6ovhc1hnwv8-big-Data.db:level=0]. 144MB to 143MB (~99% of original) in 7148ms = 20MB/s. ~584064 total partitions merged to 572842.
Jun 29 08:36:59.643849 longevity-tls-50gb-3d-master-db-node-04447069-6 scylla[7607]:  [shard  4:comp] sstable - Rebuilding bloom filter /var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nkk_313gw2p3wnwq3jb1gk-big-Filter.db: resizing bitset from 7330888 bytes to 3901872 bytes.
Jun 29 08:37:03.195276 longevity-tls-50gb-3d-master-db-node-04447069-6 scylla[7607]:  [shard  4:comp] compaction - [Compact keyspace1.standard1 a77025f1-35f1-11ef-b161-55669ab55b24] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nkk_313gw2p3wnwq3jb1gk-big-Data.db:level=0]. 1GB to 789MB (~53% of original) in 474758ms = 3MB/s. ~5864704 total partitions merged to 3121490.
Jun 29 08:37:03.380631 longevity-tls-50gb-3d-master-db-node-04447069-6 scylla[7607]:  [shard  8:stmt] reader_concurrency_semaphore - (rate limiting dropped 50 similar messages) Semaphore user with 14/100 count and 250426/175447736 memory resources: timed out, dumping permit diagnostics:
                                                                                     permits        count        memory        table/operation/state
                                                                                     7        7        122K        keyspace1.standard1/data-query/active/await
                                                                                     7        7        122K        keyspace1.standard1/data-query/active/need_cpu
                                                                                     4        0        0B        mview.users/data-query/waiting_for_admission
                                                                                     73        0        0B        mview.users_by_first_name/data-query/waiting_for_admission
                                                                                     5207        0        0B        keyspace1.standard1/data-query/waiting_for_admission
                                                                                     1        0        0B        mview.users_by_first_name/mutation-query/waiting_for_admission
                                                                                     
                                                                                     5299        14        245K        total
                                                                                     
                                                                                     Stats:
                                                                                     permit_based_evictions: 0
                                                                                     time_based_evictions: 0
                                                                                     inactive_reads: 0
                                                                                     total_successful_reads: 72653384
                                                                                     total_failed_reads: 12487434
                                                                                     total_reads_shed_due_to_overload: 0
                                                                                     total_reads_killed_due_to_kill_limit: 0
                                                                                     reads_admitted: 72863412
                                                                                     reads_enqueued_for_admission: 75769432
                                                                                     reads_enqueued_for_memory: 0
                                                                                     reads_admitted_immediately: 9376685
                                                                                     reads_queued_because_ready_list: 11241889
                                                                                     reads_queued_because_need_cpu_permits: 64527543
                                                                                     reads_queued_because_memory_resources: 0
                                                                                     reads_queued_because_count_resources: 0
                                                                                     reads_queued_with_eviction: 0
                                                                                     total_permits: 92122960
                                                                                     current_permits: 5299
                                                                                     need_cpu_permits: 14
                                                                                     awaits_permits: 7
                                                                                     disk_reads: 13
                                                                                     sstables_read: 29
Jun 29 08:37:04.832932 longevity-tls-50gb-3d-master-db-node-04447069-6 scylla[7607]:  [shard 11:comp] compaction - [Compact keyspace1.standard1 b39e79c0-35f2-11ef-bd22-55609ab55b24] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nx2_26vi82vjk5iy6ul3j8-big-Data.db:level=0]. 697MB to 691MB (~99% of original) in 26462ms = 26MB/s. ~2772608 total partitions merged to 2737888.
Jun 29 08:37:04.833252 longevity-tls-50gb-3d-master-db-node-04447069-6 scylla[7607]:  [shard 11:comp] compaction - [Compact keyspace1.standard1 c3655310-35f2-11ef-bd22-55609ab55b24] Compacting [/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nx2_26vi82vjk5iy6ul3j8-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0lyb_5jjn42vjk5iy6ul3j8-big-Data.db:level=0:origin=compaction]
Jun 29 08:37:06.711541 longevity-tls-50gb-3d-master-db-node-04447069-6 scylla[7607]:  [shard 10:comp] compaction - [Compact keyspace1.standard1 c483e270-35f2-11ef-814c-555e9ab55b24] Compacting [/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nxp_28sy81ysa2xryc1j50-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nq4_2lg741ysa2xryc1j50-big-Data.db:level=0:origin=memtable]
Jun 29 08:37:20.141887 longevity-tls-50gb-3d-master-db-node-04447069-6 scylla[7607]:  [shard  0: gms] migration_manager - Gossiping my schema version b83cf8a8-35f2-11ef-1da2-74fb2d38cdd6
```
example log output from other node within that period:
```
Jun 29 08:36:46.213851 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  0: gms] schema_tables - Creating keyspace drop_table_during_repair_ks_8
Jun 29 08:36:46.251912 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  0: gms] migration_manager - Gossiping my schema version b83cf8a8-35f2-11ef-1da2-74fb2d38cdd6
Jun 29 08:36:46.252991 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  0: gms] schema_tables - Schema version changed to b83cf8a8-35f2-11ef-1da2-74fb2d38cdd6
Jun 29 08:36:52.407740 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  8:comp] compaction - [Compact keyspace1.standard1 8c6c99e0-35f2-11ef-aefb-4edc5a5082c1] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nv8_3mj2o2nsmvs9on8kw1-big-Data.db:level=0]. 380MB to 379MB (~99% of original) in 79793ms = 4MB/s. ~1518336 total partitions merged to 1510054.
Jun 29 08:36:56.234595 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  0:comp] compaction - [Compact mview.users_by_first_name be4538a0-35f2-11ef-832f-4edd5a5082c1] Compacting [/var/lib/scylla/data/mview/users_by_first_name-bec561c035c911efb7a8556b9ab55b24/me-3ghe_0nxj_41ymo1ztgniey0hcqp-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/mview/users_by_first_name-bec561c035c911efb7a8556b9ab55b24/me-3ghe_0lx2_26vi81ztgniey0hcqp-big-Data.db:level=0:origin=compaction]
Jun 29 08:36:58.007237 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  0:comp] sstable - Rebuilding bloom filter /var/lib/scylla/data/mview/users_by_first_name-bec561c035c911efb7a8556b9ab55b24/me-3ghe_0nxk_1ekzk1ztgniey0hcqp-big-Filter.db: resizing bitset from 76968 bytes to 39168 bytes.
Jun 29 08:36:58.027598 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  0:comp] compaction - [Compact mview.users_by_first_name be4538a0-35f2-11ef-832f-4edd5a5082c1] Compacted 2 sstables to [/var/lib/scylla/data/mview/users_by_first_name-bec561c035c911efb7a8556b9ab55b24/me-3ghe_0nxk_1ekzk1ztgniey0hcqp-big-Data.db:level=0]. 13MB to 7MB (~50% of original) in 1789ms = 7MB/s. ~61568 total partitions merged to 31328.
Jun 29 08:37:01.458498 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  4:comp] compaction - [Compact keyspace1.standard1 c1625720-35f2-11ef-9bed-4ed55a5082c1] Compacting [/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nqg_1x0kg2dd3fidvtmm69-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nxk_11q0w2dd3fidvtmm69-big-Data.db:level=0:origin=memtable]
Jun 29 08:37:08.352998 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard 11:comp] compaction - [Compact mview.users_by_first_name c57e4800-35f2-11ef-a2e6-4ed85a5082c1] Compacting [/var/lib/scylla/data/mview/users_by_first_name-bec561c035c911efb7a8556b9ab55b24/me-3ghe_0nxw_0xfpc2h6il391sz1kx-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/mview/users_by_first_name-bec561c035c911efb7a8556b9ab55b24/me-3ghe_0ncb_2d39s2h6il391sz1kx-big-Data.db:level=0:origin=compaction]
Jun 29 08:37:09.017431 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard 11:comp] sstable - Rebuilding bloom filter /var/lib/scylla/data/mview/users_by_first_name-bec561c035c911efb7a8556b9ab55b24/me-3ghe_0nxw_23vhc2h6il391sz1kx-big-Filter.db: resizing bitset from 72808 bytes to 39168 bytes.
Jun 29 08:37:09.028207 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard 11:comp] compaction - [Compact mview.users_by_first_name c57e4800-35f2-11ef-a2e6-4ed85a5082c1] Compacted 2 sstables to [/var/lib/scylla/data/mview/users_by_first_name-bec561c035c911efb7a8556b9ab55b24/me-3ghe_0nxw_23vhc2h6il391sz1kx-big-Data.db:level=0]. 13MB to 7MB (~53% of original) in 672ms = 19MB/s. ~58240 total partitions merged to 31329.
Jun 29 08:37:09.376488 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  9:comp] sstable - Rebuilding bloom filter /var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nwo_1hl0h2heod6zuukp8h-big-Filter.db: resizing bitset from 7337288 bytes to 3907560 bytes.
Jun 29 08:37:09.965647 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  9:comp] compaction - [Compact keyspace1.standard1 ab34d9a0-35f2-11ef-a350-4ed95a5082c1] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nwo_1hl0h2heod6zuukp8h-big-Data.db:level=0]. 1GB to 790MB (~53% of original) in 45711ms = 32MB/s. ~5869824 total partitions merged to 3126041.
Jun 29 08:37:17.663578 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  4:comp] compaction - [Compact keyspace1.standard1 c1625720-35f2-11ef-9bed-4ed55a5082c1] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-9e918b7035c611efb472db000a922016/me-3ghe_0nxp_2qdo02dd3fidvtmm69-big-Data.db:level=0]. 140MB to 139MB (~99% of original) in 16201ms = 8MB/s. ~568576 total partitions merged to 557727.
Jun 29 08:37:20.198313 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  0: gms] schema_tables - Creating drop_table_during_repair_ks_8.standard1 id=cc85e720-35f2-11ef-b7a8-556b9ab55b24 version=cc85e721-35f2-11ef-b7a8-556b9ab55b24
Jun 29 08:37:20.199363 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  0: gms] schema_tables - Tablet metadata changed
Jun 29 08:37:20.251781 longevity-tls-50gb-3d-master-db-node-04447069-5 scylla[7490]:  [shard  0: gms] migration_manager - Gossiping my schema version cc85ce16-35f2-11ef-3ae4-79d6f8d0c97a

```

## Impact

Creating ks takes long - more than 10s and this fails c-s

## How frequently does it reproduce?

First time seen

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-04447069-7 (52.49.241.60 | 10.4.22.189) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-04447069-6 (108.128.184.168 | 10.4.22.96) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-04447069-5 (54.220.255.133 | 10.4.22.193) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-04447069-4 (34.241.17.128 | 10.4.22.222) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-04447069-3 (52.210.187.188 | 10.4.23.139) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-04447069-2 (52.16.185.73 | 10.4.23.195) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-04447069-1 (54.155.186.240 | 10.4.21.83) (shards: 14)

OS / Image: `ami-09006ca344092e50b` (aws: undefined_region)

Test: `longevity-50gb-3days-test`
Test id: `04447069-14c9-47f9-8cf8-fe71a0ec1276`
Test name: `scylla-master/tier1/longevity-50gb-3days-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1932795ef1cab447b1225e93965b00e9836afceb/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 04447069-14c9-47f9-8cf8-fe71a0ec1276`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=04447069-14c9-47f9-8cf8-fe71a0ec1276)
- Show all stored logs command: `$ hydra investigate show-logs 04447069-14c9-47f9-8cf8-fe71a0ec1276`

## Logs:
- **db-cluster-04447069.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/04447069-14c9-47f9-8cf8-fe71a0ec1276/20240630_041812/db-cluster-04447069.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/04447069-14c9-47f9-8cf8-fe71a0ec1276/20240630_041812/db-cluster-04447069.tar.gz)
- **sct-runner-events-04447069.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/04447069-14c9-47f9-8cf8-fe71a0ec1276/20240630_041812/sct-runner-events-04447069.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/04447069-14c9-47f9-8cf8-fe71a0ec1276/20240630_041812/sct-runner-events-04447069.tar.gz)
- **sct-04447069.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/04447069-14c9-47f9-8cf8-fe71a0ec1276/20240630_041812/sct-04447069.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/04447069-14c9-47f9-8cf8-fe71a0ec1276/20240630_041812/sct-04447069.log.tar.gz)
- **loader-set-04447069.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/04447069-14c9-47f9-8cf8-fe71a0ec1276/20240630_041812/loader-set-04447069.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/04447069-14c9-47f9-8cf8-fe71a0ec1276/20240630_041812/loader-set-04447069.tar.gz)
- **monitor-set-04447069.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/04447069-14c9-47f9-8cf8-fe71a0ec1276/20240630_041812/monitor-set-04447069.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/04447069-14c9-47f9-8cf8-fe71a0ec1276/20240630_041812/monitor-set-04447069.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-50gb-3days-test/23/)
[Argus](https://argus.scylladb.com/test/98050732-dfe3-464c-a66a-f235bad30829/runs?additionalRuns[]=04447069-14c9-47f9-8cf8-fe71a0ec1276)
</details>

**Comment by mykaul** [comment] 2024-07-01 10:46
Is the cluster just overloaded?

**Comment by kbr-scylla** [comment] 2024-07-01 10:48
Looks similar to https://github.com/scylladb/scylla-enterprise/issues/4082

**Comment by kbr-scylla** [comment] 2024-07-01 11:15
Let's wait for https://github.com/scylladb/scylladb/issues/19105 fix and then retest, marking as blocked

**Comment by soyacz** [comment] 2024-07-01 12:52
> Is the cluster just overloaded?

There's a substantial load, but not overloaded - ~80% load

**Comment by mykaul** [comment] 2024-07-01 13:16
> > Is the cluster just overloaded?
> 
> There's a substantial load, but not overloaded - ~80% load

80% is average. It means sometimes it's 60% and sometimes it's 100% perhaps. We need to ensure this is not the case.

If I look at the stats:
```
total_successful_reads: 72,653,384
                                                                                     total_failed_reads: 12,487,434      <---- WOW!
                                                                                     total_reads_shed_due_to_overload: 0
                                                                                     total_reads_killed_due_to_kill_limit: 0
                                                                                     reads_admitted: 72,863,412
                                                                                     reads_enqueued_for_admission: 75,769,432
                                                                                     reads_enqueued_for_memory: 0
                                                                                     reads_admitted_immediately: 9,376,685
                                                                                     reads_queued_because_ready_list: 11,241,889   <--- I need to better understand what this means[1] 
                                                                                     reads_queued_because_need_cpu_permits: 645,27,543   <--- that's busy
```

[1] https://github.com/scylladb/scylladb/issues/19535

**Comment by mykaul** [comment] 2024-07-01 13:28
> ![image](https://private-user-images.githubusercontent.com/18242288/344691672-8fc4367a-d405-49d3-b1d1-31f11363db51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDA3NzgsIm5iZiI6MTcxOTg0MDQ3OCwicGF0aCI6Ii8xODI0MjI4OC8zNDQ2OTE2NzItOGZjNDM2N2EtZDQwNS00OWQzLWIxZDEtMzFmMTEzNjNkYjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEzMjc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2OWJkOTA2YzhmYTIwN2QzMTRjNjAyNGQwNDY0ZGVhZDczM2JmZjg3OWE2ZGZhOTVhMjg4OWIxZWE5MWFjNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x4KTsEeqGrJqYyEJcAPqPRya4AnuIbLvjRBP2nTuUcM)

@soyacz - per shard please.

**Comment by soyacz** [comment] 2024-07-01 13:50
Looks much more complicated in per shard view
![image](https://github.com/scylladb/scylladb/assets/18242288/30e20a33-b8f6-4470-9bb8-834e894f2928)
this specific node in the interesting range (but acutally pattern is the same for the whole test):
![image](https://github.com/scylladb/scylladb/assets/18242288/3676ef77-fc41-42a7-b134-9e5228cb58eb)

**Comment by mykaul** [comment] 2024-07-01 14:37
@soyacz - this is what I see:
![image](https://github.com/scylladb/scylladb/assets/4655593/71e70cca-550e-47fb-8c84-33bb62c8c90f)

**Comment by mykaul** [comment] 2024-07-01 14:39
And if I look more closely, for example on a single instance, single shard - it's 100% all the way!
![image](https://github.com/scylladb/scylladb/assets/4655593/05214b6c-91bb-440e-afa0-c6cd9f465de6)

**Comment by mykaul** [comment] 2024-07-01 14:46
Different node, different shard (0!):
![image](https://github.com/scylladb/scylladb/assets/4655593/f257ffb1-f4af-4f5f-b00a-6b43fb7a1b11)

**Comment by mykaul** [comment] 2024-07-02 07:14
I wonder if we should architect the test differently, and enable per partition limits (and then the driver should backoff, based on https://github.com/scylladb/scylladb/blob/master/docs/dev/protocol-extensions.md#rate-limit-error ).

**Comment by mykaul** [comment] 2024-07-02 07:16
> ok, so a bit more context related to load: it uses client&server traffic encryption.

Would be good to take a closer look at this, see that it uses AES128 for example, see that there aren't too many SSL re-negotiations, average packet size, etc.

**Comment by fruch** [comment] 2024-07-02 20:37
> I wonder if we should architect the test differently, and enable per partition limits (and then the driver should backoff, based on https://github.com/scylladb/scylladb/blob/master/docs/dev/protocol-extensions.md#rate-limit-error ).

this is a myth, the driver can't backoff, the tools using it need to support such a thing.
none of the tools we have support it...

the driver just knows to pass this along to the code using the driver

we can experiment with the partition limits, but backoff won't happen magically.

**Comment by yarongilor** [comment] 2024-07-03 07:44
> ok, so a bit more context related to load: it uses client&server traffic encryption. There's also background thread running full scan queries, but it runs only between 3:20-3:32 (and I don't know why only that short @yarongilor is it intended?)

the `run_fullscan` is configured to run every minute:
```
run_fullscan: ['{"mode": "table_and_aggregate", "ks_cf": "keyspace1.standard1", "interval": 60}']
```
So probably the thread failed for some reason (not expected).

**Comment by mykaul** [comment] 2024-07-03 08:45
> > I wonder if we should architect the test differently, and enable per partition limits (and then the driver should backoff, based on https://github.com/scylladb/scylladb/blob/master/docs/dev/protocol-extensions.md#rate-limit-error ).
> 
> this is a myth, the driver can't backoff, the tools using it need to support such a thing. none of the tools we have support it...

It's a missing feature.

> 
> the driver just knows to pass this along to the code using the driver

At the very least the tools should print something, I hope... ?

> 
> we can experiment with the partition limits, but backoff won't happen magically.

Is it in the backlog of our tools?

**Comment by fruch** [comment] 2024-07-03 11:40
> > > I wonder if we should architect the test differently, and enable per partition limits (and then the driver should backoff, based on https://github.com/scylladb/scylladb/blob/master/docs/dev/protocol-extensions.md#rate-limit-error ).
> > 
> > 
> > this is a myth, the driver can't backoff, the tools using it need to support such a thing. none of the tools we have support it...
> 
> It's a missing feature.
> 
> > the driver just knows to pass this along to the code using the driver
> 
> At the very least the tools should print something, I hope... ?

I can't guarantee that any tool should print it

> 
> > we can experiment with the partition limits, but backoff won't happen magically.
> 
> Is it in the backlog of our tools?

No

**Comment by mykaul** [comment] 2024-07-03 11:53
@CodeLieutenant - please see above - we may want to add a print or more (actually reduce their load)  to our various stress tools.

**Comment by soyacz** [comment] 2024-07-04 07:12
> > ok, so a bit more context related to load: it uses client&server traffic encryption. There's also background thread running full scan queries, but it runs only between 3:20-3:32 (and I don't know why only that short @yarongilor is it intended?)
> 
> the `run_fullscan` is configured to run every minute:
> 
> ```
> run_fullscan: ['{"mode": "table_and_aggregate", "ks_cf": "keyspace1.standard1", "interval": 60}']
> ```
> 
> So probably the thread failed for some reason (not expected).

@yarongilor can you investigate it and create an SCT issue? There were no error related this thread - I just found it by accitdent when trying to get more context about the cluster load

**Comment by mykaul** [comment] 2024-08-05 11:01
@yarongilor - status?

**Comment by kbr-scylla** [comment] 2024-08-05 15:23
BTW the root cause of https://github.com/scylladb/scylladb/issues/19105 is considered to be fixed, @soyacz could you please rerun the test?

**Comment by soyacz** [comment] 2024-08-06 06:28
@kbr-scylla looks like it's not reproducing anymore in this test

**Closed** 2024-08-07 11:32 UTC
Labels: area/schema changes, triage/master, tests/longevity-tier1
