### ISSUE TITLE
Sum aggregation and group-by produce groups that are not present in table and do not match query

### ISSUE THREAD

**Issue by marshall-onesignal** [scylladb/scylladb#13027] opened 2023-02-27 20:57 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.6
Cluster size: 1 (local development)
OS (RHEL/CentOS/Ubuntu/AWS AMI): macOS Intel/Docker

Got a rather surprising result from a query today. Here's a very minimal reproduction setup that illustrates my problem:

```
CREATE  KEYSPACE IF NOT EXISTS ks WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 } AND DURABLE_WRITES =  true;
CREATE TABLE IF NOT EXISTS ks.xs (
  id int,
  value int,
  PRIMARY KEY (id)
);
```

Running this query produces no rows, since there is no data, good:
```
cassandra@cqlsh:counters> SELECT * FROM ks.xs;

 id | value
----+-------

(0 rows)
```

And adding a where clause also produces no data, as expected:
```
cassandra@cqlsh:counters> SELECT * FROM ks.xs WHERE id IN (0,1,2);

 id | value
----+-------

(0 rows)
```

Here's where the problem happens:
```
SELECT id, sum(value) FROM ks.xs WHERE id IN (0,1,2);

 id   | system.sum(value)
------+-------------------
 null |                 0
 
(1 rows)
```
 
The thing is, this implies to me that some rows matched this query, those rows had a `null` id. But, this value, `null` is not present in the id column. Even if it were, my WHERE clause should not match any rows with id = null, so this seems wrong for a few different reasons at least.

This seems like a bug, that a `null` group should be produced for this query, when the query should not produce any rows at all.

**Comment by nyh** [comment] 2023-02-28 12:52
I confirmed that if there are no rows, sum() returns 0, not null. But that Cassandra also does this.
In contrast, min() for no rows return null.

Some sources like https://dba.stackexchange.com/questions/92126/why-does-sum-return-0-when-no-rows-in-table suggest that also in SQL, the sum of an empty list is 0, not null. (@avikivity maybe you know better).

Are you aware of documentation or other sources that suggest that we should, or it is better to return null in this case?

**Comment by nyh** [comment] 2023-02-28 13:01
See also #12477, where group-by (which you mentioned in the issue title but not the text of the issue) also leads to the weird situation where to return a zero number (in that case, a count), we return a fake null partition key. Note that in that case, Cassandra doesn't output those fake-looking results with empty counts, so we can consider Scylla's behavior to be buggy. But in the sum() case described here, Cassandra does the same as us so we need to be more careful if we want to change it.

**Comment by avikivity** [comment] 2023-02-28 13:45
> I confirmed that if there are no rows, sum() returns 0, not null. But that Cassandra also does this. In contrast, min() for no rows return null.
> 
> Some sources like https://dba.stackexchange.com/questions/92126/why-does-sum-return-0-when-no-rows-in-table suggest that also in SQL, the sum of an empty list is 0, not null. (@avikivity maybe you know better).

The sum of nothing is 0, it's perfectly consistent.

In addition, aggregates ignore NULLs (so the sum of 5 and NULL is NULL, if computed with an aggregate,and NULL if computed with the addition operator). This is inconsistent with general NULL handling, but that's how SQL works.

> 
> Are you aware of documentation or other sources that suggest that we should, or it is better to return null in this case?

No, we should return 0.

**Comment by avikivity** [comment] 2023-02-28 13:47
> 
> ```
> SELECT id, sum(value) FROM ks.xs WHERE id IN (0,1,2);
> 
>  id   | system.sum(value)
> ------+-------------------
>  null |                 0
>  
> (1 rows)
> ```
> 
> The thing is, this implies to me that some rows matched this query, those rows had a `null` id. But, this value, `null` is not present in the id column. Even if it were, my WHERE clause should not match any rows with id = null, so this seems wrong for a few different reasons at least.
> 
> This seems like a bug, that a `null` group should be produced for this query, when the query should not produce any rows at all.

I think it's correct. You asked for the sum, which is 0. You asked for the key to which the sum belongs, but there is no such key, because you're summing across all keys. So you got NULL.

**Comment by marshall-onesignal** [comment] 2023-02-28 17:01
My great apologies, in my formatting this question, I left out an important thing, which is that I am trying to get the sum of each group. Again, sorry for the confusion here.

This query, for example, produces a "id = null" group:
```
cassandra@cqlsh:counters> select id, sum(value) from ks.xs group by id;

 id   | system.sum(value)
------+-------------------
 null |                 0
```

And similarly, if I specify one or more ids, I still get a null group:

```
cassandra@cqlsh:counters> select id, sum(value) from ks.xs where id = 123 group by id;

 id   | system.sum(value)
------+-------------------
 null |                 0

(1 rows)
```

```
cassandra@cqlsh:counters> select id, sum(value) from ks.xs where id in (1, 2, 3) group by id;

 id   | system.sum(value)
------+-------------------
 null |                 0

(1 rows)
```

**Comment by nyh** [comment] 2023-02-28 18:23
The new information, with GROUP BY, doesn't it make this issue a duplicate of #12477 ?

**Comment by marshall-onesignal** [comment] 2023-02-28 19:00
Yes that does seem like the same issue I am seeing

**Comment by avikivity** [comment] 2023-02-28 19:05
Closing as duplicate of #12477.

**Closed by avikivity** 2023-02-28 19:05 UTC
Labels: CQL
