### ISSUE TITLE
[dtest] test_refresh_and_restart_after_compaction_strategy_change timeouts on TRUNCATE (TWCS only?)

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#15610] opened 2023-10-03 06:00 UTC
compaction_additional_test.py::TestCompactionAdditional::test_refresh_and_restart_after_compaction_strategy_change
is timeing out on truncate (happens on all different compaction strategy options that this test is using)

```
self = <compaction_additional_test.TestCompactionAdditional object at 0x7f1dbec1c250>
strategy1 = {'bucket_high': 1.5, 'bucket_low': 0.5, 'class': 'SizeTieredCompactionStrategy', 'min_sstable_size': 1, ...}
strategy2 = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': 1, 'compaction_window_unit': 'MINUTES', 'min_threshold': 2}

    @pytest.mark.single_node
    @pytest.mark.parametrize("strategy1,strategy2", get_strategies_upgrade_options(), ids=generate_ids)
    def test_refresh_and_restart_after_compaction_strategy_change(self, strategy1, strategy2):
        """
        This test tries to load backup sstable by refresh and restart after changing the compaction strategy.
        refreshing loads sstable from upload directory, and sstable in staging or main sstable directory will
        be loaded in cf populating during restart.
    
        Reshaping will only be triggered conditionally if current compaction strategy isn't satisfied.
    
        LeveledCompactionStrategy:
        - level 0 has more sstables than min_threshold (strict mode) or max_compaction_threshold (relax_mode) (covered in the test)
        - have 10% overlapping sstables on same level
        - sstable level out of MAX level (9)
    
        SizeTieredCompactionStrategy:
        - have more than min_threshold similar-sized SSTables
    
        TimeWindowCompactionStrategy:
        - have sstables that span more than 1 window
        - a given window has more than min_threshold SSTables.
        - Time-Window Compaction Strategy compacts SSTables within each time window
          using Size-tiered Compaction Strategy (STCS)
    
        DateTieredCompactionStrategy:
        - doesn't support reshaping
        """
        cluster = self.cluster
        cluster.populate(1)
        node1 = cluster.nodelist()[0]
        node1.start(wait_for_binary_proto=True)
    
        node1 = self.cluster.nodelist()[0]
        session = self.patient_cql_connection(node1)
        session.execute("DROP KEYSPACE IF EXISTS keyspace1")
    
        logger.debug(f"Create test table with {strategy1}")
        node1.stress(['write', 'n=0', 'no-warmup', '-schema', 'replication(factor=1)', '-rate', 'threads=1'])
    
        session.execute(f"ALTER TABLE keyspace1.standard1 WITH compaction={strategy1}")
    
        logger.debug("Insert test data by cassandra-stress and compact")
        # Use multiple workloads to generate multiple sstables, then it's easy to reach the threshold for reshaping
    
        fill_data_by_cs(node1, n_range=[500, 550, 600, 650])
        # Compact initially, make sure there are some compacted sstables before disable autocompaction
        node1.compact()
    
        # Here we disable autocompaction for leaving all sstables in level 0, then
        # it's easy to trigger reshape with small dataset during restart (strict mode).
        # Actually it's not always necessary.
        #
        # Refreshing from upload will use strict mode reshape, restart population
        # from staging or main sstable directory will use relax mode reshape.
        # Only in relaxed mode, all sstables will be mutated to level to 0, reshaping
        # will be trigger very easily.
    
        logger.debug('disable autocompaction to leave all sstables in level 0')
        node1.nodetool('disableautocompaction keyspace1 standard1')
    
        logger.debug("Insert test data by cassandra-stress without compacting, leave it for next strategy")
    
        if (strategy2['class'] == 'TimeWindowCompactionStrategy'):
            # Prepare a sstable spans two 1 window, (window unit is 60 seconds)
            fill_data_by_cs(node1, n_range=[], duration_range=[70],
                            other_opt=['-rate', 'threads=1', '-col', 'size=FIXED(1024)'])
        elif (strategy2['class'] == 'LeveledCompactionStrategy'):
            # Need more than 10% overlapping sstables on same level
            fill_data_by_cs(node1, n_range=[500, 550, 600, 650, 1000], start=5000)
        elif (strategy2['class'] == 'SizeTieredCompactionStrategy'):
            fill_data_by_cs(node1, n_range=[500, 550, 600, 650, 2000, 5000] * 2, start=10000)
        else:
            fill_data_by_cs(node1, n_range=[500, 550, 600, 650], start=5000)
    
        cf_dir = get_node_cf_dir(node1, 'keyspace1', 'standard1', latest=True)
        logger.debug(cf_dir)
    
        # For troubleshot
        backup_dir = os.path.join(cf_dir, f'./backup.{time.time()}/')
        copy_files_to(cf_dir, backup_dir, files_only=True, create_to_dir=True)
    
        # Prepare for refresh
        copy_files_to(cf_dir, os.path.join(cf_dir, './upload/'), files_only=True)
    
        logger.info(f"Change table compaction strategy to {strategy2}")
        session.execute(f"ALTER TABLE keyspace1.standard1 WITH compaction={strategy2}")
    
        def assert_reshape(srcdir, log_mark, verify_reshape=True, followed_by=None):
            """
            Check Reshaping or Resharding really happened
            """
            try:
                exprs = [r"(Reshape|Reshard) keyspace1.standard1"]
                if followed_by:
                    exprs.append(followed_by)
                res = node1.watch_log_for(exprs, timeout=30, from_mark=log_mark)
                logger.debug(res)
            except TimeoutError:
                res = None
                msg = f"Reshape or Reshard didn't occur after loading sstables from {srcdir} directory"
                if (strategy2['class'] not in ['DateTieredCompactionStrategy', 'SizeTieredCompactionStrategy'] and verify_reshape):
                    if strategy2['class'] != strategy1['class']:
                        assert res is not None, f"Reshape didn't occurred in loading sstables from {srcdir} directory"
                    else:
                        logger.debug(msg + ", as expected.")
    
        def verify_data(srcdir):
            """
            Verify the loaded data by cs read
            """
            logger.info(f'Verify data is loaded from {srcdir} directory')
            node1.stress(['read', 'n=100', 'no-warmup', '-rate', 'threads=10', '-col', 'size=FIXED(1024)'])
    
        logger.debug("Clean test data & sstables before subtest by TRUNCATE")
>       session.execute("TRUNCATE keyspace1.standard1")

compaction_additional_test.py:699: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cassandra/cluster.py:2700: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'127.0.23.1:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.23.1:9042
```

### logs 
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4985/testReport/junit/compaction_additional_test/TestCompactionAdditional/FullDtest___full_split005___test_refresh_and_restart_after_compaction_strategy_change_SizeTieredCompactionStrategy_TimeWindowCompactionStrategy_/

Failing on this alot since Aug 11:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/81989430-61b1-11ee-bf28-5927cc3d3ce3

**Comment by fruch** [comment] 2023-10-03 06:03
Moving to P1, since it's failed two runs stright of next

**Comment by avikivity** [comment] 2023-10-08 13:56
Seen again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6622/testReport/junit/compaction_additional_test/TestCompactionAdditional/Tests___Sanity_Tests___test_refresh_and_restart_after_compaction_strategy_change_SizeTieredCompactionStrategy_TimeWindowCompactionStrategy_/

Moving to P0.

@fruch anything changed here recently?

@bhalevy I don't think the truncate part matches the schema synchronization problem we talked about.

**Comment by bhalevy** [comment] 2023-10-08 14:03
@avikivity, right.
I was talking about https://github.com/scylladb/scylladb/issues/15530

**Comment by fruch** [comment] 2023-10-08 14:37
> Seen again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6622/testReport/junit/compaction_additional_test/TestCompactionAdditional/Tests___Sanity_Tests___test_refresh_and_restart_after_compaction_strategy_change_SizeTieredCompactionStrategy_TimeWindowCompactionStrategy_/
> 
> Moving to P0.
> 
> @fruch anything changed here recently?
> 
> @bhalevy I don't think the truncate part matches the schema synchronization problem we talked about.

Not anything related to this specific test

**Comment by bhalevy** [comment] 2023-10-09 09:01
@Deexie haven't we seen a similar timeout when stopping compaction tasks? maybe for drop table?

**Comment by Deexie** [comment] 2023-10-09 10:37
> @Deexie haven't we seen a similar timeout when stopping compaction tasks? maybe for drop table?

I think you mean #15301. It was timeout during table dropping, not related to stopping compaction tasks

**Comment by tchaikov** [comment] 2023-10-10 14:25
@raphaelsc hi Raphael, anything i can assist to share your load? if you could share some pointers, probably i can experiment and implement it?

**Comment by avikivity** [comment] 2023-10-11 10:49
Seen again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6650/testReport/junit/compaction_additional_test/TestCompactionAdditional/Tests___Sanity_Tests_RAFT___test_refresh_and_restart_after_compaction_strategy_change_LeveledCompactionStrategy_TimeWindowCompactionStrategy_/

**Comment by avikivity** [comment] 2023-10-11 10:50
@tchaikov since it's a timeout, perhaps raising the request timeout can help. See truncate_request_timeout_in_ms, perhaps adjust dtest or ccm so that all nodes start with a higher timeout.

May also need to increase client-side timeout.

**Comment by bhalevy** [comment] 2023-10-11 11:03
@avikivity it's a `Client request timeout` not on the server side.

**Comment by bhalevy** [comment] 2023-10-11 12:35
> @bhalevy is it the same issue as #6309, which has been plaguing us for quite some time?

No, I don't think so.  There the timeout is on the server side and the inter-node rpc call times out.
Here it's a 1-node cluster (no node-to-node communication of course) and the truncate cql query times out on the client side, while it's unclear what holds it up on the server side.

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/5192/artifact/logs-full.release.005/1697015665569_compaction_additional_test.py%3A%3ATestCompactionAdditional%3A%3Atest_refresh_and_restart_after_compaction_strategy_change%5BLeveledCompactionStrategy-TimeWindowCompactionStrategy%5D/node1.log
```
INFO  2023-10-11 09:13:44,398 [shard 1:stat] database - Truncating keyspace1.standard1 with auto-snapshot
INFO  2023-10-11 09:13:55,338 [shard 0:comp] compaction - [Compact system.truncated 80bb1ea0-6816-11ee-b7e3-26056b6bef3d] Compacting [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-d305h_xo/test/node1/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3ga4_0pmw_3kdww2so5huh01ox8d-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-d305h_xo/test/node1/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3ga4_0pjs_1mxwx2so5huh01ox8d-big-Data.db:level=0:origin=compaction]
INFO  2023-10-11 09:14:22,686 [shard 0:main] compaction_manager - Asked to stop
```

Seems to indicate that truncate did manage to write the truncation record to system.truncated
meaning we got here: https://github.com/scylladb/scylladb/blob/5a10bd44bf594b29efba68935c812806a977878f/replica/database.cc#L2676
via https://github.com/scylladb/scylladb/blob/5a10bd44bf594b29efba68935c812806a977878f/replica/database.cc#L2640

So we passed the actual deletion of sstables, called in https://github.com/scylladb/scylladb/blob/5a10bd44bf594b29efba68935c812806a977878f/replica/database.cc#L2652

**Comment by tchaikov** [comment] 2023-10-14 07:46
> @tchaikov since it's a timeout, perhaps raising the request timeout can help. See truncate_request_timeout_in_ms, perhaps adjust dtest or ccm so that all nodes start with a higher timeout.
> 
> 
> 
> May also need to increase client-side timeout.

Thank you Avi, will give it a try early next week.

**Comment by bhalevy** [comment] 2023-10-14 08:00
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/5192/artifact/logs-full.release.005/dtest-gw2.log
```
09:11:13,591 787     dtest_setup                    DEBUG    dtest_setup.py      :692  | test_refresh_and_restart_after_compaction_strategy_change[LeveledCompactionStrategy-TimeWindowCompactionStrategy]: Cluster *_request_timeout_in_ms=10000, range_request_timeout_in_ms=30000, cql request_timeout=30
```

30 seconds should be more than enough.

As discussed in https://github.com/scylladb/scylladb/issues/15700, we may need to reproduce this class of client-side timeouts with client debug-level logging to get more insight.

**Comment by bhalevy** [comment] 2023-10-14 21:06
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/6662/testReport/junit/compaction_additional_test/TestCompactionAdditional/Tests___Sanity_Tests_RAFT___test_refresh_and_restart_after_compaction_strategy_change_TimeWindowCompactionStrategy_TimeWindowCompactionStrategy_/
```
        logger.debug("Clean test data & sstables before subtest by TRUNCATE")
>       session.execute("TRUNCATE keyspace1.standard1")

compaction_additional_test.py:699: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cassandra/cluster.py:2708: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'127.0.55.1:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.55.1:9042
```

**Comment by bhalevy** [comment] 2023-10-14 21:12
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/6661/testReport/junit/compaction_additional_test/TestCompactionAdditional/Tests___Sanity_Tests___test_refresh_and_restart_after_compaction_strategy_change_SizeTieredCompactionStrategy_TimeWindowCompactionStrategy_/

**Comment by mykaul** [comment] 2023-10-16 09:50
Need to see if it's due to the infra (which is now fixed) - will check in a day or two.

**Comment by tchaikov** [comment] 2023-10-16 11:04
```
22:57:35,226 787     compaction_additional_test ... Clean test data & sstables before subtest by TRUNCATE
22:58:05,373 787     errors ... test failed: 
self = <compaction_additional_test.TestCompactionAdditional object at 0x7fa87a212f50>
```

and the default timeout of the session returned by `patient_cql_connection()` is 30 second. so scylla failed to complete the request in 30 seconds.

but right before we tried to truncate the table, its compaction strategy was changed:
```
INFO  2023-10-12 22:57:35,210 [shard 0:stat] migration_manager - Update table 'keyspace1.standard1' From ... compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy ... To ...  compactionStrategyClass=class org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy...
INFO  2023-10-12 22:57:35,213 [shard 0:stat] schema_tables - Altering keyspace1.standard1 id=69ef28a0-6952-11ee-97ab-806478c6c025 version=7a416e54-42b3-387b-b473-6f23019187d6
INFO  2023-10-12 22:57:35,214 [shard 0:stat] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
INFO  2023-10-12 22:57:35,214 [shard 1:stat] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
INFO  2023-10-12 22:57:35,221 [shard 0:stat] schema_tables - Schema version changed to aa87d37f-7651-38b8-be1d-3276d8dbcea4
INFO  2023-10-12 22:57:35,227 [shard 0:stat] database - Truncating keyspace1.standard1 with auto-snapshot
INFO  2023-10-12 22:58:09,149 [shard 0:main] compaction_manager - Asked to stop
```
so the server did start performing the requested truncate. but unfortunately, we don't write an "info" log message in `database::truncate_table_on_all_shards()` when the we finish

1. snapshot, 
2. flush
3. and truncate the table on all shards.

**Comment by tchaikov** [comment] 2023-10-16 11:23
will add more logging messages to see if it is reproduciable.

**Comment by tchaikov** [comment] 2023-10-16 11:24
> Need to see if it's due to the infra (which is now fixed) - will check in a day or two.

@mykaul what kind of infra issue got fixed? do you happen to have link or just some words on this?

**Comment by mykaul** [comment] 2023-10-16 11:41
> > Need to see if it's due to the infra (which is now fixed) - will check in a day or two.
> 
> @mykaul what kind of infra issue got fixed? do you happen to have link or just some words on this?

Some runs were on instances that had local *SSD* and not NVMe. Regretfully, our cloud-init did not recognize those disks and did not use it - so we've used the root EBS disk, which is way way too slow for anything.

**Comment by avikivity** [comment] 2023-10-16 11:46
https://github.com/scylladb/scylla-pkg/issues/3620

**Comment by tchaikov** [comment] 2023-10-17 05:47
thank you Avi and Yaniv. i am lowering the priority to P1 at this moment because the timeout was very likely caused by the slow storage medium.

**Comment by tchaikov** [comment] 2023-10-30 02:04
https://jenkins.scylladb.com/job/scylla-master/job/next/6750/

**Comment by benipeled** [comment] 2023-10-30 13:20
...and again https://jenkins.scylladb.com/job/scylla-master/job/next/6752/testReport/junit/compaction_additional_test/TestCompactionAdditional/Tests___Sanity_Tests_RAFT___test_refresh_and_restart_after_compaction_strategy_change_LeveledCompactionStrategy_TimeWindowCompactionStrategy_/
(local node: spider2)

**Comment by michoecho** [comment] 2023-10-30 13:41
Note that only the test cases which switch to TWCS time out on TRUNCATE after 30s. Cases which switch to STCS complete the TRUNCATE step in ~40ms.

**Comment by dani-tweig** [comment] 2024-11-05 10:40
@regevran , is this issue a P1?
it has not been touched in the past year.

**Comment by regevran** [comment] 2024-11-06 11:34
> [@regevran](https://github.com/regevran) , is this issue a P1? it has not been touched in the past year.

Not in my area.
@denesb ?

**Comment by denesb** [comment] 2024-11-06 12:38
This was not seen for over a year, so I'm not even sure we should keep this open and I'm quite sure it is not P1.

**Closed** 2024-11-06 12:46 UTC
Labels: tests/dtest, triage/master, P1, symptom/ci stability
