### ISSUE TITLE
[CoreDumpEvent] occurred while attempt to drop index

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylladb#21317] opened 2024-10-28 11:53 UTC
## Packages

Scylla version: `6.3.0~dev-20241018.b11d50f59191` with build-id `d5fe38f8fd12d9b834688320151f36fb8c1e050d`

Kernel Version: `6.8.0-1017-aws`

## Issue description
New issue

During the attempt to drop the index, scylla failed with the next error which led to core dump event:

```
2024-10-20T06:17:40.780+00:00 longevity-tls-50gb-3d-master-db-node-170a3a75-3     !INFO | scylla[64284]:  [shard  0: gms] schema_tables - Altering keyspace1.standard1 id=1d112320-8dc9-11ef-88de-d8e5ae3df4bd version=02749000-8eab-11ef-be20-c2f5becb161c
2024-10-20T06:17:40.780+00:00 longevity-tls-50gb-3d-master-db-node-170a3a75-3     !INFO | scylla[64284]:  [shard  0: gms] schema_tables - Dropping keyspace1.standard1_vls3d2o485_nemesis_index id=eaa59781-8eaa-11ef-8c35-cbb1e285d8a7 version=eaa59782-8eaa-11ef-8c35-cbb1e285d8a7
```

```
2024-10-20T06:17:40.780+00:00 longevity-tls-50gb-3d-master-db-node-170a3a75-3     !INFO | scylla[64284]:  [shard  0: gms] view - Stopping to build view keyspace1.standard1_vls3d2o485_nemesis_index
2024-10-20T06:17:40.780+00:00 longevity-tls-50gb-3d-master-db-node-170a3a75-3     !INFO | scylla[64284]:  [shard  0: gms] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
2024-10-20T06:17:40.780+00:00 longevity-tls-50gb-3d-master-db-node-170a3a75-3     !INFO | scylla[64284]:  [shard  5: gms] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
2024-10-20T06:17:40.780+00:00 longevity-tls-50gb-3d-master-db-node-170a3a75-3     !INFO | scylla[64284]:  [shard  3: gms] query_processor - Column definitions for keyspace1.standard1 changed, invalidating related prepared statements
2024-10-20T06:17:40.780+00:00 longevity-tls-50gb-3d-master-db-node-170a3a75-3      !ERR | scylla[64284]:  [shard  5: gms] view - Schema version used for view updates (02749000-8eab-11ef-be20-c2f5becb161c) does not match the current base schema version of the view (eaa59780-8eaa-11ef-8c35-cbb1e285d8a7) for view keyspace1.standard1_vls3d2o485_nemesis_index of keyspace1.standard1, at: 0x61e61ae 0x61e67d0 0x61e6ad8 0x5ca6787 0x39a1f1d 0x3a4c23c 0x39ea700 0x39ed181 0x39e5f11 0x39cc1d0 0x3a1bb5e 0x60ba986
```
Here is decoded dump:
```
Oct 20 06:17:40.412444 longevity-tls-50gb-3d-master-db-node-170a3a75-3 scylla[64284]: Backtrace:
Oct 20 06:17:40.412444 longevity-tls-50gb-3d-master-db-node-170a3a75-3 scylla[64284]:
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:805
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:850
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3973
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3950
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3945
/data/scylla-s3-reloc.cache/by-build-id/d5fe38f8fd12d9b834688320151f36fb8c1e050d/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=77c77fee058b19c6f001cf2cb0371ce3b8341211, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/on_internal_error.cc:56
db::view::make_view_update_builder(data_dictionary::database, replica::table const&, seastar::lw_shared_ptr<schema const> const&, std::vector<db::view::view_and_base, std::allocator<db::view::view_and_base> >&&, mutation_reader&&, seastar::optimized_optional<mutation_reader>&&, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >) at ././db/view/view.cc:1608
db::view::view_update_generator::populate_views(replica::table const&, std::vector<db::view::view_and_base, std::allocator<db::view::view_and_base> >, dht::token, mutation_reader&&, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >) at ././db/view/view_update_generator.cc:337
db::view::view_builder::consumer::flush_fragments() at ././db/view/view.cc:2957
db::view::view_builder::consumer::consume_end_of_partition() at ././db/view/view.cc:2971
 (inlined by) _ZN22compact_mutation_stateIL20compact_for_sstables0EE24consume_end_of_partitionIN2db4view12view_builder8consumerE33noop_compacted_fragments_consumerQaa28CompactedFragmentsConsumerV2ITL0__E28CompactedFragmentsConsumerV2ITL0_0_EEEN7seastar10bool_classINSA_18stop_iteration_tagEEERT_RT0_ at ././mutation/mutation_compactor.hh:513
 (inlined by) compact_mutation_v2<(compact_for_sstables)0, db::view::view_builder::consumer, noop_compacted_fragments_consumer>::consume_end_of_partition() at ././mutation/mutation_compactor.hh:700
 (inlined by) mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}::operator()() const at ././readers/mutation_reader.hh:291
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::bool_class<seastar::stop_iteration_tag> >::invoke<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}>(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2034
auto seastar::futurize_invoke<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}>(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2063
 (inlined by) mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&) at ././readers/mutation_reader.hh:290
 (inlined by) decltype(auto) mutation_fragment_v2::consume<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&) && requires MutationFragmentConsumerV2<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >, decltype ((((std::declval<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >)()).consume)((std::declval<range_tombstone_change>)()))> at ././mutation/mutation_fragment_v2.hh:287
 (inlined by) mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::operator()(mutation_fragment_v2&&) at ././readers/mutation_reader.hh:270
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > std::__invoke_impl<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> >, mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>(std::__invoke_other, mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:61
 (inlined by) std::__invoke_result<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>::type std::__invoke<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:96
 (inlined by) std::__invoke_result<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>::type std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >::operator()<mutation_fragment_v2>(mutation_fragment_v2&&) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/refwrap.h:363
 (inlined by) mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}::operator()() at ././readers/mutation_reader.hh:251
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}>(mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2032
 (inlined by) auto seastar::futurize_invoke<mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}>(mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2063
 (inlined by) void mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>) at ././readers/mutation_reader.hh:250
 (inlined by) auto mutation_reader::impl::consume_in_thread<compact_for_query_v2<db::view::view_builder::consumer>, mutation_reader::no_filter>(compact_for_query_v2<db::view::view_builder::consumer>, mutation_reader::no_filter) requires (FlattenedConsumerV2<compact_for_query_v2<db::view::view_builder::consumer> >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>) at ././readers/mutation_reader.hh:337
db::view::view_builder::execute(db::view::view_builder::build_step&, exponential_backoff_retry) at ././readers/mutation_reader.hh:479
seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<db::view::view_builder::do_build_step()::$_0>(seastar::thread_attributes, db::view::view_builder::do_build_step()::$_0&&)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././db/view/view.cc:2555
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:215
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/thread.cc:312
```

## Impact

View schemas don't match. Potential data inconsistency

## How frequently does it reproduce?
Just once

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-170a3a75-9 (52.31.245.97 | 10.4.20.254) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-8 (52.19.177.212 | 10.4.22.144) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-7 (46.137.162.217 | 10.4.20.148) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-6 (52.209.30.91 | 10.4.23.146) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-5 (63.33.224.47 | 10.4.21.168) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-4 (34.252.147.34 | 10.4.23.42) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-3 (34.248.231.218 | 10.4.20.6) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-2 (54.171.197.125 | 10.4.21.240) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-18 (18.200.145.11 | 10.4.22.132) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-17 (54.228.229.246 | 10.4.21.13) (shards: -1)
- longevity-tls-50gb-3d-master-db-node-170a3a75-16 (52.208.3.54 | 10.4.20.71) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-15 (52.16.113.117 | 10.4.21.56) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-14 (52.215.20.76 | 10.4.22.217) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-13 (34.243.161.63 | 10.4.20.118) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-12 (18.200.105.93 | 10.4.21.184) (shards: -1)
- longevity-tls-50gb-3d-master-db-node-170a3a75-11 (34.240.120.203 | 10.4.20.37) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-10 (34.253.153.95 | 10.4.22.59) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-170a3a75-1 (108.128.254.111 | 10.4.20.120) (shards: 14)

OS / Image: `ami-0d68a690456025633` (aws: undefined_region)

Test: `longevity-50gb-3days-test`
Test id: `170a3a75-f4ae-41e2-99e8-dda8d5332da1`
Test name: `scylla-master/tier1/longevity-50gb-3days-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/99d539bbdc3a4ec912511e761275f0c202fd9a30/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 170a3a75-f4ae-41e2-99e8-dda8d5332da1`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=170a3a75-f4ae-41e2-99e8-dda8d5332da1)
- Show all stored logs command: `$ hydra investigate show-logs 170a3a75-f4ae-41e2-99e8-dda8d5332da1`

## Logs:
- **longevity-tls-50gb-3d-master-db-node-170a3a75-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-6-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-6-170a3a75.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-170a3a75-7** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-7-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-7-170a3a75.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-170a3a75-1** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-1-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-1-170a3a75.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-170a3a75-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-5-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-5-170a3a75.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-170a3a75-4** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-4-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-4-170a3a75.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-170a3a75-12** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-12-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-12-170a3a75.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-170a3a75-11** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-11-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-11-170a3a75.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-170a3a75-10** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-10-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-10-170a3a75.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-170a3a75-2** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-2-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-2-170a3a75.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-170a3a75-8** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-8-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-8-170a3a75.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-170a3a75-17** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-17-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-17-170a3a75.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-170a3a75-15** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-15-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241019_031025/longevity-tls-50gb-3d-master-db-node-170a3a75-15-170a3a75.tar.gz)
- **core.scylla-longevity-tls-50gb-3d-master-db-node-170a3a75-2-2024-10-19_08-48-10.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.systemd-network.998.1d7e4f3eada844d09b4bf05d0a4c7b01.607.1729327634000000./core.systemd-network.998.1d7e4f3eada844d09b4bf05d0a4c7b01.607.1729327634000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.systemd-network.998.1d7e4f3eada844d09b4bf05d0a4c7b01.607.1729327634000000./core.systemd-network.998.1d7e4f3eada844d09b4bf05d0a4c7b01.607.1729327634000000.zst)
- **core.scylla-longevity-tls-50gb-3d-master-db-node-170a3a75-18-2024-10-20_06-22-10.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.ad92c3e51fec4d7e9d7d1935b6353fde.5570.1729405060000000./core.scylla.106.ad92c3e51fec4d7e9d7d1935b6353fde.5570.1729405060000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.ad92c3e51fec4d7e9d7d1935b6353fde.5570.1729405060000000./core.scylla.106.ad92c3e51fec4d7e9d7d1935b6353fde.5570.1729405060000000.zst)
- **core.scylla-longevity-tls-50gb-3d-master-db-node-170a3a75-13-2024-10-20_06-22-23.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.9bc3ae695d4e422ca52948890a8cad9d.12652.1729405060000000./core.scylla.106.9bc3ae695d4e422ca52948890a8cad9d.12652.1729405060000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.9bc3ae695d4e422ca52948890a8cad9d.12652.1729405060000000./core.scylla.106.9bc3ae695d4e422ca52948890a8cad9d.12652.1729405060000000.zst)
- **core.scylla-longevity-tls-50gb-3d-master-db-node-170a3a75-9-2024-10-20_06-22-27.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.05ce1216c6e447dabb70b8f9a082f49a.44942.1729405060000000./core.scylla.106.05ce1216c6e447dabb70b8f9a082f49a.44942.1729405060000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.05ce1216c6e447dabb70b8f9a082f49a.44942.1729405060000000./core.scylla.106.05ce1216c6e447dabb70b8f9a082f49a.44942.1729405060000000.zst)
- **core.scylla-longevity-tls-50gb-3d-master-db-node-170a3a75-14-2024-10-20_06-22-29.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.19ab2baddb1948cf89cef914d893f7de.13079.1729405060000000./core.scylla.106.19ab2baddb1948cf89cef914d893f7de.13079.1729405060000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.19ab2baddb1948cf89cef914d893f7de.13079.1729405060000000./core.scylla.106.19ab2baddb1948cf89cef914d893f7de.13079.1729405060000000.zst)
- **core.scylla-longevity-tls-50gb-3d-master-db-node-170a3a75-3-2024-10-20_06-22-31.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.cfdae1b662b14084ac81e62a5b3619d6.64284.1729405060000000./core.scylla.106.cfdae1b662b14084ac81e62a5b3619d6.64284.1729405060000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.cfdae1b662b14084ac81e62a5b3619d6.64284.1729405060000000./core.scylla.106.cfdae1b662b14084ac81e62a5b3619d6.64284.1729405060000000.zst)
- **core.scylla-longevity-tls-50gb-3d-master-db-node-170a3a75-16-2024-10-20_06-22-33.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.b9f85620a19f4988a528468e0af8303b.10604.1729405060000000./core.scylla.106.b9f85620a19f4988a528468e0af8303b.10604.1729405060000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.b9f85620a19f4988a528468e0af8303b.10604.1729405060000000./core.scylla.106.b9f85620a19f4988a528468e0af8303b.10604.1729405060000000.zst)
- **db-cluster-170a3a75.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241020_062623/db-cluster-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241020_062623/db-cluster-170a3a75.tar.gz)
- **sct-runner-events-170a3a75.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241020_062623/sct-runner-events-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241020_062623/sct-runner-events-170a3a75.tar.gz)
- **sct-170a3a75.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241020_062623/sct-170a3a75.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241020_062623/sct-170a3a75.log.tar.gz)
- **loader-set-170a3a75.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241020_062623/loader-set-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241020_062623/loader-set-170a3a75.tar.gz)
- **monitor-set-170a3a75.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241020_062623/monitor-set-170a3a75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/170a3a75-f4ae-41e2-99e8-dda8d5332da1/20241020_062623/monitor-set-170a3a75.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-50gb-3days-test/42/)
[Argus](https://argus.scylladb.com/test/98050732-dfe3-464c-a66a-f235bad30829/runs?additionalRuns[]=170a3a75-f4ae-41e2-99e8-dda8d5332da1)
</details>

**Comment by mykaul** [comment] 2024-10-28 18:05
@timtimb0t - did you search for similar reports?

**Comment by raphaelsc** [comment] 2024-10-28 18:10
I think it's a dup of https://github.com/scylladb/scylladb/issues/9059

**Comment by mykaul** [comment] 2024-11-04 10:59
> I think it's a dup of [#9059](https://github.com/scylladb/scylladb/issues/9059)

@kbr-scylla - can we close as a dup?

**Comment by kbr-scylla** [comment] 2024-11-04 11:29
Duplicate of https://github.com/scylladb/scylladb/issues/9059.

**Closed by kbr-scylla** 2024-11-04 11:29 UTC
Labels: area/materialized views, tests/longevity-tier1
