### ISSUE TITLE
Never ending repair due to: Semaphore timed out: _streaming_concurrency_sem

### ISSUE THREAD

**Issue by r4fek** [scylladb/scylladb#11552] opened 2022-09-15 08:15 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.0.1
Cluster size: 3 x 8 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 10.13

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores=40 hyperthreading= memory=192GB
Disks: (SSD/HDD, count) 2x4TB

Hello,

When I run `nodetool repair` on one of the nodes it fails and starts over. Unfortunately it never ends...

```
wrz 15 07:54:59 ams-scylla1 scylla[2270]:  [shard 76] repair - repair id [id=1, uuid=b8d0515d-f57c-4f3f-a89b-b29ec6a5eb06] on shard 76, keyspace=subscriptions, cf=subscription, range=(-8634870941811091988, -8632021086302250301], got error in row level repair: std::runtime_error (Semaphore timed out: _streaming_concurrency_sem)
wrz 15 07:54:59 ams-scylla1 systemd-journald[1030]: Suppressed 192963 messages from scylla-server.service
wrz 15 07:54:59 ams-scylla1 scylla[2270]:  [shard 76] repair - Repair 30 out of 19344 ranges, id=[id=1, uuid=b8d0515d-f57c-4f3f-a89b-b29ec6a5eb06], shard=76, keyspace=subscriptions, table={subscription, xsolla_purchase_xsolla_subscription_id_idx_index, cache, xsolla_purchase_v2_scylla_cdc_log, xsolla_purchase_v2_xsolla_subscription_id_idx_index, subscription_type, xsolla_purchase_v2, xsolla_purchase_scylla_cdc_log, purchase_periodicity_scylla_cdc_log, google_billing_purchase_scylla_cdc_log, xsolla_purchase, purchase_periodicity, xsolla_purchase_v2_purchase_id_idx_index, xsolla_purchase_v2_transaction_id_idx_index, google_billing_purchase_user_id_idx_index, subscription_subscription_id_idx_index, subscription_purchase_info_idx_index, active_nord_license, subscription_scylla_cdc_log, xsolla_purchase_transaction_id_idx_index, new_nord_license, xsolla_purchase_purchase_id_idx_index, google_billing_purchase, subscription_type_scylla_cdc_log, metric, user_service_data}, range=(-8632021086302250301, -8630942598689683759], peers={10.210.3.42, 10.210.20.84}, live_peers={10.210.3.42, 10.210.20.84}
wrz 15 07:54:59 ams-scylla1 scylla[2270]:  [shard 76] repair - Repair 31 out of 19344 ranges, id=[id=1, uuid=b8d0515d-f57c-4f3f-a89b-b29ec6a5eb06], shard=76, keyspace=subscriptions, table={subscription, xsolla_purchase_xsolla_subscription_id_idx_index, cache, xsolla_purchase_v2_scylla_cdc_log, xsolla_purchase_v2_xsolla_subscription_id_idx_index, subscription_type, xsolla_purchase_v2, xsolla_purchase_scylla_cdc_log, purchase_periodicity_scylla_cdc_log, google_billing_purchase_scylla_cdc_log, xsolla_purchase, purchase_periodicity, xsolla_purchase_v2_purchase_id_idx_index, xsolla_purchase_v2_transaction_id_idx_index, google_billing_purchase_user_id_idx_index, subscription_subscription_id_idx_index, subscription_purchase_info_idx_index, active_nord_license, subscription_scylla_cdc_log, xsolla_purchase_transaction_id_idx_index, new_nord_license, xsolla_purchase_purchase_id_idx_index, google_billing_purchase, subscription_type_scylla_cdc_log, metric, user_service_data}, range=(-8630942598689683759, -8626914489139747315], peers={10.210.3.42, 10.210.20.84}, live_peers={10.210.3.42, 10.210.20.84}
wrz 15 07:55:00 ams-scylla1 scylla[2270]:  [shard 74] repair - repair id [id=1, uuid=b8d0515d-f57c-4f3f-a89b-b29ec6a5eb06] on shard 74, keyspace=subscriptions, cf=subscription, range=(-8634870941811091988, -8632021086302250301], got error in row level repair: std::runtime_error (Semaphore timed out: _streaming_concurrency_sem)
wrz 15 07:55:00 ams-scylla1 scylla[2270]:  [shard 74] repair - Repair 30 out of 19344 ranges, id=[id=1, uuid=b8d0515d-f57c-4f3f-a89b-b29ec6a5eb06], shard=74, keyspace=subscriptions, table={subscription, xsolla_purchase_xsolla_subscription_id_idx_index, cache, xsolla_purchase_v2_scylla_cdc_log, xsolla_purchase_v2_xsolla_subscription_id_idx_index, subscription_type, xsolla_purchase_v2, xsolla_purchase_scylla_cdc_log, purchase_periodicity_scylla_cdc_log, google_billing_purchase_scylla_cdc_log, xsolla_purchase, purchase_periodicity, xsolla_purchase_v2_purchase_id_idx_index, xsolla_purchase_v2_transaction_id_idx_index, google_billing_purchase_user_id_idx_index, subscription_subscription_id_idx_index, subscription_purchase_info_idx_index, active_nord_license, subscription_scylla_cdc_log, xsolla_purchase_transaction_id_idx_index, new_nord_license, xsolla_purchase_purchase_id_idx_index, google_billing_purchase, subscription_type_scylla_cdc_log, metric, user_service_data}, range=(-8632021086302250301, -8630942598689683759], peers={10.210.3.42, 10.210.20.84}, live_peers={10.210.3.42, 10.210.20.84}
wrz 15 07:55:00 ams-scylla1 scylla[2270]:  [shard 74] repair - Repair 31 out of 19344 ranges, id=[id=1, uuid=b8d0515d-f57c-4f3f-a89b-b29ec6a5eb06], shard=74, keyspace=subscriptions, table={subscription, xsolla_purchase_xsolla_subscription_id_idx_index, cache, xsolla_purchase_v2_scylla_cdc_log, xsolla_purchase_v2_xsolla_subscription_id_idx_index, subscription_type, xsolla_purchase_v2, xsolla_purchase_scylla_cdc_log, purchase_periodicity_scylla_cdc_log, google_billing_purchase_scylla_cdc_log, xsolla_purchase, purchase_periodicity, xsolla_purchase_v2_purchase_id_idx_index, xsolla_purchase_v2_transaction_id_idx_index, google_billing_purchase_user_id_idx_index, subscription_subscription_id_idx_index, subscription_purchase_info_idx_index, active_nord_license, subscription_scylla_cdc_log, xsolla_purchase_transaction_id_idx_index, new_nord_license, xsolla_purchase_purchase_id_idx_index, google_billing_purchase, subscription_type_scylla_cdc_log, metric, user_service_data}, range=(-8630942598689683759, -8626914489139747315], peers={10.210.3.42, 10.210.20.84}, live_peers={10.210.3.42, 10.210.20.84}
wrz 15 07:55:00 ams-scylla1 scylla[2270]:  [shard 75] repair - repair id [id=1, uuid=b8d0515d-f57c-4f3f-a89b-b29ec6a5eb06] on shard 75, keyspace=subscriptions, cf=subscription, range=(-8634870941811091988, -8632021086302250301], got error in row level repair: std::runtime_error (Semaphore timed out: _streaming_concurrency_sem)
wrz 15 07:55:00 ams-scylla1 scylla[2270]:  [shard 75] repair - Repair 30 out of 19344 ranges, id=[id=1, uuid=b8d0515d-f57c-4f3f-a89b-b29ec6a5eb06], shard=75, keyspace=subscriptions, table={subscription, xsolla_purchase_xsolla_subscription_id_idx_index, cache, xsolla_purchase_v2_scylla_cdc_log, xsolla_purchase_v2_xsolla_subscription_id_idx_index, subscription_type, xsolla_purchase_v2, xsolla_purchase_scylla_cdc_log, purchase_periodicity_scylla_cdc_log, google_billing_purchase_scylla_cdc_log, xsolla_purchase, purchase_periodicity, xsolla_purchase_v2_purchase_id_idx_index, xsolla_purchase_v2_transaction_id_idx_index, google_billing_purchase_user_id_idx_index, subscription_subscription_id_idx_index, subscription_purchase_info_idx_index, active_nord_license, subscription_scylla_cdc_log, xsolla_purchase_transaction_id_idx_index, new_nord_license, xsolla_purchase_purchase_id_idx_index, google_billing_purchase, subscription_type_scylla_cdc_log, metric, user_service_data}, range=(-8632021086302250301, -8630942598689683759], peers={10.210.3.42, 10.210.20.84}, live_peers={10.210.3.42, 10.210.20.84}
```

**Comment by michoecho** [comment] 2022-09-15 10:47
@denesb Possible duplicate of #11223?

**Comment by avikivity** [comment] 2022-09-15 10:51
Why do we have timeouts on repair reads?

**Comment by denesb** [comment] 2022-09-15 10:53
> Why do we have timeouts on repair reads?

To eventually break never-ending deadlocks -- which sadly do happen.

**Comment by denesb** [comment] 2022-09-15 10:53
> @denesb Possible duplicate of #11223?

Yes, that would be my first guess.

**Comment by denesb** [comment] 2022-09-15 10:55
@r4fek we are in the process of backporting the fixes for a known case of repair getting stuck (#11223). If you need to get repair to work urgently, you can use the private build I provided in [said issue](https://github.com/scylladb/scylladb/issues/11223#issuecomment-1246248493). Otherwise you can wait for 5.0.3 which will have the fix.

**Comment by avikivity** [comment] 2022-09-15 11:01
192963 timeouts?

**Comment by denesb** [comment] 2022-09-15 11:18
> 192963 timeouts?

That does seem excessive. Repair uses concurrency in the low 10s, and even if all these reads time out, it should produce just dozens of messages, not hundreds of thousands.

**Comment by r4fek** [comment] 2022-09-15 12:28
> @r4fek we are in the process of backporting the fixes for a known case of repair getting stuck (#11223). If you need to get repair to work urgently, you can use the private build I provided in [said issue](https://github.com/scylladb/scylladb/issues/11223#issuecomment-1246248493). Otherwise you can wait for 5.0.4 which will have the fix.
> 
> EDIT: 5.0.3 was just released, so the fix will be part of 5.0.4

I will wait for the official version. Thank you!

**Comment by asias** [comment] 2022-09-26 05:59
@benipeled I saw we tagged 5.0.4. When will 5.0.4 be released?

```
commit 1c82766f33b2824c0d278023bc31aee7503e0996
Author: Beni Peled <beni.peled@scylladb.com>
Date:   Wed Sep 21 09:16:13 2022 +0300

    release: prepare for 5.0.4
```

**Comment by asias** [comment] 2022-10-11 09:15
5.0.4 is out. I am closing this issue. If you saw this again please reopen. Thanks for reporting.

**Closed by asias** 2022-10-11 09:15 UTC

**Comment by r4fek** [comment] 2022-10-11 09:18
I confirm that problem no longer exists. Thank you so much!
