### ISSUE TITLE
gemini fails read during replace node operation

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#11059] opened 2022-07-17 15:14 UTC
## Installation details

Kernel Version: 5.15.0-1015-aws
Scylla version (or git commit hash): `5.1.dev-20220714.98aa3ec99b9b` with build-id `e27b38549f89da2f016567fc243c8404a6460ebc`
Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- gemini-1tb-10h-master-oracle-db-node-91804e8a-1 (34.252.85.222 | 10.0.2.42) (shards: 14)
- gemini-1tb-10h-master-db-node-91804e8a-4 (52.215.206.221 | 10.0.2.133) (shards: 14)
- gemini-1tb-10h-master-db-node-91804e8a-3 (52.210.161.198 | 10.0.1.76) (shards: 14)
- gemini-1tb-10h-master-db-node-91804e8a-2 (54.229.160.24 | 10.0.2.117) (shards: 14)
- gemini-1tb-10h-master-db-node-91804e8a-1 (34.251.167.203 | 10.0.1.154) (shards: 14)

OS / Image: `ami-08cbc2649e53039f8` (aws: eu-west-1)

Test: `gemini-1tb-10h`
Test id: `91804e8a-1d5e-4ec9-8388-1a12a6fe9e05`
Test name: `scylla-master/gemini-/gemini-1tb-10h`
Test config file(s):

- [gemini-1tb-10h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d51dc37b36434ecbd5c77214c909cca0dce50e86/test-cases/gemini/gemini-1tb-10h.yaml)

## Issue description

gemini test fails to read while `disrupt_terminate_and_replace_node` nemesis is working 

```json
[{"write_ops": 15581217,
  "write_errors": 0, 
  "read_ops": 33107, 
  "read_errors": 1, 
   "errors": [{"timestamp": "2022-07-15T06:04:15.960544369Z", 
                   "message": "Validation failed: row count differ (test has 0 rows, oracle has 1 rows, test is missing rows: [pk0=19771, \tpk1=29073, \tpk2=-31967, \tck0=1993-02-06 00:00:00 +0000 UTC, \tck1=2011-08-29 23:35:47 +0000 UTC, \tck2=1999-04-02 20:15:08 +0000 UTC], oracle is missing rows: [])", 
                    "query": "SELECT * FROM ks1.table1 WHERE pk0=19771 AND pk1=29073 AND pk2=-31967 "
    }]
}]

```

when new node is added, the ops get dropped:
![image](https://user-images.githubusercontent.com/340979/179404410-8cf3dc70-dc27-4724-a047-0bab1b6c9830.png)

and lot of read timeouts seems to be the cause of gemini not been able to query 
![image](https://user-images.githubusercontent.com/340979/179404596-7f985627-ee9a-4405-be99-b35afb7beb11.png)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 91804e8a-1d5e-4ec9-8388-1a12a6fe9e05`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=91804e8a-1d5e-4ec9-8388-1a12a6fe9e05)
- Show all stored logs command: `$ hydra investigate show-logs 91804e8a-1d5e-4ec9-8388-1a12a6fe9e05`

## Logs:
- **db-cluster-91804e8a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/91804e8a-1d5e-4ec9-8388-1a12a6fe9e05/20220715_063537/db-cluster-91804e8a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/91804e8a-1d5e-4ec9-8388-1a12a6fe9e05/20220715_063537/db-cluster-91804e8a.tar.gz)
- **monitor-set-91804e8a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/91804e8a-1d5e-4ec9-8388-1a12a6fe9e05/20220715_063537/monitor-set-91804e8a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/91804e8a-1d5e-4ec9-8388-1a12a6fe9e05/20220715_063537/monitor-set-91804e8a.tar.gz)
- **loader-set-91804e8a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/91804e8a-1d5e-4ec9-8388-1a12a6fe9e05/20220715_063537/loader-set-91804e8a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/91804e8a-1d5e-4ec9-8388-1a12a6fe9e05/20220715_063537/loader-set-91804e8a.tar.gz)
- **sct-runner-91804e8a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/91804e8a-1d5e-4ec9-8388-1a12a6fe9e05/20220715_063537/sct-runner-91804e8a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/91804e8a-1d5e-4ec9-8388-1a12a6fe9e05/20220715_063537/sct-runner-91804e8a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/166/)

**Comment by slivne** [comment] 2022-07-18 11:17
The drop maybe related to terminating of the node - not to the new node bootstrapping - need to better understand the metrics

**Comment by ShlomiBalalis** [comment] 2022-08-07 15:26
## Installation details

Kernel Version: 5.15.0-1015-aws
Scylla version (or git commit hash): `5.1.0~dev-20220802.663f2e2a8f81` with build-id `d6f523279872624d89a9a451f02d8276f0073cb5`
Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- gemini-1tb-10h-master-oracle-db-node-03f4a62e-1 (13.48.177.95 | 10.0.2.245) (shards: 14)
- gemini-1tb-10h-master-db-node-03f4a62e-4 (16.170.141.179 | 10.0.1.107) (shards: 14)
- gemini-1tb-10h-master-db-node-03f4a62e-3 (13.48.5.43 | 10.0.2.78) (shards: 14)
- gemini-1tb-10h-master-db-node-03f4a62e-2 (13.51.167.148 | 10.0.3.16) (shards: 14)
- gemini-1tb-10h-master-db-node-03f4a62e-1 (16.170.163.204 | 10.0.3.156) (shards: 14)


OS / Image: `ami-0da67a130b28d1222` (aws: eu-north-1)

Test: `gemini-1tb-10h`
Test id: `03f4a62e-5b82-40f8-8a26-591f189b921b`
Test name: `scylla-master/gemini-/gemini-1tb-10h`
Test config file(s):

- [gemini-1tb-10h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5eb7e7241a351a35cd9c1756cd43cc329cb5a873/test-cases/gemini/gemini-1tb-10h.yaml)

## Issue description

Gemini failed again during `disrupt_terminate_and_replace_node` nemesis again:
```
2022-08-05 05:30:44.357: (GeminiStressEvent Severity.ERROR) period_type=end event_id=7cded7aa-e70c-4852-b1c4-33bd589fe29a duration=2h0m22s: node=Node gemini-1tb-10h-master-loader-node-03f4a62e-1 [16.171.47.40 | 10.0.3.158] (seed: False) gemini_cmd=/$HOME/gemini -d --duration 8h --warmup 2h -c 50 -m mixed -f --non-interactive --cql-features normal --max-mutation-retries 5 --max-mutation-retries-backoff 500ms --async-objects-stabilization-attempts 5 --async-objects-stabilization-backoff 500ms --replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '3'}" --oracle-replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '1'}" --test-cluster=10.0.3.156,10.0.3.16,10.0.2.78 --outfile /home/centos/gemini_result_1937d216-9748-4bd5-a990-1f13acb79108.log --seed 57 --oracle-cluster=10.0.2.245
result=Exit code: 1
Command output: ['{"L":"INFO","T":"2022-08-05T05:30:43.852Z","M":"result channel closed"}', 'gemini encountered errors, exiting with non zero status']
errors=['Command error: Error: gemini encountered errors, exiting with non zero status\n\n']

2022-08-05 05:44:19.814: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=efa104c4-88b1-4163-82d7-7219b7304610, source=GeminiTest.test_load_random_with_nemesis (gemini_test.GeminiTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 68, in test_load_random_with_nemesis
self.verify_results()
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 127, in verify_results
self.fail(self.gemini_results['results'])
AssertionError: [{'write_ops': 5827566, 'write_errors': 0, 'read_ops': 4, 'read_errors': 1, 'errors': [{'timestamp': '2022-08-05T05:30:35.001313205Z', 'message': 'Validation failed: unable to load check data from the test store: system failed: gocql: expected 6 values send got 5', 'query': 'SELECT * FROM ks1.table1_mv_0 WHERE col6= AND pk0= AND pk1=-21347 AND pk2=-47 AND pk3=1443963375 AND pk4=? '}]}]
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 03f4a62e-5b82-40f8-8a26-591f189b921b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=03f4a62e-5b82-40f8-8a26-591f189b921b)
- Show all stored logs command: `$ hydra investigate show-logs 03f4a62e-5b82-40f8-8a26-591f189b921b`

## Logs:
- **db-cluster-03f4a62e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/03f4a62e-5b82-40f8-8a26-591f189b921b/20220805_055233/db-cluster-03f4a62e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/03f4a62e-5b82-40f8-8a26-591f189b921b/20220805_055233/db-cluster-03f4a62e.tar.gz)
- **monitor-set-03f4a62e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/03f4a62e-5b82-40f8-8a26-591f189b921b/20220805_055233/monitor-set-03f4a62e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/03f4a62e-5b82-40f8-8a26-591f189b921b/20220805_055233/monitor-set-03f4a62e.tar.gz)
- **loader-set-03f4a62e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/03f4a62e-5b82-40f8-8a26-591f189b921b/20220805_055233/loader-set-03f4a62e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/03f4a62e-5b82-40f8-8a26-591f189b921b/20220805_055233/loader-set-03f4a62e.tar.gz)
- **sct-runner-03f4a62e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/03f4a62e-5b82-40f8-8a26-591f189b921b/20220805_055233/sct-runner-03f4a62e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/03f4a62e-5b82-40f8-8a26-591f189b921b/20220805_055233/sct-runner-03f4a62e.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/170/)

**Comment by ShlomiBalalis** [comment] 2022-08-14 08:30
The issue was reproduced again this week, during `disrupt_terminate_and_replace_node`:
## Installation details

Kernel Version: 5.15.0-1017-aws
Scylla version (or git commit hash): `5.2.0~dev-20220809.3ffc978166ab` with build-id `7da4f902c8209ca890ba8338dbf376529fb6c2fe`
Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- gemini-1tb-10h-master-oracle-db-node-5b257738-1 (13.48.138.82 | 10.0.1.239) (shards: 14)
- gemini-1tb-10h-master-db-node-5b257738-4 (16.170.158.78 | 10.0.1.246) (shards: 14)
- gemini-1tb-10h-master-db-node-5b257738-3 (16.170.98.146 | 10.0.2.23) (shards: 14)
- gemini-1tb-10h-master-db-node-5b257738-2 (13.50.4.167 | 10.0.1.41) (shards: 14)
- gemini-1tb-10h-master-db-node-5b257738-1 (13.51.238.125 | 10.0.0.94) (shards: 14)


OS / Image: `ami-0786ef2aeb8f93c28` (aws: eu-north-1)

Test: `gemini-1tb-10h`
Test id: `5b257738-b914-4813-9482-c41547785b67`
Test name: `scylla-master/gemini-/gemini-1tb-10h`
Test config file(s):

- [gemini-1tb-10h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/97672913680e75c9cfcfbf2b11ec1edd8d14e600/test-cases/gemini/gemini-1tb-10h.yaml)

## Issue description

```
2022-08-12 05:30:53.248: (GeminiStressEvent Severity.ERROR) period_type=end event_id=ead41932-a09c-4d41-8c84-6a78bf996854 duration=2h0m13s: node=Node gemini-1tb-10h-master-loader-node-5b257738-1 [13.51.165.238 | 10.0.3.167] (seed: False) gemini_cmd=/$HOME/gemini -d --duration 8h --warmup 2h -c 50 -m mixed -f --non-interactive --cql-features normal --max-mutation-retries 5 --max-mutation-retries-backoff 500ms --async-objects-stabilization-attempts 5 --async-objects-stabilization-backoff 500ms --replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '3'}" --oracle-replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '1'}" --test-cluster=10.0.0.94,10.0.1.41,10.0.2.23 --outfile /home/centos/gemini_result_de72aa1d-b5f1-4398-af8e-dfb70ca9ae72.log --seed 27 --oracle-cluster=10.0.1.239
result=Exit code: 1
Command output: ['{"L":"INFO","T":"2022-08-12T05:30:52.738Z","M":"result channel closed"}', 'gemini encountered errors, exiting with non zero status']
errors=['Command error: Error: gemini encountered errors, exiting with non zero status\n\n']

2022-08-12 05:43:17.764: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=5f5ebea4-e09b-40c6-9b16-adb1aed0df76, source=GeminiTest.test_load_random_with_nemesis (gemini_test.GeminiTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 68, in test_load_random_with_nemesis
self.verify_results()
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 127, in verify_results
self.fail(self.gemini_results['results'])
AssertionError: [{'write_ops': 10353771, 'write_errors': 0, 'read_ops': 102, 'read_errors': 1, 'errors': [{'timestamp': '2022-08-12T05:30:50.869173441Z', 'message': 'Validation failed: unable to load check data from the test store: system failed: gocql: expected 5 values send got 4', 'query': "SELECT * FROM ks1.table1_mv_0 WHERE col9='%!s(int8=-1)' AND pk0=-10 AND pk1=1158642570 AND pk2=6112013876733036057 AND pk3=? "}]}]
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5b257738-b914-4813-9482-c41547785b67`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5b257738-b914-4813-9482-c41547785b67)
- Show all stored logs command: `$ hydra investigate show-logs 5b257738-b914-4813-9482-c41547785b67`

## Logs:
- **db-cluster-5b257738.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5b257738-b914-4813-9482-c41547785b67/20220812_054834/db-cluster-5b257738.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5b257738-b914-4813-9482-c41547785b67/20220812_054834/db-cluster-5b257738.tar.gz)
- **monitor-set-5b257738.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5b257738-b914-4813-9482-c41547785b67/20220812_054834/monitor-set-5b257738.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5b257738-b914-4813-9482-c41547785b67/20220812_054834/monitor-set-5b257738.tar.gz)
- **loader-set-5b257738.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5b257738-b914-4813-9482-c41547785b67/20220812_054834/loader-set-5b257738.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5b257738-b914-4813-9482-c41547785b67/20220812_054834/loader-set-5b257738.tar.gz)
- **sct-runner-5b257738.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5b257738-b914-4813-9482-c41547785b67/20220812_054834/sct-runner-5b257738.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5b257738-b914-4813-9482-c41547785b67/20220812_054834/sct-runner-5b257738.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/171/)

**Comment by slivne** [comment] 2022-10-06 10:59
In the example above there was drop in traffic in the terminate phase

![Screenshot from 2022-10-06 13-39-21](https://user-images.githubusercontent.com/3465480/194293007-18074e4e-0d8d-4563-b439-da4c32a2e096.png)


The error on the read maybe real - yet is hard to extract data via metrics.

I don't think we will be able to make progress in this manner - we need to be able to catch a cluster that has this issue and then debug it on the cluster. 

Disable read_repair_chance attributes (multiple properties) - and then try to see if we can see the issue on the nodes by having some replicas out of sync / data incorrect.

**Comment by roydahan** [comment] 2022-10-19 11:29
We need to run a reproducer with the same nemesis_seed and gemini_seed.
Set the cluster to "keep" and run the test again.

However, it will be good to have someone from dev assigned as well, so we won't start looking for assignee when the cluster is waiting alive.

**Comment by roydahan** [comment] 2022-10-30 17:50
@aleksbykov please try to find a consistent reproducer as I suggested above.

**Comment by DoronArazii** [comment] 2022-11-28 11:25
@aleksbykov ping ^^

**Comment by DoronArazii** [comment] 2023-03-01 12:22
Removing Master/Triage until we will have a reproducer.

**Comment by aleksbykov** [comment] 2023-06-13 16:47
Creating reproducer: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/gemini-1tb-repo/3. Same seed for gemini and nemesis. Running for latest master

**Comment by aleksbykov** [comment] 2023-06-27 07:59
Original issue was not reproduced with latest master using the same seeds( nemesis and gemini) and latest gemini version.
Also several runs failed because gemini could not load data from oracle. After increase timeout for getting data from MV/SI and number of attempts and increasing number of oracle nodes from 1 to 3 fix the issue. 
Latset run with only Terminate and replace operations cause coredump. Investigating that and will be opened new issue.

**Comment by aleksbykov** [comment] 2023-06-28 11:29
Open new issue: https://github.com/scylladb/scylladb/issues/14434

**Comment by temichus** [comment] 2023-07-19 10:01
@fruch,  Could you please check @aleksbykov conclusion and leave a comment or close the issue

**Closed** 2023-07-19 13:21 UTC
Labels: missing_information, Pending-QA-Reproduction
