### ISSUE TITLE
Caveats to look out for when using nfs for scylladb 4.4.8 docker (it works on nfs for data folder)

### ISSUE THREAD

**Issue by hiqsociety** [scylladb/scylladb#16185] opened 2023-11-26 01:43 UTC
is there any issues i need to be looking out for using NFS v4.1 with intr and hard option?

can anyone give a heads up on this issue?

1. will data be corrupted?
2. how can i stress test scylladb etc? is there a stress test tool? just want to see if i will break on nfs storage

**Comment by mykaul** [comment] 2023-11-26 07:36
Seems like a duplicate of https://github.com/scylladb/scylladb/issues/16069 - please do not open additional issues in this specific area. NFS is not supported and was not tested. There are no short term plans to do either.
If you do need distributed storage, it probably should be block.

**Closed** 2023-11-26 07:36 UTC

**Comment by nyh** [comment] 2023-11-26 09:08
@hiqsociety beyond the fact that this is the fifth issue opened on the NFS issue (see https://github.com/scylladb/scylladb/issues/16069, https://github.com/scylladb/scylladb/issues/16024, https://github.com/scylladb/seastar/issues/1947, https://github.com/scylladb/seastar/issues/1951), this issue isn't even a bug or an issue, but you're asking questions - the bug tracker isn't the place for that. Please try the Scylla developer mailing list (scylladb-dev at groups.google.com) or alternatively - ScyllaDB's forum or slack channels.

For a quick way to stress-test Scylladb or Cassandra, please look up cassandra-stress or YCSB.

**Comment by mykaul** [comment] 2023-11-26 13:52
We use https://forum.scylladb.com/ for discussions.

**Comment by hiqsociety** [comment] 2023-12-18 11:37
@mykaul hi, can you please elaborate this line?

```
If you do need distributed storage, it probably should be block.
```

do you mean block storage stuff like cephfs or something?

**Comment by mykaul** [comment] 2023-12-18 13:33
> @mykaul hi, can you please elaborate this line?
> 
> ```
> If you do need distributed storage, it probably should be block.
> ```
> 
> do you mean block storage stuff like cephfs or something?

CephFS is distributed *file* storage. RBD is an example.
