### ISSUE TITLE
nodetool  rebuild fails with: service::raft_operation_timeout_error

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#18959] opened 2024-05-29 10:40 UTC
## Packages

Scylla version: `6.1.0~dev-20240523.9adf74ae6c7a` with build-id `0e61ad9ecb33913aa59e185d2453859c9ed0fd1a`

Kernel Version: `5.15.0-1062-aws`

## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

Running nemesis of destroy_data_then_rebuild:
delete some sstables:
```
< t:2024-05-25 07:44:07,983 f:nemesis.py      l:1839 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: >>>>>>>>>>>>>Started random_disrupt_method destroy_data_then_rebuild
< t:2024-05-25 07:44:07,983 f:nemesis.py      l:1137 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> DestroyDataThenRebuild
< t:2024-05-25 07:44:07,983 f:nemesis.py      l:406  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Current Target: Node multi-dc-rackaware-master-db-node-e3a7a5e2-5 [18.130.216.25 | 10.3.2.57] (dc name: eu-we
st-2, rack: RACK0) with running nemesis: DestroyDataThenRebuild
< t:2024-05-25 07:44:55,958 f:nemesis.py      l:5092 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Start disruption at `2024-05-25 07:44:55.958964`
< t:2024-05-25 07:44:57,551 f:nemesis.py      l:1094 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Chosen tables: ['scylla_bench.test', 'keyspace1.standard1']
...
< t:2024-05-25 07:46:49,991 f:nemesis.py      l:1107 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: SStables amount to destroy (50 percent of all SStables): 143

```
running nodetool rebuild on multi-dc-rackaware-master-db-node-e3a7a5e2-5

found a raft error (in the middle of standard node compactions:
```
May 25 07:49:13.073409 multi-dc-rackaware-master-db-node-e3a7a5e2-5 scylla[8272]:  [shard 3:comp] compaction - [Compact keyspace1.standard1 419fcfb0-1a6b-11ef-a394-bbfeb0c053c8] Compacted 2 
sstables to [/var/lib/scylla/data/keyspace1/standard1-650b2e801a6711efaa8f87595897da37/md-3ggf_0lpr_3y3qo2hjy0ei2rbutk-big-Data.db:level=0]. 703MB to 669MB (~95% of original) in 9408ms = 74M
B/s. ~134144 total partitions merged to 127444.
```
```
May 25 07:49:17.169409 multi-dc-rackaware-master-db-node-e3a7a5e2-5 scylla[8272]:  [shard 0:strm] raft_group_registry - group [e456fd61-1a65-11ef-b651-2a3881cd993d] raft operation [add_entry
] timed out; timeout requested at [service/storage_service.cc(4545:113) `future<> service::storage_service::raft_rebuild(sstring)`], original error raft::request_aborted (Request is aborted 
by a caller)
```
```
May 25 07:49:17.293725 multi-dc-rackaware-master-db-node-e3a7a5e2-5 scylla[8272]:  [shard 0:strm] compaction - [Split keyspace1.standard1 2521ce10-1a6b-11ef-9ff9-bc04b0c053c8] Split 1 sstabl
es to [/var/lib/scylla/data/keyspace1/standard1-650b2e801a6711efaa8f87595897da37/md-3ggf_0lof_53wdc2fkvwi0t17w7c-big-Data.db:level=0,/var/lib/scylla/data/keyspace1/standard1-650b2e801a6711ef
aa8f87595897da37/md-3ggf_0lp7_1vau82fkvwi0t17w7c-big-Data.db:level=0]. 599MB to 599MB (~100% of original) in 61432ms = 9MB/s. ~114432 total partitions merged to 114347.
```
SCT error report:
```
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_destroy_data_then_rebuild of <sdcm.nemesis.Sisyph
usMonkey object at 0x7fc9120d1d20>> < t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_destroy_data_
then_rebuild of <sdcm.nemesis.SisyphusMonkey object at 0x7fc9120d1d20>>
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5117, in wrapper
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     result = method(*args[1:], **kwargs)
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1148, in disrupt_destroy_data_then_rebuild
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     self.repair_nodetool_rebuild()
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1926, in repair_nodetool_rebuild
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     self.target_node.run_nodetool('rebuild', retry=0)
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2612, in run_nodetool
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     result = _run()
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 65, in inner
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     return func(*args, **kwargs)
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     result = connection.run(**command_kwargs)
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     raise UnexpectedExit(result)
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > 
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > Command: '/usr/bin/nodetool  rebuild '
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > 
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > Exit code: 4
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > 
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > 
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > 
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > 
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > Stderr:
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > 
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > error executing POST request to http://localhost:10000/storage_service/rebuild with parameters {}: remote replied with status code 500 Internal Server Error:
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > service::raft_operation_timeout_error (group [e456fd61-1a65-11ef-b651-2a3881cd993d] raft operation [add_entry] timed out)
< t:2024-05-25 07:49:17,965 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > 
< t:2024-05-25 07:49:17,966 f:nemesis.py      l:5153 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: DestroyDataThenRebuild duration -> 262 s
```
```
disrupt_destroy_data_then_rebuild	multi-dc-rackaware-master-db-node-e3a7a5e2-5	Failed	2024-05-25 07:44:55	2024-05-25 07:49:18
Nemesis Information
Class: Sisyphus
Name: disrupt_destroy_data_then_rebuild
Status: Failed
Failure reason
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5117, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1148, in disrupt_destroy_data_then_rebuild
    self.repair_nodetool_rebuild()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1926, in repair_nodetool_rebuild
    self.target_node.run_nodetool('rebuild', retry=0)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2612, in run_nodetool
    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 65, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: '/usr/bin/nodetool  rebuild '

Exit code: 4

Stdout:



Stderr:

error executing POST request to http://localhost:10000/storage_service/rebuild with parameters {}: remote replied with status code 500 Internal Server Error:
service::raft_operation_timeout_error (group [e456fd61-1a65-11ef-b651-2a3881cd993d] raft operation [add_entry] timed out)
```
## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 8 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- multi-dc-rackaware-master-db-node-e3a7a5e2-9 (3.252.125.57 | 10.4.2.63) (shards: 7)
- multi-dc-rackaware-master-db-node-e3a7a5e2-8 (3.8.115.3 | 10.3.2.149) (shards: 7)
- multi-dc-rackaware-master-db-node-e3a7a5e2-7 (18.171.57.6 | 10.3.2.48) (shards: 7)
- multi-dc-rackaware-master-db-node-e3a7a5e2-6 (52.56.116.155 | 10.3.3.113) (shards: 7)
- multi-dc-rackaware-master-db-node-e3a7a5e2-5 (18.130.216.25 | 10.3.2.57) (shards: 7)
- multi-dc-rackaware-master-db-node-e3a7a5e2-4 (3.249.245.92 | 10.4.2.37) (shards: 7)
- multi-dc-rackaware-master-db-node-e3a7a5e2-3 (34.242.88.177 | 10.4.3.69) (shards: 7)
- multi-dc-rackaware-master-db-node-e3a7a5e2-2 (3.253.44.149 | 10.4.3.112) (shards: 7)
- multi-dc-rackaware-master-db-node-e3a7a5e2-1 (54.246.3.0 | 10.4.0.177) (shards: 7)

OS / Image: `ami-0927fb8b03edc430c ami-0870ab15d5ff48f36` (aws: undefined_region)

Test: `longevity-multidc-multirack-test`
Test id: `e3a7a5e2-1721-4742-9035-c2dca86f99a8`
Test name: `scylla-master/tablets/longevity-multidc-multirack-test`
Test config file(s):

- [longevity-multi-dc-rack-aware.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fe35c3ad1f54bd1df2de8f082c388f7851d7fdfc/test-cases/longevity/longevity-multi-dc-rack-aware.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor e3a7a5e2-1721-4742-9035-c2dca86f99a8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e3a7a5e2-1721-4742-9035-c2dca86f99a8)
- Show all stored logs command: `$ hydra investigate show-logs e3a7a5e2-1721-4742-9035-c2dca86f99a8`

## Logs:
- **db-cluster-e3a7a5e2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e3a7a5e2-1721-4742-9035-c2dca86f99a8/20240525_210520/db-cluster-e3a7a5e2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e3a7a5e2-1721-4742-9035-c2dca86f99a8/20240525_210520/db-cluster-e3a7a5e2.tar.gz)
- **sct-runner-events-e3a7a5e2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e3a7a5e2-1721-4742-9035-c2dca86f99a8/20240525_210520/sct-runner-events-e3a7a5e2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e3a7a5e2-1721-4742-9035-c2dca86f99a8/20240525_210520/sct-runner-events-e3a7a5e2.tar.gz)
- **sct-e3a7a5e2.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e3a7a5e2-1721-4742-9035-c2dca86f99a8/20240525_210520/sct-e3a7a5e2.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e3a7a5e2-1721-4742-9035-c2dca86f99a8/20240525_210520/sct-e3a7a5e2.log.tar.gz)
- **loader-set-e3a7a5e2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e3a7a5e2-1721-4742-9035-c2dca86f99a8/20240525_210520/loader-set-e3a7a5e2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e3a7a5e2-1721-4742-9035-c2dca86f99a8/20240525_210520/loader-set-e3a7a5e2.tar.gz)
- **monitor-set-e3a7a5e2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e3a7a5e2-1721-4742-9035-c2dca86f99a8/20240525_210520/monitor-set-e3a7a5e2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e3a7a5e2-1721-4742-9035-c2dca86f99a8/20240525_210520/monitor-set-e3a7a5e2.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tablets/job/longevity-multidc-multirack-test/19/)
[Argus](https://argus.scylladb.com/test/9e86af6a-44d4-4ed5-bd21-54129cbbe91e/runs?additionalRuns[]=e3a7a5e2-1721-4742-9035-c2dca86f99a8)
</details>

**Comment by mykaul** [comment] 2024-05-29 10:44
@yarongilor - can you ensure it's not a dup of https://github.com/scylladb/scylladb/issues/18933 ?

**Comment by yarongilor** [comment] 2024-05-29 12:27
> @yarongilor - can you ensure it's not a dup of #18933 ?

@mykaul , i cannot ensure that since, although it's the same nodetool command, the test scenario and the raft errors are different.
It did have some similar raft messages like:
```
< t:2024-05-25 07:45:02,554 f:db_log_reader.py l:123  c:sdcm.db_log_reader   p:DEBUG > 2024-05-25T07:45:02.462+00:00 multi-dc-rackaware-master-db-node-e3a7a5e2-1     !INFO | scylla[6830]:  [shard 0:main] raft_group_registry - marking Raft server ff5cd4a7-432e-4005-9460-49f91996571c as dead for raft groups
< t:2024-05-25 07:45:02,668 f:db_log_reader.py l:123  c:sdcm.db_log_reader   p:DEBUG > 2024-05-25T07:45:02.629+00:00 multi-dc-rackaware-master-db-node-e3a7a5e2-7     !INFO | scylla[6891]:  [shard 0:main] raft_group_registry - marking Raft server ff5cd4a7-432e-4005-9460-49f91996571c as dead for raft groups
< t:2024-05-25 07:45:02,742 f:db_log_reader.py l:123  c:sdcm.db_log_reader   p:DEBUG > 2024-05-25T07:45:02.666+00:00 multi-dc-rackaware-master-db-node-e3a7a5e2-8     !INFO | scylla[6902]:  [shard 0:main] raft_group_registry - marking Raft server ff5cd4a7-432e-4005-9460-49f91996571c as dead for raft groups
```

**Comment by mykaul** [comment] 2024-06-02 11:07
@kbr-scylla - please assign it to someone to take a look.

**Comment by kbr-scylla** [comment] 2024-06-11 09:09
@yarongilor does this reproduce on latest `master` (with 34cf5c81f6b879fe6bf3918d0ed9e8a73176363d) or `6.0` (with 45ff4d2c412ce2d8644d2b1b9421204929b40bad)?

**Comment by yarongilor** [comment] 2024-06-13 08:48
> @yarongilor does this reproduce on latest `master` (with [34cf5c8](https://github.com/scylladb/scylladb/commit/34cf5c81f6b879fe6bf3918d0ed9e8a73176363d)) or `6.0` (with [45ff4d2](https://github.com/scylladb/scylladb/commit/45ff4d2c412ce2d8644d2b1b9421204929b40bad))?

[retesting..](https://jenkins.scylladb.com/job/scylla-master/job/tablets/job/longevity-multidc-multirack-test/21/)

**Comment by yarongilor** [comment] 2024-06-19 11:33
> > @yarongilor does this reproduce on latest `master` (with [34cf5c8](https://github.com/scylladb/scylladb/commit/34cf5c81f6b879fe6bf3918d0ed9e8a73176363d)) or `6.0` (with [45ff4d2](https://github.com/scylladb/scylladb/commit/45ff4d2c412ce2d8644d2b1b9421204929b40bad))?
> 
> [retesting..](https://jenkins.scylladb.com/job/scylla-master/job/tablets/job/longevity-multidc-multirack-test/21/)

[retesting v2](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/reproductions/5/)

**Comment by yarongilor** [comment] 2024-06-19 12:25
> > > @yarongilor does this reproduce on latest `master` (with [34cf5c8](https://github.com/scylladb/scylladb/commit/34cf5c81f6b879fe6bf3918d0ed9e8a73176363d)) or `6.0` (with [45ff4d2](https://github.com/scylladb/scylladb/commit/45ff4d2c412ce2d8644d2b1b9421204929b40bad))?
> > 
> > 
> > [retesting..](https://jenkins.scylladb.com/job/scylla-master/job/tablets/job/longevity-multidc-multirack-test/21/)
> 
> [retesting v2](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/reproductions/5/)

@kbr-scylla , i rerun the test with only this SCT specific nemesis, called `CorruptThenRebuildMonkey`.
The 2 first times of nodetool-rebuild by nemesis passed ok.
Then, in the 3rd time, there was an error of:
```
node=multi-dc-rackaware-test-nod-db-node-36a011c0-6 2024-06-19T12:11:55.426+00:00 multi-dc-rackaware-test-nod-db-node-36a011c0-6 !ERR | scylla[6696]: [shard 0:strm] storage_service - Failed to complete splitting of table 45651670-2e32-11ef-9016-dc913ef4348c due to raft::request_aborted (Request is aborted by a caller), retrying after 5000ms seconds
```
And then the nodetool rebuild error is reproduced:
```
(DisruptionEvent Severity.ERROR) period_type=end event_id=003aa51f-214e-4f1d-88a7-c84671f717c0 duration=4m10s: nemesis_name=DestroyDataThenRebuild target_node=Node multi-dc-rackaware-test-nod-db-node-36a011c0-6 [18.170.54.110 | 10.3.2.154] (dc name: eu-west-2, rack: RACK1) errors=Encountered a bad command exit code! Command: '/usr/bin/nodetool rebuild ' Exit code: 4 Stdout: Stderr: error executing POST request to http://localhost:10000/storage_service/rebuild with parameters {}: remote replied with status code 500 Internal Server Error: service::raft_operation_timeout_error (group [b9de5b81-2e30-11ef-a68e-4141a41b715c] raft operation [add_entry] timed out) Traceback (most recent call last): File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5116, in wrapper result = method(*args[1:], **kwargs) File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1149, in disrupt_destroy_data_then_rebuild self.repair_nodetool_rebuild() File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1927, in repair_nodetool_rebuild self.target_node.run_nodetool('rebuild', retry=0) File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2613, in run_nodetool self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry) File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run result = _run() File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 65, in inner return func(*args, **kwargs) File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers) File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute result = connection.run(**command_kwargs) File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr) File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run raise UnexpectedExit(result) sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code! Command: '/usr/bin/nodetool rebuild ' Exit code: 4 Stdout: Stderr: error executing POST request to http://localhost:10000/storage_service/rebuild with parameters {}: remote replied with status code 500 Internal Server Error: service::raft_operation_timeout_error (group [b9de5b81-2e30-11ef-a68e-4141a41b715c] raft operation [add_entry] timed out)
```
So i left the test to continue running at the moment. See [monitor](http://34.247.184.230:3000/d/edp8xg8shifi8f/79bffd56-e9c4-5b01-a95d-ec282de7e94d?orgId=1).

**Comment by kbr-scylla** [comment] 2024-07-01 08:28
Let's wait until the suspected root cause of https://github.com/scylladb/scylladb/issues/19105 is fixed and then retest this

**Comment by kbr-scylla** [comment] 2024-07-19 16:54
@yarongilor please retest

**Comment by yarongilor** [comment] 2024-07-21 07:33
> @yarongilor please retest

[retesting](https://argus.scylladb.com/test/dfa0a7dd-68a5-4a6c-8d9c-a1131811fdbe/runs?additionalRuns[]=196cd9ce-7321-40c1-b025-294b72e16cbc)

**Comment by kbr-scylla** [comment] 2024-07-22 08:59
> @kbr-scylla , the nodetool rebuild command failure is not reproduced.

Great! Closing the issue.
Apparently scylladb/scylladb#19469 fixed it. (cc @raphaelsc )

> One different c-s error found is:

@yarongilor Can you please open a new issue about that?

**Closed by kbr-scylla** 2024-07-22 08:59 UTC
