### ISSUE TITLE
[dtest] test_add_new_node_while_add_new_table_after_bootstrapping

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#15333] opened 2023-09-10 07:00 UTC
Test is missing data after writing to 4 node cluster:
```
self = <update_cluster_layout_tests.TestUpdateClusterLayout object at 0x7fb77c9b3810>

    def test_add_new_node_while_add_new_table_after_bootstrapping(self):
>       self._add_new_node_while_add_new_table("after")

update_cluster_layout_tests.py:1525: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <update_cluster_layout_tests.TestUpdateClusterLayout object at 0x7fb77c9b3810>
when = 'after'

    def _add_new_node_while_add_new_table(self, when):
        """
        Test bootstrapped node get data in the new table
        1. Create a cluster with a three nodes with rf=1, insert data
        2. Add node, while node is bootstrapping add new table and insert data
        4. Check that node was connected and the cluster returns all data inserted
        """
        cluster = self.cluster
        rf = 1
        consistency = {1: ConsistencyLevel.ONE, 2: ConsistencyLevel.TWO}[rf]
    
        # Disable hinted handoff and set batch commit log so this doesn't
        # interfer with the test (this must be after the populate)
        cluster.set_configuration_options(
            values=self.default_config_options(), batch_commitlog=True)
        cluster.populate(3).start()
        node1 = cluster.nodelist()[0]
    
        session = self.patient_cql_connection(node1)
        create_ks(session, 'ks', rf)
        create_cf(session, 'cf', read_repair=0.0, columns={'c1': 'text', 'c2': 'text'})
    
        insert_c1c2(session, keys=range(4000), consistency=consistency)
    
        def run():
            create_ks(session, 'ks1', rf)
            create_cf(session, 'cf1', read_repair=0.0, columns={'c1': 'text', 'c2': 'text'})
            for i in range(0, 1000):
                insert = SimpleStatement("insert into ks1.cf1 (key,c1,c2) values ('%d','%d','%d')" % (i, i, i),
                                         consistency_level=consistency)
                session.execute(insert)
    
        executor = ThreadPoolExecutor(max_workers=1)
    
        # Create table and insert data before bootstrapping of the new node
        if when == "before":
            t = executor.submit(run)
    
        node4 = new_node(cluster)
        node4.start(jvm_args=['--logger-log-level', 'stream_session=debug'], no_wait=True)
        self.wait_for_node_streaming(node4)
    
        # Create table and insert data during bootstrapping of the new node
        if when == "during":
            t = executor.submit(run)
    
        node4.watch_log_for("Starting listening for CQL clients")
        session = self.patient_cql_connection(node4)
    
        # Create table and insert data after bootstrapping of the new node
        if when == "after":
            t = executor.submit(run)
    
        t.result()
        query = SimpleStatement("SELECT * FROM ks1.cf1", consistency_level=consistency)
        result = list(session.execute(query))
>       assert len(result) == 1000, "should have 1000 items in table"
E       AssertionError: should have 1000 items in table
E       assert 799 == 1000
E        +  where 799 = len([Row(key='631', c1='631', c2='631'), Row(key='403', c1='403', c2='403'), Row(key='492', c1='492', c2='492'), Row(key='517', c1='517', c2='517'), Row(key='789', c1='789', c2='789'), Row(key='947', c1='947', c2='947'), ...])

update_cluster_layout_tests.py:1515: AssertionError
```

first time this happens

### Logs

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4355/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/FullDtest___full_split006___test_add_new_node_while_add_new_table_after_bootstrapping/

**Comment by fruch** [comment] 2023-09-10 07:05
@asias I wonder how we didn't see this one fails much more, we are writing and reading with cl=ONE ...

**Comment by mykaul** [comment] 2023-09-10 12:55
Looks like a test issue, no?

**Comment by fruch** [comment] 2023-09-10 13:03
> Looks like a test issue, no?

maybe, but this test dates to 2016, and we don't have a record of it ever failing like this...

**Comment by mykaul** [comment] 2023-09-13 11:20
@asias - can you please take a look?

**Comment by asias** [comment] 2023-09-13 11:24
Sure. I will take a look.

**Comment by asias** [comment] 2023-09-14 01:06
I tried to reproduce.  I saw the following dtest complaint:

```
$ sh run.pytest.sh 

pytest -vs --keep-test-dir --cassandra-dir=/home/asias/src/cloudius-systems/scylla/build/my update_cluster_layout_tests.py::TestUpdateClusterLayout::test_add_new_node_while_add_new_table_after_bootstrapping


java: no process found
Traceback (most recent call last):
  File "/home/asias/.local/bin/pytest", line 8, in <module>
    sys.exit(console_main())
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
           ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.11/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1075, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1305, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/usr/local/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/usr/local/lib/python3.11/site-packages/pytest_html/plugin.py", line 9, in <module>
    from .html_report import HTMLReport
  File "/usr/local/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/usr/local/lib/python3.11/site-packages/pytest_html/html_report.py", line 11, in <module>
    from py.xml import html
ModuleNotFoundError: No module named 'py.xml'; 'py' is not a package
```

I tried both dtest 5.3 and master branch. I am on fedora 38.

**Comment by asias** [comment] 2023-09-14 01:08
We are running scylla version:

```

Scylla version 5.4.0~dev-0.20230908.8bff5843b528 with build-id 09be6f5c939dc30d5fa506ba9e1a94a228cb7be4 starting ...
command used: "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kq2pnrde/test/node1/bin/scylla --options-file /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kq2pnrde/test/node1/conf/scylla.yaml --log-to-stdout 1 --abort-on-seastar-bad-alloc --abort-on-lsa-bad-alloc 1 --abort-on-internal-error 1 --api-address 127.0.4.1 --collectd-hostname ip-10-0-4-194.ec2.internal.node1 --smp 2 --memory 1024M --developer-mode true --default-log-level info --collectd 0 --overprovisioned --prometheus-address 127.0.4.1 --unsafe-bypass-fsync 1 --kernel-page-cache 1 --commitlog-use-o-dsync 0 --max-networking-io-control-blocks 1000"
parsed command line options: [options-file: /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kq2pnrde/test/node1/conf/scylla.yaml, log-to-stdout, (positional) 1, abort-on-seastar-bad-alloc, abort-on-lsa-bad-alloc: 1, abort-on-internal-error: 1, api-address: 127.0.4.1, collectd-hostname, (positional) ip-10-0-4-194.ec2.internal.node1, smp, (positional) 2, memory, (positional) 1024M, developer-mode: true, default-log-level, (positional) info, collectd, (positional) 0, overprovisioned, prometheus-address: 127.0.4.1, unsafe-bypass-fsync, (positional) 1, kernel-page-cache, (positional) 1, commitlog-use-o-dsync: 0, max-networking-io-control-blocks, (positional) 1000]
```


What is the dtest commit used?

**Comment by fruch** [comment] 2023-09-14 06:20
> We are running scylla version:
> 
> ```
> 
> Scylla version 5.4.0~dev-0.20230908.8bff5843b528 with build-id 09be6f5c939dc30d5fa506ba9e1a94a228cb7be4 starting ...
> command used: "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kq2pnrde/test/node1/bin/scylla --options-file /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kq2pnrde/test/node1/conf/scylla.yaml --log-to-stdout 1 --abort-on-seastar-bad-alloc --abort-on-lsa-bad-alloc 1 --abort-on-internal-error 1 --api-address 127.0.4.1 --collectd-hostname ip-10-0-4-194.ec2.internal.node1 --smp 2 --memory 1024M --developer-mode true --default-log-level info --collectd 0 --overprovisioned --prometheus-address 127.0.4.1 --unsafe-bypass-fsync 1 --kernel-page-cache 1 --commitlog-use-o-dsync 0 --max-networking-io-control-blocks 1000"
> parsed command line options: [options-file: /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kq2pnrde/test/node1/conf/scylla.yaml, log-to-stdout, (positional) 1, abort-on-seastar-bad-alloc, abort-on-lsa-bad-alloc: 1, abort-on-internal-error: 1, api-address: 127.0.4.1, collectd-hostname, (positional) ip-10-0-4-194.ec2.internal.node1, smp, (positional) 2, memory, (positional) 1024M, developer-mode: true, default-log-level, (positional) info, collectd, (positional) 0, overprovisioned, prometheus-address: 127.0.4.1, unsafe-bypass-fsync, (positional) 1, kernel-page-cache, (positional) 1, commitlog-use-o-dsync: 0, max-networking-io-control-blocks, (positional) 1000]
> ```
> 
> What is the dtest commit used?

commit scylladb/scylla-dtest@db1b598cde4f482924770931cb3644d3b02a347c
Author: Israel Fruchter <fruch@scylladb.com>
Date:   Fri Sep 8 00:50:59 2023 +0300

    cqlsh_tests/cqlsh_tests: expect correct default compaction strategy
    
    PR #3548 introduced back `test_describe` which has hardcoded
    the assumption regrding compaction strategy of MVs and INDEXs
    since the default of enterprise is `IncrementalCompactionStrategy`
    this test we broken.
    
    in this change we introduce `self.default_compaction_strategy`
    that can be use across the tests in `TestCqlsh`

**Comment by mykaul** [comment] 2023-09-14 06:55
Sounds like a pytest issue to me. Indeed I think running in virtualenv might help.

**Comment by asias** [comment] 2023-09-14 12:08
I have been running dtest natively since forever.  It is sad I have to use virtualenv now. But anyway,  I can run with no problem using virtualenv. 

The test passes locally so far:

update_cluster_layout_tests.py::TestUpdateClusterLayout::test_add_new_node_while_add_new_table_after_bootstrapping PASSED

**Comment by fruch** [comment] 2023-09-14 12:25
> I have been running dtest natively since forever.  It is sad I have to use virtualenv now. But anyway,  I can run with no problem using virtualenv. 

I guess you can still do that, but you are on your own figuring which system package is in compatible with other packages dtest needs.

> 
> The test passes locally so far:
> 
> update_cluster_layout_tests.py::TestUpdateClusterLayout::test_add_new_node_while_add_new_table_after_bootstrapping PASSED
> 

Not surprising, almost all open issues around tests now are with instability, not with 100% reproducible issues.

**Comment by asias** [comment] 2023-09-15 00:38
> > I have been running dtest natively since forever.  It is sad I have to use virtualenv now. But anyway,  I can run with no problem using virtualenv.
> 
> I guess you can still do that, but you are on your own figuring which system package is in compatible with other packages dtest needs.
> 
> > The test passes locally so far:
> > update_cluster_layout_tests.py::TestUpdateClusterLayout::test_add_new_node_while_add_new_table_after_bootstrapping PASSED
> 
> Not surprising, almost all open issues around tests now are with instability, not with 100% reproducible issues.

I am not surprised too much neither. I had multiple runs trying to reproduce with no luck.

**Comment by mykaul** [comment] 2023-09-26 13:04
@fruch - shall we close it (and re-open if we see it again) ?

**Comment by fruch** [comment] 2023-09-26 13:41
I can confirm it's only been spotted once,

closing until it happens again

**Comment by fruch** [comment] 2023-09-28 16:14
happened again on next 
https://jenkins.scylladb.com/job/scylla-master/job/next/6590/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_add_new_node_while_add_new_table_after_bootstrapping/

@asias any ideas on where it might be coming from ? or what can be adding to have more information next time it fails ?

**Comment by mykaul** [comment] 2023-11-22 11:23
@fruch - after 2 months almost, I think we can close it?

**Comment by fruch** [comment] 2023-11-22 11:39
didn't happened since Sep 28:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/a8b94fe0-892b-11ee-bf28-5927cc3d3ce3

**Comment by pwrobelse** [comment] 2024-01-10 16:42
Hello,

It seems, that the the test failure happened again with similar logs to the original issue.

```
>       assert len(result) == 1000, "should have 1000 items in table"
E       AssertionError: should have 1000 items in table
E       assert 800 == 1000
```

Link to the logs:
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5672/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_add_new_node_while_add_new_table_after_bootstrapping/

**Comment by bhalevy** [comment] 2024-01-10 16:44
Reopening, we need to get to the bottom of it

**Comment by kostja** [comment] 2024-03-08 13:14
@temichus please extend the test with a sync - make sure other nodes notice this node has started before executing DDL. watch_log_for() used in the test is race-prone. And then we'll see if the test is still falky.

**Comment by temichus** [comment] 2024-03-31 11:32
I've created PR https://github.com/scylladb/scylla-dtest/pull/4124 with waiting other nodes notice this node has started before executing DDL. watch_log_for()

**Comment by temichus** [comment] 2024-04-17 12:53
for the last 2 weeks not failures with this issue in Eclastic. Close issue

cc @kostja  @fruch

**Closed by temichus** 2024-04-17 12:53 UTC
Labels: tests/dtest, triage/master, symptom/ci stability
