### ISSUE TITLE
Large collections are not recorded in system.large_cells

### ISSUE THREAD

**Issue by Mark-Gurevich** [scylladb/scylladb#13590] opened 2023-04-20 09:12 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): Scylla version 5.3.0~dev-0.20230417.c501163f955e with build-id 07cfea1bc38ee632328349d10316fc5d8cdaa35a
Cluster size: dtest
OS

According to this documentation (https://github.com/scylladb/scylladb/commit/20bad62562268bed1a78a0f0466c62359565f0c0)
I've done two tests:
### Test 1 (log level large_data=debug)
1. Create a collection with 10001 elements (a list).
2. Check the system.large_cells and logs for warnings

### Result:
Nothing in system.large_cells and no warnings in logs

### Test 2
1. Change the "compaction_collection_elements_count_warning_threshold" parameter and check if it has any effect.
2. Same steps as in test 1.
 
### Result:
Nothing in system.large_cells and no warnings in logs
Both tests failed.

**Comment by mykaul** [comment] 2023-04-20 09:20
@Mark-Gurevich , 
Please share the test code, so developers can run as well.

**Comment by Mark-Gurevich** [comment] 2023-04-20 09:36
I've tested this half manually.
Here is a draft-PR for basic flow.
https://github.com/scylladb/scylla-dtest/pull/3129

**Comment by nyh** [comment] 2023-04-20 11:23
I think this is a duplicate of #11449.

**Comment by nyh** [comment] 2023-04-20 11:25
Hmm, to clarify, it's a duplicate of an already-fixed issue - so maybe we didn't fix this properly? Or what's going on?

**Comment by mykaul** [comment] 2023-04-20 11:26
> I think this is a duplicate of #11449.

I thought the issue is that #11449 is not working as expected?

**Comment by Mark-Gurevich** [comment] 2023-05-10 10:43
This issue should be closed as invalid.
The feature is covered by test_too_many_collection_elements test
In this [PR](https://github.com/scylladb/scylla-dtest/pull/3154) I've added parametrization for lists and sets in addition to maps.

**Closed** 2023-05-10 11:14 UTC
