### ISSUE TITLE
Scylla may hang on shutdown with raft enabled (Operation timed out for system_distributed.service_levels )

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13925] opened 2023-05-17 14:51 UTC
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release-with-raft/142/artifact/logs-full.release.002/1684294642998_paxos_tests.py%3A%3ATestPaxos%3A%3Atest_topology_change_in_presence_of_down_node/node1.log
(I don't known if it's a recent regression or whether it was already hit in the past)
```
Scylla version 5.3.0~dev-0.20230517.9b0679c140bb with build-id 08ff81aefd3c307b44eb5a6bf260f8f3924bcb57 starting ...
...
INFO  2023-05-17 03:35:14,963 [shard 0] compaction_manager - Asked to stop
INFO  2023-05-17 03:35:14,963 [shard 0] init - Signal received; shutting down
INFO  2023-05-17 03:35:14,963 [shard 0] init - Shutting down view builder ops
INFO  2023-05-17 03:35:14,963 [shard 0] view - Draining view builder
INFO  2023-05-17 03:35:14,963 [shard 0] compaction_manager - Stopped
INFO  2023-05-17 03:35:14,963 [shard 1] compaction_manager - Asked to stop
INFO  2023-05-17 03:35:14,963 [shard 1] view - Draining view builder
INFO  2023-05-17 03:35:14,964 [shard 1] compaction_manager - Stopped
WARN  2023-05-17 03:35:14,964 [shard 0] gossip - failure_detector_loop: Got error in the loop, live_nodes={127.0.52.3, 127.0.52.7, 127.0.52.2}: seastar::sleep_aborted (Sleep is aborted)
INFO  2023-05-17 03:35:14,964 [shard 0] gossip - failure_detector_loop: Finished main loop
INFO  2023-05-17 03:35:14,964 [shard 0] init - Shutting down view builder ops was successful
INFO  2023-05-17 03:35:14,964 [shard 0] init - Shutting down local storage
INFO  2023-05-17 03:35:14,964 [shard 0] storage_service - Stop transport: starts
INFO  2023-05-17 03:35:14,964 [shard 0] migration_manager - stopping migration service
INFO  2023-05-17 03:35:14,964 [shard 1] migration_manager - stopping migration service
INFO  2023-05-17 03:35:14,964 [shard 0] storage_service - Shutting down native transport server
INFO  2023-05-17 03:35:14,965 [shard 0] cql_server_controller - CQL server stopped
INFO  2023-05-17 03:35:14,965 [shard 0] storage_service - Shutting down native transport server was successful
INFO  2023-05-17 03:35:14,965 [shard 0] storage_service - Shutting down rpc server
INFO  2023-05-17 03:35:14,965 [shard 0] storage_service - Shutting down rpc server was successful
INFO  2023-05-17 03:35:14,965 [shard 0] storage_service - Shutting down alternator server
INFO  2023-05-17 03:35:14,965 [shard 0] storage_service - Shutting down alternator server was successful
INFO  2023-05-17 03:35:14,965 [shard 0] storage_service - Shutting down redis server
INFO  2023-05-17 03:35:14,965 [shard 0] storage_service - Shutting down redis server was successful
INFO  2023-05-17 03:35:14,965 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2023-05-17 03:35:14,965 [shard 0] gossip - My status = NORMAL
INFO  2023-05-17 03:35:14,965 [shard 0] gossip - Announcing shutdown
INFO  2023-05-17 03:35:14,966 [shard 0] storage_service - Node 127.0.52.1 state jump to normal
INFO  2023-05-17 03:35:14,980 [shard 0] rpc - client 127.0.52.2:52490 msg_id 1497:  exception "gate closed" in no_wait handler ignored
INFO  2023-05-17 03:35:14,980 [shard 0] rpc - client 127.0.52.3:53546 msg_id 1291:  exception "gate closed" in no_wait handler ignored
INFO  2023-05-17 03:35:14,985 [shard 0] gossip - Sending a GossipShutdown to 127.0.52.3 with generation 1684293561
INFO  2023-05-17 03:35:14,985 [shard 0] gossip - Sending a GossipShutdown to 127.0.52.7 with generation 1684293561
INFO  2023-05-17 03:35:14,985 [shard 0] gossip - Sending a GossipShutdown to 127.0.52.2 with generation 1684293561
INFO  2023-05-17 03:35:15,425 [shard 0] rpc - client 127.0.52.3:53546 msg_id 1292:  exception "gate closed" in no_wait handler ignored
INFO  2023-05-17 03:35:16,985 [shard 0] gossip - Disable and wait for gossip loop started
INFO  2023-05-17 03:35:16,985 [shard 0] gossip - Gossip is now stopped
INFO  2023-05-17 03:35:16,985 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping nontls server
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping tls server
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping tls server - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.6:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.6:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.4:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.4:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.7:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.7:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.3:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.3:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.5:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.5:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.2:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.2:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.6:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.6:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.4:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.4:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.3:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.3:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.5:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.5:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.2:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.2:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.3:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.3:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.2:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.2:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.1:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.2:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.2:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.3:0
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.3:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 1] messaging_service - Stopping nontls server
INFO  2023-05-17 03:35:16,985 [shard 1] messaging_service - Stopping tls server
INFO  2023-05-17 03:35:16,985 [shard 1] messaging_service - Stopping tls server - Done
INFO  2023-05-17 03:35:16,985 [shard 0] messaging_service - Stopping client for address: 127.0.52.1:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 1] messaging_service - Stopping client for address: 127.0.52.3:0
INFO  2023-05-17 03:35:16,985 [shard 1] messaging_service - Stopping client for address: 127.0.52.3:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 1] messaging_service - Stopping client for address: 127.0.52.2:0
INFO  2023-05-17 03:35:16,985 [shard 1] messaging_service - Stopping client for address: 127.0.52.2:0 - Done
INFO  2023-05-17 03:35:16,985 [shard 1] messaging_service - Stopping nontls server - Done
INFO  2023-05-17 03:35:17,796 [shard 0] raft_group_registry - marking Raft server 90f83ec7-3008-4b98-b22f-0725adf1c720 as dead for raft groups
INFO  2023-05-17 03:35:17,798 [shard 0] raft_group_registry - marking Raft server 0224ee71-3c26-47f6-813d-72d2c14b9f1f as dead for raft groups
INFO  2023-05-17 03:35:17,805 [shard 0] raft_group_registry - marking Raft server 63273ff8-95fc-4382-956d-d29173d29376 as dead for raft groups
WARN  2023-05-17 03:36:51,497 [shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  720 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)
```

Coredump in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release-with-raft/142/artifact/logs-full.release.002/1684294642998_paxos_tests.py%3A%3ATestPaxos%3A%3Atest_topology_change_in_presence_of_down_node/node1-scylla.1143.1684294641.core.gz
Reloc package in http://downloads.scylladb.com/unstable/scylla/master/relocatable/2023-05-17T03:03:59Z/scylla-unstripped-5.3.0~dev-0.20230517.9b0679c140bb.x86_64.tar.gz

**Comment by DoronArazii** [comment] 2023-08-10 14:53
It's in progress under Eliran's wings, we also tracking it in our daily meeting.
Removing 'master/triage'.

**Comment by mykaul** [comment] 2023-08-10 14:55
> It's in progress under Eliran's wings, we also tracking it in our daily meeting. Removing 'master/triage'.

Note that there was no movement in this GH issue since May.

**Comment by bhalevy** [comment] 2023-08-14 04:49
Although this didn't seem to reproduce I think we ought to at least investigate the core dump before removing the triage label

**Comment by DoronArazii** [comment] 2023-08-14 10:38
@eliransin please update on the progress (ambarella of label 'shutdown').

**Comment by mykaul** [comment] 2023-10-26 12:56
> I don't think the warning is the cause but an indication. It is a query that keeps failing while the shutdown is in progress (for more than 720 seconds...). Don't have any concrete update on this. Will resume work on shutdown.

@eliransin - any updates?

**Comment by nyh** [comment] 2024-02-25 09:16
https://github.com/scylladb/scylladb/issues/17293 may be (?) a duplicate of this issue.

**Closed** 2024-04-17 16:49 UTC
Labels: area/workload prioritization, symptom/shutdown, area/service levels
