### ISSUE TITLE
cdc generation update_streams_description needs to handle errors from background loop

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11195] opened 2022-08-03 07:25 UTC
update_streams_description runs a loop in the background here:
https://github.com/scylladb/scylladb/blob/a4844826fcc7a845a03a1c927a5bfe3d57c09901/cdc/generation.cc#L452-L468

It says that it is safe for it to discard the loop function's future, but still it needs to handle it if it fails, even if to log and ignore it.
Otherwise, seastar complains like this: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/25/artifact/logs-full.debug.041/1659425645362_repair_additional_test.py%3A%3ATestRepairAdditional%3A%3Atest_repair_during_update/node1.log
```
INFO  2022-08-02 07:33:42,309 [shard 0] compaction_manager - Asked to stop
WARN  2022-08-02 07:33:42,310 [shard 0] seastar - Exceptional future ignored: seastar::sleep_aborted (Sleep is aborted), backtrace: 0x143919d0 0x1c6ac2fd 0x1c6abfbd 0x1c6ae5b3 0x1c6af442 0x1b6bf229 0x144f1375 0x144f12e4 0x145838d4 0x14a0a9d3 0x16485ac4 0x14a3f24d 0x14a3f028 0x1b85092e 0x1b856d9e 0x1b85ba02 0x1b859571 0x1b5fa6a1 0x1b5f8205 0x14428344 0x14912bf6 0x14912b2b 0x14912995 0x144ee25d 0x14426b21 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/663f2e2a8f81b57ba3934a79a21c20d011677b17/scylla/libreloc/libc.so.6+0x27b74 0x14345aad
```

Decoded:
```
[Backtrace #0]
__interceptor_backtrace.part.0 at crtstuff.c:?
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_3>(seastar::current_backtrace_tasklocal()::$_3&&) at ./build/debug/seastar/./seastar/include/seastar/util/backtrace.hh:59
seastar::current_backtrace_tasklocal() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:137
seastar::current_backtrace() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:170
seastar::report_failed_future(std::__exception_ptr::exception_ptr const&) at ./build/debug/seastar/./seastar/src/core/future.cc:210
void seastar::internal::promise_base::set_exception_impl<std::__exception_ptr::exception_ptr>(std::__exception_ptr::exception_ptr&&) at ././seastar/include/seastar/core/future.hh:865
seastar::internal::promise_base::set_exception(std::__exception_ptr::exception_ptr&&) at ././seastar/include/seastar/core/future.hh:874
seastar::promise<void>::set_exception(std::__exception_ptr::exception_ptr&&) at ././seastar/include/seastar/core/future.hh:1036
seastar::internal::coroutine_traits_base<void>::promise_type::unhandled_exception() at ././seastar/include/seastar/core/coroutine.hh:108
operator() at ./cdc/generation.cc:453
std::experimental::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at ././seastar/include/seastar/core/std-coroutine.hh:70
seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:120
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/debug/seastar/./seastar/src/core/reactor.cc:2345
seastar::reactor::run_some_tasks() at ./build/debug/seastar/./seastar/src/core/reactor.cc:2752
seastar::reactor::do_run() at ./build/debug/seastar/./seastar/src/core/reactor.cc:2921
seastar::reactor::run() at ./build/debug/seastar/./seastar/src/core/reactor.cc:2804
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/debug/seastar/./seastar/src/core/app-template.cc:265
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/debug/seastar/./seastar/src/core/app-template.cc:156
scylla_main(int, char**) at ./main.cc:540
int std::__invoke_impl<int, int (*&)(int, char**), int, char**>(std::__invoke_other, int (*&)(int, char**), int&&, char**&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
std::enable_if<is_invocable_r_v<int, int (*&)(int, char**), int, char**>, int>::type std::__invoke_r<int, int (*&)(int, char**), int, char**>(int (*&)(int, char**), int&&, char**&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:114
std::_Function_handler<int (int, char**), int (*)(int, char**)>::_M_invoke(std::_Any_data const&, int&&, char**&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
std::function<int (int, char**)>::operator()(int, char**) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
main at ./main.cc:1659
```

**Comment by bhalevy** [comment] 2022-08-03 07:25
Cc @kbr-

**Comment by kbr-** [comment] 2022-08-03 10:35
Duplicate of https://github.com/scylladb/scylladb/issues/11192

**Closed** 2022-08-03 10:38 UTC
