### ISSUE TITLE
TestMaterializedViews.test_base_replica_repair: AssertionError: Expected [[0, 0, 'a', 3.0]] from SELECT * FROM t_by_v WHERE v = 0, but got []

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#19148] opened 2024-06-06 14:36 UTC
LOGS_LINK
[logs-full.release.006](https://jenkins.scylladb.com/job/scylla-master/job/tablets/job/dtest-release-with-tablets/9/artifact/logs-full.release.006)
SPLIT_NAME
full.release.006
Error Message
AssertionError: Expected [[0, 0, 'a', 3.0]] from SELECT * FROM t_by_v WHERE v = 0, but got []

Stacktrace
```
self = <materialized_views_test.TestMaterializedViews object at 0x7fe807a55430>

    def test_base_replica_repair(self):
>       self._base_replica_repair_test()

materialized_views_test.py:3160: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
materialized_views_test.py:3238: in _base_replica_repair_test
    assert_one(session, f"SELECT * FROM t_by_v WHERE v = {i}", [i, i, "a", 3.0])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

session = <cassandra.cluster.Session object at 0x7fe807ae2cf0>
query = 'SELECT * FROM t_by_v WHERE v = 0', expected = [0, 0, 'a', 3.0]
cl = None

    def assert_one(session, query, expected, cl=None):
        """
        Assert query returns one row.
        @param session Session to use
        @param query Query to run
        @param expected Expected results from query
        @param cl Optional Consistency Level setting. Default ONE
    
        Examples:
        assert_one(session, "LIST USERS", ['cassandra', True])
        assert_one(session, query, [0, 0])
        """
        simple_query = SimpleStatement(query, consistency_level=cl)
        res = session.execute(simple_query)
        list_res = _rows_to_list(res)
>       assert list_res == [expected], f"Expected {[expected]} from {query}, but got {list_res}"
E       AssertionError: Expected [[0, 0, 'a', 3.0]] from SELECT * FROM t_by_v WHERE v = 0, but got []

tools/assertions.py:146: AssertionError
```

logs:
[logs-full.release.006.zip](https://github.com/user-attachments/files/15637606/logs-full.release.006.zip)

the issue might be related to https://github.com/scylladb/scylladb/issues/19146

**Comment by nyh** [comment] 2024-06-09 20:20
This test runs repair on the base table, and immediately when it finishes assumes the view table is already updated. But I think recently (I'm not sure... @raphaelsc ? @bhalevy ?) we made the view update happen asynchronously **after** the repair has already returned. If this is true, it breaks this test.

If I'm misremembering and this aspect of repair hasn't changed recently, my next question is: Is this failure just with tablets?
If so, maybe this failure is related to the fact that with tablets, N=RF=3 no longer guarantees "self pairing", and specifically for this test, it no longer guarantees **synchronous view updates**. The test writes 1000 rows to the base table with a view, writes with CL=ALL, but does NOT wait for the view updates (which with vnodes were synchronous because N=RF=3, but with tablets are asynchronous). I think this might cause some data to be lost but I am not sure about the details and will need to think about this some more.

**Comment by raphaelsc** [comment] 2024-06-13 20:02
this issue is missing important info. is it with tablet enabled? enterprise or OSS? if it's with tablet enabled only, the root cause can be https://github.com/scylladb/scylladb/issues/19149. it's known that migration is not transferring properly the view update backlog created by repair. @nyh It's true that we relaxed the backpressure in view update generator (maybe we didn't apply that patch by @asias? have to check), but that's only about setting a limit on the backlog of view updates done asynchronously in the generator (the asynchronicity in this path never changed AFAICT). apparently it's a tablet test, so might be indeed https://github.com/scylladb/scylladb/issues/19149.

**Comment by bhalevy** [comment] 2024-06-14 01:13
@yarongilor if the issue is with tablets, please label respectively.

**Comment by bhalevy** [comment] 2024-06-16 05:05
Also, how is this different from https://github.com/scylladb/scylladb/issues/19146?

**Comment by yarongilor** [comment] 2024-06-17 09:21
> @yarongilor if the issue is with tablets, please label respectively.

retesting without tablets..

**Comment by bhalevy** [comment] 2024-07-14 16:20
> This test runs repair on the base table, and immediately when it finishes assumes the view table is already updated. But I think recently (I'm not sure... @raphaelsc ? @bhalevy ?) we made the view update happen asynchronously **after** the repair has already returned. If this is true, it breaks this test.
> 
> If I'm misremembering and this aspect of repair hasn't changed recently, my next question is: Is this failure just with tablets? If so, maybe this failure is related to the fact that with tablets, N=RF=3 no longer guarantees "self pairing", and specifically for this test, it no longer guarantees **synchronous view updates**. The test writes 1000 rows to the base table with a view, writes with CL=ALL, but does NOT wait for the view updates (which with vnodes were synchronous because N=RF=3, but with tablets are asynchronous). I think this might cause some data to be lost but I am not sure about the details and will need to think about this some more.

I opened https://github.com/scylladb/scylladb/issues/19727 for the need to wait on view update generation when repairing the base table.

In the meanwhile, we can probably wait for it in dtest, as a workaround.

**Comment by mykaul** [comment] 2024-07-16 10:49
@yarongilor - are you adding the delay in dtest (as @bhalevy wrote above) ?

**Comment by yarongilor** [comment] 2024-07-16 12:17
> @yarongilor - are you adding the delay in dtest (as @bhalevy wrote above) ?

it should be addressed in https://github.com/scylladb/scylla-dtest/pull/4592

**Comment by bhalevy** [comment] 2024-07-20 21:11
happens also with cl=QUORUM...
https://jenkins.scylladb.com/view/master/job/scylla-master/job/tablets/job/gating-dtest-release-with-tablets/130/testReport/secondary_indexes_test/TestSecondaryIndexes/FullDtest___full_split003___test_remove_node_during_index_build/
```
self = <secondary_indexes_test.TestSecondaryIndexes object at 0x7f2d5bf96660>

    @pytest.mark.dtest_heavy
    def test_remove_node_during_index_build(self):
        """
        Remove one node during index building and read data by index
        """
>       self._node_action_during_index_build(node_action="remove", nodes=4, rf=3, num_rows=100000)

secondary_indexes_test.py:1369: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
secondary_indexes_test.py:1436: in _node_action_during_index_build
    assert_row_count_in_select(session=session, query=f"SELECT * FROM {view_name}", num_rows_expected=num_rows, consistency_level=ConsistencyLevel.QUORUM)
tools/retrying.py:51: in inner
    return func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

session = <cassandra.cluster.Session object at 0x7f2d4169b5c0>
query = 'SELECT * FROM b_index_index', num_rows_expected = 100000
consistency_level = 4, num_attempts = 1, timeout = None

    @retrying(num_attempts=1, sleep_time=10)
    def assert_row_count_in_select(  # noqa: PLR0913
        session,
        query,
        num_rows_expected,
        consistency_level=ConsistencyLevel.ONE,
        num_attempts=1,
        timeout=None,
    ):
        """
        Function to validate the row count are returned by select
        :param num_attempts: defines how many time try to assert data in case failure. Used in retrying decorator
        """
        from tools.data import get_list_res  # to avoid cyclic dependency
    
        count = len(get_list_res(session, query, consistency_level, timeout=timeout))
>       assert count == num_rows_expected, f'Expected a row count of {num_rows_expected} in query "{query}", but got {count}'
E       AssertionError: Expected a row count of 100000 in query "SELECT * FROM b_index_index", but got 99273

tools/assertions.py:518: AssertionError
```

**Comment by pehala** [comment] 2024-09-02 13:21
Is this a product bug or a test issue? It seemed to be addressed in dtest already, but it doesnt seem like it was the cause.

**Comment by bhalevy** [comment] 2024-09-02 14:43
> Is this a product bug or a test issue? It seemed to be addressed in dtest already, but it doesnt seem like it was the cause.

With https://github.com/scylladb/scylla-dtest/pull/4592 the test should pass reliably.
But the root cause seems to be https://github.com/scylladb/scylladb/issues/19727
If this issue doesn't reproduce anymore we can close it.

But when https://github.com/scylladb/scylladb/issues/19727 is fixed, we should probably revert #4592 (or write a new test that lets scylla schedule the repair of the view automatically after repairing the base table).

**Comment by dani-tweig** [comment] 2024-11-05 09:27
> If this issue doesn't reproduce anymore we can close it.

@bhalevy , can we close this?

**Comment by wmitros** [comment] 2024-11-06 07:11
> > If this issue doesn't reproduce anymore we can close it.
> 
> [@bhalevy](https://github.com/bhalevy) , can we close this?

I don't see any recent failed runs with this, and with https://github.com/scylladb/scylla-dtest/pull/4592 I don't see how this could fail anymore, so I'll close this.

However, with https://github.com/scylladb/scylla-dtest/pull/4592 this test isn't really checking much anymore - after deleting data from one node we repair all tables on it (and we can't really avoid this - with tablets we have to repair both base and view on this node) and no data is missing on other nodes so repair will recover all rows in both base and view - so the the view updates generated during repair don't matter anymore. We're just testing regular table repair now.

If we implement automatic scheduling of view repair when base table is being repaired, as @bhalevy mentioned in https://github.com/scylladb/scylladb/issues/19148#issuecomment-2324908679, we'll be able to remove the view repair initiated by the user but we'll probably add a specific test for that alongside the change so there's probably no need to update this test case

**Closed by wmitros** 2024-11-06 07:11 UTC
Labels: area/materialized views, P1, symptom/ci stability, area/tablets
