### ISSUE TITLE
[Documentation]: create a page about perftune.py

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#13382] opened 2023-03-30 14:20 UTC
We need a page explaining how perftune.py works, how to use it in different situations and how its auto-selection logic works.

**Comment by vladzcloudius** [comment] 2023-03-30 14:20
@annastuchlik FYI

**Comment by annastuchlik** [comment] 2023-07-27 15:11
Duplicate of https://github.com/scylladb/scylladb/issues/14233.

**Closed by annastuchlik** 2023-07-27 15:11 UTC
Labels: Documentation
