### ISSUE TITLE
test_initial_token is flaky

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#20637] opened 2024-09-17 08:29 UTC
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11640/consoleFull

Test timed out after 6 hours:

```
:41:26  _____________________________ test_initial_token.2 _____________________________
05:41:26  
05:41:26  self = <test.pylib.manager_client.ManagerClient object at 0x7f0cb6b7b440>
05:41:26  replace_cfg = None, cmdline = None
05:41:26  config = {'initial_token': '0, 4611686018427387904'}, property_file = None
05:41:26  start = True, expected_error = 'Bootstrap failed. See earlier errors'
05:41:26  seeds = None, timeout = 1000, server_encryption = 'none'
05:41:26  expected_server_up_state = None
05:41:26  
05:41:26      async def server_add(self,
05:41:26                           replace_cfg: Optional[ReplaceConfig] = None,
05:41:26                           cmdline: Optional[List[str]] = None,
05:41:26                           config: Optional[dict[str, Any]] = None,
05:41:26                           property_file: Optional[dict[str, Any]] = None,
05:41:26                           start: bool = True,
05:41:26                           expected_error: Optional[str] = None,
05:41:26                           seeds: Optional[List[IPAddress]] = None,
05:41:26                           timeout: Optional[float] = ScyllaServer.TOPOLOGY_TIMEOUT,
05:41:26                           server_encryption: str = "none",
05:41:26                           expected_server_up_state: Optional[ServerUpState] = None) -> ServerInfo:
05:41:26          """Add a new server"""
05:41:26          try:
05:41:26              data = self._create_server_add_data(
05:41:26                  replace_cfg,
05:41:26                  cmdline,
05:41:26                  config,
05:41:26                  property_file,
05:41:26                  start,
05:41:26                  seeds,
05:41:26                  expected_error,
05:41:26                  server_encryption,
05:41:26                  expected_server_up_state,
05:41:26              )
05:41:26      
05:41:26              # If we replace, we should wait until other nodes see the node being
05:41:26              # replaced as dead because the replace operation can be rejected if
05:41:26              # the node being replaced is considered alive. However, we sometimes
05:41:26              # do not want to wait, for example, when we test that replace fails
05:41:26              # as expected. Therefore, we make waiting optional and default.
05:41:26              if replace_cfg and replace_cfg.wait_replaced_dead:
05:41:26                  replaced_ip = await self.get_host_ip(replace_cfg.replaced_id)
05:41:26                  await self.others_not_see_server(replaced_ip)
05:41:26      
05:41:26  >           server_info = await self.client.put_json("/cluster/addserver", data, response_type="json",
05:41:26                                                       timeout=timeout)
05:41:26  
05:41:26  test/pylib/manager_client.py:351: 
05:41:26  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
05:41:26  test/pylib/rest_client.py:114: in put_json
05:41:26      ret = await self._fetch("PUT", resource_uri, response_type = response_type, host = host,
05:41:26  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
05:41:26  
05:41:26  self = <test.pylib.rest_client.UnixRESTClient object at 0x7f0cb6b79070>
05:41:26  method = 'PUT', resource = '/cluster/addserver', response_type = 'json'
05:41:26  host = None, port = None, params = None
05:41:26  json = {'config': {'initial_token': '0, 4611686018427387904'}, 'expected_error': 'Bootstrap failed. See earlier errors', 'server_encryption': 'none', 'start': True}
05:41:26  timeout = 1000, allow_failed = False
05:41:26  
05:41:26      async def _fetch(self, method: str, resource: str, response_type: Optional[str] = None,
05:41:26                       host: Optional[str] = None, port: Optional[int] = None,
05:41:26                       params: Optional[Mapping[str, str]] = None,
05:41:26                       json: Optional[Mapping] = None, timeout: Optional[float] = None, allow_failed: bool = False) -> Any:
05:41:26          # Can raise exception. See https://docs.aiohttp.org/en/latest/web_exceptions.html
05:41:26          assert method in ["GET", "POST", "PUT", "DELETE"], f"Invalid HTTP request method {method}"
05:41:26          assert response_type is None or response_type in ["text", "json"], \
05:41:26                  f"Invalid response type requested {response_type} (expected 'text' or 'json')"
05:41:26          # Build the URI
05:41:26          port = port if port else self.default_port if hasattr(self, "default_port") else None
05:41:26          port_str = f":{port}" if port else ""
05:41:26          assert host is not None or hasattr(self, "default_host"), "_fetch: missing host for " \
05:41:26                  "{method} {resource}"
05:41:26          host_str = host if host is not None else self.default_host
05:41:26          uri = self.uri_scheme + "://" + host_str + port_str + resource
05:41:26          logging.debug(f"RESTClient fetching {method} {uri}")
05:41:26      
05:41:26          client_timeout = ClientTimeout(total = timeout if timeout is not None else 300)
05:41:26          async with request(method, uri,
05:41:26                             connector = self.connector if hasattr(self, "connector") else None,
05:41:26                             params = params, json = json, timeout = client_timeout) as resp:
05:41:26              if allow_failed:
05:41:26                  return await resp.json()
05:41:26              if resp.status != 200:
05:41:26                  text = await resp.text()
05:41:26  >               raise HTTPError(uri, resp.status, params, json, text)
05:41:26  E               test.pylib.rest_client.HTTPError: HTTP error 500, uri: http+unix://api/cluster/addserver, params: None, json: {'start': True, 'config': {'initial_token': '0, 4611686018427387904'}, 'expected_error': 'Bootstrap failed. See earlier errors', 'server_encryption': 'none'}, body:
05:41:26  E               the node startup failed, but the log file doesn't contain the expected error, server_id 1983, IP 127.86.67.58, workdir scylla-1983, host_id ff14a2ef-8079-4c16-bf4c-a6bc126641ae, the node log was expected to contain the string [Bootstrap failed. See earlier errors]
05:41:26  E               Check the log files:
05:41:26  E               /scylladir/testlog/x86_64/test.py.debug-release-dev.log
05:41:26  E               /scylladir/testlog/x86_64/release/scylla-1983.log
05:41:26  
05:41:26  test/pylib/rest_client.py:72: HTTPError
05:41:26  
05:41:26  The above exception was the direct cause of the following exception:
05:41:26  
05:41:26  manager = <test.pylib.manager_client.ManagerClient object at 0x7f0cb6b7b440>
05:41:26  
05:41:26      @pytest.mark.asyncio
05:41:26      async def test_initial_token(manager: ManagerClient) -> None:
05:41:26          tokens = ["-9223372036854775808", "-4611686018427387904", "0", "4611686018427387904"]
05:41:26          cfg1 = {'initial_token': f"{tokens[0]}, {tokens[1]}"}
05:41:26          cfg2 = {'initial_token': f"{tokens[2]}, {tokens[3]}"}
05:41:26          s1 = await manager.server_add(config=cfg1)
05:41:26          s2 = await manager.server_add(config=cfg2)
05:41:26          cql1 = cluster_con([s1.ip_addr], 9042, False,
05:41:26                              load_balancing_policy=WhiteListRoundRobinPolicy([s1.ip_addr])).connect()
05:41:26          cql2 = cluster_con([s2.ip_addr], 9042, False,
05:41:26                              load_balancing_policy=WhiteListRoundRobinPolicy([s2.ip_addr])).connect()
05:41:26          res1 = cql1.execute("SELECT tokens From system.local").one()
05:41:26          res2 = cql2.execute("SELECT tokens From system.local").one()
05:41:26          assert all([i in res1.tokens for i in tokens[:2]]) and all([i in res2.tokens for i in tokens[-2:]])
05:41:26          # Try to boot a node with conflicting tokens. It should fail.
05:41:26  >       s2 = await manager.server_add(config=cfg2, expected_error="Bootstrap failed. See earlier errors")
05:41:26  
05:41:26  test/topology_custom/test_initial_token.py:35: 
05:41:26  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
05:41:26  
05:41:26  self = <test.pylib.manager_client.ManagerClient object at 0x7f0cb6b7b440>
05:41:26  replace_cfg = None, cmdline = None
05:41:26  config = {'initial_token': '0, 4611686018427387904'}, property_file = None
05:41:26  start = True, expected_error = 'Bootstrap failed. See earlier errors'
05:41:26  seeds = None, timeout = 1000, server_encryption = 'none'
05:41:26  expected_server_up_state = None
05:41:26  
05:41:26      async def server_add(self,
05:41:26                           replace_cfg: Optional[ReplaceConfig] = None,
05:41:26                           cmdline: Optional[List[str]] = None,
05:41:26                           config: Optional[dict[str, Any]] = None,
05:41:26                           property_file: Optional[dict[str, Any]] = None,
05:41:26                           start: bool = True,
05:41:26                           expected_error: Optional[str] = None,
05:41:26                           seeds: Optional[List[IPAddress]] = None,
05:41:26                           timeout: Optional[float] = ScyllaServer.TOPOLOGY_TIMEOUT,
05:41:26                           server_encryption: str = "none",
05:41:26                           expected_server_up_state: Optional[ServerUpState] = None) -> ServerInfo:
05:41:26          """Add a new server"""
05:41:26          try:
05:41:26              data = self._create_server_add_data(
05:41:26                  replace_cfg,
05:41:26                  cmdline,
05:41:26                  config,
05:41:26                  property_file,
05:41:26                  start,
05:41:26                  seeds,
05:41:26                  expected_error,
05:41:26                  server_encryption,
05:41:26                  expected_server_up_state,
05:41:26              )
05:41:26      
05:41:26              # If we replace, we should wait until other nodes see the node being
05:41:26              # replaced as dead because the replace operation can be rejected if
05:41:26              # the node being replaced is considered alive. However, we sometimes
05:41:26              # do not want to wait, for example, when we test that replace fails
05:41:26              # as expected. Therefore, we make waiting optional and default.
05:41:26              if replace_cfg and replace_cfg.wait_replaced_dead:
05:41:26                  replaced_ip = await self.get_host_ip(replace_cfg.replaced_id)
05:41:26                  await self.others_not_see_server(replaced_ip)
05:41:26      
05:41:26              server_info = await self.client.put_json("/cluster/addserver", data, response_type="json",
05:41:26                                                       timeout=timeout)
05:41:26          except Exception as exc:
05:41:26  >           raise Exception("Failed to add server") from exc
05:41:26  E           Exception: Failed to add server
05:41:26  
05:41:26  test/pylib/manager_client.py:354: Exception
```

**Comment by nyh** [comment] 2024-09-17 09:26
From the above messages, It seems the test failed in its last line:
```python
    # Try to boot a node with conflicting tokens. It should fail.
    s2 = await manager.server_add(config=cfg2, expected_error="Bootstrap failed. See earlier errors")
```
The server_add() did fail - as expected - but for some reason the "expected_error" didn't make this fine. I couldn't follow the server_add() code (too many layers of functions and TCP requests) to understand what the heck it does with "expected_error" so the person who wrote this better debug it. CC @gleb-cloudius

**Comment by gleb-cloudius** [comment] 2024-09-17 09:33
Yes. server_add failed all right. It failed because of a crash:

```
Segmentation fault on shard 0, in scheduling group gossip.
Backtrace:
  0x5c86d04
  0x5c44e6b
  0x5c7b3bc
  0x5ad7e7c
  /lib64/libc.so.6+0x40cff
  0x495a543
  0x3f86664
  0x3ec957a
  0x5c54faf
  0x5c5652a
  0x5c57707
  0x5c56ab8
  0x5be6c23
  0x5be5f83
  0x13c45c5
  0x13c5f80
  0x13c29e3
  /lib64/libc.so.6+0x2a087
  /lib64/libc.so.6+0x2a14a 
  0x13c0064
```

Somewhat unexpected.

**Comment by gleb-cloudius** [comment] 2024-09-17 09:49
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:822
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:867
 (inlined by) seastar::sigsegv_action() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3954
 (inlined by) seastar::install_oneshot_signal_handler<11, (void (*)())(&seastar::sigsegv_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3936
 (inlined by) seastar::install_oneshot_signal_handler<11, (void (*)())(&seastar::sigsegv_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3931
wasmtime_runtime::traphandlers::unix::trap_handler at /home/jenkins/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-8.0.1/src/traphandlers/unix.rs:163
?? ??:0
std::__uniq_ptr_impl<raft::fsm, std::default_delete<raft::fsm> >::_M_ptr() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:193
 (inlined by) std::unique_ptr<raft::fsm, std::default_delete<raft::fsm> >::get() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:464
 (inlined by) std::unique_ptr<raft::fsm, std::default_delete<raft::fsm> >::operator->() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:457
 (inlined by) raft::server_impl::get_current_term() const at ././raft/server.cc:1449
 (inlined by) non-virtual thunk to raft::server_impl::get_current_term() const at ././raft/server.cc:?
service::storage_service::raft_topology_cmd_handler(utils::tagged_tagged_integer<raft::internal::non_final, raft::term_tag, unsigned long>, unsigned long, service::raft_topology_cmd const&) at ././service/storage_service.cc:5472
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<service::raft_topology_cmd_result>::promise_type>::resume() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/coroutine:242
 (inlined by) seastar::internal::coroutine_traits_base<service::raft_topology_cmd_result>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:80
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:2577
seastar::reactor::run_some_tasks() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3043
seastar::reactor::do_run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3211
seastar::reactor::run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3101
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:276
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:167
scylla_main(int, char**) at ././main.cc:701
std::function<int (int, char**)>::operator()(int, char**) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591
main at ././main.cc:2283

```

**Comment by kbr-scylla** [comment] 2024-09-23 09:36
Duplicate of https://github.com/scylladb/scylladb/issues/20701

**Closed by kbr-scylla** 2024-09-23 09:36 UTC
Labels: symptom/ci stability
