### ISSUE TITLE
nodetool rebuild fails with exception: get_repair_meta: repair_meta_id X for node Y does not exist

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#7110] opened 2020-08-25 14:27 UTC
*Installation details*
Scylla version (or git commit hash): 4.2.rc3-0.20200820.e931d2867
Build id: 9e2f16fd3eb812c4f12cf1c7b86d23fae9f8e8d1

Split from issue https://github.com/scylladb/scylla/issues/6645 as this error is unrelated to the main issue investigated there (semaphore timeout).

There are two cores, see https://github.com/scylladb/scylla/issues/6645#issuecomment-678953539 and https://github.com/scylladb/scylla/issues/6645#issuecomment-678953790

/cc @asias

**Comment by denesb** [comment] 2020-08-25 14:49
Sadly, as the cores were generated *after* the error message was written to the log, the cores don't contain the information on who and under what circumstances did try to to obtain the non-existent repair-meta.

**Comment by asias** [comment] 2020-08-26 07:22
One theory how this could happen:

node2 is overwhelmed and gossip updates to node1 was delayed
node1 marks node2 as down in gossip and removes all repair instance with node2
node2 recovers and continues to run repair with node1 who has already dropped the repair_meta

**Comment by aleksbykov** [comment] 2020-08-26 09:58
Similar issue happened twice during next job: https://jenkins.scylladb.com/job/scylla-4.2/job/longevity/job/longevity-cdc-100gb-4h-test/37/
db logs available here: https://cloudius-jenkins-test.s3.amazonaws.com/22f2d308-fa1c-4370-9712-34bd4731d862/20200821_113308/db-cluster-22f2d308.zip
monitoring could be restored with hydra investigate show-monitor 22f2d308-fa1c-4370-9712-34bd4731d862
For node6 the nodetool rebuild failed with next errors:
```
Command: 'nodetool  rebuild '
Exit code: 1
Stdout:
nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: std::runtime_error ({shard 0: std::runtime_error (get_repair_meta: repair_meta_id 49580 for node 10.0.2.200 does not exist), shard 1: std::runtime_error (get_repair_meta: repair_meta_id 51474 for node 10.0.2.200 does not exist), shard 2: std::runtime_error (get_repair_meta: repair_meta_id 49628 for node 10.0.2.200 does not exist), shard 3: std::runtime_error (get_repair_meta: repair_meta_id 48804 for node 10.0.2.200 does not exist), shard 4: std::runtime_error (get_repair_meta: repair_meta_id 50605 for node 10.0.2.200 does not exist), shard 5: std::runtime_error (get_repair_meta: repair_meta_id 50528 for node 10.0.2.200 does not exist), shard 6: std::runtime_error (get_repair_meta: repair_meta_id 53835 for node 10.0.2.200 does not exist), shard 7: std::runtime_error (get_repair_meta: repair_meta_id 50177 for node 10.0.2.200 does not exist), shard 8: std::runtime_error (get_repair_meta: repair_meta_id 50073 for node 10.0.2.200 does not exist), shard 9: std::runtime_error (get_repair_meta: repair_meta_id 50427 for node 10.0.2.200 does not exist), shard 10: std::runtime_error (get_repair_meta: repair_meta_id 49225 for node 10.0.2.200 does not exist), shard 11: std::runtime_error (get_repair_meta: repair_meta_id 48690 for node 10.0.2.200 does not exist), shard 12: std::runtime_error (get_repair_meta: repair_meta_id 50444 for node 10.0.2.200 does not exist), shard 13: seastar::rpc::closed_error (connection is closed)})
See 'nodetool help' or 'nodetool help <command>'.
Stderr:
```
and 

```
Command: 'nodetool  rebuild '
Exit code: 1
Stdout:
nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: std::runtime_error ({shard 0: std::runtime_error (repair 1 on shard 0 failed to do checksum for 308 sub ranges), shard 1: std::runtime_error (repair 1 on shard 1 failed to do checksum for 308 sub ranges), shard 2: std::runtime_error (repair 1 on shard 2 failed to do checksum for 308 sub ranges), shard 3: std::runtime_error (repair 1 on shard 3 failed to do checksum for 308 sub ranges), shard 4: std::runtime_error (repair 1 on shard 4 failed to do checksum for 308 sub ranges), shard 5: std::runtime_error (repair 1 on shard 5 failed to do checksum for 308 sub ranges), shard 6: std::runtime_error (repair 1 on shard 6 failed to do checksum for 308 sub ranges), shard 7: std::runtime_error (repair 1 on shard 7 failed to do checksum for 308 sub ranges), shard 8: std::runtime_error (repair 1 on shard 8 failed to do checksum for 308 sub ranges), shard 9: std::runtime_error (repair 1 on shard 9 failed to do checksum for 308 sub ranges), shard 10: std::runtime_error (repair 1 on shard 10 failed to do checksum for 308 sub ranges), shard 11: std::runtime_error (repair 1 on shard 11 failed to do checksum for 308 sub ranges), shard 12: std::runtime_error (repair 1 on shard 12 failed to do checksum for 308 sub ranges), shard 13: std::runtime_error (repair 1 on shard 13 failed to do checksum for 308 sub ranges)})
See 'nodetool help' or 'nodetool help <command>'.
Stderr:
```

**Comment by slivne** [comment] 2020-09-14 10:52
@asias ping we hit this on 4.2 as well - please update

**Comment by asias** [comment] 2020-09-15 02:17
> @asias ping we hit this on 4.2 as well - please update

The root cause is "semaphore timeout issue" which is caused by hinted handoff. We see lots of similar phenomenon recently and the issue is handled here: https://github.com/scylladb/scylla/issues/7025.

**Comment by slivne** [comment] 2020-10-26 14:41
Well 4.2 with HH with regular streaming (without repair_based_operations passed) so something maybe off with repair in this case as well.

**Comment by asias** [comment] 2020-10-27 02:35
> Well 4.2 with HH with regular streaming (without repair_based_operations passed) so something maybe off with repair in this case as well.

Sorry, I can not parse what you meant here.

**Comment by juliayakovlev** [comment] 2020-10-28 13:06
Same issue happened on the master, version ```666.development-0.20201025.c518c1de1 with build-id 9212462fe70187b59afec0322cc758291cf9058a ```
ami: ```ami-0998c746523893a6c```

Test: longevity-cdc-100gb-4h-test

Jenkins [job](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/127/)

CorruptThenRebuild nemesis on the node longevity-cdc-100gb-4h-master-db-node-df4efebd-3 failed:

```
< t:2020-10-26 01:55:51,117 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > Command: 'nodetool  rebuild '
< t:2020-10-26 01:55:51,117 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > 
< t:2020-10-26 01:55:51,117 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > Exit code: 1
< t:2020-10-26 01:55:51,117 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > 
< t:2020-10-26 01:55:51,117 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > Stdout:
< t:2020-10-26 01:55:51,117 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > 
< t:2020-10-26 01:55:51,117 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > Using /etc/scylla/scylla.yaml as the config file
< t:2020-10-26 01:55:51,117 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: std::runtime_error ({shard 0: std::runtime_error (get_repair_meta: repair_meta_id 138300 for node 10.0.2.144 does not exist), shard 1: std::runtime_error (get_repair_meta: repair_meta_id 148821 for node 10.0.2.144 does not exist), shard 3: std::runtime_error (get_repair_meta: repair_meta_id 138255 for node 10.0.2.144 does not exist), shard 4: std::runtime_error (get_repair_meta: repair_meta_id 146320 for node 10.0.2.144 does not exist), shard 6: std::runtime_error (get_repair_meta: repair_meta_id 146339 for node 10.0.2.144 does not exist), shard 7: std::runtime_error (get_repair_meta: repair_meta_id 146371 for node 10.0.2.144 does not exist), shard 8: std::runtime_error (get_repair_meta: repair_meta_id 147054 for node 10.0.2.144 does not exist), shard 9: std::runtime_error (get_repair_meta: repair_meta_id 146421 for node 10.0.2.144 does not exist), shard 11: std::runtime_error (get_repair_meta: repair_meta_id 137077 for node 10.0.2.144 does not exist)})
```

Get SCT logs: https://cloudius-jenkins-test.s3.amazonaws.com/df4efebd-7be3-4a96-ad7e-1a7dda6b23c6/20201026_054321/sct-runner-df4efebd.zip

Get cluster logs: https://cloudius-jenkins-test.s3.amazonaws.com/df4efebd-7be3-4a96-ad7e-1a7dda6b23c6/20201026_054321/db-cluster-df4efebd.zip

Test id: df4efebd-7be3-4a96-ad7e-1a7dda6b23c6

**Comment by aleksbykov** [comment] 2020-11-04 05:42
Scylla version: 4.2.0-0.20201026.94597e38e with build-id c34028ef570d1a9de6914d12c14c415e1cc4b90f
Test: longevity-cdc-100gb-4h-test
Job: https://jenkins.scylladb.com/job/scylla-4.2/job/longevity/job/longevity-cdc-100gb-4h-test/72/

RBO is disabled. Issue reproduced during nemesis CorruptThenRepair(Scylla was stopped, Several sstables were removed, Scylla was started. Command `nodetool repair` executed)
The command `nodetool repair` failed with next error:
```
2020-11-02 21:56:53.770: (DisruptionEvent Severity.ERROR): type=end name=CorruptThenRepair node=Node longevity-cdc-100gb-4h-4-2-db-node-28d508d2-5 [13.48.104.76 | 10.0.0.106] (seed: False) duration=8959 error=Encountered a bad command exit code!

Command: 'nodetool  repair '

Exit code: 2

Stdout:

[2020-11-02 19:30:39,572] Repair session 1 finished
[2020-11-02 19:30:39,609] Starting repair command #2, repairing 1 ranges for keyspace ks_truncate (parallelism=SEQUENTIAL, full=true)
[2020-11-02 19:30:42,730] Repair session 2 
[2020-11-02 19:30:42,737] Repair session 2 finished
[2020-11-02 19:30:42,825] Starting repair command #3, repairing 1 ranges for keyspace keyspace1 (parallelism=SEQUENTIAL, full=true)
[2020-11-02 19:31:07,939] Repair session 3 
[2020-11-02 19:31:07,941] Repair session 3 finished
[2020-11-02 19:31:08,002] Starting repair command #4, repairing 1 ranges for keyspace cdc_test (parallelism=SEQUENTIAL, full=true)
[2020-11-02 21:56:52,929] Repair session 4 failed
[2020-11-02 21:56:52,931] Repair session 4 finished

Stderr:

error: Repair job has failed with the error message: [2020-11-02 21:56:52,929] Repair session 4 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2020-11-02 21:56:52,929] Repair session 4 failed
	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

Error in db.log:
```
2020-11-02T21:56:52+00:00  longevity-cdc-100gb-4h-4-2-db-node-28d508d2-5 !INFO    | scylla: [shard 0] repair - repair id 4 failed: std::runtime_error ({shard 0: std::runtime_error (get_repair_meta: repair_meta_id 144982 for node 10.0.0.106 does not exist), shard 1: std::runtime_error (get_repair_meta: repair_meta_id 144358 for node 10.0.0.106 does not exist), shard 2: std::runtime_error (get_repair_meta: repair_meta_id 144112 for node 10.0.0.106 does not exist), shard 4: std::runtime_error (get_repair_meta: repair_meta_id 143904 for node 10.0.0.106 does not exist), shard 5: std::runtime_error (Failed to repair for keyspace=cdc_test, cf=test_table, range=(8560034184590489323, 8568549812019821560]), shard 6: std::runtime_error (get_repair_meta: repair_meta_id 145046 for node 10.0.0.106 does not exist), shard 8: std::runtime_error (get_repair_meta: repair_meta_id 133363 for node 10.0.0.106 does not exist), shard 10: std::runtime_error (get_repair_meta: repair_meta_id 143444 for node 10.0.0.106 does not exist), shard 11: std::runtime_error (get_repair_meta: repair_meta_id 145290 for node 10.0.0.106 does not exist), shard 13: std::runtime_error (get_repair_meta: repair_meta_id 140469 for node 10.0.0.106 does not exist)})
2020-11-02T21:56:52+00:00  longevity-cdc-100gb-4h-4-2-db-node-28d508d2-5 !INFO    | scylla: [shard 0] repair - repair_tracker run for repair id 4 failed: std::runtime_error ({shard 0: std::runtime_error (get_repair_meta: repair_meta_id 144982 for node 10.0.0.106 does not exist), shard 1: std::runtime_error (get_repair_meta: repair_meta_id 144358 for node 10.0.0.106 does not exist), shard 2: std::runtime_error (get_repair_meta: repair_meta_id 144112 for node 10.0.0.106 does not exist), shard 4: std::runtime_error (get_repair_meta: repair_meta_id 143904 for node 10.0.0.106 does not exist), shard 5: std::runtime_error (Failed to repair for keyspace=cdc_test, cf=test_table, range=(8560034184590489323, 8568549812019821560]), shard 6: std::runtime_error (get_repair_meta: repair_meta_id 145046 for node 10.0.0.106 does not exist), shard 8: std::runtime_error (get_repair_meta: repair_meta_id 133363 for node 10.0.0.106 does not exist), shard 10: std::runtime_error (get_repair_meta: repair_meta_id 143444 for node 10.0.0.106 does not exist), shard 11: std::runtime_error (get_repair_meta: repair_meta_id 145290 for node 10.0.0.106 does not exist), shard 13: std::runtime_error (get_repair_meta: repair_meta_id 140469 for node 10.0.0.106 does not exist)})
```

DB log:
[system.log.tar.gz](https://github.com/scylladb/scylla/files/5485688/system.log.tar.gz)

All logs:
https://cloudius-jenkins-test.s3.amazonaws.com/28d508d2-d32f-42c6-95bf-5fdfd3350352/20201102_221549/db-cluster-28d508d2.zip

**Comment by slivne** [comment] 2020-12-21 10:18
@asias
-  I understand the issue is that one of the repair end points thinks the other is down and thus removes metadata related to the ongoing repair.
- We did not see this issue in the past 
I am moving this to 4.4 as repair based operation are not part of 4.3

**Comment by DoronArazii** [comment] 2022-10-12 08:55
@eliransin / @roydahan i'm closing this case - we can always reopen

**Closed by DoronArazii** 2022-10-12 08:55 UTC
Labels: high, repair-based-operations
