### ISSUE TITLE
united-pacakge: uninstall.sh permission err & nonroot.conf isn't cleaned

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylladb#8480] opened 2021-04-14 04:35 UTC
*Installation details*
Scylla version (or git commit hash): 4.4.rc4-0.20210311.ec20ff098
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS&

Unified package: http://downloads.scylladb.com.s3.amazonaws.com/downloads/scylla/relocatable/scylladb-4.4/scylla-unified-package-4.4.rc4.0.20210311.ec20ff098.tar.gz

#### ERROR 1:

[amos@amos-centos7 scylladb]$ ./uninstall.sh  --nonroot
rm: cannot remove ‘/lib/sysctl.d/99-scylla-aio.conf’: Permission denied
rm: cannot remove ‘/lib/sysctl.d/99-scylla-inotify.conf’: Permission denied
rm: cannot remove ‘/lib/sysctl.d/99-scylla-sched.conf’: Permission denied
rm: cannot remove ‘/lib/sysctl.d/99-scylla-vm.conf’: Permission denied

#### ERROR 2:

rm: cannot remove ‘/home/amos/.config/systemd/user/scylla-server.service.d’: Is a directory

```
[amos@amos-centos7 scylladb]$ sh -x  uninstall.sh --nonroot
+ set -e
++ dirname uninstall.sh
+ cd .
+ root=/
+++ dirname uninstall.sh
++ realpath -m .
+ prefix=/home/amos/scylladb
+ '[' '!' -f /home/amos/scylladb/SCYLLA-OFFLINE-FILE ']'
+ '[' -f /home/amos/scylladb/SCYLLA-NONROOT-FILE ']'
+ nonroot=true
++ realpath -m ///home/amos/scylladb
+ rprefix=/home/amos/scylladb
+ true
+ sysconfdir=/etc/sysconfig
+ retc=/home/amos/scylladb/etc
+ rsysconfdir=/home/amos/scylladb//etc/sysconfig
+ rsystemd=/home/amos/.config/systemd/user
+ rdoc=/home/amos/scylladb/share/doc
+ rdata=/home/amos/scylladb
+ rm -fv /home/amos/.config/systemd/user/scylla-server.service /home/amos/.config/systemd/user/scylla-server.service.d /home/amos/.config/systemd/user/scylla-server.slice /home/amos/.config/systemd/user/scylla-fstrim.service /home/amos/.config/systemd/user/scylla-fstrim.timer /home/amos/.config/systemd/user/scylla-helper.service /home/amos/.config/systemd/user/scylla-housekeeping-daily.service /home/amos/.config/systemd/user/scylla-housekeeping-daily.timer /home/amos/.config/systemd/user/scylla-housekeeping-restart.service /home/amos/.config/systemd/user/scylla-housekeeping-restart.timer /home/amos/.config/systemd/user/node-exporter.service
removed ‘/home/amos/.config/systemd/user/scylla-server.service’
rm: cannot remove ‘/home/amos/.config/systemd/user/scylla-server.service.d’: Is a directory
removed ‘/home/amos/.config/systemd/user/scylla-server.slice’
removed ‘/home/amos/.config/systemd/user/scylla-fstrim.service’
removed ‘/home/amos/.config/systemd/user/scylla-fstrim.timer’
removed ‘/home/amos/.config/systemd/user/scylla-housekeeping-daily.service’
removed ‘/home/amos/.config/systemd/user/scylla-housekeeping-daily.timer’
removed ‘/home/amos/.config/systemd/user/scylla-housekeeping-restart.service’
removed ‘/home/amos/.config/systemd/user/scylla-housekeeping-restart.timer’
removed ‘/home/amos/.config/systemd/user/node-exporter.service’
```

#### the nonroot config isn't removed.

```
[amos@amos-centos7 scylladb]$ ls /home/amos/.config/systemd/user/scylla-server.service.d
nonroot.conf
```

**Comment by syuu1228** [comment] 2021-05-17 10:40
@amoskong It is a bug, but there is no option `--nonroot` for uninstall.sh, installation mode is auto-detect.

**Comment by amoskong** [comment] 2021-05-17 10:49
> @amoskong It is a bug, but there is no option `--nonroot` for uninstall.sh, installation mode is auto-detect.

Ok, I will remove the option.

**Comment by syuu1228** [comment] 2021-05-24 10:41
@amoskong Not able to reproduce "ERROR 1", it should be missing SCYLLA-NONROOT-FILE on ~/scylladb.
And I able to reproduce "ERROR 2", should be fixed by https://github.com/scylladb/scylla/pull/8662.

**Comment by syuu1228** [comment] 2021-05-24 10:42
So unless "ERROR 1" can reproduce, I think we can close this.

**Comment by syuu1228** [comment] 2021-05-24 10:44
Note that if we want to fix the issue at released version / rc version, we need to backport a3b25e3

**Comment by yaronkaikov** [comment] 2023-10-05 11:56
https://github.com/scylladb/scylladb/issues/8480#issuecomment-846955168

**Closed by yaronkaikov** 2023-10-05 11:56 UTC
Labels: bug, offlineinstaller
