### ISSUE TITLE
backup_restore_tests.py::TestBackupRestore::test_restore_snapshot_using_old_token_ownership fails in CI

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylladb#13211] opened 2023-03-16 15:12 UTC
*Installation details*
Scylla version (or git commit hash): 1d9b7f3a929bb29454f3f5152785f920f3119fe1

```
self = <backup_restore_tests.TestBackupRestore object at 0x7fc6cd144b10>

    @pytest.mark.next_gating
    @pytest.mark.dtest_debug
    def test_restore_snapshot_using_old_token_ownership(self):
        """
        Check that we can restore snapshot files that use a non updated token ownership
    
        1. Use a single node and create a keyspace + table
        2. Insert data
        3. Create snapshot and save files
        4. Add an additional node
        5. Drop keyspace
        6. Create keyspace + table
        7. Restore data
        8. Check that all data exists
        """
        cluster = self.cluster
        snapshot_name = 'testsnapshot'
        num_keys = 1000
        c1_values = list(map(lambda x: '{}'.format(x), range(num_keys)))
        c2_values = list(map(lambda x: '{}'.format(x), range(num_keys, 2 * num_keys)))
        keys = range(num_keys)
    
        # Disable hinted handoff and set batch commit log so this doesn't
        # interfere with the test (this must be after the populate)
        cluster.set_configuration_options(values={'hinted_handoff_enabled': False}, batch_commitlog=True)
        logger.debug("Starting a cluster of one node...")
        cluster.populate(1).start()
        node1 = cluster.nodelist()[0]
    
        logger.debug("Creating a CQL connection...")
        session = self.patient_cql_connection(node1)
    
        logger.debug("Creating a keyspace 'ks'...")
        create_ks(session, 'ks', 1)
    
        logger.debug("Creating a column family 'cf'...")
        create_cf(session, 'cf', read_repair=0.0, columns={'c1': 'text', 'c2': 'text'})
    
        logger.debug("Inserting concurrently {} keys...".format(num_keys))
        insert_c1c2(session, keys=keys, consistency=ConsistencyLevel.ONE,
                    c1_values=c1_values, c2_values=c2_values)
    
        logger.debug("Creating a snapshot...")
        node1.nodetool('snapshot -t {} -cf cf -- ks'.format(snapshot_name))
    
        snapshot_dir = self.get_snapshot_dir(snapshot_name)
        assert snapshot_dir is not None, "Can't find a snapshot directory for {}".format(snapshot_name)
        logger.debug("Snapshot dir is {}".format(snapshot_dir))
    
        logger.debug("Staring a new node (node2)...")
        node2 = new_node(cluster)
        node2.start(wait_for_binary_proto=True, wait_other_notice=True)
    
        logger.debug("Dropping a keyspace...")
        session.execute(SimpleStatement("DROP KEYSPACE ks"))
    
        logger.debug("Creating the same keyspace.table...")
        create_ks(session, 'ks', 1)
>       create_cf(session, 'cf', read_repair=0.0, columns={'c1': 'text', 'c2': 'text'})

backup_restore_tests.py:403: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dtest_class.py:407: in create_cf
    session.execute('SELECT * FROM %s LIMIT 1' % name)
cassandra/cluster.py:2611: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.ReadFailure: Error from server: code=1300 [Replica(s) failed to execute read] message="Operation failed for ks.cf - received 0 responses and 1 failures from 1 CL=ONE." info={'consistency': 'ONE', 'required_responses': 1, 'received_responses': 0, 'failures': 1}

cassandra/cluster.py:4829: ReadFailure
```

**Comment by gleb-cloudius** [comment] 2023-03-16 15:15
Node 1 gets: 

```
WARN  2023-03-16 13:39:01,759 [shard 1] storage_proxy - Exception when communicating with 127.0.80.2, to read from ks.cf: Failed to load schema version c65798fd-d164-37d1-8367-6a7e8daee2f4
```

node 2 learns about it a little bit later:

```
INFO  2023-03-16 13:39:01,769 [shard 0] schema_tables - Creating ks.cf id=e95ac430-c3ff-11ed-9878-c63464eb9706 version=c65798fd-d164-37d1-8367-6a7e8daee2f4
```

It means node 2 failed to pull it from node 1 for some reason.

**Comment by michoecho** [comment] 2023-03-25 14:39
The test seems to fail due to a race with a schema change. (Because it complains about failing to load a schema version, and several milliseconds later the failing node reports that the schema was changed to that version).

Yet, the failing read (`session.execute('SELECT * FROM %s LIMIT 1' % name)`) is called immediately after `session.cluster.control_connection.wait_for_schema_agreement(wait_time=120)`. Doesn't this mean that `wait_for_schema_agreement` isn't doing its job?

`wait_for_schema_agreement` works by polling the schema version (on the control connection host) from `system.local` and the schema versions from `system.peers` until all nodes are seen to have the same version. Is that supposed to be enough?
What changes to system.local and system.peers are guaranteed to happen after `CREATE TABLE` returns a successful response to the client?
Doesn't this method of waiting for schema agreement require the poll to happen on the same host as the schema modifying statement (`CREATE TABLE` in this case) was executed on (which maybe can be different from the one on the control connection)? If that's the case, perhaps the shortest path to fixing this flakiness is to execute the `CREATE TABLE` on the control connection host?

**Comment by michoecho** [comment] 2023-03-25 15:01
That said, even if `wait_for_schema_agreement` not doing its job explains the flakiness, it doesn't explain why node 2 failed to pull the schema.

**Comment by michoecho** [comment] 2023-03-25 15:24
It would be nice if `Failed to load schema version` reported the underlying reason, but the underlying exception is effectively silenced, because seastar RPC doesn't print nested exceptions.

**Comment by fruch** [comment] 2023-03-26 20:00
> That said, even if `wait_for_schema_agreement` not doing its job explains the flakiness, it doesn't explain why node 2 failed to pull the schema.

This function doesn't raise exception if it fails, it return a boolean that we don't check here.

So it in theory waited 2min and return false.

https://github.com/datastax/python-driver/blob/f5001b8759d34896a1899b791a5ca57db8ba8069/cassandra/cluster.py#L3925

**Comment by michoecho** [comment] 2023-03-26 20:03
> So it in theory waited 2min and return false.

That's not what happened here because we see from log timestamps that it succeeded within a fraction of a second.

**Comment by michoecho** [comment] 2023-03-28 10:36
> One more question is, shouldn't schema changes with raft eliminate such races?

I mean, there isn't really a race here. It's only a "race" in the sense that a temporary condition (a schema disagreement) causes the read failure, but in principle such a read should just have caused a schema pull on the nodes which don't know the newest version yet, and then the read should succeed. But the schema pull has failed for an unknown reason.

About Raft: no, it shouldn't eliminate this kind of problems. Raft only ensures that all nodes see schema changes in the same order. It doesn't give any guarantees about the ordering of schema modifications with respect to data statements. (Correct me if I'm wrong).

**Comment by DoronArazii** [comment] 2023-04-03 09:13
@eliransin does your team can pick up this CI-Stability issue ?
Or at least give some clue who should handle this

**Comment by tgrabiec** [comment] 2023-04-05 08:46
> It would be nice if `Failed to load schema version` reported the underlying reason, but the underlying exception is effectively silenced, because seastar RPC doesn't print nested exceptions.

https://github.com/scylladb/seastar/issues/1598

**Comment by tgrabiec** [comment] 2023-04-05 08:59
node1:

```
WARN  2023-03-16 13:39:01,759 [shard 1] storage_proxy - Exception when communicating with 127.0.80.2, to read from ks.cf: Failed to load schema version c65798fd-d164-37d1-8367-6a7e8daee2f4
```

node2:
```
INFO  2023-03-16 13:39:01,759 [shard 0] schema_tables - Creating keyspace ks
```

schema version loading probably failed on node2 because node2 doesn't contain the keyspace yet so table schema definition fails to be deserialized. That's https://github.com/scylladb/scylladb/issues/3760. We should pull the schema using raft first (@gleb-cloudius @kostja is there a github issue for doing this?), this will make sure we have all earlier schema changes before we request the schema version.

But we shouldn't run into this if drivers waited for schema agreement, since keyspace is created before the table is created. Looks like schema agreement waiting is broken.

**Comment by gleb-cloudius** [comment] 2023-04-05 09:58
> 
> schema version loading probably failed on node2 because node2 doesn't contain the keyspace yet so table schema definition fails to be deserialized. That's #3760. We should pull the schema using raft first (@gleb-cloudius @kostja is there a github issue for doing this?), this will make sure we have all earlier schema changes before we request the schema version.
> 
Yes, we should. I do not remember having the issue about it.

> But we shouldn't run into this if drivers waited for schema agreement, since keyspace is created before the table is created. Looks like schema agreement waiting is broken.

Exactly.

**Comment by bhalevy** [comment] 2023-04-10 18:54
Hit again in https://jenkins.scylladb.com/job/scylla-master/job/next/5867/testReport/backup_restore_tests/TestBackupRestore/Tests___Sanity_Tests_RAFT___test_restore_snapshot_using_old_token_ownership/

**Comment by DoronArazii** [comment] 2023-04-13 07:49
@kostja assigning this to your team (please re-assign if it's caused from another direction)

**Comment by DoronArazii** [comment] 2023-04-20 14:49
@kostja ping, please give CI-Stability cases attention

**Comment by kostja** [comment] 2023-04-20 16:49
It is not failing right now. There are several of these fail-once-in-a-lifetime issues, and often they are not reproducible locally, even with --repeat. So there is not much I can do about these. We discussed at the team call, no clear plan how to address these.

**Comment by raphaelsc** [comment] 2023-04-27 15:10
Just bumped into it here https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/914/

**Comment by raphaelsc** [comment] 2023-04-27 15:15
> It is not failing right now. There are several of these fail-once-in-a-lifetime issues, and often they are not reproducible locally, even with --repeat. So there is not much I can do about these. We discussed at the team call, no clear plan how to address these.

the issue was hit twice over the course of two weeks. I understand your sentiment about it not being easy to reproduce, but given the frequency, it means somethign may have changed that is triggering this problem. 

In the past, I also had to investigate issues which show up in CI, but never locally. One of the variables that change between your local env and jenkins is the overprovisioned flag which will impact seastar behavior and as a result scylla. So I suggest using it.

**Comment by kbr-scylla** [comment] 2023-04-28 09:26
Reproducer if someone wants to play:
https://github.com/kbr-scylla/scylladb/commit/5fb1722ac8422fdecd0e25ceed31339a8e5eef47

reproduced ~9 out of 10 times for me:
```
$ ./test.py --mode dev test_schema_pull --repeat 10
Found 10 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[1/10]     topology_custom   dev   [ FAIL ] topology_custom.test_schema_pull.1
[2/10]     topology_custom   dev   [ FAIL ] topology_custom.test_schema_pull.3
[3/10]     topology_custom   dev   [ FAIL ] topology_custom.test_schema_pull.2
[4/10]     topology_custom   dev   [ FAIL ] topology_custom.test_schema_pull.4
[5/10]     topology_custom   dev   [ FAIL ] topology_custom.test_schema_pull.5
[6/10]     topology_custom   dev   [ FAIL ] topology_custom.test_schema_pull.8
[7/10]     topology_custom   dev   [ FAIL ] topology_custom.test_schema_pull.7
[8/10]     topology_custom   dev   [ PASS ] topology_custom.test_schema_pull.6
[9/10]     topology_custom   dev   [ FAIL ] topology_custom.test_schema_pull.10
[10/10]    topology_custom   dev   [ FAIL ] topology_custom.test_schema_pull.9
```

In this particular test the reason that the driver doesn't wait for schema agreement is because it doesn't yet know about the second node.

I doubt that this is the same reason as in the original dtest; the dtest as usual uses a normal value for `ring_delay` I think, so the driver should have plenty of time to learn about the second node. But it's not impossible in theory. There could be other reasons that the driver doesn't wait for schema agreement though, e.g. it considers the other node dead for some reason.

**Comment by kbr-scylla** [comment] 2023-04-28 09:30
In any case, I think we should focus on fixing Scylla first, then the driver. Scylla should pull the keyspace definition if it needs it.

**Comment by kbr-scylla** [comment] 2023-04-28 09:33
> In my test the reason that the driver doesn't wait for schema agreement is because it doesn't yet know about the second node.

By uncommenting this line in the test:
```python3
    #h2 = (await wait_for_cql_and_get_hosts(cql, [srvs[1]], time.time() + 60))[0]
```
we can "fix" the test by ensuring that the driver becomes aware of the second node before creating the keyspace. Then it will wait for schema agreement.

**Comment by tgrabiec** [comment] 2023-04-28 12:35
That doesn't help if the coordinator doesn't have it.

**Comment by kbr-scylla** [comment] 2023-04-28 12:36
> That doesn't help if the coordinator doesn't have it.

How can it not have it if it started the read in the first place, which required knowing the schema?
Schema changing in the middle of the read?

**Comment by kbr-scylla** [comment] 2023-04-28 12:43
If the replica has the keyspace definition but not the table definition, it will correctly put the table definition - right?
But then if it doesn't have the keyspace definition, it won't even try to pull it, but give up immediately. This one I don't understand. Why can't it pull the keyspace like it does for the table?

**Comment by tgrabiec** [comment] 2023-04-30 08:57
On Fri, Apr 28, 2023 at 2:43 PM Kamil Braun ***@***.***>
wrote:

> If the replica has the keyspace definition but not the table definition,
> it will correctly put the table definition - right?
> But then if it doesn't have the keyspace definition, it won't even try to
> pull it, but give up immediately. This one I don't understand. Why can't it
> pull the keyspace like it does for the table?
>

It should, it's a known bug:
https://github.com/scylladb/scylladb/issues/3760

**Comment by tgrabiec** [comment] 2023-04-30 09:03
On Fri, Apr 28, 2023 at 2:36 PM Kamil Braun ***@***.***>
wrote:

> That doesn't help if the coordinator doesn't have it.
>
> How can it not have it if it started the read in the first place, which
> required knowing the schema?
> Schema changing in the middle of the read?
>
I mean that the coordinator will fail the request when creating a statement
in the cql layer. The client may think the schema change was successful,
but execution may land on a connection to a host which doesn't yet have the
latest schema. There's no one to pull the schema from in this case.

**Comment by gleb-cloudius** [comment] 2023-04-30 09:16
> It should, it's a known bug: #3760

We need to change schema pull as discussed here:
https://github.com/scylladb/scylladb/pull/13387#discussion_r1175178909

**Comment by kostja** [comment] 2023-04-30 10:56
I think the idea of not having a read barrier in schema pull was to avoid dependency on the global quorum on the write path. What we want to have, ideally, is raft snapshot transfer from the nearest follower, not from a leader.

**Comment by gleb-cloudius** [comment] 2023-04-30 11:11
> I think the idea of not having a read barrier in schema pull was to avoid dependency on the global quorum on the write path. 

True, but the schema mismatch should happen only in a short period after a DLL, so it should not be a problem.

> What we want to have, ideally, is raft snapshot transfer from the nearest follower, not from a leader. @gleb-cloudius

What is the nearest follower? Why do you think it will have an up-to-date schema? If we will pull from a request sander (which is guarantied to have the schema) then you basically propose to fix https://github.com/scylladb/scylladb/issues/3760 in non raft way by including the whole schema.

**Comment by nyh** [comment] 2023-05-01 09:05
Seen again in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/998/testReport/junit/backup_restore_tests/TestBackupRestore/Tests___Sanity_Tests___test_restore_snapshot_using_old_token_ownership/

**Comment by kostja** [comment] 2023-05-01 11:08
> uld happen only in a short per

I think if your write path depends on a read barrier, at least in some cases, you can't claim your write path is unaffected by the majority  loss. I think it is *OK* in general to fail the write path after a majority loss. Anyway, we could add this barrier and see if anyone complains. 

As to the proposed solution: the nearest follower is the coordinator who sent the request with a newer schema. I suggest we fetch entire group0 snapshot from this follower in this case. We can always compare our term/index with the sender's to see that their state is fresher. No need for log transfer.

The RPC could look like follows:
* the fallen-behind replica sends its term, index to the write coordinator.
* the coordinator  sees if its commit index is more fresh, in which case it takes a snapshot locally and transfers that snapshot to the replica.

**Comment by gleb-cloudius** [comment] 2023-05-01 11:36
> > uld happen only in a short per
> 
> I think if your write path depends on a read barrier, at least in some cases, you can't claim your write path is unaffected by the majority loss. I think it is _OK_ in general to fail the write path after a majority loss. Anyway, we could add this barrier and see if anyone complains.

Yes. The barrier will obviously will be down with a timeout.

> 
> As to the proposed solution: the nearest follower is the coordinator who sent the request with a newer schema. I suggest we fetch entire group0 snapshot from this follower in this case. We can always compare our term/index with the sender's to see that their state is fresher. No need for log transfer.
> 
> The RPC could look like follows:
> 
>     * the fallen-behind replica sends its term, index to the write coordinator.
> 
>     * the coordinator  sees if its commit index is more fresh, in which case it takes a snapshot locally and transfers that snapshot to the replica.

I do not like write home grown raft extensions without any prove of safety or at least some existing papers. I am fine with just fixing  https://github.com/scylladb/scylladb/issues/3760 in non raft related way which will fix this bug as well.

**Comment by kbr-scylla** [comment] 2023-05-04 10:08
> I mean that the coordinator will fail the request when creating a statement
in the cql layer. The client may think the schema change was successful,
but execution may land on a connection to a host which doesn't yet have the
latest schema. There's no one to pull the schema from in this case.

That's a completely different problem though, I don't think we should consider it in the context of this issue.

**Closed** 2023-05-14 13:50 UTC
Labels: P1, CI-Stability

**Comment by benipeled** [comment] 2023-05-18 14:18
Seen in next-enterprise https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2400/testReport/junit/backup_restore_tests/TestBackupRestore/Tests___Sanity_Tests_RAFT___test_restore_snapshot_using_old_token_ownership/

**Comment by kbr-scylla** [comment] 2023-05-18 14:20
The patch didn't make it yet to next-enterprise, it's waiting for the weekly master-to-enterprise merge.

**Comment by gleb-cloudius** [comment] 2023-11-30 15:40
> @gleb-cloudius seems like a backport is needed, please confirm and check if follow ups are necesssary

This issue existed forever. The patch here fixes it for the schema over raft, but not for the gossiper mode. We can backport it to all version that have non experimental schema over raft, but not this patch, but I am not sure here are any.

**Comment by mykaul** [comment] 2024-05-05 10:39
> > @gleb-cloudius seems like a backport is needed, please confirm and check if follow ups are necesssary
> 
> This issue existed forever. The patch here fixes it for the schema over raft, but not for the gossiper mode. We can backport it to all version that have non experimental schema over raft, but not this patch, but I am not sure here are any.

@gleb-cloudius - can you please backport to 5.2 (2023.1.x eventual target) ?

**Comment by gleb-cloudius** [comment] 2024-05-05 10:56
@mkaul What exactly needs to be done? I checked at the patch applies cleanly to 5.2.17.

**Comment by mykaul** [comment] 2024-05-05 11:01
> @mkaul What exactly needs to be done? I checked at the patch applies cleanly to 5.2.17.

Prepare a PR (or @yaronkaikov - can we just run the bot) ?

**Comment by yaronkaikov** [comment] 2024-05-05 11:05
> > @mkaul What exactly needs to be done? I checked at the patch applies cleanly to 5.2.17.
> 
> Prepare a PR (or @yaronkaikov - can we just run the bot) ?

Done
