### ISSUE TITLE
Scylla aborting on startup after enospc

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylladb#11299] opened 2022-08-15 23:36 UTC
## Installation details

Kernel Version: 5.15.0-1017-aws
Scylla version (or git commit hash): `5.2.0~dev-20220809.3ffc978166ab` with build-id `7da4f902c8209ca890ba8338dbf376529fb6c2fe`
Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-02b6a6a3-7 (13.50.5.249 | 10.0.0.119) (shards: 7)
- longevity-twcs-48h-master-db-node-02b6a6a3-6 (13.48.135.168 | 10.0.3.208) (shards: 7)
- longevity-twcs-48h-master-db-node-02b6a6a3-5 (13.51.178.28 | 10.0.2.93) (shards: 7)
- longevity-twcs-48h-master-db-node-02b6a6a3-4 (13.51.170.89 | 10.0.2.187) (shards: 7)
- longevity-twcs-48h-master-db-node-02b6a6a3-3 (13.51.174.154 | 10.0.0.60) (shards: 7)
- longevity-twcs-48h-master-db-node-02b6a6a3-2 (13.49.0.236 | 10.0.2.107) (shards: 7)
- longevity-twcs-48h-master-db-node-02b6a6a3-1 (16.170.141.204 | 10.0.3.109) (shards: 7)

OS / Image: `ami-0786ef2aeb8f93c28` (aws: eu-north-1)

Test: `longevity-twcs-48h-test`
Test id: `02b6a6a3-4530-4e1b-af60-ce437fbec08a`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/97672913680e75c9cfcfbf2b11ec1edd8d14e600/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

At `2022-08-12 03:35:39` an enospc nemesis started running with node 2 as the target node. After the disk space occupied by the nemesis was clened, and scylla service was restarted, it aborted:
```
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]: Aborting on shard 5.
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]: Backtrace:
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   0x4c91418
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   0x4cc0b22
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   0x7f029e634a1f
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   /opt/scylladb/libreloc/libc.so.6+0x3d2a1
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   /opt/scylladb/libreloc/libc.so.6+0x268a3
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   0x1350830
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   0x13baf70
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   0x4ca0ba4
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   0x4ca1f87
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   0x4cc0fd5
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   0x4c7494a
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   /opt/scylladb/libreloc/libpthread.so.0+0x92a4
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]:   /opt/scylladb/libreloc/libc.so.6+0x100322
```
Translated:
```
2022-08-12 04:08:41.139 <2022-08-12 04:08:38.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=379af2d9-3f83-4d39-b34d-c2109f84d851: type=ABORTING_ON_SHARD regex=Aborting on shard line_number=9116 node=longevity-twcs-48h-master-db-node-02b6a6a3-2
2022-08-12T04:08:38+00:00 longevity-twcs-48h-master-db-node-02b6a6a3-2     !INFO | scylla[7722]: Aborting on shard 5.
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:760
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:790
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:802
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3672
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3648
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3644
?? ??:0
?? ??:0
?? ??:0
operator() at ./replica/table.cc:610
replica::table::seal_active_memtable(flush_permit&&)::$_45::operator()(std::function<seastar::future<void> ()>) const [clone .resume] at table.cc:?
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2345
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2752
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2921
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4145
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
?? ??:0
?? ??:0
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 02b6a6a3-4530-4e1b-af60-ce437fbec08a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=02b6a6a3-4530-4e1b-af60-ce437fbec08a)
- Show all stored logs command: `$ hydra investigate show-logs 02b6a6a3-4530-4e1b-af60-ce437fbec08a`

## Logs:
- **db-cluster-02b6a6a3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/02b6a6a3-4530-4e1b-af60-ce437fbec08a/20220813_085133/db-cluster-02b6a6a3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/02b6a6a3-4530-4e1b-af60-ce437fbec08a/20220813_085133/db-cluster-02b6a6a3.tar.gz)
- **monitor-set-02b6a6a3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/02b6a6a3-4530-4e1b-af60-ce437fbec08a/20220813_085133/monitor-set-02b6a6a3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/02b6a6a3-4530-4e1b-af60-ce437fbec08a/20220813_085133/monitor-set-02b6a6a3.tar.gz)
- **loader-set-02b6a6a3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/02b6a6a3-4530-4e1b-af60-ce437fbec08a/20220813_085133/loader-set-02b6a6a3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/02b6a6a3-4530-4e1b-af60-ce437fbec08a/20220813_085133/loader-set-02b6a6a3.tar.gz)
- **sct-runner-02b6a6a3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/02b6a6a3-4530-4e1b-af60-ce437fbec08a/20220813_085133/sct-runner-02b6a6a3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/02b6a6a3-4530-4e1b-af60-ce437fbec08a/20220813_085133/sct-runner-02b6a6a3.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/47/)

Could be related https://github.com/scylladb/scylladb/issues/6653#issuecomment-1214335036 and/or https://github.com/scylladb/scylladb/issues/11245

**Comment by ShlomiBalalis** [comment] 2022-08-15 23:39
The issue occurred on another run:
## Installation details

Kernel Version: 5.15.0-1017-aws
Scylla version (or git commit hash): `5.2.0~dev-20220809.3ffc978166ab` with build-id `7da4f902c8209ca890ba8338dbf376529fb6c2fe`
Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-200gb-48h-verify-limited--db-node-524c39ba-5 (16.170.143.144 | 10.0.3.44) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-524c39ba-4 (13.49.21.239 | 10.0.0.254) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-524c39ba-3 (13.53.176.251 | 10.0.3.222) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-524c39ba-2 (16.170.146.216 | 10.0.2.0) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-524c39ba-1 (13.50.16.196 | 10.0.2.79) (shards: 14)


OS / Image: `ami-0786ef2aeb8f93c28` (aws: eu-north-1)

Test: `longevity-200gb-48h`
Test id: `524c39ba-658e-4281-b0db-43a8fa8ae71f`
Test name: `scylla-master/longevity/longevity-200gb-48h`
Test config file(s):

- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/97672913680e75c9cfcfbf2b11ec1edd8d14e600/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)

## Issue description

The error was reproduced during an enospc nemesis on node 5:
At first, the node did reach enospc:
`2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5      !ERR | scylla[7814]:  [shard  5] storage_service - Shutting down communications due to I/O errors until operator intervention: Commitlog error: std::system_error (error system:28, No space left on device)`
And afterwards, the space occupied by the nemesis was cleaned, and we attempted to restart the scylla service, only for it to abort:
```
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]: Aborting on shard 7.
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]: Backtrace:
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   0x4c91418
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   0x4cc0b22
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   0x7f0cde2a1a1f
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   /opt/scylladb/libreloc/libc.so.6+0x3d2a1
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   /opt/scylladb/libreloc/libc.so.6+0x268a3
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   0x1350830
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   0x13baf70
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   0x4ca0ba4
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   0x4ca1f87
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   0x4cc0fd5
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   0x4c7494a
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   /opt/scylladb/libreloc/libpthread.so.0+0x92a4
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]:   /opt/scylladb/libreloc/libc.so.6+0x100322
```
Trabslated:
```
2022-08-12T06:02:40+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5     !INFO | scylla[7814]: Aborting on shard 7.
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:760
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:790
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:802
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3672
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3648
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3644
?? ??:0
?? ??:0
?? ??:0
operator() at ./replica/table.cc:610
replica::table::seal_active_memtable(flush_permit&&)::$_45::operator()(std::function<seastar::future<void> ()>) const [clone .resume] at table.cc:?
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2345
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2752
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2921
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4145
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
?? ??:0
?? ??:0
```
Corrupted commitlog files:
```
2022-08-12T06:03:54+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard  2] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-36028797019129999.log. 16092152 bytes skipped.
2022-08-12T06:03:54+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard  1] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-18014398509648014.log. 14946296 bytes skipped.
2022-08-12T06:03:54+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard  6] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-108086391057057931.log. 1384440 bytes skipped.
2022-08-12T06:03:54+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard  0] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-166029.log. 23173112 bytes skipped.
2022-08-12T06:03:54+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard 10] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-180143985094985867.log. 23533560 bytes skipped.
2022-08-12T06:03:55+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard  4] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-72057594038093966.log. 1114104 bytes skipped.
2022-08-12T06:03:55+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard  8] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-144115188076021900.log. 6096888 bytes skipped.
2022-08-12T06:03:55+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard 12] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-216172782113949834.log. 20283384 bytes skipped.
2022-08-12T06:03:56+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard  3] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-54043195528611978.log. 7442424 bytes skipped.
2022-08-12T06:03:57+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard 11] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-198158383604467853.log. 23714808 bytes skipped.
2022-08-12T06:03:58+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard 13] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-234187180623431816.log. 22301688 bytes skipped.
2022-08-12T06:03:58+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard  9] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-162129586585503883.log. 10914808 bytes skipped.
2022-08-12T06:03:58+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5  !WARNING | scylla[12565]:  [shard  7] commitlog_replayer - Corrupted file: /var/lib/scylla/commitlog/CommitLog-2-126100789566539917.log. 32899064 bytes skipped.
```
Startup failure:
`2022-08-12T06:04:15+00:00 longevity-200gb-48h-verify-limited--db-node-524c39ba-5      !ERR | scylla[12565]:  [shard  0] init - Startup failed: std::out_of_range (attempted to read 4 bytes from a 0 byte buffer)`

A coredump was also initialized, but could not be saved since it was before the occupied space taken by the nemesis was cleaned.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 524c39ba-658e-4281-b0db-43a8fa8ae71f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=524c39ba-658e-4281-b0db-43a8fa8ae71f)
- Show all stored logs command: `$ hydra investigate show-logs 524c39ba-658e-4281-b0db-43a8fa8ae71f`

## Logs:
- **db-cluster-524c39ba.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/524c39ba-658e-4281-b0db-43a8fa8ae71f/20220812_061841/db-cluster-524c39ba.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/524c39ba-658e-4281-b0db-43a8fa8ae71f/20220812_061841/db-cluster-524c39ba.tar.gz)
- **monitor-set-524c39ba.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/524c39ba-658e-4281-b0db-43a8fa8ae71f/20220812_061841/monitor-set-524c39ba.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/524c39ba-658e-4281-b0db-43a8fa8ae71f/20220812_061841/monitor-set-524c39ba.tar.gz)
- **loader-set-524c39ba.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/524c39ba-658e-4281-b0db-43a8fa8ae71f/20220812_061841/loader-set-524c39ba.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/524c39ba-658e-4281-b0db-43a8fa8ae71f/20220812_061841/loader-set-524c39ba.tar.gz)
- **sct-runner-524c39ba.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/524c39ba-658e-4281-b0db-43a8fa8ae71f/20220812_061841/sct-runner-524c39ba.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/524c39ba-658e-4281-b0db-43a8fa8ae71f/20220812_061841/sct-runner-524c39ba.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/191/)

**Comment by bhalevy** [comment] 2022-08-17 19:07
Looks like a duplicate of #11245

**Comment by avikivity** [comment] 2022-09-19 11:16
@xemul please pursue with high priority

**Comment by xemul** [comment] 2023-07-13 07:20
> Looks like a duplicate of #11245

Closing as the "master" issue is fixed and backported

**Closed by xemul** 2023-07-13 07:21 UTC
Labels: duplicate
