### ISSUE TITLE
service_level_controller - update_from_distributed_data failed to update configuration

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#10291] opened 2022-03-29 13:01 UTC
In performance test job runs (https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-throughput/) we can see errors in Scylla logs (for all the nodes, about the same time) like below:
```2022-03-27T03:49:19+00:00  perf-regression-perf-v8-db-node-da347b1b-3 !ERR     | scylla:  [shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  900 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)```

*Installation details*
Scylla version (or git commit hash): Scylla version 5.1.dev-0.20220317.c45050895403 with build-id 076f513b6143670def988c7626389b270411f8f7
Cluster size: 3x i3.2xlarge
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

logs:
+--------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Collected logs by test-id: da347b1b-b558-4efe-a036-91fc2bd411c2                                       |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/da347b1b-b558-4efe-a036-91fc2bd411c2/20220327_050736/db-cluster-da347b1b.zip  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/da347b1b-b558-4efe-a036-91fc2bd411c2/20220327_050736/monitor-set-da347b1b.zip |
| loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/da347b1b-b558-4efe-a036-91fc2bd411c2/20220327_050736/loader-set-da347b1b.zip  |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/da347b1b-b558-4efe-a036-91fc2bd411c2/20220327_050736/sct-runner-da347b1b.zip  |

**Comment by juliayakovlev** [comment] 2022-04-28 07:20
Reproduced in `2022.1.rc3`

It began right after c-s load was started

```
022-04-27T14:55:36+00:00 system-sla-2022-1-db-node-d1c7104e-1 ! WARNING |  [shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  90 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)
```

## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `2022.1~rc3-20220406.5cc3b678c` with build-id `48dfae0735cd8efc4ae2f5c777beaee2a1e89f4a`
Cluster size: 3 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- system-sla-2022-1-db-node-d1c7104e-3 (18.203.127.238 | 10.0.3.67) (shards: 8)
- system-sla-2022-1-db-node-d1c7104e-2 (34.250.44.179 | 10.0.1.153) (shards: 8)
- system-sla-2022-1-db-node-d1c7104e-1 (3.250.24.206 | 10.0.2.220) (shards: 8)


OS / Image: `ami-071c70d20f0fdbb2c` (aws: eu-west-1)

Test: `features-sla-read-throughput-1to5-ratio-test`
Test id: `d1c7104e-e3dc-4d89-8a5e-df8a9d98164a`
Test name: `enterprise-2022.1/SCT_Enterprise_Features/Workload_Prioritization/features-sla-read-throughput-1to5-ratio-test`
Test config file(s):

- [system-sla-test.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/26669988977199aa81816c32f017be68c3fc0dea/test-cases/features/system-sla-test.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor d1c7104e-e3dc-4d89-8a5e-df8a9d98164a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d1c7104e-e3dc-4d89-8a5e-df8a9d98164a)
- Show all stored logs command: `$ hydra investigate show-logs d1c7104e-e3dc-4d89-8a5e-df8a9d98164a`

## Logs:
- **db-cluster-d1c7104e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/db-cluster-d1c7104e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/db-cluster-d1c7104e.tar.gz)
- **monitor-set-d1c7104e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/monitor-set-d1c7104e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/monitor-set-d1c7104e.tar.gz)
- **loader-set-d1c7104e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/loader-set-d1c7104e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/loader-set-d1c7104e.tar.gz)
- **sct-runner-d1c7104e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/sct-runner-d1c7104e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/sct-runner-d1c7104e.tar.gz)
- **parallel-timelines-report-d1c7104e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/parallel-timelines-report-d1c7104e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/parallel-timelines-report-d1c7104e.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/SCT_Enterprise_Features/job/Workload_Prioritization/job/features-sla-read-throughput-1to5-ratio-test/2/)

**Comment by roydahan** [comment] 2022-06-27 16:22
I don't think it's relevant anymore.
If it does, please re-open.

**Comment by JerryKwan** [comment] 2022-11-03 02:12
@roydahan 
Encountered the same problem too, the version is scylla-server-5.0.4-0.20220921.1c82766f3.x86_64
**_[shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  4770 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)_**

**Comment by talexander** [comment] 2022-12-16 16:07
me too

service_level_controller - update_from_distributed_data: failed to update configuration for more than  7650 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)

**Comment by Felix-zhoux** [comment] 2023-02-23 07:45
I met the same problem.
`service_level_controller - update_from_distributed_data: failed to update configuration for more than  1800 seconds`

What does this error mean, what effect does it have on writing, can anyone give me some pointers?

**Comment by codingcuisg** [comment] 2023-05-03 09:21
Dear team, we encountered similar issue on scylla version 5.0.5

One node(node A) suddenly reported as unreachable by scylla monitoring, but nodetool status show all nodes to be active and we could see increasing number of background read on every node, another node (node B in same rack) was having high read latency. 
```
[shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than 540 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)
```

The latency came down after a force kill of node A, and the background read reduced after a rolling restart of scylla cluster. 

However the system_distributed.service_levels doesn't have any data and we are not using WP, also there is no repair/compaction scheduled at that time. Could you help suggest how to avoid this issue ?

**Comment by mykaul** [comment] 2023-06-08 12:50
@eliransin - has anyone looked at this?

**Comment by gulldan** [comment] 2023-06-28 08:49
Dear team, we encountered similar issue on scylla version 4.6.3-0.20220414.8bf149fdd
4 nodes cluster.
for sometime helps reboot node, but after a few days its appears again

**Comment by roydahan** [comment] 2023-06-28 14:56
4.6.x isn't supported anymore.
Please upgrade to a minimal supported release - 5.1 or above.

**Comment by gulldan** [comment] 2023-08-17 13:34
> 4.6.x isn't supported anymore. Please upgrade to a minimal supported release - 5.1 or above.

updated to 5.2.6, nothing changed.

**Comment by naijaexboy** [comment] 2023-09-11 12:22
Hello Team, I having this issue, is there any known solution to this error?                                                                                  
its shown in RED in my journalctl status --- [shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  900 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)

**Comment by mykaul** [comment] 2023-09-11 12:26
@eliransin - who can look at the above?

**Comment by pgoron** [comment] 2023-09-15 12:08
Hello team, same error seen with scylla-5.2.7 during shutdown sequence until we killed scylla process.
Shutdown sequence initiated by scylla after an I/O error (Disk error: std::system_error (error system:5, Input/output error))

below are logs in reverse order (most recent first)
```
﻿ERROR 2023-09-15 11:35:58,806 [shard  0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  11340 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)
...
﻿WARN  2023-09-15 08:28:18,703 [shard  0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  90 seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)
﻿INFO  2023-09-15 08:27:02,094 [shard  0] raft_group_registry - marking Raft server 94728f61-ac65-4266-ac9b-d87736125ac4 as dead for raft groups
...
﻿INFO  2023-09-15 08:27:01,203 [shard  0] storage_service - Stop transport: done
```
﻿ERROR 2023-09-15 08:26:58,426 [shard  6] storage_service - Shutting down communications due to I/O errors until operator intervention: Disk error: std::system_error (error system:5, Input/output error)

**Comment by mykaul** [comment] 2023-09-18 08:25
@pgoron - I suggest opening a new issue - Disk error sound critical - what do you see in the journal logs?

**Comment by pgoron** [comment] 2023-09-18 10:10
Hi @mykaul , disk errors were reported by kernel and we replaced the node.
```
[Fri Sep 15 08:26:59 2023] sd 1:1:0:1: [sdb] tag#595 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[Fri Sep 15 08:26:59 2023] sd 1:1:0:1: [sdb] tag#595 Sense Key : Aborted Command [current] 
[Fri Sep 15 08:26:59 2023] sd 1:1:0:1: [sdb] tag#595 Add. Sense: No additional sense information
[Fri Sep 15 08:26:59 2023] sd 1:1:0:1: [sdb] tag#595 CDB: Read(16) 88 00 00 00 00 00 6a dd 9a c0 00 00 01 00 00 00
[Fri Sep 15 08:26:59 2023] blk_update_request: I/O error, dev sdb, sector 1792907968 op 0x0:(READ) flags 0x0 phys_seg 2 prio class 0
```

Usually such hw issues are automatically handled by our node replacement automation but here scylla process stayed stuck in its shutdown sequence, looping over `failed to update configuration for more than xxx seconds : exceptions::read_timeout_exception (Operation timed out for system_distributed.service_levels - received only 0 responses from 1 CL=ONE.)`.

Might be the consequence of disk issue or due to another condition. I shared it here just in case it could help to diagnose this github issue as some symptoms seem common.

Rgds,

**Comment by mykaul** [comment] 2023-09-18 10:31
Thanks @pgoron - I think this is an entirely different issue - where in certain situation Scylla gets stuck on shutdown. The original is a different issue, though.

**Comment by MujeerAhmed** [comment] 2024-01-23 05:05
Hello Scylla Team 👋

I am facing the same issue in my production environment. I'm running scylla 5.2 on ubuntu 20.04. Is there a temporary fix to this?

**Comment by mykaul** [comment] 2024-01-28 07:53
@ptrsmrn - seems related to service levels - which are moving to Raft soon, no?

**Comment by ptrsmrn** [comment] 2024-01-29 15:28
> @ptrsmrn - seems related to service levels - which are moving to Raft soon, no?

@mykaul yes, @Jadw1 is working on it.

**Comment by jarPotato** [comment] 2024-02-05 18:40
I'm facing this issue after two of my nodes became unreachable. I tried to change the seed node, did a rolling restart and tried nodetool removenode on one of the nodes that is down.
I can't add new nodes to the cluster since it says one of the down nodes is in UNKNOWN state.

I'm using scylla 5.2.11. Is there anyway I can at least join new nodes in my cluster?

**Comment by denesb** [comment] 2024-02-06 06:13
@asias can you advise with the above?

**Comment by yarongilor** [comment] 2024-02-06 08:19
The error might be reproduced in 2023.1 staging test of longevity-large-collections-12h + restart-then-repair nemesis:
```
2024-02-05 21:20:42.541 <2024-02-05 21:20:05.025>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=3f34735c-ec23-4fbd-b1c0-9e9aaecb154a: type=DATABASE_ERROR regex=(^ERROR|!\s*?ERR).*\[shard.*\] line_number=2805647 node=longevity-large-collections-12h-res-db-node-ef25e3a6-3
2024-02-05T21:20:05.025+00:00 longevity-large-collections-12h-res-db-node-ef25e3a6-3      !ERR | scylla[6132]:  [shard 0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  5310 seconds : exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
```

## Packages

Scylla version: `2023.1.0~rc4-20230402.f90af81a13cc` with build-id `4db7799d283c7ca63c7639b04db34c301dbcfb66`





Kernel Version: `5.19.0-1022-aws`


## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 4 nodes (i3en.3xlarge)

Scylla Nodes used in this run:
- longevity-large-collections-12h-res-db-node-ef25e3a6-4 (3.252.202.140 | 10.4.1.137) (shards: 10)
- longevity-large-collections-12h-res-db-node-ef25e3a6-3 (54.216.91.193 | 10.4.0.110) (shards: 10)
- longevity-large-collections-12h-res-db-node-ef25e3a6-2 (52.50.244.49 | 10.4.0.93) (shards: 10)
- longevity-large-collections-12h-res-db-node-ef25e3a6-1 (34.247.69.52 | 10.4.0.228) (shards: 10)


OS / Image: `ami-000f0d43cb22bd09e` (aws: undefined_region)

Test: `longevity-50gb-3days-test-restart-then-repair`
Test id: `ef25e3a6-cad6-44ea-a479-d3396fdb7bb8`
Test name: `scylla-staging/yarongilor/longevity-50gb-3days-test-restart-then-repair`
Test config file(s):

- [longevity-large-collections-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5e5917e610a955e87a79ab7219436662e2571d81/test-cases/longevity/longevity-large-collections-12h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor ef25e3a6-cad6-44ea-a479-d3396fdb7bb8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ef25e3a6-cad6-44ea-a479-d3396fdb7bb8)
- Show all stored logs command: `$ hydra investigate show-logs ef25e3a6-cad6-44ea-a479-d3396fdb7bb8`


## Logs:
- **db-cluster-ef25e3a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/db-cluster-ef25e3a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/db-cluster-ef25e3a6.tar.gz)
- **email_data-ef25e3a6.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/email_data-ef25e3a6.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/email_data-ef25e3a6.json.tar.gz)
- **output-ef25e3a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/output-ef25e3a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/output-ef25e3a6.log.tar.gz)
- **debug-ef25e3a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/debug-ef25e3a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/debug-ef25e3a6.log.tar.gz)
- **events-ef25e3a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/events-ef25e3a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/events-ef25e3a6.log.tar.gz)
- **normal-ef25e3a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/normal-ef25e3a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/normal-ef25e3a6.log.tar.gz)
- **argus-ef25e3a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/argus-ef25e3a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/argus-ef25e3a6.log.tar.gz)
- **raw_events-ef25e3a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/raw_events-ef25e3a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/raw_events-ef25e3a6.log.tar.gz)
- **critical-ef25e3a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/critical-ef25e3a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/critical-ef25e3a6.log.tar.gz)
- **warning-ef25e3a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/warning-ef25e3a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/warning-ef25e3a6.log.tar.gz)
- **summary-ef25e3a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/summary-ef25e3a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/summary-ef25e3a6.log.tar.gz)
- **left_processes-ef25e3a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/left_processes-ef25e3a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/left_processes-ef25e3a6.log.tar.gz)
- **error-ef25e3a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/error-ef25e3a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/error-ef25e3a6.log.tar.gz)
- **2024_02_05__10_55_09_582.sct-ef25e3a6.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/2024_02_05__10_55_09_582.sct-ef25e3a6.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/2024_02_05__10_55_09_582.sct-ef25e3a6.log.gz)
- **2024_02_05__18_00_57_130.sct-ef25e3a6.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/2024_02_05__18_00_57_130.sct-ef25e3a6.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/2024_02_05__18_00_57_130.sct-ef25e3a6.log.gz)
- **loader-set-ef25e3a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/loader-set-ef25e3a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/loader-set-ef25e3a6.tar.gz)
- **monitor-set-ef25e3a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/monitor-set-ef25e3a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ef25e3a6-cad6-44ea-a479-d3396fdb7bb8/20240206_015514/monitor-set-ef25e3a6.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-50gb-3days-test-restart-then-repair/4/)
[Argus](https://argus.scylladb.com/test/2d42e52b-b135-4d64-8f05-4f26cf8c993a/runs?additionalRuns[]=ef25e3a6-cad6-44ea-a479-d3396fdb7bb8)
</details>

**Comment by asias** [comment] 2024-02-06 08:48
> I'm facing this issue after two of my nodes became unreachable. I tried to change the seed node, did a rolling restart and tried nodetool removenode on one of the nodes that is down. I can't add new nodes to the cluster since it says one of the down nodes is in UNKNOWN state.
> 
> I'm using scylla 5.2.11. Is there anyway I can at least join new nodes in my cluster?

First, when a node is unreachable. It is much better to run the replace a dead procedure than running removenode. When more than one nodes are down, you can use ignore_dead_nodes_for_replace option to ignore the peer down node when running replace. With replace, you can add 2 more nodes back.

**Comment by jarPotato** [comment] 2024-02-07 01:25
I tried replace node procedure with the two config params you mentioned, but faced an error that looked like #13865 
But debugging that issue nudged me towards the [Raft manual recovery procedure](https://opensource.docs.scylladb.com/stable/architecture/raft.html#raft-manual-recovery-procedure) guide, using which I was able to recover my cluster! (removenode worked when all UN nodes where in recovery mode)

Thank you helping me out @asias!

**Comment by asias** [comment] 2024-02-07 01:27
On Wed, Feb 7, 2024, 09:25 Mustafa ***@***.***> wrote:

> I tried replace node procedure with the two config params you mentioned,
> but faced an error that looked like #13865
> <https://github.com/scylladb/scylladb/issues/13865>
> But debugging that issue nudged me towards the Raft manual recovery
> procedure
> <https://opensource.docs.scylladb.com/stable/architecture/raft.html#raft-manual-recovery-procedure>
> guide, using which I was able to recover my cluster! (removenode worked
> when all UN nodes where in recovery mode)
>
> Thank you helping me out @asias <https://github.com/asias>!
>

Good to hear! You are welcome.

**Closed** 2024-03-27 11:09 UTC
Labels: area/service levels
