### ISSUE TITLE
LWT-write with null clustering column crashes Scylla

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylladb#11954] opened 2022-11-11 12:53 UTC
*Installation details*
Scylla version: 5.0.5 and 5.1.0-rc4 (latest)

Writes using LWT and a `null` clustering column crashes Scylla and dumps core. Same non-LWT write is properly rejected.

```cql
CREATE KEYSPACE ks WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1};
CREATE TABLE ks.tbl (pk text, ck text, data text, PRIMARY KEY(pk,ck));
INSERT INTO ks.tbl (pk , ck , data ) VALUES ( 'a', NULL, 'data');
-- InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid null value in condition for a key column"
INSERT INTO ks.tbl (pk , ck , data ) VALUES ( 'a', NULL, 'data') IF NOT EXISTS; 
-- crash
```

**Comment by nyh** [comment] 2022-11-13 14:16
The regular insert cases was fixed with issue #7852, and we have a test for it in test/cql-pytest, `test_null.py`::`test_insert_null_key` so as you noticed it's properly reject.

The LWT (`IF NOT EXISTS`) variant of the same test is unfortunately missing, so we didn't notice this bug. Here is a reproducer we can add to `test_null.py`. It currently passes on Cassandra and crashes Scylla:

```python
# Same as test_insert_null_key() above, just adds IF NOT EXISTS and
# reproduces issue #11954.
def test_insert_null_key_lwt(cql, table1):
    s = unique_key_string()
    with pytest.raises(InvalidRequest, match='null value'):
        cql.execute(f"INSERT INTO {table1} (p,c) VALUES ('{s}', null) IF NOT EXISTS")
    with pytest.raises(InvalidRequest, match='null value'):
        cql.execute(f"INSERT INTO {table1} (p,c) VALUES (null, '{s}') IF NOT EXISTS")
    # Try the same thing with prepared statement, where a "None" stands for
    # a null. Note that this is completely different from UNSET_VALUE - only
    # with the latter should the insertion be ignored.
    stmt = cql.prepare(f"INSERT INTO {table1} (p,c) VALUES (?, ?) IF NOT EXISTS")
    with pytest.raises(InvalidRequest, match='null value'):
        cql.execute(stmt, [s, None])
    with pytest.raises(InvalidRequest, match='null value'):
        cql.execute(stmt, [None, s])
```

**Comment by nyh** [comment] 2022-11-15 09:59
In PR #11982 I added a reproducing test/cql-pytest for this bug, `test_null.py::test_insert_null_key_lwt`.
The test is currently `skip`ed, because it crashes Scylla, so remove this skip mark to test a fix to this bug.

**Closed** 2022-11-27 14:40 UTC
Labels: bug, high, CQL, lwt

**Comment by avikivity** [comment] 2022-12-04 13:04
Backported to 5.0, 5.1.
