### ISSUE TITLE
test_tablets.test_topology_changes: compaction not disabled on table test.test during TRUNCATE

### ISSUE THREAD

**Issue by Jadw1** [scylladb/scylladb#20091] opened 2024-08-09 13:08 UTC
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10833/testReport/junit/(root)/test_tablets/Tests___Unit_Tests___test_topology_changes_dev_5/

```
manager = <test.pylib.manager_client.ManagerClient object at 0x7f7ab14fad20>

    @pytest.mark.asyncio
    async def test_topology_changes(manager: ManagerClient):
        logger.info("Bootstrapping cluster")
        servers = await manager.servers_add(3)
    
        cql = manager.get_cql()
        await cql.run_async("CREATE KEYSPACE test WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1} AND tablets = {'initial': 32};")
        await cql.run_async("CREATE TABLE test.test (pk int PRIMARY KEY, c int);")
    
        logger.info("Populating table")
    
        keys = range(256)
        await asyncio.gather(*[cql.run_async(f"INSERT INTO test.test (pk, c) VALUES ({k}, {k});") for k in keys])
        expected_rows = await cql.run_async("SELECT * FROM test.test;")
    
        async def check():
            logger.info("Checking table")
            rows = await cql.run_async("SELECT * FROM test.test;")
            assert rows == expected_rows
            assert len(rows) == len(keys)
            for r in rows:
                assert r.c == r.pk
    
        await inject_error_on(manager, "tablet_allocator_shuffle", servers)
    
        logger.info("Adding new server")
        await manager.server_add()
    
        await check()
    
        logger.info("Adding new server")
        await manager.server_add()
    
        await check()
        time.sleep(5) # Give load balancer some time to do work
        await check()
    
        await manager.decommission_node(servers[0].server_id)
    
        await check()
    
>       await cql.run_async("DROP KEYSPACE test;")
E       cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.36.98.22:9042 datacenter1>: ConnectionShutdown('Connection to 127.36.98.22:9042 was closed'), <Host: 127.36.98.26:9042 datacenter1>: <Error from server: code=0000 [Server error] message="group [cc3c6421-5635-11ef-af7c-ffc20843cccf] raft operation [read_barrier] timed out, there is no raft quorum, total voters count 4, alive voters count 2, dead voters [127.36.98.40,127.36.98.22]">, <Host: 127.36.98.61:9042 datacenter1>: <Error from server: code=0000 [Server error] message="group [cc3c6421-5635-11ef-af7c-ffc20843cccf] raft operation [read_barrier] timed out, there is no raft quorum, total voters count 4, alive voters count 2, dead voters [127.36.98.22,127.36.98.40]">, <Host: 127.36.98.40:9042 datacenter1>: ConnectionException('Host has been marked down or removed'), <Host: 127.36.98.107:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})

test/topology_experimental_raft/test_tablets.py:237: NoHostAvailable
```

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10833/artifact/testlog/x86_64/dev/failed_test/test_topology_changes.5/scylla-3871.log
```
ERROR 2024-08-09 12:57:50,500 [shard 0: gms] on_internal_error - compaction not disabled on table test.test during TRUNCATE, at: /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x554d8e /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x5553b0 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x5556b8 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3a0767 0x1631230 0x13ad94d 0x130a00e 0x13259e1 0x1068450 0x1068306 0x106821a 0x106816b /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x4426ed /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x44264f 0x10680c9 0x133c9ea 0x10389aa /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3eb8bf /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3ecc8a /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3edd17 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3ed218 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x361036 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x360419 0xfdd201 0x101bca0 0xfdbfaf /lib64/libc.so.6+0x2a087 /lib64/libc.so.6+0x2a14a 0xfdaaa4
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Aborting on shard 0, in scheduling group gossip.
Backtrace:
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x4153b4
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3de565
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x4095c6
  /lib64/libc.so.6+0x40cff
  /lib64/libc.so.6+0x994a3
  /lib64/libc.so.6+0x40c4d
  /lib64/libc.so.6+0x28901
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3a07ea
  0x1631230
  0x13ad94d
  0x130a00e
  0x13259e1
  0x1068450
  0x1068306
  0x106821a
  0x106816b
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x4426ed
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x44264f
  0x10680c9
  0x133c9ea
  0x10389aa
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3eb8bf
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3ecc8a
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3edd17
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3ed218
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x361036
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x360419
  0xfdd201
  0x101bca0
  0xfdbfaf
  /lib64/libc.so.6+0x2a087
  /lib64/libc.so.6+0x2a14a
  0xfdaaa4
```

**Comment by Jadw1** [comment] 2024-08-09 13:09
The test failed in CI for https://github.com/scylladb/scylladb/pull/20055. The PR looks entirely unrelated.

**Comment by mykaul** [comment] 2024-08-11 07:25
Dup of https://github.com/scylladb/scylladb/issues/19707 ?

**Comment by lersek** [comment] 2024-08-15 09:40
I'm reopening this issue because I was just [hit by it](https://github.com/scylladb/scylladb/pull/20159#issuecomment-2290823823), in an entirely unrelated patch set. (And the same test case passed fine for me locally.)

**Comment by mykaul** [comment] 2024-08-15 09:45
Do we have a backtrace for this? I'm not sure why we crash, this should be avoided. TRUNCATE may succeed or fail or whatnot, crash is less optimal.

**Comment by lersek** [comment] 2024-08-15 10:06
It's not as much as an uncontrolled crash but an exception being deliberately thrown (and then not caught); AFAICT. The output does seem to contain a backtrace (of sorts); please see [here](https://github.com/scylladb/scylladb/pull/20159#issuecomment-2291007689) and (originally) [here](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10920/artifact/testlog/x86_64/dev/failed_test/test_topology_changes.5/scylla-3864.log).

**Comment by lersek** [comment] 2024-08-15 10:07
... or, well, deliberate call to `::abort()`.

**Comment by lersek** [comment] 2024-08-15 10:14
This looks like a relatively recent symptom / issue report (~1 week old?), so bisection (against CI) might help. (... It also might not, if the problem is not deterministic...)

**Comment by lersek** [comment] 2024-08-15 10:21
I agree this is a duplicate of #19707. @mykaul Yaniv, can you please re-close this with the proper resolution again? (I'm not sure if I can do that properly.) Thanks!

**Closed** 2024-08-15 10:23 UTC

**Comment by lersek** [comment] 2024-08-15 10:38
Here's an idea: *unless* `test_topology_changes` is specifically designed to exercise tablets, can we at least modify `test_topology_changes` such that it create the keyspace `test` with tablets disabled? Because, if tablets vs. vnodes is irrelevant for `test_topology_changes`, then by switching it over to vnodes will at least let us avoid #19707 / #16411.
