### ISSUE TITLE
Error sending messages automatically on the Scylla University website

### ISSUE THREAD

**Issue by NikiYani** [scylladb/scylladb#21140] opened 2024-10-16 10:13 UTC
The problem has already been sent to university@scylladb.com

Good afternoon. I logged in through my Github account and should have received a confirmation email, but it didn’t arrive. Can you resend? Or fix sending emails?

Thank you in advance)

**Comment by mykaul** [comment] 2024-10-16 10:35
CC @tzach , @guy9 

I think the forum is a better venue for such questions/issues.

**Comment by tzach** [comment] 2024-10-17 05:33
Yes, the issue is not related to this repo.
Closing.

**Closed by tzach** 2024-10-17 05:33 UTC
