### ISSUE TITLE
CQL using TTL = 0 (meant to disable TTL) doesn't work for tables with default_time_to_live > 0

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#9842] opened 2021-12-26 21:58 UTC
Scenario

```
create keyspace ks with replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};

create table ks.tb ( k int primary key, v int) with default_time_to_live = 120 and gc_grace_seconds = 120;

insert into ks.tb (k,v) values (10,10) using timestamp 2 and ttl 0; 
select k,v,writetime(v),ttl(v) from ks.tb where k=10;
```

the result on scylla 4.5.2

```
insert into ks.tb (k,v) values (10,10) using timestamp 2 and ttl 0; 
select k,v,writetime(v),ttl(v) from ks.tb where k=10;

 k  | v  | writetime(v) | ttl(v)
----+----+--------------+--------
 10 | 10 |            2 |    119

(1 rows)
cqlsh> 
```

The expected output is 

```
cqlsh> insert into ks.tb (k,v) values (10,10) using timestamp 2 and ttl 0; 
cqlsh> select k,v,writetime(v),ttl(v) from ks.tb where k=10;

 k  | v  | writetime(v) | ttl(v)
----+----+--------------+--------
 10 | 10 |            2 |   null

(1 rows)
cqlsh> 
```

(tested on cassandra 3.11.3, 3.11.11)

**Comment by slivne** [comment] 2021-12-26 21:59
(maybe a regression needs to be validated)

**Comment by nyh** [comment] 2021-12-27 09:16
I reproduced this issue in a cql-pytest and sent it in a patch tot he mailing list, titled `[PATCH] cql-pytest: add a couple of default-TTL tests`.

**Comment by nyh** [comment] 2022-12-08 13:04
Closing as a duplicate of #6447.

**Closed by nyh** 2022-12-08 13:04 UTC
Labels: bug, cassandra 3.x compatibility
