### ISSUE TITLE
test.py seem to lose stderr

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#5685] opened 2020-01-30 18:29 UTC
git id: a16cb0071946f6a08d77e26c7eaff092ea375a4e

    $ ./test.py --mode=dev boost/aggregate_fcts_test
     
     
     
     ================================================================================
    [N/TOTAL] TEST                                                 MODE   RESULT  
    ------------------------------------------------------------------------------
    [1/1]     boost/aggregate_fcts_test                            dev    [ FAIL ]
    ------------------------------------------------------------------------------
    The following test(s) have failed: boost/aggregate_fcts_test
    Output of build/dev/test/boost/aggregate_fcts_test --report_level=no --logger=HRF,test_suite:XML,test_suite,/home/xemul/src/scylla/testlog/dev/xml/aggregate_fcts_test.1.xunit.xml -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0:
    random-seed=2983006108
    Running 6 test cases...
    Entering test module "test/boost/aggregate_fcts_test.cc"
    test/boost/aggregate_fcts_test.cc(0): Entering test case "test_aggregate_avg"
    
    ------------------------------------------------------------------------------
    Summary: 1 of the total 1 tests failed

In logs

    $ cat testlog/dev/aggregate_fcts_test.1.log 
    random-seed=2983006108
    Running 6 test cases...
    Entering test module "test/boost/aggregate_fcts_test.cc"
    test/boost/aggregate_fcts_test.cc(0): Entering test case "test_aggregate_avg"

While after manual run

    $ build/dev/test/boost/aggregate_fcts_test --report_level=no --logger=HRF,test_suite:XML,test_suite,/home/xemul/src/scylla/testlog/dev/xml/aggregate_fcts_test.1.xunit.xml -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0
    random-seed=711057079
    Running 6 test cases...
    Entering test module "test/boost/aggregate_fcts_test.cc"
    test/boost/aggregate_fcts_test.cc(0): Entering test case "test_aggregate_avg"
    unknown location(0): fatal error: in "test_aggregate_avg": signal: SIGSEGV, si_code: 0 (memory access violation at address: 0x00000080)
    /home/xemul/src/scylla/seastar/src/testing/seastar_test.cc(37): last checkpoint
    Test is aborted
    test/boost/aggregate_fcts_test.cc(0): Leaving test case "test_aggregate_avg"; testing time: 297us
    Test is aborted
    Leaving test module "test/boost/aggregate_fcts_test.cc"; testing time: 331us
    Segmentation fault

**Comment by kostja** [comment] 2020-02-12 20:38
Is there an easy way to reproduce this?

```
kostja@hulk ~/work/scylla/scylla
 % git diff             
diff --git a/test/boost/query_processor_test.cc b/test/boost/query_processor_test.cc
index 3dd396d95..3b4d4c76f 100644
--- a/test/boost/query_processor_test.cc
+++ b/test/boost/query_processor_test.cc
@@ -68,6 +68,8 @@ SEASTAR_TEST_CASE(test_execute_internal_insert) {
 
 SEASTAR_TEST_CASE(test_execute_internal_delete) {
     return do_with_cql_env([] (auto& e) {
+        std::cerr << "stderr marker in the log" << std::endl;
+        fprintf(stderr, "fprintf marker in the log\n");
         auto& qp = e.local_qp();
         return qp.execute_internal("create table ks.cf (p1 varchar, c1 int, r1 int, PRIMARY KEY (p1, c1));").then([](auto rs) {
             BOOST_REQUIRE(rs->empty());
kostja@hulk ~/work/scylla/scylla
 % ./test.py query_processor 
================================================================================
[N/TOTAL] TEST                                                 MODE   RESULT  
------------------------------------------------------------------------------
[1/1]     boost/query_processor_test                           dev    [ PASS ]
------------------------------------------------------------------------------
kostja@hulk ~/work/scylla/scylla
 % grep marker testlog/dev/*.log 
stderr marker in the log
fprintf marker in the log

```

**Comment by xemul** [comment] 2020-02-12 22:41
Make test artificially fail?

**Comment by xemul** [comment] 2020-06-03 10:53
Steps to reproduce.

1. get 536ab4ebe40266624baeb2f271481b8feb35f71a
2. apply a BUG

```
      diff --git a/row_cache.cc b/row_cache.cc
      index 15287a5fa..b971c4263 100644
      --- a/row_cache.cc
      +++ b/row_cache.cc
      @@ -284,7 +284,7 @@ class partition_range_cursor final {
           // Strong exception guarantees.
           bool advance_to(dht::ring_position_view pos) {
               auto cmp = cache_entry::compare(_cache.get()._schema);
      -        if (cmp(_end_pos, pos)) { // next() may have moved _start_pos past the _end_pos.
      +        if (!cmp(_end_pos, pos)) { // next() may have moved _start_pos past the _end_pos.
                   _end_pos = pos;
               }
               _end = _cache.get()._partitions.lower_bound(_end_pos, cmp);
```

3. build
4. run `test.py --mode=dev boost/row_cache_test`. The output would be like

```
    === TEST.PY TEST OUTPUT ===
    random-seed=1447248886
    Running 58 test cases...
    Entering test module "test/boost/row_cache_test.cc"
    test/boost/row_cache_test.cc(0): Entering test case "test_cache_delegates_to_underlying"
    row_cache_test: partition_version.hh:232: partition_version* partition_version_ref::operator->(): 
    Assertion `_version' failed.
    === TEST.PY SUMMARY START ===
    Test exited with code -6
```
    
    === TEST.PY SUMMARY END ===

5. Run `./build/dev/test/boost/row_cache_test`. The output would be like

 ```
   random-seed=2909578614
    Running 58 test cases...
    row_cache_test: partition_version.hh:232: partition_version* partition_version_ref::operator->(): 
    Assertion `_version' failed.
    unknown location(0): fatal error: in "test_cache_delegates_to_underlying": signal: SIGABRT 
    (application abort requested)
```

The line ` unknown location(0): fatal error: in "test_cache_delegates_to_underlying": signal: SIGABRT (application abort requested)` is missing in test.py output

**Comment by espindola** [comment] 2020-06-10 01:00
Another case where it looks like stderr is missing:
https://jenkins.scylladb.com/job/scylla-master/job/next/2086/consoleText

**Comment by bhalevy** [comment] 2020-06-10 06:11
> Another case where it looks like stderr is missing:
> https://jenkins.scylladb.com/job/scylla-master/job/next/2086/consoleText

@espindola in that case the full log kept locally under testlog/$mode is copied to jenkins artifact dir: https://jenkins.scylladb.com/job/scylla-master/job/next/2086/artifact/testlog/dev/row_cache_test.274.log and seems to contain everything.

In the case that @xemul is describing it looks like the saved log is truncated, with this part missing:
```
unknown location(0): fatal error: in "test_aggregate_avg": signal: SIGSEGV, si_code: 0 (memory access violation at address: 0x00000080)
/home/xemul/src/scylla/seastar/src/testing/seastar_test.cc(37): last checkpoint
Test is aborted
test/boost/aggregate_fcts_test.cc(0): Leaving test case "test_aggregate_avg"; testing time: 297us
Test is aborted
Leaving test module "test/boost/aggregate_fcts_test.cc"; testing time: 331us
Segmentation fault 
```

**Comment by bhalevy** [comment] 2020-06-10 06:22
Apparently, boost prints some of these messages to stdout, not to stderr...
```
$ ./build/dev/test/boost/row_cache_test
random-seed=3713542992
Running 58 test cases...
row_cache_test: partition_version.hh:232: partition_version* partition_version_ref::operator->(): Assertion `_version' failed.
unknown location(0): fatal error: in "test_cache_delegates_to_underlying": signal: SIGABRT (application abort requested)
/local/home/bhalevy/dev/scylla/seastar/src/testing/seastar_test.cc(43): last checkpoint
Killed
bhalevy@lt scylla$ ./build/dev/test/boost/row_cache_test 2> /dev/null
random-seed=2793093725
Running 58 test cases...
unknown location(0): fatal error: in "test_cache_delegates_to_underlying": signal: SIGABRT (application abort requested)
/local/home/bhalevy/dev/scylla/seastar/src/testing/seastar_test.cc(43): last checkpoint
Killed
bhalevy@lt scylla$ ./build/dev/test/boost/row_cache_test 1> /dev/null
row_cache_test: partition_version.hh:232: partition_version* partition_version_ref::operator->(): Assertion `_version' failed.
Killed
```

**Comment by kostja** [comment] 2020-07-07 18:33
Both stdout and stderr are captured by test.py and redirected to the same log file. If stdout is not a terminal, it's not line-buffered, so the message is lost in libstdc buffer. test.py can not control this. The fix is to make sure boost tests don't buffer stdout (setvbuf/std::setbuf).

**Comment by espindola** [comment] 2020-07-07 19:50
Test.py could do whatever it is that "stdbuf -oL" does to set stdout to
line buffering.

**Comment by kostja** [comment] 2020-07-07 21:40
stdbuf uses LD_PRELOAD to set needed buffering on the invoked program:
https://github.com/coreutils/coreutils/blob/master/src/libstdbuf.c
There is a less hacky fix with opening a pty in test.py, but it's quite a bit of code.
It just isn't clear why row_cache_test shouldn't apply a single line fix instead with setvbuf(), or stop using stdout for critical output.

**Comment by kostja** [comment] 2020-07-21 21:07
@espindola @xemul so what's your resolution? Should I hack in LD-PRELOAD, create a pseudo-terminal, or maybe a one line fix for row_cache_test is not such a bad idea?

**Comment by nyh** [comment] 2020-07-21 21:33
There's more than one way to do this (as the Perl saying goes)... Another way you didn't mention is not to clone stdbuf, but instead, just use it! To run a test xyz, don't invoke "xyz" but rather "stdbuf  -o0 xyz". Fairly trivial and hopefully just a tiny slowdown.

Yes another thing we can do is to link the tests with a trivial object file redefining abort() or signal() to fflush(stdout) before really aborting. I think this would have solved this bug.

This could have also been fixed within Boost. It is (if I understand correctly) boost code which does an unclean abort, and it could have done a fflush(stdout) before (or could have just called a normal exit()... Why not?). I'm pretty sure we're not the only ones redirecting Boost test output, and pretty sure a lot of test code writes to stdout (and as the examples above show - even Boost itself writes to stdout).

**Comment by espindola** [comment] 2020-07-21 21:43
I think using stdbuf is my preference too.
After that it would be the other options in test.py.
My least favourite option is changing row_cache_test. The reason being that, even if that is the only problematic test now, that might not always be the case.

**Comment by kostja** [comment] 2020-07-21 21:53
OK, I checked and stdbuf is part of GNU coreutils. It's unlikely there is a distro that doesn't have it. My value judgement is that using stdbuf is a hack and should be avoided. It's not composable: if later we want to add another prefix tool, like taskset, or another tool that adds another LD_PRELOAD, or valgrind, we may be in trouble. 
Another issue is that I should perhaps stop keeping Microsoft Windows in mind, or some other Unix, which we will perhaps never port to.

**Comment by xemul** [comment] 2020-07-22 12:56
My preference is to stop writing tests output on the console :) (for Jenkins we may have an option to do it, v of course)

Rationale: it's impossible to find anything useful in printed logs, I always go and read/grep/sed the log files. Seeing tens and hundreds of lines on the screen is just annoying, because the needed info -- names of failed tests -- is above them, so one needs to scroll the terminal up, which is time consuming sometimes, and one has to look carefully not to scroll to high.

**Comment by slivne** [comment] 2021-01-24 21:48
@kostja was this resolved ?

**Comment by kostja** [comment] 2021-01-25 07:51
No.

**Comment by kostja** [comment] 2023-07-24 16:14
Given it has not been impacting anyone else since, and given the wrong synopsys (it's not test.py problem, it's boost test / expectations issue with line vs block buffering), I think this should be closed with "Won't fix". @xemul

**Closed** 2023-07-24 17:04 UTC
Labels: test.py

**Comment by nyh** [comment] 2023-07-25 10:35
There's something I don't understand about this issue. The original complaint was that messages in stderr were lost. But somehow the later discussion was about stdout (not stderr) being buffered? Note that stderr is always unbuffered, even if redirected.
Maybe the problem is that Boost writes the error messages to stdout and not stderr, and that's why it got buffered - and lost on a crash? Maybe this can be configured?

I think it's a mistake to close the issue just because we stopped caring about Boost tests and created better (Python-based) test frameworks. We still have over 100,000 lines of test code in tes/boost.cc - that's more than twice the number of lines in test/cql-pytest and 25 times the number of lines in test/topology* :-)

**Comment by kostja** [comment] 2023-07-25 14:26
> There's something I don't understand about this issue. The original complaint was that messages in stderr were lost. But somehow the later discussion was about stdout (not stderr) being buffered? Note that stderr is always unbuffered, even if redirected. Maybe the problem is that Boost writes the error messages to stdout and not stderr, and that's why it got buffered - and lost on a crash? Maybe this can be configured?
> 
> I think it's a mistake to close the issue just because we stopped caring about Boost tests and created better (Python-based) test frameworks. We still have over 100,000 lines of test code in tes/boost.cc - that's more than twice the number of lines in test/cql-pytest and 25 times the number of lines in test/topology* :-)

Yes, exactly, the issue is with boost output. It's not that we stopped caring, it's that the output is lost in some very specific cases which don't affect many people (and there is a workaround - run the test directly from the command line).
