### ISSUE TITLE
A select-query of a frozen-tuple column fails with: "ValueError: value must be less than number of nanoseconds in a day (86400000000000)"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#14645] opened 2023-07-11 16:36 UTC
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

Gemini load created a table with a schema of:
```
CREATE TABLE ks1.table1 (
    pk0 varint,
    pk1 tinyint,
    ck0 float,
    ck1 tinyint,
    col0 ascii,
    col1 timeuuid,
    col10 text,
    col11 text,
    col2 ascii,
    col3 frozen<udt_363317622>,
    col4 inet,
    col5 decimal,
    col6 duration,
    col7 float,
    col8 frozen<tuple<tinyint, tinyint, duration, time, timeuuid>>,
    col9 double,
    PRIMARY KEY ((pk0, pk1), ck0, ck1)
) WITH CLUSTERING ORDER BY (ck0 ASC, ck1 ASC)
```
Trying to select `col8`, it failed with a ValueError.

failure output:
```
cqlsh> SELECT col8 FROM ks1.table1 LIMIT 1;
Traceback (most recent call last):
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/protocol.py", line 755, in recv_results_rows
    self.parsed_rows = [
                       ^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/protocol.py", line 756, in <listcomp>
    tuple(ctype.from_binary(val, protocol_version)
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/protocol.py", line 756, in <genexpr>
    tuple(ctype.from_binary(val, protocol_version)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/cqltypes.py", line 312, in from_binary
    return cls.deserialize(byts, protocol_version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/cqltypes.py", line 789, in deserialize
    return cls.deserialize_safe(byts, protocol_version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/cqltypes.py", line 934, in deserialize_safe
    values.append(col_type.from_binary(item, proto_version))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/cqltypes.py", line 312, in from_binary
    return cls.deserialize(byts, protocol_version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/cqltypes.py", line 732, in deserialize
    return util.Time(int64_unpack(byts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/util.py", line 955, in __init__
    self._from_timestamp(value)
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/util.py", line 1002, in _from_timestamp
    raise ValueError("value must be less than number of nanoseconds in a day (%d)" % Time.DAY)
ValueError: value must be less than number of nanoseconds in a day (86400000000000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/protocol.py", line 763, in recv_results_rows
    self.column_types[i].from_binary(row[i], protocol_version)
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/cqltypes.py", line 312, in from_binary
    return cls.deserialize(byts, protocol_version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/cqltypes.py", line 789, in deserialize
    return cls.deserialize_safe(byts, protocol_version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/cqltypes.py", line 934, in deserialize_safe
    values.append(col_type.from_binary(item, proto_version))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/cqltypes.py", line 312, in from_binary
    return cls.deserialize(byts, protocol_version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/cqltypes.py", line 732, in deserialize
    return util.Time(int64_unpack(byts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/util.py", line 955, in __init__
    self._from_timestamp(value)
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/util.py", line 1002, in _from_timestamp
    raise ValueError("value must be less than number of nanoseconds in a day (%d)" % Time.DAY)
ValueError: value must be less than number of nanoseconds in a day (86400000000000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/share/cassandra/libexec/cqlsh.py", line 1100, in perform_simple_statement
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/cluster.py", line 5151, in result
    raise self._final_exception
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/connection.py", line 1266, in process_msg
    response = decoder(header.version, self.user_type_map, stream_id,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/protocol.py", line 1196, in decode_message
    msg = msg_class.recv_body(body, protocol_version, user_type_map, result_metadata)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/protocol.py", line 744, in recv_body
    msg.recv(f, protocol_version, user_type_map, result_metadata)
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/protocol.py", line 730, in recv
    self.recv_results_rows(f, protocol_version, user_type_map, result_metadata)
  File "/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.0.zip/cassandra/protocol.py", line 765, in recv_results_rows
    raise DriverException('Failed decoding result column "%s" of type %s: %s' % (self.column_names[i],
cassandra.DriverException: Failed decoding result column "col8" of type frozen<tuple<tinyint, tinyint, duration, time, timeuuid>>: value must be less than number of nanoseconds in a day (86400000000000)
```
## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1039-aws
Scylla version (or git commit hash): `5.4.0~dev-20230703.1ab2bb69b8a6` with build-id `1054adfa55f238441c3044e6213fd02d31d43279`

Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- gemini-1tb-10h-master-oracle-db-node-05f874bf-1 (18.208.140.197 | 10.12.10.147) (shards: 14)
- gemini-1tb-10h-master-db-node-05f874bf-4 (34.233.121.232 | 10.12.8.197) (shards: 14)
- gemini-1tb-10h-master-db-node-05f874bf-3 (52.91.3.189 | 10.12.11.74) (shards: 14)
- gemini-1tb-10h-master-db-node-05f874bf-2 (54.209.17.161 | 10.12.10.149) (shards: 14)
- gemini-1tb-10h-master-db-node-05f874bf-1 (3.95.57.105 | 10.12.9.168) (shards: 14)

OS / Image: `` (aws: undefined_region)

Test: `gemini-1tb-10h`
Test id: `05f874bf-3ec8-4a33-97d9-c80a309f62bd`
Test name: `scylla-master/gemini-/gemini-1tb-10h`
Test config file(s):

- [gemini-1tb-10h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/61bd88960a0768f4429aabe6f4679081bab2f72e/test-cases/gemini/gemini-1tb-10h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 05f874bf-3ec8-4a33-97d9-c80a309f62bd`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=05f874bf-3ec8-4a33-97d9-c80a309f62bd)
- Show all stored logs command: `$ hydra investigate show-logs 05f874bf-3ec8-4a33-97d9-c80a309f62bd`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/223/)
[Argus](https://argus.scylladb.com/test/1d37c1f1-6c7b-43f1-a2c5-6eb30b0887d2/runs?additionalRuns[]=05f874bf-3ec8-4a33-97d9-c80a309f62bd)
</details>

**Comment by cvybhu** [comment] 2023-07-12 11:43
It looks like we allow inserting `time` values larger than `86400000000000`.

It works with rust driver:
```rust
    session
        .query("CREATE TABLE IF NOT EXISTS tab (p int, t time, primary key (p))", ())
        .await
        .unwrap();

    let time: i64 = 86400000000001;
    session.query("INSERT INTO tab (p, t) VALUES (0, ?)", (time,)).await.unwrap();
```

Then trying to select the value causes an error because it's out of bounds accepted by `cqlsh`

**Comment by cvybhu** [comment] 2023-07-12 11:48
It's interesting that Gemini generated an invalid `time` value. Is this supposed to happen?

**Comment by cvybhu** [comment] 2023-07-12 12:33
There was a recent change in how Gemini generates `time` values: https://github.com/scylladb/gemini/pull/359

Previously it was:
```go
// genValue

case TYPE_TIME:
    return utils.RandTime(r).UnixNano()
		
...

func RandTime(rnd *rand.Rand) time.Time {
	min := time.Date(1970, 1, 0, 0, 0, 0, 0, time.UTC).Unix()
	max := time.Date(2024, 1, 0, 0, 0, 0, 0, time.UTC).Unix()

	sec := rnd.Int63n(max-min) + min
	return time.Unix(sec, 0).UTC()
}
```

Now it's:
```go
// genValue

case TYPE_TIME:
    return utils.RandTime(r)
		
...

// RandTime generates time in string representation
// it is done in such way because we wanted to make JSON statement to work
// but scylla supports only string representation of time in JSON format
func RandTime(rnd *rand.Rand) int64 {
	return rnd.Int63()
}
```

**Comment by cvybhu** [comment] 2023-07-12 14:29
The original code also generated out-of-range values. But why wasn't this a problem before?

```go
package main

import "fmt"
import "time"
import "math/rand"

func RandTime() time.Time {
	min := time.Date(1970, 1, 0, 0, 0, 0, 0, time.UTC).Unix()
	max := time.Date(2024, 1, 0, 0, 0, 0, 0, time.UTC).Unix()

	sec := rand.Int63n(max-min) + min
	return time.Unix(sec, 0).UTC()
}

func main() {
    rand.Seed(time.Now().UnixNano())
    t := RandTime().UnixNano()

    fmt.Println("TIME: ", t)

    if t < 0 || t > 86399999999999 {
        fmt.Println("OUT OF RANGE!")
    }
}
```

It generates an out-of-range value every single time:

```
jancio@janciolap ~/c/gotest> go run .
TIME:  647135675000000000
OUT OF RANGE!
jancio@janciolap ~/c/gotest> go run .
TIME:  253104895000000000
OUT OF RANGE!
jancio@janciolap ~/c/gotest> go run .
TIME:  1474165754000000000
OUT OF RANGE!
```

**Comment by cvybhu** [comment] 2023-07-12 14:33
Ah, the PR that changed `time` generation also enabled using `time` values in tests:

![image](https://github.com/scylladb/scylladb/assets/36861778/5b4c83f2-ee0d-4612-8f0c-b3f46a701773)

**Comment by cvybhu** [comment] 2023-07-12 14:36
In that case we have to fix the generation of `time` values in Gemini, I will open a PR.

**Comment by dkropachev** [comment] 2023-07-12 19:41
I would suggest to take a look at addressing this issue in Scylla it self.

**Comment by cvybhu** [comment] 2023-07-12 19:46
> I would suggest to take a look at addressing this issue in Scylla it self.

There's a separate issue for Scylla validation:  #14667.
We're not sure if we should allow such values or not. Cassandra allows them. It needs further consideration.

This issue was about failure in a Gemini run, so I think this was addressed.
AFAIU Gemini isn't supposed to generate invalid values, so it's an independent problem.

**Comment by nyh** [comment] 2023-07-13 07:16
Closing this issue. The error that @yarongilor came from cqlsh - it is ugly but caused by the fact that this data (`time` column greater than 24 hours) is illegal. It was a Gemini bug (fixed by https://github.com/scylladb/gemini/pull/389) that this illegal data was entered into the database, and a Scylla bug - #14667 - why this data was accepted.
So I think there's no other content left in this issue.

**Closed by nyh** 2023-07-13 07:16 UTC
Labels: CQL, P1
