### ISSUE TITLE
5.4: test_commitlog_delete_when_over_disk_limit failure

### ISSUE THREAD

**Issue by wprzytula** [scylladb/scylladb#19661] opened 2024-07-09 09:30 UTC
```
[Exception] - critical check dn <= nn has failed
 == [File] - test/boost/commitlog_test.cc
 == [Line] -348
```

logs:
[boost.commitlog_test.test_commitlog_delete_when_over_disk_limit.2.log](https://github.com/user-attachments/files/16141329/boost.commitlog_test.test_commitlog_delete_when_over_disk_limit.2.log)

**Comment by kbr-scylla** [comment] 2024-07-09 09:44
This failure was mentioned by @bhalevy in the past in another issue: https://github.com/scylladb/scylladb/issues/10527#issuecomment-1549688084

@wmitros you fixed that other issue -- do they have the same root cause?

**Comment by kbr-scylla** [comment] 2024-07-09 09:44
Commitlog test -- assigning to storage team

**Comment by wmitros** [comment] 2024-07-09 11:54
> This failure was mentioned by @bhalevy in the past in another issue: [#10527 (comment)](https://github.com/scylladb/scylladb/issues/10527#issuecomment-1549688084)
> 
> @wmitros you fixed that other issue -- do they have the same root cause?

Looks like the fix was not backported to 5.4 so it's most likely the same issue, maybe we should reconsider

**Comment by mykaul** [comment] 2024-07-11 11:59
> > This failure was mentioned by @bhalevy in the past in another issue: [#10527 (comment)](https://github.com/scylladb/scylladb/issues/10527#issuecomment-1549688084)
> > @wmitros you fixed that other issue -- do they have the same root cause?
> 
> Looks like the fix was not backported to 5.4 so it's most likely the same issue, maybe we should reconsider

@wmitros - indeed - which fix? https://github.com/scylladb/scylladb/pull/14610 ?!

**Comment by wmitros** [comment] 2024-07-11 14:06
> > > This failure was mentioned by @bhalevy in the past in another issue: [#10527 (comment)](https://github.com/scylladb/scylladb/issues/10527#issuecomment-1549688084)
> > > @wmitros you fixed that other issue -- do they have the same root cause?
> > 
> > 
> > Looks like the fix was not backported to 5.4 so it's most likely the same issue, maybe we should reconsider
> 
> @wmitros - indeed - which fix? #14610 ?!

Yes, this fix to the test. It's quite old so I was surprised when I saw it wasn't present in 5.4

**Comment by mykaul** [comment] 2024-07-11 14:08
> > > > This failure was mentioned by @bhalevy in the past in another issue: [#10527 (comment)](https://github.com/scylladb/scylladb/issues/10527#issuecomment-1549688084)
> > > > @wmitros you fixed that other issue -- do they have the same root cause?
> > > 
> > > 
> > > Looks like the fix was not backported to 5.4 so it's most likely the same issue, maybe we should reconsider
> > 
> > 
> > @wmitros - indeed - which fix? #14610 ?!
> 
> Yes, this fix to the test. It's quite old so I was surprised when I saw it wasn't present in 5.4

Indeed, that's why I put '?!' above. A bit odd.

**Comment by piodul** [comment] 2024-07-11 15:31
@wmitros please send a backport PR to 5.4. It's only a test fix and it affects CI stability, so it shouldn't be too controversial.

**Comment by piodul** [comment] 2024-07-11 15:36
@wprzytula please change the issue title to mention that it's about a failure on the 5.4 branch. Usually, such a bug report should mention which scylla version it is relevant to. By default, it is assumed that issues are about the master branch, so it was a bit confusing for me to see that we are talking about 5.4 here.

**Comment by wmitros** [comment] 2024-07-11 16:25
Adding a backport label didn't seem to work, posted https://github.com/scylladb/scylladb/pull/19706

**Comment by piodul** [comment] 2024-07-15 05:39
The backport PR was merged. Closing the issue.

**Closed by piodul** 2024-07-15 05:39 UTC
Labels: symptom/ci stability
