### ISSUE TITLE
Priority-based fair admission of writes

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#1926] opened 2016-12-12 13:11 UTC
Currently there is a single queue for commitlog writes. So writes to system tables may be blocked behind a long queue of user writes. We would like system writes to be served with higher priority than user writes though.

To solve this, we could have a separate queue for each priority group, and as new segments are made available, dequeue from queues fairly based on ratio of priority shares, taking mutation sizes into consideration. 

For example, assuming 80/20 share ratio between two non-empty queues, on average, for every 20 bytes pulled from one queue we would pull 80 bytes from the other.

When there is no competition, the queue which is active gets all the bandwidth.

The same mechanism would be employed when writes block on admission to memtable space, where we also have the streaming priority group. There, instead of waiting for commitlog segments, writes wait for dirty memory to be freed by the current memtable flush.

**Comment by tgrabiec** [comment] 2016-12-12 13:17
Streaming writes don't go through commitlog, so there is no problem in this layer. So there is no problem with streaming writes there. There still is in the dirty memory space.

**Comment by glommer** [comment] 2019-01-10 19:56
We have the same issue with multi-workload writes for per-user SLA: a heavy throughput class will cause the commitlog to block and increase latency for latency classes.

**Comment by kostja** [comment] 2024-05-02 20:43
Duplicate of https://github.com/scylladb/scylladb/issues/15566

**Closed by kostja** 2024-05-02 20:43 UTC
Labels: symptom/performance, area/stability, symptom/latency, area/commitlog
