### ISSUE TITLE
Using `--online-discard 0` flag in scylla_setup does not disable the online discard

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#21426] opened 2024-11-04 09:08 UTC
## Packages

Scylla version: `6.3.0~dev-20240921.cd861bc78881` with build-id `66f68fcba94a28c6d0267156866992dd3da6f7a0`

Kernel Version: `6.8.0-1016-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

I tried to setup scylla_raid_setup without online discard using `--online-discard` that was added by https://github.com/scylladb/scylladb/pull/9608.
It is performed by run command after Scylla install:
`sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme1n1 --setup-nic-and-disks --online-discard 0 --swap-directory`.

When I check if it is disabled - it is still enabled:
```
< t:2024-10-29 16:22:19,170 f:base.py         l:143  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.1.94>: Command "sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme1n1 --setup-nic-and-disks  --online-discard 0 --swap-directory / " finished with status 0
< t:2024-10-29 16:22:19,170 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.1.94>: Running command "cat /proc/mounts"...
< t:2024-10-29 16:22:19,174 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.1.94>: /dev/nvme1n1 /var/lib/scylla xfs rw,noatime,attr2,discard,inode64,logbufs=8,logbsize=32k,noquota 0 0
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- elasticity-test-ubuntu-db-node-92ed11ec-3 (3.252.201.235 | 10.4.1.137) (shards: 7)
- elasticity-test-ubuntu-db-node-92ed11ec-2 (54.247.230.24 | 10.4.1.94) (shards: 7)
- elasticity-test-ubuntu-db-node-92ed11ec-1 (52.30.38.166 | 10.4.0.171) (shards: 7)

OS / Image: `ami-01c7a2af0b5876566` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-650gb-elasticity-20921`
Test id: `92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6`
Test name: `scylla-staging/yulia/performance/scylla-master-perf-regression-latency-650gb-elasticity-20921`
Test method: `performance_regression_test.PerformanceRegressionTest.test_latency_read_with_nemesis`
Test config file(s):

- [perf-regression-latency-650gb-elasticity.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4aae55c73d1bff406753b84a5a36254089783ea1/test-cases/performance/perf-regression-latency-650gb-elasticity.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6)
- Show all stored logs command: `$ hydra investigate show-logs 92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6`

## Logs:
- **db-cluster-92ed11ec.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6/20241029_164340/db-cluster-92ed11ec.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6/20241029_164340/db-cluster-92ed11ec.tar.gz)
- **sct-runner-events-92ed11ec.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6/20241029_164340/sct-runner-events-92ed11ec.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6/20241029_164340/sct-runner-events-92ed11ec.tar.gz)
- **sct-92ed11ec.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6/20241029_164340/sct-92ed11ec.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6/20241029_164340/sct-92ed11ec.log.tar.gz)
- **loader-set-92ed11ec.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6/20241029_164340/loader-set-92ed11ec.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6/20241029_164340/loader-set-92ed11ec.tar.gz)
- **monitor-set-92ed11ec.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6/20241029_164340/monitor-set-92ed11ec.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6/20241029_164340/monitor-set-92ed11ec.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/performance/job/scylla-master-perf-regression-latency-650gb-elasticity-20921/7/)
[Argus](https://argus.scylladb.com/test/05ddbde6-0609-45c4-8585-33c786e10b46/runs?additionalRuns[]=92ed11ec-3a1b-4cd3-821a-46ad5f5a91c6)
</details>

**Comment by fruch** [comment] 2024-11-06 08:20
@roydahan @yaronkaikov, FYI, its blocks to some degree investigation of #20921

**Comment by swasik** [comment] 2024-11-06 14:03
> [@roydahan](https://github.com/roydahan) [@yaronkaikov](https://github.com/yaronkaikov), FYI, its blocks to some degree investigation of [#20921](https://github.com/scylladb/scylladb/issues/20921)

It may also help debugging [#4504](https://github.com/scylladb/scylla-enterprise/issues/4504) which is already opened for 3 months so would be great if we can resolve it quickly.

**Comment by syuu1228** [comment] 2024-11-07 15:26
Manually tested this on EC2 instance, but not able to reproduce it.
Here's condition:
 - instance type: i4i.2xlarge
 - region: us-east-1
 - AMI: latest Ubuntu 24.04LTS (ami-005fc0f236362e99f)
 - Scylla version: 6.2.0-0.20241013.b8a9fd4e49e8
 
Here's console output:
```
$ sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme1n1 --setup-nic-and-disks --online-discard 0 --swap-directory .
This is a supported kernel version.
Created symlink /etc/systemd/system/multi-user.target.wants/scylla-server.service → /lib/systemd/system/scylla-server.service.
ntp is already configured, skip setup
Creating XFS volume for scylla using 1 disk(s): /dev/nvme1n1
meta-data=/dev/nvme1n1           isize=512    agcount=4, agsize=457763672 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=1    bigtime=0 inobtcount=0
data     =                       bsize=1024   blocks=1831054687, imaxpct=5
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=1024   blocks=894069, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
Created symlink /etc/systemd/system/local-fs.target.wants/var-lib-scylla.mount → /etc/systemd/system/var-lib-scylla.mount.
update-initramfs: Generating /boot/initrd.img-6.8.0-1018-aws

...
(dropped unrelated lines)
...

$ cat /etc/systemd/system/var-lib-scylla.mount
[Unit]
Description=Scylla data directory
Before=local-fs.target scylla-server.service
After=
Wants=
DefaultDependencies=no

[Mount]
What=/dev/disk/by-uuid/37cef048-66e7-4c30-bc10-c9dfd510188b
Where=/var/lib/scylla
Type=xfs
Options=noatime

[Install]

$ cat /proc/mounts|grep /var/lib/scylla
/dev/nvme1n1 /var/lib/scylla xfs rw,noatime,attr2,inode64,logbufs=8,logbsize=32k,noquota 0 0
```

Also tested on 6.3.0~dev-0.20241106.6efde20939d0 (latest 6.3.0-dev), not able to reproduce it, too.
```
$ sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme1n1 --setup-nic-and-disks --online-discard 0 --swap-directory /
This is a supported kernel version.
ntp is already configured, skip setup
Creating XFS volume for scylla using 1 disk(s): /dev/nvme1n1
blkdiscard: /dev/nvme1n1 contains existing file system (xfs).
blkdiscard: This is destructive operation, data will be lost! Use the -f option to override.
/dev/nvme1n1: 4 bytes were erased at offset 0x00000000 (xfs): 58 46 53 42
meta-data=/dev/nvme1n1           isize=512    agcount=4, agsize=457763672 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=1    bigtime=0 inobtcount=0
data     =                       bsize=1024   blocks=1831054687, imaxpct=5
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=1024   blocks=894069, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
update-initramfs: Generating /boot/initrd.img-6.8.0-1018-aws

...
(dropped unrelated lines)
...


$ cat /proc/mounts|grep /var/lib/scylla
/dev/nvme1n1 /var/lib/scylla xfs rw,noatime,attr2,inode64,logbufs=8,logbsize=32k,noquota 0 0
$ cat /etc/systemd/system/var-lib-scylla.mount
[Unit]
Description=Scylla data directory
Before=local-fs.target scylla-server.service
After=
Wants=
DefaultDependencies=no

[Mount]
What=/dev/disk/by-uuid/07784063-8df6-4522-ae23-13d82b0d7dbb
Where=/var/lib/scylla
Type=xfs
Options=noatime

[Install]
WantedBy=local-fs.target
```

**Comment by juliayakovlev** [comment] 2024-11-07 16:36
@syuu1228 
Did `/dev/nvme1n1 /var/lib/scylla` mount point exist before `scylla_setup` run?

I ran it again from SCT and see that this mount exists already with `discard` enabled before running scylla_setup. It is configured in Scylla AMI that we use in the test:
```
Region: us-east-1
Image id: ami-0ff2b00a3f8d0fbd0
```
```
< t:2024-11-07 16:22:56,014 f:cluster.py      l:2243 c:sdcm.cluster_aws     p:DEBUG > Node elasticity-test-ubuntu-db-node-2fceff07-3 [3.237.194.47 | 10.12.0.236]: Run proc/mounts before scylla_setup
< t:2024-11-07 16:22:56,014 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.12.0.236>: Running command "cat /proc/mounts"...
< t:2024-11-07 16:22:56,058 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.12.0.236>: /dev/nvme1n1 /var/lib/scylla xfs rw,noatime,attr2,discard,inode64,logbufs=8,logbsize=32k,noquota 0 0
```

The we try to re-configure and run `scylla_setup`:
```
< t:2024-11-07 16:25:04,589 f:cluster.py      l:2255 c:sdcm.cluster_aws     p:DEBUG > Node elasticity-test-ubuntu-db-node-2fceff07-3 [3.237.194.47 | 10.12.0.236]: Run proc/mounts after scylla_setup
< t:2024-11-07 16:25:04,589 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.12.0.236>: Running command "cat /proc/mounts"...
< t:2024-11-07 16:25:04,593 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.12.0.236>: /dev/nvme1n1 /var/lib/scylla xfs rw,noatime,attr2,discard,inode64,logbufs=8,logbsize=32k,noquota 0 0
```

Discard was not disabled.

Please, try to use Scylla ami, not ubuntu

**Comment by roydahan** [comment] 2024-11-07 16:42
@juliayakovlev I think that there is a problem with your assumption of AMI setup.
Looks like this issue is invalid.

**Comment by swasik** [comment] 2024-11-07 17:17
Which assumption is incirrect? Do you mean that online discard option shouldn't work with Scylla AMI?

**Comment by fruch** [comment] 2024-11-07 17:26
I would say SMI should supply a way to pick the scylla setup parameters via user-data

And regardless of it, supply doc how to disable this feature

**Comment by roydahan** [comment] 2024-11-10 16:27
The ami_setup already mounts /var/lib/scylla.
Running scylla_setup afterwards, probably can't change it.
To change it, one probably needs to stop scylla, umount /var/lib/scylla and then remount it without the discard option (or possibly run again scylla_setup).

**Comment by juliayakovlev** [comment] 2024-11-11 06:01
> The ami_setup already mounts /var/lib/scylla. Running scylla_setup afterwards, probably can't change it. To change it, one probably needs to stop scylla, umount /var/lib/scylla and then remount it without the discard option (or possibly run again scylla_setup).

@roydahan 
I did it already and face out with problem described in https://github.com/scylladb/scylladb/issues/21457
Now I am working according to @piodul recommendation to fix the problem.
Last run that I did looks better

**Comment by roydahan** [comment] 2024-11-12 11:11
Closing as invalid issue.

**Closed** 2024-11-12 11:11 UTC
Labels: bug

**Comment by mykaul** [comment] 2024-11-13 14:06
> The ami_setup already mounts /var/lib/scylla.

@roydahan , @yaronkaikov - isn't this a bug? Why would it do that? It may not be what the customer/user wanted.

**Comment by roydahan** [comment] 2024-11-14 23:11
This is the recommended configuration, hence the AMI comes with this configuration as part of the setup.
You may claim that the customer may want to control it and have a way to pass it as a parameter to the AMI, but there was never such a requirement and this is one config parameter among others that isn't controllable (and TBH I don't think should be)

**Comment by mykaul** [comment] 2024-11-17 13:48
> This is the recommended configuration, hence the AMI comes with this configuration as part of the setup. You may claim that the customer may want to control it and have a way to pass it as a parameter to the AMI, but there was never such a requirement and this is one config parameter among others that isn't controllable (and TBH I don't think should be)

Why would the AMI do it, if the Scylla setup is (re)-doing it? Please reconsider.
