### ISSUE TITLE
OOMKilled on Kubernetes

### ISSUE THREAD

**Issue by vladiceanu** [scylladb/scylladb#11191] opened 2022-08-02 11:32 UTC
*Installation details*
Scylla version (or git commit hash): 4.6.3
Cluster size: 3 nodes (i3.2xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI (EKS 1.20)

*Hardware details (for performance issues)* 
Platform (physical/VM/cloud instance type/docker): Kubernetes/docker

We're running Scylla (4.6.3) in Kubernetes (1.20) using Scylla-operator (1.7.2).

After upgrading from version 4.0.8 to 4.6.3, our Scylla nodes get OOMKilled after ~30 days of uptime. The memory utilization graph (based on node-exporter metrics by Prometheus) shows very slow, but constant growth in memory utilization.

<img width="1351" alt="Screenshot 2022-08-01 at 9 49 59 AM" src="https://user-images.githubusercontent.com/19838344/182363277-1706c26a-95d1-4293-9217-994644e30d4e.png">

_(metrics are only available as of the 13th of June due to retention)_

The requests and limits for Scylla Pods are set to 56Gi and 7 cores. 

No other workloads (except system Daemonsets) share the same nodes with Scylla. We run a repair on all tables every night via the Scylla manager.

It was noticed that before the OOM happens, there are a few drops in memory utilization:

<img width="1368" alt="Screenshot 2022-08-01 at 12 41 48 PM" src="https://user-images.githubusercontent.com/19838344/182364207-1e15bdcb-9af5-4fbf-8e6c-4e37af96a137.png">

Before the upgrade to 4.6.3, the very same Scylla cluster with the same load was running without any issues for more than a year. 
[proc_maps.txt](https://github.com/scylladb/scylladb/files/9241754/proc_maps.txt)

**Comment by avikivity** [comment] 2022-08-02 11:39
```
600000000000-6001dc200000 rw-p 00000000 00:00 0
6001dc200000-601000000000 ---p 00000000 00:00 0
601000000000-6011dc200000 rw-p 00000000 00:00 0
6011dc200000-602000000000 ---p 00000000 00:00 0
602000000000-6021dc200000 rw-p 00000000 00:00 0
6021dc200000-603000000000 ---p 00000000 00:00 0
603000000000-6031dc200000 rw-p 00000000 00:00 0
6031dc200000-604000000000 ---p 00000000 00:00 0
604000000000-6041dc200000 rw-p 00000000 00:00 0
6041dc200000-605000000000 ---p 00000000 00:00 0
605000000000-6051dc200000 rw-p 00000000 00:00 0
6051dc200000-606000000000 ---p 00000000 00:00 0
606000000000-6061dc200000 rw-p 00000000 00:00 0
6061dc200000-700000000000 ---p 00000000 00:00 0
```

**Comment by avikivity** [comment] 2022-08-02 11:41
Scylla tries to allocate 52 GiB:

```
>>> 0x1dc200000 * 7 / (1024**3)
52.076171875
```

**Comment by vladiceanu** [comment] 2022-08-02 12:22
> Scylla tries to allocate 52 GiB:
> 
> ```
> >>> 0x1dc200000 * 7 / (1024**3)
> 52.076171875
> ```

Yes, when Scylla Pod starts, the memory utilization is 52.1Gi, however, it grows over time until it reaches 56Gi and gets OOMKilled.

<img width="1377" alt="Screenshot 2022-08-02 at 2 18 48 PM" src="https://user-images.githubusercontent.com/19838344/182372827-eda89ab2-2765-44d6-8a7b-d767cc3b3a2c.png">

**Comment by avikivity** [comment] 2022-08-02 13:38
Please take a /proc/pid/maps snapshot when it grows by at least 1GB so we can see where it went.

**Comment by fee-mendes** [comment] 2022-08-11 02:12
Since this is EKS and Operator is in place, are you specifying `scyllaArgs` in your [Scylla Cluster CRD](https://operator.docs.scylladb.com/stable/scylla_cluster_crd.html)? In particular, I have seem an OOM situation recently, and it happened due to the fact that Scylla wasn't aware of the memory it had to consume. As a result, since the host OS memory is higher than what we allow the pod to run, specifying `--memory XXG --lock-memory` did the trick.

It may be worth a try, and - of course - a jump from 4.0.8 to 4.6.3 is quite big, so it may be related or not.

**Comment by slivne** [comment] 2022-08-11 08:06
@vladiceanu is there any additional info ?

**Comment by vladiceanu** [comment] 2022-08-11 09:55
> Since this is EKS and Operator is in place, are you specifying `scyllaArgs` in your [Scylla Cluster CRD](https://operator.docs.scylladb.com/stable/scylla_cluster_crd.html)? In particular, I have seem an OOM situation recently, and it happened due to the fact that Scylla wasn't aware of the memory it had to consume. As a result, since the host OS memory is higher than what we allow the pod to run, specifying `--memory XXG --lock-memory` did the trick.
> 
> It may be worth a try, and - of course - a jump from 4.0.8 to 4.6.3 is quite big, so it may be related or not.

That is a very good catch - we do not have specified any arguments via `scyllaArgs`, assuming Scylla would detect based on rack specs (scyllaArgs seems to be supported as of the 4.2.0 version of Scylla)


Hi @avikivity,

> Please take a /proc/pid/maps snapshot when it grows by at least 1GB so we can see where it went.

<img width="1352" alt="Screenshot 2022-08-11 at 11 46 58 AM" src="https://user-images.githubusercontent.com/19838344/184108154-3b5c6a01-8cc5-49b7-aa80-9ad92ed0e207.png">

[scylla_maps_52_1_to_53_1_gb_increase.txt](https://github.com/scylladb/scylladb/files/9307742/scylla_maps_52_1_to_53_1_gb_increase.txt)

**Comment by avikivity** [comment] 2022-08-11 13:44
Main heap usage is unchanged.

```console
$ awk '/^[^6].*rw-p/ { split($1, a, "-"); s += strtonum("0x" a[2]) - strtonum("0x" a[1]) }  END { print(s) }'   scylla_maps_52_1_to_53_1_gb_increase.txt 
33415168
```

excess heap is just ~33MB.

**Comment by avikivity** [comment] 2022-08-11 13:46
Please capture /proc/.../smaps instead, it has additional information. From the capture above, the heap looks fine, but maybe the memory leaked somewhere else.

**Comment by vladiceanu** [comment] 2022-08-11 16:14
> Please capture /proc/.../smaps instead, it has additional information. From the capture above, the heap looks fine, but maybe the memory leaked somewhere else.

sure, attached it below. Thank you

[scylla_smaps_52_1_to_53_1_gb_increase.txt](https://github.com/scylladb/scylladb/files/9310126/scylla_smaps_52_1_to_53_1_gb_increase.txt)

**Comment by vladiceanu** [comment] 2022-08-23 10:44
hello @fee-mendes // @avikivity,
I've passed `--memory XXG --lock-memory` arguments to the Scylla process but unfortunately the result is still the same, memory slowly increases over time. Please let me know if there is anything else required for debugging purposes. Thank you

**Comment by avikivity** [comment] 2022-08-23 12:37
```console
$ grep Rss scylla_smaps_52_1_to_53_1_gb_increase.txt | sort -k2n | tail -n 30
Rss:                1940 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                2048 kB
Rss:                3128 kB
Rss:                3128 kB
Rss:                3128 kB
Rss:                3128 kB
Rss:                3128 kB
Rss:                3128 kB
Rss:                3128 kB
Rss:                7972 kB
Rss:               38728 kB
Rss:             7774208 kB
Rss:             7774208 kB
Rss:             7774208 kB
Rss:             7774208 kB
Rss:             7776256 kB
Rss:             7776256 kB
Rss:             7776256 kB
```

**Comment by avikivity** [comment] 2022-08-23 12:40
The largest non-heap one is scylla test. It's 38MB and cannot increase much:

```
00f3e000-0473f000 r-xp 00d3d000 ca:01 94458570                           /opt/scylladb/libexec/scylla
Size:              57348 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:               38728 kB
Pss:               38726 kB
Shared_Clean:          4 kB
```

**Comment by avikivity** [comment] 2022-08-23 12:40
The 7972 kB entry is also scylla text.

**Comment by avikivity** [comment] 2022-08-23 12:41
3128 -> kernel aio rings, their size and number won't increase.

```
7fb78ead6000-7fb78ede4000 rw-s 00000000 00:11 337932967                  /[aio] (deleted)
Size:               3128 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                3128 kB
Pss:                3128 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:      3124 kB
Private_Dirty:         4 kB
Referenced:         3128 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:            0
VmFlags: rd wr sh mr mw ms de sd 
```

**Comment by avikivity** [comment] 2022-08-23 12:44
The 2048 kB mappings are anonymous, no idea what they are. Maybe thread stacks? Don't appear to be a problem since there are too few of them.

```console
$ grep Size.*2048 scylla_smaps_52_1_to_53_1_gb_increase.txt 
Size:               2048 kB
Size:               2048 kB
Size:               2048 kB
Size:               2048 kB
Size:               2048 kB
Size:               2048 kB
Size:               2048 kB
Size:               2048 kB
Size:               2048 kB
Size:               2048 kB
Size:               2048 kB
Size:               2048 kB
Size:               2048 kB
```

**Comment by vladiceanu** [comment] 2022-08-24 08:08
```bash
# grep  Rss: jmx_smaps.txt | sort -k2nr | tail -n +30 | awk ' { s += $2 } END { print s } '
3336
```
and 
```bash
# grep  Rss: jmx_smaps.txt | sort -k2n | tail -n 30
Rss:                 156 kB
Rss:                 180 kB
Rss:                 196 kB
Rss:                 216 kB
Rss:                 308 kB
Rss:                 328 kB
Rss:                 344 kB
Rss:                 596 kB
Rss:                 668 kB
Rss:                 732 kB
Rss:                 784 kB
Rss:                1272 kB
Rss:                1276 kB
Rss:                1428 kB
Rss:                1460 kB
Rss:                1548 kB
Rss:                2072 kB
Rss:                2532 kB
Rss:                2664 kB
Rss:                3688 kB
Rss:                3764 kB
Rss:                4004 kB
Rss:                4776 kB
Rss:                6436 kB
Rss:                6788 kB
Rss:                7052 kB
Rss:                8180 kB
Rss:                8188 kB
Rss:               18028 kB
Rss:               82736 kB
```

[scylla_jmx_maps.txt](https://github.com/scylladb/scylladb/files/9414131/scylla_jmx_maps.txt)
[scylla_jmx_smaps.txt](https://github.com/scylladb/scylladb/files/9414132/scylla_jmx_smaps.txt)
[scylla_jmx_pmap.txt](https://github.com/scylladb/scylladb/files/9414133/scylla_jmx_pmap.txt)

**Comment by avikivity** [comment] 2022-08-24 08:16
```console
$ awk '/^Rss/ { s += $2 } END { print s } ' scylla_jmx_smaps.txt 
175580
```

175 MB. Not enough to cause trouble. But was it captured when total pod memory usage was high?

Try to enter the pod's containers while this is happening and run `top` and sort by rss (`M` hotkey).

**Comment by vladiceanu** [comment] 2022-08-24 08:59
The memory grows continuously, sharing the screenshot:
<img width="1344" alt="Screenshot 2022-08-24 at 10 55 47 AM" src="https://user-images.githubusercontent.com/19838344/186376024-ffc70d9c-e880-490c-9100-d81c103eb9ba.png">

Sharing here the screenshot of `top -o %MEM`:
<img width="829" alt="Screenshot 2022-08-24 at 10 58 29 AM" src="https://user-images.githubusercontent.com/19838344/186376520-a3cd4050-b98c-4c08-97d1-018c2f3c3557.png">

Also, here is the scylla-jmx VM summary:
<img width="874" alt="Screenshot 2022-08-24 at 10 53 06 AM" src="https://user-images.githubusercontent.com/19838344/186376086-39c99b51-ef8c-4871-8776-d8bc9ba11d7b.png">

**Comment by avikivity** [comment] 2022-08-24 09:11
Maybe it's scylla-operator that consumes the additional memory? Why does operator need 2.1 GB? /cc @tnozicka

**Comment by tnozicka** [comment] 2022-08-24 10:50
Also the CPU is high for the operator. In a steady state the starter binary is at almost 0% cpu and around 40MiB. Initially I thought this could be setup / tuning but as scylla is already running there (unless it's from a different container). Please file an issue for the operator on https://github.com/scylladb/scylla-operator/issues/new/choose and provide correlated logs for this period.

**Comment by vladiceanu** [comment] 2022-08-24 11:27
> Also the CPU is high for the operator. In a steady state the starter binary is at almost 0% cpu and around 40MiB. Initially I thought this could be setup / tuning but as scylla is already running there (unless it's from a different container). Please file an issue for the operator on https://github.com/scylladb/scylla-operator/issues/new/choose and provide correlated logs for this period.

thanks, created the bug https://github.com/scylladb/scylla-operator/issues/1016 in Scylla-operator

**Comment by avikivity** [comment] 2022-08-24 12:58
Closing as the problem is not in scylladb core.

**Closed by avikivity** 2022-08-24 12:58 UTC
Labels: User Request, bad_alloc, k8
