### ISSUE TITLE
Deprecate Thrift

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#12262] opened 2022-12-11 10:56 UTC
It doesn't seem to be used and not worth the efforts and complexity associated.

**Comment by mykaul** [comment] 2022-12-11 11:00
@tgrabiec - would that also allow not to support partial keys?

**Comment by nyh** [comment] 2022-12-11 12:33
Duplicate of https://github.com/scylladb/scylladb/issues/3811.

**Comment by mykaul** [comment] 2022-12-11 13:44
Closing as dup, will continue the discussion on #3811

**Comment by avikivity** [comment] 2022-12-11 13:53
Really closing as duplicate of #3811.

**Closed by avikivity** 2022-12-11 13:53 UTC
Labels: thrift-api
