### ISSUE TITLE
Some boost tests generate malformed XML files.

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#4774] opened 2019-07-30 08:50 UTC
Example run:
`./test.py --verbose --jenkins jenkins_test --mode=dev --name=multishard`
A file "jenkins_test.release.multishard_mutation_query_test.boost.xml" is generated.

More often than not, the XML (from this particular test) is malformed. Example:
> 35364 | The element type "Info" must be terminated by the matching end-tag "</Info>".

https://pastebin.com/AaFGqAw8

The errors are various and don't follow a pattern.
Therefore my hypothesis is that they come from interleaved messages that are written into the XML file concurrently from multiple shards by boost test macros like this one:
`BOOST_CHECK(exp_live_it == exp_live_end);`

Maybe we should add some synchronization mechanism so that only one shard outputs to the file at a time?

This needs to be fixed, as we need to feed the file to Jenkins.

**Comment by denesb** [comment] 2019-07-30 09:09
Adding synchronization will possibly skew the test as basically only one shard will be making progress at a time, the rest will be waiting for the lock. The problem is that since we can't really reach into boost::test internals, we'd have to wrap the test macros with one that takes a lock before proceeding. Unless there is a way to provide callbacks to boost to which it reports failures and we write the xml file ourselves in a thread safe manner.

**Comment by denesb** [comment] 2019-07-30 09:10
I just had a look at the `XML` and this is even worst than I thought, boost wants to write into it *every* message it would print as test output.

**Comment by kbr-** [comment] 2019-07-30 09:28
We could also smp::submit_to shard 0 every time we need to output a message.

**Comment by denesb** [comment] 2019-07-30 09:57
This would require wrapping all `BOOST_` macros with something of our own. Also note that some of these output the messages deep inside some boost code, I'm not sure how we could intercept and redirect these.

**Comment by kbr-** [comment] 2019-07-30 10:09
> This would require wrapping all BOOST_ macros with something of our own.

That's what I had in mind. We already have SEASTAR_TEST_CASE and friends, so why not take this further?

> I'm not sure how we could intercept and redirect these.

No need to intercept anything, just make sure that either
1. the boost macros always get called on the same shard, or
2. the boost macros always get called under some lock, or
3. whatever we can come up with.

By "saving the messages" I meant that we wouldn't call the macros where we call them right now, but do something else to store the message (e.g. save the information about the result of `exp_live_it == exp_live_end` and when the check happened). Then at the end of the test call the boost macros or some other mechanism to output the messages.

**Comment by denesb** [comment] 2019-07-30 11:06
> > This would require wrapping all BOOST_ macros with something of our own.
> 
> That's what I had in mind. We already have SEASTAR_TEST_CASE and friends, so why not take this further?

I don't mind wrapping the `BOOST_*` macros if that's what this takes.

> 
> > I'm not sure how we could intercept and redirect these.
> 
> No need to intercept anything, just make sure that either
> 
>     1. the boost macros always get called on the same shard, or
> 
>     2. the boost macros always get called under some lock, or
> 
>     3. whatever we can come up with.
> 
> 
> By "saving the messages" I meant that we wouldn't call the macros where we call them right now, but do something else to store the message (e.g. save the information about the result of `exp_live_it == exp_live_end` and when the check happened). Then at the end of the test call the boost macros or some other mechanism to output the messages.

Whatever we come up with, we have to take into consideration, that:
* Ordering all the checks can introduce an additional constraint into the test, skewing its results, potentially allowing bugs to slip through.
* Lazily evaluating these expressions can be prohibitively expensive as in some cases these are multi megabyte mutations.
* Many checks are done on moving targets, objects that are mutated during the course of the test.

Based on the previous points it seems that the best course of action is to evaluate all expressions on-spot, then send the result for analysis to the designated shard (shard 0) asynchronously.

**Comment by avikivity** [comment] 2020-02-04 12:28
I think that a lock is fine. It will slow the tests down a little, but we only run on three shards, so there won't be too much contention.

**Comment by denesb** [comment] 2020-02-04 12:40
Wouldn't that possibly hide races due to the added synchronization points?

**Comment by denesb** [comment] 2020-08-03 08:14
We are still seeing this, reopening.

**Comment by nyh** [comment] 2023-10-08 15:44
@raphaelsc just sent PR #15654 and @avikivity committed, which supposedly fixes the problems we still had in this area.
Since we don't have other reports of this problem for three years, I hope this was the last such problem that Raphael fixed, so I'm closing this issue as done.

**Closed by nyh** 2023-10-08 15:44 UTC
Labels: internals, unitest

**Comment by nyh** [comment] 2023-10-19 08:40
@mykaul why did you change the "closed as completed" to "closed as not planned" - I think this was a real issue, that we really did fix (in PR #15654).

**Comment by mykaul** [comment] 2023-10-19 08:58
> > @mykaul why did you change the "closed as completed" to "closed as not planned" - I think this was a real issue, that we really did fix (in PR #15654).
> 
> I was under the impression it was fixed in issue #15654 - which I marked as completed with the 5.4 milestone. PR - #15655 ?

(can't help myself but complain how confusing it is that GH treats issues and PRs in the same way - just a number, instead of 'Ixxxx' vs 'PRxxxx' or something...)

**Comment by nyh** [comment] 2023-10-19 09:07
Yes, the fact they decided to use the same namespace for issues and PRs is sad :-(
