### ISSUE TITLE
row_cache_stress_test is flakey

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#12800] opened 2023-02-09 21:01 UTC
Seen on next-promotion fd4ee4878ab6814c5cc119c7538ac0eafa560afb

```
 Output of build/release/test/unit/row_cache_stress_test -c1 -m1G --seconds 10 --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100:
22:57:46  === TEST.PY STARTING TEST unit.row_cache_stress_test.3 ===
22:57:46  export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/jenkins/workspace/scylla-master/next/scylla/ubsan-suppressions.supp'
22:57:46  export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
22:57:46  build/release/test/unit/row_cache_stress_test -c1 -m1G --seconds 10 --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100
22:57:46  === TEST.PY TEST unit.row_cache_stress_test.3 OUTPUT ===
22:57:46  INFO  2023-02-09 22:29:42,330 seastar - Reactor backend: linux-aio
22:57:46  WARN  2023-02-09 22:29:42,331 [shard 0] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
22:57:46  INFO  2023-02-09 22:29:42,339 [shard 0] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
22:57:46  INFO  2023-02-09 22:29:42,340 [shard 0] seastar - IO queue uses 0.75ms latency goal for device 0
22:57:46  INFO  2023-02-09 22:29:42,340 [shard 0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
22:57:46  INFO  2023-02-09 22:29:42,340 [shard 0] seastar - Created io queue dev(0) capacities: 512:2000:2000 1024:3000:3000 2048:5000:5000 4096:9000:9000 8192:17000:17000 16384:33000:33000 32768:65000:65000 65536:129000:129000 131072:257000:257000
22:57:46  INFO  2023-02-09 22:29:43,350 [shard 0] testlog - reads/s: 0, scans/s: 0, mutations/s: 10, flushes/s: 1, Cache: 0/0 [MB], LSA: 44/65 [MB], std free: 929 [MB]
22:57:46  INFO  2023-02-09 22:29:43,831 [shard 0] testlog - single-0 is using pk=5 ck=[0, 1333]
22:57:46  INFO  2023-02-09 22:29:43,831 [shard 0] testlog - single-1 is using pk=5 ck=[962, 2295]
22:57:46  INFO  2023-02-09 22:29:43,831 [shard 0] testlog - single-2 is using pk=5 ck=[1925, 3258]
22:57:46  INFO  2023-02-09 22:29:43,833 [shard 0] testlog - single-3 is using pk=5 ck=[2888, 4221]
22:57:46  INFO  2023-02-09 22:29:43,833 [shard 0] testlog - single-4 is using pk=5 ck=[3851, 5184]
22:57:46  INFO  2023-02-09 22:29:43,833 [shard 0] testlog - single-5 is using pk=5 ck=[4814, 6147]
22:57:46  INFO  2023-02-09 22:29:43,833 [shard 0] testlog - single-6 is using pk=5 ck=[5777, 7110]
22:57:46  INFO  2023-02-09 22:29:43,833 [shard 0] testlog - single-7 is using pk=5 ck=[6740, 8073]
22:57:46  INFO  2023-02-09 22:29:43,833 [shard 0] testlog - single-8 is using pk=5 ck=[7703, 9036]
22:57:46  INFO  2023-02-09 22:29:43,833 [shard 0] testlog - single-9 is using pk=5 ck=[8666, 9999]
22:57:46  INFO  2023-02-09 22:29:44,350 [shard 0] testlog - reads/s: 10, scans/s: 2, mutations/s: 8, flushes/s: 0, Cache: 28/44 [MB], LSA: 84/117 [MB], std free: 878 [MB]
22:57:46  INFO  2023-02-09 22:29:45,350 [shard 0] testlog - reads/s: 28, scans/s: 0, mutations/s: 2, flushes/s: 1, Cache: 35/56 [MB], LSA: 113/173 [MB], std free: 820 [MB]
22:57:46  INFO  2023-02-09 22:29:46,350 [shard 0] testlog - reads/s: 73, scans/s: 0, mutations/s: 0, flushes/s: 0, Cache: 39/63 [MB], LSA: 133/204 [MB], std free: 786 [MB]
22:57:46  INFO  2023-02-09 22:29:47,350 [shard 0] testlog - reads/s: 69, scans/s: 0, mutations/s: 0, flushes/s: 0, Cache: 3/5 [MB], LSA: 125/186 [MB], std free: 766 [MB]
22:57:46  INFO  2023-02-09 22:29:48,375 [shard 0] testlog - reads/s: 86, scans/s: 0, mutations/s: 0, flushes/s: 0, Cache: 7/12 [MB], LSA: 154/232 [MB], std free: 758 [MB]
22:57:46  INFO  2023-02-09 22:29:49,375 [shard 0] testlog - reads/s: 78, scans/s: 0, mutations/s: 0, flushes/s: 0, Cache: 85/135 [MB], LSA: 180/275 [MB], std free: 720 [MB]
22:57:46  INFO  2023-02-09 22:29:50,385 [shard 0] testlog - reads/s: 11, scans/s: 0, mutations/s: 10, flushes/s: 1, Cache: 3/5 [MB], LSA: 139/207 [MB], std free: 692 [MB]
22:57:46  INFO  2023-02-09 22:29:51,385 [shard 0] testlog - reads/s: 36, scans/s: 0, mutations/s: 0, flushes/s: 0, Cache: 9/14 [MB], LSA: 173/258 [MB], std free: 694 [MB]
22:57:46  INFO  2023-02-09 22:29:52,350 [shard 0] testlog - Test done.
22:57:46  INFO  2023-02-09 22:29:52,385 [shard 0] testlog - reads/s: 98, scans/s: 0, mutations/s: 0, flushes/s: 0, Cache: 13/21 [MB], LSA: 199/297 [MB], std free: 695 [MB]
22:57:46  row_cache_stress_test: test/unit/row_cache_stress_test.cc:405: auto main(int, char **)::(anonymous class)::operator()()::(anonymous class)::operator()() const: Assertion `t.tracker.get_stats().partitions == 0' failed.
22:57:46  Aborting on shard 0.
22:57:46  Backtrace:
22:57:46    0x27aeec8
22:57:46    0x27e1302
22:57:46    /lib64/libc.so.6+0x3cb4f
22:57:46    /lib64/libc.so.6+0x8ce7b
22:57:46    /lib64/libc.so.6+0x3caa5
22:57:46    /lib64/libc.so.6+0x267fb
22:57:46    /lib64/libc.so.6+0x2671a
22:57:46    /lib64/libc.so.6+0x35655
22:57:46    0xa90f78
22:57:46    0xa8d1b5
22:57:46    0x2a39006
22:57:46  === TEST.PY SUMMARY START ===
22:57:46  Test exited with code -6
22:57:46  
22:57:46  === TEST.PY SUMMARY END ===
```

**Comment by avikivity** [comment] 2023-02-09 21:02
Likely duplicate of #12778

**Comment by tgrabiec** [comment] 2023-02-10 11:28
Duplicate of https://github.com/scylladb/scylladb/issues/12778

**Closed by tgrabiec** 2023-02-10 11:28 UTC
Labels: test, CI-Stability
