### ISSUE TITLE
integrate perf tool to scylla bin to run perf tests and collect, analyze perf results regularly

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#12484] opened 2023-01-09 19:03 UTC
Integrate performance tools to scylla to run performance tests in regular base and store, compare performance results and find regression:
tools for integration:
 - perf_fast_forward 
 - perf_row_cache_update
 - perf_simple_query

Example of execution:
 - `scylla perf_simple_query --smp 1 -m 1G`
 - `scylla perf_row_cache_update ...`

**Comment by roydahan** [comment] 2023-01-16 10:11
@avikivity according to @aleksbykov there is a mail thread related to that.
Is there anyone in charge of this who can help push it forward?

**Comment by avikivity** [comment] 2023-01-16 10:40
This was previously done by @denesb with `scylla sstables` and `scylla types`. But maybe @tchaikov can do it.

@tchaikov the idea here is to avoid the huge code duplication caused by static linking by making the scylla binary be a command switchboard like `git`. See our main: https://github.com/scylladb/scylladb/blob/master/main.cc#L1742.

We want to integrate the tools in test/perf. I guess a few are unneeded, but shouldn't be difficult to convert en mass.

**Comment by tchaikov** [comment] 2023-01-17 09:44
ack. i am on this.

**Comment by denesb** [comment] 2023-01-17 09:51
By folding perf tests into the scylla executable, we also fold `cql_test_env`. We must watch out for any clashing globals. But more importantly we will now have the startup/teardown algorithms duplicated. Not the end of the world, but maybe it is time we pick up @bhalevy's startup/teardown refactoring effort, so this can be shared between main and tests (including perf tests).

**Comment by tchaikov** [comment] 2023-01-18 10:18
thanks @denesb , indeed. i just ran into `debug::the_database` which is included by both `main.cc` and `cql_test_env.cc`.

@bhalevy could you point me to your startup/teardown refactoring effort if it's still around?

**Comment by tchaikov** [comment] 2023-01-18 14:33
@aleksbykov hi Aleksandr, do you happen to know where we are using these tools, for instance `perf_fast_forward` in our tests? i wanted to update all the references as well. but grepping them in the `scylla-dtest` repo, but nothing is found.

**Comment by roydahan** [comment] 2023-01-18 17:40
> @aleksbykov hi Aleksandr, do you happen to know where we are using these tools, for instance `perf_fast_forward` in our tests? i wanted to update all the references as well. when grepping them in the `scylla-dtest` repo, nothing is found.

We don't use them in dtest.
I think we use perf_fast_foward in our "Microbenchmarking" tests in scylla-pkg (@yaronkaikov may be able to refer to the exact location).

**Comment by yaronkaikov** [comment] 2023-01-18 19:13
> > @aleksbykov hi Aleksandr, do you happen to know where we are using these tools, for instance `perf_fast_forward` in our tests? i wanted to update all the references as well. when grepping them in the `scylla-dtest` repo, nothing is found.
> 
> We don't use them in dtest. I think we use perf_fast_foward in our "Microbenchmarking" tests in scylla-pkg (@yaronkaikov may be able to refer to the exact location).

@roydahan Yes, we use it as part of benchmarking - The files are located at `Build` artifacts - here is an example: https://jenkins.scylladb.com/view/master/job/scylla-master/job/build/lastSuccessfulBuild/artifact/scylla/build/release/test/perf/

**Comment by tchaikov** [comment] 2023-01-20 05:33
@roydahan and @yaronkaikov thank you for providing the details on how `perf_fast_foward` is used!

@aleksbykov i see we need at least something like 
```diff
diff --git a/scripts/jenkins-pipelines/general.properties b/scripts/jenkins-pipelines/general.properties
index 7de93e39..42c1109d 100644
--- a/scripts/jenkins-pipelines/general.properties
+++ b/scripts/jenkins-pipelines/general.properties
@@ -118,7 +118,7 @@ amiIdFileArm=amiId_aarch64.properties
 amiIdPropertyNameX86=us-east-1-x86_64
 amiIdPropertyNameArm=us-east-1-aarch64
 amiMetadataFieldName=scylla-ami-id
-microbenchmarksTestExe=build/release/test/perf/perf_fast_forward
+microbenchmarksTestCmd="build/release/scylla perf-fast-forward"
 dtestIncludeSmoke=-m dtest_smoke
 internalAwsIP=169.254.169.254
 jmxSubmoduleDir=scylla/tools/jmx
diff --git a/scripts/jenkins-pipelines/groovy_modules/test.groovy b/scripts/jenkins-pipelines/groovy_modules/test.groovy
index 3fa06d79..a2d3ba00 100644
--- a/scripts/jenkins-pipelines/groovy_modules/test.groovy
+++ b/scripts/jenkins-pipelines/groovy_modules/test.groovy
@@ -294,8 +294,8 @@ def microBenchMarks (boolean dryRun = false) {
                echo "No old perf_large_partition_data files ${gitProperties.scyllaCheckoutDir}/perf_large_partition_data. Nothing to remove"
        }

-       String perfFastForwardCmd1 = "${generalProperties.microbenchmarksTestExe} --populate -c1"
-       String perfFastForwardCmd2 = "${generalProperties.microbenchmarksTestExe} -c1 --enable-cache --output-format=json"
+       String perfFastForwardCmd1 = "${gitProperties.scyllaCheckoutDir}/${generalProperties.microbenchmarksTestCmd} --populate -c1"
+       String perfFastForwardCmd2 = "${gitProperties.scyllaCheckoutDir}/${generalProperties.microbenchmarksTestCmd} -c1 --enable-cache --output-format=json"
        dir("${gitProperties.scyllaCheckoutDir}") {
                general.runOrDryRunSh (dryRun, "./tools/toolchain/dbuild /bin/bash -c '${perfFastForwardCmd1}; ${perfFastForwardCmd2}'", "Running microBenchMarks")
        }
```

in scylla-pkg, but i don't think that'd suffice. as the test is now integrated into `scylla`, while the unified package is not installed by scylla-ccm as we normally do for preparing dtest tests. how do you image to "run perf tests and collect, analyze perf results regularly"? are we going to have these test out of the https://jenkins.scylladb.com/job/scylla-master/job/microbenchmarks jobs or we are going keep them there?

**Comment by aleksbykov** [comment] 2023-01-20 09:46
For that moment, we use next 'https://github.com/scylladb/scylla-cluster-tests/blob/8660cc46b188c8294678a77c183834c5fcad5e65/sdcm/microbenchmarking.py'. The script parse results of microbenchmarking tests, build report and send email.

basic path of usage is going to be next:
1. create instance with prepared ami or create empty instance and install relocatable packages (it is going to be done with [SCT](git@github.com:scylladb/scylla-cluster-tests.git).
2. Run specified command
3. Get result from console or file (depend on sub command output. it will be great if it is possible to have --json parameter and result are written in json format)
4. Parse results, save in ES.
5. Run result comparision per build, prepare report and send email

**Comment by tchaikov** [comment] 2023-01-20 09:56
@aleksbykov thank you for the detailed explanation. so but what i shall / need do from my side? i foresee that https://github.com/scylladb/scylla-pkg/blob/next/scripts/jenkins-pipelines/microbenchmarks.jenkinsfile would be broken once my change gets merged. shall we drop it and implement the steps above?

**Comment by aleksbykov** [comment] 2023-01-20 10:08
I think after you merge your changes, it will some kind of standard to use such commands. So we should unified the workflow.
I think it will be not difficult to fix the microbenchmark pipeline and it become simpler, and could be run just with relocatable packages.
@roydahan / @yaronkaikov WDYT?

**Closed** 2023-01-20 13:26 UTC
Labels: enhancement, performance, test

**Comment by yaronkaikov** [comment] 2023-01-30 20:50
> I think after you merge your changes, it will some kind of standard to use such commands. So we should unified the workflow. I think it will be not difficult to fix the microbenchmark pipeline and it become simpler, and could be run just with relocatable packages. @roydahan / @yaronkaikov WDYT?

@aleksbykov @tchaikov The problem now is the following. To run the pipeline benchmark-tests we need now `Scylla` bin file, right? This file is currently not being uploaded to the Jenkins artifacts (it is about 1.8Gb for each run), and when we run the pipeline we don't build Scylla again. 
So the way I see it (and maybe you guys have a better idea), we can do one of the following:

1. Upload Scylla bin file to Jenkins artifacts
2. Integrate this test into `Build`, Then we can run this as a separate stage after unit tests are completed successfully. The issue with it, is it's not bound to the `monster` server which I think we need to compare results (right @roydahan ?)

**Comment by yaronkaikov** [comment] 2023-01-31 08:42
> > I think after you merge your changes, it will some kind of standard to use such commands. So we should unified the workflow. I think it will be not difficult to fix the microbenchmark pipeline and it become simpler, and could be run just with relocatable packages. @roydahan / @yaronkaikov WDYT?
> 
> @aleksbykov @tchaikov The problem now is the following. To run the pipeline benchmark-tests we need now `Scylla` bin file, right? This file is currently not being uploaded to the Jenkins artifacts (it is about 1.8Gb for each run), and when we run the pipeline we don't build Scylla again. So the way I see it (and maybe you guys have a better idea), we can do one of the following:
> 
> 1. Upload Scylla bin file to Jenkins artifacts
> 2. Integrate this test into `Build`, Then we can run this as a separate stage after unit tests are completed successfully. The issue with it, is it's not bound to the `monster` server which I think we need to compare results (right @roydahan ?)

One more option is to add to microbenchmark pipeline a `build` stage where we will build Scylla in release mode only without any unittests

**Comment by tchaikov** [comment] 2023-01-31 08:47
> > I think after you merge your changes, it will some kind of standard to use such commands. So we should unified the workflow. I think it will be not difficult to fix the microbenchmark pipeline and it become simpler, and could be run just with relocatable packages. @roydahan / @yaronkaikov WDYT?
> 
> @aleksbykov @tchaikov The problem now is the following. To run the pipeline benchmark-tests we need now `Scylla` bin file, right? This file is currently not being uploaded to the Jenkins artifacts (it is about 1.8Gb for each run), 

right. IIUC, it is indeed uploaded as a part of the relocatable package. see https://github.com/scylladb/scylla-pkg/blob/7a2f95e5a7d3f1e351ca5ce170afc14dc3d7f665/scripts/jenkins-pipelines/microbenchmarks.jenkinsfile#L117-L121 . we just need to extract and use (or put in other words, to install) the `scylla` executable packaged in it.  `scylla-ccm` understands how to do the installation, but we don't use it in the microbenchmark jenkins job for setting up the cluster.

**Comment by aleksbykov** [comment] 2023-01-31 09:26
i think, we can run these tests as we run aritifact tests with relocatable packages using sct. We can create new aws instance with same type each time, download relocatable packages on it and execute all perf tools one by one.

**Comment by aleksbykov** [comment] 2023-01-31 09:27
> For that moment, we use next 'https://github.com/scylladb/scylla-cluster-tests/blob/8660cc46b188c8294678a77c183834c5fcad5e65/sdcm/microbenchmarking.py'. The script parse results of microbenchmarking tests, build report and send email.
> 
> basic path of usage is going to be next:
> 
> 1. create instance with prepared ami or create empty instance and install relocatable packages (it is going to be done with SCT.
> 2. Run specified command
> 3. Get result from console or file (depend on sub command output. it will be great if it is possible to have --json parameter and result are written in json format)
> 4. Parse results, save in ES.
> 5. Run result comparision per build, prepare report and send email

like described here

**Comment by yaronkaikov** [comment] 2023-01-31 09:46
@aleksbykov It means this job is moving to SCT? i am fine with it. So please create the relevant job and let me know once it's working so we can trigger it
/cc @roydahan

**Comment by roydahan** [comment] 2023-01-31 21:32
No, we don’t want to move it to SCT.
This job runs on a local machine in the lab to keep the results consistent and comparable.

IIUC, we just need to use the relocatable packages to install it.

**Comment by yaronkaikov** [comment] 2023-02-06 12:43
Submitted a PR to fix it on pkg side : https://github.com/scylladb/scylla-pkg/pull/3285
