### ISSUE TITLE
`test_nonfrozen_user_type_set_field` is flaky

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#14759] opened 2023-07-19 16:10 UTC
Build https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2526/ failed on `test/boost/user_types_test.cc`::`test_nonfrozen_user_type_set_field`.

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2526/artifact/testlog/x86_64/debug/boost.user_types_test.test_nonfrozen_user_type_set_field.1.log

**Comment by mykaul** [comment] 2023-07-20 11:09
@eliransin - please see if it's in your team and assign.

**Comment by DoronArazii** [comment] 2023-07-27 09:22
@eliransin / @ptrsmrn we need somebody to triage it - please help

**Comment by ptrsmrn** [comment] 2023-07-27 09:45
@patjed41 the link to the error expired, do we have the output of this test saved somewhere else?

**Comment by patjed41** [comment] 2023-07-27 11:02
> @patjed41 the link to the error expired, do we have the output of this test saved somewhere else? There's something logged in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2526/consoleFull#7208642002d64d3cc-9cf1-4f8e-9ae7-050ec58d788c

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2526/consoleFull#7208642002d64d3cc-9cf1-4f8e-9ae7-050ec58d788c contains the logs of the failed test from the expired link. The beginning, `Output of build/debug/test/boost/user_types_test --run_test=test_nonfrozen_user_type_set_field`, is highlighted in red .

**Comment by DoronArazii** [comment] 2023-08-10 10:05
@wmitros raising the priority as we're trying to fight hard with CI-Stability issues

**Comment by wmitros** [comment] 2023-09-05 12:50
The test has not reappeared and I can't seem to reproduce. The backtrace seems very similar to https://github.com/scylladb/scylladb/issues/14830 and it can be observed at a similar moment in the process, so I suggest we close this issue for now and possibly reopen it if it turns out to be a different issue

**Closed** 2023-09-05 13:04 UTC
Labels: P1, CI-Stability
