### ISSUE TITLE
[dtest]  wide_rows_test.TestWideRows.test_large_cell_in_materialized_view is flakey

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15700] opened 2023-10-12 10:01 UTC
Seen in: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6655/testReport/junit/wide_rows_test/TestWideRows/Tests___Sanity_Tests_RAFT___test_large_cell_in_materialized_view_SizeTieredCompactionStrategy_/

```
self = <wide_rows_test.TestWideRows object at 0x7f53f793cb10>

    def test_large_cell_in_materialized_view(self):
        """
         Create table with one large cell. Create materialized view on the table.
         Validate that just large cell is reported in the system.large_cells table and there are warning in the
         log for both base table and materialized view
        """
        rows_number = 10
        columns_num = 10
        entity_type = 'cell'
        view_name = '%s_view' % self.TABLE_NAME
    
        session = self.prepare_cluster(nodes=3, rf=3)
    
        self.create_large_row_table(session=session, table_name=self.TABLE_NAME, columns_num=columns_num,
                                    entity_type=entity_type)
        # Insert large row
        expected_cells_data_size = self.create_large_row_data(session=session,
                                                              table_name=self.TABLE_NAME,
                                                              columns_num=columns_num,
                                                              rows_num=rows_number,
                                                              one_blob_size=self.BLOB_SIZE_1MB,
                                                              start_row_index=0)
    
>       session.execute('create materialized view %s as select * from %s '
                        'where userid is not null and event is not null primary key (userid, event)' %
                        (view_name, self.TABLE_NAME))

wide_rows_test.py:1456: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cassandra/cluster.py:2708: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.98.1:9042

cassandra/cluster.py:5048: OperationTimedOut
```

**Comment by michoecho** [comment] 2023-10-12 16:07
So the client timed out a `create materialized view` statement after 30s, even though Scylla logs prove that all nodes created and built the view within the first 1s. Did the coordinator get stuck somewhere between publishing the new schema and responding to the client, or did the response never make it to the client?

**Comment by avikivity** [comment] 2023-10-12 18:30
Do we know if it timed out on the statement, or the following schema sync?

**Comment by michoecho** [comment] 2023-10-12 18:50
> Do we know if it timed out on the statement, or the following schema sync?

We don't. You need to enable debug logs for the driver to know that. We can enable them for this test so we will know which stage failed the next time this happens.

**Comment by michoecho** [comment] 2023-10-12 18:56
But I wonder what's the chance this will happen again. Whatever happened, it doesn't seem specific to this test.

Maybe we should enable driver debug logs for all tests? It's going to spam a lot of logs, but if we have issues like this, maybe it's a good idea.

**Comment by avikivity** [comment] 2023-10-12 21:28
We could do that, in a side branch and run it N times to flush out some bugs. If it's a common problem then we can fix it without increasing log sizes too much (or destabilizing tests that generate large numbers of queries)

**Comment by bhalevy** [comment] 2023-10-14 07:09
We saw quite a few client request timeouts recently in various tests:

https://github.com/scylladb/scylladb/issues/15700 (CREATE MATERIALIZED VIEW)
https://github.com/scylladb/scylladb/issues/15648 (CREATE TABLE)
https://github.com/scylladb/scylladb/issues/15610 (TRUNCATE)
https://github.com/scylladb/scylladb/issues/15455 (CREATE/DROP INDEX)

**Comment by bhalevy** [comment] 2023-10-14 07:12
@Lorak-mmk could this be related to this recent change in the python driver: https://github.com/scylladb/python-driver/pull/256?

**Comment by bhalevy** [comment] 2023-10-14 20:59
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/6659/testReport/junit/compaction_additional_test/TestTimeWindowDataSegregation/Tests___Sanity_Tests_RAFT___test_enable_disable_optimized_query_for_twcs/
```
compaction_additional_test.py:2475: in _enable_optimized_tw_queries_config
    session.execute(f"ALTER TABLE {self.keyspace_name}.{self.table_name} with compaction = "
cassandra/cluster.py:2708: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.11.2:9042
```

**Comment by Lorak-mmk** [comment] 2023-10-16 10:57
> @Lorak-mmk could this be related to this recent change in the python driver: [scylladb/python-driver#256](https://github.com/scylladb/python-driver/pull/256)?

In the last link you pasted ( https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/6659/testReport/junit/compaction_additional_test/TestTimeWindowDataSegregation/Tests___Sanity_Tests_RAFT___test_enable_disable_optimized_query_for_twcs/ ) I can see the error in the `dtest-gw3.log` file. Does this file contain driver's debug logs? I don't see them, but want to make sure

**Comment by bhalevy** [comment] 2023-10-16 11:03
It should contain the driver logs, but I don't know if the it is configured to log in debug level.

**Comment by michoecho** [comment] 2023-10-16 11:10
> Does this file contain driver's debug logs? I don't see them, but want to make sure

No, it doesn't contain driver debug logs. Currently the only dtest with driver debug logs enabled is `test_add_udt_to_another_data_types`. Other tests only get info logs.

**Comment by michoecho** [comment] 2023-10-16 15:39
I was going to pick this up, but since we found a suspected test infra problem that's supposed to explain a wide class of weird delays (https://github.com/scylladb/scylla-pkg/issues/3620), I'll wait until it reproduces with that problem fixed. Let's observe this in the upcoming weeks.

**Comment by mykaul** [comment] 2023-11-12 15:59
Haven't seen it in a month - closing for the time being.

**Closed by mykaul** 2023-11-12 15:59 UTC
Labels: materialized-views, P2, CI-Stability, infra?
