### ISSUE TITLE
json_test.TestsFromJsonUpdate.test_basic_data_types: "No keyspace has been specified"

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#12081] opened 2022-11-25 15:49 UTC
Weird failure in CI.
https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3182/testReport/junit/json_test/TestsFromJsonUpdate/Sanity_Tests___test_basic_data_types/

```
RuntimeError: Doctest failed! Captured output:
**********************************************************************
Line 29, in test_basic_data_types
Failed example:
    cqlsh('''
    UPDATE primitive_type_test
    SET col1 = fromJson('"bar1"'),
        col2 = fromJson('"0x0012"'),
        col3 = fromJson('"127.0.0.2"'),
        col4 = fromJson('"blarg2"'),
        col5 = fromJson('"2011-02-02 21:05:00.000+0000"'),
        col6 = fromJson('"efe0922a-8638-11e4-b2ac-b4b6763e9d6f"'),
        col7 = fromJson('"05dd0249-25b4-4dec-ba27-54f8730f3c03"'),
        col8 = fromJson('"bleh2"'),
        col9 = fromJson('-8223372036854775808'),
        col10 = fromJson('2234.45678'),
        col11 = fromJson('8.87123121222E7'),
        col12 = fromJson('7.8712312E7'),
        col13 = fromJson('-1947483648'),
        col14 = fromJson('1847483648'),
        col15 = fromJson('false')
    WHERE key1 = 'test'
    ''')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python3.9/doctest.py", line 1334, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest test_basic_data_types[2]>", line 1, in <module>
        cqlsh('''
      File "/jenkins/workspace/releng/Scylla-CI/scylla-dtest/json_test.py", line 89, in cqlsh
        raise RuntimeError("Unexpected cqlsh error: {}".format(err))
    RuntimeError: Unexpected cqlsh error: <stdin>:20:InvalidRequest: Error from server: code=2200 [Invalid query] message="No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename"
```

**Comment by nyh** [comment] 2022-11-27 11:04
I think this is not a bug in Scylla, but rather a bug in the new cqlsh we started to use, or how it's used in dtest - the json_test.py has particularly funky and unique code for keeping track of this "USE" thing instead of just using full table names everywhere and avoiding this problem :-(
I opened an issue in the dtest repository: https://github.com/scylladb/scylla-dtest/issues/2923

Interestingly this error is sporadic, it happens in different tests in different runs.

**Comment by mykaul** [comment] 2022-11-28 11:35
@fruch - the newer cqlsh was reverted, right? Can we close the above after this revert, or do we wish to keep it open till we ensure it's not happening with the newer one?

**Comment by fruch** [comment] 2022-11-28 12:18
> @fruch - the newer cqlsh was reverted, right? Can we close the above after this revert, or do we wish to keep it open till we ensure it's not happening with the newer one?

I know @avikivity reverted

we have a defect for the root cause in
https://github.com/scylladb/python-driver/issues/187

So from my POV we can close it.

**Comment by DoronArazii** [comment] 2023-04-17 08:27
Closing due to last comment by Israel.
Both mentioned issues above are also fixed.

**Closed by DoronArazii** 2023-04-17 08:27 UTC
Labels: dtest
