### ISSUE TITLE
DynamoDB API create table with secondary index adds extra KeySchema

### ISSUE THREAD

**Issue by bartpeeters** [scylladb/scylladb#11455] opened 2022-09-05 14:33 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version: 5.0.2
Cluster size: 3
OS: Debian buster, but Scylla runs in Docker

When I use boto3 or the AWS cli to create a table with a `RANGE` `KeyType` in `KeySchema` and a secondary index without `RANGE` `KeyType` in `KeySchema`:

```python
client.create_table(
    AttributeDefinitions=[
        {
            'AttributeName': 'channelId',
            'AttributeType': 'S'
        },
        {
            'AttributeName': 'ownerId',
            'AttributeType': 'S'
        },
    ],
    TableName='some-table',
    KeySchema=[
        {
            'AttributeName': 'channelId',
            'KeyType': 'HASH'
        },
        {
            'AttributeName': 'ownerId',
            'KeyType': 'RANGE'
        },
    ],
    GlobalSecondaryIndexes=[
        {
            'IndexName': 'ownerId-index',
            'KeySchema': [
                {
                    'AttributeName': 'ownerId',
                    'KeyType': 'HASH'
                },
            ],
            'Projection': {
                'ProjectionType': 'ALL',
            },
        },
    ],
    BillingMode='PAY_PER_REQUEST',
)
```

ScyllaDB will automatically add an extra `KeySchema` entry for the global secondary index, based on the `RANGE` `KeyType` defined in the table his `KeySchema`.

Relevant output of describe-table:

```
'GlobalSecondaryIndexes': [{'IndexName': 'ownerId-index',
                           'KeySchema': [{'AttributeName': 'ownerId',
                                          'KeyType': 'HASH'},
                                         {'AttributeName': 'channelId',
                                          'KeyType': 'RANGE'}]}],
```

When doing same the same on AWS, the relevant output of describe-table is:

```
'GlobalSecondaryIndexes': [{'IndexName': 'ownerId-index',
                           'KeySchema': [{'AttributeName': 'ownerId',
                                          'KeyType': 'HASH'}]}],
```

So no `RANGE` `KeyType` on the secondary index, which is as expected because we do not supply a `RANGE` `KeyType` in the `KeySchema` for the global secondary index, only on the table itself.

**Comment by tzach** [comment] 2022-09-05 19:14
@nyh FYI

**Comment by nyh** [comment] 2022-09-05 20:56
This is a duplicate of issue #5320.
We know of that issue for almost three years now, but so far nobody was really bothered by it so it didn't get any priority. Maybe if you can explain what kinds of problems it causes for which application, we can increase the priority to fix it.

**Closed by nyh** 2022-09-05 20:56 UTC
Labels: Alternator

**Comment by bartpeeters** [comment] 2022-09-06 08:15
@nyh 
It is one of the things that makes Alternator not work with Terraform, after creating the table using Terraform and then applying the plan again it will pickup 'changes' to the index:

```
- global_secondary_index {
    - hash_key           = "ownerId" -> null
    - non_key_attributes = [] -> null
    - range_key          = "channelId" -> null
    - read_capacity      = 0 -> null
    - write_capacity     = 0 -> null
  }
+ global_secondary_index {
    + hash_key           = "ownerId"
    + name               = "ownerId-index"
    + non_key_attributes = []
    + projection_type    = "ALL"
  }
```

Terraform index resource code:

```
global_secondary_index {
  name            = "ownerId-index"
  hash_key        = "ownerId"
  projection_type = "ALL"
}
```

But I don't think this is the only thing tripping up Terraform, you also don't see the `name` or `projection_type` properties on the current table.

**Comment by nyh** [comment] 2022-09-06 16:20
> But I don't think this is the only thing tripping up Terraform, you also don't see the `name` or `projection_type` properties on the current table.

You're right about the missing properties in DescribeTable as well - this is issue #5026, and the missing GSI properties is tested by the currently-failing test `test_gsi.py`::`test_gsi_describe`. But "IndexName" should not be missing - can you please check if it's really missing? The "Projection" I know is missing.

**Comment by bartpeeters** [comment] 2022-09-07 08:23
`IndexName` does not seem to be missing, when using aws CLI and describe-table:

```
"GlobalSecondaryIndexes": [
    {
        "IndexName": "ownerId-index",
        "KeySchema": [
            {
                "AttributeName": "ownerId",
                "KeyType": "HASH"
            },
            {
                "AttributeName": "channelId",
                "KeyType": "RANGE"
            }
        ]
    }
]
```

No idea why Terraform outputs the `-` part without the `name`.

I also tried changing the `global_secondary_index` to contain the `range_key`:

```
global_secondary_index {
  name            = "ownerId-index"
  hash_key        = "ownerId"
  range_key = "channelId"
  projection_type = "ALL"
}
```

But Terraform still detects changes:

```
- global_secondary_index {
    - hash_key           = "ownerId" -> null
    - non_key_attributes = [] -> null
    - range_key          = "channelId" -> null
    - read_capacity      = 0 -> null
    - write_capacity     = 0 -> null
  }
+ global_secondary_index {
    + hash_key           = "ownerId"
    + name               = "ownerId-index"
    + non_key_attributes = []
    + projection_type    = "ALL"
    + range_key          = "channelId"
  }
```

So I think Terraform really needs

```
"Projection": {
     "ProjectionType": "ALL"
},
```

to be returned from `describe-table`, for it to not think the index needs to be recreated.
