### ISSUE TITLE
cql_cast_test.TestCQLCast.test_cast_issue_3110 AssertionError: casting from type varint to type decimal

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13588] opened 2023-04-20 08:06 UTC
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/233/testReport/cql_cast_test/TestCQLCast/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split002___test_cast_issue_3110/
```
AssertionError: casting from type varint to type decimal: expected 3.2767456456456457E+52 but got 32767456456456456456545678943512357658768763546575675.0
assert '32767456456456456456545678943512357658768763546575675.0' == '3.2767456456456457E+52'
  - 3.2767456456456457E+52
  + 32767456456456456456545678943512357658768763546575675.0
```

Could be related to #13551 / #13564

**Comment by bhalevy** [comment] 2023-04-20 08:06
@nyh please look into this

**Comment by nyh** [comment] 2023-04-20 08:11
It's not related directly to that issue and PR. Rather it is related to the fact that while working on those, I found and closed issue #3110 when I realized it was invalid - the issue considered a bug in Cassandra (which has been long solved since) as a thing we should do as well. When I closed issue #3110, a dtest (aptly named "test_cast_issue_3110") that was listed as "requires" that issue, started to run, and unsurprisingly it fails because it tests the wrong thing.

So this is a dtest bug, @juliayakovlev @fruch please look into it.

**Comment by fruch** [comment] 2023-04-20 08:17
the test was correct matching cassnadra expectations back then 

anyhow logically those are equal, but the test compares strings. 
```python
>>> 3.2767456456456457E+52 == 32767456456456456456545678943512357658768763546575675.
True
```

scylla stopped sending back the short notation, and we need to fix the test to be o.k. with both.

other tests having this issue were fixed not long ago, this one should be fixed as well

**Comment by nyh** [comment] 2023-04-20 08:31
> the test was correct matching cassnadra expectations back then
> 
> anyhow logically those are equal, but the test compares strings.

Not exactly. Both varint (the original type) and decimal (the type being cast into) are variable-length (i.e., infinite precision) types. So converting the number 32767456456456456456545678943512357658768763546575675 into 3.2767456456456457E+52 isn't just a valid choice - it's a bug - it means precision was lost in the conversion. It's a bug that Cassandra had in the past (and since fixed) and Scylla never had.

> ```python
> >>> 3.2767456456456457E+52 == 32767456456456456456545678943512357658768763546575675.
> True
> ```

Python's floating point type is the usual 64-bit "double", and doesn't have infinite precision like Cassandra's varint or decimal types which are being tested by this test. Cassandra also has a limited-precision type called "double", but it's not what is being tested here.

> scylla stopped sending back the short notation, and we need to fix the test to be o.k. with both.
> other tests having this issue were fixed not long ago, this one should be fixed as well

It's not the same issue. Those other tests involved the way a "double" value was printed. It's not a "double" being tested in this specific test.

**Comment by fruch** [comment] 2023-04-20 08:43
So we need to compare results with cassndra 4.1 ?, i.e. that should be the oracle and if it's doesn't match it's a scylla bug ?

**Comment by fruch** [comment] 2023-04-20 09:04
running this test with Cassandra 4.1, there are a few differences between cassandra and  scylla

1) scylla adds `.0`, Cassandra drops it, I think safe enough for the test to ignore this difference. 
2) in case of avg Cassandra round the answer (SELECT avg(cast(varint_clmn as decimal)) FROM cast_varint_test)

````
Expected :'-2110054581'
Actual   :'-2110054580.3'
```
@nyh there an option issue for the avg difference ?

**Comment by nyh** [comment] 2023-04-20 11:31
> running this test with Cassandra 4.1, there are a few differences between cassandra and scylla
> 
>     1. scylla adds `.0`, Cassandra drops it, I think safe enough for the test to ignore this difference.

I agree.
 
>     2. in case of avg Cassandra round the answer (SELECT avg(cast(varint_clmn as decimal)) FROM cast_varint_test)
> 
> 
> ```
> Expected :'-2110054581'
> Actual   :'-2110054580.3'
> ``` 
> 
> @nyh there an open issue for the avg difference ?

No. Are you saying that this is a Cassandra bug, or a Scylla bug? The statement `SELECT avg(cast(varint_clmn as decimal))` should perform the average using the "decimal" type, so result in a fraction, not an integer. I think the integer is wrong.

I'll try writing a test specifically for that and open an issue accordingly when I understand what the problem is.

**Comment by nyh** [comment] 2023-04-20 11:43
I discovered something very surprising: If I add two "decimal" values 1.0 and 2.0, the avg() is 1.5 as expected. The same is true for 1 and 2.0 or 1.0 and 2. But... If I average 1 and 2 (again, these are `decimal` values, not `varint`!) the result is an integer on both Cassandra and Scylla (rounded to 1 on Scylla, to 2 on Cassandra). This looks like a bug, I'll check if it is known (in Scylla or Cassandra) and report it.

I'm guessing that the "actual" in your above example came from an old version of Cassandra which used "double" for the calculations so didn't have this bug.

**Comment by nyh** [comment] 2023-04-20 11:54
I opened #13601

**Comment by nyh** [comment] 2023-04-20 12:02
Opened https://issues.apache.org/jira/browse/CASSANDRA-18470 on Cassandra.
By the way, @fruch the two problems you reported above may be related. If Scylla adds ".0" in its CAST() from varint to decimal, then the average will be done correctly. While if Cassandra doesn't add the ".0" it will have this CASSANDRA-18470  on the AVG, and return a rounded integer.

**Comment by fruch** [comment] 2023-04-20 12:05
meanwhile I'm change all those cast test to align to Cassandra 4.1, and remove all the skips from the test matrix.

I did run into one more difference in timestamps, that scylla prints them without milisecscondes and without the timezone marker Z at the end

````
SELECT cast(timestamp_clmn as text) FROM cast_timestamp_test WHERE k=0

Expected :'2017-12-27T11:57:42.000Z'
Actual   :'2017-12-27T11:57:42'
````

**Comment by nyh** [comment] 2023-04-20 12:19
@fruch the timestamp difference is the same as reported in #7997 (there it was for toJson(), but apparently "cast as text" has the same issue). I don't know how we never noticed this difference. As all other tests that fail now in this test, the problem has nothing to do with casts - but it's nice this test finds so many bugs.

**Comment by nyh** [comment] 2023-04-20 12:52
> Opened https://issues.apache.org/jira/browse/CASSANDRA-18470 on Cassandra. By the way, @fruch the two problems you reported above may be related. If Scylla adds ".0" in its CAST() from varint to decimal, then the average will be done correctly.

I now understand the issue better (see https://github.com/scylladb/scylladb/issues/13601) and adding ".0" doesn't make it "correct", just one digit more correct. For example, averaging 0, 0, 1 results in 0 (zero digits of precision) but averaging 0.0, 0.0, 1.0 results in 0.3. If we want 6 digits of precision in the average, we need inputs with six digits of precision, e.g., 0.000000, 0.000000, 1.000000 will average to 0.333333.

**Comment by nyh** [comment] 2023-04-20 15:31
We discussed here a lot of interesting differences and bugs (and opened new issue), but at the core, this issue was about a dtest that started to fail and had to be fixed, and @fruch did this in https://github.com/scylladb/scylla-dtest/pull/3130.

So I think this issue can be closed (or closed once that PR is committed).

**Comment by nyh** [comment] 2023-05-24 10:54
The dtest was fixed, so closing this issue.

**Comment by DoronArazii** [comment] 2023-05-31 10:32
Pushing the "close" button per Nadav's last comment ^^

/Cc @nyh

**Closed by DoronArazii** 2023-05-31 10:32 UTC
Labels: dtest
