### ISSUE TITLE
Accept peer SSL certificates

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#7517] opened 2020-11-01 06:01 UTC
Accept peer's SSL certificates. Allowing Scylla to perform additional checks from the client

https://issues.apache.org/jira/browse/CASSANDRA-14652

**Comment by slivne** [comment] 2020-11-05 10:35
@elcallio please review this - we should consider if this should be added

**Comment by avikivity** [comment] 2020-11-05 10:38
It is eminently reasonable, I think it should be supported.

**Comment by elcallio** [comment] 2020-11-09 10:37
The key word here is "allowing". From what I can see in the commit, and code after it, there is no instance where an authenticator actually _uses_ said SSL certificates... Is this an interface patch for open source cassandra with some actual sasl-ssl auth only done in datastax?

**Comment by avikivity** [comment] 2020-11-09 11:12
The patch author is from Apple, so probably not.

**Comment by avikivity** [comment] 2020-11-09 11:14
But yes, from the description it looks remarkably useless.

To make it useful we'll need some mapping from certificate names to Scylla users.

**Comment by elcallio** [comment] 2020-11-09 11:57
Is that really what you want? I maybe imagined that you would want to combine password check with certificate validation? But this is somewhat redundant in that case, since we already have client verification validation optional. 
Mapping username -> cert seems weird to me, and would at the very least require either publicly signed certs or yet another trust store configured for the authenticator. 

I would very much like to know which problem this is supposed to solve, since, again, we do already allow client cert verification for tls connections.

**Comment by avikivity** [comment] 2020-11-09 11:59
I retract my suggestion, I'm not knowledgeable enough in this area.

@tzach please explain what you want.

**Comment by nyh** [comment] 2022-11-13 10:29
A newer duplicate of this issue: #10099

**Comment by eliransin** [comment] 2023-10-31 09:34
@elcallio  #10099 has been resolved (which @nyh stated is a duplicate of this one), since I am not sure it is an exact duplicate.
Can you please either close this one or leave a comment of what is the gap between this issue and the aforementioned one?

**Comment by elcallio** [comment] 2023-10-31 09:37
@eliransin - I think @tzach , as OP, and feature requester general, need to decide if the cert-based auth feature fulfils whatever the cassandra commit in question aimed to support...

**Comment by eliransin** [comment] 2023-11-01 12:11
> @eliransin - I think @tzach , as OP, and feature requester general, need to decide if the cert-based auth feature fulfils whatever the cassandra commit in question aimed to support...

@tzach are there any caveats that the certificate base authentication doesn't support?

**Comment by mykaul** [comment] 2023-11-01 13:04
> > @eliransin - I think @tzach , as OP, and feature requester general, need to decide if the cert-based auth feature fulfils whatever the cassandra commit in question aimed to support...
> 
> @tzach are there any caveats that the certificate base authentication doesn't support?

How do you revoke access?

**Comment by elcallio** [comment] 2023-11-01 13:10
certficate_revocation_list in tls options for the connection.

**Comment by mykaul** [comment] 2023-11-01 13:20
> certficate_revocation_list

Do we fetch it online, or via a file that needs to be updated? (Anyway, if we have a way - great!)

**Comment by elcallio** [comment] 2023-11-01 13:24
It is a file, needs to be updated (per node), but it is included in reloadable aspects of TLS config, so should auto-update from there.

**Comment by elcallio** [comment] 2024-08-19 10:56
Scylla certificate authentication was merged ages ago. Closing this.

**Closed by elcallio** 2024-08-19 10:56 UTC
Labels: enhancement, user request
