### ISSUE TITLE
nodetool scrub command failed for keyspace1

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#14341] opened 2023-06-21 13:29 UTC
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Scenario: run a nemesis named `disrupt_corrupt_then_scrub`.
It goes over all non-system keyspaces one by one and runs a `nodetool scrub --skip-corrupted`.
The command ran on node-17 and succeeded for several keyspaces:
```
< t:2023-06-09 07:46:20,413 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted audit"...
< t:2023-06-09 07:46:30,033 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  scrub --skip-corrupted audit" finished with status 0
< t:2023-06-09 07:46:30,080 f:cluster.py      l:2587 c:sdcm.cluster_aws     p:DEBUG > Node longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 [34.254.243.205 | 10.4.2.46] (seed: False): Command '/usr/bin/nodetool  scrub --skip-corrupted audit' duration -> 9.620077687985031 s
< t:2023-06-09 07:46:30,114 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_9"...
< t:2023-06-09 07:46:36,924 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_9" finished with status 0
< t:2023-06-09 07:46:36,924 f:cluster.py      l:2587 c:sdcm.cluster_aws     p:DEBUG > Node longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 [34.254.243.205 | 10.4.2.46] (seed: False): Command '/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_9' duration -> 6.679275764996419 s
< t:2023-06-09 07:46:36,952 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted mview"...
< t:2023-06-09 07:48:58,542 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  scrub --skip-corrupted mview" finished with status 0
< t:2023-06-09 07:48:58,542 f:cluster.py      l:2587 c:sdcm.cluster_aws     p:DEBUG > Node longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 [34.254.243.205 | 10.4.2.46] (seed: False): Command '/usr/bin/nodetool  scrub --skip-corrupted mview' duration -> 141.58956764798495 s
< t:2023-06-09 07:48:58,572 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_8"...
< t:2023-06-09 07:49:04,735 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_8" finished with status 0
< t:2023-06-09 07:49:04,740 f:cluster.py      l:2587 c:sdcm.cluster_aws     p:DEBUG > Node longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 [34.254.243.205 | 10.4.2.46] (seed: False): Command '/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_8' duration -> 6.152492672990775 s
< t:2023-06-09 07:49:04,751 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted sec_index"...
< t:2023-06-09 07:51:22,373 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  scrub --skip-corrupted sec_index" finished with status 0
< t:2023-06-09 07:51:22,426 f:cluster.py      l:2587 c:sdcm.cluster_aws     p:DEBUG > Node longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 [34.254.243.205 | 10.4.2.46] (seed: False): Command '/usr/bin/nodetool  scrub --skip-corrupted sec_index' duration -> 137.61757291899994 s
< t:2023-06-09 07:51:22,490 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_3"...
< t:2023-06-09 07:51:29,099 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_3" finished with status 0
< t:2023-06-09 07:51:29,189 f:cluster.py      l:2587 c:sdcm.cluster_aws     p:DEBUG > Node longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 [34.254.243.205 | 10.4.2.46] (seed: False): Command '/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_3' duration -> 6.601797412993619 s
< t:2023-06-09 07:51:29,294 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_2"...
< t:2023-06-09 07:51:35,435 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_2" finished with status 0
< t:2023-06-09 07:51:35,436 f:cluster.py      l:2587 c:sdcm.cluster_aws     p:DEBUG > Node longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 [34.254.243.205 | 10.4.2.46] (seed: False): Command '/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_2' duration -> 6.117488875985146 s
< t:2023-06-09 07:51:35,455 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_1"...
< t:2023-06-09 07:51:42,079 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_1" finished with status 0
< t:2023-06-09 07:51:42,147 f:cluster.py      l:2587 c:sdcm.cluster_aws     p:DEBUG > Node longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 [34.254.243.205 | 10.4.2.46] (seed: False): Command '/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_1' duration -> 6.623959996009944 s
< t:2023-06-09 07:51:42,247 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_0"...
< t:2023-06-09 07:51:48,385 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_0" finished with status 0
< t:2023-06-09 07:51:48,386 f:cluster.py      l:2587 c:sdcm.cluster_aws     p:DEBUG > Node longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 [34.254.243.205 | 10.4.2.46] (seed: False): Command '/usr/bin/nodetool  scrub --skip-corrupted drop_table_during_repair_ks_0' duration -> 6.138026553991949 s
```
Then it was executed for the cassandra-stress `keyspace1` and failed with:
```
< t:2023-06-09 07:51:48,454 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted keyspace1"...
< t:2023-06-09 07:52:18,894 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "/usr/bin/nodetool  scrub --skip-corrupted keyspace1"; Exit status: 2
< t:2023-06-09 07:52:18,939 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-09 07:52:18.921: (NodetoolEvent Severity.ERROR) period_type=end event_id=854744df-87d5-48a2-a71c-63862afd3e80 during_nemesis=CorruptThenScrub duration=30s: nodetool_command=scrub node=longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 errors=["Encountered a bad command exit code!\n\nCommand: '/usr/bin/nodetool  scrub --skip-corrupted keyspace1'\n\nExit code: 2\n\nStdout:\n\n\n\nStderr:\n\n\tat sun.rmi.transport.Transport.serviceCall(Transport.java:196)\n\tat sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)\n\tat sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)\n\tat sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)\n\tat java.security.AccessController.doPrivileged(Native Method)\n\tat sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:750)\n\n\n", 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2586, in run_nodetool\n    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run\n    result = _run()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner\n    return func(*args, **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run\n    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute\n    result = connection.run(**command_kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run\n    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run\n    raise UnexpectedExit(result)\nsdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!\n\nCommand: \'/usr/bin/nodetool  scrub --skip-corrupted keyspace1\'\n\nExit code: 2\n\nStdout:\n\n\n\nStderr:\n\n\tat sun.rmi.transport.Transport.serviceCall(Transport.java:196)\n\tat sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)\n\tat sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)\n\tat sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)\n\tat java.security.AccessController.doPrivileged(Native Method)\n\tat sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:750)\n\n\n\n']
```

The logs of node-17 only shows pulling of a new schema version at that time:
```
system.log:Jun 09 07:51:22 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  4] compaction - [Scrub sec_index.users_address_ind_index 699c5f50-069a-11ee-a766-43315261f4b7] Finished scrub
bing in skip mode 1 sstables to [/var/lib/scylla/data/sec_index/users_address_ind_index-194148b004b311eea98744a19294ac6a/me-10756-big-Data.db:level=0]. 31MB to 31MB (~99% of original) in 6020ms = 5MB/s. ~3
05792 total partitions merged to 305743.
system.log:Jun 09 07:51:42 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] migration_manager - Requesting schema pull from 10.4.1.221:6
system.log:Jun 09 07:51:42 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] migration_manager - Pulling schema from 10.4.1.221:0
system.log:Jun 09 07:51:42 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] schema_tables - Schema version changed to a1564a83-6e10-35fb-8c29-68d5ae2f63b4
system.log:Jun 09 07:51:42 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] migration_manager - Schema merge with 10.4.1.221:0 completed
system.log:Jun 09 07:51:48 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] migration_manager - Requesting schema pull from 10.4.1.221:12
system.log:Jun 09 07:51:48 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] migration_manager - Pulling schema from 10.4.1.221:0
system.log:Jun 09 07:51:48 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] schema_tables - Schema version changed to a1564a83-6e10-35fb-8c29-68d5ae2f63b4
system.log:Jun 09 07:51:48 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] migration_manager - Schema merge with 10.4.1.221:0 completed
system.log:Jun 09 07:51:57 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] migration_manager - Requesting schema pull from 10.4.3.19:12
system.log:Jun 09 07:51:57 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] migration_manager - Pulling schema from 10.4.3.19:0
system.log:Jun 09 07:51:57 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] compaction - [Compact system_schema.columns 82824610-069a-11ee-8acf-43335261f4b7] Compacting [/var/lib/scy
lla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/me-5208-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/me-5194-big-Data.db:l
evel=0:origin=compaction]
system.log:Jun 09 07:51:58 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] schema_tables - Schema version changed to a1564a83-6e10-35fb-8c29-68d5ae2f63b4
system.log:Jun 09 07:51:58 longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 scylla[5437]:  [shard  0] migration_manager - Schema merge with 10.4.3.19:0 completed
```
## Impact

nodetool scrub didn't run on a specific keyspace, probably it's the one with highest load.

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1036-aws
Scylla version (or git commit hash): `2023.1.0~rc6-20230517.ca8d6a0d4fa7` with build-id `3c3e22ad787d01bbfda9da05aa4a62beb1004157`

Cluster size: 5 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-9 (54.216.198.148 | 10.4.2.13) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-8 (34.254.192.137 | 10.4.3.46) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-7 (34.253.18.25 | 10.4.2.182) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-6 (54.194.73.205 | 10.4.0.27) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-5 (54.216.70.54 | 10.4.0.161) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-4 (54.194.208.139 | 10.4.2.174) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-3 (3.250.177.78 | 10.4.1.174) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-23 (34.241.7.56 | 10.4.3.208) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-22 (34.245.144.201 | 10.4.2.152) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-21 (52.215.255.86 | 10.4.1.219) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-20 (34.244.176.128 | 10.4.1.175) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-2 (52.209.140.130 | 10.4.1.114) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-19 (34.241.240.18 | 10.4.3.75) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-18 (3.248.231.10 | 10.4.3.229) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 (34.254.243.205 | 10.4.2.46) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-16 (3.250.67.90 | 10.4.1.179) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-15 (3.251.88.158 | 10.4.2.41) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-14 (3.250.107.33 | 10.4.0.33) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-13 (34.254.100.94 | 10.4.1.81) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-12 (34.240.10.195 | 10.4.3.19) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-11 (54.195.75.97 | 10.4.3.153) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-10 (63.35.252.98 | 10.4.3.120) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-2c733d4e-1 (54.154.223.243 | 10.4.1.221) (shards: 14)

OS / Image: `ami-094190108e73c7d8e` (aws: eu-west-1)

Test: `ics-longevity-mv-si-4days-test`
Test id: `2c733d4e-8037-4c44-ade7-11121a59151e`
Test name: `enterprise-2023.1/SCT_Enterprise_Features/ICS/ics-longevity-mv-si-4days-test`
Test config file(s):

- [longevity-mv-si-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/618b852e4d5384cf988f4d1bab96d8244c52b732/test-cases/longevity/longevity-mv-si-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 2c733d4e-8037-4c44-ade7-11121a59151e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2c733d4e-8037-4c44-ade7-11121a59151e)
- Show all stored logs command: `$ hydra investigate show-logs 2c733d4e-8037-4c44-ade7-11121a59151e`

## Logs:
- **db-cluster-2c733d4e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/db-cluster-2c733d4e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/db-cluster-2c733d4e.tar.gz)
- **sct-runner-events-2c733d4e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/sct-runner-events-2c733d4e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/sct-runner-events-2c733d4e.tar.gz)
- **2023_06_06__10_57_50_567.sct-2c733d4e.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/2023_06_06__10_57_50_567.sct-2c733d4e.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/2023_06_06__10_57_50_567.sct-2c733d4e.log.gz)
- **2023_06_08__02_08_35_418.sct-2c733d4e.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/2023_06_08__02_08_35_418.sct-2c733d4e.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/2023_06_08__02_08_35_418.sct-2c733d4e.log.gz)
- **2023_06_09__16_14_23_380.sct-2c733d4e.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/2023_06_09__16_14_23_380.sct-2c733d4e.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/2023_06_09__16_14_23_380.sct-2c733d4e.log.gz)
- **monitor-set-2c733d4e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/monitor-set-2c733d4e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/monitor-set-2c733d4e.tar.gz)
- **loader-set-2c733d4e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/loader-set-2c733d4e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c733d4e-8037-4c44-ade7-11121a59151e/20230610_220045/loader-set-2c733d4e.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/SCT_Enterprise_Features/job/ICS/job/ics-longevity-mv-si-4days-test/3/)
[Argus](https://argus.scylladb.com/test/b46c8b3c-0d01-42f8-98cc-512c5945a9f5/runs?additionalRuns[]=2c733d4e-8037-4c44-ade7-11121a59151e)
</details>

**Comment by yarongilor** [comment] 2023-06-27 10:57
> Is there a specific log for nodetool (and specifically its scrub operation) ? Can it run with debug/verbose mode? Is it reproducible? Anything interesting in the workload?

Looks like it's a rare error that is not so reproducible.
Can't tell much about any log/debug enhancements.

**Comment by fgelcer** [comment] 2023-08-09 11:55
@DoronArazii

**Comment by DoronArazii** [comment] 2023-08-09 12:43
@denesb can you please have a look

**Comment by denesb** [comment] 2023-08-09 13:07
Unpacking the error message:
```
< t:2023-06-09 07:52:18,939 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-09 07:52:18.921: (NodetoolEvent Severity.ERROR) period_type=end event_id=854744df-87d5-48a2-a71c-63862afd3e80 during_nemesis=CorruptThenScrub duration=30s: nodetool_command=scrub node=longevity-mv-si-4d-2023-1-db-node-2c733d4e-17 errors=["Encountered a bad command exit code!

Command: '/usr/bin/nodetool  scrub --skip-corrupted keyspace1'

Exit code: 2

Stdout:



Stderr:

     at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
     at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
     at java.security.AccessController.doPrivileged(Native Method)
     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:750)


", 'Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2586, in run_nodetool
    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: \'/usr/bin/nodetool  scrub --skip-corrupted keyspace1\'

Exit code: 2

Stdout:



Stderr:

     at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
     at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
     at java.security.AccessController.doPrivileged(Native Method)
     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:750)



']
```

I have no idea what those Java backtraces mean. Possibly a timeout, as according to @yarongilor there is no error in the scylla logs.

**Comment by mykaul** [comment] 2023-08-09 13:12
Any chance we ran out of memory?

**Comment by denesb** [comment] 2023-08-09 13:15
> Any chance we ran out of memory?

I have no idea how that would manifest itself in Java, but if that was the case in scylla, we should see bad allocs in the logs. Although not entirely sure how the REST API would handle these, maybe it just converts it into status=500 response to the client (JMX), which then... well I don't know how JMX works.

**Comment by mykaul** [comment] 2023-08-09 13:31
> > Any chance we ran out of memory?
> 
> I have no idea how that would manifest itself in Java, but if that was the case in scylla, we should see bad allocs in the logs. Although not entirely sure how the REST API would handle these, maybe it just converts it into status=500 response to the client (JMX), which then... well I don't know how JMX works.

If the JMX doesn't have enough memory to run.

**Comment by denesb** [comment] 2023-08-10 03:53
> If the JMX (its JRE) doesn't have enough memory to run.

JMX should always be running in the background. If it crashed, we should see nodetool complaining that it cannot connect. Maybe that is exactly what is happening? I can't tell for sure, because weirdly the exception itself is missing from the error message, we only see the backtrace(s).

**Comment by DoronArazii** [comment] 2023-08-10 07:38
@denesb please summarize what do you need for keep exploring this issue

/Cc @yarongilor @fgelcer

**Comment by denesb** [comment] 2023-08-10 08:51
> @denesb please summarize what do you need for keep exploring this issue
> 
> /Cc @yarongilor @fgelcer

I don't know to be honest. I have 0 experience debugging our nodetool/jmx stack, or java issues in general.

Seeing the error itself, not just the backtrace would help a lot for sure.

**Comment by mykaul** [comment] 2023-08-10 08:53
Why is nodetool scrub calling JMX in the 1st place anyway? How do they interact?

**Comment by denesb** [comment] 2024-04-03 06:57
We are retiring JMX and the Java nodetool. I think we should close this and reopen/open new issue if the problem is seen with the native nodetool as well.

**Closed** 2024-04-03 08:56 UTC
Labels: status/missing information, area/nodetool-scrub
