### ISSUE TITLE
SELECT query raises a seastar::timed_out_error on read_ahead after a node rollback during a rolling upgrade

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylladb#12435] opened 2023-01-03 12:44 UTC
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

During a rolling upgrade AMI job, we are upgrading from the base version: 4.6.11-20221128.6c0825e2a to 5.0.9-20221229.dfb229a18. 
We upgrade nodes 4 and 2 (in that sequence).
We then rollback the second node (node 2 in this case).
After the upgrade we run a suite of CQL queries. On running the query:  `SELECT k FROM no_range_ghost_test`
we got a client `cassandra.OperationTimedOut` error:

```
< t:2023-01-02 15:06:22,554 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > #SORTED SELECT k FROM no_range_ghost_test < t:2023-01-02 15:06:22,554 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > #SORTED SELECT k FROM no_range_ghost_test
< t:2023-01-02 15:06:22,554 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > Traceback (most recent call last):
< t:2023-01-02 15:06:22,554 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3240, in _run_db_queries
< t:2023-01-02 15:06:22,554 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >     res = session.execute(item['queries'][i].replace('#SORTED', ''))
< t:2023-01-02 15:06:22,554 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1329, in execute_verbose
< t:2023-01-02 15:06:22,554 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >     return execute_orig(*args, **kwargs)
< t:2023-01-02 15:06:22,554 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "cassandra/cluster.py", line 2668, in cassandra.cluster.Session.execute
< t:2023-01-02 15:06:22,554 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "cassandra/cluster.py", line 4953, in cassandra.cluster.ResponseFuture.result
< t:2023-01-02 15:06:22,554 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.0.2.169:9042
```

with the `last_host` node showing these seastar timeout errors:

```
Jan 02 15:05:18 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 0] compaction - [Compact system_schema.keyspaces def3b6d0-8aae-11ed-a7e8-fdd8626a41dd] Compacted 2 sstables to [/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-2632-big-Data.db:level=0]. 11kB to 6kB (~54% of original) in 110ms = 58kB/s. ~256 total partitions merged to 13.
Jan 02 15:05:18 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 0] compaction - [Compact system_schema.dropped_columns df0b0f60-8aae-11ed-a7e8-fdd8626a41dd] Compacting [/var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/md-2264-big-Data.db:level=0:origin=upgrade,/var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/md-2272-big-Data.db:level=0:origin=memtable]
Jan 02 15:05:19 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 0] compaction - [Compact system_schema.dropped_columns df0b0f60-8aae-11ed-a7e8-fdd8626a41dd] Compacted 2 sstables to [/var/lib/scylla/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/md-2280-big-Data.db:level=0]. 11kB to 5kB (~51% of original) in 128ms = 44kB/s. ~256 total partitions merged to 2.
Jan 02 15:05:19 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 6] schema_tables - Schema version changed to 9bf72682-5c4b-3a4e-9449-ad99fb7200b6
Jan 02 15:05:21 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 6] compaction - [Compact ks1.table1_mv_0 d2255d00-8aae-11ed-91b7-fddf626a41dd] Compacted 2 sstables to [/var/lib/scylla/data/ks1/table1_mv_0-e02a3c008aa311ed825379cbffdf47b4/md-286-big-Data.db:level=0]. 809MB to 809MB (~100% of original) in 24004ms = 33MB/s. ~179456 total partitions merged to 179308.
Jan 02 15:05:23 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 4] compaction - [Compact ks1.table1_mv_0 d22a6610-8aae-11ed-b6e2-fddb626a41dd] Compacted 2 sstables to [/var/lib/scylla/data/ks1/table1_mv_0-e02a3c008aa311ed825379cbffdf47b4/md-284-big-Data.db:level=0]. 811MB to 811MB (~99% of original) in 25673ms = 31MB/s. ~179584 total partitions merged to 179469.
Jan 02 15:05:23 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 3] compaction - [Compact ks1.table1 d852efd0-8aae-11ed-82fd-fdde626a41dd] Compacted 2 sstables to [/var/lib/scylla/data/ks1/table1-d7eed7d08aa311ed8444275fd59272fe/md-267-big-Data.db:level=0]. 552MB to 552MB (~100% of original) in 15832ms = 34MB/s. ~137728 total partitions merged to 137608.
Jan 02 15:05:25 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] compaction - [Compact ks1.table1_mv_0 d36e09a0-8aae-11ed-8360-fddc626a41dd] Compacted 2 sstables to [/var/lib/scylla/data/ks1/table1_mv_0-e02a3c008aa311ed825379cbffdf47b4/md-285-big-Data.db:level=0]. 812MB to 812MB (~99% of original) in 25751ms = 31MB/s. ~179840 total partitions merged to 179737.
Jan 02 15:05:25 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 2] compaction - [Compact ks1.table1_mv_0 d2c6cd20-8aae-11ed-84b1-fddd626a41dd] Compacted 2 sstables to [/var/lib/scylla/data/ks1/table1_mv_0-e02a3c008aa311ed825379cbffdf47b4/md-282-big-Data.db:level=0]. 824MB to 824MB (~100% of original) in 26992ms = 30MB/s. ~182272 total partitions merged to 182184.
Jan 02 15:05:27 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 0] compaction - [Compact ks1.table1_mv_0 d48e1fa0-8aae-11ed-a7e8-fdd8626a41dd] Compacted 2 sstables to [/var/lib/scylla/data/ks1/table1_mv_0-e02a3c008aa311ed825379cbffdf47b4/md-280-big-Data.db:level=0]. 815MB to 815MB (~100% of original) in 26369ms = 30MB/s. ~180352 total partitions merged to 180135.
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 0 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 0 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 2 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 0 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 2 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 5 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 5 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 5 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 5 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 7 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 7 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 7 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 7 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 0 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 7 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 0 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 7 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 0 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 7 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 7 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 7 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 5 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 0 failed: seastar::timed_out_error (timedout)
Jan 02 15:05:32 rolling-upgrade--centos-db-node-87b03593-2 scylla[45634]:  [shard 5] mutation_reader - shard_reader::close(): read_ahead on shard 7 failed: seastar::timed_out_error (timedout)
```

## Impact

We stop the rolling upgrade procedure when the CQL queries from the suite fail, as was the case here.

## How frequently does it reproduce?

The issue was encountered 2 times, with this report coming from a reproducing run. The previous run can be found here: https://jenkins.scylladb.com/job/scylla-5.0/job/rolling-upgrade/job/rolling-upgrade-ami-test/54/

## Installation details

Kernel Version: 5.11.0-1022-aws
Scylla version (or git commit hash): `4.6.11-20221128.6c0825e2a` with build-id `20fae5748479d9299577bec6c68d77ef5cc0d6a7`

Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--centos-db-node-87b03593-4 (54.195.128.101 | 10.0.3.98) (shards: 8)
- rolling-upgrade--centos-db-node-87b03593-3 (54.246.78.124 | 10.0.2.213) (shards: 8)
- rolling-upgrade--centos-db-node-87b03593-2 (52.18.7.144 | 10.0.2.169) (shards: 8)
- rolling-upgrade--centos-db-node-87b03593-1 (18.203.127.131 | 10.0.2.110) (shards: 8)

OS / Image: `ami-030d958508f559ae9` (aws: eu-west-1)

Test: `rolling-upgrade-ami-test`
Test id: `87b03593-4ed3-4625-b6ba-489aab03e038`
Test name: `scylla-5.0/rolling-upgrade/rolling-upgrade-ami-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/cf186b3791b8c19e5bcb23565dd002cad910cbe9/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 87b03593-4ed3-4625-b6ba-489aab03e038`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=87b03593-4ed3-4625-b6ba-489aab03e038)
- Show all stored logs command: `$ hydra investigate show-logs 87b03593-4ed3-4625-b6ba-489aab03e038`

## Logs:
- **db-cluster-87b03593.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87b03593-4ed3-4625-b6ba-489aab03e038/20230102_151641/db-cluster-87b03593.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87b03593-4ed3-4625-b6ba-489aab03e038/20230102_151641/db-cluster-87b03593.tar.gz)
- **monitor-set-87b03593.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87b03593-4ed3-4625-b6ba-489aab03e038/20230102_151641/monitor-set-87b03593.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87b03593-4ed3-4625-b6ba-489aab03e038/20230102_151641/monitor-set-87b03593.tar.gz)
- **loader-set-87b03593.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87b03593-4ed3-4625-b6ba-489aab03e038/20230102_151641/loader-set-87b03593.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87b03593-4ed3-4625-b6ba-489aab03e038/20230102_151641/loader-set-87b03593.tar.gz)
- **sct-runner-87b03593.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/87b03593-4ed3-4625-b6ba-489aab03e038/20230102_151641/sct-runner-87b03593.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/87b03593-4ed3-4625-b6ba-489aab03e038/20230102_151641/sct-runner-87b03593.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/rolling-upgrade/job/rolling-upgrade-ami-test/55/)
</details>

**Comment by denesb** [comment] 2023-01-03 13:54
> @denesb looks like we should swallow timeouts on read aheads.

Yes, makes sense.

**Comment by KnifeyMoloko** [comment] 2023-01-03 14:06
For completeness - we've also encountered this twice when upgrading from 5.0.8 to 5.0.9, so it's not isolated to upgrade scenarios that involve 4.6.x --> 5.0.x

**Comment by fgelcer** [comment] 2023-01-04 10:01
@avikivity @denesb , who is going to fix this one? who should be assigned to it?

**Comment by denesb** [comment] 2023-01-04 10:07
I will fix it.

**Comment by denesb** [comment] 2023-01-04 10:07
Note that the error is benign.

**Comment by denesb** [comment] 2023-01-04 10:20
Fix is here: https://github.com/scylladb/scylladb/pull/12441

**Comment by fgelcer** [comment] 2023-01-04 11:53
> Note that the error is benign.

@KnifeyMoloko , is it causing the test to fail? how? if the error is benign, but we hit it during some verification, and if just stopped the test, we should either wait for this fix and re-test, or adapt the test to not fail with that error, and continue...

in either case, 5.0.9 is waiting for one of the solutions above

**Comment by fgelcer** [comment] 2023-01-04 12:36
@mykaul the milestone should be 5.0 (it will be patched as 5.0.9), or am i missing something?

**Comment by mykaul** [comment] 2023-01-04 12:58
> @mykaul the milestone should be 5.0 (it will be patched as 5.0.9), or am i missing something?

Don't we need the fix on 5.2 as well?

**Comment by DoronArazii** [comment] 2023-01-04 13:46
Since it will be enter to master first, the correct milestone here is 5.2 (Next OSS version).

It will be backported to 5.0 (maybe to 5.1 as well?)

**Comment by DoronArazii** [comment] 2023-01-04 14:02
> I'm not sure we should backport this: it is just eating a warning log.

Then how it will get into 5.0 branch?

**Comment by denesb** [comment] 2023-01-04 14:04
> > I'm not sure we should backport this: it is just eating a warning log.
> 
> Then how it will get into 5.0 branch?

The question is does it have to? Is a warning in the logs really so bad? Sure it is annoying that is why I posted the fix, the question is just if it really warrants a backport or its something we can live with in older versions.

**Comment by denesb** [comment] 2023-01-04 14:06
Like I said this warning is benign, it is not failing anything is just notifies us in the logs that a background read that we wanted to wait for while stopping a read timed out. Nothing to fix here really. My fix just makes this message not logged for time-outs.

**Comment by avikivity** [comment] 2023-01-04 14:07
@KnifeyMoloko I see the base version, but what is the target version?

@denesb is this a regression due to a recent backport?

**Comment by denesb** [comment] 2023-01-04 14:11
No, this code has been like that (more-or-less) since the multishard reader was written.

**Comment by denesb** [comment] 2023-01-04 14:12
The timeout itself can be a recent regression, but there is no way to tell that just from this log.

**Comment by fgelcer** [comment] 2023-01-04 14:35
> @KnifeyMoloko I see the base version, but what is the target version?

`Scylla version 5.0.9-20221229.dfb229a18 with build-id 59fc05ebe70400602e648217a2af8a7f026ea215`

**Comment by fgelcer** [comment] 2023-01-04 14:35
AFAICT we didn't fail any test for this before, or we have yet another failure in the current test

**Comment by avikivity** [comment] 2023-01-04 14:41
@KnifeyMoloko Please report both versions for all upgrade bug reports.

If it's not a regression, then why was it reported as blocking 5.0.9?

**Comment by fgelcer** [comment] 2023-01-04 15:03
> @KnifeyMoloko Please report both versions for all upgrade bug reports.
> 
> If it's not a regression, then why was it reported as blocking 5.0.9?

@KnifeyMoloko is out today, but for 5.0.8 that job ran and passed, but for 5.0.9 it failed twice... so it is either a regression, or something else is a regression, if not this one

**Comment by avikivity** [comment] 2023-01-04 15:32
It's not impossible for it to be a regression, there were changes in the area.

**Closed** 2023-01-04 20:36 UTC
Labels: Backport candidate

**Comment by yaronkaikov** [comment] 2023-01-05 06:35
@avikivity Can you please backport this to 5.0? , we need it to re-spin 5.0.9

**Comment by DoronArazii** [comment] 2023-01-08 08:40
@avikivity backport ping

**Comment by avikivity** [comment] 2023-01-08 09:45
I'd like to understand if it is a regression or not, and if it is, what caused it, and if not, why tests started failing so late in the 5.0 cycle.

**Comment by fgelcer** [comment] 2023-01-08 10:03
i will re-run the same test but upgrading to `5.0.8` and see if it does reproduce... but AFAICT this is a regression

**Comment by fgelcer** [comment] 2023-01-08 10:07
> I'd like to understand if it is a regression or not, and if it is, what caused it, and if not, why tests started failing so late in the 5.0 cycle.

@avikivity @DoronArazii , running the reproducer [here](https://jenkins.scylladb.com/job/scylla-5.0/job/SCT_Reproducers/job/upgrade-ami/2/) (from 4.6 only, to the same we ran before, and passed last time, 5.0.8 - `5.0.8-20221221.874fa1520 with build-id a6d441e82e54f6facd370c0ce65938c48a993c15`)

**Comment by fgelcer** [comment] 2023-01-08 16:09
> > I'd like to understand if it is a regression or not, and if it is, what caused it, and if not, why tests started failing so late in the 5.0 cycle.
> 
> @avikivity @DoronArazii , running the reproducer [here](https://jenkins.scylladb.com/job/scylla-5.0/job/SCT_Reproducers/job/upgrade-ami/2/) (from 4.6 only, to the same we ran before, and passed last time, 5.0.8 - `5.0.8-20221221.874fa1520 with build-id a6d441e82e54f6facd370c0ce65938c48a993c15`)

@avikivity , from my perspective, the issue did not reproduce when upgrading from 4.6 to 5.0.8... details in [the job](https://jenkins.scylladb.com/job/scylla-5.0/job/SCT_Reproducers/job/upgrade-ami/2/)

**Comment by avikivity** [comment] 2023-01-09 11:41
@denesb so did anything post 5.0.8 made that likely to happen?

**Comment by denesb** [comment] 2023-01-09 12:54
```
bf92c2b44 Merge 'reader_concurrency_semaphore: fix waiter/inactive race' from Botond Dénes
0e388d214 reader_concurrency_semaphore: unify admission logic across all paths
```
These two can cause timeouts if the backport went wrong.
We can try running a job with these two reverted.

**Comment by avikivity** [comment] 2023-01-09 15:59
@fgelcer can you rerun the test with a private for that? I can prepare it.

**Comment by fgelcer** [comment] 2023-01-09 19:26
@yaronkaikov , here is my branch:
https://github.com/fgelcer/scylladb/tree/12435_revert_commits_branch-5.0

**Comment by fgelcer** [comment] 2023-01-09 19:54
[running here](https://jenkins.scylladb.com/view/scylla-5.0/job/scylla-5.0/job/byo/job/byo_build_tests_dtest/)

**Comment by fgelcer** [comment] 2023-01-09 20:43
@avikivity , running the test again, with my branch reverting the 2 commits listed by @denesb .
can be tracker [in here](https://jenkins.scylladb.com/job/scylla-5.0/job/SCT_Reproducers/job/upgrade-ami/3/)

**Comment by fgelcer** [comment] 2023-01-10 05:21
@avikivity , @denesb , running branch-5.0 with these 2 commits reverted did fix the issue, and one of them is indeed the cause of the regression ([Jenkins job passed](https://jenkins.scylladb.com/job/scylla-5.0/job/SCT_Reproducers/job/upgrade-ami/3/))

what now? do we revert them for `5.0.9` or we patch `5.0.9` to include a fix?

**Comment by denesb** [comment] 2023-01-10 06:17
I think revert. I don't know what the problem is. Let's see what @avikivity says.

**Comment by fgelcer** [comment] 2023-01-10 06:38
> I think revert. I don't know what the problem is. Let's see what @avikivity says.

if @avikivity agrees, then we need to rebuild `5.0.9` with these 2 commits reverted.. @yaronkaikov FYI

**Comment by denesb** [comment] 2023-01-11 05:10
Queued the reverts.

**Comment by yaronkaikov** [comment] 2023-01-11 06:15
@Annamikhlin once it's promoted we need to re-spin 5.0.9

**Comment by avikivity** [comment] 2023-02-05 17:19
@denesb please see what we missed with the backport and redo it.

**Comment by denesb** [comment] 2023-02-09 09:52
I re-did the backport and double checked that I didn't miss anything. Re-pushed the backports.
The strange thing is, I didn't find anything missing in the original backports. Not sure what went wrong.

**Comment by avikivity** [comment] 2023-04-16 19:43
@denesb please check that all active branches are covered and drop the label if so.

**Comment by denesb** [comment] 2023-04-17 05:02
This isssue is a bit confusing because it was opened for a real bug, but was fixed with a symptom treating patch: silencing the error, instead of fixing the source.
I think the error silencing is not worth backporting.
