### ISSUE TITLE
Gracefully handle cases when there are to many tombstones

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#3672] opened 2018-08-08 11:43 UTC
Cassandra has TombstoneOverwhelmingException added long ago https://issues.apache.org/jira/browse/CASSANDRA-6117

That is no now propagate  to the client ...

To help users understand this case 
- we should log such partitions (like large_partitions)
- add them to a system table (like the large_partitions table)
- add a metric so this can be viewable from the outside.

**Comment by avikivity** [comment] 2018-08-08 12:07
Another alternative (which allows the user to get the data) is to return an empty page while processing tombstones.

**Comment by tgrabiec** [comment] 2018-08-08 12:49
This issue mentions solutions, but I am missing a statement of the problem.

@avikivity Returning empty pages would still force the application layer to wait for live data. If the problem is that the page may time-out, because page processing time is not proportional to the size of the page, then I think empty pages are not a general solution. It won't work for count(*). We need a different mechanism in the driver to keep the query alive.

**Comment by avikivity** [comment] 2018-08-08 13:01
The problem is that you have a partition with a large prefix of row tombstones, or a range with a large prefix  of row and partition tombstones, your queries will time out.

A mechanism to keep the query alive is not to use timeouts when your query is not real-time. The problem with that is that other bugs or failures are then not reported. It's possible in principle to handle these problems, but in practice there's always another one.

Why wouldn't empty pages work for count(*)? return an empty page with the paging state containing the last primary key encountered, and an intermediate count. It could even work with map/reduce (we'd return a list of such states together with end-tokens).

**Comment by avikivity** [comment] 2020-11-24 13:02
Reviving. + @psarna, @denesb .

First we need to separate between OLTP and analytics. For OLTP empty-page keepalives are bad, since they can keep alive a query that has timed out. We should not send a keepalive past the timeout.

For analytics queries (so declared with ALTER SESSION), the timeout is only used to make sure the node did not dies. The client is interested in the result if it can be obtained.

I found this:

```c++
stop_iteration reconcilable_result_builder::consume(clustering_row&& cr, row_tombstone, bool is_alive) {
    _live_rows += is_alive;
    auto stop = _memory_accounter.update_and_check(cr.memory_usage(_schema));
    if (is_alive) {
        // We are considering finishing current read only after consuming a
        // live clustering row. While sending a single live row is enough to
        // guarantee progress, not ending the result on a live row would
        // mean that the next page fetch will read all tombstones after the
        // last live row again.
        _stop = stop;
    }
    return _mutation_consumer->consume(std::move(cr)) || _stop;
}
```

If we can divorce the clustering key kept for paging from the last live clustering key, then we could solve this. Something like std::optional<primary_key> _page_resume_override. If set, instead of starting at the last key in the data, start here. This works not only for empty pages, but also for [live dead dead dead ... dead{repeats 10000000 times}].

**Comment by denesb** [comment] 2020-11-24 14:01
> Something like std::optional<primary_key> _page_resume_override.

I assume you meant `std::optional<clustering_key>`, or rather, `std::optional<position_in_partition>` if you want to be able to cover range tombstones as well.

This would work well if we only consider dead rows, as in row tombstones, but is soon complicated if you consider range tombstones. Range tombstones that apply to the read range have to be accumulated in memory so that we can decide if any live row we read is covered by them or not. There can be arbitrary number of these as they are allowed to overlap.

Lets consider two cases with range tombstones and see how this could help them:
1) the partition has many range tombstones, that cover some of the rows, not enough to cause memory problems but enough to cause a timeout
2) the partition has so many range tombstones that it is enough to consume all memory dedicated to the read/page or even cause OOM

In case (1) we want to wrap-up the page before we time-out and send whatever we have to the coordinator. We might be positioned at a dead row and want to continue from this row on the next page, either because we haven't seen a live row yet, or because we don't want to repeat the work of dropping the many dead rows (covered by the range tombstone) seen since the last seen live one. So we wrap up the page and send whatever we have along with the position of the last processed [dead] row to the coordinator. On the next page we continue from this position. The problem is that all those pesky range tombstones have to be re-emitted again because they still apply to the read-range. This is not really a problem if we hit the querier cache because then all those range tombstones are still in memory and we can continue from where we left off. If we miss, the range tombstones have to be re-accumulated again, consuming precious time from the time window we have to fill the page, although we will still be able to make progress.

This mechanism would not help case (2) at all however. The problem in the first place is that accumulating all the range tombstones takes too much memory, so we have to interrupt it. Remembering where we were when doing this is of no help. On the next page we will need all of them all the same, so we'll start from the beginning and will not be able to make any progress.

An edge case is when accumulating all the range tombstones takes too much time, instead of too much memory. This is another case that is not helped by the proposed mechanism.

So the proposal can help some [common] subset of all the cases, it cannot provide a solution to all of them.

**Comment by vladzcloudius** [comment] 2020-11-24 14:02
> This issue mentions solutions, but I am missing a statement of the problem.
> 
> @avikivity Returning empty pages would still force the application layer to wait for live data. If the problem is that the page may time-out, because page processing time is not proportional to the size of the page, then I think empty pages are not a general solution. It won't work for count(*). We need a different mechanism in the driver to keep the query alive.

The problem is less timeouts but scylla crashing due to OOM. 
We have a few users reporting intensive crashes while the analysis (made by @avikivity) makes us believe that the root cause is a long tombstones prefix.

I think that the definition of a solution stated by @slivne in the opening message is the best way to go.

**Comment by denesb** [comment] 2020-11-24 14:20
In my opinion the real solution is what @avikivity  proposed + de-overlapping range tombstones. If you de-overlap range tombstones there is only ever one of them that you have to keep in memory, instead of an arbitrary number. They will also have distinct positions. Of course this is not what we should start with. We should first implement the TombstoneOverwhelmingException protection, then proceed to do the real fix.

**Comment by avikivity** [comment] 2020-11-24 14:21
> > Something like std::optional<primary_key> _page_resume_override.
> 
> I assume you meant `std::optional<clustering_key>`, or rather, `std::optional<position_in_partition>` if you want to be able to cover range tombstones as well.

I'd like to support a full scan of a table that contains nothing but partition tombstones. So we'd read a few thousand partition tombstones, and send an empty page with resume_after = <the last partition key we read>.


> 
> This would work well if we only consider dead rows, as in row tombstones, but is soon complicated if you consider range tombstones. Range tombstones that apply to the read range have to be accumulated in memory so that we can decide if any live row we read is covered by them or not. There can be arbitrary number of these as they are allowed to overlap.

Range tombstones must be solved separately by deoverlapping them.

Since they are rare, I am prepared to start without deoverlap, but the deoverlap is long overdue and we should volunteer someone to do it.

> 
> Lets consider two cases with range tombstones and see how this could help them:
> 
> 1. the partition has many range tombstones, that cover some of the rows, not enough to cause memory problems but enough to cause a timeout
> 2. the partition has so many range tombstones that it is enough to consume all memory dedicated to the read/page or even cause OOM
> 
> In case (1) we want to wrap-up the page before we time-out and send whatever we have to the coordinator. We might be positioned at a dead row and want to continue from this row on the next page, either because we haven't seen a live row yet, or because we don't want to repeat the work of dropping the many dead rows (covered by the range tombstone) seen since the last seen live one. So we wrap up the page and send whatever we have along with the position of the last processed [dead] row to the coordinator. On the next page we continue from this position. The problem is that all those pesky range tombstones have to be re-emitted again because they still apply to the read-range. This is not really a problem if we hit the querier cache because then all those range tombstones are still in memory and we can continue from where we left off. If we miss, the range tombstones have to be re-accumulated again, consuming precious time from the time window we have to fill the page, although we will still be able to make progress.
> 
> This mechanism would not help case (2) at all however. The problem in the first place is that accumulating all the range tombstones takes too much memory, so we have to interrupt it. Remembering where we were when doing this is of no help. On the next page we will need all of them all the same, so we'll start from the beginning and will not be able to make any progress.
> 
> An edge case is when accumulating all the range tombstones takes too much time, instead of too much memory. This is another case that is not helped by the proposed mechanism.
> 
> So the proposal can help some [common] subset of all the cases, it cannot provide a solution to all of them.

**Comment by avikivity** [comment] 2020-11-24 14:22
In fact both are needed. As I noted above, OLTP workloads don't care if you can slog your way through millions of tombstones to find a live row, it is too late by now.

**Comment by vladzcloudius** [comment] 2020-11-24 14:59
> In fact both are needed. As I noted above, OLTP workloads don't care if you can slog your way through millions of tombstones to find a live row, it is too late by now.

If by "both" you refer both Shlomi's proposal (short term solution) and "zero page" + de-overlapping (long term solution) - then I couldn't agree more.

**Comment by avikivity** [comment] 2020-11-24 16:36
Forgot to mention, it can work for count(*). We keep sending an empty page for every N internal pages consumed by the aggregation machinery (perhaps N=1, maybe a little more). The paging state contains the current aggregation state, and primary key to continue from. This lets the client continue to push the server to complete the query, so each side can be sure the other hasn't abandoned it (client: server is still alive. server: client is still interested in the query).

**Comment by dorlaor** [comment] 2020-11-24 16:59
Apart from paging empty pages back, how can we get rid from those
tombstones?
We can try to mark all of the relevant sstables for compaction.

Another option is to rewrite that affected partition by rewrite it all
,squashing all of the tombstones and data into a fresh new sstable.
I think it's impossible to do it w/ the current format and timestamp but
it may worth an enhancement for these cases.

**Comment by tgrabiec** [comment] 2021-08-12 21:53
@dorlaor Here's a sketch of one idea to make the impact of tombstones less significant: https://github.com/scylladb/scylla/issues/3673

**Comment by vladzcloudius** [comment] 2021-08-12 22:51
> @dorlaor Here's a sketch of one idea to make the impact of tombstones less significant: #3673

@tgrabiec According to last comments in #3673 the implementation of that idea requires changing the sstable layout which seems to be a bit far fetched IMHO.

Any reason not to implement "empty page" idea as a first stage?
The problem as Avi described above is not in being able to read a partition with long prefix tombstones prefix fast but rather being able to read it at all. Today such queries time out. With empty pages a Client will be able to progress without getting timeout from the DB.

And getting a lot of empty pages is actually a good indication that something needs to be done by the Client (e.g. reducing gc_grace, or running a major).

**Comment by tgrabiec** [comment] 2021-08-12 23:38
> > @dorlaor Here's a sketch of one idea to make the impact of tombstones less significant: #3673
> 
> @tgrabiec According to last comments in #3673 the implementation of that idea requires changing the sstable layout which seems to be a bit far fetched IMHO.
> 
> Any reason not to implement "empty page" idea as a first stage?

No reason, we should do empty pages or similar first.

**Comment by avikivity** [comment] 2022-08-10 21:32
@denesb is this not complete?

**Comment by denesb** [comment] 2022-08-11 02:43
There were many ideas listed in this issue, not all of which are implemented yet.

**Comment by avikivity** [comment] 2022-08-11 09:58
We don't have to implement all ideas, just need to gracefully cases where there are to many tombstones.

**Comment by denesb** [comment] 2022-08-11 10:05
We should be graceful enough now. I suppose we can close this.

**Comment by avikivity** [comment] 2022-08-11 10:12
A long saga has ended.

**Closed by avikivity** 2022-08-11 10:12 UTC
Labels: enhancement, stability
