### ISSUE TITLE
Warning of: sstable - Generating a new run identifier for SSTable me-9184-big-Data.db as overlapping was detected

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#12124] opened 2022-11-29 07:47 UTC
## Installation details

Kernel Version: 5.15.0-1022-aws
Scylla version (or git commit hash): `2022.2.0~rc4-20221106.f5714e0db12f` with build-id `f4a927b8a00fbcd8d48640835192aeaa7968b1f2`
Relocatable Package: http://downloads.scylladb.com/unstable/scylla-enterprise/enterprise-2022.2/relocatable/2022-11-06T15:44:05Z/scylla-enterprise-x86_64-package.tar.gz
Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- alternator-ttl-big-data-set-alterna-db-node-7f741c80-4 (34.243.249.165 | 10.4.3.239) (shards: 14)
- alternator-ttl-big-data-set-alterna-db-node-7f741c80-3 (3.250.5.16 | 10.4.1.247) (shards: 14)
- alternator-ttl-big-data-set-alterna-db-node-7f741c80-2 (63.33.164.105 | 10.4.0.4) (shards: 14)
- alternator-ttl-big-data-set-alterna-db-node-7f741c80-1 (3.253.5.3 | 10.4.0.9) (shards: 14)

OS / Image: `ami-00253925d2028dcef` (aws: eu-west-1)

Test: `longevity-alternator-ttl-big-dataset`
Test id: `7f741c80-adc2-475d-9b3f-4149fdcb907a`
Test name: `scylla-staging/yarongilor/longevity-alternator-ttl-big-dataset`
Test config file(s):

- [longevity-alternator-ttl-big-dataset.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/47785cba3b488badb0417b65c03ce418ead10630/test-cases/longevity/longevity-alternator-ttl-big-dataset.yaml)

## Issue description

**>>>>>>>**
Alternator TTL 
non-LWT
Write ONLY (append)
No nemesis

A test with more (small) keys and possibly higher rate of writing.
Big dataset of 1TB

Configuration:
Alternator TTL enabled.
YCSB write stress  2000200300 keys (1TB)
TTL : 12 hours.
TTL scan interval = 1 hour
tombstone grace-seconds = 2 hours
gc_grace_seconds: 12 hours
Scylla version 2022.2.0~rc4

Scans run every hour.
Items deletion starts after 12 hours.
All data is eventually expired and deleted.

First got a lot of warnings like:
```

2022-11-22 04:24:15.582 <2022-11-22 04:24:15.000>: (DatabaseLogEvent Severity.WARNING) period_type=one-time event_id=1e25b400-b93c-4f3f-9e77-765b6c16444f: type=WARNING regex=(^WARNING|!\s*?WARNING).*\[shard.*\] line_number=18138 node=alternator-ttl-big-data-set-alterna-db-node-7f741c80-4
2022-11-22T04:24:15+00:00 alternator-ttl-big-data-set-alterna-db-node-7f741c80-4  !WARNING | scylla[8017]:  [shard  0] sstable - Unable to delete /var/lib/scylla/data/alternator_usertable_no_lwt/usertable_no_lwt-b0f1e8c0697411ed82e3b2eee6879bc1/me-8764-big-TOC.txt because it doesn't exist.

```
Then later got a lot of warnings like:
```
2022-11-22 04:24:28.104 <2022-11-22 04:24:28.000>: (DatabaseLogEvent Severity.WARNING) period_type=one-time event_id=1e25b400-b93c-4f3f-9e77-765b6c16444f: type=WARNING regex=(^WARNING|!\s*?WARNING).*\[shard.*\] line_number=19921 node=alternator-ttl-big-data-set-alterna-db-node-7f741c80-3
2022-11-22T04:24:28+00:00 alternator-ttl-big-data-set-alterna-db-node-7f741c80-3  !WARNING | scylla[7957]:  [shard  0] sstable - Generating a new run identifier for SSTable /var/lib/scylla/data/alternator_usertable_no_lwt/usertable_no_lwt-b0f1e8c0697411ed82e3b2eee6879bc1/me-9184-big-Data.db as overlapping was detected when inserting it into SSTable run 285f590d-75a2-4954-9abc-3f47a7a4b72c
```

[Alternator Dashboard](https://snapshots.raintank.io/dashboard/snapshot/YTJwuCABenTZzIsv2gsSFQc3NHnJASZS)

[Argus](https://argus.scylladb.com/test/734c8771-99f4-438d-a8ae-71219ed7a50c/runs?additionalRuns[]=7f741c80-adc2-475d-9b3f-4149fdcb907a)

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7f741c80-adc2-475d-9b3f-4149fdcb907a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7f741c80-adc2-475d-9b3f-4149fdcb907a)
- Show all stored logs command: `$ hydra investigate show-logs 7f741c80-adc2-475d-9b3f-4149fdcb907a`

## Logs:
- **db-cluster-7f741c80.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f741c80-adc2-475d-9b3f-4149fdcb907a/20221122_044704/db-cluster-7f741c80.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f741c80-adc2-475d-9b3f-4149fdcb907a/20221122_044704/db-cluster-7f741c80.tar.gz)
- **monitor-set-7f741c80.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f741c80-adc2-475d-9b3f-4149fdcb907a/20221122_044704/monitor-set-7f741c80.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f741c80-adc2-475d-9b3f-4149fdcb907a/20221122_044704/monitor-set-7f741c80.tar.gz)
- **loader-set-7f741c80.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f741c80-adc2-475d-9b3f-4149fdcb907a/20221122_044704/loader-set-7f741c80.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f741c80-adc2-475d-9b3f-4149fdcb907a/20221122_044704/loader-set-7f741c80.tar.gz)
- **sct-runner-7f741c80.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f741c80-adc2-475d-9b3f-4149fdcb907a/20221122_044704/sct-runner-7f741c80.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f741c80-adc2-475d-9b3f-4149fdcb907a/20221122_044704/sct-runner-7f741c80.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-alternator-ttl-big-dataset/3/)

**Comment by raphaelsc** [comment] 2023-07-20 15:14
This is a duplicate of https://github.com/scylladb/scylladb/issues/14560, closing this one.

**Closed by raphaelsc** 2023-07-20 15:14 UTC
