### ISSUE TITLE
CAST and agg functions of CAST from varint (holds very long numbers) to decimal returns value different from Cassandra

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#3110] opened 2017-12-31 07:23 UTC
*Installation details*
Scylla version (or git commit hash): master

*** After rebase it rturns as expected ****
CAST from varint (holds very long numbers) to float returns:
- "Infinity" in Cassandra and "inf" in Scylla
- "NaN" in Cassandra and "nan" in Scylla
***************************************************

CAST/SUM(CAST())/MIN(CAST())/MAX(CAST())//CAST(MAX/MIN/AVG) from varint (holds very long numbers) to decimal returns value with different format, not like in Cassandra (expected result).

**Example:**
CREATE TABLE cast_varint_test (k int PRIMARY KEY, varint_clmn varint):
INSERT INTO cast_varint_test (k, varint_clmn) VALUES (0, 32767456456456456456545678943512357658768763546575675);
INSERT INTO cast_varint_test (k, varint_clmn) VALUES (1, -32767456456456456456545678943512357658768769876743674);
INSERT INTO cast_varint_test (k, varint_clmn) VALUES (2, 4258);

1. SUM(CAST(varint as decimal)): SELECT sum(cast(varint_clmn as decimal)) FROM cast_varint_test;
    Expected result: 4258.0. Actual result: -6330163741
2. CAST(): SELECT cast(max(varint_clmn) as decimal) FROM cast_varint_test
    Expected result: 3.2767456456456457E+52. Actual result: 32767456456456456456545678943512357658768763546575675
3 CAST(MIN(varint) as decimal):  SELECT cast(min(varint_clmn) as decimal) FROM cast_varint_test;
   Expected result: -3.2767456456456457E+52. Actual result: -32767456456456456456545678943512357658768769876743674

**Comment by juliayakovlev** [comment] 2018-01-02 08:10
After rebase I found that  now we return "Infinity" and "NaN" as Cassandra

**Comment by slivne** [comment] 2018-01-02 08:12
can you please provide the git commit that works for you .... for future
reference if we will have questions

**Comment by hagrid-the-developer** [comment] 2018-01-03 07:07
It seems that Cassandra does the conversion: number -> double -> Decimal. I think we should preserve Scylla's behavior here (number -> Decimal), especially when converting varint (or other integer type) to Decimal I would expect to preserve all digits.

**Comment by juliayakovlev** [comment] 2018-01-03 14:57
@slivne 
Shlomi, could you explain, which commit you need to provide?

**Comment by hagrid-the-developer** [comment] 2018-01-14 07:57
I think we can close this issue. NaN and Infinity work correctly, conversion from varint should be probably preserved as is, because C* implementation is a compromise that leads to precision lost.

**Comment by hagrid-the-developer** [comment] 2018-01-17 10:25
I have created C* issue: https://issues.apache.org/jira/browse/CASSANDRA-14170.

**Comment by juliayakovlev** [comment] 2018-01-24 12:27
We still lose decimal numbers in case cast to decimal.
This is example for cast from bigint to decimal:
CREATE TABLE IF NOT EXISTS cast_bigint_test (k int PRIMARY KEY, bigint_clmn bigint);
INSERT INTO cast_bigint_test (k, bigint_clmn) VALUES (0, 7657139128428828644);
INSERT INTO cast_bigint_test (k, bigint_clmn) VALUES (1, 125);
INSERT INTO cast_bigint_test (k, bigint_clmn) VALUES (2, -5698);

SELECT min(cast(bigint_clmn as decimal)) FROM cast_bigint_test;
Cassandra result: -5698.0. Scylla result: -5698

**Comment by hagrid-the-developer** [comment] 2018-03-20 14:20
Fix for C* issue has been submitted, so C* in trunk should return more similar results to Scylla.

**Comment by hagrid-the-developer** [comment] 2018-03-25 11:06
Commit in Cassandra's repository: https://github.com/apache/cassandra/commit/3fa7c0894449b5c6033a6c4f47ec3292d07268b8.

**Comment by slivne** [comment] 2018-07-29 19:13
@juliayakovlev  / @roydahan - since cassandra fixed their impl we can validate in a manual run that they align (or more align_ with the values we return and approve our implementation (and close this issue)

**Comment by tzach** [comment] 2018-08-09 09:53
@hagrid-the-developer what is the difference between this and issues #3109 #3111 and #3112 (all closed)?

**Comment by hagrid-the-developer** [comment] 2018-08-14 07:18
@tzach:
* This issue: Cassandra used to convert decimal/varint through double: decimal -> double -> string. This caused loss of digits that wasn't necessary, was fixed on C. site.

#3109 -- Conversion from float/double to string: S. does print less decimal points then C. (please note: if numbers are read as numbers without conversion to string, then nothing is lost). Conversion timestamp -> string: S does print a bit different format then C.

#3111: Partly about C issue with conversion decimal/float -> double -> string and partly S issue related to missing .0 when converting decimal numbers without decimal places to string. First fixed by C, the other fixed on 21 Jan 2018.

#3112: Partly issue with a conversion of decimal to float/double. Different Java engines use different implementations, like conversion: decimal -> string -> double or some sophisticated numerical calculations. S uses conversion: decimal -> rational_number -> double and it isn't worse (I think it is often better) than other Java implementations. Thanks to the nature of floating points, results for various Java engines and for S implementation slightly differ.

**Comment by nyh** [comment] 2023-04-18 09:44
I'm closing this issue because I think most of the details in it are wrong (claiming that wrong results are to be expected) or outdated, and because I'm working on #13551 and attempting to write more tests to figure out exactly what our casts do wrong, if at all. I'll open new issues if I find bugs in modern Scylla.

**Closed by nyh** 2023-04-18 09:44 UTC

**Comment by roydahan** [comment] 2023-04-19 08:33
@nyh there is a test in dtest for this issue specifically and a "require" decorator.
If you make progress with the other issue, please contribute back to dtest in "test_cast_issue_3110".

**Comment by nyh** [comment] 2023-04-19 08:49
I closed this issue because I think it's invalid, so I don't know what this test_cast_issue_3110 is supposed to be testing. I tried to understand the code but it is very complicated because it is written using many layers of abstraction and mixing correctly working stuff with known bugs (test_cast_issue_3110 is just a tiny wrapper to a bigger-test-that-does-everything-with-a-gazillion-options.
I think this test actually expecting wrong things, such as the decimal type wrongly converting large integers to floating points. As explained in the discussion above, I think this expectation came from Cassandra bugs and not any real reason why it had to be this way.

As far as I can tell @juliayakovlev wrote this test, maybe she could please fix it?

**Comment by juliayakovlev** [comment] 2023-04-19 09:02
> I closed this issue because I think it's invalid, so I don't know what this test_cast_issue_3110 is supposed to be testing. I tried to understand the code but it is very complicated because it is written using many layers of abstraction and mixing correctly working stuff with known bugs (test_cast_issue_3110 is just a tiny wrapper to a bigger-test-that-does-everything-with-a-gazillion-options. I think this test actually expecting wrong things, such as the decimal type wrongly converting large integers to floating points. As explained in the discussion above, I think this expectation came from Cassandra bugs and not any real reason why it had to be this way.
> 
> As far as I can tell @juliayakovlev wrote this test, maybe she could please fix it?

@nyh 
When I joined to Scylla and worked on the "cast" feature, it was explained me that expected vaue is the value that Cassandra returns. This is the rreason why the expected value for this test is as it is.

As I understand, the expected value has been changed. So what is expectation now?

**Comment by fruch** [comment] 2023-04-19 09:08
Sounds like https://github.com/scylladb/scylladb/pull/12509 has change the notation

I've fixed a bunch of tests to be able to check both options in https://github.com/scylladb/scylla-dtest/pull/2982.

I think it was agreed in https://github.com/scylladb/scylladb/pull/12509 that the long notation is the acceptable one

**Comment by juliayakovlev** [comment] 2023-04-19 09:38
> > I closed this issue because I think it's invalid, so I don't know what this test_cast_issue_3110 is supposed to be testing. I tried to understand the code but it is very complicated because it is written using many layers of abstraction and mixing correctly working stuff with known bugs (test_cast_issue_3110 is just a tiny wrapper to a bigger-test-that-does-everything-with-a-gazillion-options. I think this test actually expecting wrong things, such as the decimal type wrongly converting large integers to floating points. As explained in the discussion above, I think this expectation came from Cassandra bugs and not any real reason why it had to be this way.
> > As far as I can tell @juliayakovlev wrote this test, maybe she could please fix it?
> 
> @nyh When I joined to Scylla and worked on the "cast" feature, it was explained me that expected vaue is the value that Cassandra returns. This is the rreason why the expected value for this test is as it is.
> 
> As I understand, the expected value has been changed. So what is expectation now?

@nyh 
I checked the test and found my comments.
First comment:
```
        # TODO: Cassandra problem:
        # TODO: SELECT avg(cast(varint_clmn as decimal)) FROM cast_varint_test;
        # TODO: ServerError: java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
        # TODO: So I do not really know which value should be here
```

Second comment for SUM and AVG from varint to decimal:
```
# -- this Cassandra result seems wrong (CASSANDRA-14170)
```

I need to know what to expect and I can to fix excpected values

**Comment by nyh** [comment] 2023-04-19 09:48
Yes, we reported CASSANDRA-14170 about conversion to "decimal", and it was fixed long ago. You can run modern Cassandra again to see what it does today (in my cql-pytest framework, running tests against Cassandra is easy and natural, for exactly this reason), but we also need to have some common sense - if something in Cassandra looks like a bug (and we even reported it as a bug), we shouldn't insist that Scylla have the same bug (which this issue seems to have suggested). All these cast and sum operations are pretty simple, we can easily figure out what they should do if they aren't buggy.

Anyway, @roydahan may be right that as soon as I closed this issue, the test protected by a "require" for it will start running and will need to pass, so this test should be fixed to pass - and while doing that, if the test still reports a genuine bug we should know what it is and open a new issue for it.

**Comment by nyh** [comment] 2023-04-19 09:59
> Sounds like #12509 has change the notation
> 
> I've fixed a bunch of tests to be able to check both options in [scylladb/scylla-dtest#2982](https://github.com/scylladb/scylla-dtest/pull/2982).
> 
> I think it was agreed in #12509 that the long notation is the acceptable one

Wow, what a mess, but I'm not sure it is relevant here (I think the failures were about long integers, not floating point - seeing them in floating point was the bug in Cassandra). Anyway, somebody (hopefully @juliayakovlev ?) will simply have to run this commented-out-by-"requires" test and see what needs to be done to make it pass - including fixing the expected values or the format or whatever, of course paying attention if something is still wrong, and if it is report it as a new issue (please note that I just fixed a real bug in this area, https://github.com/scylladb/scylladb/pull/13564, so failures of other tests in this file like https://github.com/scylladb/scylladb/issues/13551 are to be expected until my patch is committed).

**Comment by nyh** [comment] 2023-04-19 10:11
> Anyway, @roydahan may be right that as soon as I closed this issue, the test protected by a "require" for it will start running and will need to pass

By the way, when the "requires" feature was added, I warned about this problem - that when the test checks github if an issue was already fixed, it will force the test to pass as soon as the issue is closed - even if (as it turns out) the test has other bugs which were hidden by the previous failures. I preferred the more traditional pytest option, "xfail", a label which needs to be manually removed and doesn't disappear automatically when some issue is closed.
