### ISSUE TITLE
Dtest TestMaterializedViews::test_mv_populating_from_existing_data_during_node_remove failed with raft

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#10163] opened 2022-03-02 20:29 UTC
*Installation details*
Scylla version (or git commit hash): 5.1.dev-0.20220301.cfa391050976 with build-id 027f20572dc0da08a1c2858150e646cae483b647
Cluster size: 3

Dtest: materialized_views_test.py::TestMaterializedViews::test_mv_populating_from_existing_data_during_node_remove  failed to start with enabled raft experimental feature.

repo with enabled raft experimental feature: https://github.com/aleksbykov/scylla-dtest/tree/add-raft-experimental-too-all
Changes could be found: PR: https://github.com/scylladb/scylla-dtest/pull/2639

Node1 log has latest meaningful lines:
```
INFO  2022-03-03 02:51:29,872 [shard 0] format_selector - Selected me sstables format
INFO  2022-03-03 02:51:29,875 [shard 0] features - Feature NONFROZEN_UDTS is enabled
INFO  2022-03-03 02:51:29,876 [shard 0] features - Feature PARALLELIZED_AGGREGATION is enabled
INFO  2022-03-03 02:51:29,876 [shard 0] features - Feature PER_TABLE_CACHING is enabled
INFO  2022-03-03 02:51:29,877 [shard 0] features - Feature PER_TABLE_PARTITIONERS is enabled
INFO  2022-03-03 02:51:29,882 [shard 0] features - Feature RANGE_SCAN_DATA_VARIANT is enabled
INFO  2022-03-03 02:51:29,884 [shard 0] features - Feature SEPARATE_PAGE_SIZE_AND_SAFETY_LIMIT is enabled
INFO  2022-03-03 02:51:29,884 [shard 0] schema_tables - Schema version changed to 59adb24e-f3cd-3e02-97f0-5b395827453f
INFO  2022-03-03 02:51:29,884 [shard 0] features - Feature SUPPORTS_RAFT_CLUSTER_MANAGEMENT is enabled
INFO  2022-03-03 02:51:29,885 [shard 0] features - Feature TOMBSTONE_GC_OPTIONS is enabled
INFO  2022-03-03 02:51:29,885 [shard 0] features - Feature UDA is enabled
INFO  2022-03-03 02:51:29,886 [shard 0] features - Feature VIEW_VIRTUAL_COLUMNS is enabled
ERROR 2022-03-03 02:51:29,889 [shard 0] rpc - client 127.0.38.2:7000: fail to connect: Connection refused
ERROR 2022-03-03 02:51:29,889 [shard 0] rpc - client 127.0.38.3:7000: fail to connect: Connection refused
ERROR 2022-03-03 02:51:29,889 [shard 0] rpc - client 127.0.38.4:7000: fail to connect: Connection refused
INFO  2022-03-03 02:51:29,893 [shard 0] schema_tables - Schema version changed to 59adb24e-f3cd-3e02-97f0-5b395827453f
ERROR 2022-03-03 02:51:30,838 [shard 0] rpc - client 127.0.38.2:7000: fail to connect: Connection refused
ERROR 2022-03-03 02:51:30,839 [shard 0] rpc - client 127.0.38.3:7000: fail to connect: Connection refused
ERROR 2022-03-03 02:51:30,839 [shard 0] rpc - client 127.0.38.4:7000: fail to connect: Connection refused
ERROR 2022-03-03 02:51:30,891 [shard 0] rpc - client 127.0.38.2:7000: fail to connect: Connection refused
```
Other nodes are not started yet. if raft is disabaled, then test is passed.

node1 log:
[system.log](https://github.com/scylladb/scylla/files/8172627/system.log)

execute test from repo above:
```
python -m pytest -s -v --keep-test-dir --scylla-version=unstable/master:latest /home/abykov/Projects/scylla-dtest/materialized_views_test.py::TestMaterializedViews::test_mv_populating_from_existing_data_during_node_remove
```

**Comment by kostja** [comment] 2022-03-22 11:16
@aleksbykov you can no longer perform schema changes if you lost the majority of the cluster. The test needs to be updated. Who should modify the test? Cc @fruch

**Comment by fruch** [comment] 2022-03-23 14:06
> @aleksbykov you can no longer perform schema changes if you lost the majority of the cluster. The test needs to be updated. Who should modify the test? Cc @fruch

I guess it on @aleksbykov (currently working on raft) but @kostja you'll need to a bit more specific of what needed to be changed.

Also how a user would figure this out ? is there any message of warning about the situation ?

**Comment by slivne** [comment] 2022-07-25 14:48
raft is still experimental - pushing this out to 5.2 

The test may have been fixed.

The issue is that in raft tests you need a majority - so tests that had two nodes and one was stopped and started, have been updated to 3 nodes

**Comment by kostja** [comment] 2022-11-18 15:24
Should be addressed by now, please re-test.

**Comment by nyh** [comment] 2024-02-12 15:57
This issue should probably be closed. We've moved to raft (this is the old Raft-based schema operations, not topology operations) long ago and this issue did not recur.

**Closed** 2024-02-12 16:04 UTC
Labels: type/bug, area/raft

**Comment by mykaul** [comment] 2024-09-26 11:54
https://jenkins.scylladb.com/job/scylla-6.2/job/dtest-debug/2/testReport/materialized_views_test/TestMaterializedViews/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split025___test_mv_populating_from_existing_data_during_node_remove_2/ fails, also in release - https://jenkins.scylladb.com/job/scylla-6.2/job/dtest-release/2/testReport/materialized_views_test/TestMaterializedViews/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split006___test_mv_populating_from_existing_data_during_node_decommission/ - could be a different issue.

**Comment by kostja** [comment] 2024-09-26 12:08
It must be a different one
```
               std::runtime_error (Removenode failed. See earlier errors (Rolled back: Failed to drain tablets: std::runtime_error (raft topology: exec_global_command(barrier) failed with seastar::rpc::closed_error (connection is closed))). Request ID: 17d54a82-78dc-11ef-a570-30c80a06a2b9)
```
