### ISSUE TITLE
test.py is not able to launch a cluster due to "RuntimeError: This event loop is already running" with python 3.12

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#16676] opened 2024-01-08 06:42 UTC
in fedora 39, python 3.12 is the default python, and it is more picky than python 3.11 which is shipped with fedora 38.

we use `ScyllaServer.cql_is_up()` for testing if a scylla server is ready for serving CQL requests after starting it when testing, for instance, topology tests, where a cluster is used for testing. and the cluster is typically managed using the `manager` fixture, which is an instance of `ManagerClient`, which is used to communicate with `ScyllaClusterManager`. and `ScyllaClusterManager` manages instances of `ScyllaServer`.

if we adds servers using something like
```py
servers = await manager.servers_add(7, config={'failure_detector_timeout_in_ms': 2000})
```

in the test , and perform the test with python 3.12. the created `ScyllaServer` instance could fail due to
```
Exception in thread asyncio_thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 627, in run_forever
    self._check_running()
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 619, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

the root cause is still unknown. but it's likely due to the the asyncio in python3.12. after preliminary debugging, it happens at
```py
            with Cluster(execution_profiles={EXEC_PROFILE_DEFAULT: profile},
                         contact_points=[self.rpc_address],
                         # This is the latest version Scylla supports
                         protocol_version=4,
                         control_connection_timeout=self.TOPOLOGY_TIMEOUT,
                         auth_provider=auth) as cluster:
                with cluster.connect() as session:
```

when `cluster.connect()` is called. please note, where the python driver is used to connect to the cluster.  the test was performed with python driver [v3.26.4](https://github.com/scylladb/python-driver/releases/tag/3.26.4-scylla). after applying the change of https://github.com/scylladb/python-driver/pull/248, the problem still exists.

the test passes with python 3.11.

**Comment by tchaikov** [comment] 2024-01-31 07:16
for those who wants to run the tests which involve `ScyllaClusterManager`, please try:

```console
$ python3.11 -m venv venv-3.11
$ source venv-3.11/bin/activate
$ pip install -r requirements.txt # see below for the content of requirements.txt 
```

the content of `requirements.txt`. it tries to replicate the python modules used by f38:
```
pytest==7.2.2
pytest-asyncio==0.20.3
aiohttp==3.8.4
pytest-aiohttp
colorama
pyyaml
scylla-driver
aiohttp
unidiff
humanfriendly
treelib
```

**Comment by temichus** [comment] 2024-03-07 13:10
investigations results:
there is only 1 run_forever function in all Scylla organization:
https://github.com/scylladb/python-driver/blob/8138dca6427176a4eccb6b872769b16e31769ad7/cassandra/io/asyncioreactor.py#L127

and the name is the same as in issue "asyncio_thread"

there is a reproducer of issue:
```
from cassandra.io.asyncioreactor import AsyncioConnection
import asyncio
import time

async def test():
    AsyncioConnection.initialize_reactor()

test() #  work without problems in synchronous Python

asyncio.run(test())  # RuntimeError: This event loop is already running
time.sleep(5) # sleep to wai output fail from Thread
```

asked @avelanarius to check my guess that the actual issue in the python-driver

**Comment by xtrey** [comment] 2024-03-08 13:17
@tchaikov could you please provide more information how to reproduce this issue?
 I'm not able to install aiohttp 3.8.4 with python 12, there is an issue with that combination https://github.com/aio-libs/aiohttp/issues/7739 and I can't install it. I'm getting the same error as in aforementioned issue:
```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects
```
Increasing version of aiohttp to 3.9.3 returns completely different error. All test are failing with the next error and they are just simply not starting:
```
self = <aiohttp.helpers.TimerContext object at 0x7f9ddb9162d0>

    def __enter__(self) -> BaseTimerContext:
        task = current_task(loop=self._loop)
    
        if task is None:
>           raise RuntimeError(
                "Timeout context manager should be used " "inside a task"
            )
E           RuntimeError: Timeout context manager should be used inside a task
```

**Comment by tchaikov** [comment] 2024-03-08 13:39
sure. i am using fedora39. and my `python3-aiohttp` is installed using the package shipped along with it.
```console
$ dnf info python3-aiohttp
Last metadata expiration check: 6:37:56 ago on Fri 08 Mar 2024 02:57:39 PM CST.
Installed Packages
Name         : python3-aiohttp
Version      : 3.9.3
Release      : 1.fc39
Architecture : x86_64
Size         : 2.9 M
Source       : python-aiohttp-3.9.3-1.fc39.src.rpm
Repository   : @System
From repo    : updates
Summary      : Python HTTP client/server for asyncio
URL          : https://github.com/aio-libs/aiohttp
License      : Apache-2.0
Description  : Python HTTP client/server for asyncio which supports both the client and the
             : server side of the HTTP protocol, client and server websocket, and webservers
             : with middlewares and pluggable routing.
```

```
RuntimeError: Timeout context manager should be used inside a task
```

i also have the above exception. that's the symptom. but the underlying problem comes from `RuntimeError: This event loop is already running` exception .

**Comment by Lorak-mmk** [comment] 2024-03-12 13:27
The problem is in the class `AsyncioConnection` in `initialize_reactor`:
```python
    @classmethod
    def initialize_reactor(cls):
        with cls._lock:
            if cls._pid != os.getpid():
                cls._loop = None
            if cls._loop is None:
                try:
                    cls._loop = asyncio.get_running_loop()
                except RuntimeError:
                    cls._loop = asyncio.new_event_loop()
                    asyncio.set_event_loop(cls._loop)

            if not cls._loop_thread:
                # daemonize so the loop will be shut down on interpreter
                # shutdown
                cls._loop_thread = Thread(target=cls._loop.run_forever,
                                          daemon=True, name="asyncio_thread")
                cls._loop_thread.start()
```

If we are already in a thread with some event loop, this code is going to create a new thread and execute `run_forever` on it which will cause the error from the issue.
I see 2 potential solutions.

1. Always create new event loop for drivers thread:
```python
    @classmethod
    def initialize_reactor(cls):
        with cls._lock:
            if cls._pid != os.getpid():
                cls._loop = None
            if cls._loop is None:
                cls._loop = asyncio.new_event_loop()

            if not cls._loop_thread:
                # daemonize so the loop will be shut down on interpreter
                # shutdown
                cls._loop_thread = Thread(target=cls._loop.run_forever,
                                          daemon=True, name="asyncio_thread")
                cls._loop_thread.start()
```
note the lack of `set_event_loop` - it shouldn't be called in `initialize_reactor` under any conditions.

2. Reuse existing loop when possible. This is what the current code seems to try to do.  It should probably look about like this (didn't test it):

```python
    @classmethod
    def initialize_reactor(cls):
        with cls._lock:
            if cls._pid != os.getpid():
                cls._loop = None
            if cls._loop is None:
                try:
                    cls._loop = asyncio.get_running_loop()
                except RuntimeError:
                    cls._loop = asyncio.new_event_loop()
                    # daemonize so the loop will be shut down on interpreter
                    # shutdown
                    cls._loop_thread = Thread(target=cls._loop.run_forever,
                                              daemon=True, name="asyncio_thread")
                    cls._loop_thread.start()
```

But then also `push` method needs to be adjusted as it uses self._loop_thread.

**Comment by temichus** [comment] 2024-03-12 16:10
@tchaikov could you please provide the test that you run? 
because error that  @xtrey provided connected with aiohttp not a driver

**Comment by tchaikov** [comment] 2024-03-13 13:23
thanks for looking into this issue. i will retry and provide the test tomorrow.

**Comment by temichus** [comment] 2024-03-13 16:24
@tchaikov Thank you please also check https://github.com/scylladb/scylladb/pull/17760 - this is possible solution for you

**Comment by fruch** [comment] 2024-03-13 22:09
@tchaikov one small question, is this issue observed, when running from within the toolchain image ?

**Comment by tchaikov** [comment] 2024-03-14 00:08
No, as the description of the issue puts, I hit this when testing on fedora39, not in the dbuild container.

**Comment by fruch** [comment] 2024-03-14 04:40
> No, as the description of the issue puts, I hit this when testing on fedora39, not in the dbuild container.

Can you check if

Doing those steps:

https://python-driver.docs.scylladb.com/stable/installation.html#libev-support

And running the code snippet from it, to confirm the libev event loop is used, make this specific problem go away ?

As part of 3.12 support, we replace the default fault back event loop to asyncio, but one we cover the most, and the one we used in dtest and while running inside dbuild, is libev event loop.

We should understand why you are getting to the fallback asyncio one.

Yes, we should fix this one as well, but using libev can unblock what you are doing, and should be close to how it will behave inside dbuild image

**Comment by tchaikov** [comment] 2024-03-14 06:56
@fruch hi Israel, thank you for the pointers. it does help. after following the instructions and reinstalling the python-driver from the source, the issue that i previously ran into goes away.

**Comment by tchaikov** [comment] 2024-03-14 07:00
> @tchaikov could you please provide the test that you run? because error that @xtrey provided connected with aiohttp not a driver

sure. i am testing using following command line:
```
./test.py --verbose  --mode release topology_experimental_raft/test_tablets
`` 
on f39, with scylla-driver (f3567166a2c151a1d8a44e1281b17bd612b2032d), without libev extension installed (i didn't install libev-devel).

**Comment by tchaikov** [comment] 2024-03-14 07:10
> @tchaikov Thank you please also check #17760 - this is the possible solution for you. it fixes aiohttp problem

@temichus i cherry-picked the commit in #17760 onto master HEAD, and reran the test. once the cluster manager client connected to the server, the server side printed following backtrace
```
Exception in thread asyncio_thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 628, in run_forever
    self._check_running()
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 620, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

**Comment by tchaikov** [comment] 2024-03-14 07:14
> > No, as the description of the issue puts, I hit this when testing on fedora39, not in the dbuild container.
> 
> Can you check if
> 
> Doing those steps:
> 
> https://python-driver.docs.scylladb.com/stable/installation.html#libev-support
> 
> And running the code snippet from it, to confirm the libev event loop is used, make this specific problem go away ?
> 
> As part of 3.12 support, we replace the default fault back event loop to asyncio, but one we cover the most, and the one we used in dtest and while running inside dbuild, is libev event loop.
> 
> We should understand why you are getting to the fallback asyncio one.
> 
> Yes, we should fix this one as well, but using libev can unblock what you are doing, and should be close to how it will behave inside dbuild image

@fruch does it make sense to let python-driver bail out if the libev reactor is missing when running on python 3.12 (and up) with an error message referencing a github issue?

**Comment by fruch** [comment] 2024-03-14 07:54
> > > No, as the description of the issue puts, I hit this when testing on fedora39, not in the dbuild container.
> > 
> > 
> > Can you check if
> > Doing those steps:
> > https://python-driver.docs.scylladb.com/stable/installation.html#libev-support
> > And running the code snippet from it, to confirm the libev event loop is used, make this specific problem go away ?
> > As part of 3.12 support, we replace the default fault back event loop to asyncio, but one we cover the most, and the one we used in dtest and while running inside dbuild, is libev event loop.
> > We should understand why you are getting to the fallback asyncio one.
> > Yes, we should fix this one as well, but using libev can unblock what you are doing, and should be close to how it will behave inside dbuild image
> 
> @fruch does it make sense to let python-driver bail out if the libev reactor is missing when running on python 3.12 (and up) with an error message referencing a github issue?

it's a call we took, not to fail and default to asyncio, but we can revisit this decision

**Comment by tchaikov** [comment] 2024-03-14 08:01
okay, i think the decision was made based on the assumption that asyncio worked.

**Comment by fruch** [comment] 2024-03-14 08:11
> okay, i think the decision was made based on the assumption that asyncio worked.

we proven it to work, and it pass the driver integration tests, but only when it was used by sync. code 
that event loop on the driver is still marked as experimental, our assumption was they it would be easy on whom uses python3.12, and we didn't fix more then one issue in, only to get to that point.

but we need to sync back with upstream about that, and align regarding testing of the event loop (they might be doing that already, or it might be a joint effort),

anyhow it would be a bit confusion or annoying to who uses it, one way or the other.

**Comment by tchaikov** [comment] 2024-03-14 08:15
i see. so it was a regression. but since we don't exercise it in our CI. that piece of code was broke somehow.

> anyhow it would be a bit confusion or annoying to who uses it, one way or the other.

indeed. just wanted to ensure that none of us or our users will run into the same problem before it gets fixed.

**Comment by temichus** [comment] 2024-03-14 09:30
@tchaikov, your error is a Driver issue https://github.com/scylladb/python-driver/issues/312. but after that, you will be rich aiohttp problem that is fixed here  https://github.com/scylladb/scylladb/pull/17760.
I ran tests within the toolchain but with installed new Python3.12 inside:
```
bash-5.2$ python3.12 ./test.py --mode release topology_experimental_raft/test_tablets
Found 2 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[2/2]      topology_experimental_raft release [ PASS ] topology_experimental_raft.test_tablets.1                        
------------------------------------------------------------------------------
CPU utilization: 5.2%
bash-5.2$ 

```

So, What resolution of this issue? 
I think we can close it and leave https://github.com/scylladb/python-driver/issues/312 only.
And proceed with https://github.com/scylladb/scylladb/pull/17760 is it is next issue that you will faced with

**Comment by temichus** [comment] 2024-03-18 08:58
UPD https://github.com/scylladb/scylladb/pull/17760 merged

**Comment by temichus** [comment] 2024-03-18 09:02
> @tchaikov, your error is a Driver issue [scylladb/python-driver#312](https://github.com/scylladb/python-driver/issues/312). but after that, you will be rich aiohttp problem that is fixed here #17760. I ran tests within the toolchain but with installed new Python3.12 inside:
> 
> ```
> bash-5.2$ python3.12 ./test.py --mode release topology_experimental_raft/test_tablets
> Found 2 tests.
> ================================================================================
> [N/TOTAL]   SUITE    MODE   RESULT   TEST
> ------------------------------------------------------------------------------
> [2/2]      topology_experimental_raft release [ PASS ] topology_experimental_raft.test_tablets.1                        
> ------------------------------------------------------------------------------
> CPU utilization: 5.2%
> 
> bash-5.2$ python3.12 -V
> Python 3.12.2
> ```
> 
> @tchaikov @fruch @Lorak-mmk What resolution of this issue? I think we can close it and leave [scylladb/python-driver#312](https://github.com/scylladb/python-driver/issues/312) only. And proceed with #17760 as it is the next issue that you will face with

@tchaikov @fruch @Lorak-mmk
https://github.com/scylladb/scylladb/pull/17760 is merged now
should we close this issue and leave open only on the Python driver, or both should be left open?

**Comment by tchaikov** [comment] 2024-03-18 10:56
@temichus hi Artsiom, sorry for the latency. [the one opened for client side issue](https://github.com/scylladb/python-driver/issues/312) is good enough now.

i am closing this issue.

**Comment by avikivity** [comment] 2024-05-26 13:54
Seeing it again on aarch64, de798775fd30bd07b0cc31d0465364d3e2816e9b.

**Comment by avikivity** [comment] 2024-05-26 13:56
frozen toolchain that exhibits the problem: docker.io/avikivity/scylla-toolchain:f40-test

**Comment by avikivity** [comment] 2024-05-26 13:56
@kostja please prioritize

**Comment by kostja** [comment] 2024-05-27 11:42
Could you also write down your steps to reproduce, are they the same as in the original report?

**Comment by avikivity** [comment] 2024-05-29 13:21
On an arm machine

1. dbuild --image that_image -it --
2. ./configure.py
3. ninja dev-build
4. ./test.py --mode dev

**Comment by avikivity** [comment] 2024-05-31 11:55
@kostja please update

**Comment by temichus** [comment] 2024-06-03 12:36
@avikivity as I mentioned above:



> investigations results: there is only 1 run_forever function in all Scylla organization: https://github.com/scylladb/python-driver/blob/8138dca6427176a4eccb6b872769b16e31769ad7/cassandra/io/asyncioreactor.py#L127
> 
> and the name is the same as in issue "asyncio_thread"
> 
> there is a reproducer of issue:
> 
> ```
> from cassandra.io.asyncioreactor import AsyncioConnection
> import asyncio
> import time
> 
> def test():
>     AsyncioConnection.initialize_reactor()
> 
> test() # work without problems in synchronous Python
> 
> 
> async def await_test():
>     AsyncioConnection.initialize_reactor()
> 
> 
> asyncio.run(await_test())  # RuntimeError: This event loop is already running
> time.sleep(5) # sleep to wai output fail from Thread
> ```
> 
> full error output
> 
> ```
> Exception in thread asyncio_thread:
> Traceback (most recent call last):
>   File "/home/artsiom/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
>     self.run()
>   File "/home/artsiom/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 982, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/artsiom/.pyenv/versions/3.11.7/lib/python3.11/asyncio/base_events.py", line 596, in run_forever
>     self._check_running()
>   File "/home/artsiom/.pyenv/versions/3.11.7/lib/python3.11/asyncio/base_events.py", line 588, in _check_running
>     raise RuntimeError('This event loop is already running')
> RuntimeError: This event loop is already running
> ```
> 
> asked @avelanarius to check my guess that the actual issue in the python-driver


resolution of this issue was close it and leave Driver issue https://github.com/scylladb/python-driver/issues/312 opened

I've recheck my investigations. and still here is only 1 run_forever function call in all Scylla organization: https://github.com/scylladb/python-driver/blob/8138dca6427176a4eccb6b872769b16e31769ad7/cassandra/io/asyncioreactor.py#L127

cc @kostja , @Lorak-mmk

**Comment by avikivity** [comment] 2024-06-03 13:57
Well, we need to fix it. I don't care about where the issue is opened. I care that it gets fixed ASAP.

**Comment by fruch** [comment] 2024-06-03 15:10
If we don't have this, one would need to check why libev isn't the default

```python
>>> from cassandra.cluster import DefaultConnection
>>> print(DefaultConnection)
<class 'cassandra.io.libevreactor.LibevConnection'>
>>>
```

probably it's an issue with installation of the driver on arm image.

**Comment by fruch** [comment] 2024-06-03 15:47
I've tried the docker image avi supplied

and then I've found out that for https://pypi.org/project/scylla-driver/3.26.8/

we don't have wheels for ARM, it probably was broken at the time of the release.
and the ARM builds goes to a separate experimental pipeline.

@Lorak-mmk FYI,

1) we should make the arm build first class citizen, and fail the release if it fails.
2) we can temporary install libev like `dnf install libev libev-devel` on dbuild image, as a temporary measure until figuring out the release, or issuing a new release with fixes for ARM building

**Comment by fruch** [comment] 2024-06-03 15:50
the failed action
https://github.com/scylladb/python-driver/actions/runs/8328863220

not that it helps anyone, after 3 months we don't have logs for it...

**Comment by fruch** [comment] 2024-06-03 16:08
trying to address the build issue in:

https://github.com/scylladb/python-driver/pull/326

**Comment by Lorak-mmk** [comment] 2024-06-04 17:17
Fixing the ARM build is important, and a one way to fix the issue - because it will stop usage of AsyncIoConnection.
I think AsyncIoConnection should be fixed too to accomodate scenario from this issue. I opened a PR with a fix: https://github.com/scylladb/python-driver/pull/327

**Comment by avikivity** [comment] 2024-06-05 09:42
Let me see if I understand what happened:
1. due to aarch64 binaries (wheels?) of the python driver not present on the pypi server, pip rebuilt it itself
2. due to libev-devel not being installed on the toolchain image, the driver used a different path than usual, AsyncIoConnection
3. The AsyncIoConnection path interferes with the asyncio event loop (by launching a separate event loop on the same thread)

**Comment by fruch** [comment] 2024-06-05 10:22
> Let me see if I understand what happened:
> 1. due to aarch64 binaries (wheels?) of the python driver not present on the pypi server, pip rebuilt it itself
> 2. due to libev-devel not being installed on the toolchain image, the driver used a different path than usual, AsyncIoConnection
> 3. The AsyncIoConnection path interferes with the asyncio event loop (by launching a separate event loop on the same thread)

Yes, that sums it up quite right

**Comment by tchaikov** [comment] 2024-06-05 10:32
yeah, this is exactly the problem i ran into. but i was on amd64.

**Comment by Lorak-mmk** [comment] 2024-06-05 11:06
> Let me see if I understand what happened:
> 
>     1. due to aarch64 binaries (wheels?) of the python driver not present on the pypi server, pip rebuilt it itself
> 
>     2. due to libev-devel not being installed on the toolchain image, the driver used a different path than usual, AsyncIoConnection
> 
>     3. The AsyncIoConnection path interferes with the asyncio event loop (by launching a separate event loop on the same thread)

That's right, but it's worth noting that AsyncIoConnection interferes with asyncio event loop not because of some design issue / inherent flaw, but a simple bug.

**Comment by Lorak-mmk** [comment] 2024-06-05 11:14
Regarding 3: it doesn't launch the loop on the same thread. It takes the existing running loop, and tries to run it again on a new thread.

**Comment by fruch** [comment] 2024-06-09 14:48
> Ok. What's needed to get this fixed?

1) Arm wheels are now in place in pypi
So rebuilding a dbuild should now work.
   Next release wouldn't upload to pypi is arm binaries would be missing

2) @Lorak-mmk is workingbon a fix to the asyncio event loop

3) we are syncing with upstream, and would stop falling back to asyncio event loop as it still experimantal, mean that if libev eventloop is missing in python 3.12, there would be an error message sending to you to pick the exact eventloop to your needs (i.e. indicating libev isn't available)

**Comment by tchaikov** [comment] 2024-06-09 14:52
so, IIUC,

1. once the asyncio event loop fix lands, 
2. we just need create a new tag ending with "scylla", 
3. the workflow will take care of the rest of publish, 
4. then we just need to redo the image after PyPI is updated.

but we don't need to wait for the upstream for step 1, right?

**Comment by fruch** [comment] 2024-06-09 15:04
> so, IIUC,
> 
> 1. once the asyncio event loop fix lands,
> 2. we just need create a new tag ending with "scylla",
> 3. the workflow will take care of the rest of publish,
> 4. then we just need to redo the image after PyPI is updated.
> 
> but we don't need to wait for the upstream for step 1, right?

no, if libev eventloop is available, code doesn't get into using asyncio eventloop.
i.e. same as is now on the x86 dbuild image.

so now that there are arm wheel in place, rebuilding an arm dbuild should work.
(once can try it local with the docker avi supplied above to see it in action)

**Comment by kostja** [comment] 2024-06-09 15:21
@avikivity here's the fix https://github.com/scylladb/python-driver/pull/327/files but it is being treated by @fruch coldly.

**Comment by fruch** [comment] 2024-06-09 15:35
> @avikivity here's the fix https://github.com/scylladb/python-driver/pull/327/files but it is being treated by @fruch coldly.

it got lot of love and support, but it's a fix for an experimental part of the driver. and that going to be like that until it would be tested rigorously.

meanwhile a fix for missing ARM artifacts was supplied.

**Comment by avikivity** [comment] 2024-06-09 15:46
> > Ok. What's needed to get this fixed?
> 
> 1. Arm wheels are now in place in pypi
>    So rebuilding a dbuild should now work.


I confirm that it works.

**Comment by avikivity** [comment] 2024-06-09 15:47
Closing as fixed (though the driver AsyncIOConnection stuff should still get fixed)

**Closed by avikivity** 2024-06-09 15:47 UTC
Labels: area/build, area/drivers
