### ISSUE TITLE
test_simple_kill_node_while_decommissioning fails after restarting decommissioned node: cassandra.Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl ONE. Requires 1, alive 0"

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#15146] opened 2023-08-24 06:22 UTC
```
12:52:34  _____ TestUpdateClusterLayout.test_simple_kill_node_while_decommissioning ______
...
12:52:34      def test_simple_kill_node_while_decommissioning(self):
12:52:34          """
12:52:34          Test a decommissioning node killed is able to rejoin the cluster with data
12:52:34          1. Create a cluster with a three nodes with rf=1, insert data
12:52:34          2. Decommission a node
12:52:34          3. While node is decommissioning kill it
12:52:34          4. Boot the node back up
12:52:34          5. Check that the node rejoins the cluster and works correctly
12:52:34          """
12:52:34          cluster = self.cluster
...
12:52:34          # starting node2 - it should reconnect and run as is
12:52:34          logger.debug("Start node2 ")
12:52:34          node2.start(wait_other_notice=False, wait_for_binary_proto=True)
12:52:34          session2 = self.patient_cql_connection(node2)
12:52:34  >       result = list(session2.execute("SELECT * FROM ks.cf"))
...
12:52:34  update_cluster_layout_tests.py:1036: 
12:52:34  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
12:52:34  cassandra/cluster.py:5267: in cassandra.cluster.ResultSet.next
12:52:34      ???
12:52:34  cassandra/cluster.py:5288: in cassandra.cluster.ResultSet.fetch_next_page
12:52:34      ???
12:52:34  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
12:52:34  
12:52:34  >   ???
12:52:34  E   cassandra.Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl ONE. Requires 1, alive 0" info={'consistency': 'ONE', 'required_replicas': 1, 'alive_replicas': 0}
12:52:34  
```

see https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/3971

**Comment by tchaikov** [comment] 2023-08-25 05:34
and https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4006

**Comment by benipeled** [comment] 2023-08-27 09:07
And now on next (a few times) https://jenkins.scylladb.com/job/scylla-master/job/next/6441/

**Comment by benipeled** [comment] 2023-08-27 10:58
Fixed by @bhalevy on https://github.com/scylladb/scylla-dtest/pull/3524

**Comment by avikivity** [comment] 2023-10-11 19:01
Seen again, same place: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6653/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_simple_kill_node_while_decommissioning/

**Comment by bhalevy** [comment] 2023-10-12 05:19
> Seen again, same place: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6653/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_simple_kill_node_while_decommissioning/

But not same error.
This issues's title is too broad @tchaikov.
Let's make sure to be more specific about the failure kind since many times different problems cause different symptoms and so they require different solutions, so there's no point in having a broad issue like this one.

Previously, the error the test reported was:
```
12:52:34  E   cassandra.Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl ONE. Requires 1, alive 0" info={'consistency': 'ONE', 'required_replicas': 1, 'alive_replicas': 0}
```

And now:
```
E   cassandra.OperationTimedOut: errors={'127.0.96.1:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.96.1:9042
```

@tchaikov please look into this.

**Comment by tchaikov** [comment] 2023-10-12 06:24
> This issues's title is too broad @tchaikov. Let's make sure to be more specific about the failure kind since many times different problems cause different symptoms and so they require different solutions, so there's no point in having a broad issue like this one.
> 

i think, the title is supposed to be searchable and short, the developer interested in it should read the description. could you please propose a better one? so i can follow your example in future?

**Comment by bhalevy** [comment] 2023-10-12 07:01
> > This issues's title is too broad @tchaikov. Let's make sure to be more specific about the failure kind since many times different problems cause different symptoms and so they require different solutions, so there's no point in having a broad issue like this one.
> 
> i think, the title is supposed to be searchable and short, the developer interested in it should read the description. could you please propose a better one? so i can follow your example in future?

In this case, it could be something like: `test_simple_kill_node_while_decommissioning fails after restarting decommissioned node: cassandra.Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl ONE. Requires 1, alive 0"`

I know it's much longer but it is much more informative.

**Comment by tchaikov** [comment] 2023-10-12 07:07
thank you for the suggestion, hope we don't have to have embed the error message in the title. please note the error message is sitting right at the last line of the description.

also, it's a really bad indication that we have way too many failures so that we have the needs to differentiate one from the another. imaging that there is a huge family with 50 kids: all of boys are named Mark and all the girls are named Maya...

**Comment by bhalevy** [comment] 2023-10-12 07:36
> thank you for the suggestion, hope we don't have to embed the error message in the title. please note the error message is sitting right at the last line of the description.
> 
> also, it's a really bad indication that we have way too many failures so that we have the needs to differentiate one from the another. imaging that there is a huge family with 50 kids: all of boys are named Mark and all the girls are named Maya...

If all kids are due to errors, then the situation is indeed dire ;-)

**Comment by mykaul** [comment] 2023-10-26 13:10
@tchaikov - what's the next step here?

**Comment by denesb** [comment] 2023-11-08 13:50
Also seen at: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4504/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_simple_kill_node_while_decommissioning/

**Comment by bhalevy** [comment] 2023-11-08 16:12
Looking at the node logs it looks like we're starting to query node2 a tidbit too early, before others recognize it as a normal token owner.

https://github.com/scylladb/scylla-ccm/pull/523 fixes that at it makes the dtest pass reliably for me locally.
While without the ccm change it fails about 1 out of 2-3 runs.

**Comment by Annamikhlin** [comment] 2023-11-15 11:51
also failed on `master/next` - 
https://jenkins.scylladb.com/job/scylla-master/job/next/6822/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Build___x86___Sanity_raft___Sanity_Tests_x86___RAFT___test_simple_kill_node_while_decommissioning/

**Comment by bhalevy** [comment] 2023-11-29 12:31
> @bhalevy - this is still targeted for 5.4. Should it be?

I think we can postpone it since the failure is rare enough.

**Comment by benipeled** [comment] 2024-01-01 10:24
And now on 2024.1 https://jenkins.scylladb.com/job/enterprise-2024.1/job/next/61/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_simple_kill_node_while_decommissioning/

**Comment by bhalevy** [comment] 2024-01-01 13:05
@asked to backport https://github.com/scylladb/scylla-ccm/pull/523#issuecomment-1873320343

**Comment by mykaul** [comment] 2024-04-24 09:04
Assuming all is fixed - closing - please re-open / open a new issue if it reproduces.

**Closed by mykaul** 2024-04-24 09:04 UTC
Labels: P1, symptom/ci stability
