### ISSUE TITLE
Expose cfstats data from metrics

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#2198] opened 2017-03-22 19:06 UTC
*Installation details*
Scylla version (or git commit hash): 1.7

Its useful to expose key cfstats parameters in metrics, to be consumed by Prometheus/Grafana or other monitoring services. The following subset of cfstats data seems more useful:

- Read Count
- Read Latency
- Write Count
- Write Latency
- SSTable count
- SSTables in each level
- Compacted partition minimum bytes
- Compacted partition maximum bytes
- Compacted partition mean bytes
- Average tombstones per slice (last five minutes)
- Maximum tombstones per slice (last five minutes)

For the full list of reported metrics:
http://docs.scylladb.com/nodetool-commands/cfstats/

**Comment by benoit-canet** [comment] 2017-06-26 14:26
Do you want exactly the same stuff as what is exported in nodetool ?
Some of these are not existing in nodetool. Can I skip them ?

**Comment by benoit-canet** [comment] 2017-07-24 13:14
@tzach: ping

**Comment by tzach** [comment] 2017-07-24 17:57
@benoit-canet which are not presented on nodetool? it might be a bug

**Comment by benoit-canet** [comment] 2017-07-25 11:30
Here is an extract of nodetool cfstat:

         Table: size_estimates
                SSTable count: 0
                Space used (live): 0
                Space used (total): 0
                Space used by snapshots (total): 0
                Off heap memory used (total): 0
                SSTable Compression Ratio: 0.0
                Number of keys (estimate): 0
                Memtable cell count: 0
                Memtable data size: 0
                Memtable off heap memory used: 0
                Memtable switch count: 0
                Local read count: 0
                Local read latency: NaN ms
                Local write count: 0
                Local write latency: NaN ms
                Pending flushes: 0
                Bloom filter false positives: 0
                Bloom filter false ratio: 0,00000
                Bloom filter space used: 0
                Bloom filter off heap memory used: 0
                Index summary off heap memory used: 0
                Compression metadata off heap memory used: 0
                Compacted partition minimum bytes: 0
                Compacted partition maximum bytes: 0
                Compacted partition mean bytes: 0
                Average live cells per slice (last five minutes): 0.0
                Maximum live cells per slice (last five minutes): 0
                Average tombstones per slice (last five minutes): 0.0
                Maximum tombstones per slice (last five minutes): 0

As you can see some are marked as Nan. (not cheese one ;)

**Comment by tzach** [comment] 2017-07-25 17:41
The read and write latency should be now available https://github.com/scylladb/scylla/issues/1630
@amnonh did you wire them to `nodetool cfstat ?`

**Comment by amnonh** [comment] 2022-11-22 15:29
Just to explain, the read/write latencies per table are already part of the metric layer, it's just off by default because it crashses Prometheus servers

**Comment by amnonh** [comment] 2022-11-23 07:57
@tzach 
I've just checked nodetool with scylla 5.1 (dockerized) while runing `cassandra-stress`
```
# nodetool tablestats keyspace1
Total number of tables: 60
----------------
Keyspace : keyspace1
	Read Count: 312085
	Read Latency: 7.501161542528478E-6 ms
	Write Count: 8139967
	Write Latency: 2.3376016143554387E-6 ms
	Pending Flushes: 0
		Table: standard1
		SSTable count: 0
		Space used (live): 0
		Space used (total): 0
		Space used by snapshots (total): 0
		Off heap memory used (total): 2614755328
		SSTable Compression Ratio: 0.0
		Number of partitions (estimate): 0
		Memtable cell count: 1000000
		Memtable data size: 940335748
		Memtable off heap memory used: 2614755328
		Memtable switch count: 0
		Local read count: 312085
		Local read latency: 0.008 ms
		Local write count: 8139967
		Local write latency: 0.002 ms
		Pending flushes: 0
		Percent repaired: 0.0
		Bloom filter false positives: 0
		Bloom filter false ratio: 0.00000
		Bloom filter space used: 0
		Bloom filter off heap memory used: 0
		Index summary off heap memory used: 0
		Compression metadata off heap memory used: 0
		Compacted partition minimum bytes: 0
		Compacted partition maximum bytes: 0
		Compacted partition mean bytes: 0
		Average live cells per slice (last five minutes): 0.0
		Maximum live cells per slice (last five minutes): 0
		Average tombstones per slice (last five minutes): 0.0
		Maximum tombstones per slice (last five minutes): 0
		Dropped Mutations: 0
```
I don't see any missing values.

Did you use an old nodetool/scylla version?
Maybe you tested it without traffic?

What do you want to do with this issue?

**Comment by mykaul** [comment] 2023-01-03 08:28
@tzach - ping

**Comment by tzach** [comment] 2023-01-03 10:15
@amnonh I do not understand what you tested
The original issue is about validating that all the info from `nodetool cfstats` is available via metrics.
Is it the case?

**Comment by amnonh** [comment] 2023-03-07 08:38
The issue is not clear, it talks about Prometheus metrics and then there is an example for persumambly missing data in nodetool, so what's it about?

**Comment by mykaul** [comment] 2023-03-07 08:54
> The issue is not clear, it talks about Prometheus metrics and then there is an example for persumambly missing data in nodetool, so what's it about?

I think the ask (and I'm not sure it makes sense - from performance perspective) is that 'nodetool cfstats' metrics will be available via Prometheus metrics.

**Comment by amnonh** [comment] 2023-03-07 09:13
We have some of those metrics, but with the overload to the system, per-table metrics are turned off

**Closed** 2023-08-04 16:13 UTC
Labels: enhancement, User Request, monitoring-tracing
