### ISSUE TITLE
Scylla failed to start after rollback due to feature MAINTENANCE_TENANT enabled

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#21519] opened 2024-11-11 04:42 UTC
## Packages

Base Scylla version: `6.1.3-20241027.91c693bf9332` with build-id `acd9011394e1b4161249007e2ad5cd986bbf0aa1`
Target Scylla version (or git commit hash): `6.2.1-20241106.a3a0ffbcd015` with build-id `94e4419682b4191f7c37e2d6bf02f4fa7988dff3`

Kernel Version: `5.14.0-514.el9.x86_64`

## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

after rollback from 6.2.1 to 6.1.3, Scylla with version 6.1.3 failed to start with error:
```
2024-11-07T00:07:40.616+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4      !ERR | scylla[122546]:  [shard  0:main] init - Startup failed: gms::unsupported_feature_exception (Unknown feature 'MAINTENANCE_TENANT' was previously enabled in the cluster.  That means this node is performing a prohibited downgrade procedure and should not be allowed to boot.)

```

the  MAINTENANCE_TENANT was enabled by default after upgrade to 6.2.1.
```
2024-11-06T23:55:23.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] init - Scylla version 6.2.1-0.20241106.a3a0ffbcd015 with build-id 94e4419682b4191f7c37e2d6bf02f4fa7988dff3 starting ...
...
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature MAINTENANCE_TENANT is enabled
```

## Impact

upgrade faileder

## How frequently does it reproduce?

no always

## Installation details

Cluster size: 4 nodes (n2-highmem-16)

Scylla Nodes used in this run:
- rolling-upgrade--centos-9-db-node-ac975443-0-4 (35.237.185.191 | 10.142.15.219) (shards: 14)
- rolling-upgrade--centos-9-db-node-ac975443-0-3 (35.190.174.180 | 10.142.15.217) (shards: 14)
- rolling-upgrade--centos-9-db-node-ac975443-0-2 (35.237.166.206 | 10.142.15.213) (shards: 14)
- rolling-upgrade--centos-9-db-node-ac975443-0-1 (34.23.0.233 | 10.142.15.211) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-9` (gce: undefined_region)

Test: `rolling-upgrade-centos9-test`
Test id: `ac975443-4bc0-4402-8419-85e1d19da9f9`
Test name: `scylla-6.2/rolling-upgrade/rolling-upgrade-centos9-test`
Test method: `upgrade_test.UpgradeTest.test_rolling_upgrade`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5e7d4ab1fbfb9ebcbaced1e7bad43721c6446db4/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor ac975443-4bc0-4402-8419-85e1d19da9f9`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ac975443-4bc0-4402-8419-85e1d19da9f9)
- Show all stored logs command: `$ hydra investigate show-logs ac975443-4bc0-4402-8419-85e1d19da9f9`

## Logs:
- **db-cluster-ac975443.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ac975443-4bc0-4402-8419-85e1d19da9f9/20241107_000922/db-cluster-ac975443.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ac975443-4bc0-4402-8419-85e1d19da9f9/20241107_000922/db-cluster-ac975443.tar.gz)
- **sct-runner-events-ac975443.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ac975443-4bc0-4402-8419-85e1d19da9f9/20241107_000922/sct-runner-events-ac975443.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ac975443-4bc0-4402-8419-85e1d19da9f9/20241107_000922/sct-runner-events-ac975443.tar.gz)
- **sct-ac975443.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ac975443-4bc0-4402-8419-85e1d19da9f9/20241107_000922/sct-ac975443.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ac975443-4bc0-4402-8419-85e1d19da9f9/20241107_000922/sct-ac975443.log.tar.gz)
- **loader-set-ac975443.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ac975443-4bc0-4402-8419-85e1d19da9f9/20241107_000922/loader-set-ac975443.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ac975443-4bc0-4402-8419-85e1d19da9f9/20241107_000922/loader-set-ac975443.tar.gz)
- **monitor-set-ac975443.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ac975443-4bc0-4402-8419-85e1d19da9f9/20241107_000922/monitor-set-ac975443.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ac975443-4bc0-4402-8419-85e1d19da9f9/20241107_000922/monitor-set-ac975443.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-6.2/job/rolling-upgrade/job/rolling-upgrade-centos9-test/6/)
[Argus](https://argus.scylladb.com/test/e2740600-9e06-4ebc-a78a-eb1adfe0242a/runs?additionalRuns[]=ac975443-4bc0-4402-8419-85e1d19da9f9)
</details>

**Comment by mykaul** [comment] 2024-11-11 05:55
@kbr-scylla - this sounds familiar, no?

**Comment by kbr-scylla** [comment] 2024-11-12 09:53
@aleksbykov so you performed a full upgrade (all nodes) and then rollback? Then it's expected that it fails, and cluster features (such as `MAINTENANCE_TENANT`) are used to prevent exactly t hat.

If the cluster feature got enabled before all nodes got upgraded, then that's a bug.

So what happened here?

**Comment by aleksbykov** [comment] 2024-11-12 10:02
@kbr-scylla ,
1 node was upgraded, second node was upgraded and then rollbacked.

**Comment by aleksbykov** [comment] 2024-11-12 10:03
Not all nodes was upgraded. It happened in mixed cluster

**Comment by kostja** [comment] 2024-11-13 12:19
@Jadw1 apparently maintenance tenant get somehow unconditionally enabled even if the upgrade is not finished. Could it be the case?

**Comment by roydahan** [comment] 2024-11-13 12:39
I think the affected node (rolling-upgrade--centos-9-db-node-ac975443-0-4) was somehow downgraded to the wrong version, it started as 6.1.3, upgraded to 6.2.1 but in the end I see on it:
Scylla version 6.1.2-0.20240915.b60f9ef4c223

**Comment by roydahan** [comment] 2024-11-13 12:44
@dimakr can you please also look at this one?
It doesn't look like the "double downgrade" issue to me, but worth looking at it.

**Comment by roydahan** [comment] 2024-11-13 12:46
```
 egrep -i 'scylla version| features - Feature' rolling-upgrade--centos-9-db-node-ac975443-0-4/messages.log
2024-11-06T22:10:36.241+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]: **Scylla version 6.1.3-0.20241027.91c693bf9332** with build-id acd9011394e1b4161249007e2ad5cd986bbf0aa1 starting ...
2024-11-06T22:10:36.524+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0:main] init - Scylla version 6.1.3-0.20241027.91c693bf9332 with build-id acd9011394e1b4161249007e2ad5cd986bbf0aa1 starting ...
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature HOST_ID_BASED_HINTED_HANDOFF is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature SUPPORTS_CONSISTENT_TOPOLOGY_CHANGES is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature TABLETS is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature SECONDARY_INDEXES_ON_STATIC_COLUMNS is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature RANGE_TOMBSTONE_AND_DEAD_ROWS_DETECTION is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature UDA_NATIVE_PARALLELIZED_AGGREGATION is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature TYPED_ERRORS_IN_READ_RPC is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature TABLE_DIGEST_INSENSITIVE_TO_EXPIRY is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature UUID_SSTABLE_IDENTIFIERS is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature LARGE_COLLECTION_DETECTION is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature CDC_GENERATIONS_V2 is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature SEPARATE_PAGE_SIZE_AND_SAFETY_LIMIT is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature SUPPORTS_RAFT_CLUSTER_MANAGEMENT is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature MAINTENANCE_TENANT is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature RANGE_SCAN_DATA_VARIANT is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature COLLECTION_INDEXING is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature AGGREGATE_STORAGE_OPTIONS is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature UDA is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature GROUP0_SCHEMA_VERSIONING is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature ALTERNATOR_TTL is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature PARALLELIZED_AGGREGATION is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature EMPTY_REPLICA_PAGES is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature EMPTY_REPLICA_MUTATION_PAGES is enabled
2024-11-06T22:10:39.639+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0: gms] features - Feature TOMBSTONE_GC_OPTIONS is enabled
2024-11-06T22:10:41.589+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0:main] init - Scylla version 6.1.3-0.20241027.91c693bf9332 initialization completed.
2024-11-06T23:52:55.874+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[79601]:  [shard  0:main] init - Scylla version 6.1.3-0.20241027.91c693bf9332 shutdown complete.
2024-11-06T23:55:22.891+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]: Scylla version **6.2.1-0.20241106.a3a0ffbcd015** with build-id 94e4419682b4191f7c37e2d6bf02f4fa7988dff3 starting ...
2024-11-06T23:55:23.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] init - Scylla version 6.2.1-0.20241106.a3a0ffbcd015 with build-id 94e4419682b4191f7c37e2d6bf02f4fa7988dff3 starting ...
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature TOMBSTONE_GC_OPTIONS is enabled
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature EMPTY_REPLICA_MUTATION_PAGES is enabled
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature EMPTY_REPLICA_PAGES is enabled
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature ALTERNATOR_TTL is enabled
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature UDA is enabled
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature GROUP0_SCHEMA_VERSIONING is enabled
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature COLLECTION_INDEXING is enabled
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature RANGE_SCAN_DATA_VARIANT is enabled
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature SUPPORTS_RAFT_CLUSTER_MANAGEMENT is enabled
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature SEPARATE_PAGE_SIZE_AND_SAFETY_LIMIT is enabled
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature PARALLELIZED_AGGREGATION is enabled
2024-11-06T23:55:24.388+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature CDC_GENERATIONS_V2 is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature UUID_SSTABLE_IDENTIFIERS is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature TABLE_DIGEST_INSENSITIVE_TO_EXPIRY is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature MAINTENANCE_TENANT is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature UDA_NATIVE_PARALLELIZED_AGGREGATION is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature LARGE_COLLECTION_DETECTION is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature RANGE_TOMBSTONE_AND_DEAD_ROWS_DETECTION is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature SECONDARY_INDEXES_ON_STATIC_COLUMNS is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature AGGREGATE_STORAGE_OPTIONS is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature TYPED_ERRORS_IN_READ_RPC is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature TABLETS is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature SUPPORTS_CONSISTENT_TOPOLOGY_CHANGES is enabled
2024-11-06T23:55:24.389+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] features - Feature HOST_ID_BASED_HINTED_HANDOFF is enabled
2024-11-06T23:55:29.638+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] init - Scylla version 6.2.1-0.20241106.a3a0ffbcd015 initialization completed.
2024-11-07T00:05:01.886+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[117041]:  [shard  0:main] init - Scylla version 6.2.1-0.20241106.a3a0ffbcd015 shutdown complete.
2024-11-07T00:07:38.643+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[122546]: Scylla version 6.1.2-0.20240915.b60f9ef4c223 with build-id c713ac9e819492d7560aa3ad461c43cf404c977b starting ...
2024-11-07T00:07:39.138+00:00 rolling-upgrade--centos-9-db-node-ac975443-0-4     !INFO | scylla[122546]:  [shard  0:main] init - **Scylla version 6.1.2-0.20240915.b60f9ef4c223** with build-id c713ac9e819492d7560aa3ad461c43cf404c977b starting ...
```

**Comment by roydahan** [comment] 2024-11-13 12:53
And yes, the commit that enabled this feature flag was introduced between 6.1.2 to 6.1.3.
Now we only need to understand why the downgrade took 6.1.2 and not 6.1.3.

**Comment by roydahan** [comment] 2024-11-13 13:16
Suspiciously enough, 6.1.3 was promoted at the same date, but still not sure how it could happen.

**Comment by mykaul** [comment] 2024-11-13 14:37
@piodul , @kostja  - this is delaying the release of 6.2.1, let's get to the bottom of it, if a workaround is available, is it a regression, etc. , so we can make an educated decision about this issue.

**Comment by mykaul** [comment] 2024-11-13 16:19
> > [@piodul](https://github.com/piodul) , [@kostja](https://github.com/kostja) - this is delaying the release of 6.2.1, let's get to the bottom of it, if a workaround is available, is it a regression, etc. , so we can make an educated decision about this issue.
> 
> [@mykaul](https://github.com/mykaul) Even though [@roydahan](https://github.com/roydahan) already explained that this is a test-side issue?
> 
> The "bug" is that SCT accidentally downgraded scylla twice (6.2.1 -> 6.1.3 -> 6.1.2), beyond the original 6.1.3, instead of the intended once (6.2.1 -> 6.1.3).
> 
> Apparently it meant to downgrade cqlsh and Scylla separately (it first ran `yum downgrade scylla-*cqlsh -y` and then `yum downgrade scylla\* -y`), but the downgrade of cqlsh also caused an additional downgrade of Scylla, and that was unintended.

1. I thought there was a parallel effort to validate this - @roydahan ?
2. So we've introduced a flag in the middle of the stream, but how come it was enabled? It was enabled somehow in 6.1.3? and then failed at 6.1.2? It wasn't clear to me that we've managed to upgrade all the way (from 6.1.2 to 6.1.3 -or- 6.2.1) to even enable the feature?

@kostja - any updates here?

**Comment by michoecho** [comment] 2024-11-13 16:23
> So we've introduced a flag in the middle of the stream, but how come it was enabled? It was enabled somehow in 6.1.3? and then failed at 6.1.2? It wasn't clear to me that we've managed to upgrade all the way (from 6.1.2 to 6.1.3 -or- 6.2.1) to even enable the feature?

@mykaul The test started by creating a 6.1.3 cluster, then upgraded some nodes to 6.2.1, then downgraded a node to 6.1.3, then downgraded the same node to 6.1.2. The last downgrade failed, because the cluster had ` MAINTENANCE_TENANT` (a cluster feature added in 6.1.3) enabled, and 6.1.2 doesn't recognize it.

**Comment by mykaul** [comment] 2024-11-13 16:25
> > So we've introduced a flag in the middle of the stream, but how come it was enabled? It was enabled somehow in 6.1.3? and then failed at 6.1.2? It wasn't clear to me that we've managed to upgrade all the way (from 6.1.2 to 6.1.3 -or- 6.2.1) to even enable the feature?
> 
> [@mykaul](https://github.com/mykaul) The test started by creating a 6.1.3 cluster, then upgraded some nodes to 6.2.1, then downgraded a node to 6.1.3, then downgraded the same node to 6.1.2. The last downgrade failed, because the cluster had `MAINTENANCE_TENANT` (a cluster feature added in 6.1.3) enabled, and 6.1.2 doesn't recognize it.

@roydahan - if that's the case, why are we keeping the bug open? Are we verifying the positive, correct path?

**Comment by mykaul** [comment] 2024-11-13 16:25
Thanks @michoecho for jumping quickly on this!

**Comment by mykaul** [comment] 2024-11-13 16:30
Closing - please re-open if we see it's a real issue and needs more attention.

**Closed by mykaul** 2024-11-13 16:30 UTC
Labels: area/rolling upgrades, P1, status/release blocker

**Comment by kostja** [comment] 2024-11-13 18:10
@roydahan @aleksbykov is there an sct issue that would establish the root cause of this double donwgrade and prevent it from happening in the future?

**Comment by dimakr** [comment] 2024-11-13 18:15
@kostja Here is the issue for SCT https://github.com/scylladb/scylla-cluster-tests/issues/9047

**Comment by roydahan** [comment] 2024-11-14 22:52
There is already a fix that was merged and backported - https://github.com/scylladb/scylla-cluster-tests/pull/9196
