### ISSUE TITLE
lwt: support user defined types in column conditions

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#5776] opened 2020-02-10 12:41 UTC
Currently it is not possible to use a user defined type in a conditional expression.
E.g. the following doesn't work IF user.name != NULL.
We should add support for it.

**Comment by nyh** [comment] 2023-05-22 12:49
We have a newer (and much more detailed) duplicate of this issue in https://github.com/scylladb/scylladb/issues/13624. I know it's strange, but I'll close this one because the new issue has much more details - about Cassandra compatibility, and a reproducing test.

**Closed by nyh** 2023-05-22 12:49 UTC
Labels: lwt
