### ISSUE TITLE
CQL layer accepts set values too large to be written to an sstable

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylladb#3017] opened 2017-11-24 11:37 UTC
Schema:
```cql
create table cf (
    pk int,
verylongcolumnname________________________________________________________________________________sdsfdsfds set<text>,
    primary key(pk));
```
Scylla gladly accepts adding values of size near 64kB:
```cql
update cf set verylongcolumnname________________________________________________________________________________sdsfdsfds = verylongcolumnname________________________________________________________________________________sdsfdsfds + {'<65531-byte string>'} where pk = 0;
```
However, since values of a set are serialised in sstables as a part of column name which is limited to 64kB and it is impossible to write such collection to an sstable. Consequently, all flush and drain attempts fail repeatedly with the following error:
```
ERROR 2017-11-24 11:32:48,138 [shard 0] database - failed to write sstable /var/lib/scylla/data/ks/cf-fcd86380d10911e7910c000000000004/ks-cf-ka-328-Data.db: std::runtime_error (Column name too large (65644 > 65535))
```

Looks like the same problem exists for map entries which key causes the final column name in an sstable to exceed 64kB.

**Comment by argenet** [comment] 2017-11-28 00:43
Seems we need some sort of query validation similar to https://github.com/blerer/cassandra/blob/10374-2.2/src/java/org/apache/cassandra/cql3/QueryProcessor.java#L212

**Comment by ptrsmrn** [comment] 2023-05-30 10:18
Together with @cvybhu we took a very quick look at this issue and it seems like the limit works for sets but doesn't work for map values and for map values scylla crashes, BUT no error is printed (we started scylla with `--default-log-level info`).

**Comment by nyh** [comment] 2024-01-15 08:23
Note that according to https://github.com/scylladb/scylladb/issues/7745 map keys and some of the other things mentioned here shouldn't actually be limited to 64KB, and this was changed nine years ago in Cassandra (https://github.com/scylladb/scylladb/commit/bc9a61fc851791926e8d2b6134f2bbca68a0ae11)

**Comment by nyh** [comment] 2024-01-15 09:23
Unfortunately the bug still very much exists, even for sets which @ptrsmrn thought above was fixed (I'm not preparing new tests for this and other  . The following cql-pytest crashes Scylla:

```python
def test_set_65k(cql, table3):
    stmt = cql.prepare(f'UPDATE {table3} SET set_column = set_column + ? WHERE p = ?')
    p = unique_key_int()
    val = random_string(length=65*1024)
    cql.execute(stmt, [{val}, p])
    results = list(cql.execute(f'SELECT p, set_column FROM {table3} WHERE p={p}'))
    assert results == [(p, SortedSet([val]))]
    nodetool.flush(cql, table3)
    nodetool.compact(cql, table3)
```
The INSERT and SELECT of over-64KB set values is accepted, as it should (it's accepted in Cassandra since CASSANDRA-10374, https://github.com/scylladb/scylladb/commit/bc9a61fc851791926e8d2b6134f2bbca68a0ae11, nine years ago). But then the compaction crashes Scylla, with the error:
```
ERROR 2024-01-15 11:08:07,770 [shard 0:main] table - failed to write sstable /tmp/scylla-test-2631817/data/cql_test_1705309687334/cql_test_1705309687499-990f19b0b38511ee960dca8fcfe9967c/me-3gcs_0pdj_4ktn72a5cet23dqum4-big-Data.db: std::overflow_error (assigning U to T caused an overflow)
ERROR 2024-01-15 11:08:07,770 [shard 0:strm] table - Memtable flush failed due to: std::overflow_error (assigning U to T caused an overflow). Aborting, at ..
```
The backtrace points to `replica::table::seal_active_memtable()`.

**Comment by denesb** [comment] 2024-07-17 12:55
The original error talks about column-name overflow, but this is not an issue anymore with the `mx` sstable format. Before, collection keys (as well as clustering keys) were all part of the column name, which was repeated for every cell. This is no longer the case in `mx` sstable formats.
I see we are still crashing, but not for the reason which the original report claims.

**Comment by nyh** [comment] 2024-07-17 13:10
@denesb please check the reproducer I included above (in January), and if it still crashes, feel free to close this issue and open a new one with the reproducer. If the reproducer no longer crashes, great :-)

**Comment by nyh** [comment] 2024-07-29 13:33
@denesb I checked my old reproducer, and it no longer fails on master Scylla. So I'm closing this issue.

It's not clear to me exactly when or how we fixed this bug, didn't we already have mx in January when I last reproduced this?

@denesb above you claimed "I see we are still crashing", but I can't reproduce this myself. If you can reproduce a crash please reopen this issue or open a new one with the updated reproducer.

**Closed by nyh** 2024-07-29 13:33 UTC
Labels: bug, area/cql, P2

**Comment by denesb** [comment] 2024-08-04 13:53
> @denesb above you claimed "I see we are still crashing", but I can't reproduce this myself. If you can reproduce a crash please reopen this issue or open a new one with the updated reproducer.

I don't have a reproducer, I just based my "I see we are still crashing" based on the comments above.

I agree we can close this, the problem should not happen with any currently supported ScyllaDB version anymore.
