### ISSUE TITLE
CI failure in dtest  update_cluster_layout_tests . TestUpdateClusterLayout.test_add_node_with_large_partition4

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#14776] opened 2023-07-20 18:29 UTC
Seen in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2615/, failure in dtest  `update_cluster_layout_tests`.`TestUpdateClusterLayout`.`test_add_node_with_large_partition4`:

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2615/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_add_node_with_large_partition4/
```
    def test_add_node_with_large_partition4(self):
...
        logger.debug("Check rows on node2")
>       self.check_rows_on_node(node2, nr_rows, ks='keyspace1', cf='standard1', counter_column='cn', timeout=timeout)
...
    def check_rows_on_node(self, node_to_check, rows, found=None, missings=None, restart=True, ks='ks', cf='cf',
                           counter_column=None, timeout=None):
...
            count = result[0][0]
>           assert count == rows
E           assert 297000 == 300000
E             +297000
E             -300000

update_cluster_layout_tests.py:82: AssertionError
```

**Comment by fruch** [comment] 2023-07-26 06:42
failed the same in enterprise gating today:

https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2483/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_add_node_with_large_partition4/

```
        session = self.patient_cql_connection(node_to_check, ks)
        if rows > 1000 and counter_column:
            query = SimpleStatement(f"SELECT count({counter_column}) FROM {ks}.{cf} LIMIT {rows * 2}",
                                    consistency_level=ConsistencyLevel.ONE)
            result = list(session.execute(query, timeout=timeout))
            count = result[0][0]
>           assert count == rows
E           assert 297000 == 300000
E             +297000
E             -300000

```

**Comment by fruch** [comment] 2023-07-26 06:46
in the last month this test passed 550, and failed 4 times.
the only failures it had is when running as part of gating. (in the last year it never failed in daily runs)

**Comment by fruch** [comment] 2023-07-26 06:49
@bhalevy @DoronArazii FYI

**Comment by DoronArazii** [comment] 2023-07-26 07:33
@bhalevy please assign someone to triage this

**Comment by bhalevy** [comment] 2023-07-26 10:15
@tchaikov can you please bisect to see what change introduced this?

**Comment by tchaikov** [comment] 2023-07-26 10:23
sure. i am on it.

**Comment by bhalevy** [comment] 2023-07-31 11:45
@tchaikov what's the verdict?

**Comment by tchaikov** [comment] 2023-08-01 07:29
@bhalevy hi Benny, i was trying to reproduce this issue locally. but failed.

but after reading through cassandra-stress's source code, i now have a theory to explain this.

i suspect that this is a bug in the test. we:

1. perform the customized "insert" operation for 100 times.
2. the clustering is specified with `cluster: uniform(3000,3000)`, so that each partition holds 3000 rows.
2. each insert operation inserts to a single fixed partition with `fixed(1)`

along with the spec on other values of columns of the table, we are able to create a table with large partitions.

but due to the inherent randomness of the test, even we perform 100 times, there are chances that we fails to distribute the emitted operations on 100 *different* partitions. what if two or more of them are targeting the same partition?

i will update the  test so it is more tolerant.

**Comment by bhalevy** [comment] 2023-08-01 07:51
> @bhalevy hi Benny, i was trying to reproduce this issue locally. but failed.
> 
> but after reading through cassandra-stress's source code, i now have a theory to explain this.
> 
> i suspect that this is a bug in the test. we:
> 
> 1. perform the customized "insert" operation for 100 times.
> 2. the clustering is specified with `cluster: uniform(3000,3000)`, so that each partition holds 3000 rows.
> 3. each insert operation inserts into a single fixed partition with `fixed(1)`
> 
> along with the spec on other values of columns of the table, we are able to create a table with large partitions.
> 
> but due to the inherent randomness of the test, even we perform 100 times, there are chances that we fails to distribute the emitted operations on 100 _different_ partitions. what if two or more of them are targeting the same partition?
> 
> i will update the test so it is more tolerant.

Maybe we need to add `f"pop=seq(1..{nr_partitions})"` stress option to tell it to write to those partitions.

Also, the comments say:
```
        1. Create a cluster with a single node with rf=2, insert data with large partitions
```

But I don't see where it's set.

**Comment by bhalevy** [comment] 2023-08-01 08:15
In cassandra-stress-custom-large-partition-1.yaml:
```
  CREATE KEYSPACE keyspace1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 2};
```

**Comment by tchaikov** [comment] 2023-08-01 09:15
> > @bhalevy hi Benny, i was trying to reproduce this issue locally. but failed.
> > but after reading through cassandra-stress's source code, i now have a theory to explain this.
> > i suspect that this is a bug in the test. we:
> > 
> > 1. perform the customized "insert" operation for 100 times.
> > 2. the clustering is specified with `cluster: uniform(3000,3000)`, so that each partition holds 3000 rows.
> > 3. each insert operation inserts into a single fixed partition with `fixed(1)`
> > 
> > along with the spec on other values of columns of the table, we are able to create a table with large partitions.
> > but due to the inherent randomness of the test, even we perform 100 times, there are chances that we fails to distribute the emitted operations on 100 _different_ partitions. what if two or more of them are targeting the same partition?
> > i will update the test so it is more tolerant.
> 
> Maybe we need to add `f"pop=seq(1..{nr_partitions})"` stress option to tell it to write to those partitions.
> 

just realized that the `user` command did not allow us to specify the primary key (or a given key) 's population with command line option. i will use the profile file as a template and generate yet another profile file on the fly, and feed the new profile to c-s.

**Comment by tchaikov** [comment] 2023-08-01 10:39
closing, as it's a bug in dtest.

**Comment by tchaikov** [comment] 2023-08-22 02:44
spotted again in next promotion build: https://jenkins.scylladb.com/job/scylla-master/job/next/6424/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_add_node_with_large_partition4/

**Comment by bhalevy** [comment] 2023-08-22 07:21
I'm still not sure the bug is on scylla's side.
I don't remember how the test is implemented exactly, but could the inconsistency be caused by using cl=ONE?

**Comment by gleb-cloudius** [comment] 2023-08-22 13:02
Hit it here:
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3189/

**Comment by Annamikhlin** [comment] 2023-08-23 05:43
failed on the same in master gating today:
https://jenkins.scylladb.com/job/scylla-master/job/next/6430/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_add_node_with_large_partition4/

**Comment by tchaikov** [comment] 2023-08-23 07:24
> I'm still not sure the bug is on scylla's side. I don't remember how the test is implemented exactly, but could the inconsistency be caused by using cl=ONE?

IIUC, in the test, the RF of the cluster is 2, so once the 2nd node joins the cluster, it should be streamed with the mutations of the tables, including the one whose cl=ONE. but when verifying the number of rows in the 2nd node, we use `cl=ONE` for the read request. hence the read request does just go straight to the 2nd node. so there is chance that the 2nd node is not fully consistent with the 1st one and a mutation fragment including 1 partition (300 rows) has not applied yet?

**Comment by bhalevy** [comment] 2023-08-23 08:01
When verifying we stop the other node so  cl=ONE on the remaining node should be fine.

I just noticed that we pass `counter_column='cn'` and in this case, `check_rows_on_node` uses:
```
            query = SimpleStatement(f"SELECT count({counter_column}) FROM {ks}.{cf} LIMIT {rows * 2}",
                                    consistency_level=ConsistencyLevel.ONE)
```

It could be have too many variables in this test: cassandra-stress, counter column, aggregation function (`count({counter_column}`).

while if we'd pass no counter_column, the verification would be with:
```
            query = SimpleStatement(f"SELECT * FROM {ks}.{cf} LIMIT {rows * 2}", consistency_level=ConsistencyLevel.ONE)
```

which, from experience, is less flaky.

**Comment by tchaikov** [comment] 2023-08-23 09:25
> When verifying we stop the other node so cl=ONE on the remaining node should be fine.

is it possible that the streaming is not yet finished when the first node is stopped?

> which, from experience, is less flaky.

the default population of a column if its population distribution is not specified is `uniform(1..100B)`. so the `cn` column should not be NULL. in other words, the first column of the row returned by
```cql
SELECT count(cn) FROM ks.cf LIMIT {rows * 2}
```
and the number of rows returned by
```cql
SELECT * FROM ks.cf LIMIT {rows * 2}
```

**Comment by tchaikov** [comment] 2023-08-24 02:30
i see. you think "count()" is different from "all the data". the former is what we intend or claim to verify in this very test. my only concern is the huge amount of result set returned by the test. since it is already paginated, if we just count the number of it in the test, it should be fine.

let me prepare a change.

**Comment by tchaikov** [comment] 2023-08-24 02:33
since the change is happening in dtest. i am reopening https://github.com/scylladb/scylla-dtest/issues/3384 and closing this one.

**Comment by avikivity** [comment] 2023-10-11 10:55
Seen again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6650/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests_RAFT___test_add_node_with_large_partition4/

```
>       assert count == rows
E       assert 297000 == 300000
```

**Comment by bhalevy** [comment] 2023-10-19 10:10
Should be handled (finally I hope) by https://github.com/scylladb/scylla-dtest/pull/3676
This seems like an issue with use of cassandra stress in the dtest.
We shouldn't rely on it to generate contents in a deterministic way, but rather generate the data ourselves.

Longer term, I think we should implement a configurable, self-verifyable load generator natively in Python to replace c-s for testing.

**Closed by bhalevy** 2023-10-19 10:10 UTC
Labels: bug, dtest, P1, CI-Stability

**Comment by mykaul** [comment] 2023-10-19 10:49
For stress we are developing https://github.com/scylladb/cql-stress
Could add to it verification, I reckon.
