### ISSUE TITLE
Nodes are getting "wrong schema version" errors, then a quorum write fails with a timeout exception

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#10003] opened 2022-01-31 16:03 UTC
*Installation details*
Kernel version: `5.11.0-1027-aws`
Scylla version (or git commit hash): `5.0.dev-0.20220127.ba6c02b38 with build-id b93317e46cc252428454f96e8716b0948f28304c`
Cluster size: 6 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   longevity-tls-50gb-3d-master-db-node-1bdb69d6-1 (54.75.41.17 | 10.0.2.245): 14 shards
   longevity-tls-50gb-3d-master-db-node-1bdb69d6-4 (18.202.236.152 | 10.0.2.126): 14 shards
   longevity-tls-50gb-3d-master-db-node-1bdb69d6-7 (34.255.208.176 | 10.0.2.16): 14 shards
   longevity-tls-50gb-3d-master-db-node-1bdb69d6-16 (18.203.139.69 | 10.0.2.86): 14 shards
   longevity-tls-50gb-3d-master-db-node-1bdb69d6-17 (54.75.56.198 | 10.0.2.236): 14 shards
   longevity-tls-50gb-3d-master-db-node-1bdb69d6-18 (54.171.134.46 | 10.0.0.209): 14 shards
Scylla running with shards number (terminated nodes):
   longevity-tls-50gb-3d-master-db-node-1bdb69d6-2 (34.252.164.228 | 10.0.0.69): 14 shards
   >> List of nodes is larger than 10. See sct log for a full list of nodes.

OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-098e8a18da4ea000f` (aws: eu-west-1)

Test: `longevity-50gb-3days`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2c3e4506cee8b75c0f4e89b0aefb9f335c52d6dd/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

**Issue description**

====================================
1. a nemesis of kill-scylla was executed. 
```
KillScylla | 1 | nodestartendduration | node | start | end | duration | nodestartenddurationerrorNode longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 [54.170.162.228 \| 10.0.1.180] (seed: False)2022-01-30 06:11:212022-01-30 06:48:152214Schema agreement is not reached | node | start | end | duration | error | Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 [54.170.162.228 \| 10.0.1.180] (seed: False) | 2022-01-30 06:11:21 | 2022-01-30 06:48:15 | 2214 | Schema agreement is not reached
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 [54.170.162.228 \| 10.0.1.180] (seed: False) | 2022-01-30 06:11:21 | 2022-01-30 06:48:15 | 2214 | Schema agreement is not reached

```
2. DB nodes like 1 and 16 started getting "wrong schema" errors for few hours
3. eventually the c-s stress failed with write-timeout-exception for a lack of quorum.

log had errors of:
```
2022-01-30 14:19:31.243: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=73f4676b-c329-4650-91a0-b52bde53bd6c: type=NodeSchemaVersion node=longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 error=Current node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 [54.170.162.228 | 10.0.1.180] (seed: False). Wrong Schema version. Node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-1 [54.75.41.17 | 10.0.2.245] (seed: True) (not target node) schema version in SYSTEM.PEERS is 30b004c4-865e-3e93-932d-1b17482bd5dd, but schema version in gossip 7f791e7b-e8ce-340c-aa89-d51dba08456f
2022-01-30 14:19:31.253: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=342baeb1-9811-4748-b89b-e2123de38bab: type=NodeSchemaVersion node=longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 error=Current node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 [54.170.162.228 | 10.0.1.180] (seed: False). Wrong Schema version. Node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-16 [18.203.139.69 | 10.0.2.86] (seed: False) (not target node) schema version in SYSTEM.PEERS is 30b004c4-865e-3e93-932d-1b17482bd5dd, but schema version in gossip 7f791e7b-e8ce-340c-aa89-d51dba08456f
2022-01-30 14:23:21.090: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=3637dda1-497a-4311-8803-7b34cb94cc54: type=NodeSchemaVersion node=longevity-tls-50gb-3d-master-db-node-1bdb69d6-16 error=Current node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-16 [18.203.139.69 | 10.0.2.86] (seed: False). Wrong Schema version. Node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-1 [54.75.41.17 | 10.0.2.245] (seed: True) (not target node) schema version in SYSTEM.PEERS is 30b004c4-865e-3e93-932d-1b17482bd5dd, but schema version in gossip 7f791e7b-e8ce-340c-aa89-d51dba08456f
2022-01-30 14:37:26.134: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=ccd8c587-43bb-412a-b005-64ec75944f5b: type=NodeStatus node=longevity-tls-50gb-3d-master-db-node-1bdb69d6-4 error=Current node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-4 [18.202.236.152 | 10.0.2.126] (seed: False). Wrong node status. Node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-1 [54.75.41.17 | 10.0.2.245] (seed: True) status in nodetool.status is UN, but status in gossip LEFT
2022-01-30 14:37:26.427: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=3380ff04-0949-4014-bd7f-1cba5d134ed7: type=NodeStatus node=longevity-tls-50gb-3d-master-db-node-1bdb69d6-4 error=Current node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-4 [18.202.236.152 | 10.0.2.126] (seed: False). Wrong node status. Node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-16 [18.203.139.69 | 10.0.2.86] (seed: False) status in nodetool.status is UN, but status in gossip LEFT
2022-01-30 14:42:06.148: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=3c33e1fa-a25b-4cd7-9112-9f0014fb13c5: type=NodeStatus node=longevity-tls-50gb-3d-master-db-node-1bdb69d6-7 error=Current node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-7 [34.255.208.176 | 10.0.2.16] (seed: False). Wrong node status. Node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-1 [54.75.41.17 | 10.0.2.245] (seed: True) status in nodetool.status is UN, but status in gossip LEFT
2022-01-30 14:42:06.468: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=22abb096-f9e0-476d-845e-9360bd91157d: type=NodeStatus node=longevity-tls-50gb-3d-master-db-node-1bdb69d6-7 error=Current node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-7 [34.255.208.176 | 10.0.2.16] (seed: False). Wrong node status. Node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-16 [18.203.139.69 | 10.0.2.86] (seed: False) status in nodetool.status is UN, but status in gossip LEFT
2022-01-30 14:45:55.097: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=ede08b12-2136-41d5-9f02-14ac685b6d22: type=NodeSchemaVersion node=longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 error=Current node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 [54.170.162.228 | 10.0.1.180] (seed: False). Wrong Schema version. Node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-1 [54.75.41.17 | 10.0.2.245] (seed: True) (not target node) schema version in SYSTEM.PEERS is 30b004c4-865e-3e93-932d-1b17482bd5dd, but schema version in gossip 7f791e7b-e8ce-340c-aa89-d51dba08456f
2022-01-30 14:45:55.398: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=fcd728c0-e351-4c97-a39e-a4cb553e83f1: type=NodeSchemaVersion node=longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 error=Current node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 [54.170.162.228 | 10.0.1.180] (seed: False). Wrong Schema version. Node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-16 [18.203.139.69 | 10.0.2.86] (seed: False) (not target node) schema version in SYSTEM.PEERS is 30b004c4-865e-3e93-932d-1b17482bd5dd, but schema version in gossip 7f791e7b-e8ce-340c-aa89-d51dba08456f
2022-01-30 14:49:46.929: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=65de8cbc-b7a3-47c5-af36-f7ad8e28a374: type=NodeSchemaVersion node=longevity-tls-50gb-3d-master-db-node-1bdb69d6-16 error=Current node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-16 [18.203.139.69 | 10.0.2.86] (seed: False). Wrong Schema version. Node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-1 [54.75.41.17 | 10.0.2.245] (seed: True) (not target node) schema version in SYSTEM.PEERS is 30b004c4-865e-3e93-932d-1b17482bd5dd, but schema version in gossip 7f791e7b-e8ce-340c-aa89-d51dba08456f
2022-01-30 15:08:45.010: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=41053ea7-4444-4ee8-b37c-58eaf645c08b: type=IOException regex=java\.io\.IOException line_number=194529 node=Node longevity-tls-50gb-3d-master-loader-node-1bdb69d6-1 [54.154.121.89 | 10.0.3.239] (seed: False)
java.io.IOException:e query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
2022-01-30 15:08:48.396: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=352e1d85-bbe9-4bef-a05a-911f2f2a2dec: type=IOException regex=java\.io\.IOException line_number=193275 node=Node longevity-tls-50gb-3d-master-loader-node-1bdb69d6-3 [52.210.68.15 | 10.0.0.140] (seed: False)
java.io.IOException:he write)
2022-01-30 15:08:53.357: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=352e1d85-bbe9-4bef-a05a-911f2f2a2dec: type=IOException regex=java\.io\.IOException line_number=194626 node=Node longevity-tls-50gb-3d-master-loader-node-1bdb69d6-1 [54.154.121.89 | 10.0.3.239] (seed: False)
java.io.IOException: Operation x10 on keimeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
2022-01-30 15:08:53.357: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=5ba05f93-a54d-449e-8c78-497afcfa52a9: type=IOException regex=java\.io\.IOException line_number=194626 node=Node longevity-tls-50gb-3d-master-loader-node-1bdb69d6-1 [54.154.121.89 | 10.0.3.239] (seed: False)
java.io.IOException: Operation x10 on keimeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
2022-01-30 15:10:07.554: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=644dbd3e-f333-4569-a58d-53c81df914ed: type=IOException regex=java\.io\.IOException line_number=194134 node=Node longevity-tls-50gb-3d-master-loader-node-1bdb69d6-3 [52.210.68.15 | 10.0.0.140] (seed: False)
java.io.IOException: Operation x10 ohe write)
2022-01-30 15:10:12.583: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=8f91053e-1c16-47ec-ae3d-cc3224080b83: type=IOException regex=java\.io\.IOException line_number=195469 node=Node longevity-tls-50gb-3d-master-loader-node-1bdb69d6-1 [54.154.121.89 | 10.0.3.239] (seed: False)
java.io.IOException: Operation x10 oistency QUORUM (3 replica were required but only 2 acknowledged the write)
2022-01-30 15:10:17.190: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=644dbd3e-f333-4569-a58d-53c81df914ed: type=IOException regex=java\.io\.IOException line_number=195232 node=Node longevity-tls-50gb-3d-master-loader-node-1bdb69d6-2 [34.244.213.155 | 10.0.0.159] (seed: False)
java.io.IOException: Operation x10 on koutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledged the write)
2022-01-30 15:24:48.346: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=65ed7065-0bcc-41f9-a0cd-4f331e1b8a8d: type=NodeStatus node=longevity-tls-50gb-3d-master-db-node-1bdb69d6-4 error=Current node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-4 [18.202.236.152 | 10.0.2.126] (seed: False). Wrong node status. Node Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-18 [54.171.134.46 | 10.0.0.209] (seed: False) status in nodetool.status is UN, but status in gossip LEFT
```

list of nemesis ran:
```
< t:2022-01-30 05:54:46,349 f:nemesis.py      l:1216 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: >>>>>>>>>>>>>Started random_disrupt_method kill_scylla
< t:2022-01-30 06:11:21,483 f:nemesis.py      l:792  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> KillScylla Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 [54.170.162.228 | 10.0.1.180] (seed: False)
< t:2022-01-30 06:48:14,490 f:nemesis.py      l:3173 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2022-01-30 07:03:21,594 f:nemesis.py      l:1226 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: <<<<<<<<<<<<<Finished random_disrupt_method kill_scylla
< t:2022-01-30 07:08:21,962 f:nemesis.py      l:1216 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: >>>>>>>>>>>>>Started random_disrupt_method network_start_stop_interface
< t:2022-01-30 07:23:39,137 f:nemesis.py      l:792  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> NetworkStartStopInterface Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 [54.170.162.228 | 10.0.1.180] (seed: False)
< t:2022-01-30 07:39:38,360 f:nemesis.py      l:1226 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: <<<<<<<<<<<<<Finished random_disrupt_method network_start_stop_interface
< t:2022-01-30 07:44:38,796 f:nemesis.py      l:1216 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: >>>>>>>>>>>>>Started random_disrupt_method run_unique_sequence
< t:2022-01-30 08:01:30,955 f:nemesis.py      l:792  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> RunUniqueSequence Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-17 [54.75.56.198 | 10.0.2.236] (seed: False)
< t:2022-01-30 08:17:20,032 f:nemesis.py      l:792  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> MgmtRepairCli Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-4 [18.202.236.152 | 10.0.2.126] (seed: False)
< t:2022-01-30 14:50:40,905 f:nemesis.py      l:792  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> TerminateAndReplaceNode Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-8 [54.170.162.228 | 10.0.1.180] (seed: False)
< t:2022-01-30 16:04:12,733 f:nemesis.py      l:792  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> GrowShrinkCluster Node longevity-tls-50gb-3d-master-db-node-1bdb69d6-4 [18.202.236.152 | 10.0.2.126] (seed: False)

```
====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 1bdb69d6-92e7-44f0-bfe2-715494307241`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1bdb69d6-92e7-44f0-bfe2-715494307241)
Show all stored logs command: `$ hydra investigate show-logs 1bdb69d6-92e7-44f0-bfe2-715494307241`

Test id: `1bdb69d6-92e7-44f0-bfe2-715494307241`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/1bdb69d6-92e7-44f0-bfe2-715494307241/20220130_154319/grafana-screenshot-overview-20220130_154322-longevity-tls-50gb-3d-master-monitor-node-1bdb69d6-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/1bdb69d6-92e7-44f0-bfe2-715494307241/20220130_154319/grafana-screenshot-overview-20220130_154322-longevity-tls-50gb-3d-master-monitor-node-1bdb69d6-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/1bdb69d6-92e7-44f0-bfe2-715494307241/20220130_161519/db-cluster-1bdb69d6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1bdb69d6-92e7-44f0-bfe2-715494307241/20220130_161519/db-cluster-1bdb69d6.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/1bdb69d6-92e7-44f0-bfe2-715494307241/20220130_161519/monitor-set-1bdb69d6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1bdb69d6-92e7-44f0-bfe2-715494307241/20220130_161519/monitor-set-1bdb69d6.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days/121/)

**Comment by yarongilor** [comment] 2022-02-01 12:42
Reproduced in 200gb-48h longevity:
error:
```
2022-01-31 18:37:09.628: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=2f7d0d06-c3ca-412e-8f4f-419f6170fd8f: type=NodeSchemaVersion node=longevity-200gb-48h-verify-limited--db-node-f5807201-4 error=Current node Node longevity-200gb-48h-verify-limited--db-node-f5807201-4 [54.216.85.22 | 10.0.1.106] (seed: False). Wrong Schema version. Node Node longevity-200gb-48h-verify-limited--db-node-f5807201-5 [34.244.38.247 | 10.0.0.167] (seed: False) (not target node) schema version in SYSTEM.PEERS is 14cbfc64-27d3-3386-b671-01492b5a283c, but schema version in gossip bbe23ee5-ea2c-317a-bffc-9d11a237a495
```
*Installation details*
Kernel version: `5.11.0-1027-aws`
Scylla version (or git commit hash): `5.0.dev-0.20220127.ba6c02b38 with build-id b93317e46cc252428454f96e8716b0948f28304c`
Cluster size: 4 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   longevity-200gb-48h-verify-limited--db-node-f5807201-1 (34.242.105.52 | 10.0.0.145): 14 shards
   longevity-200gb-48h-verify-limited--db-node-f5807201-3 (34.244.147.63 | 10.0.2.53): 14 shards
   longevity-200gb-48h-verify-limited--db-node-f5807201-4 (54.216.85.22 | 10.0.1.106): 14 shards
   longevity-200gb-48h-verify-limited--db-node-f5807201-5 (34.244.38.247 | 10.0.0.167): 14 shards
Scylla running with shards number (terminated nodes):
   longevity-200gb-48h-verify-limited--db-node-f5807201-2 (63.33.206.201 | 10.0.1.104): 14 shards
   longevity-200gb-48h-verify-limited--db-node-f5807201-6 (63.32.54.98 | 10.0.0.225): 14 shards
   longevity-200gb-48h-verify-limited--db-node-f5807201-7 (34.240.148.45 | 10.0.0.198): 14 shards
   longevity-200gb-48h-verify-limited--db-node-f5807201-8 (63.35.221.67 | 10.0.0.237): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-098e8a18da4ea000f` (aws: eu-west-1)


Test: `longevity-200gb-48h`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2c3e4506cee8b75c0f4e89b0aefb9f335c52d6dd/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)


**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE


====================================






Restore Monitor Stack command: `$ hydra investigate show-monitor f5807201-90f8-4fa8-9a7e-db068436bd48`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f5807201-90f8-4fa8-9a7e-db068436bd48)
Show all stored logs command: `$ hydra investigate show-logs f5807201-90f8-4fa8-9a7e-db068436bd48`

Test id: `f5807201-90f8-4fa8-9a7e-db068436bd48`


Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/f5807201-90f8-4fa8-9a7e-db068436bd48/20220131_210858/grafana-screenshot-overview-20220131_210859-longevity-200gb-48h-verify-limited--monitor-node-f5807201-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/f5807201-90f8-4fa8-9a7e-db068436bd48/20220131_210858/grafana-screenshot-overview-20220131_210859-longevity-200gb-48h-verify-limited--monitor-node-f5807201-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/f5807201-90f8-4fa8-9a7e-db068436bd48/20220131_212818/db-cluster-f5807201.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f5807201-90f8-4fa8-9a7e-db068436bd48/20220131_212818/db-cluster-f5807201.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/f5807201-90f8-4fa8-9a7e-db068436bd48/20220131_212818/loader-set-f5807201.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f5807201-90f8-4fa8-9a7e-db068436bd48/20220131_212818/loader-set-f5807201.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/f5807201-90f8-4fa8-9a7e-db068436bd48/20220131_212818/monitor-set-f5807201.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f5807201-90f8-4fa8-9a7e-db068436bd48/20220131_212818/monitor-set-f5807201.tar.gz)
sct - [https://cloudius-jenkins-test.s3.amazonaws.com/f5807201-90f8-4fa8-9a7e-db068436bd48/20220131_212818/sct-runner-f5807201.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f5807201-90f8-4fa8-9a7e-db068436bd48/20220131_212818/sct-runner-f5807201.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/163/)

**Comment by DoronArazii** [comment] 2022-09-18 08:22
@eliransin are we planning to deal with it on 5.1?

**Comment by soyacz** [comment] 2023-01-16 12:15
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

When forcibly killing scylla with `kill -9`, when node is back we get schema agreement is not reached within 30 minutes.
Although problem might arise eariler - just `kill_scylla` nemesis verifies schema

## Impact

outdated schema on nodes

## How frequently does it reproduce?



## Installation details

Kernel Version: 5.15.0-1028-aws
Scylla version (or git commit hash): `2022.2.0-20230112.4f0f82ff2e1d` with build-id `a1d0fdd6fed1f802854040dbefcf5c45bbc4e820`
Relocatable Package: http://downloads.scylladb.com/unstable/scylla-enterprise/enterprise-2022.2/relocatable/2023-01-12T16:08:35Z/scylla-enterprise-x86_64-package.tar.gz



Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-9 (3.121.234.71 | 10.11.1.127) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-8 (35.157.20.1 | 10.11.3.224) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-7 (3.66.18.102 | 10.11.2.147) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-6 (18.185.51.182 | 10.11.0.10) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-5 (3.70.247.141 | 10.11.0.150) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-4 (18.184.167.224 | 10.11.1.79) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-3 (18.184.161.86 | 10.11.1.169) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-2 (18.194.79.33 | 10.11.0.12) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-13 (3.76.212.250 | 10.11.1.235) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-12 (3.64.216.142 | 10.11.1.88) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-11 (54.93.59.89 | 10.11.2.138) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-10 (18.159.208.63 | 10.11.3.22) (shards: 7)
- longevity-lwt-parallel-24h-2022-2-db-node-e8b3f088-1 (3.70.170.3 | 10.11.2.157) (shards: 7)


OS / Image: `ami-0b0fad9cda29039ae` (aws: eu-central-1)

Test: `longevity-lwt-parallel-schema-changes-with-disruptive-24h-test`
Test id: `e8b3f088-362c-4423-b19c-794c41fa48e9`
Test name: `enterprise-2022.2/longevity/longevity-lwt-parallel-schema-changes-with-disruptive-24h-test`
Test config file(s):

- [longevity-lwt-parallel-24h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2cc59fa33f6de3c12f103794bf42abde53444a95/test-cases/longevity/longevity-lwt-parallel-24h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor e8b3f088-362c-4423-b19c-794c41fa48e9`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e8b3f088-362c-4423-b19c-794c41fa48e9)
- Show all stored logs command: `$ hydra investigate show-logs e8b3f088-362c-4423-b19c-794c41fa48e9`


## Logs:
- **db-cluster-e8b3f088.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e8b3f088-362c-4423-b19c-794c41fa48e9/20230114_093710/db-cluster-e8b3f088.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e8b3f088-362c-4423-b19c-794c41fa48e9/20230114_093710/db-cluster-e8b3f088.tar.gz)
- **monitor-set-e8b3f088.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e8b3f088-362c-4423-b19c-794c41fa48e9/20230114_093710/monitor-set-e8b3f088.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e8b3f088-362c-4423-b19c-794c41fa48e9/20230114_093710/monitor-set-e8b3f088.tar.gz)
- **loader-set-e8b3f088.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e8b3f088-362c-4423-b19c-794c41fa48e9/20230114_093710/loader-set-e8b3f088.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e8b3f088-362c-4423-b19c-794c41fa48e9/20230114_093710/loader-set-e8b3f088.tar.gz)
- **sct-runner-e8b3f088.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e8b3f088-362c-4423-b19c-794c41fa48e9/20230114_093710/sct-runner-e8b3f088.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e8b3f088-362c-4423-b19c-794c41fa48e9/20230114_093710/sct-runner-e8b3f088.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-lwt-parallel-schema-changes-with-disruptive-24h-test/7/)
</details>

**Comment by DoronArazii** [comment] 2023-02-20 19:33
@eliransin it's in the plans for 5.2?

**Comment by mykaul** [comment] 2023-02-21 09:35
> @eliransin it's in the plans for 5.2?

Like all schema management issues, we need to re-run with Raft (enabled by default now for new deployments) and see if it reproduces. Raft doesn't fix world hunger and climate issues, but should help most schema consistency issues. If it doesn't, we'd like to know and investigate.

**Comment by DoronArazii** [comment] 2023-02-21 09:39
@yarongilor / @soyacz ^^

**Comment by DoronArazii** [comment] 2023-02-28 10:52
@fgelcer ping

**Comment by eliransin** [comment] 2023-03-06 08:17
Waiting for an answer if it is not reproducible with Raft.

**Comment by mykaul** [comment] 2023-04-17 14:30
> Waiting for an answer if it is not reproducible with Raft.

@fgelcer - any updates?

**Comment by fgelcer** [comment] 2023-04-20 14:37
> but schema version in gossip

last 9 runs of 200gb 48h job passed... and the 50gb 3days are failing with other issues (perhaps before we could see this schema mismatch), but so far, not seeing it in master runs (where raft is enabled)

**Comment by eliransin** [comment] 2023-07-05 09:52
> last 9 runs of 200gb 48h job passed... and the 50gb 3days are failing with other issues (perhaps before we could see this schema mismatch), but so far, not seeing it in master runs (where raft is enabled)

@fgelcer / @mykaul I see that this issue is pending QA reproduction since march, this tells me that it probably didn't reproduce since than, I would like to close the issue, unless @fgelcer has some new failures reproductions to share, just as a reminder, we hypothesized that raft based schema changes will solve this, right now it looks like they did.
We can always open a new issue if it happens again, either way even with the same symptoms it is most likely that it
will be a different bug after the raft integration.

**Comment by mykaul** [comment] 2023-07-05 09:57
> > last 9 runs of 200gb 48h job passed... and the 50gb 3days are failing with other issues (perhaps before we could see this schema mismatch), but so far, not seeing it in master runs (where raft is enabled)
> 
> @fgelcer / @mykaul I see that this issue is pending QA reproduction since march, this tells me that it probably didn't reproduce since than, I would like to close the issue, unless @fgelcer has some new failures reproductions to share, just as a reminder, we hypothesized that raft based schema changes will solve this, right now it looks like they did. We can always open a new issue if it happens again, either way even with the same symptoms it is most likely that it will be a different bug after the raft integration.

Agreed, let's close. If we see it again / different, we can always open a new issue.

**Closed by mykaul** 2023-07-05 09:57 UTC
Labels: bug, schema changes, Pending-QA-Reproduction, P2

**Comment by fgelcer** [comment] 2023-07-11 08:46
> > last 9 runs of 200gb 48h job passed... and the 50gb 3days are failing with other issues (perhaps before we could see this schema mismatch), but so far, not seeing it in master runs (where raft is enabled)
> 
> @fgelcer / @mykaul I see that this issue is pending QA reproduction since march, this tells me that it probably didn't reproduce since than, I would like to close the issue, unless @fgelcer has some new failures reproductions to share, just as a reminder, we hypothesized that raft based schema changes will solve this, right now it looks like they did. We can always open a new issue if it happens again, either way even with the same symptoms it is most likely that it will be a different bug after the raft integration.

sorry, i missed this email between many other issues and mentions... i can confirm `kill_scylla` nemesis passed successfully on a run from June 9th (but since they are failing with something else, so the nemesis did not run, since June 9th)
