### ISSUE TITLE
Inserted data only becomes available after restart

### ISSUE THREAD

**Issue by rngcntr** [scylladb/scylladb#16759] opened 2024-01-12 11:12 UTC
*Installation details*
Scylla version: 5.4.1
Cluster size: 1 Node
Platform: Docker on Kubernetes

After Upgrading Scylla from 5.2.11 via 5.4.0 to 5.4.1, we started observing missing data in Scylla. Every once in a while, an `INSERT` is committed successfully but the inserted values are not visible until Scylla is restarted. As far as we can tell, version 5.2.11 was not affected while 5.4.1 is. 5.4.0 was not long enough in operation to make a reliable statement.

The suspected bug occurs extremely rarely, making it hard for us to reproduce. Out of ~800M inserts per day, only a dozen are affected. In our running environment, I was able to perform the following steps:
1. Execute the normal `INSERT` workload using multiple concurrent clients.
2. Wait until a client notices that a `SELECT` on a previously `INSERT`ed key returns no columns
3. Shut down all clients to make sure there is no unnecessary load on our ScyllaDB
4. (optional) wait as long as you want for ScyllaDB to (process backlog/perform compactions/achieve consistency/whatever...)
5. Execute query: `SELECT * FROM tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX.edgestore WHERE key = <affected_key>`. The result is empty.
6. Restart ScyllaDB and wait until it is operational.
7. Execute the same query again and notice the `INSERT`ed data suddenly became available:

|key|column1|value|
|--|--|--|
|<affected_key>|0xXX|0xXXXXXXXXXXXXXXXX|
|<affected_key>|0xXX|0xXXXXXXXXXXXXXXXXXXXX|
|<affected_key>|0xXXXX|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
|<affected_key>|0xXXXX|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
|<affected_key>|0xXXXX|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
|<affected_key>|0xXXXX|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
|<affected_key>|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|

`X` obviously masks potentially private hexadecimal data which is not relevant to this report.

What I already tried instead of restarting Scylla:
- `nodetool refresh`
- `nodetool flush`
- `nodetool rebuild` and `nodetool repair` even though I'm aware both shouldn't make any difference on a single node cluster.

It looks to me like Scylla has somehow recognized the transaction as completed even though it has not been persisted as expected. There seems to be some procedure which is triggered either by the shutdown or by the startup that picks this transaction up and replays it so the its modifications actually become available. 

**Appendix**: The Scylla [logs](https://github.com/scylladb/scylladb/files/13918121/logs-without-compactions.txt) captured during this operation. I removed all compaction logs to reduce the file to a reasonable size.

**Comment by michoecho** [comment] 2024-01-12 15:39
>(optional) wait as long as you want for ScyllaDB to (process backlog/perform compactions/achieve consistency/whatever...)

While it might take some time for data to be replicated to other nodes, it should be immediately visible on all replicas which acknowledged it. In particular, since this is a single-node cluster, all INSERTs which succeeded should be visible immediately.

>It looks to me like Scylla has somehow recognized the transaction as completed even though it has not been persisted as expected.

It shouldn't be possible for that to happen. If the write eventually became visible, then it must have been there the whole time, since it was acknowledged -- either in the memtables (in-memory trees with recent writes), or the sstables (on-disk files with older writes).

That's why my first suspicion is a bug in the read path. Since the write became visible after restart, it shouldn't be a bug in sstable readers – a restart doesn't change the readers and doesn't change the sstables. And since memtable readers do almost the same thing during SELECTs (which didn't work) and during flush to disk (which did work), it also shouldn't be a bug in memtable readers.

Hence, it sounds like a bug in the row cache (a layer between the SELECTs and the sstables, which holds merged results of recent reads and writes).

If you are again able to reproduce a state where an acknowledged write isn't visible, please run `SELECT * FROM MUTATION_FRAGMENTS(tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX.edgestore) WHERE key = <affected_key>`.

`SELECT * FROM MUTATION_FRAGMENTS(...)` is a debug statement which queries all sources of data (i.e. sstables, memtables, and the cache). That should tell us where the write is stored, and what's hiding it.

Also, try doing the SELECT with BYPASS CACHE. If it's a cache bug, this select should succeed.

>There seems to be some procedure which is triggered either by the shutdown or by the startup that picks this transaction up and replays it so the its modifications actually become available.

Well, replay procedures do exist in Scylla. When something is written, it's first written to the commitlog (which is persisted to disk either before the write is acknowledged or soon after, depending on the configuration), and then it's written to memtables. If Scylla doesn't shut down cleanly, then the commitlog is replayed on startup to recover the lost memtables.

But that only happens after an unclean shutdown, and it's logged. Your logs don't mention commitlog replay, so commitlog should be irrelevant to this case.

There's also batchlog replay, but that would only be relevant if you were doing BATCH inserts and they failed.

**Comment by rngcntr** [comment] 2024-01-15 11:53
Thanks for the great analysis, it looks like your suspicion is spot on as far as my investigations go. The bug occurred again today and just as you predicted, the results suggest the culprit is somewhere in the cache:

`SELECT * FROM tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX.edgestore WHERE key = <affected_key>;` yields an empty response.

At the same time, `SELECT * FROM tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX.edgestore WHERE key = <affected_key> BYPASS CACHE;` shows the expected result:
|key|column1|value|
|--|--|--|
|<affected_key>|0xXX|0xXXXXXXXXXXXXXXXX|
|<affected_key>|$|0xXXXXXXXXXXXXXXXXXXXX|
|<affected_key>|0xXXXXXX|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
|<affected_key>|0xXXXX|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
|<affected_key>|0xXXXX|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
|<affected_key>|0xXXXX|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
|<affected_key>|0xXXXX|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
|<affected_key>|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|

That clearly shows the data being available even though the cache says otherwise. To confirm that, here is the output of `SELECT * FROM MUTATION_FRAGMENTS(tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX.edgestore) WHERE key = <affected_key>`:
|key|mutation_source|partition_region|column1|position_weight|metadata|mutation_fragment_kind|value|
|--|--|--|--|--|--|--|--|
|<affected_key>|row-cache|0||null|{"tombstone":{}}|partition start|null|
|<affected_key>|row-cache|3||null|null|partition end|null|
|<affected_key>|sstable:/var/lib/scylla/data/tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX/edgestore-a8a600f010c411ee90302aa2f5097436/me-3gcs_0sim_408wg27cloiofdn8bl-big-Data.db|0||null|{"tombstone":{}}|partition start|null|
|<affected_key>|sstable:/var/lib/scylla/data/tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX/edgestore-a8a600f010c411ee90302aa2f5097436/me-3gcs_0sim_408wg27cloiofdn8bl-big-Data.db|2|0xXX|0|{"marker":{"timestamp":1705313742651345}|"columns":{"value":{"is_live":true,"type":"regular","timestamp":1705313742651345}}}|clustering row|{"value":"XXXXXXXXXXXXXXXX"}|
|<affected_key>|sstable:/var/lib/scylla/data/tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX/edgestore-a8a600f010c411ee90302aa2f5097436/me-3gcs_0sim_408wg27cloiofdn8bl-big-Data.db|2|$|0|{"marker":{"timestamp":1705313742651345}|"columns":{"value":{"is_live":true,"type":"regular","timestamp":1705313742651345}}}|clustering row|{"value":"XXXXXXXXXXXXXXXXXXXX"}|
|<affected_key>|sstable:/var/lib/scylla/data/tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX/edgestore-a8a600f010c411ee90302aa2f5097436/me-3gcs_0sim_408wg27cloiofdn8bl-big-Data.db|2|0xXXXXXX|0|{"marker":{"timestamp":1705313742651345}|"columns":{"value":{"is_live":true,"type":"regular","timestamp":1705313742651345}}}|clustering row|{"value":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}|
|<affected_key>|sstable:/var/lib/scylla/data/tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX/edgestore-a8a600f010c411ee90302aa2f5097436/me-3gcs_0sim_408wg27cloiofdn8bl-big-Data.db|2|0xXXXX|0|{"marker":{"timestamp":1705313742651345}|"columns":{"value":{"is_live":true,"type":"regular","timestamp":1705313742651345}}}|clustering row|{"value":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}|
|<affected_key>|sstable:/var/lib/scylla/data/tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX/edgestore-a8a600f010c411ee90302aa2f5097436/me-3gcs_0sim_408wg27cloiofdn8bl-big-Data.db|2|0xXXXX|0|{"marker":{"timestamp":1705313742651345}|"columns":{"value":{"is_live":true,"type":"regular","timestamp":1705313742651345}}}|clustering row|{"value":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}|
|<affected_key>|sstable:/var/lib/scylla/data/tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX/edgestore-a8a600f010c411ee90302aa2f5097436/me-3gcs_0sim_408wg27cloiofdn8bl-big-Data.db|2|0xXXXX|0|{"marker":{"timestamp":1705313742651345}|"columns":{"value":{"is_live":true,"type":"regular","timestamp":1705313742651345}}}|clustering row|{"value":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}|
|<affected_key>|sstable:/var/lib/scylla/data/tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX/edgestore-a8a600f010c411ee90302aa2f5097436/me-3gcs_0sim_408wg27cloiofdn8bl-big-Data.db|2|0xXXXX|0|{"marker":{"timestamp":1705313742651345}|"columns":{"value":{"is_live":true,"type":"regular","timestamp":1705313742651345}}}|clustering row|{"value":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}|
|<affected_key>|sstable:/var/lib/scylla/data/tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX/edgestore-a8a600f010c411ee90302aa2f5097436/me-3gcs_0sim_408wg27cloiofdn8bl-big-Data.db|2|0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|0|{"marker":{"timestamp":1705313742651345}|"columns":{"value":{"is_live":true,"type":"regular","timestamp":1705313742651345}}}|clustering row|{"value":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}|
|<affected_key>|sstable:/var/lib/scylla/data/tenant_6e10XXXX_XXXX_XXXX_XXXX_XXXXXXXXXXXX/edgestore-a8a600f010c411ee90302aa2f5097436/me-3gcs_0sim_408wg27cloiofdn8bl-big-Data.db|3||null|null|partition end|null|

Does that give you any further insights? Having `null` in the cache looks suspicious to me because if I query an unaffected key, there's either no `row-cache` mutation source at all or it contains the same data as the `sstable`s.

**Comment by michoecho** [comment] 2024-01-16 13:21
> Having null in the cache looks suspicious to me because if I query an unaffected key, there's either no row-cache mutation source at all or it contains the same data as the sstables.

From your outputs, it seems that there is an empty entry in the cache, which is hiding the actual data. That's bad, because the cache is supposed to always be consistent with the sstables.
Unfortunately it's hard to know what went wrong, because we only see the end result. And there were very big changes in cache code between 5.2 and 5.4, too big to guess which one was bad, especially since row cache is the most complicated part of the program.

So if you could provide more info about the circumstances of the bug, it could be a big help.

Please share anything that could be helpful in reproducing the problem, in particular:

1. What kind of deletes are run on the table?
- Partition deletes? (`WHERE key = ?`)
- Row deletes? (`WHERE key = ? AND column1 = ?`)
- Row range deletes? For what kind of ranges? (E.g. `WHERE key = ? AND column1 < ?`, or `WHERE key = ? AND column1 >= ? AND column1 <= ?`)
2. What kind of selects are run on the table?
- Partition selects?
- Row selects?
- Row range selects? For what kind of ranges?
3. Did you set a custom `gc_grace_seconds` or `tombstone_gc` when creating the table?
4. Are you setting any custom TTL or manually setting timestamps in the affected table? (E.g. `INSERT ... USING TTL x` or `INSERT ... USING TIMESTAMP x`)?
5. Do you happen to know if there had been any prior deletions (or TTL expirations) in the affected partition?
6. Do you happen to know how much time passed before the relevant insert and the bad select?
7. Is something uncommon happening around the same time as the bad inserts/selects (e.g. `ALTER TABLE`)?

**Comment by tgrabiec** [comment] 2024-01-17 11:01
The "column1" and "value" resemble thrift-compatibility table layout. Are you using thrift API to create/access this table?

**Comment by michoecho** [comment] 2024-01-17 11:03
> The "column1" and "value" resemble thrift-compatibility table layout. Are you using thrift API to create/access this table?

Actually, I was going to ask a related question, but I forgot about it:
Is the `$` value for `column1` something special? A null (not just an empty string, but null) key, perhaps?

**Comment by rngcntr** [comment] 2024-01-17 11:55
@tgrabiec I'm not accessing the table directly but via JanusGraph which uses Scylla as a storage backend. [`janusgraph-cql`](https://github.com/JanusGraph/janusgraph/tree/master/janusgraph-cql) communicates with Scylla via the [DataStax Java Driver](https://docs.datastax.com/en/developer/java-driver/4.17/manual/core/).

@michoecho It is definitely not a `null`, that looks different. `null` is represented in [this table](https://github.com/scylladb/scylladb/issues/16759#issuecomment-1892023492) by an empty cell. I'd assume `$` has some semantic meaning to JanusGraph but Scylla should be agnostic to that. I can try to investigate this further in case it is relevant to you.

**Comment by rngcntr** [comment] 2024-01-17 13:39
Quick update regarding the `$`: That's just a column with value `0x24` and my IDE interpreted that as an ASCII code. I will update the tables in my earlier comments accordingly

**Comment by rngcntr** [comment] 2024-01-19 13:14
Just in case this helps you narrowing down the search space:
Today I thought it could be worth trying to `INSERT` the same data again and check if that repairs the row cache. It does. So there's at least nothing inherently wrong with the inserted `(key,column1,value)` triplets and the cache does not permanently refuse to store that data.

Repairing the cache works both when using `INSERT [...]` or `INSERT [...] USING TIMESTAMP [...]`.

**Comment by eliransin** [comment] 2024-01-24 09:47
For what it's worth we have this code:
https://github.com/scylladb/scylladb/blob/05643208a860ad1baf3956bbd6689a5debac3930/replica/database.cc#L2009-L2048


This contains at least one path that can cause exactly that:
1. If we get `mutation_reordered_with_truncate_exception` during apply in memory.

if this exception is thrown sporadically or if there was a truncate at some point it can explain this.

**Comment by avikivity** [comment] 2024-01-24 11:55
How long does it take to reproduce? We could try to bisect it.

If you can prepare a standalone reproducer, we could run it, otherwise we could provide you with instructions.

**Comment by rngcntr** [comment] 2024-01-24 12:15
@avikivity I mentioned in the opening post that the issue only occurs at scale. Even then, we have seen spans of multiple days without the issue appearing even once. Since the documentation says that downgrading is not possible, I guess that implies we would have to setup a fresh environment in order to bisect versions. Sadly, we are already struggling with compute resources so replicating the entire environment is barely an option for us.

**Comment by avikivity** [comment] 2024-01-24 18:59
Ah, since it's single-node it's possible to downgrade by editing the system.local table (removing features introduced in 5.4).

**Comment by avikivity** [comment] 2024-01-24 19:56
@michoecho we can try to run the randomized cache tests with a much higher iteration count, maybe it will catch something. Unlikely but it's a low-effort check.

**Comment by rngcntr** [comment] 2024-01-25 06:09
> Since it's a single-node cluster I assumed it's not too large. What's the dataset size?

The dataset size is about 2TB. To replicate the setup, I'd have to clone the entire environment which includes all the clients that generate the workload and make the requests. That's what's beyond our capabilities.

> Ah, since it's single-node it's possible to downgrade by editing the system.local table (removing features introduced in 5.4).

But you would still not recommend it because of possibly buggy intermediate versions is what I read from your earlier comment.

> we can try to run the randomized cache tests with a much higher iteration count

Do these tests use concurrent clients to issue queries? High concurrency and limitation of resources could be key to reproduce the issue. Most of the times I noticed the bug, Scylla was operating at full load, using 100% of its 8 CPUs. However I'm not overly confident this is a necessary condition. One could still argue that the more queries there are in a given time frame, the more likely it is to find one that fails.

**Comment by avikivity** [comment] 2024-01-25 11:59
> > Since it's a single-node cluster I assumed it's not too large. What's the dataset size?
> 
> The dataset size is about 2TB. To replicate the setup, I'd have to clone the entire environment which includes all the clients that generate the workload and make the requests. That's what's beyond our capabilities.

What about replicating at 1/8 scale? To just 1 vcpu (and with 1/8 of the storage, memory, and workload)?


> 
> > Ah, since it's single-node it's possible to downgrade by editing the system.local table (removing features introduced in 5.4).
> 
> But you would still not recommend it because of possibly buggy intermediate versions is what I read from your earlier comment.


Correct. We could do some work to look for fixes beyond a particular commit hash, but it's hard to be sure.

> 
> > we can try to run the randomized cache tests with a much higher iteration count
> 
> Do these tests use concurrent clients to issue queries? 

At least some do. I have low confidence that we'll see the same failures though.

> High concurrency and limitation of resources could be key to reproduce the issue. Most of the times I noticed the bug, Scylla was operating at full load, using 100% of its 8 CPUs. 

This doesn't mean much. With a moderate write load it will use spare CPU to compact. You can see that in the advanced dashboard under CPU time, compaction.

> However I'm not overly confident this is a necessary condition. One could still argue that the more queries there are in a given time frame, the more likely it is to find one that fails.

Right.

Yet another option: cook up a version that verifies every read with the equivalent of BYPASS CACHE, and then dumps core on a discrepancy.

This requires:
 - your system can sustain the query rate with BYPASS CACHE (can be tested by disabling the cache temporarily; and perhaps you can enlarge it temporarily)
 - you're okay with a crash and some downtime when the bug is detected; no risk to data
 - you're okay with giving us the core dump (we can sign an NDA) to analyze

**Comment by rngcntr** [comment] 2024-01-25 15:25
> What about replicating at 1/8 scale? To just 1 vcpu (and with 1/8 of the storage, memory, and workload)?

That sounds more reasonable, but since we currently expect the issue to come up just by chance, wouldn't that be a huge disadvantage for bisecting? At the current throughput, it would take at least two, better three days without an error to state with reasonable confidence that a version is not affected by the bug. Scaled by 1/8th that would give us something in the range of ~3 weeks for one iteration of git bisect. And there are around 2^12 commits to be bisected. Let alone that reducing the load could still make the error less likely due to reduced concurrency.

> This doesn't mean much. With a moderate write load it will use spare CPU to compact. You can see that in the advanced dashboard under CPU time, compaction.

The panel you mentioned varies between 5% and 25% of time spent on compaction. I also built a panel that shows the load distribution between groups:
![image](https://github.com/scylladb/scylladb/assets/7890887/25c666e5-68ac-4e37-90e0-d0455a9371d4)

> Yet another option: cook up a version that verifies every read with the equivalent of BYPASS CACHE, and then dumps core on a discrepancy.

I can try this tomorrow, but I expect a significant decrease of throughput, given that Scylla already utilizes the disk quite a bit:
![image](https://github.com/scylladb/scylladb/assets/7890887/468d75f7-8b40-4cbb-b47f-5b7677ae410a)

**Comment by rngcntr** [comment] 2024-01-26 05:55
> can be tested by disabling the cache temporarily

How would I even do that? The first thing I could find in the [docs](https://opensource.docs.scylladb.com/stable/faq.html#do-i-ever-need-to-disable-the-scylla-cache-to-use-less-memory) is that it's impossible to disable the cache.

**Comment by tgrabiec** [comment] 2024-01-26 09:38
> > can be tested by disabling the cache temporarily
> 
> How would I even do that? The first thing I could find in the [docs](https://opensource.docs.scylladb.com/stable/faq.html#do-i-ever-need-to-disable-the-scylla-cache-to-use-less-memory) is that it's impossible to disable the cache.

It is actually possible to disable cache per node for all requests via config param. In scylla.yaml that's `enable_cache: false`. It requires node restart to take effect.

**Comment by mykaul** [comment] 2024-01-28 10:20
@michoecho - could this be solved by https://github.com/scylladb/scylladb/commit/938b993331e9143a6ff6967b1321274ab40bc1cc ?

**Comment by michoecho** [comment] 2024-01-28 10:31
> @michoecho - could this be solved by [938b993](https://github.com/scylladb/scylladb/commit/938b993331e9143a6ff6967b1321274ab40bc1cc) ?

I don't think so, although I have no proof.

**Comment by avikivity** [comment] 2024-01-28 18:14
> > can be tested by disabling the cache temporarily
> 
> How would I even do that? The first thing I could find in the [docs](https://opensource.docs.scylladb.com/stable/faq.html#do-i-ever-need-to-disable-the-scylla-cache-to-use-less-memory) is that it's impossible to disable the cache.

There's `enable_cache` config item, `WITH caching = {'enabled': 'false'}`  clause for ALTER TABLE, and `BYPASS CACHE` for individual queries.

**Comment by avikivity** [comment] 2024-01-28 18:14
> > @michoecho - could this be solved by [938b993](https://github.com/scylladb/scylladb/commit/938b993331e9143a6ff6967b1321274ab40bc1cc) ?
> 
> I don't think so, although I have no proof.

It's worth trying.

**Comment by avikivity** [comment] 2024-01-28 18:20
> > What about replicating at 1/8 scale? To just 1 vcpu (and with 1/8 of the storage, memory, and workload)?
> 
> That sounds more reasonable, but since we currently expect the issue to come up just by chance, wouldn't that be a huge disadvantage for bisecting? At the current throughput, it would take at least two, better three days without an error to state with reasonable confidence that a version is not affected by the bug. Scaled by 1/8th that would give us something in the range of ~3 weeks for one iteration of git bisect. And there are around 2^12 commits to be bisected. Let alone that reducing the load could still make the error less likely due to reduced concurrency.


Per-shard the concurrency would remain unchanged (1/8 the workload but also 1/8 the cpu power to process it). It's actually incorrect that there's 1/8 the cpu power, since with hyperthreading a single vcpu has ~80% the power of two vcpus.

What we could do is scale down the workload less than we scale the database. That should increase concurrency. We can also reduce the amount of cache to increase pressure on it.

**Comment by rngcntr** [comment] 2024-02-01 06:59
So far, I had no success trying to reproduce the issue in small scale. I've set up a minimalistic docker compose using ScyllaDB, JanusGraph and a JanusGraph client that sends queries similar to the ones we perform in our production environment. But maybe I just wasn't patient enough. That being said, it looks like @michoecho was indeed successful! Does your reproducer enable you to bisect the issue?

Meanwhile, we noticed the bug also appear in another cluster which we previously assumed to be unaffected. The circumstances here are a little bit different, as it is a three node cluster with 64 cores/512G Mem/8TB SSD per node, running ScyllaDB v5.4.0. In four weeks of operation, the bug has only occurred once. That, however, confirms that it also occurs in multi-node setups.

**Comment by michoecho** [comment] 2024-02-01 09:56
> That being said, it looks like @michoecho was indeed successful! Does your reproducer enable you to bisect the issue?

I didn't try bisecting yet. I didn't have the time yesterday (and likely today), and I'll probably go back to the investigation tomorrow.

I don't have high hopes for the bisect, because the cache (and its readers) was switched to a new data structure in 5.4, and I think there's a 99% chance the bisect is just going to point to the commit which does the switch (i.e. https://github.com/scylladb/scylladb/commit/b41df53781795f805d3c112f56a3245d5c84c3ce), so it won't narrow the problem down enough. (Though of course it's worth trying a bisect anyway).

I think I'm going to debug it by logging all modifications to the cache structure, and then reviewing the log for the partition which failed. This should be enough to point at which modification was the illegal one.

But anyway, now that I can reproduce it locally, it should only be a matter of time before I figure it out.

**Closed** 2024-02-04 12:28 UTC
Labels: symptom/data consistency, P1, status/release blocker, backport/5.2, backport/5.4

**Comment by avikivity** [comment] 2024-02-04 13:06
Backported to 5.2, 5.4.

**Comment by nuivall** [comment] 2024-02-04 15:29
@avikivity would it be worth to cover also 2022.2 potentially for https://github.com/scylladb/scylla-enterprise/issues/3767?

**Comment by avikivity** [comment] 2024-02-04 15:53
We don't discuss Enterprise issues on this tracker.

**Comment by michoecho** [comment] 2024-02-05 10:44
@rngcntr A fix for the bug has been merged, so it should be fixed in the next patch release.

It turned out that this bug has been introduced not in 5.4, but way back in 2020.

When a memtable is flushed into an sstable, the cache has to brought up to date. This is done over several seconds — partition entries are incrementally moved/merged from memtable into the cache, in token order. While this is happening, reads from already-processed partitions source the new sstable, while reads from yet-unprocessed partitions source the memtable.

As it turns out, the variable which tracks the boundary between already-processed and yet-unprocessed partitions wasn't updated in some circumstances (when the async preemption happened in the right place), which caused some already-processed partitions to use the memtable (which doesn't have their data anymore) instead of the new sstable. Which resulted in the reads not returning the data from the latest memtable, and that's what you saw.

It wasn't noticed for so long presumably because in most use cases it's hidden by replication/reconciliation. It isn't that hard to hit the bug on a single node, but it's probably very hard to hit it for the same partitions on two/three nodes at the same time. And as long as at least one queried replica returns the newest data, it will be returned to the client.

Thanks a lot for your help. Without it, who knows how for much more time this bug could have survived.

**Comment by rngcntr** [comment] 2024-02-06 06:49
@michoecho I am very pleased to read that you not only found the culprit but also sorted it out. Great job! I'm now looking forward to testing the next patch release and report back if the problem has been solved.
Do you think it's plausible the bug did not show up in earlier releases because even though it existed, it was covered up by something else? Just asking because for us, the issue dates back exactly to the day of the rollout of 5.4

**Comment by michoecho** [comment] 2024-02-06 11:04
> @michoecho I am very pleased to read that you not only found the culprit but also sorted it out. Great job! I'm now looking forward to testing the next patch release and report back if the problem has been solved. Do you think it's plausible the bug did not show up in earlier releases because even though it existed, it was covered up by something else? Just asking because for us, the issue dates back exactly to the day of the rollout of 5.4

No, I can't think of any solid reason why it would show up in 5.4 but not earlier. I can reproduce it with earlier versions just as well as with 5.4.

But it could just be a coincidence. E.g. maybe the new version changed some timings significantly, making it easier to hit the race with your hardware and workload.

(And of course there's always the dreadful possibility that there exist two different bugs with the same symptoms and the one I found is different than the one you found. I hope not.)

**Comment by rngcntr** [comment] 2024-03-14 09:29
> (And of course there's always the dreadful possibility that there exist two different bugs with the same symptoms and the one I found is different than the one you found. I hope not.)

Just reporting that we've been running on the latest ScyllaDB version for a few weeks now and the issue didn't occur anymore since we updated. Great work!

**Comment by mykaul** [comment] 2024-03-14 09:48
Thanks for the confirmation @rngcntr !  Very useful input.
