### ISSUE TITLE
2i (based on MV) creation works differently than in C*, as it does not inherit the compaction strategy value (and maybe other properties)

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylladb#3283] opened 2018-03-14 07:37 UTC
*Installation details*
Scylla version (or git commit hash): 2.1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

2i (based on MV) creation works differently than in C*, as it does not inherit the compaction strategy value (and maybe other properties).

As result when the base table compaction strategy is non-default (not STCS), the 2i (MV) will not inherit that property and you will need to manually change the MV using ```ALTER``` command.
See ticket #3284  for ```ALTER MV``` issue.

Taken from [DSE docs](https://www.datastax.com/dev/blog/cassandra-native-secondary-index-deep-dive):

> An interesting details to know is that the compaction strategy of the secondary index table inherits from the one chosen for the base table.

```
CREATE KEYSPACE direct_ts WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TABLE direct_ts.data_points (
    rack_id text,
    sensor_id text,
    curr_epoch timestamp,
    value int,
    PRIMARY KEY ((rack_id, sensor_id), curr_epoch)
) WITH CLUSTERING ORDER BY (curr_epoch DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'TieWindowCompactionStrategy', 'compaction_window_size': '60', 'compaction_window_unit': 'MINUTES'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE INDEX data_points_curr_epoch_idx ON direct_ts.data_points (curr_epoch);
CREATE INDEX data_points_value_idx ON direct_ts.data_points (value);

CREATE MATERIALIZED VIEW direct_ts.data_points_curr_epoch_idx_index AS
    SELECT curr_epoch, rack_id, sensor_id
    FROM direct_ts.data_points
    WHERE curr_epoch IS NOT NULL
    PRIMARY KEY (curr_epoch, rack_id, sensor_id)
    WITH CLUSTERING ORDER BY (rack_id ASC, sensor_id ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW direct_ts.data_points_value_idx_index AS
    SELECT value, rack_id, sensor_id, curr_epoch
    FROM direct_ts.data_points
    WHERE value IS NOT NULL
    PRIMARY KEY (value, rack_id, sensor_id, curr_epoch)
    WITH CLUSTERING ORDER BY (rack_id ASC, sensor_id ASC, curr_epoch DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

**Comment by tzach** [comment] 2018-03-14 12:27
> An interesting details to know is that the compaction strategy of the secondary index table inherits from the one chosen for the base table.

This is true for Apache Cassandra sec index, not for Apache Cassandra MV. Scylla  Sec Index is based on MV, so are similar to the second.
With a different partition key and a data pattern of the MV table, I'm not sure the same compaction strategy as the base table always makes sense.

**Comment by vladzcloudius** [comment] 2020-02-03 20:45
@slivne @eliransin What's the status of this bug?
If we think that it's a non-issue - let's close it.

**Comment by vladzcloudius** [comment] 2020-02-12 23:46
@eliransin ping

**Comment by raphaelsc** [comment] 2022-07-19 14:52
IMO it doesn't make sense to inherit the strategy blindly as the base table strategy may be a poor choice for the read-modify-write nature of MV.

**Comment by raphaelsc** [comment] 2022-07-20 12:41
> What is the default compaction strategy for a Sec Index (or `MV`)? as of 2021.1 (maybe even 2020.1) when creating a (base) table the default is `ICS`, while in Scylla OSS the default is still `STCS` (ICS being an Ent feature only). If `ICS` was used for the `base` table, doesn't it make sense that the sec index (or `MV`) should also have `ICS`?
> 
> IIRC @vladzcloudius suggested recently to make the `SAG` option also a default, so that's another attribute we need to consider whether the `MV` / Sec Index should/not inherit from the base table.
> 
> @raphaelsc I understand your point if the user made a poor choice, but what if he didn't and made a correct choice, and he is expecting that choice to propagate to the `MV` / Sec Index? It's more a matter of perception by the user.
> 

For example, let's say user picks TWCS for base table. If we inherit that in MV table, then we'll have read latency issues as TWCS doesn't handle well deletions. So TWCS (in its current state) will never be a good choice for MV. We pick default strategy which is STCS in OSS and ICS in ent, but the user can override that at any time of the day. Sure, we need to update our docs if we're deviating from the behavior in C*.

**Comment by vladzcloudius** [comment] 2022-07-21 21:45
@tomer-sandler It only makes sense to "inherit" a compaction strategy when it's ICS ;)

Another way to put it: MVs should always use ICS and this is the case today on Enterprise.

OSS is quite doomed in this regard since the only option it has to handle MVs tombstones accumulation is running periodic majors or using LCS.

On Ent starting from 2021.1.9 ICSes tombstone compaction, which is enabled by default, is even a stronger tool than SAG. Therefore there is no need to enable SAG even.

IMO this issue should be closed.

**Comment by kostja** [comment] 2024-05-02 21:01
We use ICS in the enterprise by default, and for the OSS it's a duplicate of https://github.com/scylladb/scylladb/issues/8639

**Closed** 2024-05-02 21:01 UTC
Labels: type/bug, area/sec index
