### ISSUE TITLE
k8s test: aborting on shard when no space left on device

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#11241] opened 2022-08-08 15:14 UTC
## Installation details

Kernel Version: 5.4.204-113.362.amzn2.x86_64
Scylla version (or git commit hash): `5.1.0~dev-20220802.663f2e2a8f81` with build-id `d6f523279872624d89a9a451f02d8276f0073cb5`
Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: eu-north-1)

Test: `longevity-scylla-operator-basic-12h-eks`
Test id: `5007b4d2-897c-4948-9822-912e150a945b`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-basic-12h-eks`
Test config file(s):

- [longevity-scylla-operator-basic-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5eb7e7241a351a35cd9c1756cd43cc329cb5a873/test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml)

## Issue description

Ran `NodetoolEnospc` nemesis (occupy 90% space on the node) on the node sct-cluster-us-east1-b-us-east1-2 [10.0.3.82 | 10.0.0.158]
```
< t:2022-08-07 04:33:52,540 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-08-07 04:33:52.539: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=d53dacc0-5e51-4c06-a928-52a348cb
01fb: nemesis_name=NodetoolEnospc target_node=Node sct-cluster-us-east1-b-us-east1-2 [10.0.3.82 | 10.0.0.158] (seed: False)
```

Memtable flush failed due to storage_io_error:
```
ERROR 2022-08-07 04:34:33,036 [shard 12] table - Memtable flush failed due to: storage_io_error (Storage I/O error: 28: filesystem error: mkdir failed: No space left on device [/var/lib/scylla/data/system/peers-
37f71aca7dc2383ba70672528af04d4f/306.sstable]). Aborting, at 0x4fa031e 0x4fa0810 0x4fa0b18 0x130df76 0x13831e0 0x4c165d4 0x4c179b7 0x4c36a05 0x4bea37a /opt/scylladb/libreloc/libpthread.so.0+0x92a4 /opt/scylladb/
libreloc/libc.so.6+0x100322
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::handle_exception<dirty_memory_manager::flush_one(replica::memtable_list&, flush_permit&&)::$_46>(dirty_memory_mana
ger::flush_one(replica::memtable_list&, flush_permit&&)::$_46&&)::{lambda(auto:1&&)#1}, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::future<void>::handle_exception<dirty_memory_manager::flush_one(replica::memtable_list&, flush_permit&&)::$_46>(dirty_memory_manager::flush_one(replica::memtable_list&, flush_permit&&)::$_46&&)::{lambda(auto:1&&)#1}>(seastar::future<void>::handle_exception<dirty_memory_manager::flush_one(replica::memtable_list&, flush_permit&&)::$_46>(dirty_memory_manager::flush_one(replica::memtable_list&, flush_permit&&)::$_46&&)::{lambda(auto:1&&)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::handle_exception<dirty_memory_manager::flush_one(replica::memtable_list&, flush_permit&&)::$_46>(auto:1&&)::{lambda(auto:1&&)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<replica::memtable_list::flush()::$_45::operator()<flush_permit>(flush_permit) const::{lambda()#1}, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::future<void>::finally_body<replica::memtable_list::flush()::$_45::operator()<flush_permit>(flush_permit) const::{lambda()#1}, false> >(seastar::future<void>::finally_body<replica::memtable_list::flush()::$_45::operator()<flush_permit>(flush_permit) const::{lambda()#1}, false>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::finally_body<replica::memtable_list::flush()::$_45::operator()<flush_permit>(auto:1) const::{lambda()#1}, false>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::shared_future<>::shared_state::get_future(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(seastar::future<void>&&)#1}, seastar::future<void>::then_wrapped_nrvo<void, seastar::shared_future<>::shared_state::get_future(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(seastar::future<void>&&)#1}>(seastar::shared_future<>::shared_state::get_future(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(seastar::future<void>&&)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::shared_future<>::shared_state::get_future(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda(seastar::future<void>&&)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
```

And then aborting on shard:
```
WARN  2022-08-07 04:34:33,037 [shard  1] storage_proxy - Failed to apply mutation from 172.20.229.184#1: seastar::abort_requested_exception (abort requested)
WARN  2022-08-07 04:34:33,037 [shard  3] storage_proxy - Failed to apply mutation from 172.20.229.184#3: seastar::abort_requested_exception (abort requested)
Aborting on shard 12.
Backtrace:
0x4c06e48
0x4c36552
0x7f44353d9a1f
/opt/scylladb/libreloc/libc.so.6+0x3d2a1
/opt/scylladb/libreloc/libc.so.6+0x268a3
0x130dfb0
0x13831e0
0x4c165d4
0x4c179b7
0x4c36a05
0x4bea37a
/opt/scylladb/libreloc/libpthread.so.0+0x92a4
/opt/scylladb/libreloc/libc.so.6+0x100322
```

Decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:760
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:790
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:802
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3672
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3648
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3644
?? ??:0
/data/scylla-s3-reloc.cache/by-build-id/d6f523279872624d89a9a451f02d8276f0073cb5/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x3d2a1 
/data/scylla-s3-reloc.cache/by-build-id/d6f523279872624d89a9a451f02d8276f0073cb5/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x268a3 
operator() at ./replica/table.cc:610
replica::table::seal_active_memtable(flush_permit&&)::$_49::operator()(std::function<seastar::future<void> ()>) const [clone .resume] at table.cc:?
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2345
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2752
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2921
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4145
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
/data/scylla-s3-reloc.cache/by-build-id/d6f523279872624d89a9a451f02d8276f0073cb5/extracted/scylla/libexec/scylladb/libreloc/libpthread.so.0 0x92a4 
/data/scylla-s3-reloc.cache/by-build-id/d6f523279872624d89a9a451f02d8276f0073cb5/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x100322 
```

No coredump

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5007b4d2-897c-4948-9822-912e150a945b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5007b4d2-897c-4948-9822-912e150a945b)
- Show all stored logs command: `$ hydra investigate show-logs 5007b4d2-897c-4948-9822-912e150a945b`

## Logs:
- **db-cluster-5007b4d2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5007b4d2-897c-4948-9822-912e150a945b/20220807_122955/db-cluster-5007b4d2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5007b4d2-897c-4948-9822-912e150a945b/20220807_122955/db-cluster-5007b4d2.tar.gz)
- **monitor-set-5007b4d2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5007b4d2-897c-4948-9822-912e150a945b/20220807_122955/monitor-set-5007b4d2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5007b4d2-897c-4948-9822-912e150a945b/20220807_122955/monitor-set-5007b4d2.tar.gz)
- **loader-set-5007b4d2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5007b4d2-897c-4948-9822-912e150a945b/20220807_122955/loader-set-5007b4d2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5007b4d2-897c-4948-9822-912e150a945b/20220807_122955/loader-set-5007b4d2.tar.gz)
- **sct-runner-5007b4d2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5007b4d2-897c-4948-9822-912e150a945b/20220807_122955/sct-runner-5007b4d2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5007b4d2-897c-4948-9822-912e150a945b/20220807_122955/sct-runner-5007b4d2.tar.gz)
- **kubernetes-5007b4d2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5007b4d2-897c-4948-9822-912e150a945b/20220807_122955/kubernetes-5007b4d2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5007b4d2-897c-4948-9822-912e150a945b/20220807_122955/kubernetes-5007b4d2.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-basic-12h-eks/19/)

**Comment by slivne** [comment] 2022-08-11 07:42
this seems a duplicate - there is a change on memetable flush failing - I think we ave seen this - right @fgelcer / @bhalevy 

@bhalevy if its the same as another issue please reference and close

**Comment by bhalevy** [comment] 2022-08-11 07:57
Duplicate of https://github.com/scylladb/scylladb/issues/11245

**Closed by bhalevy** 2022-08-11 07:57 UTC
