### ISSUE TITLE
(legacy) nodetool help -> crash - java.lang.NoSuchMethodError: 'java.lang.Object com.google.common.base.Objects.firstNonNull(java.lang.Object, java.lang.Object)

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#16679] opened 2024-01-08 08:24 UTC
From https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/464/artifact/logs-full.release.012/dtest-gw2.log :
```
>               raise NodetoolError(" ".join(nodetool), exit_status, stdout, stderr)
E               ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/61395a3658acbe786928090913b047373cea21fa/share/cassandra/bin/nodetool -h 127.0.60.1 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy help exited with non-zero status; exit status: 2; 
E               stderr: error: 'java.lang.Object com.google.common.base.Objects.firstNonNull(java.lang.Object, java.lang.Object)'
E               -- StackTrace --
E               java.lang.NoSuchMethodError: 'java.lang.Object com.google.common.base.Objects.firstNonNull(java.lang.Object, java.lang.Object)'
E               	at io.airlift.command.GlobalUsageSummary$2.apply(GlobalUsageSummary.java:100)
E               	at io.airlift.command.GlobalUsageSummary$2.apply(GlobalUsageSummary.java:97)
E               	at com.google.common.collect.Iterators$6.transform(Iterators.java:829)
E               	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
E               	at io.airlift.command.UsagePrinter.appendTable(UsagePrinter.java:57)
E               	at io.airlift.command.GlobalUsageSummary.usage(GlobalUsageSummary.java:96)
E               	at io.airlift.command.GlobalUsageSummary.usage(GlobalUsageSummary.java:52)
E               	at io.airlift.command.Help.help(Help.java:57)
E               	at io.airlift.command.Help.help(Help.java:50)
E               	at io.airlift.command.Help.run(Help.java:25)
E               	at org.apache.cassandra.tools.NodeTool$CassHelp.run(NodeTool.java:257)
E               	at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:196)
E               	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:62)
```

I wonder if it's a recent regression, has to do with Java or some CCM issue.

Test is https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/464/artifact/logs-full.release.012/1704670906368_rolling_upgrade_test.py%3A%3ATestRollingUpgrade%3A%3Atest_rolling_upgrade/

**Comment by mykaul** [comment] 2024-01-08 08:30
@denesb - what's unclear to me is why wasn't the native nodetool launched, as help should be supported - the version is:
 ```INFO  2024-01-07 23:41:30,817 [shard 0:main] init - Scylla version 5.5.0~dev-0.20240107.61395a3658ac with build-id b5931bda78dc22ba021f7f3e812cbc72166480a5 starting ...```

I've opened https://github.com/scylladb/scylla-ccm/issues/547 to see if it may be a CCM issue not calling the wrapper properly (though I don't expect a crash from the legacy nodetool either).
Worth understanding if we regressed and/or which Java version is installed there.

**Comment by mykaul** [comment] 2024-01-08 12:32
@denesb - Avi raised an interesting point - even if you did implement 'help', then the call should be unconditionally redirected to the Java one, otherwise you'll show just partial (the currently implemented) content, no?

**Comment by denesb** [comment] 2024-01-08 13:09
> @denesb - Avi raised an interesting point - even if you did implement 'help', then the call should be unconditionally redirected to the Java one, otherwise you'll show just partial (the currently implemented) content, no?

Yes, I also raised this on https://github.com/scylladb/scylladb/issues/16622. I will send a patch soon.

**Comment by denesb** [comment] 2024-01-09 08:40
Looks like `nodetool help` (the java one) is crashing indeed. I reproduced on my local machine too. No idea why.

**Comment by denesb** [comment] 2024-01-09 08:42
> E               ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/61395a3658acbe786928090913b047373cea21fa/share/cassandra/bin/nodetool -h 127.0.60.1 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy help exited with non-zero status; exit status: 2; 

The reason this was not routed to `scylla-nodetool` is that the `nodetool-wrapper` script uses `$1` do decide whether `scylla-nodetool` has implemented to command or not. In this case `$1` is `-h`, so this check will fail, even though the real command here is `help`. To work around cases like this, we'd need to implement an arg parser in the scrip. IMO it is just not worth it. The simple check should work in most cases.

**Comment by fruch** [comment] 2024-01-09 09:10
> > E               ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/61395a3658acbe786928090913b047373cea21fa/share/cassandra/bin/nodetool -h 127.0.60.1 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy help exited with non-zero status; exit status: 2; 
> 
> The reason this was not routed to `scylla-nodetool` is that the `nodetool-wrapper` script uses `$1` do decide whether `scylla-nodetool` has implemented to command or not. In this case `$1` is `-h`, so this check will fail, even though the real command here is `help`. To work around cases like this, we'd need to implement an arg parser in the scrip. IMO it is just not worth it. The simple check should work in most cases.

I thought that it's just the help command that doesn't work

It's still a common practice to check the help for some command existence, and it can break users automation, as it breaks some small parts of ours.

I can stop checking the help, and just assume this command exists

**Comment by fruch** [comment] 2024-01-09 09:14
> > E               ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/61395a3658acbe786928090913b047373cea21fa/share/cassandra/bin/nodetool -h 127.0.60.1 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy help exited with non-zero status; exit status: 2; 
> 
> The reason this was not routed to `scylla-nodetool` is that the `nodetool-wrapper` script uses `$1` do decide whether `scylla-nodetool` has implemented to command or not. In this case `$1` is `-h`, so this check will fail, even though the real command here is `help`. To work around cases like this, we'd need to implement an arg parser in the scrip. IMO it is just not worth it. The simple check should work in most cases.

This is how CCM is doing the call by default
(And probably other tools like SCT as well)

**Comment by denesb** [comment] 2024-01-09 09:37
> This is how CCM is doing the call by default
> (And probably other tools like SCT as well)

I see. This will require some further patches than. For one, we must teach `scylla-nodetool` to ignore `-Dxxxx` arguments. Currently, it would choke on it.

**Comment by mykaul** [comment] 2024-01-09 09:47
```-Dcom.sun.jndi.rmiURLParsing=legacy``` that CCM is using is quite ugly and should have been in a wrapper script in the 1st place.

**Comment by denesb** [comment] 2024-01-09 11:58
Opened https://github.com/scylladb/scylladb/issues/16695 and https://github.com/scylladb/scylladb/issues/16696 for the two new issues I discovered why looking at this.

**Comment by denesb** [comment] 2024-01-09 13:19
> `-Dcom.sun.jndi.rmiURLParsing=legacy` that CCM is using is quite ugly and should have been in a wrapper script in the 1st place.

Yes, but it is a good reminder that other user scripts using nodetool might have similar options and `scylla-sstable` has to just swallow these.

**Comment by denesb** [comment] 2024-05-14 12:38
The wrapper script is now gone and the native nodetool is feature complete. Closing this.

**Closed by denesb** 2024-05-14 12:38 UTC
Labels: area/nodetool, symptom/ci stability
