### ISSUE TITLE
`ttl_test.TestDistributedTTL.test_ttl_is_respected_on_repair` dtest is flaky

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#11947] opened 2022-11-10 14:26 UTC
Failure observed in CI runs (there may be more):

https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2947/
https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2948/

With:
```
E   cassandra.Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl ONE. Requires 1, alive 0" info={'consistency': 'ONE', 'required_replicas': 1, 'alive_replicas': 0}
```

Here's a part of the test:
```
        session2 = self.patient_exclusive_cql_connection(self.node2)
        session2.execute("USE ks;")
        assert_unavailable(session2.execute, "SELECT * FROM ttl_table;")
        self.node1.start(wait_for_binary_proto=True)
        self.session1 = self.patient_exclusive_cql_connection(self.node1)
        self.session1.execute("USE ks;")
        self.session1.execute("""
            ALTER KEYSPACE ks WITH REPLICATION =
            {'class' : 'SimpleStrategy', 'replication_factor' : 2};
        """)
        self.node1.repair(['ks'])
        ttl_start = time.time()
        ttl_session1 = self.session1.execute('SELECT ttl(col1) FROM ttl_table;')
        self.node1.stop()
    
>       assert_row_count(session2, 'ttl_table', 1)
```

so the situation is: we have 2 nodes, we have a CQL connection to node2, node1 is dead.
We have a keyspace with RF=2 and a table in this keyspace.
We try to make a CL=ONE `count(*)` query from this table using the node2 CQL connection.

The query fails. ScyllaDB claims that there are 0 alive replicas.

But that's not true: node2 is a live replica. And this is the node which we try to execute the query on, with a CQL connection directly with this node. This query should definitely succeed.

When I saw this is a `count(*)` query, I immediately thought about our latest query distribution optimization (https://github.com/scylladb/scylladb/pull/9209). Could it be we try to distribute the query for coordination to the dead node?

**Comment by havaker** [comment] 2022-11-10 17:09
> When I saw this is a `count(*)` query, I immediately thought about our latest query distribution optimization (https://github.com/scylladb/scylladb/pull/9209). Could it be we try to distribute the query for coordination to the dead node?

The node which originally received `count(*)` query (the dispatcher) splits it into subqueries and sends it to other nodes for execution. If a send fails, the dispatcher retries the execution of a subquery locally (https://github.com/scylladb/scylladb/pull/10329). There is even a [dtest](https://github.com/scylladb/scylla-dtest/blob/054c102ac70527a2b4c3bee8335a24113196091e/cql_tests.py#L647-L649) that checks this retrying functionality (I've touched it in https://github.com/scylladb/scylla-dtest/pull/2645). So I don't really see how the query distribution layer could be the source of this problem.

Something may have changed since I was working with this code though, @Jadw1 could you have a look/confirm?

**Comment by Jadw1** [comment] 2022-11-17 15:30
There is already an issue about this test https://github.com/scylladb/scylladb/issues/11684. 
I've checked this test locally and it every time I've run it, it was ok. I'm going to add some debugging logs and enable them, so next time when the build will fail, there should be information if this is caused by distributed aggregates.

> The node which originally received `count(*)` query (the dispatcher) splits it into subqueries and sends it to other nodes for execution. If a send fails, the dispatcher retries the execution of a subquery locally (#10329). There is even a [dtest](https://github.com/scylladb/scylla-dtest/blob/054c102ac70527a2b4c3bee8335a24113196091e/cql_tests.py#L647-L649) that checks this retrying functionality (I've touched it in [scylladb/scylla-dtest#2645](https://github.com/scylladb/scylla-dtest/pull/2645)). So I don't really see how the query distribution layer could be the source of this problem.

and I didn't change that logic.

**Comment by nyh** [comment] 2023-02-09 16:23
Closing as a duplicate of https://github.com/scylladb/scylladb/issues/11684.

**Closed by nyh** 2023-02-09 16:23 UTC
