### ISSUE TITLE
nodetool cleanup takes several times longer on a specific node compared to another

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylladb#11566] opened 2022-09-18 10:30 UTC
## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `2022.2.0~rc1-20220902.a9bc6d191031` with build-id `074a0cb9e6a5ab36ba5e7f81385e68079ab6eeda`

Cluster size: 5 nodes (i3en.3xlarge)

Scylla Nodes used in this run:
- longevity-tls-2tb-48h-1dis-2nondis--db-node-310c42b4-6 (54.75.104.172 | 10.4.2.203) (shards: 10)
- longevity-tls-2tb-48h-1dis-2nondis--db-node-310c42b4-5 (54.75.118.167 | 10.4.3.84) (shards: 10)
- longevity-tls-2tb-48h-1dis-2nondis--db-node-310c42b4-4 (54.247.61.225 | 10.4.1.73) (shards: 10)
- longevity-tls-2tb-48h-1dis-2nondis--db-node-310c42b4-3 (34.245.94.48 | 10.4.3.151) (shards: 10)
- longevity-tls-2tb-48h-1dis-2nondis--db-node-310c42b4-2 (34.241.106.173 | 10.4.3.66) (shards: 10)
- longevity-tls-2tb-48h-1dis-2nondis--db-node-310c42b4-1 (34.254.225.226 | 10.4.3.119) (shards: 10)

OS / Image: `ami-03d21402486bbce67` (aws: eu-west-1)

Test: `longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test`
Test id: `310c42b4-c7be-4d91-af5d-74981aac2905`
Test name: `enterprise-2022.2/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test`
Test config file(s):

- [longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/abeb03c8e24f5e8a1121fcc9c2fd871368b61c5c/test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml)

## Issue description

At `2022-09-12 16:17:10.494` a RemoveNodeThenAddNode nemesis has started on node 1. As part of the nemesis, after the new node (node 6) was added in place of the removed one, we execute `nodetool cleanup` on each node for each non system keyspace.
For node 2, each cleanup took 1.5~2.5 hours:
```
< t:2022-09-12 19:44:10,939 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  cleanup mview"...
< t:2022-09-12 21:21:22,151 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  cleanup mview" finished with status 0
< t:2022-09-12 21:21:22,151 f:cluster.py      l:2529 c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-2tb-48h-1dis-2nondis--db-node-310c42b4-2 [34.241.106.173 | 10.4.3.66] (seed: True): Command '/usr/bin/nodetool -u cassandra -pw 'cassandra'  cleanup mview' duration -> 5831.212122262004 s
```
```
< t:2022-09-12 21:21:22,152 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  cleanup keyspace1"...
< t:2022-09-12 23:49:51,517 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  cleanup keyspace1" finished with status 0
< t:2022-09-12 23:49:51,517 f:cluster.py      l:2529 c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-2tb-48h-1dis-2nondis--db-node-310c42b4-2 [34.241.106.173 | 10.4.3.66] (seed: True): Command '/usr/bin/nodetool -u cassandra -pw 'cassandra'  cleanup keyspace1' duration -> 8909.364292721002 s
```
In node 3, however, it took several times more, so much so that the second cleanup didn't get to end before the run was over:
```
< t:2022-09-12 23:49:51,518 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  cleanup mview"...
< t:2022-09-13 08:57:06,719 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  cleanup mview" finished with status 0
< t:2022-09-13 08:57:06,719 f:cluster.py      l:2529 c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-2tb-48h-1dis-2nondis--db-node-310c42b4-3 [34.245.94.48 | 10.4.3.151] (seed: True): Command '/usr/bin/nodetool -u cassandra -pw 'cassandra'  cleanup mview' duration -> 32835.20102806701 s
```
```
< t:2022-09-13 08:57:06,720 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  cleanup keyspace1"...
```
Comparing the cleanup of mview alone the time for the cleanup of node 3 was over 5.5 the time it took for node 2.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 310c42b4-c7be-4d91-af5d-74981aac2905`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=310c42b4-c7be-4d91-af5d-74981aac2905)
- Show all stored logs command: `$ hydra investigate show-logs 310c42b4-c7be-4d91-af5d-74981aac2905`

## Logs:
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/310c42b4-c7be-4d91-af5d-74981aac2905/20220913_155540/db-cluster-310c42b4.tar.gz 
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/310c42b4-c7be-4d91-af5d-74981aac2905/20220913_155540/loader-set-310c42b4.tar.gz 
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/310c42b4-c7be-4d91-af5d-74981aac2905/20220913_155540/monitor-set-310c42b4.tar.gz
sct - https://cloudius-jenkins-test.s3.amazonaws.com/310c42b4-c7be-4d91-af5d-74981aac2905/20220913_155540/sct-runner-310c42b4.tar.gz 

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test/4/)

## Related issue: https://github.com/scylladb/scylladb/issues/10060

**Comment by DoronArazii** [comment] 2022-09-18 11:05
@raphaelsc please have a look

**Comment by mykaul** [comment] 2022-12-05 11:27
@ShlomiBalalis - since it's serial, and during that time there was additional IO I assume, it can be expected that time will differ between nodes?

**Comment by ShlomiBalalis** [comment] 2023-03-15 16:47
> @ShlomiBalalis - since it's serial, and during that time there was additional IO I assume, it can be expected that time will differ between nodes?

Not to this extent, definitely. We're talking about a 500% increase when comparing the cleanup times of the mview keyspace alone.

**Comment by raphaelsc** [comment] 2024-10-21 00:13
@mykaul we made some progress in cleanup efficiency with 1545ae2d3be23d9ae8e9, but we're not investing in it any longer since tablets make cleanup cheap. It wasn't clear however the cause was related to cleanup itself, it could be that poor node was overloaded. I think we can close this one?!

**Closed** 2024-10-27 19:27 UTC
Labels: bug, area/nodetool
