### ISSUE TITLE
RFC: backward-compatible implement repair for Tablets

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#16101] opened 2023-11-20 09:56 UTC
This issue aims to provide a backward-compatible version of Repair that works with Tablets.
Future ideas, like incremental repair, are out of scope for this issue.

In particular, we need to flush out Repair REST API updates, which will affect users, like [nodetool repair](https://opensource.docs.scylladb.com/stable/operating-scylla/nodetool-commands/repair.html) and [Scylla Manager recurrent repair](https://manager.docs.scylladb.com/stable/repair/)

**Comment by mykaul** [comment] 2023-11-20 10:10
It's unclear to me if we have to have a compatible REST API - we can add new API for tablets.
I think 'nodetool repair' in some way or another need to be handled. Either it will be compatible, or re-route to a better tool, or something like 'nodetool repair is deprecated for tablets. Please use <this amazing tool> to repair tablets' ?

**Comment by avikivity** [comment] 2023-11-20 10:25
Easiest to use the existing API.

**Comment by tzach** [comment] 2023-11-20 12:29
> Easiest to use the existing API.

This is what I assumed.
"backward-compatible" is not accurate.  Tablet Repair should not support irrelevant options.
Below is a list of options from [nodetool repair](https://opensource.docs.scylladb.com/stable/operating-scylla/nodetool-commands/repair.html), and if there are, AFAIU, relevant for Tablets.

- `-dc` - relevant
- `-local --in-local-dc` - relevant
- `keyspace` `table` - relevant
- `-hosts` - relevant (?)*
- `--partitioner-range` - irrelevant
- `--start-token` - irrelevant
- `-et --end-token` - irrelevant

`*` Hosts option is error prune and degarus. Might be helpful for debugging?

**Comment by avikivity** [comment] 2023-11-20 16:26
We can support start-token/end-token, can be useful for repairing a single tablet.

**Comment by mykaul** [comment] 2023-11-22 15:40
@bhalevy - who can own this (hopefully more people can join this effort!)

**Comment by bhalevy** [comment] 2023-11-22 15:59
> @bhalevy - who can own this (hopefully more people can join this effort!)

That falls under @denesb and @asias + @tgrabiec for the tablet specific parts.

**Comment by dorlaor** [comment] 2023-11-26 09:50
> We can support start-token/end-token, can be useful for repairing a single tablet.

It will create a ton of ranges with large clusters and will slow us down. Also, scylla manager will need to learn the tablet's tokens and later to call them.

**Comment by bhalevy** [comment] 2023-12-21 13:55
@tgrabiec reassigning to you as you're actively working on this.

**Comment by bhalevy** [comment] 2023-12-28 14:04
@asias what else needs to be done here?

**Comment by bhalevy** [comment] 2024-01-07 09:56
@asias can we close this issue as duplicate of https://github.com/scylladb/scylladb/issues/16599?

**Comment by bhalevy** [comment] 2024-01-17 07:21
> @asias can we close this issue as duplicate of #16599?

ping @asias / @tgrabiec , is this a dup of #16599?

**Comment by asias** [comment] 2024-01-17 07:33
> > @asias can we close this issue as duplicate of #16599?
> 
> ping @asias / @tgrabiec , is this a dup of #16599?

16599 alone is not enough. Not all repair options are supported yet with 16599. Let's keep this open as an umbrella.

**Comment by bhalevy** [comment] 2024-03-18 06:54
@asias is anything still missing, or can this issue be closed?

**Comment by asias** [comment] 2024-03-18 06:56
It is done at scylla side. I am closing it.

The SM part is tracked here: https://github.com/scylladb/scylla-manager/pull/3753

**Closed by asias** 2024-03-18 06:56 UTC
Labels: area/repair, P1, status/release blocker, area/tablets
