### ISSUE TITLE
docs: Issue in page Scylla Large Rows and Large Cells Tables - Add large collection

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#12760] opened 2023-02-07 07:16 UTC
I would like to report an issue in page https://docs.scylladb.com/branch-5.1/troubleshooting/large-rows-large-cells-tables

### Problem
Scylla 5.2 add adds support for detecting collections that have too many items and recording them in `system.large_cells`.
https://github.com/scylladb/scylladb/commit/20bad62562268bed1a78a0f0466c62359565f0c0

```
(cqlsh) SELECT * from system.large_cells;

 keyspace_name | table_name | sstable_name      | cell_size | partition_key | clustering_key | column_name | collection_elements | compaction_time
---------------+------------+-------------------+-----------+---------------+----------------+-------------+---------------------+---------------------------------
            ks |       maps | me-10-big-Data.db |     10929 |          user |                |  properties |                1001 | 2023-02-06 13:07:23.203000+0000

(1 rows)

```

**Comment by bhalevy** [comment] 2023-02-07 10:34
Large collections are tracked in system.large_cells (well each collection is a cells),
based either on their total size, in which case they will cross the `cell_size` threshold, and/or the number of elements they contain, in which case they will cross the `collection_elements` threshold.

**Comment by annastuchlik** [comment] 2023-02-09 18:08
@tzach In fact, the feature has already been documented by @bhalevy, but it's on _master_ (which will turn into _stable_ when we release 5.2): https://docs.scylladb.com/master/troubleshooting/large-rows-large-cells-tables.html#find-large-cells
All the required feature elements are reflected in the docs:
- updated the example with `collection_elements` equal to `17042`.
- added the new `collection_elements` parameter to the Parameters table.
- documented the new `compaction_collection_elements_count_warning_threshold` parameter that specifies what "too many" collection elements means.
- updated the schema with `collection_elements bigint,`.

I see nothing else to add. @bhalevy Can you confirm?

Btw, @tzach, where did you find this link: https://docs.scylladb.com/branch-5.1/troubleshooting/large-rows-large-cells-tables
Such links should not be in use because we have _master_, _stable_, and version without the "branch" prefix, so _5.1_, not _branch-5.1_.

**Comment by bhalevy** [comment] 2023-02-09 18:10
> @tzach In fact, the feature has already been documented by @bhalevy, but it's on _master_ (which will turn into _stable_ when we release 5.2): https://docs.scylladb.com/master/troubleshooting/large-rows-large-cells-tables.html#find-large-cells All the required feature elements are reflected in the docs:
> 
> * updated the example with `collection_elements` equal to `17042`.
> * added the new `collection_elements` parameter to the Parameters table.
> * documented the new `compaction_collection_elements_count_warning_threshold` parameter that specifies what "too many" collection elements means.
> * updated the schema with `collection_elements bigint,`.
> 
> I see nothing else to add. @bhalevy Can you confirm?
> 

confirmed

**Comment by annastuchlik** [comment] 2023-02-09 18:22
@bhalevy Thanks! And thank you for always remembering to update the docs along with the code!!!

**Comment by annastuchlik** [comment] 2023-02-09 18:25
The feature is documented on master and branch-5.2: https://github.com/scylladb/scylladb/blob/branch-5.2/docs/troubleshooting/large-rows-large-cells-tables.rst
Closing.

**Closed by annastuchlik** 2023-02-09 18:25 UTC
Labels: Documentation
