### ISSUE TITLE
cql: CREATE TABLE with non-existing KS returns empty error

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylladb#20097] opened 2024-08-10 11:58 UTC
In `6.0` when `CREATE TABLE` is issued for a ks.cf and ks doesn't exist we get an empty error message:
```
cqlsh> CREATE TABLE not_existing_ks.my_table (id VARCHAR PRIMARY KEY, field_a VARCHAR, field_b VARCHAR);
NoHostAvailable: 
```
The error message should clearly state what the error is about, i.e. a non-existing keyspace.
We're reporting explanatory errors in similar scenarios, e.g.:
```
cqlsh> CREATE TABLE my_table (id VARCHAR PRIMARY KEY, field_a VARCHAR, field_b VARCHAR);
InvalidRequest: Error from server: code=2200 [Invalid query] message="No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename"
cqlsh> INSERT INTO movies.nowshowing (movie, director, main_actor, released) VALUES ('Sonic the Hedgehog', 'Jeff Fowler', 'Ben Schwartz', '2020-14-02') IF NOT EXISTS;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace movies does not exist"

**Comment by tzach** [comment] 2024-08-11 10:43
Look like a regression. Here is what I got from 2024.1
```
ConfigurationException: Cannot add table 'my_table' to non existing keyspace 'not_existing_ks'.
```

(not sure why "ConfigurationException")

**Comment by ptrsmrn** [comment] 2024-08-27 20:33
OK, this was because I was using:
```
$ cqlsh --version
cqlsh 5.0.1
$ which cqlsh
/snap/bin/cqlsh
```
When using "our" `cqlsh` I see the error message correctly reported:
```
$ ./bin/cqlsh 
Connected to  at 127.0.0.1:9042
[cqlsh 6.0.23.dev3+g86a280a | Scylla 6.2.0~dev-0.20240827.5c0f6d461321 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> CREATE TABLE not_existing_ks.my_table (id VARCHAR PRIMARY KEY, field_a VARCHAR, field_b VARCHAR);
NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.0.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Can't find a keyspace not_existing_ks">})

**Comment by ptrsmrn** [comment] 2024-08-27 20:34
> (not sure why "ConfigurationException")

Maybe it's because of differences between different scylla versions this CQL query is tested against or maybe it's because you use yet another `cqlsh`?

**Comment by ptrsmrn** [comment] 2024-08-27 20:35
Not sure what to do now, it turned out to be "unsupported" driver, so do we consider the matter settled?

**Comment by ptrsmrn** [comment] 2024-08-28 10:11
FWIW:
In order to fix this issue it's enough to change this class:
```
// data_dictionary.hh:55
class no_such_keyspace : public std::runtime_error
```
to inherit this exception instead:
```
class no_such_keyspace : public exceptions::invalid_request_exception
```
This makes the error returned to the python driver in cqlsh explicit, like so:
```
cqlsh> CREATE TABLE not_existing_ks.my_table (id VARCHAR PRIMARY KEY, field_a VARCHAR, field_b VARCHAR);
InvalidRequest: Error from server: code=2200 [Invalid query] message="Can't find a keyspace not_existing_ks"

**Comment by ptrsmrn** [comment] 2024-08-28 10:12
I'm closing the Issue, because it appears to be a driver incompatibility at most.
cc @dkropachev

**Comment by dkropachev** [comment] 2024-08-28 22:56
@ptrsmrn , I have checked it agains cassandra, it works correctly:
```
cqlsh> CREATE TABLE not_existing_ks.my_table (id VARCHAR PRIMARY KEY, field_a VARCHAR, field_b VARCHAR);
InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace 'not_existing_ks' doesn't exist"
cqlsh> 
```

Can you please clarify why exactly you have closed it ? 
It seemse to me that scylla responses with wrong code.

**Comment by dkropachev** [comment] 2024-08-28 23:10
@mykaul , I think it should be addressed in Scylla, can you please reopen it.

**Comment by ptrsmrn** [comment] 2024-08-29 07:26
> Can you please clarify why exactly you have closed it ? It seemse to me that scylla responses with wrong code.

@dkropachev I closed it, because I realized I was getting this vague error message only when using some random `cqlsh` binary (it was installed with `snap` on my `Fedora40` OS, I am not sure of its origin TBH), but when I used `cqlsh` we provide, then the error message was displayed correctly.

**Comment by mykaul** [comment] 2024-08-29 07:50
@ptrsmrn - the error comes mostly from the server and you can sniff the protocol to see it (or tracing in Scylla). It looks like a regression and a compatibility issues with Cassandra.

**Comment by dkropachev** [comment] 2024-08-29 08:31
> > Can you please clarify why exactly you have closed it ? It seemse to me that scylla responses with wrong code.
> 
> @dkropachev I closed it, because I realized I was getting this vague error message only when using some random `cqlsh` binary (it was installed with `snap` on my `Fedora40` OS, I am not sure of its origin TBH), but when I used `cqlsh` we provide, then the error message was displayed correctly. EDIT: I don't know much about drivers. I'm also OK with re-opening this issue.

I have tested it on `scylladb/scylla:6.1` image and returns same error you provided:
```
cqlsh> CREATE TABLE not_existing_ks.my_table (id VARCHAR PRIMARY KEY, field_a VARCHAR, field_b VARCHAR);
NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 172.17.0.2:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Can't find a keyspace not_existing_ks">})
```

**Comment by kostja** [comment] 2024-08-29 08:49
@ptrsmrn what is the origin of the regression? Was the base class changed in one of the commits in 6.x, and if yes, what was the reason for the change?

**Comment by ptrsmrn** [comment] 2024-08-29 11:22
> @ptrsmrn what is the origin of the regression? Was the base class changed in one of the commits in 6.x, and if yes, what was the reason for the change?

As I wrote [here](https://scylladb-corporate.slack.com/archives/C3AE85S07/p1724786680408389), I don't know what's the origin of the regression, I couldn't identify it. 
Furthemore, I don't know if it's a regression. We have tests that verify this error message and they pass, they also had to pass in the past. But the tests use our python driver for cqlsh, not the one I used. So maybe nothing has changed, hence it's not a regression (in the sense that it was working and is no longer working), maybe it never worked.

**Comment by mykaul** [comment] 2024-08-29 11:31
I'd be very surprised if it's a driver issue.

**Comment by ptrsmrn** [comment] 2024-08-29 13:48
> Ok, I have rerun test again and here is the buffer scylla responds with: `\x00\x00\x00\x00\x00%Can't find a keyspace not_existing_ks` , it is definnitely returning `code` 0.

I believe scylla-server doesn't return any error code, which is interpreted as 0.
`class no_such_keyspace` doesn't have an error code, it only carries an error message.

**Comment by dkropachev** [comment] 2024-08-29 13:54
> > Ok, I have rerun test again and here is the buffer scylla responds with: `\x00\x00\x00\x00\x00%Can't find a keyspace not_existing_ks` , it is definnitely returning `code` 0.
> 
> I believe scylla-server doesn't return any error code, which is interpreted as 0. `class no_such_keyspace` doesn't have an error code, it only carries an error message.

Did not get that, can you please elaborate.

**Comment by ptrsmrn** [comment] 2024-08-29 17:31
> > > Ok, I have rerun test again and here is the buffer scylla responds with: `\x00\x00\x00\x00\x00%Can't find a keyspace not_existing_ks` , it is definnitely returning `code` 0.
> > 
> > 
> > I believe scylla-server doesn't return any error code, which is interpreted as 0. `class no_such_keyspace` doesn't have an error code, it only carries an error message.
> 
> Did not get that, can you please elaborate.

@dkropachev sorry, sure I can, but this is about C++, so I'll try to be as language agnostic as I can.
Exception class `no_such_keyspace` inherits directly from `std::runtime_exception`, which only allows to set error message, it doesn't allow to set an error code. OTOH other exception classes inherit from `cassandra_exception` class, which allows to set both the error message and the error code.
So what I meant was that there's no code present in `no_such_keyspace` exception (it doesn't contain such field), which, I'm guessing, is interpreted by "our" driver as: "the code is set to 0", but by [the driver I used originally](https://github.com/scylladb/scylladb/issues/20097#issuecomment-2313466622) as "I don't understand this exception, but this is still some exception". 
So my resolution to this problem was to make `no_such_keyspace` inherit from `invalid_request_exception`, which in turn inherits from `cassandra_exception` and by default sets the error code to `INVALID = 0x2200`.

**Comment by kostja** [comment] 2024-08-29 20:44
@ptrsmrn @dkropachev writes in the beginning of the report that it is a regression starting from 6.x. So it must be a recent change. We mustn't regress even the legacy drivers. Your fix would be OK when we find out why the code changed in the first place.

**Comment by dkropachev** [comment] 2024-08-29 21:05
@kostja , to confirm your words, I did more testing and results are:
## Cassandra 4 

Code: 8704 (2200)
Message: "Keyspace 'not_existing_ks' doesn't exist"
HexMessage: "4b6579737061636520276e6f745f6578697374696e675f6b732720646f65736e2774206578697374"
Hex response: "0000220000284b6579737061636520276e6f745f6578697374696e675f6b732720646f65736e2774206578697374"

## Scylla 6.1.0

Code: 0 (0000)
Message : "Can't find a keyspace not_existing_ks"
HexMessage: "43616e27742066696e642061206b65797370616365206e6f745f6578697374696e675f6b73"
HexResponse: "00002300004743616e6e6f7420616464207461626c6520276d795f7461626c652720746f206e6f6e206578697374696e67206b6579737061636520276e6f745f6578697374696e675f6b73272e"

## Scylla 5.4

Code: 8960 (2300)
Message : "Cannot add table 'my_table' to non existing keyspace 'not_existing_ks'."
HexMessage: "43616e6e6f7420616464207461626c6520276d795f7461626c652720746f206e6f6e206578697374696e67206b6579737061636520276e6f745f6578697374696e675f6b73272e"
HexResponse: "00002300004743616e6e6f7420616464207461626c6520276d795f7461626c652720746f206e6f6e206578697374696e67206b6579737061636520276e6f745f6578697374696e675f6b73272e"

## Scylla 5.1: 

Code: 8960 (2300)
Message : "Cannot add table 'my_table' to non existing keyspace 'not_existing_ks'."
HexMessage: "43616e6e6f7420616464207461626c6520276d795f7461626c652720746f206e6f6e206578697374696e67206b6579737061636520276e6f745f6578697374696e675f6b73272e"
HexResponse: "00002300004743616e6e6f7420616464207461626c6520276d795f7461626c652720746f206e6f6e206578697374696e67206b6579737061636520276e6f745f6578697374696e675f6b73272e"

**Closed** 2024-09-09 15:32 UTC
Labels: backport/none
