### ISSUE TITLE
changing coredump directory

### ISSUE THREAD

**Issue by infordb** [scylladb/scylladb#3663] opened 2018-08-07 06:00 UTC
OS : centos 7.2

scylla_coredump_setup changes coredump directory using symbolic link
```
    if [ $SYMLINK = 1 ]; then
        rm -rf /var/lib/systemd/coredump
        mkdir -p /var/lib/scylla/coredump
        ln -sf /var/lib/scylla/coredump /var/lib/systemd/coredump
```
 
systemd-tmpfiles-clean.service generated the error message.
_"Failed to open directory /var/lib/systemd/coredump: Too many levels of symbolic links"_

If the coredump directory is created with a symbolic link, the error message is generated.

Could you add a setting to change the coredump directory without using a symbolic link?
 

## test
```
[root@dbtest04 ~]# /usr/bin/systemd-tmpfiles --clean 
Failed to open directory /var/lib/systemd/coredump: Too many levels of symbolic links
[root@dbtest04 scylla]# rm -rf /var/lib/systemd/coredump
[root@dbtest04 scylla]# /usr/bin/systemd-tmpfiles --clean 
[root@dbtest04 scylla]#
```

**Comment by tzach** [comment] 2018-08-09 09:25
@syuu1228 any idea?

**Comment by avikivity** [comment] 2018-08-09 10:07
It's possible to use a bind mount.

However, I don't understand why we had the error in the first place.

Please run

    find -L /var -mindepth 15

**Comment by ban4785** [comment] 2018-08-13 01:46
@avikivity

**Comment by ban4785** [comment] 2018-08-13 01:52
we did `find -L /var -mindepth 15` and no result printed.

**Comment by avikivity** [comment] 2018-08-13 05:52
Please strace `systemd-tmpfiles --clean` to understand what it is complaining about.

**Comment by infordb** [comment] 2018-08-20 04:58
@avikivity 
attached the result of strace 
[strace.txt](https://github.com/scylladb/scylla/files/2301163/strace.txt)

**Comment by avikivity** [comment] 2018-08-20 07:26
aha:

```
openat(AT_FDCWD, "/var/lib/systemd/coredump", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_NOFOLLOW|O_NOATIME|O_CLOEXEC) = -1 ELOOP (Too many levels of symbolic links)
```
`O_NOFOLLOW` refuses symbolic links.

@syuu1228 please change it to a bind mount instead.

**Comment by avikivity** [comment] 2018-08-21 10:34
Yes.

**Comment by syuu1228** [comment] 2020-04-13 09:39
bind-mount coredump directory is merged at https://github.com/scylladb/scylla/commit/5f18964763608b5e5d5a833c0777e253d2c21624

**Comment by syuu1228** [comment] 2023-10-11 05:19
The issue is fixed at https://github.com/scylladb/scylladb/commit/5f18964763608b5e5d5a833c0777e253d2c21624, closing.

**Closed by syuu1228** 2023-10-11 05:19 UTC
Labels: bug
