### ISSUE TITLE
Incorrect UUID Comparison

### ISSUE THREAD

**Issue by yottacto** [scylladb/scylladb#15561] opened 2023-09-27 11:50 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

**Installation details**
Scylla version (or git commit hash): 5.2.8

**Description of the issue:**
Even with UUIDs in clustering columns, the order of UUIDs is not correct. You can reproduce the issue with the following steps:

**Steps to reproduce:**
1. Create a table named 'foo' with the schema: `create table xxx.foo (key int, value uuid, primary key (key, value));`
2. Insert a UUID value into the table: `insert into xxx.foo (key,value) values(1, 018ad500-b25d-09d0-7e90-ea5438411dc7);`
3. Execute the following query: `select * from xxx.foo where key = 1 and value < 018ad550-b227-2108-2871-99a6c9bdfe96;`

**Expected behavior:**
The query should not return any results, as there are no UUID values in the specified range.

**Actual behavior:**
The query returns the following unexpected result:
```
 key | value
-----+--------------------------------------
   1 | 018ad500-b25d-09d0-7e90-ea5438411dc7

(1 rows)
```

**Comment by michoecho** [comment] 2023-09-28 14:53
Why do you think this ordering is incorrect?

You can find the ordering logic of UUIDs here:
https://github.com/scylladb/scylladb/blob/6d34f9920262b6feb9be154a176d6a477f036dd0/types/types.cc#L2350

The logic is:
- Two UUIDs of different versions are ordered by their versions.
- Two UUIDs of version 1 are ordered by their (timestamp, node ID) tuples.
- Two UUIDs of equal version, different from version 1, are ordered lexicographically. (Byte-by-byte. Equivalently: as big-endian 128-bit numbers).

`018ad500-b25d-09d0-7e90-ea5438411dc7` and `018ad550-b227-2108-2871-99a6c9bdfe96` both have version 0 (the first 0 in `09d0`, so they are ordered lexicographically. So 018ad5**00**-b25d-09d0-7e90-ea5438411dc7 < 018ad5**50**-b227-2108-2871-99a6c9bdfe96.

**Comment by yottacto** [comment] 2023-09-29 15:56
Thank you for your response. I've corrected the UUID typo and updated the steps for clarity:

**Steps to Reproduce:**
2. Insert a corrected UUID value (with the correct type) into the table:
   ```sql
   insert into xxx.foo (key, value) values (1, 018ad550-b25d-09d0-7e90-ea5438411dc7);
   ```
3. Execute the following query:
   ```sql
   select * from xxx.foo where key = 1 and value < 018ad550-b227-2108-2871-99a6c9bdfe96;
   ```

The updated output is as follows:

```bash
 key | value
-----+--------------------------------------
   1 | 018ad550-b25d-09d0-7e90-ea5438411dc7

(1 row)
```

Additionally, you can generate a set of ULIDs, convert them to UUIDs insert them into the database, and sort the corresponding column to observe the output. This can help further illustrate the issue with UUID sorting.

**Comment by yottacto** [comment] 2023-10-07 00:45
@michoecho

**Comment by michoecho** [comment] 2023-10-07 10:43
I wrote down the ordering algorithm above, and your experiment is consistent with it.
018ad550-b25d-**0**9d0-7e90-ea5438411dc7 has version 0, while 018ad550-b227-**2**108-2871-99a6c9bdfe96 has version 2.
Hence, 018ad550-b25d-**0**9d0-7e90-ea5438411dc7 is smaller than 018ad550-b227-**2**108-2871-99a6c9bdfe96.

Again, why do you think this order is wrong? How do you expect UUID ordering to be defined? There is no standard ordering of UUIDs. As far as I can see, your examples are consistent with how UUID comparison is defined in Scylla and Cassandra.
Other databases or libraries might have a different definition, but this doesn't mean that either is wrong.

**Comment by nyh** [comment] 2024-06-17 11:59
@yottacto could you please try to come up with an argument why you believe the order you got was **wrong**?

In particular, did you compare it to the order on Cassandra or any other type of database and think Scylla is being wrong?

Without such an explanation, I think we have to close this issue.

**Comment by nyh** [comment] 2024-06-17 14:40
> AFAIK in PostgreSQL, UUIDs are treated as 128-bit unsigned integers and are compared byte by byte from left to right.

Why is this good, or useful?

One of undesirable effects of blindly treating UUIDs as 128-bit arrays is that it doesn't sort the specific case of time-based UUIDs in the expected (time-based) order, whereas our method does preserve this order.
I want to write now a test that compares Scylla's choice of order to Cassandra's, and if it's the same, I'll close this issue unless someone can explain to me why the PostgreSQL order is better, or useful in some sense.

I also want to point out that changing Scylla's order algorithm will be a backward-compatibility disaster, and we are unlikely to do this. The problem is that existing data in existing sstables would be sorted by the original sorting algorithm, and we can't just switch to a different sorting algorithm without breaking searches in those existing sstables.

**Comment by mykaul** [comment] 2024-06-17 14:54
libuuid compares them (as v1 I believe) - https://github.com/cloudbase/libuuid/blob/a29bf0fe780306ae67802a22502b1e5447a71e73/compare.c#L42 :

```
#define UUCMP(u1,u2) if (u1 != u2) return((u1 < u2) ? -1 : 1);

int uuid_compare(const uuid_t uu1, const uuid_t uu2)
{
	struct uuid	uuid1, uuid2;

	uuid_unpack(uu1, &uuid1);
	uuid_unpack(uu2, &uuid2);

	UUCMP(uuid1.time_low, uuid2.time_low);
	UUCMP(uuid1.time_mid, uuid2.time_mid);
	UUCMP(uuid1.time_hi_and_version, uuid2.time_hi_and_version);
	UUCMP(uuid1.clock_seq, uuid2.clock_seq);
	return memcmp(uuid1.node, uuid2.node, 6);
}
```

Makes most sense to me.

**Comment by nyh** [comment] 2024-06-17 17:11
Sent a pull request https://github.com/scylladb/scylladb/pull/19343 with a test verifying the algorithm explained a year ago by @michoecho, and the fact that the UUID sort order used by Scylla is identical to Cassandra's - so for this reason and for backward-compatibility, we'll probably never change it (or at least, will need a very strong reason to even consider this idea).

**Comment by mykaul** [comment] 2024-06-18 06:39
I wonder if it's worth documenting somewhere that CQL (Cassandra and Scylla's) comparison is different than Postgresql.

**Comment by nyh** [comment] 2024-06-18 08:21
> I wonder if it's worth documenting somewhere that CQL (Cassandra and Scylla's) comparison is different than Postgresql.

I think the answer is yes - I think we should have a reference to Scylla's data types, which among other things should explain how they are sorted (which is important for clustering-row ordering, for inequality relations (`WHERE a < ...`), and aggregations like `max`).  For some types the answer is obvious, for others (like UUID), it's not.
In this case, the fact that if the user inserts a version 1 ("time") UUID into a UUID column, then his data gets sorted according to time, is interesting.
I'll open an issue about that.

**Comment by nyh** [comment] 2024-06-18 08:41
Opened https://github.com/scylladb/scylladb/issues/19353 about the documentation.

**Closed** 2024-06-18 14:11 UTC
Labels: area/cql
