### ISSUE TITLE
Counter updates timeouts & bad_alloc

### ISSUE THREAD

**Issue by horschi** [scylladb/scylladb#16187] opened 2023-11-26 13:13 UTC
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.1.18-0.20230920.3f3ecbe72732-1
Cluster size: 15+3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 22.04

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets=1 cores=6 hyperthreading=12 memory=64GB RAM
Disks: (SSD/HDD, count): 2x SSD

*Description*

Every now and then it seems counter updates seem to have issues, even though there are not many counter writes happening (counters are only written from one thread).

I just have seen a node causing lots of counter update errors:
```
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.21:9042] Timed out waiting for server response
```

```
ScyllaConnection: Recent Scylla error: com.datastax.driver.core.exceptions.TransportException: [nexthost/10.0.0.21:9042] Connection has been closed
```

And some bad alloc errors:
```
Nov 24 12:35:38 os-p-L12-1 scylla[2796088]: Reactor stalled for 69 ms on shard 2. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f48ede37a1f 0x168b018 0x1522f6f 0x16023c5 0x15d6281 0x15e78ed 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Nov 24 12:35:38 os-p-L12-1 scylla[2796088]: Reactor stalled for 129 ms on shard 2. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f48ede37a1f 0x1608c4a 0x19a0460 0x18adc78 0x18ad5f4 0x1588e92 0x15e1ddc 0x15ef278 0x15ead06 0x15e7674 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Nov 24 12:35:38 os-p-L12-1 scylla[2796088]: Reactor stalled for 237 ms on shard 2. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f48ede37a1f 0x19af3af 0x1602339 0x15d6281 0x15e7501 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Nov 24 12:35:38 os-p-L12-1 scylla[2796088]: Reactor stalled for 445 ms on shard 2. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f48ede37a1f 0x168b036 0x1522f6f 0x16023c5 0x15d6281 0x15e78ed 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Nov 24 12:37:08 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:38:12 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:39:15 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:40:21 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:41:22 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:42:27 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:43:30 os-p-L12-1 scylla[2796088]: Reactor stalled for 72 ms on shard 4. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f48ede37a1f 0x1608cd4 0x19a0460 0x18adc78 0x18ad5f4 0x1588e92 0x15e1ddc 0x15ef278 0x15ead06 0x15e7674 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Nov 24 12:43:30 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:43:30 os-p-L12-1 scylla[2796088]: Reactor stalled for 132 ms on shard 4. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f48ede37a1f 0x19af33b 0x16023c5 0x15d6281 0x15e78ed 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Nov 24 12:43:30 os-p-L12-1 scylla[2796088]: Reactor stalled for 240 ms on shard 4. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f48ede37a1f 0x1603285 0x1602380 0x15d6281 0x15e78ed 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab740 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Nov 24 12:44:35 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:45:39 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:46:41 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:47:47 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:48:50 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:49:50 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:50:48 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:52:01 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:52:01 os-p-L12-1 scylla[2796088]: Reactor stalled for 71 ms on shard 0. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f48ede37a1f 0x1608cd4 0x19a0460 0x18adc78 0x18ad5f4 0x1588e92 0x15e1ddc 0x15ef278 0x15ead06 0x15e7674 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d6955c 0x4d0f598 0x4d0ea71 0x1037db6 0x103539a 0x27b74 0x103426d
Nov 24 12:52:01 os-p-L12-1 scylla[2796088]: Reactor stalled for 131 ms on shard 0. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f48ede37a1f 0x1603271 0x1602380 0x15d6281 0x15e78ed 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d6955c 0x4d0f598 0x4d0ea71 0x1037db6 0x103539a 0x27b74 0x103426d
Nov 24 12:53:04 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:54:01 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:55:12 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:56:14 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:57:15 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:58:13 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 12:59:24 os-p-L12-1 scylla[2796088]:  [shard 2] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Nov 24 13:00:04 os-p-L12-1 scylla[2796088]:  [shard 0] api - perform_keyspace_flush: keyspace=system_schema tables={}
Nov 24 13:00:04 os-p-L12-1 scylla[2796088]:  [shard 0] api - perform_keyspace_flush: keyspace=system_distributed_everywhere tables={}
Nov 24 13:00:04 os-p-L12-1 scylla[2796088]:  [shard 0] api - perform_keyspace_flush: keyspace=system_traces tables={}
Nov 24 13:00:04 os-p-L12-1 scylla[2796088]:  [shard 0] api - perform_keyspace_flush: keyspace=system tables={}
```

After a restart of that node everything was fine again.

Are there any metrics I should share?

**Comment by avikivity** [comment] 2023-11-26 16:46
What's your disk:ram ratio?

Please share per-shard memory metrics of lsa used space and non lsa used space (I think on the detailed dashboard).

I don't think it's related to counters.

**Comment by horschi** [comment] 2023-12-07 07:58
Bad alloc keeps happening. Restarting scylla seems to help for a few days.

```
Dec 07 07:31:17 o-p-L3-4 scylla[2001480]:  [shard 5] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Dec 07 07:31:17 o-p-L3-4 scylla[2001480]: Reactor stalled for 71 ms on shard 4. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f4cdc730a1f 0x16022bf 0x15e5365 0x15ef087 0x15ead06 0x15e7674 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Dec 07 07:31:17 o-p-L3-4 scylla[2001480]: Reactor stalled for 131 ms on shard 4. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f4cdc730a1f 0x1608ea1 0x19a04d8 0x18adc78 0x18ad5f4 0x1588e92 0x15e1ddc 0x15ef278 0x15ead06 0x15e7674 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Dec 07 07:31:18 o-p-L3-4 scylla[2001480]: Reactor stalled for 239 ms on shard 4. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f4cdc730a1f 0x16022e2 0x15e5365 0x15ef087 0x15ead06 0x15e7674 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Dec 07 07:31:18 o-p-L3-4 scylla[2001480]: Reactor stalled for 447 ms on shard 4. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f4cdc730a1f 0x12084cf 0x16023c5 0x15d6281 0x15e78ed 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab4cc 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Dec 07 07:33:12 o-p-L3-4 scylla[2001480]:  [shard 5] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Dec 07 07:34:15 o-p-L3-4 scylla[2001480]:  [shard 5] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Dec 07 07:35:19 o-p-L3-4 scylla[2001480]:  [shard 5] cql_server - exception while processing connection: std::bad_alloc (std::bad_alloc)
Dec 07 07:35:19 o-p-L3-4 scylla[2001480]: Reactor stalled for 71 ms on shard 1. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f4cdc730a1f 0x15d902f 0x1608c67 0x19a04d8 0x18adc78 0x18ad5f4 0x1588e92 0x15e1ddc 0x15ef278 0x15ead06 0x15e7674 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab740 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
Dec 07 07:35:19 o-p-L3-4 scylla[2001480]: Reactor stalled for 131 ms on shard 1. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f4cdc730a1f 0x16030e1 0x1602380 0x15d6281 0x15e78ed 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab740 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d89355 0x4d3ccca 0x92a4 0x100322
```

**Comment by mykaul** [comment] 2023-12-07 09:10
decoded backtrace for:
```
Nov 24 14:01:45 os-p-L3-1 scylla[3677563]: Reactor stalled for 446 ms on shard 0. Backtrace: 0x4d59732 0x4d58390 0x4d59640 0x7f0a0468da1f 0x12084e8 0x16023c5 0x15d6281 0x15e78ed 0x1604681 0x4d2a025 0x4d2a58f 0x4d2a8b8 0x4d2bf1f 0x4d2efe1 0x1dab740 0x1daa7f8 0x1df91ff 0x1de623f 0x1de789f 0x4d68f24 0x4d6a307 0x4d6955c 0x4d0f598 0x4d0ea71 0x1037db6 0x103539a 0x27b74 0x103426d
```

Is:
```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:774
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:793
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1368
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1110
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1127
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1351
?? ??:0
blob_storage at ././utils/managed_bytes.hh:60
 (inlined by) standard_migrator<blob_storage>::migrate(void*, void*, unsigned long) const at ././utils/allocation_strategy.hh:72
operator() at ./utils/logalloc.cc:1712
 (inlined by) void logalloc::region_impl::for_each_live<logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*, unsigned long)#1}>(logalloc::segment*, logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*, unsigned long)#1}&&) at ./utils/logalloc.cc:1558
 (inlined by) logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&) at ./utils/logalloc.cc:1709
logalloc::region_impl::compact_segment(logalloc::segment*, logalloc::segment_descriptor&) at ./utils/logalloc.cc:2071
 (inlined by) logalloc::segment_pool::compact_segment(logalloc::segment*) at ./utils/logalloc.cc:2650
logalloc::segment_pool::reclaim_segments(unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:1056
 (inlined by) logalloc::tracker::impl::reclaim_locked(unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:2429
logalloc::tracker::impl::reclaim(unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:2399
 (inlined by) logalloc::tracker::reclaim(unsigned long) at ./utils/logalloc.cc:530
 (inlined by) logalloc::tracker::reclaim(seastar::memory::reclaimer::request) at ./utils/logalloc.cc:2144
 (inlined by) operator() at ./utils/logalloc.cc:518
 (inlined by) seastar::memory::reclaiming_result std::__invoke_impl<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request>(std::__invoke_other, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request>, seastar::memory::reclaiming_result>::type std::__invoke_r<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request>(logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:114
 (inlined by) std::_Function_handler<seastar::memory::reclaiming_result (seastar::memory::reclaimer::request), logalloc::tracker::tracker()::$_0>::_M_invoke(std::_Any_data const&, seastar::memory::reclaimer::request&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
std::function<seastar::memory::reclaiming_result (seastar::memory::reclaimer::request)>::operator()(seastar::memory::reclaimer::request) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) seastar::memory::reclaimer::do_reclaim(unsigned long) at ./build/release/seastar/./seastar/include/seastar/core/memory.hh:199
 (inlined by) seastar::memory::cpu_pages::run_reclaimers(seastar::memory::reclaimer_scope, unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1143
 (inlined by) seastar::memory::cpu_pages::find_and_unlink_span_reclaiming(unsigned int) at ./build/release/seastar/./seastar/src/core/memory.cc:716
seastar::memory::cpu_pages::allocate_large_and_trim(unsigned int) at ./build/release/seastar/./seastar/src/core/memory.cc:741
seastar::memory::cpu_pages::allocate_large(unsigned int) at ./build/release/seastar/./seastar/src/core/memory.cc:787
seastar::memory::allocate_large(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1338
 (inlined by) seastar::memory::allocate(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1399
operator new[](unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:2066
utils::reusable_buffer::reserve(unsigned long) at ././utils/reusable_buffer.hh:62
 (inlined by) operator() at ././utils/reusable_buffer.hh:121
 (inlined by) bytes_ostream utils::reusable_buffer::make_buffer<cql_transport::response::compress_lz4()::$_18>(unsigned long, cql_transport::response::compress_lz4()::$_18&&) at ././utils/reusable_buffer.hh:116
 (inlined by) cql_transport::response::compress_lz4() at ./transport/server.cc:1538
 (inlined by) cql_transport::response::compress(cql_transport::cql_compression) at ./transport/server.cc:1519
cql_transport::response::make_message(unsigned char, cql_transport::cql_compression) at ./transport/server.cc:1504
operator() at ./transport/server.cc:1494
seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression)::$_13>(cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression)::$_13&&) at ././seastar/include/seastar/core/future.hh:2149
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression)::$_13>(cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression)::$_13&&, seastar::internal::monostate) at ././seastar/include/seastar/core/future.hh:1993
 (inlined by) seastar::future<void> seastar::future<void>::then_impl<cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression)::$_13, seastar::future<void> >(cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression)::$_13&&) at ././seastar/include/seastar/core/future.hh:1615
 (inlined by) seastar::internal::future_result<cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression)::$_13, void>::future_type seastar::internal::call_then_impl<seastar::future<void> >::run<cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression)::$_13>(seastar::future<void>&, cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression)::$_13&&) at ././seastar/include/seastar/core/future.hh:1248
 (inlined by) seastar::future<void> seastar::future<void>::then<cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression)::$_13, seastar::future<void> >(cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression)::$_13&&) at ././seastar/include/seastar/core/future.hh:1534
 (inlined by) cql_transport::cql_server::connection::write_response(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, service_permit, cql_transport::cql_compression) at ./transport/server.cc:1493
 (inlined by) operator() at ./transport/server.cc:684
operator() at ././seastar/include/seastar/core/future.hh:1682
 (inlined by) void seastar::futurize<void>::satisfy_with_result_of<seastar::future<seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > > >::then_wrapped_nrvo<void, cql_transport::cql_server::connection::process_request()::$_4::operator()(seastar::future<std::optional<cql_transport::cql_binary_frame_v3> >&&) const::{lambda(auto:1)#2}::operator()<seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > >(seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >) const::{lambda(fragmented_temporary_buffer)#1}::operator()(seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >)::{lambda(seastar::future<seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > > >)#1}>(cql_transport::cql_server::connection::process_request()::$_4::operator()(seastar::future<std::optional<cql_transport::cql_binary_frame_v3> >&&) const::{lambda(auto:1)#2}::operator()<seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > >(seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >) const::{lambda(fragmented_temporary_buffer)#1}::operator()(seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >)::{lambda(seastar::future<seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > > >)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda(fragmented_temporary_buffer)#1}&, seastar::future_state<seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > > >&&)#1}::operator()(seastar::internal, seastar::internal::promise_base_with_type, {lambda(fragmented_temporary_buffer)#1}&) const::{lambda()#1}>(seastar::internal, seastar::future<seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > > >::then_wrapped_nrvo<void, cql_transport::cql_server::connection::process_request()::$_4::operator()(seastar::future<std::optional<cql_transport::cql_binary_frame_v3> >&&) const::{lambda(auto:1)#2}::operator()<seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > >(seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >) const::{lambda(fragmented_temporary_buffer)#1}::operator()(seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >)::{lambda(seastar::future<seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > > >)#1}>(cql_transport::cql_server::connection::process_request()::$_4::operator()(seastar::future<std::optional<cql_transport::cql_binary_frame_v3> >&&) const::{lambda(auto:1)#2}::operator()<seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > >(seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >) const::{lambda(fragmented_temporary_buffer)#1}::operator()(seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >)::{lambda(seastar::future<seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > > >)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda(fragmented_temporary_buffer)#1}&, seastar::future_state<seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > > >&&)#1}::operator()(seastar::internal, seastar::internal::promise_base_with_type, {lambda(fragmented_temporary_buffer)#1}&) const::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2131
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1681
 (inlined by) seastar::continuation<seastar::internal::promise_base_with_type<void>, cql_transport::cql_server::connection::process_request()::$_4::operator()(seastar::future<std::optional<cql_transport::cql_binary_frame_v3> >&&) const::{lambda(auto:1)#2}::operator()<seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > >(seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >) const::{lambda(fragmented_temporary_buffer)#1}::operator()(seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >)::{lambda(seastar::future<seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<seastar::foreign_ptr> > > >)#1}, std::unique_ptr<cql_transport::response, std::default_delete<seastar::foreign_ptr> >::then_wrapped_nrvo<void, seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<seastar::foreign_ptr> > > >(seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<seastar::foreign_ptr> > >&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::foreign_ptr<std::unique_ptr<cql_transport::response, std::default_delete<seastar::foreign_ptr> > >&, seastar::future_state<std::default_delete<seastar::foreign_ptr> >&&)#1}, std::default_delete<seastar::foreign_ptr> >::run_and_dispose() at ././seastar/include/seastar/core/future.hh:781
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2345
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2752
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2921
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2804
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:265
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:156
scylla_main(int, char**) at ./main.cc:555
std::function<int (int, char**)>::operator()(int, char**) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) main at ./main.cc:1711
?? ??:0
_start at ??:?
```

**Comment by horschi** [comment] 2023-12-07 09:20
@mykaul : We have recently activated CQL compression, so it might be related to it.

**Comment by mykaul** [comment] 2023-12-07 09:20
> @mykaul : We have recently activated CQL compression, so it might be related to it.

We've released 5.4 yesterday, which (among many, many other features) has this - so please upgrade.

**Comment by horschi** [comment] 2023-12-26 14:44
13437 sounds like it.

I added some application side compression, that compresses some of the blobs in scylla (in addition to the CQL compression), and it seems to have resolved the issue. I assume because its reducing the required size of the buffers.

**Comment by mykaul** [comment] 2023-12-26 14:46
> 13437 sounds like it.
> 
> I added some application side compression, that compresses some of the blobs in scylla (in addition to the CQL compression), and it seems to have resolved the issue. I assume because its reducing the required size of the buffers.

You could upgrade to 5.4, which contains the fix. Or disable compression - if you have app-side compression, perhaps it's not useful at all.

**Comment by avikivity** [comment] 2023-12-27 14:58
Ugh sorry for not responding. But it indeed looks like a duplicate of #13437.

**Comment by avikivity** [comment] 2023-12-27 14:58
Closing as duplicate.

**Closed by avikivity** 2023-12-27 14:58 UTC
Labels: OSS Release/Triage
