### ISSUE TITLE
test_replace_reuse_ip is flaky

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#14885] opened 2023-07-30 15:14 UTC
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6322/

Test Result (4 failures / +4)Tests / Unit Tests / test_replace.test_replace_reuse_ip_using_host_idTests / Unit Tests / test_replace.test_replace_reuse_ipTests / Unit Tests / non-boost tests.topology.test_replace.debug.1Tests / Unit Tests / non-boost tests.topology.test_replace.debug.3
--
  | Identified problems
  | pytest failurea pytest failed: topology/test_replace.py::test_replace_reuse_ip_using_host_idIndication 1

[Test Result](https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6322/testReport/) (4 failures / +4)
[Tests / Unit Tests / test_replace.test_replace_reuse_ip_using_host_id](https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6322/testReport/junit/(root)/test_replace/Tests___Unit_Tests___test_replace_reuse_ip_using_host_id/)
[Tests / Unit Tests / test_replace.test_replace_reuse_ip](https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6322/testReport/junit/(root)/test_replace/Tests___Unit_Tests___test_replace_reuse_ip/)
[Tests / Unit Tests / non-boost tests.topology.test_replace.debug.1](https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6322/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___topology_test_replace_debug_1/)
[Tests / Unit Tests / non-boost tests.topology.test_replace.debug.3](https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6322/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___topology_test_replace_debug_3/)
	
Identified problems
pytest failure

a pytest failed: topology/test_replace.py::test_replace_reuse_ip_using_host_id
[Indication 1](https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6322/consoleFull#1997646587fcc21424-66d2-4bd8-8e0d-9746405e5b16)https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6322/

**Comment by benipeled** [comment] 2023-07-31 11:21
Seen also on build `aarch64` only - https://jenkins.scylladb.com/job/scylla-master/job/build/1554/

**Comment by benipeled** [comment] 2023-08-01 16:24
And now on next enterprise (x86) :/
https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2494/testReport/junit/(root)/test_replace/Tests___Unit_Tests___test_replace_reuse_ip_using_host_id/

**Comment by avikivity** [comment] 2023-08-01 19:59
@kostja P1ing

**Comment by Annamikhlin** [comment] 2023-08-08 09:24
Failed already few times on `master/build`.
last failure from today:
https://jenkins.scylladb.com/job/scylla-master/job/build/1562/testReport/junit/(root)/test_replace/Build__Test__Publish___buildTestPublishArm___test_replace_reuse_ip_using_host_id/

**Comment by patjed41** [comment] 2023-08-10 09:29
Investigated. Although it takes some time, these failures can be reproduced locally.

All test cases in `test_replace.py` are flaky and all are flaky for the same reasons. They fail because of the token ring and group 0 inconsistency. These tests are very simple:
- start a cluster with 3 nodes,
- stop one node,
- replace it with a new node.

The inconsistency is that the stopped node is not removed from group 0 as it should be.

The are two issues here.

The first issue is with `wait_for_token_ring_and_group0_consistency`. This function only checks the group 0 config once, at the beginning. However, it is possible that the replaced node is removed from it later, after the topology coordinator considers the replacing operation done. This can be easily fixed by changing `wait_for_token_ring_and_group0_consistency` so that it checks group 0 multiple times as it does for token ring.

The second issue is that the replaced node might never be removed from group 0 in these tests. The scenario is as follows:
- replacing starts,
- `handle_topology_transition` is called inside the topology coordinator's loop,
- the replaced node is marked as `left`,
- `handle_topology_transition` finishes **before** raft commits a config change that makes the replacing node a voter,
- the topology coordinator starts a new step of its loop,
- `cleanup_group0_config_if_needed` is called but since raft hasn't committed a change making the replacing node a voter yet, `if (!rconf.is_joint())` returns `false`, so the replace node isn't removed,
- the coordinator decides that it has nothing to do and starts sleeping on `co_await await_event();`,
- the replace operation has been the last event in the test, so the coordinator will never be awoken and the replaced node will never be removed.

This issue requires some changes in the topology coordinator. Probably, we want to remove the replaced node earlier, before the coordinator considers replacing done. Another approach could be to somehow change the coordinator's logic in a way that prevents sleeping before removing the `left` nodes.

cc @kbr-scylla @gleb-cloudius

**Comment by gleb-cloudius** [comment] 2023-08-10 09:37
There is no harm in having a node that was been replaced in the raft config until next topology operation if it is already non voter by this point. But I understand how this uncertainty  can harm tests. The solutions that I see are either add an ability to wait for config to become non joint and retry the cleanup or just do it on a timer (if cleanup did not run because of joint config, sleep with a timer and retry).

**Comment by kbr-scylla** [comment] 2023-08-10 09:43
Generally I agree that we should fix the coordinator so it doesn't incorrectly decide that there is no more work to do (e.g. if there are LEFT nodes that should be removed from configuration).

But for this particular problem of replace there's the easy fix of removing the replaced node during the replace operation, the same as we do for `removenode`:
```cpp
    future<bool> handle_topology_transition(group0_guard guard) {
...
            case topology::transition_state::write_both_read_new: {
...
                case node_state::removing:
                    co_await remove_from_group0(node.id);
```

so similarly for
```
                case node_state::replacing: {
```
we should add `remove_from_group0(replaced_node)`.

**Comment by avikivity** [comment] 2023-08-10 10:51
Nice progress. Note: if a flaky test implicates the code, then the flakiness is in that the test only failed occasionally, not every time. The test should be strengthened to fail more often with the unfixed code, if possible.

**Comment by patjed41** [comment] 2023-08-10 14:06
I sent a PR with Kamil's approach - #15009.

> Nice progress. Note: if a flaky test implicates the code, then the flakiness is in that the test only failed occasionally, not every time. The test should be strengthened to fail more often with the unfixed code, if possible.

After discussing it with @kbr-scylla, we concluded that it should be possible but not that simple, so I'll send it as a follow up.

**Closed** 2023-08-11 07:16 UTC
Labels: P1, CI-Stability

**Comment by avikivity** [comment] 2023-10-25 15:55
@kbr-scylla please advise if this needs to be backported to 5.2.

**Comment by kbr-scylla** [comment] 2023-10-26 10:59
- change applies only to raft-topology experimental mode
- the test became flaky after switching tests to use raft-topology, but the switch was not done on 5.2

so no need to backport
