### ISSUE TITLE
error in storage proxy after node rollbacked [storage_proxy -. * std::runtime_error (unknown exception)]

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#14882] opened 2023-07-30 08:10 UTC
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

after node rolling-upgrade--debian-buster-loader-node-1a9206a9-0-1 was rollbacked to older version,
we started seeing this errors on node-4 (which is still on the old version)

```
2023-07-29 05:44:32.949 <2023-07-29 05:44:32.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=73459c1c-86db-45a9-9308-168e2de07ba4: type=RUNTIME_ERROR regex=std::runtime_error line_number=15841 node=rolling-upgrade--debian-buster-db-node-1a9206a9-0-4
2023-07-29T05:44:32+00:00 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4      !ERR | scylla[3411]:  [shard 19] storage_proxy - Exception when communicating with 10.142.0.144, to read from keyspace1.standard1: std::runtime_error (unknown exception)
```

## Impact

It's confusing to the user, is the rollback failed ? or what is the status of the cluster currently 

## How frequently does it reproduce?

it happens across multiple of the rolling upgrades tests

## Installation details

Kernel Version: 4.19.0-24-cloud-amd64
Scylla version (or git commit hash): `5.3.0~rc0-20230523.3c3621db072d` with build-id `78cb9caaf1cdd0b37c3a38fa83548e6c4e3d4ab4`
Target Scylla version (or git commit hash): `5.4.0~dev-20230728.7351c8424df3` with build-id `d47e513b9bff8db5782a5220c05f5ac2a70b7a6c`

Cluster size: 4 nodes (n2-highmem-32)

Scylla Nodes used in this run:
- rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 (34.73.164.218 | 10.142.0.153) (shards: 30)
- rolling-upgrade--debian-buster-db-node-1a9206a9-0-3 (35.185.45.3 | 10.142.0.149) (shards: 30)
- rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 (34.148.223.133 | 10.142.0.144) (shards: 30)
- rolling-upgrade--debian-buster-db-node-1a9206a9-0-1 (35.196.106.103 | 10.142.0.135) (shards: 30)

OS / Image: `` (gce: undefined_region)

Test: `rolling-upgrade-debian10-test`
Test id: `1a9206a9-9f9b-4e76-859b-023425d64d71`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-debian10-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6e3d34cd1b9fc6533a4e5a3874fd36ad401b9a81/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 1a9206a9-9f9b-4e76-859b-023425d64d71`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1a9206a9-9f9b-4e76-859b-023425d64d71)
- Show all stored logs command: `$ hydra investigate show-logs 1a9206a9-9f9b-4e76-859b-023425d64d71`

## Logs:
- **db-cluster-1a9206a9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1a9206a9-9f9b-4e76-859b-023425d64d71/20230729_065943/db-cluster-1a9206a9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1a9206a9-9f9b-4e76-859b-023425d64d71/20230729_065943/db-cluster-1a9206a9.tar.gz)
- **sct-runner-events-1a9206a9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1a9206a9-9f9b-4e76-859b-023425d64d71/20230729_065943/sct-runner-events-1a9206a9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1a9206a9-9f9b-4e76-859b-023425d64d71/20230729_065943/sct-runner-events-1a9206a9.tar.gz)
- **sct-1a9206a9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1a9206a9-9f9b-4e76-859b-023425d64d71/20230729_065943/sct-1a9206a9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1a9206a9-9f9b-4e76-859b-023425d64d71/20230729_065943/sct-1a9206a9.log.tar.gz)
- **loader-set-1a9206a9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1a9206a9-9f9b-4e76-859b-023425d64d71/20230729_065943/loader-set-1a9206a9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1a9206a9-9f9b-4e76-859b-023425d64d71/20230729_065943/loader-set-1a9206a9.tar.gz)
- **monitor-set-1a9206a9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1a9206a9-9f9b-4e76-859b-023425d64d71/20230729_065943/monitor-set-1a9206a9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1a9206a9-9f9b-4e76-859b-023425d64d71/20230729_065943/monitor-set-1a9206a9.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-debian10-test/199/)
[Argus](https://argus.scylladb.com/test/5581b90e-e664-44ae-92ae-b996ca485251/runs?additionalRuns[]=1a9206a9-9f9b-4e76-859b-023425d64d71)
</details>

**Comment by mykaul** [comment] 2023-07-30 10:42
This is what I see in the other node at that time:
```
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] gossip - My status = NORMAL
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] gossip - Announcing shutdown
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] storage_service - Node 10.142.0.144 state jump to normal
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] gossip - Sending a GossipShutdown to 10.142.0.149 with generation 1690608853
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] gossip - Sending a GossipShutdown to 10.142.0.135 with generation 1690608853
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] gossip - Sending a GossipShutdown to 10.142.0.153 with generation 1690608853
Jul 29 05:44:32 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] rpc - client 10.142.0.153:55260 msg_id 2:  exception "gate closed" in no_wait handler ignored
Jul 29 05:44:32 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] rpc - client 10.142.0.153:55260 msg_id 3:  exception "gate closed" in no_wait handler ignored
Jul 29 05:44:33 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] rpc - client 10.142.0.153:55260 msg_id 4:  exception "gate closed" in no_wait handler ignored
Jul 29 05:44:33 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] gossip - Disable and wait for gossip loop started
Jul 29 05:44:34 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] gossip - failure_detector_loop: Finished main loop
Jul 29 05:44:34 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] gossip - Gossip is now stopped
Jul 29 05:44:34 rolling-upgrade--debian-buster-db-node-1a9206a9-0-2 scylla[1902]:  [shard  0] storage_service - Stop transport: stop_gossiping done
```

What's the bug?

Also it's clear it's disconnecting from node 4 - was it unexpected?
```
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard  0] gossip - Got shutdown message from 10.142.0.144, received_generation=1690608853, local_generation=1690608853
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard  0] gossip - InetAddress 10.142.0.144 is now DOWN, status = shutdown
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard  0] rpc - client 10.142.0.144:7001: client connection dropped: recv: Connection reset by peer
...
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard 19] rpc - client 10.142.0.144:7001: client connection dropped: recv: Connection reset by peer
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard 19] rpc - client 10.142.0.144:7001: client connection dropped: recv: Connection reset by peer
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard 16] storage_proxy - Exception when communicating with 10.142.0.144, to read from keyspace1.standard1: std::runtime_error (unknown exception)
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard 17] storage_proxy - Exception when communicating with 10.142.0.144, to read from keyspace1.standard1: std::runtime_error (unknown exception)
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard 17] storage_proxy - Exception when communicating with 10.142.0.144, to read from keyspace1.standard1: std::runtime_error (unknown exception)
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard 17] storage_proxy - Exception when communicating with 10.142.0.144, to read from keyspace1.standard1: std::runtime_error (unknown exception)
Jul 29 05:44:31 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard 20] storage_proxy - Exception when communicating with 10.142.0.144, to read from keyspace1.standard1: std::runtime_error (unknown exception)
...
Jul 29 05:44:32 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard 13] storage_proxy - Exception when communicating with 10.142.0.144, to read from keyspace1.standard1: std::runtime_error (unknown exception)
Jul 29 05:44:32 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard  9] storage_proxy - Exception when communicating with 10.142.0.144, to read from keyspace1.standard1: std::runtime_error (unknown exception)
Jul 29 05:44:32 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard  9] storage_proxy - Exception when communicating with 10.142.0.144, to read from keyspace1.standard1: std::runtime_error (unknown exception)
Jul 29 05:44:35 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard  0] raft_group_registry - marking Raft server 4a89e2e0-8149-4256-bf44-4d45247523cc as dead for raft groups
Jul 29 05:46:24 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard  0] raft_group_registry - marking Raft server 4a89e2e0-8149-4256-bf44-4d45247523cc as alive for raft groups
Jul 29 05:46:26 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard  0] storage_service - Node 10.142.0.144 state jump to normal
Jul 29 05:46:26 rolling-upgrade--debian-buster-db-node-1a9206a9-0-4 scylla[3411]:  [shard  0] gossip - InetAddress 10.142.0.144 is now UP, status = NORMAL
```

**Comment by DoronArazii** [comment] 2023-07-30 10:50
@asias please help with triaging this issue

**Comment by fruch** [comment] 2023-07-30 11:05
@mykaul 

the bug is that we don't expect this error print, any error print introduced without us knowing about is a regression (until proven otherwise), especiply something cryptic as "std::runtime_error (unknown exception)"

this kind of a print could hold off a production upgrade, (it did multiple times), until understood, those tests are trying to prevent that.

**Comment by asias** [comment] 2023-07-31 01:25
The error level log was from a cql read path.  The node 10.142.0.144 was shutdown.  It is ok to fail some of the reads to 10.142.0.144. But I am not sure why it got the unknown exception.  

```
    void error(gms::inet_address ep, std::exception_ptr eptr) {
        sstring why;
        bool disconnect = false;
        try {
            std::rethrow_exception(eptr);
        } catch (rpc::closed_error&) {
            // do not report connection closed exception, gossiper does that
            disconnect = true;
        } catch (rpc::timeout_error&) {
            // do not report timeouts, the whole operation will timeout and be reported
            return; // also do not report timeout as replica failure for the same reason
        } catch (semaphore_timed_out&) {
            // do not report timeouts, the whole operation will timeout and be reported
            return; // also do not report timeout as replica failure for the same reason
        } catch (timed_out_error&) {
            // do not report timeouts, the whole operation will timeout and be reported
            return; // also do not report timeout as replica failure for the same reason
        } catch(...) {
            slogger.error("Exception when communicating with {}, to read from {}.{}: {}", ep, _schema->ks_name(), _schema->cf_name(), eptr);
        }

        if (!_request_failed) { // request may fail only once.
            on_error(ep, disconnect);
        }
    }
```

**Comment by aleksbykov** [comment] 2023-10-17 16:28
Issue was reproduced in 
## Installation details

Kernel Version: 5.15.0-1036-aws
Scylla version (or git commit hash): `5.3.0~rc0-20230523.3c3621db072d` with build-id `ac735c65cfc09d37f3191db6df39e94b8ec0417b`
Target Scylla version (or git commit hash): `5.4.0~dev-20231006.498e3ec435be` with build-id `4946cafea6c2f76cfcf635bd60a90df4a5ed9f55`




Cluster size: 4 nodes (im4gn.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-cfad18a6-4 (176.34.201.247 | 10.4.3.62) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-cfad18a6-3 (3.254.113.250 | 10.4.1.100) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-cfad18a6-2 (54.216.101.209 | 10.4.0.184) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-cfad18a6-1 (63.33.210.123 | 10.4.2.187) (shards: 7)


OS / Image: `ami-0eb5875e5928452ba` (aws: undefined_region)

Test: `rolling-upgrade-ami-arm-test`
Test id: `cfad18a6-c8b7-4d36-aff3-12bcbea2090f`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-arm-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0ebb9363e3e989e2ef5097caaabb112319307511/test-cases/upgrades/rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor cfad18a6-c8b7-4d36-aff3-12bcbea2090f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=cfad18a6-c8b7-4d36-aff3-12bcbea2090f)
- Show all stored logs command: `$ hydra investigate show-logs cfad18a6-c8b7-4d36-aff3-12bcbea2090f`


## Logs:
- **db-cluster-cfad18a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cfad18a6-c8b7-4d36-aff3-12bcbea2090f/20231007_072442/db-cluster-cfad18a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cfad18a6-c8b7-4d36-aff3-12bcbea2090f/20231007_072442/db-cluster-cfad18a6.tar.gz)
- **sct-runner-events-cfad18a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cfad18a6-c8b7-4d36-aff3-12bcbea2090f/20231007_072442/sct-runner-events-cfad18a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cfad18a6-c8b7-4d36-aff3-12bcbea2090f/20231007_072442/sct-runner-events-cfad18a6.tar.gz)
- **sct-cfad18a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cfad18a6-c8b7-4d36-aff3-12bcbea2090f/20231007_072442/sct-cfad18a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cfad18a6-c8b7-4d36-aff3-12bcbea2090f/20231007_072442/sct-cfad18a6.log.tar.gz)
- **loader-set-cfad18a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cfad18a6-c8b7-4d36-aff3-12bcbea2090f/20231007_072442/loader-set-cfad18a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cfad18a6-c8b7-4d36-aff3-12bcbea2090f/20231007_072442/loader-set-cfad18a6.tar.gz)
- **monitor-set-cfad18a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cfad18a6-c8b7-4d36-aff3-12bcbea2090f/20231007_072442/monitor-set-cfad18a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cfad18a6-c8b7-4d36-aff3-12bcbea2090f/20231007_072442/monitor-set-cfad18a6.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-arm-test/71/)
[Argus](https://argus.scylladb.com/test/8e5f044d-57c2-43ad-8fe8-ac75a11a422d/runs?additionalRuns[]=cfad18a6-c8b7-4d36-aff3-12bcbea2090f)
</details>

**Comment by fruch** [comment] 2023-10-17 16:48
happened on multiple rolling upgrades this week

```
2023-10-14 05:38:58.404 <2023-10-14 05:38:58.349>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=b5083c62-0909-4a5d-b59e-a690e8e60843: type=RUNTIME_ERROR regex=std::runtime_error line_number=11353 node=rolling-upgrade--centos-db-node-e9674e0f-0-1
2023-10-14T05:38:58.349+00:00 rolling-upgrade--centos-db-node-e9674e0f-0-1      !ERR | scylla:  [shard 4] storage_proxy - Exception when communicating with 10.142.15.200, to read from keyspace1.standard1: std::runtime_error (unknown exception)
```

## Installation details

Kernel Version: 3.10.0-1160.99.1.el7.x86_64
Scylla version (or git commit hash): `5.3.0~rc0-20230523.3c3621db072d` with build-id `78cb9caaf1cdd0b37c3a38fa83548e6c4e3d4ab4`
Target Scylla version (or git commit hash): `5.4.0~dev-20231006.498e3ec435be` with build-id `16c6112202348a8adba536b4195d48adfdf958f9`




Cluster size: 4 nodes (n2-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--centos-db-node-e9674e0f-0-4 (35.231.101.254 | 10.142.15.200) (shards: 7)
- rolling-upgrade--centos-db-node-e9674e0f-0-3 (34.148.205.28 | 10.142.15.196) (shards: 7)
- rolling-upgrade--centos-db-node-e9674e0f-0-2 (34.139.244.171 | 10.142.15.194) (shards: 7)
- rolling-upgrade--centos-db-node-e9674e0f-0-1 (35.237.33.46 | 10.142.0.123) (shards: 7)


OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: undefined_region)

Test: `rolling-upgrade-centos7-test`
Test id: `e9674e0f-a1df-4cd0-9125-3c510e7de33e`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-centos7-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9d973065b179412f57dd2f493ddca78b644b76d0/test-cases/upgrades/rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor e9674e0f-a1df-4cd0-9125-3c510e7de33e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e9674e0f-a1df-4cd0-9125-3c510e7de33e)
- Show all stored logs command: `$ hydra investigate show-logs e9674e0f-a1df-4cd0-9125-3c510e7de33e`


## Logs:
- **db-cluster-e9674e0f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9674e0f-a1df-4cd0-9125-3c510e7de33e/20231014_065350/db-cluster-e9674e0f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9674e0f-a1df-4cd0-9125-3c510e7de33e/20231014_065350/db-cluster-e9674e0f.tar.gz)
- **sct-runner-events-e9674e0f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9674e0f-a1df-4cd0-9125-3c510e7de33e/20231014_065350/sct-runner-events-e9674e0f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9674e0f-a1df-4cd0-9125-3c510e7de33e/20231014_065350/sct-runner-events-e9674e0f.tar.gz)
- **sct-e9674e0f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9674e0f-a1df-4cd0-9125-3c510e7de33e/20231014_065350/sct-e9674e0f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9674e0f-a1df-4cd0-9125-3c510e7de33e/20231014_065350/sct-e9674e0f.log.tar.gz)
- **loader-set-e9674e0f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9674e0f-a1df-4cd0-9125-3c510e7de33e/20231014_065350/loader-set-e9674e0f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9674e0f-a1df-4cd0-9125-3c510e7de33e/20231014_065350/loader-set-e9674e0f.tar.gz)
- **monitor-set-e9674e0f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9674e0f-a1df-4cd0-9125-3c510e7de33e/20231014_065350/monitor-set-e9674e0f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9674e0f-a1df-4cd0-9125-3c510e7de33e/20231014_065350/monitor-set-e9674e0f.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/315/)
[Argus](https://argus.scylladb.com/test/3f60c813-ab37-4cea-b400-21e8d4fc6dc9/runs?additionalRuns[]=e9674e0f-a1df-4cd0-9125-3c510e7de33e)
</details>

**Comment by fruch** [comment] 2023-10-17 16:50
## Installation details

Kernel Version: 5.15.0-1036-aws
Scylla version (or git commit hash): `5.3.0~rc0-20230523.3c3621db072d` with build-id `ac735c65cfc09d37f3191db6df39e94b8ec0417b`
Target Scylla version (or git commit hash): `5.4.0~dev-20231006.498e3ec435be` with build-id `4946cafea6c2f76cfcf635bd60a90df4a5ed9f55`




Cluster size: 4 nodes (im4gn.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-bfc64497-4 (34.240.14.101 | 10.4.3.139) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-bfc64497-3 (54.171.21.65 | 10.4.3.218) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-bfc64497-2 (34.244.37.76 | 10.4.2.167) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-bfc64497-1 (52.215.220.203 | 10.4.0.246) (shards: 7)


OS / Image: `ami-0eb5875e5928452ba` (aws: undefined_region)

Test: `rolling-upgrade-ami-arm-test`
Test id: `bfc64497-c6e9-4eb0-b513-d59d5cde5f36`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-arm-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9d973065b179412f57dd2f493ddca78b644b76d0/test-cases/upgrades/rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor bfc64497-c6e9-4eb0-b513-d59d5cde5f36`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=bfc64497-c6e9-4eb0-b513-d59d5cde5f36)
- Show all stored logs command: `$ hydra investigate show-logs bfc64497-c6e9-4eb0-b513-d59d5cde5f36`


## Logs:
- **db-cluster-bfc64497.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bfc64497-c6e9-4eb0-b513-d59d5cde5f36/20231014_073123/db-cluster-bfc64497.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bfc64497-c6e9-4eb0-b513-d59d5cde5f36/20231014_073123/db-cluster-bfc64497.tar.gz)
- **sct-runner-events-bfc64497.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bfc64497-c6e9-4eb0-b513-d59d5cde5f36/20231014_073123/sct-runner-events-bfc64497.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bfc64497-c6e9-4eb0-b513-d59d5cde5f36/20231014_073123/sct-runner-events-bfc64497.tar.gz)
- **sct-bfc64497.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bfc64497-c6e9-4eb0-b513-d59d5cde5f36/20231014_073123/sct-bfc64497.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bfc64497-c6e9-4eb0-b513-d59d5cde5f36/20231014_073123/sct-bfc64497.log.tar.gz)
- **loader-set-bfc64497.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bfc64497-c6e9-4eb0-b513-d59d5cde5f36/20231014_073123/loader-set-bfc64497.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bfc64497-c6e9-4eb0-b513-d59d5cde5f36/20231014_073123/loader-set-bfc64497.tar.gz)
- **monitor-set-bfc64497.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bfc64497-c6e9-4eb0-b513-d59d5cde5f36/20231014_073123/monitor-set-bfc64497.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bfc64497-c6e9-4eb0-b513-d59d5cde5f36/20231014_073123/monitor-set-bfc64497.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-arm-test/72/)
[Argus](https://argus.scylladb.com/test/8e5f044d-57c2-43ad-8fe8-ac75a11a422d/runs?additionalRuns[]=bfc64497-c6e9-4eb0-b513-d59d5cde5f36)
</details>

**Comment by fruch** [comment] 2023-10-17 16:54
@asias 

this seems to be back, and happening across all upgrade tests, do we have any way to identify where it's coming from ?

**Comment by avikivity** [comment] 2023-10-17 18:02
It's somewhat expected, if a new node sends an exception to an old node it is converted to unknown_exception. See handle_mutation_failed() in storage_proxy.cc.

There's another question - whether an exception should have been generated in this scenario.

**Comment by avikivity** [comment] 2023-10-17 18:05
@piodul  please advise

could it be that during the de-exceptionization we lost the exception payload we had in rpc?

**Comment by piodul** [comment] 2023-10-17 20:26
@avikivity I think it's because of https://github.com/scylladb/scylladb/pull/14681. We used to have rolling upgrade test runs with lots of `abort_requested_exception` messages in the logs (https://github.com/scylladb/scylladb/issues/10447), so now don't type erase the exception but rather encode it properly and send it over the wire. Of course, as you already wrote, old versions of scylla won't be able to decode it, if a new replica reports this error to an old coordinator we wil get the "unknown exception" message.

We could have used a cluster feature to prevent the confusing message, but we decided not to do it [here](https://github.com/scylladb/scylladb/pull/14681#issuecomment-1640100332). In retrospect, I think the reasoning about the exception being rare was wrong - even though we don't need to actually pull the schema, this is only checked _after_ checking the abort source:

```c++
future<schema_ptr> migration_manager::get_schema_for_read(table_schema_version v, netw::messaging_service::msg_addr dst, netw::messaging_service& ms, abort_source* as) {
    return get_schema_for_write(v, dst, ms, as);
}

future<schema_ptr> migration_manager::get_schema_for_write(table_schema_version v, netw::messaging_service::msg_addr dst, netw::messaging_service& ms, abort_source* as) {
    if (_as.abort_requested()) {
        co_return coroutine::exception(std::make_exception_ptr(abort_requested_exception()));
    }

    auto s = local_schema_registry().get_or_null(v);

    if (s && s->is_synced()) {
        co_return s;
    }

    // ... do the actual schema pull here ...
}
```

So, this exception will commonly occur after `nodetool drain`.

cc: @kbr-scylla @patjed41

**Comment by fruch** [comment] 2023-10-17 21:31
so basically this is a temporary thing until we gonna have both versions (base and target/new) with https://github.com/scylladb/scylladb/pull/14681
 
so question is, is anyone gonna invest in fix it ? (or backporting), or we should ignore those until that time, or until next releases are out ?

**Comment by fruch** [comment] 2023-10-18 08:08
as I wrote on on the `Impact` section

> It's confusing to the user, is the rollback failed ? or what is the status of the cluster currently

**Comment by mykaul** [comment] 2023-10-18 08:16
> as I wrote on on the `Impact` section
> 
> > It's confusing to the user, is the rollback failed ? or what is the status of the cluster currently

The user doesn't look at the logs.

**Comment by fruch** [comment] 2023-10-18 08:24
> > as I wrote on on the `Impact` section
> > 
> > > It's confusing to the user, is the rollback failed ? or what is the status of the cluster currently
> 
> The user doesn't look at the logs.

A user and our support team that does an upgrade of a cluster is looking at them.

And countless times they were holding an upgrade to wait to check those kind of harmless prints. And in the worse case is was with more issues, and those are side tracking who investigating.

**Comment by fruch** [comment] 2023-10-18 08:26
Anyhow for any ignore, I need somone from the core team to approve, not deciding it on my own

**Comment by fruch** [comment] 2023-10-25 13:23
Still happening, still waiting for confirmation if this error print should be ignored

**Comment by fruch** [comment] 2023-10-29 15:34
> Still happening, still waiting for confirmation if this error print should be ignored

@mykaul still waiting for an answer about this one

**Comment by mykaul** [comment] 2023-10-29 15:47
@fruch - I think it's benign and we don't plan on fixing it, if it has no user visible impact.

**Comment by mykaul** [comment] 2023-12-25 11:10
Closing for the time being.

**Closed by mykaul** 2023-12-25 11:10 UTC
Labels: Regression, rolling-upgrades, Master/Triage, P2
