### ISSUE TITLE
Wrong result of adding a element and removing it from a collection (list) in a single UPDATE 

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylladb#10048] opened 2022-02-08 17:23 UTC
Scylla version (or git commit hash): fc17b8bf3bdd8b1183a601e7245132e060eff5cb

In a single `UPDATE` statement, you can specify multiple modifications of a non-frozen collection column, which I believe should be applied in order. However, if you add an element `X` and then remove element `X` from a collection (for example `LIST`) in a single `UPDATE`, it's not correctly applied:

```
CREATE KEYSPACE ks WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1};
CREATE TABLE ks.t(pk int, ck int, v list<int>, PRIMARY KEY(pk, ck));
INSERT INTO ks.t(pk, ck, v) VALUES (1, 2, []);
UPDATE ks.t SET v = v + [200], v = v - [200] WHERE pk = 1 AND ck = 2;
SELECT * FROM ks.t;

 pk | ck | v
----+----+-------
  1 |  2 | [200]

(1 rows)
```

This works correctly in Cassandra 3.11.8:
```
CREATE KEYSPACE ks WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1};
CREATE TABLE ks.t(pk int, ck int, v list<int>, PRIMARY KEY(pk, ck));
INSERT INTO ks.t(pk, ck, v) VALUES (1, 2, []);
UPDATE ks.t SET v = v + [200], v = v - [200] WHERE pk = 1 AND ck = 2;
SELECT * FROM ks.t;

 pk | ck | v
----+----+------
  1 |  2 | null

(1 rows)
```

**Comment by nyh** [comment] 2024-06-17 07:36
This is a duplicate of #7747. I'll close this one and update the older one with the new example.

**Closed** 2024-06-17 07:37 UTC
Labels: bug, area/cql, P2
