### ISSUE TITLE
After soft_reboot to one node all nodes marked as down and latency went to 40s

### ISSUE THREAD

**Issue by Mark-Gurevich** [scylladb/scylladb#13355] opened 2023-03-29 06:42 UTC
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

The job was running with raft enabled even though it should have been disabled.

At 2023-03-16 09:54:13 disrupt_soft_reboot nemesis started and rebooted node longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3 (10.4.3.143)

Scylla was initialised at 09:57:28 
Right after all nodes were marked as down.

```
023-03-16T09:57:28+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] init - Scylla version 2023.1.0~rc2-0.20230302.726f8a090337 initialization completed.
2023-03-16T09:58:42+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] raft_group_registry - marking Raft server 10f8a09b-7a74-4f2a-8b89-282ff620a856 as dead for raf
t groups
2023-03-16T09:58:42+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] raft_group_registry - marking Raft server 84d34178-a540-4a43-9ef6-7e9e5f3ea863 as dead for raf
t groups
2023-03-16T09:58:42+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] raft_group_registry - marking Raft server 26d0aeb4-33a5-482e-8da9-1482c1b1892d as dead for raft groups
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3  !WARNING | scylla[808]:  [shard  2] gossip - failure_detector_loop: Send echo to node 10.4.2.20, status = failed: seastar::rpc::timeout_error (rpc call timed out)
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  2] gossip - failure_detector_loop: Mark node 10.4.2.20 as DOWN
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3  !WARNING | scylla[808]:  [shard  1] gossip - failure_detector_loop: Send echo to node 10.4.2.71, status = failed: seastar::rpc::timeout_error (rpc call timed out)
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  1] gossip - failure_detector_loop: Mark node 10.4.2.71 as DOWN
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] gossip - InetAddress 10.4.2.20 is now DOWN, status = NORMAL
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] gossip - InetAddress 10.4.2.71 is now DOWN, status = NORMAL
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3  !WARNING | scylla[808]:  [shard  0] gossip - failure_detector_loop: Send echo to node 10.4.1.22, status = failed: seastar::rpc::timeout_error (rpc call timed out)
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] gossip - failure_detector_loop: Mark node 10.4.1.22 as DOWN
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] gossip - InetAddress 10.4.1.22 is now DOWN, status = NORMAL
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-31adfce0c27d11edb9ef4ad0ad130416/me-499170-big-Data.db to candidates
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  9] LeveledManifest - Adding high-level (L3) /var/lib/scylla/data/keyspace1/standard1-31adfce0c27d11edb9ef4ad0ad130416/me-497919-big-Data.db to candidates
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3  !WARNING | scylla[808]:  [shard  0] service_level_controller - update_from_distributed_data: failed to update configuration for more than  90 seconds : exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] raft_group_registry - marking Raft server 84d34178-a540-4a43-9ef6-7e9e5f3ea863 as alive for raft groups
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] raft_group_registry - marking Raft server 10f8a09b-7a74-4f2a-8b89-282ff620a856 as alive for raft groups
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3     !INFO | scylla[808]:  [shard  0] raft_group_registry - marking Raft server 26d0aeb4-33a5-482e-8da9-1482c1b1892d as alive for raft groups
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3  !WARNING | scylla[808]:  [shard  5] seastar - Exceptional future ignored: std::_Nested_exception<exceptions::authentication_exception> (authentication failed): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1), backtrace: 0x554b51e 0x554bad0 0x554bdb8 0x517cbe5 0x24d4a5c 0x51bf564 0x51c07e7 0x51e15d1 0x51918ba /opt/scylladb/libreloc/libc.so.6+0x8b12c /opt/scylladb/libreloc/libc.so.6+0x10cbbf
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3  !WARNING | scylla[808]:  [shard  5] seastar - Exceptional future ignored: std::_Nested_exception<exceptions::authentication_exception> (authentication failed): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1), backtrace: 0x554b51e 0x554bad0 0x554bdb8 0x517cbe5 0x24d4a5c 0x51bf564 0x51c07e7 0x51e15d1 0x51918ba /opt/scylladb/libreloc/libc.so.6+0x8b12c /opt/scylladb/libreloc/libc.so.6+0x10cbbf
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3  !WARNING | scylla[808]:  [shard  6] seastar - Exceptional future ignored: std::_Nested_exception<exceptions::authentication_exception> (authentication failed): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1), backtrace: 0x554b51e 0x554bad0 0x554bdb8 0x517cbe5 0x24d4a5c 0x51bf564 0x51c07e7 0x51e15d1 0x51918ba /opt/scylladb/libreloc/libc.so.6+0x8b12c /opt/scylladb/libreloc/libc.so.6+0x10cbbf
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3  !WARNING | scylla[808]:  [shard  5] seastar - Exceptional future ignored: std::_Nested_exception<exceptions::authentication_exception> (authentication failed): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1), backtrace: 0x554b51e 0x554bad0 0x554bdb8 0x517cbe5 0x24d4a5c 0x51bf564 0x51c07e7 0x51e15d1 0x51918ba /opt/scylladb/libreloc/libc.so.6+0x8b12c /opt/scylladb/libreloc/libc.so.6+0x10cbbf
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3  !WARNING | scylla[808]:  [shard  8] seastar - Exceptional future ignored: std::_Nested_exception<exceptions::authentication_exception> (authentication failed): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1), backtrace: 0x554b51e 0x554bad0 0x554bdb8 0x517cbe5 0x24d4a5c 0x51bf564 0x51c07e7 0x51e15d1 0x51918ba /opt/scylladb/libreloc/libc.so.6+0x8b12c /opt/scylladb/libreloc/libc.so.6+0x10cbbf
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3  !WARNING | scylla[808]:  [shard  6] seastar - Exceptional future ignored: std::_Nested_exception<exceptions::authentication_exception> (authentication failed): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1), backtrace: 0x554b51e 0x554bad0 0x554bdb8 0x517cbe5 0x24d4a5c 0x51bf564 0x51c07e7 0x51e15d1 0x51918ba /opt/scylladb/libreloc/libc.so.6+0x8b12c /opt/scylladb/libreloc/libc.so.6+0x10cbbf
2023-03-16T10:00:30+00:00 longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3  !WARNING | scylla[808]:  [shard  5] seastar - Exceptional future ignored: std::_Nested_exception<exceptions::authentication_exception> (authentication failed): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1), backtrace: 0x554b51e 0x554bad0 0x554bdb8 0x517cbe5 0x24d4a5c 0x51bf564 0x51c07e7 0x51e15d1 0x51918ba /opt/scylladb/libreloc/libc.so.6+0x8b12c /opt/scylladb/libreloc/libc.so.6+0x10cbbf
```

Seastar BACKTRACE:
```
[Backtrace #0]
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_3>(seastar::current_backtrace_tasklocal()::$_3&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:137
seastar::current_backtrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:170
seastar::report_failed_future(std::__exception_ptr::exception_ptr const&) at ./build/release/seastar/./seastar/src/core/future.cc:210
 (inlined by) seastar::report_failed_future(seastar::future_state_base::any&&) at ./build/release/seastar/./seastar/src/core/future.cc:218
seastar::future_state_base::any::check_failure() at ././seastar/include/seastar/core/future.hh:574
 (inlined by) seastar::future_state<auth::authenticated_user>::clear() at ././seastar/include/seastar/core/future.hh:623
 (inlined by) ~future_state at ././seastar/include/seastar/core/future.hh:628
 (inlined by) ~future at ././seastar/include/seastar/core/future.hh:1349
 (inlined by) ~ at ./transport/server.cc:817
 (inlined by) ~continuation at ././seastar/include/seastar/core/future.hh:764
 (inlined by) seastar::continuation<seastar::internal::promise_base_with_type<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >, cql_transport::cql_server::connection::process_auth_response(unsigned short, cql_transport::request_reader, service::client_state&, tracing::trace_state_ptr)::$_8::operator()(seastar::future<auth::authenticated_user>)::{lambda()#1}, seastar::future<void>::then_impl_nrvo<{lambda()#1}, seastar::future<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > > >({lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<std::unique_ptr<cql_transport::response, std::default_delete<cql_transport::response> > >&&, {lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>::run_and_dispose() at ././seastar/include/seastar/core/future.hh:785
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2509
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2946
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3115
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4326
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94>::_M_invoke(std::_Any_data const&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:290
std::function<void ()>::operator()() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:591
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:73
/data/scylla-s3-reloc.cache/by-build-id/efcc950cda22875aa488c5295c6cc68f35d9cc6f/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=81daba31ee66dbd63efdc4252a872949d874d136, for GNU/Linux 3.2.0, not stripped

start_thread at ??:?
__clone3 at :?
```

At the same time Cassandra Stress had errors :
```
2023-03-16 10:00:16.583: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=42542213-3f20-495d-a770-bcd6ee2ae514: type=ConsistencyError regex=Cannot achieve consistency level line_numb
er=710423 node=Node longevity-tls-1tb-7d-2023-1-loader-node-8ace7e5f-3 [3.252.190.121 | 10.4.3.55] (seed: False)
ERROR 10:00:16,056 Authentication error on host /10.4.3.143:9042: Cannot achieve consistency level for cl ONE. Requires 1, alive 0
2023-03-16 10:00:17.140: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=42542213-3f20-495d-a770-bcd6ee2ae514: type=ConsistencyError regex=Cannot achieve consistency level line_numb
er=710427 node=Node longevity-tls-1tb-7d-2023-1-loader-node-8ace7e5f-3 [3.252.190.121 | 10.4.3.55] (seed: False)
com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /10.4.3.143:9042: Cannot achieve consistency level for cl ONE. Requires 1, alive 0
2023-03-16 10:00:19.617: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=42542213-3f20-495d-a770-bcd6ee2ae514: type=ConsistencyError regex=Cannot achieve consistency level line_numb
er=29408 node=Node longevity-tls-1tb-7d-2023-1-loader-node-8ace7e5f-4 [34.253.80.230 | 10.4.1.137] (seed: False)
.
.
.
2023-03-16 10:04:32.794: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=852af2b4-094e-4aa9-a14f-2816aaaf4444: type=ConsistencyError regex=Cannot achieve consistency level line_number=87970 node=Node longevity-tls-1tb-7d-2023-1-loader-node-8ace7e5f-1 [3.252.189.73 | 10.4.1.148] (seed: False)
com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /10.4.3.143:9042: Cannot achieve consistency level for cl ONE. Requires 1, alive 0
```

Latency dropped to 40 seconds
![latency_40](https://user-images.githubusercontent.com/13746611/228287266-39758fde-42aa-410d-9b18-9f923cf45614.jpeg)

--

<br class="Apple-interchange-newline">

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1031-aws
Scylla version (or git commit hash): `2023.1.0~rc2-20230302.726f8a090337` with build-id `efcc950cda22875aa488c5295c6cc68f35d9cc6f`

Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-6 (3.250.3.58 | 10.4.0.180) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-5 (52.213.184.138 | 10.4.1.130) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-4 (34.242.11.155 | 10.4.2.20) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-3 (52.19.227.172 | 10.4.3.143) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-2 (52.214.166.243 | 10.4.2.71) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-8ace7e5f-1 (52.213.205.16 | 10.4.1.22) (shards: 14)

OS / Image: `ami-0336a5a646b08dc25` (aws: eu-west-1)

Test: `longevity-1tb-7days-test`
Test id: `8ace7e5f-6988-4f46-895b-6ee229dd35c5`
Test name: `longevity-1tb-7days-test`
Test config file(s):

- [longevity-1TB-5days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4ec1600f015410814cdbe6d94ce29af866d6ccda/test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 8ace7e5f-6988-4f46-895b-6ee229dd35c5`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=8ace7e5f-6988-4f46-895b-6ee229dd35c5)
- Show all stored logs command: `$ hydra investigate show-logs 8ace7e5f-6988-4f46-895b-6ee229dd35c5`

## Logs:
- **db-cluster-8ace7e5f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/db-cluster-8ace7e5f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/db-cluster-8ace7e5f.tar.gz)
- **email_data-8ace7e5f.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/email_data-8ace7e5f.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/email_data-8ace7e5f.json.tar.gz)
- **output-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/output-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/output-8ace7e5f.log.tar.gz)
- **debug-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/debug-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/debug-8ace7e5f.log.tar.gz)
- **events-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/events-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/events-8ace7e5f.log.tar.gz)
- **sct-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/sct-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/sct-8ace7e5f.log.tar.gz)
- **normal-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/normal-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/normal-8ace7e5f.log.tar.gz)
- **argus-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/argus-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/argus-8ace7e5f.log.tar.gz)
- **raw_events-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/raw_events-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/raw_events-8ace7e5f.log.tar.gz)
- **critical-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/critical-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/critical-8ace7e5f.log.tar.gz)
- **warning-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/warning-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/warning-8ace7e5f.log.tar.gz)
- **summary-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/summary-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/summary-8ace7e5f.log.tar.gz)
- **left_processes-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/left_processes-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/left_processes-8ace7e5f.log.tar.gz)
- **error-8ace7e5f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/error-8ace7e5f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/error-8ace7e5f.log.tar.gz)
- **monitor-set-8ace7e5f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/monitor-set-8ace7e5f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/monitor-set-8ace7e5f.tar.gz)
- **loader-set-8ace7e5f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/loader-set-8ace7e5f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8ace7e5f-6988-4f46-895b-6ee229dd35c5/20230319_124536/loader-set-8ace7e5f.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/disabled_raft/job/longevity-1tb-7days-test/2/)
</details>

**Comment by mykaul** [comment] 2023-03-29 10:16
@kostja - can your team look into this? It's unclear to me if the test is with or without Raft. @Mark-Gurevich  ?

**Comment by roydahan** [comment] 2023-03-29 11:17
The test is "with Raft" (consistent_cluster_management: true).

**Comment by kostja** [comment] 2023-04-03 09:19
com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /10.4.3.143:9042: Cannot achieve consistency level for cl ONE. Requires 1, alive 0

This has to do with configuration of auth tables. They should be replicated on more than one node to make the test available. Unfortunately, auth tables are still not using Raft.

**Comment by kostja** [comment] 2023-04-03 09:21
@Mark-Gurevich could you please either disable auth if it is not relevant for this test (use AllowAllAuthenticator) or properly replicate the auth tables? We plan to move over the auth tables to raft but this test shouldn't' wait for it, I think.

**Comment by kbr-scylla** [comment] 2023-04-03 09:28
> com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /10.4.3.143:9042: Cannot achieve consistency level for cl ONE. Requires 1, alive 0

> This has to do with configuration of auth tables. They should be replicated on more than one node to make the test available. Unfortunately, auth tables are still not using Raft.

Does this explain the 40s latency though?

**Comment by kostja** [comment] 2023-04-03 09:29
It is latency as seen by the test, so it can be a quirk of the test not being able to connect, since a conneciton pool is used under the hood.

**Comment by kostja** [comment] 2023-04-03 10:21
The way to go, however, is by isolating the problem, so auth issue should be addressed first.

**Comment by roydahan** [comment] 2023-04-03 16:16
From what we see this issue happens only for the scenario when we have auth enabled.
There is a related issue that we opened for the driver that also happened in this case: https://github.com/scylladb/java-driver/issues/209

**Comment by DoronArazii** [comment] 2023-04-05 11:10
@ptrsmrn can you please assign someone to check it

**Comment by DoronArazii** [comment] 2023-04-18 06:55
@eliransin ping, can someone pick this up (it's a P1 case).
Maybe at least give some first impression.

@elcallio authentication it's your area of expertise if I remember correctly.

**Comment by elcallio** [comment] 2023-04-18 21:43
@DoronArazii not really. I only did the initial transposition from cassandra. The current implementation was however not done by me. But I also am confused by the above behaviour; Auth queries should be done using LOCAL_ONE cl. There is however a very weird thing in the code which uses QUORUM for user named "cassandra". Is this the user being used here? Even so, since this is the default user, it should be readily available on all hosts in the cluster, assuming they are reachable. So not sure why this causes a query fail? Or is this another case of recent changes altering assumptions again?
I am not 100% buying this being an auth issue as such; This query should work assuming anything works.

**Comment by DoronArazii** [comment] 2023-04-27 06:29
@eliransin / @elcallio this case should block 5.2 ?

/Cc @avikivity @mykaul @roydahan

**Comment by mykaul** [comment] 2023-04-27 08:34
> @eliransin / @elcallio this case should block 5.2 ?
> 
> /Cc @avikivity @mykaul @roydahan

No - we should begin with ensuring the auth table are properly replicated in QA tests (I vaguely remember that they don't follow the docs there?).

**Comment by fgelcer** [comment] 2023-05-02 05:58
https://github.com/scylladb/scylla-cluster-tests/issues/6084

**Comment by mykaul** [comment] 2023-07-31 10:04
@Mark-Gurevich , @fgelcer - anything we need from QA here? After the changes to the auth table? In any case, moving this to 5.4, so we'll continue to look at it there.

**Comment by mykaul** [comment] 2023-10-22 14:10
ping @Mark-Gurevich , @fgelcer

**Comment by Mark-Gurevich** [comment] 2023-10-23 09:05
@mykaul I'm not sure about it. I know the issue [Do we set "system_auth_rf" correctly](https://github.com/scylladb/scylla-cluster-tests/issues/6084) is still open.

**Comment by mykaul** [comment] 2023-10-23 09:07
> @mykaul I'm not sure about it. I know the issue [Do we set "system_auth_rf" correctly](https://github.com/scylladb/scylla-cluster-tests/issues/6084) is still open.

@Mark-Gurevich - why is it open, while on QA tasks project it's marked Done? Let's bring it to completion and nail down this issue please.

**Comment by Mark-Gurevich** [comment] 2023-10-24 11:07
@mykaul I see Roy closed the issue spoken above yesterday.
[This](https://github.com/scylladb/scylla-cluster-tests/pull/6160)
I don't think anything else is needed from QA here.

**Comment by mykaul** [comment] 2023-10-24 12:20
So now we can't reproduce this issue?

**Comment by roydahan** [comment] 2023-10-24 17:48
> @mykaul I see Roy closed the issue spoken above yesterday. [This](https://github.com/scylladb/scylla-cluster-tests/pull/6160) fixed the `system_auth_rf`. I don't think anything else is needed from QA here.

Because it's done long ago as the issue stated.

**Closed** 2023-10-29 09:49 UTC
Labels: P1
