### ISSUE TITLE
Multiple coredumps on reader_permit::impl::on_evicted(): Assertion `_state == reader_permit::state::inactive' failed

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#12024] opened 2022-11-17 20:25 UTC
## Installation details

Kernel Version: 3.10.0-1160.76.1.el7.x86_64
Scylla version (or git commit hash): `5.1.0~rc3-20221009.9deeeb4db1cd` with build-id `4e3d124e4636ed9e7f88aeaace85c1ac637ed200`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla/relocatable/scylladb-5.1/scylla-x86_64-package-5.1.0-rc3.0.20221009.9deeeb4db1cd.tar.gz
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--centos-db-node-ce37ee0a-0-4 (35.229.73.69 | 10.142.0.142) (shards: 8)
- rolling-upgrade--centos-db-node-ce37ee0a-0-3 (34.74.89.57 | 10.142.0.122) (shards: 8)
- rolling-upgrade--centos-db-node-ce37ee0a-0-2 (35.185.52.247 | 10.142.0.107) (shards: 8)
- rolling-upgrade--centos-db-node-ce37ee0a-0-1 (34.148.60.51 | 10.142.0.102) (shards: 8)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: us-east1)

Test: `rolling-upgrade-centos7-test`
Test id: `ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-centos7-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9f6c413f87eae8e414ddfbbe44338a29d2a6712c/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

**>>>>>>>**

getting a coredump, during `Step8 - Run stress and verify after upgrading entire cluster` on all the nodes, multiple times:
here is the 1st assert i found in the logs:
```
Oct 22 08:29:11 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]:  [shard 6] create_table - TimeWindowCompactionStrategy tables without a default_time_to_live may potentially introduce too many windows. Ensure that insert statements specify a TTL (via USING TTL), 
when inserting data to this table. The restrict_twcs_without_default_ttl configuration option can be changed to silence this warning or make it into an error
Oct 22 08:29:11 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]:  [shard 0] create_table - TimeWindowCompactionStrategy tables without a default_time_to_live may potentially introduce too many windows. Ensure that insert statements specify a TTL (via USING TTL), 
when inserting data to this table. The restrict_twcs_without_default_ttl configuration option can be changed to silence this warning or make it into an error
Oct 22 08:29:25 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]:  [shard 3] reader_concurrency_semaphore - Semaphore _read_concurrency_sem with 100/100 count and 5157683/127171297 memory resources: timed out, dumping permit diagnostics:
                                                                            permits        count        memory        table/description/state
                                                                            100        100        5037K        scylla_bench.test/data-query/inactive
                                                                            44        0        0B        keyspace_complex.email_ind_index/data-query/waiting
                                                                            73        0        0B        keyspace_complex.user_with_ck/data-query/waiting
                                                                            586        0        0B        scylla_bench.test/data-query/waiting
                                                                            
                                                                            803        100        5037K        total
                                                                            
                                                                            Total: 803 permits with 100 count and 5037K memory resources
Oct 22 08:29:29 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]:  [shard 5] reader_concurrency_semaphore - Semaphore _read_concurrency_sem with 100/100 count and 4956925/127171297 memory resources: timed out, dumping permit diagnostics:
                                                                            permits        count        memory        table/description/state
                                                                            100        100        4841K        scylla_bench.test/data-query/inactive
                                                                            422        0        0B        keyspace_complex.email_ind_index/data-query/waiting
                                                                            869        0        0B        keyspace_complex.user_with_ck/data-query/waiting
                                                                            272        0        0B        scylla_bench.test/data-query/waiting
                                                                            
                                                                            1663        100        4841K        total
                                                                            
                                                                            Total: 1663 permits with 100 count and 4841K memory resources
Oct 22 08:29:30 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]:  [shard 7] reader_concurrency_semaphore - Semaphore _read_concurrency_sem with 100/100 count and 4984183/127171297 memory resources: timed out, dumping permit diagnostics:
                                                                            permits        count        memory        table/description/state
                                                                            100        100        4867K        scylla_bench.test/data-query/inactive
                                                                            1104        0        0B        keyspace_complex.user_with_ck/data-query/waiting
                                                                            208        0        0B        scylla_bench.test/data-query/waiting
                                                                            539        0        0B        keyspace_complex.email_ind_index/data-query/waiting
                                                                            
                                                                            1951        100        4867K        total
                                                                            
                                                                            Total: 1951 permits with 100 count and 4867K memory resources
Oct 22 08:35:08 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]:  [shard 5] reader_concurrency_semaphore - (rate limiting dropped 577 similar messages) Semaphore _read_concurrency_sem with 100/100 count and 5219356/127171297 memory resources: timed out, dumping p
ermit diagnostics:
                                                                            permits        count        memory        table/description/state
                                                                            100        100        5097K        scylla_bench.test/data-query/inactive
                                                                            1259        0        0B        scylla_bench.test/data-query/waiting
                                                                            
                                                                            1359        100        5097K        total
                                                                            
                                                                            Total: 1359 permits with 100 count and 5097K memory resources
Oct 22 08:35:09 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]:  [shard 6] reader_concurrency_semaphore - Semaphore _read_concurrency_sem with 100/100 count and 4079765/127171297 memory resources: timed out, dumping permit diagnostics:
                                                                            permits        count        memory        table/description/state
                                                                            100        100        3984K        scylla_bench.test/data-query/inactive
                                                                            1        0        0B        system.peers/shard-reader/waiting
                                                                            1214        0        0B        scylla_bench.test/data-query/waiting
                                                                            
                                                                            1315        100        3984K        total
                                                                            
                                                                            Total: 1315 permits with 100 count and 3984K memory resources
Oct 22 08:35:10 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]:  [shard 3] reader_concurrency_semaphore - (rate limiting dropped 592 similar messages) Semaphore _read_concurrency_sem with 100/100 count and 4064542/127171297 memory resources: timed out, dumping p
ermit diagnostics:
                                                                            permits        count        memory        table/description/state
                                                                            100        100        3969K        scylla_bench.test/data-query/inactive
                                                                            1        0        0B        system.peers/shard-reader/waiting
                                                                            1399        0        0B        scylla_bench.test/data-query/waiting
                                                                            
                                                                            1500        100        3969K        total
                                                                            
                                                                            Total: 1500 permits with 100 count and 3969K memory resources
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: scylla: reader_concurrency_semaphore.cc:213: void reader_permit::impl::on_evicted(): Assertion `_state == reader_permit::state::inactive' failed.
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: Aborting on shard 6.
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: Backtrace:
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: 0x4e45cb8
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: 0x4e75462
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: 0x7f6f8940ca1f
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: /opt/scylladb/libreloc/libc.so.6+0x3d2a1
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: /opt/scylladb/libreloc/libc.so.6+0x268a3
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: /opt/scylladb/libreloc/libc.so.6+0x26788
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: /opt/scylladb/libreloc/libc.so.6+0x35a15
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: 0x3b32f75
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: 0x3b35515
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: 0x4e5482d
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: 0x4e74ab8
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: 0x4e568a1
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: 0x4e75935
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: 0x4e28d7a
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: /opt/scylladb/libreloc/libpthread.so.0+0x92a4
Oct 22 08:35:14 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[30750]: /opt/scylladb/libreloc/libc.so.6+0x100322
Oct 22 08:36:38 rolling-upgrade--centos-db-node-ce37ee0a-0-1 systemd[1]: scylla-server.service: main process exited, code=killed, status=6/ABRT
Oct 22 08:36:38 rolling-upgrade--centos-db-node-ce37ee0a-0-1 systemd[1]: Unit scylla-server.service entered failed state.
Oct 22 08:36:38 rolling-upgrade--centos-db-node-ce37ee0a-0-1 systemd[1]: scylla-server.service failed.
Oct 22 08:36:39 rolling-upgrade--centos-db-node-ce37ee0a-0-1 systemd[1]: scylla-server.service holdoff time over, scheduling restart.
Oct 22 08:36:39 rolling-upgrade--centos-db-node-ce37ee0a-0-1 systemd[1]: Stopping Scylla JMX...
Oct 22 08:36:39 rolling-upgrade--centos-db-node-ce37ee0a-0-1 systemd[1]: scylla-jmx.service: main process exited, code=exited, status=143/n/a
Oct 22 08:36:39 rolling-upgrade--centos-db-node-ce37ee0a-0-1 systemd[1]: Stopped Scylla JMX.
Oct 22 08:36:39 rolling-upgrade--centos-db-node-ce37ee0a-0-1 systemd[1]: Unit scylla-jmx.service entered failed state.
Oct 22 08:36:39 rolling-upgrade--centos-db-node-ce37ee0a-0-1 systemd[1]: scylla-jmx.service failed.
Oct 22 08:36:39 rolling-upgrade--centos-db-node-ce37ee0a-0-1 systemd[1]: Stopped Scylla Server.
Oct 22 08:36:39 rolling-upgrade--centos-db-node-ce37ee0a-0-1 systemd[1]: Starting Scylla Server...
Oct 22 08:36:39 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[2579]: Scylla version 5.2.0~dev-0.20221021.dd0b571d7efc with build-id 1b0b5a47b197fed837c50467f4117483357cfe44 starting ...
Oct 22 08:36:39 rolling-upgrade--centos-db-node-ce37ee0a-0-1 scylla[2579]: command used: "/usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --num-io-queues=8 --io-properties-file=/etc/scylla.d/io_properties.yaml --lock-memory=1"
```

and the backtrace decoded:
```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:754
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:784
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:796
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3656
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3632
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3628
?? ??:0
/data/scylla-s3-reloc.cache/by-build-id/1b0b5a47b197fed837c50467f4117483357cfe44/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x3d2a1 
/data/scylla-s3-reloc.cache/by-build-id/1b0b5a47b197fed837c50467f4117483357cfe44/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x268a3 
/data/scylla-s3-reloc.cache/by-build-id/1b0b5a47b197fed837c50467f4117483357cfe44/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x26788 
/data/scylla-s3-reloc.cache/by-build-id/1b0b5a47b197fed837c50467f4117483357cfe44/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x35a15 
reader_permit::impl::on_evicted() at ./reader_concurrency_semaphore.cc:213
 (inlined by) reader_concurrency_semaphore::do_detach_inactive_reader(reader_concurrency_semaphore::inactive_read&, reader_concurrency_semaphore::evict_reason) at ./reader_concurrency_semaphore.cc:795
 (inlined by) reader_concurrency_semaphore::detach_inactive_reader(reader_concurrency_semaphore::inactive_read&, reader_concurrency_semaphore::evict_reason) at ./reader_concurrency_semaphore.cc:818
 (inlined by) operator() at ./reader_concurrency_semaphore.cc:875
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<reader_concurrency_semaphore::evict_readers_in_background()::$_4::operator()() const::{lambda()#2}&>(reader_concurrency_semaphore::evict_readers_in_background()::$_4::operator()() const::{lambda()#2}&) at ././seastar/include/seastar/core/future.hh:2149
 (inlined by) auto seastar::futurize_invoke<reader_concurrency_semaphore::evict_readers_in_background()::$_4::operator()() const::{lambda()#2}&>(reader_concurrency_semaphore::evict_readers_in_background()::$_4::operator()() const::{lambda()#2}&) at ././seastar/include/seastar/core/future.hh:2180
 (inlined by) seastar::future<void> seastar::do_until<reader_concurrency_semaphore::evict_readers_in_background()::$_4::operator()() const::{lambda()#2}, reader_concurrency_semaphore::evict_readers_in_background()::$_4::operator()() const::{lambda()#1}>(reader_concurrency_semaphore::evict_readers_in_background()::$_4::operator()() const::{lambda()#1}, reader_concurrency_semaphore::evict_readers_in_background()::$_4::operator()() const::{lambda()#2}) at ././seastar/include/seastar/core/loop.hh:343
 (inlined by) operator() at ./reader_concurrency_semaphore.cc:874
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<reader_concurrency_semaphore::evict_readers_in_background()::$_4>(reader_concurrency_semaphore::evict_readers_in_background()::$_4&&) at ././seastar/include/seastar/core/future.hh:2149
 (inlined by) auto seastar::futurize_invoke<reader_concurrency_semaphore::evict_readers_in_background()::$_4>(reader_concurrency_semaphore::evict_readers_in_background()::$_4&&) at ././seastar/include/seastar/core/future.hh:2180
 (inlined by) auto seastar::internal::invoke_func_with_gate<reader_concurrency_semaphore::evict_readers_in_background()::$_4>(seastar::gate&, reader_concurrency_semaphore::evict_readers_in_background()::$_4&&) at ././seastar/include/seastar/core/gate.hh:221
 (inlined by) auto seastar::with_gate<reader_concurrency_semaphore::evict_readers_in_background()::$_4>(seastar::gate&, reader_concurrency_semaphore::evict_readers_in_background()::$_4&&) at ././seastar/include/seastar/core/gate.hh:239
 (inlined by) reader_concurrency_semaphore::evict_readers_in_background() at ./reader_concurrency_semaphore.cc:873
 (inlined by) reader_concurrency_semaphore::maybe_admit_waiters() at ./reader_concurrency_semaphore.cc:946
reader_concurrency_semaphore::signal(reader_resources const&) at ./reader_concurrency_semaphore.cc:634
 (inlined by) reader_permit::impl::signal(reader_resources) at ./reader_concurrency_semaphore.cc:228
 (inlined by) reader_permit::impl::on_evicted() at ./reader_concurrency_semaphore.cc:216
 (inlined by) reader_concurrency_semaphore::do_detach_inactive_reader(reader_concurrency_semaphore::inactive_read&, reader_concurrency_semaphore::evict_reason) at ./reader_concurrency_semaphore.cc:795
 (inlined by) reader_concurrency_semaphore::detach_inactive_reader(reader_concurrency_semaphore::inactive_read&, reader_concurrency_semaphore::evict_reason) at ./reader_concurrency_semaphore.cc:818
 (inlined by) reader_concurrency_semaphore::evict(reader_concurrency_semaphore::inactive_read&, reader_concurrency_semaphore::evict_reason) at ./reader_concurrency_semaphore.cc:823
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:209
 (inlined by) void seastar::reactor::complete_timers<seastar::timer_set<seastar::timer<seastar::lowres_clock>, &seastar::timer<seastar::lowres_clock>::_link>, boost::intrusive::list<seastar::timer<seastar::lowres_clock>, boost::intrusive::member_hook<seastar::timer<seastar::lowres_clock>, boost::intrusive::list_member_hook<>, &seastar::timer<seastar::lowres_clock>::_link> >, seastar::reactor::do_expire_lowres_timers()::$_76>(seastar::timer_set<seastar::timer<seastar::lowres_clock>, &seastar::timer<seastar::lowres_clock>::_link>&, boost::intrusive::list<seastar::timer<seastar::lowres_clock>, boost::intrusive::member_hook<seastar::timer<seastar::lowres_clock>, boost::intrusive::list_member_hook<>, &seastar::timer<seastar::lowres_clock>::_link> >&, seastar::reactor::do_expire_lowres_timers()::$_76&&) at ./build/release/seastar/./seastar/src/core/reactor.cc:1368
 (inlined by) seastar::reactor::do_expire_lowres_timers() at ./build/release/seastar/./seastar/src/core/reactor.cc:2376
seastar::reactor::poll_once() at ./build/release/seastar/./seastar/src/core/reactor.cc:3002
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:2899
 (inlined by) bool std::__invoke_impl<bool, seastar::reactor::do_run()::$_44&>(std::__invoke_other, seastar::reactor::do_run()::$_44&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<bool, seastar::reactor::do_run()::$_44&>, bool>::type std::__invoke_r<bool, seastar::reactor::do_run()::$_44&>(seastar::reactor::do_run()::$_44&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:114
 (inlined by) std::_Function_handler<bool (), seastar::reactor::do_run()::$_44>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
std::function<bool ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2926
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4133
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_90>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:73
/data/scylla-s3-reloc.cache/by-build-id/1b0b5a47b197fed837c50467f4117483357cfe44/extracted/scylla/libexec/scylladb/libreloc/libpthread.so.0 0x92a4 
/data/scylla-s3-reloc.cache/by-build-id/1b0b5a47b197fed837c50467f4117483357cfe44/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x100322
```

the coredump details are here (i'm not 100% sure to map that assert above to the specific core, although the assert backtraces seem to be almost identical):
```
corefile_url=https://storage.cloud.google.com/upload.scylladb.com/core.scylla.997.a87e423c5cd7490ba90081ef7de76662.2579.1666427887000000/core.scylla.997.a87e423c5cd7490ba90081ef7de76662.2579.1666427887000000.gz
backtrace=           PID: 2579 (scylla)
           UID: 997 (scylla)
           GID: 1002 (scylla)
        Signal: 6 (ABRT)
     Timestamp: Sat 2022-10-22 08:38:07 UTC (1min 52s ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --num-io-queues=8 --io-properties-file=/etc/scylla.d/io_properties.yaml --lock-memory=1
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
          Unit: scylla-server.service
         Slice: scylla-server.slice
       Boot ID: a87e423c5cd7490ba90081ef7de76662
    Machine ID: b1527a5456aab241a74a8a3dc31395c0
      Hostname: rolling-upgrade--centos-db-node-ce37ee0a-0-1
      Coredump: /var/lib/systemd/coredump/core.scylla.997.a87e423c5cd7490ba90081ef7de76662.2579.1666427887000000
       Message: Process 2579 (scylla) of user 997 dumped core.
                
                Stack trace of thread 2586:
                #0  0x00007f099ddd82a2 raise (libc.so.6)
                #1  0x00007f099ddc18a4 abort (libc.so.6)
                #2  0x00007f099ddc1789 __assert_fail_base.cold (libc.so.6)
                #3  0x00007f099ddd0a16 __assert_fail (libc.so.6)
                #4  0x0000000003b32f76 _ZN28reader_concurrency_semaphore19maybe_admit_waitersEv (scylla)
                #5  0x0000000003b35516 _ZN28reader_concurrency_semaphore5evictERNS_13inactive_readENS_12evict_reasonE (scylla)
                #6  0x0000000004e5482e _ZN7seastar7reactor23do_expire_lowres_timersEv (scylla)
                #7  0x0000000004e74ab9 _ZNSt17_Function_handlerIFbvEZN7seastar7reactor6do_runEvE4$_44E9_M_invokeERKSt9_Any_data (scylla)
                #8  0x0000000004e568a2 _ZN7seastar7reactor6do_runEv (scylla)
                #9  0x0000000004e75936 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE4$_90E9_M_invokeERKSt9_Any_data (scylla)
                #10 0x0000000004e28d7b _ZN7seastar12posix_thread13start_routineEPv (scylla)
                #11 0x00007f099e9762a5 start_thread (libpthread.so.0)
                #12 0x00007f099de9b323 __clone (libc.so.6)
                
                Stack trace of thread 2592:
                #0  0x00007f099e97f94c read (libpthread.so.0)
                #1  0x0000000004e97765 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000004e97ac0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)
                #3  0x0000000004e28d7b _ZN7seastar12posix_thread13start_routineEPv (scylla)
                #4  0x00007f099e9762a5 start_thread (libpthread.so.0)
                #5  0x00007f099de9b323 __clone (libc.so.6)
                
                Stack trace of thread 2593:
                #0  0x00007f099de9058f __poll (libc.so.6)
                #1  0x0000000004e9a256 _ZN7seastar21reactor_backend_epoll26task_quota_timer_thread_fnEv (scylla)
                #2  0x00007f099e05eca4 execute_native_thread_routine (libstdc++.so.6)
                #3  0x00007f099e9762a5 start_thread (libpthread.so.0)
                #4  0x00007f099de9b323 __clone (libc.so.6)
                
                Stack trace of thread 2583:
                #0  0x00007f099de9b486 epoll_pwait (libc.so.6)
                #1  0x0000000004e9a70c _ZN7seastar21reactor_backend_epoll16wait_and_processEiPK10__sigset_t (scylla)
                #2  0x0000000004e9aae1 _ZN7seastar21reactor_backend_epoll23wait_and_process_eventsEPK10__sigset_t (scylla)
                #3  0x0000000004e56bdd _ZN7seastar7reactor6do_runEv (scylla)
                #4  0x0000000004e75936 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE4$_90E9_M_invokeERKSt9_Any_data (scylla)
                #5  0x0000000004e28d7b _ZN7seastar12posix_thread13start_routineEPv (scylla)
                #6  0x00007f099e9762a5 start_thread (libpthread.so.0)
                #7  0x00007f099de9b323 __clone (libc.so.6)
                
                Stack trace of thread 2589:
                #0  0x00007f099e97f94c read (libpthread.so.0)
                #1  0x0000000004e97765 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000004e97ac0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)
                #3  0x0000000004e28d7b _ZN7seastar12posix_thread13start_routineEPv (scylla)
                #4  0x00007f099e9762a5 start_thread (libpthread.so.0)
                #5  0x00007f099de9b323 __clone (libc.so.6)
                
                Stack trace of thread 2590:
                #0  0x00007f099de9058f __poll (libc.so.6)
                #1  0x0000000004e9a256 _ZN7seastar21reactor_backend_epoll26task_quota_timer_thread_fnEv (scylla)
                #2  0x00007f099e05eca4 execute_native_thread_routine (libstdc++.so.6)
                #3  0x00007f099e9762a5 start_thread (libpthread.so.0)
                #4  0x00007f099de9b323 __clone (libc.so.6)
                
                Stack trace of thread 2580:
                #0  0x00007f099de9b486 epoll_pwait (libc.so.6)
                #1  0x0000000004e9a70c _ZN7seastar21reactor_backend_epoll16wait_and_processEiPK10__sigset_t (scylla)
                #2  0x0000000004e9aa58 _ZN7seastar21reactor_backend_epoll18kernel_submit_workEv (scylla)
                #3  0x0000000004e74ab9 _ZNSt17_Function_handlerIFbvEZN7seastar7reactor6do_runEvE4$_44E9_M_invokeERKSt9_Any_data (scylla)
                #4  0x0000000004e568a2 _ZN7seastar7reactor6do_runEv (scylla)
                #5  0x0000000004e75936 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE4$_90E9_M_invokeERKSt9_Any_data (scylla)
                #6  0x0000000004e28d7b _ZN7seastar12posix_thr

download_instructions=gsutil cp gs://upload.scylladb.com/core.scylla.997.a87e423c5cd7490ba90081ef7de76662.2579.1666427887000000/core.scylla.997.a87e423c5cd7490ba90081ef7de76662.2579.1666427887000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.997.a87e423c5cd7490ba90081ef7de76662.2579.1666427887000000.gz
```

i spoke with @bhalevy about it, and he said to mention @denesb , as it could be related to 7fbad8de875816f0fb71ffa1965ba65543354629

more backtraces and coredumps can be found in the logs (in the `sct-runner-ce37ee0a.tar.gz` look at `error.log`)

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92)
- Show all stored logs command: `$ hydra investigate show-logs ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92`

## Logs:
- **db-cluster-ce37ee0a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92/20221022_091330/db-cluster-ce37ee0a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92/20221022_091330/db-cluster-ce37ee0a.tar.gz)
- **monitor-set-ce37ee0a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92/20221022_091330/monitor-set-ce37ee0a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92/20221022_091330/monitor-set-ce37ee0a.tar.gz)
- **loader-set-ce37ee0a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92/20221022_091330/loader-set-ce37ee0a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92/20221022_091330/loader-set-ce37ee0a.tar.gz)
- **sct-runner-ce37ee0a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92/20221022_091330/sct-runner-ce37ee0a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ce37ee0a-f5f1-4bf9-8c60-0ff854a10e92/20221022_091330/sct-runner-ce37ee0a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/258/)

**Comment by fgelcer** [comment] 2022-11-17 20:27
@bhalevy @denesb , it is failing on master rolling upgrades for the last 4 weeks. i will be checking now about other tests, if their coredumps are related...

**Comment by bhalevy** [comment] 2022-11-17 20:32
It looks like a recursive path where on_evicted is reentered after setting `_state = reader_permit::state::evicted`

**Comment by michoecho** [comment] 2022-11-17 20:49
Second duplicate of #11923.

**Comment by denesb** [comment] 2022-11-18 05:30
Duplicate of #11932

**Closed by denesb** 2022-11-18 05:30 UTC
Labels: master/triage

**Comment by bhalevy** [comment] 2022-11-18 13:06
> Duplicate of #11932

You mean, duplicate of #11923 :)
