### ISSUE TITLE
[test.py] assert not self.running fails in scylla_cluster.release_ips

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#15991] opened 2023-11-08 06:32 UTC
Seen in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4580
Full backtrace:
```
19:15:56  Traceback (most recent call last):
19:15:56    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1615, in workaround_python26789
19:15:56      code = await main()
19:15:56             ^^^^^^^^^^^^
19:15:56    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1582, in main
19:15:56      await run_all_tests(signaled, options)
19:15:56    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1365, in run_all_tests
19:15:56      await reap(done, pending, signaled)
19:15:56    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1342, in reap
19:15:56      result = coro.result()
19:15:56               ^^^^^^^^^^^^^
19:15:56    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 201, in run
19:15:56      await test.run(options)
19:15:56    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 957, in run
19:15:56      async with get_cluster_manager(self.mode + '/' + self.uname, self.suite.clusters, test_path) as manager:
19:15:56    File "/usr/lib64/python3.11/contextlib.py", line 211, in __aexit__
19:15:56      await anext(self.gen)
19:15:56    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/scylla_cluster.py", line 1329, in get_cluster_manager
19:15:56      await manager.stop()
19:15:56    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/scylla_cluster.py", line 1023, in stop
19:15:56      await self.clusters.put(self.cluster, is_dirty=True)
19:15:56    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/pool.py", line 104, in put
19:15:56      await self.destroy(obj)
19:15:56    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 369, in recycle_cluster
19:15:56      await cluster.release_ips()
19:15:56    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/scylla_cluster.py", line 656, in release_ips
19:15:56      assert not self.running
19:15:56  AssertionError
```

**Comment by mykaul** [comment] 2023-11-09 12:15
@kostja  - please assign someone to look at this please.

**Comment by mykaul** [comment] 2023-12-25 11:49
ping @kostja

**Comment by kostja** [comment] 2023-12-26 08:24
We have identified a possible root cause in https://github.com/scylladb/scylladb/issues/16472, closing as duplicate

**Closed** 2023-12-28 11:59 UTC
Labels: Master/Triage, test.py, CI-Stability
