### ISSUE TITLE
database_test.snapshot_works_okay fails sporadically

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#13662] opened 2023-04-24 17:08 UTC
HEAD: 642854f36f7686aea4a37ed62cf57025c81e61b8

```
bash-5.2# ./test.py --mode dev database_test --repeat 200
Found 6000 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
...
[5040/6000]  boost     dev   [ FAIL ] boost.database_test.snapshot_works.169
[5185/6000]  boost     dev   [ PASS ] boost.database_test.test_safety_after_truncate.174  
```

**Comment by avikivity** [comment] 2023-04-24 17:12
Also seen:

```
[5265/6000]  boost     dev   [ FAIL ] boost.database_test.test_distributed_loader_with_pending_delete.176
```

**Comment by DoronArazii** [comment] 2023-05-03 12:03
@bhalevy can you please assign someone | raising priority to p1

**Comment by bhalevy** [comment] 2023-05-03 20:16
> @bhalevy can you please assign someone | raising priority to p1

@denesb is reproducing database_test failures already

**Comment by denesb** [comment] 2023-05-04 08:35
Very likely a duplicate of https://github.com/scylladb/scylladb/issues/13660. Lets close and we will re-open if we see it in the wild after https://github.com/scylladb/scylladb/issues/13660 is fixed.

**Closed by denesb** 2023-05-04 08:35 UTC
Labels: test, P1, CI-Stability
