### ISSUE TITLE
test_cassandra_issue_10250 fails due to operation timeout

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#14655] opened 2023-07-12 07:06 UTC
```
self = <test.pylib.random_tables.RandomTable object at 0x7f1e22daa650>
name = 'c2', ctype = <class 'test.pylib.random_tables.IntType'>
column = <test.pylib.random_tables.Column object at 0x7f1e22daa910>

    async def add_column(self, name: str = None, ctype: Type[ValueType] = None, column: Column = None):
        """Add a value column to the table"""
        if column is not None:
            assert type(column) is Column, "Wrong column type to add_column"
        else:
            name = name if name is not None else f"v_{self.next_value_id():02}"
            ctype = ctype if ctype is not None else TextType
            column = Column(name, ctype=ctype)
        self.columns.append(column)
        assert self.manager.cql is not None
>       await self.manager.cql.run_async(f"ALTER TABLE {self.full_name} "
                                         f"ADD {column.name} {column.ctype.name}")
E       cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.152.174.25:9042

```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2411

- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2411/artifact/testlog/x86_64/debug/scylla-133.log
- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2411/artifact/testlog/x86_64/debug/scylla-151.log
- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2411/artifact/testlog/x86_64/debug/scylla-181.log

**Comment by kbr-scylla** [comment] 2023-07-12 10:58
Duplicate of https://github.com/scylladb/scylladb/issues/14612

**Closed by kbr-scylla** 2023-07-12 10:58 UTC
Labels: CI-Stability
