### ISSUE TITLE
Support for SELECT column['key'] 

### ISSUE THREAD

**Issue by kokizzu** [scylladb/scylladb#2448] opened 2017-06-06 14:10 UTC
Currently we can 

```
UPDATE tab SET col['key'] = ...
DELETE col['key'] FROM tab
```

but we can't 

```
SELECT col['key'] FROM tab
```

for `map<keytype,valtype>` data type,

**Comment by slivne** [comment] 2017-07-03 10:38
I tried the following on cassandra 2.2 / 3.0 - its not possible in cassandra CQL as well.

It may be supported by upstream cassandra toward 4.0 https://issues.apache.org/jira/browse/CASSANDRA-7396

```
create KEYSPACE ks with replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};
use ks;
create TABLE tb ( key text primary key, value map<text,text> );
insert into tb (key, value) values ('0',{'0': '0', '1' :'1'});
select value['0'] from tb where key='0';
```

**Comment by avikivity** [comment] 2020-08-05 16:08
Still unsupported.

**Comment by nyh** [comment] 2024-06-16 16:35
Three years later, I opened https://github.com/scylladb/scylladb/issues/7751 that is a duplicate of this one, but the newer issue is more complete, has a list of reproducing tests and also user's requests, so I'm closing this one as a duplicate.

**Closed by nyh** 2024-06-16 16:35 UTC
Labels: enhancement, area/cql, area/cassandra 4.x compatibility, good first issue
