### ISSUE TITLE
YCSB benchmark shows high Scylla P95 READ Latency in WRITE-heavy workload test 

### ISSUE THREAD

**Issue by temichus** [scylladb/scylladb#13449] opened 2023-04-06 08:44 UTC
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

in-scope of task  https://github.com/scylladb/qa-tasks/issues/851
I performed the same YCSB workload tests as BenchANT did and compare them against Cassandra's results.
Comparing shows that in a WRITE-heavy workload scenario (80% write/ 20% read), Scylla has higher P95 READ Latency (15ms) than Cassandra(12.7ms)

Scylla results:
```
[OVERALL], Throughput(ops/sec), 31562.565549908937
[READ], AverageLatency(us), 4709.9761448336
[READ], MinLatency(us), 254
[READ], MaxLatency(us), 1564671
[READ], 95thPercentileLatency(us), 15151
[READ], 99thPercentileLatency(us), 59519
[INSERT], AverageLatency(us), 2736.4024041831044
[INSERT], MinLatency(us), 236
[INSERT], MaxLatency(us), 1816575
[INSERT], 95thPercentileLatency(us), 9199
[INSERT], 99thPercentileLatency(us), 16127
```

Cassandra results
```
[OVERALL], Throughput(ops/sec), 20674.493614872645
[READ], AverageLatency(us), 5151.1509889765075
[READ], MinLatency(us), 264
[READ], MaxLatency(us), 2299903
[READ], 95thPercentileLatency(us), 12687
[READ], 99thPercentileLatency(us), 20895
[INSERT], AverageLatency(us), 4693.9253434609
[INSERT], MinLatency(us), 218
[INSERT], MaxLatency(us), 2303999
[INSERT], 95thPercentileLatency(us), 11599
[INSERT], 99thPercentileLatency(us), 18623
```

Cassandra's results/ Installation details from BenchANT - https://github.com/benchANT/mongodb-vs-cassandra-blog/tree/main/results/vanilla-vs-tuned_batch-0_cassandra_vanilla_write_initial_0_YwCv5P8i

Scylla results/logs -
```
+-----------------------------------------------------------------------------------------------------------------------------------------------+
|                                        Collected logs by test-id: 38c8a9b0-5daf-4663-ad9b-4c7eb7d051c9                                        |
+-------------+---------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                            |
+-------------+---------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/38c8a9b0-5daf-4663-ad9b-4c7eb7d051c9/20230404_111205/db-cluster-38c8a9b0.tar.gz  |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/38c8a9b0-5daf-4663-ad9b-4c7eb7d051c9/20230404_111205/sct-runner-38c8a9b0.tar.gz  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/38c8a9b0-5daf-4663-ad9b-4c7eb7d051c9/20230404_111205/monitor-set-38c8a9b0.tar.gz |
| loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/38c8a9b0-5daf-4663-ad9b-4c7eb7d051c9/20230404_111205/loader-set-38c8a9b0.tar.gz  |
+-------------+---------------------------------------------------------------------------------------------------------------------------------+
```
Restore Monitor Stack command: `$ hydra investigate show-monitor 38c8a9b0-5daf-4663-ad9b-4c7eb7d051c9`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=38c8a9b0-5daf-4663-ad9b-4c7eb7d051c9)

SCT yaml config -  https://github.com/temichus/scylla-cluster-tests/blob/benchANT/test-cases/performance/ycsb/bench_ant/scalability_testing/perf-benchANT-performance-WRITE-heavy.yaml
SCT test - https://github.com/temichus/scylla-cluster-tests/blob/benchANT/ycsb_bench_ant_performance_regression_test.py

YCSB run command - 
```
    bin/ycsb run scylla
    -p scylla.keyspace=ycsb -p scylla.username=cassandra
    -p scylla.password=cassandra -p scylla.writeconsistencylevel=ONE
    -p scylla.readconsistencylevel=ONE -p workload=site.ycsb.workloads.CoreWorkload
    -p maxexecutiontime=1800 -threads 100 -p recordcount=40000000 -p operationcount=90000000
    -p fieldcount=10 -p fieldlength=50 -p requestdistribution=zipfian -p insertorder=ordered
    -p readproportion=0.2 -p updateproportion=0.0 -p insertproportion=0.8 -p scanproportion=0.0
    -p scanlengthdistribution=uniform -p core_workload_insertion_retry_limit=3
    -p core_workload_insertion_retry_interval=3 -p insertstart=40000001 -t
```

## Installation details

- Scylla version: 5.1.6-0.20230223.530600a64674
- Cluster size: 3 nodes
- instance_type_db: 'i3.xlarge'
- instance_type_loader: 'c5.4xlarge'
- ami_id_db_scylla: ami-030c6d08802b88609

**Comment by michoecho** [comment] 2023-04-06 15:49
Scylla is overloaded in this setup. Latency measurements are meaningless when the system is overloaded.

![image](https://user-images.githubusercontent.com/45052050/230431226-d73f47ab-3723-4f4f-b26c-df81df0f1485.png)
![image](https://user-images.githubusercontent.com/45052050/230431305-e2abcff6-469b-4fa3-b9f2-ec20cb156ff9.png)

**Comment by mykaul** [comment] 2023-04-09 09:47
@temichus - can you please re-test, without overloading? Seems like Scylla's throughput in this scenario is 50% than C*, and I think it's reasonable that the latency will be somewhat higher.

Please re-open if you have new results - currently, this looks fine (to me).

**Comment by roydahan** [comment] 2023-04-09 11:44
What does it mean without overloading?
We use the exact same commands as the benchmark is claimed to be configured in their [blog](https://github.com/benchANT/mongodb-vs-cassandra-blog/tree/main/results/vanilla-vs-tuned_batch-0_cassandra_vanilla_write_initial_0_YwCv5P8i).
As much as I skeptical about their results, we're taking them for granted at the moment.

**Comment by mykaul** [comment] 2023-04-09 12:31
> What does it mean without overloading? We use the exact same commands as the benchmark is claimed to be configured in their [blog](https://github.com/benchANT/mongodb-vs-cassandra-blog/tree/main/results/vanilla-vs-tuned_batch-0_cassandra_vanilla_write_initial_0_YwCv5P8i). As much as I skeptical about their results, we're taking them for granted at the moment.

I mean - there's no bug here. If you get 50% higher throughput, it seems OK'ish to me that your P95 (and certainly P99 - it's even worse) will be worse than the other db. There are (from what I can see) 3 possibilities:
- substantially better throughput, and similar latency (which is what we see here, I believe)
- similar throughput and substantially better latency (which I've asked for as a separate test)
- Anything else, which may be an issue - but we don't see it here.
First two possibilities are not a bug.

**Comment by roydahan** [comment] 2023-04-09 18:08
So, I looked at the results from their blog and It looks like the [benchmark](https://github.com/benchANT/mongodb-vs-cassandra-blog/blob/main/results/vanilla-vs-tuned_batch-0_cassandra_vanilla_write_initial_0_YwCv5P8i/0_run.txt) doesn't use "target" flag for YCSB.
It means that it doesn't throttle the throughput for this test and comparing the latencies here is misleading (@temichus did they actually compared them in the blog for this scenario??).
For the same workload, Scylla did 31K op/s, Cassandra did 20K op/s and Mongo did 11K op/s.
So, it's not very comparable.

If we do want to compare latencies in this test (not sure we do), we can use "target" flag and set the same amount of op/s as Cassandra achieved (i.e. 20K) and result for sure will be better.

Closing the issue for now.

**Closed by roydahan** 2023-04-09 18:08 UTC

**Comment by michoecho** [comment] 2023-04-10 10:40
> So, I looked at the results from their blog and It looks like the [benchmark](https://github.com/benchANT/mongodb-vs-cassandra-blog/blob/main/results/vanilla-vs-tuned_batch-0_cassandra_vanilla_write_initial_0_YwCv5P8i/0_run.txt) doesn't use "target" flag for YCSB.
It means that it doesn't throttle the throughput for this test and comparing the latencies here is misleading

Exactly. They "throttled" by choosing a number of threads just big enough to arrive at a given CPU load. That's a terrible way to write a performance test for a queueing system.

**Comment by roydahan** [comment] 2023-04-13 09:28
@temichus what you can do in order to compare to Cassandra is to use the "-target" flag and set it to the throughput they got for Cassandra (20K).

**Comment by mykaul** [comment] 2023-04-13 12:39
> with the same ENV and Throughput
> Scylla has :
> READ P95 - 4 times lower Latency than C*
> INSERT P95 - 5.5 times lower Latency than C*

Kaboom!
