### ISSUE TITLE
coredump in make_streaming_consumer during shutdown, after view builder was already shut down

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#19133] opened 2024-06-06 08:22 UTC
https://jenkins.scylladb.com/view/master/job/scylla-master/job/tablets/job/dtest-release-with-tablets/9/testReport/bootstrap_test/TestBootstrap/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split002___test_cluster_become_unavailable_when_kill_node_during_bootstrap_gracefully_/

node-3 failure log:
```
INFO  2024-06-05 13:23:37,079 [shard 1:strm] repair - repair[7cde7518-6861-4473-aae8-1def4d09d21b]: Started to repair 1 out of 1 tables in keyspace=keyspace, table=standard1, table_id=bf019070-233e-11ef-baba-a47d15ed9b71, repair_reason=bootstrap
INFO  2024-06-05 13:23:37,086 [shard 0:main] compaction_manager - Asked to stop
INFO  2024-06-05 13:23:37,086 [shard 0:main] view_update_generator - Terminating background fiber
INFO  2024-06-05 13:23:37,086 [shard 0:main] service_level_controller - update_from_distributed_data: configuration polling loop aborted
INFO  2024-06-05 13:23:37,086 [shard 0:main] compaction_manager - Stopped
INFO  2024-06-05 13:23:37,086 [shard 0:strm] raft_topology - raft_state_monitor_fiber aborted with seastar::abort_requested_exception (abort requested)
INFO  2024-06-05 13:23:37,086 [shard 0:strm] raft_topology - cleanup fiber aborted
INFO  2024-06-05 13:23:37,086 [shard 1:main] compaction_manager - Asked to stop
INFO  2024-06-05 13:23:37,087 [shard 1:main] view_update_generator - Terminating background fiber
INFO  2024-06-05 13:23:37,087 [shard 1:main] compaction_manager - Stopped
WARN  2024-06-05 13:23:37,087 [shard 0:strm] repair - repair[7cde7518-6861-4473-aae8-1def4d09d21b]: Repair job aborted by user, job=7cde7518-6861-4473-aae8-1def4d09d21b, keyspace=keyspace, tables=["standard1"]
WARN  2024-06-05 13:23:37,087 [shard 0:strm] repair - repair[7cde7518-6861-4473-aae8-1def4d09d21b]: shard=0, keyspace=keyspace, cf=standard1, range=(9193830251816599482,+inf), got error in row level repair: seastar::abort_requested_exception (abort requested)
INFO  2024-06-05 13:23:37,087 [shard 0:main] init - Shutting down group 0 usage in local storage
INFO  2024-06-05 13:23:37,087 [shard 0:main] init - Shutting down group 0 usage in local storage was successful
INFO  2024-06-05 13:23:37,087 [shard 0:main] init - Shutting down storage service uninit address map
INFO  2024-06-05 13:23:37,087 [shard 0:main] init - Shutting down storage service uninit address map was successful
INFO  2024-06-05 13:23:37,087 [shard 0:main] init - Shutting down group 0 service
WARN  2024-06-05 13:23:37,087 [shard 0:strm] gossip - failure_detector_loop: Got error in the loop, live_nodes={127.0.14.1, 127.0.14.2}: seastar::sleep_aborted (Sleep is aborted)
INFO  2024-06-05 13:23:37,087 [shard 0:strm] gossip - failure_detector_loop: Finished main loop
INFO  2024-06-05 13:23:37,088 [shard 0:main] init - Shutting down group 0 service was successful
INFO  2024-06-05 13:23:37,088 [shard 0:main] init - Shutting down sstables loader API
WARN  2024-06-05 13:23:37,088 [shard 1:strm] repair - repair[7cde7518-6861-4473-aae8-1def4d09d21b]: Repair job aborted by user, job=7cde7518-6861-4473-aae8-1def4d09d21b, keyspace=keyspace, tables=["standard1"]
WARN  2024-06-05 13:23:37,088 [shard 1:strm] repair - repair[7cde7518-6861-4473-aae8-1def4d09d21b]: shard=1, keyspace=keyspace, cf=standard1, range=(9193830251816599482,+inf), got error in row level repair: seastar::abort_requested_exception (abort requested)
INFO  2024-06-05 13:23:37,088 [shard 0:main] init - Shutting down sstables loader API was successful
INFO  2024-06-05 13:23:37,088 [shard 0:main] init - Shutting down sstables loader
INFO  2024-06-05 13:23:37,088 [shard 0:main] init - Shutting down sstables loader was successful
INFO  2024-06-05 13:23:37,088 [shard 0:main] init - Shutting down view builder
INFO  2024-06-05 13:23:37,088 [shard 0:main] view - Stopping view builder
INFO  2024-06-05 13:23:37,088 [shard 0:main] view - Draining view builder
INFO  2024-06-05 13:23:37,088 [shard 1:main] view - Stopping view builder
INFO  2024-06-05 13:23:37,088 [shard 1:main] view - Draining view builder
INFO  2024-06-05 13:23:37,089 [shard 0:main] init - Shutting down view builder was successful
INFO  2024-06-05 13:23:37,089 [shard 0:main] init - Shutting down storage service notifications
INFO  2024-06-05 13:23:37,089 [shard 0:main] init - Shutting down storage service notifications was successful
INFO  2024-06-05 13:23:37,089 [shard 0:main] init - Shutting down system distributed keyspace
scylla: seastar/include/seastar/core/sharded.hh:799: Service &seastar::sharded<db::view::view_builder>::local() [Service = db::view::view_builder]: Assertion `local_is_initialized()' failed.
Aborting on shard 1, in scheduling group streaming.
Backtrace:
  0x5f4c338
  0x5f82aa1
  /jenkins/workspace/scylla-master/tablets/dtest-release-with-tablets/scylla/.ccm/scylla-repository/01ff8108c1b08bc9d15d4ebc0cc989b89baf15ee/libreloc/libc.so.6+0x3dbaf
  /jenkins/workspace/scylla-master/tablets/dtest-release-with-tablets/scylla/.ccm/scylla-repository/01ff8108c1b08bc9d15d4ebc0cc989b89baf15ee/libreloc/libc.so.6+0x8e883
  /jenkins/workspace/scylla-master/tablets/dtest-release-with-tablets/scylla/.ccm/scylla-repository/01ff8108c1b08bc9d15d4ebc0cc989b89baf15ee/libreloc/libc.so.6+0x3dafd
  /jenkins/workspace/scylla-master/tablets/dtest-release-with-tablets/scylla/.ccm/scylla-repository/01ff8108c1b08bc9d15d4ebc0cc989b89baf15ee/libreloc/libc.so.6+0x2687e
  /jenkins/workspace/scylla-master/tablets/dtest-release-with-tablets/scylla/.ccm/scylla-repository/01ff8108c1b08bc9d15d4ebc0cc989b89baf15ee/libreloc/libc.so.6+0x2679a
  /jenkins/workspace/scylla-master/tablets/dtest-release-with-tablets/scylla/.ccm/scylla-repository/01ff8108c1b08bc9d15d4ebc0cc989b89baf15ee/libreloc/libc.so.6+0x36186
  0x43f6ced
  0x43f62e3
  0x472c22d
  0x5f5c96f
  0x5f5df6a
  0x5f5f1e7
  0x5f830a0
  0x5f1e60a
  /jenkins/workspace/scylla-master/tablets/dtest-release-with-tablets/scylla/.ccm/scylla-repository/01ff8108c1b08bc9d15d4ebc0cc989b89baf15ee/libreloc/libc.so.6+0x8c946
  /jenkins/workspace/scylla-master/tablets/dtest-release-with-tablets/scylla/.ccm/scylla-repository/01ff8108c1b08bc9d15d4ebc0cc989b89baf15ee/libreloc/libc.so.6+0x11296f
```
test scenario:
```
13:23:04,055 698     bootstrap_test                 INFO     bootstrap_test.py   :753  | test_cluster_become_unavailable_when_kill_node_during_bootstrap[gracefully]: Starting stress command on node1: ['write', 'cl=TWO', 'duration=5s', '-rate', 'threads=10', '-log', 'interval=5', '-schema', 'replication(factor=2) keyspace=keyspace']
13:23:22,538 698     bootstrap_test                 INFO     bootstrap_test.py   :753  | test_cluster_become_unavailable_when_kill_node_during_bootstrap[gracefully]: Starting stress command on node1: ['write', 'cl=TWO', 'duration=30s', '-rate', 'threads=10', '-log', 'interval=5', '-schema', 'replication(factor=2) keyspace=keyspace']
13:23:22,538 698     bootstrap_test                 INFO     bootstrap_test.py   :763  | test_cluster_become_unavailable_when_kill_node_during_bootstrap[gracefully]: Adding new node
13:23:22,639 698     bootstrap_test                 INFO     bootstrap_test.py   :768  | test_cluster_become_unavailable_when_kill_node_during_bootstrap[gracefully]: Trying to find the following 'Starting to bootstrap|raft topology: start streaming|raft_topology - start streaming' message in logs of node 'node3'
13:23:22,646 698     ccm                            DEBUG    cluster.py          :754  | test_cluster_become_unavailable_when_kill_node_during_bootstrap[gracefully]: node3: Starting scylla: args=['/jenkins/workspace/scylla-master/tablets/dtest-release-with-tablets/scylla/.dtest/dtest-r2r8th56/test/node3/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/tablets/dtest-release-with-tablets/scylla/.dtest/dtest-r2r8th56/test/node3/conf/scylla.yaml', '--log-to-stdout', '1', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--logger-log-level', 'stream_session=debug', '--api-address', '127.0.14.3', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--overprovisioned', '--prometheus-address', '127.0.14.3', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=False wait_for_binary_proto=True
13:23:24,760 698     bootstrap_test                 INFO     bootstrap_test.py   :770  | test_cluster_become_unavailable_when_kill_node_during_bootstrap[gracefully]: Trying to find the following 'Beginning stream session|sync data for keyspace=keyspace, status=started' message in logs of node 'node3'
13:23:37,085 698     bootstrap_test                 INFO     bootstrap_test.py   :775  | test_cluster_become_unavailable_when_kill_node_during_bootstrap[gracefully]: {'Gracefully'} killing node'node3' (PID is '18621')
13:23:47,189 698     bootstrap_test                 INFO     bootstrap_test.py   :785  | test_cluster_become_unavailable_when_kill_node_during_bootstrap[gracefully]: Checking the following message 'gossip - Removed endpoint 127.0.14.3' exits in node 'node1'
13:23:47,189 698     bootstrap_test                 INFO     bootstrap_test.py   :785  | test_cluster_become_unavailable_when_kill_node_during_bootstrap[gracefully]: Checking the following message 'gossip - Removed endpoint 127.0.14.3' exits in node 'node2'
13:23:47,190 698     bootstrap_test                 INFO     bootstrap_test.py   :790  | test_cluster_become_unavailable_when_kill_node_during_bootstrap[gracefully]: Waiting until stress thread will finish running
```
coredump is found in:
https://jenkins.scylladb.com/job/scylla-master/job/tablets/job/dtest-release-with-tablets/9/artifact/logs-full.release.002/1717593866558_bootstrap_test.py%3A%3ATestBootstrap%3A%3Atest_cluster_become_unavailable_when_kill_node_during_bootstrap%5Bgracefully%5D/

**Comment by mykaul** [comment] 2024-06-06 08:38
@yarongilor - assuming the build ID is 7c641530a4e630e25ce1a3c89aa738d93a7aaf75 (please verify), the backtrace is 
```
Backtrace:
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:826
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:859
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:871
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:4076
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4052
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:4048
/data/scylla-s3-reloc.cache/by-build-id/7c641530a4e630e25ce1a3c89aa738d93a7aaf75/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=9148cab1b932d44ef70e306e9c02ee38d06cad51, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
__assert_fail_base.cold at ??:?
__assert_fail at ??:?
seastar::sharded<db::view::view_builder>::local() at ././seastar/include/seastar/core/sharded.hh:799
 (inlined by) operator() at ./streaming/consumer.cc:38
seastar::future<void> std::__invoke_impl<seastar::future<void>, streaming::make_streaming_consumer(seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::sharded<replica::database>&, seastar::sharded<db::view::view_builder>&, unsigned long, streaming::stream_reason, seastar::bool_class<sstables::offstrategy_tag>, utils::tagged_uuid<service::session_id_tag>)::$_0&, flat_mutation_reader_v2>(std::__invoke_other, streaming::make_streaming_consumer(seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::sharded<replica::database>&, seastar::sharded<db::view::view_builder>&, unsigned long, streaming::stream_reason, seastar::bool_class<sstables::offstrategy_tag>, utils::tagged_uuid<service::session_id_tag>)::$_0&, flat_mutation_reader_v2&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<seastar::future<void>, streaming::make_streaming_consumer(seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::sharded<replica::database>&, seastar::sharded<db::view::view_builder>&, unsigned long, streaming::stream_reason, seastar::bool_class<sstables::offstrategy_tag>, utils::tagged_uuid<service::session_id_tag>)::$_0&, flat_mutation_reader_v2>, seastar::future<void> >::type std::__invoke_r<seastar::future<void>, streaming::make_streaming_consumer(seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::sharded<replica::database>&, seastar::sharded<db::view::view_builder>&, unsigned long, streaming::stream_reason, seastar::bool_class<sstables::offstrategy_tag>, utils::tagged_uuid<service::session_id_tag>)::$_0&, flat_mutation_reader_v2>(streaming::make_streaming_consumer(seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::sharded<replica::database>&, seastar::sharded<db::view::view_builder>&, unsigned long, streaming::stream_reason, seastar::bool_class<sstables::offstrategy_tag>, utils::tagged_uuid<service::session_id_tag>)::$_0&, flat_mutation_reader_v2&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:114
 (inlined by) std::_Function_handler<seastar::future<void> (flat_mutation_reader_v2), streaming::make_streaming_consumer(seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::sharded<replica::database>&, seastar::sharded<db::view::view_builder>&, unsigned long, streaming::stream_reason, seastar::bool_class<sstables::offstrategy_tag>, utils::tagged_uuid<service::session_id_tag>)::$_0>::_M_invoke(std::_Any_data const&, flat_mutation_reader_v2&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:290
std::function<seastar::future<void> (flat_mutation_reader_v2)>::operator()(flat_mutation_reader_v2) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
 (inlined by) operator() at ./mutation_writer/multishard_writer.cc:88
 (inlined by) seastar::future<void> std::__invoke_impl<seastar::future<void>, mutation_writer::shard_writer::consume()::$_0&, mutation_fragment_v2*>(std::__invoke_other, mutation_writer::shard_writer::consume()::$_0&, mutation_fragment_v2*&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
 (inlined by) std::__invoke_result<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment_v2*>::type std::__invoke<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment_v2*>(mutation_writer::shard_writer::consume()::$_0&, mutation_fragment_v2*&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:96
 (inlined by) std::invoke_result<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment_v2*>::type std::invoke<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment_v2*>(mutation_writer::shard_writer::consume()::$_0&, mutation_fragment_v2*&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/functional:113
 (inlined by) auto seastar::internal::future_invoke<mutation_writer::shard_writer::consume()::$_0&, mutation_fragment_v2*>(mutation_writer::shard_writer::consume()::$_0&, mutation_fragment_v2*&&) at ././seastar/include/seastar/core/future.hh:1172
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1486
 (inlined by) void seastar::futurize<seastar::future<void> >::satisfy_with_result_of<seastar::future<mutation_fragment_v2*>::then_impl_nrvo<mutation_writer::shard_writer::consume()::$_0, seastar::future<void> >(mutation_writer::shard_writer::consume()::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&, seastar::future_state<mutation_fragment_v2*>&&)#1}::operator()(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&, seastar::future_state<mutation_fragment_v2*>&&) const::{lambda()#1}>(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&&) at ././seastar/include/seastar/core/future.hh:2017
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1482
 (inlined by) seastar::continuation<seastar::internal::promise_base_with_type<void>, mutation_writer::shard_writer::consume()::$_0, seastar::future<mutation_fragment_v2*>::then_impl_nrvo<mutation_writer::shard_writer::consume()::$_0, seastar::future<void> >(mutation_writer::shard_writer::consume()::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, mutation_writer::shard_writer::consume()::$_0&, seastar::future_state<mutation_fragment_v2*>&&)#1}, mutation_fragment_v2*>::run_and_dispose() at ././seastar/include/seastar/core/future.hh:748
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2694
seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:3157
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3325
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4568
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0>::_M_invoke(std::_Any_data const&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:290
std::function<void ()>::operator()() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:90
start_thread at ??:?
__clone3 at :?
```

Please provide it next time.

**Comment by mykaul** [comment] 2024-06-06 08:40
@asias - please take an initial look and assign to relevant team.

**Comment by bhalevy** [comment] 2024-06-11 10:14
@denesb / @asias were calling make_streaming_consumer during shutdown after the view builder has already been shut down.

@yarongilor the fact that this happened during `Shutting down system distributed keyspace` seems coincidental, probably just a matter of timing.  I'll edit the title to describe the symptom in a better way (I hope).

**Comment by asias** [comment] 2024-06-12 00:13
The relevant code:

```
std::function<future<> (flat_mutation_reader_v2)> make_streaming_consumer(
        sharded<db::view::view_builder>& vb,
) {
            auto use_view_update_path = co_await db::view::check_needs_view_update_path(vb.local(), db.local().get_token_metadata(), *cf, reason);
```

vb is stopped.

**Comment by denesb** [comment] 2024-06-12 05:05
Looks like shutdown order problem. Repair/Streaming is not stopped when the view builder was already stopped. /cc @xemul.

**Comment by denesb** [comment] 2024-06-12 05:12
Likely a regression introduced by https://github.com/scylladb/scylladb/pull/18706.

**Closed** 2024-06-12 18:33 UTC
Labels: P3, symptom/shutdown, area/tablets, symptom/crash
