### ISSUE TITLE
Scylla fails to startup with `seastar::sleep_aborted` after enospc

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylladb#11413] opened 2022-08-30 12:08 UTC
## Installation details

Kernel Version: 5.15.0-1017-aws
Scylla version (or git commit hash): `5.2.0~dev-20220822.fa7033bc2be5` with build-id `4c66b02f12d1bb1ae1903aa192e269c3a4351112`
Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-0046d985-9 (16.170.223.249 | 10.0.2.213) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-8 (13.48.29.183 | 10.0.3.200) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-7 (16.171.64.225 | 10.0.2.117) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-6 (13.51.233.255 | 10.0.3.98) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-5 (13.51.159.211 | 10.0.0.13) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-4 (13.48.24.210 | 10.0.1.127) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-3 (13.50.4.80 | 10.0.2.205) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-2 (13.50.16.241 | 10.0.2.30) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-13 (13.51.234.124 | 10.0.2.48) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-12 (13.49.77.125 | 10.0.1.150) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-11 (13.53.102.42 | 10.0.0.87) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-10 (13.51.170.156 | 10.0.0.103) (shards: 7)
- longevity-twcs-48h-master-db-node-0046d985-1 (13.51.178.145 | 10.0.1.36) (shards: 7)

OS / Image: `ami-01f560421aa059eb4` (aws: eu-north-1)

Test: `longevity-twcs-48h-test`
Test id: `0046d985-04f7-4622-9440-831e8742d111`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c416ba78fb1f8f55d3bc806e27ba9fbebd106818/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

**>>>>>>>**
ENOSPC on the node:
```
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8      !ERR | scylla[7597]:  [shard 2] storage_service - Shutting down communications due to I/O errors until operator intervention: Commitlog error: std::filesystem::__cxx11::filesystem_error (error system:28, filesystem error: open failed: No space left on device [/var/lib/scylla/hints/2/10.0.3.98/HintsLog-2-36028797019099747.log])
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8  !WARNING | scylla[7597]:  [shard 5] commitlog - Exception in segment reservation: storage_io_error (Storage I/O error: 28: filesystem error: open failed: No space left on device [/var/lib/scylla/hints/5/10.0.3.98/HintsLog-2-90071992547545699.log])
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8  !WARNING | scylla[7597]:  [shard 4] commitlog - Exception in segment reservation: storage_io_error (Storage I/O error: 28: filesystem error: open failed: No space left on device [/var/lib/scylla/hints/4/10.0.3.98/HintsLog-2-72057594038063715.log])
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8  !WARNING | scylla[7597]:  [shard 0] commitlog - Exception in segment reservation: storage_io_error (Storage I/O error: 28: filesystem error: open failed: No space left on device [/var/lib/scylla/hints/0/10.0.3.98/HintsLog-2-135779.log])
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8  !WARNING | scylla[7597]:  [shard 1] commitlog - Exception in segment reservation: storage_io_error (Storage I/O error: 28: filesystem error: open failed: No space left on device [/var/lib/scylla/hints/1/10.0.3.98/HintsLog-2-18014398509617763.log])
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8  !WARNING | scylla[7597]:  [shard 2] commitlog - Exception in segment reservation: storage_io_error (Storage I/O error: 28: filesystem error: open failed: No space left on device [/var/lib/scylla/hints/2/10.0.3.98/HintsLog-2-36028797019099747.log])
```
Coredump after not being able to flush memtable:
```
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8      !ERR | scylla[7597]:  [shard 6] table - Memtable flush failed due to: storage_io_error (Storage I/O error: 28: filesystem error: mkdir failed: No space left on device [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/20.sstable]). Aborting, at 0x505aede 0x505b3d0 0x505b6d8 0x1782246 0x17eb670 0x4cd1114 0x4cd24f7 0x4cf1545 0x4ca4eba /opt/scylladb/libreloc/libpthread.so.0+0x92a4 /opt/scylladb/libreloc/libc.so.6+0x100322
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]: Aborting on shard 6.
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]: Backtrace:
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   0x4cc1988
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   0x4cf1092
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   0x7f58be703a1f
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   /opt/scylladb/libreloc/libc.so.6+0x3d2a1
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   /opt/scylladb/libreloc/libc.so.6+0x268a3
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   0x1782280
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   0x17eb670
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   0x4cd1114
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   0x4cd24f7
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   0x4cf1545
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   0x4ca4eba
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   /opt/scylladb/libreloc/libpthread.so.0+0x92a4
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | scylla[7597]:   /opt/scylladb/libreloc/libc.so.6+0x100322
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | systemd[1]: Created slice system-systemd\x2dcoredump.slice.
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !INFO | systemd[1]: Started Process Core Dump (PID 14200/UID 0).
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8      !ERR | systemd-coredump[14201]: Cannot store coredump of 7597 (scylla): No space left on device
2022-08-23T17:07:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8     !CRIT | systemd-coredump[14201]: Process 7597 (scylla) of user 113 dumped core.
```

Commitlog parse errors:
```
2022-08-23T17:08:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8  !WARNING | scylla[14554]:  [shard 0] commitlog - Cannot parse the version of the file: CommitLog-2-72057594038063841.log
2022-08-23T17:08:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8  !WARNING | scylla[14554]:  [shard 0] commitlog - Cannot parse the version of the file: Recycled-CommitLog-2-54043195528581775.log
2022-08-23T17:08:31+00:00 longevity-twcs-48h-master-db-node-0046d985-8  !WARNING | scylla[14554]:  [shard 0] commitlog - Cannot parse the version of the file: CommitLog-2-54043195528581781.log
```
Startuo failure:

```
2022-08-23T17:08:49+00:00 longevity-twcs-48h-master-db-node-0046d985-8      !ERR | scylla[14554]:  [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
```

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 0046d985-04f7-4622-9440-831e8742d111`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=0046d985-04f7-4622-9440-831e8742d111)
- Show all stored logs command: `$ hydra investigate show-logs 0046d985-04f7-4622-9440-831e8742d111`

## Logs:
- **db-cluster-0046d985.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0046d985-04f7-4622-9440-831e8742d111/20220824_090614/db-cluster-0046d985.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0046d985-04f7-4622-9440-831e8742d111/20220824_090614/db-cluster-0046d985.tar.gz)
- **monitor-set-0046d985.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0046d985-04f7-4622-9440-831e8742d111/20220824_090614/monitor-set-0046d985.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0046d985-04f7-4622-9440-831e8742d111/20220824_090614/monitor-set-0046d985.tar.gz)
- **loader-set-0046d985.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0046d985-04f7-4622-9440-831e8742d111/20220824_090614/loader-set-0046d985.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0046d985-04f7-4622-9440-831e8742d111/20220824_090614/loader-set-0046d985.tar.gz)
- **sct-runner-0046d985.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0046d985-04f7-4622-9440-831e8742d111/20220824_090614/sct-runner-0046d985.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0046d985-04f7-4622-9440-831e8742d111/20220824_090614/sct-runner-0046d985.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/48/)

**Comment by KnifeyMoloko** [comment] 2022-08-30 12:08
Possibly related to: https://github.com/scylladb/scylladb/issues/11299

**Comment by DoronArazii** [comment] 2022-08-31 11:33
@bhalevy please have a look

**Comment by bhalevy** [comment] 2022-08-31 11:34
Duplicate of #11245

**Comment by bhalevy** [comment] 2022-08-31 11:35
fa7033bc2be5 does not include a980510654e5a504da1b58bf8398c05676e01572

**Closed by bhalevy** 2022-08-31 11:35 UTC
Labels: master/triage
