### ISSUE TITLE
replica::stale_topology_exception in replace_address_test.TestReplaceAddress.test_serve_writes_during_bootstrap[use_host_id-rbo_disabled]

### ISSUE THREAD

**Issue by Deexie** [scylladb/scylladb#18603] opened 2024-05-09 17:23 UTC
EDIT from @kbr-scylla:

logs present in this post: https://github.com/scylladb/scylladb/issues/18603#issuecomment-2221244883

```
E           AssertionError: Unexpected errors found: [('node4', ['ERROR 2024-05-08 22:59:08,924 [shard 0:stmt] storage_proxy - Exception when communicating with 127.0.44.1, to read from ks.cf: replica::stale_topology_exception (stale topology exception, caller version 9, callee fence version 10)', 'ERROR 2024-05-08 22:59:08,924 [shard 0:stmt] storage_proxy - Exception when communicating with 127.0.44.2, to read from ks.cf: replica::stale_topology_exception (stale topology exception, caller version 9, callee fence version 10)'])]
```
in test_serve_writes_during_bootstrap[use_host_id-rbo_disabled]

Related jenkins files:
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/1459/testReport/junit/replace_address_test/TestReplaceAddress/FullDtest___full_split006___test_serve_writes_during_bootstrap_use_host_id_rbo_disabled_/

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/1459/artifact/logs-full.release.006/1715209170299_replace_address_test.py%3A%3ATestReplaceAddress%3A%3Atest_serve_writes_during_bootstrap%5Buse_host_id-rbo_disabled%5D/node4.log

**Comment by Annamikhlin** [comment] 2024-07-10 19:12
seen again on https://jenkins.scylladb.com/job/scylla-6.0/job/next/138/testReport/junit/replace_address_test/TestReplaceAddress/Build___x86___dtest_with_topology_changes___test_serve_writes_during_bootstrap_use_host_id_rbo_disabled_/

logs:
[dtest-gw3.log](https://github.com/user-attachments/files/16167871/dtest-gw3.log)
[1720627605998_replace_address_test.py__TestReplaceAddress__test_serve_writes_during_bootstrap[use_host_id-rbo_disabled].zip](https://github.com/user-attachments/files/16167873/1720627605998_replace_address_test.py__TestReplaceAddress__test_serve_writes_during_bootstrap.use_host_id-rbo_disabled.zip)

**Comment by lsfreitas** [comment] 2024-11-20 10:54
Seen again on: https://jenkins.scylladb.com/job/scylla-master/job/next/8493/testReport/replace_address_test/TestReplaceAddress/Build___x86___dtest___test_serve_writes_during_bootstrap_use_endpoint_rbo_disabled_/

**Comment by lsfreitas** [comment] 2024-11-20 10:57
@dani-tweig @denesb I've spotted this issue again, not sure if there's anyone looking into this

**Comment by dani-tweig** [comment] 2024-11-20 11:52
@piodul, can you estimate how severe this problem is?

**Comment by piodul** [comment] 2024-11-20 12:15
> [@piodul](https://github.com/piodul), can you estimate how severe this problem is?

This seems to be a topology on raft issue, @kbr-scylla could you take a look?

**Comment by kostja** [comment] 2024-11-22 17:35
These are two unrelated failures, The original one is gone. 
Closing in favor of https://github.com/scylladb/scylladb/issues/21667

**Comment by kbr-scylla** [comment] 2024-11-25 12:18
@kostja the original is actually not gone, @Annamikhlin uploaded logs here: https://github.com/scylladb/scylladb/issues/18603#issuecomment-2221244883

It contains the error from original report 
```
16:06:45,998 707     dtest_setup                    ERROR    dtest_setup.py      :637  | test_serve_writes_during_bootstrap[use_host_id-rbo_disabled]: Unexpected errors found: [('node4', ['ERROR 2024-07-10 16:06:27,060 [shard 0:stmt] storage_proxy - Exception when communicating with 127.0.92.2, to read from ks.cf: replica::stale_topology_exception (stale topology exception, caller version 9, callee fence version 10)', 'ERROR 2024-07-10 16:06:27,059 [shard 0:stmt] storage_proxy - Exception when communicating with 127.0.92.1, to read from ks.cf: replica::stale_topology_exception (stale topology exception, caller version 9, callee fence version 10)'])]
```

reopening

**Comment by kbr-scylla** [comment] 2024-11-25 12:21
That said, the last failure with `replica::stale_topology_exception` was seen on Jul 10, over 4 months ago, it's possible that it is no longer happening

but we should search for similar issues and confirm, and take a look at the logs

**Comment by kostja** [comment] 2024-11-25 14:00
@kbr-scylla did you see the original error happen recently?

**Comment by kbr-scylla** [comment] 2024-11-25 14:36
No, I asked @bitpathfinder to find out if it was popping up

**Comment by bitpathfinder** [comment] 2024-11-25 15:32
Closing since the issue no longer reproduces (last seen in July).

**Closed by bitpathfinder** 2024-11-25 15:32 UTC
Labels: triage/master, symptom/ci stability
