### ISSUE TITLE
Delete data that only has a minority alive replicas should not be resurrected by repair

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/scylladb#15243] opened 2023-09-01 08:14 UTC
Suppose we have a table with three replicas 'r1, r2, r3', and a record 'item1' is deleted by a request with a consistency level of `QUORUM`. The deletion tombstone may only be recorded in two replica nodes 'r1' and 'r2'. In the absence of timely repair, another replica node 'r3' does not know that 'item1' has been deleted. After 10 days(Default `gc_grace_seconds`  ), all 'item1' related records on 'r1' and 'r2' will be cleaned up by compact. At this time, if we repair the table, 'item1' will be repaired into 3 copies because there is still a living copy in 'r3'. 

We used `CL=QUORUM` to **delete**. After the final data is resurrected , it can still be **read** through `CL=QUORUM`. This should not happen, I think using CL=ONE to read deleted data is acceptable, using CL=QUORUM to read and still success is unacceptable.

It seems that 'nodetool repair' has too high availability, and sometimes we don't want this to happen. I will suggest that delete data that only has a minority alive replicas should not be resurrected by repair, or the user has the power to choose whether to resurrect.

**Comment by mykaul** [comment] 2023-09-01 15:18
https://www.scylladb.com/2022/06/30/preventing-data-resurrection-with-repair-based-tombstone-garbage-collection/ describe the issue and the solution, I think (or am I missing something from your description?)

**Comment by nyh** [comment] 2023-09-18 19:47
I think @mykaul and @michoecho's answers are complete - this isn't a bug but rather a documented feature (you might call limitation) of how deletion interacts with Scylla's/Cassandra's eventual consistency with timestamp-based conflict resolution: Because of the eventual consistency, deletion needs to leave behind a "tombstone", and removing it can lead to resurrection exactly like you warned about. So  you can either never remove the tombstone, or remove it only after a repair. If you remove it before doing repair, you'll get resurrection.

So I'm closing this issue as working by design. If you think we missed something, feel free to reopen the issue or just add more comments and I can reopen it.

**Closed by nyh** 2023-09-18 19:47 UTC
