### ISSUE TITLE
Alternator roles do not cooperate with service levels

### ISSUE THREAD

**Issue by psarna** [scylladb/scylladb#11379] opened 2022-08-25 11:55 UTC
In alternator authentication we're capable of authenticating a user based on information kept in system_auth.roles table, but we actually only use this username for tracing purposes, and alternator is still executed on behalf of an "internal" user.

We should instead prepare an "authenticated" session when the alternator user authenticated, which would allow attaching service levels to alternator roles. Then, service level parameters can be effective even in alternator sessions.

To be more specific - here, we create an anonymous client state later used in lower layers:
https://github.com/scylladb/scylladb/blob/18fa5038b1e4f9506499c14a3b96ed7c5dc49d8c/alternator/server.cc#L410

What we should consider instead, is using an `authenticated_user` structure if this alternator request was signed by an authenticated user. Then, the user could benefit from service-level-specific configuration attached to their role.

/cc @nyh

**Comment by nyh** [comment] 2022-08-25 12:25
@tzach you asked me about this just a few days ago

**Comment by psarna** [comment] 2022-08-25 12:26
I think it might be quite trivial to add, but also tricky to test. I think I'll just send a PoC soon and we can use in as part of the discussion

**Comment by tzach** [comment] 2022-08-25 13:05
How would an alternator user will create roles and service level without access to CQL?

**Comment by psarna** [comment] 2022-08-25 13:22
No idea, but certainly possible - e.g. by providing a meta-virtual-table for such configurations. For now, it would only be possible by setting up service levels via cql

**Comment by nyh** [comment] 2022-08-25 14:34
Note that currently, the only way to actually add new accounts for authentication is also only by CQL. There's a chicken-and-egg problem: if you need to create an account to authenticate to the Alternator API, you can't use the Alternator API to create the account.

**Comment by nyh** [comment] 2022-08-25 15:44
I think this issue is closely related (I don't know if to go as far as calling it a duplicate, because the focus is different) to #5047 which is about using Scylla roles to implement ACLs in Alternator.
Probably the same implementation can be a base for solving both issues.

**Comment by AdamStawarz** [comment] 2022-09-07 14:19
@psarna do we have any timeline(ETA) for it ?

**Comment by psarna** [comment] 2022-09-07 15:29
I do - ETA for development is 0 hours, the series is in review: https://github.com/scylladb/scylladb/pull/11380 . It's likely it will be merged soon

**Comment by AdamStawarz** [comment] 2022-10-03 07:03
Because "Merging is blocked" and @psarna is not involved anymore, could someone tell me what is the plan for this patch ?

**Comment by nyh** [comment] 2022-10-19 21:12
@AdamStawarz Piotr's patch for this issue was forgotten, but now merged.

**Comment by arkgal** [comment] 2022-11-10 11:52
Additional questions from customer:

```
1. Comparing the "internal" user and the alternator role, what is the difference between them? Wondering any super privileges of the "internal" user
2. Is RBAC supported after this fix ? i.e. granting a role with read-only access, will it work for the alternator requests?
```

Can you please advise?
Thanks!

**Comment by nyh** [comment] 2022-11-10 12:47
@arkgal note that this is the open-source bug tracker, not the place for customer questions.
Anyway, my answers:
1. When authentication is enabled in Alternator (see the Authorization section in compatibility.md),  each request has to be signed by a value user (compatibility.md explains how the user names and passwords are determined). Before this patch, it didn't matter at all which of the valid users you authenticated as - everything else will be the same.
2.This patch adds code to remember for each request which user it was authenticated under. It will allow us later to do something with this information - like RBAC. But currently we don't do it, as far as I know (unless somehow it works automatically and I don't know, maybe @eliransin knows). The open issue about it is https://github.com/scylladb/scylladb/issues/5047,if there's more to be said about RBAC specifically, let's discuss it there.

**Closed by nyh** 2022-11-10 12:47 UTC
Labels: Backport candidate, Alternator

**Comment by nyh** [comment] 2022-12-04 22:17
I think I don't want to backport this change - I think it can be considered a feature, not a bug?
Unless someone else really wants this backported...

**Comment by avikivity** [comment] 2023-03-09 10:09
Not a bug, not backporting.
