### ISSUE TITLE
[5.2.12] Replacement of a DB node caused increased load of one of the existing nodes leading to write queries timeouts

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylladb#16469] opened 2023-12-19 15:53 UTC
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

`disrupt_terminate_and_replace_node` nemesis steps:
- Terminate a target DB node
- Sleep for 5 minutes letting the DB cluster to live with a dead DB node
- Add new DB node
- Trigger `node replace` operation

So, during the above nemesis on the step of `replacing` node we get huge latencies on the one of the existing DB nodes:

![Screenshot from 2023-12-19 17-38-04](https://github.com/scylladb/scylladb/assets/3796058/1e20efaf-8477-4547-a2d3-dd04a538b1dd)

And it led to the loader timeouts:
```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```

The problematic node logs at that time:
```
Dec 18 01:40:58 longevity-10gb-3h-5-2-db-node-eastus-6 scylla[858]:  [shard 3] compaction - [Compact keyspace1.standard1 79f4c520-9d46-11ee-8949-cfa9c5a64819] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-b96e29e09d3b11ee9c7fcc9bd19608b9/me-2173-big-Data.db:level=0]. 332MB to 166MB (~50% of original) in 6921ms = 48MB/s. ~1340672 total partitions merged to 670227.
Dec 18 01:41:50 longevity-10gb-3h-5-2-db-node-eastus-6 scylla[858]:  [shard 0] storage_service - replace[6b5fc8d2-5faf-49a8-b60b-96f631321f77]: Added replacing_node=10.0.0.14 to replace existing_node=10.0.0.7, coordinator=10.0.0.14
Dec 18 01:41:50 longevity-10gb-3h-5-2-db-node-eastus-6 scylla[858]:  [shard 0] token_metadata - Added node 10.0.0.14 as pending replacing endpoint which replaces existing node 10.0.0.7
Dec 18 01:42:21 longevity-10gb-3h-5-2-db-node-eastus-6 scylla[858]:  [shard 0] storage_service - replace[6b5fc8d2-5faf-49a8-b60b-96f631321f77]: Marked ops done from coordinator=10.0.0.14
Dec 18 01:42:22 longevity-10gb-3h-5-2-db-node-eastus-6 scylla[858]:  [shard 0] storage_service - Set host_id=fe961042-a84c-4cc3-a0fc-5a5b31ab2b1d to be owned by node=10.0.0.14
Dec 18 01:42:22 longevity-10gb-3h-5-2-db-node-eastus-6 scylla[858]:  [shard 0] storage_service - handle_state_normal: remove endpoint=10.0.0.7 token=-1168511761428216455
```

Other ok nodes logs:
```
Dec 18 01:40:38 longevity-10gb-3h-5-2-db-node-eastus-1 scylla[17122]:  [shard 2] compaction - [Compact keyspace1.standard1 6c690ec0-9d46-11ee-8eee-411e25d22c91] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-b96e29e09d3b11ee9c7fcc9bd19608b9/me-2088-big-Data.db:level=0]. 403MB to 221MB (~55% of original) in 9838ms = 40MB/s. ~1610752 total partitions merged to 877913.
Dec 18 01:41:50 longevity-10gb-3h-5-2-db-node-eastus-1 scylla[17122]:  [shard 0] storage_service - replace[6b5fc8d2-5faf-49a8-b60b-96f631321f77]: Added replacing_node=10.0.0.14 to replace existing_node=10.0.0.7, coordinator=10.0.0.14
Dec 18 01:41:50 longevity-10gb-3h-5-2-db-node-eastus-1 scylla[17122]:  [shard 0] token_metadata - Added node 10.0.0.14 as pending replacing endpoint which replaces existing node 10.0.0.7
Dec 18 01:42:21 longevity-10gb-3h-5-2-db-node-eastus-1 scylla[17122]:  [shard 0] storage_service - replace[6b5fc8d2-5faf-49a8-b60b-96f631321f77]: Marked ops done from coordinator=10.0.0.14
Dec 18 01:42:21 longevity-10gb-3h-5-2-db-node-eastus-1 scylla[17122]:  [shard 0] storage_service - Set host_id=fe961042-a84c-4cc3-a0fc-5a5b31ab2b1d to be owned by node=10.0.0.14
```

So, from the DB logs point of view no real diff, but load of that node (`green` on screenshots):

![Screenshot from 2023-12-19 17-38-36](https://github.com/scylladb/scylladb/assets/3796058/ac673176-d2d1-42d3-a45a-a4aeb558c8d8)
![Screenshot from 2023-12-19 17-37-41](https://github.com/scylladb/scylladb/assets/3796058/30b0e8d3-e1f6-44bd-bfa6-793a3e801b79)

## Impact

Write queries timeouts

## How frequently does it reproduce?

Observed first time.

## Installation details

Kernel Version: 5.15.0-1053-azure
Scylla version (or git commit hash): `5.2.12-20231217.5052890ae8ca` with build-id `7cdb9e283490ec1de4110b96b7dc1879ca609b1f`

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-5-2-db-node-3eaadb32-eastus-8 (20.169.190.55 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-5-2-db-node-3eaadb32-eastus-7 (52.142.15.153 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-5-2-db-node-3eaadb32-eastus-6 (20.163.234.123 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-5-2-db-node-3eaadb32-eastus-5 (20.163.234.109 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-5-2-db-node-3eaadb32-eastus-4 (20.163.234.47 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-5-2-db-node-3eaadb32-eastus-3 (20.163.234.44 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-5-2-db-node-3eaadb32-eastus-2 (20.163.233.249 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-5-2-db-node-3eaadb32-eastus-1 (20.163.233.222 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.2.12-x86_64-2023-12-18T00-20-16` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `3eaadb32-dc91-4e9c-8244-ca868ce68884`
Test name: `scylla-5.2/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4b1cff19ba2799019f2abfa623964ac6d4222701/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 3eaadb32-dc91-4e9c-8244-ca868ce68884`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=3eaadb32-dc91-4e9c-8244-ca868ce68884)
- Show all stored logs command: `$ hydra investigate show-logs 3eaadb32-dc91-4e9c-8244-ca868ce68884`

## Logs:
- **db-cluster-3eaadb32.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/db-cluster-3eaadb32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/db-cluster-3eaadb32.tar.gz)
- **sct-runner-events-3eaadb32.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/sct-runner-events-3eaadb32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/sct-runner-events-3eaadb32.tar.gz)
- **sct-3eaadb32.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/sct-3eaadb32.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/sct-3eaadb32.log.tar.gz)
- **monitor-set-3eaadb32.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/monitor-set-3eaadb32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/monitor-set-3eaadb32.tar.gz)
- **loader-set-3eaadb32.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/loader-set-3eaadb32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/loader-set-3eaadb32.tar.gz)
- **parallel-timelines-report-3eaadb32.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/parallel-timelines-report-3eaadb32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3eaadb32-dc91-4e9c-8244-ca868ce68884/20231218_020915/parallel-timelines-report-3eaadb32.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-10gb-3h-azure-test/34/)
[Argus](https://argus.scylladb.com/test/8c977b7f-0cad-49ba-a41d-604ac9130d59/runs?additionalRuns[]=3eaadb32-dc91-4e9c-8244-ca868ce68884)
</details>

**Comment by mykaul** [comment] 2023-12-19 15:58
Anything on the node logs?

**Comment by vponomaryov** [comment] 2023-12-19 16:00
> Anything on the node logs?

Nothing special as it is written in the bug description.
Only sudden big node load imbalance.

**Comment by mykaul** [comment] 2023-12-24 12:11
@asias - please have an initial assessment - only to see who needs to handle this further.

**Comment by mykaul** [comment] 2023-12-27 12:26
@asias - re-ping

**Comment by asias** [comment] 2023-12-28 06:39
We need to understand why there was a huge spike of writes to the cluster. It might be hints or c-s had a burts of writes for some reason. @mykaul I think core front team could take a look. @ptrsmrn.

**Comment by nuivall** [comment] 2023-12-28 13:45
Some findings:
- scylla reported latency differs from driver (6s vs 10s and more)
- cluster story seems to be more complicated, around 1 AM there are 3 InstanceDown alerts, not one.
- nonBalancedcqlTraffic alerts triggers earlier around 0:55 AM (not sure what it means, or how it is triggered)
- 1:41AM when new node is added (not sure what stage of "adding" is it) it seems the traffic stops:
![Screenshot from 2023-12-28 14-36-00](https://github.com/scylladb/scylladb/assets/2939488/87d21dae-0044-4f3c-b5a6-a80686a5143d)
So to me looks like either:
- cassandra stress deadlock
- scylla deadlock (I think much less likely)
- load just stops ?

**Comment by nuivall** [comment] 2023-12-28 13:48
an idea how to discard "cassandra stress deadlock" theory would be to try reproducing with our stress tester: https://github.com/scylladb/cql-stress

**Comment by ptrsmrn** [comment] 2023-12-29 14:27
@asias other than what Marcin wrote, we didn't see anything suspicious.

**Comment by mykaul** [comment] 2023-12-31 12:20
@roydahan  - please provide your opinion.

**Comment by mykaul** [comment] 2023-12-31 13:13
Q: do we replace with RBNO?

**Comment by vponomaryov** [comment] 2024-01-02 15:16
> Q: do we replace with RBNO?

Yes:
```
2023-12-17T23:31:03.366+00:00 longevity-10gb-3h-5-2-db-node-eastus-2     !INFO | scylla[14572]:  [shard 0] storage_service - enable_repair_based_node_ops=true, allowed_repair_based_node_ops={replace}
```

**Comment by roydahan** [comment] 2024-01-03 01:23
Looking at it now.
Meanwhile, restarted the job to have more datapoints.

**Comment by roydahan** [comment] 2024-01-03 12:40
The next run passed that point, it shouldn't be a blocker for 5.2.12, but we should continue looking into this test.

**Comment by mykaul** [comment] 2024-09-19 09:53
Closing for the time being. Please re-open if needed.

**Closed by mykaul** 2024-09-19 09:53 UTC
Labels: triage/oss, status/release blocker
