### ISSUE TITLE
[test.py][arm][debug mode] test_crash_topology_coordinator_before_streaming Node failed to start after replace was aborted for it by kill topology coordinator

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#17612] opened 2024-03-04 07:35 UTC
Scylla version: 5.5.0~dev-0.20240302. with build-id 7647765287058d0e6965b6223fb5599a73aea2e4
Cluster size: 5 nodes.

Test.py PR: https://github.com/scylladb/scylladb/pull/16197
Platform: arm
Instance type: im4gn.2xlarge

When i was investigating on arm architecture with debug mode why new test `test_crash_coordinator_before_streaming` failed, i created aws instance based on arm architecture and built scylla in debug mode with the PR. when i ran test, it become failed on latest step with backtrace (like a coredump). 
next steps were executed:
1. stop the node
2. set error injection to topology coordinator before streaming
3. start replace operation and wait when it will be aborted by crashing topology coordinator
4. wait while new topology coordinator will be elected
5. start node which was stopped for replace
and this node failed to start with Abort and traceback:
```
INFO  2024-03-04 06:54:17,196 [shard 0:strm] raft_topology - executing global topology command barrier_and_drain, excluded nodes: {70035666-6ca3-4f9b-bc9f-fd68680063e1}
DEBUG 2024-03-04 06:54:17,196 [shard 0:strm] raft_topology - send barrier_and_drain command with term 4 and index 7 to dcb6b7e9-2d7c-4131-b249-f1cf839ffd77/127.40.150.6
DEBUG 2024-03-04 06:54:17,196 [shard 0:strm] raft_topology - topology cmd rpc barrier_and_drain is called
DEBUG 2024-03-04 06:54:17,197 [shard 0:strm] raft_topology - send barrier_and_drain command with term 4 and index 7 to c250afdd-77ee-461c-8ea6-14b5793f2c2a/127.40.150.3
DEBUG 2024-03-04 06:54:17,197 [shard 0:strm] raft_topology - send barrier_and_drain command with term 4 and index 7 to 8f8812d4-46e7-4479-b375-9c9c356751cf/127.40.150.5
DEBUG 2024-03-04 06:54:17,197 [shard 0:strm] raft_topology - send barrier_and_drain command with term 4 and index 7 to 68830b64-0225-496d-8e6f-a516268a2fa4/127.40.150.4
DEBUG 2024-03-04 06:54:17,209 [shard 0:strm] raft_topology - Got raft_topology_cmd::barrier_and_drain, version 29, current version 29
DEBUG 2024-03-04 06:54:17,210 [shard 1:strm] raft_topology - Got raft_topology_cmd::barrier_and_drain, version 29, current version 29
DEBUG 2024-03-04 06:54:17,210 [shard 0:strm] raft_topology - raft_topology_cmd::barrier_and_drain done
DEBUG 2024-03-04 06:54:17,210 [shard 1:strm] raft_topology - raft_topology_cmd::barrier_and_drain done
INFO  2024-03-04 06:54:17,281 [shard 0:strm] raft_topology - updating topology state: advance fence version to 29
DEBUG 2024-03-04 06:54:17,325 [shard 0:strm] raft_topology - reload raft topology state
INFO  2024-03-04 06:54:17,524 [shard 0:strm] token_metadata - Added node 86e8f635-a167-49c8-9871-ce04b71e3722 as pending replacing endpoint which replaces existing node 70035666-6ca3-4f9b-bc9f-fd68680063e1
DEBUG 2024-03-04 06:54:17,611 [shard 0:strm] raft_topology - topology_state_load: the last committed CDC generation ID: (2024/03/04 06:52:44, cd503846-d9f3-11ee-77ae-87eaaba9131f)
Aborting on shard 0.
Backtrace:
  0xceee0e3
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x3f805af
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x3f8018b
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x3d62e13
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x3d93a23
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x3ec842f
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x3ec8777
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x3ec859b
  linux-vdso.so.1+0x9cf
  /lib64/libc.so.6+0x90a7f
  /lib64/libc.so.6+0x44b3f
  /lib64/libc.so.6+0x30287
  0x1eab7387
  0x1eab72fb
  0x1eab7077
  0x1eab699f
  0xe27ca9f
  0x1e8fb9d7
  0x105b62a7
  0x105b5e77
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x3d85167
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x3d8e233
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x3d91f5b
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x3d8fffb
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x37abd0f
  /home/ubuntu/scylla/build/debug/seastar/libseastar.so+0x37a9437
  0xcf8fb3b
  0xe03f79b
  0xe03f35f
  0xe03eb6f
  0xd1efa9b
  0xcf8d4e7
  /lib64/libc.so.6+0x3059b
  /lib64/libc.so.6+0x3066f
  0xcea80af

```
place were it failed:
```
        # kill coordinator during bootstrap
        logger.debug("Kill coordinator during bootstrap")
        nodes = await manager.running_servers()
        coordinator_host = await get_coordinator_host(manager)
        other_nodes = [srv for srv in nodes if srv.server_id != coordinator_host.server_id]
        new_node = await manager.server_add(start=False)
        await manager.api.enable_injection(coordinator_host.ip_addr, "crash_coordinator_before_stream", one_shot=True)
        await manager.server_start(new_node.server_id,
                                   expected_error="Startup failed: std::runtime_error")
        await wait_new_coordinator_elected(manager, 4, time.time() + 60)
        await manager.server_restart(coordinator_host.server_id)
        await check_token_ring_and_group0_consistency(manager)
    
        # kill coordinator during replace
        logger.debug("Kill coordinator during replace")
        nodes = await manager.running_servers()
        coordinator_host = await get_coordinator_host(manager)
        other_nodes = [srv for srv in nodes if srv.server_id != coordinator_host.server_id]
        node_to_replace_srv_id = other_nodes[-1].server_id
        await manager.server_stop_gracefully(node_to_replace_srv_id)
        await manager.api.enable_injection(coordinator_host.ip_addr, "crash_coordinator_before_stream", one_shot=True)
        replace_cfg = ReplaceConfig(replaced_id = node_to_replace_srv_id, reuse_ip_addr = False, use_host_id = True)
        new_node = await manager.server_add(start=False, replace_cfg=replace_cfg)
        await manager.server_start(new_node.server_id, expected_error="Replace failed. See earlier errors")
    
        await wait_new_coordinator_elected(manager, 5, time.time() + 60)
>       await manager.server_restart(node_to_replace_srv_id, wait_others=1)

```

All test logs : 
[test_with_backtrace.tar.gz](https://github.com/scylladb/scylladb/files/14477919/test_with_backtrace.tar.gz)

the same test passed for x86_architecture for dev and debug modes

**Comment by kbr-scylla** [comment] 2024-03-04 10:22
@aleksbykov I cannot decode the backtrace using http://backtrace.scylladb.com/index.html, it looks like the binary used was not uploaded to the binaries repository.

Please reproduce and use the binary you built to decode the backtrace using [seastar-addr2line](https://github.com/scylladb/seastar/blob/master/scripts/seastar-addr2line) tool
`seastar/scripts/seastar-addr2line -e <path-to-binary>`
then paste the trace

OR upload the binary (build-id 7647765287058d0e6965b6223fb5599a73aea2e4) somewhere and paste link here so I can decode

**Comment by kbr-scylla** [comment] 2024-03-13 16:57
@aleksbykov ping see above, would it be possible to reproduce and  provide binary or decoded backtrace?

**Comment by aleksbykov** [comment] 2024-03-14 05:45
@kbr-scylla , after i fix test in related PR, the issue was not reproduced. i will try to reproduced with old test code and update status here

**Comment by kbr-scylla** [comment] 2024-03-14 12:26
Ok, thanks

**Comment by kbr-scylla** [comment] 2024-04-25 12:30
If we no longer have a way to reproduce it, I'll close the issue.

**Comment by aleksbykov** [comment] 2024-04-26 07:41
@kbr-scylla , i reproduce the issue. You can run these job:
https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/2244/artifact/testlog/aarch64/dev/
with rebuild, it allow to reproduce

**Comment by kbr-scylla** [comment] 2024-04-26 09:12
Branch with modified version of the test to reproduce: https://github.com/aleksbykov/scylla/commits/reproduce-17612/

**Comment by kbr-scylla** [comment] 2024-05-06 07:35
> The test in this branch is broken. It tries to restart a nodes that previously we started replace operation on. The node is banned.

Still, we should not have assertion errors.

**Comment by gleb-cloudius** [comment] 2024-05-06 07:38
> > The test in this branch is broken. It tries to restart a nodes that previously we started replace operation on. The node is banned.
> 
> Still, we should not have assertion errors.

The only assertion errors I saw were error injections. We need to change error injection code to print something before aborting.

**Comment by kbr-scylla** [comment] 2024-05-06 07:42
Ah, so this comes from error injection?
```
DEBUG 2024-04-25 22:47:51,969 [shard 0:strm] raft_topology - topology_state_load: the last committed CDC generation ID: (2024/04/25 19:47:51, b3508f1e-033c-11ef-66bc-ee7c3646817a)
Aborting on shard 0.
Backtrace:
  /jenkins/workspace/scylla-master/byo/byo_build_tests_dtest/scylla/build/dev/seastar/libseastar.so+0x405917
  /jenkins/workspace/scylla-master/byo/byo_build_tests_dtest/scylla/build/dev/seastar/libseastar.so+0x42d363
  linux-vdso.so.1+0x7db
  /lib64/libc.so.6+0x90a7f
  /lib64/libc.so.6+0x44b3f
  /lib64/libc.so.6+0x30287
  0x27a923b
  0x277cb57
  0x13d5e87
  /jenkins/workspace/scylla-master/byo/byo_build_tests_dtest/scylla/build/dev/seastar/libseastar.so+0x412977
  /jenkins/workspace/scylla-master/byo/byo_build_tests_dtest/scylla/build/dev/seastar/libseastar.so+0x4137c3
  /jenkins/workspace/scylla-master/byo/byo_build_tests_dtest/scylla/build/dev/seastar/libseastar.so+0x412e93
  /jenkins/workspace/scylla-master/byo/byo_build_tests_dtest/scylla/build/dev/seastar/libseastar.so+0x3876f3
  /jenkins/workspace/scylla-master/byo/byo_build_tests_dtest/scylla/build/dev/seastar/libseastar.so+0x386b97
  0xfcd87b
  0x1006027
  0xfcccbf
  /lib64/libc.so.6+0x3059b
  /lib64/libc.so.6+0x3066f
  0xfcba2f
Scylla version 5.5.0~dev-0.20240425.1ed2a40087b3 with build-id 2293a798af38dd9bc6c31e89ac23baf29b62ce14 starting ...
```

if so, there is no issue to fix here?

**Comment by kbr-scylla** [comment] 2024-05-06 07:45
Closing then.

**Comment by gleb-cloudius** [comment] 2024-05-06 07:45
> 
> if so, there is no issue to fix here?

As far as I can tell.

**Closed** 2024-05-06 07:45 UTC
Labels: area/topology changes, area/raft, status/release blocker

**Comment by mykaul** [comment] 2024-05-06 07:59
I don't fully understand how it will now cause the test to pass? What needs to happen here? Not run in debug?

**Comment by gleb-cloudius** [comment] 2024-05-06 08:02
> I don't fully understand how it will now cause the test to pass? What needs to happen here? Not run in debug?

The issue does not exist in the new version of the test. The old one was incorrect.
