### ISSUE TITLE
docs: Issue in page Scylla Gocql Extension

### ISSUE THREAD

**Issue by fud** [scylladb/scylladb#14350] opened 2023-06-22 01:32 UTC
I would like to report an issue in page https://opensource.docs.scylladb.com/branch-5.2/using-scylla/drivers/cql-drivers/scylla-gocqlx-driver

### Problem

In this part of the page it refers to Golang in the university.

[Scylla University: Golang and Scylla Part 3 – GoCQLX](https://university.scylladb.com/courses/the-mutant-monitoring-system-training-course/lessons/golang-and-scylla-part-3-gocqlx/) - part three of the Golang three-part course which focuses on how to create a sample Go application that executes a few basic CQL statements with a Scylla cluster using the GoCQLX package

There is no golang referenced in this course.

###  Suggest a fix

Remove the link.

**Comment by mykaul** [comment] 2023-06-22 07:26
@guy9  ?

**Comment by guy9** [comment] 2023-06-25 06:12
Good catch, thanks. Fixed in https://github.com/scylladb/scylladb/pull/14385

**Comment by annastuchlik** [comment] 2023-06-27 15:47
@fud Thank you for reporting the issue!

The issue is fixed with https://github.com/scylladb/scylladb/pull/14385. Closing.

**Closed by annastuchlik** 2023-06-27 15:47 UTC
Labels: Documentation
