### ISSUE TITLE
In-memory sstable components grows ~250% after major compaction

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#5266] opened 2019-11-08 00:13 UTC
*Installation details*
Scylla version (or git commit hash): d61a3e68b8d8da
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Triggered by
writing 30 million *unique* rows
issuing major compaction

before:

		Off heap memory used (total): 32835572
		SSTable Compression Ratio: 0.0
		Number of partitions (estimate): 29971242
		Memtable cell count: 28758
		Memtable data size: 24846912
		Memtable off heap memory used: 31588352
		Memtable switch count: 216
		Local read count: 0
		Local read latency: NaN ms
		Local write count: 30000000
		Local write latency: 0.004 ms
		Pending flushes: 0
		Percent repaired: 0.0
		Bloom filter false positives: 0
		Bloom filter false ratio: 0.00000
		Bloom filter space used: 902416
		Bloom filter off heap memory used: 902412
		Index summary off heap memory used: 344808

after:

		Off heap memory used (total): 81452744
		SSTable Compression Ratio: 0.0
		Number of partitions (estimate): 29971242
		Memtable cell count: 28758
		Memtable data size: 24846912
		Memtable off heap memory used: 31588352
		Memtable switch count: 216
		Local read count: 0
		Local read latency: NaN ms
		Local write count: 30000000
		Local write latency: 0.004 ms
		Pending flushes: 0
		Percent repaired: 0.0
		Bloom filter false positives: 0
		Bloom filter false ratio: 0.00000
		Bloom filter space used: 37464336
		Bloom filter off heap memory used: 37464332
		Index summary off heap memory used: 12400060

**Comment by slivne** [comment] 2020-03-26 23:22
did you flush the memtables before running the major compaction ?

**Comment by bhalevy** [comment] 2021-04-19 12:59
Cc @cmm

**Comment by nyh** [comment] 2024-04-18 07:11
Is this a duplicate of https://www.google.com/url?q=https://github.com/scylladb/scylladb/issues/73 ?

**Comment by denesb** [comment] 2024-05-10 12:46
Yes, closing as dup of https://github.com/scylladb/scylladb/issues/73 (wow a two digit issue).

**Closed by denesb** 2024-05-10 12:46 UTC
Labels: type/bug, area/compaction
