### ISSUE TITLE
test_topology_add_decommission_reboot failed: rejected node_ops_cmd=decommission_abort: the node ops is unknown

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11011] opened 2022-07-11 06:14 UTC
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/22/testReport/lwt_random_test/TestRandomPaxos/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split035___test_topology_add_decommission_reboot/
```
ccmlib.node.NodetoolError: Nodetool command '/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/3b20407f2536de65bb599116876095bd5ec6a585/scylla-tools-java/bin/nodetool -h 127.0.32.3 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy decommission' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: seastar::rpc::remote_verb_error (node_ops_cmd_check: Node 127.0.32.3 rejected node_ops_cmd=decommission_abort from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown)
See 'nodetool help' or 'nodetool help <command>'.
```

**Comment by bhalevy** [comment] 2022-07-11 06:14
@asias please look into this

**Comment by asias** [comment] 2022-07-11 07:11
I will take a look.

**Comment by asias** [comment] 2022-07-12 03:30
@bhalevy where can I find the full logs for the run (both dtest and scylla logs)?

**Comment by asias** [comment] 2022-07-12 03:30
I tried to reproduce. I couldn't so far.

**Comment by bhalevy** [comment] 2022-07-12 08:34
> @bhalevy where can I find the full logs for the run (both dtest and scylla logs)?

@asias with the parallel dtest infrastructure the logs are now stored per split-worker:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/22/artifact/logs-full.debug.035/1657442607497_lwt_random_test.py%3A%3ATestRandomPaxos%3A%3Atest_topology_add_decommission_reboot/

**Comment by fee-mendes** [comment] 2022-07-13 03:51
As soon as we start a decommission/removenode operation the coordinator node will wait for a reply from all replicas to ensure whether it can proceed. If you stop the network on a node after a couple seconds (2 or so) and the decommissioned/removed node didn't had a chance to notice that the stopped node is down **and** it managed to receive a response to the initial request, it will proceed with the operation.

At this point, if you get the right timing, you'll notice that logs will start failing on sending the `<operation>_heartbeat` and then on `<operation>_abort`, which is where the logs will end up at.

I noticed the jenkins job in question completes the operation fairly quickly, which seems to indicate the table is fairly small. In reality, if you have a larger table that is able to take a few minutes to complete, you'll notice on logs that streaming will fallback and retry later. However, if you manage to get to this point, then no matter what result you get on the end (success or not), the `nodetool` output seems to always be `^.*the node ops is unknown$`

This is what I have on docker that can reproduce it fairly consistently. 3-node-cluster, RF=1. Populate with:
`cassandra-stress write n=10000000 -pop seq=1..10000000 -node 172.17.0.2`


Run
```shell
#!/bin/bash

# Node to decommission
DECOM="dc1-node3"

# Node to stop
STOP="dc1-node2"

echo 'BEFORE - nodetool status'
docker exec -it ${STOP} nodetool status

echo "Start decommissioning ${DECOM}"
docker exec ${DECOM} nodetool decommission &

echo "Sleep for 2 seconds, and kill network on ${STOP} node"
sleep 2

echo "Disconnect Scylla node ${STOP} from the network"
docker network disconnect bridge ${STOP}

# At this point it may be that decommission succeeded for a small table 
# or streaming will retry if it takes longer
echo "Sleep for 40s"
sleep 40

echo "Connect ${STOP} node back on network"
docker network connect bridge ${STOP}
```

**Comment by asias** [comment] 2022-07-13 05:55
I looked at the log and I know what was going on:

The decommission_prepare verb took long time to execute so the hearbeat_update verb was delayed. As a result, node 2 removed the ops with uuid 27bddbb6-7a8b-4eda-be9c-d156226d9df2 automatically because node 3 did not send any updates. When the decommission_prepare verb finished eventually and node 3 talked to node2 again. The ops 27bddbb6-7a8b-4eda-be9c-d156226d9df2 was not removed by node2 already.  I have patches to improve this area: 

https://github.com/scylladb/scylla/pull/10850 (not merged)

72797bf516a323ee984d5a1ad2e42349178d12d7 (merged)



node3
```
INFO  2022-07-10 08:40:31,177 [shard 0] storage_service - DECOMMISSIONING: starts
INFO  2022-07-10 08:40:31,180 [shard 0] storage_service - decommission[27bddbb6-7a8b-4eda-be9c-d156226d9df2]: Started decommission operation, removing node=127.0.32.3, sync_nodes=[127.0.32.3, 127.0.32.1, 127.0.32.2], ignore_nodes=[]
INFO  2022-07-10 08:40:31,445 [shard 0] storage_service - decommission[27bddbb6-7a8b-4eda-be9c-d156226d9df2]: Added node=127.0.32.3 as leaving node, coordinator=127.0.32.3
INFO  2022-07-10 08:41:25,733 [shard 0] storage_service - decommission[27bddbb6-7a8b-4eda-be9c-d156226d9df2]: Started heartbeat_updater
INFO  2022-07-10 08:41:25,733 [shard 0] storage_service - DECOMMISSIONING: unbootstrap starts
INFO  2022-07-10 08:41:25,733 [shard 0] storage_service - Started batchlog replay for decommission
WARN  2022-07-10 08:41:25,787 [shard 0] storage_service - decommission[27bddbb6-7a8b-4eda-be9c-d156226d9df2]: Failed to send heartbeat: seastar::rpc::remote_verb_error (node_ops_cmd_check: Node 127.0.32.1 rejected node_ops_cmd=decommission_heartbeat from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown)
INFO  2022-07-10 08:41:25,829 [shard 0] storage_service - Finished batchlog replay for decommission
INFO  2022-07-10 08:41:25,829 [shard 0] storage_service - enable_repair_based_node_ops=true, allowed_repair_based_node_ops={replace}
WARN  2022-07-10 08:41:35,834 [shard 0] storage_service - decommission[27bddbb6-7a8b-4eda-be9c-d156226d9df2]: Failed to send heartbeat: seastar::rpc::remote_verb_error (node_ops_cmd_check: Node 127.0.32.1 rejected node_ops_cmd=decommission_heartbeat from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown)
WARN  2022-07-10 08:41:45,868 [shard 0] storage_service - decommission[27bddbb6-7a8b-4eda-be9c-d156226d9df2]: Failed to send heartbeat: seastar::rpc::remote_verb_error (node_ops_cmd_check: Node 127.0.32.1 rejected node_ops_cmd=decommission_heartbeat from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown)
WARN  2022-07-10 08:41:55,903 [shard 0] storage_service - decommission[27bddbb6-7a8b-4eda-be9c-d156226d9df2]: Failed to send heartbeat: seastar::rpc::remote_verb_error (node_ops_cmd_check: Node 127.0.32.1 rejected node_ops_cmd=decommission_heartbeat from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown)
WARN  2022-07-10 08:42:05,942 [shard 0] storage_service - decommission[27bddbb6-7a8b-4eda-be9c-d156226d9df2]: Failed to send heartbeat: seastar::rpc::remote_verb_error (node_ops_cmd_check: Node 127.0.32.1 rejected node_ops_cmd=decommission_heartbeat from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown)
```

node2
```
INFO  2022-07-10 08:40:31,232 [shard 0] storage_service - decommission[27bddbb6-7a8b-4eda-be9c-d156226d9df2]: Added node=127.0.32.3 as leaving node, coordinator=127.0.32.3
INFO  2022-07-10 08:41:24,262 [shard 0] storage_service - decommission[27bddbb6-7a8b-4eda-be9c-d156226d9df2]: Removed node=127.0.32.3 as leaving node, coordinator=127.0.32.3
WARN  2022-07-10 08:41:25,748 [shard 0] storage_service - node_ops_cmd_check: Node 127.0.32.2 rejected node_ops_cmd=decommission_heartbeat from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown
WARN  2022-07-10 08:41:35,803 [shard 0] storage_service - node_ops_cmd_check: Node 127.0.32.2 rejected node_ops_cmd=decommission_heartbeat from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown
WARN  2022-07-10 08:41:45,842 [shard 0] storage_service - node_ops_cmd_check: Node 127.0.32.2 rejected node_ops_cmd=decommission_heartbeat from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown
WARN  2022-07-10 08:41:55,876 [shard 0] storage_service - node_ops_cmd_check: Node 127.0.32.2 rejected node_ops_cmd=decommission_heartbeat from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown
WARN  2022-07-10 08:42:05,913 [shard 0] storage_service - node_ops_cmd_check: Node 127.0.32.2 rejected node_ops_cmd=decommission_heartbeat from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown
WARN  2022-07-10 08:42:15,952 [shard 0] storage_service - node_ops_cmd_check: Node 127.0.32.2 rejected node_ops_cmd=decommission_heartbeat from node=127.0.32.3 with ops_uuid=27bddbb6-7a8b-4eda-be9c-d156226d9df2, pending_node_ops={}, the node ops is unknown
```

**Comment by asias** [comment] 2022-07-13 05:58
> As soon as we start a decommission/removenode operation the coordinator node will wait for a reply from all replicas to ensure whether it can proceed. If you stop the network on a node after a couple seconds (2 or so) and the decommissioned/removed node didn't had a chance to notice that the stopped node is down **and** it managed to receive a response to the initial request, it will proceed with the operation.
> 
> At this point, if you get the right timing, you'll notice that logs will start failing on sending the `<operation>_heartbeat` and then on `<operation>_abort`, which is where the logs will end up at.
> 
> I noticed the jenkins job in question completes the operation fairly quickly, which seems to indicate the table is fairly small. In reality, if you have a larger table that is able to take a few minutes to complete, you'll notice on logs that streaming will fallback and retry later. However, if you manage to get to this point, then no matter what result you get on the end (success or not), the `nodetool` output seems to always be `^.*the node ops is unknown$`
> 
> This is what I have on docker that can reproduce it fairly consistently. 3-node-cluster, RF=1. Populate with: `cassandra-stress write n=10000000 -pop seq=1..10000000 -node 172.17.0.2`
> 
> Run
> 
> ```shell
> #!/bin/bash
> 
> # Node to decommission
> DECOM="dc1-node3"
> 
> # Node to stop
> STOP="dc1-node2"
> 
> echo 'BEFORE - nodetool status'
> docker exec -it ${STOP} nodetool status
> 
> echo "Start decommissioning ${DECOM}"
> docker exec ${DECOM} nodetool decommission &
> 
> echo "Sleep for 2 seconds, and kill network on ${STOP} node"
> sleep 2
> 
> echo "Disconnect Scylla node ${STOP} from the network"
> docker network disconnect bridge ${STOP}
> 
> # At this point it may be that decommission succeeded for a small table 
> # or streaming will retry if it takes longer
> echo "Sleep for 40s"
> sleep 40
> 
> echo "Connect ${STOP} node back on network"
> docker network connect bridge ${STOP}
> ```

Thanks. This procedure produces similar situation. It makes decommission_prepare took long time to finish on node 2 so that node3 will not update node1 for the hearbeat. As a result node 1 will remove the uuid for the decommission.

**Comment by mykaul** [comment] 2023-02-21 16:07
@asias - with both patches merged, what else is needed to close this?

**Comment by bhalevy** [comment] 2023-02-21 18:11
Saw this with 2022.1.5 in the field.
The reason for the decommission to aborted on the remote node is unclear.
https://github.com/scylladb/scylladb/pull/12799 would help understand the reason as it added warnings and error printouts.

**Comment by bhalevy** [comment] 2023-02-21 18:19
The odd thing is the ~50 seconds gap that repeats in the different instances:

```
Feb 21 10:23:15 ip-10-163-2-8 scylla[17559]:  [shard 0] storage_service - decommission[e61d82d1-0314-491a-bc4b-f147757cdac4]: Added node=10.182.0.136 as leaving node, coordinator=10.182.0.136
Feb 21 10:24:02 ip-10-163-2-8 scylla[17559]:  [shard 0] storage_service - decommission[e61d82d1-0314-491a-bc4b-f147757cdac4]: Removed node=10.182.0.136 as leaving node, coordinator=10.182.0.136
```

```
Feb 21 14:53:53 ip-10-163-2-8 scylla[17559]:  [shard 0] storage_service - decommission[bc6206b0-3790-4d49-b631-e08c7568bf22]: Added node=10.182.2.140 as leaving node, coordinator=10.182.2.140
Feb 21 14:54:43 ip-10-163-2-8 scylla[17559]:  [shard 0] storage_service - decommission[bc6206b0-3790-4d49-b631-e08c7568bf22]: Removed node=10.182.2.140 as leaving node, coordinator=10.182.2.140
```

```
Feb 21 17:26:17 ip-10-163-3-116 scylla:  [shard 0] storage_service - decommission[c5deb297-8a21-4cb7-9a83-e4987d5294ed]: Added node=10.182.2.140 as leaving node, coordinator=10.182.2.140
Feb 21 17:27:10 ip-10-163-3-116 scylla:  [shard 0] storage_service - decommission[c5deb297-8a21-4cb7-9a83-e4987d5294ed]: Removed node=10.182.2.140 as leaving node, coordinator=10.182.2.140
```

**Comment by bhalevy** [comment] 2023-02-21 18:20
while
```
service/storage_service.hh:106:    std::chrono::seconds _watchdog_interval{120};
```

**Comment by asias** [comment] 2023-02-24 01:51
I sent a PR here: https://github.com/scylladb/scylladb/pull/12980

**Closed** 2023-02-25 03:25 UTC
Labels: dtest

**Comment by avikivity** [comment] 2023-10-26 13:51
@asias please evaluate for backport

**Comment by denesb** [comment] 2023-12-14 13:56
> @asias please evaluate for backport

@asias ping. Should we backport this to 5.2?

**Comment by asias** [comment] 2023-12-14 13:57
> > @asias please evaluate for backport
> 
> @asias ping. Should we backport this to 5.2?

yes

**Comment by denesb** [comment] 2023-12-15 09:45
> > > @asias please evaluate for backport
> > 
> > 
> > @asias ping. Should we backport this to 5.2?
> 
> yes

Does not apply to 5.2, please prepare a backport PR.
