### ISSUE TITLE
scylla_io_setup - AWS tuning should follow the same logic as GCP and Azure

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#9399] opened 2021-09-28 00:08 UTC
[scylla_io_setup](https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_io_setup#L189) currently completely ignores the instance type of AWS instances unless we pass the `--ami` parameter to it. This is counterintuitive and causes us to run iotune under supported instances unnecessarily.
 
Even then, different than on GCP and Azure, where we simply run `iotune` whenever the instance is detected as not supported, running `scylla_io_setup --ami` to an unsupported instance will cause the script to fail badly, as in:

```python
    if not is_developer_mode():
        if args.ami:
            idata = aws_instance()

            if not idata.is_supported_instance_class():
                logging.error('{} is not supported instance type, run "scylla_io_setup" again without --ami option.'.format(idata.instance()))
                sys.exit(1)
```

This issue is for removing the need for passing `--ami` when tuning the underlying storage, and replace that option with the same behavior as we have today for GCP & Azure.

**Comment by syuu1228** [comment] 2022-06-13 11:45
We dropped the option when we move cloud related code to scylla-machine-image (from 5.0):
https://github.com/scylladb/scylla-machine-image/blob/branch-5.0/common/scylla_cloud_io_setup

**Comment by syuu1228** [comment] 2023-10-16 09:29
Since we moved cloud related code to scylla-machine-image, the issue is not exist anymore. Closing.

**Closed by syuu1228** 2023-10-16 09:29 UTC
Labels: enhancement
