### ISSUE TITLE
test_login_message_after_half_of_the_cluster_is_down fails due to a raft failure when starting a server

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#16813] opened 2024-01-17 03:46 UTC
```
04:27:37              if resp.status != 200:
04:27:37                  text = await resp.text()
04:27:37  >               raise HTTPError(uri, resp.status, params, json, text)
04:27:37  E               test.pylib.rest_client.HTTPError: HTTP error 500, uri: http+unix://api/cluster/addservers, params: None, json: {'start': True, 'config': {'failure_detector_timeout_in_ms': 2000, 'authenticator': 'PasswordAuthenticator', 'authorizer': 'CassandraAuthorizer', 'permissions_validity_in_ms': 0, 'permissions_update_interval_in_ms': 0}, 'servers_num': 2}, body:
04:27:37  E               failed to start the node, server_id 19, IP 127.25.14.11, workdir scylla-19, host_id 632ed2d1-f8f7-4ba0-804d-0d6b5f976611, cql [not connected]
04:27:37  E               Check the log files:
04:27:37  E               /scylladir/testlog/x86_64/test.py.debug-release-dev.log
04:27:37  E               /scylladir/testlog/x86_64/debug/scylla-19.log
04:27:37  
04:27:37  test/pylib/rest_client.py:69: HTTPError
04:27:37  
04:27:37  The above exception was the direct cause of the following exception:
04:27:37  
04:27:37  manager = <test.pylib.manager_client.ManagerClient object at 0x7f8ca0d143d0>
04:27:37  
04:27:37      @pytest.mark.asyncio
04:27:37      async def test_login_message_after_half_of_the_cluster_is_down(manager: ManagerClient) -> None:
04:27:37          """Tests the error message after half of the cluster goes down"""
04:27:37          config = {
04:27:37              'failure_detector_timeout_in_ms': 2000,
04:27:37              'authenticator': 'PasswordAuthenticator',
04:27:37              'authorizer': 'CassandraAuthorizer',
04:27:37              'permissions_validity_in_ms': 0,
04:27:37              'permissions_update_interval_in_ms': 0,
04:27:37          }
04:27:37      
04:27:37  >       servers = await manager.servers_add(2, config=config)
04:27:37  
04:27:37  test/auth_cluster/test_password_login_message.py:34:
```
```
04:27:37  =================================== FAILURES ===================================
04:27:37  _____________ test_login_message_after_half_of_the_cluster_is_down _____________
04:27:37  
04:27:37  self = <test.pylib.manager_client.ManagerClient object at 0x7f8ca0d143d0>
04:27:37  servers_num = 2, cmdline = None
04:27:37  config = {'authenticator': 'PasswordAuthenticator', 'authorizer': 'CassandraAuthorizer', 'failure_detector_timeout_in_ms': 2000, 'permissions_update_interval_in_ms': 0, ...}
04:27:37  property_file = None, start = True, expected_error = None
04:27:37  
04:27:37      async def servers_add(self, servers_num: int = 1,
```

```
04:27:37  21:23:52.999 DEBUG> RESTClient fetching GET http+unix://api/cluster/running-servers
04:27:37  ------------------------------ Captured log call -------------------------------
04:27:37  21:23:53.001 DEBUG> RESTClient fetching PUT http+unix://api/cluster/addservers
```

we have following error in `scylla-19.log`:

```
INFO  2024-01-16 21:23:55,790 [shard 0:main] init - starting maintenance auth service
INFO  2024-01-16 21:23:55,791 [shard 0:main] init - starting maintenance native server
INFO  2024-01-16 21:23:55,793 [shard 0:stmt] cql_server_controller - Setting up maintenance socket on /scylladir/testlog/x86_64/debug/scylla-19/cql.m
INFO  2024-01-16 21:23:55,796 [shard 1:comp] compaction - [Compact system.truncated ca4c7a70-b4a4-11ee-95b5-b45e0a468aca] Compacted 2 sstables to [/scylladir/testlog/x86_64/debug/scylla-19/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-7-big-Data.db:level=0]. 79kB to 74kB (~93% of original) in 112ms = 709kB/s. ~256 total partitions merged to 6.
INFO  2024-01-16 21:23:55,802 [shard 0:stmt] cql_server_controller - Starting listening for CQL clients on /scylladir/testlog/x86_64/debug/scylla-19/cql.m (unencrypted, non-shard-aware)
WARN  2024-01-16 21:23:55,803 [shard 0:stmt] gossip - Fail to apply application_state: std::runtime_error (endpoint_state_map does not contain endpoint = 127.25.14.11, application_states = {{RPC_READY -> Value(1,1)}})
INFO  2024-01-16 21:23:55,807 [shard 0:main] raft_group0 - Disabling migration_manager schema pulls because Raft is enabled and we're bootstrapping.
...
ERROR 2024-01-16 21:24:04,636 [shard 0: gms] storage_service - raft topology: raft_topology_cmd failed with: std::runtime_error ({shard 0: std::runtime_error (repair[09c5b863-28ad-4f96-8ea4-b06c48a26a04]: 1 out of 68 ranges failed, keyspace=system_auth, tables={role_permissions, roles, role_members, role_attributes}, repair_reason=bootstrap, nodes_down_during_repair={}, aborted_by_user=false, failed_because=seastar::nested_exception: std::runtime_error (Failed to repair for keyspace=system_auth, cf=roles, range=(15700365075489932,401683124264446534]) (while cleaning up after std::out_of_range (regular column id 0 >= 0)))})
INFO  2024-01-16 21:24:04,711 [shard 0:main] init - Shutting down group 0 usage in local storage
INFO  2024-01-16 21:24:04,712 [shard 0:strm] storage_service - raft_state_monitor_fiber aborted with seastar::abort_requested_exception (abort requested)
INFO  2024-01-16 21:24:04,712 [shard 0:strm] storage_service - raft topology: cleanup fiber aborted
...
INFO  2024-01-16 21:24:06,847 [shard 0:main] init - Shutting down configurables was successful
ERROR 2024-01-16 21:24:06,848 [shard 0:main] init - Startup failed: 
std::runtime_error (Bootstrap failed. See earlier errors)
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5814/consoleFull

[scylla-19.log](https://github.com/scylladb/scylladb/files/13958333/scylla-19.log)

**Comment by kbr-scylla** [comment] 2024-01-22 10:29
This is actually a failure in repair
`ERROR 2024-01-16 21:24:04,636 [shard 0: gms] storage_service - raft topology: raft_topology_cmd failed with: std::runtime_error ({shard 0: std::runtime_error (repair[09c5b863-28ad-4f96-8ea4-b06c48a26a04]: 1 out of 68 ranges failed, keyspace=system_auth, tables={role_permissions, roles, role_members, role_attributes}, repair_reason=bootstrap, nodes_down_during_repair={}, aborted_by_user=false, failed_because=seastar::nested_exception: std::runtime_error (Failed to repair for keyspace=system_auth, cf=roles, range=(15700365075489932,401683124264446534]) (while cleaning up after std::out_of_range (regular column id 0 >= 0)))})`

and it looks like a duplicate of https://github.com/scylladb/scylladb/issues/16821
Closing as duplicate.

**Closed by kbr-scylla** 2024-01-22 10:29 UTC
Labels: raft, CI-Stability
