### ISSUE TITLE
CQL Multi column relations are broken with mixed clustering order.

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylladb#65] opened 2015-08-04 12:57 UTC
This is basically the same issue as [CASSANDRA-7281](https://issues.apache.org/jira/browse/CASSANDRA-7281). If some column has reversed type (result of `CLUSTERING ORDER BY`) its value will be compared incorrectly and, consequently, multi column relations won't use a proper lexicographical ordering.
For example, with a table like this:

```
CREATE TABLE table (p1 int, c1 int, c2 int, PRIMARY KEY (a, b, c)) WITH CLUSTERING ORDER BY (c1 ASC, c2 DESC)
```

and values:

```
INSERT INTO table (p1, c1, c2) VALUES (0, 1, 0);
INSERT INTO table (p1, c1, c2) VALUES (0, 1, 1);
INSERT INTO table (p1, c1, c2) VALUES (0, 1, 2);
```

result of:

```
SELECT c1, c2 FROM table WHERE p1 = 0 AND (c1, c2) >= (1, 1);
```

will be `[(1, 0), (1, 1)]` instead of: `[(1, 1), (1, 2)]`

**Comment by avelanarius** [comment] 2022-11-27 15:26
Stumbled here by accident while searching through issues, it looks like this issue has been long fixed - the reproducer has worked correctly for a long time (tested it with master Scylla, Scylla 3.0.0).

I'd close the issue, but a quick search through tests suggests that we don't have a test for this scenario.

**Comment by mykaul** [comment] 2022-11-27 15:48
> Stumbled here by accident while searching through issues, it looks like this issue has been long fixed - the reproducer has worked correctly for a long time (tested it with master Scylla, Scylla 3.0.0).
> 
> I'd close the issue, but a quick search through tests suggests that we don't have a test for this scenario.

It's better to open a specific issue on missing test.

**Closed** 2022-12-01 19:41 UTC
Labels: bug, CQL

**Comment by avikivity** [comment] 2022-12-01 20:14
Two digit issue from 2015. Congrats to everyone involved.

**Comment by avikivity** [comment] 2022-12-01 20:15
Commit only adds a regression test, so no backports needed.
