### ISSUE TITLE
scylla service restart takes 20 minutes after enospc nemesis

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#8559] opened 2021-04-27 17:52 UTC
scenario: 
1. run enospc nemesis to reach 99% used disk capacity on node-6.
2. then delete all above created files, sleep a bit and restart scylla service.
3. the timeout command for scylla service restart expired after 8 minutes.
4. then it took another 12 minutes as a total of 20 minutes for node-6 to complete initialization.

logs:
```
< t:2021-04-21 09:52:59,448 f:cluster.py      l:1356 c:sdcm.cluster         p:DEBUG > 2021-04-21T09:52:47+00:00  longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 !NOTICE  | sudo: scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/bin/systemctl restart scylla-server.service

< t:2021-04-21 10:01:07,485 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo systemctl restart scylla-server.service"; Exit status: -1

2021-04-21T10:08:47+00:00  longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 !INFO    | scylla: Scylla version 4.3.3-0.20210419.28f5e0bd2 with build-id c4a1db52eac953329ed2383fc23431f5c9cabf62 starting ...
2021-04-21T10:08:49+00:00  longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 !INFO    | scylla: [shard 0] init - Scylla version 4.3.3-0.20210419.28f5e0bd2 with build-id c4a1db52eac953329ed2383fc23431f5c9cabf62 starting ...
2021-04-21T10:12:02+00:00  longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 !INFO    | scylla: [shard 0] init - Scylla version 4.3.3-0.20210419.28f5e0bd2 initialization completed.
```

*Installation details*
Scylla version (or git commit hash): `4.3.3-0.20210419.28f5e0bd2 with build-id c4a1db52eac953329ed2383fc23431f5c9cabf62`
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-071018db599725edc` (aws: eu-north-1)

Test: longevity-cdc-100gb-4h-test
Test name: longevity_test.LongevityTest.test_custom_time
Test config file(s):
- [longevity-cdc-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d743c85b8327aee48e9ed6fe618973fa871d8a25/test-cases/longevity/longevity-cdc-100gb-4h.yaml)

**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 4419244a-6461-4886-af1e-238712f0fd2c`
Show all stored logs command: `$ hydra investigate show-logs 4419244a-6461-4886-af1e-238712f0fd2c`

Test id: `4419244a-6461-4886-af1e-238712f0fd2c`

Logs:
prometheus - [https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/prometheus_snapshot_20210421_101534.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/prometheus_snapshot_20210421_101534.tar.gz)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_100525/grafana-screenshot-overview-20210421_100525-longevity-cdc-100gb-4h-4-3-monitor-node-4419244a-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_100525/grafana-screenshot-overview-20210421_100525-longevity-cdc-100gb-4h-4-3-monitor-node-4419244a-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_100525/grafana-screenshot-scylla-per-server-metrics-nemesis-20210421_100907-longevity-cdc-100gb-4h-4-3-monitor-node-4419244a-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_100525/grafana-screenshot-scylla-per-server-metrics-nemesis-20210421_100907-longevity-cdc-100gb-4h-4-3-monitor-node-4419244a-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_101603/grafana-screenshot-overview-20210421_101604-longevity-cdc-100gb-4h-4-3-monitor-node-4419244a-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_101603/grafana-screenshot-overview-20210421_101604-longevity-cdc-100gb-4h-4-3-monitor-node-4419244a-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_101603/grafana-screenshot-scylla-per-server-metrics-nemesis-20210421_101915-longevity-cdc-100gb-4h-4-3-monitor-node-4419244a-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_101603/grafana-screenshot-scylla-per-server-metrics-nemesis-20210421_101915-longevity-cdc-100gb-4h-4-3-monitor-node-4419244a-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_102553/db-cluster-4419244a.zip](https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_102553/db-cluster-4419244a.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_102553/loader-set-4419244a.zip](https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_102553/loader-set-4419244a.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_102553/monitor-set-4419244a.zip](https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_102553/monitor-set-4419244a.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_102553/sct-runner-4419244a.zip](https://cloudius-jenkins-test.s3.amazonaws.com/4419244a-6461-4886-af1e-238712f0fd2c/20210421_102553/sct-runner-4419244a.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.3/job/longevity/job/longevity-cdc-100gb-4h-test/53/)

**Comment by slivne** [comment] 2021-05-06 07:47
I expect its doing commitlog replay - but you can double check that in the log.

Calle - can you check and see if its commitlog replay that is taking a long time - or something else that is "strange" and do the first analysis.

**Comment by elcallio** [comment] 2021-05-10 08:24
Only node 6 is doing replay. That is one with a _lot_ of files (including recycled ones, which seem to indicate we are not filtering correctly). But it takes ~2m:

```
Apr 21 10:08:49 longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 scylla[66097]:  [shard 0] init - Scylla version 4.3.3-0.20210419.28f5e0bd2 with build-id c4a1db52eac953329ed2383fc23431f5c9cabf62 starting ...

...
Apr 21 10:09:10 longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 scylla[66097]:  [shard 0] init - replaying commit log

....

Apr 21 10:11:32 longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 scylla[66097]:  [shard 0] commitlog_replayer - Log replay complete, 56191822 replayed mutations (0 invalid, 0 skipped)
Apr 21 10:11:32 longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 scylla[66097]:  [shard 0] init - replaying commit log - flushing memtables
Apr 21 10:11:37 longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 scylla[66097]:  [shard 0] init - replaying commit log - removing old commitlog segments

...
<compaction>
...

Apr 21 10:11:50 longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 scylla[66097]:  [shard 0] init - Waiting for gossip to settle before accepting client requests...

...
<compaction>
....
Apr 21 10:12:02 longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 scylla[66097]:  [shard 0] init - Scylla version 4.3.3-0.20210419.28f5e0bd2 initialization completed.

```

At this point, the rest of the cluster seems to have connected with the restarted node again, and everyone is back to doing compaction. Followed by some compaction. 

I can't see anything "strange" as such. The node restarts, it does take almost 4 minutes total, but given the amount of replay and compaction happening before it even gets to gossip, that does not seem wholly unreasonable.

**Comment by slivne** [comment] 2021-05-10 08:35
I guess it may be an issue the shutdown ... that takes long and then systemd kills scylla since we have a timeout of 15 minutes if I recall correctly.

**Comment by xemul** [comment] 2021-05-10 10:32
@slivne , #8079

**Comment by elcallio** [comment] 2021-05-10 10:42
Sorry, but the hints thing is _before_ node restart (first run shutdown). Replay etc is on the start after.

**Comment by elcallio** [comment] 2021-05-10 10:43
I somewhat misunderstood the issue somewhat. The concern is that the restart _as a whole_ timed out, not the actual node start?

**Comment by slivne** [comment] 2021-05-10 10:44
Yes

And I don;t think the commitlog hard limit is part of 4.3 https://github.com/scylladb/scylla/commit/4082f57edc3e7764e11e9e858a0a8059981c6309

**Comment by elcallio** [comment] 2021-05-10 10:46
I can't really comment on whether added53b7d614280695d5468c08f401d6833cbab fixes this, but it seems likely, if it is a hints hang.

**Comment by slivne** [comment] 2021-05-10 10:49
How the hard limit is not part of 4.3 so why do we need this "soft limit"

**Comment by elcallio** [comment] 2021-05-10 10:51
Ugh, not at my best here today. It is not? Then I am confused.

**Comment by piodul** [comment] 2021-05-10 11:10
If the commitlog didn't enforce a hard space limit in 4.3.3, then the patch which makes it soft for hints again won't help.

Maybe it's https://github.com/scylladb/scylla/issues/8577? It also had an ENOSPC nemesis. @bhalevy saw that commitlog shutdown might get stuck if an I/O error happens and sent a PR which should help with it (https://github.com/scylladb/scylla/pull/8578).

Looking at the logs of the node 6 (this issue), there was an I/O error in hints commitlog on shard 9:

```
2021-04-21T09:52:00+00:00  longevity-cdc-100gb-4h-4-3-db-node-4419244a-6 !ERR     | scylla: [shard 9] commitlog - Failed to persist commits to disk for HintsLog-1-162129586586159264.log: storage_io_error (Storage I/O error: 28: No space left on device)
```

**Comment by elcallio** [comment] 2021-05-10 11:11
One hints manager on shard 9 had a `no space left on device`. Possibly during a hints drain, which is includes a commitlog shutdown call. If the exception was hit here, it is possible this is hitting the problem @bhalevy addressed in #8578.

**Comment by elcallio** [comment] 2021-05-10 11:11
@piodul - samesis!

**Comment by slivne** [comment] 2021-05-25 14:03
Thanks - #8578 is still not merged and this is not a blocker - its not a regression

**Comment by slivne** [comment] 2021-06-21 10:41
Potentially also related to https://github.com/scylladb/scylla/pull/8764 - once this is merged - we can see if it reproduces and if not close

**Comment by mykaul** [comment] 2023-08-22 14:54
Both above PRs are merged - closing for the time being as completed.

**Closed by mykaul** 2023-08-22 14:54 UTC
Labels: bug, commit-log
