### ISSUE TITLE
Add a separate RPC verb for asynchronous view updates

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylladb#14810] opened 2023-07-24 21:09 UTC
When there's a table with a materialized view, each request goes through the following steps:
1) Coordinator receives a request from the user
2) Coordinator sends the request to base table replicas
3) Each base replica generates the corresponding view table updates and sends them to view table replicas
4) Base table replicas apply the base mutation locally
5) View replicas apply the view mutations locally

The problem is that operations 2) and 3) use the same RPC verb - `MUTATION`.

Having a separate verb for view table updates will allow finer control over their flow control.

Additionally it prevents deadlocks that could arise with high load.
Imagine the following deadlock scenario:
* A cluster receives a lot of requests, each request calls the `MUTATION` verb on a remote replica
* There's so many `MUTATION` requests that the nodes push back and don't accept any more `MUTATION` calls until the existing ones complete
* To complete a `MUTATION` call the replica needs to send out view updates, but this can't be done, as remote nodes don't accept any more `MUTATION` calls
* A deadlock happens

Having a separate verb prevents this, the remote node can still accept `VIEW_MUTATION`, even when it's swamped with `MUTATION` calls.

Right now this isn't a very likely scenario, but in the near future I plan to add strict concurrency limits to RPC servers, so that a receiver node can't be overloaded by sender nodes. With these limits the risk of a deadlock increases.

A similar thing was done for hints in https://github.com/scylladb/scylladb/pull/5378, there's `HINT_MUTATION` to help with proper flow control.

**Comment by kostja** [comment] 2024-04-17 19:16
Duplicate of #4038

**Closed by kostja** 2024-04-17 19:16 UTC
Labels: feature/enhancement, area/materialized views
