### ISSUE TITLE
test_insert_data_after_recreating_cf error after starting tablet migration: "raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#17512] opened 2024-02-25 17:21 UTC
https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/143/testReport/junit/secondary_indexes_test/TestSecondaryIndexes/FullDtest___full_split007___test_insert_data_after_recreating_cf/

Scylla version 5.5.0~dev-0.20240219.f83df2410885 with build-id 014deb7b33da99edb4de0809858ccce3903d931e

The test failed with an error of `raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID...`:
```
failed on teardown with "AssertionError: Unexpected errors found: [('node1', ["ERROR 2024-02-20 10:42:59,799 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:43:18,808 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:43:41,819 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:46:39,904 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:47:04,916 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:43:33,815 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:46:12,890 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:47:02,915 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:46:15,891 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:44:41,847 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:47:58,944 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:43:09,804 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:43:40,819 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:46:55,912 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:43:16,807 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:47:30,930 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:43:38,818 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:42:16,779 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:45:02,857 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:42:31,786 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:45:46,877 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:44:08,832 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:47:42,936 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:42:42,791 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:46:57,913 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:47:55,943 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:45:53,881 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:46:01,884 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:45:18,865 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:46:16,892 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)", "ERROR 2024-02-20 10:43:50,823 [shard 0:strm] raft_topology - topology change 
```

node log had:
```
INFO  2024-02-20 10:42:16,768 [shard 0:strm] load_balancer - Prepared 1 migration plans, out of which there were 1 tablet migration(s) and 0 resize decision(s)
INFO  2024-02-20 10:42:16,769 [shard 0:strm] raft_topology - updating topology state: Starting tablet migration
INFO  2024-02-20 10:42:16,772 [shard 1:comp] compaction - [Compact system.truncated b7282400-cfdc-11ee-9159-ef13e8dccbf0] Compacted 2 sstables to [/jenkins/workspace/scylla-master/byo/dtest-byo/scylla/.dtest/dtest-901x7lmr/test/node1/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gds_0tqg_4klxd27knwh8cf8bn4-big-Data.db:level=0]. 79kB to 74kB (~93% of original) in 4ms = 19MB/s. ~256 total partitions merged to 7.
INFO  2024-02-20 10:42:16,779 [shard 0:strm] raft_topology - entered `tablet migration` transition state
ERROR 2024-02-20 10:42:16,779 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)
INFO  2024-02-20 10:42:17,779 [shard 0:strm] raft_topology - entered `tablet migration` transition state
ERROR 2024-02-20 10:42:17,779 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)
```
The error happened after running commands like:
```
10:42:52,170 802     secondary_indexes_test         DEBUG    secondary_indexes_test.py:758  | test_insert_data_after_recreating_cf: round 1
10:42:52,170 802     secondary_indexes_test         DEBUG    secondary_indexes_test.py:761  | test_insert_data_after_recreating_cf: DROP COLUMNFAMILY ks.cf
10:42:54,078 802     tools.data                     DEBUG    data.py             :320  | test_insert_data_after_recreating_cf: Create index: CREATE INDEX col1_key ON cf (col1)
10:42:57,048 802     tools.data                     DEBUG    data.py             :325  | test_insert_data_after_recreating_cf: Index col1_key has been created
10:42:57,048 802     tools.tables_view_manager      DEBUG    tables_view_manager.py:675  | test_insert_data_after_recreating_cf: Waiting for view ks.col1_key_index to finish building: num_nodes=4 num_alive=4 cl=QUORUM
10:42:57,051 802     tools.tables_view_manager      DEBUG    tables_view_manager.py:684  | test_insert_data_after_recreating_cf: wait_for_view ks.col1_key_index: status=defaultdict(<class 'set'>, {'SUCCESS': {UUID('8286f345-a954-4ed0-8d95-754c12269788'), UUID('6d5643d0-91d2-4d93-96d1-ecb89c0fd353'), UUID('43f5e4a6-88db-46b8-9119-d77eeacc5750'), UUID('e59ad40e-8b78-4131-9893-12f093cf53d7')}})
```

log:
https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/143/artifact/logs-full.release.007/dtest-gw3.log

**Comment by bhalevy** [comment] 2024-02-25 17:33
@tgrabiec is the above message should be logged as an error?
If the table was dropped then the error is expected, so maybe it should be squelched

**Comment by bhalevy** [comment] 2024-02-28 11:38
Similar error in https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/143/testReport/lwt_schema_modification_test/TestLWTSchemaModification/FullDtest___full_split005___test_index_drop_add/
```
failed on teardown with "AssertionError: Unexpected errors found: [('node1', ["ERROR 2024-02-20 10:44:41,242 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID 065219f1-cfdd-11ee-9d0b-dbe2f26e0cab)"
...
```

**Comment by yarongilor** [comment] 2024-02-28 12:33
Reproduced in https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/143/testReport/junit/concurrent_schema_changes_test/TestConcurrentSchemaChanges/FullDtest___full_split004___test_snapshot/ - 
```
failed on teardown with "AssertionError: Unexpected errors found: [('node1', ["ERROR 2024-02-20 10:40:00,069 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID 524c4931-cfdc-11ee-964f-fd82fce7d7a5)", "ERROR 2024-02-20 10:40:03,071 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID 524c4931-cfdc-11ee-964f-fd82fce7d7a5)", "ERROR 2024-02-20 10:40:02,070 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID 524c4931-cfdc-11ee-964f-fd82fce7d7a5)", "ERROR 2024-02-20 10:39:58,068 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID 524c4931-cfdc-11ee-964f-fd82fce7d7a5)", "ERROR 2024-02-20 10:40:01,070 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID 524c4931-cfdc-11ee-964f-fd82fce7d7a5)", "ERROR 2024-02-20 10:39:59,069 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID 524c4931-cfdc-11ee-964f-fd82fce7d7a5)"])]"
```

**Comment by tchaikov** [comment] 2024-03-04 07:48
"lwt_schema_modification_test.py::TestLWTSchemaModification::test_index_drop_add" also fails due to this issue.

**Comment by tgrabiec** [comment] 2024-03-04 19:36
> @tgrabiec is the above message should be logged as an error? If the table was dropped then the error is expected, so maybe it should be squelched

It's logged in a generic place which logs all exceptions during migration. If this is indeed a table drop then the error is temporary. If it's a logic error or corrupted metadata (e.g. tablets present but table not present), then it won't be. Because of the latter, I feel uneasy about silencing it unconditionally. 

Can we make the test expect this error?

**Comment by raphaelsc** [comment] 2024-03-04 19:54
> > @tgrabiec is the above message should be logged as an error? If the table was dropped then the error is expected, so maybe it should be squelched
> 
> It's logged in a generic place which logs all exceptions during migration. If this is indeed a table drop then the error is temporary. If it's a logic error or corrupted metadata (e.g. tablets present but table not present), then it won't be. Because of the latter, I feel uneasy about silencing it unconditionally.
> 
> Can we make the test expect this error?

@tgrabiec 

```
INFO  2024-02-20 10:42:15,064 [shard 0:strm] schema_tables - Creating ks.col1_key_index id=b623ac51-cfdc-11ee-b344-c406b81e7f7f version=b623ac52-cfdc-11ee-b344-c406b81e7f7f

INFO  2024-02-20 10:42:16,740 [shard 0:strm] database - Dropping ks.col1_key_index with auto-snapshot
INFO  2024-02-20 10:42:16,741 [shard 0:strm] database - Truncating ks.col1_key_index with auto-snapshot


INFO  2024-02-20 10:42:19,246 [shard 0:strm] schema_tables - Creating ks.col1_key_index id=b8a1cbb1-cfdc-11ee-ab7e-e31cbe59c8de version=b8a1cbb2-cfdc-11ee-ab7e-e31cbe59c8de
```

[table is recreated]

coordinator tries to access table with old id

`ERROR 2024-02-20 10:42:20,781 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID b623ac51-cfdc-11ee-b344-c406b81e7f7f)`


do we need to add a defense in for_each_tablet_transition(), but alternatively we just retry after sleeping for 1s.

and we adjust tests to recognize this failure, like you recommended.

**Comment by tgrabiec** [comment] 2024-03-04 19:58
> do we need to add a defense in for_each_tablet_transition(), but alternatively we just retry after sleeping for 1s.

I worry that just ignoring such tablets may cover up logic errors.

**Comment by raphaelsc** [comment] 2024-03-04 20:21
> > do we need to add a defense in for_each_tablet_transition(), but alternatively we just retry after sleeping for 1s.
> 
> I worry that just ignoring such tablets may cover up logic errors.

> > do we need to add a defense in for_each_tablet_transition(), but alternatively we just retry after sleeping for 1s.
> 
> I worry that just ignoring such tablets may cover up logic errors.

indeed, the alternative I mentioned above is what we have today already, when handling exception in coordinator.

**Comment by tgrabiec** [comment] 2024-03-04 23:01
Actually, I wonder how is this possible. `for_each_tablet_transition()` is called by coordinator under group0_guard, which is supposed to mutually-exclude with local group0 state machine changes. Also, table drop should drop tablets of the dropped table as part of the same group0 operation. So coordinator should not be able to observe under group0_guard lock tablet transitions for a table which is no longer there in the database.

**Comment by tgrabiec** [comment] 2024-03-04 23:11
This is a secondary indexes test. So the problem is that we're not calling `db.get_notifier().before_drop_column_family()` when dropping secondary indexes in `make_update_indices_mutations()`, and tablets are never dropped for them. Similar change was needed to handle index creation in 8181e287312c2b3eefa222eb6946cdae29195aa5

**Comment by tgrabiec** [comment] 2024-03-04 23:48
Refs https://github.com/scylladb/scylladb/issues/17627

**Comment by bhalevy** [comment] 2024-03-11 15:39
Happens also with https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/164/testReport/lwt_schema_modification_test/TestLWTSchemaModification/FullDtest___full_split003___test_index_drop_add/
```
failed on teardown with "AssertionError: Unexpected errors found: [('node1', ["ERROR 2024-03-11 11:03:23,894 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID f0f30190-df96-11ee-9fd7-67661e29bcf0)"
...
```

**Comment by bhalevy** [comment] 2024-03-18 12:03
> Refs #17627

@tgrabiec is it a dup of it?

**Comment by tgrabiec** [comment] 2024-03-18 17:14
Duplicate of https://github.com/scylladb/scylladb/issues/17627

**Closed by tgrabiec** 2024-03-18 17:14 UTC
Labels: P1, symptom/ci stability, area/tablets
