### ISSUE TITLE
truncate table command failed with timeout during rolling upgrade

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#10200] opened 2022-03-13 12:49 UTC
Test details
Test: upgrade_test.UpgradeTest.test_rolling_upgrade
Build number: 19
Backend: gce: eu-west-1
Kernel version: 3.10.0-1160.59.1.el7.x86_64
Test-id: 1e2fd466-7b76-47df-aa15-c3a5bf62493f
Start time: 2022-03-10 17:19:30
End time: 2022-03-10 19:13:29
Started by user: fabio
Cassandra-stress uses shared-aware driver
Test result
FAILED
System under test
ScyllaDB version: 4.6.rc5-0.20220203.5694ec189 with build-id f5d85bf5abe6d2f9fd3487e2469ce1c34304cc14 (-)
Target ScyllaDB repo: https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/branch-4.6/rpm/centos/2022-03-06T14:25:55Z/scylla.repo
Instance type: n1-highmem-8
Number of ScyllaDB nodes: 4
Last events by severity

Restore commands:
Restore Monitor Stack command: $ hydra investigate show-monitor 03f57677-3701-4f63-b18e-9361f0e9842f
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=03f57677-3701-4f63-b18e-9361f0e9842f)
Show all stored logs command: $ hydra investigate show-logs 03f57677-3701-4f63-b18e-9361f0e9842f
Logs:
[grafana - https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_103641/grafana-screenshot-longevity-10gb-3h-test-scylla-per-server-metrics-nemesis-20220304_103852-longevity-10gb-3h-master-monitor-node-03f57677-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_103641/grafana-screenshot-longevity-10gb-3h-test-scylla-per-server-metrics-nemesis-20220304_103852-longevity-10gb-3h-master-monitor-node-03f57677-1.png)
[grafana - https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_103641/grafana-screenshot-overview-20220304_103641-longevity-10gb-3h-master-monitor-node-03f57677-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_103641/grafana-screenshot-overview-20220304_103641-longevity-10gb-3h-master-monitor-node-03f57677-1.png)
[db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_105350/db-cluster-03f57677.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_105350/db-cluster-03f57677.tar.gz)
[loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_105350/loader-set-03f57677.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_105350/loader-set-03f57677.tar.gz)
[monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_105350/monitor-set-03f57677.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_105350/monitor-set-03f57677.tar.gz)
[sct - https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_105350/sct-runner-03f57677.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_105350/sct-runner-03f57677.tar.gz)
Links:
[Build URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-test/446/)
[Download "Overview metrics" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_103641/grafana-screenshot-overview-20220304_103641-longevity-10gb-3h-master-monitor-node-03f57677-1.png)
[Download "Per server metrics nemesis" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_103641/grafana-screenshot-longevity-10gb-3h-test-scylla-per-server-metrics-nemesis-20220304_103852-longevity-10gb-3h-master-monitor-node-03f57677-1.png)
[Download Parallel Timelines report](https://cloudius-jenkins-test.s3.amazonaws.com/03f57677-3701-4f63-b18e-9361f0e9842f/20220304_105350/parallel-timelines-report-03f57677.tar.gz)

scenario: 
1. 2 nodes are upgraded from 4.6 to master. 2 other nodes with 4.6
2. run command of: TRUNCATE ks_no_range_ghost_test.users
3. command failed with:
```
< t:2022-03-10 19:13:12,780 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > TRUNCATE ks_no_range_ghost_test.users < t:2022-03-10 19:13:12,780 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > TRUNCATE ks_no_range_ghost_test.users
< t:2022-03-10 19:13:12,780 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > Traceback (most recent call last):
< t:2022-03-10 19:13:12,780 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3252, in _run_db_queries
< t:2022-03-10 19:13:12,780 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >     res = session.execute(item['queries'][i])
< t:2022-03-10 19:13:12,780 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1302, in execute_verbose
< t:2022-03-10 19:13:12,780 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >     return execute_orig(*args, **kwargs)
< t:2022-03-10 19:13:12,780 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "cassandra/cluster.py", line 2627, in cassandra.cluster.Session.execute
< t:2022-03-10 19:13:12,780 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "cassandra/cluster.py", line 4893, in cassandra.cluster.ResponseFuture.result
< t:2022-03-10 19:13:12,780 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > cassandra.OperationTimedOut: errors={'10.142.0.25:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.142.0.25:9042
< t:2022-03-10 19:13:12,784 f:common.py       l:1309 c:cassandra.cluster    p:DEBUG > Shutting down Cluster Scheduler
< t:2022-03-10 19:13:12,784 f:common.py       l:1309 c:cassandra.cluster    p:DEBUG > Shutting down control connection
```

timeout error from log:
```
ERROR - [1]
2022-03-10 19:13:27.522: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=08d4fd6a-2a04-48e6-9ea8-f194d00d42d0, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 609, in test_rolling_upgrade
self.fill_and_verify_db_data('after upgraded two nodes')
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 464, in fill_and_verify_db_data
self.verify_db_data()
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3362, in verify_db_data
self.run_db_queries(session, session.default_fetch_size)
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3296, in run_db_queries
self._run_db_queries(item, session)
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3256, in _run_db_queries
raise ex
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3252, in _run_db_queries
res = session.execute(item['queries'][i])
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1302, in execute_verbose
return execute_orig(*args, **kwargs)
File "cassandra/cluster.py", line 2627, in cassandra.cluster.Session.execute
File "cassandra/cluster.py", line 4893, in cassandra.cluster.ResponseFuture.result
cassandra.OperationTimedOut: errors={'[10.142.0.25:9042](http://10.142.0.25:9042/)': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=[10.142.0.25:9042](http://10.142.0.25:9042/)
```

**Comment by roydahan** [comment] 2022-03-13 15:54
Probably same as #6309

**Comment by fruch** [comment] 2022-03-30 06:19
seen again in branch-4.6:

seems like scylla is sending this error (a CQL specific error), and not timeout, hence out code doesn't retry (on timeouts we retry 5 times)
```
class TruncateError(RequestExecutionException):
    summary = 'Error during truncate'
    error_code = 0x1003
```

also our default timeout equals to the truncate scylla timeout
``` 
session.default_timeout = 60.0
```

which leads to those errors:
```
cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.142.0.36:9042

or 

cassandra.OperationTimedOut: errors={'[10.142.0.25:9042](http://10.142.0.25:9042/)': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=[10.142.0.25:9042](http://10.142.0.25:9042/)
```
### Restore commands:
Restore Monitor Stack command: $ hydra investigate show-monitor 5421cc1e-f4a1-45f3-b24a-2f69b5a5b171
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=branch-4.6&test_id=5421cc1e-f4a1-45f3-b24a-2f69b5a5b171)
Show all stored logs command: $ hydra investigate show-logs 5421cc1e-f4a1-45f3-b24a-2f69b5a5b171

### Logs:
[grafana - https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_172339/grafana-screenshot-overview-20220328_172339-rolling-upgrade-4-6-centos-monitor-node-5421cc1e-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_172339/grafana-screenshot-overview-20220328_172339-rolling-upgrade-4-6-centos-monitor-node-5421cc1e-0-1.png)
[grafana - https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_172339/grafana-screenshot-rolling-upgrade-centos7-test-scylla-per-server-metrics-nemesis-20220328_172457-rolling-upgrade-4-6-centos-monitor-node-5421cc1e-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_172339/grafana-screenshot-rolling-upgrade-centos7-test-scylla-per-server-metrics-nemesis-20220328_172457-rolling-upgrade-4-6-centos-monitor-node-5421cc1e-0-1.png)
[db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_173314/db-cluster-5421cc1e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_173314/db-cluster-5421cc1e.tar.gz)
[loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_173314/loader-set-5421cc1e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_173314/loader-set-5421cc1e.tar.gz)
[monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_173314/monitor-set-5421cc1e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_173314/monitor-set-5421cc1e.tar.gz)
[sct - https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_173314/sct-runner-5421cc1e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_173314/sct-runner-5421cc1e.tar.gz)

### Links:
[Build URL](https://jenkins.scylladb.com/job/scylla-4.6/job/rolling-upgrade/job/rolling-upgrade-centos7-test/20/)
[Download "Overview metrics" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_172339/grafana-screenshot-overview-20220328_172339-rolling-upgrade-4-6-centos-monitor-node-5421cc1e-0-1.png)
[Download "Per server metrics nemesis" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/5421cc1e-f4a1-45f3-b24a-2f69b5a5b171/20220328_172339/grafana-screenshot-rolling-upgrade-centos7-test-scylla-per-server-metrics-nemesis-20220328_172457-rolling-upgrade-4-6-centos-monitor-node-5421cc1e-0-1.png)

**Comment by soyacz** [comment] 2022-04-07 11:19
5.0 is also suffering from this
## Installation details

Kernel Version: 3.10.0-1160.59.1.el7.x86_64

Scylla version (or git commit hash): `4.6.1-20220328.2309d6b51` with build-id `b82694809fb853b33db490da163c0a46561beb4f`

Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-5-0-centos-db-node-94881f87-0-4 (35.231.116.67 | 10.142.0.229) (shards: 8)
- rolling-upgrade-5-0-centos-db-node-94881f87-0-3 (34.148.96.103 | 10.142.0.39) (shards: 8)
- rolling-upgrade-5-0-centos-db-node-94881f87-0-2 (35.231.79.230 | 10.142.0.225) (shards: 8)
- rolling-upgrade-5-0-centos-db-node-94881f87-0-1 (34.74.173.234 | 10.142.0.223) (shards: 8)


OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: eu-west-1)


Test: `rolling-upgrade-centos7-test`

Test id: `94881f87-802d-4bce-a8ee-dcb7353a6227`

Test name: `rolling-upgrade/rolling-upgrade-centos7-test`

Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/bc98a38562683b13f49421b98071d2a8de1f3a32/test-cases/upgrades/rolling-upgrade.yaml)


- Restore Monitor Stack command: `$ hydra investigate show-monitor 94881f87-802d-4bce-a8ee-dcb7353a6227`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=94881f87-802d-4bce-a8ee-dcb7353a6227)
- Show all stored logs command: `$ hydra investigate show-logs 94881f87-802d-4bce-a8ee-dcb7353a6227`



## Logs:
- **db-cluster-94881f87.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/94881f87-802d-4bce-a8ee-dcb7353a6227/20220406_230134/db-cluster-94881f87.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/94881f87-802d-4bce-a8ee-dcb7353a6227/20220406_230134/db-cluster-94881f87.tar.gz)
- **monitor-set-94881f87.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/94881f87-802d-4bce-a8ee-dcb7353a6227/20220406_230134/monitor-set-94881f87.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/94881f87-802d-4bce-a8ee-dcb7353a6227/20220406_230134/monitor-set-94881f87.tar.gz)
- **loader-set-94881f87.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/94881f87-802d-4bce-a8ee-dcb7353a6227/20220406_230134/loader-set-94881f87.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/94881f87-802d-4bce-a8ee-dcb7353a6227/20220406_230134/loader-set-94881f87.tar.gz)
- **sct-runner-94881f87.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/94881f87-802d-4bce-a8ee-dcb7353a6227/20220406_230134/sct-runner-94881f87.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/94881f87-802d-4bce-a8ee-dcb7353a6227/20220406_230134/sct-runner-94881f87.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/rolling-upgrade/job/rolling-upgrade-centos7-test/7/)

**Comment by enaydanov** [comment] 2022-04-11 14:09
## Installation details

Kernel Version: 3.10.0-1160.59.1.el7.x86_64
Scylla version (or git commit hash): 4.6.1-0.20220328.2309d6b51 with build-id b82694809fb853b33db490da163c0a46561beb4f
Cluster size: 4 nodes (n1-highmem-8)
OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: eu-west-1)
Test: `rolling-upgrade-centos7-test`
Test id: 606f5631-6963-4914-8367-79a7a4322412
 
Test name: `rolling-upgrade/rolling-upgrade-centos7-test`

* Restore Monitor Stack command: `$ hydra investigate show-monitor 606f5631-6963-4914-8367-79a7a4322412`

* Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=606f5631-6963-4914-8367-79a7a4322412)

* Show all stored logs command: `$ hydra investigate show-logs 606f5631-6963-4914-8367-79a7a4322412`
 
 
## Logs:

[grafana - https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_134620/grafana-screenshot-overview-20220410_134620-rolling-upgrade-4-6-centos-monitor-node-606f5631-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_134620/grafana-screenshot-overview-20220410_134620-rolling-upgrade-4-6-centos-monitor-node-606f5631-0-1.png)
[grafana - https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_134620/grafana-screenshot-rolling-upgrade-centos7-test-scylla-per-server-metrics-nemesis-20220410_134736-rolling-upgrade-4-6-centos-monitor-node-606f5631-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_134620/grafana-screenshot-rolling-upgrade-centos7-test-scylla-per-server-metrics-nemesis-20220410_134736-rolling-upgrade-4-6-centos-monitor-node-606f5631-0-1.png)
[db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_135615/db-cluster-606f5631.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_135615/db-cluster-606f5631.tar.gz)
[loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_135615/loader-set-606f5631.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_135615/loader-set-606f5631.tar.gz)
[monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_135615/monitor-set-606f5631.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_135615/monitor-set-606f5631.tar.gz)
[sct - https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_135615/sct-runner-606f5631.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/606f5631-6963-4914-8367-79a7a4322412/20220410_135615/sct-runner-606f5631.tar.gz)

[Build URL](https://jenkins.scylladb.com/job/scylla-4.6/job/rolling-upgrade/job/rolling-upgrade-centos7-test/25/)

**Comment by roydahan** [comment] 2022-04-28 13:43
@DoronArazii / @slivne please assign

**Comment by DoronArazii** [comment] 2022-05-16 11:16
per @roydahan this is not a regression

**Comment by avikivity** [comment] 2022-05-17 14:37
@bhalevy I thought we improved truncate, but maybe it's only on master.

```c++
future<> table::clear() {
    auto permits = co_await _config.dirty_memory_manager->get_all_flush_permits();
    if (_commitlog) {
        for (auto& t : *_memtables) {
            _commitlog->discard_completed_segments(_schema->id(), t->get_and_discard_rp_set());
        }
    }
    auto old_memtables = _memtables->clear_and_add();
    for (auto& smt : old_memtables) {
        co_await smt->clear_gently();
    }
    co_await _cache.invalidate(row_cache::external_updater([] { /* There is no underlying mutation source */ }));
}
```

Two things we can improve:

1. move the loop that clears old_memtables to a background thread. We have to wait for it during shutdown, but not during truncate.
2. Instead of invalidating the cache in the foreground, create a new cache, and invalidate the old one in the background. Alternatively, teach the cache to do the same thing (move the internal btree somewhere and clear it in the background, and instantiate a new tree immediately).

This makes memtable/cache operations O(1) instead of O(data).

**Comment by avikivity** [comment] 2022-05-17 14:37
Anyway, we should close this in favor of the original report.

**Comment by fgelcer** [comment] 2022-05-23 11:02
> Anyway, we should close this in favor of the original report.

that is a good question, should we still use (in this case) the original issue, or use this (or one of the new ones) to report new reproductions of this failure?
IIRC @slivne asked to not use old ones

**Comment by avikivity** [comment] 2022-05-23 11:35
Why not use the old ones? What will we do with all the duplicates?

**Comment by mykaul** [comment] 2022-12-20 07:27
Duplicate of https://github.com/scylladb/scylladb/issues/6309

**Closed by mykaul** 2022-12-20 07:27 UTC
