### ISSUE TITLE
Reactor stall when building group0 snapshot with lots of tablets

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#15303] opened 2023-09-06 12:37 UTC
Example:
```
Reactor stalled for 65 ms on shard 0. Backtrace: 0x590429a 0x59036a5 0x5904a4f 0x3db6f 0x1d0abcc 0x1d230ef 0x1df838e 0x1cc447a 0x1bc028a 0x1bb1faa 0x591573f 0x5916977 0x5915ce9 0x58b9267 0x58b841c 0x58b95cc 0x4fe6be3 0x1297eb0 0x12949ce 0x27b49 0x27c0a 0x1292764

 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1178
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1458
?? ??:0
intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::leftmost_node() const at ././utils/intrusive_btree.hh:337
 (inlined by) intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::cbegin() const at ././utils/intrusive_btree.hh:939
 (inlined by) intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::begin() at ././utils/intrusive_btree.hh:951
 (inlined by) std::pair<intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::iterator, bool> intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::insert_before_hint<std::unique_ptr<rows_entry, alloc_strategy_deleter<rows_entry> > >(intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::iterator, std::unique_ptr<rows_entry, alloc_strategy_deleter<rows_entry> >, rows_entry::tri_compare) at ././utils/intrusive_btree.hh:415
mutation_partition::append_clustered_row(schema const&, position_in_partition_view, seastar::bool_class<dummy_tag>, seastar::bool_class<continuous_tag>) at ./mutation/mutation_partition.cc:700
partition_builder::accept_row(position_in_partition_view, row_tombstone const&, row_marker const&, seastar::bool_class<dummy_tag>, seastar::bool_class<continuous_tag>) at ././partition_builder.hh:57
 (inlined by) void mutation_partition_view::do_accept<partition_builder>(column_mapping const&, partition_builder&) const at ./mutation/mutation_partition_view.cc:214
frozen_mutation::unfreeze(seastar::lw_shared_ptr<schema const>) const at ./mutation/frozen_mutation.cc:97
replica::read_tablet_mutations(seastar::sharded<replica::database>&) at ./replica/tablets.cc:240
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<std::vector<canonical_mutation, std::allocator<canonical_mutation> > >::promise_type>::resume() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/coroutine:240
 (inlined by) seastar::internal::coroutine_traits_base<std::vector<canonical_mutation, std::allocator<canonical_mutation> > >::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:83
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2597
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:3060
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3229
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3112
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:276
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:167
seastar::app_template::run(int, char**, std::function<seastar::future<void> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:182
perf::scylla_tablets_main(int, char**) at ./test/perf/perf_tablets.cc:155
std::function<int (int, char**)>::operator()(int, char**) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
```

Relevant code:

```c++
future<std::vector<canonical_mutation>> read_tablet_mutations(seastar::sharded<replica::database>& db) {
    auto s = db::system_keyspace::tablets();
    auto rs = co_await db::system_keyspace::query_mutations(db, db::system_keyspace::NAME, db::system_keyspace::TABLETS);
    std::vector<canonical_mutation> result;
    result.reserve(rs->partitions().size());
    for (auto& p: rs->partitions()) {
        result.emplace_back(canonical_mutation(p.mut().unfreeze(s)));
    }
    co_return std::move(result);
}
```

There are two problems:
1) No yields across partitions (per-table tablet_map)
2) unfreeze() works on whole tablet_map, which can also be large enough to cause stalls

Possible solutions:
1) Don't use query_mutations() but use a paged consumer like read_tablet_metadata() does, and split mutations based on size
2) Change group0 snapshotting to use some form of streaming of system tables instead of mutations

**Comment by tgrabiec** [comment] 2023-09-06 12:38
@kbr-scylla  Are there any plans to "Change group0 snapshotting to use some form of streaming of system tables instead of sending mutations"?

**Comment by kbr-scylla** [comment] 2023-09-06 12:43
Not that I know of.

But isn't "group 0 snapshotting" too wide? I.e., some parts of group 0 snapshot could be small enough to just transfer the entire mutations; some parts could be large, and these would have to be streamed in some way.

cc @gleb-cloudius @kostja 
We should consider adding this to the topology plan.
OTOH I don't know if we need to do this for schema topology.

It's certainly a fact that we did release schema-on-group0 with "dumb" snapshotting. And we did observe some problems with that already (hitting commitlog size limit when applying schema).

Question is whether we want to do the same with topology... But isn't topology even smaller than schema?

**Comment by gleb-cloudius** [comment] 2023-09-06 12:53
> Not that I know of.
> 
> But isn't "group 0 snapshotting" too wide? I.e., some parts of group 0 snapshot could be small enough to just transfer the entire mutations; some parts could be large, and these would have to be streamed in some way.
> 
> cc @gleb-cloudius @kostja We should consider adding this to the topology plan. OTOH I don't know if we need to do this for core topology.
> 
> It's certainly a fact that we did release schema-on-group0 with "dumb" snapshotting. And we did observe some problems with that already (hitting commitlog size limit when applying schema).

That turned out to be "schema commitlog" regression, not schema over raft one :)
But what do you mean by "dump" snapshot? The one that is applied at transfer time? This is orthogonal to how it is transferred.
 
> 
> Question is whether we want to do the same with topology... But isn't topology even smaller than schema? (well ok, tablet metadata probably isn't, but dunno about the rest of it)

Legacy topology should not be huge. Of course if we will do something dump we can end up with a lot of tombstones there for instance.

**Comment by kbr-scylla** [comment] 2023-09-06 12:55
>  But what do you mean by "dump" snapshot? The one that is applied at transfer time? This is orthogonal to how it is transferred.

Dumb i.e. stupid i.e. transferred in a stupid way, as a single blob instead of in parts like with streaming.

**Comment by kostja** [comment] 2023-09-07 06:37
I agree we need to stream snapshots piecemeal.

**Comment by kbr-scylla** [comment] 2023-12-05 14:45
@kostja @tgrabiec @bhalevy please decide which team/group is responsible for delivering this -- storage team/group (since its tablets related, and tablets metadata is what seems to be the largest part of group 0 state) or cluster team (since it's group 0)

**Comment by avikivity** [comment] 2023-12-05 14:49
Seems like it's a generic raft problem.

Didn't we agree to transfer snapshots using repair?

**Comment by gleb-cloudius** [comment] 2023-12-05 14:57
> Seems like it's a generic raft problem.
> 

Snapshot transfer is outside raft, so it is anything but raft problem. Schema part of the goup0 for instance is transferred by pre-existing schema_pull function.

**Comment by avikivity** [comment] 2023-12-05 15:54
I meant the integration of Raft into scylladb, not the PhD or its implementation in scylladb.

**Comment by gleb-cloudius** [comment] 2023-12-05 16:00
> I meant the integration of Raft into scylladb, not the PhD or its implementation in scylladb.

And the integration consists of many part since we managed multiple (sub) state machines  in group0 and constantly add more. And that what @kbr-scylla was asking: should anyone who extends group0 with new parts make sure that their code does not stall or should it be the responsibility of poor sods who happen to introduce group0 in the first place.

**Comment by avikivity** [comment] 2023-12-05 17:46
If it's a custom integration then it should be done by the tablets team.

**Comment by kbr-scylla** [comment] 2023-12-05 18:39
The ideal solution would be to provide a generic framework for piecewise transfer of table (or set of tables) contents.

For schema mutations we transfer as a single blob of mutations with a single RPC call, because we reused existing migration_manager schema pull code.

For `system.topology` we transfer a single blob because it was the easiest thing to implement. It didn't seem to cause any problem yet, `system.topology` itself is not a large table. Although of course it might turn otherwise when we test large clusters.

For `system.tablets` the pattern was continued. But now it turns out that `system.tablets` is too large for a single blob transfer.

Now the question is who should develop this generic framework, if at all (or continue solving the problem again and again for each new addition separately).

It seems that this issue is not a blocker for releasing raft-based topology, but it may be a blocker for releasing tablets (although maybe it's a rare stall so not really a blocker?)

**Comment by kbr-scylla** [comment] 2023-12-05 20:04
> It shouldn't be hard to invoke streaming or repair for all group0 tables.

I don't know if it's that simple -- different components may require different atomicity / isolation guarantees, for example. IIUC streaming/repair doesn't provide much in that regard.

**Comment by kostja** [comment] 2023-12-05 21:05
I think we need to come up with a solution first. I remember you @kbr-scylla investigated the problem when working on strongly consistent tables, and created a rather sophisticated design document for it. Let's dig it up and discuss at the next raft call.

**Comment by bhalevy** [comment] 2024-02-15 13:41
Let's start with the low hanging fruit (adding maybe_yield) in 6.0
and improve the solution later on if needed.

**Comment by bhalevy** [comment] 2024-02-16 13:23
Actually since the table_id is the partition key in system.tablets and there's a row per table, I suggest:
```diff
diff --git a/replica/tablets.cc b/replica/tablets.cc
index d9528881df..703a6a89f2 100644
--- a/replica/tablets.cc
+++ b/replica/tablets.cc
@@ -303,7 +303,7 @@ future<std::vector<canonical_mutation>> read_tablet_mutations(seastar::sharded<r
     std::vector<canonical_mutation> result;
     result.reserve(rs->partitions().size());
     for (auto& p: rs->partitions()) {
-        result.emplace_back(canonical_mutation(p.mut().unfreeze(s)));
+        result.emplace_back(canonical_mutation(co_await p.mut().unfreeze_gently(s)));
     }
     co_return std::move(result);
 }
```

It might be possible later on to build the canonical_mutation directly from the frozen mutation with unfreezing it first.
I'd consider defining a canonical_mutation_builder derived from partition_builder, which will essentially do what `mutation_partition_serializer::write_serialized` does in-line while "unfreezing" the frozen_mutation into a canonical mutation.  See `mutation_partition_view::do_accept_gently`.

**Comment by bhalevy** [comment] 2024-02-28 04:46
ping @kostja how about the above proposal?

**Comment by kbr-scylla** [comment] 2024-03-07 16:19
@bhalevy your proposal looks good for dealing with the stall, but it likely won't be sufficient for the more general problem of tablets metadata being large and not being possible to apply in a single command.

**Comment by kbr-scylla** [comment] 2024-03-07 16:21
> more general problem

to be precise it's a different problem, and a bit harder to solve

**Comment by kostja** [comment] 2024-03-07 16:42
@kbr-scylla I think for now it's sufficient to deal with the stall. @bhalevy could you sent it as a pull request?

**Closed** 2024-03-08 14:44 UTC
Labels: symptom/latency, area/topology changes, area/raft, symptom/stalls, area/tablets
