### ISSUE TITLE
Use a dedicated scheduling group for schema commitlog

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15566] opened 2023-09-27 14:47 UTC
Schema commitlog uses the default scheduling group, `main`.
Maybe we should use a dedicated scheduling group for schema commitlog, with appropriately adjusted number of shares?

Also, what other tasks are running on `main`? (Maybe `main` is already exclusive to schema commitlog...)

cc @xemul @kostja @gleb-cloudius @tgrabiec @avikivity

**Comment by avikivity** [comment] 2023-09-27 15:44
`main` should be left alone so things we forget have somewhere to live.

I'm not thrilled about adding a new scheduling group but it's the right thing to do.

Better is to have nested groups (and so commitlog/data and commitlog/schema).

**Comment by xemul** [comment] 2023-09-27 15:46
nested sched groups: https://github.com/scylladb/seastar/issues/1070

**Comment by kbr-scylla** [comment] 2023-10-16 14:53
@kostja please decide who should work on this -- storage group or your group?

**Comment by kostja** [comment] 2023-10-17 18:37
@kbr-scylla depends on how you suggest to fix it. Nested scheduling groups?

**Comment by kbr-scylla** [comment] 2023-10-18 08:27
Not necessarily, if it's too much effort we could simply have a separate normal scheduling group.

**Comment by kbr-scylla** [comment] 2023-12-05 15:31
> @kostja please decide who should work on this -- storage group or your group?

@kostja ping

I think this should belong to Storage.

**Comment by kostja** [comment] 2023-12-13 11:25
So this issue actually breaks down into 3 or 4 related items.

Let me first write what the goal of this issue is: we want to make sure that there is no priority inversion between the data path and the schema path. E.g. when a node needs to make a read barrier to fetch the latest schema, and this barrier needs to write schema mutations to the schema commit log, these writes are not queued behind data path writes to data commit log and compaction.  At the end of the day it manifests with latency spikes in clusters which alter tables under heavy load (todo: we need a link to the original issue here).

In order to fix that we need to do multiple things:
1) change the scheduling group for the commit log; this seems to be trivial, and can be done when creating the commit log in system_tables.cc
2) We need to make sure the schema commit log is using a differetn IO priority class than the rest of the writes. This is not implemented, neither in the commit log API nor at the instantiation place.
3) we need to retest to see if it helps.

**Comment by kbr-scylla** [comment] 2023-12-14 07:24
> At the end of the day it manifests with latency spikes in clusters which alter tables under heavy load (todo: we need a link to the original issue here).

https://github.com/scylladb/scylladb/issues/15622

The issue is fixed.

Schema commit log is already using a separate scheduling group from regular commitlog -- the main scheduling group, but as @avikivity said, "main should be left alone so things we forget have somewhere to live."

The above issue was caused by a priority inversion as you described, but the problem was not commitlog as initially suspected, it was using the user data memory pool for Raft tables -- so schema writes were waiting for user memtable flushes.

I think there is no longer a concept of IO priority classes, they were merged with scheduling groups (?)

There really is nothing else to be done than creating a separate scheduling group for schema commitlog, I think.

**Comment by eliransin** [comment] 2024-01-29 17:02
> I think there is no longer a concept of IO priority classes, they were merged with scheduling groups (?)

This is correct.

@kbr-scylla if the issue is fixed why don't we close this one?

**Comment by kbr-scylla** [comment] 2024-01-30 08:35
Sorry for confusion @eliransin I meant that https://github.com/scylladb/scylladb/issues/15622 is fixed (which was the cause of latency spikes that Kostja mentioned)

The current issue is not fixed, schema commitlog is in `main` group while (I believe) it should have its own

**Comment by mykaul** [comment] 2024-03-10 16:00
Will it make to 6.0?

**Comment by kostja** [comment] 2024-05-02 20:43
See also https://github.com/scylladb/scylladb/issues/1926

**Closed** 2024-05-21 15:57 UTC
Labels: area/schema changes, area/commitlog, area/topology changes
