### ISSUE TITLE
Issue in page Upgrade Guide - Scylla 4.5 to 4.6 for Ubuntu 20.04

### ISSUE THREAD

**Issue by praveenkhatra** [scylladb/scylladb#11268] opened 2022-08-10 12:22 UTC
I would like to report an issue in page https://docs.scylladb.com/master/upgrade/upgrade-opensource/upgrade-guide-from-4.5-to-4.6/upgrade-guide-from-4.5-to-4.6-ubuntu-20-04

### Problem
Unable to use nodetool command.
nodetool: Failed to connect to '127.0.0.1:7199' - URISyntaxException: 'Malformed IPv6 address at index 7: rmi://[127.0.0.1]:7199'.
# curl -v 127.0.0.1:7199
*   Trying 127.0.0.1:7199...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 7199 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:7199
> User-Agent: curl/7.68.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server

###  Suggest a fix

# curl -X GET "http://localhost:10000/storage_service/scylla_release_version"
"4.6.2-0.20220405.eb372d7f0"

tcp6       0      0 127.0.0.1:7199          :::*                    LISTEN      2806/scylla-jmx

I don't see any errors or warning in the log file.

**Comment by slivne** [comment] 2022-08-11 07:38
@praveenkhatra 
this is a duplicate of #10442

the fix is part of 4.6.4 and later releases - please upgrade to that release or latest avail 4.6.5

I am closing this issue - if you have further questions please reopen and provide an update

**Closed** 2022-08-11 07:38 UTC
Labels: duplicate, User Request

**Comment by praveenkhatra** [comment] 2022-08-11 11:50
Hi @slivne ,
Thanks for the update. After upgrade the version I am able to use the nodetool commands and able to add new node to the cluster.
One part that I found  misleading is  curl output providing the wring version info.
After Upgrade to 4.6.5 :

# curl -X GET "http://localhost:10000/storage_service/scylla_release_version"
"4.6.2-0.20220405.eb372d7f0"


# dpkg -s scylla-server.  ( This provides the correct package version installed)
Package: scylla-server
Status: install ok installed
Priority: optional
Section: database
Installed-Size: 149271
Maintainer: Takuya ASADA <syuu@scylladb.com>
Architecture: amd64
Version: 4.6.5-0.20220719.2ec293ab0-1
Depends: scylla-conf (= 4.6.5-0.20220719.2ec293ab0-1), scylla-python3 (= 4.6.5-0.20220719.2ec293ab0-1)

 Do you know ifI have to update any other config to fix the release output?
