### ISSUE TITLE
Creating an MV with ID parameter results in an unexpected result

### ISSUE THREAD

**Issue by dawmd** [scylladb/scylladb#20616] opened 2024-09-16 11:30 UTC
The current grammar of CQL used by Scylla allows for creating a materialised view specifying its ID. However, the created MV uses a different ID. Although the official documentation doesn't mention the ID option, so it's probably not a problem to treat it arbitrarily, the `DESCRIBE SCHEMA WITH INTERNALS` statement uses it in returned create statements.

We should either specify the semantics of the option and stick to it, or stop using it in `DESCRIBE` statements.

---

Steps to reproduce:

```sql
cassandra@cqlsh> CREATE KEYSPACE some_ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cassandra@cqlsh> CREATE TABLE some_ks.some_table (pk int PRIMARY KEY);
cassandra@cqlsh> CREATE MATERIALIZED VIEW some_ks.some_mv AS
   ... SELECT pk
   ... FROM some_ks.some_table
   ... WHERE pk IS NOT NULL
   ... PRIMARY KEY (pk)
   ... WITH ID = b5310320-7418-11ef-acfe-491536e0fa07;
```

Scylla reports that the materialised view has been created, but its ID is different from the specified one, e.g.:

```log
INFO  2024-09-16 13:06:48,756 [shard 0: gms] schema_tables - Creating some_ks.some_mv id=c4db7370-741b-11ef-880c-12d058685c53 version=c4db7371-741b-11ef-880c-12d058685c53
```

---

Scylla version: 6.2.0~dev-0.20240916.028410ba5868
cqlsh version: 6.0.23.dev5+gdaf4c2f

**Comment by piodul** [comment] 2024-09-16 11:41
Most likely it was never a problem for anyone - the only place where I can see that it could be a problem is restore of materialized views contents from backup. However, such an operation does not make much sense - and we recommend against it ([link](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/restore.html)) - because a materialized view can be recreated from the base table.

I suppose that this bug was discovered while testing https://github.com/scylladb/scylladb/pull/20168 with a round-trip test (i.e. create and describe stuff twice, compare the output of describe). If that's the case, and if Cassandra supports the `WITH ID` part, then I think we should just fix the code to make `WITH ID` work properly.

**Comment by nyh** [comment] 2024-09-16 11:43
In create_table_statement.cc, we use `_properties.properties()->get_id()` to extract and use the "WITH ID" option. In create_view_statement.cc, this code is missing.

To add insult to injury, CREATE MATERIALIZED VIEW doesn't even report that it didn't use this WITH option. If I use "WITH dog=cat", it would also be silently ignored? This should be fixed too.

**Comment by dawmd** [comment] 2024-09-16 12:59
I'm not sure if I interpret the documentation correctly, but it seems that Cassandra doesn't support the option:

```sql
CREATE MATERIALIZED VIEW [IF NOT EXISTS] [keyspace_name.] view_name
AS SELECT column_list
FROM [keyspace_name.] base_table_name
WHERE column_name IS NOT NULL [AND column_name IS NOT NULL ...] 
      [AND relation...] 
PRIMARY KEY ( column_list )
[WITH [table_properties]
      [AND CLUSTERING ORDER BY (cluster_column_name order_option )]]
```
(via [cqlCreateMaterializedView](https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/cqlCreateMaterializedView.html))

The `table_properties` values are defined [here](https://docs.datastax.com/en/cql-oss/3.1/cql/cql_reference/tabProp.html) and `ID` doesn't seem to be present.

**Comment by nyh** [comment] 2024-09-17 16:22
> I'm not sure if I interpret the documentation correctly

This is one of the reasons why it was so important to me that test/cql-pytest tests run on both Cassandra and Scylla - it makes it very easy to try some command on Cassandra without learning how to actually run Cassandra manually (see test/cql-pytest/README.md). So you don't need to "interpret" the documentation - which is often inaccurate - to understand how a Cassandra feature behaves - you can just try it. And as a bonus, exactly the same test can run against Scylla too, and become a regression test.

> , but it seems that Cassandra doesn't support the option:

The Cassandra source code I looked at suggests that it does: from `src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java`:
```java
        if (attrs.hasProperty(TableAttributes.ID))
            builder.id(attrs.getId());
```

But both source code and documentation can be mis-interpreted (maybe this code doesn't do what I think it do). A test will tell you the truth.

**Comment by dawmd** [comment] 2024-09-23 17:13
Thank you, Nadav, for looking into this. I tested the option against Cassandra 5.1 and it respects it indeed. Providing an ID will result in a materialised view with that specific ID. If there's already an MV bearing that ID, we'll get an error, e.g.:

```sql
NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.0.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="java.lang.IllegalStateException: Map already contains 1b255f4d-ef25-40a6-0000-aaaabbbb0006">})
```

Since the option doesn't seem to be covered by Cassandra's documentation, I don't think we should mention it in our user documentation either. Implementing it and explaining the rationale in an appropriate place (commit message + dev docs?) should be enough.

**Comment by nyh** [comment] 2024-09-23 20:25
I wrote a small test and to my surprise discovered that our implementation of "WITH" doesn't silently ignore **any** name it doesn't know how to handle - e.g., `WITH garbagename = 'hello'` will be rejected with an "Unknown property 'garbagename'" error. So somehow it is recognizing - but then ignoring - this "ID" option.

It turns out the culprit which prevents an error on this unrecognized ID function (which would have been better than silently ignoring it) is the function `cf_prop_defs::validate()` in cql3/statements/cf_prop_defs.cc.

It turns out that that function has a list of supported options:
```
    static std::set<sstring> keywords({
        KW_COMMENT,
        KW_GCGRACESECONDS, KW_CACHING, KW_DEFAULT_TIME_TO_LIVE,
        KW_MIN_INDEX_INTERVAL, KW_MAX_INDEX_INTERVAL, KW_SPECULATIVE_RETRY,
        KW_BF_FP_CHANCE, KW_MEMTABLE_FLUSH_PERIOD, KW_COMPACTION,
        KW_COMPRESSION, KW_CRC_CHECK_CHANCE,  KW_ID, KW_PAXOSGRACESECONDS,
        KW_SYNCHRONOUS_UPDATES
    });
    static std::set<sstring> obsolete_keywords({
        sstring("index_interval"),
        sstring("replicate_on_write"),
        sstring("populate_io_cache_on_flush"),
        sstring("read_repair_chance"),
        sstring("dclocal_read_repair_chance"),
    });
```

KW_ID is on that list, so an ID option is allowed by every function that calls this validate() function, including cql3/statements/create_view_statement.cc which calls it in
```
    _properties.validate(db, keyspace(), schema_extensions);
```

But we should either accept that different statements accept different options and call a **different** validation function (or different options for the same validation function) for each statement type, or, alternatively, we should make sure that each statement type must support (or at least print an error on) each option that its validator allows but it really doesn't know how to support.

**Closed** 2024-10-03 10:16 UTC
Labels: area/materialized views, status/missing information, backport/none, area/backup and restore
