### ISSUE TITLE
off-strategy compaction causes high read latency 

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#11040] opened 2022-07-14 07:19 UTC
Test report: 

https://groups.google.com/a/scylladb.com/g/scylla-perf-results/c/7Y2EFr21U-4

Procedure:

n1, n2, n3 was added to the cluster
repair was performed  on n1, n2, n3
n2 is killed
n4 replaces n2

Important timeline:
```
First repair
2022-07-11T14:02:42+00:00  perf-latency-nemesis-perf-v12-db-node-b6e3deb1-1 !INFO    | scylla:  [shard 0] repair - repair[9ac066da-9127-4583-9e86-ed1910245ff8]: starting user-requested repair for keyspace system_traces, 

Last repair
2022-07-11T14:20:28+00:00  perf-latency-nemesis-perf-v12-db-node-b6e3deb1-2 !INFO    | scylla[6586]: [shard 0] repair - repair[57748c38-5256-48b9-98c2-02a2e8f8afe1]: starting user-requested repair for keyspace keyspace1,


Off-strategy starts after repair (First read latency spike starts)
perf-latency-nemesis-perf-v12-db-node-b6e3deb1-1/messages.log:2022-07-11T14:25:37+00:00  perf-latency-nemesis-perf-v12-db-node-b6e3deb1-1 !INFO    | scylla:  [shard 6] compaction - [Reshape keyspace1.standard1 557a2780-0125-11ed-bc

Replace ops starts (Second read latency spike starts)
2022-07-11T14:40:18+00:00  perf-latency-nemesis-perf-v12-db-node-b6e3deb1-4 !INFO    | scylla[6506]: [shard 0] storage_service - Replacing a node with a different IP address, my address=10.0.2.246, node being replaced=10.0.0.189


Off-strategy for replace starts 

2022-07-11T15:08:10+00:00  perf-latency-nemesis-perf-v12-db-node-b6e3deb1-4 !INFO    | scylla:  [shard 6] compaction_manager - Starting off-strategy compaction for keyspace1.standard1, 712 candidates were found
2022-07-11T15:08:10+00:00  perf-latency-nemesis-perf-v12-db-node-b6e3deb1-4 !INFO    | scylla:  [shard 6] compaction_manager - Starting off-strategy compaction for keyspace1.standard1, 712 candidates were found
2022-07-11T15:10:02+00:00  perf-latency-nemesis-perf-v12-db-node-b6e3deb1-4 !INFO    | scylla[6506]: [shard 0] compaction - [Reshape keyspace1.standard1 8a0c3230-012b-11ed-aec4-6230d23a0af3] Reshaping

Replace ops finishes and server startup finishes
2022-07-11T15:12:08+00:00  perf-latency-nemesis-perf-v12-db-node-b6e3deb1-4 !INFO    | scylla:  [shard 0] init - Scylla version 5.1.dev-0.20220711.7e2d2cf1c18d initialization completed.

Off-strategy for replace continues (Third read latency spike)
2022-07-11T15:26:31+00:00  perf-latency-nemesis-perf-v12-db-node-b6e3deb1-4 !INFO    | scylla:  [shard 3] compaction - [Reshape keyspace1.standard1 9278df90-012b-11ed-a058-622ed23a0af3] Reshaped 713 sstables to 

First bootstrap starts
2022-07-11T15:29:01+00:00  perf-latency-nemesis-perf-v12-db-node-b6e3deb1-4 !INFO    | scylla:  [shard 0] stream_session - [Stream #30d4a8c0-012e-11ed-a8dc-d9878fcc0156] Executing streaming plan for Bootstrap-keyspace1-index-0 with
```

Latency:
The yellow line is p99 read latency. 
Read latency spike 1 is during off-strategy compaction for repair ops
Read latency spike 2.1 is during off-replace ops itself.
Read latency spike 2.2 is during off-strategy compaction for replace ops
Read latency spike 3 is at the end of off-strategy compaction for replace ops

![image](https://user-images.githubusercontent.com/320076/178922664-4b4423ce-b3aa-4d51-bd08-481becfc4faa.png)

There were 3000+ stalls. The stall detector threshhold is 5ms .

[stalls.txt](https://github.com/scylladb/scylla/files/9109401/stalls.txt)

Off-strategy reshape log:

[reshape.start.end.txt](https://github.com/scylladb/scylla/files/9109427/reshape.start.end.txt)

![image](https://user-images.githubusercontent.com/320076/178924404-75d04b75-e916-4c36-904c-2f82f209b4b1.png)

**Comment by raphaelsc** [comment] 2022-07-18 16:42
> Test report:
> 
> https://groups.google.com/a/scylladb.com/g/scylla-perf-results/c/7Y2EFr21U-4

cannot access this. 

> 
> P
> ![image](https://user-images.githubusercontent.com/320076/178922664-4b4423ce-b3aa-4d51-bd08-481becfc4faa.png)
> 
> There were 3000+ stalls. The stall detector threshhold is 5ms .
> 
> [stalls.txt](https://github.com/scylladb/scylla/files/9109401/stalls.txt)

please decode the stalls, wasn't able to find scylla version in the logs.

> 
> Off-strategy reshape log:
> 
> [reshape.start.end.txt](https://github.com/scylladb/scylla/files/9109427/reshape.start.end.txt)
> 
> ![image](https://user-images.githubusercontent.com/320076/178924404-75d04b75-e916-4c36-904c-2f82f209b4b1.png)

**Comment by asias** [comment] 2022-07-19 01:51
@raphaelsc See https://github.com/scylladb/scylla/issues/11038


You can find the binary here:

https://github.com/scylladb/scylla/issues/11038#issuecomment-1186692721

The decode:
https://github.com/scylladb/scylla/issues/11038#issuecomment-1185530113

**Comment by asias** [comment] 2022-07-19 01:53
> > Test report:
> > https://groups.google.com/a/scylladb.com/g/scylla-perf-results/c/7Y2EFr21U-4
> 
> cannot access this.

Try subscribe to: https://groups.google.com/a/scylladb.com/g/scylla-perf-results

**Comment by bhalevy** [comment] 2022-07-23 09:09
@raphaelsc is it possible that since the maintenance sstables are not written as a run, with the same run id, although they are disjoint, the partitioned_sstable_set created for reshape compaction doesn't select them incrementally, but rather reads them all in parallel, thus creating memory allocation pressure (for over 700 sstables)?

**Comment by raphaelsc** [comment] 2022-07-23 18:10
> @raphaelsc is it possible that since the maintenance sstables are not written as a run, with the same run id, although they are disjoint, the partitioned_sstable_set created for reshape compaction doesn't select them incrementally, but rather reads them all in parallel, thus creating memory allocation pressure (for over 700 sstables)?

partition_sstable_set is ring_position aware, so even though the disjoint files are written using different run id, the incremental selector will still be able to operate on the disjointness, feeding one file at a time to be consumed by the combined reader.

**Comment by slivne** [comment] 2022-07-27 07:39
@bhalevy / @raphaelsc - any news ?

**Comment by raphaelsc** [comment] 2022-07-27 20:21
> @bhalevy / @raphaelsc - any news ?

restored monitoring, I am still investigating it. We suspected readers of reshape compaction were kept alive until completion, leading to a memory pressure, but I ruled it out as the merging reader is able to discard sstable readers once they become exhausted.

**Comment by raphaelsc** [comment] 2022-07-27 20:22
@asias repair-based replace has been enabled by default for a long time already. do you suspect this is a regression?

**Comment by bhalevy** [comment] 2022-07-28 04:46
> Btw, you can play with off strategy using --blocked-reactor-notify-ms 1 to find the stalls to see if it is originated from off strategy compaction and if there is anything we can do in compaction to improve the stalls.

Aren't the stalls we already know about an indication of memory pressure?

I'm not saying we can't improve other paths, but we should not lose focus on the main problem.

**Comment by asias** [comment] 2022-07-29 00:27
> > Btw, you can play with off strategy using --blocked-reactor-notify-ms 1 to find the stalls to see if it is originated from off strategy compaction and if there is anything we can do in compaction to improve the stalls.
> 
> Aren't the stalls we already know about an indication of memory pressure?

We only know about the stalls bigger than 5ms. There could have smaller stalls that contributes to the delay. 

The test was run with: 

append_scylla_args: --blocked-reactor-notify-ms 5 

> 
> I'm not saying we can't improve other paths, but we should not lose focus on the main problem.

We already have https://github.com/scylladb/scylladb/issues/11038 to track the memory related issue. I think Raphael is not going to fix the memory allocator part. 

When I ran with '--blocked-reactor-notify-ms 1 ', I saw plenty of small stalls from compaction. Yes, the 1 ms detecor might not be accurate according to Avi, but it might help us point to code in compaction that could be improved in terms of reducing stalls even with false positive stall report.

**Comment by raphaelsc** [comment] 2022-07-29 02:13
> > > Btw, you can play with off strategy using --blocked-reactor-notify-ms 1 to find the stalls to see if it is originated from off strategy compaction and if there is anything we can do in compaction to improve the stalls.
> > 
> > 
> > Aren't the stalls we already know about an indication of memory pressure?
> 
> We only know about the stalls bigger than 5ms. There could have smaller stalls that contributes to the delay.
> 
> The test was run with:
> 
> append_scylla_args: --blocked-reactor-notify-ms 5
> 
> > I'm not saying we can't improve other paths, but we should not lose focus on the main problem.
> 
> We already have #11038 to track the memory related issue. I think Raphael is not going to fix the memory allocator part.

The underlying mechanism used by compaction can be potentially patched to reduce memory usage. I am currently working on that. That will have a better effect on reducing those background reclaims which according to my analysis is the main contributor to the high latencies. Not sure the patch will help with all the pressure on memory, but will probably alleviate it to some good extent.

> 
> When I ran with '--blocked-reactor-notify-ms 1 ', I saw plenty of small stalls from compaction. Yes, the 1 ms detecor might not be accurate according to Avi, but it might help us point to code in compaction that could be improved in terms of reducing stalls even with false positive stall report.

You'll indeed see lots of false positives on certain environments. Locally, I wasn't able to see any stalls in compaction with '--blocked-reactor-notify-ms 5' when bootstrapping two new nodes while running a mixed workload with QUORUM in parallel. Benny recently patched compaction setup to yield if needed. Will retry reducing it to 2-3, then see if I can bump into anything that can be potentially improved.

**Comment by slivne** [comment] 2022-08-10 09:12
Is this supposed to be fixed ?

**Comment by raphaelsc** [comment] 2022-08-10 16:26
> Is this supposed to be fixed ?

Will probably remain opened as a placeholder for stalls originated by off-strategy. A potential source was fixed by 934af9be52df9bae661a. We can also wait for another run to confirm the problem is mitigated and then close this issue.

**Comment by avikivity** [comment] 2022-08-10 16:38
Just holding a bug open is wrong. If we don't know of anything remaining, we should close it.

**Comment by raphaelsc** [comment] 2022-08-10 16:46
> Just holding a bug open is wrong. If we don't know of anything remaining, we should close it.

Alright. I am closing this issue then. If we face a stall caused by off-strategy later, we can reopen (if on the same area) or open a different issue.

**Closed by raphaelsc** 2022-08-10 16:46 UTC
Labels: latency, compaction
