### ISSUE TITLE
test_auth_raft_command_split

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#21200] opened 2024-10-20 14:54 UTC
https://github.com/scylladb/scylladb/pull/21191

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12561/testReport/junit/(root)/test_auth_raft_command_split/Tests___Unit_Tests___test_auth_raft_command_split_dev_3/

```
>               raise HTTPError(uri, resp.status, params, json, text)
E               test.pylib.rest_client.HTTPError: HTTP error 500, uri: http://api/cluster/addservers, params: None, json: {'start': True, 'server_encryption': 'none', 'servers_num': 3}, body:
E               failed to start the node, server_id 101, IP 127.103.43.31, workdir scylla-101, host_id <missing>
E               Check the log files:
E               /scylladir/testlog/x86_64/test.py.debug-release-dev.log
E               /scylladir/testlog/x86_64/dev/scylla-101.log

test/pylib/rest_client.py:72: HTTPError

The above exception was the direct cause of the following exception:

manager = <test.pylib.manager_client.ManagerClient object at 0x7f57da995040>

    @pytest.mark.asyncio
    async def test_auth_raft_command_split(manager: ManagerClient) -> None:
>       servers = await manager.servers_add(3)

test/auth_cluster/test_auth_raft_command_split.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.pylib.manager_client.ManagerClient object at 0x7f57da995040>
servers_num = 3, cmdline = None, config = None, property_file = None
start = True, seeds = None, driver_connect_opts = {}, expected_error = None
server_encryption = 'none'

    async def servers_add(self, servers_num: int = 1,
                          cmdline: Optional[List[str]] = None,
                          config: Optional[dict[str, Any]] = None,
                          property_file: Optional[dict[str, Any]] = None,
                          start: bool = True,
                          seeds: Optional[List[IPAddress]] = None,
                          driver_connect_opts: dict[str, Any] = {},
                          expected_error: Optional[str] = None,
                          server_encryption: str = "none") -> List[ServerInfo]:
        """Add new servers concurrently.
        This function can be called only if the cluster uses consistent topology changes, which support
        concurrent bootstraps. If your test does not fulfill this condition and you want to add multiple
        servers, you should use multiple server_add calls."""
        assert servers_num > 0, f"servers_add: cannot add {servers_num} servers, servers_num must be positive"
    
        try:
            data = self._create_server_add_data(None, cmdline, config, property_file, start, seeds, expected_error, server_encryption, None)
            data['servers_num'] = servers_num
            server_infos = await self.client.put_json("/cluster/addservers", data, response_type="json",
                                                      timeout=ScyllaServer.TOPOLOGY_TIMEOUT * servers_num)
        except Exception as exc:
>           raise Exception("Failed to add servers") from exc
E           Exception: Failed to add servers

test/pylib/manager_client.py:390: Exception
```

**Comment by nyh** [comment] 2024-10-20 15:07
This is a duplicate of https://github.com/scylladb/scylladb/issues/21199 - here too the problem was the failure to create the server, and the log https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12561/artifact/testlog/x86_64/dev/failed_test/test_auth_raft_command_split.3.dev.3/scylla-101.log shows:

```
ERROR 2024-10-20 12:00:12,537 [shard 0:main] init - Startup failed: std::system_error (error system:24, could not create inotify instance: Too many open files)
```

**Closed by nyh** 2024-10-20 15:07 UTC
Labels: symptom/ci stability
