### ISSUE TITLE
protect reads against OOM

### ISSUE THREAD

**Issue by glommer** [scylladb/scylladb#4077] opened 2019-01-09 16:41 UTC
Reads can OOM the database if they use too much memory. We should strive to address the source of the OOM (for example, large number of SSTables -> should make compaction more aggressive), but there will always be situations in which we will overlook and memory usage will grow.

Instead of crashing we should fail the read with clear indications as to why

**Comment by slivne** [comment] 2019-02-10 11:31
@denesb
- I think there is a related issue todo better memory accounting for readers - can you please reference 
- what is the limit we are placing on reader memory consumption ? so that we will know to abort it.

**Comment by denesb** [comment] 2019-02-11 06:08
>     * I think there is a related issue todo better memory accounting for readers - can you please reference
This is https://github.com/scylladb/scylla/issues/4176.
>     * what is the limit we are placing on reader memory consumption ? so that we will know to abort it.
The limit is 2% of the shard's memory. What do you mean by "so that we will know to abort it"?

**Comment by denesb** [comment] 2019-02-11 06:10
The limit for readers' memory consumption is global, that is we don't limit the memory consumption of individual readers. We also don't OOM kill readers (is this what you meant by "abort")? If the memory consumption of all active readers is above the limit we won't admit new reads, until it drops below the limit.

**Comment by denesb** [comment] 2019-02-18 11:12
There is also #2778 which is related to this.

**Comment by avikivity** [comment] 2019-05-25 20:03
Let's close this and instead open issues for individual sources of OOMs. There's no way to close such a general ticket, because we can never know we identified all OOM sources and fixed them.

**Comment by denesb** [comment] 2019-05-31 09:27
This issue is already linked to a bunch of issues that propose fixing different aspects of OOM induced by admitting too many read requests. In a sense this ticket serves as an umbrella for all these subtickets. So instead of closing I think we should just reduce its scope to OOM caused by admitting too many read requests. Of course there is the possibility that we will not be able to find and fix all such OOM sources either.

**Comment by glommer** [comment] 2019-05-31 09:49
I'd like to keep this issue open as an umbrella issue as it has a Field-Tier1 tag. Feel free to rename the issue to make it more focused, protecting our readers is a good enough solution in my view

**Comment by bhalevy** [comment] 2022-08-17 06:16
Nowadays read-based OOM issues are rare enough with everything done so far that we can close this issue.
For tracking a class of issues, let's use labels are/or a project (like we have for compaction related issues).

**Closed by bhalevy** 2022-08-17 06:16 UTC
Labels: stability, Field-Tier1, out of memory, Eng-2, overload
