### ISSUE TITLE
test topology_raft_disabled / test_raft_upgrade_basic is flaky

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16110] opened 2023-11-21 10:04 UTC
In CI run https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4784/, topology_raft_disabled's `test_raft_upgrade_basic` ::`test_raft_upgrade_basic` failed:

```
=================================== FAILURES ===================================
___________________________ test_raft_upgrade_basic ____________________________

manager = <test.pylib.manager_client.ManagerClient object at 0x7fd6fe91a250>
random_tables = <test.pylib.random_tables.RandomTables object at 0x7fd6fe935410>

    @pytest.mark.asyncio
    @log_run_time
    @pytest.mark.replication_factor(1)
    async def test_raft_upgrade_basic(manager: ManagerClient, random_tables: RandomTables):
        servers = await manager.running_servers()
        cql = manager.cql
        assert(cql)
    
        # system.group0_history should either not exist or there should be no entries in it before upgrade.
        if await cql.run_async("select * from system_schema.tables where keyspace_name = 'system' and table_name = 'group0_history'"):
            assert(not (await cql.run_async("select * from system.group0_history")))
    
        logging.info(f"Enabling Raft on {servers} and restarting")
        await asyncio.gather(*(enable_raft_and_restart(manager, srv) for srv in servers))
        cql = await reconnect_driver(manager)
    
        logging.info("Cluster restarted, waiting until driver reconnects to every server")
        hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
    
        logging.info(f"Driver reconnected, hosts: {hosts}. Waiting until upgrade finishes")
>       await asyncio.gather(*(wait_until_upgrade_finishes(cql, h, time.time() + 60) for h in hosts))

test/topology_raft_disabled/test_raft_upgrade_basic.py:43: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology_raft_disabled/util.py:60: in wait_until_upgrade_finishes
    await wait_for_upgrade_state('use_post_raft_procedures', cql, host, deadline)
test/topology_raft_disabled/util.py:56: in wait_for_upgrade_state
    await wait_for(reached_state, deadline)
test/pylib/util.py:46: in wait_for
    res = await pred()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    async def reached_state():
>       rs = await cql.run_async("select value from system.scylla_local where key = 'group0_upgrade_state'", host=host)
E       cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.87.57.46:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})

test/topology_raft_disabled/util.py:46: NoHostAvailable
```

See more details in:
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4784/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___topology_raft_disabled_test_raft_upgrade_basic_release_2/

**Comment by kbr-scylla** [comment] 2023-11-22 10:05
This is caused by driver dropping connections to a cluster that has recently restarted, due to a delayed on_down notification, in the middle of serving a query.

https://github.com/scylladb/scylladb/pull/16010 is a fix in the context of another test. I think we should wait until that one passes review, then we can refactor and make it a more general mechanism to use in other tests as well.

**Comment by kbr-scylla** [comment] 2024-02-29 13:46
Logs missing, closing. I suspect it is caused by https://github.com/scylladb/python-driver/issues/295

**Closed by kbr-scylla** 2024-02-29 13:46 UTC
Labels: symptom/ci stability
