### ISSUE TITLE
Incorrect output in cfhistograms/tablehistograms

### ISSUE THREAD

**Issue by sulabhk95** [scylladb/scylladb#10089] opened 2022-02-16 12:11 UTC
Version: Scylla version 4.4.1-0.20210406.00da6b5e9

https://groups.google.com/g/scylladb-users/c/H3rEL0raWKc

Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                                (micros)          (micros)           (bytes)
    50%             0.00              0.00           1065.50             14237                72
    75%             0.00              0.00           1286.50            105778               642
    95%       1469901.75              0.00           1706.15            219342              1109
    98%       9799345.00              0.00           1934.88            315852              1916
    99%       9799345.00              0.00           2067.69            379022              1916
    Min             0.00              0.00            554.00               771                 5
    Max       9799345.00              0.00           2202.00            785939              3973

Looks like it is showing total sstable touched but as per docs should show sstables per query.

**Comment by bhalevy** [comment] 2023-05-04 06:12
Fixed with https://github.com/scylladb/scylladb/commit/fcd7f6ac5f42c588627139068bd9cf2e52a412ae

**Closed by bhalevy** 2023-05-04 06:12 UTC

**Comment by DoronArazii** [comment] 2023-07-30 19:18
@scylladb/scylla-maint please consider backport to 5.1 + 5.2

**Comment by bhalevy** [comment] 2023-07-31 05:53
The root cause is https://github.com/scylladb/scylla-tools-java/issues/330

**Comment by bhalevy** [comment] 2023-08-24 11:34
@Deexie do we have an existing test for this path?

**Comment by Deexie** [comment] 2023-08-24 12:47
There is a PR with it: https://github.com/scylladb/scylla-dtest/pull/3113
