### ISSUE TITLE
test_tablet_split: terminate after `std::logic_error` "Invalid tablet id: 3 >= 2", leading to "Coordinator node timed out" in test

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#18543] opened 2024-05-07 08:34 UTC
Spotted in CI
[scylla-2626.log](https://github.com/scylladb/scylladb/files/15232816/scylla-2626.log)
[scylla-2632.log](https://github.com/scylladb/scylladb/files/15232817/scylla-2632.log)
[topology_experimental_raft.test_tablets.5.log](https://github.com/scylladb/scylladb/files/15232818/topology_experimental_raft.test_tablets.5.log)

The test failed with:
```
>       await check()

test/topology_experimental_raft/test_tablets.py:723: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    async def check():
        logger.info("Checking table")
        cql = manager.get_cql()
>       rows = await cql.run_async("SELECT * FROM test.test;")
E       cassandra.ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for test.test - received only 0 responses from 1 CL=LOCAL_QUORUM." info={'consistency': 'LOCAL_QUORUM', 'required_responses': 1, 'received_responses': 0}
```

probably because one of the nodes crashed during the query (scylla-2632):
```
terminate called after throwing an instance of 'std::logic_error'
  what():  Invalid tablet id: 3 >= 2
Aborting on shard 1.
Backtrace:
  0xd59dc4a
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x48b0cdc
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x48b0933
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x46eb6f8
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x471c2c5
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4816ed9
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x481721e
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x481702e
  /lib64/libc.so.6+0x3dbaf
  /lib64/libc.so.6+0x8e883
  /lib64/libc.so.6+0x3dafd
  /lib64/libc.so.6+0x2687e
  /lib64/libstdc++.so.6+0xa4d18
  /lib64/libstdc++.so.6+0xb4f4b
  /lib64/libstdc++.so.6+0xb4fb6
  0xd73597a
  0xe845723
  0x1295deb5
  0x1295d4e4
  0x1295f57e
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x470e22e
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4716750
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x471a772
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4819be5
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4817d80
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4817c70
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x48173dc
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x44bd588
  /lib64/libc.so.6+0x8c946
  /lib64/libc.so.6+0x11296f
------ Ending test debug/topology_experimental_raft.test_tablets.5::test_tablet_split ------
```

The failure looks similar to https://github.com/scylladb/scylladb/issues/17938, although IIRC I didn't see a node crash there, just the same timeout.

**Comment by kbr-scylla** [comment] 2024-05-07 08:35
The error looks critical, so marking as release blocker

**Comment by bhalevy** [comment] 2024-05-07 10:07
@raphaelsc please look into this (failure is in test_tablet_split)

**Comment by raphaelsc** [comment] 2024-05-07 12:19
Duplicate of https://github.com/scylladb/scylladb/issues/18085. Fix is already sent and reviewed, but I am fighting some terrible flakiness. Closing this one.

**Closed by raphaelsc** 2024-05-07 12:19 UTC
Labels: symptom/ci stability, status/release blocker, area/tablets
