### ISSUE TITLE
The algorithm for picking an index for a request is not always deterministic

### ISSUE THREAD

**Issue by psarna** [scylladb/scylladb#7969] opened 2021-01-26 16:38 UTC
Scylla version (or git commit hash): master(82585568322824db7f0d9706cae959122a49fb08)

The algorithm for picking an index for a query which is eligible for indexing is not really deterministic in case of multiple indexes of the same type (global/local).
The algorithm is as follows: all indexes are traversed and scored. An eligible global index gets a 1, and an eligible local index gets a 2. While traversing, an index with current highest score is kept.

The problem is that when more than 1 index has the highest score, we'll pick one which is first in the traversal order, and the traversal order is based on:
 * the order of adding the indexes *until the first restart*
 * the order of loading the indexes from schema table after a restart

So, aside from the fact that a node can change the order after a restart, we an also easily reach a situation where two coordinator nodes use different indexes for identical queries.

It's not technically bad to pick indexes in such a way, but it would be better if users had an influence on which index has higher priority.

@slivne I was mistaken when I claimed that we pick by the order of restrictions passed to the query. That's a good idea and clients could have power over which index to pick that way, but it's not implemented.

/cc @nyh @dekimir

**Comment by nyh** [comment] 2023-06-29 07:21
> So, aside from the fact that a node can change the order after a restart, we an also easily reach a situation where two coordinator nodes use different indexes for identical queries.

Exactly this happened in issue #14434. And even worse - it resulted in a failing scan instead of inconsistent performance: After a node restart an ongoing paged query switched from node A to node B. The paging state contained one key chosen by node A, but node B thought it was a different indexed column, and tried to read the key using the wrong type and got a marshaling error.

So we need to make a consistent choice of which index to use if several are available for use in a query. The comments in the cql-pytest `test/cql-pytest/test_secondary_index.py`::`test_order_of_indexes` suggest that a good choice would be the first index that appears in the query's restriction.

**Comment by michoecho** [comment] 2023-06-29 08:03
> it resulted in a failing scan

In this case the scan failed because the garbage key was not deserializable with the expected type of the key.

But if that was (e.g. because the expected type is `blob` which accepts anything), the garbage key will be used, and I don't know what follows. Maybe it can cause the scan to silently lose rows instead of failing? Or return some rows twice?

**Comment by mykaul** [comment] 2024-02-04 12:15
@nyh - what's the next step here?

**Comment by nyh** [comment] 2024-02-05 14:43
@mykaul as you saw I had a PR to fix it, it wasn't well liked, everything had a higher priority, and half a year passed since. I'll need to "dive" into this issue again to prepare a different PR or decide how or why to continue pushing the PR I already sent. Let me know if you'd like me to work on this issue.

**Comment by mykaul** [comment] 2024-02-06 11:21
> @mykaul as you saw I had a PR to fix it, it wasn't well liked, everything had a higher priority, and half a year passed since. I'll need to "dive" into this issue again to prepare a different PR or decide how or why to continue pushing the PR I already sent. Let me know if you'd like me to work on this issue.

I think the PR (if it's already with column order)  is what we need to push. As for priorities  - let's discuss it against all other works items.

**Comment by mykaul** [comment] 2024-04-24 09:06
@kostja - looks like it missed 6.0 - moving to 6.1.

**Closed** 2024-05-03 14:58 UTC
Labels: type/bug, area/sec index

**Comment by mykaul** [comment] 2024-05-29 10:56
@yaronkaikov - can we unleash the backport bot on this? What's missing? The PR?

**Comment by yaronkaikov** [comment] 2024-05-29 10:58
> @yaronkaikov - can we unleash the backport bot on this? What's missing? The PR?

No, the `promoted-to-master` label

**Comment by yaronkaikov** [comment] 2024-05-29 10:59
> > @yaronkaikov - can we unleash the backport bot on this? What's missing? The PR?
> 
> No, the `promoted-to-master` label

Sorry, its an issue,  let me check

**Comment by yaronkaikov** [comment] 2024-05-29 11:10
So it seems that the PR is not linked in GitHub to this issue, so the sync label can't work.
I will add the labels manually in the PR - https://github.com/scylladb/scylladb/pull/14450

**Comment by michoecho** [comment] 2024-05-30 00:23
Question: even with the accepted fix, can't the same problem as above (corruption due to mismatched indexes across query pages) still occur when a paged secondary index query happens concurrently with a change in the set of indexes? It sounds like even if the index choice algorithm is deterministic with respect to the set of indexes, it could still choose the wrong index if that set changes. Or is there some mechanism which prevents this?

**Comment by nyh** [comment] 2024-05-30 07:36
> Question: even with the accepted fix, can't the same problem as above (corruption due to mismatched indexes across query pages) still occur when a paged secondary index query happens concurrently with a change in the set of indexes? It sounds like even if the index choice algorithm is deterministic with respect to the set of indexes, it could still choose the wrong index if that set changes. Or is there some mechanism which prevents this?

Yes, this potential problem was noted by Avi in his review of my PR (https://github.com/scylladb/scylladb/pull/14450), and in fact one of the things that froze this PR (and I was not suprised it was accepted). I told Avi that I would create a new issue, but forgot to do it. I'll do it now.

**Comment by nyh** [comment] 2024-05-30 08:31
> > Question: even with the accepted fix, can't the same problem as above (corruption due to mismatched indexes across query pages) still occur when a paged secondary index query happens concurrently with a change in the set of indexes? It sounds like even if the index choice algorithm is deterministic with respect to the set of indexes, it could still choose the wrong index if that set changes. Or is there some mechanism which prevents this?
> 
> Yes, this potential problem was noted by Avi in his review of my PR (#14450), and in fact one of the things that froze this PR (and I was not suprised it was accepted). I told Avi that I would create a new issue, but forgot to do it. I'll do it now.

@michoecho @avikivity I added a new issue https://github.com/scylladb/scylladb/issues/18992 about the problem of adding/dropping an index while a paged request is ongoing. I'll prepare tests reproducing it later. But as I explained in the last paragraph of the issue, it is probably low priority because we have a bigger problem when adding an index - https://github.com/scylladb/scylladb/issues/7963 - that Scylla can begin using it before fully built.
