### ISSUE TITLE
Scylla requires ALLOW FILTERING when querying by index on static column and clustering key

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#12828] opened 2023-02-13 15:26 UTC
When using index on static column, we can query by it without issue:
```
cqlsh> CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> create table statics (p int, c int, b int static, primary key (p, c)) ;
cqlsh> use test;
cqlsh:test> create table statics (p int, c int, b int static, primary key (p, c)) ;
cqlsh:test> insert into statics (p, c, b) values (1, 1, 1);
cqlsh:test> insert into statics (p, c, b) values (2, 2, 2);
cqlsh:test> create INDEX b_key ON statics (b) ;
cqlsh:test> insert into statics (p, c, b) values (3, 3, 3);
cqlsh:test> select * from statics where b=1;

 p | c | b
---+---+---
 1 | 1 | 1

(1 rows)
```
But when we add clustering key to the query, it fails:
```
cqlsh:test> select * from statics where b=1 and c=1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING"
```
This looks like should not require ALLOW FILTERING when using index on static column in query.

refs: https://github.com/scylladb/scylladb/pull/11166
Scylla version 5.2.0~rc0-0.20230119.34ab98e1be2e with build-id 88ca9e450d4e14608b5119a0588d64820dc37b86

**Comment by nyh** [comment] 2023-02-13 15:44
I think that you're right:

* The restriction `where b=1` basically matches a set of partitions (that are listed in the index).
* Adding `c=1` to the restriction retrieves a single clustering key from each of those partitions. This does not require reading the entire partition ("filtering") - the individual clustering row can be read directly.

It is possible that we require ALLOW FILTERING because we don't do the second point efficiently (e.g., we might first read all the _rows_ in all partitions matching `b=1`, and only then filter `c=1`), and if that's the case then the fix to this issue needs to make this read efficiently - it's not enough to drop the requirement of ALLOW FILTERING (if we do just that, it would be cheating).

**Comment by nyh** [comment] 2023-02-14 07:48
I changed my mind. I think that requiring ALLOW FILTERING in this `where b=1 and c=1` might not be wrong at all, and this might not be a bug at all.

The "philosophy" behind ALLOW FILTERING is that in "normal" non-filtering queries, the amount of work the database does should be proportional to the size of the output. For example, a single-row select reads (roughly) one row and outputs one row. A full-table scan reads the entire table and outputs the entire table. In contrast, in a query with filtering, the database might need to read (in the worst case) a million rows only to return a single (or even no) row.

The problem is that in your query, `where b=1 and c=1`, we must read from the index the entire list of partitions in `where b=1` - this may be a list of a million partitions that have 1 as their static column value - and then we need to check each of these partitions if it has a clustering row with `c=1`. We may end up with reading a list of a million partitions but outputting just one row, or none at all.

The main observation is that `c=1` isn't guaranteed to find one row in each partition - most partitions might not have such a clustering row like that at all. This makes it filtering. Exactly like the query `where c=1` (a full-table scan looking for a clustering key c=1 in any partition) requires ALLOW FILTERING.

**Comment by nyh** [comment] 2023-02-14 12:32
Note to self: even if we decide that this is not a bug, I want to add a test for it in test/cql-pytest/test_allow_filtering.py. It can be tested not just for a static-column index but also for a regular index.

**Comment by mykaul** [comment] 2023-02-15 12:07
@piodul - is that something you should handle?

**Comment by nyh** [comment] 2023-02-15 12:15
@mykaul no - as I explained above, I think this is not a bug. I created a test (@denesb just merged it to next) which demonstrates that this same behavior is also true for Cassandra, and explains why it makes sense. When this test is promoted to master, it will close this issue automatically, although maybe to reduce confusion I'll just close it now.

**Closed by nyh** 2023-02-15 12:15 UTC
Labels: sec-index, Master/Triage
