### ISSUE TITLE
Cassandra stress failed to achieve QUORUM after 1 node was terminated

### ISSUE THREAD

**Issue by igorsimb** [scylladb/scylladb#11527] opened 2022-09-12 15:56 UTC
## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `5.1.0~rc1-20220902.d10aee15e7e9` with build-id `43e78d18c87e23b0de6b268cde25861265d09063`
Cluster size: 6 nodes (im4gn.4xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-5-1-db-node-110b368f-7 (18.168.200.39 | 10.3.10.31) (shards: 15)
- longevity-100gb-4h-5-1-db-node-110b368f-6 (3.8.95.113 | 10.3.8.55) (shards: 15)
- longevity-100gb-4h-5-1-db-node-110b368f-5 (18.170.69.10 | 10.3.9.59) (shards: 15)
- longevity-100gb-4h-5-1-db-node-110b368f-4 (13.40.169.133 | 10.3.8.22) (shards: 15)
- longevity-100gb-4h-5-1-db-node-110b368f-3 (18.134.97.157 | 10.3.10.57) (shards: 15)
- longevity-100gb-4h-5-1-db-node-110b368f-2 (18.170.40.26 | 10.3.10.129) (shards: 15)
- longevity-100gb-4h-5-1-db-node-110b368f-1 (13.40.109.221 | 10.3.10.214) (shards: 15)

OS / Image: `ami-0eaedf0d2d7ae2900` (aws: eu-west-2)

Test: `longevity-100gb-4h-arm-test`
Test id: `110b368f-d0f0-4702-ba75-fd350d8c65e0`
Test name: `scylla-5.1/longevity/longevity-100gb-4h-arm-test`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4d64ffd58cef80f21ea3c4c3e97040bf4cb1ebe4/test-cases/longevity/longevity-100gb-4h.yaml)

## Issue description

At 2022-09-07 14:34:43 `disrupt_remove_node_then_add_node` nemesis started with node 2 being the target node. It terminates a node, runs full repair, runs nodetool removenode command, and adds a new node.
All nodes were healthy before the nemesis started:
```
< t:2022-09-07 14:34:48,515 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Datacenter: eu-west-2
< t:2022-09-07 14:34:48,515 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > =====================
< t:2022-09-07 14:34:48,515 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Status=Up/Down
< t:2022-09-07 14:34:48,515 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > |/ State=Normal/Leaving/Joining/Moving
< t:2022-09-07 14:34:48,515 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > --  Address      Load       Tokens       Owns    Host ID                               Rack
< t:2022-09-07 14:34:48,518 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.3.10.129  112.19 GB  256          ?       d14f9331-bb77-4914-8ca9-5cb5dcebde72  2c
< t:2022-09-07 14:34:48,519 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.3.8.55    85.16 GB   256          ?       1aeeb529-c4cf-4d71-9c04-7d118a42b985  2c
< t:2022-09-07 14:34:48,520 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.3.8.22    94.25 GB   256          ?       cba53c8a-cb9d-4170-b5d0-cc4f21298571  2c
< t:2022-09-07 14:34:48,520 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.3.10.214  79.41 GB   256          ?       50e3a3a3-fc10-45d3-b4a3-292635ca9878  2c
< t:2022-09-07 14:34:48,521 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.3.9.59    68.72 GB   256          ?       72878dcd-a341-4693-b7ab-0ccf2ea62df0  2c
< t:2022-09-07 14:34:48,521 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.3.10.57   175.19 GB  256          ?       ec2419c4-9f31-4072-83a5-b5016cd2b2cc  2c
< t:2022-09-07 14:34:48,567 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
```

Just after we terminated the target node, at 14:35:10 cassandra stress failed with
```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```

I went over all the nodes' logs of and this was the only message that seemed out of the ordinary to me (in node 3):

```
2022-09-07T13:07:22+00:00 longevity-100gb-4h-5-1-db-node-110b368f-3     !INFO | scylla[8080]:  [shard  0] reader_concurrency_semaphore - Semaphore _read_concurrency_sem with 3/100 count and 180632/82082529 memory resources: timed out, dumping permit diagnostics:
permits count   memory  table/description/state
2       2       160K    keyspace1.standard1/data-query/active/blocked
1       1       16K     keyspace1.standard1/data-query/active/used
2       0       0B      keyspace1.standard1/mutation-query/waiting
7       0       0B      keyspace1.standard1/data-query/waiting

12      3       176K    total

Total: 12 permits with 3 count and 176K memory resources
```

After that, at 14:37:54 repair command was executed and failed as follows:
```
< t:2022-09-07 14:37:54,136 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: failed to execute repair command on node Node longevity-100gb-4h-5-1-db-node-110b368f-1 [13.40.109.221 | 10.3.10.214] (seed: True) due to the following error: Encountered a bad command exit code!
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > Command: '/usr/bin/nodetool  repair '
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > Exit code: 2
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > [2022-09-07 14:36:11,027] Starting repair command #880, repairing 1 ranges for keyspace keyspace1 (parallelism=SEQUENTIAL, full=true)
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > [2022-09-07 14:37:49,133] Repair session 880 failed
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > [2022-09-07 14:37:49,133] Repair session 880 finished
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > Stderr:
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > error: Repair job has failed with the error message: [2022-09-07 14:37:49,133] Repair session 880 failed
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > -- StackTrace --
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR > java.lang.RuntimeException: Repair job has failed with the error message: [2022-09-07 14:37:49,133] Repair session 880 failed
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR >   at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR >   at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotif
icationProgressListener.java:77)
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR >   at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwa
rder.java:583)
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR >   at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR >   at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
< t:2022-09-07 14:37:54,138 f:nemesis.py      l:2802 c:sdcm.nemesis         p:ERROR >   at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108
)
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 110b368f-d0f0-4702-ba75-fd350d8c65e0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=110b368f-d0f0-4702-ba75-fd350d8c65e0)
- Show all stored logs command: `$ hydra investigate show-logs 110b368f-d0f0-4702-ba75-fd350d8c65e0`

## Logs:
- **db-cluster-110b368f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/110b368f-d0f0-4702-ba75-fd350d8c65e0/20220907_150855/db-cluster-110b368f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/110b368f-d0f0-4702-ba75-fd350d8c65e0/20220907_150855/db-cluster-110b368f.tar.gz)
- **monitor-set-110b368f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/110b368f-d0f0-4702-ba75-fd350d8c65e0/20220907_150855/monitor-set-110b368f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/110b368f-d0f0-4702-ba75-fd350d8c65e0/20220907_150855/monitor-set-110b368f.tar.gz)
- **loader-set-110b368f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/110b368f-d0f0-4702-ba75-fd350d8c65e0/20220907_150855/loader-set-110b368f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/110b368f-d0f0-4702-ba75-fd350d8c65e0/20220907_150855/loader-set-110b368f.tar.gz)
- **sct-runner-110b368f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/110b368f-d0f0-4702-ba75-fd350d8c65e0/20220907_150855/sct-runner-110b368f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/110b368f-d0f0-4702-ba75-fd350d8c65e0/20220907_150855/sct-runner-110b368f.tar.gz)
- **parallel-timelines-report-110b368f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/110b368f-d0f0-4702-ba75-fd350d8c65e0/20220907_150855/parallel-timelines-report-110b368f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/110b368f-d0f0-4702-ba75-fd350d8c65e0/20220907_150855/parallel-timelines-report-110b368f.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.1/job/longevity/job/longevity-100gb-4h-arm-test/6/)

**Comment by roydahan** [comment] 2022-09-14 11:19
The summary of this issue is the symptom not the cause.
Please check if any node crashed at that time of the failure.

**Comment by rayakurl** [comment] 2022-09-14 11:27
@roydahan - there was nothing obvious from node side .
This is what @igorsimb wrote above:
I went over all the nodes' logs of and this was the only message that seemed out of the ordinary to me (in node 3):
```
2022-09-07T13:07:22+00:00 longevity-100gb-4h-5-1-db-node-110b368f-3     !INFO | scylla[8080]:  [shard  0] reader_concurrency_semaphore - Semaphore _read_concurrency_sem with 3/100 count and 180632/82082529 memory resources: timed out, dumping permit diagnostics:
permits count   memory  table/description/state
2       2       160K    keyspace1.standard1/data-query/active/blocked
1       1       16K     keyspace1.standard1/data-query/active/used
2       0       0B      keyspace1.standard1/mutation-query/waiting
7       0       0B      keyspace1.standard1/data-query/waiting

12      3       176K    total

Total: 12 permits with 3 count and 176K memory resources
```

**Comment by roydahan** [comment] 2022-09-14 11:31
Please check the monitor for any signs of crashed node.
The repair logs may also suggest which node was the one we lost connection to.

**Comment by roydahan** [comment] 2022-09-19 09:38
Another run of the same test has passed here:
https://argus.scylladb.com/test/20d46499-8e66-46e2-bc9c-a6330d5e56e5/runs?additionalRuns[]=e008dc23-16da-44ee-9263-677135c5402b

I suggest to compare monitors.

**Comment by DoronArazii** [comment] 2022-10-20 12:30
@rayakurl any updates regarding this case?

**Comment by mykaul** [comment] 2022-10-30 15:37
@roydahan - did we see this issue on other tests, and specifically, non ARM machines?

**Comment by avikivity** [comment] 2022-11-02 15:53
These messages indicate overload. @denesb please scan them for anomalies.

**Comment by avikivity** [comment] 2022-11-02 15:54
The dashboard you pasted also looks like disk overload. I'll download the monitor set and see.

**Comment by avikivity** [comment] 2022-11-02 18:40
Multiple nodes show huge queue delays (but not disk delays).

From 10.3.8.22:

![image](https://user-images.githubusercontent.com/1017210/199574125-01b79cd2-3b6b-48fc-939a-45c652041c14.png)
![image](https://user-images.githubusercontent.com/1017210/199574361-0074c7ee-bfa2-45f2-9257-896d7dc09896.png)


Multi-second queue delays.

@xemul is the disk truly overloaded? It doesn't look so. So what's going on?

**Comment by xemul** [comment] 2022-11-03 07:14
Queue lengths are quite large: commitlog ~130, query ~750 (!), streaming ~250.

The IO queue's bucket limit is 12`582`912 units, 128k request weights are r=1`403`602 w=2`320`997, so the disk is allowed to have 12 reads or 6 writes of that size at a time and 15 shards compete for this resource, roughly a shard can have 1.5-2 large requests per tick.

**Comment by denesb** [comment] 2022-11-03 07:30
> These messages indicate overload. @denesb please scan them for anomalies.

I don't see anything obviously wrong with the posted printouts.

**Comment by mykaul** [comment] 2022-11-14 12:11
@avikivity

**Comment by DoronArazii** [comment] 2023-02-20 12:36
@avikivity / @denesb do we need more info from QA? where is it stuck?

**Comment by denesb** [comment] 2023-03-02 10:31
> @avikivity / @denesb do we need more info from QA? where is it stuck?

I have no idea where this is stuck. This is one of those issues which didn't have enough information to arrive at conclusions and by now everybody forgot any half-conclusions or theories they had about it.

**Comment by DoronArazii** [comment] 2023-03-05 10:19
Okay, reducing the priority to P3 until we will hit it again.

**Comment by roydahan** [comment] 2023-03-05 13:03
This test has run dozens of times since this issue happened.
I don't think it has reproduced since.

Closing for now.

**Closed by roydahan** 2023-03-05 13:03 UTC
Labels: missing_information, waiting-reproduction/QA, P3
