### ISSUE TITLE
test_change_ip is flaky

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#14274] opened 2023-06-16 12:53 UTC
Seen in:
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1846/artifact/testlog/x86_64/debug/topology.test_change_ip.1.log
https://jenkins.scylladb.com/job/scylla-master/job/build/1491/artifact/testlog/aarch64/debug/topology.test_change_ip.1.log

```
=================================== FAILURES ===================================
_______________________________ test_change_two ________________________________

manager = <test.pylib.manager_client.ManagerClient object at 0x7f7ee6e44990>
random_tables = <test.pylib.random_tables.RandomTables object at 0x7f7ee6e47990>

    @pytest.mark.asyncio
    async def test_change_two(manager, random_tables):
        """Stop two nodes, change their IPs and start, check the cluster is
        funcitonal"""
        servers = await manager.running_servers()
        table = await random_tables.add_table(ncolumns=5)
        s_1 = servers[1].server_id
        s_2 = servers[2].server_id
        logger.info("Gracefully stopping servers %s and %s to change ips", s_1, s_2)
        await manager.server_stop_gracefully(s_1)
        await manager.server_stop_gracefully(s_2)
        await manager.server_change_ip(s_1)
        await manager.server_change_ip(s_2)
        await manager.server_start(s_1)
        await manager.server_start(s_2)
>       await table.add_column()

test/topology/test_change_ip.py:30: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.pylib.random_tables.RandomTable object at 0x7f7ee6e46f90>
name = 'v_04', ctype = <class 'test.pylib.random_tables.TextType'>
column = <test.pylib.random_tables.Column object at 0x7f7ee44c4790>

    async def add_column(self, name: str = None, ctype: Type[ValueType] = None, column: Column = None):
        """Add a value column to the table"""
        if column is not None:
            assert type(column) is Column, "Wrong column type to add_column"
        else:
            name = name if name is not None else f"v_{self.next_value_id():02}"
            ctype = ctype if ctype is not None else TextType
            column = Column(name, ctype=ctype)
        self.columns.append(column)
        assert self.manager.cql is not None
>       await self.manager.cql.run_async(f"ALTER TABLE {self.full_name} "
                                         f"ADD {column.name} {column.ctype.name}")
E       cassandra.OperationTimedOut: errors={'127.161.209.46:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.161.209.46:9042

test/pylib/random_tables.py:187: OperationTimedOut
```

The Alter times out on .46:

```
INFO  2023-06-15 16:14:03,253 [shard 0] migration_manager - Update table 'test_1686834603565.t_01' From org.apache.cassandra.config.CFMetaData@0x6190007c2480[cfId=f2a19f80-0b7d-11ee-a5c9-2fe709ae0468,ksName=test_1686834603565,cfName=t_01,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.FloatType,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.FloatType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=c_01, type=org.apache.cassandra.db.marshal.UTF8Type, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_01, type=org.apache.cassandra.db.marshal.UUIDType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_02, type=org.apache.cassandra.db.marshal.Int32Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_03, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=a19cecf8-8dc5-3569-a76b-b52695315c48,droppedColumns={},collections={},indices={}] To org.apache.cassandra.config.CFMetaData@0x61900041eb80[cfId=f2a19f80-0b7d-11ee-a5c9-2fe709ae0468,ksName=test_1686834603565,cfName=t_01,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.FloatType,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.FloatType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=c_01, type=org.apache.cassandra.db.marshal.UTF8Type, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_01, type=org.apache.cassandra.db.marshal.UUIDType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_02, type=org.apache.cassandra.db.marshal.Int32Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_03, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=v_04, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=7fc5d340-0b7e-11ee-a525-5e0f71ef2eae,droppedColumns={},collections={},indices={}]
INFO  2023-06-15 16:14:04,109 [shard 0] compaction - [Compact system.scylla_local 7f95e9a0-0b7e-11ee-a525-5e0f71ef2eae] Compacted 2 sstables to [/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-39/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-48-big-Data.db:level=0]. 64kB to 59kB (~90% of original) in 1110ms = 53kB/s. ~256 total partitions merged to 2.
WARN  2023-06-15 16:14:06,037 [shard 0] gossip - Fail to send EchoMessage to 127.161.209.23: seastar::rpc::closed_error (connection is closed)
INFO  2023-06-15 16:14:30,534 [shard 0] gossip - FatClient 127.161.209.23 has been silent for 30000ms, removing from gossip
INFO  2023-06-15 16:15:00,792 [shard 0] gossip - 60000 ms elapsed, 127.161.209.42 gossip quarantine over
INFO  2023-06-15 16:15:01,802 [shard 0] gossip - FatClient 127.161.209.42 has been silent for 30000ms, removing from gossip
INFO  2023-06-15 16:15:31,047 [shard 0] gossip - 60000 ms elapsed, 127.161.209.23 gossip quarantine over
INFO  2023-06-15 16:16:02,291 [shard 0] gossip - 60000 ms elapsed, 127.161.209.42 gossip quarantine over
Reactor stalled for 33 ms on shard 0. Backtrace: 0x169e0f90 0x481a0c4 0x48195cc 0x466bb53 0x466679f 0x4666247 0x4666b08 0x466d04a 0x3cb1f 0x1697fc9d 0x16980786 0x1697ea80 0x16a70747 0x55036bf 0x468d278 0x469534e 0x4699390 0x4696fb6 0x42186c0 0x4215f5a 0x16a7dd3e 0x177b1ba0 0x177b1951 0x177b1510 0x16c78ddc 0x16a7b1a0 0x2750f 0x275c8 0x169776e4
------ Ending test debug/topology.test_change_ip.1::test_change_two ------
```

All other nodes have `schema_tables - Altering test_1686834603565.t_01 ..` quickly after .46 executes the DDL, but .46 itself does not. 

Logs from .4:

```
INFO  2023-06-15 16:14:03,854 [shard 0] schema_tables - Altering test_1686834603565.t_01 id=f2a19f80-0b7d-11ee-a5c9-2fe709ae0468 version=4337bb6d-fcfe-3a8a-a976-bde37c264b92
Reactor stalled for 36 ms on shard 0. Backtrace: 0x169e0f90 0x481a0c4 0x48195cc 0x466bb53 0x466679f 0x4666247 0x4666b08 0x466d04a 0x3cb1f 0x1a4e24f3 0x2002a6d8 0x1fffda06 0x1a62e83c 0x1a62e50b 0x1a5ef8d7 0x1a5ef651 0x1a5ef405 0x1a5ef014 0x1a5f8585 0x1a5e25b4 0x1a5eb75b 0x1a5e8271 0x200ca857 0x2009f10e 0x2025fafa 0x16e741ee 0x16e73e81 0x468d278 0x469534e 0x4699390 0x4696fb6 0x42186c0 0x4215f5a 0x16a7dd3e 0x177b1ba0 0x177b1951 0x177b1510 0x16c78ddc 0x16a7b1a0 0x2750f 0x275c8 0x169776e4
INFO  2023-06-15 16:14:03,922 [shard 0] query_processor - Column definitions for test_1686834603565.t_01 changed, invalidating related prepared statements
INFO  2023-06-15 16:14:03,948 [shard 1] query_processor - Column definitions for test_1686834603565.t_01 changed, invalidating related prepared statements
Reactor stalled for 33 ms on shard 0. Backtrace: 0x169e0f90 0x481a0c4 0x48195cc 0x466bb53 0x466679f 0x4666247 0x4666b08 0x466d04a 0x3cb1f 0x1a220de4 0x1a21016b 0x1a1a9b6a 0x19c7d251 0x201b354a 0x1dbe922e 0x1dbe8e21 0x468d278 0x469534e 0x4699390 0x4696fb6 0x42186c0 0x4215f5a 0x16a7dd3e 0x177b1ba0 0x177b1951 0x177b1510 0x16c78ddc 0x16a7b1a0 0x2750f 0x275c8 0x169776e4
INFO  2023-06-15 16:14:06,051 [shard 0] compaction - [Compact system.scylla_local 7f7e6a00-0b7e-11ee-a268-9e25b192fe9c] Compacted 2 sstables to [/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-28/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-52-big-Data.db:level=0]. 64kB to 59kB (~90% of original) in 2792ms = 21kB/s. ~256 total partitions merged to 2.
INFO  2023-06-15 16:14:06,503 [shard 0] schema_tables - Schema version changed to 4bac208f-da8d-344d-baef-b759716414f2
INFO  2023-06-15 16:14:27,928 [shard 0] gossip - FatClient 127.161.209.23 has been silent for 30000ms, removing from gossip
Rate-limit: suppressed 5 backtraces on shard 0
INFO  2023-06-15 16:14:58,215 [shard 0] gossip - 60000 ms elapsed, 127.161.209.42 gossip quarantine over
INFO  2023-06-15 16:14:59,224 [shard 0] gossip - FatClient 127.161.209.42 has been silent for 30000ms, removing from gossip
INFO  2023-06-15 16:15:28,526 [shard 0] gossip - 60000 ms elapsed, 127.161.209.23 gossip quarantine over
INFO  2023-06-15 16:15:59,825 [shard 0] gossip - 60000 ms elapsed, 127.161.209.42 gossip quarantine over
```

Logs from .58:

```
INFO  2023-06-15 16:14:05,255 [shard 0] schema_tables - Altering test_1686834603565.t_01 id=f2a19f80-0b7d-11ee-a5c9-2fe709ae0468 version=4337bb6d-fcfe-3a8a-a976-bde37c264b92
INFO  2023-06-15 16:14:05,346 [shard 1] query_processor - Column definitions for test_1686834603565.t_01 changed, invalidating related prepared statements
INFO  2023-06-15 16:14:05,357 [shard 0] query_processor - Column definitions for test_1686834603565.t_01 changed, invalidating related prepared statements
INFO  2023-06-15 16:14:05,513 [shard 0] compaction - [Compact system.cdc_local 7bbea2e0-0b7e-11ee-8fb7-4733ef9beb6e] Compacted 2 sstables to [/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/cdc_local-0bcaffd40c833eadad13dc1d5015b77c/me-6-big-Data.db:level=0]. 68kB to 63kB (~92% of original) in 8756ms = 7kB/s. ~256 total partitions merged to 2.
INFO  2023-06-15 16:14:05,653 [shard 0] compaction - [Compact system.peers 8125ff80-0b7e-11ee-8fb7-4733ef9beb6e] Compacting [/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-14-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-16-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-12-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-18-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-10-big-Data.db:level=0:origin=compaction]
INFO  2023-06-15 16:14:07,447 [shard 0] compaction - [Compact system.peers 8125ff80-0b7e-11ee-8fb7-4733ef9beb6e] Compacted 5 sstables to [/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-20-big-Data.db:level=0]. 31kB to 7kB (~24% of original) in 1176ms = 6kB/s. ~640 total partitions merged to 1.
INFO  2023-06-15 16:14:07,514 [shard 0] compaction - [Compact system.local 824949d0-0b7e-11ee-8fb7-4733ef9beb6e] Compacting [/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/local-7ad54392bcdd35a684174e047860b377/me-28-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/local-7ad54392bcdd35a684174e047860b377/me-26-big-Data.db:level=0:origin=compaction]
INFO  2023-06-15 16:14:08,927 [shard 0] compaction - [Compact system.local 824949d0-0b7e-11ee-8fb7-4733ef9beb6e] Compacted 2 sstables to [/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/local-7ad54392bcdd35a684174e047860b377/me-30-big-Data.db:level=0]. 14kB to 8kB (~55% of original) in 936ms = 8kB/s. ~256 total partitions merged to 1.
INFO  2023-06-15 16:14:09,028 [shard 0] compaction - [Compact system.scylla_local 832d6840-0b7e-11ee-8fb7-4733ef9beb6e] Compacting [/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-22-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-20-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-18-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-16-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-14-big-Data.db:level=0:origin=compaction]
INFO  2023-06-15 16:14:09,526 [shard 0] schema_tables - Schema version changed to 4bac208f-da8d-344d-baef-b759716414f2
INFO  2023-06-15 16:14:10,728 [shard 0] compaction - [Compact system.scylla_local 832d6840-0b7e-11ee-8fb7-4733ef9beb6e] Compacted 5 sstables to [/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-116/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-24-big-Data.db:level=0]. 82kB to 59kB (~71% of original) in 1537ms = 38kB/s. ~640 total partitions merged to 2.
Rate-limit: suppressed 38 backtraces on shard 0
INFO  2023-06-15 16:14:58,832 [shard 0] gossip - 60000 ms elapsed, 127.161.209.23 gossip quarantine over
INFO  2023-06-15 16:14:58,833 [shard 0] gossip - 60000 ms elapsed, 127.161.209.42 gossip quarantine over
INFO  2023-06-15 16:14:59,852 [shard 0] gossip - FatClient 127.161.209.42 has been silent for 30000ms, removing from gossip
INFO  2023-06-15 16:14:59,866 [shard 0] gossip - FatClient 127.161.209.23 has been silent for 30000ms, removing from gossip
INFO  2023-06-15 16:16:00,334 [shard 0] gossip - 60000 ms elapsed, 127.161.209.23 gossip quarantine over
INFO  2023-06-15 16:16:00,335 [shard 0] gossip - 60000 ms elapsed, 127.161.209.42 gossip quarantine over
------ Ending test debug/topology.test_change_ip.1::test_change_two ------
```

**Comment by kbr-scylla** [comment] 2023-06-19 11:03
Duplicate of https://github.com/scylladb/scylladb/issues/14257?

**Closed** 2023-06-19 13:47 UTC
Labels: schema changes, CI-Stability
