### ISSUE TITLE
C-S command failed with error: "Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)"

### ISSUE THREAD

**Issue by Mark-Gurevich** [scylladb/scylladb#14007] opened 2023-05-23 19:19 UTC
## Issue description
The issue happened in [longevity-10gb-3h-azure-test#67](https://argus.scylladb.com/test/cdc07d5f-cef2-4aff-8ca7-ec364aa9b6e7/runs?additionalRuns[]=35248e63-cf4c-4070-85ec-eba3efa8d4da)
During nemesis **disrupt_soft_reboot_node** right after "node 5" was sent reboot command the failure occured.

Disruption event to node 5:
`2023-04-28 11:24:15.318: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=3a23db1d-cbec-433b-b11a-7f7cd80dfb89: nemesis_name=SoftRebootNode target_node=Node longevity-10gb-3h-master-db-node-35248e63-eastus-5 [13.82.145.18 | 10.0.0.9] (seed: False)`

2 seconds later c-s failed:
`2023-04-28 11:24:17.936: (CassandraStressLogEvent Severity.CRITICAL) period_type=one-time event_id=2e2b498a-2a12-4538-8a93-aca96d24bc3c during_nemesis=SoftRebootNode: type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=12685 node=Node longevity-10gb-3h-master-loader-node-35248e63-eastus-2 [20.124.219.242 | 10.0.0.12] (seed: False)
java.io.IOException: Operation x10 on key(s) [3634504f4e324d374b30]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)`

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

## How frequently does it reproduce?

Looks very close to issue: 
[C-S command failed with errors: WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (3 replica were required but only 2 acknowledjava.io.IOException: Operation x10 on key(s) during node replace at bootsrap](https://github.com/scylladb/scylladb/issues/11805)  
## Installation details

Kernel Version: 5.15.0-1037-azure
Scylla version (or git commit hash): `2023.2.0~dev-20230427.e4ffb1fcf18f` with build-id `6233f9b12c6c2204bcbc461bfe8c69d8f65811a5`

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-35248e63-eastus-9 (52.152.138.87 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-35248e63-eastus-8 (20.169.244.15 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-35248e63-eastus-7 (74.235.236.30 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-35248e63-eastus-6 (52.188.54.155 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-35248e63-eastus-5 (13.82.145.18 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-35248e63-eastus-4 (52.152.143.91 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-35248e63-eastus-3 (52.149.213.19 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-35248e63-eastus-2 (20.232.44.143 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-35248e63-eastus-10 (40.114.94.44 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-35248e63-eastus-1 (20.115.33.31 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-enterprise-2023.2.0-dev-x86_64-2023-04-28T09-03-34` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `35248e63-cf4c-4070-85ec-eba3efa8d4da`
Test name: `scylla-enterprise/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a8da7cf7c837c115ea01c60a71348358616f890f/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 35248e63-cf4c-4070-85ec-eba3efa8d4da`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=35248e63-cf4c-4070-85ec-eba3efa8d4da)
- Show all stored logs command: `$ hydra investigate show-logs 35248e63-cf4c-4070-85ec-eba3efa8d4da`

## Logs:
- **db-cluster-35248e63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/db-cluster-35248e63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/db-cluster-35248e63.tar.gz)
- **sct-runner-events-35248e63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/sct-runner-events-35248e63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/sct-runner-events-35248e63.tar.gz)
- **sct-35248e63.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/sct-35248e63.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/sct-35248e63.log.tar.gz)
- **monitor-set-35248e63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/monitor-set-35248e63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/monitor-set-35248e63.tar.gz)
- **loader-set-35248e63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/loader-set-35248e63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/loader-set-35248e63.tar.gz)
- **parallel-timelines-report-35248e63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/parallel-timelines-report-35248e63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/35248e63-cf4c-4070-85ec-eba3efa8d4da/20230428_114306/parallel-timelines-report-35248e63.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-enterprise/job/longevity/job/longevity-10gb-3h-azure-test/67/)
[Argus](https://argus.scylladb.com/test/cdc07d5f-cef2-4aff-8ca7-ec364aa9b6e7/runs?additionalRuns[]=35248e63-cf4c-4070-85ec-eba3efa8d4da)
</details>

**Comment by michoecho** [comment] 2023-05-25 10:48
@asias Does the above ring a bell?

**Comment by michoecho** [comment] 2023-06-06 17:37
I just bumped into https://github.com/scylladb/scylladb/pull/13677, and my conclusion after reviewing the symptoms here again is that this is a duplicate of the issue which has been fixed by that PR. (This is most evident due to the fact that other nodes have no `Removed node 10.0.0.7` messages in their logs).

I think we can close this as a duplicate, although something is off here. There are some past runs of this test (e.g. https://jenkins.scylladb.com/job/scylla-enterprise/job/longevity/job/longevity-10gb-3h-azure-test/65/) which *didn't* fail, even though they should have also been affected by this issue. How come they didn't fail?

**Comment by mykaul** [comment] 2023-06-07 07:13
@Mark-Gurevich - can you reply to Michal (and probably also try to reproduce on master, to see if the fix is good there) ?

**Comment by fgelcer** [comment] 2023-06-07 07:20
> @Mark-Gurevich - can you reply to Michal (and probably also try to reproduce on master, to see if the fix is good there) ?

@mykaul , on [latest master run](https://argus.scylladb.com/test/aa05fe67-89bd-4e30-88db-5e2b2e3d986d/runs?additionalRuns[]=dad4e725-615c-4e7b-a806-db689703efe1) we didn't see this issue reproducing.. 

also, on [latest enterprise ("master") run](https://argus.scylladb.com/test/cdc07d5f-cef2-4aff-8ca7-ec364aa9b6e7/runs?additionalRuns[]=34996367-b941-470e-b185-d2f746fe850d) it did not reproduce.

**Closed by fgelcer** 2023-06-07 07:20 UTC
