### ISSUE TITLE
alternator_tests.TesterAlternator.test_cluster_traces fails intermittently

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11874] opened 2022-11-02 08:19 UTC
Last seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/128/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split004___test_cluster_traces/

```
KeyError: 'The following "prepare_ballot: sending prepare" trace message not found from "127.0.18.1" source!'
```

But the test seems to fail intermittently since it started running regularly.
See also https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/122/testReport/junit/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split004___test_cluster_traces/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/120/testReport/junit/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split004___test_cluster_traces/

I'm not sure if the culprit is in the dtest or in scylla.
@nyh since this tests alternator, can you please look into this?
Cc @eliransin

**Comment by nyh** [comment] 2022-11-02 09:51
I'll take a look at this test now.

**Comment by nyh** [comment] 2022-11-02 10:49
Closing as a duplicate of #10189.

**Closed by nyh** 2022-11-02 10:49 UTC
Labels: dtest, master/triage

**Comment by bhalevy** [comment] 2022-11-02 11:21
👍
