### ISSUE TITLE
Tests / Unit Tests / non-boost tests.topology_experimental_raft.test_raft_cluster_features.debug is flaky

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#15747] opened 2023-10-17 22:00 UTC
Seen in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4217/testReport/junit/(root)/test_raft_cluster_features/Tests___Unit_Tests___test_rolling_upgrade_happy_path_5/

`AssertionError: Deadline exceeded, failing test.`

```
manager = <test.pylib.manager_client.ManagerClient object at 0x7fed911b51d0>

    @pytest.mark.asyncio
    async def test_rolling_upgrade_happy_path(manager: ManagerClient) -> None:
        for _ in range(3):
            await manager.server_add()
>       await test_cluster_features.test_rolling_upgrade_happy_path(manager)

test/topology_experimental_raft/test_raft_cluster_features.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology/test_cluster_features.py:92: in test_rolling_upgrade_happy_path
    await asyncio.gather(*(wait_for_feature(TEST_FEATURE_NAME, cql, h, time.time() + 60) for h in hosts))
test/pylib/util.py:131: in wait_for_feature
    await wait_for(feature_is_enabled, deadline)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pred = <function wait_for_feature.<locals>.feature_is_enabled at 0x7fed906d8a40>
deadline = 1697493961.5800846, period = 1

    async def wait_for(
            pred: Callable[[], Awaitable[Optional[T]]],
            deadline: float, period: float = 1) -> T:
        while True:
>           assert(time.time() < deadline), "Deadline exceeded, failing test."
E           AssertionError: Deadline exceeded, failing test.

test/pylib/util.py:45: AssertionError
```

Ran on an m5ad.8xlarge instance, so shouldn't be an infra problem even though it's a timeout

**Comment by Annamikhlin** [comment] 2023-10-24 07:50
failed today in `master/build` - 
https://jenkins.scylladb.com/job/scylla-master/job/build/1671/testReport/junit/(root)/test_raft_cluster_features/Build__Test__Publish___buildTestPublishArm___test_rolling_upgrade_happy_path/

**Comment by piodul** [comment] 2023-10-24 15:41
The node logs from the original report are gone, but there are still some from the second report [here](https://github.com/scylladb/scylladb/issues/15747#issuecomment-1776699062).

This excerpt from https://jenkins.scylladb.com/job/scylla-master/job/build/1671/artifact/testlog/aarch64/debug/scylla-305.log looks very similar to https://github.com/scylladb/scylladb/issues/15728#issuecomment-1769530969 and the explanation is the same - the topology coordinator failed to fence the previous coordinator, it throws an exception which causes the topology coordinator to exit and not do anything else.

```
INFO  2023-10-24 05:44:23,654 [shard 0:main] raft_group0 - gaining leadership
INFO  2023-10-24 05:44:23,660 [shard 0:stre] storage_service - raft topology: refreshing topology to check if it's synchronized with local metadata
ERROR 2023-10-24 05:44:23,672 [shard 0:stre] storage_service - raft topology: failed to fence previous coordinator raft::request_aborted (Request is aborted by a caller)
INFO  2023-10-24 05:44:23,676 [shard 0:stre] storage_service - raft_state_monitor_fiber aborted with raft::request_aborted (Request is aborted by a caller)
```

So it's a duplicate of https://github.com/scylladb/scylladb/issues/15728. It will be fixed by Gleb's patch which was already queued.

**Comment by piodul** [comment] 2023-11-04 15:56
Unfortunately, it's not fixed yet, we had a similar failure today here: https://jenkins.scylladb.com/job/scylla-master/job/build/1684/

Logs are slightly different (there is a difference in the last message):

```
INFO  2023-11-04 09:13:14,211 [shard 0:strm] storage_service - raft topology: refreshing topology to check if it's synchronized with local metadata
INFO  2023-11-04 09:13:14,215 [shard 0:main] raft_group0 - gaining leadership
ERROR 2023-11-04 09:13:14,219 [shard 0:strm] storage_service - raft topology: failed to fence previous coordinator raft::request_aborted (Request is aborted by a caller)
INFO  2023-11-04 09:13:14,222 [shard 0:strm] storage_service - raft_state_monitor_fiber aborted with seastar::sleep_aborted (Sleep is aborted)
```

The fix mentioned above has a bug: although it catches the `raft::request_aborted` exception from `start_operation`/`update_topology_state`, it then calls `sleep_abortable` which throws an uncaught `abort_requested_exception`.

Will send a fix shortly.

**Closed** 2023-11-07 20:58 UTC
Labels: raft, P1, CI-Stability

**Comment by kbr-scylla** [comment] 2023-11-08 13:25
We should backport to 5.4 to prevent flakiness.
I'll wait ~one week before backporting.

**Comment by Annamikhlin** [comment] 2023-11-16 06:57
seen on `2024.1`:
https://jenkins.scylladb.com/job/enterprise-2024.1/job/build/1/testReport/junit/(root)/test_cluster_features/Build__Test__Publish___buildTestPublishX86___test_rolling_upgrade_happy_path/

required backport to 2024.1

**Comment by kbr-scylla** [comment] 2023-11-16 11:46
Queued backport to 5.4 (will eventually end up in 2024.1).

**Comment by mykaul** [comment] 2023-12-13 12:24
> Queued backport to 5.4 (will eventually end up in 2024.1).

Removed labels.
