### ISSUE TITLE
WARN "sstable - Could not remove table directory `.../snapshots`" ... Directory not empty

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#13538] opened 2023-04-17 09:49 UTC
Steps to reproduce:
1. create keyspace
2. create table
3. drop table

Scylla will print a WARN like this one:
```
WARN  2023-04-17 11:45:28,322 [shard 0] sstable - Could not remove table directory "/tmp/scylla-workdir/data/ks/tt-94b9b6c0dd0411ed8d16521e2d09d017/snapshots": std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/tmp/scylla-workdir/data/ks/tt-94b9b6c0dd0411ed8d16521e2d09d017/snapshots]). Ignored.
```

and indeed, there's stuff in there:
```
$ ls /tmp/scylla-workdir/data/ks/tt-94b9b6c0dd0411ed8d16521e2d09d017/snapshots/
pre-drop-1681724728307
[kbraun@fedora scylladb]$ ls /tmp/scylla-workdir/data/ks/tt-94b9b6c0dd0411ed8d16521e2d09d017/snapshots/pre-drop-1681724728307/
manifest.json  schema.cql
```

cc @bhalevy

**Comment by fruch** [comment] 2023-05-29 22:43
we started seeing this on SCT:
```
2023-05-28 00:56:50.630: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=38002d55-8282-49c3-ad8d-803932019368: type=FILESYSTEM_ERROR regex=filesystem_error line_number=1441 node=sct-cluster-us-east1-b-us-east1-2
WARN  2023-05-28 00:50:09,926 [shard 0] sstable - Could not remove table directory "/var/lib/scylla/data/drop_table_during_repair_ks_9/standard1-59f11060fcee11ed933a16fd46eae316/snapshots": std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/data/drop_table_during_repair_ks_9/standard1-59f11060fcee11ed933a16fd46eae316/snapshots]). Ignored.
```

since it's `filesystem_error`, SCT mark as failure need to be checked.

we can ignore those warnings completely ? and if so, what's the point of print those ?

**Comment by fruch** [comment] 2023-06-11 15:13
@nyh is this warning is something we should ignore ? or something to follow up to check why those snapshot folders are not empty  ?

**Comment by nyh** [comment] 2023-06-11 15:59
> That's the intended behavior as per @nyh request in [#11001 (review)](https://github.com/scylladb/scylladb/pull/11001#pullrequestreview-1033633203)
> 
> That said, in this particular example the table is empty upon removal so we could in theory detect that and allow removing the logically-empty snapshots directory, but I think this optimization is not worth the effort.
> 
> Note that this would be handled by #7123

I don't remember asking anything about printing warnings and can't dig into the history right now. Let me just say what I did want:

In the past, whenever we deleted a table and auto-snapshotting was disabled, we always left behind the table's directory and  an empty "snapshots" subdirectory (this was issue https://github.com/scylladb/scylladb/issues/10896). This was annoying for tests (as well as actual users) which created and dropped thousands of tables one after another - and although you never had more than a handful of tables at any time, you ended up with a data directory with thousands of empty subdirectories. This is what I wanted to avoid. I suggested that if the snapshots directory is empty when we delete a table, we can delete that empty directory - and then the table directory becomes empty and we can delete it too.

If auto-snapshoting is enabled, the "snapshots" directory will not be empty, and will not - and should not - be automatically removed, that's the whole point of the auto-snapshot feature (which I hate, but that's a story for another day). We shouldn't warn that it remains non-empty, that's the intended behavior in that case!

@fruch if you don't disable auto-snapshot in your test, or if a test explicitly **asks** for a snapshot, the directory will remain non-empty, and Scylla must not complain about it being empty. If it warns in these cases, it's a Scylla bug that should be fixed in Scylla.

 I asked that if the snapshot directory is empty

**Comment by fruch** [comment] 2023-06-11 16:03
If auto snapshot is enabled by default then all of our tests would have.

In longevity test we don't disable such configuration.

And we are creating snapshots in multiple cases

**Comment by nyh** [comment] 2023-06-11 16:04
> I don't remember asking anything about printing warnings and can't dig into the history right now. 

Well I got curious and looked at the history anyway, and it turns out I suggested you can call rmdir() for an empty and non-empty directory alike, and it will simply do nothing for a non-empty directory. I meant the rmdir() system call, which is silent if the directory is non-empty. If our version of rmdir() throws and the caller is chatty and prints a warning messsage in that case, we need to catch the ENOTDIR exception and ignore it (any other sort of failure, we can be chatty about).

**Comment by bhalevy** [comment] 2023-06-11 16:50
I think it's wrong to ignore those failures and it's just fine to warn about the snapshots directories being left behind, otherwise they may accumulate silently until the node runs out of space, so the user is warned to do something about them.  They may be left behind due to scheduled snapshots or due to auto-snapshot, but it doesn't matter.
Those leftovers needs to be managed somehow and an admin needs to make a decision and delete them at some point.
Hence the warning.

**Comment by bhalevy** [comment] 2023-06-11 16:51
I'd vote for closing this issue as "not planned".
SCT can disable auto-snapshot if that's an issue for it, or just rm -rf the table directory after it's been dropped.

**Comment by fruch** [comment] 2023-06-11 16:58
> I'd vote for closing this issue as "not planned".
> SCT can disable auto-snapshot if that's an issue for it, or just rm -rf the table directory after it's been dropped.

We can ignore the warning, same as the users would, when auto snapshot is on there would be a lot of that warning.

**Comment by nyh** [comment] 2023-06-11 18:01
> I think it's wrong to ignore those failures  and it's just fine to warn about the snapshots directories being left behind, otherwise they may accumulate silently until the node runs out of space

I disagree. auto-snapshot and explicit snapshot are both **features** not bugs. I don't like them, and have several issues about redesigning them, but they are features we have deliberately. We shouldn't log warnings when people use advertised features exactly like they are advertised.

So I think the warnings need to go away for the ENOTEMPTY error from rmdir(). For any other errors, the warning is justified (maybe even should be an error, not just a warning).

**Comment by nyh** [comment] 2023-06-11 18:03
> I'd vote for closing this issue as "not planned".

I vote against. Until the auto-snapshot feature is deprecated, we shouldn't warn users who use it.

> SCT can disable auto-snapshot if that's an issue for it

SCT should definitely disable auto-snapshot. It's a disaster of a feature. Unless, that is, SCT wants to **test** that feature. Which it probably should do, so it's good they left it. Here it caught **this** bug for us (the excessive warnings) - so kudos for the SCT team for bringing it to our attention.

>, or just rm -rf the table directory after it's been dropped.

Users shouldn't have to use filesystem commands on their Scylla database directory :-(

**Comment by bhalevy** [comment] 2023-06-11 20:04
> > I think it's wrong to ignore those failures  and it's just fine to warn about the snapshots directories being left behind, otherwise they may accumulate silently until the node runs out of space
> 
> I disagree. auto-snapshot and explicit snapshot are both **features** not bugs. I don't like them, and have several issues about redesigning them, but they are features we have deliberately. We shouldn't log warnings when people use advertised features exactly like they are advertised.
> 
> So I think the warnings need to go away for the ENOTEMPTY error from rmdir(). For any other errors, the warning is justified (maybe even should be an error, not just a warning).

Maybe we can settle on demoting the warnings to info level if all that is left there are snapshots

**Comment by fruch** [comment] 2023-07-05 14:49
@nyh @bhalevy, so what's the way forward here ? we should ignore those or not ? it should be fixed on scylla end ?

**Comment by nyh** [comment] 2023-07-05 15:44
I assigned this issue to myself, it shouldn't take more than an hour to fix, I'll hopefully do it tomorrow. If I forgot to do it, and someone else wants to take over, reassign it to yourself.

**Comment by nyh** [comment] 2023-07-06 17:54
The irony is that we spent 15 comments and two months to talk about this issue, while the fix was already in the code and had a tiny bug that prevented it from working. I'm sending the one-line patch now.

**Comment by nyh** [comment] 2023-07-06 18:10
@fruch, sent a 10-byte patch to Scylla in https://github.com/scylladb/scylladb/pull/14557. So you won't have to touch the tests, which were absolutely correct (and thanks!) to declare these warnings to be wrong.

**Closed** 2023-07-07 12:48 UTC
Labels: UX

**Comment by denesb** [comment] 2023-12-18 11:27
Not a bugfix, but it fixes an annoying logspam. backported to 5.2.
