### ISSUE TITLE
scylla-server.service failed with "Exception occurred while creating perftune.yaml: argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylladb#10050] opened 2022-02-08 23:38 UTC
Installation details
Kernel version: 5.11.0-1022-aws
Scylla version (or git commit hash): 4.6.rc5-0.20220203.5694ec189 with build f5d85bf5abe6d2f9fd3487e2469ce1c34304cc14
Cluster size: 7 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-06df116ea1c70171c (aws: eu-west-1)

Test: longevity-50gb-3days-test
Test name: longevity_test.LongevityTest.test_custom_time
Test config file(s):

longevity-50GB-3days-authorization-and-tls-ssl.yaml
Issue description

====================================
While running GrowShrinkCluster nemesis, when starting up a new node `scylla-server.service` failed when trying to create `perftune.yaml` on node 14:

```
< t:2022-02-08 01:38:04,372 f:base.py         l:142  c:RemoteCmdRunner      p:DEBUG > Command "sudo rm -f /etc/scylla/ami_disabled" finished with status 0 
< t:2022-02-08 01:38:04,382 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "sudo systemctl start scylla-server.service"...
< t:2022-02-08 01:38:04,373 f:base.py         l:222  c:RemoteCmdRunner      p:DEBUG > read1,      79547850,     864,     864,     864,     3.4,     2.9,     7.4,    10.0,    14.1,    17.7,86076.0,  0.00251,      0,      0,       0,       0,       0,       0
< t:2022-02-08 01:38:04,383 f:base.py         l:222  c:RemoteCmdRunner      p:DEBUG > read2,      79562860,     883,     883,     883,     3.5,     3.0,     7.6,    10.1,    15.5,    17.9,86076.0,  0.00251,      0,      0,       0,       0,       0,       0
< t:2022-02-08 01:38:04,383 f:base.py         l:222  c:RemoteCmdRunner      p:DEBUG > read3,      79565765,     929,     929,     929,     3.6,     3.0,     7.6,    11.7,    14.9,    19.4,86076.0,  0.00251,      0,      0,       0,       0,       0,       0
< t:2022-02-08 01:38:04,383 f:base.py         l:222  c:RemoteCmdRunner      p:DEBUG > total,     477337996,    5273,    5273,    5273,     3.8,     3.3,     7.7,    10.1,    14.2,    19.4,86076.0,  0.00251,      0,      0,       0,       0,       0,       0
< t:2022-02-08 01:38:04,638 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-4 !    INFO | {"L":"INFO","T":"2022-02-08T01:38:04.230Z","N":"http","M":"GET /storage_service/host_id","from":"10.0.2.138:47738","status":200,"bytes":424,"duration":"13ms"}
< t:2022-02-08 01:38:04,638 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-4 !     ERR |  [shard 0] rpc - client 10.0.1.217:7001: fail to connect: Connection refused
< t:2022-02-08 01:38:04,750 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-13 !    INFO | {"L":"INFO","T":"2022-02-08T01:38:04.228Z","N":"http","M":"GET /storage_service/host_id","from":"10.0.2.138:59718","status":200,"bytes":424,"duration":"7ms"}
< t:2022-02-08 01:38:04,750 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-14 !  NOTICE | scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/systemctl start scylla-server.service
< t:2022-02-08 01:38:04,750 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-13 !    INFO | {"L":"INFO","T":"2022-02-08T01:38:04.253Z","N":"http","M":"GET /gossiper/endpoint/live/","from":"10.0.2.138:59718","status":200,"bytes":63,"duration":"10ms"}
< t:2022-02-08 01:38:04,750 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-14 !    INFO | pam_unix(sudo:session): session opened for user root by (uid=0)
< t:2022-02-08 01:38:04,751 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-13 !    INFO | {"L":"INFO","T":"2022-02-08T01:38:04.293Z","N":"http","M":"GET /storage_service/nodes/joining","from":"10.0.2.138:59718","status":200,"bytes":2,"duration":"30ms"}
< t:2022-02-08 01:38:04,751 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-14 !    INFO | Starting Scylla Server...
< t:2022-02-08 01:38:04,751 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-13 !    INFO | {"L":"INFO","T":"2022-02-08T01:38:04.363Z","N":"http","M":"GET /storage_service/nodes/moving","from":"10.0.2.138:59718","status":200,"bytes":2,"duration":"10ms"}
< t:2022-02-08 01:38:04,751 f:events_processes.py l:146  c:sdcm.sct_events.events_processes p:DEBUG > Get process `MainDevice' from EventsProcessesRegistry[lod_dir=/home/ubuntu/sct-results/20220207-003336-504089,id=0x7fda2bd63970,default=True]
< t:2022-02-08 01:38:04,751 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-13 !     ERR |  [shard 0] rpc - client 10.0.1.217:7001: fail to connect: Connection refused
< t:2022-02-08 01:38:04,751 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-14 !    INFO | Exception occurred while creating perftune.yaml: argument of type 'NoneType' is not iterable
< t:2022-02-08 01:38:04,752 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-14 !    INFO | To fix the error, please re-run scylla_setup.
< t:2022-02-08 01:38:04,752 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-02-08T01:38:04+00:00 longevity-tls-50gb-3d-4-6-db-node-8fc9e95f-14 !  NOTICE | scylla-server.service: Control process exited, code=exited, status=1/FAILURE
```

A possibly related issue was encountered 5 minutes later on node 15: https://github.com/scylladb/scylla/issues/10051
====================================

Restore Monitor Stack command: $ hydra investigate show-monitor 8fc9e95f-1c88-48d4-bad6-4cc7d360758b
Show all stored logs command: (Not available - SCT runner instance crashed during test)

Test id: 8fc9e95f-1c88-48d4-bad6-4cc7d360758b

Jenkins job url: https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/longevity/view/Long%20Longevities/job/longevity-50gb-3days-test/9/
Monitor node: http://52.19.120.3:3000
SCT runner instance IP: 54.247.23.104

**Comment by roydahan** [comment] 2022-02-09 11:42
@syuu1228

**Comment by syuu1228** [comment] 2022-02-14 11:01
Not able to reproduce manually with ami-06df116ea1c70171c on i3.4xlarge, and also could not get detail information from jenkins jobs.
To determine the bug, I guess we at least need to get backtrace of the python script, and get perftune.yaml file that causing the error, but I do not have an idea how to get it from SCT

**Comment by KnifeyMoloko** [comment] 2022-02-15 13:39
@syuu1228 Unfortunately we cannot get details from the jenkins job (the runner node failed during the test, but quite some time after this issue happened). I managed to collect the db and sct-runner logs here: s3://scylla-qa-team/maciej_c/2022-02-07_8fc9e95f-1c88-48d4-bad6-4cc7d360758b. I don't have the permission to make that folder public / add you to the ACL, but I'm working on that. I'll update here once that's done.

**Comment by slivne** [comment] 2022-02-16 07:19
@roydahan ping

**Comment by KnifeyMoloko** [comment] 2022-02-21 15:27
I moved the logs to a public folder here: s3://scylla-qa-public/maciej_c/2022-02-07_8fc9e95f-1c88-48d4-bad6-4cc7d360758b/ @syuu1228 you should be able to download them now.

**Comment by syuu1228** [comment] 2022-02-28 11:24
Seems like we had same issue a years ago: #8008
But we already fixed it, maybe we are hitting similar bug or something..

Unfortunately, we disabled the Traceback in the script (was mistake, need to re-enable. see #10140), I do not find more information in the log, but I guess the Exception is likely raised at perftune.py, not scylla_prepare.

**Comment by slivne** [comment] 2022-03-06 10:26
pushing this out

**Comment by syuu1228** [comment] 2022-03-19 21:20
> Seems like we had same issue a years ago: #8008 But we already fixed it, maybe we are hitting similar bug or something..
> 
> Unfortunately, we disabled the Traceback in the script (was mistake, need to re-enable. see #10140), I do not find more information in the log, but I guess the Exception is likely raised at perftune.py, not scylla_prepare.

Tried to reproduce but I couldn't.
I think we should try to reproduce it in SCT again, with Traceback enabling patch (#10140).

**Comment by syuu1228** [comment] 2023-10-16 14:04
Closing, since there is no Traceback log, and not able to reproduced for a long time.

**Closed by syuu1228** 2023-10-16 14:04 UTC
Labels: bug
