### ISSUE TITLE
offline_tools_test.TestOfflineTools.test_sstablelevelreset is flaky

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#15210] opened 2023-08-29 14:22 UTC
The build https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3324/ failed on the dtest `offline_tools_test.TestOfflineTools.test_sstablelevelreset`.

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3324/testReport/offline_tools_test/TestOfflineTools/Tests___Sanity_Tests___test_sstablelevelreset/

**Comment by kbr-scylla** [comment] 2023-08-29 14:32
cc @denesb

**Comment by kbr-scylla** [comment] 2023-08-29 14:35
Relevant logs (attaching so we don't lose them when the job is cleared by Jenkins):

[dtest-gw4.log](https://github.com/scylladb/scylladb/files/12465742/dtest-gw4.log)
[1693304667338_offline_tools_test.py TestOfflineTools test_sstablelevelreset.zip](https://github.com/scylladb/scylladb/files/12465744/1693304667338_offline_tools_test.py.TestOfflineTools.test_sstablelevelreset.zip)

**Comment by tchaikov** [comment] 2023-08-29 15:17
@denesb yes, it was https://github.com/scylladb/scylla-dtest/pull/3491 . i will take a look tomorrow.

**Comment by tchaikov** [comment] 2023-08-30 02:35
the error was 
```
Data component is missing for sstable /jenkins/workspace/scylla-enterprise/gating-dtest-release/scylla-enterprise/.dtest/dtest-gw45qhqb/test/node1/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/me-14-big
```

but what https://github.com/scylladb/scylla-dtest/pull/3491 changed is not related to how the test is performed. it just changed the way how we retrieve the sstable level. while the failed check was verifying the output from `sstablelevelreset`. i admit that the name of this method is a little bit misleading though.

**Comment by tchaikov** [comment] 2023-08-30 02:55
> Relevant logs (attaching so we don't lose them when the job is cleared by Jenkins):
> 
> [dtest-gw4.log](https://github.com/scylladb/scylladb/files/12465742/dtest-gw4.log) [1693304667338_offline_tools_test.py TestOfflineTools test_sstablelevelreset.zip](https://github.com/scylladb/scylladb/files/12465744/1693304667338_offline_tools_test.py.TestOfflineTools.test_sstablelevelreset.zip)

per the logging message of dtest, the `sstablelevelreset` tool was expecting the data component of `system_schema/indexes-0feb57ac311f382fba6d9024d305702f/me-14-big`. but it failed.
```
ERROR 10:24:27,124 Error in ThreadPoolExecutor\njava.lang.AssertionError: Data component is missing for sstable /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-5ewmod99/test/node1/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/me-14-big
```
while at the scylla's end, it was compacting 
```
INFO  2023-08-29 10:24:24,668 [shard 0] compaction - [Compact system_schema.indexes 39d869c0-4656-11ee-80a0-e3488715716c] Compacting [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-5ewmod99/test/node1/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/me-12-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-5ewmod99/test/node1/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/me-10-big-Data.db:level=0:origin=compaction]
```
but the corresponding "Compacted" message is not found. please note, the quoted logging message above is the last one in `node1.log`. presumably, `me-12-big-Data.db` and `me-10-big-Data.db` was supposed to be compacted into `me-14-big-Data.db. as "10" is the next generation id of this table used by shard 0.

**Comment by benipeled** [comment] 2023-08-30 05:25
and now on enterprise https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2528/testReport/junit/offline_tools_test/TestOfflineTools/Tests___Sanity_Tests___test_sstablelevelreset/

**Comment by benipeled** [comment] 2023-08-31 09:33
@avikivity next-enterprise is broken because of this failure, we need OS>Ent merge asap

**Comment by mykaul** [comment] 2023-08-31 09:37
@scylladb/scylla-maint can do this too, I hope?

**Comment by fruch** [comment] 2023-08-31 09:44
There nothing todo here

It's a fix in ccm, and it merged.

Now it hit the master, it would work on enterprise branch as well

For release we might want to backport, but that's a different discussion

**Comment by benipeled** [comment] 2023-08-31 09:47
> There nothing todo here
> 
> It's a fix in ccm, and it merged.
> 
> Now it hit the master, it would work on enterprise branch as well
> 
> For releases we might want to backport, but that's a different discussion

oops, you're right, it's ccm

**Comment by benipeled** [comment] 2023-08-31 09:50
The next-enterprise build didn't include the fix, rerun it now and it should include it

**Comment by tchaikov** [comment] 2023-09-01 03:44
i am still seeing the failure.

**Closed** 2023-09-02 18:52 UTC
Labels: CI-Stability

**Comment by mykaul** [comment] 2023-09-03 11:08
I'm seeing the failure @ https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4199/testReport/offline_tools_test/TestOfflineTools/FullDtest___full_split001___test_sstablelevelreset/ - which looks like after this issue was closed. Re-open?

**Comment by tchaikov** [comment] 2023-09-03 11:16
> I'm seeing the failure @ https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4199/testReport/offline_tools_test/TestOfflineTools/FullDtest___full_split001___test_sstablelevelreset/ - which looks like after this issue was closed. Re-open?

lemme quote some interesting bits in https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4199/

```
Started 1 day 4 hr ago
```

```
Revision: a45eda983aaea9ee36362635663c4c0a99520b47 
Repository: git@github.com:scylladb/scylla-ccm.git
```

if we take a look at https://github.com/scylladb/scylla-ccm/commits/master . a45eda983aaea9ee36362635663c4c0a99520b47 is sitting before https://github.com/scylladb/scylla-ccm/commit/5eefb82512a444f49d43a557e431ccbbb609ff23, and https://github.com/scylladb/scylla-ccm/commit/5eefb82512a444f49d43a557e431ccbbb609ff23 was merged 16 hours ago. 

so i'd suggest keep this issue closed until we find a genuine regression.
