### ISSUE TITLE
TestSSTableGenerationAndLoading::test_sstableloader_compression is flaky since May

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#14842] opened 2023-07-26 15:08 UTC
when it's failing it's like that
```
>                   assert not has_errors, f"The stderr of sstableloader has errors: {stderr}"
E                   AssertionError: The stderr of sstableloader has errors: WARN  04:34:37,285 Ignoring codec  [frozen<tuple<int, uuid, bigint, bigint>> <-> java.nio.ByteBuffer] because it collides with previously registered codec  [frozen<tuple<int, uuid, bigint, bigint>> <-> java.nio.ByteBuffer]
E                     ERROR 04:37:51,468 LEAK DETECTED: a reference (org.apache.cassandra.utils.concurrent.Ref$State@119ae5b7) to class org.apache.cassandra.io.sstable.format.SSTableReader$InstanceTidier@462528327:/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.dtest/dtest-7_nna6zx/test/node1/data_copy/ks/counter1-18ba60a0ea3411ed9602eb9edec59c82/me-3-big was not released before the reference was garbage collected
E                     
E                   assert not True
```

first time it failed like that with: `5.3.0-dev-0.20230504.113fb3201972` on debug run

today it failed on next gating:
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/3236/testReport/junit/sstable_generation_loading_test/TestSSTableGenerationAndLoading/FullDtest___full_split001___test_sstableloader_compression_Snappy_Snappy_/

```
AssertionError: The stderr of sstableloader has errors: ERROR 09:15:22,027 LEAK DETECTED: a reference (org.apache.cassandra.utils.concurrent.Ref$State@6b031aed) to class org.apache.cassandra.io.sstable.format.SSTableReader$InstanceTidier@571945556:/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-8q2bd5ev/test/node1/data_copy/ks/standard1-be04bdc02b9411ee80b563b1cecd1948/me-2-big was not released before the reference was garbage collected
  
assert not True
``` 

happened 31 times since May

history in ELK:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/18171930-2bc6-11ee-b96a-256b7e8b2261

**Comment by DoronArazii** [comment] 2023-07-27 09:19
@raphaelsc I think it's under your domain, can you please take a look

**Comment by tchaikov** [comment] 2023-08-06 08:57
@raphaelsc hi Raphael, i think https://github.com/scylladb/scylla-dtest/issues/3350 should help us to address this issue despite the root cause is still unknown. but the native tool would be much easier for us to get the bottom of the problem. so, i am hijacking this issue from you.

**Comment by tchaikov** [comment] 2023-08-07 03:01
looks like a dup of #4190

**Comment by fruch** [comment] 2023-08-07 03:16
@tchaikov we still need todo something about it

It's a gating test, and slowing people down , cause it has a high failing rate

Or we take it out of gating, until fixed, or we get it fix.

**Comment by tchaikov** [comment] 2023-08-07 03:18
sorry for the confusion. i am not claiming that it's not an issue. i just think it's a duplicated one.

**Comment by tchaikov** [comment] 2023-08-07 03:20
IMHO, create more issues for a single problem does not help to address it.

**Comment by tchaikov** [comment] 2023-08-07 04:10
just created https://github.com/scylladb/scylla-dtest/issues/3464 to track this issue. if you want to keep this issue open, i don't feel strong about. but i doubt if we can do anything on scylla's end.

**Comment by raphaelsc** [comment] 2023-08-09 12:26
> hi @fruch and @DoronArazii , now that [scylladb/scylla-dtest#3465](https://github.com/scylladb/scylla-dtest/pull/3465) has been merged, we should not be suffering from this issue, so i am removing the CI-Stability and P1 labels.
> 
> also, i believe that the better place for this issue is [scylladb/scylla-tools-java#337](https://github.com/scylladb/scylla-tools-java/issues/337) . i still think it''d be better to close it.

thanks a lot Kefu for tackling this.

**Comment by DoronArazii** [comment] 2023-08-09 12:50
> hi @fruch and @DoronArazii , now that [scylladb/scylla-dtest#3465](https://github.com/scylladb/scylla-dtest/pull/3465) has been merged, we should not be suffering from this issue, so i am removing the CI-Stability and P1 labels.
> 
> also, i believe that the better place for this issue is [scylladb/scylla-tools-java#337](https://github.com/scylladb/scylla-tools-java/issues/337) . i still think it''d be better to close it.

Thanks Kefu.
@fruch per Dev this is fixed.
Is it something that we can reproduce? or it's better closing it & re-opening if necessary?

**Comment by DoronArazii** [comment] 2023-08-30 10:16
@fruch ping

**Comment by mykaul** [comment] 2023-10-26 12:50
Closing for the time being - please re-open if it still an issue.

**Closed by mykaul** 2023-10-26 12:50 UTC
Labels: dtest
