### ISSUE TITLE
snapshot_works fails due to timeout

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#13556] opened 2023-04-18 06:41 UTC
```
03:54:14  [4796/8140]  boost     dev   [ FAIL ] boost.database_test.snapshot_works.1 74.02s
...
05:05:55  test/boost/database_test.cc(529): Entering test case "snapshot_works"
...
05:05:55  INFO  2023-04-17 22:53:58,294 [shard 0] compaction_manager - Starting off-strategy compaction for system_schema.keyspaces, 0 candidates were found
05:05:55  INFO  2023-04-17 22:53:58,294 [shard 1] compaction_manager - Done with off-strategy compaction for system.scylla_views_builds_in_progress
...
05:05:56  INFO  2023-04-17 22:54:01,477 [shard 1] compaction_manager - Starting off-strategy compaction for system_schema.view_virtual_columns, 0 candidates were found
05:05:56  INFO  2023-04-17 22:54:01,477 [shard 1] compaction_manager - Done with off-strategy compaction for system_schema.view_virtual_columns
...
05:05:56  INFO  2023-04-17 22:54:13,626 [shard 1] messaging_service - Stopping tls server
05:05:56  INFO  2023-04-17 22:54:13,626 [shard 1] messaging_service - Stopping tls server - Done
05:05:56  unknown location(0): fatal error: in "snapshot_works": exceptions::read_timeout_exception: Operation timed out for system_auth.roles - received only 0 responses from 1 CL=LOCAL_ONE.
05:05:56  test/boost/database_test.cc(551): last checkpoint
05:05:56  test/boost/database_test.cc(529): Leaving test case "snapshot_works"; testing time: 73775085us
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/683/consoleFull

**Comment by xemul** [comment] 2023-04-18 06:51
Very similar sympthons are in next-promotion with test_distrintued_loader_with_pending_delete test case:
https://jenkins.scylladb.com/job/scylla-master/job/next/5885/consoleText

Flood of offstrategy compaction with 0 candidates messages

Cc @raphaelsc , @bhalevy

**Comment by denesb** [comment] 2023-04-18 08:52
Also similar to https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/687/.
Here the failing test is [boost.Master Test Suite.dev.test_distributed_loader_with_incomplete_sstables](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/687/testReport/junit/boost.Master%20Test%20Suite/dev/test_distributed_loader_with_incomplete_sstables/).

**Comment by bhalevy** [comment] 2023-04-21 06:37
similar issue in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/769/artifact/testlog/x86_64/dev/boost.database_test.clear_snapshot.1.log
```
unknown location(0): fatal error: in "clear_snapshot": exceptions::read_timeout_exception: Operation timed out for system_auth.roles - received only 0 responses from 1 CL=LOCAL_ONE.
```

**Comment by bhalevy** [comment] 2023-04-24 11:25
@eliransin can your team do the triage please?

**Comment by benipeled** [comment] 2023-04-25 06:24
Same on 5.2 - https://jenkins.scylladb.com/job/scylla-5.2/job/next/105/artifact/testlog/x86_64/dev/boost.database_test.snapshot_skip_flush_works.2.log/*view*/

```
unknown location(0): fatal error: in "snapshot_skip_flush_works": exceptions::read_timeout_exception: Operation timed out for system_auth.roles - received only 0 responses from 1 CL=LOCAL_ONE.
```

**Comment by bhalevy** [comment] 2023-04-25 06:29
> Same on 5.2 - https://jenkins.scylladb.com/job/scylla-5.2/job/next/105/artifact/testlog/x86_64/dev/boost.database_test.snapshot_skip_flush_works.2.log/*view*/
> 
> ```
> unknown location(0): fatal error: in "snapshot_skip_flush_works": exceptions::read_timeout_exception: Operation timed out for system_auth.roles - received only 0 responses from 1 CL=LOCAL_ONE.
> ```

This is #13660

**Comment by DoronArazii** [comment] 2023-05-03 07:25
@eliransin / @ptrsmrn ping
Raising the priority to P1 (same as all the CI-Stability cases)

**Comment by denesb** [comment] 2023-05-03 07:38
I'm already working on an issue (https://github.com/scylladb/scylladb/issues/13660) which I suspect is a duplicate of this issue.

**Closed** 2023-05-03 07:40 UTC
Labels: Master/Triage, P1, CI-Stability
