### ISSUE TITLE
TestClusterReplacement.test_rolling_cluster_replacement_sequentially_dead_nodes_remove_and_add_multi_dc failed

### ISSUE THREAD

**Issue by Annamikhlin** [scylladb/scylladb#17872] opened 2024-03-18 15:33 UTC
link to failed job: https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/522/testReport/junit/cluster_replacement_test/TestClusterReplacement/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split010___test_rolling_cluster_replacement_sequentially_dead_nodes_remove_and_add_multi_dc/

dtest-release failed in `TestClusterReplacement.test_rolling_cluster_replacement_sequentially_dead_nodes_remove_and_add_multi_dc` test

with ERROR:
```
self = <cluster_replacement_test.TestClusterReplacement object at 0x7f6906ec68d0>

    @pytest.mark.required_features("!tablets")
    @pytest.mark.next_gating
    def test_rolling_cluster_replacement_sequentially_dead_nodes_remove_and_add_multi_dc(self):
        """
        This test uses the field strategy to replace a node in a multi dc cluster.
        Add a new node to the cluster and then decommission the old node.
        Replace all nodes on dc2 then move to replace nodes on dc1.
        """
        cluster = self.cluster
        cluster.populate(self.cluster_topology).start()
        node1 = self.cluster.nodelist()[0]
        n_of_keys = self.num_keys
        self._insert_data(node1, rf={"dc1": 2, "dc2": 2}, n_of_keys=n_of_keys)
        for node in self.cluster.nodelist()[::-1]:
>           self.replace_dead_node_by_remove_and_add(old_node=node)

cluster_replacement_test.py:171: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cluster_replacement_test.py:47: in replace_dead_node_by_remove_and_add
    new_node.start(wait_for_binary_proto=True, wait_other_notice=True)
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:686: in start
    scylla_process = self._start_scylla(args=args, marks=marks, update_pid=update_pid,
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:329: in _start_scylla
    self.wait_for_binary_interface(from_mark=from_mark, process=self._process_scylla, timeout=t)
../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:540: in wait_for_binary_interface
    self.watch_log_for("Starting listening for CQL clients", **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ccmlib.scylla_node.ScyllaNode object at 0x7f6905d2a850>
exprs = 'Starting listening for CQL clients', from_mark = 0, timeout = 420
process = <Popen: returncode: 1 args: ['/jenkins/workspace/scylla-master/dtest-release...>
verbose = False, filename = 'system.log'

    def watch_log_for(self, exprs, from_mark=None, timeout=600, process=None, verbose=False, filename='system.log'):
        """
        Watch the log until one or more (regular) expression are found.
        This methods when all the expressions have been found or the method
        timeouts (a TimeoutError is then raised). On successful completion,
        a list of pair (line matched, match object) is returned.
        """
        elapsed = 0
        tofind = [exprs] if isinstance(exprs, str) else exprs
        tofind = [re.compile(e) for e in tofind]
        matchings = []
        reads = ""
        if len(tofind) == 0:
            return None
    
        log_file = os.path.join(self.get_path(), 'logs', filename)
        while not os.path.exists(log_file):
            time.sleep(.1)
            if process:
                process.poll()
                if process.returncode is not None:
                    self.print_process_output(self.name, process, verbose)
                    if process.returncode != 0:
                        raise RuntimeError()  # Shouldn't reuse RuntimeError but I'm lazy
    
        with open(log_file) as f:
            if from_mark:
                f.seek(from_mark)
    
            while True:
                # First, if we have a process to check, then check it.
                # Skip on Windows - stdout/stderr is cassandra.bat
                if not common.is_win():
                    if process:
                        process.poll()
                        if process.returncode is not None:
                            self.print_process_output(self.name, process, verbose)
                            if process.returncode != 0:
                                raise RuntimeError()  # Shouldn't reuse RuntimeError but I'm lazy
    
                line = f.readline()
                if line:
                    reads = reads + line
                    for e in tofind:
                        m = e.search(line)
                        if m:
                            matchings.append((line, m))
    
                            # This is bogus! - One should not modify the list from inside the loop which iterates on
                            # that list.
                            # However since we are going to break from the loop a few lines below that should be ok.
                            tofind.remove(e)
    
                            if len(tofind) == 0:
                                return matchings[0] if isinstance(exprs, str) else matchings
                            break
                else:
                    # yep, it's ugly
                    time.sleep(0.01)
                    elapsed = elapsed + 1
                    if elapsed > 100 * timeout:
                        raise TimeoutError(time.strftime("%d %b %Y %H:%M:%S", time.gmtime()) + " [" + self.name + "] Missing: " + str(
                            [e.pattern for e in tofind]) + ":\n" + reads[:50] + f".....\nSee {filename} for remainder")
    
                if process:
                    if common.is_win():
                        if not self.is_running():
                            return None
                    else:
                        process.poll()
                        if process.returncode is not None:
                            if process.returncode == 0:
                                return None
                            else:
>                               raise RuntimeError(f"The process is dead, returncode={process.returncode}")
E                               RuntimeError: The process is dead, returncode=1

../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:506: RuntimeError
```

**Comment by patjed41** [comment] 2024-05-08 09:12
Failed again in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8594/.

I see the logs from the first failure are still there, but I'll provide the new logs just to be safe:
[1715093534234_cluster_replacement_test.py TestClusterReplacement test_rolling_cluster_replacement_sequentially_dead_nodes_remove_and_add_multi_dc.zip](https://github.com/scylladb/scylladb/files/15246537/1715093534234_cluster_replacement_test.py.TestClusterReplacement.test_rolling_cluster_replacement_sequentially_dead_nodes_remove_and_add_multi_dc.zip)
[dtest-gw4.log](https://github.com/scylladb/scylladb/files/15246539/dtest-gw4.log)

**Comment by kbr-scylla** [comment] 2024-05-08 09:32
Looks very similar to https://github.com/scylladb/scylladb/issues/17526

possible explanation that likely applies for this test as well: https://github.com/scylladb/scylladb/issues/17526#issuecomment-2096048910

**Comment by kbr-scylla** [comment] 2024-06-07 15:57
Marking as `blocked` -- let's focus on fixing https://github.com/scylladb/scylladb/issues/17526 first, which is likely the same root cause, and see if this keeps happening.

**Comment by kbr-scylla** [comment] 2024-06-25 11:16
Thanks, closing.

**Closed by kbr-scylla** 2024-06-25 11:16 UTC
Labels: symptom/ci stability, status/blocked
