### ISSUE TITLE
nodetool: Failed to connect to '127.0.0.1:7199' - URISyntaxException: 'Malformed IPv6 address at index 7: rmi://[127.0.0.1]:7199'.

### ISSUE THREAD

**Issue by yuyang08180818** [scylladb/scylladb#11043] opened 2022-07-14 08:51 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):CentOS 7.8

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by amnonh** [comment] 2022-07-14 08:56
@yuyang08180818 can you please add more details, how do you run scylla?
how did you run the nodetool command,
if you are running your own scylla and scylla-jmx, how did you run scylla-jmx?

**Comment by yuyang08180818** [comment] 2022-07-14 09:07
> @yuyang08180818您能否添加更多详细信息，您如何运行 scylla？ 您是如何运行 nodetool 命令的， 如果您正在运行自己的 scylla 和 scylla-jmx，您是如何运行 scylla-jmx 的？

run scylla ：sudo systemctl start scylla-server
run  nodetool ：nodetool status

**Comment by yuyang08180818** [comment] 2022-07-14 09:08
> @yuyang08180818 can you please add more details, how do you run scylla? how did you run the nodetool command, if you are running your own scylla and scylla-jmx, how did you run scylla-jmx?

run scylla ：sudo systemctl start scylla-server
run nodetool ：nodetool status

**Comment by d-mankowski-synerise** [comment] 2022-08-05 18:55
duplicate of https://github.com/scylladb/scylladb/issues/10442

**Comment by slivne** [comment] 2022-08-11 08:30
closing this issue as its a duplicate - please upgfrade to 4.6.4 or later - if there is still anything needed please reopen

**Closed by slivne** 2022-08-11 08:30 UTC
