### ISSUE TITLE
Switch internal distributed keyspaces from SimpleStrategy to NetworkTopologyStrategy / EverywhereStrategy / Raft Group 0

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#8582] opened 2021-05-03 12:25 UTC
In our documentation (and see also issue #5224) we strongly recommend that users who create a keyspace should not use `SimpleStrategy` replication, and instead should use `NetworkTopologyStrategy`. The problem with the former is that as soon as you want to add more DCs to the cluster, `SimpleStrategy` is no longer good enough: Its main problem is that it fails to achieve the _availability_ expected with a cluster with multiple DCs: With `SimpleStrategy`, each piece of data is replicated to a random subset of RF (e.g., 3) nodes, but these nodes are chosen without regard to DC assignment - so some pieces of data will have all replicas in the _same_ DC, meaning that if this DC is unavailable, this data is completely unavailable. In contrast, `NetworkTopologyStrategy` ensures that all DCs have copies of the data.

So although we recommend `NetworkTopologyStrategy` to users who run CQL `CREATE KEYSPACE` and can control its replication strategy - in a few cases Scylla itself creates distributed tables and does not follow its own advice, and creates them with `SimpleStrategy`... The following is a (hopefully?) complete list of such cases:

1. **Authentication** creates the keyspace AUTH_KS (`system_auth`) with `SimpleStrategy` and RF=1 (`auth/service.cc`). Issue #1796 discusses the problems with this, and began by asking that we should use everywhere replication for this keyspace, but at the end @slivne and @glommer decided we should go with `NetworkTopologyStrategy` with RF=3 (per DC).
2. **Redis** tables live in keyspaces called `REDIS_*` which by default (see `redis/keyspace_utils.cc`) use `SimpleStrategy` and RF=3 (if there are at least three nodes in the cluster). These defaults may be overriden by configuration parameters declared in  `db/config.cc` (and our defaults are also documented there).
3. **Distributed System Tables** - these are Scylla's internal system tables which are distributed (whereas most system tables are node-local), and created in the `system_distributed` keyspace (see `db/system_distributed_keyspace.hh`).  The tables in this keyspace include `view_build_status`, `service_levels`, and several CDC-related tables (`cdc_generation_description`, `cdc_streams_descriptions`, `cdc_streams_description_v2`, `cdc_generation_timestamps`). This keyspace is created in `db/system_distributed_keyspace.cc` with `SimpleStrategy` and RF=3.
4. **Tracing** - uses a keyspace `system_traces` (see `tracing/trace_keyspace_helper.cc`). The keyspace is created using the `table_helper::setup_keyspace()` function (see `table_helper.cc`) and that function uses `SimpleStrategy` and the RF passed to it by the caller (surprisingly, it is 2, not 3). 

Until recently, **Alternator** also created keyspaces with `SimpleStrategy` in almost the same way as Redis does this today, but this was fixed in Alternator in #5596 to use `NetworkTopologyStrategy`. Strangely (I still don't know why) our implementation in Alternator (commit dca6c2c81d709ece7980546ad9e5874fa31d32f7) did not use the ability to pass one `replication_factor` that gets applied to all extant DCs - and instead has code which lists all the DCs and sets the same RF on all of them explicitly.

One of the frustrating things about the above list is that each of the listed places has its own code for creating the keyspace. For tracing there was an attempt to create a seemingly-generic function `table_helper::setup_keyspace()`, but it wasn't used in any other place... Maybe as part of this issue we should try to have all these four places call the same function.

Another problem we need to address in all the above cases is whether we need to use the `LOCAL_QUORUM` and `LOCAL_ONE` consistency levels - and stop using `QUORUM` or `ONE` which are perhaps less appropriate for multi-DC setups. In Redis, we indeed default (`db/config.cc`) to `LOCAL_QUORUM`. But in authentication (see `auth/service.cc` and also `password_authenticator::consistency_for_user()`  in `auth/password_authenticator.cc`) we use `ONE` or `QUORUM` or `LOCAL_ONE` - I'm not sure exactly when exactly each is used.  Tracing uses the `ANY` consistency level (see `tracing/trace_keyspace_helper.cc`) so is probably fine. In distributed systems tables (`db/system_distributed_keyspace.cc`) we seem to be using `QUORUM` or `ONE` in different places in that file - not the `LOCAL` versions of those. 

TODO: Also discuss which documentation we need to change (on how to expand the DCs when adding them)

**Comment by slivne** [comment] 2021-05-03 12:38
Please note - we need to validate this will not cause issues in upgrades - if tables already exist they should retain SimpleStrategy. If tables don't exist (new cluster / new keyspace) they should start with NetworkTopologyStrategy.

**Comment by nyh** [comment] 2021-05-03 18:41
> Please note - we need to validate this will not cause issues in upgrades - if tables already exist they should retain SimpleStrategy. If tables don't exist (new cluster / new keyspace) they should start with NetworkTopologyStrategy.

I think this will happen naturally, as all these internal keyspaces (I compiled a full list above) we only create them once, if they don't exist - and afterwards never touch them again.

**Comment by eliransin** [comment] 2021-05-04 07:23
@slivne, I think we should be more active and figure out an upgrade path, it doesn't have to be in the first version but IMHO it has to be at some point, even if it is manual, maybe we need to provide the procedure used for converting user tables. Those tables are small so I expect this to be a breeze in comparison to user tables and the first benefit of this is that we immediately get auth availability increase.

**Comment by nyh** [comment] 2022-01-17 12:33
#9934 is a duplicate of this issue with some interesting observations by @kbr-

**Comment by tgrabiec** [comment] 2022-01-17 18:44
Should we prohibit bootstrapping a node in another DC if there are SimpleStrategy keyspaces? This will force users to change the replication strategy first and avoid all the pitfalls.

This will also enable topology changes to rely on the fact that only NetworkTopologyStrategy is used in a multi-DC setup and use weak token metadata consistency across DCs, strong within DC.

**Comment by gleb-cloudius** [comment] 2022-01-18 12:39
On Mon, Jan 17, 2022 at 10:45:09AM -0800, Tomasz Grabiec wrote:
> Should we prohibit bootstrapping a node in another DC if there are SimpleStrategy keyspaces? This will force users to change the replication strategy first and avoid all the pitfalls.
> 
Not all. A user will have to add new DC to the replication strategy
after bootstrapping it.

--
			Gleb.

**Comment by avikivity** [comment] 2022-01-18 13:29
> Should we prohibit bootstrapping a node in another DC if there are SimpleStrategy keyspaces? This will force users to change the replication strategy first and avoid all the pitfalls.

Good idea.

**Comment by avikivity** [comment] 2022-01-18 13:31
> On Mon, Jan 17, 2022 at 10:45:09AM -0800, Tomasz Grabiec wrote: Should we prohibit bootstrapping a node in another DC if there are SimpleStrategy keyspaces? This will force users to change the replication strategy first and avoid all the pitfalls.
> Not all. A user will have to add new DC to the replication strategy after bootstrapping it.


Let's create a variant of NetworkTopologyStrategy that automatically replicates to all datacenters (and has a default rf=3).

**Comment by gleb-cloudius** [comment] 2022-01-18 13:35
> 
> Let's create a variant of NetworkTopologyStrategy that automatically replicates to all datacenters (and has a default rf=3).

This will make the keyspace unavailable for a new DC until it is extended to 3 nodes (also for each_quorum queries, but who use it anyway).

**Comment by avikivity** [comment] 2022-01-18 13:42
Since it's a new strategy, we can define it in a convenient way. Say local_rf = min(requested_rf, dc_nodes).

**Comment by vladzcloudius** [comment] 2022-03-22 17:34
> > Let's create a variant of NetworkTopologyStrategy that automatically replicates to all datacenters (and has a default rf=3).
> 
> This will make the keyspace unavailable for a new DC until it is extended to 3 nodes (also for each_quorum queries, but who use it anyway).

@avikivity when you run this: 

```
alter keyspace ... with replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 'X'}
```

It will set RF to X in all currently present DCs.

**Comment by nyh** [comment] 2022-12-06 12:27
Now that @avikivity changed the title of this issue to refer to NetworkTopologyStrategy / EverywhereStrategy / ... instead of just NetworkTopologyStrategy, this issue largely overlaps with https://github.com/scylladb/scylladb/issues/1796 which asks that for at least one internal distributed keyspace (system_auth) we use EverywhereStrategy. So it's possible that one PR would mark both issues fixed.

**Comment by avikivity** [comment] 2022-12-06 12:43
Let's merge it into #1796. There's no point in having so many overlapping issues. We'll use first-write-wins.

**Comment by avikivity** [comment] 2022-12-06 12:46
Closing as duplicate of #1796. Let's hope there isn't an even earlier issue.

**Closed by avikivity** 2022-12-06 12:46 UTC
Labels: enhancement
