### ISSUE TITLE
test_optimized_reversed_queries_flag fails

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#15232] opened 2023-08-31 06:34 UTC
it's found in the next job of enterprise. but that area should be identical to that of OSS. so i am filing the issue in the OSS repo.

we check for the error message when tearing down the cluster. and an unexpected error message showed up:

```
failed on teardown with "AssertionError: Unexpected errors found: [('node1', ['ERROR 2023-08-30 12:26:44,865 [shard 0] storage_proxy - Exception when communicating with 127.0.71.1, to read from system.local: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 1 (configured via max_memory_for_unlimited_query_hard_limit))'])]"
...
    @pytest.fixture(scope='function', autouse=False)
    def fixture_dtest_setup(request,
                            dtest_config,
                            fixture_dtest_setup_overrides,
                            fixture_logging_setup,
                            fixture_dtest_cluster_name,
                            fixture_dtest_create_cluster_func):
...
        try:
            if not dtest_setup.allow_log_errors:
                try:
>                   dtest_setup.check_errors_all_nodes()
...


    def check_errors_all_nodes(self, nodes=None, exclude_errors=None, search_str=None, regex=False):
        if nodes is None:
            nodes = self.cluster.nodelist()
...
        if found_errors:
>           raise AssertionError('Unexpected errors found: {}'.format(found_errors))
E           AssertionError: Unexpected errors found: [('node1', ['ERROR 2023-08-30 12:26:44,865 [shard 0] storage_proxy - Exception when communicating with 127.0.71.1, to read from system.local: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 1 (configured via max_memory_for_unlimited_query_hard_limit))'])]
```

in the corresponding dtest we have:
```py
@pytest.mark.dtest_full
@pytest.mark.single_node
class TestOptimizedReversedQueriesFlag(Tester):
# ...
    def test_optimized_reversed_queries_flag(self):
        """
        Test that:
        - `enable_optimized_reversed_reads` option can be dynamically changed as new pages
          are fetched during a reversed query, and the pages return consistent results
        - the option actually has an effect, which we verify by checking if a reversed query
          is considered 'unlimited' when the option is false and not 'unlimited' when it's true

          Ref: https://github.com/scylladb/scylla/pull/9908
        """
        logger.info('Set enable_optimized_reversed_reads to False'
                    ' and max_memory_for_unlimited_query to 1B')
        self.set_config_and_reload(node, {'enable_optimized_reversed_reads': False,
                                          'max_memory_for_unlimited_query': 1})

        with pytest.raises(ReadFailure):
            logger.info('Query using old reversed read algorithm, should fail')
            session.execute(query).one()

        logger.info('Set enable_optimized_reversed_reads to True')
        self.set_config_and_reload(node, {'enable_optimized_reversed_reads': True})
        logger.info('Query using new reversed read algorithm, should succeed')
        assert session.execute(query).one()
```

**Comment by fruch** [comment] 2023-08-31 06:35
@tchaikov it failed only on enterprise... I would recommend moving it there

**Comment by fruch** [comment] 2023-08-31 06:37
test is failed twice since `2023.3.0-dev-0.20230830.dc3d9ef6d064`

seem like there one more extra error, that the test doesn't expect 
```
ERROR 2023-08-30 19:21:42,695 [shard 0] storage_proxy - Exception when communicating with 127.0.96.1, to read from ks.t: std::runtime_error (Memory usage of reversed read exceeds hard limit of 1 (configured via max_memory_for_unlimited_query_hard_limit), while reading partition 0)
ERROR 2023-08-30 19:21:42,706 [shard 0] storage_proxy - Exception when communicating with 127.0.96.1, to read from system.local: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 1 (configured via max_memory_for_unlimited_query_hard_limit))
```

Logs:
https://jenkins.scylladb.com/job/scylla-enterprise/job/gating-dtest-release/740/artifact/logs-full.release.000/1693423305733_reversed_queries_test.py%3A%3ATestOptimizedReversedQueriesFlag%3A%3Atest_optimized_reversed_queries_flag/node1.log/*view*/

**Comment by fruch** [comment] 2023-08-31 06:45
not clear who is reading from system.local at the exact same time, but I'm guess lot of feature and especially enterprise feature might, maybe we should ignore those as well in the test ? 

@kbr-scylla, as the one wrote the test, what do you think of this ?

**Comment by tchaikov** [comment] 2023-08-31 07:05
@fruch see the fix and analysis, how about keeping it here? as i still think it applies to OSS also.

**Comment by kbr-scylla** [comment] 2023-08-31 08:40
> @kbr-scylla, as the one wrote the test, what do you think of this ?

Makes sense, although it would be good to understand what is this internal read that wasn't appearing before but now causes the test to fail.

**Comment by mykaul** [comment] 2023-09-03 12:26
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4209/ just failed with this as well.

**Comment by fruch** [comment] 2023-09-03 13:29
> https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4209/ just failed with this as well.

@mykaul it's the same test, but the failure is different

```
failed on teardown with "AssertionError: Core file(s) found. Marking test as failed."
```

Seems like it's part of @nyh PR, I would suggest taking a look

**Comment by nyh** [comment] 2023-09-03 13:48
@fruch it wasn't not my PR, it's @nuivall 's PR (https://github.com/scylladb/scylladb/pull/14773) which failed on a random flaky test, and now indeed I restarted the CI and now it failed on another unrelated flaky test :-(

https://github.com/scylladb/scylladb/pull/14773 suggests there is a core file, i.e., Scylla crashed. 
The crashed Scylla's log file https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4209/artifact/logs-full.release.000/1693738307881_reversed_queries_test.py%3A%3ATestOptimizedReversedQueriesFlag%3A%3Atest_optimized_reversed_queries_flag/node1.log ends with:
```
INFO  2023-09-03 10:51:46,843 [shard 0:main] init - completed re-reading configuration file
ERROR 2023-09-03 10:51:46,853 [shard 1:stat] storage_proxy - Exception when communicating with 127.0.64.1, to read from ks.t: std::runtime_error (Memory usage of reversed read exceeds hard limit of 1 (configured via max_memory_for_unlimited_query_hard_limit), while reading partition 0)
INFO  2023-09-03 10:51:46,864 [shard 0:main] init - re-reading configuration file
INFO  2023-09-03 10:51:46,865 [shard 0:main] init - completed re-reading configuration file
INFO  2023-09-03 10:51:46,878 [shard 0:main] compaction_manager - Asked to stop
WARN  2023-09-03 10:51:46,878 [shard 0:stre] gossip - failure_detector_loop: Got error in the loop, live_nodes={}: seastar::sleep_aborted (Sleep is aborted)
INFO  2023-09-03 10:51:46,878 [shard 0:stre] gossip - failure_detector_loop: Finished main loop
INFO  2023-09-03 10:51:46,878 [shard 1:main] compaction_manager - Asked to stop
INFO  2023-09-03 10:51:46,879 [shard 1:main] compaction_manager - Stopped
INFO  2023-09-03 10:51:46,879 [shard 0:main] init - Signal received; shutting down
INFO  2023-09-03 10:51:46,879 [shard 0:main] init - Shutting down view builder ops
INFO  2023-09-03 10:51:46,879 [shard 0:main] view - Draining view builder
Segmentation fault on shard 0.
Backtrace:
  0x591f618
  0x59555a6
  /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/14773/libreloc/libc.so.6+0x3db6f
  /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/14773/libreloc/libstdc++.so.6+0xb4d5b
  0x276ce4e
  0x3bf157c
  0x3b7552d
  0x3c257e7
  0x5be4306
```

decoded backtrace (@bhalevy's http://backtrace.scylladb.com/ is amazing!)
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:64
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:821
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:851
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:863
 (inlined by) seastar::sigsegv_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:4021
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4002
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3998
/data/scylla-s3-reloc.cache/by-build-id/6ea5bd2fc09dc993974511fa46edc88182b15e86/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=245240a31888ad5c11bbc55b18e02d87388f59a9, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
/data/scylla-s3-reloc.cache/by-build-id/6ea5bd2fc09dc993974511fa46edc88182b15e86/extracted/scylla/libreloc/libstdc++.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=d25eaf3596d9455fe9725f6e9cd1aa5433f31b92, stripped

std::__exception_ptr::exception_ptr::_M_addref() at ??:?
exception_ptr at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/exception_ptr.h:200
 (inlined by) seastar::internal::promise_base::set_exception(std::__exception_ptr::exception_ptr const&) at ././seastar/include/seastar/core/future.hh:819
 (inlined by) seastar::promise<void>::set_exception(std::__exception_ptr::exception_ptr const&) at ././seastar/include/seastar/core/future.hh:982
 (inlined by) seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::expiry_handler::operator()(seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::entry&) at ././seastar/include/seastar/core/semaphore.hh:179
 (inlined by) operator() at ././seastar/include/seastar/core/abortable_fifo.hh:233
seastar::internal::abortable_fifo<seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::entry, seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::expiry_handler>::make_back_abortable(seastar::abort_source&) at ././seastar/include/seastar/core/abortable_fifo.hh:239
 (inlined by) seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::wait(seastar::abort_source&, unsigned long) at ././seastar/include/seastar/core/semaphore.hh:327
seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > seastar::get_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>(seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&, unsigned long, seastar::abort_source&) at ././seastar/include/seastar/core/semaphore.hh:651
 (inlined by) gms::gossiper::lock_endpoint(gms::inet_address, utils::tagged_uuid<gms::permit_id_tag>, std::source_location) at ./gms/gossiper.cc:837
operator() at ./gms/gossiper.cc:2195
 (inlined by) void std::__invoke_impl<void, gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}>(std::__invoke_other, gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
 (inlined by) std::__invoke_result<gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}>::type std::__invoke<gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}>(std::__invoke_result&&, (gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}&&)...) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:96
 (inlined by) decltype(auto) std::__apply_impl<gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}, std::tuple<>>(gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}&&, std::tuple<>&&, std::integer_sequence<unsigned long>) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/tuple:2288
 (inlined by) decltype(auto) std::apply<gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}, std::tuple<> >(gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}&&, std::tuple<>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/tuple:2299
 (inlined by) seastar::future<void> seastar::futurize<void>::apply<gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}>(gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:1970
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:262
 (inlined by) seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}>(seastar::thread_attributes, std::invoke_result&&, (gms::gossiper::add_local_application_state(std::__cxx11::list<std::pair<gms::application_state, gms::versioned_value>, std::allocator<std::pair<gms::application_state, gms::versioned_value> > >)::$_0::operator()(gms::gossiper&)::{lambda()#1}&&)...)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././seastar/include/seastar/util/noncopyable_function.hh:129
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:215
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:311
```

This implicates (maybe) gms::gossiper::lock_endpoint. 

I'll open a new issue about it.

**Comment by mykaul** [comment] 2023-09-03 13:50
cc @bhalevy - the lock_endpoint might be related to a recent patch in this area?

**Comment by nyh** [comment] 2023-09-03 13:59
Opened a new issue - https://github.com/scylladb/scylladb/issues/15258. @bhalevy maybe related to your commit 93be4c0cb0f0c53fe0eb7cd4d06ba15a7fc01d29 (PR https://github.com/scylladb/scylladb/pull/14801)?

**Comment by bhalevy** [comment] 2023-09-03 13:59
> seastar::internal::abortable_fifo<seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::entry, seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>::expiry_handler>::make_back_abortable(seastar::abort_source&) at ././seastar/include/seastar/core/abortable_fifo.hh:239

It could be. But I suspect it's coincidental, and this is actually https://github.com/scylladb/scylladb/issues/15253
(which I may have caused by a different patch)

@nyh based on https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4209/artifact/logs-full.release.000/1693738307881_reversed_queries_test.py%3A%3ATestOptimizedReversedQueriesFlag%3A%3Atest_optimized_reversed_queries_flag/node1.log
I tried to find 9ebd50b0e43e (5.4.0~dev-0.20230903.9ebd50b0e43e)
but I couldn't find this version. I don't understand why...

**Comment by nyh** [comment] 2023-09-03 14:32
@bhalevy it's a CI run, so the commit hash points to a branch in @nuivall's repository - see https://github.com/scylladb/scylladb/commit/9ebd50b0e43ed8c5af3897a541f6c3982bc48aef. But his changes (to Alternator) seem completely orthogonal to this failure. At least I think they are.

**Comment by bhalevy** [comment] 2023-09-03 14:53
I see.  No problem.
I reproduced the stack-use-after-return locally, and I'm investigating the failure.

**Comment by fruch** [comment] 2023-09-05 21:02
happend again
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4256/testReport/junit/reversed_queries_test/TestOptimizedReversedQueriesFlag/FullDtest___full_split000___test_optimized_reversed_queries_flag/

the fix was not accurate

**Closed** 2023-09-06 04:40 UTC
