### ISSUE TITLE
Cassandra stress gets stuck long after the insertion is over

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylladb#10322] opened 2022-04-03 12:28 UTC
## Installation details

Kernel Version: 5.11.0-1028-aws

Scylla version (or git commit hash): `5.0~rc1-20220206.891990ec0` with build-id `20d9fa2c6020017f4afdc4941c0cca9c9a29d94a`

Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade-master-centos-db-node-4e9d8293-4 (52.214.40.91 | 10.0.0.117) (shards: 8)
- rolling-upgrade-master-centos-db-node-4e9d8293-3 (34.242.81.247 | 10.0.1.39) (shards: 8)
- rolling-upgrade-master-centos-db-node-4e9d8293-2 (52.212.76.31 | 10.0.3.200) (shards: 8)
- rolling-upgrade-master-centos-db-node-4e9d8293-1 (54.76.171.248 | 10.0.3.206) (shards: 8)

OS / Image: `ami-0bc914203a30cf359` (aws: eu-west-1)

Test: `rolling-upgrade-ami-test`

Test id: `4e9d8293-2faf-473b-8510-e0ecbf41e1db`

Test name: `rolling-upgrade/rolling-upgrade-ami-test`

Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1cf1a7533b0af12a4484921aa18db289b82b4f94/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

At `2022-03-26 04:10:08.323` we start a user cassandra stress thread:
`cassandra-stress user no-warmup profile=/tmp/complex_schema.yaml  ops'(insert=1)' cl=ALL n=5000000 -mode cql3 native -rate threads=1000 -pop seq=1..5000000`
Which usually lasts about 5 minutes. The stress, however, doesn't stop after all of the rows have been written, but instead the stress continues with no insert for over 2 hours:
```
total,       4943463,   19139,   19139,   19139,    53.3,    42.8,   126.9,   253.9,   334.2,   378.5,  344.0, -1.09130,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
total,       4964551,   21088,   21088,   21088,    47.8,    42.2,   103.0,   135.7,   164.0,   175.6,  345.0, -1.09188,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
total,       4984847,   20296,   20296,   20296,    48.9,    41.4,   114.8,   150.3,   185.7,   198.3,  346.0, -1.09246,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
total,       5000000,   18244,   18244,   18244,    53.9,    45.2,   125.4,   158.7,   203.4,   216.1,  346.8, -1.09303,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)

com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)

com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Results:
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Op rate                   :   14,416 op/s  [insert: 14,458 op/s]
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Partition rate            :   14,416 pk/s  [insert: 14,458 pk/s]
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Row rate                  :   14,416 row/s [insert: 14,458 row/s]
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Latency mean              :   69.1 ms [insert: 69.1 ms]
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Latency median            :   37.0 ms [insert: 37.0 ms]
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Latency 95th percentile   :  142.5 ms [insert: 142.5 ms]
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Latency 99th percentile   :  974.1 ms [insert: 974.1 ms]
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Latency 99.9th percentile : 2002.8 ms [insert: 2,002.8 ms]
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Latency max               : 9395.2 ms [insert: 9,395.2 ms]
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Total partitions          :  5,000,000 [insert: 5,000,000]
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Total errors              :          0 [insert: 0]
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Total GC count            : 0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Total GC memory           : 0.000 KiB
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Total GC time             :    0.0 seconds
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
Avg GC time               :    NaN ms
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
StdDev GC time            :    0.0 ms
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 1 acknowledged the write)
Total operation time      : 00:05:46
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)

com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
END
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 4e9d8293-2faf-473b-8510-e0ecbf41e1db`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=4e9d8293-2faf-473b-8510-e0ecbf41e1db)
- Show all stored logs command: `$ hydra investigate show-logs 4e9d8293-2faf-473b-8510-e0ecbf41e1db`

## Logs:
- **db-cluster-4e9d8293.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4e9d8293-2faf-473b-8510-e0ecbf41e1db/20220326_095157/db-cluster-4e9d8293.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4e9d8293-2faf-473b-8510-e0ecbf41e1db/20220326_095157/db-cluster-4e9d8293.tar.gz)
- **monitor-set-4e9d8293.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4e9d8293-2faf-473b-8510-e0ecbf41e1db/20220326_095157/monitor-set-4e9d8293.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4e9d8293-2faf-473b-8510-e0ecbf41e1db/20220326_095157/monitor-set-4e9d8293.tar.gz)
- **loader-set-4e9d8293.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4e9d8293-2faf-473b-8510-e0ecbf41e1db/20220326_095157/loader-set-4e9d8293.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4e9d8293-2faf-473b-8510-e0ecbf41e1db/20220326_095157/loader-set-4e9d8293.tar.gz)
- **sct-runner-4e9d8293.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4e9d8293-2faf-473b-8510-e0ecbf41e1db/20220326_095157/sct-runner-4e9d8293.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4e9d8293-2faf-473b-8510-e0ecbf41e1db/20220326_095157/sct-runner-4e9d8293.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/91/)
Created from https://github.com/scylladb/scylla-cluster-tests/issues/4552

**Comment by slivne** [comment] 2022-04-13 21:44
I expect this is a bug in cassandra-stress or in the driver.

We are supposed to shutdown when the load ends and we don't

@avelanarius assigning this to you - you can get someone from your team to check.

- Please note I was not able to reproduce this on a single machine, so you may need a cluster.
- QA are also maybe running a version they settled on so it may not be the exact same thing as the one in the release

**Comment by ShlomiBalalis** [comment] 2022-04-27 09:29
The issue happened again in the rolling upgrade ami test of master:

## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `5.0~rc3-20220406.f92622e0d` with build-id `2b79c4744216b294fdbd2f277940044c899156ea`
Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade-master-centos-db-node-000670ad-4 (34.251.74.54 | 10.0.1.236) (shards: 8)
- rolling-upgrade-master-centos-db-node-000670ad-3 (34.241.87.65 | 10.0.1.219) (shards: 8)
- rolling-upgrade-master-centos-db-node-000670ad-2 (34.244.60.151 | 10.0.1.56) (shards: 8)
- rolling-upgrade-master-centos-db-node-000670ad-1 (54.155.85.71 | 10.0.1.130) (shards: 8)


OS / Image: `ami-07835983d717b1ea3` (aws: eu-west-1)

Test: `rolling-upgrade-ami-test`
Test id: `000670ad-44dd-4e7d-bcf9-7c4bca0ace2e`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f485155a9f8b359c8e8da8d07cd3d4396aa5ca27/test-cases/upgrades/rolling-upgrade.yaml)

Name of the stuck stress' log: cassandra-stress-l0-c0-k1-fbaa488c-46d4-45ac-b903-0992f9265b12.log

- Restore Monitor Stack command: `$ hydra investigate show-monitor 000670ad-44dd-4e7d-bcf9-7c4bca0ace2e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=000670ad-44dd-4e7d-bcf9-7c4bca0ace2e)
- Show all stored logs command: `$ hydra investigate show-logs 000670ad-44dd-4e7d-bcf9-7c4bca0ace2e`

## Logs:
- **db-cluster-000670ad.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/000670ad-44dd-4e7d-bcf9-7c4bca0ace2e/20220423_095511/db-cluster-000670ad.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/000670ad-44dd-4e7d-bcf9-7c4bca0ace2e/20220423_095511/db-cluster-000670ad.tar.gz)
- **monitor-set-000670ad.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/000670ad-44dd-4e7d-bcf9-7c4bca0ace2e/20220423_095511/monitor-set-000670ad.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/000670ad-44dd-4e7d-bcf9-7c4bca0ace2e/20220423_095511/monitor-set-000670ad.tar.gz)
- **loader-set-000670ad.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/000670ad-44dd-4e7d-bcf9-7c4bca0ace2e/20220423_095511/loader-set-000670ad.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/000670ad-44dd-4e7d-bcf9-7c4bca0ace2e/20220423_095511/loader-set-000670ad.tar.gz)
- **sct-runner-000670ad.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/000670ad-44dd-4e7d-bcf9-7c4bca0ace2e/20220423_095511/sct-runner-000670ad.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/000670ad-44dd-4e7d-bcf9-7c4bca0ace2e/20220423_095511/sct-runner-000670ad.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/95/)

**Comment by rayakurl** [comment] 2022-05-10 15:29
@avelanarius , @Lorak-mmk  - any progress with this issue? It's a high frequency one

**Comment by fgelcer** [comment] 2022-05-15 18:49
i'm seeing such issue on `longevity-200gb-48h-network-monkey-test`

found that c-s prepare command ran for 13 hours (instead of 1.5 hours), and while analyzing it, the c-s command returned the `Results`, but the command stayed stuck printing the following message ~95K times:
```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
``` 

it happened on `5.0~rc3-20220406.f92622e0d with build-id 2b79c4744216b294fdbd2f277940044c899156ea`

here test details, and logs:


## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `5.0~rc3-20220406.f92622e0d` with build-id `2b79c4744216b294fdbd2f277940044c899156ea`
Cluster size: 6 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-200gb-48h-network-5-0-db-node-2a818039-6 (54.247.117.7 | 10.0.0.121) (shards: 8)
- longevity-200gb-48h-network-5-0-db-node-2a818039-5 (54.72.211.175 | 10.0.1.91) (shards: 8)
- longevity-200gb-48h-network-5-0-db-node-2a818039-4 (108.128.235.226 | 10.0.3.3) (shards: 8)
- longevity-200gb-48h-network-5-0-db-node-2a818039-3 (3.248.133.197 | 10.0.1.222) (shards: 8)
- longevity-200gb-48h-network-5-0-db-node-2a818039-2 (79.125.29.61 | 10.0.0.247) (shards: 8)
- longevity-200gb-48h-network-5-0-db-node-2a818039-1 (3.248.131.203 | 10.0.0.158) (shards: 8)


OS / Image: `ami-07835983d717b1ea3` (aws: eu-west-1)

Test: `longevity-200gb-48h-network-monkey-test`
Test id: `2a818039-b3db-4c5f-8fc0-e2da48cea703`
Test name: `scylla-5.0/longevity/longevity-200gb-48h-network-monkey-test`
Test config file(s):

- [longevity-200GB-48h-network-monkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/70e5a5df08201ec695a1f993c37e1421b690f169/test-cases/longevity/longevity-200GB-48h-network-monkey.yaml)


- Restore Monitor Stack command: `$ hydra investigate show-monitor 2a818039-b3db-4c5f-8fc0-e2da48cea703`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2a818039-b3db-4c5f-8fc0-e2da48cea703)
- Show all stored logs command: `$ hydra investigate show-logs 2a818039-b3db-4c5f-8fc0-e2da48cea703`

## Logs:
- **db-cluster-2a818039.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2a818039-b3db-4c5f-8fc0-e2da48cea703/20220428_134333/db-cluster-2a818039.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a818039-b3db-4c5f-8fc0-e2da48cea703/20220428_134333/db-cluster-2a818039.tar.gz)
- **monitor-set-2a818039.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2a818039-b3db-4c5f-8fc0-e2da48cea703/20220428_134333/monitor-set-2a818039.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a818039-b3db-4c5f-8fc0-e2da48cea703/20220428_134333/monitor-set-2a818039.tar.gz)
- **loader-set-2a818039.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2a818039-b3db-4c5f-8fc0-e2da48cea703/20220428_134333/loader-set-2a818039.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a818039-b3db-4c5f-8fc0-e2da48cea703/20220428_134333/loader-set-2a818039.tar.gz)
- **sct-runner-2a818039.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2a818039-b3db-4c5f-8fc0-e2da48cea703/20220428_134333/sct-runner-2a818039.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a818039-b3db-4c5f-8fc0-e2da48cea703/20220428_134333/sct-runner-2a818039.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-200gb-48h-network-monkey-test/2/)

**Comment by avelanarius** [comment] 2022-05-15 19:23
A quick update: @Lorak-mmk looked into this issue last week. In all those cases (including `longevity-200gb-48h-network-monkey-test` just posted), cassandra-stress prints `END`, which looking at the code means that all cassandra-stress workers have finished work and the Java Driver session should be closed. However, for some reason the driver still tries to execute some queries generating those exceptions:

```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
```

We don't know yet who makes those queries and we were not able to reproduce the problem. If we don't have any breakthrough soon, we'll probably have to do live debugging (wait for the issue to appear once again, login to the loader machine and do debugging there).

**Comment by Lorak-mmk** [comment] 2022-06-01 12:40
Turns out that cassandra-stress doesn't actually get stuck, it terminates correctly. The issue is, that it prints a lot of errors, a few dozen per second, to stderr, but sct python script only writes a few per second to log file - you can see that status lines are separated by just a few of error lines - and cassandra-stress only prints one status line per few seconds.
So the problem is actually in scylla-cluster-tests python scripts that stream output from loader to file on runner - for some reason they stream stderr very slow, so it keeps writing logs for a few hours after cassandra-stress terminates.

It would be nice if someone who knows scylla-cluster-tests codebase took a look at it and tried to fix this - I'm not at all familiar with it.

**Comment by Lorak-mmk** [comment] 2022-06-15 11:28
I'm going to put all of my findings here as I'm going for unpaid leave until October.

CS getting "stuck" is most likely caused by StreamWatcher from Python Invoke library (used by Fabric library used by SCT) not only having really bad API, but also implementing in in a very inefficient way. This causes stderr streaming to take a lot of hours, as I noted in the previous comment.

StreamWatcher allows Fabrics/Invokes user to process output of the program while it is running (and also send input to it, but that's not important). To do that user creates class that derives from StreamWatcher, and passes an instance of this class to Invoke. The API user has to implement is pretty simple - https://docs.pyinvoke.org/en/stable/api/watchers.html#invoke.watchers.StreamWatcher - it consists of one method, `submit`, which accepts ENTIRE output generated by program up to this point. This means the library has to hold whole output in memory, which is problematic if program generated a lot of output, as noticed by @fruch - https://github.com/pyinvoke/invoke/issues/615#issuecomment-480562542 .
Implementation of this API is also not so good. Invoke doesn't store output as a string/bytes - but rather as a list of strings.
Every time it reads something from output it appends it to that list: https://github.com/pyinvoke/invoke/blob/267182beae2f1877b2c2e6f16f5cbdf21e226b59/invoke/runners.py#L721
Problem is, StreamWatcher expects a string - so after every read it joins all those strings into a big one, and passes it to the watcher: https://github.com/pyinvoke/invoke/blob/267182beae2f1877b2c2e6f16f5cbdf21e226b59/invoke/runners.py#L911
So for every read, the library needs to allocatge buffer of the size of whole output, copy the whole output there, and after watcher processes it - discards the whole thing. Why? I have no idea.

One possible fix (apart from changing Invoke's API and it's implementation) is to use libssh2 backend, which doesn't seem to suffer from those problems. If I understand SCT correctly, it should be enough to add `ssh_transport: 'libssh2'` to this test's yaml file. Maybe it's worth considering doing that in other tests too - to prevent the issue from happening somewhere else.

Another orthogonal aspect of this issue is why are those errors even there in the first place - as they are not happening in every run. The answer is I have no idea. We (@avelanarius and I) looked trough metrics of good and bad runs, but didn't see any obvious issues. Comparing metrics is not that easy here, as the runs often look totally different to each other (some use MVs and repairs, some don't. Load in time is also totally different). I suspect it's due to the use of gemini which randomizes operations it performs, making the test pretty unpredictable.
 What we managed to find out is that the issue happens before rolling upgrade even begins - but that's all :<

**Comment by fruch** [comment] 2022-06-15 12:43
@Lorak-mmk SCT defaults to  `ssh_transport: libssh2` for a while now. but non of this fabric/ssh explain why we are having those storm of failures ?

**Comment by roydahan** [comment] 2022-06-20 22:29
I don't think this issue still happens in rolling-upgrade-ami-test.
We will run again the longevity-200gb-network with later RC and report back.

**Comment by fgelcer** [comment] 2022-07-26 19:43
i'm seeing this same issue with longevity-3h-gce on `2022.1.rc9-0.20220721.9c95c3a8c with build-id fa046ed1198afeb5070da0003ce35a4560faa15f` (using the new GCE project):


## Installation details

Kernel Version: 5.15.0-1013-gcp
Scylla version (or git commit hash): `2022.1~rc9-20220721.9c95c3a8c` with build-id `fa046ed1198afeb5070da0003ce35a4560faa15f`
Cluster size: 6 nodes (n1-highmem-16)

Scylla Nodes used in this run:
- longevity-10gb-3h-2022-1-db-node-fe55d650-0-9 (35.196.204.234 | 10.142.0.18) (shards: 16)
- longevity-10gb-3h-2022-1-db-node-fe55d650-0-8 (34.75.180.133 | 10.142.0.23) (shards: 16)
- longevity-10gb-3h-2022-1-db-node-fe55d650-0-7 (104.196.195.69 | 10.142.0.21) (shards: 16)
- longevity-10gb-3h-2022-1-db-node-fe55d650-0-6 (34.139.108.37 | 10.142.0.9) (shards: 16)
- longevity-10gb-3h-2022-1-db-node-fe55d650-0-5 (35.237.196.135 | 10.142.0.8) (shards: 16)
- longevity-10gb-3h-2022-1-db-node-fe55d650-0-4 (34.74.162.174 | 10.142.0.7) (shards: 16)
- longevity-10gb-3h-2022-1-db-node-fe55d650-0-3 (34.139.194.246 | 10.142.0.6) (shards: 16)
- longevity-10gb-3h-2022-1-db-node-fe55d650-0-2 (34.138.165.46 | 10.142.0.5) (shards: 16)
- longevity-10gb-3h-2022-1-db-node-fe55d650-0-1 (34.148.52.172 | 10.142.0.4) (shards: 16)


OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/1950566603300258993` (gce: us-east1)

Test: `longevity-10gb-3h-gce-test`
Test id: `fe55d650-f894-4b67-b3e5-45ace4b88ff5`
Test name: `enterprise-2022.1/longevity/longevity-10gb-3h-gce-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/457608877c20652e072cdcf705d79da3bbd88990/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description

**>>>>>>>**

c-s command is set to run 180m:
```
stress_cmd=cassandra-stress write cl=QUORUM duration=180m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=1000 -pop seq=1..10000000 -log interval=5
```

but the command really ends only after 4h25min:
```
2022-07-25 20:50:03.524: (CassandraStressEvent Severity.NORMAL) period_type=begin event_id=64219be0-df83-45b4-9cc3-017d686bbfb2: node=Node longevity-10gb-3h-2022-1-loader-node-fe55d650-0-1 [34.74.22.254 | 10.142.0.15] (seed: False)
2022-07-25 20:50:04.630: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=64219be0-df83-45b4-9cc3-017d686bbfb2: type=ShardAwareDriver regex=Using optimized driver line_number=95 node=Node longevity-10gb-3h-2022-1-loader-node-fe55d650-0-1 [34.74.22.254 | 10.142.0.15] (seed: False)
2022-07-25 20:50:33.464: (CassandraStressEvent Severity.NORMAL) period_type=begin event_id=4dfdb09b-5e9b-4dbe-a0fa-1ca0363e2155: node=Node longevity-10gb-3h-2022-1-loader-node-fe55d650-0-2 [35.227.76.198 | 10.142.0.16] (seed: False)
2022-07-25 20:50:34.467: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=4dfdb09b-5e9b-4dbe-a0fa-1ca0363e2155: type=ShardAwareDriver regex=Using optimized driver line_number=95 node=Node longevity-10gb-3h-2022-1-loader-node-fe55d650-0-2 [35.227.76.198 | 10.142.0.16] (seed: False)
2022-07-26 01:15:03.702: (CassandraStressEvent Severity.NORMAL) period_type=end event_id=64219be0-df83-45b4-9cc3-017d686bbfb2 duration=4h25m0s: node=Node longevity-10gb-3h-2022-1-loader-node-fe55d650-0-1 [34.74.22.254 | 10.142.0.15] (seed: False)
2022-07-26 01:15:33.798: (CassandraStressEvent Severity.NORMAL) period_type=end event_id=4dfdb09b-5e9b-4dbe-a0fa-1ca0363e2155 duration=4h25m0s: node=Node longevity-10gb-3h-2022-1-loader-node-fe55d650-0-2 [35.227.76.198 | 10.142.0.16] (seed: False)
```

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor fe55d650-f894-4b67-b3e5-45ace4b88ff5`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=fe55d650-f894-4b67-b3e5-45ace4b88ff5)
- Show all stored logs command: `$ hydra investigate show-logs fe55d650-f894-4b67-b3e5-45ace4b88ff5`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/longevity/job/longevity-10gb-3h-gce-test/21/)

**Comment by roydahan** [comment] 2024-05-08 00:33
dup of https://github.com/scylladb/java-driver/issues/258

**Closed by roydahan** 2024-05-08 00:33 UTC
Labels: type/bug
