### ISSUE TITLE
scylla sstable should be able to work on sstables that have some or all components on object storage

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#20585] opened 2024-09-13 11:01 UTC
Noe that we have a native S3 stack, sstables storage can be in an s3 bucket.
Currently all components would be stored either locally or on s3, but in the future, with tiering,
some components may be stored locally while some components (like Data and/or Index) may be stored on s3.

Cc @regevran @denesb

**Comment by bhalevy** [comment] 2024-09-13 11:04
We would probably need this with https://github.com/scylladb/scylladb/issues/20459, if backup deduplication would be done externally by examining the sstables on snapshot vs. the sstables on object storage (unless we name the sstables on backup using the **original** uuid generation and not using the current uuid generation that might be different after intra-node (cross-shards, in the same node) migration.

**Comment by denesb** [comment] 2024-09-13 11:04
Duplicate of https://github.com/scylladb/scylladb/issues/20532.

**Closed** 2024-09-13 12:07 UTC
Labels: area/scylla tools
