### ISSUE TITLE
Read timeout should be enforced on the replica side

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#2927] opened 2017-11-02 07:59 UTC
Currently replica-side reads don't time out, reads only time out on coordinator side. If a read takes more than a timeout, and clients retry, reads may keep accumulating on replica side, making overload worse than it should be. We should propagate the timeout and expire reads, like we do for writes.

**Comment by gleb-cloudius** [comment] 2017-11-02 10:19
To make the scope more clear we already propagate timeout values to
replica side all is left is a hard part to actually honor the timeout 
in databse::query().

--
			Gleb.

**Comment by glommer** [comment] 2018-04-28 16:27
@tgrabiec  isn't this is handled by the per-request timeout patchset ? Am I missing something ?

**Comment by tgrabiec** [comment] 2018-04-29 17:26
@glommer The work which has already been implemented for this will expire reads on replica side if they are blocked on sstable read concurrency limiter. They still won't expire after admitted.

**Comment by gleb-cloudius** [comment] 2018-04-30 07:18
On Sun, Apr 29, 2018 at 10:26:28AM -0700, Tomasz Grabiec wrote:
> @glommer The work which has already been implemented for this will expire reads on replica side if they are blocked on sstable read concurrency limiter. They still won't expire after admitted.
> 
What expiration points do we still have that do not honor the timeout?

--
			Gleb.

**Comment by tgrabiec** [comment] 2018-04-30 07:32
What do you mean by "expiration point"? Actual reading from sstables doesn't respect the timeout.

**Comment by gleb-cloudius** [comment] 2018-04-30 07:38
On Mon, Apr 30, 2018 at 12:32:21AM -0700, Tomasz Grabiec wrote:
> What do you mean by "expiration point"? Actual reading from sstables doesn't respect the timeout. 
> 
I mean points where a read can stuck without timeout. What is "actual
reading"? A read submitted to IO queue?  Actually sstable read may
require more than one IO, right? So the code that tracks how long the
overall process takes is missing?

--
			Gleb.

**Comment by tgrabiec** [comment] 2018-04-30 07:42
2018-04-30 9:38 GMT+02:00 Gleb Natapov <notifications@github.com>:

> On Mon, Apr 30, 2018 at 12:32:21AM -0700, Tomasz Grabiec wrote:
> > What do you mean by "expiration point"? Actual reading from sstables
> doesn't respect the timeout.
> >
> I mean points where a read can stuck without timeout. What is "actual
> reading"? A read submitted to IO queue? Actually sstable read may
> require more than one IO, right? So the code that tracks how long the
> overall process takes is missing?


Yes, a read may do many IOs, on many files. Some of them in parallel, some
of them sequentually. We will not timeout at any point once the read is
admitted to start reading from sstables, past the concurrency limiting
queue.

**Comment by tgrabiec** [comment] 2019-04-10 12:53
We also saw reads queueing inside the `data_query_stage` execution stage when CPU is overloaded. That queue doesn't timeout.

**Comment by avikivity** [comment] 2020-04-23 09:52
We could wrap `file` with something that times out after a certain point. But it wouldn't play well with #1865 caches.

I don't think this can help much. At any point in time, most reads in a loaded system are queued, not running, so this will affect only a small number of queries.

**Comment by denesb** [comment] 2020-04-30 18:37
I think a better way would be setting a timer in the same layer that is doing the querier caching, then pass down a cancellation handle all the way down to seastar I/O. The timer, when triggered, cancels the read, including all outstanding I/O requests. If the page was filled and the reader is saved we kill the timer.

**Comment by eliransin** [comment] 2020-10-08 10:16
There is some more discussion about this on the duplicate issue on #7340 (which I'm going to close as a duplicate) , the highlights of it is:
1. We will need  I/O cancellation support in (seasrar scylladb/seastar/#811) 
2. It can create a live lock where reads accumulate to such a long queue (on the read concurrency semaphore) that all of the
reads will become stale at the moment of execution.

**Comment by eliransin** [comment] 2020-10-08 10:18
@vladzcloudius FYI

**Comment by vladzcloudius** [comment] 2020-10-17 14:13
@amihayday @slivne @denesb @eliransin @eyalgutkind 
Please, let's give it the highers priority: this issue is hurting us a lot all over the place.

**Comment by vladzcloudius** [comment] 2020-11-03 16:42
> @amihayday @slivne @denesb @eliransin @eyalgutkind
> Please, let's give it the highers priority: this issue is hurting us a lot all over the place.

@eliransin @slivne ping

**Comment by slivne** [comment] 2021-02-24 21:57
@bhalevy the work you and @xemul are doing will cover this - right ?

**Comment by bhalevy** [comment] 2021-02-25 11:58
@slivne no, not yet.

**Comment by slivne** [comment] 2021-02-25 12:25
I'll rephrase

I know that we are not done - in the sense that you still have some patches - but what I meant as following your changes - will this be closed or are we missing something in addition to that.

**Comment by bhalevy** [comment] 2021-02-25 14:55
> I'll rephrase
> 
> I know that we are not done - in the sense that you still have some patches - but what I meant as following your changes - will this be closed or are we missing something in addition to that.

I was under the assumption that timeouts were not conveyed to the replica side but apparently they are (https://github.com/scylladb/scylla/issues/2927#issuecomment-341376890), and all was left was to actually honor them.
Said that, Pavel's fix for https://github.com/scylladb/seastar/issues/859, with my project to close flat_mutation_reader:s will do that and it indeed seems like there's nothing more missing.

@denesb, @tgrabiec please confirm.

**Comment by denesb** [comment] 2021-02-25 15:04
I didn't see the code in your close series which actually takes action when a reader is timed out. Your series lays the groundwork for doing so, yes, but is not enough on its own.
We will still need to glue all this together. Set up a timeout timer and when this timer fires we cancel all I/O and propagate up an exception terminating any in-progress operation on the reader, after which we close and destroy them.

**Comment by avikivity** [comment] 2021-02-25 16:29
Well, the timeouts on r_c_s should already work, no? As well as the timeout parameter propagated to in-progress queries?

**Comment by denesb** [comment] 2021-02-25 17:42
The timeout on the r_c_s does already work, but after passing the semaphore
we hav no timeout at all effectively.

**Comment by denesb** [comment] 2021-08-10 14:38
This issue should be renamed to: read timeout should be enforced on replica side.
We already propagate read timeouts to the replica, for a long time now. The problem is with enforcing it. We have recently made some progress on this: since 3d816b7c1 all reads wait on admission before starting to read, so we should have at most one concurrent pure cache read  at a time. This means that we can't have a huge number of in-progress cache reads that are already timed out but will still finish anymore. @bhalevy worked on checking the timeout in the sstable reader too (I can't find that commit now), was that merged?
We still need a unified timeout which is able to kill the read no matter in what state it is in, but coverage has improved.

**Comment by bhalevy** [comment] 2021-08-10 14:53
> @bhalevy worked on checking the timeout in the sstable reader too (I can't find that commit now), was that merged?

https://github.com/scylladb/scylla/commit/9bbe7b14823c1ca48e6659014f7edc235b3df10a is in 4.6

**Comment by bhalevy** [comment] 2021-08-11 14:25
@avikivity I prepared a branch with the patches relevant for timeout for backporting to 4.5
(except for moving the r_c_s in front of the cache (3d816b7) that should be done by @denesb)
in https://github.com/bhalevy/scylla/commits/reader-timeout-backport-4.5-v1

I can work on backporting to 4.3 and 4.4 too, it's not trivial, but shouldn't be too hard.

**Comment by dorlaor** [comment] 2021-08-16 13:52
@bhalevy was the entire code merged upstream?
Discord needs it, I am not sure what version they use for it - @fee-mendes do you know?
Let's backport to it

**Comment by bhalevy** [comment] 2021-08-23 06:00
> @bhalevy was the entire code merged upstream?

@dorlaor yes, it's all in master.

**Comment by PeterCorless** [comment] 2022-01-04 22:54
4.5 is out (and we're already working on 4.6). Is this still open, @bhalevy ?

**Comment by bhalevy** [comment] 2022-01-05 13:09
@PeterCorless the branch I prepared for backport mentioned in  https://github.com/scylladb/scylla/issues/2927#issuecomment-896872517 was not merged to 4.5.  ping @avikivity 

Regarding keeping this issue open, the decision should be based on the state in master.
@tgrabiec is there anything else you think should be done to close this issue?

**Comment by DoronArazii** [comment] 2022-04-24 08:55
@tgrabiec can you please refer to last [comment](https://github.com/scylladb/scylla/issues/2927#issuecomment-1005671561) by @bhalevy ?

**Comment by tgrabiec** [comment] 2022-06-22 16:06
I think we still don't time-out individual IO operations, right? @xemul @bhalevy

**Comment by tgrabiec** [comment] 2022-06-22 18:05
IO cancelation on close() is not enough if we defer close() until IO completes. The question is whether we cancel active IOs based on query timeout.

**Comment by denesb** [comment] 2022-06-23 05:20
I don't think we do that, not even on master, I don't remember seeing patches adding this to reads.

**Comment by bhalevy** [comment] 2022-06-23 06:25
See @xemul's patch: scylladb/seastar@66b4c6acfdf0fa72d2397830f5306de7c41eaa64
that cancels the outstanding read requests when the file_data_source_impl (that's used in make_file_input_stream) is closed.

**Comment by bhalevy** [comment] 2022-06-23 06:31
and then acf8da2bcef47168376e876e2fdc37fc26ebc82e changed the flat_mutation_reader timeout mechanism to use a timeout in the reader permit.  It doesn't cancel the outstanding IOs directly, but rather triggers a timeout error from the reader that should lead to closing it - and that cancels the outstanding I/Os as mentioned above.

**Comment by bhalevy** [comment] 2022-07-06 08:08
> @bhalevy so whats left to complete this ?

Nothing as far as I'm aware of.
@tgrabiec @denesb please confirm.

**Comment by bhalevy** [comment] 2022-07-07 15:31
> @bhalevy Could you point me to the place in code which is now responsible for triggering the close?

It starts with an exception thrown in `flat_mutation_reader_v2::maybe_timed_out` called by the mx sstable reader `fill_buffer` implementation. That should propagate on the error path which will eventually cause the reader(s) to be closed.

**Comment by bhalevy** [comment] 2022-07-08 07:39
> So we timeout only between consume_input(), reading triggered by consume_input() is not timing out?

No, consume_input itself doesn't consider the timeout.
Do we need to apply the timeout in that fine resolution?

**Comment by tgrabiec** [comment] 2022-07-11 15:14
Why not?

**Comment by avikivity** [comment] 2022-09-06 15:41
Timeouts are coarse controls. If the timeout is 30ms and you time out after 33ms, the extra work done isn't a deal breaker. 

If you spend more effort enforcing timeouts at a fine granularity than you save from not doing the extra work, you come out at a loss.

The expectation is that most queries will complete before the timeout expires, some will timeout before their execution starts (esp with 3d816b7c16fd0e311a80bc0fcae098e6e15b406f), and only a tiny fraction will be timed out during execution. It's not worth slowing everything down for the latter case.

ps. your question did not time out.

**Comment by bhalevy** [comment] 2022-09-06 18:13
As per https://github.com/scylladb/scylla-enterprise/issues/1808#issuecomment-1238310837, closing this issue since it's too broad, in favor of #11469 that tracks the remaining work.

**Closed by bhalevy** 2022-09-06 18:13 UTC
Labels: bug, stability, Field-Tier1, overload
