### ISSUE TITLE
alternator: test_item_latency is flaky

### ISSUE THREAD

**Issue by nuivall** [scylladb/scylladb#18847] opened 2024-05-23 09:15 UTC
```
test_table_s = dynamodb.Table(name='alternator_Test_1716375329548')
metrics = 'http://127.249.147.1:9180/metrics'

    def test_item_latency(test_table_s, metrics):
>       with check_sets_latency(metrics, ['DeleteItem', 'GetItem', 'PutItem', 'UpdateItem']):

test/alternator/test_metrics.py:235: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.11/contextlib.py:144: in __exit__
    next(self.gen)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

metrics = 'http://127.249.147.1:9180/metrics'
operation_names = ['DeleteItem', 'GetItem', 'PutItem', 'UpdateItem']

    @contextmanager
    def check_sets_latency(metrics, operation_names):
        the_metrics = get_metrics(metrics)
        saved_latency_count = { x: get_metric(metrics, 'scylla_alternator_op_latency_count', {'op': x}, the_metrics) for x in operation_names }
        saved_latency_sum = { x: get_metric(metrics, 'scylla_alternator_op_latency_sum', {'op': x}, the_metrics) for x in operation_names }
        # TODO: Also look at the latency_bucket.
        yield
        the_metrics = get_metrics(metrics)
        for op in operation_names:
            # The total "count" and "sum" on all shards should strictly increase
            assert saved_latency_count[op] < get_metric(metrics, 'scylla_alternator_op_latency_count', {'op': op}, the_metrics)
>           assert saved_latency_sum[op] < get_metric(metrics, 'scylla_alternator_op_latency_sum', {'op': op}, the_metrics)
E           assert 175340000.0 < 175340000.0
E            +  where 175340000.0 = get_metric('http://127.249.147.1:9180/metrics', 'scylla_alternator_op_latency_sum', {'op': 'UpdateItem'}, '# HELP scylla_alien_receive_batch_queue_length Current receive batch queue length\n# TYPE scylla_alien_receive_batch_..._sstables_to_move_count{shard="0"} 0.000000\nscylla_view_update_generator_sstables_to_move_count{shard="1"} 0.000000\n')

test/alternator/test_metrics.py:230: AssertionError
```

logs: 
- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9060/testReport/junit/(root)/test_metrics/test_item_latency_208/
- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9060/testReport/junit/(root)/non-boost%20tests/alternator_test_metrics_debug_3/

happened in PRs:
https://github.com/scylladb/scylladb/pull/17799
https://github.com/scylladb/scylladb/pull/18769

**Comment by nuivall** [comment] 2024-05-23 09:18
seems like around 4% of runs fails

**Comment by kbr-scylla** [comment] 2024-05-23 12:17
Without assigning the issue or at least adding triage/ label, nobody will ever look at it.
(You're lucky that I like clicking on links that appear on GH. I'll assign to @nyh )

**Comment by nyh** [comment] 2024-05-26 10:57
I'm looking into this right now. So far I couldn't reproduce this problem in my own dev-mode runs (even after running 1000 times), maybe it depends on the slowness of a debug build (I see the failures were only on debug builds). I'm continuing to investigate. Note that it's a relatively new test, introduced in d207962e40cdf8fa977941e5a7afb5c7353d3138.

**Comment by nyh** [comment] 2024-05-26 11:46
What this test does is to run an operation (each one in DeleteItem, GetItem, PutItem, UpdateItem) and then immediately check that the latency metrics for all of them were updated. All four of these operations end with code that looks like:
```
future<executor::request_return_type> executor::put_item(client_state& client_state, tracing::trace_state_ptr trace_state, service_permit permit, rjson::value request) {
    ...
    return op->execute(_proxy, client_state, trace_state, std::move(permit), needs_read_before_write, _stats).finally([op, start_time, this] {
        _stats.api_operations.put_item_latency.mark(std::chrono::steady_clock::now() - start_time);
    });
```
In other words, the operation's future only ends **after** the put_item_latency object is incremented, so if the test waits, like it does, for the PutItem to return and only then fetches the metrics, everything should be correct.

But the failure gives us a hint what went wrong:
```
assert saved_latency_count[op] < get_metric(metrics, 'scylla_alternator_op_latency_count', {'op': op}, the_metrics)
>           assert saved_latency_sum[op] < get_metric(metrics, 'scylla_alternator_op_latency_sum', {'op': op}, the_metrics)
```

Note how the `latency_count` metric **did** get incremented, just `latency_sum` didn't. So we're sure that the mark() function was correctly called, but incremented the counter - but not the sum. Why?

I can think of two possible bugs: 
1. the `utils::timed_rate_moving_average_summary_and_histogram::mark()` method incremented scylla_alternator_op_latency_count but did not increment scylla_alternator_op_latency_sum at all, or didn't increment it immediately. The code of the metrics is so convoluted that I can't even figure what `scylla_alternator_op_latency_sum` actually returns and who returns it. @amnonh maybe you can remind me before I continue digging?
2. Maybe somehow in debug mode we have bug where `std::chrono::steady_clock::now() ` (used to calculate the time for this sum) somehow didn't increase. We recently had a bug in the lowres clock in debug mode (https://github.com/scylladb/seastar/issues/2238) but I don't think steady_clock can have this bug.
3. timed_rate_moving_average_summary_and_histogram.mark() 

(timed_rate_moving_average::mark() calls rates_moving_average::mark() 
 assert saved_latency_count[op] < get_metric(metrics, 'scylla_alternator_op_latency_count', {'op': op}, the_metrics)
>           assert saved_latency_sum[op]

**Comment by nyh** [comment] 2024-06-02 20:10
If I understand correctly, `scylla_alternator_op_latency_sum` comes from 
```c++
seastar::metrics::make_histogram("op_latency", \
seastar::metrics::description("Latency histogram of an operation via Alternator API"), {op(CamelCaseName)}, [this]{return to_metrics_histogram(api_operations.name.histogram());}).aggregate({seastar::metrics::shard_label}).set_skip_when_empty(), 
```
in alternator/stats.cc.

As far as I can tell, to_metrics_histogram() from utils/histogram_metrics_helper.hh, is the function used by the code above to generate the sum.  It apparently uses some "sampling" stuff which I don't understand to calculate the sum. @amnonh can you please help me figure out how a "sum" of such a histogram is calculated and if there might be a way that a non-zero increment still leaves sum zero?

In particular, might it be possible that a low-enough latency, but **not** zero, leave sum unincremented? How low can it be to happen?

But I don't have any idea how, even if the above guess is possible, the zero-change-to-sum happens only in the debug build. That doesn't make sense - in the debug build the latencies would be higher, not closer to zero. Maybe the histogram is "adaptive" in some way so if a lot of latencies are high, then even a not-so-low latency might be considered zero?

Unfortunately, I'm fresh out of ideas, so I need some help.

**Comment by amnonh** [comment] 2024-06-02 20:49
I'll try to address all questions:
1. Though the histogram can theoretically use sampling, it doesn't (or is not supposed to); a histogram is a collection of ever-growing counters. It's best to check the Prometheus side; it should show the buckets, and the buckets should be ever-growing.
2. In addition to the histograms, there are summaries. Summaries are created by calculating the P50, P95, and P99 quantiles of the histogram's rate, which could get a zero if the rate is low.

**Comment by nyh** [comment] 2024-06-03 07:49
> I'll try to address all questions:
> 
>     1. Though the histogram can theoretically use sampling, it doesn't (or is not supposed to); a histogram is a collection of ever-growing counters. It's best to check the Prometheus side; it should show the buckets, and the buckets should be ever-growing.

My difficulty is that I wasn't yet able to reproduce this failure :-(

So you are saying that no matter what is the current values stored by a histograms, storing any new value, no matter how tiny (except exactly zero), is guaranteed to increment the "count" by one and the "sum" by something non-zero?


>     2. In addition to the histograms, there are summaries. Summaries are created by calculating the P50, P95, and P99 quantiles of the histogram's rate, which could get a zero if the rate is low.

Am I correct that scylla_alternator_op_latency_sum metric (see code above defining it above) comes from a "histogram", not a "summary"?

**Comment by amnonh** [comment] 2024-06-03 13:26
> > I'll try to address all questions:
> > ```
> > 1. Though the histogram can theoretically use sampling, it doesn't (or is not supposed to); a histogram is a collection of ever-growing counters. It's best to check the Prometheus side; it should show the buckets, and the buckets should be ever-growing.
> > ```
> 
> My difficulty is that I wasn't yet able to reproduce this failure :-(
> 
> So you are saying that no matter what is the current values stored by a histograms, storing any new value, no matter how tiny (except exactly zero), is guaranteed to increment the "count" by one and the "sum" by something non-zero?
> 

Yes, value size is irrelevant; the size will only determine the bucket, and the underlying counters are integers.
And the total counter will always grow by one.
Unless of course there's a bug somewhere (which I expect we would hit by now, but you can never really know) 

> > ```
> > 2. In addition to the histograms, there are summaries. Summaries are created by calculating the P50, P95, and P99 quantiles of the histogram's rate, which could get a zero if the rate is low.
> > ```
> 
> Am I correct that scylla_alternator_op_latency_sum metric (see code above defining it above) comes from a "histogram", not a "summary"?

You are correct, I'm trying to cover as much of what's there just in case it draw an attention to something else

**Comment by nyh** [comment] 2024-06-03 14:04
I had a new guess, that maybe the std::chrono::steady_clock we use is low resolution and assigns 0 to some short times. But a small experiment showed me that this guess is wrong - steady_clock actually has very good resolution (looks better than microsecond) - although I couldn't find it documented anywhere. In fact @amnonh - you fixed this in 722b4b6e985003a4f225e7c09c12525ada0b8140 - you said "To get a correct latency estimations executor should use a higher clock resolution.".

So I'm still fresh out ideas what's wrong :-( Some operations seem to increment the count correctly, but do not increase the "sum" value.

I still haven't been able to reproduce this issue, so I'm very limited in the kind of experiments I can do.

**Comment by nyh** [comment] 2024-06-03 14:44
I went back to the logs of the original failure (which I am not yet able to reproduce, not even in debug build), and see:
```
>           assert saved_latency_sum[op] < get_metric(metrics, 'scylla_alternator_op_latency_sum', {'op': op}, the_metrics)
E           assert 180479000.0 < 180479000.0
```
As far as I can tell (@amnonh is this correct?), the units of these scylla_alternator_op_latency_sum counters are microseconds. We're either very luck to see a whole millisecond, or steady_clock or something we do to it has only **millisecond** precision. A millisecond precision is not enough - an UpdateItem (the operation which failed), can take less than a millisecond. 

I tried the same thing locally, and saw numbers like 640.0 - this is fraction of a millisecond, not a whole multiple of millisecond. So I don't understand what's going on :-( How could the flaky test be using millisecond precision and my laptop microseconds?

**Comment by nyh** [comment] 2024-06-03 15:35
I went back to all the error messages. In https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9060 the test failed FOUR times (out of 100 runs). The errors are:

```
E           assert 180479000.0 < 180479000.0
E            +  where 180479000.0 = get_metric('http://127.249.147.2:9180/metrics', 'scylla_alternator_op_latency_sum', {'op': 'UpdateItem'}, '# HELP scylla_alien_receive_batch_queue_length Current receive batch queue 
E           assert 182297000.0 < 182297000.0
E            +  where 182297000.0 = get_metric('http://127.249.147.3:9180/metrics', 'scylla_alternator_op_latency_sum', {'op': 'UpdateItem'}, '# HELP scylla_alien_receive_batch_queue_length Current receive batch queue 
E           assert 179649000.0 < 179649000.0
E            +  where 179649000.0 = get_metric('http://127.249.147.4:9180/metrics', 'scylla_alternator_op_latency_sum', {'op': 'UpdateItem'}, '# HELP scylla_alien_receive_batch_queue_length Current receive batch queue 
E           assert 175340000.0 < 175340000.0
E            +  where 175340000.0 = get_metric('http://127.249.147.1:9180/metrics', 'scylla_alternator_op_latency_sum', {'op': 'UpdateItem'}, '# HELP scylla_alien_receive_batch_queue_length Current receive batch queue l
```

In https://github.com/scylladb/scylladb/pull/17799 it also failed four times of 100 runs, with the errors:
```
E           assert 178190000.0 < 178190000.0
E            +  where 178190000.0 = get_metric('http://127.102.44.1:9180/metrics', 'scylla_alternator_op_latency_sum', {'op': 'UpdateItem'}, '# HELP scylla_alien_receive_batch_queue_length Current receive batch queue 
E           assert 177094000.0 < 177094000.0
E            +  where 177094000.0 = get_metric('http://127.102.44.4:9180/metrics', 'scylla_alternator_op_latency_sum', {'op': 'UpdateItem'}, '# HELP scylla_alien_receive_batch_queue_length Current receive batch queue l
E           assert 179268000.0 < 179268000.0
E            +  where 179268000.0 = get_metric('http://127.102.44.2:9180/metrics', 'scylla_alternator_op_latency_sum', {'op': 'UpdateItem'}, '# HELP scylla_alien_receive_batch_queue_length Current receive batch queue 
E           assert 179055000.0 < 179055000.0
E            +  where 179055000.0 = get_metric('http://127.102.44.3:9180/metrics', 'scylla_alternator_op_latency_sum', {'op': 'UpdateItem'}, '# HELP scylla_alien_receive_batch_queue_length Current receive batch queue 
```

All 8 of these failures happen in UpdateItem (never in any other operation), and always the total "sum" is a whole number of milliseconds. I don't think any of this is a coincidence.
I don't know if those entire runs use milliseconds (?) , or there is some bug that happens when sum crosses a multiple of a thousand (?) or some bug only in the UpdateItem case or something else crazy :-(

**Comment by nyh** [comment] 2024-06-03 16:39
@amnonh I'm pretty sure this is a bug in the metrics/histograms layers. I don't have all the evidence yet but I'm getting close.

I repeated the failing test 50,000 (!) times and adding printouts of the "scylla_alternator_op_latency_sum" before and after the operation.

In the first operation we see:
```
NYH DeleteItem 0.0 640.0
NYH GetItem 0.0 640.0
NYH PutItem 0.0 1024.0
NYH UpdateItem 0.0 640.0
```
I.e. as expected the sum of latencies started in 0, and numbers like 640 or 1024 microseconds were added to it.

The 10th run shows
```
NYH DeleteItem 5888.0 6528.0
NYH GetItem 5760.0 6400.0
NYH PutItem 6400.0 7168.0
NYH UpdateItem 5760.0 6400.0
```
It seems the latency added was again 640 or 768 micros.
Now I begin to suspect something... How come is the latency added to the sum always such a nice multiple of 128 like 640, 768 or 1024? I doubt this was true in the original measurement inside Alternator (the now()-start_time) but I can later add printouts to verify. Something is "clamping" the real measurements to be a multiple of 128 microseconds.

By the 10,000th run, the multiple-of-128 mystery continues -
```
NYH DeleteItem 6617090.0 6617730.0
NYH GetItem 6400130.0 6400770.0
NYH PutItem 7326340.0 7326980.0
NYH UpdateItem 6524540.0 6525180.0
```
In fact here exactly 640 micros was added to each sum. That is very strange - all operations took exactly the same time, up to the microsecond? Of course this must be wrong.

But it get's even stranger. The 20,000th run:
```
NYH DeleteItem 13205000.0 13205800.0
NYH GetItem 12800500.0 12801200.0
NYH PutItem 14612400.0 14613000.0
NYH UpdateItem 13030800.0 13031400.0
```
Now, suddenly, the increment of sum (and the sum itself) is always a multiple of 100, not 128! The increment was 600, 700 or 800 for the different operations. Note how 600, 700, 800 is 6,7,8 times 100, whereas the numbers we saw earlier, 640, 768, 1024, were 5, 6 or 8 times 128! That cannot possibly be a coincidence.

The 40,000th run:
```
NYH DeleteItem 26444200.0 26444800.0
NYH GetItem 25601900.0 25602600.0
NYH PutItem 29285900.0 29286500.0
NYH UpdateItem 26098700.0 26099300.0
```
Still all increments (and sums) are a multiple of 100.

@amnonh do you have any guess what might possibly cause the latency histogram's sum to be reported first as being incremented at multiples of powers of of two like 640 microseconds, and later when it grows bigger, it suddenly becomes a multiple of 100?
@amnonh do you have low-level unit tests for these histograms testing how they count large numbers?

I suspect that what happens that at some point, when the sum is high enough (the original failures showed 178 million microseconds, I haven't reached it quite that sum in test in this comment) the precision somewhere in the histogram or metrics layer is so much that suddenly we are getting sums a multiple of 1000, and an operation that takes less than a millisecond can perhaps cause the sum not to increase at all.

I suspect that the reason why we see this problem only in the debug run is that this test is run on the same Scylla as many other previous tests and it already did many previous requests, and because it's a debug run and because the latency measures wall clock on an over-committed machine, it can have very high latencies which makes it easier to reach very high "sum" which is very hard for me to reach in my test.

**Comment by amnonh** [comment] 2024-06-03 17:49
It sounds like a problem with number truncation (maybe the switch between double and int).
In general, I'm against using the sum. It's there for compatibility, but the best you can get from it is average.
It's hard to keep precision with large numbers.
Instead, in the monitoring, I switched to P50.

The reported histogram's sum is not the sum of the actual values entered but a calculation based on the buckets.
https://github.com/scylladb/scylladb/blob/95db1c60d63b458a96545639f5d232edc9391896/utils/histogram_metrics_helper.hh#L37

Maybe the test should be different? Using the histogram is safe, let me know if you need my help in switching the test to use the histogram buckets instead of the sum

**Comment by nyh** [comment] 2024-06-04 07:07
@amnonh this is very anti-climatic :-(

So it turns out (is this documented anywhere?) that the "sum" of a histogram is very inaccurate: When it starts out it always jumps in multiples of 0.128 milliseconds, but as the uptime of the database grows, it loses accuracy and at some point only counts whole milliseconds, and at that point sub-millisecond latencies don't even change it at all
.
This should be documented somewhere, because the "sum" and "count" metrics are separate metrics like `scylla_alternator_op_latency_sum` - they don't even have the word "histogram" in their name - and users might assume, like I did, that they are accurate. And they are in fact very easy to keep accurate (just keep a sum _not_ per bucket, but a real accurate sum), so users will rightly expect that we do. I'll open a new issue about that for your consideration.

So indeed, I need to change this test now - because "sum" is broken in this sense and may not increase, so the test can't check that it increases. I still want to check that the operation does "something" to the latency histograms (the goal of the test is to check we didn't forget to measure the latency of the operations being tested), so indeed @amnonh I want your advice: Which `scylla_alternator_op_latency_*` metric can I read instead of "sum" and be sure that it **always** increases on every request, even if it's very short?

**Comment by nyh** [comment] 2024-06-04 09:01
I sent a PR (https://github.com/scylladb/scylladb/pull/19080) to unflake this test by not replying on the "sum" metric, and opened an issue https://github.com/scylladb/scylladb/issues/19081 about fixing the "sum" metric.

**Comment by amnonh** [comment] 2024-06-04 12:30
> @amnonh this is very anti-climatic :-(
> > 
> So indeed, I need to change this test now - because "sum" is broken in this sense and may not increase, so the test can't check that it increases. I still want to check that the operation does "something" to the latency histograms (the goal of the test is to check we didn't forget to measure the latency of the operations being tested), so indeed @amnonh I want your advice: Which `scylla_alternator_op_latency_*` metric can I read instead of "sum" and be sure that it **always** increases on every request, even if it's very short?

Yes, you can use the histogram buckets.
If you only want to see that a new item was inserted,  it's enough to check the last bucket and see that it increases and equals to count.

If you want to see what latency was increased, you must hold a copy of the histogram and do a subtraction.

**Closed** 2024-06-10 07:38 UTC
Labels: area/alternator, symptom/ci stability
