### ISSUE TITLE
Alternator /localnodes does not give public ips, only private ips

### ISSUE THREAD

**Issue by nopzdk** [scylladb/scylladb#21882] opened 2024-12-11 06:28 UTC
I have created a cluster on AWS with public IPs, but I am not able to get the public IPs when reaching the http://cluster:8000/localnodes endpoint, that means my connection fails and i cannot use this on IPs that are not directly attached the nodes. 
I tried setting the rpc address, but still only got private ips in the api call.

example
curl http://public-ip:8000/localnodes
gives this response,
["172.29.0.109","172.29.0.141","172.29.0.48"]
which is not accessible from a public ip.

**Comment by mykaul** [comment] 2024-12-11 09:26
@nopzdk - we usually ask to add relevant labels to the bug, for easier triage.
You have not shared your configuration, nor logs.

**Comment by mykaul** [comment] 2024-12-11 09:27
(unrelated, I don't think anyone should use public IPs for anything in the cloud, unless they are public facing service!)

**Comment by nyh** [comment] 2024-12-11 11:29
Which version of Scylla are you using?
This appears to be a duplicate of https://github.com/scylladb/scylladb/issues/18711, which I already fixed and I believe reached release 6.1 and 6.0.
Or is this issue somehow different?

**Comment by tarzanek** [comment] 2024-12-11 13:05
sounds like the same issue (there were other folks who hit it) , but I expect they use recent 2024.1.x (create in SC lately, so I'd expect 2024.1.11)

**Comment by mykaul** [comment] 2024-12-12 12:44
Closing for the time being, please re-open if needed (or in Enterprise).

**Closed by mykaul** 2024-12-12 12:44 UTC
Labels: area/alternator
