### ISSUE TITLE
flaky dtest test_update_schema_while_node_is_killed

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#15200] opened 2023-08-28 17:46 UTC
In CI run https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3294/testReport/junit/schema_management_test/TestSchemaManagement/Tests___Sanity_Tests___test_update_schema_while_node_is_killed_alter_table_/ we had a failure in the dtest  `schema_management_test`.`TestSchemaManagement`.`test_update_schema_while_node_is_killed`:

```
self = <schema_management_test.TestSchemaManagement object at 0x7f96c49ac090>
case = 'alter_table'

    @pytest.mark.parametrize("case", ("create_table", "alter_table", "drop_table"))
    def test_update_schema_while_node_is_killed(self, case):
        """
        Check that a node that is killed durring a table creation/alter/drop is able to rejoin and to synch on schema
        """
    
        logger.debug('1. Create a cluster and insert data')
        self.cluster.set_configuration_options(values={'ring_delay_ms': 5000})
        self.cluster.populate(3)
        self.cluster.start(wait_other_notice=True)
    
        [node1, node2, node3] = self.cluster.nodelist()
    
        session = self.patient_cql_connection(node1)
    
        def create_table_case():
            logger.debug('Creating table')
            create_c1c2_table(session)
            logger.debug('Populating')
            insert_c1c2(session, n=10)
    
        logger.debug('Creating keyspace')
        create_ks(session, 'ks', 3)
        if case != 'create_table':
            create_table_case()
    
        case_map = {
            "create_table": create_table_case,
            "alter_table": functools.partial(
                session.execute, "ALTER TABLE ks.cf ADD (c3 text);", timeout=180),
            "drop_table": functools.partial(
                session.execute, "DROP TABLE cf;", timeout=180),
        }
        with ThreadPoolExecutor(max_workers=2) as executor:
            logger.debug(f'2. kill node during {case}')
            kill_node_future = executor.submit(node2.stop, gently=False, wait_other_notice=True)
>           case_map[case]()

schema_management_test.py:252: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cassandra/cluster.py:2700: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.58.1:9042

cassandra/cluster.py:5019: OperationTimedOut
```

I am not familiar with this test, my guess (?) is that it is a test bug - maybe it tries to use a connection to one specific coordinator after killing it and the driver is not failing over silently and instead reporting an error. But why would it start failing now? I wonder if it's related to dtest commit 791f96dd0667882c98ff5b7ea535122e05b97886, where @ShlomiBalalis recently added - if I understand correctly - this and other tests to "gating".

**Comment by nyh** [comment] 2023-09-03 06:29
Another failure in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3420/testReport/junit/schema_management_test/TestSchemaManagement/Tests___Sanity_Tests___test_update_schema_while_node_is_killed_alter_table_/

**Comment by fruch** [comment] 2023-09-04 11:37
@nyh FYI it was not added by mistake, it's the new policy now, test are gating until proven otherwise.

**Comment by fruch** [comment] 2023-09-04 11:50
Also seem other similar failures in this:

```
E   cassandra.connection.ConnectionShutdown: Connection <LibevConnection(139721705567056) 127.0.20.1:9042 (closed)> is already closed
```

**Comment by fruch** [comment] 2023-09-04 12:03
this has failed 4 times (with similar results, i.e. client losing connection) so far: 

https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/a6ff5bd0-4b1a-11ee-b96a-256b7e8b2261


I think this might be a driver issue, the driver should be closing connect in this case, not in a way that should fail like that.
but maybe I'm missing something

**Comment by nyh** [comment] 2023-09-04 13:25
@fruch I vaguely remember that recently @kbr-scylla (?) had a similar problem in their topology tests where the driver failed to reconnect after losing the connection, because the reconnect timeout was too low, or too high. Or something. And had to be configured when creating the CQL connection. Sorry, I know I'm being very vague, I don't remember the details :-(

**Comment by nyh** [comment] 2023-09-04 13:26
> @fruch I vaguely remember that recently @kbr-scylla (?) had a similar problem in their topology tests where the driver failed to reconnect after losing the connection, because the reconnect timeout was too low, or too high. Or something. And had to be configured when creating the CQL connection. Sorry, I know I'm being very vague, I don't remember the details :-(

Found it! https://github.com/scylladb/scylladb/pull/15112. I'm not sure it's the same thing, though...

**Comment by fruch** [comment] 2023-09-04 19:45
> > @fruch I vaguely remember that recently @kbr-scylla (?) had a similar problem in their topology tests where the driver failed to reconnect after losing the connection, because the reconnect timeout was too low, or too high. Or something. And had to be configured when creating the CQL connection. Sorry, I know I'm being very vague, I don't remember the details :-(
> 
> Found it! #15112. I'm not sure it's the same thing, though...

Doesn't exactly looks like it, but it would be a change worth having, we never want to get to 10min delay between retries in a dtest

**Comment by fruch** [comment] 2023-09-04 20:21
looking a bit more closely at it, I can confirm it's 
https://github.com/scylladb/python-driver/issues/168

so I've taking this out of gating

**Comment by DoronArazii** [comment] 2023-09-06 11:09
@kostja please assign someone

**Comment by kbr-scylla** [comment] 2023-09-06 14:28
@DoronArazii if this is https://github.com/scylladb/python-driver/issues/168, then it's on the driver team's plate.

**Comment by fruch** [comment] 2023-09-06 14:40
I belive @Lorak-mmk is working on it

**Comment by bhalevy** [comment] 2023-10-15 11:20
https://github.com/scylladb/python-driver/issues/168 is fixed, so let's close this bug and return the test to next_gating.

**Closed by bhalevy** 2023-10-15 11:20 UTC
Labels: dtest, Master/Triage, CI-Stability
