### ISSUE TITLE
Alternator: incomplete attribute definitions in return of DescribeTable

### ISSUE THREAD

**Issue by julienrf** [scylladb/scylladb#19716] opened 2024-07-12 14:50 UTC
*Installation details*
Scylla version (or git commit hash): 6.0.1-0.20240612.bc89aac9d017 with build-id e845b7c6530ae1385e7bb3b7def09b4ffdf191c2
Cluster size: 1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

The command `DescribeTable` returns a structure containing a property `AttributeDefinitions`, which, currently, only lists the attributes that are part of the primary key of the table.

Instead, it should list all the attributes that were defined during the `CreateTable` command.

here is a sequence of commands to illustrate the issue:

~~~ bash
# Create a table with two attributes: id and x
aws dynamodb --region eu-central-1 --endpoint-url http://localhost:8000 \
  create-table \
    --table-name Foo \
    --attribute-definitions \
      AttributeName=id,AttributeType=S \
      AttributeName=x,AttributeType=N \
    --key-schema \
      AttributeName=id,KeyType=HASH \
    --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1

{
    "TableDescription": {
        "AttributeDefinitions": [
            {
                "AttributeName": "id",
                "AttributeType": "S"
            },
            {
                "AttributeName": "x",
                "AttributeType": "N"
            }
        ],
        "TableName": "Foo",
        "KeySchema": [
            {
                "AttributeName": "id",
                "KeyType": "HASH"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": "2024-07-12T16:39:27+02:00",
        "ProvisionedThroughput": {
            "ReadCapacityUnits": 1,
            "WriteCapacityUnits": 1
        },
        "TableId": "8a707750-405c-11ef-9697-5bfae9d33f46"
    }
}

# Describe the table
aws dynamodb --region eu-central-1 --endpoint-url http://localhost:8000 \
  describe-table \
    --table-name Foo

{
    "Table": {
        "AttributeDefinitions": [
            {
                "AttributeName": "id",
                "AttributeType": "S"
            }
        ],
        "TableName": "Foo",
        "KeySchema": [
            {
                "AttributeName": "id",
                "KeyType": "HASH"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": "2024-07-12T16:39:37+02:00",
        "ProvisionedThroughput": {
            "NumberOfDecreasesToday": 0,
            "ReadCapacityUnits": 0,
            "WriteCapacityUnits": 0
        },
        "TableArn": "arn:scylla:alternator:alternator_Foo:scylla:table/Foo",
        "TableId": "8a707750-405c-11ef-9697-5bfae9d33f46",
        "BillingModeSummary": {
            "BillingMode": "PAY_PER_REQUEST",
            "LastUpdateToPayPerRequestDateTime": "2024-07-12T16:39:37+02:00"
        }
    }
}
~~~

Note that in the result of the `create-table` command we see both attribute definitions, `id` and `x`, as supplied in the request. However, in the result of the `describe-table` command there is only `id`. The `x` attribute definition is missing.

The relevant part of the implementation is here:

https://github.com/scylladb/scylladb/blob/3cdf549da2818f4bf908ffc933f6cff7180c7137/alternator/executor.cc#L508-L517

We only copy the attribute definitions of the key schema to populate the resulting `AttributeDefinitions` property.

Related: #5026 and https://github.com/scylladb/scylladb/commit/6672059543cb1880de9c65aca1dad1775df769e2

**Comment by mykaul** [comment] 2024-07-14 14:28
Duplicate of https://github.com/scylladb/scylladb/issues/17141 ?

**Comment by nyh** [comment] 2024-07-14 14:46
> Duplicate of #17141 ?

It doesn't look that way so - that other issue is about what UpdateTable returns. This issue is about DescribeTable.

@julienrf can you please explain to me what the definition of "x" in the CreateTable is supposed to do? "x" is not a key column, it's not a key column of any GSI, so its definition simply doesn't do anything... In fact, I'm surprised we don't just fail CreateTable in this case. I'll write a test for this case and see what DynamoDB does in this case.

In any case, if we don't throw an error in CreateTable, the "x" is still ignored so it's not surprising that DescribeTable doesn't return it.

**Comment by julienrf** [comment] 2024-07-16 15:59
You make a good point that in my example `x` is not used anywhere. I ended up with such a scenario when working on something, but I agree that in practice that may not happen (ie, `x` would be referenced at least in the key definition or in an index definition). I will double check whether this is really an issue on my side and comment again here ASAP:

**Comment by julienrf** [comment] 2024-07-17 05:57
I just checked and I confirm that in ScyllaDB Alternator the attribute definitions contain only the attribute used in the primary key, but not those used in the secondary indexes, unlike in DynamoDB.

So, even if we change the example in the issue description to use the attribute `x` in a secondary index, it is not listed in the attribute definitions on a subsequent DescribeTable call.

**Comment by nyh** [comment] 2024-07-17 06:20
> I just checked and I confirm that in ScyllaDB Alternator the attribute definitions contain only the attribute used in the primary key, but not those used in the secondary indexes, unlike in DynamoDB.

Can you please give a detailed, self-contained, example?

In test/alternator/test_gsi.py we have a test `test_gsi_5_describe_table_schema` which is supposed to do what you tried: It has a table where there is an attribute "x" which appears only in the GSI key, not the base table key, and the test verifies that this "x" does appear in the AttributeDefinitions we get back from DescribeTable. So either there's a bug in this test (?), or somehow your situation is different from what this test tries (which is why I am asking for a more detailed example) - or something was wrong in your test?

**Comment by julienrf** [comment] 2024-07-17 07:47
Hey sorry @nyh actually my test was incorrectly set up and after double-checking I agree with you that all the attributes that are used either in the primary key or in secondary indexes are correctly listed in the output of DescribeTable. Therefore, I don’t think the issue originally reported is really important. Feel free to close it.

**Comment by nyh** [comment] 2024-07-17 07:55
> Hey sorry @nyh actually my test was incorrectly set up and after double-checking I agree with you that all the attributes that are used either in the primary key or in secondary indexes are correctly listed in the output of DescribeTable. Therefore, I don’t think the issue originally reported is really important. Feel free to close it.

Thanks for checking.

The only thing that maybe remains of this issue is the **error checking**: to consider printing an error if there is an attempt to "CreateTable" with a definition of "x" that isn't used by any key column of the table or any of its indexes. I want to write a test for this case, and see if DynamoDB prints an error in this case about the spurious "x". If it doesn't, I think this issue should be closed. But if it does print an error in that case, we should too.

**Comment by nyh** [comment] 2024-07-17 08:35
> CC @amnonh

May I ask why @amnonh would be interested in this specific issue?

**Comment by mykaul** [comment] 2024-07-17 08:41
@nyh - since @amnonh and me just discussed these:

> ```shell
>         "ProvisionedThroughput": {
>             "NumberOfDecreasesToday": 0,
>             "ReadCapacityUnits": 0,
>             "WriteCapacityUnits": 0
> ```

**Comment by nyh** [comment] 2024-07-17 08:46
@mykaul I think you are confusing this issue with a different issue. This issue was specifically about the `AttributeDefinitions` property, it has nothing to do with provisioned throughput.

**Comment by nyh** [comment] 2024-07-18 08:25
@julienrf I hope you don't mind, I opened a new issue (https://github.com/scylladb/scylladb/issues/19784) on what I believe remains of this issue - just the missing error-checking - and am closing this one.

**Closed by nyh** 2024-07-18 08:25 UTC
Labels: area/alternator
