### ISSUE TITLE
test_raft_service_levels.test_service_levels_work_during_recovery: `TimeoutError` while restarting servers

### ISSUE THREAD

**Issue by Jadw1** [scylladb/scylladb#18089] opened 2024-03-28 13:32 UTC
Test failed in: https://jenkins.scylladb.com/job/scylla-master/job/next/7446/
Full logs: [logs.zip](https://github.com/scylladb/scylladb/files/14832133/logs.zip)

The failure was in debug mode

```
manager = <test.pylib.manager_client.ManagerClient object at 0x7f646d6c5a90>

    @pytest.mark.asyncio
    async def test_service_levels_work_during_recovery(manager: ManagerClient):
        servers = await manager.servers_add(3)
    
        logging.info("Waiting until driver connects to every server")
        cql = manager.get_cql()
        hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
    
        logging.info("Creating a bunch of service levels")
        sls = ["sl" + unique_name() for _ in range(10)]
        for sl in sls:
            await cql.run_async(f"CREATE SERVICE LEVEL {sl}")
    
        # insert a service levels into old table as if it was created before upgrade to v2 and later removed after upgrade
        sl_v1 = "sl" + unique_name()
        await cql.run_async(f"INSERT INTO system_distributed.service_levels (service_level) VALUES ('{sl_v1}')")
    
        logging.info("Validating service levels were created in v2 table")
        result = await cql.run_async("SELECT service_level FROM system.service_levels_v2")
        for sl in result:
            assert sl.service_level in sls
    
        logging.info(f"Restarting hosts {hosts} in recovery mode")
        await asyncio.gather(*(enter_recovery_state(cql, h) for h in hosts))
        for srv in servers:
>           await restart(manager, srv)

test/auth_cluster/test_raft_service_levels.py:130: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology/util.py:123: in restart
    await manager.server_start(server.server_id)
test/pylib/manager_client.py:184: in server_start
    await self.client.put_json(f"/cluster/server/{server_id}/start", data, timeout=timeout)
test/pylib/rest_client.py:111: in put_json
    ret = await self._fetch("PUT", resource_uri, response_type = response_type, host = host,
test/pylib/rest_client.py:64: in _fetch
    async with request(method, uri,
/usr/lib64/python3.11/site-packages/aiohttp/client.py:1243: in __aenter__
    self._resp = await self._coro
/usr/lib64/python3.11/site-packages/aiohttp/client.py:605: in _request
    await resp.start(conn)
/usr/lib64/python3.11/site-packages/aiohttp/client_reqrep.py:961: in start
    with self._timer:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <aiohttp.helpers.TimerContext object at 0x7f646c3a2750>
exc_type = <class 'asyncio.exceptions.CancelledError'>
exc_val = CancelledError(), exc_tb = <traceback object at 0x7f646c3aeb80>

    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> Optional[bool]:
        if self._tasks:
            self._tasks.pop()
    
        if exc_type is asyncio.CancelledError and self._cancelled:
>           raise asyncio.TimeoutError from None
E           TimeoutError

/usr/lib64/python3.11/site-packages/aiohttp/helpers.py:735: TimeoutError
```

**Comment by mykaul** [comment] 2024-03-31 07:35
@Jadw1 - are you looking into it?

**Comment by piodul** [comment] 2024-04-02 06:00
The zip in the description contained node logs from a different test (nodes 175, 176, 177), I reuploaded the zip with the correct logs (178, 179, 180) and edited the description.

**Comment by piodul** [comment] 2024-04-02 07:17
The test gets stuck while trying to restart the first node (178). The driver tries to reconnect to the node but, strangely, it cannot due to authentication failure:

```
20:14:07.402 INFO> Restarting hosts [<Host: 127.84.6.7:9042 datacenter1>, <Host: 127.84.6.6:9042 datacenter1>, <Host: 127.84.6.13:9042 datacenter1>] in recovery mode
20:14:07.421 INFO> Stopping Server(178, 127.84.6.6, 127.84.6.6) gracefully
...
20:14:07.539 WARNING> Host 127.84.6.6:9042 has been marked down
...
20:14:10.938 INFO> Restarting Server(178, 127.84.6.6, 127.84.6.6)
...
20:14:17.431 DEBUG> Message pushed from server: <EventMessage(event_type='STATUS_CHANGE', event_args={'change_type': 'UP', 'address': ('127.84.6.6', 9042)}, stream_id=-1, trace_id=None)>
20:14:18.378 DEBUG> Connection 140069289241104: '('127.0.0.1', 44234)' -> '('127.84.6.6', 9042)'
20:14:18.378 DEBUG> Sending initial options message for new connection (140069289241104) to 127.84.6.6:9042
20:14:18.382 DEBUG> Parsing sharding info from message options {'COMPRESSION': ['lz4', 'snappy'], 'SCYLLA_LWT_ADD_METADATA_MARK': ['LWT_OPTIMIZATION_META_BIT_MASK=2147483648'], 'SCYLLA_NR_SHARDS': ['2'], 'SCYLLA_PARTITIONER': ['org.apache.cassandra.dht.Murmur3Partitioner'], 'SCYLLA_RATE_LIMIT_ERROR': ['ERROR_CODE=61440'], 'SCYLLA_SHARD': ['0'], 'SCYLLA_SHARDING_ALGORITHM': ['biased-token-round-robin'], 'SCYLLA_SHARDING_IGNORE_MSB': ['12'], 'TABLETS_ROUTING_V1': ['']}
20:14:18.382 DEBUG> Received options response on new connection (140069289241104) from 127.84.6.6:9042
20:14:18.382 DEBUG> No available compression types supported on both ends. locally supported: odict_keys([]). remotely supported: ['lz4', 'snappy']
20:14:18.382 DEBUG> Sending StartupMessage on <CustomConnection(140069289241104) 127.84.6.6:9042>
20:14:18.382 DEBUG> Sent StartupMessage on <CustomConnection(140069289241104) 127.84.6.6:9042>
20:14:18.384 DEBUG> Got AuthenticateMessage on new connection (140069289241104) from 127.84.6.6:9042: org.apache.cassandra.auth.PasswordAuthenticator
20:14:18.384 DEBUG> Sending SASL-based auth response on <CustomConnection(140069289241104) 127.84.6.6:9042>
20:14:18.392 DEBUG> Received ErrorMessage on new connection (140069289241104) from 127.84.6.6:9042: Error from server: code=0100 [Bad credentials] message="Username and/or password are incorrect"
20:14:18.392 DEBUG> Defuncting connection (140069289241104) to 127.84.6.6:9042:
Traceback (most recent call last):
  File "cassandra/connection.py", line 608, in cassandra.connection.defunct_on_error.wrapper
  File "cassandra/connection.py", line 1498, in cassandra.connection.Connection._handle_auth_response
cassandra.AuthenticationFailed: Failed to authenticate to 127.84.6.6:9042: Error from server: code=0100 [Bad credentials] message="Username and/or password are incorrect"
20:14:18.392 DEBUG> Closing connection (140069289241104) to 127.84.6.6:9042
20:14:18.393 DEBUG> Closed socket to 127.84.6.6:9042
```

While node 179 was booting, there is a schema mismatch right after the auth service is started:

```
...
INFO  2024-03-27 20:14:04,985 [shard 0:main] init - starting auth service
INFO  2024-03-27 20:14:04,989 [shard 0:main] migration_manager - Schema mismatch for 127.84.6.7 (c0c4e05c-ec65-11ee-5b4e-e3e1b5a4751a != c050a778-ec65-11ee-b403-cee0a1c176d5).
...
```

Similar situation on 180:

```
...
INFO  2024-03-27 20:13:53,820 [shard 0:main] init - starting auth service
INFO  2024-03-27 20:13:53,823 [shard 0:main] migration_manager - Schema mismatch for 127.84.6.13 (c0c4e05c-ec65-11ee-5b4e-e3e1b5a4751a != 59adb24e-f3cd-3e02-97f0-5b395827453f).
INFO  2024-03-27 20:13:53,829 [shard 0:comp] compaction - [Compact system.topology_requests c5225e40-ec65-11ee-bf42-b68445587e1d] Compacting [/scylladir/testlog/x86_64/debug/scylla-180/data/system/topology_requests-b3068525d0f239c28250584f9b1bf460/me-3ges_1en5_3rgjk2wpgwqpqoou1p-big-Data.db:level=0:origin=memtable,/scylladir/testlog/x86_64/debug/scylla-180/data/system/topology_requests-b3068525d0f239c28250584f9b1bf460/md-3ges_1emy_5pz4g2wpgwqpqoou1p-big-Data.db:level=0:origin=memtable]
...
```

Shortly after, there is a log spam of messages about schema mismatches on nodes 178 and 179 (strangely, not on 180) and the situation does not seem to fix itself.

@nuivall could you take a look at this?

**Comment by nuivall** [comment] 2024-04-03 10:01
@piodul so currently without https://github.com/scylladb/scylladb/pull/18039 when you restart in recovery auth erroneously enters v1 mode. Not saying it's 100% the cause but maybe we can merge the version fix and then if it happens again at least we'll be sure we're debugging v2 not old v1 implementation.

One odd thing I don't get is if you grep for `init - Scylla version 5.5.0~dev-0.20240327.c3989d8e03c1 with build-id b65976879f5c67befd3d4509c69da5bd40c459ca starting ...` you'll see this message twice on node 178 but only once on other. So they were not restarted? Or logs missing?

Because if they'd crash on startup and with only one node alive it's obvious why auth v1 fails (needs either established connection or quorum).

**Comment by piodul** [comment] 2024-04-03 10:16
> @piodul so currently without #18039 when you restart in recovery auth erroneously enters v1 mode. Not saying it's 100% the cause but maybe we can merge the version fix and then if it happens again at least we'll be sure we're debugging v2 not old v1 implementation.

Right, this might be it. The test fails because it cannot authenticate the incoming connection, maybe it tries to look at the legacy table and creation/initialization of that table fails because the cluster is mixed. Curiously though, the test is flaky and it DOES work sometimes.

> 
> One odd thing I don't get is if you grep for `init - Scylla version 5.5.0~dev-0.20240327.c3989d8e03c1 with build-id b65976879f5c67befd3d4509c69da5bd40c459ca starting ...` you'll see this message twice on node 178 but only once on other. So they were not restarted? Or logs missing?

No, that's fine. The test reaches a loop which is supposed to do a rolling restart of all nodes. It only manages to restart one node (178) but the driver fails to reconnect, so the test thinks that restarting the node failed.

> 
> Because if they'd crash on startup and with only one node alive it's obvious why auth v1 fails (needs either established connection or quorum).

No, there is no crash as far as I can see.

**Comment by piodul** [comment] 2024-04-03 10:21
I'm running this test 100 times in debug mode with current master to see how frequently it reproduces so that we can compare after #18039 is merged: https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/2191/

**Comment by nuivall** [comment] 2024-04-03 10:57
Auth V1 node restarts at `20:14:12`, then at `20:14:18` `Username and/or password are incorrect` error starts to appear, but at `20:14:19` it ends. Looks like the driver is not retrying on "Bad credentials" error. And perhaps it is a transient thing? 6 seconds maybe is not enough to always fully start in debug mode?

**Comment by nuivall** [comment] 2024-04-03 11:09
Yes, that's likely the case, this error is typically not transient, but it can be when user is not found in "roles" table. Which does happen, e.g. due to https://github.com/scylladb/scylladb/issues/10481 So there are 2 bugs here:
1. driver should retry on `Username and/or password are incorrect` because auth reads (even in v2) are eventually consistent.
2. without v1 downgrade in the test the user is more likely to be found (I guessing `wait_for_cql_and_get_hosts` is doing better retry, or timing is different so normal tests don't fail)

Wrt. 2. we actually may have some `auth_cluster` failures in theory due to https://github.com/scylladb/scylladb/issues/10481 if my guess about `wait_for_cql_and_get_hosts` is not correct

**Comment by mykaul** [comment] 2024-04-03 11:57
> 1. driver should retry on `Username and/or password are incorrect` because auth reads (even in v2) are eventually consistent.

This sounds very confusing - to the driver.

**Comment by nuivall** [comment] 2024-04-03 13:29
> > 1. driver should retry on `Username and/or password are incorrect` because auth reads (even in v2) are eventually consistent.
> 
> This sounds very confusing - to the driver.

We can add another message if it helps, but with login usually it's vague to help protect with enumeration attacks or information leaks.

Anyway retry should be rather based on error code or code path and we can also return auth error when encounter std::system_error or even unavailable_exception and I bet those can be transient.

**Comment by piodul** [comment] 2024-05-23 13:46
The fix https://github.com/scylladb/scylladb/pull/18039 got merged some time ago and the test no longer seem to fail. We had another failure reported after merging it in https://github.com/scylladb/scylladb/issues/18231, but the test failed in a different place and the root cause is most likely different. No use in keeping two issues open, anyway.

I'm closing this issue.

**Closed by piodul** 2024-05-23 13:46 UTC
Labels: symptom/ci stability, area/service levels
