### ISSUE TITLE
Error: hints_manager - Exception when draining 127.0.18.3: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty  found on alive nodes during replace operation

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#17209] opened 2024-02-07 15:03 UTC
Scylla version:  5.5.0~dev-0.20240206.c0c291b98536 with build-id ee177ddf9e48dacd755092d72e31345d862d2dd4

test: [replace_address_test.TestReplaceAddress.test_replace_node_using_new_ip_then_shut_down](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/37/testReport/replace_address_test/TestReplaceAddress/test_replace_node_using_new_ip_then_shut_down_rbo_enabled_/) ran with raft topology experimental feature. Cluster started with 2 nodes and background payload with cassandra. Then add node3.
After node3 bootstrapped, it terminated. Payload continue running. Then the node3 is going to be replaced with new node by host id and new node will have new ip address.
At the end of replace process. both nodes: node1 and node2 are reported next errors:
```
INFO  2024-02-07 11:13:57,975 [shard 0:strm] stream_session - [Stream #fcfe4050-c5a9-11ee-abbc-69a9c656316f] Skip sending ks=system_traces, cf=node_slow_log_time_idx, reader contains no data, with new rpc streaming
INFO  2024-02-07 11:13:57,975 [shard 1:strm] stream_session - [Stream #fcfe4050-c5a9-11ee-abbc-69a9c656316f] Skip sending ks=system_traces, cf=node_slow_log_time_idx, reader contains no data, with new rpc streaming
INFO  2024-02-07 11:13:57,975 [shard 0:strm] stream_session - [Stream #fcfe4050-c5a9-11ee-abbc-69a9c656316f] Streaming plan for Replace-system_traces-index-10 succeeded, peers={127.0.18.4}, tx=0 KiB, 0.00 KiB/s, rx=0 KiB, 0.00 KiB/s
INFO  2024-02-07 11:13:57,977 [shard 0:strm] raft_topology - updating topology state: replacing: streaming completed for node ca87276f-28fd-4fc9-90aa-cffed529fc60
INFO  2024-02-07 11:13:57,987 [shard 0:strm] token_metadata - Added node ca87276f-28fd-4fc9-90aa-cffed529fc60 as pending replacing endpoint which replaces existing node f7c00c12-5709-49ed-95e7-fa8beaf5ec44
INFO  2024-02-07 11:13:57,998 [shard 0:strm] raft_topology - entered `write both read new` transition state
INFO  2024-02-07 11:13:57,998 [shard 0:strm] raft_topology - executing global topology command barrier_and_drain, excluded nodes: {f7c00c12-5709-49ed-95e7-fa8beaf5ec44}
INFO  2024-02-07 11:13:58,018 [shard 0:strm] raft_topology - updating topology state: advance fence version to 10
INFO  2024-02-07 11:13:58,027 [shard 0:strm] token_metadata - Added node ca87276f-28fd-4fc9-90aa-cffed529fc60 as pending replacing endpoint which replaces existing node f7c00c12-5709-49ed-95e7-fa8beaf5ec44
INFO  2024-02-07 11:13:58,039 [shard 0:strm] raft_topology - removing node f7c00c12-5709-49ed-95e7-fa8beaf5ec44 from group 0 configuration...
INFO  2024-02-07 11:13:58,046 [shard 0:strm] raft_topology - node f7c00c12-5709-49ed-95e7-fa8beaf5ec44 removed from group 0 configuration
INFO  2024-02-07 11:13:58,046 [shard 0:strm] raft_topology - updating topology state: replace: read fence completed
INFO  2024-02-07 11:13:58,054 [shard 0:strm] gossip - Removed endpoint 127.0.18.3
INFO  2024-02-07 11:13:58,055 [shard 0:strm] gossip - Finished to force remove node 127.0.18.3
INFO  2024-02-07 11:13:58,056 [shard 0:strm] messaging_service - Dropping connection to 127.0.18.4 because it was created without topology information
INFO  2024-02-07 11:13:58,056 [shard 0:strm] messaging_service - Dropping connection to 127.0.18.4 because it was created without topology information
ERROR 2024-02-07 11:13:58,061 [shard 1:strm] hints_manager - Exception when draining 127.0.18.3: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-h35rl6vs/test/node1/hints/1/127.0.18.3])
INFO  2024-02-07 11:13:58,065 [shard 0:strm] load_balancer - Examining DC datacenter1
```

Looks like hints for node 3 stay on alive nodes: node1 and node2, and folder could n't be removed.

Logs could be found here: https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/37/artifact/logs-full.release.000/

JObs for reproduce: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/37/ could be just rebuild

**Comment by aleksbykov** [comment] 2024-02-07 15:17
The same issue happened also in this test: [materialized_views_test.TestMaterializedViews.test_remove_node_during_mv_insert_3_nodes](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/38/testReport/materialized_views_test/TestMaterializedViews/test_remove_node_during_mv_insert_3_nodes/)

logs could be found here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/38/testReport/

**Comment by mykaul** [comment] 2024-02-08 07:39
@ptrsmrn - is this something your team needs to look at?

**Comment by ptrsmrn** [comment] 2024-02-08 10:39
@mykaul yes, @dawmd has it in his queue.

**Comment by kbr-scylla** [comment] 2024-02-19 10:11
Very similar issue: https://github.com/scylladb/scylladb/issues/17023

**Comment by kbr-scylla** [comment] 2024-03-17 19:41
Similar failure in `hintedhandoff_additional_test.TestHintedHandoff.test_hintedhandoff_removenode`: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/dtest_raft_topolgy/job/dtest-full-with-consistent-topology-changes/28/testReport/junit/hintedhandoff_additional_test/TestHintedHandoff/FullDtest___full_split001___test_hintedhandoff_removenode/

**Comment by kbr-scylla** [comment] 2024-03-17 20:50
Another test failing on this: `replace_address_test.TestReplaceAddress.test_replace_with_background_workload`
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/dtest_raft_topolgy/job/dtest-full-with-consistent-topology-changes/31/testReport/junit/replace_address_test/TestReplaceAddress/FullDtest___full_split007___test_replace_with_background_workload_use_host_id_rbo_enabled_/

**Comment by piodul** [comment] 2024-04-03 12:54
Closing this one as a duplicate of https://github.com/scylladb/scylladb/issues/17023

**Closed by piodul** 2024-04-03 12:54 UTC
Labels: type/bug, area/hinted handoff, area/topology changes, area/raft
