### ISSUE TITLE
Adding a column to the base table should invalidate prepared statements for views

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16392] opened 2023-12-12 15:04 UTC
In https://github.com/scylladb/scylla-enterprise/issues/3493#issuecomment-1850936534, @tgrabiec noticed that:

"I've noticed that adding a column to the base table does not invalidate prepared statements for the views. So select * query doesn't see the new column. Only after scylla restarts queries start to see it. So it can happen that depending on which host you contact, you may see the new column or not."

**Comment by mykaul** [comment] 2024-01-09 07:44
This sounds quite severe, no? I think it should be prioritized. @nyh - any rough estimates on the complexity of a fix for this?

**Comment by mykaul** [comment] 2024-01-16 18:05
@nyh - ping - do we have any thoughts on this? Just an estimate would be great - assigning it to you (temporarily) for consideration.

**Comment by nyh** [comment] 2024-01-17 10:45
> This sounds quite severe, no? I think it should be prioritized. @nyh - any rough estimates on the complexity of a fix for this?

As I said I just quoted @tgrabiec's statement about this being a bug - I didn't reproduce it myself and I don't know, if this bug exists, how severe it is. I'm not really an expert in prepared statement invalidation and why was important to have it for non-views - I assume the same reasons why we need prepared-statement-invalidation would apply to views (@mykaul maybe you know who the expert on this might be).

**Comment by mykaul** [comment] 2024-01-17 14:25
@eliransin - is the above in your team? Who can look at this?

**Comment by eliransin** [comment] 2024-01-17 16:43
First step IMO is to reproduce the issue (if even exists):
IIUC this should reproduce it quite easily:
1. Start a 3 node cluster
2. Create a materialized view that "select *" the rows
3. Create a prepared statement on the view that "select *" the row
4. Write a row
5. Issue the prepared statement from 3 and validate that we get 1 row and that it is correct
6. Add a column to the base table
7. Write another row with the new column
8. Issue the prepared statement from 3 and validate that we get 2 row and that they have the new value set where it should.

Will make an attempt on this.

**Comment by eliransin** [comment] 2024-01-17 17:35
Fix submitted

**Comment by eliransin** [comment] 2024-01-21 08:41
@nyh had very good questions about why didn't this happen automatically and I think he is right. This fix in #16830 will work. However, it is not the correct point for fixing this so I will try to figure it out using the correct point this time.
@mykaul you asked for an estimation, I think it will take a day or two to debug and lock in on the actual fix.

**Closed** 2024-01-22 10:24 UTC
Labels: bug, materialized-views, Field-Tier2

**Comment by eliransin** [comment] 2024-01-22 13:09
This bug exists since very long ago, so all live versions needs a backport :slightly_smiling_face:  (I checked 5.1 and above).
It looks like the fix itself is going to merge cleanly since this code looks untouched on older versions.
The test is not guarantied to merge cleanly since there was a lot of development around test.py during the past months.

**Comment by mykaul** [comment] 2024-01-23 16:53
@scylladb/scylla-maint please backport

**Comment by nyh** [comment] 2024-01-23 17:31
> @scylladb/scylla-maint please backport

I'll do it now.

**Comment by nyh** [comment] 2024-01-23 19:18
Backported to next-5.4 (df1843311aaffccb1de4123e58d3b05985e8165b) - both the code and test backported cleanly (but this took ages to do).
Next I'll do next-5.2.
