### ISSUE TITLE
test_added_node_gets_closed_shards is flaky

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15051] opened 2023-08-14 14:16 UTC
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3057/testReport/junit/alternator_stream_tests/TestAlternatorStreams/Tests___Sanity_Tests___test_added_node_gets_closed_shards/

```
Error Message
botocore.errorfactory.InternalServerError: An error occurred (InternalServerError) when calling the BatchWriteItem operation (reached max retries: 0): Internal server error: exceptions::invalid_request_exception (cdc: attempted to get a stream from an earlier generation than the currently used one. With CDC you cannot send writes with timestamps too far into the past, because that would break consistency properties (write timestamp: 2023/08/14 12:29:22, current generation started at: 2023/08/14 12:29:22))
Stacktrace
self = <alternator_stream_tests.TestAlternatorStreams object at 0x7f508a352b50>

    @pytest.mark.next_gating
    def test_added_node_gets_closed_shards(self):
        """
        test scenario:
            1. create a table with Streams.
            2. run alternator stress. (or multiple stresses to multiple nodes needed?)
            3. add new node to cluster.
            4. wait for new node bootstrap.
            5. run streams APIs queries, connecting to the new node.
            6. see that it returns some 'closed' shards with EndingSequenceNumber.
            https://github.com/scylladb/scylla/pull/8209#issuecomment-790625323
        """
        stream_specification = enums.StreamSpecification.KEYS_ONLY.value
        self.prepare_dynamodb_cluster(num_of_nodes=3)
        node1 = self.cluster.nodelist()[0]
    
        logger.info(f'Pre setup - Creating "{TABLE_NAME}" table via "{node1.name}" node with "{stream_specification}"'
                    f' stream key')
>       stream_arn = self.prefill_dynamodb_table(node=node1, stream_specification=stream_specification)[0]

alternator_stream_tests.py:253: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
alternator_utils.py:876: in prefill_dynamodb_table
    table = super().prefill_dynamodb_table(node=node, table_name=table_name, num_of_items=num_of_items, **kwargs)
alternator_utils.py:723: in prefill_dynamodb_table
    return self.batch_write_actions(table_name=table_name, node=node, new_items=new_items)
alternator_utils.py:395: in batch_write_actions
    raise error
alternator_utils.py:388: in batch_write_actions
    batch.put_item(item)
/usr/local/lib/python3.11/site-packages/boto3/dynamodb/table.py:103: in put_item
    self._add_request_and_process({'PutRequest': {'Item': Item}})
/usr/local/lib/python3.11/site-packages/boto3/dynamodb/table.py:112: in _add_request_and_process
    self._flush_if_needed()
/usr/local/lib/python3.11/site-packages/boto3/dynamodb/table.py:139: in _flush_if_needed
    self._flush()
/usr/local/lib/python3.11/site-packages/boto3/dynamodb/table.py:144: in _flush
    response = self._client.batch_write_item(
/usr/local/lib/python3.11/site-packages/botocore/client.py:535: in _api_call
    return self._make_api_call(operation_name, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <botocore.client.DynamoDB object at 0x7f50885da2d0>
operation_name = 'BatchWriteItem'
api_params = {'RequestItems': {'user_table': [{'PutRequest': {'Item': {'hash_key': {...}, 'x': {...}}}}, {'PutRequest': {'Item': {'...Request': {'Item': {'hash_key': {...}, 'x': {...}}}}, {'PutRequest': {'Item': {'hash_key': {...}, 'x': {...}}}}, ...]}}

    def _make_api_call(self, operation_name, api_params):
        operation_model = self._service_model.operation_model(operation_name)
        service_name = self._service_model.service_name
        history_recorder.record(
            'API_CALL',
            {
                'service': service_name,
                'operation': operation_name,
                'params': api_params,
            },
        )
        if operation_model.deprecated:
            logger.debug(
                'Warning: %s.%s() is deprecated', service_name, operation_name
            )
        request_context = {
            'client_region': self.meta.region_name,
            'client_config': self.meta.config,
            'has_streaming_input': operation_model.has_streaming_input,
            'auth_type': operation_model.auth_type,
        }
        api_params = self._emit_api_params(
            api_params=api_params,
            operation_model=operation_model,
            context=request_context,
        )
        endpoint_url, additional_headers = self._resolve_endpoint_ruleset(
            operation_model, api_params, request_context
        )
        request_dict = self._convert_to_request_dict(
            api_params=api_params,
            operation_model=operation_model,
            endpoint_url=endpoint_url,
            context=request_context,
            headers=additional_headers,
        )
        resolve_checksum_context(request_dict, operation_model, api_params)
    
        service_id = self._service_model.service_id.hyphenize()
        handler, event_response = self.meta.events.emit_until_response(
            'before-call.{service_id}.{operation_name}'.format(
                service_id=service_id, operation_name=operation_name
            ),
            model=operation_model,
            params=request_dict,
            request_signer=self._request_signer,
            context=request_context,
        )
    
        if event_response is not None:
            http, parsed_response = event_response
        else:
            maybe_compress_request(
                self.meta.config, request_dict, operation_model
            )
            apply_request_checksum(request_dict)
            http, parsed_response = self._make_request(
                operation_model, request_dict, request_context
            )
    
        self.meta.events.emit(
            'after-call.{service_id}.{operation_name}'.format(
                service_id=service_id, operation_name=operation_name
            ),
            http_response=http,
            parsed=parsed_response,
            model=operation_model,
            context=request_context,
        )
    
        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.errorfactory.InternalServerError: An error occurred (InternalServerError) when calling the BatchWriteItem operation (reached max retries: 0): Internal server error: exceptions::invalid_request_exception (cdc: attempted to get a stream from an earlier generation than the currently used one. With CDC you cannot send writes with timestamps too far into the past, because that would break consistency properties (write timestamp: 2023/08/14 12:29:22, current generation started at: 2023/08/14 12:29:22))

/usr/local/lib/python3.11/site-packages/botocore/client.py:980: InternalServerError
```

**Comment by nyh** [comment] 2023-08-14 14:22
I think this a duplicate of #15039. It's a dtest bug (https://github.com/scylladb/scylla-dtest/issues/3498), not a Scylla bug, and should be fixed by https://github.com/scylladb/scylla-dtest/pull/3499.

**Comment by nyh** [comment] 2023-08-14 14:24
Note that the reason why all these flaky-test bugs started coming out of the woodwork now is that we stopped the long sleeps in the beginning of the test, leading to various failures caused by test code that forgets to sleep (or in this case, slept in the wrong place).

**Comment by avikivity** [comment] 2023-08-14 14:29
Closing as duplicate of #15039.

**Closed** 2023-08-14 14:29 UTC
Labels: CI-Stability
