### ISSUE TITLE
TestCdc.test_change_field_type_with_cdc[Single_cluster] failed

### ISSUE THREAD

**Issue by Annamikhlin** [scylladb/scylladb#17905] opened 2024-03-19 20:08 UTC
seen on https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2864/testReport/junit/cdc_test/TestCdc/Build___x86___dtest_with_topology_changes___test_change_field_type_with_cdc_Single_cluster_/

```
self = <cdc_test.TestCdc object at 0x7f616017d550>
request = <FixtureRequest for <Function test_change_field_type_with_cdc[Single_cluster]>>
cluster_config = ClusterConfig(size=[3], replication="{'class': 'NetworkTopologyStrategy', 'replication_factor': 3}")

    @pytest.mark.next_gating
    def test_change_field_type_with_cdc(self, request, cluster_config):
>       self.schema_change_template(request, "ALTER TABLE ks.cf ALTER b TYPE blob", cluster_size=cluster_config.size, replication=cluster_config.replication)

cdc_test.py:445: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cdc_test.py:438: in schema_change_template
    self.check_common_invariants(session, base_rows, log_rows, update_rows, write_count, with_preimage)
cdc_test.py:621: in check_common_invariants
    self.check_that_log_corresponds_to_current_state(session, base_rows, update_rows)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cdc_test.TestCdc object at 0x7f616017d550>
session = <cassandra.cluster.Session object at 0x7f626eb7d1d0>
base_rows = [Row(a=4317, b=b'9', tok=-9223297786983086897), Row(a=3372, b=b'9', tok=-9221834874718566760), Row(a=14340, b=b'6', to...19848578536890599), Row(a=7034, b=b'9', tok=-9219268429937221800), Row(a=13909, b=b'6', tok=-9218713672343429522), ...]
update_rows = [Row(cdc_stream_id=b'\x80\xae|\xe5|Y\x8b\x8c\x83+!\xc5\xcc\x00\x00\x11', cdc_time=UUID('6831a342-e60e-11ee-b36e-855ffe...e-5a46-52654df3df0a'), cdc_batch_seq_no=0, a=23, b=b'1', cdc_operation=2, cdc_ttl=None, tok=-9174258065831523444), ...]

    def check_that_log_corresponds_to_current_state(self, session, base_rows, update_rows):
        logger.debug("Check that most recent records in log table correspond to current state of base table")
    
        latest_rows = {}
        for row in update_rows:
            if row.a in latest_rows:
                assert datetime_from_uuid1(row.cdc_time) >= datetime_from_uuid1(latest_rows[row.a].cdc_time), f"Update rows are not sorted, pk: {row.a}"
            latest_rows[row.a] = row
    
        assert len(latest_rows) == len(base_rows)
        for row in base_rows:
            assert row.a in latest_rows
            latest = latest_rows[row.a]
            assert row.a == latest.a
>           assert row.b == latest.b
E           AssertionError: assert b'9' == None
E            +  where b'9' = Row(a=4317, b=b'9', tok=-9223297786983086897).b
E            +  and   None = Row(cdc_stream_id=b'\x7f\xf0\x00\x00\x00\x00\x00\x00\xf5\xacf\x7f\xb8\x00\x00\x01', cdc_time=UUID('6ceae5c4-e60e-11ee-4a3c-a7dce7bc6779'), cdc_batch_seq_no=0, a=4317, b=None, cdc_operation=2, cdc_ttl=None, tok=9218868437227405312).b

cdc_test.py:667: AssertionError
```

link to full log:
https://jenkins.scylladb.com/job/scylla-enterprise/job/gating-dtest-release-with-consistent-topology-changes/68/artifact/logs-full.release.002/dtest-gw0.log/*view*/

**Comment by tchaikov** [comment] 2024-03-20 05:44
[1710866049202_cdc_test.py--TestCdc--test_change_field_type_with_cdc[Single_cluster].zip](https://github.com/scylladb/scylladb/files/14662408/1710866049202_cdc_test.py--TestCdc--test_change_field_type_with_cdc.Single_cluster.zip)
[dtest-gw0.log.zip](https://github.com/scylladb/scylladb/files/14662409/dtest-gw0.log.zip)

**Comment by kbr-scylla** [comment] 2024-06-06 13:01
Duplicate of https://github.com/scylladb/scylladb/issues/14401

**Closed by kbr-scylla** 2024-06-06 13:01 UTC
