### ISSUE TITLE
when i use select * from table limit 1 read timeout,scylla logs :Memory usage of unpaged query exceeds hard limit

### ISSUE THREAD

**Issue by vlaualv** [scylladb/scylladb#10240] opened 2022-03-18 04:28 UTC
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

Scylla version (or git commit hash): Scylla version 4.3.6-0.20210801.5cd698c89
Cluster size: 2 datacenter ,3 nodes every datacenter
OS: Centos 7

Perform the following query
`cqlsh> select * from ads_search.query_feature WHERE limit 1;    
SyntaxException: line 1:45 no viable alternative at input 'limit'
cqlsh> select * from ads_search.query_feature limit 1;       
ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for ads_search.query_feature - received only 0 responses from 2 CL=LOCAL_QUORUM." info={'received_responses': 0, 'required_responses': 2, 'consistency': 'LOCAL_QUORUM'}`

The scylla log as follows:
`Mar 18 11:40:21 ip-x-x-x-x-bj02 scylla[7302]:  [shard 3] storage_proxy - Exception when communicating with x-x-x-x, to read from ads_search.query_feature: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 104857600 (configured via max_memory_for_unlimited_query_hard_limit))
Mar 18 12:03:57 ip-x-x-x-x-bj02 scylla[7302]:  [shard 3] storage_proxy - Exception when communicating with x-x-x-x, to read from ads_search.query_feature: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 104857600 (configured via max_memory_for_unlimited_query_hard_limit))
Mar 18 12:08:53 ip-x-x-x-x-bj02 scylla[7302]:  [shard 3] storage_proxy - Exception when communicating with x-x-x-x, to read from ads_search.query_feature: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 104857600 (configured via max_memory_for_unlimited_query_hard_limit))
Mar 18 12:13:21 ip-x-x-x-x-bj02 scylla[7302]:  [shard 3] storage_proxy - Exception when communicating with x-x-x-x, to read from ads_search.query_feature: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 104857600 (configured via max_memory_for_unlimited_query_hard_limit))`

but if I query exect key,I can query the result successfully
`cqlsh> select * from ads_search.query_feature WHERE rowkey=0x11;                  

 rowkey | qactr | qcctr | qda  | qinfo | qma  | qta  | qw
--------+-------+-------+------+-------+------+------+------
   0x11 |  0x11 |  null | null |  null | null | null | null`

this problem confused me,
If anyone knows what is happening here

**Comment by avikivity** [comment] 2022-03-20 15:05
Possibly #7689. Did that table experience many deletions? Does major compaction (`nodetool compact`) help?

**Comment by foxhunter72143** [comment] 2022-03-21 02:06
> Possibly #7689. Did that table experience many deletions? Does major compaction (`nodetool compact`) help?

Yes,there were many ttl deletion. I loaded a few GB data ,there were all exipired.When I loaded new data into syclla cluster , the problem was gone .  I did not do major compation. I am not sure that major compaction will help. How can I avoid this problem now ?

**Comment by liucheng-potato** [comment] 2023-03-01 13:33
> > Possibly #7689. Did that table experience many deletions? Does major compaction (`nodetool compact`) help?
> 
> Yes,there were many ttl deletion. I loaded a few GB data ,there were all exipired.When I loaded new data into syclla cluster , the problem was gone . I did not do major compation. I am not sure that major compaction will help. How can I avoid this problem now ?

hi, How did you solve and avoid this problem

**Comment by avikivity** [comment] 2023-03-01 18:26
Sorry, I forgot to follow up. In 5.2 this won't happen.

Closing as duplicate of #7689.

**Closed by avikivity** 2023-03-01 18:26 UTC
