### ISSUE TITLE
Scylla doesn't started after uprade if full cluster was stopped

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#10287] opened 2022-03-28 17:46 UTC
Scylla version init: 4.6.0-0.20220306.2f2d22a86
Scylla upgrading: 5.0.rc2-0.20220322.f3564db94

In 2 scenarios from 3, scylla is not started after upgrade to 5.0 and enabling raft experimental feature.
1, 2 scenarios:
Cluster created with scylla version 4.6. after that it is upgraded to version 5.0. after that 
```
experimental_features: 
 - raft
```
added to all nodes. And then nodes are restarted.
.After that scylla could not be started. because first node could connect to others
```
20:04:47,374 cassandra.pool  WARNING thread.py      :57   | Error attempting to reconnect to 127.0.51.2:9042, scheduling retry in 131.84 seconds: [Errno 111] Tried connecting to [('127.0.51.2', 9042)]. Last error: Connection refused
20:04:51,287 cassandra.pool  WARNING thread.py      :57   | Error attempting to reconnect to 127.0.51.3:9042, scheduling retry in 143.36 seconds: [Errno 111] Tried connecting to [('127.0.51.3', 9042)]. Last error: Connection refused
20:06:28,047 cassandra.pool  WARNING thread.py      :57   | Error attempting to reconnect to 127.0.51.1:9042, scheduling retry in 220.16 seconds: [Errno 111] Tried connecting to [('127.0.51.1', 9042)]. Last error: Connection refused
20:06:59,230 cassandra.pool  WARNING thread.py      :57   | Error attempting to reconnect to 127.0.51.2:9042, scheduling retry in 243.2 seconds: [Errno 111] Tried connecting to [('127.0.51.2', 9042)]. Last error: Connection refused
20:07:14,670 cassandra.pool  WARNING thread.py      :57   | Error attempting to reconnect to 127.0.51.3:9042, scheduling retry in 245.76 seconds: [Errno 111] Tried connecting to [('127.0.51.3', 9042)]. Last error: Connection refused
20:10:08,279 cassandra.pool  WARNING thread.py      :57   | Error attempting to reconnect to 127.0.51.1:9042, scheduling retry in 481.28 seconds: [Errno 111] Tried connecting to [('127.0.51.1', 9042)]. Last error: Connection refused
20:11:02,528 cassandra.pool  WARNING thread.py      :57   | Error attempting to reconnect to 127.0.51.2:9042, scheduling retry in 455.68 seconds: [Errno 111] Tried connecting to [('127.0.51.2', 9042)]. Last error: Connection refused
20:11:20,474 cassandra.pool  WARNING thread.py      :57   | Error attempting to reconnect to 127.0.51.3:9042, scheduling retry in 527.36 seconds: [Errno 111] Tried connecting to [('127.0.51.3', 9042)]. Last error: Connection refused

```

in 3rd scenario, after upgrade each node, first node is stopped, is updated with enabling raft, and started again. Then these actions applied to other nodes one by one. in this scenario all nodes restarted and raft is enabled.

Steps to reproduce:
1. Use test from PR: https://github.com/scylladb/scylla-dtest/pull/2673
2.  execute test with command:
```
$ pytest -vvv -s -p "no:email_plugin" --scylla-version=unstable/branch-5.0:latest upgrade_test.py::TestUpgradeWithRaft
```

**Comment by aleksbykov** [comment] 2022-03-29 18:45
i think the main issue is that when cluster is started with cluster.populate().start() nodes started without bootstrap enabled.
if bootstrap enabled upon node creation, the cluster with raft started successfully

**Comment by roydahan** [comment] 2022-04-18 11:44
@aleksbykov / @kostja, I don't understand if the issue is only relevant to dtest or it also happens in regular upgrade.

**Comment by aleksbykov** [comment] 2022-04-19 12:54
I think this issue is related and depend on the issue https://github.com/scylladb/scylla/issues/10355.
For that moment we have only dtest upgrade test as PoC.

**Comment by roydahan** [comment] 2022-05-18 10:03
@kostja From what I understand, the issue is only when you set configuration to use raft and then fully stop the cluster and start it.

If that's the case, is it even a real issue?
We can define that the upgrade procedure should be as in "3rd scenario" gradually move nodes one by one.

**Comment by kostja** [comment] 2022-10-14 18:19
@aleksbykov please re-test, should be addressed in the latest master

**Comment by kostja** [comment] 2023-01-13 11:53
Closing - no feedback. Please reopen if there is more input. Thanks!

**Closed by kostja** 2023-01-13 11:53 UTC
Labels: raft
