### ISSUE TITLE
Need a guardrails mechanism for incorrect TWCS settings

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#11439] opened 2022-09-02 18:35 UTC
HEAD https://github.com/scylladb/scylladb/commit/2c46c246083688b550eb1bef2421c88e8ffb59f2

Every now and then we end up in a situation on where users of TWCS end up underestimating their window buckets when using TWCS. Unfortunately, scenarios on which one employs a `default_time_to_live` setting of 1 year but a window size of `30 minutes` are not rarely enough.

Such configuration is known to only make harm to a workload: As more and more windows are created, the number of SSTables will grow in the same pace, and the situation will only get worse as the number of shards increase. 

We often see in the field a situation on which a TWCS misconfiguration causes several stalls, IO pressure, repair to introduce latency spikes and backups to take forever due to the overhead caused by deduplicating too many tiny SSTables.

We need a mechanism to forbid - or at least WARN - the user of the consequences of his choices. In particular, I would say that any TWCS table with over 20 windows is likely configured incorrectly and - as such - we likely need to start responding back to the user with insights.

One particular example where we have the TWCS window being (correctly) auto-configured is when CDC is enabled for a table. Depending on the specified TTL setting passed, the CDC log table will auto-create a TWCS table with the optimal settings. So we already have the mechanisms to determine if a setting makes sense or not, we now have to stop these recurring scenarios from repeating. :-)

**Comment by raphaelsc** [comment] 2022-09-03 02:56
Agree completely with the sentiment. Ideas were proposed here: https://github.com/scylladb/scylladb/issues/6923

**Comment by raphaelsc** [comment] 2022-09-03 02:56
We need to raise the priority.

**Comment by avikivity** [comment] 2022-09-04 10:17
Closing as duplicate of #6923

**Comment by avikivity** [comment] 2022-09-04 10:18
(but agree it should be scheduled, @slivne )

**Closed by avikivity** 2022-09-04 10:17 UTC
