### ISSUE TITLE
TestUpdateClusterLayout::test_simple_kill_node_while_decommissioning driver times out after waiting for 30 seconds when connecting the decomissioned server

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#17124] opened 2024-02-02 09:15 UTC
see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6266

```
cassandra.OperationTimedOut: errors={'127.0.94.3:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.94.3:9042
..
        node2.start(wait_other_notice=True, wait_for_binary_proto=True)
        with self.cql_cluster_session(node2) as session2:
>           result = list(session2.execute("SELECT * FROM ks.cf"))
```

servers stopped printing logging messages after the decommissioned node restart and marked "UN"

node1.log:
```
INFO  2024-02-01 05:15:08,030 [shard 0: gms] gossip - Node 127.0.94.2 has restarted, now UP, status = NORMAL
ERROR 2024-02-01 05:15:08,030 [shard 1:strm] rpc - client 127.0.94.2:7000: client connection dropped: connection is closed
WARN  2024-02-01 05:15:08,030 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.0.94.2, status = failed: seastar::rpc::closed_error (connection is closed)
...
INFO  2024-02-01 05:15:08,034 [shard 0: gms] storage_service - handle_state_normal for 127.0.94.2/08db32dd-332e-4484-8c7f-aeefd071d3ef finished
INFO  2024-02-01 05:15:08,039 [shard 0:comp] compaction - [Compact system.scylla_local ddac8970-c0c0-11ee-8df5-eb979568a510] Compacting [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-r3bs9exr/test/node1/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3gd9_0el8_07i2825pu6t4nrybdc-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-r3bs9exr/test/node1/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3gd9_0ekw_07i2925pu6t4nrybdc-big-Data.db:level=0:origin=compaction]
INFO  2024-02-01 05:15:08,045 [shard 0:comp] compaction - [Compact system.scylla_local ddac8970-c0c0-11ee-8df5-eb979568a510] Compacted 2 sstables to [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-r3bs9exr/test/node1/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3gd9_0el8_08kn425pu6t4nrybdc-big-Data.db:level=0]. 12kB to 6476 bytes (~51% of original) in 4ms = 3MB/s. ~256 total partitions merged to 5.
INFO  2024-02-01 05:15:09,131 [shard 0:strm] raft_group0 - losing leadership
INFO  2024-02-01 05:15:38,727 [shard 0:main] compaction_manager - Asked to stop
```

node2.log
```
INFO  2024-02-01 05:15:07,638 [shard 0:main] init - Scylla API server listening on 127.0.94.2:10000 ...
...
INFO  2024-02-01 05:15:08,458 [shard 0:main] migration_manager - Schema agreement check passed.
INFO  2024-02-01 05:15:09,131 [shard 0:main] raft_group0 - gaining leadership
INFO  2024-02-01 05:15:38,727 [shard 0:main] compaction_manager - Asked to stop
```
node3.log
```
INFO  2024-02-01 05:15:08,629 [shard 0:comp] compaction - [Compact system.scylla_local de069050-c0c0-11ee-9823-a9c5734f9e90] Compacting [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-r3bs9exr/test/node3/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3gd9_0el8_3q68w2bag1mysaf4i8-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-r3bs9exr/test/node3/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3gd9_0ekv_5p49d2bag1mysaf4i8-big-Data.db:level=0:origin=compaction]
INFO  2024-02-01 05:15:08,634 [shard 0:comp] compaction - [Compact system.scylla_local de069050-c0c0-11ee-9823-a9c5734f9e90] Compacted 2 sstables to [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-r3bs9exr/test/node3/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3gd9_0el8_3qte92bag1mysaf4i8-big-Data.db:level=0]. 12kB to 6481 bytes (~52% of original) in 4ms = 3MB/s. ~256 total partitions merged to 5.
INFO  2024-02-01 05:15:38,727 [shard 0:main] compaction_manager - Asked to stop
```

it is expected that the driver was also trying to connect to node3, because we use `cluster.connect(wait_for_all_pools=True)` in `dtest_setup.py`. but the funny thing is that the it somehow failed to connect to node3.

**Comment by tchaikov** [comment] 2024-02-02 09:17
[1706764541750_update_cluster_layout_tests.py TestUpdateClusterLayout test_simple_kill_node_while_decommissioning.zip](https://github.com/scylladb/scylladb/files/14137934/1706764541750_update_cluster_layout_tests.py.TestUpdateClusterLayout.test_simple_kill_node_while_decommissioning.zip)

**Comment by bhalevy** [comment] 2024-02-04 14:17
The issue description above got garbled due to missing `` ` ``

**Comment by tchaikov** [comment] 2024-02-04 14:23
thank you for pointing out this. fixed.

**Comment by tchaikov** [comment] 2024-02-05 04:41
`test_simple_decommission_node_while_query_info` this time. see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6374/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_decommission_node_while_query_info_2_/

**Comment by Annamikhlin** [comment] 2024-02-07 08:58
seen also on https://jenkins.scylladb.com/job/scylla-master/job/next/7193/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Build___x86___dtest___test_simple_decommission_node_while_query_info_2_/

**Comment by fruch** [comment] 2024-02-07 16:08
history show this issue with test_simple_kill_node_while_decommissioning, is happening since September:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/6a77bc60-c5d2-11ee-81c7-3986d18dafd5

test_simple_decommission_node_while_query_info was refactor recently in https://github.com/scylladb/scylla-dtest/pull/3814 by @bhalevy, so it's probably something new as part of that.

**Comment by denesb** [comment] 2024-02-08 13:00
Also seen in https://github.com/scylladb/scylladb/pull/16927.

**Comment by nyh** [comment] 2024-02-19 18:06
Seen again in CI run: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/7992/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/FullDtest___full_split001___test_simple_decommission_node_while_query_info_2_/

**Comment by bhalevy** [comment] 2024-02-20 08:28
@xemul since you're looking into issues with decommissioning (from the tablets path), can you please look into this issue too?
It's hurting us in CI mostly, but it we need to understand the root cause and see how serious it is.

**Comment by bhalevy** [comment] 2024-02-25 14:35
Why is it ok to see client-side errors during topology changes?
We need to fix that.

Cc @avelanarius

**Comment by avikivity** [comment] 2024-02-26 16:22
Raising to P0.

**Comment by Annamikhlin** [comment] 2024-02-26 19:12
seen again in:
https://jenkins.scylladb.com/job/scylla-master/job/next/7291/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Build___x86___dtest___test_simple_decommission_node_while_query_info_2_/

**Comment by xemul** [comment] 2024-03-04 14:11
https://github.com/scylladb/scylla-dtest/pull/3985 doesn't help, it still happens rarely

**Comment by xemul** [comment] 2024-03-04 17:15
Driver complains
```
E   cassandra.OperationTimedOut: errors={'127.0.79.1:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.79.1:9042
```

In node-1 logs I have

```
20:05:30,608 [shard 0:strm] storage_service - decommission[077e2627-bf0d-41bd-af6c-dee41073f850]: Added node=127.0.79.2 as leaving node, coordinator=127.0.79.2
20:05:43,588 [shard 0:stmt] cql_server - Processing EXECUTE request from 127.0.0.1:52688
20:05:43,612 [shard 0: gms] gossip - Removed endpoint 127.0.79.2
20:06:43,589 [shard 0:stmt] cql_server - Done processing EXECUTE request from 127.0.0.1:52688
20:06:43,589 [shard 0:stmt] cql_server - 127.0.0.1:52688: request resulted in read_timeout_error, stream 92, code 4608, message [Operation timed out for ks.cf - received only 1 responses from 2 CL=TWO.]
```

**Comment by fruch** [comment] 2024-03-04 18:45
> Driver complains
> ```
> E   cassandra.OperationTimedOut: errors={'127.0.79.1:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.79.1:9042
> ```
> 
> In node-1 logs I have
> 
> ```
> 20:05:30,608 [shard 0:strm] storage_service - decommission[077e2627-bf0d-41bd-af6c-dee41073f850]: Added node=127.0.79.2 as leaving node, coordinator=127.0.79.2
> 20:05:43,588 [shard 0:stmt] cql_server - Processing EXECUTE request from 127.0.0.1:52688
> 20:05:43,612 [shard 0: gms] gossip - Removed endpoint 127.0.79.2
> 20:06:43,589 [shard 0:stmt] cql_server - Done processing EXECUTE request from 127.0.0.1:52688
> 20:06:43,589 [shard 0:stmt] cql_server - 127.0.0.1:52688: request resulted in read_timeout_error, stream 92, code 4608, message [Operation timed out for ks.cf - received only 1 responses from 2 CL=TWO.]
> ```

So what's holding this query for that long ?

**Comment by xemul** [comment] 2024-03-05 05:14
> So what's holding this query for that long ?

This is what I'm currently investigating

**Comment by xemul** [comment] 2024-03-05 05:16
Apparently one of the replicas that coordinator tried to query was the decommissioned one and it didn't respond

**Comment by xemul** [comment] 2024-03-05 07:22
node1 logs:
```
09:55:20,504 [shard 0:stmt] cql_server - Processing EXECUTE 0/386 request from 127.0.0.1:60216
09:55:20,530 [shard 0: gms] seastar - stopped client socket from 127.0.85.1:65066 to 127.0.85.2:7000
09:55:20,530 [shard 0:stmt] seastar - stopped client socket from 127.0.85.1:65530 to 127.0.85.2:7000
09:55:20,530 [shard 0:main] seastar - stopped client socket from 127.0.85.1:52920 to 127.0.85.2:7000
09:55:20,530 [shard 1:stmt] seastar - stopped client socket from 127.0.85.1:49867 to 127.0.85.2:7000
09:55:20,530 [shard 1:stmt] seastar - stopped client socket from 127.0.85.1:53841 to 127.0.85.2:7000
09:55:20,530 [shard 1:strm] seastar - stopped client socket from 127.0.85.1:63599 to 127.0.85.2:7000
09:55:20,530 [shard 0:strm] seastar - stopped client socket from 127.0.85.1:61294 to 127.0.85.2:7000

09:55:30,317 [shard 0: gms] seastar - stopped client socket from 127.0.85.1:59698 to 127.0.85.2:7000
09:55:30,317 [shard 0:main] seastar - stopped client socket from 127.0.85.1:58596 to 127.0.85.2:7000
09:55:30,317 [shard 1:strm] seastar - stopped client socket from 127.0.85.1:61301 to 127.0.85.2:7000
09:55:30,317 [shard 0:strm] seastar - stopped client socket from 127.0.85.1:57678 to 127.0.85.2:7000

09:56:20,505 [shard 0:stmt] cql_server - Done processing EXECUTE 1/389 request from 127.0.0.1:60216
09:56:20,505 [shard 0:stmt] cql_server - 127.0.0.1:60216: request resulted in read_timeout_error, stream 51, code 4608, message [Operation timed out for ks.cf - received only 1 responses from 2 CL=TWO.]
```

node2 logs:
```
09:55:08,629 [shard 0:strm] api - decommission
09:55:20,530 [shard 0:strm] seastar - stopped server socket from 127.0.85.1:65066
09:55:20,530 [shard 1:strm] seastar - stopped server socket from 127.0.85.1:63599
09:55:20,530 [shard 1:strm] seastar - stopped server socket from 127.0.85.1:49867
09:55:20,530 [shard 1:strm] seastar - stopped server socket from 127.0.85.1:53841
09:55:20,530 [shard 0:strm] seastar - stopped server socket from 127.0.85.1:52920
09:55:20,530 [shard 0:strm] seastar - stopped server socket from 127.0.85.1:61294
09:55:20,530 [shard 0:strm] seastar - stopped server socket from 127.0.85.1:65530

09:55:30,145 [shard 0:strm] storage_service - Stop transport: starts
09:55:30,146 [shard 0:strm] storage_service - Stop transport: shutdown rpc and cql server done
09:55:30,316 [shard 0:strm] storage_service - Stop transport: stop_gossiping done
09:55:30,317 [shard 0:strm] seastar - stopped server socket from 127.0.85.1:59698
09:55:30,317 [shard 0:strm] seastar - stopped server socket from 127.0.85.1:57678
09:55:30,317 [shard 0:strm] seastar - stopped server socket from 127.0.85.1:58596
09:55:30,317 [shard 1:strm] seastar - stopped server socket from 127.0.85.1:61301
09:55:30,317 [shard 0:strm] storage_service - Stop transport: shutdown messaging_service done
09:55:30,317 [shard 0:strm] storage_service - Stop transport: shutdown stream_manager done
09:55:30,317 [shard 0:strm] storage_service - Stop transport: done
```

Summary:
09:55:08,629 node2 decommission starts
09:55:20,504 node1 query starts
09:55:20,530 node2 closes some connections from node1
09:55:30,145 node2 starts stopping transport (after unbootstrapping)
09:55:30,317 node2 closes remaining connections from node1
09:56:20,505 node1 times-out processing query

**Comment by xemul** [comment] 2024-03-05 08:36
```
11:22:15,843 [shard 1:stmt] cql_server - Processing EXECUTE 0/390 request from 127.0.0.1:42062
11:22:15,843 [shard 1:stmt] rpc - send READ_DATA to 127.0.67.2:0      // multiple
11:22:15,846 [shard 1:stmt] rpc - send READ_DIGEST to 127.0.67.2:0    // multiple
11:22:15,859 [shard 0: gms] gossip - Node 127.0.67.2 will be removed from gossip at [2024-03-08 11:22:14]: (expire = 1709886134996526720, now = 1709626935859056195, diff = 259199 seconds)
11:22:15,859 [shard 0: gms] storage_service - Removing tokens {...} for 127.0.67.2
11:22:15,863 [shard 1:stmt] rpc - send READ_DATA to 127.0.67.2:0      // multiple
11:22:15,863 [shard 1:stmt] rpc - send READ_DIGEST to 127.0.67.2:0    // multiple
11:22:15,865 [shard 0: gms] gossip - Removed endpoint 127.0.67.2
11:22:15,865 [shard 0: gms] gossip - InetAddress 127.0.67.2 is now DOWN, status = LEFT
11:22:15,865 [shard 0:strm] seastar - stopped client socket from 127.0.67.1:60194 to 127.0.67.2:7000
11:22:15,865 [shard 0:main] seastar - stopped client socket from 127.0.67.1:55812 to 127.0.67.2:7000
11:22:15,865 [shard 0:stmt] seastar - stopped client socket from 127.0.67.1:63380 to 127.0.67.2:7000
11:22:15,865 [shard 0: gms] seastar - stopped client socket from 127.0.67.1:50892 to 127.0.67.2:7000
11:22:15,865 [shard 1:stmt] seastar - stopped client socket from 127.0.67.1:54689 to 127.0.67.2:7000
11:22:15,866 [shard 1:stmt] rpc - message 3 to 127.0.67.2:0 failed with seastar::rpc::closed_error (connection is closed)    // multiple
11:22:15,866 [shard 1:stmt] rpc - message 5 to 127.0.67.2:0 failed with seastar::rpc::closed_error (connection is closed)    // multiple
                            ^^^ this is the last message about RPC failure to node 67.2

11:22:15,866 [shard 1:strm] seastar - stopped client socket from 127.0.67.1:62397 to 127.0.67.2:7000
11:22:15,866 [shard 1:stmt] seastar - stopped client socket from 127.0.67.1:50003 to 127.0.67.2:7000
11:22:16,858 [shard 1:strm] rpc - send GOSSIP_ECHO to 127.0.67.2:0

+10 sec
11:22:25,003 [shard 0:strm] storage_service - decommission[6e00cf02-ef34-4163-8065-23f0ca571e20]: Started to check if nodes={127.0.67.2} have left the cluster, coordinator=127.0.67.2
11:22:25,003 [shard 0:strm] storage_service - decommission[6e00cf02-ef34-4163-8065-23f0ca571e20]: Finished to check if nodes={127.0.67.2} have left the cluster, coordinator=127.0.67.2
11:22:25,003 [shard 0:strm] storage_service - decommission[6e00cf02-ef34-4163-8065-23f0ca571e20]: Marked ops done from coordinator=127.0.67.2
11:22:25,008 [shard 0:strm] rpc - send RAFT_APPEND_ENTRIES to 127.0.67.2:0
11:22:25,644 [shard 0:strm] seastar - stopped server socket from 127.0.67.2:61160
11:22:25,644 [shard 0:strm] seastar - stopped server socket from 127.0.67.2:60168
11:22:25,644 [shard 0:strm] seastar - stopped server socket from 127.0.67.2:50518
11:22:25,644 [shard 0: gms] seastar - stopped client socket from 127.0.67.1:51680 to 127.0.67.2:7000
11:22:25,644 [shard 0:strm] seastar - stopped server socket from 127.0.67.2:51434
11:22:25,644 [shard 0:strm] seastar - stopped server socket from 127.0.67.2:65474
11:22:25,644 [shard 0:main] seastar - stopped client socket from 127.0.67.1:63482 to 127.0.67.2:7000
11:22:25,644 [shard 0:strm] seastar - stopped client socket from 127.0.67.1:59708 to 127.0.67.2:7000
11:22:25,644 [shard 1:strm] seastar - stopped server socket from 127.0.67.2:61331
11:22:25,644 [shard 1:strm] seastar - stopped server socket from 127.0.67.2:64683
11:22:25,644 [shard 1:strm] seastar - stopped client socket from 127.0.67.1:60679 to 127.0.67.2:7000
11:22:25,644 [shard 1:strm] seastar - stopped server socket from 127.0.67.2:61417
11:22:25,644 [shard 1:strm] seastar - stopped server socket from 127.0.67.2:52147

+50 sec
11:23:15,843 [shard 1:stmt] cql_server - Done processing EXECUTE 1/391 request from 127.0.0.1:42062
11:23:15,843 [shard 1:stmt] cql_server - 127.0.0.1:42062: request resulted in read_timeout_error, stream 94, code 4608, message [Operation timed out for ks.cf - received only 1 responses from 2 CL=TWO.]
11:23:15,844 [shard 1:stmt] cql_server - Advertising disconnection of CQL client 127.0.0.1:42062
```

despite node2 failed all READ_DATA/READ_DIGEST requests from node1, it took node1 1 more minute to time-out its reading

**Comment by xemul** [comment] 2024-03-05 10:17
Timeout exception is raised from `digest_read_resolver::on_timeout()`

**Comment by xemul** [comment] 2024-03-05 11:11
Closed connection from decommissioned node don't fail the request instantly because of

```
    void on_error(gms::inet_address ep, error_kind kind) override {
        if (waiting_for(ep)) {
            _failed++;
        }
        if (kind == error_kind::DISCONNECT && _block_for == _target_count_for_cl) {
            // if the error is because of a connection disconnect and there is no targets to speculate
            // wait for timeout in hope that the client will issue speculative read
            // FIXME: resolver should have access to all replicas and try another one in this case
            return;
        }
```

`_block_for == 2, _target_count_for_cl == 2`

**Comment by xemul** [comment] 2024-03-06 14:10
OK, driver-side has configurable (off by default) speculative execution. Turning it ON fixes the issue

**Comment by xemul** [comment] 2024-03-07 05:49
dtest fix merged

**Closed by xemul** 2024-03-07 05:49 UTC
Labels: triage/master, P0, symptom/ci stability

**Comment by kostja** [comment] 2024-06-04 16:17
@avikivity if you think that this sort of "fix" is adequate then client-side fencing is indeed not a priority.

**Comment by mykaul** [comment] 2024-07-18 12:33
@fruch - can it be backported to 5.4.x branch?

**Comment by kbr-scylla** [comment] 2024-07-18 12:39
So apparently the fix did not address the original report -- which was about `test_simple_kill_node_while_decommissioning` -- instead it addressed all the other reports which were posted in comments -- about a different test, `test_simple_decommission_node_while_query_info`.

And now we pretend that `test_simple_kill_node_while_decommissioning` was fixed, while the fixed thing is something else entirely.
