### ISSUE TITLE
Reactor stall 1304ms was detected during node decommissioning with 1000 keyspaces

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#12332] opened 2022-12-15 13:06 UTC
## Installation details

Kernel Version: 5.15.0-1026-aws
Scylla version (or git commit hash): `5.2.0~dev-20221210.e47794ed9832` with build-id `a0d3f077099c66bf6c75707e386c6be3ba2c431f`

Cluster size: 6 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- longevity-1000-keyspaces-master-db-node-8ca4e603-9 (3.252.249.172 | 10.4.1.149) (shards: 30)
- longevity-1000-keyspaces-master-db-node-8ca4e603-8 (34.243.249.154 | 10.4.0.113) (shards: 30)
- longevity-1000-keyspaces-master-db-node-8ca4e603-7 (52.30.152.123 | 10.4.2.35) (shards: 30)
- longevity-1000-keyspaces-master-db-node-8ca4e603-6 (52.18.179.107 | 10.4.1.170) (shards: 30)
- longevity-1000-keyspaces-master-db-node-8ca4e603-5 (34.246.174.147 | 10.4.3.150) (shards: 30)
- longevity-1000-keyspaces-master-db-node-8ca4e603-4 (34.244.167.236 | 10.4.2.130) (shards: 30)
- longevity-1000-keyspaces-master-db-node-8ca4e603-3 (54.229.118.138 | 10.4.1.207) (shards: 30)
- longevity-1000-keyspaces-master-db-node-8ca4e603-2 (52.209.53.73 | 10.4.0.112) (shards: 30)
- longevity-1000-keyspaces-master-db-node-8ca4e603-1 (52.215.203.239 | 10.4.1.241) (shards: 30)

OS / Image: `ami-01edd05a94c7ebf24` (aws: eu-west-1)

Test: `longevity-multi-keyspaces-60h-test`
Test id: `8ca4e603-75fa-41ca-96c9-662c5fce53a5`
Test name: `scylla-master/raft/longevity-multi-keyspaces-60h-test`
Test config file(s):

- [longevity-multi-keyspaces.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d007cef368b29d19563df5b4933744ae44448cb5/test-cases/longevity/longevity-multi-keyspaces.yaml)

## Issue description
Test configure 1000 keyspaces. While node4 was decommissioning, large reactor stall was detected:
```
2022-12-13T10:26:30+00:00 longevity-1000-keyspaces-master-db-node-8ca4e603-4     !INFO | scylla[5910]: Reactor stalled for 1304 ms on shard 0. Backtrace: 0x4fd4f73 0x4fd4360 0x4fd5710 0x3cb4f 0x1bd70e8 0x1bd5be4 0x1bc9c5b 0x1bc297f 0x1bd8cd2 0x4fa5ed5 0x4fa6242 0x4fa7a29 0x4fa7cd4 0x4faa691 0x37b07f0 0x38bae7c 0x11a31da 0x4fe5794 0x4fe69d7 0x4fe5d39 0x4f8c6b5 0x4f8b828 0x10eb614 0x10ed120 0x10e9d75 0x2750f 0x275c8 0x10e7ee4
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:793
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:812
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1338
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1115
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1132
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1374
?? ??:0
logalloc::region_impl::alloc_small(logalloc::region_impl::object_descriptor const&, unsigned int, unsigned long) at ./utils/logalloc.cc:1688
operator() at ./utils/logalloc.cc:1879
 (inlined by) void logalloc::region_impl::for_each_live<logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*, unsigned long)#1}>(logalloc::segment*, logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*, unsigned long)#1}&&) at ./utils/logalloc.cc:1725
 (inlined by) logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&) at ./utils/logalloc.cc:1878
logalloc::region_impl::compact() at ./utils/logalloc.cc:2218
 (inlined by) logalloc::tracker::impl::compact_and_evict_locked(unsigned long, unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:2699
logalloc::tracker::impl::reclaim_locked(unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:2602
 (inlined by) logalloc::tracker::impl::reclaim(unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:2581
logalloc::tracker::reclaim(unsigned long) at ./utils/logalloc.cc:558
 (inlined by) logalloc::tracker::reclaim(seastar::memory::reclaimer::request) at ./utils/logalloc.cc:2322
 (inlined by) operator() at ./utils/logalloc.cc:546
 (inlined by) seastar::memory::reclaiming_result std::__invoke_impl<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request>(std::__invoke_other, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request>, seastar::memory::reclaiming_result>::type std::__invoke_r<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request>(logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:114
 (inlined by) std::_Function_handler<seastar::memory::reclaiming_result (seastar::memory::reclaimer::request), logalloc::tracker::tracker()::$_0>::_M_invoke(std::_Any_data const&, seastar::memory::reclaimer::request&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:290
std::function<seastar::memory::reclaiming_result (seastar::memory::reclaimer::request)>::operator()(seastar::memory::reclaimer::request) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:591
 (inlined by) seastar::memory::reclaimer::do_reclaim(unsigned long) at ./build/release/seastar/./seastar/include/seastar/core/memory.hh:199
 (inlined by) seastar::memory::cpu_pages::run_reclaimers(seastar::memory::reclaimer_scope, unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1147
 (inlined by) seastar::memory::cpu_pages::maybe_reclaim() at ./build/release/seastar/./seastar/src/core/memory.cc:730
seastar::memory::cpu_pages::allocate_large_and_trim(unsigned int) at ./build/release/seastar/./seastar/src/core/memory.cc:769
seastar::memory::cpu_pages::allocate_large(unsigned int) at ./build/release/seastar/./seastar/src/core/memory.cc:791
 (inlined by) seastar::memory::allocate_large(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1342
seastar::memory::allocate(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1403
operator new(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:2065
std::__new_allocator<nonwrapping_interval<dht::token> >::allocate(unsigned long, void const*) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/new_allocator.h:137
 (inlined by) std::allocator<nonwrapping_interval<dht::token> >::allocate(unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/allocator.h:188
 (inlined by) std::allocator_traits<std::allocator<nonwrapping_interval<dht::token> > >::allocate(std::allocator<nonwrapping_interval<dht::token> >&, unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/alloc_traits.h:464
 (inlined by) std::_Vector_base<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >::_M_allocate(unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_vector.h:378
 (inlined by) void std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >::_M_realloc_insert<nonwrapping_interval<dht::token>&>(__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, nonwrapping_interval<dht::token>&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/vector.tcc:453
 (inlined by) nonwrapping_interval<dht::token>& std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >::emplace_back<nonwrapping_interval<dht::token>&>(nonwrapping_interval<dht::token>&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/vector.tcc:123
 (inlined by) service::storage_service::stream_ranges(std::unordered_map<seastar::basic_sstring<char, unsigned int, 15u, true>, std::unordered_multimap<nonwrapping_interval<dht::token>, gms::inet_address, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, gms::inet_address> > >, std::hash<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::equal_to<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, std::unordered_multimap<nonwrapping_interval<dht::token>, gms::inet_address, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, gms::inet_address> > > > > >) at ./service/storage_service.cc:3156
service::storage_service::unbootstrap() at ./service/storage_service.cc:2944
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/coroutine:244
 (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:120
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2486
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2923
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3092
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2975
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:265
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:156
scylla_main(int, char**) at ./main.cc:526
std::function<int (int, char**)>::operator()(int, char**) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:591
main at ./main.cc:1791
?? ??:0
?? ??:0
_start at ??:?
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 8ca4e603-75fa-41ca-96c9-662c5fce53a5`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=8ca4e603-75fa-41ca-96c9-662c5fce53a5)
- Show all stored logs command: `$ hydra investigate show-logs 8ca4e603-75fa-41ca-96c9-662c5fce53a5`

Monitoring: http://54.247.23.190:3000/d/K64kPG54z/longevity-multi-keyspaces-60h-test-scylla-per-server-metrics-nemesis-master?from=1670926141013&to=1670991329850&var-by=dc&var-cluster=&var-dc=All&var-node=All&var-shard=All&var-mount_point=%2Fvar%2Flib%2Fscylla&var-func=sum&var-dash_version=master&var-all_scyllas_versions=All&var-count_dc=All&var-scylla_version=master&var-monitoring_version=4.1.0&orgId=1

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/raft/job/longevity-multi-keyspaces-60h-test/2/)

**Comment by aleksbykov** [comment] 2022-12-15 16:38
https://cloudius-jenkins-test.s3.amazonaws.com/8ca4e603-75fa-41ca-96c9-662c5fce53a5/node4.log.tar.gz

**Comment by mykaul** [comment] 2022-12-18 12:01
Did it happen in 5.1? Is it a regression?

**Comment by roydahan** [comment] 2022-12-18 12:13
Probably not a regression, but we can check.

**Comment by bhalevy** [comment] 2022-12-18 12:21
Related to #11005

**Comment by aleksbykov** [comment] 2022-12-18 14:51
issue reproduced without raft:
all logs: https://cloudius-jenkins-test.s3.amazonaws.com/1e904399-a48c-48d5-9d6e-154ddfd1cdc0/20221218_134206/db-cluster-1e904399.tar.gz

**Comment by avikivity** [comment] 2022-12-18 14:56
I guess it's this:

```c++
future<>
storage_service::stream_ranges(std::unordered_map<sstring, std::unordered_multimap<dht::token_range, inet_address>> ranges_to_stream_by_keyspace) {
```


1000 keyspaces * all vnodes = a lot.

We should iterate over keyspaces one at a time, planning all keyspaces in advance is too much. We should calculate ranges_to_stream when we transfer a keyspace.

**Comment by avikivity** [comment] 2022-12-18 14:57
Assigning it low priority. Few users have 1000 keyspaces.

**Closed** 2022-12-19 16:52 UTC
Labels: bug, latency-low, master/triage

**Comment by avikivity** [comment] 2022-12-19 18:23
So much for low priority...

**Comment by denesb** [comment] 2022-12-20 05:05
> So much for low priority...

Maybe there was a priority inversion.

**Comment by denesb** [comment] 2022-12-21 11:59
I had another look at this @avikivity and I'm not sure we stall because of copying so many elements in the vector. The stall is in memory reclaim. Maybe we need a large allocation which triggers costly reclaim and LSA compaction, which is the direct cause of the stall.

**Comment by avikivity** [comment] 2022-12-21 12:28
Agree, maybe we need to use a non-contiguous container. Do we know the large allocation size?

**Comment by denesb** [comment] 2022-12-21 12:51
I checked the logs and there is now large alloc warning.

**Comment by avikivity** [comment] 2023-01-10 17:54
Minor, might not actually be a real fix, so not backporting.
