### ISSUE TITLE
offline-install: Failed to get D-Bus connection: No such file or directory on CentOS 7

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylladb#7071] opened 2020-08-20 00:02 UTC
*Installation details*
Scylla version (or git commit hash):  scylla-unified-package-0.20200819.2e1499ee93f.tar.gz / 666.development-0.20200819.2e1499ee93f
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description

The offline installation failed for a dbus connection error.

#### prepare

- curl http://downloads.scylladb.com.s3.amazonaws.com/relocatable/unstable/master/latest/scylla-unified-package-0.20200819.2e1499ee93f.tar.gz -o scylla-unified-package-0.20200819.2e1499ee93f.tar.gz
- tar xvfz scylla-unified-package-0.20200819.2e1499ee93f.tar.gz

#### install error

```
[scylla-test@amos-centos7-offline-installer offline_install]$ time ./install.sh --nonroot --prefix `pwd`/install_root
Failed to get D-Bus connection: No such file or directory

real	1m56.806s
user	0m0.978s
sys	0m7.878s
[scylla-test@amos-centos7-offline-installer offline_install]$ echo $?
1
```

```
[scylla-test@amos-centos7-offline-installer offline_install]$ ls
install_root  offline-install.sh  scylla-jmx      scylla-tools
install.sh    scylla              scylla-python3  scylla-unified-package-0.20200819.2e1499ee93f.tar.gz

[scylla-test@amos-centos7-offline-installer offline_install]$ cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

[scylla-test@amos-centos7-offline-installer offline_install]$ rpm -qa |grep dbus
dbus-glib-0.100-7.el7.x86_64
python-slip-dbus-0.4.0-4.el7.noarch
dbus-libs-1.10.24-14.el7_8.x86_64
dbus-1.10.24-14.el7_8.x86_64
dbus-python-1.1.1-9.el7.x86_64
[scylla-test@amos-centos7-offline-installer offline_install]$ ps aux|grep dbus
dbus       463  0.0  0.0  66472  2196 ?        Ssl  23:31   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
```

```
[scylla-test@amos-centos7-offline-installer install_root]$ ./bin/scylla --version
666.development-0.20200819.2e1499ee93f
```

/CC @penberg @roydahan @slivne

**Comment by amoskong** [comment] 2020-08-20 02:53
The error is raised in executing `systemctl --user daemon-reload` in the end of install.sh

```
[scylla-test@amos-centos7-offline-installer scylla]$ sh -x ./install.sh --nonroot --prefix `pwd`/install_root
....
....
+ sed -i -e 's#^SCYLLA_ARGS="#SCYLLA_ARGS="--workdir /home/scylla-test/offline_install/scylla/install_root #g' /home/scylla-test/offline_install/scylla/install_root//etc/sysconfig/scylla-server
+ touch /home/scylla-test/offline_install/scylla/install_root/SCYLLA-NONROOT-FILE
+ systemctl --user daemon-reload
Failed to get D-Bus connection: No such file or directory
[scylla-test@amos-centos7-offline-installer scylla]$ 
```

**Comment by penberg** [comment] 2020-08-20 05:19
@syuu1228 @avikivity How do these user services in cgroup work? Is reloading the systemctl daemon supposed to work when the `--user` flag is passed?

**Comment by avikivity** [comment] 2020-08-20 07:24
Yes, it's supposed to work.

@amoskong are you testing in a vm or a container? some (most) containers don't have systemd.

**Comment by amoskong** [comment] 2020-08-20 07:54
> Yes, it's supposed to work.
> 
> @amoskong are you testing in a vm or a container? some (most) containers don't have systemd.

I'm testing in a GCE instance (centos7), which has systemd.

**Comment by avikivity** [comment] 2020-08-20 11:26
Ho hum. On centos 7, `systemctl --user status` fails in the same way. It works on my Fedora machine.

From systemd rpm changelog:

```
* Wed Aug 12 2015 Lukas Nykryn <lnykryn@redhat.com> - 219-11
- everything: remove traces of --user (#1071363)
```

So it looks like --user doesn't work on CentOS 7.

I don't want to add a new supervisor (like we did for the docker image). Let's document that supervisor support is only for CentOS 8 or above, and not run set up the .service files. The user will have to run them manually. We'll recommend RHEL 8/CentOS 8 for such installs.

/cc @tzach

**Comment by amoskong** [comment] 2020-08-21 00:19
> Ho hum. On centos 7, `systemctl --user status` fails in the same way. It works on my Fedora machine.
> 
> From systemd rpm changelog:
> 
> ```
> * Wed Aug 12 2015 Lukas Nykryn <lnykryn@redhat.com> - 219-11
> - everything: remove traces of --user (#1071363)
> ```
> 
> So it looks like --user doesn't work on CentOS 7.
> 
> I don't want to add a new supervisor (like we did for the docker image). Let's document that supervisor support is only for CentOS 8 or above, and not run set up the .service files. The user will have to run them manually. We'll recommend RHEL 8/CentOS 8 for such installs.
> 
> /cc @tzach

Thanks, I will recheck with CentOS8.

**Comment by amoskong** [comment] 2020-08-21 02:36
> > Ho hum. On centos 7, `systemctl --user status` fails in the same way. It works on my Fedora machine.
> > From systemd rpm changelog:
> > ```
> > * Wed Aug 12 2015 Lukas Nykryn <lnykryn@redhat.com> - 219-11
> > - everything: remove traces of --user (#1071363)
> > ```
> > 
> > 
> > So it looks like --user doesn't work on CentOS 7.
> > I don't want to add a new supervisor (like we did for the docker image). Let's document that supervisor support is only for CentOS 8 or above, and not run set up the .service files. The user will have to run them manually. We'll recommend RHEL 8/CentOS 8 for such installs.
> > /cc @tzach
> 
> Thanks, I will recheck with CentOS8.

I had successfully (nonroot) install scylla on CentOS8, and it can be started by 'systemctl --user start scylla-server'

There is some problem in scylla_setup, and I skipped the problem by manual config.
I will report issues for those problem
- scylla-python3 bin isn't correct in sbin/scylla_setup
    - python3 isn't installed inside /opt/scylladb, but /home/scylla-test/install_root/ (the prefix for install.sh)
- the default var/lib/scylla directory isn't created inside /home/scylla-test/install_root/
    - fail to start scylla: `scylla[45616]: Could not initialize seastar: std::runtime_error (Couldn't stat /home/scylla-test/install_root/var/lib/scylla)`

**Comment by amoskong** [comment] 2020-11-16 12:06
The fix only added an error note in installation.
@roydahan  SCT doesn't support to lunch and manage scylla from cmdline, so we can't test with centos7.  

job: https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/artifacts-centos7-test-clone/10/console

```
< t:2020-11-16 09:11:13,867 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Scylla non-root install completed.
< t:2020-11-16 09:11:27,418 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Scylla-JMX non-root install completed.
< t:2020-11-16 09:11:27,725 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > WARNING: This distribution does not support systemd user mode, please configure and launch Scylla manually.
```

**Comment by amoskong** [comment] 2020-12-15 08:05
Hi @syuu1228 

I just see this error "Failed to connect to bus: No such file or directory" on CentOS8.

test job: https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/artifacts-offline-install/job/artifacts-centos8-nonroot-test/8/console
test id: 07d93eee-529f-457d-b7e0-5ab2553891f7

```
> gce_image_db: https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-8
12-15 06:14:37,167 f:tester.py       l:128  c:sdcm.tester          p:ERROR > sdcm.cluster.NodeSetupFailed: 
[Node artifacts-centos8-jenkins-db-node-07d93eee-0-1 [34.75.147.44 | 10.142.0.106] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!

12-15 06:14:37,167 > Command: 'bash -cxe "\ntar xvfz ./unified_package.tar.gz\n./install.sh --nonroot \nsudo rm -f /tmp/scylla.yaml\n"'
12-15 06:14:37,167 > 
12-15 06:14:37,167 > Exit code: 1
12-15 06:14:37,167 > 
12-15 06:14:37,167 > Stdout:
12-15 06:14:37,167 > 
12-15 06:14:37,167 > scylla-tools/debian/control
12-15 06:14:37,167 > scylla-tools/debian/copyright
12-15 06:14:37,167 > scylla-tools/debian/rules
12-15 06:14:37,167 > scylla-tools/debian/scylla-tools-core.install
12-15 06:14:37,167 > scylla-tools/debian/scylla-tools.install
12-15 06:14:37,167 > scylla-tools/debian/source/
12-15 06:14:37,167 > scylla-tools/debian/source/format
12-15 06:14:37,167 > scylla-tools/debian/source/options
12-15 06:14:37,167 > uninstall.sh
12-15 06:14:37,167 > .relocatable_package_version
12-15 06:14:37,167 > 
12-15 06:14:37,167 > Stderr:
12-15 06:14:37,167 > 
12-15 06:14:37,167 > + tar xvfz ./unified_package.tar.gz
12-15 06:14:37,167 > + ./install.sh --nonroot
12-15 06:14:37,167 > Failed to connect to bus: No such file or directory
12-15 06:14:37,167 > 
```

**Comment by avikivity** [comment] 2020-12-15 12:42
How do you send the command to the node?

Please have it show the value of $XDG_RUNTIME_DIR. If it's not defined, then systemctl --user will fail (also a good idea to show the output of systemctl --user).

**Comment by amoskong** [comment] 2020-12-28 07:10
> How do you send the command to the node?

The command was sent by SSH (fabric)

> Please have it show the value of $XDG_RUNTIME_DIR. If it's not defined, then systemctl --user will fail (also a good idea to show the output of systemctl --user).

When the error occurred the variable $XDG_RUNTIME_DIR is empty.

It's caused by that the SSH session established before user@1000.service is ready, so the env variables are out of data.
I'm trying to solve the problem by re-connect ssh session.

**Comment by dreamerHarshit** [comment] 2021-02-12 09:56
Is the issue fixed? As i'm still facing this issue on centOS as well as RedHat linux.

`+ '[' 0 -gt 0 ']'
+ has_java=false
+ '[' -x /usr/bin/java ']'
++ /usr/bin/java -version
++ cut -f 3 -d ' '
++ head -n1
+ javaver='"1.8.0_282"'
+ [[ "1.8.0_282" =~ ^"1.8.0 ]]
+ has_java=true
+ true
+ '[' -z '' ']'
+ true
+ prefix=/home/letsmailharshit/scylladb
++ realpath -m ///home/letsmailharshit/scylladb
+ rprefix=/home/letsmailharshit/scylladb
+ '[' -f /etc/os-release ']'
+ . /etc/os-release
++ NAME='CentOS Linux'
++ VERSION='7 (Core)'
++ ID=centos
++ ID_LIKE='rhel fedora'
++ VERSION_ID=7
++ PRETTY_NAME='CentOS Linux 7 (Core)'
++ ANSI_COLOR='0;31'
++ CPE_NAME=cpe:/o:centos:centos:7
++ HOME_URL=https://www.centos.org/
++ BUG_REPORT_URL=https://bugs.centos.org/
++ CENTOS_MANTISBT_PROJECT=CentOS-7
++ CENTOS_MANTISBT_PROJECT_VERSION=7
++ REDHAT_SUPPORT_PRODUCT=centos
++ REDHAT_SUPPORT_PRODUCT_VERSION=7
+ '[' -z '' ']'
+ sysconfdir=/etc/sysconfig
+ true
+ '[' -z /home/letsmailharshit/scylladb/python3/bin/python3 ']'
+ scylla_args=()
+ args=()
+ false
+ true
+ scylla_args+=(--nonroot)
+ args+=(--nonroot)
++ readlink -f scylla
+ cd /home/letsmailharshit/scylla
+ ./install.sh --root / --prefix /home/letsmailharshit/scylladb --python3 /home/letsmailharshit/scylladb/python3/bin/python3 --sysconfdir /etc/sysconfig --nonroot

Failed to get D-Bus connection: No such file or directory`

**Comment by penberg** [comment] 2021-02-12 11:02
@dreamerHarshit, which version of Scylla is this?

@syuu1228, can you please have a look at this?

**Comment by dreamerHarshit** [comment] 2021-02-12 11:26
@penberg I was using scylla 4.3

**Comment by dreamerHarshit** [comment] 2021-02-15 06:28
@penberg @syuu1228 is there any update, are we working on this?

**Comment by penberg** [comment] 2021-02-15 10:58
@syuu1228 If I read this issue correctly, this is a CentOS 7 limitation, right? We probably need to backport 44109348291038dfe717c44b4c83c4f7edd3a011 to make the error message human-readable?

**Comment by dreamerHarshit** [comment] 2021-02-15 11:05
@penberg yes it is working fine with centos 8 but giving error on centos 7 and RHEL.
Will you please help me in understanding what the limitation exactly is? and is it there with RHEL as well?

**Comment by penberg** [comment] 2021-02-16 08:17
@dreamerHarshit The issue is with the `systemctl --user daemon-reload` command (which reloads systemd user services). See, for example, @avikivity's comment here: https://github.com/scylladb/scylla/issues/7071#issuecomment-677557405.

And yes, this `systemd` limitation affects RHEL 7 too:

```
$ grep PRETTY /etc/os-release
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
$ systemctl --user daemon-reload
Failed to get D-Bus connection: No such file or directory
```

@avikivity @syuu1228 What are the workarounds to run Scylla on CentOS 7 in user-mode? The Docker image uses http://supervisord.org/, which is one option.

**Comment by avikivity** [comment] 2021-02-18 18:33
Un-backported from 4.3.

It causes an error in ccm.

**Comment by slivne** [comment] 2021-03-29 07:57
@penberg can we close this - do we need to add a comment on the offline installer docs

**Comment by syuu1228** [comment] 2021-03-31 17:00
> @dreamerHarshit The issue is with the `systemctl --user daemon-reload` command (which reloads systemd user services), which is not supported on older `systemd` versions (such as the one on CentOS 7).
> 
> 
> 
> See, for example, @avikivity's comment here for more details: https://github.com/scylladb/scylla/issues/7071#issuecomment-677557405.
> 
> 
> 
> And yes, this `systemd` limitation affects RHEL 7 too:
> 
> 
> 
> ```
> 
> $ grep PRETTY /etc/os-release
> 
> PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
> 
> $ systemctl --user daemon-reload
> 
> Failed to get D-Bus connection: No such file or directory
> 
> ```
> 
> 
> 
> @avikivity @syuu1228 What are the workarounds to run Scylla on CentOS 7 in user-mode? The Docker image uses http://supervisord.org/, which is one option.

@penberg @avikivity Do we want support non-root on CentOS7 using supervisord?
I think we discussed not to implement it just for CentOS7, since the distribution become outdated.
If we decided to do it, I suppose implementation itself should be easy since we already uses supervisord in Docker image.
Bit problematic things is, configuration between systemd unit and supervisord can be inconsistent, since we will probably maintain systemd only.

**Comment by avikivity** [comment] 2021-04-04 13:58
If we have to, we'll move the supervisord setup to install.sh. Hopefully we won't have to.

One the one hand, CentOS 7 is indeed outdated.

On the other hand, the users who need non-root install are exactly the users that use outdated systems.

@tzach ^

**Comment by mykaul** [comment] 2023-03-08 11:00
I'm not sure what the status of the issue is (still open) and certainly unsure it's worth backporting anywhere.
@syuu1228 perhaps you remember / know what's going on?

**Comment by syuu1228** [comment] 2023-03-29 10:45
> I'm not sure what the status of the issue is (still open) and certainly unsure it's worth backporting anywhere. @syuu1228 perhaps you remember / know what's going on?

@mykaul We use systemd user mode (systemctl --user) on non-root installation, but CentOS7 doesn't supported it, so we decided not to support CentOS7 on non-root installation.
Instead of support CentOS7, we implemented warning message which says "This distribution does not supported" on 44109348291038dfe717c44b4c83c4f7edd3a011.
So this can close now.

**Comment by syuu1228** [comment] 2023-03-29 10:52
NOTE: We unofficially have supervisord mode, so we actually can install non-root in CentOS7 by `./install.sh --nonroot --supervisor --prefix ~/scylladb`.
But it will not become official feature, and not well tested.

**Comment by syuu1228** [comment] 2023-10-11 05:26
We don't support CentOS7 on offline installation, closing.

**Closed by syuu1228** 2023-10-11 05:26 UTC
Labels: Backport candidate, offlineinstaller

**Comment by denesb** [comment] 2023-12-14 12:20
Was closed due to aging, no backport needed.
