### ISSUE TITLE
Node fails to boot on restart with consistent-topology-changes if there was no group0 raft snapshot yet

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#14918] opened 2023-08-01 19:49 UTC
Version: accd6271bc

This can happen when the consistent-topology-changes feature was enabled in an already bootstrapped cluster (5.2). The reason is that the new code added in ff386e7a445d17ed2199a26e4ac75905b071a91b to raft_sys_table_storage::bootstrap() didn't run, and group0 snapshot.id may not be set.

Scylla node fails to start after restart because of
```
[shard 0] token_metadata - shared_token_metadata: invalid new fence version, can't be greater than the current version, current version 0, new fence version 6".
```

That's on boot. I see that system.topology has version 8. But token metadata has version 0, and topology_state_load() did not run yet.

I see that group 0 server has the following state on boot:

```
Aug 01 19:21:09 ip-172-31-40-68 scylla[2613]:  [shard 0] raft - [7e13b892-2109-4b71-9537-4ebbbf4c8dda] start raft instance: snapshot id=00000000-0000-0000-0000-000000000000 commit index=44 last stable index=44
```

And all commands are skipped on replay due to:
```
roup0_raft_sm - cmd.prev_state_id (807a9158-2ffb-11ee-fb94-f9ee315612f9) different than last group 0 state ID in history table (80995246-2ffb-11ee-69ba-7066a788e49e)
```

Hence there is no call to topology_state_load() which would restore token metadata version.

**Comment by kostja** [comment] 2023-08-03 15:56
Reproduced in the latest master, 
```
ERROR 2023-08-03 18:52:34,912 [shard 0] token_metadata - shared_token_metadata: invalid new fence version, can't be greater than the current version, current version 0, new fence version 9, at: 0x5c08fae 0x5c09560 0x5c09848 0x580b7b7 0x3cf2b05 0x3ee7cfa 0x137caf1 0x5ada85f 0x5ada7ef 0x3e1b1ab 0x1299deb 0x128f5b5 0x5aeb086
```
in test_topology_rejoin

**Comment by kostja** [comment] 2023-08-04 09:19
[
[scylla-1.log](https://github.com/scylladb/scylladb/files/12259203/scylla-1.log)
Full log of the crashed node.

**Comment by kostja** [comment] 2023-08-04 20:18
Looks like a boot order issue. In order to trigger the situation the node needs to restart without bootstrap fully finished yet. In this case, setup_group0_if_exists() in main will not start group0, and therefore, will not load the topology state machine. However, the next call in main is trying to update the fence version from the persisted state             ss.local().update_fence_version(sys_ks.local().get_topology_fence_version().get()).get();
and it expects a fully loaded group0 state machine already.

setup_group0_if_existS() wasn't such a good idea after all.

@gleb-cloudius @gusev-p @kbr-scylla

**Comment by kostja** [comment] 2023-08-04 20:19
reproducible in test test_topology_rejoin, which has become flaky

**Comment by kbr-scylla** [comment] 2023-08-10 08:37
> This can happen when the consistent-topology-changes feature was enabled in an already bootstrapped cluster (5.2).

Upgrading to raft-topology won't automagically work, we need a dedicated upgrade procedure for it with a cluster feature and so on, similar to the raft-schema upgrade procedure we have now.

I expect implementing and testing such a procedure to be a task for week or two.

**Comment by kostja** [comment] 2023-11-29 14:19
Do we need to keep this issue open? Is it still reproducible? Do we care about an upgrade from 5.2 to 6.0 (we don't).

**Comment by tgrabiec** [comment] 2023-11-29 14:26
> Do we need to keep this issue open? 
> Is it still reproducible?

Not sure, possibly.

> Do we care about an upgrade from 5.2 to 6.0 (we don't). @tgrabiec

The problem is not 5.2 specific, it probably applies to any upgrade from non-raft topology to raft topology. If we solve that, or have another issue about it, we can close this issue.

**Comment by kostja** [comment] 2023-11-29 14:30
The thing is that going forward we will not support an upgrade from anything but 5.4, where raft is enabled/default.

**Comment by mykaul** [comment] 2023-11-29 15:50
> The thing is that going forward we will not support an upgrade from anything but 5.4, where raft is enabled/default.

But a 5.4 may be a 5.2 that was upgraded, and Raft was not enabled during upgrade, no?

**Comment by kostja** [comment] 2023-11-29 16:28
In this case it will be enabled by the upgrade to 5.4, where raft is ON by default in all clusters.

**Comment by kostja** [comment] 2023-11-29 16:28
There is a chance it is explicitly disabled though... I am not sure we want to support this.

**Comment by kbr-scylla** [comment] 2023-11-29 16:31
Upgrade from pre-raft-topology to post-raft-topology issue is here: https://github.com/scylladb/scylladb/issues/15008
Closing this one.

**Closed by kbr-scylla** 2023-11-29 16:31 UTC
Labels: bug, topology changes
