### ISSUE TITLE
raft_topology - topology change coordinator fiber got error raft::stopped_error  when shutting down node 

### ISSUE THREAD

**Issue by cezarmoise** [scylladb/scylladb#20589] opened 2024-09-13 15:09 UTC
Error happens when dtest cleans up and wants to shutdown the cluster.

```
ERROR 2024-09-12 15:50:48,370 [shard 0: gms] raft - [e5f50fd5-e45a-4a43-b01b-4e0732bc9afc] applier fiber stopped because of the error: std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1342): exceptions::mutation_write_failure_exception (Operation failed for system.cdc_local - received 0 responses and 1 failures from 1 CL=ONE.)
INFO  2024-09-12 15:50:48,371 [shard 0:strm] raft_topology - raft_state_monitor_fiber aborted with raft::stopped_error (Raft instance is stopped, reason: "background error, std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1342): exceptions::mutation_write_failure_exception (Operation failed for system.cdc_local - received 0 responses and 1 failures from 1 CL=ONE.)")
ERROR 2024-09-12 15:50:48,372 [shard 0: gms] raft_topology - topology change coordinator fiber got error raft::stopped_error (Raft instance is stopped, reason: "background error, std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1342): exceptions::mutation_write_failure_exception (Operation failed for system.cdc_local - received 0 responses and 1 failures from 1 CL=ONE.)")
```

Replicates easily with a high number of workers, but happens also with 3 (like on Jenkins) and 0.
Only replicates on debug,
Replicates on master too, but at a lower %. With enterprise, I get 2-3 errors per run.
```
pytest --scylla-version='unstable/enterprise:latest:debug' --tablets --count=7 -n=7 schema_test.py::TestSchema::test_restart_with_large_tables
```

Occurrences that I could find:
- [scylla-master/dtest-debug#319](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/lastBuild/testReport/schema_test/TestSchema/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_restart_with_large_tables/ )
- [scylla-master/dtest-debug#313](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/313/testReport/snapshot_test/TestParallelSnapshotOperations/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split010___test_parallel_operations_create_list_clear_for_all_ks/)

See attached logs
[dtest-error.log](https://github.com/user-attachments/files/16995565/dtest-error.log)
[dtest-no-error.log](https://github.com/user-attachments/files/16995566/dtest-no-error.log)
[node1-error.log](https://github.com/user-attachments/files/16995567/node1-error.log)
[node1-no-error.log](https://github.com/user-attachments/files/16995568/node1-no-error.log)

**Comment by cezarmoise** [comment] 2024-09-13 15:10
cc: @pehala

**Comment by bhalevy** [comment] 2024-09-15 11:13
Possibly similar error in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/319/testReport/schema_test/TestSchema/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_restart_with_large_tables/
```
failed on teardown with "AssertionError: Unexpected errors found:
node1: 2 errors
ERROR 2024-09-08 06:21:21,516 [shard 0: gms] raft - [d11f9a3d-5039-4ed9-9f9f-44b7ceed68ea] applier fiber stopped because of the error: std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1342): exceptions::mutation_write_failure_exception (Operation failed for system.scylla_local - received 0 responses and 1 failures from 1 CL=ONE.)
ERROR 2024-09-08 06:21:21,515 [shard 0: gms] storage_proxy - exception during mutation write to 127.0.82.1: utils::internal::nested_exception<std::runtime_error> (Could not write mutation system:scylla_local (pk{0010656e61626c65645f6665617475726573}) to commitlog): seastar::gate_closed_exception (gate closed)"
```

@kostja who should look into this?

**Comment by cezarmoise** [comment] 2024-09-16 14:04
Also https://jenkins.scylladb.com/job/scylla-enterprise/job/next/lastBuild/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Build___x86___dtest_with_tablets___test_removenode_rejoin/ 

```
failed on teardown with "AssertionError: Unexpected errors found:
node3: 1 errors
ERROR 2024-09-15 18:57:15,527 [shard 0:main] init - Startup failed: seastar::gate_closed_exception (gate closed)"
```

**Comment by mykaul** [comment] 2024-09-24 09:41
@cezarmoise - no labels make sure no one is looking at this. But this seems like a dup of the other issue you've opened on a similar scenario - Raft errors during shutdown - https://github.com/scylladb/scylla-dtest/issues/4713 ?

**Comment by kostja** [comment] 2024-09-24 17:38
Generally it's not a problem - we could try improving the boot order so that all parties that use Raft are stopped before Raft is stopped.

@gleb-cloudius has been looking into a similar issue earlier before. 

So it's not a release blocker.

**Comment by kbr-scylla** [comment] 2024-09-26 14:28
Failures for `system.cdc_local` writes during shutdown were reported in https://github.com/scylladb/scylladb/issues/19665
Fix https://github.com/scylladb/scylladb/commit/af83c5e53eb465f1183eae7102c0f2df0095f999 was merged into `master`  on September 10.
All reports posted here are from builds without that fix.
Closing as duplicate of https://github.com/scylladb/scylladb/issues/19665.

Note however that the fix af83c5e53eb465f1183eae7102c0f2df0095f999 was not backported to 6.1/6.0 because it caused another regression: https://github.com/scylladb/scylladb/issues/20701 which @gleb-cloudius is currently working on fixing.

Once the fix is in, we can backport a combined patchset to 6.0 and 6.1.

**Closed by kbr-scylla** 2024-09-26 14:28 UTC
Labels: area/raft, triage/master

**Comment by gleb-cloudius** [comment] 2024-09-26 14:39
> Once the fix is in, we can backport a combined patchset to 6.0 and 6.1.

No. We should not. If you remember I explicitly didn't want to backport original patch because fixing init order to silence benign error has a lot of potential to backfire. And here it exposed a race that existed before as well, but was much more unlikely to happen. The proper fix will not be small.

**Comment by kbr-scylla** [comment] 2024-09-26 14:41
Then what do we do for 6.0/6.1? If we don't do anything, it will remain flaky

**Comment by gleb-cloudius** [comment] 2024-09-26 14:44
Ignore the error.

**Comment by kbr-scylla** [comment] 2024-09-26 14:45
Then please open an issue in scylla-dtest to ignore this particular error in 6.0/6.1/2024.2.

**Comment by bhalevy** [comment] 2024-10-13 07:37
Where are we on ignoring the errors in scylla-dtest?
We still have some unneeded noise in this area.
Cc @pehala 

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/324/testReport/schema_test/TestSchema/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_restart_with_large_tables/
```
failed on teardown with "AssertionError: Unexpected errors found:
node1: 2 errors
ERROR 2024-10-13 06:03:33,507 [shard 0: gms] storage_proxy - exception during mutation write to 127.0.35.1: utils::internal::nested_exception<std::runtime_error> (Could not write mutation system:cdc_local (pk{00096364635f6c6f63616c}) to commitlog): seastar::gate_closed_exception (gate closed)
ERROR 2024-10-13 06:03:33,508 [shard 0: gms] raft - [5458579f-7191-4d88-8e6e-81772c49768a] applier fiber stopped because of the error: std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1360): exceptions::mutation_write_failure_exception (Operation failed for system.cdc_local - received 0 responses and 1 failures from 1 CL=ONE.)"
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/324/testReport/bootstrap_test/TestBootstrap/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split018___test_cluster_become_unavailable_when_kill_node_during_tablets_bootstrap_gracefully_/
```
failed on teardown with "AssertionError: Unexpected errors found:
node2: 2 errors
ERROR 2024-10-13 05:43:17,688 [shard 1:strm] storage_proxy - exception during mutation write to 127.0.60.2: utils::internal::nested_exception<std::runtime_error> (Could not write mutation keyspace:standard1 (pk{000a4c3634324e50344d3331}) to commitlog): seastar::gate_closed_exception (gate closed)
ERROR 2024-10-13 05:43:17,689 [shard 1:strm] storage_proxy - exception during mutation write to 127.0.60.2: utils::internal::nested_exception<std::runtime_error> (Could not write mutation keyspace:standard1 (pk{000a4e364b4e314e33393330}) to commitlog): seastar::gate_closed_exception (gate closed)"
```

**Comment by pehala** [comment] 2024-10-13 10:01
There has been no progress, it got lost since I this got closed and I am not aware of followup issues being created.


> Then please open an issue in scylla-dtest to ignore this particular error in 6.0/6.1/2024.2.

But based on this, this should not be happening on scylla-master, on there it should be fixed

**Comment by gleb-cloudius** [comment] 2024-10-13 10:51
> Where are we on ignoring the errors in scylla-dtest? We still have some unneeded noise in this area. Cc [@pehala](https://github.com/pehala)
> 
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/324/testReport/schema_test/TestSchema/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_restart_with_large_tables/
> 
> ```
> failed on teardown with "AssertionError: Unexpected errors found:
> node1: 2 errors
> ERROR 2024-10-13 06:03:33,507 [shard 0: gms] storage_proxy - exception during mutation write to 127.0.35.1: utils::internal::nested_exception<std::runtime_error> (Could not write mutation system:cdc_local (pk{00096364635f6c6f63616c}) to commitlog): seastar::gate_closed_exception (gate closed)
> ERROR 2024-10-13 06:03:33,508 [shard 0: gms] raft - [5458579f-7191-4d88-8e6e-81772c49768a] applier fiber stopped because of the error: std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1360): exceptions::mutation_write_failure_exception (Operation failed for system.cdc_local - received 0 responses and 1 failures from 1 CL=ONE.)"
> ```

Looks like the fix was not enough. It stopped group0 usage by local storage service before shutting down the commitlog, but group0 can be used by some other components now. More serious shutdown sequence rework is needed. We should probably split out db shutdown from ss:do_drain into separate function and call it much later in the shutdown sequence. But this is again playing Whac-A-Mole for a benign error. Just ignore it in dtest.

> 
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/324/testReport/bootstrap_test/TestBootstrap/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split018___test_cluster_become_unavailable_when_kill_node_during_tablets_bootstrap_gracefully_/
> 
> ```
> failed on teardown with "AssertionError: Unexpected errors found:
> node2: 2 errors
> ERROR 2024-10-13 05:43:17,688 [shard 1:strm] storage_proxy - exception during mutation write to 127.0.60.2: utils::internal::nested_exception<std::runtime_error> (Could not write mutation keyspace:standard1 (pk{000a4c3634324e50344d3331}) to commitlog): seastar::gate_closed_exception (gate closed)
> ERROR 2024-10-13 05:43:17,689 [shard 1:strm] storage_proxy - exception during mutation write to 127.0.60.2: utils::internal::nested_exception<std::runtime_error> (Could not write mutation keyspace:standard1 (pk{000a4e364b4e314e33393330}) to commitlog): seastar::gate_closed_exception (gate closed)"
> ```

This is unrelated to raft. We do not drain ongoing storage proxy requests during shutdown. This error should have always been there.
