### ISSUE TITLE
raft topology: updating the snitch

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17513] opened 2024-02-25 18:59 UTC
https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/config-change/switch-snitch.html

We have a documented procedure to update the snitch.
Do we test this? cc @temichus

But looking at the raft-topology code, there seems to be no path that would update DC/Rack of node if they change.
We have this function with a TODO:
```cpp
future<> storage_service::update_topology_with_local_metadata(raft::server& raft_server) {
    // TODO: include more metadata here
    auto local_shard_count = smp::count;
    auto local_ignore_msb = _db.local().get_config().murmur3_partitioner_ignore_msb_bits();
    auto local_release_version = version::release();
    auto local_supported_features = boost::copy_range<std::set<sstring>>(_feature_service.supported_feature_set());
```

we need a test.py test for the above procedure and if it fails (it likely will), need to fix.

Alternatively, we may decide that the above procedure is actually not up-to-date, and one should instead add a node in new DC/Rack and remove the old ones? Or perform replace?

cc @vladzcloudius -- how does it work in the field?

cc @tzach

**Comment by tzach** [comment] 2024-02-26 06:51
> we need a test.py test for the above procedure and if it fails (it likely will), need to fix.

+1
As a start, we should add a disclaimer stating which snitches this procedure works and does not work.
BTW, There might be more documented procedures without tests.

> Alternatively, we may decide that the above procedure is actually not up-to-date, and one should instead add a node in new DC/Rack and remove the old ones? Or perform replace?

Are you suggesting replacing all nodes, one by one, to update the snitch?

**Comment by tzach** [comment] 2024-02-26 06:51
@annastuchlik FYI

**Comment by gleb-cloudius** [comment] 2024-03-18 11:03
Well the documented procedure will not work even if we will add code to raft that updates topology since restarting nodes one by one will not work. Updating topology requires quorum.

How often the procedure is used? The simplest will be to amend it for raft to enter recover mode before changing the snitch and exiting it after.

**Comment by kbr-scylla** [comment] 2024-03-18 11:07
> Well the documented procedure will not work even if we will add code to raft that updates topology since restarting nodes one by one will not work. Updating topology requires quorum.

We can change it to restart all nodes at once. Some dtests that did full cluster restart had to be adjusted in this way

**Comment by kbr-scylla** [comment] 2024-03-18 11:08
> The simplest will be to amend it for raft to enter recover mode before changing the snitch and exiting it after.

Recovery mode should really be left for disaster recovery scenarios

**Comment by gleb-cloudius** [comment] 2024-03-20 09:33
@tgrabiec It is easy to update datacenter/rack names in the topology during boot, but how tablets will handle it?

**Comment by kbr-scylla** [comment] 2024-03-20 09:56
> @tgrabiec It is easy to update datacenter/rack names in the topology during boot, but how tablets will handle it?

cc @denesb @bhalevy

**Comment by bhalevy** [comment] 2024-03-20 10:23
NetworkTopologyStrategy relies on dc/rack locations so I don't see how can the snitch be changed arbitrarily.
Assuming that the strategy rf configuration still applies to the new topology if some nodes change their DC, for example, the existing replicas might not conform to the topology anymore.
Just running repair won't fix that.  This represents a change in RF configuration - some DCs in the new topology will need to lose tablets by deallocation and some will need to allocate and rebuild tablets.
So it's essentially an extreme case of https://github.com/scylladb/scylladb/issues/16129
It might be possible to do that with https://github.com/scylladb/scylladb/pull/17846
but we'll need code to call it and apply the revised tablet map and generated the corresponding tablet transitions.

**Comment by gleb-cloudius** [comment] 2024-03-20 10:30
> NetworkTopologyStrategy relies on dc/rack locations so I don't see how can the snitch be changed arbitrarily. Assuming that the strategy rf configuration still applies to the new topology if some nodes change their DC, for example, the existing replicas might not conform to the topology anymore. Just running repair won't fix that. This represents a change in RF configuration - some DCs in the new topology will need to lose tablets by deallocation and some will need to allocate and rebuild tablets. So it's essentially an extreme case of #16129 It might be possible to do that with #17846 but we'll need code to call it and apply the revised tablet map and generated the corresponding tablet transitions.

I do not understand what you are saying. Do you claim that the snitch cannot be changed today using our documented procedure or do you mean that the procedure will not work with tablets as is?

**Comment by bhalevy** [comment] 2024-03-20 10:35
> > NetworkTopologyStrategy relies on dc/rack locations so I don't see how can the snitch be changed arbitrarily. Assuming that the strategy rf configuration still applies to the new topology if some nodes change their DC, for example, the existing replicas might not conform to the topology anymore. Just running repair won't fix that. This represents a change in RF configuration - some DCs in the new topology will need to lose tablets by deallocation and some will need to allocate and rebuild tablets. So it's essentially an extreme case of #16129 It might be possible to do that with #17846 but we'll need code to call it and apply the revised tablet map and generated the corresponding tablet transitions.
> 
> I do not understand what you are saying. Do you claim that the snitch cannot be changed today using our documented procedure or do you mean that the procedure will not work with tablets as is?

I'm saying that the procedure won't work with tablets as is.

**Comment by kbr-scylla** [comment] 2024-03-20 10:36
cc @mykaul ^

**Comment by mykaul** [comment] 2024-03-20 11:27
Reasonable limitation, IMHO. @tzach ?

**Comment by vladzcloudius** [comment] 2024-03-20 11:29
> https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/config-change/switch-snitch.html
> 
> We have a documented procedure to update the snitch. Do we test this? cc @temichus
> 
> But looking at the raft-topology code, there seems to be no path that would update DC/Rack of node if they change. We have this function with a TODO:
> 
> ```c++
> future<> storage_service::update_topology_with_local_metadata(raft::server& raft_server) {
>     // TODO: include more metadata here
>     auto local_shard_count = smp::count;
>     auto local_ignore_msb = _db.local().get_config().murmur3_partitioner_ignore_msb_bits();
>     auto local_release_version = version::release();
>     auto local_supported_features = boost::copy_range<std::set<sstring>>(_feature_service.supported_feature_set());
> ```
> 
> we need a test.py test for the above procedure and if it fails (it likely will), need to fix.
> 
> Alternatively, we may decide that the above procedure is actually not up-to-date, and one should instead add a node in new DC/Rack and remove the old ones? Or perform replace?
> 
> cc @vladzcloudius -- how does it work in the field?
> 
> cc @tzach

The procedure in question is a regression itself and we have 3 year old GH asking to fix that regression.

It's completely unacceptable that you have to shut down the whole cluster to make a configuration change.

And the root cause of the regression in question is the infamous guardrail and AFAIK nothing else.

If an online snitches change is not restored then the logical next step is to kill snitches framework all together. This was already proposed by @xemul in the past.

What do I think about it? - I think it's all going in a very wrong direction.

**Comment by mykaul** [comment] 2024-03-20 12:02
> If an online snitches change is not restored then the logical next step is to kill snitches framework all together. This was already proposed by @xemul in the past.

Yes, we should move to the file based, created by scripts (to be shared also with the drivers). We did not make any progress on this.

> 
> What do I think about it? - I think it's all going in a very wrong direction.

I remember - you also had a request to allow mixed snitches, IIRC.

**Comment by kbr-scylla** [comment] 2024-03-25 09:45
> I agree with @vladzcloudius that a full cluster shutdown is problematic for tablets.
For now, let's add a limitation: it would not work with a safe topology update.

If I understand correctly there are two problems:
- for vnode-based tables, there is a problem with availability. Full cluster shutdown disrupts client applications. This problem existed before 6.0
- For tablets in 6.0, there is an additional problems of correctness (i.e. even further regression compared to vnodes) -- snitch change is simply not handled by tablets code (yet?)

**Closed** 2024-03-25 19:07 UTC
Labels: type/documentation, area/topology changes, area/raft

**Comment by tgrabiec** [comment] 2024-03-25 20:38
> @tgrabiec It is easy to update datacenter/rack names in the topology during boot, but how tablets will handle it?

Tablets don't store rack/dc info, all code gets it from locator::topology. So it should work the same as with vnodes.

If that violates RF, then that's on the admin, like with vnodes.

**Comment by tgrabiec** [comment] 2024-03-25 20:40
> I'm saying that the procedure won't work with tablets as is.

@bhalevy Can you explain what scenario worked with vnodes and doesn't with tablets?

**Comment by tgrabiec** [comment] 2024-03-25 20:43
I can think of the counter-example, where changing DC will lead to data loss with vnodes, but won't with tablets. Because snitch change doesn't affect replicas for a given key with tablets (same set of nodes), but with vnodes the replica set will change if some nodes suddenly join an existing DC. That's like parallel bootstrap without streaming.

**Comment by bhalevy** [comment] 2024-03-25 21:09
> > I'm saying that the procedure won't work with tablets as is.
> 
> @bhalevy Can you explain what scenario worked with vnodes and doesn't with tablets?

With vnodes, if nodes dc changes due to snitch change, running repair/rebuild should populate the now missing token replucas based on the token rung, and running cleanup will delete now-disowned tokens.

With tablets that ain't going to work and we need a way to migrate tablets in order to bring the replicas back into agreement with the rf configuration.

**Comment by kbr-scylla** [comment] 2024-03-26 07:55
Opened https://github.com/scylladb/scylladb/issues/18024

**Comment by tgrabiec** [comment] 2024-03-26 19:43
> > > I'm saying that the procedure won't work with tablets as is.
> > 
> > 
> > @bhalevy Can you explain what scenario worked with vnodes and doesn't with tablets?
> 
> With vnodes, if nodes dc changes due to snitch change, running repair/rebuild should populate the now missing token replucas based on the token rung, and running cleanup will delete now-disowned tokens.
> 
> With tablets that ain't going to work and we need a way to migrate tablets in order to bring the replicas back into agreement with the rf configuration.

So you're not talking about renaming a DC, but moving a subset of nodes already present in some dc (so have tablet replicas), to another DC? Is this even supposed to be supported?

If it's a DC rename, then those nodes will appear as unavailable to requests, until keyspace definition is adjusted. Then replicas will match RF again.

**Comment by bhalevy** [comment] 2024-03-26 23:03
> > > > I'm saying that the procedure won't work with tablets as is.
> > > 
> > > 
> > > @bhalevy Can you explain what scenario worked with vnodes and doesn't with tablets?
> > 
> > 
> > With vnodes, if nodes dc changes due to snitch change, running repair/rebuild should populate the now missing token replucas based on the token rung, and running cleanup will delete now-disowned tokens.
> > With tablets that ain't going to work and we need a way to migrate tablets in order to bring the replicas back into agreement with the rf configuration.
> 
> So you're not talking about renaming a DC, but moving a subset of nodes already present in some dc (so have tablet replicas), to another DC? Is this even supposed to be supported?

Not sure if it's officially supported, but is there anything preventing it?

> If it's a DC rename, then those nodes will appear as unavailable to requests, until keyspace definition is adjusted. Then replicas will match RF again.

They will be unavailable for request with consistency_level LOCAL_* and EACH_QUORUM.
Other consistency levels may be happy with whatever dc nodes have.
What do you mean by "keyspace definition"?

**Comment by tgrabiec** [comment] 2024-03-26 23:49
> What do you mean by "keyspace definition" the rf per dc options for network topology strategy?

Yes.

**Comment by kbr-scylla** [comment] 2024-03-27 11:33
@annastuchlik for consistent topology updates  the problem has been addressed. It should work as before with slight modification (parallel restart of nodes) that was already included in the docs (https://github.com/scylladb/scylladb/commit/69bf96252284173ec6f9cdf7087539a88b83c319#diff-8d98adb842d5cbb12aa22f77449ef7db02cc9fd04f1fb55d703641b788855812)

There is no requirement to use tablets in 6.0 -- you can have raft-topology but not use tablets. Then everything should work.

**but** if you use tablets, apparently there's still a problem (https://github.com/scylladb/scylladb/issues/18024)

So I think the wording would be something like "if you use tablets, then changing snitch is not supported" (and maybe a note that new keyspaces are created by default with tablets?)

**Comment by vladzcloudius** [comment] 2025-02-17 22:56
> > > I'm saying that the procedure won't work with tablets as is.
> > 
> > 
> > [@bhalevy](https://github.com/bhalevy) Can you explain what scenario worked with vnodes and doesn't with tablets?
> 
> With vnodes, if nodes dc changes due to snitch change, running repair/rebuild should populate the now missing token replucas based on the token rung, and running cleanup will delete now-disowned tokens.

This kind of change can lead to a data loss which `repair` may not be able to fix.
Therefore such a change should be always harshly forbidden.
Ref https://github.com/scylladb/scylladb/issues/22869

> 
> With tablets that ain't going to work and we need a way to migrate tablets in order to bring the replicas back into agreement with the rf configuration.

I guess the same relates to tablets - DC/RACK name of existing nodes should be always and totally forbidden.
