### ISSUE TITLE
raft topology: restarting a node after decommission hangs trying to map IP

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#14803] opened 2023-07-24 11:53 UTC
https://github.com/kbr-scylla/scylladb/commit/7c6fdfc78d55f836250c88e737c5a2bb63a5b6b9

The following test fails due to Scylla hanging on startup:
```python3
from test.pylib.manager_client import ManagerClient
import pytest
import logging

logger = logging.getLogger(__name__)

@pytest.mark.asyncio
async def test_restart_after_decom(request, manager: ManagerClient):
    logger.info("Bootstrapping first node")
    servers = [await manager.server_add() for _ in range(2)]

    logger.info(f"Decommissioning node {servers[0]}")
    await manager.decommission_node(servers[0].server_id)
    servers = servers[1:]

    logger.info(f"Restarting node {servers[0]}")
    await manager.server_stop_gracefully(servers[0].server_id)
    await manager.server_start(servers[0].server_id)
```

Logs on the restarting server:
```
INFO  2023-07-24 13:47:45,968 [shard 0] raft_group0 - setup_group0: group 0 ID present. Starting existing Raft server.
INFO  2023-07-24 13:47:45,968 [shard 0] raft_group0 - Server 3457f7bf-defd-43bb-be5c-a5728d0857e6 is starting group 0 with id dd3e8320-2a17-11ee-8cd0-345b6af419b3
WARN  2023-07-24 13:47:45,973 [shard 0] storage_service - raft topology: cannot map d427f5ce-8bd3-494d-a64c-989efe163976 to ip, retrying.
INFO  2023-07-24 13:47:45,976 [shard 0] compaction - [Compact system_schema.columns e7f68010-2a17-11ee-bfc3-4880f894f28e] Compacted 2 sstables to [/home/kbraun/dev/scylladb/testlog/dev/scylla-2/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/
me-3g7x_0wrl_5l9dc2wzd8s5y9jxqm-big-Data.db:level=0]. 26kB to 20kB (~79% of original) in 35ms = 747kB/s. ~256 total partitions merged to 6.
WARN  2023-07-24 13:47:46,973 [shard 0] storage_service - (rate limiting dropped 196 similar messages) raft topology: cannot map d427f5ce-8bd3-494d-a64c-989efe163976 to ip, retrying.
WARN  2023-07-24 13:47:47,977 [shard 0] storage_service - (rate limiting dropped 197 similar messages) raft topology: cannot map d427f5ce-8bd3-494d-a64c-989efe163976 to ip, retrying.
WARN  2023-07-24 13:47:48,982 [shard 0] storage_service - (rate limiting dropped 197 similar messages) raft topology: cannot map d427f5ce-8bd3-494d-a64c-989efe163976 to ip, retrying.
WARN  2023-07-24 13:47:49,983 [shard 0] storage_service - (rate limiting dropped 195 similar messages) raft topology: cannot map d427f5ce-8bd3-494d-a64c-989efe163976 to ip, retrying.
WARN  2023-07-24 13:47:50,987 [shard 0] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map d427f5ce-8bd3-494d-a64c-989efe163976 to ip, retrying.
WARN  2023-07-24 13:47:51,990 [shard 0] storage_service - (rate limiting dropped 197 similar messages) raft topology: cannot map d427f5ce-8bd3-494d-a64c-989efe163976 to ip, retrying.
WARN  2023-07-24 13:47:52,993 [shard 0] storage_service - (rate limiting dropped 197 similar messages) raft topology: cannot map d427f5ce-8bd3-494d-a64c-989efe163976 to ip, retrying.
```

In short, the restarting node is reapplying commands from the Raft log. One of the commands is the one which added the node that we just decommissioned to topology. This command is trying to map the node's host ID to IP for updating the token ring. In `storage_service::topology_state_load`:

```cpp
    auto id2ip = [this, &am] (raft::server_id id) -> future<gms::inet_address> {
        auto ip = am.find(id);
        while (!ip) {
            static logger::rate_limit rate_limit{std::chrono::seconds(1)};
            slogger.log(log_level::warn, rate_limit, "raft topology: cannot map {} to ip, retrying.", id);
            // FIXME: https://github.com/scylladb/scylladb/issues/12279
            // Loop until gossiper figures the address
            // but the solution is to change token_metadata to work with server_ids instead of ips
            co_await sleep_abortable(std::chrono::milliseconds(5), _abort_source);
            ip = am.find(id);
        }
        co_return *ip;
    };
```

This loop hangs, because we no longer have the IP of that node -- it has already decommissioned.

The solution is https://github.com/scylladb/scylladb/issues/6403.

cc @kostja @gleb-cloudius @tgrabiec

**Comment by kbr-scylla** [comment] 2023-07-24 11:53
See also https://github.com/scylladb/scylladb/pull/13655#issuecomment-1521389804

**Comment by kbr-scylla** [comment] 2023-07-24 11:54
cc @avikivity

**Comment by kbr-scylla** [comment] 2023-07-24 11:54
This is the blocker I mentioned on today's status meeting.

**Comment by kostja** [comment] 2023-07-24 13:57
There are other ways to look at this. First, it is a manifestation of the fact that state machine state is incomplete - part of the state, really, are IP addresses, which it was decided to not store in Raft (revert this mistake). 
Second, with the centralized topology coordinator we don't have to "apply" the log one command at a time, we can collapse multiple commands into the new state of the topology state machine, and only apply the new state.

**Comment by kbr-scylla** [comment] 2023-07-24 14:01
>  Second, with the centralized topology coordinator we don't have to "apply" the log one command at a time, we can collapse multiple commands into the new state of the topology state machine, and only apply the new state.

The coordinator doesn't control how commands are batched, Raft does. Besides, it's not right to rely on a certain batching of commands, command application must be deterministic however we decide to batch them.

**Comment by kostja** [comment] 2023-10-12 18:03
@gusev-p hopefully will get addressed by your host id work

**Comment by patjed41** [comment] 2023-11-06 11:57
I was trying to merge test cases in `test_replace.py` and found a new manifestation of this issue -- replace with `reuse_ip_addr = True` immediately followed by another replace. The second replacing node hangs trying to map the IP of the first replaced node, whose IP has been taken over by the first replacing node.

So, this issue blocks merging test cases in `test_replace.py`. The only motivation for this merging was to increase efficiency by not starting a new cluster every time, but I think we should also do it to verify that a fix for this issue also fixes the 2-replace scenario.

**Comment by patjed41** [comment] 2023-11-06 14:00
> I was trying to merge test cases in `test_replace.py` and found a new manifestation of this issue -- replace with `reuse_ip_addr = True` immediately followed by another replace. The second replacing node hangs trying to map the IP of the first replaced node, whose IP has been taken over by the first replacing node.
> 
> So, this issue blocks merging test cases in `test_replace.py`. The only motivation for this merging was to increase efficiency by not starting a new cluster every time, but I think we should also do it to verify that a fix for this issue also fixes the 2-replace scenario.

It turns out that the a different issue causes the 2-replace scenario to fail. I opened #15967.

**Comment by aleksbykov** [comment] 2023-12-25 12:33
@kamil is it same issue?

node1 start operation by remove node with host id 95512453-82ac-4d64-8082-e4e4f51ec955. But node1 was stopped after 
log: `INFO  2023-12-25 19:11:02,073 [shard 0:strm] storage_service - raft topology: node 95512453-82ac-4d64-8082-e4e4f51ec955 removed from group 0 configuration`


```
INFO  2023-12-25 19:11:02,019 [shard 1:strm] repair - repair[b707b398-556a-4b80-9da9-7e8baaf1d707]: stats: repair_reason=removenode, keyspace=system_distributed_everywhere, tables={cdc_generation_descriptions_v2
}, ranges_nr=1025, round_nr=1025, round_nr_fast_path_already_synced=1025, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=10250, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.3647312 se
conds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.82.1, 0}, {127.0.82.2, 0}, {127.0.82.4, 0}}, row_from_disk_nr={{127.0.82.1, 0}, {127.0.82.2, 0}, {127.0.82.4, 0}}, row
_from_disk_bytes_per_sec={{127.0.82.1, 0}, {127.0.82.2, 0}, {127.0.82.4, 0}} MiB/s, row_from_disk_rows_per_sec={{127.0.82.1, 0}, {127.0.82.2, 0}, {127.0.82.4, 0}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
INFO  2023-12-25 19:11:02,019 [shard 1:strm] repair - repair[b707b398-556a-4b80-9da9-7e8baaf1d707]: completed successfully, keyspace=system_distributed_everywhere
INFO  2023-12-25 19:11:02,028 [shard 0:strm] repair - repair[b707b398-556a-4b80-9da9-7e8baaf1d707]: stats: repair_reason=removenode, keyspace=system_distributed_everywhere, tables={cdc_generation_descriptions_v2
}, ranges_nr=1025, round_nr=1025, round_nr_fast_path_already_synced=1025, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=10250, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.3742238 se
conds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.82.1, 0}, {127.0.82.2, 0}, {127.0.82.4, 0}}, row_from_disk_nr={{127.0.82.1, 0}, {127.0.82.2, 0}, {127.0.82.4, 0}}, row
_from_disk_bytes_per_sec={{127.0.82.1, 0}, {127.0.82.2, 0}, {127.0.82.4, 0}} MiB/s, row_from_disk_rows_per_sec={{127.0.82.1, 0}, {127.0.82.2, 0}, {127.0.82.4, 0}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
INFO  2023-12-25 19:11:02,028 [shard 0:strm] repair - repair[b707b398-556a-4b80-9da9-7e8baaf1d707]: completed successfully, keyspace=system_distributed_everywhere
INFO  2023-12-25 19:11:02,029 [shard 0:strm] repair - repair[b707b398-556a-4b80-9da9-7e8baaf1d707]: completed successfully
INFO  2023-12-25 19:11:02,029 [shard 0:strm] repair - repair[b707b398-556a-4b80-9da9-7e8baaf1d707]: sync data for keyspace=system_distributed_everywhere, status=succeeded
INFO  2023-12-25 19:11:02,029 [shard 0:strm] repair - removenode_with_repair: finished with keyspace=system_distributed_everywhere, leaving_node=127.0.82.3, nr_ranges=1025, nr_ranges_synced=1025, nr_ranges_skipped=0
INFO  2023-12-25 19:11:02,029 [shard 0:strm] repair - removenode_with_repair: finished with keyspaces={system_auth, system_distributed, keyspace1, system_traces, system_distributed_everywhere}, leaving_node=127.0.82.3
INFO  2023-12-25 19:11:02,029 [shard 0:strm] storage_service - raft topology: streaming completed
INFO  2023-12-25 19:11:02,070 [shard 0:strm] storage_service - raft topology: removing node 95512453-82ac-4d64-8082-e4e4f51ec955 from group 0 configuration...
INFO  2023-12-25 19:11:02,073 [shard 0:strm] storage_service - raft topology: node 95512453-82ac-4d64-8082-e4e4f51ec955 removed from group 0 configuration
INFO  2023-12-25 19:11:02,079 [shard 0:main] compaction_manager - Asked to stop
INFO  2023-12-25 19:11:02,079 [shard 0:main] view_update_generator - Terminating background fiber
INFO  2023-12-25 19:11:02,079 [shard 0:main] init - Signal received; shutting down
```


After that node1 was restarted, but it stucked on 
```
INFO  2023-12-25 19:11:05,471 [shard 0:main] init - starting sstables loader
INFO  2023-12-25 19:11:05,471 [shard 1:comp] compaction - [Compact system.truncated adc32da0-a31e-11ee-abff-758b6694ba76] Compacted 2 sstables to [/home/abykov/.dtest/dtest-h_ppg9_3/test/node1/data/system/trunca
ted-38c19fd0fb863310a4b70d0cc66628aa/me-3gc7_0xuh_2rvoh2m5tv3rc850mu-big-Data.db:level=0]. 148kB to 74kB (~50% of original) in 4ms = 37MB/s. ~256 total partitions merged to 6.
INFO  2023-12-25 19:11:05,472 [shard 0:main] raft_group0 - setup_group0: group 0 ID present. Starting existing Raft server.
INFO  2023-12-25 19:11:05,472 [shard 0:main] raft_group0 - Server e0755096-d049-4e43-af47-8e7d6d450650 is starting group 0 with id 967795f0-a31e-11ee-bce9-3b15ac2fe55a
WARN  2023-12-25 19:11:05,478 [shard 0:main] storage_service - raft topology: cannot map 95512453-82ac-4d64-8082-e4e4f51ec955 to ip, retrying.
INFO  2023-12-25 19:11:05,479 [shard 0:comp] compaction - [Compact system_schema.tables adc3c9e0-a31e-11ee-bb0c-758c6694ba76] Compacted 2 sstables to [/home/abykov/.dtest/dtest-h_ppg9_3/test/node1/data/system_sc
hema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3gc7_0xuh_2sqjl2uegigcmwginq-big-Data.db:level=0]. 20kB to 14kB (~68% of original) in 8ms = 2MB/s. ~256 total partitions merged to 7.
INFO  2023-12-25 19:11:05,479 [shard 0:comp] compaction - [Compact system.topology adc52970-a31e-11ee-bb0c-758c6694ba76] Compacting [/home/abykov/.dtest/dtest-h_ppg9_3/test/node1/data/system/topology-5be1feb3929
e3df98da8d771c36129a0/me-3gc7_0xug_0o0752vf5w4ntp4foa-big-Data.db:level=0:origin=memtable,/home/abykov/.dtest/dtest-h_ppg9_3/test/node1/data/system/topology-5be1feb3929e3df98da8d771c36129a0/me-3gc7_0xtn_44j802vf
5w4ntp4foa-big-Data.db:level=0:origin=compaction]

INFO  2023-12-25 19:11:05,498 [shard 0:comp] compaction - [Compact system.local adc7c180-a31e-11ee-bb0c-758c6694ba76] Compacted 2 sstables to [/home/abykov/.dtest/dtest-h_ppg9_3/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/me-3gc7_0xuh_2yb5t2uegigcmwginq-big-Data.db:level=0]. 24kB to 12kB (~52% of original) in 1ms = 24MB/s. ~256 total partitions merged to 1.
INFO  2023-12-25 19:11:05,498 [shard 0:comp] compaction - [Compact system.truncated adc80fa0-a31e-11ee-bb0c-758c6694ba76] Compacting [/home/abykov/.dtest/dtest-h_ppg9_3/test/node1/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gc7_0xuh_2g3ap2uegigcmwginq-big-Data.db:level=0:origin=memtable,/home/abykov/.dtest/dtest-h_ppg9_3/test/node1/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gc7_0xuh_2g3ao2uegigcmwginq-big-Data.db:level=0:origin=memtable,/home/abykov/.dtest/dtest-h_ppg9_3/test/node1/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-6-big-Data.db:level=0:origin=compaction]
INFO  2023-12-25 19:11:05,499 [shard 0:comp] compaction - [Compact system.truncated adc80fa0-a31e-11ee-bb0c-758c6694ba76] Compacted 3 sstables to [/home/abykov/.dtest/dtest-h_ppg9_3/test/node1/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gc7_0xuh_2yqld2uegigcmwginq-big-Data.db:level=0]. 16kB to 5kB (~35% of original) in 1ms = 16MB/s. ~384 total partitions merged to 1.
WARN  2023-12-25 19:11:06,480 [shard 0:main] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 95512453-82ac-4d64-8082-e4e4f51ec955 to ip, retrying.
WARN  2023-12-25 19:11:07,483 [shard 0:main] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 95512453-82ac-4d64-8082-e4e4f51ec955 to ip, retrying.
WARN  2023-12-25 19:11:08,487 [shard 0:main] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 95512453-82ac-4d64-8082-e4e4f51ec955 to ip, retrying.
WARN  2023-12-25 19:11:09,489 [shard 0:main] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 95512453-82ac-4d64-8082-e4e4f51ec955 to ip, retrying.
WARN  2023-12-25 19:11:10,493 [shard 0:main] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 95512453-82ac-4d64-8082-e4e4f51ec955 to ip, retrying.

```

LOG: 
[node1.logs.tar.gz](https://github.com/scylladb/scylladb/files/13765996/node1.logs.tar.gz)
[rest-node.logs.tar.gz](https://github.com/scylladb/scylladb/files/13765997/rest-node.logs.tar.gz)

Scenario is in Draft PR: https://github.com/scylladb/scylla-dtest/pull/3806

**Comment by mykaul** [comment] 2023-12-25 12:44
@kbr-scylla is on PTO. @gusev-p might be able to look at this.

**Comment by gusev-p** [comment] 2023-12-25 15:21
It sounds like another manifestation of the same problem - we're waiting indefinitely for ip to appear for a given host_id while applying raft log. If the node is gone (removed) we may never get an ip for it.

I'm currently sitting at this issue, I'll take this scenario into account.

**Comment by aleksbykov** [comment] 2024-01-11 03:40
The issue look reproduced with dtest Scylla version 5.5.0~dev-0.20240109.f4f724921cc7 with build-id 7ea78454c2abfa05e04884e24c276a41865e6dd1: 
https://jenkins.scylladb.com/job/scylla-staging/job/artsiom_mishuta/job/dtest-pytest-gating/2/artifact/logs-full.release.000/1704894645188_repair_based_node_operations_test.py%3A%3ATestRepairBasedNodeOperations%3A%3Atest_enable_rbno_for_default_operation/

but now it is also coredump: https://jenkins.scylladb.com/job/scylla-staging/job/artsiom_mishuta/job/dtest-pytest-gating/2/artifact/logs-full.release.000/1704894645188_repair_based_node_operations_test.py%3A%3ATestRepairBasedNodeOperations%3A%3Atest_enable_rbno_for_default_operation/node4-scylla.3362.1704894642.core.gz

```
ERROR 2024-01-10 13:50:42,154 [shard 0:main] raft_group_registry - Failed to start a Raft group 16cc46b0-afbd-11ee-b8b0-7e27321f65a7: seastar::sleep_aborted (Sleep is aborted), at: 0x6123efe 0x6124510 0x61247f8 0x5be4187 0x47e66c4 0x13a45fa 0x5c2117f 0x5c22467 0x5c217c8 0x5bb3da7 0x5bb2f5c 0x1338279 0x1339cd0 0x13368fc /jenkins/workspace/scylla-staging/artsiom_mishuta/dtest-pytest-gating/scylla/.ccm/scylla-repository/f4f724921cc71a06b16ddb8a48728d42d79acee0/libreloc/libc.so.6+0x27b89 /jenkins/workspace/scylla-staging/artsiom_mishuta/dtest-pytest-gating/scylla/.ccm/scylla-repository/f4f724921cc71a06b16ddb8a48728d42d79acee0/libreloc/libc.so.6+0x27c4a 0x13341a4
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::(anonymous namespace)::thread_wake_task
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#2}, seastar::future<int> >(scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#3}, false>, seastar::future<int>::then_wrapped_nrvo<seastar::future<int>, seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#3}, false> >(seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#3}, false>&, seastar::future_state<int>&&)#1}, int>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false>, seastar::future<int>::then_wrapped_nrvo<seastar::future<int>, seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false> >(seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false>&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false>&, seastar::future_state<int>&&)#1}, int>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}, seastar::future<int>::then_impl_nrvo<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}, seastar::future<void> >(seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}&, seastar::future_state<int>&&)#1}, int>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}, seastar::future<void>::then_wrapped_nrvo<void, seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}>(seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Aborting on shard 0.
Backtrace:
  0x5c0f5c8
  0x5c45e71
  /jenkins/workspace/scylla-staging/artsiom_mishuta/dtest-pytest-gating/scylla/.ccm/scylla-repository/f4f724921cc71a06b16ddb8a48728d42d79acee0/libreloc/libc.so.6+0x3dbaf
  /jenkins/workspace/scylla-staging/artsiom_mishuta/dtest-pytest-gating/scylla/.ccm/scylla-repository/f4f724921cc71a06b16ddb8a48728d42d79acee0/libreloc/libc.so.6+0x8e883
  /jenkins/workspace/scylla-staging/artsiom_mishuta/dtest-pytest-gating/scylla/.ccm/scylla-repository/f4f724921cc71a06b16ddb8a48728d42d79acee0/libreloc/libc.so.6+0x3dafd
  /jenkins/workspace/scylla-staging/artsiom_mishuta/dtest-pytest-gating/scylla/.ccm/scylla-repository/f4f724921cc71a06b16ddb8a48728d42d79acee0/libreloc/libc.so.6+0x2687e
  0x5be4207
  0x47e66c4
  0x13a45fa
  0x5c2117f
  0x5c22467
  0x5c217c8
  0x5bb3da7
  0x5bb2f5c
  0x1338279
  0x1339cd0
  0x13368fc
  /jenkins/workspace/scylla-staging/artsiom_mishuta/dtest-pytest-gating/scylla/.ccm/scylla-repository/f4f724921cc71a06b16ddb8a48728d42d79acee0/libreloc/libc.so.6+0x27b89
  /jenkins/workspace/scylla-staging/artsiom_mishuta/dtest-pytest-gating/scylla/.ccm/scylla-repository/f4f724921cc71a06b16ddb8a48728d42d79acee0/libreloc/libc.so.6+0x27c4a
  0x13341a4
```

Decoded backtrace
```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:826
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:856
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:868
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:4062
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4038
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:4034
/data/scylla-s3-reloc.cache/by-build-id/7ea78454c2abfa05e04884e24c276a41865e6dd1/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7026fe8c129a523e07856d7c96306663ceab6e24, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:57
service::raft_group_registry::start_server_for_group(service::raft_server_for_group) at ./service/raft/raft_group_registry.cc:430
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/coroutine:240
 (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:125
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2666
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:3129
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3305
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3188
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:276
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:167
scylla_main(int, char**) at ./main.cc:670
std::function<int (int, char**)>::operator()(int, char**) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
main at ./main.cc:2081
__libc_start_call_main at ??:?
__libc_start_main_alias_2 at :?
_start at ??:?
```

**Comment by asias** [comment] 2024-01-11 12:23
> It sounds like another manifestation of the same problem - we're waiting indefinitely for ip to appear for a given host_id while applying raft log. If the node is gone (removed) we may never get an ip for it.

If raft knows the node is gone, do we really need to get the ip for the host?

> I'm currently sitting at this issue, I'll take this scenario into account.

**Comment by kbr-scylla** [comment] 2024-01-11 12:25
@asias the IP was being used to ban the node from the cluster and remove all traces about if from gossiper. But this goal can be achieved without obtaining the IP.

**Comment by temichus** [comment] 2024-01-11 15:09
REMINDER: remove issues related test disabling from https://github.com/scylladb/scylla-dtest/pull/3844 when issue closed

**Comment by kbr-scylla** [comment] 2024-01-15 10:16
I verified that this no longer reproduces after Petr's PR.
We should include a test in test.py, then close the issue

**Closed** 2024-02-06 16:21 UTC
Labels: area/topology changes, area/raft
