### ISSUE TITLE
Switch to uuid-generations as S3 in-bucket prefixes for sstables

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#14175] opened 2023-06-07 13:35 UTC
When S3-backed sstable is opened it generates itself a uuid that's committed into system.sstables and that's then used as a prefix for objects (the object name is thus `s3://$bucket/$this_uuid/$component_basename`)

Since now we have uuid-based generations for sstables, we can use generation as the in-bucket prefix and drop those fancy uuids altogether.

Refer to sstables/storage.cc:

```c++
void s3_storage::open(sstable& sst) {
    auto uuid = utils::UUID_gen::get_time_UUID();
    sst.manager().system_keyspace().sstables_registry_create_entry(_location, uuid, status_creating, ...).get();
    _remote_prefix = uuid.to_sstring();
    _client->put_object(make_s3_object_name(sst, component_type::TOC), std::move(bufs)).get();
}

sstring s3_storage::make_s3_object_name(const sstable& sst, component_type type) {
    return format("/{}/{}/{}", _bucket, *_remote_prefix, sstable_version_constants::get_component_map(sst.get_version()).at(type));
}
```

cc @tchaikov

**Comment by tchaikov** [comment] 2023-06-09 09:56
turns out we need to get #13932 landed before switching over to the `sstable::generation_type` and its generator. so, stay tuned!

**Comment by tchaikov** [comment] 2023-06-09 09:56
@mykaul hi Yaniv, could you please assign this issue to me?

**Closed** 2023-10-23 21:54 UTC
Labels: object storage

**Comment by avikivity** [comment] 2023-11-08 19:41
Not a bug, not backporting.
