### ISSUE TITLE
Scylla 2.2 to 2.3 upgrade procedure for Ubuntu upgrades the entire host, not just the Scylla packages

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylladb#3812] opened 2018-10-04 00:44 UTC
The guide at https://docs.scylladb.com/upgrade/upgrade-guide-from-2.2-to-2.3-ubuntu-16-04/ suggests using `dist-upgrade`, which will upgrade all the packages of the OS, not just scylla. For users who prefer not to touch other configured and locked down system components, we need a better procedure. 

I would suggest something like 
```bash
for i in `dpkg -l |grep scylla | awk '{ print $2 }'`; do 
    sudo apt-get install $i $(dpkg-query -Wf '${Depends}' $i | sed 's/ *\(([^()]*)\)\? *[,|] */\n/g') 
done
```

It seems to work in general, but needs to be tested properly

Example: 
  - Install an old version of ubuntu 16.04
  - Install Scylla 2.2
  - make sure the kernel isn't the latest available
  - run the scriptlet above
  - make sure kernel isn't touched, while all the Scylla packages are upgraded

**Comment by dorlaor** [comment] 2018-10-04 04:50
It's a good point but I think that users are better off to run the latest
OS.
It's worth to comment that the standard upgrade will upgrade the OS and in
a comment suggest your option.

**Comment by tzach** [comment] 2018-10-04 06:46
Good point @dyasny please open an issue (or send PR) to the internal doc repo
I agree with @dorlaor it's worth mentioning, but good practice anyway so we can keep the process simple.

**Comment by slivne** [comment] 2018-10-04 09:08
Closing this is a doc issue

**Comment by penberg** [comment] 2018-10-04 09:43
Can someone explain why `apt update scylla`, which updates a *metapackage* does not work as expected?

I don't think this is a documentation issue. There must be something wrong with how our package is configured.

**Comment by penberg** [comment] 2018-10-04 09:48
And btw, while @dorlaor's suggestion about keeping the OS up-to-date makes sense (and we can state that in the documentation), that's not related to `apt update scylla` not doing the right thing.

So can someone explain why the current behavior is correct?

**Comment by dyasny** [comment] 2018-10-04 13:11
This issue was brought up by a Scylla user who explicitly did not want to upgrade any other packages due to $reasons. And these reasons are quite valid in enterprise environments.

**Comment by tzach** [comment] 2018-10-11 09:51
@dyasny can you please clarify which update command was used?
The [docs include](https://docs.scylladb.com/upgrade/upgrade-guide-from-2.2-to-2.3-ubuntu-16-04/)
```
sudo apt-get update
sudo apt-get dist-upgrade scylla
```
If the first line is the issue, we should add a disclaimer in the doc
if the second, the problem is in the packaging

**Comment by dyasny** [comment] 2018-10-11 13:13
@tzach it is the second command. `dist-upgrade` will upgrade all the packages, not just Scylla. The command I provided above might not be very idempotent. So we need a better option

**Closed** 2023-03-29 18:34 UTC
