### ISSUE TITLE
materialized_views_test: interrupt_build_process_with_resharding_max_to_half_test: View ks.t_by_v2 not built

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#6666] opened 2020-06-18 06:04 UTC
Scylla version 8628ede009b339205e26b680c4e95c601fa38a6a

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/526/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_max_to_half_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 2020, in interrupt_build_process_with_resharding_max_to_half_test
    self._do_resharding_test(str(cpu_count() - 1), str(cpu_count() // 2))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 2082, in _do_resharding_test
    wait_for_view(cluster=self.cluster, session=session, ks='ks', view="t_by_v2")
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 967, in wait_for_view
    raise Exception(error_msg)
Exception: View ks.t_by_v2 not built
```

The test stop the cluster (gently) during view building and then starts all nodes back up with a different number of shards.

We see on https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/526/artifact/logs-release.2/1592453006704_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_max_to_half_test/node1.log
after restart:
```
INFO  2020-06-18 03:54:38,047 [shard 0] view - Resuming to build view ks.t_by_v2 at -7262916379954748337
ERROR 2020-06-18 03:54:38,048 [shard 11] view - Error applying view update to 127.0.37.3: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2020-06-18 03:54:38,048 [shard 5] view - Error applying view update to 127.0.37.3: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2020-06-18 03:54:38,048 [shard 11] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2020-06-18 03:54:38,048 [shard 5] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
...
INFO  2020-06-18 03:54:55,352 [shard 0] gossip - InetAddress 127.0.37.3 is now UP, status = NORMAL
INFO  2020-06-18 03:54:55,355 [shard 0] storage_service - Node 127.0.37.3 state jump to normal
INFO  2020-06-18 03:54:55,358 [shard 0] storage_service - Remove node 127.0.37.3 from pending replacing endpoint
INFO  2020-06-18 03:54:55,379 [shard 16] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-280-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-256-big-Data.db:level=0, ]
INFO  2020-06-18 03:54:55,381 [shard 15] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-447-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-423-big-Data.db:level=0, ]
INFO  2020-06-18 03:54:55,409 [shard 16] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-304-big-Data.db:level=0, ]. 22722 bytes to 11324 (~49% of original) in 24ms = 0.45MB/s. ~256 total partitions merged to 1.
INFO  2020-06-18 03:54:55,416 [shard 15] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-471-big-Data.db:level=0, ]. 16817 bytes to 11379 (~67% of original) in 26ms = 0.42MB/s. ~256 total partitions merged to 1.
INFO  2020-06-18 03:55:06,617 [shard 0] storage_service - Node 127.0.37.3 state jump to normal
INFO  2020-06-18 03:55:06,619 [shard 0] storage_service - Remove node 127.0.37.3 from pending replacing endpoint
INFO  2020-06-18 03:55:06,648 [shard 15] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-495-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-471-big-Data.db:level=0, ]
INFO  2020-06-18 03:55:06,652 [shard 16] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-328-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-304-big-Data.db:level=0, ]
INFO  2020-06-18 03:55:06,690 [shard 15] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-519-big-Data.db:level=0, ]. 16865 bytes to 11366 (~67% of original) in 33ms = 0.33MB/s. ~256 total partitions merged to 1.
INFO  2020-06-18 03:55:06,694 [shard 16] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-352-big-Data.db:level=0, ]. 22335 bytes to 11324 (~50% of original) in 35ms = 0.31MB/s. ~256 total partitions merged to 1.
INFO  2020-06-18 03:55:10,032 [shard 0] view - Finished building view ks.t_by_v2
```

On https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/526/artifact/logs-release.2/1592453006704_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_max_to_half_test/node2.log
There's no mention of view building after the restart other than starting the view builder service:
```
INFO  2020-06-18 03:54:49,255 [shard 0] init - Launching generate_mv_updates for non system tables
INFO  2020-06-18 03:54:49,255 [shard 0] init - starting the view builder
```

On https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/526/artifact/logs-release.2/1592453006704_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_max_to_half_test/node3.log

```
INFO  2020-06-18 03:55:18,522 [shard 0] init - Launching generate_mv_updates for non system tables
INFO  2020-06-18 03:55:18,522 [shard 0] init - starting the view builder
INFO  2020-06-18 03:55:18,550 [shard 0] view - Building view ks.t_by_v2, starting at token minimum token
INFO  2020-06-18 03:55:18,559 [shard 3] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node3/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-75-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node3/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-54-big-Data.db:level=0, ]
INFO  2020-06-18 03:55:18,560 [shard 0] init - starting native transport
INFO  2020-06-18 03:55:18,569 [shard 0] cql_server_controller - Starting listening for CQL clients on 127.0.37.3:9042 (unencrypted)
INFO  2020-06-18 03:55:18,579 [shard 0] thrift_controller - Thrift server listening on 127.0.37.3:9160 ...
INFO  2020-06-18 03:55:18,582 [shard 0] init - serving
INFO  2020-06-18 03:55:18,582 [shard 0] init - Scylla version 666.development-0.20200617.8628ede00 initialization completed.
INFO  2020-06-18 03:55:18,598 [shard 3] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node3/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-99-big-Data.db:level=0, ]. 10466 bytes to 5549 (~53% of original) in 28ms = 0.19MB/s. ~256 total partitions merged to 1.
INFO  2020-06-18 03:55:19,706 [shard 0] view - Finished building view ks.t_by_v2
```

**Comment by bhalevy** [comment] 2020-06-18 06:09
@psarna please look into this

**Comment by bhalevy** [comment] 2020-06-18 06:12
It's odd that according to https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/526/artifact/logs-release.2/dtest.log
```
2020-06-18 03:55:26,843 27910   dtest                          DEBUG    | materialized_views_test.py:TestMaterializedViews.interrupt_build_process_with_resharding_max_to_half_test - Waiting for view ks.t_by_v2 to finish building...
...
2020-06-18 04:03:26,688 27910   dtest                          DEBUG    | materialized_views_test.py:TestMaterializedViews.interrupt_build_process_with_resharding_max_to_half_test - Test failed with errors: [(<materialized_views_test.TestMaterializedViews testMethod=interrupt_build_process_with_resharding_max_to_half_test>, (<class 'Exception'>, Exception('View ks.t_by_v2 not built'), <traceback object at 0x7f07078e2be0>))]
```

The test waited for 8 minutes, starting at `2020-06-18 03:55:26,843` but we see no activity in the node logs after 03:55:1*.
node1:
```
INFO  2020-06-18 03:55:10,032 [shard 0] view - Finished building view ks.t_by_v2
```
node2:
```
INFO  2020-06-18 03:55:07,261 [shard 16] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-unbm3rpt/test/node2/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-400-big-Data.db:level=0, ]. 22337 bytes to 11323 (~50% of original) in 38ms = 0.28MB/s. ~256 total partitions merged to 1.
```
node3:
```
INFO  2020-06-18 03:55:19,706 [shard 0] view - Finished building view ks.t_by_v2
```

**Comment by nyh** [comment] 2020-06-18 08:06
Could this be a duplicate of #6094 ? In that issue the view *was* built, but not marked as built. @psarna commited a patch hoping to fix it, but apparently not all the problems are gone (and 6094 is still open too...).

**Comment by psarna** [comment] 2020-06-18 08:24
What's weird is that node2 shows no logs indicating that this view building even started... Perhaps the node is somehow not aware that it needs to build the view, or thinks that's already finished? I grepped node2's log for information about failed bookkeeping, but haven't found any.

**Comment by slivne** [comment] 2020-06-18 11:21
Check if there was replay of commitlog / sync to the commitlog 

We should check the RF of system_distributed.

**Comment by psarna** [comment] 2020-06-18 11:33
Actually, the progress should be stored locally in `system.scylla_views_builds_in_progress` and `system.built_views`. My point from #6094 about using higher cl when checking if a view was built still stands, but that seems to be a different issue - what's worrying is that I don't see `Finished building view ks.t_by_v2` anywhere in node2 logs. It suggests that after the restart, node2 somehow decided not to start building `t_b_v2`, I'll try to figure out how and why.

**Comment by psarna** [comment] 2020-06-18 11:34
Also, logs do not indicate that any commitlog activity was ongoing.

**Comment by psarna** [comment] 2020-06-18 14:25
sadly, this test always passes fine for me locally

**Comment by slivne** [comment] 2020-07-01 11:12
@psarna 
- we can try byo-dtest and see if it reproduces
- we can try to add debugggin information to dtest to see if it can help

**Comment by psarna** [comment] 2020-07-06 12:39
update: last week I tried both to reproduce locally multiple times and to run byo, but the latter didn't succeed due to configuration issues in the Jenkins job itself. Eliran offered to help me figure out how to successfully run a byo test and I'll take it from there.
As for debugging information - I don't have any ideas what to add really... current debugging *should* have been enough to figure out what's happening - it looks like the view building just didn't start at all, so it's hard to guess what was the reason. Perhaps if we manage to reproduce it with byo it will provide some more context.

**Comment by psarna** [comment] 2020-07-13 09:41
With Eliran's help I was able to run byo, but 3 consecutive runs I launched today all resulted in the test passing.

**Comment by DoronArazii** [comment] 2023-04-16 12:17
Last hit was almost 3 years ago.
Closing for the time being.

/Cc @bhalevy

**Closed by DoronArazii** 2023-04-16 12:17 UTC
Labels: materialized-views, dtest
