### ISSUE TITLE
view_builder: reads/writes to view_build_status with CL=ONE

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#11835] opened 2022-10-24 14:21 UTC
This table is part of the `system_distributed` keyspace, which has RF=3. Said table is used to keep track of in-progress builds and is also used by streaming to determine whether view updates have to be generated for the streamed data. Since all writes and reads to/from this table happen with `CL=ONE`, forgetting/failing to repair this table before node operations can result in unnecessary view update generation for streamed data, which can result in significant excess load to the cluster.
I don't know if there is a strong reason for using `CL=ONE` (@nyh can you think of one?), but if there isn't, we should do writes with `EACH_QUORUM` and reads with `LOCAL_QUORUM`.

**Comment by mykaul** [comment] 2023-06-28 12:53
@eliransin - this one is also an interesting case for CL=one writes?

**Comment by kostja** [comment] 2024-03-29 14:22
Duplicate of #15329

**Closed by kostja** 2024-03-29 14:22 UTC
Labels: area/materialized views
