### ISSUE TITLE
Failed to complete splitting of table due to raft::request_aborted (Request is aborted by a caller)] while scylla stopped during Rollback rolling-upgrade

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#20890] opened 2024-09-30 12:49 UTC
Longevity test failed because of error leveled log when split monitor was aborted for shutdown. Can be fixed by demoting log to warn when context is shutdown.

```
2024-09-04T17:06:51.756+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 6:main] batchlog_manager - Stopped
2024-09-04T17:06:51.757+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 4:main] batchlog_manager - Stopped
2024-09-04T17:06:51.757+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down batchlog manager was successful
2024-09-04T17:06:51.757+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down authorization cache api
2024-09-04T17:06:51.757+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down authorization cache api was successful
2024-09-04T17:06:51.757+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down auth service
2024-09-04T17:06:51.757+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down auth service was successful
2024-09-04T17:06:51.757+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down tracing
2024-09-04T17:06:51.757+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down tracing was successful
2024-09-04T17:06:51.757+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down group 0 usage in local storage
2024-09-04T17:06:51.757+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:strm] raft_topology - raft_state_monitor_fiber aborted with seastar::abort_requested_exception (abort requested)
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:strm] raft_topology - cleanup fiber aborted
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3      !ERR | scylla[11720]:  [shard 0:strm] storage_service - Failed to complete splitting of table 3dddc5d0-6ad4-11ef-86f2-3e83f53a6924 due to raft::request_aborted (Request is aborted by a caller), retrying after 5000ms seconds
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down group 0 usage in local storage was successful
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down storage service uninit address map
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down storage service uninit address map was successful
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down group 0 service
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down group 0 service was successful
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] init - Shutting down view builder
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 0:main] view - Stopping view builder
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 1:main] view - Stopping view builder
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 3:main] view - Stopping view builder
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 2:main] view - Stopping view builder
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 4:main] view - Stopping view builder
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 6:main] view - Stopping view builder
2024-09-04T17:06:51.758+00:00 rolling-upgrade--ubuntu-jammy-db-node-e8da0eed-0-3     !INFO | scylla[11720]:  [shard 5:main] view - Stopping view builder
```

**Comment by raphaelsc** [comment] 2024-11-18 16:45
> Hi [@raphaelsc](https://github.com/raphaelsc) , very similar error been spotted on this argus: https://argus.scylladb.com/tests/scylla-cluster-tests/529fe97a-d621-498f-8947-8928aa8201d0
> 
> basically the error looks like:
> 
> ```
> 2024-11-18T11:48:22.658+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-2     !INFO | scylla[10720]:  [shard 0:main] init - Shutting down group 0 service
> 2024-11-18T11:48:22.658+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-2      !ERR | scylla[10720]:  [shard 0:strm] storage_service - Failed to complete splitting of table 01a7b420-a596-11ef-ae4c-2ca870b061a8 due to raft::request_aborted (Aborted while waiting for leader on server: dfc6cb75-9bf2-4056-8bd6-579560c4bae8, latest applied entry: 201), retrying after 5000ms seconds
> 2024-11-18T11:48:22.658+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-2     !INFO | scylla[10720]:  [shard 0:main] init - Shutting down group 0 service was successful
> ```
> 
> could you please clarify if its kind of expected? maybe we should ignore it like in this issue

@timtimb0t seems different. split found the problem, but it's caused by something else. I'd open a github issue for some triage. what's the context we found that error? shutting down cluster? On master, we demoted that log to warn.

**Comment by timtimb0t** [comment] 2024-11-19 10:30
Here is the context:

## Packages

Base Scylla version: `6.0.4-20240919.7d421abec43d` with build-id `84cd4ae97ea9d9820a56ede82cc51ff18e019400`
Target Scylla version (or git commit hash): `2024.2.0-20241118.614d56348f46` with build-id `e67376d9ddfea081a3bab398f4581ecdde59911d`




Kernel Version: `6.8.0-1017-gcp`


## Issue description

- Start to upgrade 1 node
- Start to upgrade 2 node
- Rollback 1 and 2 nodes
- Upgrade 1 node

After the 1 node received update request at  11:40:24 the next error occurred (during shut down):
```
2024-11-18T11:41:25.160+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-1     !INFO | scylla[10765]:  [shard 0:strm] raft_topology - raft_state_monitor_fiber aborted with seastar::abort_requested_exception (abort requested)
2024-11-18T11:41:25.160+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-1     !INFO | scylla[10765]:  [shard 0:strm] raft_topology - cleanup fiber aborted
2024-11-18T11:41:25.161+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-1      !ERR | scylla[10765]:  [shard 0:strm] storage_service - Failed to complete splitting of table 01a7b420-a596-11ef-ae4c-2ca870b061a8 due to raft::request_aborted (Aborted while waiting for leader on server: 58e4b145-9334-4fc2-80aa-4fc36f705bdc, latest applied entry: 195), retrying after 5000ms seconds
2024-11-18T11:41:25.161+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-1     !INFO | scylla[10765]:  [shard 0:main] init - Shutting down group 0 usage in local storage was successful
```
the same picture with the second node that received the same request at 11:47:45:

```
2024-11-18T11:48:22.658+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-2     !INFO | scylla[10720]:  [shard 0:main] init - Shutting down group 0 service
2024-11-18T11:48:22.658+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-2      !ERR | scylla[10720]:  [shard 0:strm] storage_service - Failed to complete splitting of table 01a7b420-a596-11ef-ae4c-2ca870b061a8 due to raft::request_aborted (Aborted while waiting for leader on server: dfc6cb75-9bf2-4056-8bd6-579560c4bae8, latest applied entry: 201), retrying after 5000ms seconds
2024-11-18T11:48:22.658+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-2     !INFO | scylla[10720]:  [shard 0:main] init - Shutting down group 0 service was successful
```

and as result such an error occurred on the 1 node:
```
2024-11-18T12:04:17.949+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-1     !INFO | scylla[23354]:  [shard 0:main] init - Shutting down configurables
2024-11-18T12:04:17.949+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-1     !INFO | scylla[23354]:  [shard 0:main] init - Shutting down configurables was successful
2024-11-18T12:04:17.949+00:00 rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-1      !ERR | scylla[23354]:  [shard 0:main] init - Startup failed: service::raft_operation_timeout_error (group [6f795ef0-a595-11ef-b16b-be9dd73f59a9] raft operation [read_barrier] timed out)
```


## Impact

One of the nodes didn't update properly

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-3 (34.74.201.133 | 10.142.15.217) (shards: 7)
- rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-2 (35.229.95.106 | 10.142.15.211) (shards: 7)
- rolling-upgrade--ubuntu-jammy-db-node-529fe97a-0-1 (34.75.143.222 | 10.142.15.209) (shards: 7)


OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts` (gce: undefined_region)

Test: `rolling-upgrade-with-sla-no-shares-test`
Test id: `529fe97a-d621-498f-8947-8928aa8201d0`
Test name: `enterprise-2024.2/rolling-upgrade/rolling-upgrade-with-sla-no-shares-test`
Test method: `upgrade_test.UpgradeTest.test_generic_cluster_upgrade`
Test config file(s):

- [generic-rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/8672d338b2ce83acf6ab81b6be5f3d7f72b03ff4/test-cases/upgrades/generic-rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 529fe97a-d621-498f-8947-8928aa8201d0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=529fe97a-d621-498f-8947-8928aa8201d0)
- Show all stored logs command: `$ hydra investigate show-logs 529fe97a-d621-498f-8947-8928aa8201d0`


## Logs:
- **db-cluster-529fe97a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/529fe97a-d621-498f-8947-8928aa8201d0/20241118_121348/db-cluster-529fe97a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/529fe97a-d621-498f-8947-8928aa8201d0/20241118_121348/db-cluster-529fe97a.tar.gz)
- **sct-runner-events-529fe97a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/529fe97a-d621-498f-8947-8928aa8201d0/20241118_121348/sct-runner-events-529fe97a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/529fe97a-d621-498f-8947-8928aa8201d0/20241118_121348/sct-runner-events-529fe97a.tar.gz)
- **sct-529fe97a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/529fe97a-d621-498f-8947-8928aa8201d0/20241118_121348/sct-529fe97a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/529fe97a-d621-498f-8947-8928aa8201d0/20241118_121348/sct-529fe97a.log.tar.gz)
- **loader-set-529fe97a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/529fe97a-d621-498f-8947-8928aa8201d0/20241118_121348/loader-set-529fe97a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/529fe97a-d621-498f-8947-8928aa8201d0/20241118_121348/loader-set-529fe97a.tar.gz)
- **monitor-set-529fe97a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/529fe97a-d621-498f-8947-8928aa8201d0/20241118_121348/monitor-set-529fe97a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/529fe97a-d621-498f-8947-8928aa8201d0/20241118_121348/monitor-set-529fe97a.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2024.2/job/rolling-upgrade/job/rolling-upgrade-with-sla-no-shares-test/9/)
[Argus](https://argus.scylladb.com/test/51ef5acf-b341-4e5a-8329-bd4aa3cafbc9/runs?additionalRuns[]=529fe97a-d621-498f-8947-8928aa8201d0)
</details>

**Comment by timtimb0t** [comment] 2024-11-19 10:33
Also could you please share the new issue? I'll attach it to argus

**Comment by kostja** [comment] 2024-11-22 17:50
I disagree it's a p3. We're plagued by shutdown bugs, and each time we se raft:: in the name, @kbr-scylla team gets involved.

**Comment by kostja** [comment] 2024-11-22 18:25
Generally our QA team treats any error in a normally operating cluster as a bug. Indeed, if the exception is bening, why is it not suppressed in the first place by the code? 
Every new test will have to add this suppression - and it will have to do it after a painful cycle of CI failure -> issue -> investigation -> suppression.

**Comment by kostja** [comment] 2024-11-22 18:25
> Generally our QA team treats any error in a normally operating cluster as a bug. Indeed, if the exception is benign, why is it not suppressed in the first place by the code? Every new test will have to add this suppression - and it will have to do it after a painful cycle of CI failure -> issue -> investigation -> suppression.

**Comment by kostja** [comment] 2024-11-22 18:27
Actually, come to think about it a bit more, I disagree with you closing this bug. I think I made the reason for this very clear. Any error in the log with raft in its name gets assigned to @kbr-scylla team for investigation. Closing this issue is doing him a very very bad favour.

**Comment by raphaelsc** [comment] 2024-11-22 18:36
> Generally our QA team treats any error in a normally operating cluster as a bug. Indeed, if the exception is benign, why is it not suppressed in the first place by the code? Every new test will have to add this suppression - and it will have to do it after a painful cycle of CI failure -> issue -> investigation -> suppression.

If we're picking only patched versions in the upgrade test, we wouldn't get the failure anymore.

For example, the cleanup fiber in storage service also handles it and dumps a message with info level

```
        } catch (raft::request_aborted&) {
             rtlogger.info("cleanup fiber aborted");
             break;
        }
```

With the patch I mentioned, the log will be demoted to warn and that won't cause the test to fail. I won't disagree with the procedures though, in general, I think it's very good that raft team takes a 2nd look to check we don't have a bigger problem here.

**Closed** 2024-11-22 19:09 UTC
Labels: P3, area/tablets
