### ISSUE TITLE
`ninja build/<mode>/scylla`: "unknown target"

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#18321] opened 2024-04-20 17:30 UTC
```
$ ./configure.py --mode dev
Note: using the lld linker
-- Found Boost: /usr/include (found suitable version "1.78.0", minimum required is "1.73.0")  
-- Found Boost: /usr/include (found suitable version "1.78.0", minimum required is "1.73.0") found components: filesystem program_options thread unit_test_framework chrono atomic 
-- Configuring done (0.3s)
-- Generating done (0.2s)
-- Build files have been written to: /home/kbraun/dev/scylladb/build/dev/seastar
$ ninja -j10 build/dev/scylla
[1/2] ./SCYLLA-VERSION-GEN --output-dir /home/kbraun/dev/scylladb/build
ninja: error: unknown target 'build/dev/scylla'
```

This is how I build Scylla 99% of the time (I want to build just the binary.)

Looks like 6e487a49aa8d5504567b85a6ce157886ecb750b3 broke it --- running the above before that commit works.

**Comment by michoecho** [comment] 2024-04-20 19:26
The commit didn't break the target, it just renamed it (and all other file targets) to the absolute path instead of the relative path.
So you can use `ninja $PWD/build/dev/scylla`.

**Comment by avikivity** [comment] 2024-04-20 20:41
It's enough to convert the absolute path back to a relative one, no need for phony targets (and we'd need many).

IIRC make knows how to do this automatically, too bad ninja doesn't.

**Comment by nyh** [comment] 2024-04-21 08:07
Whoever did this change, please create another change to fix it. Like Kamil, I **almost always** do `ninja build/dev/scylla` (or some specific unit test), and having to type an even longer command is not a welcome change. 

Additionally, it's a mistake to put full paths in makefiles. I should be able to move a Scylla working directory and it should continue working. I don't do this often, but in the rare cases that I might, I'd be surprised if it stopped working.

**Comment by michoecho** [comment] 2024-04-22 05:37
> Additionally, it's a mistake to put full paths in makefiles. I should be able to move a Scylla working directory and it should continue working. I don't do this often, but in the rare cases that I might, I'd be surprised if it stopped working.

It never worked. Because:
1. You would need to avoid *all* uses of absolute paths, which requires some amount of discipline, more than `configure.py` ever had.
2. cmake generates its build scripts with absolute paths as well, so the Seastar build directory wouldn't survive the move even if you perfected the `configure.py`.

But also, why would anyone want this to work anyway?

**Comment by kostja** [comment] 2024-04-24 11:34
Can we just remove configure.py please? Sorry to say it but the whole problem is coming from an attempt to add out-of-source build to ninja, while cmake has it out of the box. When are going to stop inventing cmake?

**Comment by avikivity** [comment] 2024-04-24 11:51
> Can we just remove configure.py please? Sorry to say it but the whole problem is coming from an attempt to add out-of-source build to configure.py, while cmake has it out of the box. When are going to stop inventing cmake? And yes, ninja can be the build tool used for cmake, instead of make, if we like ninja so much.

Post a patch

**Comment by michoecho** [comment] 2024-04-25 08:35
> > Can we just remove configure.py please? Sorry to say it but the whole problem is coming from an attempt to add out-of-source build to configure.py, while cmake has it out of the box. When are going to stop inventing cmake? And yes, ninja can be the build tool used for cmake, instead of make, if we like ninja so much.
> 
> Post a patch

@avikivity Would you accept it?

**Comment by avikivity** [comment] 2024-04-25 08:48
The plan is to replace the guts of configure.py with calls to cmake, leaving a compatibility interface. @tchaikov is making slow progress on it.

**Comment by nyh** [comment] 2024-04-25 09:10
> Can we just remove configure.py please? Sorry to say it but the whole problem is coming from an attempt to add out-of-source build to configure.py, while cmake has it out of the box. When are going to stop inventing cmake?

This is not a fair statement. We've had this configure.py for many years, and never had **this** problem, described in this issue, so it's not fair pinning this recent regression on configure.py, of all things.

Migrating to cmake would have happened quicker if we had many developers actually believing that cmake is a great system, the best invention since sliced bread, or that it would really improve something - anything - in the build experience. But I'm not sure many of us actually believe any of these statements. Believing that "everybody in the community uses it" (?) is not the same as believing it is good or improves something real - and not the same as wanting to **personally** be involved in maintaining the build scripts in that new language because this language is so lovely.  Looking at "git blame" in Scylla's configure.py (`git blame --line-porcelain configure.py | grep '^author ' | sort | uniq -c | sort -n`) I see 54 authors, with 17 authors having written more than 30 lines in the existing configure.py.  In `Seastar's CMakeLists.txt, we have only 5 authors having written more than 30 lines, and two of the two three - who together wrote 65% (!!) of the current Seastar CMakeLists.txt, are no longer working in ScyllaDB. It sounds like many current Scylla employees want us to use cmake - but only if someone else, not them, actually works on the cmake code :-( And this is why we haven't moved to cmake - not because of some sinister plan to avoid it.

**Comment by michoecho** [comment] 2024-04-25 10:32
I have one objective argument against cmake: if you want some feature which cmake didn't implement, then in your own build generator you can implement it yourself. If you rely on cmake, you might have to wait years.

For example, there is a [7-year old feature request](https://gitlab.kitware.com/cmake/cmake/-/issues/16808) about adding some configurability to LTO. (Which is not directly relevant to us, but it would be if we used GCC). If you use your own build generator, adding this customization is trivial.

Another example: tweaking the build order. I once sent a patch which moved `messaging_service.cc` to the front of build order, because it's by far the longest-compiling file, and often it's the bottleneck of the entire compilation, so it makes sense to start it ASAP. Trivial with configure.py, AFAIK impossible with CMake.

(Yet another example, most likely irrelevant for Scylla, but relevant for a personal project of mine — cmake doesn't support header units, and only recently added support modules. It has some [plans](https://gitlab.kitware.com/cmake/cmake/-/issues/25293) for indefinite future. With a configure.py-style generator it took me a few hours to switch to modules and header units.)

IMHO the entire value of "standard" build generators is that they abstract over multiple operating systems, and if you don't make use of that, then all you get is extra baggage and a layer of misdirection.

As for subjective arguments, I don't like the CMake language. And I think it's easier to debug the output of configure.py, which is just a python script that prints text, than CMake, whose decisions are hidden in its source code.

But all in all, it doesn't really matter. Scylla has many problems with how its build is set up, but the build scripts aren't a big one.

> Can we just remove configure.py please? Sorry to say it but the whole problem is coming from an attempt to add out-of-source build to configure.py, while cmake has it out of the box.

This issue is just a silly mistake that can be fixed in a few minutes.

**Comment by avikivity** [comment] 2024-04-25 10:36
What's so good about sliced bread?

**Comment by avikivity** [comment] 2024-04-25 10:39
> As for subjective arguments, I don't like the CMake language. And I think it's easier to debug the output of configure.py, which is just a python script that prints text, than CMake, whose decisions are hidden in its source code.

Everyone knows Python, and it's not a tricky language. Few know cmake well, and it has plenty of rough edges.

The main advantage of cmake is that it integrates with the rest of the C++ ecosystem. It can consume other cmake projects or be consumed by them. It has only minor bearing for us, but it's there.

It may also save us from having to implement support for C++ modules (though that's blocked by lack of ccache/distcc support).

**Comment by nyh** [comment] 2024-04-25 10:44
> IMHO the entire value of "standard" build generators is that they abstract over multiple operating systems, and if you don't make use of that, then all you get is extra baggage and a layer of misdirection.

"layer of misdirection" is either the greatest Freudian slip of all time, or a great deliberate slogan :-)

**Comment by michoecho** [comment] 2024-04-25 11:08
> It may also save us from having to implement support for C++ modules
 
@avikivity It really isn't that hard. But...

> (though that's blocked by lack of ccache/distcc support).

...when I switched a personal project to modules, what made me give up and revert wasn't ccache/distcc, but the lack of support in clangd. (It can't automatically pick up changes in the modules your current file depends on, until you recompile them manually). 

And I see that initial clangd support remains stuck in review hell (https://github.com/llvm/llvm-project/pull/66462).

**Closed** 2024-04-29 11:59 UTC
