### ISSUE TITLE
SEGV Scylla 4.6.1 Redhat 7 with Rust driver 0.4.4

### ISSUE THREAD

**Issue by dominikwerder** [scylladb/scylladb#10493] opened 2022-05-05 13:38 UTC
*Installation details*
Scylla version (or git commit hash): 4.6.1 from RPM
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): redhat 7.9
Platform (physical/VM/cloud instance type/docker): physical
Client: Rust, 0.4.4

Query against scylla (not sure which yet, might vary) crashes the node:

scylla[17801]: Segmentation fault on shard 23.
scylla[17801]: Backtrace:
scylla[17801]: 0x3db6c38
scylla[17801]: 0x3de7a26
scylla[17801]: 0x4436c11
scylla[17801]: 0x7f1a0eb1fa1f
scylla[17801]: 0x1db1863
scylla[17801]: 0x22e0dd8
scylla[17801]: 0x3dc9604
scylla[17801]: 0x3dca9f7
scylla[17801]: 0x3de8025
scylla[17801]: 0x3da1c3a
scylla[17801]: /opt/scylladb/libreloc/libpthread.so.0+0x9298
scylla[17801]: /opt/scylladb/libreloc/libc.so.6+0x100352

Same on the other mcahine:
scylla[48713]: Segmentation fault on shard 4.
scylla[48713]: Backtrace:
scylla[48713]: 0x3db6c38
scylla[48713]: 0x3de7a26
scylla[48713]: 0x4436c11
scylla[48713]: 0x7fc4eb075a1f
scylla[48713]: 0x1db1863
scylla[48713]: 0x22e0dd8
scylla[48713]: 0x3dc9604
scylla[48713]: 0x3dca9f7
scylla[48713]: 0x3de8025
scylla[48713]: 0x3da1c3a
scylla[48713]: /opt/scylladb/libreloc/libpthread.so.0+0x9298
scylla[48713]: /opt/scylladb/libreloc/libc.so.6+0x100352

**Comment by psarna** [comment] 2022-05-05 13:42
I would guess it's a duplicate of https://github.com/scylladb/scylla/issues/9774 , fixed in master (with experimental Raft), not in 4.6

**Comment by mykaul** [comment] 2023-04-17 13:32
Most likely fixed with 5.2, with Raft support. Closing - please re-test with 5.2 (GA soon!)

**Closed by mykaul** 2023-04-17 13:32 UTC
Labels: User Request, schema changes
