### ISSUE TITLE
test_raft_upgrade: test_recovery_after_majority_loss fails with NoHostAvailable('Unable to connect to any servers', {})

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12520] opened 2023-01-13 11:00 UTC
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/5576/testReport/junit/(root)/non-boost%20tests/Unit_Tests___topology_raft_disabled_test_raft_upgrade_release_3/
Scylla version 5.2.0~dev-0.20230112.4e41e7531c6b with build-id 99672d2b15986b8cd9706565c1e383264ac13a52

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/5576/artifact/testlog/x86_64/release/topology_raft_disabled.test_raft_upgrade.3.log
```
03:17:55.111 INFO> Killing all nodes except Server(222, 127.23.147.33)
...
03:17:55.208 INFO> Entering recovery state on Server(222, 127.23.147.33)
03:17:55.209 INFO> Stopping Server(222, 127.23.147.33) gracefully
03:17:55.210 DEBUG> ManagerClient stopping gracefully 222
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/5576/artifact/testlog/x86_64/test.py.debug-release-dev.log
```
03:17:55.163 INFO> [release/topology_raft_disabled.test_raft_upgrade.3] Cluster ScyllaCluster(name: f827092a-92df-11ed-bd2c-141877431f1a, running: ScyllaServer(234, 127.23.147.64, c21ba3cd-06c0-48b3-b5bd-57be1623a811), ScyllaServer(222, 127.23.147.33, a3b26c80-1554-45c7-af5b-9fa0b0f100d4), ScyllaServer(230, 127.23.147.4, 0a519418-ffd0-42a0-aba2-3b1e5f545e2b), stopped: ) stopping server 230
03:17:55.164 INFO> [release/topology_raft_disabled.test_raft_upgrade.3] stopping ScyllaServer(230, 127.23.147.4, 0a519418-ffd0-42a0-aba2-3b1e5f545e2b) in scylla-230
03:17:55.165 INFO> [release/topology_raft_disabled.test_raft_upgrade.3] Cluster ScyllaCluster(name: f827092a-92df-11ed-bd2c-141877431f1a, running: ScyllaServer(234, 127.23.147.64, c21ba3cd-06c0-48b3-b5bd-57be1623a811), ScyllaServer(222, 127.23.147.33, a3b26c80-1554-45c7-af5b-9fa0b0f100d4), stopped: ) stopping server 234
03:17:55.165 INFO> [release/topology_raft_disabled.test_raft_upgrade.3] stopping ScyllaServer(234, 127.23.147.64, c21ba3cd-06c0-48b3-b5bd-57be1623a811) in scylla-234
03:17:55.207 INFO> [release/topology_raft_disabled.test_raft_upgrade.3] stopped ScyllaServer(230, 127.23.147.4, 0a519418-ffd0-42a0-aba2-3b1e5f545e2b) in scylla-230
03:17:55.207 INFO>  [13/Jan/2023:01:17:55 +0000] "GET /cluster/server/230/stop HTTP/1.1" 200 229 "-" "Python/3.11 aiohttp/3.8.3"
03:17:55.207 INFO> [release/topology_raft_disabled.test_raft_upgrade.3] stopped ScyllaServer(234, 127.23.147.64, c21ba3cd-06c0-48b3-b5bd-57be1623a811) in scylla-234
03:17:55.207 INFO>  [13/Jan/2023:01:17:55 +0000] "GET /cluster/server/234/stop HTTP/1.1" 200 230 "-" "Python/3.11 aiohttp/3.8.3"
03:17:55.215 INFO> [release/topology_raft_disabled.test_raft_upgrade.3] Cluster ScyllaCluster(name: f827092a-92df-11ed-bd2c-141877431f1a, running: ScyllaServer(222, 127.23.147.33, a3b26c80-1554-45c7-af5b-9fa0b0f100d4), stopped: ScyllaServer(230, 127.23.147.4, 0a519418-ffd0-42a0-aba2-3b1e5f545e2b), ScyllaServer(234, 127.23.147.64, c21ba3cd-06c0-48b3-b5bd-57be1623a811)) stopping server 222
03:17:55.215 INFO> [release/topology_raft_disabled.test_raft_upgrade.3] gracefully stopping ScyllaServer(222, 127.23.147.33, a3b26c80-1554-45c7-af5b-9fa0b0f100d4)
...
03:22:55.614 INFO> [release/topology_raft_disabled.test_raft_upgrade.3] Finished test release/topology_raft_disabled.test_raft_upgrade.3::test_recovery_after_majority_loss, cluster: ScyllaCluster(name: f827092a-92df-11ed-bd2c-141877431f1a, running: , stopped: ScyllaServer(230, 127.23.147.4, 0a519418-ffd0-42a0-aba2-3b1e5f545e2b), ScyllaServer(234, 127.23.147.64, c21ba3cd-06c0-48b3-b5bd-57be1623a811))
03:22:55.614 ERROR> Error handling request
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 940, in _after_test
    self.cluster.after_test(self.current_test_case_full_name)
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 713, in after_test
    if self._get_keyspace_count() != self.keyspace_count:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 688, in _get_keyspace_count
    assert self.running, "No active nodes left"
AssertionError: No active nodes left
03:22:55.626 INFO>  [13/Jan/2023:01:22:55 +0000] "GET /cluster/after-test HTTP/1.1" 500 245 "-" "Python/3.11 aiohttp/3.8.3"
03:22:55.856 INFO> [release/topology_raft_disabled.test_raft_upgrade.3] Test topology_raft_disabled.test_raft_upgrade.3 failed 
```

**Comment by bhalevy** [comment] 2023-01-13 11:00
Cc @kostja @kbr-scylla

**Comment by kbr-scylla** [comment] 2023-01-13 11:02
Known:
https://github.com/scylladb/scylladb/issues/8079#issuecomment-1370849745

**Comment by kbr-scylla** [comment] 2023-01-13 11:03
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/5576/artifact/testlog/x86_64/release/scylla-222.log
```
INFO  2023-01-13 03:18:02,946 [shard 0] hints_manager - Asked to stop
INFO  2023-01-13 03:18:02,946 [shard 0] hints_manager - Stopped
INFO  2023-01-13 03:18:02,946 [shard 0] hints_manager - Asked to stop
INFO  2023-01-13 03:18:02,946 [shard 1] hints_manager - Asked to stop
INFO  2023-01-13 03:18:02,946 [shard 1] hints_manager - Stopped
INFO  2023-01-13 03:18:02,946 [shard 1] hints_manager - Asked to stop
INFO  2023-01-13 03:18:02,946 [shard 1] hints_manager - Stopped
INFO  2023-01-13 03:22:56,997 [shard 0] hints_manager - Stopped

```

**Comment by bhalevy** [comment] 2023-01-13 15:29
How is the hang on shutdown related to this issue?

**Comment by kbr-scylla** [comment] 2023-01-13 15:36
node hanged on shutdown => test timed out => test failed
```
>       await restart(manager, srv1)

test/topology_raft_disabled/test_raft_upgrade.py:346: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology_raft_disabled/test_raft_upgrade.py:37: in restart
    await manager.server_stop_gracefully(server.server_id)
test/pylib/manager_client.py:137: in server_stop_gracefully
    await self.client.get_text(f"/cluster/server/{server_id}/stop_gracefully")
test/pylib/rest_client.py:78: in get_text
    ret = await self._fetch("GET", resource_uri, response_type = "text", host = host,
test/pylib/rest_client.py:60: in _fetch
    async with request(method, uri,
/usr/lib64/python3.11/site-packages/aiohttp/client.py:1189: in __aenter__
    self._resp = await self._coro
/usr/lib64/python3.11/site-packages/aiohttp/client.py:560: in _request
    await resp.start(conn)
/usr/lib64/python3.11/site-packages/aiohttp/client_reqrep.py:894: in start
    with self._timer:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <aiohttp.helpers.TimerContext object at 0x7fd1cc4928d0>
exc_type = <class 'asyncio.exceptions.CancelledError'>
exc_val = CancelledError(), exc_tb = <traceback object at 0x7fd1cc469b00>

    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> Optional[bool]:
        if self._tasks:
            self._tasks.pop()
    
        if exc_type is asyncio.CancelledError and self._cancelled:
>           raise asyncio.TimeoutError from None
E           TimeoutError

```
(from https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/5576/artifact/testlog/x86_64/release/topology_raft_disabled.test_raft_upgrade.3.log)

**Comment by kbr-scylla** [comment] 2023-01-13 15:37
The "assert self.running, "No active nodes left"" is caused by the framework trying to perform a post-test check on a completely dead cluster. I guess this can be considered a bug in the framework, which should be prepared to deal with such clusters. @kostja @alecco

**Comment by kostja** [comment] 2023-01-13 15:52
Yes, we should not check it for dirty clusters, it's a one line fix. The assert is there because for clean clusters we need to verify the environment is clean before recycle.

**Comment by kbr-scylla** [comment] 2023-01-13 15:54
@kostja please create a dedicated issue for that, this issue describes a different problem (`test_recovery_after_majority_loss` failure) which is a duplicate of https://github.com/scylladb/scylladb/issues/8079#issuecomment-1370849745

**Closed by kbr-scylla** 2023-01-13 15:54 UTC
Labels: bug, test, test.py
