### ISSUE TITLE
Data loss when a node crashes

### ISSUE THREAD

**Issue by margdoc** [scylladb/scylladb#16872] opened 2024-01-19 09:57 UTC
When running such a test:

```python
from cassandra.cluster import Cluster
from test.pylib.manager_client import ManagerClient

import pytest
import logging

logger = logging.getLogger(__name__)

@pytest.mark.asyncio
async def test_data_loss(manager: ManagerClient):
    server = await manager.server_add()

    manager.cql.execute("CREATE KEYSPACE ks WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1}")
    manager.cql.execute("CREATE TABLE ks.t (k int PRIMARY KEY, v int)")

    for i in range(256):
        manager.cql.execute(f"INSERT INTO ks.t (k, v) VALUES ({i}, {i})")

    await manager.server_stop(server.server_id)
    await manager.server_start(server.server_id)

    cluster = Cluster([server.ip_addr])
    cql = cluster.connect()

    res = cql.execute(f"SELECT v FROM ks.t")
    assert len(list(res)) == 256
```

Assert throws error:
```
>       assert len(list(res)) == 256
E       assert 0 == 256
E        +  where 0 = len([])
E        +    where [] = list(<cassandra.cluster.ResultSet object at 0x7fed71b6f8d0>)
```
which indicates that inserted data was lost during the crash and not recovered after restart. Shouldn't it be recovered using the commitlog?

cc @kbr-scylla

**Comment by kbr-scylla** [comment] 2024-01-19 10:18
I think this is caused by the default commitlog configuration i.e. periodic mode
```cpp
    , commitlog_sync(this, "commitlog_sync", value_status::Used, "periodic",
        "The method that Scylla uses to acknowledge writes in milliseconds:\n"
        "\n"
        "\tperiodic : Used with commitlog_sync_period_in_ms (Default: 10000 - 10 seconds ) to control how often the commit log is synchronized to disk. Periodic syncs are acknowledged immediately.\n"
        "\tbatch : Used with commitlog_sync_batch_window_in_ms (Default: disabled **) to control how long Scylla waits for other writes before performing a sync. When using this method, writes are not acknowledged until fsynced to disk.\n"
        "Related information: Durability")
```

I checked that adding a sleep before the `stop` fixes the problem

And adding
```python3
        'commitlog_sync': 'batch',
```
to scylla_cluster.py `make_scylla_confg` also helps.

So closing, as it's not a bug.

**Closed by kbr-scylla** 2024-01-19 10:18 UTC
