### ISSUE TITLE
Hundreds of "oversized allocation" warnings during the test

### ISSUE THREAD

**Issue by Mark-Gurevich** [scylladb/scylladb#12319] opened 2022-12-14 16:19 UTC
## Installation details

Kernel Version: 5.15.0-1026-aws
Scylla version (or git commit hash): `5.2.0~dev-20221210.e47794ed9832` with build-id `a0d3f077099c66bf6c75707e386c6be3ba2c431f`

Cluster size: 40 nodes (m5d.large) and scale to 60 nodes.

Scylla Nodes used in this run:
- cluster-scale-test-master-db-node-500732b4-9 (18.215.126.235 | 10.12.3.162) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-8 (44.200.62.234 | 10.12.1.167) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-7 (3.230.115.24 | 10.12.1.71) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-62 (44.204.106.156 | 10.12.1.65) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-61 (34.239.94.161 | 10.12.3.203) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-60 (44.198.171.184 | 10.12.0.52) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-6 (3.238.103.134 | 10.12.3.156) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-59 (18.213.118.184 | 10.12.2.60) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-58 (34.205.48.42 | 10.12.0.92) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-57 (44.192.42.182 | 10.12.1.206) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-56 (3.94.20.123 | 10.12.1.91) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-55 (3.235.124.167 | 10.12.0.240) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-54 (3.209.81.131 | 10.12.1.110) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-53 (3.237.87.23 | 10.12.1.104) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-52 (3.236.176.218 | 10.12.1.17) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-51 (34.234.170.107 | 10.12.2.100) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-50 (44.193.74.227 | 10.12.3.144) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-5 (35.172.236.66 | 10.12.1.64) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-49 (3.215.179.139 | 10.12.2.172) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-48 (3.236.185.214 | 10.12.0.67) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-47 (44.204.222.52 | 10.12.0.110) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-46 (54.173.13.114 | 10.12.2.170) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-45 (3.222.116.248 | 10.12.2.110) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-44 (34.200.250.47 | 10.12.0.35) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-43 (3.227.245.18 | 10.12.0.124) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-42 (34.237.222.82 | 10.12.2.1) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-41 (3.239.106.79 | 10.12.3.195) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-40 (34.206.72.221 | 10.12.0.233) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-4 (3.219.34.2 | 10.12.0.25) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-39 (18.213.218.44 | 10.12.3.84) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-38 (44.201.1.86 | 10.12.1.194) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-37 (3.228.8.96 | 10.12.0.26) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-36 (44.199.200.171 | 10.12.2.177) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-35 (44.192.102.54 | 10.12.0.160) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-34 (3.239.187.218 | 10.12.0.255) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-33 (44.202.184.106 | 10.12.0.39) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-32 (3.238.41.242 | 10.12.1.217) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-31 (44.200.126.73 | 10.12.3.174) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-30 (34.201.3.58 | 10.12.3.115) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-3 (3.215.73.15 | 10.12.1.106) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-29 (3.221.127.106 | 10.12.3.150) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-28 (44.192.89.132 | 10.12.3.69) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-27 (3.234.227.53 | 10.12.0.176) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-26 (54.236.36.183 | 10.12.2.46) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-25 (44.204.96.195 | 10.12.0.141) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-24 (3.237.93.138 | 10.12.0.105) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-23 (3.236.201.120 | 10.12.3.250) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-22 (44.211.87.240 | 10.12.1.38) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-21 (3.236.76.112 | 10.12.0.148) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-20 (100.27.39.206 | 10.12.2.66) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-2 (34.239.227.251 | 10.12.0.196) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-19 (54.160.5.146 | 10.12.2.112) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-18 (3.227.20.253 | 10.12.1.8) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-17 (18.234.139.95 | 10.12.3.152) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-16 (35.170.72.97 | 10.12.1.73) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-15 (3.231.27.199 | 10.12.0.6) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-14 (34.205.54.183 | 10.12.1.21) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-13 (3.237.252.139 | 10.12.1.10) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-12 (44.204.197.154 | 10.12.2.120) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-11 (44.193.82.166 | 10.12.0.16) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-10 (34.236.242.196 | 10.12.1.202) (shards: 2)
- cluster-scale-test-master-db-node-500732b4-1 (44.212.46.232 | 10.12.2.227) (shards: 2)

OS / Image: `ami-0131a575da50af716` (aws: us-east-1)

Test: `scale-40-60-cluster-test-test`
Test id: `500732b4-ccfa-491f-b116-4a63c34b0200`
Test name: `scylla-master/raft/scale-40-60-cluster-test-test`
Test config file(s):

- [scale-cluster.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d007cef368b29d19563df5b4933744ae44448cb5/test-cases/scale/scale-cluster.yaml)

## Issue description

grep "oversized allocation" sct-500732b4.log | wc -l
963

Node tool status before the first warning appeared:
```
< t:2022-12-12 01:50:02,806 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Datacenter: us-east
< t:2022-12-12 01:50:02,807 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > ===================
< t:2022-12-12 01:50:02,807 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Status=Up/Down
< t:2022-12-12 01:50:02,808 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > |/ State=Normal/Leaving/Joining/Moving
< t:2022-12-12 01:50:02,809 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > --  Address      Load       Tokens       Owns    Host ID                               Rack
< t:2022-12-12 01:50:02,816 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.0.141  4.71 MB    256          ?       0e121895-d24d-482c-b293-c726bff32ca4  1a
< t:2022-12-12 01:50:02,820 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.1.8    3.19 MB    256          ?       b472d79c-a642-4db5-a7cd-56cfa3065bfd  1a
< t:2022-12-12 01:50:02,825 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.1.73   2.71 MB    256          ?       b782174f-9d85-4b32-a2e9-42b70c5c507f  1a
< t:2022-12-12 01:50:02,828 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.1.10   2.23 MB    256          ?       541ae60d-f27c-4d31-b415-7a5fdeac4520  1a
< t:2022-12-12 01:50:02,831 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.1.202  1.75 MB    256          ?       ef21e081-562d-4256-9503-3046b2ffbec1  1a
< t:2022-12-12 01:50:02,836 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.0.196  917 KB     256          ?       67659ed9-cf47-4e19-9797-76a9395cebd6  1a
< t:2022-12-12 01:50:02,839 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.3.69   5.32 MB    256          ?       97d68feb-f43a-4720-a1ab-4d7eaf85e4aa  1a
< t:2022-12-12 01:50:02,842 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.0.6    2.48 MB    256          ?       d8b2435f-524b-421c-ab6e-a51edd6381e0  1a
< t:2022-12-12 01:50:02,846 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.1.71   1.35 MB    256          ?       197bdfeb-befd-49cc-8e9d-1965c8956d5c  1a
< t:2022-12-12 01:50:02,851 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.1.64   1.2 MB     256          ?       f06c9673-35ed-46c5-bfc8-6e6c6bf9a9ad  1a
< t:2022-12-12 01:50:02,853 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.2.66   3.38 MB    256          ?       c4f8c907-85a9-47fd-855b-d0e373a6b791  1a
< t:2022-12-12 01:50:02,858 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.3.156  1.27 MB    256          ?       4b983bce-598d-4045-939d-9d7a2459a491  1a
< t:2022-12-12 01:50:02,862 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.3.152  2.79 MB    256          ?       eeb8334c-71e5-4d6f-bdf1-a08bb83ddb77  1a
< t:2022-12-12 01:50:02,866 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.0.25   1.06 MB    256          ?       6fef2354-9fc8-4d8f-8292-614b57263294  1a
< t:2022-12-12 01:50:02,876 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.0.148  3.69 MB    256          ?       6d618678-aea5-4ded-9478-bc4cdc47ce44  1a
< t:2022-12-12 01:50:02,880 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.1.21   2.33 MB    256          ?       968ea4e1-ed8a-4884-9d36-ce8ef59192c2  1a
< t:2022-12-12 01:50:02,883 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.3.150  5.89 MB    256          ?       f1bfb7c3-e6ac-41f0-8bf1-ec9e6b6155b6  1a
< t:2022-12-12 01:50:02,883 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.0.16   1.75 MB    256          ?       ce40017f-6aba-4f10-b992-b480a08bd7c1  1a
< t:2022-12-12 01:50:02,885 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.2.46   4.71 MB    256          ?       dda02812-ca11-4f02-852c-27bb96408b91  1a
< t:2022-12-12 01:50:02,887 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.3.174  6.25 MB    256          ?       5ba993ba-5073-4cfb-bbdd-dc7718c71c67  1a
< t:2022-12-12 01:50:02,890 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.0.105  4.99 MB    256          ?       23ee1696-5d68-4f37-bf3b-7dae719c8dcc  1a
< t:2022-12-12 01:50:02,890 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.1.106  1015 KB    256          ?       22b80117-621e-4300-b728-acea880ac3ed  1a
< t:2022-12-12 01:50:02,892 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.1.38   3.78 MB    256          ?       f9c62eca-02a1-4cf9-9970-0ee038295add  1a
< t:2022-12-12 01:50:02,894 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.1.167  1.42 MB    256          ?       9d804bd9-5742-4fda-8f18-cabf880525ba  1a
< t:2022-12-12 01:50:02,899 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.3.162  1.58 MB    256          ?       ee64b2f7-75af-4ce8-b6a4-3228fab965bf  1a
< t:2022-12-12 01:50:02,901 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.2.227  802 KB     256          ?       ef1f7dd8-861a-4506-9d6a-b20245320e9b  1a
< t:2022-12-12 01:50:02,907 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.2.120  1.84 MB    256          ?       c905edd0-9466-44e6-a95d-430ec53ff52a  1a
< t:2022-12-12 01:50:02,909 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.3.250  4 MB       256          ?       c5442495-eb3c-4c8f-b7b9-ad9519a72c96  1a
< t:2022-12-12 01:50:02,911 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.0.176  5.53 MB    256          ?       24ad3a82-f3af-4776-b184-728209bc1c54  1a
< t:2022-12-12 01:50:02,915 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.2.112  3.72 MB    256          ?       d0c7120c-3b30-4f82-a1bb-72ffab14d60a  1a
< t:2022-12-12 01:50:02,917 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.3.115  6.19 MB    256          ?       5df4f729-69a5-4978-b891-db236b523e25  1a
< t:2022-12-12 01:50:02,917 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2022-12-12 01:50:02,920 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
< t:2022-12-12 01:50:03,420 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  status " finished with status 0
< t:2022-12-12 01:50:03,420 f:cluster.py      l:2565 c:sdcm.cluster_aws     p:DEBUG > Node cluster-scale-test-master-db-node-500732b4-31 [44.200.126.73 | 10.12.3.174] (seed: False): Command '/usr/bin/node
tool  status ' duration -> 7.7547175159998005
```

The first message appeared at 2022-12-12 10:50:52
```
< t:2022-12-12 01:50:52,235 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-12-12T01:50:52+00:00 cluster-scale-test-master-db-node-500732b4-32  !WARNING | scylla[7655]:  [shard 0] seastar_
memory - oversized allocation: 1179648 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at 0x53708fe 0x5370eb0 0x5371198 0x4fa7986 0x4fa7cd4 0x4faa691 0x3685
657 0x36727aa 0x4fe5794 0x4fe69d7 0x4fe5d39 0x4f8c6b5 0x4f8b828 0x10eb614 0x10ed120 0x10e9d75 /opt/scylladb/libreloc/libc.so.6+0x2750f /opt/scylladb/libreloc/libc.so.6+0x275c8 0x10e7ee4
```

BACKTRACE:
```
[Backtrace #0]
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_3>(seastar::current_backtrace_tasklocal()::$_3&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:137
seastar::current_backtrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:170
seastar::memory::cpu_pages::warn_large_allocation(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:776
 (inlined by) seastar::memory::cpu_pages::check_large_allocation(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:784
 (inlined by) seastar::memory::cpu_pages::allocate_large(unsigned int) at ./build/release/seastar/./seastar/src/core/memory.cc:790
 (inlined by) seastar::memory::allocate_large(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1342
seastar::memory::allocate(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1403
operator new(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:2065
std::__new_allocator<nonwrapping_interval<dht::token> >::allocate(unsigned long, void const*) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/new_allocator.h:137
 (inlined by) std::allocator<nonwrapping_interval<dht::token> >::allocate(unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/allocator.h:188
 (inlined by) std::allocator_traits<std::allocator<nonwrapping_interval<dht::token> > >::allocate(std::allocator<nonwrapping_interval<dht::token> >&, unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/alloc_traits.h:464
 (inlined by) std::_Vector_base<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >::_M_allocate(unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_vector.h:378
 (inlined by) void std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >::_M_range_insert<__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > > >(__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, __gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, __gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, std::forward_iterator_tag) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/vector.tcc:787
 (inlined by) void std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >::_M_insert_dispatch<__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > > >(__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, __gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, __gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, std::__false_type) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_vector.h:1779
 (inlined by) __gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > > std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >::insert<__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, void>(__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token> const*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, __gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, __gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_vector.h:1481
 (inlined by) locator::abstract_replication_strategy::get_pending_address_ranges(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >, gms::inet_address, locator::endpoint_dc_rack) const at ./locator/abstract_replication_strategy.cc:299
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >::promise_type>::resume() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/coroutine:244
 (inlined by) seastar::internal::coroutine_traits_base<std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:78
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2486
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2923
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3092
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2975
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:265
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:156
scylla_main(int, char**) at ./main.cc:526
std::function<int (int, char**)>::operator()(int, char**) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:591
main at ./main.cc:1791
/data/scylla-s3-reloc.cache/by-build-id/a0d3f077099c66bf6c75707e386c6be3ba2c431f/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=db8b8949801cc5d89afa366440dcc44c9c9ca76a, for GNU/Linux 3.2.0, not stripped


__libc_start_call_main at ??:?
__libc_start_main_alias_2 at :?
_start at ??:?
```

The test itself started later at 02:25

```
< t:2022-12-12 02:25:34,906 f:grow_cluster_test.py l:92   c:GrowClusterTest      p:INFO  > Starting to grow cluster: 2022-12-12 02:25:34.906077
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 500732b4-ccfa-491f-b116-4a63c34b0200`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=500732b4-ccfa-491f-b116-4a63c34b0200)
- Show all stored logs command: `$ hydra investigate show-logs 500732b4-ccfa-491f-b116-4a63c34b0200`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/raft/job/scale-40-60-cluster-test-test/2/)

**Comment by roydahan** [comment] 2022-12-14 18:44
SCT log: https://cloudius-jenkins-test.s3.amazonaws.com/500732b4-ccfa-491f-b116-4a63c34b0200/20221212_112324/sct-500732b4.log.tar.gz

**Comment by bhalevy** [comment] 2022-12-15 13:42
Duplicate of #11005

**Closed** 2022-12-15 14:08 UTC
Labels: master/triage
