### ISSUE TITLE
[branch 5.2] Iterator invalidation in lsa_partition_reader::reset_state()

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#14696] opened 2023-07-14 06:26 UTC
do_refresh_state() keeps iterators to rows_entry in a vector.
This vector might be resized during the procedure, triggering memory reclaim and invalidating the iterators, which can cause arbitrarily long loops and/or a segmentation fault during make_heap().

**Comment by michoecho** [comment] 2023-07-14 06:26
Refs https://github.com/scylladb/scylla-enterprise/issues/3125

**Comment by bhalevy** [comment] 2023-07-23 06:26
@michoecho I understand that #14696 was merged to 5.2 
Can you please document what fixed this issue in later release?

@scylladb/scylla-maint should we close this issue and add the `Backport Candidate` label to facilitate backport to 5.1?

**Comment by michoecho** [comment] 2023-07-23 19:18
> Can you please document what fixed this issue in later release?

It was fixed by https://github.com/scylladb/scylladb/pull/12048, which rewrote the entire implementation of memtable readers (unifying it with `partition_snapshot_row_cursor`).

**Comment by denesb** [comment] 2023-07-24 06:54
Fixed in 41aef6dc96996016543fdc07d1febbaa8c2cabd7 (Gihub didn't auto-close the issue because the fix was targeted at 5.2).

**Closed by denesb** 2023-07-24 06:54 UTC
Labels: bug, Requires-Backport-to-5.2, Requires-Backport-to-5.1

**Comment by denesb** [comment] 2023-07-24 06:56
> @scylladb/scylla-maint should we close this issue and add the `Backport Candidate` label to facilitate backport to 5.1?

Should we only backport to 5.1? How about enterprise? @michoecho what are the user-visible symptoms and how hard it is to trigger?

**Comment by michoecho** [comment] 2023-07-24 07:22
> Should we only backport to 5.1? How about enterprise?

We should backport it to all supported versions, including enterprise.

> @michoecho what are the user-visible symptoms

Segmentation fault.

> how hard it is to trigger?

Very hard — it took us a few years to discover it.

But on the other hand, it was discovered when it happened in production, and it took down two nodes at once.

In other words, you have to be very unlikely to trigger it, but there are some workloads which make it likely enough.

**Comment by denesb** [comment] 2023-07-24 12:12
I see no test attached to the fix. I presume this is very hard to reproduce in a unit test. Was this patch tested manually, perhaps on the cluster this bug affected?

**Comment by michoecho** [comment] 2023-07-24 12:46
> I see no test attached to the fix. I presume this is very hard to reproduce in a unit test.

Yes, see https://github.com/scylladb/scylladb/pull/14697#issuecomment-1635872206.

In general it's impossible to test for invalidation bugs reliably. This is a systemic problem. It would require additional LSA machinery to fix. For example, we could force all accesses to LSA to go through handles (rather than raw pointers/references) which would check (at least in debug mode) that no invalidation happened. (The key is that tests should also check for *potential* invalidation — any instance of allocation with reclaiming enabled, even if the allocation didn't happened to trigger reclaim). 

> Was this patch tested manually, perhaps on the cluster this bug affected?

The only "testing" here was me fooling around trying to write the unit test for this. The patch relied on review rather than testing.

You can't test it on the affected cluster, because it's not reproducing the bug reliably. It happened once — on two nodes, but only once — and didn't happen again.

**Comment by denesb** [comment] 2023-07-24 12:59
Ok, let's let the fix see at least one OSS release, to make sure there are no adverse effects, then we can backport.

**Comment by denesb** [comment] 2023-08-09 06:08
Backported to 5.1.
