### ISSUE TITLE
seastar::logger::info stalls 115ms

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#11145] opened 2022-07-28 07:01 UTC
```
Test: performance_regression_test.PerformanceRegressionTest.test_latency_mixed_with_nemesis
Test start time: 2022-07-27 11:48:33.486992
Test id: 7d18efab-9db2-4351-9179-6e907f8aca7e
Scylla Server Version: 5.1.dev.20220724.f46b207472a3 with build-id d947aaccafa94647f71c1c79326eb88840c5b6d2
Setup Details:

    ami_id_db_scylla: ami-01315ab72a1b3951d
    append_scylla_args: --blocked-reactor-notify-ms 5
    cluster_backend: aws
    instance_type_db: i3.2xlarge
    instance_type_loader: c5.2xlarge
    instance_type_monitor: t3.large
    region_name: ['us-east-1']
```
```
Links:

    [Build URL](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/for_xemul/job/latency-with-nemesis-rbno-control/33/)
    [Download "Per server metrics nemesis" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-overview-20220727_163427-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [Download "Overview metrics" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_163633-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)

Logs:

    [prometheus - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_114217.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_114217.tar.gz)
    [prometheus - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_163359.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_163359.tar.gz)
    [prometheus - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_164808.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_164808.tar.gz)
    [prometheus - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_170317.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_170317.tar.gz)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_112917/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_113134-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_112917/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_113134-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_112917/grafana-screenshot-overview-20220727_112917-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_112917/grafana-screenshot-overview-20220727_112917-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_162022/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_162226-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_162022/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_162226-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_162022/grafana-screenshot-overview-20220727_162022-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_162022/grafana-screenshot-overview-20220727_162022-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_163633-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_163633-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-overview-20220727_163427-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-overview-20220727_163427-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_164920/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_165125-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_164920/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_165125-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_164920/grafana-screenshot-overview-20220727_164920-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_164920/grafana-screenshot-overview-20220727_164920-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/db-cluster-7d18efab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/db-cluster-7d18efab.tar.gz)
    [loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/loader-set-7d18efab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/loader-set-7d18efab.tar.gz)
    [monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/monitor-set-7d18efab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/monitor-set-7d18efab.tar.gz)
    [sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/sct-runner-7d18efab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/sct-runner-7d18efab.tar.gz)

```

```
2022-07-27T16:15:37+00:00  perf-latency-nemesis-perf-job-db-node-7d18efab-6 !INFO    | scylla[6551]: [shard 0] repair - decommission_with_repair: keyspace=system_distributed_everywhere, range=(5935038423055455301, 5942507453253964852], current_replica_endpoints={10.0.0.249, 10.0.3.162, 10.0.0.182, 10.0.0.52}, new_replica_endpoints={10.0.0.52, 10.0.0.249, 10.0.3.162}, neighbors={10.0.0.52}, mandatory_neighbor={}
2022-07-27T16:15:37+00:00  perf-latency-nemesis-perf-job-db-node-7d18efab-6 !INFO    | scylla[6551]: [shard 0] repair - decommission_with_repair: keyspace=system_distributed_everywhere, range=(5935038423055455301, 5942507453253964852], current_replica_endpoints={10.0.0.249, 10.0.3.162, 10.0.0.182, 10.0.0.52}, new_replica_endpoints={10.0.0.52, 10.0.0.249, 10.0.3.162}, neighbors={10.0.0.52}, mandatory_neighbor={}
2022-07-27T16:15:37+00:00  perf-latency-nemesis-perf-job-db-node-7d18efab-6 !INFO    | scylla[6551]: Reactor stalled for 115 ms on shard 0. Backtrace: 0x4bbb9d2 0x4bba630 0x4bbb8e0 0x7fd365262a1f 0x1a8b4bf 0xf59a 0x117c4 0x36d18ed 0x4f5b763 0x36cd5ac 0x36c89c3 0x4e3a0e1
2022-07-27T16:15:37+00:00  perf-latency-nemesis-perf-job-db-node-7d18efab-6 !INFO    | scylla[6551]: Reactor stalled for 115 ms on shard 0. Backtrace: 0x4bbb9d2 0x4bba630 0x4bbb8e0 0x7fd365262a1f 0x1a8b4bf 0xf59a 0x117c4 0x36d18ed 0x4f5b763 0x36cd5ac 0x36c89c3 0x4e3a0e1
```

Decoded:

```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:772
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:791
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1366
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1108
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1125
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1349
?? ??:0
seastar::logger::lambda_log_writer<seastar::logger::log<seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, nonwrapping_interval<dht::token>&>(seastar::log_level, seastar::logger::format_info, seastar::basic_sstring<char, unsigned int, 15u, true>&&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, nonwrapping_interval<dht::token>&)::{lambda(seastar::internal::log_buf::inserter_iterator)#1}>::operator()(seastar::internal::log_buf::inserter_iterator) at sstables.cc:?
?? ??:0
?? ??:0
std::enable_if<true, seastar::internal::log_buf::inserter_iterator>::type fmt::v7::vformat_to<seastar::internal::log_buf::inserter_iterator, fmt::v7::basic_string_view<char>, char, true>(seastar::internal::log_buf::inserter_iterator, fmt::v7::basic_string_view<char> const&, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<fmt::v7::type_identity<char>::type>, fmt::v7::type_identity<char>::type> >) at /usr/include/fmt/core.h:1984
 (inlined by) std::enable_if<true, seastar::internal::log_buf::inserter_iterator>::type fmt::v7::format_to<seastar::internal::log_buf::inserter_iterator, std::basic_string_view<char, std::char_traits<char> >, char const*&, seastar::basic_sstring<char, unsigned int, 15u, true>&, nonwrapping_interval<dht::token>&, utils::small_vector<gms::inet_address, 3ul> const&, utils::small_vector<gms::inet_address, 3ul> const&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&, true>(seastar::internal::log_buf::inserter_iterator, std::basic_string_view<char, std::char_traits<char> > const&, char const*&, seastar::basic_sstring<char, unsigned int, 15u, true>&, nonwrapping_interval<dht::token>&, utils::small_vector<gms::inet_address, 3ul> const&, utils::small_vector<gms::inet_address, 3ul> const&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&) at /usr/include/fmt/core.h:2005
 (inlined by) operator() at ././seastar/include/seastar/util/log.hh:223
 (inlined by) seastar::logger::lambda_log_writer<seastar::logger::log<char const*&, seastar::basic_sstring<char, unsigned int, 15u, true>&, nonwrapping_interval<dht::token>&, utils::small_vector<gms::inet_address, 3ul> const&, utils::small_vector<gms::inet_address, 3ul> const&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&>(seastar::log_level, seastar::logger::format_info, char const*&, seastar::basic_sstring<char, unsigned int, 15u, true>&, nonwrapping_interval<dht::token>&, utils::small_vector<gms::inet_address, 3ul> const&, utils::small_vector<gms::inet_address, 3ul> const&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&)::{lambda(seastar::internal::log_buf::inserter_iterator)#1}>::operator()(seastar::internal::log_buf::inserter_iterator) at ././seastar/include/seastar/util/log.hh:107
operator() at ./build/release/seastar/./seastar/src/util/log.cc:283
 (inlined by) seastar::logger::do_log(seastar::log_level, seastar::logger::log_writer&) at ./build/release/seastar/./seastar/src/util/log.cc:303
void seastar::logger::log<char const*&, seastar::basic_sstring<char, unsigned int, 15u, true>&, nonwrapping_interval<dht::token>&, utils::small_vector<gms::inet_address, 3ul> const&, utils::small_vector<gms::inet_address, 3ul> const&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&>(seastar::log_level, seastar::logger::format_info, char const*&, seastar::basic_sstring<char, unsigned int, 15u, true>&, nonwrapping_interval<dht::token>&, utils::small_vector<gms::inet_address, 3ul> const&, utils::small_vector<gms::inet_address, 3ul> const&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&) at ././seastar/include/seastar/util/log.hh:226
 (inlined by) void seastar::logger::info<char const*&, seastar::basic_sstring<char, unsigned int, 15u, true>&, nonwrapping_interval<dht::token>&, utils::small_vector<gms::inet_address, 3ul> const&, utils::small_vector<gms::inet_address, 3ul> const&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&>(seastar::logger::format_info, char const*&, seastar::basic_sstring<char, unsigned int, 15u, true>&, nonwrapping_interval<dht::token>&, utils::small_vector<gms::inet_address, 3ul> const&, utils::small_vector<gms::inet_address, 3ul> const&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&, std::vector<gms::inet_address, std::allocator<gms::inet_address> >&) at ././seastar/include/seastar/util/log.hh:345
 (inlined by) operator() at ./repair/repair.cc:1684
void std::__invoke_impl<void, repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30>(std::__invoke_other, repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::__invoke_result<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30>::type std::__invoke<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30>(repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
 (inlined by) decltype(auto) std::__apply_impl<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30, std::tuple<>>(repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&, std::tuple<>&&, std::integer_sequence<unsigned long>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1858
 (inlined by) decltype(auto) std::apply<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30, std::tuple<> >(repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&, std::tuple<>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1869
 (inlined by) seastar::future<void> seastar::futurize<void>::apply<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30>(repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:2113
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:258
 (inlined by) seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30>(seastar::thread_attributes, repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././seastar/include/seastar/util/noncopyable_function.hh:124
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:209
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:299

```

The content to log  is easy like below. I am not sure how the logger would stall 115ms.

```
2022-07-27T16:15:37+00:00  perf-latency-nemesis-perf-job-db-node-7d18efab-6 !INFO    | scylla[6551]: [shard 0] repair - decommission_with_repair: keyspace=system_distributed_everywhere, range=(5935038423055455301, 5942507453253964852], current_replica_endpoints={10.0.0.249, 10.0.3.162, 10.0.0.182, 10.0.0.52}, new_replica_endpoints={10.0.0.52, 10.0.0.249, 10.0.3.162}, neighbors={10.0.0.52}, mandatory_neighbor={}
2022-07-27T16:15:37+00:00  perf-latency-nemesis-perf-job-db-node-7d18efab-6 !INFO    | scylla[6551]: [shard 0] repair - decommission_with_repair: keyspace=system_distributed_everywhere, range=(5935038423055455301, 5942507453253964852], current_replica_endpoints={10.0.0.249, 10.0.3.162, 10.0.0.182, 10.0.0.52}, new_replica_endpoints={10.0.0.52, 10.0.0.249, 10.0.3.162}, neighbors={10.0.0.52}, mandatory_neighbor={}
```

Near the log there is a kernel callstack but it is empty. 

```
2022-07-27T16:15:37+00:00  perf-latency-nemesis-perf-job-db-node-7d18efab-6 !INFO    | scylla[6551]: Reactor stalled for 115 ms on shard 0. Backtrace: 0x4bbb9d2 0x4bba630 0x4bbb8e0 0x7fd365262a1f 0x1a8b4bf 0xf59a 0x117c4 0x36d18ed 0x4f5b763 0x36cd5ac 0x36c89c3 0x4e3a0e1
2022-07-27T16:15:37+00:00  perf-latency-nemesis-perf-job-db-node-7d18efab-6 !INFO    | scylla[6551]: Reactor stalled for 115 ms on shard 0. Backtrace: 0x4bbb9d2 0x4bba630 0x4bbb8e0 0x7fd365262a1f 0x1a8b4bf 0xf59a 0x117c4 0x36d18ed 0x4f5b763 0x36cd5ac 0x36c89c3 0x4e3a0e1
2022-07-27T16:15:37+00:00  perf-latency-nemesis-perf-job-db-node-7d18efab-6 !INFO    | scylla[6551]: kernel callstack:
2022-07-27T16:15:37+00:00  perf-latency-nemesis-perf-job-db-node-7d18efab-6 !INFO    | scylla[6551]: kernel callstack:
```

**Comment by bhalevy** [comment] 2022-07-29 15:57
@asias the fact the logging is included in the backtrace doesn't mean the stall comes from there in any way.
Note it's called from:
```
 (inlined by) operator() at ./repair/repair.cc:1684
```

which indicates it's likely to be a duplicate of #11146
there too, the stall is a result of the whole loop not yielding and the stall detector just samples it at different points in time.

**Comment by xemul** [comment] 2022-08-02 12:05
It can also spend some time in `syslog()`:
```
        // NOTE: syslog() can block, which will stall the reactor thread.
        //       this should be rare (will have to fill the pipe buffer
        //       before syslogd can clear it) but can happen.  If it does,
        //       we'll have to implement some internal buffering (which
        //       still means the problem can happen, just less frequently).
        // syslog() interprets % characters, so send msg as a parameter
```
but surely there's no proof that it really does

**Comment by avikivity** [comment] 2022-08-02 13:48
If it was in syslog we'd see it in the calltrace. It's probably the loop you indicated.

**Comment by asias** [comment] 2022-08-08 07:26
> @asias the fact the logging is included in the backtrace doesn't mean the stall comes from there in any way. Note it's called from:
> 
> ```
>  (inlined by) operator() at ./repair/repair.cc:1684
> ```
> 
> which indicates it's likely to be a duplicate of #11146 there too, the stall is a result of the whole loop not yielding and the stall detector just samples it at different points in time.

I agree the root cause of the stall is probably the loop not the log it self. We will see if this shows up again with the fix we already merged.

**Comment by fgelcer** [comment] 2022-08-08 08:24
@asias , is it safe to say that the stalled function, when reporting the issue, would be `(inlined by) operator() at ./repair/repair.cc:1684` ? or could you please update the issue with the correct function call, so when reporting a stall it will be more useful to know the right thing to search in logs...

**Comment by asias** [comment] 2022-08-08 08:36
The stall reported is correct. The stall sampling was indeed inside the function rlogger.info. I do not think we need special handling for the report of the stalls here.

**Comment by avikivity** [comment] 2022-08-08 12:09
Then it's likely a duplicate like @bhalevy says, no?

**Comment by asias** [comment] 2022-08-09 02:12
> Then it's likely a duplicate like @bhalevy says, no?

Yes. I mentioned it here: https://github.com/scylladb/scylladb/issues/11145#issuecomment-1207764008

**Comment by avikivity** [comment] 2022-08-09 10:10
Closing as probable duplicate of #11145.

**Closed by avikivity** 2022-08-09 10:10 UTC
