### ISSUE TITLE
"Cannot achieve consistency level for cl LOCAL_ONE. Requires 1, alive 0" while one node out of two-node cluster is down

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#16875] opened 2024-01-19 12:39 UTC
Test (comes from scylladb/scylla-dtest#3877)

1. start node-1 with `tablets` and `consistent-topology-changes` features ON
2. create keyspace with NetworkTopologyStrategy and rf=2
3. create table
4. insert a row into table
5. start node-2 with `tablets` and `consistent-topology-changes` features ON
6. stop node-1
7. select from ks.cf from node-2 and get

```
cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.0.2:9042 datacenter1>: Unavailable('Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl LOCAL_ONE. Requires 1, alive 0" info={\'consistency\': \'LOCAL_ONE\', \'required_replicas\': 1, \'alive_replicas\': 0}')})
```

script to select

```python
 import cassandra
 from cassandra.cluster import Cluster
 c = Cluster(['127.0.0.2'])
 s = c.connect()
 res = s.execute('select * from ks.cf')
```

If bringing node-1 back, select succeeds
If _not_ using only `tablets` feature, select succeeds (so it's not consisten-topology-changes)

**Comment by xemul** [comment] 2024-01-19 12:42
```
$ ./cqlsh 127.0.0.2 -e "select * from system.tablets;"

 keyspace_name | table_id                             | last_token          | table_name | tablet_count | new_replicas | replicas                                    | session | stage
---------------+--------------------------------------+---------------------+------------+--------------+--------------+---------------------------------------------+---------+-------
            ks | a1b02700-b6c6-11ee-8192-b43bc698d568 | 9223372036854775807 |         cf |            1 |         null | [(da00846b-b45e-4f95-a706-c61ef9dfffde, 0)] |    null |  null

(1 rows)

```

**Comment by xemul** [comment] 2024-01-19 12:43
The `da00846b-b45e-4f95-a706-c61ef9dfffde` is node-1

```
$ ./cqlsh 127.0.0.2 -e "select rpc_address, host_id from system.local;"

 rpc_address | host_id
-------------+--------------------------------------
   127.0.0.2 | c1a9aebe-afb8-49a6-9854-c5946754272a

(1 rows)
$ ./cqlsh 127.0.0.2 -e "select rpc_address, host_id from system.peers;"

 rpc_address | host_id
-------------+--------------------------------------
   127.0.0.1 | da00846b-b45e-4f95-a706-c61ef9dfffde

(1 rows)
```

**Comment by xemul** [comment] 2024-01-19 12:45
Load balancer says (when both nodes are up)

```
INFO  2024-01-19 15:43:48,068 [shard 0:strm] load_balancer - Examining DC datacenter1
INFO  2024-01-19 15:43:48,068 [shard 0:strm] load_balancer - Node c1a9aebe-afb8-49a6-9854-c5946754272a: rack=rack1 avg_load=0, tablets=0, shards=2, state=normal
INFO  2024-01-19 15:43:48,068 [shard 0:strm] load_balancer - Node da00846b-b45e-4f95-a706-c61ef9dfffde: rack=rack1 avg_load=0.5, tablets=1, shards=2, state=normal
INFO  2024-01-19 15:43:48,068 [shard 0:strm] load_balancer - target node: c1a9aebe-afb8-49a6-9854-c5946754272a, avg_load: 0, max: 0.5
INFO  2024-01-19 15:43:48,068 [shard 0:strm] load_balancer - Not possible to achieve balance.
INFO  2024-01-19 15:43:48,068 [shard 0:strm] load_balancer - Prepared 0 migrations in DC datacenter1
INFO  2024-01-19 15:43:48,068 [shard 0:strm] load_balancer - Prepared 0 migrations
```

**Comment by xemul** [comment] 2024-01-19 12:46
@tgrabiec , please comment on the above -- is this scenario stupid and not supposed to work with tablets, or is it an issue to fix?

**Comment by xemul** [comment] 2024-01-19 12:47
```
$ ./cqlsh 127.0.0.1 -e "select * from system_schema.keyspaces where keyspace_name='ks';"

 keyspace_name | durable_writes | replication
---------------+----------------+---------------------------------------------------------------------------------------
            ks |           True | {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'datacenter1': '2'}
```

**Comment by tgrabiec** [comment] 2024-01-19 13:50
The reason is that table is created while there is only 1 node in the cluster, so only node-1 is the replica. Duplicate of https://github.com/scylladb/scylladb/issues/16529.

**Closed by tgrabiec** 2024-01-19 13:50 UTC
Labels: tablets

**Comment by xemul** [comment] 2024-03-11 18:06
@yarongilor , your test differs -- you crate keyspace with rf=1, then kill one of the nodes thus creating deliberate data loss

**Comment by xemul** [comment] 2024-03-11 18:07
Here:

```
    for ks in keyspaces:
        create_ks(session, ks, {dc: 1})
```
