### ISSUE TITLE
Regression in test_static_columns_cas

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#10838] opened 2022-06-20 09:02 UTC
First seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/35/testReport/cql_additional_tests/TestCQL/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_static_columns_cas/
```
AssertionError: Expected [[True, 1, 'foo', None, 'foo']] from INSERT INTO test(id, version) VALUES (1, 1) IF NOT EXISTS, but got [[True, 1, None, None, None]]
```

git bisect pointed at the regression since 670b2562a1699418461718057ad43d46b0e3ded7

Cc @kostja

**Comment by kostja** [comment] 2022-06-20 13:00
cql_addtitional_tests.py

**Comment by bhalevy** [comment] 2022-06-20 13:03
yes.  it's cql_additional_tests.py::TestCQL::test_static_columns_cas

**Comment by bhalevy** [comment] 2022-07-07 11:32
I see also a regression since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/49/testReport/junit/cql_additional_tests/TestLWTWithCQL/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split005___test_conditional_updates_on_static_columns_with_null_values_batch/
```
AssertionError: Expected [[True, 2, 2, None], [True, 2, 2, None]] from 
            BEGIN BATCH
                INSERT INTO lwt_on_static_columns_with_null_batch (a, b, d) values (2, 2, 'a');
                UPDATE lwt_on_static_columns_with_null_batch SET s = 2 WHERE a = 2 IF s = null;
            APPLY BATCH, but got [[True, 2, 2, None], [True, 2, None, None]]
```

Please look into it and see if it's the same root cause as in test_static_columns_cas.
If not, let's open a new issue for it.

**Comment by slivne** [comment] 2022-07-17 07:26
@kostja / @gusev-p ping

**Comment by slivne** [comment] 2022-07-31 11:53
@fruch whats the status of dtest next - why isn't this getting merged

**Comment by fruch** [comment] 2022-07-31 12:00
it's already in master, it was by accident pushed straight to master. so it's missed the next process to get this mark as closed

the test stopped failing in 
https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/63/testReport/junit/cql_additional_tests/TestCQL/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_static_columns_cas/

closing

**Comment by bhalevy** [comment] 2022-08-01 10:10
> I see also a regression since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/49/testReport/junit/cql_additional_tests/TestLWTWithCQL/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split005___test_conditional_updates_on_static_columns_with_null_values_batch/
> 
> ```
> AssertionError: Expected [[True, 2, 2, None], [True, 2, 2, None]] from 
>             BEGIN BATCH
>                 INSERT INTO lwt_on_static_columns_with_null_batch (a, b, d) values (2, 2, 'a');
>                 UPDATE lwt_on_static_columns_with_null_batch SET s = 2 WHERE a = 2 IF s = null;
>             APPLY BATCH, but got [[True, 2, 2, None], [True, 2, None, None]]
> ```
> 
> Please look into it and see if it's the same root cause as in test_static_columns_cas. If not, let's open a new issue for it.

@gusev-p 
This test still fails.
Most recently: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/68/testReport/cql_additional_tests/TestLWTWithCQL/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split004___test_conditional_updates_on_static_columns_with_null_values_batch/

**Comment by bhalevy** [comment] 2022-08-01 11:03
@fruch not sure reopening this issue is warranted.
It's possible that the issue in `test_conditional_updates_on_static_columns_with_null_values_batch` is different and a new should be opened for it (could also be only an issue with the dtest) as was in #7176

**Comment by fruch** [comment] 2022-08-01 11:06
> @fruch not sure reopening this issue is warranted. It's possible that the issue in `test_conditional_updates_on_static_columns_with_null_values_batch` is different and a new should be opened for it (could also be only an issue with the dtest) as was in #7176

it started the exact same day 670b2562a1699418461718057ad43d46b0e3ded7 was merged, yes the test should align.
but seems like it's the same root cause as the failure of `test_static_columns_cas`

**Comment by slivne** [comment] 2022-08-01 11:13
@gusev-p / @kostja ping

**Comment by kostja** [comment] 2022-08-03 08:52
https://github.com/scylladb/scylla-dtest/pull/2800

**Closed** 2022-08-03 09:26 UTC
Labels: test, Regression, lwt, dtest, master/high

**Comment by nyh** [comment] 2022-09-06 16:08
I just saw this failure also in testing branch-5.0: https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2090/testReport/junit/cql_additional_tests/TestCQL/Sanity_Tests___test_static_columns_cas/

Maybe it needs backporting?

**Comment by avelanarius** [comment] 2022-11-09 14:12
Also saw this issue when backporting a commit to branch-5.0: https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2896/testReport/cql_additional_tests/TestCQL/Sanity_Tests___test_static_columns_cas/

**Comment by fruch** [comment] 2022-11-09 14:21
> I just saw this failure also in testing branch-5.0: https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2090/testReport/junit/cql_additional_tests/TestCQL/Sanity_Tests___test_static_columns_cas/
> 
> Maybe it needs backporting?

I think it's the other way around, the test changes seem to have got into branch-5.0...
I'll revert them.

**Comment by fruch** [comment] 2022-11-09 14:26
> > I just saw this failure also in testing branch-5.0: https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2090/testReport/junit/cql_additional_tests/TestCQL/Sanity_Tests___test_static_columns_cas/
> > Maybe it needs backporting?
> 
> I think it's the other way around, the test changes seem to have got into branch-5.0... I'll revert them.

Seems my assumption was wrong, seems like the failures your are getting aren't related to this specific issue. even that it seems similar, the changes and the cause of the issue are not in branch-5.0.
