### ISSUE TITLE
test_cluster_reduction_with_cdc fails with WriteTimeout expecting 3 resoposes

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#15293] opened 2023-09-05 20:55 UTC
test_cluster_reduction_with_cdc started failing last too runs of next
with WriteTimeout expecting 3 resoposes, while at this stage we decommissioned one node already, or during the decommissioning
this is with consistent schema enabled
 
```
self = <cdc_test.TestCdc object at 0x7fcda36dc150>
request = <FixtureRequest for <Function test_cluster_reduction_with_cdc[Single_cluster]>>
cluster_config = ClusterConfig(size=[3], replication="{'class': 'NetworkTopologyStrategy', 'replication_factor': 3}")

    @pytest.mark.next_gating
    @pytest.mark.no_boot_speedups
    # Test had history of timing out in debug, see: https://github.com/scylladb/scylla-dtest/issues/3275
    @pytest.mark.scylla_mode('!debug')
    def test_cluster_reduction_with_cdc(self, request, cluster_config):
>       self.cluster_reduction_with_cdc_template(request=request, cluster_size=cluster_config.size,
                                                 replication=cluster_config.replication, with_preimage=False)

cdc_test.py:352: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cdc_test.py:336: in cluster_reduction_with_cdc_template
    write_count = finish_writing()
cdc_test.py:628: in finisher
    (confirmed, unconfirmed) = fut.result()
/usr/lib64/python3.11/concurrent/futures/_base.py:449: in result
    return self.__get_result()
/usr/lib64/python3.11/concurrent/futures/_base.py:401: in __get_result
    raise self._exception
/usr/lib64/python3.11/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
cdc_test.py:605: in run_writes
    session.execute(stmt, (i, str(worker_id)))
cassandra/cluster.py:2700: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.WriteTimeout: Error from server: code=1100 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for ks.cf - received only 2 responses from 3 CL=QUORUM." info={'consistency': 'QUORUM', 'required_responses': 3, 'received_responses': 2, 'write_type': 'UNLOGGED_BATCH'}

cassandra/cluster.py:5019: WriteTimeout
```

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4273/testReport/junit/cdc_test/TestCdc/FullDtest___full_split010___test_cluster_reduction_with_cdc_Single_cluster_/

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4274/testReport/cdc_test/TestCdc/FullDtest___full_split010___test_cluster_reduction_with_cdc_Single_cluster_/

### Logs
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4273/artifact/logs-full.release.010/1693933819617_cdc_test.py%3A%3ATestCdc%3A%3Atest_cluster_reduction_with_cdc%5BSingle_cluster%5D/

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4274/artifact/logs-full.release.010/1693935257205_cdc_test.py%3A%3ATestCdc%3A%3Atest_cluster_reduction_with_cdc%5BSingle_cluster%5D/

**Comment by kbr-scylla** [comment] 2023-10-16 14:41
Closing since it's most likely a duplicate of https://github.com/scylladb/scylladb/issues/15454 (caused by the infra problem.)

**Closed by kbr-scylla** 2023-10-16 14:41 UTC
Labels: dtest, CDC, CI-Stability
