### ISSUE TITLE
nodetool cleanup doesn't finish running on cluster with large collections

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylladb#9917] opened 2022-01-14 23:55 UTC
_Installation details_ 
Kernel version: `5.4.162-86.275.amzn2.x86_64` 
Scylla version (or git commit hash): `4.5.3-0.20211223.c8f14886d with build-id 9a5b504c51cbe8feb1217517d6977f7793b2971e` 
Cluster size: 4 nodes (i3en.3xlarge) 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker image - `scylladb/scylla:4.5.3` (`sha256:b89abe41ed96dac16dc2c9ac624d947e0f24dd7300d5de095d0cbeb847a8b437`)

Scylla running with shards number (live nodes): 
sct-cluster-us-east1-b-us-east1-0 (10.0.0.164 | 172.20.171.121): 11 shards 
sct-cluster-us-east1-b-us-east1-1 (10.0.2.226 | 172.20.216.144): 11 shards 
sct-cluster-us-east1-b-us-east1-2 (10.0.1.255 | 172.20.227.31): 11 shards 
sct-cluster-us-east1-b-us-east1-3 (10.0.3.26 | 172.20.62.144): 11 shards 

Test: `longevity-scylla-operator-large-collections-12h` 
Test name: `longevity_test.LongevityTest.test_custom_time` Test config file(s):
* [longevity-large-collections-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f8ab3f33014ca1a7d0c0858e025859e93f4866f9/test-cases/longevity/longevity-large-collections-12h.yaml)
* [data_dir/large_collections.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f8ab3f33014ca1a7d0c0858e025859e93f4866f9/data_dir/large_collections.yaml)

**Issue description** 
In this test run we run `large-collections` type of a load, config for it is referenced above.
On each node we have disks 7500Gb in size.
Nemesis called `nodetool_cleanup` loops over each node serially and runs "nodetool cleanup" command for each test keyspace.
In our case there are 2 of them - `large_collection_test` and `ks_truncate_large_partition`.
The latter one goes fast as expected.
But the former one has problems.
Cleanup command time spendings on nodes:
- First node, about 77 minutes
- Second node, about 72 minutes
- Third node, about 95 minutes
- Forth node, didn't end

The picture about forth node:
From the loader point of view:
```
2022-01-13 23:35:09,444 f:remote_base.py  l:520  c:KubernetesCmdRunner  p:DEBUG > Running command "/usr/bin/nodetool  cleanup large_collection_test"...
...
2022-01-14 03:35:17,659 f:remote_base.py  l:520  c:KubernetesCmdRunner  p:DEBUG > Running command "/usr/bin/nodetool  cleanup large_collection_test"...
...
2022-01-14 03:35:12,071 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > update1,     1109960,      18,       0,       0,    59.5,    53.3,    95.1,   100.1,   100.1,   100.1,35225.0,  0.00103,      0,      0,       0       ,       0,       0,       0
...
2022-01-14 03:35:11,519 ... > Saw 1 exceptions within threads (WebSocketConnectionClosedException):
2022-01-14 03:35:11,519 ... >                         'WARN  23:35:11,493 Only 21.707GiB free across all '
2022-01-14 03:35:11,519 ... >                         'data volumes. Consider adding more capacity to your '
2022-01-14 03:35:11,519 ... >                         'cluster or removing obsolete snapshots\n',
2022-01-14 03:35:11,519 ... > websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
...
2022-01-14 03:35:17,659 ... > Running command "/usr/bin/nodetool  cleanup large_collection_test"...         
2022-01-14 03:35:18,020 ... > insert,      3335788,      84,      84,      84,    65.0,    52.4,   141.4,   162.0,   188.5,   188.5,35231.0,  0.00103,      0,      0,       0       ,       0,       0,       0   
2022-01-14 03:35:19,070 ... > total,       5555863,     130,     125,     125,    78.4,    77.1,   120.8,   178.9,   180.9,   180.9,35232.0,  0.00103,      0,      0,       0       ,       0,       0,       0   
2022-01-14 03:35:19,943 ... > WARN  03:35:19,932 Only 21.687GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
2022-01-14 03:35:20,020 ... > insert,      3335979,      84,      84,      84,    73.8,    60.7,   130.7,   149.8,   165.8,   165.8,35233.0,  0.00103,      0,      0,       0       ,       0,       0,       0   
2022-01-14 05:48:07,469 ... > total,       6659825,     168,     136,     136,    63.2,    57.6,   120.6,   151.7,   183.0,   183.0,43200.4,  0.00179,      0,      0,       0       ,       0,       0,       0
2022-01-14 05:48:07,511 ... > Results:                                                                 
2022-01-14 05:48:07,511 ... > Op rate                   :      154 op/s  [insert: 93 op/s, read1: 31 op/s, update1: 31 op/s]
2022-01-14 05:48:07,549 ... > Partition rate            :      119 pk/s  [insert: 93 pk/s, read1: 26 pk/s, update1: 0 pk/s]
2022-01-14 05:48:07,549 ... > Row rate                  :      119 row/s [insert: 93 row/s, read1: 26 row/s, update1: 0 row/s]
2022-01-14 05:48:07,573 ... > Latency mean              :   64.8 ms [insert: 65.5 ms, read1: 62.0 ms, update1: 65.8 ms] 
2022-01-14 05:48:07,573 ... > Latency median            :   59.3 ms [insert: 59.9 ms, read1: 56.3 ms, update1: 60.1 ms] 
2022-01-14 05:48:07,594 ... > Latency 95th percentile   :  119.5 ms [insert: 117.6 ms, read1: 129.8 ms, update1: 118.0 ms] 
2022-01-14 05:48:07,637 ... > Latency 99th percentile   :  154.4 ms [insert: 146.8 ms, read1: 181.8 ms, update1: 147.2 ms] 
2022-01-14 05:48:07,660 ... > Latency 99.9th percentile :  213.1 ms [insert: 188.1 ms, read1: 266.7 ms, update1: 189.3 ms] 
2022-01-14 05:48:07,660 ... > Latency max               : 4399.8 ms [insert: 845.7 ms, read1: 4,399.8 ms, update1: 608.2 ms] 
2022-01-14 05:48:07,682 ... > Total partitions          :  5,126,906 [insert: 3,998,395, read1: 1,128,511, update1: 0]
2022-01-14 05:48:07,807 ... > Total errors              :          0 [insert: 0, read1: 0, update1: 0]
2022-01-14 05:48:07,807 ... > Total GC count            : 0                                            
2022-01-14 05:48:09,675 ... > Total GC memory           : 0.000 KiB                                    
2022-01-14 05:48:09,697 ... > Total GC time             :    0.0 seconds                               
2022-01-14 05:48:09,720 ... > Avg GC time               :    NaN ms                                    
2022-01-14 05:48:09,742 ... > StdDev GC time            :    0.0 ms                                    
2022-01-14 05:48:09,763 ... > Total operation time      : 12:00:00                                     
2022-01-14 05:48:09,787 ... >                                                                          
2022-01-14 05:48:09,787 ... > END                                                                      
2022-01-14 05:48:09,847 ... > STDERR: Failed to connect over JMX; not collecting these stats           
2022-01-14 05:48:09,847 ... > Failed to connect over JMX; not collecting these stats                   
2022-01-14 05:48:09,847 ... > Failed to connect over JMX; not collecting these stats                   
2022-01-14 05:48:09,847 ... > Failed to connect over JMX; not collecting these stats                   
2022-01-14 05:48:09,847 ... > com.datastax.driver.core.exceptions.TransportException:
<long java stacktrace>
```
From the loader point of view we see that it tried to finish command 2 times. 
First time it was 4 hours and connection drop.
Second time it was 2 hours and almost 13 minutes.

From the DB node point view that failed (last one in the loop -> node-3):
```
WARN  2022-01-13 23:35:11,693 [shard 9] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
INFO  2022-01-13 23:35:11,698 [shard 7] compaction - [Cleanup large_collection_test.table_with_large_collection 73849500-74c9-11ec-af0c-fb1a18e0a1df] Cleaning [/var/lib/scylla/data/large_collection_test/table_with_large_collection       -bc42a250749711ec8a389cc4b9179865/md-3032-big-Data.db:level=0:origin=memtable, ]
...
<lots of cleanup messages>
<thousands of unpaged queries warning messages>
WARN  2022-01-14 05:48:09,902 [shard 0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
INFO  2022-01-14 05:48:21,093 [shard 8] compaction - [Cleanup large_collection_test.table_with_large_collection 724baec0-74e8-11ec-aaf0-fb1b18e0a1df] Cleaned 1 sstables to [/var/lib/scylla/data/large_collection_test/table_with_large_collection-bc42a250749711ec8a389cc4b9179865/md-4507-big-Data.db:level=0, ]. 43GB to 43GB (~99% of original) in 9077023ms = 4MB/s. ~30592 total partitions merged to 30468.
...
```
So, here we can see that cleanup was going all that time and it lasted more than the test run, so, the end was not observed.

Note:
- there are warning about lack of free space. And it is having disks with 7500Gb!
- monitoring shows that there is node load about 30%
- monitoring shows that the problematic nodes goes mad having lots of sstables reads - up to 41. Whereas other nodes mostly had about 10.
- monitoring shows that memory usage is much higher on the problematic node.

And one more problem that may be related and appears having large collections:
Following messages appear in 3 minutes after the start of the load with large collections and end right after loader stops:
```
WARN  2022-01-13 17:48:15,497 [shard 7] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
…
<+706040 such messages>
...
WARN  2022-01-14 05:48:09,902 [shard 0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
```
Numbers:
- There are 706042 such messages in 12 hours (similar for other nodes).
- It is about ~16 per second
- Total lines in the log: 710658
- All other lines in the log: 4616
- % of useful messages: 0.0065
- Size of the db log: 128.8Mb
- Size of the useful db log part: 0.8Mb

Restore Monitor Stack command: `$ hydra investigate show-monitor bdf64109-f68f-4d69-90af-7b49ca9fd5cc` 
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=bdf64109-f68f-4d69-90af-7b49ca9fd5cc) 
Show all stored logs command: `$ hydra investigate show-logs bdf64109-f68f-4d69-90af-7b49ca9fd5cc`

Test id: `bdf64109-f68f-4d69-90af-7b49ca9fd5cc`

Logs: 
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/bdf64109-f68f-4d69-90af-7b49ca9fd5cc/20220114_062716/db-cluster-bdf64109.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/bdf64109-f68f-4d69-90af-7b49ca9fd5cc/20220114_062716/loader-set-bdf64109.tar.gz
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/bdf64109-f68f-4d69-90af-7b49ca9fd5cc/20220114_062716/monitor-set-bdf64109.tar.gz
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/bdf64109-f68f-4d69-90af-7b49ca9fd5cc/20220114_062716/sct-runner-bdf64109.tar.gz

[Jenkins job URL](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/longevity-scylla-operator-large-collections-12h/12)

**Comment by vponomaryov** [comment] 2022-01-14 23:59
@aleksbykov had the same problem on the common Scylla installation (non-k8s). So, I guess, he may add some info too from his run.

**Comment by fruch** [comment] 2023-01-12 09:14
@soyacz would update with the details from current run that we see the issue.

**Comment by DoronArazii** [comment] 2023-01-12 11:00
@bhalevy I think it's your team's area, can you please have a look & determine the priority

**Comment by soyacz** [comment] 2023-01-12 12:17
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

The most recent case of this issue happened in operator 1.8 tests.
nodetool cleanup takes >3h for each node for test keyspace with large collections. 
Also db logs show 700k lines like (example from sct-cluster-us-east1-b-us-east1-1):
`WARN  2023-01-12 01:07:20,513 [shard 3] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)`

Nodetool status shows more than 1.15TB data per node.
## Impact

nodetool cleanup takes a lot of time.

## How frequently does it reproduce?

When using large collections

## Installation details

Kernel Version: 5.4.226-129.415.amzn2.x86_64
Scylla version (or git commit hash): `2022.1.3-20220922.539a55e35` with build-id `d1fb2faafd95058a04aad30b675ff7d2b930278d`
Relocatable Package: http://downloads.scylladb.com/unstable/scylla-enterprise/enterprise-2022.1/relocatable/2022-09-22T13:36:03Z/scylla-enterprise-x86_64-package.tar.gz
Operator Image: scylladb/scylla-operator:1.8.0-rc.0
Operator Helm Version: 1.8.0-rc.0
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 5 nodes (i3en.3xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: eu-north-1)

Test: `longevity-scylla-operator-large-collections-12h`
Test id: `e351dc9e-d991-4c66-ae64-d0493a871f27`
Test name: `scylla-operator/operator-1.8/eks/longevity-scylla-operator-large-collections-12h`
Test config file(s):

- [longevity-large-collections-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/e95ce5d965c5c6ca623886dd5b58d8f66e9107a0/test-cases/longevity/longevity-large-collections-12h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor e351dc9e-d991-4c66-ae64-d0493a871f27`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e351dc9e-d991-4c66-ae64-d0493a871f27)
- Show all stored logs command: `$ hydra investigate show-logs e351dc9e-d991-4c66-ae64-d0493a871f27`


## Logs:
- **db-cluster-e351dc9e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e351dc9e-d991-4c66-ae64-d0493a871f27/20230112_021910/db-cluster-e351dc9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e351dc9e-d991-4c66-ae64-d0493a871f27/20230112_021910/db-cluster-e351dc9e.tar.gz)
- **sct-runner-e351dc9e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e351dc9e-d991-4c66-ae64-d0493a871f27/20230112_021910/sct-runner-e351dc9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e351dc9e-d991-4c66-ae64-d0493a871f27/20230112_021910/sct-runner-e351dc9e.tar.gz)
- **monitor-set-e351dc9e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e351dc9e-d991-4c66-ae64-d0493a871f27/20230112_021910/monitor-set-e351dc9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e351dc9e-d991-4c66-ae64-d0493a871f27/20230112_021910/monitor-set-e351dc9e.tar.gz)
- **loader-set-e351dc9e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e351dc9e-d991-4c66-ae64-d0493a871f27/20230112_021910/loader-set-e351dc9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e351dc9e-d991-4c66-ae64-d0493a871f27/20230112_021910/loader-set-e351dc9e.tar.gz)
- **kubernetes-e351dc9e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e351dc9e-d991-4c66-ae64-d0493a871f27/20230112_021910/kubernetes-e351dc9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e351dc9e-d991-4c66-ae64-d0493a871f27/20230112_021910/kubernetes-e351dc9e.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.8/job/eks/job/longevity-scylla-operator-large-collections-12h/8/)
</details>

**Comment by bhalevy** [comment] 2023-01-12 12:52
The unpaged query warmings have nothing to do with cleanup. @tgrabiec I guess this has to do with the large collections.  Can increasing `max_memory_for_unlimited_query_soft_limit` at least get rid of the warning? Should/could anything else need to change on the test/client side?

@raphaelsc please look into the cleanup aspects amd see if large collection causes cleanup to slow down significantly (I don't see why...)

**Comment by DoronArazii** [comment] 2023-02-02 08:47
Removing "OSS Release/Triage" as it's in the ToDo list of Benny's team.

**Comment by raphaelsc** [comment] 2023-02-02 12:58
> ## Issue description
> * [ ]  This issue is a regression.
> * [ ]  It is unknown if this issue is a regression.
> 
> The most recent case of this issue happened in operator 1.8 tests. nodetool cleanup takes >3h for each node for test keyspace with large collections. Also db logs show 700k lines like (example from sct-cluster-us-east1-b-us-east1-1): `WARN 2023-01-12 01:07:20,513 [shard 3] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)`
> 
> Nodetool status shows more than 1.15TB data per node.
> 
> ## Impact
> nodetool cleanup takes a lot of time.

This is very raw, making it very very hard for me to investigate it.

When you say that cleanup takes a lot of time, please share io_properties.yaml, then the used disk space used by all keyspaces. Also, when you say it's taking a lot of time, it implies that it was faster before. How much faster? When it was faster? Is it a regression? Without this data, I am left with guessing work.

Large collection by itself may cause stalls, affecting latency, not throughput. What are the size of collections? Do you have the output of system large cells table? 

/CC @bhalevy FYI

**Comment by vponomaryov** [comment] 2023-02-02 16:08
@raphaelsc 

`io_properties.yaml` file and other scylla files are available in the provided above K8S logs archive.
It lays in the following dirs:
- `namespaces/scylla/pods/sct-cluster-us-east1-b-us-east1-0/scylla/io_properties.yaml`
- `namespaces/scylla/pods/sct-cluster-us-east1-b-us-east1-1/scylla/io_properties.yaml`
- `namespaces/scylla/pods/sct-cluster-us-east1-b-us-east1-2/scylla/io_properties.yaml`
- `namespaces/scylla/pods/sct-cluster-us-east1-b-us-east1-3/scylla/io_properties.yaml`

Here are the data from these files:

```
disks:
  - mountpoint: /var/lib/scylla
    read_iops: 272931
    read_bandwidth: 2211962880
    write_iops: 135315
    write_bandwidth: 819716480
```

```
disks:
  - mountpoint: /var/lib/scylla
    read_iops: 272843
    read_bandwidth: 2236467200
    write_iops: 222013
    write_bandwidth: 1020539456
```

```
disks:
  - mountpoint: /var/lib/scylla
    read_iops: 272886
    read_bandwidth: 2236102144
    write_iops: 222144
    write_bandwidth: 1020275072
```

```
disks:
  - mountpoint: /var/lib/scylla
    read_iops: 246916
    read_bandwidth: 2248748288
    write_iops: 219789
    write_bandwidth: 1023791168
```
``

**Comment by soyacz** [comment] 2023-02-02 16:49
> @soyacz When you say that cleanup takes a lot of time, please share io_properties.yaml, then the used disk space used by all keyspaces. Also, when you say it's taking a lot of time, it may imply that it was faster before. How much faster? When it was faster? Is it a regression? Without this data, I am left with guessing work.

@raphaelsc I tried to post all the info I know - and for me it's also not easy to get these info after nodes are down.
Also often I don't know what info is relevant - so thanks for pointing directions which things to collect. We can plan adding some automatic info collection in the moment we find an error.

**Comment by bhalevy** [comment] 2023-02-03 05:21
> write_iops: 135315
>     write_bandwidth: 819716480

Not that it should explain significant slowdown of cleanup by itself, but this node's write performance is significantly worse than the other nodes'.

**Comment by tgrabiec** [comment] 2023-02-07 10:56
The message:

```
Memory usage of unpaged query exceeds soft limit ...
```

... does not come from cleanup, which is not exercising this path. It comes from queries to the database, probably CQL.

Is there a workload running concurrently with cleanup?

**Comment by soyacz** [comment] 2023-02-07 11:20
> The message:
> 
> ```
> Memory usage of unpaged query exceeds soft limit ...
> ```
> 
> ... does not come from cleanup, which is not exercising this path. It comes from queries to the database, probably CQL.
> 
> Is there a workload running concurrently with cleanup?

yes, workload as usual

**Comment by DoronArazii** [comment] 2023-02-28 10:51
@bhalevy is it feasible for 5.2? or should I push it to the next version?

**Comment by DoronArazii** [comment] 2023-03-09 11:37
@bhalevy ping

**Comment by bhalevy** [comment] 2023-03-09 12:31
> @bhalevy is it feasible for 5.2? or should I push it to the next version?

We don't have a clear understanding of the root cause yes so no, it's not feasible for 5.2.

**Comment by DoronArazii** [comment] 2023-06-06 13:20
@vponomaryov since it's old, can you please try to reproduce on the latest

**Comment by bhalevy** [comment] 2023-06-06 16:46
what's the schema in this issue?
Is compaction bottlenecked on deserializing and reserializing collections?

**Comment by raphaelsc** [comment] 2023-06-06 16:55
> @raphaelsc didn't we see an issue with compacting large collections on the field recently? We don't have a solution for that yet.

we did, but the side effect is slowness. from the description, it seems cleanup went just fine on most of the nodes, but in one node cleanup didn't finish. this reminded me of https://github.com/scylladb/scylladb/issues/10743, where resharding didn't finish due to I/O scheduler changes. new i/o scheduler is available in 4.4, and this test was performed against 4.5.

**Comment by raphaelsc** [comment] 2023-06-06 17:00
> > @raphaelsc didn't we see an issue with compacting large collections on the field recently? We don't have a solution for that yet.
> 
> we did, but the side effect is slowness. from the description, it seems cleanup went just fine on most of the nodes, but in one node cleanup didn't finish. this reminded me of #10743, where resharding didn't finish due to I/O scheduler changes. new i/o scheduler is available in 4.4, and this test was performed against 4.5.

no that issue was not actually new i/o scheduler, but introduced by i/o throttler which is not available in that version

**Comment by vponomaryov** [comment] 2023-06-09 09:23
> > @vponomaryov since it's old, can you please try to reproduce on the latest
> 
> Triggered a test run. Will update here when I get results.

Have no correct results. Running once again.

**Comment by bhalevy** [comment] 2023-06-14 06:18
> @DoronArazii , the bug has not been reproduced using Scylla 5.2.1.

Based on https://github.com/scylladb/scylladb/issues/9917#issuecomment-1579132339 this looks like a fluke, related to hardware / environment issues on one of the nodes in the cluster.

I suggest closing it

**Closed** 2023-06-14 06:27 UTC
Labels: bug, nodetool, Pending-QA-Reproduction
