### ISSUE TITLE
large allocation during double_node_failure_during_mv_insert_3_nodes_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#4449] opened 2019-04-21 12:47 UTC
Seen in [dtest-release/100/artifact/logs-release.2/1555735815550_materialized_views_test.TestMaterializedViews.double_node_failure_during_mv_insert_3_nodes_test/node1.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/100/artifact/logs-release.2/1555735815550_materialized_views_test.TestMaterializedViews.double_node_failure_during_mv_insert_3_nodes_test/node1.log):
```
WARN  2019-04-20 04:49:49,020 [shard 0] seastar_memory - oversized allocation: 1310720 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at   0x438610b
  0x3ed8213
  0x3edcb1b
  0x24a62f5
  0x2498414
  0x2499ab8
  0x249b93e
  0x1dd4e11
  0x1ddc0a0
  0x1ebe22c
  0x1de8124
  0x1e2c17e
  0x1e2b979
  0x1e2e3a0
  0x3e9946c
  0x3f21ff1
  0x3f221ee
  0x3ff68d5
  0x3e94651
  0x8b66f4
  /jenkins/workspace/scylla-master/dtest-release@2/scylla-dtest/../scylla/dynamic_libs/libc.so.6+0x24412
  0x9166ed

$ addr2line -Cfpi -e logs-release.2/scylla 
seastar::current_backtrace() at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../include/seastar/util/backtrace.hh:55
 (inlined by) seastar::current_backtrace() at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/util/backtrace.cc:84
seastar::memory::cpu_pages::warn_large_allocation(unsigned long) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/memory.cc:624
operator new(unsigned long) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/memory.cc:632
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/memory.cc:638
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/memory.cc:1209
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/memory.cc:1259
 (inlined by) operator new(unsigned long) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/memory.cc:1662
seastar::circular_buffer<seastar::shared_mutex::waiter, std::allocator<seastar::shared_mutex::waiter> >::expand(unsigned long) at /usr/include/c++/8/ext/new_allocator.h:111
 (inlined by) seastar::circular_buffer<seastar::shared_mutex::waiter, std::allocator<seastar::shared_mutex::waiter> >::expand(unsigned long) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/circular_buffer.hh:301
db::hints::manager::end_point_hints_manager::store_hint(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<frozen_mutation const>, tracing::trace_state_ptr)::{lambda()#1}::operator()() at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/circular_buffer.hh:295
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/circular_buffer.hh:331
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/circular_buffer.hh:391
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/shared_mutex.hh:73
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/shared_mutex.hh:137
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release@2/scylla/db/hints/manager.cc:166
db::hints::manager::end_point_hints_manager::store_hint(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<frozen_mutation const>, tracing::trace_state_ptr) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/future.hh:1482
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/future.hh:1554
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/gate.hh:123
 (inlined by) db::hints::manager::end_point_hints_manager::store_hint(seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<frozen_mutation const>, tracing::trace_state_ptr) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/db/hints/manager.cc:160
db::hints::manager::store_hint(gms::inet_address, seastar::lw_shared_ptr<schema const>, seastar::lw_shared_ptr<frozen_mutation const>, tracing::trace_state_ptr) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/db/hints/manager.cc:299
service::storage_proxy::hint_to_dead_endpoints<std::vector<gms::inet_address, std::allocator<gms::inet_address> > >(std::unique_ptr<service::mutation_holder, std::default_delete<service::mutation_holder> >&, std::vector<gms::inet_address, std::allocator<gms::inet_address> > const&, db::write_type, tracing::trace_state_ptr)::{lambda(gms::inet_address)#1}::operator()(gms::inet_address) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/service/storage_proxy.cc:1625
 (inlined by) ?? at /usr/include/c++/8/bits/predefined_ops.h:283
 (inlined by) ?? at /usr/include/c++/8/bits/stl_algo.h:3194
 (inlined by) ?? at /usr/include/c++/8/bits/stl_algo.h:4105
 (inlined by) ?? at /usr/include/boost/range/algorithm/count_if.hpp:44
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/service/storage_proxy.cc:1620
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/service/storage_proxy.cc:1616
 (inlined by) service::storage_proxy::hint_to_dead_endpoints(unsigned long, db::consistency_level) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/service/storage_proxy.cc:1068
operator() at /jenkins/workspace/scylla-master/dtest-release@2/scylla/service/storage_proxy.cc:1104
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/future.hh:1482
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/future.hh:1554
 (inlined by) parallel_for_each<__gnu_cxx::__normal_iterator<service::storage_proxy::unique_response_handler*, std::vector<service::storage_proxy::unique_response_handler> >, service::storage_proxy::mutate_begin(std::vector<service::storage_proxy::unique_response_handler>, db::consistency_level, std::optional<std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long int, std::ratio<1, 1000> > > >)::<lambda(service::storage_proxy::unique_response_handler&)> > at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/future-util.hh:129
seastar::future<> service::storage_proxy::mutate_internal<boost::iterator_range<__gnu_cxx::__normal_iterator<mutation*, std::vector<mutation, std::allocator<mutation> > > > >(boost::iterator_range<__gnu_cxx::__normal_iterator<mutation*, std::vector<mutation, std::allocator<mutation> > > >, db::consistency_level, bool, tracing::trace_state_ptr, std::optional<std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > >) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/future-util.hh:180
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/service/storage_proxy.cc:1111
 (inlined by) service::storage_proxy::mutate_internal<boost::iterator_range<__gnu_cxx::__normal_iterator<mutation*, std::vector<mutation, std::allocator<mutation> > > > >(boost::iterator_range<__gnu_cxx::__normal_iterator<mutation*, std::vector<mutation, std::allocator<mutation> > > >, db::consistency_level, bool, tracing::trace_state_ptr, std::optional<std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > >)::{lambda(std::vector<service::storage_proxy::unique_response_handler, std::allocator<service::storage_proxy::unique_response_handler> >)#1}::operator()(std::vector<service::storage_proxy::unique_response_handler, std::allocator<service::storage_proxy::unique_response_handler> >) const at /jenkins/workspace/scylla-master/dtest-release@2/scylla/service/storage_proxy.cc:1288
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/future.hh:1472
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/future.hh:1002
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/future.hh:983
 (inlined by) seastar::future<> service::storage_proxy::mutate_internal<boost::iterator_range<__gnu_cxx::__normal_iterator<mutation*, std::vector<mutation, std::allocator<mutation> > > > >(boost::iterator_range<__gnu_cxx::__normal_iterator<mutation*, std::vector<mutation, std::allocator<mutation> > > >, db::consistency_level, bool, tracing::trace_state_ptr, std::optional<std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > > >) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/service/storage_proxy.cc:1291
service::storage_proxy::do_mutate(std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/service/storage_proxy.cc:1252
seastar::noncopyable_function<seastar::future<> (service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)>::direct_vtable_for<std::_Mem_fn<seastar::future<> (service::storage_proxy::*)(std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)> >::call(seastar::noncopyable_function<seastar::future<> (service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)> const*, service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool) at /usr/include/c++/8/bits/invoke.h:73
 (inlined by) ?? at /usr/include/c++/8/bits/invoke.h:96
 (inlined by) ?? at /usr/include/c++/8/functional:114
 (inlined by) seastar::noncopyable_function<seastar::future<> (service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)>::direct_vtable_for<std::_Mem_fn<seastar::future<> (service::storage_proxy::*)(std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)> >::call(seastar::noncopyable_function<seastar::future<> (service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)> const*, service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/util/noncopyable_function.hh:71
seastar::noncopyable_function<seastar::future<> (service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)>::direct_vtable_for<seastar::inheriting_concrete_execution_stage<seastar::future<>, service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool>::make_stage_for_group(seastar::scheduling_group)::{lambda(service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)#1}>::call(seastar::noncopyable_function<seastar::future<> (service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)> const*, service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/util/noncopyable_function.hh:145
 (inlined by) seastar::inheriting_concrete_execution_stage<seastar::future<>, service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool>::make_stage_for_group(seastar::scheduling_group)::{lambda(service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)#1}::operator()(service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool) const at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/execution_stage.hh:323
 (inlined by) seastar::noncopyable_function<seastar::future<> (service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)>::direct_vtable_for<seastar::inheriting_concrete_execution_stage<seastar::future<>, service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool>::make_stage_for_group(seastar::scheduling_group)::{lambda(service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)#1}>::call(seastar::noncopyable_function<seastar::future<> (service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool)> const*, service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/util/noncopyable_function.hh:71
seastar::concrete_execution_stage<seastar::future<>, service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool>::do_flush() at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/util/noncopyable_function.hh:145
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/future.hh:1472
 (inlined by) seastar::concrete_execution_stage<seastar::future<>, service::storage_proxy*, std::vector<mutation, std::allocator<mutation> >, db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >, tracing::trace_state_ptr, bool>::do_flush() at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/include/seastar/core/execution_stage.hh:243
operator() at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/execution_stage.cc:140
 (inlined by) run_and_dispose at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../include/seastar/core/task.hh:48
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/reactor.cc:3652
seastar::reactor::run_some_tasks() [clone .part.2880] at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/reactor.cc:4077
seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/reactor.cc:4060
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/reactor.cc:4220
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /jenkins/workspace/scylla-master/dtest-release@2/scylla/seastar/build/release/../../src/core/app-template.cc:186
main at /jenkins/workspace/scylla-master/dtest-release@2/scylla/main.cc:350
```

**Comment by bhalevy** [comment] 2019-04-21 12:47
Might be related to #4385

**Comment by bhalevy** [comment] 2019-04-21 12:51
Seen also in [TestHintedHandoff.hintedhandoff_retransmit_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/100/artifact/logs-release.2/1555742628994_hintedhandoff_additional_test.TestHintedHandoff.hintedhandoff_retransmit_test/node2.log)

**Comment by bhalevy** [comment] 2019-04-21 14:44
@vladzcloudius this looks like in code you authored. Can you please look into this?

**Comment by tgrabiec** [comment] 2019-04-23 08:12
Caused by https://github.com/scylladb/seastar/issues/628

**Comment by vladzcloudius** [comment] 2019-04-24 21:39
> Caused by [scylladb/seastar#628](https://github.com/scylladb/seastar/issues/628)

@bhalevy I guess this takes me off the hook, doesn't it? ;)

**Comment by bhalevy** [comment] 2019-04-25 05:39
> > Caused by [scylladb/seastar#628](https://github.com/scylladb/seastar/issues/628)
> 
> @bhalevy I guess this takes me off the hook, doesn't it? ;)

@vladzcloudius yes, it does :)

**Comment by eliransin** [comment] 2019-05-06 07:29
@nyh @psarna 
It doesn't look like a materialized view/secondary indexes thing, but just to be on the safe side lets check.

**Comment by nyh** [comment] 2023-01-30 15:52
There are no recent re-occurances of this issue, and it's suggested above that this was a Seastar issue fixed long ago, so closing this issue.

**Closed by nyh** 2023-01-30 15:52 UTC
Labels: materialized-views, dtest
