### ISSUE TITLE
Unable to replace node using IP of a node

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylladb#13865] opened 2023-05-12 10:24 UTC
*Installation details*
Scylla version (or git commit hash): 5.2.0-0.20230427.429b696bbc1b with build-id 9736db0414bad938b1d5d959bb25fbb4fb8558ce
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): Container image (docker.io/scylladb/scylla:5.2.0)

One of the e2e test in scylla-operator started failing after bumping ScyllaDB to 5.2.0. 
Issue doesn't reproduce on 5.1.9.

Steps to reproduce:
1. Create 2 node cluster using 5.2.0
2. Replace first node using `replace_address_first_boot` using the IP address of first node.
3. New node doesn't boot due to constantly printed error message:
```
INFO  2023-05-12 10:17:57,539 [shard 0] raft_group0 - server 14ded179-01ce-43d8-a485-db0b660efaac found group 0 with group id 5f131d10-f0ad-11ed-add7-0164f91eb567, leader 8c7e0296-a83b-4c30-83cf-460484fffde1
WARN  2023-05-12 10:17:58,541 [shard 0] raft_group0 - failed to modify config at peer 8c7e0296-a83b-4c30-83cf-460484fffde1: seastar::rpc::timeout_error (rpc call timed out). Retrying.
```

Node 1 doesn't produce any new logs when these are being constantly printed in node 0.
Tcpdump on node 0 shows traffic to node 1 to port 7000, on which nodes have connectivity.

Logs:
Node 0 before replacement - [node0.txt](https://github.com/scylladb/scylladb/files/11461946/node0.txt)
Node 1 - [node1.txt](https://github.com/scylladb/scylladb/files/11461949/node1.txt)
Node 0 after replacement - [node0-after.txt](https://github.com/scylladb/scylladb/files/11461952/node0-after.txt)

|                           | Host ID                              | IP Address     |
|---------------------------|--------------------------------------|----------------|
| Node 0 before replacement | 3a2959ff-cbf9-490b-bffc-48b8861761f5 | 10.101.236.231 |
| Node 1                    | 8c7e0296-a83b-4c30-83cf-460484fffde1 | 10.100.250.75  |
| Node 0 after replacement  | 14ded179-01ce-43d8-a485-db0b660efaac | 10.109.122.165 |

**Comment by kbr-scylla** [comment] 2023-05-19 13:28
Raft is not live without a majority of servers being alive.
For 2 servers a majority means 2.

**Comment by DoronArazii** [comment] 2023-05-22 07:23
@kbr-scylla what you're trying to say is that this issue isn't related to raft?

**Comment by mykaul** [comment] 2023-05-22 08:27
I'm unsure we should support 2 nodes clusters. However, 2 nodes per DC is a topology we may wish to support.

**Comment by kbr-scylla** [comment] 2023-05-22 08:29
It's not like we don't support 2 node clusters. We do.
But if we kill one of them you lose Raft majority so you can't perform schema or topology changes.
There is still a way out in this case, which is the manual recovery procedure:
https://docs.scylladb.com/stable/architecture/raft.html#raft-manual-recovery-procedure

**Comment by kbr-scylla** [comment] 2023-05-22 08:30
Also relevant
https://docs.scylladb.com/stable/architecture/raft.html#handling-failures

(the entire document is pretty much relevant)

**Comment by mykaul** [comment] 2023-05-22 11:51
I was referring specifically to the following step:
```
Verify that all the nodes have entered RECOVERY mode when restarting; look for one of the following messages in their logs
```

**Comment by DoronArazii** [comment] 2023-05-22 13:57
> It definitely is. But it's not something that can be fixed because it follows from the design of Raft. https://docs.scylladb.com/stable/architecture/raft.html#quorum-requirement

Thanks for triaging this Kamil.

@zimnx / @temichus apparently this is working as expected by design.
Please verify that it's documented well enough & close the issue as won't fix.

**Comment by kostja** [comment] 2023-07-18 18:33
Working as planned. The docs are unambiguous about it. https://opensource.docs.scylladb.com/stable/architecture/raft.html#quorum-requirement

**Closed by kostja** 2023-07-18 18:33 UTC
Labels: Regression, raft
