### ISSUE TITLE
Reactor stalled for 978 ms on shard 6

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#13632] opened 2023-04-23 11:24 UTC
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

```
2023-04-21 20:56:02.447 <2023-04-21 20:56:02.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=8151e532-3a81-4fae-b6c6-2f3cc4345d92: type=REACTOR_STALLED regex=Reactor stalled line_number=224350 node=longevity-large-partitions-200k-pks-db-node-9140d014-1
2023-04-21T20:56:02+00:00 longevity-large-partitions-200k-pks-db-node-9140d014-1     !INFO | scylla[76735]: Reactor stalled for 978 ms on shard 6. Backtrace: 0x4f44fb3 0x4f443a0 0x4f45780 0x3cb4f 0x1b31041 0x1b2e7fe 0x1b6a32b 0x1b3a53a 0x18f33cd 0x4f55894 0x4f56b17 0x4f77901 0x4f27bfa 0x8b14c 0x10c9ff
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:797
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:816
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1346
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1123
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1140
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1382
?? ??:0
rows_entry::position() const at ././mutation_partition.hh:964
 (inlined by) rows_entry::tri_compare::operator()(position_in_partition_view, rows_entry const&) const at ././mutation_partition.hh:1002
 (inlined by) intrusive_b::searcher<position_in_partition_view, rows_entry, &rows_entry::_link, rows_entry::tri_compare, (intrusive_b::key_search)0>::ge(position_in_partition_view const&, intrusive_b::node_base const&, rows_entry::tri_compare const&, bool&) at ././utils/intrusive_btree.hh:1050
 (inlined by) unsigned long intrusive_b::node<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::index_for<position_in_partition_view>(position_in_partition_view const&, rows_entry::tri_compare const&, bool&) const at ././utils/intrusive_btree.hh:1388
 (inlined by) bool intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::key_lower_bound<position_in_partition_view>(position_in_partition_view const&, rows_entry::tri_compare const&, intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::cursor&) const at ././utils/intrusive_btree.hh:276
 (inlined by) intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::const_iterator intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::lower_bound<position_in_partition_view>(position_in_partition_view const&, bool&, rows_entry::tri_compare) const at ././utils/intrusive_btree.hh:487
intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::iterator intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::lower_bound<position_in_partition_view>(position_in_partition_view const&, bool&, rows_entry::tri_compare) at ././utils/intrusive_btree.hh:500
 (inlined by) intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::iterator intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0>::lower_bound<position_in_partition_view>(position_in_partition_view const&, rows_entry::tri_compare) at ././utils/intrusive_btree.hh:514
 (inlined by) auto utils::immutable_collection<intrusive_b::tree<rows_entry, &rows_entry::_link, rows_entry::tri_compare, 12ul, 20ul, (intrusive_b::key_search)0, (intrusive_b::with_debug)0> >::lower_bound<position_in_partition_view&, rows_entry::tri_compare&>(position_in_partition_view&, rows_entry::tri_compare&) at ././utils/immutable-collection.hh:52
 (inlined by) partition_snapshot_row_cursor::prepare_heap(position_in_partition_view) at ././partition_snapshot_row_cursor.hh:218
 (inlined by) partition_snapshot_row_cursor::maybe_advance_to(position_in_partition_view) at ././partition_snapshot_row_cursor.hh:347
partition_snapshot_row_cursor::advance_to(position_in_partition_view) at ././partition_snapshot_row_cursor.hh:446
 (inlined by) cache::cache_flat_mutation_reader::move_to_range(__gnu_cxx::__normal_iterator<nonwrapping_interval<clustering_key_prefix> const*, std::vector<nonwrapping_interval<clustering_key_prefix>, std::allocator<nonwrapping_interval<clustering_key_prefix> > > >) at ././cache_flat_mutation_reader.hh:686
operator() at ././cache_flat_mutation_reader.hh:333
 (inlined by) operator() at ././row_cache.hh:481
 (inlined by) decltype(auto) logalloc::allocating_section::with_reclaiming_disabled<cache::lsa_manager::run_in_read_section<cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1}>(cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1} const&)::{lambda()#1}&>(logalloc::region&, cache::lsa_manager::run_in_read_section<cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1}>(cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1} const&)::{lambda()#1}&) at ././utils/logalloc.hh:499
 (inlined by) operator() at ././utils/logalloc.hh:521
 (inlined by) decltype(auto) logalloc::allocating_section::with_reserve<logalloc::allocating_section::operator()<cache::lsa_manager::run_in_read_section<cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1}>(cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1} const&)::{lambda()#1}>(logalloc::region&, cache::lsa_manager::run_in_read_section<cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1}>(cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1} const&)::{lambda()#1}&&)::{lambda()#1}>(logalloc::region&, cache::lsa_manager::run_in_read_section<cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1}>(cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1} const&)::{lambda()#1}&&) at ././utils/logalloc.hh:470
 (inlined by) decltype(auto) logalloc::allocating_section::operator()<cache::lsa_manager::run_in_read_section<cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1}>(cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1} const&)::{lambda()#1}>(logalloc::region&, cache::lsa_manager::run_in_read_section<cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1}>(cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1} const&)::{lambda()#1}&&) at ././utils/logalloc.hh:520
 (inlined by) decltype(auto) cache::lsa_manager::run_in_read_section<cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1}>(cache::cache_flat_mutation_reader::fill_buffer()::{lambda()#1}::operator()() const::{lambda()#1} const&) at ././row_cache.hh:480
 (inlined by) operator() at ././cache_flat_mutation_reader.hh:332
 (inlined by) cache::cache_flat_mutation_reader::fill_buffer() at ././cache_flat_mutation_reader.hh:340
operator() at ././readers/flat_mutation_reader_v2.hh:209
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<flat_mutation_reader_v2::impl::consume_pausable<std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<compact_for_query_v2<query_result_builder> > > >(std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<compact_for_query_v2<query_result_builder> > >)::{lambda()#1}&>(flat_mutation_reader_v2::impl::consume_pausable<std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<compact_for_query_v2<query_result_builder> > > >(std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<compact_for_query_v2<query_result_builder> > >)::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:2147
 (inlined by) auto seastar::futurize_invoke<flat_mutation_reader_v2::impl::consume_pausable<std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<compact_for_query_v2<query_result_builder> > > >(std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<compact_for_query_v2<query_result_builder> > >)::{lambda()#1}&>(flat_mutation_reader_v2::impl::consume_pausable<std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<compact_for_query_v2<query_result_builder> > > >(std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<compact_for_query_v2<query_result_builder> > >)::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:2178
 (inlined by) seastar::internal::repeater<flat_mutation_reader_v2::impl::consume_pausable<std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<compact_for_query_v2<query_result_builder> > > >(std::reference_wrapper<flat_mutation_reader_v2::impl::consumer_adapter<compact_for_query_v2<query_result_builder> > >)::{lambda()#1}>::run_and_dispose() at ././seastar/include/seastar/core/loop.hh:73
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2509
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2946
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3115
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4326
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_94>::_M_invoke(std::_Any_data const&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:290
std::function<void ()>::operator()() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:591
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:73
?? ??:0
?? ??:0
?? ??:0
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.19.0-1022-aws
Scylla version (or git commit hash): `5.2.0~rc4-20230402.d70751fee3f9` with build-id `80951fe7ff3c6e2c268211c71a9236071ac18a35`

Cluster size: 5 nodes (i4i.8xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-200k-pks-db-node-9140d014-9 (3.250.19.126 | 10.4.2.80) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-8 (3.252.166.100 | 10.4.2.27) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-7 (34.244.69.234 | 10.4.3.245) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-6 (3.253.19.45 | 10.4.3.84) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-5 (34.244.58.37 | 10.4.0.8) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-4 (3.253.49.23 | 10.4.0.52) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-3 (3.251.80.67 | 10.4.1.29) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-2 (54.216.123.205 | 10.4.3.93) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-13 (3.250.53.166 | 10.4.0.200) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-12 (54.194.207.232 | 10.4.1.2) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-11 (3.250.33.202 | 10.4.1.157) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-10 (34.253.220.36 | 10.4.0.149) (shards: 30)
- longevity-large-partitions-200k-pks-db-node-9140d014-1 (34.244.185.221 | 10.4.2.148) (shards: 30)

OS / Image: `ami-05ad5589d671f2b48` (aws: eu-west-1)

Test: `longevity-large-partition-200k-pks-4days-aws-i4i-test`
Test id: `9140d014-7bd9-484c-9183-09e4efb8929b`
Test name: `scylla-5.2/longevity/longevity-large-partition-200k-pks-4days-aws-i4i-test`
Test config file(s):

- [longevity-large-partition-200k_pks-2days-i4i.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/e6a6814e8deb415a2471d9609092ac543ac1abef/test-cases/longevity/longevity-large-partition-200k_pks-2days-i4i.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9140d014-7bd9-484c-9183-09e4efb8929b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9140d014-7bd9-484c-9183-09e4efb8929b)
- Show all stored logs command: `$ hydra investigate show-logs 9140d014-7bd9-484c-9183-09e4efb8929b`

## Logs:
- **db-cluster-9140d014.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/db-cluster-9140d014.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/db-cluster-9140d014.tar.gz)
- **email_data-9140d014.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/email_data-9140d014.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/email_data-9140d014.json.tar.gz)
- **output-9140d014.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/output-9140d014.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/output-9140d014.log.tar.gz)
- **debug-9140d014.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/debug-9140d014.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/debug-9140d014.log.tar.gz)
- **events-9140d014.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/events-9140d014.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/events-9140d014.log.tar.gz)
- **normal-9140d014.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/normal-9140d014.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/normal-9140d014.log.tar.gz)
- **argus-9140d014.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/argus-9140d014.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/argus-9140d014.log.tar.gz)
- **raw_events-9140d014.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/raw_events-9140d014.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/raw_events-9140d014.log.tar.gz)
- **critical-9140d014.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/critical-9140d014.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/critical-9140d014.log.tar.gz)
- **warning-9140d014.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/warning-9140d014.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/warning-9140d014.log.tar.gz)
- **summary-9140d014.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/summary-9140d014.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/summary-9140d014.log.tar.gz)
- **left_processes-9140d014.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/left_processes-9140d014.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/left_processes-9140d014.log.tar.gz)
- **error-9140d014.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/error-9140d014.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/error-9140d014.log.tar.gz)
- **2023_04_20__07_58_38_563.sct-9140d014.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/2023_04_20__07_58_38_563.sct-9140d014.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/2023_04_20__07_58_38_563.sct-9140d014.log.gz)
- **2023_04_20__22_43_00_745.sct-9140d014.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/2023_04_20__22_43_00_745.sct-9140d014.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/2023_04_20__22_43_00_745.sct-9140d014.log.gz)
- **2023_04_21__06_03_53_493.sct-9140d014.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/2023_04_21__06_03_53_493.sct-9140d014.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/2023_04_21__06_03_53_493.sct-9140d014.log.gz)
- **2023_04_21__13_45_04_322.sct-9140d014.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/2023_04_21__13_45_04_322.sct-9140d014.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/2023_04_21__13_45_04_322.sct-9140d014.log.gz)
- **2023_04_21__20_20_26_105.sct-9140d014.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/2023_04_21__20_20_26_105.sct-9140d014.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/2023_04_21__20_20_26_105.sct-9140d014.log.gz)
- **monitor-set-9140d014.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/monitor-set-9140d014.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/monitor-set-9140d014.tar.gz)
- **loader-set-9140d014.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/loader-set-9140d014.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9140d014-7bd9-484c-9183-09e4efb8929b/20230422_053937/loader-set-9140d014.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-large-partition-200k-pks-4days-aws-i4i-test/6/)
</details>

**Comment by mykaul** [comment] 2023-04-23 11:45
@yarongilor - there's little value (right now) on testing with 5.19 (and looking at stalls), since we assume the interrupts are not properly mapped.

**Comment by mykaul** [comment] 2023-04-25 14:16
Closing (under the assumption it's due to misconfigured interrupts) - please re-open once reproduced with a 5.15 kernel.

**Closed by mykaul** 2023-04-25 14:16 UTC

**Comment by michoecho** [comment] 2023-04-26 16:44
> My only explanation is coincidence — the stack trace happens in with_reserve, so it might be that memory reclaim took 977 ms,

On second thought — the above should have triggered `lsa-timing` logs, which are not present. So this couldn't be memory reclaim.

Interestingly, in the same second as the stall, this happens:
```
2023-04-21T20:56:02+00:00 longevity-large-partitions-200k-pks-db-node-9140d014-1     !INFO | sshd[4926]: Bad packet length 1349176281.
```

This error happened only 4 times across all nodes throughout the test run, and in all cases it was accompanied by stalls. I wonder if it could be the cause of the stall somehow.

**Comment by mykaul** [comment] 2023-04-27 08:46
> @michoecho - I keep suggesting sshd should be limited to specific cores, if the topology allows it (those that are not used by shards).

If QA's nodes are publicly available, btw, they may be getting SSH scans and whatnot. @roydahan - could that be the case?

**Comment by michoecho** [comment] 2023-04-27 11:06
> If QA's nodes are publicly available, btw, they may be getting SSH scans and whatnot. @roydahan - could that be the case?

I'm fairly sure I did see SSH scans in QA test logs sometimes, but I don't really see that here (usually they are a long stream of login attempts for various "common" usernames, like "admin" and so on — there wasn't anything like that in this test).

But anyway, how could sshd cause second-long stalls in Seastar? Linux's CPU scheduler is much more granular than that, after all.

**Comment by michoecho** [comment] 2023-04-27 11:10
I guess if someone sent a tricky packet to sshd, it could do some giant allocations which swap out Seastar's memory and cause paging stalls? I have no idea how sshd works on that level.

**Comment by mykaul** [comment] 2023-04-27 11:10
> I guess if someone sent a tricky packet to sshd, it could do some giant allocations which swap out Seastar's memory and cause paging stalls? I have no idea how sshd works on that level.

I sincerely hope that's not the case, but that was my suspicion as well.

**Comment by avikivity** [comment] 2023-04-27 13:44
> > My only explanation is coincidence — the stack trace happens in with_reserve, so it might be that memory reclaim took 977 ms,
> 
> On second thought — the above should have triggered `lsa-timing` logs, which are not present. So this couldn't be memory reclaim.
> 
> Interestingly, in the same second as the stall, this happens:
> 
> ```
> 2023-04-21T20:56:02+00:00 longevity-large-partitions-200k-pks-db-node-9140d014-1     !INFO | sshd[4926]: Bad packet length 1349176281.
> ```
> 
> This error happened only 4 times across all nodes throughout the test run, and in all cases it was accompanied by stalls. I wonder if it could be the cause of the stall somehow.

I've seen this Bad packet length before.

https://github.com/scylladb/scylladb/issues/11528#issuecomment-1365200311

There follows the same discussion about whether bad packets could indeed cause it, and the same delving into openssh code.

**Comment by avikivity** [comment] 2023-04-27 13:46
https://github.com/scylladb/scylladb/issues/11528#issuecomment-1438770086 asked for a kernel callstack. Do we have one now?

It could indeed be #8828. If the stall happened at a relatively young age in the life of the process (or at least, shortly after the workload started), it would be an additional data point in favor. Though with tests, that's normal.

**Comment by michoecho** [comment] 2023-04-27 13:54
> [#11528 (comment)](https://github.com/scylladb/scylladb/issues/11528#issuecomment-1438770086) asked for a kernel callstack. Do we have one now?
> 
> It could indeed be #8828. If the stall happened at a relatively young age in the life of the process (or at least, shortly after the workload started), it would be an additional data point in favor. Though with tests, that's normal.

We do have a kernel stacktrace, but it seems irrelevant.
(But truth be told I never studied how our kernel stacktrace gathering works, and what they actually represent, so I'm a bad judge of that.)
```
[Backtrace #0]
0xffffffffffffff80 (1068067760 bytes after last symbol)
kmem_cache_alloc+0xfb
bvec_alloc+0x94
bio_alloc_bioset+0x2e6
iomap_dio_alloc_bio.isra.0+0x39
iomap_dio_bio_iter+0x2d3
__iomap_dio_rw+0x3b1
iomap_dio_rw+0x11
xfs_file_dio_read+0xc5
xfs_file_read_iter+0x132
aio_read+0xec
__io_submit_one.constprop.0+0x113
io_submit_one+0xde
__x64_sys_io_submit+0x83
do_syscall_64+0x59
entry_SYSCALL_64_after_hwframe+0x63
```
Doesn't seem like #8828, does it?
