### ISSUE TITLE
all upgrade tests failing with `ALTERNATOR_STREAMS` being disabled in latest master

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#15214] opened 2023-08-29 20:46 UTC
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

during upgrade the 1st node, service start fails with the following check:
```
< t:2023-08-26 07:25:59,776 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-08-26T07:25:59+00:00 rolling-upgrade--centos-8-db-node-b3773563-0-3      !ERR | scylla[255421]:  [shard  0] init - Startup failed: std::runtime_error (Feature 'ALTERNATOR_STREAMS' was previously enabled in the cluster but its support is disabled by this node. Set the corresponding configuration option to enable the support for the feature.)
< t:2023-08-26 07:25:59,781 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-08-26 07:25:59.778 <2023-08-26 07:25:59.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=a641df7d-8ec2-4e12-a385-b8f540cafb04: type=RUNTIME_ERROR regex=std::runtime_error line_number=12887 node=rolling-upgrade--centos-8-db-node-b3773563-0-3
< t:2023-08-26 07:25:59,781 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-08-26T07:25:59+00:00 rolling-upgrade--centos-8-db-node-b3773563-0-3      !ERR | scylla[255421]:  [shard  0] init - Startup failed: std::runtime_error (Feature 'ALTERNATOR_STREAMS' was previously enabled in the cluster but its support is disabled by this node. Set the corresponding configuration option to enable the support for the feature.)
```

## Impact

service fails to start

## How frequently does it reproduce?

it is being reproduced in all upgrade tests, Alternator, pre-installed Scylla and non-pre-installed Scylla

## Installation details

Kernel Version: 4.18.0-500.el8.x86_64
Scylla version (or git commit hash): `5.3.0~rc0-20230523.3c3621db072d` with build-id `78cb9caaf1cdd0b37c3a38fa83548e6c4e3d4ab4`

targed version is `Scylla version 5.4.0~dev-0.20230824.93be4c0cb0f0 with build-id 9e29ac9d5d35
1d94023b4d80a71e21172f311f9d`

Cluster size: 4 nodes (n2-highmem-16)

Scylla Nodes used in this run:
- rolling-upgrade--centos-8-db-node-b3773563-0-4 (34.138.54.115 | 10.142.0.187) (shards: 14)
- rolling-upgrade--centos-8-db-node-b3773563-0-3 (104.196.218.171 | 10.142.0.183) (shards: 14)
- rolling-upgrade--centos-8-db-node-b3773563-0-2 (34.73.23.198 | 10.142.0.177) (shards: 14)
- rolling-upgrade--centos-8-db-node-b3773563-0-1 (34.23.26.240 | 10.142.0.163) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-8` (gce: undefined_region)

Test: `rolling-upgrade-centos8-test`
Test id: `b3773563-b1af-4083-9f3f-ae54f84f88b3`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-centos8-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/78a9096345b96647cc95d39fe1c11a6e0505677c/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b3773563-b1af-4083-9f3f-ae54f84f88b3`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b3773563-b1af-4083-9f3f-ae54f84f88b3)
- Show all stored logs command: `$ hydra investigate show-logs b3773563-b1af-4083-9f3f-ae54f84f88b3`

## Logs:
- **db-cluster-b3773563.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b3773563-b1af-4083-9f3f-ae54f84f88b3/20230826_073924/db-cluster-b3773563.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b3773563-b1af-4083-9f3f-ae54f84f88b3/20230826_073924/db-cluster-b3773563.tar.gz)
- **sct-runner-events-b3773563.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b3773563-b1af-4083-9f3f-ae54f84f88b3/20230826_073924/sct-runner-events-b3773563.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b3773563-b1af-4083-9f3f-ae54f84f88b3/20230826_073924/sct-runner-events-b3773563.tar.gz)
- **sct-b3773563.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b3773563-b1af-4083-9f3f-ae54f84f88b3/20230826_073924/sct-b3773563.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b3773563-b1af-4083-9f3f-ae54f84f88b3/20230826_073924/sct-b3773563.log.tar.gz)
- **loader-set-b3773563.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b3773563-b1af-4083-9f3f-ae54f84f88b3/20230826_073924/loader-set-b3773563.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b3773563-b1af-4083-9f3f-ae54f84f88b3/20230826_073924/loader-set-b3773563.tar.gz)
- **monitor-set-b3773563.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b3773563-b1af-4083-9f3f-ae54f84f88b3/20230826_073924/monitor-set-b3773563.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b3773563-b1af-4083-9f3f-ae54f84f88b3/20230826_073924/monitor-set-b3773563.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos8-test/212/)
[Argus](https://argus.scylladb.com/test/bc02ce5e-a796-4435-a3e2-c7a1744e3111/runs?additionalRuns[]=b3773563-b1af-4083-9f3f-ae54f84f88b3)
</details>

**Comment by DoronArazii** [comment] 2023-08-30 09:30
@nuivall can you please provide some assessment

**Comment by fgelcer** [comment] 2023-08-30 09:41
> i'm re-running one of the failed jobs [here](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-debian11-test/)

it also failed, with the same error

**Comment by nyh** [comment] 2023-08-30 10:56
Very odd. The "alternator streams" feature has been experimental protected by this ALTERNATOR_STREAMS cluster feature bit for three years, with no changes. So what changed now? Could we have a regression in the cluster feature handling?

**Comment by nyh** [comment] 2023-08-30 11:00
@fgelcer I'm not familiar withy what this test does, maybe you can give me a few more details. Where is it defined which Scylla ran before the upgrade and which ran afterwards?

Where can I find the scylla.yaml configuration file used before and/or after the upgrade (configuration of Scylla, not the test, which only seems to say which workload was run during the upgrade)?

**Comment by nyh** [comment] 2023-08-30 11:03
Earlier this month, @kbr-scylla added commit b835acf853d8cf3553b96fe0aa4f5746304cccc5 which moved cluster features to Raft. Maybe this feature doesn't work across upgrades (the new node tries to use Raft to list features, the old node doesn't have Raft)? (just a wild guess).

By the way, why are we testing upgrades from the unpublished 5.3 release to master? Shouldn't we test upgrades from 5.2, our last official open-source release?

**Comment by kbr-scylla** [comment] 2023-08-30 11:05
> Earlier this month, @kbr-scylla added commit https://github.com/scylladb/scylladb/commit/b835acf853d8cf3553b96fe0aa4f5746304cccc5 which moved cluster features to Raft. Maybe this feature doesn't work across upgrades (the new node tries to use Raft to list features, the old node doesn't have Raft)? (just a wild guess).

This is only in experimental raft-topology mode (protected by experimental flag)

**Comment by nyh** [comment] 2023-08-30 11:09
Thanks @kbr-scylla sorry for the spam.

I have a better guess: In 190147559843980aa3f18cc5ad654b246c27fa70, last week, @avikivity dropped the "--experimental" option, which he says was "deprecated for 2 years since Scylla 4.6" and replaced by "--experimenta-feature". See PR https://github.com/scylladb/scylladb/pull/14948.

The mention of the ALTERNATOR_STREAMS bit being turned on, which was experimental, suggests maybe this test used the "--experimental" flag trying to turn on all experimental flags (I don't know why, if it was, it was a mistake) - and this is no longer supported. If that's not true, and the test didn't use "--experimental", maybe it's another bug in https://github.com/scylladb/scylladb/pull/14948?

**Comment by nyh** [comment] 2023-08-30 11:11
> I have a better guess: In [1901475](https://github.com/scylladb/scylladb/commit/190147559843980aa3f18cc5ad654b246c27fa70), last week, @avikivity dropped the "--experimental" option, which he says was "deprecated for 2 years since Scylla 4.6" and replaced by "--experimenta-feature". See PR #14948.

Correction: It was @tchaikov 's PR (the PR was only merged by @avikivity ).

**Comment by nyh** [comment] 2023-08-30 11:18
@fgelcer can you please test whether this test uses the "experimental" option of Scylla, through either the command line or scylla.yaml?

**Comment by tchaikov** [comment] 2023-08-31 08:06
@fgelcer @nuivall hi Fabio and Marcin, since it was me who broke the tests. i am trying fix them. see https://github.com/scylladb/scylla-cluster-tests/pull/6559

**Closed** 2023-09-03 12:30 UTC
Labels: test

**Comment by chaitanya-tondlekar** [comment] 2024-07-30 12:05
Whats the resolution over here ? I am still facing same while upgrading from 5.2.19 to 5.4.9

**Comment by nyh** [comment] 2024-07-30 12:21
> Whats the resolution over here ? I am still facing same while upgrading from 5.2.19 to 5.4.9

If I understand the discussion here correctly, what happened was that you used the `--experimental` flag in Scylla 5.2.19, and in Scylla 5.4.9 you need to specify each of them separately, e.g., `--experimental-features=alternator-streams`. Maybe if you add that specific setting to your scylla.yaml, things will go back to working? (I didn't check, but I think it's worth checking)

That being said, there's something more fundamental I don't understand maybe @tchaikov or @fgelcer or someone else understood: Once some experimental feature is enabled in a cluster, do we forbid turning it off FOREVER? Why? In this case I assume the user didn't even want to use Alternator Streams, and it was only ever enabled by the old "--experimental" flag, and now the user is not allowed to turn it off?

**Comment by chaitanya-tondlekar** [comment] 2024-07-30 12:33
Yes, in my scylla.yaml for 5.2.19 `experimental: true` is set. 
I tried starting service on 5.4.9 like 
`sudo service scylla-server start --experimental-features=alternator-streams` but its still failing. 
can you help exact what needs to be added in scylla.yaml to make service start in 5.4.9 ?

**Comment by nyh** [comment] 2024-07-30 13:24
I hoped that putting
```
experimental_features:
    - alternator-streams
```
would work, but maybe I'm wrong...

**Comment by chaitanya-tondlekar** [comment] 2024-07-30 13:45
Tried, but failed with same error :(

**Comment by tchaikov** [comment] 2024-07-30 14:30
> > Whats the resolution over here ? I am still facing same while upgrading from 5.2.19 to 5.4.9
> 
> If I understand the discussion here correctly, what happened was that you used the `--experimental` flag in Scylla 5.2.19, and in Scylla 5.4.9 you need to specify each of them separately, e.g., `--experimental-features=alternator-streams`. Maybe if you add that specific setting to your scylla.yaml, things will go back to working? (I didn't check, but I think it's worth checking)

we are actually using ``--experimental-features=alternator-streams` in our test. see https://github.com/scylladb/scylladb/blob/fdcbbb85adcd3dc5bf7f4c40cd0e398d405e1b78/test/alternator/run#L51

so this should work.

> 
> That being said, there's something more fundamental I don't understand maybe @tchaikov or @fgelcer or someone else 

FWIW, Fabio does not work on this project anymore.

> understood: Once some experimental feature is enabled in a cluster, do we forbid turning it off FOREVER? 

no, i don't think so. we just dropped the `--experimental` option. but user can still enable/disable a certain experimental feature using the `experimental_features` option.

> Why? In this case I assume the user didn't even want to use Alternator Streams, and it was only ever enabled by the old "--experimental" flag, and now the user is not allowed to turn it off?

`experimental_features` is empty by default. so the user does not have to use it if he/she does not want to.

**Comment by tchaikov** [comment] 2024-07-30 14:36
> Yes, in my scylla.yaml for 5.2.19 `experimental: true` is set. I tried starting service on 5.4.9 like `sudo service scylla-server start --experimental-features=alternator-streams` but its still failing.

did you remove `experimental: true` from `scylla.yaml` before upgrading to 5.4.9 ?

**Comment by avikivity** [comment] 2024-07-30 15:23
@nyh why is alternator-streams experimental?

**Comment by chaitanya-tondlekar** [comment] 2024-07-30 16:35
@tchaikov No `experimental: true` was not removed from scylla.yaml while upgrading binaries to 5.4.9.
Should we first comment it out in 5.2.19 and take a reboot and then do the upgrade process ?

**Comment by tchaikov** [comment] 2024-07-30 23:12
@chaitanya-tondlekar I'd like to propose an alternative approach so that scylla can still using existing or equivalent settings in the whole process. i suggest the following steps (i am referencing https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/upgrade-guide-from-5.4-to-6.0-generic.html#upgrade-procedure):

    1. drain the nodes, backup data
    2. comment `experimental: true` out or remove it from `scylla.yaml`
    3. stop scylla
    4. install 5.4.9
    5. start scylla

do you think we should update the document accordingly? i didn't update it because i thought that the user should not `experimental` features in production.

**Comment by nyh** [comment] 2024-07-30 23:32
@tchaikov you made a good point: One of the things that define an "experimental" feature is that upgrades are not guaranteed to work - the implementation may change and not be backward compatible (regarding on-disk data and also rolling upgrade of a cluster).
So once you used any experimental feature, you're not supposed to upgrade at all.
That being said, if someone mistakenly enabled an experimental feature but didn't use it, an upgrade should be able to work.

**Comment by tchaikov** [comment] 2024-07-30 23:58
just wanted to further clarify this.

> That being said, if someone mistakenly enabled an experimental feature but didn't use it, an upgrade should be able to work.

yeah, but sometimes, it's difficult to tell "use" from "enable", without reading user data, so some extra steps are expected. like the step removing `experimental: true` from the settings.

**Comment by chaitanya-tondlekar** [comment] 2024-07-31 17:48
@tchaikov I tried with your steps and now its failing to start scylla service with below error : 

Jul 31 17:45:50 scyl-dbeadmin-3 scylla:  [shard 0:main] init - Startup failed: gms::unsupported_feature_exception (Feature 'KEYSPACE_STORAGE_OPTIONS' was previously enabled in the cluster but its support is disabled by this node. Set the corresponding configuration option to enable the support for the feature.)

What can be done for this ?

**Comment by chaitanya-tondlekar** [comment] 2024-07-31 17:52
@tchaikov i added and it worked. Service is up and running on one of node with 5.4.9
```
experimental_features:
   - alternator-streams
   - keyspace-storage-options
```
