### ISSUE TITLE
database_test.test_* fails sporadically with auth query timing out

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#13660] opened 2023-04-24 15:56 UTC
HEAD: 642854f36f7686aea4a37ed62cf57025c81e61b8

```
bash-5.2# ./test.py --mode dev database_test --repeat 200
Found 6000 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[837/6000]  boost     dev   [ PASS ] boost.database_test.max_result_size_for_unlimited_query_selection_test.28                           
[838/6000]  boost     dev   [ FAIL ] boost.database_test.test_safety_after_truncate.29
```

**Comment by raphaelsc** [comment] 2023-04-24 17:05
just bumped on it

`unknown location(0): fatal error: in "test_safety_after_truncate": exceptions::read_timeout_exception: Operation timed out for system_auth.roles - received only 0 responses from 1 CL=LOCAL_ONE.`

seems a dup of https://github.com/scylladb/scylladb/issues/13556

**Comment by denesb** [comment] 2023-04-25 07:20
Will look into it.

**Comment by denesb** [comment] 2023-04-27 06:46
I can reproduce, although when I run this, for me other tests fail, not the one that fails for @avikivity.

**Comment by denesb** [comment] 2023-04-27 06:48
The symptom seems to be always the same: an auth query timing out. Strangely, this doesn't always generate a reader concurrency semaphore report.

**Comment by denesb** [comment] 2023-04-27 06:50
An example report from a run which did produce a semaphore diagnostics report:
```
56582 INFO  2023-04-26 10:15:09,150 [shard 1] reader_concurrency_semaphore - Semaphore _system_read_concurrency_sem with 1/100 count and 16384/21474836 memory resources: timed out, dumping permit diagnostics:
    1 permits count   memory  table/description/state
    2 1   1   16K system_auth.roles/data-query/waiting_for_execution
    3 1   0   0B  system_auth.roles/shard-reader/waiting_for_admission
    4 1   0   0B  system_auth.roles/data-query/waiting_for_admission
    5 1   0   0B  system_auth.roles/shard-reader/evicted
    6 1   0   0B  *.*/view_builder/active
    7 
    8 5   1   16K total
    9 
   10 Stats:
   11 permit_based_evictions: 0
   12 time_based_evictions: 1
   13 inactive_reads: 0
   14 total_successful_reads: 6
   15 total_failed_reads: 0
   16 total_reads_shed_due_to_overload: 0
   17 total_reads_killed_due_to_kill_limit: 0 
   18 reads_admitted: 23
   19 reads_enqueued_for_admission: 6
   20 reads_enqueued_for_memory: 0
   21 reads_admitted_immediately: 19
   22 reads_queued_because_ready_list: 4
   23 reads_queued_because_used_permits: 2 
   24 reads_queued_because_memory_resources: 0
   25 reads_queued_because_count_resources: 0 
   26 reads_queued_with_eviction: 0 
   27 total_permits: 34
   28 current_permits: 5
   29 used_permits: 0
   30 blocked_permits: 0
   31 disk_reads: 0
   32 sstables_read: 0
```

**Comment by denesb** [comment] 2023-04-27 06:51
A query timing out while `waiting_for_execution`. This doesn't make sense. Could this be a reproducer for https://github.com/scylladb/scylladb/pull/13541?

**Comment by denesb** [comment] 2023-04-27 06:52
I'll run the tests again with https://github.com/scylladb/scylladb/pull/13541, see if it makes a difference.

**Comment by denesb** [comment] 2023-04-27 08:25
> I'll run the tests again with #13541, see if it makes a difference.

This alone didn't cut it. But with an added tweak the tests are passing (run still in progress :crossed_fingers:).

**Comment by mykaul** [comment] 2023-04-27 08:28
> > I'll run the tests again with #13541, see if it makes a difference.
> 
> This alone didn't cut it. But with an added tweak the tests are passing (run still in progress crossed_fingers).

Tweak for #13541 or the tests?

**Comment by denesb** [comment] 2023-04-27 08:30
> > > I'll run the tests again with #13541, see if it makes a difference.
> > 
> > 
> > This alone didn't cut it. But with an added tweak the tests are passing (run still in progress crossed_fingers).
> 
> Tweak for #13541 or the tests?

The former. If the tests will pass, I will have to check if the tweak alone cuts it or #13541 is not needed at all.
To be honest, I don't have a complete understanding of how the problem fixed by #13541 happens. I should take this opportunity of having a reproducer (still not 100% sure about that) to dig deeper, the only problem is that a test run takes 10s of minutes at the least...

**Comment by denesb** [comment] 2023-04-27 08:38
Well, tests didn't pass.

**Comment by denesb** [comment] 2023-04-28 11:28
Timeout was a red herring. Looks like the read just gets very late to the replica side.

**Comment by denesb** [comment] 2023-05-04 06:23
I cannot reproduce this anymore on master. So, in lack of a better idea, I'm bisecting up to a commit I know still reproduces the failure. Knowing what fixed this might shed some light on what was wrong in the first place (provided the bisect succeeds).

**Comment by denesb** [comment] 2023-05-04 12:48
Bisecting points at 022465d673 as the fix for this.

**Comment by denesb** [comment] 2023-05-04 12:49
I will double check the bisecting result.

**Comment by denesb** [comment] 2023-05-04 12:49
Although it makes perfect sense. @raphaelsc when was the excessive off-strategy logging introduced, that 022465d673 fixes?

**Comment by bhalevy** [comment] 2023-05-04 14:22
> Although it makes perfect sense. @raphaelsc when was the excessive off-strategy logging introduced, that [022465d](https://github.com/scylladb/scylladb/commit/022465d6730fc3ecabcc96a850e044f81981c7d6) fixes?

I think that the inflation in number of messages was exposed by c270c305c09836563b9f900d8fe1c2081ad7d6ce

**Comment by raphaelsc** [comment] 2023-05-04 14:30
I think it's actually this commit: https://github.com/scylladb/scylladb/commit/e3e7c3c7e51bd73d79218ed4e8f62b4fe4df7daf

and 

https://github.com/scylladb/scylladb/commit/e103e41c7678350e61a1be34f5e41785362ecacb

@bhalevy That one you referred to is actually the ability to run the entire suite with cgs, but it's not wired to CI yet.

**Comment by raphaelsc** [comment] 2023-05-04 14:35
This commit b4e4bbd64a8 is interesting. We had to reduce the number of compaction groups for debug mode, to avoid timeouts. With dev mode, we're testing 1, 2, and 256 groups for a subset of database tests. One of the tests is test_safety_after_truncate. Perhaps we can restrict database_test to 1 and 2 groups (as in debug mode), unless otherwise specified by --xlog2-compaction-groups param that can be passed to test.py and will override this anyway.

**Comment by bhalevy** [comment] 2023-05-04 16:50
> @bhalevy That one you referred to is actually the ability to run the entire suite with cgs, but it's not wired to CI yet.

yes. we crossed paths. I fixed this and edited my comment above while you were writing your comment.

**Comment by denesb** [comment] 2023-05-05 06:14
This diff also makes the test pass consistently:
```diff
diff --git a/test/boost/database_test.cc b/test/boost/database_test.cc
index 28db4b0633..fba9d1e03e 100644
--- a/test/boost/database_test.cc
+++ b/test/boost/database_test.cc
@@ -75,7 +75,8 @@ future<> do_with_cql_env_and_compaction_groups(std::function<void(cql_test_env&)
 #ifdef SEASTAR_DEBUG
     std::vector<unsigned> x_log2_compaction_group_values = { 0 /* 1 CG */, 1 /* 2 CGs */ };
 #else
-    std::vector<unsigned> x_log2_compaction_group_values = { 0 /* 1 CG */, 1 /* 2 CGs */, 8 /* 256 CGs */ };
+    std::vector<unsigned> x_log2_compaction_group_values = { 0 /* 1 CG */, 1 /* 2 CGs */ };
+    //std::vector<unsigned> x_log2_compaction_group_values = { 0 /* 1 CG */, 1 /* 2 CGs */, 8 /* 256 CGs */ };
 #endif
     for (auto x_log2_compaction_groups : x_log2_compaction_group_values) {
         // clean the dir before running
```
So the problem is definitely related to the compaction groups.

**Comment by denesb** [comment] 2023-05-05 07:08
After applying the above patch:
```diff
diff --git a/run b/run
new file mode 100755
index 0000000000..8e75da2b49
--- /dev/null
+++ b/run
@@ -0,0 +1,8 @@
+#!/bin/bash
+
+CGROUPS=$1
+echo "Running with x**${CGROUPS} compaction groups"
+
+export X_LOG2_CGROUPS=${CGROUPS}
+
+perf record --call-graph=dwarf  -F 99 -o perf.data.${CGROUPS} -- ./build/release/test/boost/database_test_g -t test_safety_after_truncate -x no -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100 &> out.${CGROUPS}
diff --git a/test/boost/database_test.cc b/test/boost/database_test.cc
index 28db4b0633..9919fd516b 100644
--- a/test/boost/database_test.cc
+++ b/test/boost/database_test.cc
@@ -21,6 +21,7 @@
 #include "test/lib/log.hh"
 #include "test/lib/random_utils.hh"
 #include "test/lib/key_utils.hh"
+#include "test/lib/test_utils.hh"
 
 #include "replica/database.hh"
 #include "utils/lister.hh"
@@ -77,6 +78,9 @@ future<> do_with_cql_env_and_compaction_groups(std::function<void(cql_test_env&)
 #else
     std::vector<unsigned> x_log2_compaction_group_values = { 0 /* 1 CG */, 1 /* 2 CGs */, 8 /* 256 CGs */ };
 #endif
+    auto v = std::atoi(tests::getenv_safe("X_LOG2_CGROUPS").data());
+    testlog.info("v={}", v);
+    x_log2_compaction_group_values = { v };
     for (auto x_log2_compaction_groups : x_log2_compaction_group_values) {
         // clean the dir before running
         if (cfg.db_config->data_file_directories.is_set()) {
```

I ran the `run` script with `1` and `8` and compared the results (`perf diff perf.data.1 perf.data.8`):
```
# Event 'cycles:u'
#
# Baseline  Delta Abs  Shared Object         Symbol                                                                                                                                                                                                          >
# ........  .........  ....................  ................................................................................................................................................................................................................>
#
              +60.98%  database_test_g       [.] compaction_manager::get_candidates<std::unordered_set<seastar::lw_shared_ptr<sstables::sstable>, std::hash<seastar::lw_shared_ptr<sstables::sstable> >, std::equal_to<seastar::lw_shared_ptr<sstables::sstab>
              +15.07%  database_test_g       [.] compaction_manager::perform_task
    14.11%    -13.56%  [unknown]             [k] 0xffffffff8b097043
    11.41%    -11.22%  libhwloc.so.15.5.0    [.] 0x0000000000007464
     4.97%     -4.88%  database_test_g       [.] seastar::thread_pool::work
     3.89%     -3.81%  database_test_g       [.] compound_type<(allow_prefixes)1>::iterator::iterator
               +2.89%  database_test_g       [.] compaction_manager::stop_ongoing_compactions
               +2.37%  database_test_g       [.] logalloc::region_impl::~region_impl
               +2.06%  database_test_g       [.] replica::table::make_compound_sstable_set
               +1.98%  database_test_g       [.] sstables::compound_sstable_set::~compound_sstable_set
     1.38%     -1.34%  database_test_g       [.] seastar::net::virtio_options::virtio_options
               +1.00%  database_test_g       [.] seastar::memory::small_pool::add_more_objects
     1.45%     -0.81%  database_test_g       [.] std::_Function_handler<double (), compaction_manager::compaction_manager(compaction_manager::config, seastar::abort_source&, tasks::task_manager&)::$_7>::_M_invoke
               +0.67%  database_test_g       [.] sstables::partitioned_sstable_set::size
               +0.49%  database_test_g       [.] seastar::memory::small_pool::trim_free_list
     1.36%     -0.44%  database_test_g       [.] seastar::memory::free
               +0.41%  database_test_g       [.] sstables::sstable_set::size
     2.67%     -0.32%  database_test_g       [.] seastar::memory::allocate
               +0.32%  database_test_g       [.] compaction_manager::add
               +0.31%  database_test_g       [.] boost::heap::binomial_heap<replica::dirty_memory_manager_logalloc::size_tracked_region*, boost::heap::compare<replica::dirty_memory_manager_logalloc::region_evictable_occupancy_ascending_less_comparator>,>
               +0.24%  ld-linux-x86-64.so.2  [.] strcmp
               +0.22%  database_test_g       [.] compaction_manager::remove
               +0.17%  libc.so.6             [.] __memset_avx2_unaligned_erms
```
You can see that `get_candidates()` dominates the runtime of the version with x**2 compaction groups. The runtime difference is very noticable as well:
```
$ time ./run 1
Running with x**1 compaction groups

real    0m3.508s
user    0m0.174s
sys     0m0.309s

$ time ./run 8
Running with x**8 compaction groups

real    0m6.173s
user    0m5.956s
sys     0m0.660s

$ time ./run 9
Running with x**9 compaction groups

real    0m20.522s
user    0m31.344s
sys     0m0.936s
```
The increase in the time to run the test is not linear.

**Comment by raphaelsc** [comment] 2023-05-05 17:47
> After applying the below patch:
> 
> ```diff
> diff --git a/run b/run
> new file mode 100755
> index 0000000000..8e75da2b49
> --- /dev/null
> +++ b/run
> @@ -0,0 +1,8 @@
> +#!/bin/bash
> +
> +CGROUPS=$1
> +echo "Running with x**${CGROUPS} compaction groups"
> +
> +export X_LOG2_CGROUPS=${CGROUPS}
> +
> +perf record --call-graph=dwarf  -F 99 -o perf.data.${CGROUPS} -- ./build/release/test/boost/database_test_g -t test_safety_after_truncate -x no -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100 &> out.${CGROUPS}
> diff --git a/test/boost/database_test.cc b/test/boost/database_test.cc
> index 28db4b0633..9919fd516b 100644
> --- a/test/boost/database_test.cc
> +++ b/test/boost/database_test.cc
> @@ -21,6 +21,7 @@
>  #include "test/lib/log.hh"
>  #include "test/lib/random_utils.hh"
>  #include "test/lib/key_utils.hh"
> +#include "test/lib/test_utils.hh"
>  
>  #include "replica/database.hh"
>  #include "utils/lister.hh"
> @@ -77,6 +78,9 @@ future<> do_with_cql_env_and_compaction_groups(std::function<void(cql_test_env&)
>  #else
>      std::vector<unsigned> x_log2_compaction_group_values = { 0 /* 1 CG */, 1 /* 2 CGs */, 8 /* 256 CGs */ };
>  #endif
> +    auto v = std::atoi(tests::getenv_safe("X_LOG2_CGROUPS").data());
> +    testlog.info("v={}", v);
> +    x_log2_compaction_group_values = { v };
>      for (auto x_log2_compaction_groups : x_log2_compaction_group_values) {
>          // clean the dir before running
>          if (cfg.db_config->data_file_directories.is_set()) {
> ```
> 
> I ran the `run` script with `1` and `8` and compared the results (`perf diff perf.data.1 perf.data.8`):
> 
> ```
> # Event 'cycles:u'
> #
> # Baseline  Delta Abs  Shared Object         Symbol                                                                                                                                                                                                          >
> # ........  .........  ....................  ................................................................................................................................................................................................................>
> #
>               +60.98%  database_test_g       [.] compaction_manager::get_candidates<std::unordered_set<seastar::lw_shared_ptr<sstables::sstable>, std::hash<seastar::lw_shared_ptr<sstables::sstable> >, std::equal_to<seastar::lw_shared_ptr<sstables::sstab>
>               +15.07%  database_test_g       [.] compaction_manager::perform_task
>     14.11%    -13.56%  [unknown]             [k] 0xffffffff8b097043
>     11.41%    -11.22%  libhwloc.so.15.5.0    [.] 0x0000000000007464
>      4.97%     -4.88%  database_test_g       [.] seastar::thread_pool::work
>      3.89%     -3.81%  database_test_g       [.] compound_type<(allow_prefixes)1>::iterator::iterator
>                +2.89%  database_test_g       [.] compaction_manager::stop_ongoing_compactions
>                +2.37%  database_test_g       [.] logalloc::region_impl::~region_impl
>                +2.06%  database_test_g       [.] replica::table::make_compound_sstable_set
>                +1.98%  database_test_g       [.] sstables::compound_sstable_set::~compound_sstable_set
>      1.38%     -1.34%  database_test_g       [.] seastar::net::virtio_options::virtio_options
>                +1.00%  database_test_g       [.] seastar::memory::small_pool::add_more_objects
>      1.45%     -0.81%  database_test_g       [.] std::_Function_handler<double (), compaction_manager::compaction_manager(compaction_manager::config, seastar::abort_source&, tasks::task_manager&)::$_7>::_M_invoke
>                +0.67%  database_test_g       [.] sstables::partitioned_sstable_set::size
>                +0.49%  database_test_g       [.] seastar::memory::small_pool::trim_free_list
>      1.36%     -0.44%  database_test_g       [.] seastar::memory::free
>                +0.41%  database_test_g       [.] sstables::sstable_set::size
>      2.67%     -0.32%  database_test_g       [.] seastar::memory::allocate
>                +0.32%  database_test_g       [.] compaction_manager::add
>                +0.31%  database_test_g       [.] boost::heap::binomial_heap<replica::dirty_memory_manager_logalloc::size_tracked_region*, boost::heap::compare<replica::dirty_memory_manager_logalloc::region_evictable_occupancy_ascending_less_comparator>,>
>                +0.24%  ld-linux-x86-64.so.2  [.] strcmp
>                +0.22%  database_test_g       [.] compaction_manager::remove
>                +0.17%  libc.so.6             [.] __memset_avx2_unaligned_erms
> ```
> 
> You can see that `get_candidates()` dominates the runtime of the version with x**2 compaction groups. The runtime difference is very noticable as well:
> 
> ```
> $ time ./run 1
> Running with x**1 compaction groups
> 
> real    0m3.508s
> user    0m0.174s
> sys     0m0.309s
> 
> $ time ./run 8
> Running with x**8 compaction groups
> 
> real    0m6.173s
> user    0m5.956s
> sys     0m0.660s
> 
> $ time ./run 9
> Running with x**9 compaction groups
> 
> real    0m20.522s
> user    0m31.344s
> sys     0m0.936s
> ```
> 
> The increase in the time to run the test is not linear.

very good analysis. I think the problem may be the global task list in compaction_manager, which can grow unbounded, and each compaction group will have to operate on all entries.

With N groups, and each group having M tasks in the list, there are N * M tasks. The total amount of ops can amount to ~(N * M) * (N * (M - 1)). We can say it can produce quadratic behavior.

We can reduce the overhead significantly by having a task list for each group. so complexity isn't affected by number of groups.

**Comment by bhalevy** [comment] 2023-05-07 05:59
> We can reduce the overhead significantly by having a task list for each group. so complexity isn't affected by number of groups.

Sounds like the right direction.  Please explore it.

**Comment by avikivity** [comment] 2023-05-07 15:43
Who's get_candidates() caller that's calling it quadratically?

**Comment by bhalevy** [comment] 2023-05-09 13:54
@raphaelsc :point_up:

**Comment by raphaelsc** [comment] 2023-05-09 17:45
> Who's get_candidates() caller that's calling it quadratically?

with compaction groups, we're creating tasks faster than we can consume them.

so task list grows unboundly.

we should probably restrict each cg to a single pending task.

I noticed that task list is growing above 10k in the test, which is proportional to number of cgs.

As get_candidates() iterate through all tasks, we're getting quadratic behavior.

I will rework this area.

**Comment by raphaelsc** [comment] 2023-05-09 18:13
@avikivity @bhalevy I am thinking about renaming compaction::table_state to compaction::compaction_group or compaction::group.

table_state is very very vague. the class named table_state is compaction notion of a table (or compaction group, or whatever), not a table state. 

I am seeing things like this:

    std::unordered_map<compaction::table_state*, compaction_state> _compaction_state;

And it really hurts.

With my suggestion it becomes:

    std::unordered_map<compaction::compaction_group*, compaction_group_state> _compaction_state;

**Comment by bhalevy** [comment] 2023-05-10 13:13
If you want to rename `table_state` to `compaction::compaction_group`, I *THINK* we should rename `replica::compaction_group` to `replica::sub_table` (which I think is a better name regardless).

And then you'd have `replica::sub_table::as_compaction_group()` which is comprehensible, at least to me :)

**Comment by raphaelsc** [comment] 2023-05-10 13:40
> If you want to rename `table_state` to `compaction::compaction_group`, I _THINK_ we should rename `replica::compaction_group` to `replica::sub_table` (which I think is a better name regardless).
> 
> And then you'd have `replica::sub_table::as_compaction_group()` which is comprehensible, at least to me :)

What about implicit conversion during argument passing? So we don't have to rename replica::compaction_group now, until we reach an agreement on what it should be called. But if we want to name it replica::subtable, I am fine with proceeding with the change immediately. subtable by its definition fits well the concept of the class.

```
namespace compaction {

struct compaction_group {};

struct compaction_manager {
    void compact(compaction_group& cg) {}
};

}

namespace replica {

struct compaction_group {
    std::unique_ptr<compaction::compaction_group> _cg;

    compaction_group() : _cg(std::make_unique<compaction::compaction_group>()) {}

    operator compaction::compaction_group&() const {
        return *_cg;
    }
};

}

int main() {
    replica::compaction_group cg;
    compaction::compaction_manager().compact(cg);
}
```

**Comment by avikivity** [comment] 2023-05-10 17:18
10k tasks? that's crazy. What are all these tasks doing? This is a unit test. 

I don't expect to see 10k tasks in production.

**Comment by raphaelsc** [comment] 2023-05-10 22:52
> 10k tasks? that's crazy. What are all these tasks doing? This is a unit test.
> 
> I don't expect to see 10k tasks in production.

The problem is exarcebated with 256 compaction groups for each table. 

Those are mostly pending tasks, which yielded somewhere, after table triggered compaction. When those pending tasks resume, the task list is huge.

I will understand better what triggered this.

**Comment by raphaelsc** [comment] 2023-05-10 23:45
> > 10k tasks? that's crazy. What are all these tasks doing? This is a unit test.
> > I don't expect to see 10k tasks in production.
> 
> The problem is exarcebated with 256 compaction groups for each table.
> 
> Those are mostly pending tasks, which yielded somewhere, after table triggered compaction. When those pending tasks resume, the task list is huge.
> 
> I will understand better what triggered this.

It was this:

```
            db.invoke_on_all([] (replica::database& db) {
                for (auto& x : db.get_column_families()) {
                    replica::table& t = *(x.second);
                    t.enable_auto_compaction();
                }
            }).get();
```

which happens only on boot

**Comment by raphaelsc** [comment] 2023-05-10 23:51
Fixing this inefficiency in get_candidates() make the test only go ~4% faster, meaning that the test time is still dominated by rerunning a subset of the tests with a couple of xlog_compaction_group settings.

**Comment by raphaelsc** [comment] 2023-05-10 23:59
Patching the test like below make it go 240% faster.

```
diff --git a/test/boost/database_test.cc b/test/boost/database_test.cc
index 28db4b0633..96e75e2b0e 100644
--- a/test/boost/database_test.cc
+++ b/test/boost/database_test.cc
@@ -72,11 +72,7 @@ static future<> apply_mutation(sharded<replica::database>& sharded_db, table_id
 }
 
 future<> do_with_cql_env_and_compaction_groups(std::function<void(cql_test_env&)> func, cql_test_config cfg = {}, thread_attributes thread_attr = {}) {
-#ifdef SEASTAR_DEBUG
     std::vector<unsigned> x_log2_compaction_group_values = { 0 /* 1 CG */, 1 /* 2 CGs */ };
-#else
-    std::vector<unsigned> x_log2_compaction_group_values = { 0 /* 1 CG */, 1 /* 2 CGs */, 8 /* 256 CGs */ };
-#endif
```

**Comment by raphaelsc** [comment] 2023-05-11 00:13
auth query is timing out, because we're forcing its table to have N groups per shard. we don't even have yet an efficient sstable set for reading from groups. and additionally, the overhead of having so many groups for a small table, with little data spread across N=(# of groups * # of shards) groups is huge.

**Closed** 2023-05-14 13:50 UTC
Labels: test, P1, CI-Stability

**Comment by avikivity** [comment] 2023-11-30 15:31
Backported to 5.2. Already in 5.4, 5.1 doesn't need it.
