### ISSUE TITLE
Shorthand syntax for map update (+=) is not supported

### ISSUE THREAD

**Issue by rbino** [scylladb/scylladb#5375] opened 2019-11-28 11:52 UTC
*Installation details*
Scylla version (or git commit hash): 3.1.1 Docker image
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04

Using Cassandra 3.11.5 I can do this:
```
cqlsh:test> CREATE TABLE test (id int, my_map map<int, ascii>, PRIMARY KEY (id));
cqlsh:test> INSERT INTO test (id, my_map) VALUES ( 1, {1: 'foo'});
cqlsh:test> UPDATE test SET my_map += {2: 'bar'} WHERE id=1;
cqlsh:test> SELECT * FROM test;

 id | my_map
----+----------------------
  1 | {1: 'foo', 2: 'bar'}
```

While on Scylla 3.1.1 I get this:
```
cqlsh:test> CREATE TABLE test (id int, my_map map<int, ascii>, PRIMARY KEY (id));
cqlsh:test> INSERT INTO test (id, my_map) VALUES ( 1, {1: 'foo'});
cqlsh:test> UPDATE test SET my_map += {2: 'bar'} WHERE id=1;
SyntaxException: line 1:23 no viable alternative at input '+'
```

I'm aware I can just do
```
cqlsh:test> UPDATE test SET my_map = my_map + {2: 'bar'} WHERE id=1;
cqlsh:test> SELECT * FROM test;

 id | my_map
----+----------------------
  1 | {1: 'foo', 2: 'bar'}
```

But I suppose that's still a Cassandra compatibility issue (i.e. I can't use Scylla as a drop-in replacement without modifying the code).

**Comment by nyh** [comment] 2024-06-17 06:42
Issue #7735 is a duplicate of this one but has more information on where this new "+=" is allowed (not just maps - all collections and counters) and when it was introduced in Cassandra and how it can be tested, so I'm closing this one as a duplicate

**Closed by nyh** 2024-06-17 06:42 UTC
Labels: enhancement, user request, area/cql, area/cassandra 3.x compatibility, P3
