### ISSUE TITLE
Scylla segfaults in test_topology_ops in remove_node

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14102] opened 2023-05-31 12:18 UTC
Seen on aarch64 (release build), but I'm not sure if it's ARM specific, so I didn't mention that in the issue subject.

https://jenkins.scylladb.com/job/scylla-enterprise/job/build/896/artifact/testlog/aarch64/release/topology_experimental_raft.test_topology_ops.1.log
```
=================================== FAILURES ===================================
______________________________ test_topology_ops _______________________________

request = <FixtureRequest for <Function test_topology_ops>>
manager = <test.pylib.manager_client.ManagerClient object at 0xfffee5610c50>

    @pytest.mark.asyncio
    async def test_topology_ops(request, manager: ManagerClient):
        """Test basic topology operations using the topology coordinator."""
        logger.info("Bootstrapping cluster")
        servers = [await manager.server_add(), await manager.server_add(), await manager.server_add()]
    
        logger.info(f"Stopping node {servers[0]}")
        await manager.server_stop_gracefully(servers[0].server_id)
    
        logger.info(f"Replacing node {servers[0]}")
        replace_cfg = ReplaceConfig(replaced_id = servers[0].server_id, reuse_ip_addr = False, use_host_id = False)
        servers = servers[1:] + [await manager.server_add(replace_cfg)]
        await check_token_ring_and_group0_consistency(manager)
    
        logger.info(f"Stopping node {servers[0]}")
        await manager.server_stop_gracefully(servers[0].server_id)
    
        logger.info(f"Removing node {servers[0]} using {servers[1]}")
>       await manager.remove_node(servers[1].server_id, servers[0].server_id)

test/topology_experimental_raft/test_topology_ops.py:36: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/pylib/manager_client.py:190: in remove_node
    await self.client.put_json(f"/cluster/remove-node/{initiator_id}", data,
test/pylib/rest_client.py:104: in put_json
    ret = await self._fetch("PUT", resource_uri, response_type = response_type, host = host,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.pylib.rest_client.UnixRESTClient object at 0xffff897c8750>
method = 'PUT', resource = '/cluster/remove-node/209', response_type = None
host = None, port = None, params = None
json = {'ignore_dead': [], 'server_id': 207}, timeout = 1000

    async def _fetch(self, method: str, resource: str, response_type: Optional[str] = None,
                     host: Optional[str] = None, port: Optional[int] = None,
                     params: Optional[Mapping[str, str]] = None,
                     json: Optional[Mapping] = None, timeout: Optional[float] = None) -> Any:
        # Can raise exception. See https://docs.aiohttp.org/en/latest/web_exceptions.html
        assert method in ["GET", "POST", "PUT", "DELETE"], f"Invalid HTTP request method {method}"
        assert response_type is None or response_type in ["text", "json"], \
                f"Invalid response type requested {response_type} (expected 'text' or 'json')"
        # Build the URI
        port = port if port else self.default_port if hasattr(self, "default_port") else None
        port_str = f":{port}" if port else ""
        assert host is not None or hasattr(self, "default_host"), "_fetch: missing host for " \
                "{method} {resource}"
        host_str = host if host is not None else self.default_host
        uri = self.uri_scheme + "://" + host_str + port_str + resource
        logging.debug(f"RESTClient fetching {method} {uri}")
    
        client_timeout = ClientTimeout(total = timeout if timeout is not None else 300)
        async with request(method, uri,
                           connector = self.connector if hasattr(self, "connector") else None,
                           params = params, json = json, timeout = client_timeout) as resp:
            if resp.status != 200:
                text = await resp.text()
>               raise HTTPError(uri, resp.status, params, json, text)
E               test.pylib.rest_client.HTTPError: HTTP error 500, uri: http+unix://api/cluster/remove-node/209, params: None, json: {'server_id': 207, 'ignore_dead': []}, body:
E               Server disconnected
```

https://jenkins.scylladb.com/job/scylla-enterprise/job/build/896/artifact/testlog/aarch64/release/scylla-209.log
```
Scylla version 2023.2.0~dev-0.20230527.8ed2e63d56a6 with build-id c713381ee0acce852cb22e0465cb5880fbab7585 starting ...
...
INFO  2023-05-28 01:16:08,824 [shard 0] raft_group_registry - marking Raft server 4bd96f00-34a0-4021-8f04-e1fe335b4ecd as alive for raft groups
INFO  2023-05-28 01:16:09,139 [shard 1] compaction - [Compact system.peers 3a2a4830-fcf5-11ed-8ffd-976f4c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-89-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-87-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,140 [shard 0] compaction - [Compact system.peers 3a2a6f40-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-60-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-58-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,144 [shard 1] compaction - [Compact system.peers 3a2a4830-fcf5-11ed-8ffd-976f4c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-91-big-Data.db:level=0]. 13kB to 7kB (~55% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,147 [shard 0] compaction - [Compact system.peers 3a2a6f40-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-62-big-Data.db:level=0]. 14kB to 7kB (~51% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,147 [shard 0] compaction - [Compact system.local 3a2b80b0-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-16-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-14-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,148 [shard 1] compaction - [Compact system.peers 3a2ba7c0-fcf5-11ed-8ffd-976f4c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-93-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-91-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,152 [shard 1] compaction - [Compact system.peers 3a2ba7c0-fcf5-11ed-8ffd-976f4c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-95-big-Data.db:level=0]. 14kB to 7kB (~51% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,152 [shard 0] compaction - [Compact system.local 3a2b80b0-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-18-big-Data.db:level=0]. 14kB to 8kB (~54% of original) in 4ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,152 [shard 0] compaction - [Compact system.peers 3a2c4400-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-64-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-62-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,155 [shard 0] compaction - [Compact system.peers 3a2c4400-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-66-big-Data.db:level=0]. 13kB to 7kB (~55% of original) in 2ms = 3MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,169 [shard 0] compaction - [Compact system.peers 3a2edc10-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-68-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-66-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,169 [shard 1] compaction - [Compact system.peers 3a2edc10-fcf5-11ed-8ffd-976f4c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-97-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-95-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,173 [shard 1] compaction - [Compact system.peers 3a2edc10-fcf5-11ed-8ffd-976f4c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-99-big-Data.db:level=0]. 13kB to 7kB (~55% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,175 [shard 0] compaction - [Compact system.peers 3a2edc10-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-70-big-Data.db:level=0]. 14kB to 7kB (~51% of original) in 4ms = 1MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,175 [shard 0] compaction - [Compact system.local 3a2fc670-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-20-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-18-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,176 [shard 1] compaction - [Compact system.peers 3a2fed80-fcf5-11ed-8ffd-976f4c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-101-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-99-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,177 [shard 0] token_metadata - Added node 127.44.248.42 as pending replacing endpoint which replaces existing node 127.44.248.34
INFO  2023-05-28 01:16:09,181 [shard 0] compaction - [Compact system.local 3a2fc670-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-22-big-Data.db:level=0]. 14kB to 8kB (~54% of original) in 5ms = 1MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,181 [shard 1] compaction - [Compact system.peers 3a2fed80-fcf5-11ed-8ffd-976f4c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-103-big-Data.db:level=0]. 14kB to 7kB (~51% of original) in 4ms = 1MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,181 [shard 0] compaction - [Compact system.peers 3a30b0d0-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-72-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-70-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,185 [shard 0] compaction - [Compact system.peers 3a30b0d0-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-74-big-Data.db:level=0]. 13kB to 7kB (~55% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,406 [shard 0] compaction - [Compact system.scylla_local 3a5305e0-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-22-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-20-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,411 [shard 0] compaction - [Compact system.scylla_local 3a5305e0-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-24-big-Data.db:level=0]. 64kB to 59kB (~90% of original) in 4ms = 14MB/s. ~256 total partitions merged to 2.
INFO  2023-05-28 01:16:09,675 [shard 0] compaction - [Compact system.peers 3a7c11b0-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-76-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-74-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,676 [shard 1] compaction - [Compact system.peers 3a7c38c0-fcf5-11ed-8ffd-976f4c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-105-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-103-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,681 [shard 1] compaction - [Compact system.peers 3a7c38c0-fcf5-11ed-8ffd-976f4c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-107-big-Data.db:level=0]. 13kB to 7kB (~55% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,682 [shard 0] compaction - [Compact system.peers 3a7c11b0-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-78-big-Data.db:level=0]. 14kB to 7kB (~51% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,682 [shard 0] compaction - [Compact system.local 3a7d2320-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-24-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-22-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,683 [shard 1] compaction - [Compact system.peers 3a7d4a30-fcf5-11ed-8ffd-976f4c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-109-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-107-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,686 [shard 0] token_metadata - Added node 127.44.248.42 as pending replacing endpoint which replaces existing node 127.44.248.34
INFO  2023-05-28 01:16:09,687 [shard 1] compaction - [Compact system.peers 3a7d4a30-fcf5-11ed-8ffd-976f4c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-111-big-Data.db:level=0]. 14kB to 7kB (~51% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,691 [shard 0] compaction - [Compact system.local 3a7d2320-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-26-big-Data.db:level=0]. 14kB to 8kB (~54% of original) in 6ms = 1MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,691 [shard 0] compaction - [Compact system.peers 3a7e82b0-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-80-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-78-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,696 [shard 0] compaction - [Compact system.peers 3a7e82b0-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-82-big-Data.db:level=0]. 13kB to 7kB (~55% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,731 [shard 0] gossip - removed 127.44.248.34 from _seeds, updated _seeds list = {127.44.248.41}
INFO  2023-05-28 01:16:09,731 [shard 0] token_metadata - Removed node 127.44.248.42 as pending replacing endpoint which replaces existing node 127.44.248.34
INFO  2023-05-28 01:16:09,742 [shard 1] compaction - [Compact system.peers 3a864ae0-fcf5-11ed-8ffd-976f4c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-113-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-111-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,746 [shard 0] compaction - [Compact system.local 3a86e720-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-28-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-26-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,746 [shard 1] compaction - [Compact system.peers 3a864ae0-fcf5-11ed-8ffd-976f4c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-115-big-Data.db:level=0]. 13kB to 6kB (~46% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,752 [shard 0] compaction - [Compact system.local 3a86e720-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/local-7ad54392bcdd35a684174e047860b377/me-30-big-Data.db:level=0]. 14kB to 8kB (~54% of original) in 4ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,752 [shard 0] compaction - [Compact system.peers 3a87d180-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-84-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-82-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,753 [shard 1] compaction - [Compact system.peers 3a87f890-fcf5-11ed-8ffd-976f4c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-115-big-Data.db:level=0:origin=compaction,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-117-big-Data.db:level=0:origin=memtable]
INFO  2023-05-28 01:16:09,756 [shard 0] compaction - [Compact system.peers 3a87d180-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-88-big-Data.db:level=0]. 14kB to 7kB (~51% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:09,756 [shard 0] compaction - [Compact system.peers 3a886dc0-fcf5-11ed-954d-97704c0a5784] Compacting [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-86-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-88-big-Data.db:level=0:origin=compaction]
INFO  2023-05-28 01:16:09,759 [shard 1] compaction - [Compact system.peers 3a87f890-fcf5-11ed-8ffd-976f4c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-119-big-Data.db:level=0]. 13kB to 52kB (~399% of original) in 4ms = 13MB/s. ~256 total partitions merged to 2.
INFO  2023-05-28 01:16:09,760 [shard 0] compaction - [Compact system.peers 3a886dc0-fcf5-11ed-954d-97704c0a5784] Compacted 2 sstables to [/jenkins/workspace/scylla-enterprise/build/scylla/testlog/aarch64/release/scylla-209/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-90-big-Data.db:level=0]. 13kB to 7kB (~55% of original) in 3ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-28 01:16:10,029 [shard 0] gossip - Got shutdown message from 127.44.248.41, received_generation=1685236558, local_generation=1685236558
INFO  2023-05-28 01:16:10,030 [shard 0] gossip - InetAddress 127.44.248.41 is now DOWN, status = shutdown
INFO  2023-05-28 01:16:12,273 [shard 0] api - remove_node: host_id=6b28ddbc-c177-456a-99b7-1cab109fde82 ignore_nodes={}
INFO  2023-05-28 01:16:12,903 [shard 0] raft_group_registry - marking Raft server 6b28ddbc-c177-456a-99b7-1cab109fde82 as dead for raft groups
INFO  2023-05-28 01:16:14,307 [shard 0] storage_service - raft topology: request removenode for: 6b28ddbc-c177-456a-99b7-1cab109fde82
Segmentation fault on shard 0.
Backtrace:
  0x3882f13
  0x3873723
  0x389e13f
  0x22c59c7
  linux-vdso.so.1+0x7db
  0xe00000007ebf
------ Ending test release/topology_experimental_raft.test_topology_ops.1::test_topology_ops ------
```

Decoded:
```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar.lto/./seastar/include/seastar/util/backtrace.hh:60
seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar.lto/./seastar/src/core/reactor.cc:788
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar.lto/./seastar/src/core/reactor.cc:818
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar.lto/./seastar/src/core/reactor.cc:830
 (inlined by) seastar::sigsegv_action() at ./build/release/seastar.lto/./seastar/src/core/reactor.cc:3941
 (inlined by) operator() at ./build/release/seastar.lto/./seastar/src/core/reactor.cc:3922
 (inlined by) __invoke at ./build/release/seastar.lto/./seastar/src/core/reactor.cc:3918
wasmtime_runtime::traphandlers::unix::trap_handler at /jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-runtime-8.0.1/src/traphandlers/unix.rs:163
linux-vdso.so.1 0x7db 
?? ??:0
```

We don't save core dumps in ./test.py so there isn't one AFAIK.

**Comment by kbr-scylla** [comment] 2023-05-31 12:22
Reminds of https://github.com/scylladb/scylladb/issues/13707, also happened immediately after `raft topology: request removenode for`

**Comment by kbr-scylla** [comment] 2023-05-31 12:25
That one was fixed by replacing `fmt::format` with `seastar::format`, but since it now strikes again, the root cause might be elsewhere... I don't see any new `fmt::format`s introduced.
@avikivity suspected a miscompile on ARM.

**Comment by bhalevy** [comment] 2023-05-31 14:02
Could there be a relation to dynamically linking with seastar? (just throwing a wild guess with evidence)

**Comment by kostja** [comment] 2023-06-02 20:01
I am helpless with this one without frequency information. @bhalevy did you ever see it again?

**Comment by kbr-scylla** [comment] 2023-06-05 07:07
From today:
https://jenkins.scylladb.com/job/scylla-enterprise/job/build/904/artifact/testlog/aarch64/release/
https://jenkins.scylladb.com/job/scylla-enterprise/job/build/904/artifact/testlog/aarch64/release/scylla-221.log

**Comment by kbr-scylla** [comment] 2023-07-18 14:33
The last build where `test_topology_ops` failed in the scylla-enterprise job was 20 days ago:
https://jenkins.scylladb.com/job/scylla-enterprise/job/build/933/

Might be that the issue "resolved itself" (as a side effect of other fixes perhaps).
Closing for now -- if we observe this again, we can reopen.

**Closed by kbr-scylla** 2023-07-18 14:33 UTC
Labels: Master/Triage
