### ISSUE TITLE
test_schema_and_data_on_mixed_versions_cluster failed with 'Unable to complete the operation against any hosts'

### ISSUE THREAD

**Issue by Annamikhlin** [scylladb/scylladb#21704] opened 2024-11-27 12:17 UTC
`test_schema_and_data_on_mixed_versions_cluster` failed on all dtest: `dtest-release`, `test-with-gossip-topology-changes` and `dtest-release-with-raft` 
* https://jenkins.scylladb.com/job/scylla-master/job/dtest-release-with-raft/530/testReport/junit/mixed_version_test/TestSchemaChangesSchemaVersioningFrom52/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_schema_and_data_on_mixed_versions_cluster/

* https://jenkins.scylladb.com/job/scylla-master/job/dtest-with-gossip-topology-changes/142/testReport/junit/mixed_version_test/TestSchemaChangesSchemaVersioningFrom52/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_schema_and_data_on_mixed_versions_cluster/

with error:
```
self = <mixed_version_test.TestSchemaChangesSchemaVersioningFrom52 object at 0x7f46d54b0f20>
dtest_config = <dtest_config.DTestConfig object at 0x7f46c02090d0>

    @unmark.next_gating  # https://github.com/scylladb/scylla-enterprise/issues/3237
    def test_schema_and_data_on_mixed_versions_cluster(self, dtest_config):  # noqa: PLR0915
        """Check schema changes on a partly upgraded cluster.
    
        The test flow:
    
          1) Upgrade one of two nodes;
          2) Create a new keyspace and a new table on upgraded node;
          3) Check if it will be propagated to the old node;
          4) Do the same for ALTER TABLE, DROP TABLE and DROP KEYSPACE;
          5) Repeat 2-4 in the opposite direction: do a schema change on old version node and check it on upgraded.
        """
    
        self.clone_upgrade_path(dtest_config)
        self.init_cluster(nodes=2)
    
        node_for_upgrade = self.cluster.nodelist()[0]
        version = self.current_upgrade_path[0]
        logger.info("****** START UPGRADE TEST FROM %s TO %s ******", node_for_upgrade.node_scylla_version, version)
        logger.info(
            "Upgrade %s node to from '%s' to '%s' version",
            node_for_upgrade.name,
            node_for_upgrade.node_scylla_version,
            version,
        )
        node_for_upgrade.upgrade(upgrade_to_version=version)
        logger.info("****** FINISHED UPGRADE TO %s ******", version)
    
        node1: ScyllaNode = self.cluster.nodelist()[0]
        node2: ScyllaNode = self.cluster.nodelist()[1]
    
        logger.debug("Upgraded node: %s, not upgraded node: %s", node1.name, node2.name)
    
        assert node1.get_node_scylla_version() != node2.get_node_scylla_version(), f"Nodes have same version {node2.get_node_scylla_version()}"
    
        for schema_change_node, verification_node in ((node1, node2), (node2, node1)):
            logger.info("Do CREATE TABLE schema change on node %s", schema_change_node.name)
            with self.patient_exclusive_cql_connection(schema_change_node) as session:
                logger.debug("Creating keyspace and table on node %s", schema_change_node.name)
                session.execute(f"CREATE KEYSPACE {self.ks}" f" WITH replication={{'class': 'SimpleStrategy', 'replication_factor': '2'}}")
>               session.execute(f"CREATE TABLE {self.ks}.{self.cf} (a int primary key, b int)")

mixed_version_test.py:70: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cassandra/cluster.py:2729: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.70.1:9042 datacenter1>: ConnectionShutdown('Connection to 127.0.70.1:9042 is closed')})

cassandra/cluster.py:5120: NoHostAvailable
```

crash is:
```
INFO  2024-11-26 23:19:34,592 [shard 0: gms] schema_tables - Schema version changed to f40717eb-0f33-317c-b81d-f4ac6914061d
WARN  2024-11-26 23:19:34,592 [shard 0:stmt] create_keyspace - SimpleStrategy replication class is not recommended, but was used for keyspace test_upgrades. You may suppress this warning by delisting SimpleStrategy from replication_strategy_warn_list configuration option, or make it into an error by listing this replication strategy on replication_strategy_fail_list.
WARN  2024-11-26 23:19:34,592 [shard 0:stmt] create_keyspace - Using Replication Factor replication_factor=2 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
scylla: seastar/include/seastar/rpc/rpc_types.hh:109: T &seastar::rpc::client_info::retrieve_auxiliary(const sstring &) [T = const utils::tagged_uuid<locator::host_id_tag>]: Assertion `it != user_data.end()' failed.
Aborting on shard 0, in scheduling group statement.
Backtrace:
  0x5d92154
  0x5d4d38b
  0x5d85a68
  /jenkins/workspace/scylla-master/dtest-release-with-raft/scylla/.ccm/scylla-repository/1f5b83dc56f0f0f0d4c1c7c7c16044d0d534666c/libreloc/libc.so.6+0x40cff
  /jenkins/workspace/scylla-master/dtest-release-with-raft/scylla/.ccm/scylla-repository/1f5b83dc56f0f0f0d4c1c7c7c16044d0d534666c/libreloc/libc.so.6+0x99663
  /jenkins/workspace/scylla-master/dtest-release-with-raft/scylla/.ccm/scylla-repository/1f5b83dc56f0f0f0d4c1c7c7c16044d0d534666c/libreloc/libc.so.6+0x40c4d
  /jenkins/workspace/scylla-master/dtest-release-with-raft/scylla/.ccm/scylla-repository/1f5b83dc56f0f0f0d4c1c7c7c16044d0d534666c/libreloc/libc.so.6+0x28901
  /jenkins/workspace/scylla-master/dtest-release-with-raft/scylla/.ccm/scylla-repository/1f5b83dc56f0f0f0d4c1c7c7c16044d0d534666c/libreloc/libc.so.6+0x2881d
  /jenkins/workspace/scylla-master/dtest-release-with-raft/scylla/.ccm/scylla-repository/1f5b83dc56f0f0f0d4c1c7c7c16044d0d534666c/libreloc/libc.so.6+0x38d86
  0x2e9d6b2
  0x1897dec
  0x1896fc8
  0x189666f
  0x1893fca
  0x1893356
  0x623d171
  0x623cc91
  0x623d4e5
  0x5d5f57f
  0x5d60b1a
  0x5d61cf7
  0x5d610a8
  0x5cef2d3user_data.end()' failed.
  0x5cee633
  0x13e7e05
  0x13e97c0
  0x13e6223
  /jenkins/workspace/scylla-master/dtest-release-with-raft/scylla/.ccm/scylla-repository/1f5b83dc56f0f0f0d4c1c7c7c16044d0d534666c/libreloc/libc.so.6+0x2a087
  /jenkins/workspace/scylla-master/dtest-release-with-raft/scylla/.ccm/scylla-repository/1f5b83dc56f0f0f0d4c1c7c7c16044d0d534666c/libreloc/libc.so.6+0x2a14a
  0x13e38a4
```

full logs:
[dtest-gw12.log](https://github.com/user-attachments/files/17934069/dtest-gw12.log)
[1732662630123_mixed_version_test.py__TestSchemaChangesSchemaVersioningFrom52__test_schema_and_data_on_mixed_versions_cluster.zip](https://github.com/user-attachments/files/17934070/1732662630123_mixed_version_test.py__TestSchemaChangesSchemaVersioningFrom52__test_schema_and_data_on_mixed_versions_cluster.zip)

**Comment by kreuzerkrieg** [comment] 2024-11-28 10:43
checking

**Comment by yaronkaikov** [comment] 2024-12-02 08:40
Seen again https://jenkins.scylladb.com/job/scylla-master/job/dtest-release-with-raft/lastCompletedBuild/testReport/

 I did bisect using https://jenkins.scylladb.com/job/scylla-master/job/bisect/120/
here is the bisect log
```
git bisect start
# status: waiting for both good and bad commits
# good: [65949ce607805d11d3dc143ec2f0fddbae61370b] test: topology_custom: ensure node visibility before keyspace creation
git bisect good 65949ce607805d11d3dc143ec2f0fddbae61370b
# status: waiting for bad commit, 1 good commit known
# bad: [2b3115ac79c108f22c671944c199ab5e25ecf048] scylla-server.service: drop scylla-jmx.service
git bisect bad 2b3115ac79c108f22c671944c199ab5e25ecf048
# first bad commit: [2b3115ac79c108f22c671944c199ab5e25ecf048] scylla-server.service: drop scylla-jmx.service
# bad: [6c267bbc7056a20de119f22ec748c30b6b6f1612] test.py: Make it test/cqlpy python module
git bisect bad 6c267bbc7056a20de119f22ec748c30b6b6f1612
# good: [2b3115ac79c108f22c671944c199ab5e25ecf048] scylla-server.service: drop scylla-jmx.service
git bisect good 2b3115ac79c108f22c671944c199ab5e25ecf048
# first bad commit: [6c267bbc7056a20de119f22ec748c30b6b6f1612] test.py: Make it test/cqlpy python module
```
The failures are here - https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/758/, https://jenkins.scylladb.com/job/scylla-master/job/dtest-release-with-raft/534/ and https://jenkins.scylladb.com/job/scylla-master/job/dtest-with-gossip-topology-changes/146/

**Comment by yaronkaikov** [comment] 2024-12-02 08:41
@xtrey fyi

**Comment by gleb-cloudius** [comment] 2024-12-02 09:48
The problem is that 5.2 does not send host id and 6.3 now uses it unconditionally in migration manager verb. This was done by mistake during idl transition, but it will be mandatory in 6.3 anyway after the next set of patches will be in.

**Comment by kbr-scylla** [comment] 2024-12-02 09:50
> The problem is that 5.2 does not send host id and 6.3 now uses it unconditionally in migration manager verb. This was done by mistake during idl transition, but it will be mandatory in 6.3 anyway after the next set of patches will be in.

This could be a problem if we plan to support upgrade from 2023.1 to 2025.1. Hopefully we don't. @tzach ?

**Comment by gleb-cloudius** [comment] 2024-12-02 10:02
> > The problem is that 5.2 does not send host id and 6.3 now uses it unconditionally in migration manager verb. This was done by mistake during idl transition, but it will be mandatory in 6.3 anyway after the next set of patches will be in.
> 
> This could be a problem if we plan to support upgrade from 2023.1 to 2025.1. Hopefully we don't. [@tzach](https://github.com/tzach) ?

Me to, because otherwise moving to host ids in practically non viable. As an option we can introduce a patch that sends host id to 2023.1 and require one more step in the upgrade path.

**Comment by dani-tweig** [comment] 2024-12-02 12:30
> > The problem is that 5.2 does not send host id and 6.3 now uses it unconditionally in migration manager verb. This was done by mistake during idl transition, but it will be mandatory in 6.3 anyway after the next set of patches will be in.
> 
> This could be a problem if we plan to support upgrade from 2023.1 to 2025.1. Hopefully we don't. [@tzach](https://github.com/tzach) ?

We should support the following upgrade paths
2024.1 -> 2025.1 
2024.2 -> 2025.1 
6.2 -> 2025.1

**Comment by dani-tweig** [comment] 2024-12-02 12:34
> We should support the following upgrade paths
> 2024.1 -> 2025.1
> 2024.2 -> 2025.1
> 6.2 -> 2025.1

@kbr-scylla, so the test is problematic because it tries to upgrade from un-supported versions to 2025.1?

**Comment by kbr-scylla** [comment] 2024-12-03 11:22
From @gleb-cloudius 's description the test apparently upgrades from 5.2 directly to `master` (6.3).
That would correspond with 2023.1 (based on 5.2) to 2025.1 (based on 6.3 IIUC).
Which is not among the supported upgrade paths you listed.

Which means we should adjust the test to not skip so many versions. @temichus @aleksbykov can I assign this to you?

**Comment by lsfreitas** [comment] 2024-12-09 12:19
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/765/testReport/mixed_version_test/TestSchemaChangesSchemaVersioningFrom52/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_schema_and_data_on_mixed_versions_cluster/

**Comment by lsfreitas** [comment] 2024-12-11 10:11
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/767/testReport/mixed_version_test/TestSchemaChangesSchemaVersioningFrom52/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_schema_and_data_on_mixed_versions_cluster/

**Comment by lsfreitas** [comment] 2024-12-12 11:14
Seen again at: https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/768/testReport/mixed_version_test/TestSchemaChangesSchemaVersioningFrom52/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_schema_and_data_on_mixed_versions_cluster/

**Comment by lsfreitas** [comment] 2024-12-13 15:02
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/769/testReport/mixed_version_test/TestSchemaChangesSchemaVersioningFrom52/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_schema_and_data_on_mixed_versions_cluster/

**Comment by lsfreitas** [comment] 2024-12-14 19:54
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/770/testReport/mixed_version_test/TestSchemaChangesSchemaVersioningFrom52/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_schema_and_data_on_mixed_versions_cluster/

**Comment by mykaul** [comment] 2024-12-15 08:25
@temichus - please handle in higher priority.

**Comment by lsfreitas** [comment] 2024-12-16 11:14
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/771/testReport/mixed_version_test/TestSchemaChangesSchemaVersioningFrom52/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_schema_and_data_on_mixed_versions_cluster/

**Comment by mykaul** [comment] 2024-12-16 12:18
> From [@gleb-cloudius](https://github.com/gleb-cloudius) 's description the test apparently upgrades from 5.2 directly to `master` (6.3). That would correspond with 2023.1 (based on 5.2) to 2025.1 (based on 6.3 IIUC). Which is not among the supported upgrade paths you listed.
> 
> Which means we should adjust the test to not skip so many versions. [@temichus](https://github.com/temichus) [@aleksbykov](https://github.com/aleksbykov) can I assign this to you?

This is inaccurate, and I'd like to ensure we are on the same page:
OSS:
5.2 -> 5.4 -> 6.0 -> 6.1 -> 6.2 is a supported upgrade path
Enterprise:
2023.1 -> 2024.1 -> 2025.1 is a supported path
*but*, so is:
2023.1 -> 2025.1 direct upgrade! (which is different than either of the two above!)

So our upgrade matrix needs to test all of the above.
nit: you may need to be on the latest 5.2.x or 2023.1.x or whatever - but the latest patch release, before you upgrade. That's a reasonable requirement.

**Comment by aleksbykov** [comment] 2024-12-16 13:07
> _but_, so is:
> 2023.1 -> 2025.1 direct upgrade! (which is different than either of the two above!)

@mykaul , This is valid upgrade path, am i right? and it also have to be checked in mixed cluster

**Comment by mykaul** [comment] 2024-12-16 13:10
> > _but_, so is:
> > 2023.1 -> 2025.1 direct upgrade! (which is different than either of the two above!)
> 
> [@mykaul](https://github.com/mykaul) , This is valid upgrade path, am i right? and it also have to be checked in mixed cluster

Valid AND recommended!

**Comment by gleb-cloudius** [comment] 2024-12-16 13:18
> [@kbr-scylla](https://github.com/kbr-scylla) [@gleb-cloudius](https://github.com/gleb-cloudius) , according to your comments [#21704 (comment)](https://github.com/scylladb/scylladb/issues/21704#issuecomment-2511054508) and [#21704 (comment)](https://github.com/scylladb/scylladb/issues/21704#issuecomment-2511083509), then we need have some patch to run upgrade from 2023.1 -> 2025.1?

https://github.com/scylladb/scylla-enterprise/pull/5075

**Comment by lsfreitas** [comment] 2024-12-18 11:04
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/773/testReport/mixed_version_test/TestSchemaChangesSchemaVersioningFrom52/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_schema_and_data_on_mixed_versions_cluster/

**Closed** 2024-12-18 16:51 UTC
Labels: area/test, triage/master, P1
