### ISSUE TITLE
[6.1] test_index_is_cached_in_big_partition_workload failed with cache misses mismatch error

### ISSUE THREAD

**Issue by AbhinavKumarJha** [scylladb/scylladb#21938] opened 2024-12-16 10:08 UTC
https://jenkins.scylladb.com/job/scylla-6.1/job/scylla-ci/194/testReport/junit/boost/cache_algorithm_test/test_index_is_cached_in_big_partition_workload/

Stacktrace
```
[Exception] - critical check get_misses() == misses_before has failed [50 != 49]
 == [File] - test/boost/cache_algorithm_test.cc
 == [Line] -179
```
Standard Output
```
[Info] - 3 out of 6 times failed.
 == [File] - test/boost/cache_algorithm_test.cc
 == [Line] - 122

[Info] - passed: release=3
 == [File] - test/boost/cache_algorithm_test.cc
 == [Line] - 122

[Info] - failed: dev=3
 == [File] - test/boost/cache_algorithm_test.cc
 == [Line] - 122
```

**Comment by kbr-scylla** [comment] 2024-12-16 10:13
@bhalevy looks related to cache in storage -- who would be appropriate for triage?

**Comment by bhalevy** [comment] 2024-12-16 11:22
@michoecho please look into this
Cc @paszkow

**Comment by michoecho** [comment] 2024-12-16 16:00
Closing as a duplicate of https://github.com/scylladb/scylladb/issues/21536.

**Closed by michoecho** 2024-12-16 16:00 UTC
Labels: tests/unitest, triage/oss, tests/flaky
