### ISSUE TITLE
SSTable index cache steals too much memory from row cache

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#11202] opened 2022-08-03 10:35 UTC
Scylla 4.6 introduced the caching of index entries (9f957f1cf99a1d75104e48c21f8cff67b9867070) and index file page caching (078a6e422b96c7d2cca04c8cbe539ff6a572b95c) in the common global LRU cache, in which also rows are placed.

On row cache miss, when the index is read, the loaded pages and parsed entries are stored in the cache for later reuse.

AFAIK, index caching is needed mainly to avoid repeated I/O when the index fragment is read repeatedly in a quick succession (for example, during the last few steps of a binary search through the promoted index).
However, since those changes, the index cache survives in memory much longer, stealing some space from rows.

Since the index on disk is orders of magnitude smaller than data, it's intuitive to assume that this will also be the case in cache, and rows won't lose much space. However, that is a gross underestimation, because the index is cached with page and segment (the range between subsequent summary entries) granularity. In the worst case, when the accessed rows are sparse within the index, each row cache miss incurs a load of a whole separate index page and index segment.

This can induce a feedback loop behaviour. The load of an index page and segment may evict multiple rows. If they are later reaccessed, they too will be brought back into the cache with their surrounding index, evicting more rows, and so on, until almost every row in cache (except the most popular ones, which stay in the cache indefinitely) is accompanied by its surrounding index.

The effect will vary with index density, row sizes, access probability distribution, and sparsity of the distribution within the index. Workloads with very skewed distributions or with dense distribution of cache rows within the index are weakly affected. Workloads with flat distributions may have their hit rate reduced by a factor of up to (average index cache entry footprint / average row cache entry footprint). In a standard cassandra-stress test with a flat distrubution and sparse accesses, it was seen to decrease hit rates by a factor of ~16x.

To prevents this, our cache eviction policy should evict index entries much more aggressively.

**Comment by bhalevy** [comment] 2022-08-03 10:44
Cc @tgrabiec

**Comment by racevedoo** [comment] 2022-08-05 16:18
I can confirm that for some of our workloads, upgrading from 4.5 to 4.6 makes the cache hit ratio decrease significantly, causing performance problems. We'll try to provide more details soon, but this seems pretty important to me.

**Comment by slivne** [comment] 2022-08-11 07:59
thanks @racevedoo for the update we looked for OSS users to confirm this - do you have screenshots showing this - just so we will have some user workload to explain this.

**Comment by slivne** [comment] 2022-08-11 08:02
/cc @avikivity - lets decide on the roll out of the fix:
- as a first step think we need a way to disable this - and backport it, in my view we can either add a table property (in schema) that will allow to disable this / add a flag that will allow to disable this completly per node
- the "real fix" needs to be more complex to evaluate if n indexpage should be cached / what we should prefer to evict.

**Comment by slivne** [comment] 2022-08-11 08:03
@avikivity assigned this to you - to provide the first step afterwords will reassign to someone that will actually do the work.

**Comment by avikivity** [comment] 2022-08-11 08:33
I think in easy first step is a kill switch. That will be a regression compared to 4.5 since 4.5 shared index reads for the two bounds of a query, but this won't.

A second step will be to have a separate LRU (cache_tracker?) for index, and limit the size of that LRU to just 5% of memory.

A third step is size-aware, frequency-aware eviction algorithm.

**Comment by slivne** [comment] 2022-08-11 08:38
@bhalevy reassigning to you to schedule - please note this is a regression.

**Comment by racevedoo** [comment] 2022-08-11 11:13
> thanks @racevedoo for the update we looked for OSS users to confirm this - do you have screenshots showing this - just so we will have some user workload to explain this.

sure! here are the ones I could come up with:
- From the grafana "cache" section:
![image](https://user-images.githubusercontent.com/5193063/184119945-207d5b76-25c3-49a6-a42f-24e3c18dcc04.png)
![image](https://user-images.githubusercontent.com/5193063/184120167-344fcc1c-2785-42a6-999f-8414114baaa6.png)

Note that the amount of reads with no misses drops substantially, while the total number of reads is basically the same (we had to add another node to the cluster to avoid more problems - the yellow line in the graphs):
![image](https://user-images.githubusercontent.com/5193063/184120413-f9ead228-932a-4fb8-9c2a-95b1ce67c912.png)

The p99 read latency also increases a lot after the upgrade (the upgrade happened at about 17:47 on 2022-07-27):
![image](https://user-images.githubusercontent.com/5193063/184120809-94199b63-eb0e-4612-a15f-e1e789e4a2ea.png)


Please tell me if you'd like any additional screenshots :smile:

**Comment by laurovenancio** [comment] 2022-08-11 15:01
Just providing some more details about the performance regression @racevedoo mentioned.

We've updated two production clusters from scylla 4.5 to 4.6. Both experienced performance regressions. For instance, in the first cluster:
CPU: ~3% -> 7%
Read latency p99: ~1.25ms -> - 2.3ms
Cached Rows: 10M -> 100k

There was also an increase in the backgroud_reclaim scheduling group cpu consumption (~0.4ms -> ~20ms).

Both clusters have a very simple schema: just one table with two columns (a partition key and a value) without clustering key.

It seems to me that the partition index is not very useful when there is no clustering key. Maybe it should not be cached in this case.

**Comment by tgrabiec** [comment] 2022-08-12 12:23
> It seems to me that the partition index is not very useful when there is no clustering key. Maybe it should not be cached in this case.

Why do you think so?

**Comment by avikivity** [comment] 2022-08-14 10:25
It depends on the branching factor (ratio of row size to key size) and workload.

High branching factor and/or wide key read distribution: row cache is less effective, index cache is more effective, index cache saves one I/O on every miss (and misses are prevalent).

Low branching factor and/or narrow read key distribution: row cache is more effective, index cache is sparse and therefore less effective, index cache competes with row cache for memory without being very effective.

**Comment by racevedoo** [comment] 2022-08-15 13:35
> I think in easy first step is a kill switch. That will be a regression compared to 4.5 since 4.5 shared index reads for the two bounds of a query, but this won't. But it's very easy to implement and provides relief to those suffering from the regression.

I guess the kill switch is indeed a good idea for a quick fix

**Comment by laurovenancio** [comment] 2022-08-15 14:11
> > It seems to me that the partition index is not very useful when there is no clustering key. Maybe it should not be cached in this case.
> 
> Why do you think so?

Actually, this is wrong. I misunderstood the partition index purpose. I thought it was an index of rows inside a partition.

**Comment by slivne** [comment] 2022-08-22 11:14
@bhalevy we may need to reassign this to someone else to provide the simple flag to disable ...

**Comment by bhalevy** [comment] 2022-08-26 12:38
@tgrabiec How difficult would it be to enable/disable it per table? Or would a global config flag would be more practical?

**Comment by michoecho** [comment] 2022-09-07 02:35
Posted an `index_reader`-level fix proposition (or rather two propositions) at #11474. @avikivity @tgrabiec Take a look and say what you think about that direction.
I'll follow the other (cache-level) direction too. I'm not sure which of the two (if any) is more appropriate for backporting.

**Closed** 2022-09-15 23:04 UTC
Labels: performance, User Request, Regression, master/high

**Comment by avikivity** [comment] 2022-09-18 10:31
Backported the flag to 4.6, 5.0, 5.1.
