### ISSUE TITLE
boost.tablets_test.test_read_required_hosts fails without force-gossip-topology-changes

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#18463] opened 2024-04-29 14:11 UTC
After merging #18285, the raft-based topology became the default for new clusters. As a consequence, all boost unit tests started using the raft-based topology by default. Then, `tablets_test.test_read_required_hosts` started failing. Before #18285, `tablet_cql_test_config` in `tablets_test.cc` incorrectly didn't use `consistent-topology-changes`. So, all test cases in `tablets_test.cc` ran with the gossip-based topology.

We didn't want to block #18285, so we decided to keep running this test case with the gossip-based topology (the new way is using `force-gossip-topology-changes`) and left a FIXME:
```
// FIXME: the test fails without using force_gossip_topology_changes.
// Fix the test and remove force_gossip_topology_changes from config.
```

The test case fails on `auto table2 = add_table(e).get();` with
```
ERROR 2024-04-17 11:14:16,083 [shard 0:main] load_balancer -
Replica 9b94d710-fbfb-11ee-9c4f-448617b47e11:0 of tablet
9b94d713-fbfb-11ee-9c4f-448617b47e11:0 not found in topology
```
It should be further investigated and fixed.

This patch left the FIXME: 88038d958a1d22c2d6a8d0395072dd02b91382bd

Relevant discussion: https://github.com/scylladb/scylladb/pull/18285#discussion_r1568985497

**Comment by mykaul** [comment] 2024-09-22 14:39
@patjed41 - is this still relevant? Who should be assigned to it?

**Closed** 2024-10-11 22:17 UTC
Labels: tests/unitest, P3, area/tablets, backport/none

**Comment by nodep** [comment] 2024-10-15 08:34
The cause for why this test was failing is described in: #20960
