### ISSUE TITLE
docs: Issue on page Backup your Data - need to use Describe Schema with Internals

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#18930] opened 2024-05-28 09:11 UTC
I would like to report an issue on page https://opensource.docs.scylladb.com/master/operating-scylla/procedures/backup-restore/backup

### Problem

The backup does not relflect the new DESCRIBE SCHEMA WITH INTERNALS 
https://github.com/scylladb/scylladb/issues/16482

###  Suggest a fix

Use DESCRIBE SCHEMA WITH INTERNALS

**Comment by Michal-Leszczynski** [comment] 2024-05-28 14:52
@tzach, was @Jadw1 supposed to be assigned to this issue?

**Comment by tzach** [comment] 2024-05-28 17:34
@Michal-Leszczynski you open the original issue #16482  so I assumed you can review.
If other Michals can help - I'm all for it :)

**Comment by piodul** [comment] 2024-05-29 06:12
This is a duplicate of https://github.com/scylladb/scylladb/issues/18456

**Closed by piodul** 2024-05-29 06:12 UTC
Labels: documentation
