### ISSUE TITLE
dependency for dev-disk-cloud-azure_resource-part1.device is ignored warning on Azure

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#11136] opened 2022-07-27 12:37 UTC
## Installation details

Kernel Version: 5.15.0-1014-azure
Scylla version (or git commit hash): `5.1.0~dev-20220726.29c28dcb0c33` with build-id `f0f40bc93cc45be63928bbe9eaf674885347ba58`
Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-e9a355e3-eastus-7 (20.121.24.166 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-e9a355e3-eastus-6 (40.76.90.127 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-e9a355e3-eastus-5 (52.255.176.181 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-e9a355e3-eastus-4 (40.76.89.131 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-e9a355e3-eastus-3 (13.92.43.111 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-e9a355e3-eastus-2 (40.76.86.43 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-e9a355e3-eastus-1 (52.188.62.229 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/ScyllaDB-5.1.0.dev-0.20220726.29c28dcb0c33-1-build-208` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `e9a355e3-2bf7-401d-8b06-1dd5388380c3`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1398b900874f8b9660d7c7b692d5a0a455b25466/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description
When reloading systemd on Azure with Scylla installed, we can see warnings:
```
2022-07-26T11:22:04+00:00 longevity-10gb-3h-master-db-node-eastus-1     !INFO | systemd[1]: Reloading.
2022-07-26T11:22:04+00:00 longevity-10gb-3h-master-db-node-eastus-1  !WARNING | systemd[1]: dev-disk-cloud-azure_resource\x2dpart1.device: Requested dependency After=network-online.target ignored (device units cannot be delayed).
2022-07-26T11:22:04+00:00 longevity-10gb-3h-master-db-node-eastus-1  !WARNING | systemd[1]: dev-disk-cloud-azure_resource\x2dpart1.device: Requested dependency After=network.target ignored (device units cannot be delayed).
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor e9a355e3-2bf7-401d-8b06-1dd5388380c3`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e9a355e3-2bf7-401d-8b06-1dd5388380c3)
- Show all stored logs command: `$ hydra investigate show-logs e9a355e3-2bf7-401d-8b06-1dd5388380c3`

## Logs:
- **db-cluster-e9a355e3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9a355e3-2bf7-401d-8b06-1dd5388380c3/20220726_155943/db-cluster-e9a355e3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9a355e3-2bf7-401d-8b06-1dd5388380c3/20220726_155943/db-cluster-e9a355e3.tar.gz)
- **monitor-set-e9a355e3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9a355e3-2bf7-401d-8b06-1dd5388380c3/20220726_155943/monitor-set-e9a355e3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9a355e3-2bf7-401d-8b06-1dd5388380c3/20220726_155943/monitor-set-e9a355e3.tar.gz)
- **loader-set-e9a355e3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9a355e3-2bf7-401d-8b06-1dd5388380c3/20220726_155943/loader-set-e9a355e3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9a355e3-2bf7-401d-8b06-1dd5388380c3/20220726_155943/loader-set-e9a355e3.tar.gz)
- **sct-runner-e9a355e3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9a355e3-2bf7-401d-8b06-1dd5388380c3/20220726_155943/sct-runner-e9a355e3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9a355e3-2bf7-401d-8b06-1dd5388380c3/20220726_155943/sct-runner-e9a355e3.tar.gz)
- **parallel-timelines-report-e9a355e3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9a355e3-2bf7-401d-8b06-1dd5388380c3/20220726_155943/parallel-timelines-report-e9a355e3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9a355e3-2bf7-401d-8b06-1dd5388380c3/20220726_155943/parallel-timelines-report-e9a355e3.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/58/)

**Comment by syuu1228** [comment] 2022-08-12 06:15
I'm not sure it is caused by scylla or not, but i will take a look anyway

**Comment by syuu1228** [comment] 2022-08-15 08:42
@soyacz /dev/disk/cloud/azure_resource-part1 is "Temporary/Resource Disk", which is pre-configured Azure official Ubuntu distro images, we don't change setting.
It's done in /etc/fstab:
```
$ cat /etc/fstab 
# CLOUD_IMG: This file was created/modified by the Cloud Image build process
UUID=b201084f-154f-4029-a5b8-f903ac9fc29b	/	 ext4	defaults,discard0 1
UUID=8FF9-31A2	/boot/efi	vfat	umask=0077	0 1
/dev/disk/cloud/azure_resource-part1	/mnt	auto	defaults,nofail,x-systemd.requires=cloud-init.service,_netdev,comment=cloudconfig	0	2
```

**Comment by syuu1228** [comment] 2022-08-15 08:43
So I think we can ignore the warning message.

**Comment by syuu1228** [comment] 2023-10-20 00:45
Seems like this is systemd issue occuring when "_netdev" is specified on mount option.
reference: https://bugzilla.redhat.com/show_bug.cgi?id=2043524
And /dev/disk/cloud/azure_resource-part1 is specifies "_netdev":
```
$ grep azure_resource /etc/fstab 
/dev/disk/cloud/azure_resource-part1    /mnt    auto    defaults,nofail,x-systemd.requires=cloud-init.service,_netdev,comment=cloudconfig       0       2
```

But it isn't caused by our configuration, it also occurs on Ubuntu 22.04 image, so likely it's default behavor of Azure official image.
And since it's Azure specific configuration done by waagent(Azure linux agent), it's safer to not modify the configuration.
Also it's just a warning message, doesn't cause any error from this so we can ignore.

Closing.

**Closed by syuu1228** 2023-10-20 00:45 UTC
Labels: bug, Azure
