### ISSUE TITLE
test_simple_removenode_4 dtest timed out in debug mode -- removenode request hangs, topology coordinator stuck in finite tablet migrations loop

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#20634] opened 2024-09-17 07:43 UTC
I'm filing this issue against scylla and not against dtest since it seems like the test hit some internal issues in scylla.

Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/320/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split027___test_simple_removenode_4/
```
self = <update_cluster_layout_tests.TestUpdateClusterLayout object at 0x7fb67a5db8f0>

    def test_simple_removenode_4(self):
        logger.debug("Test kill removenode coordinator node in the middle")
>       self._do_simple_removenode(to_kill_coordinator=True)

update_cluster_layout_tests.py:1683: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
update_cluster_layout_tests.py:1663: in _do_simple_removenode
    node1.removenode(node2_hostid)
../scylla/.local/lib/python3.12/site-packages/ccmlib/node.py:1464: in removenode
    self.nodetool("removenode " + str(hid))
../scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py:798: in nodetool
    return self._do_run_nodetool(nodetool, capture_output, wait, timeout, verbose)
../scylla/.local/lib/python3.12/site-packages/ccmlib/node.py:820: in _do_run_nodetool
    stdout, stderr = p.communicate(timeout=timeout)
/usr/local/lib/python3.12/subprocess.py:1209: in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
/usr/local/lib/python3.12/subprocess.py:2115: in _communicate
    ready = selector.select(timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selectors.PollSelector object at 0x7fb678b926c0>, timeout = None

    def select(self, timeout=None):
        # This is shared between poll() and epoll().
        # epoll() has a different signature and handling of timeout parameter.
        if timeout is None:
            timeout = None
        elif timeout <= 0:
            timeout = 0
        else:
            # poll() has a resolution of 1 millisecond, round away from
            # zero to wait *at least* timeout seconds.
            timeout = math.ceil(timeout * 1e3)
        ready = []
        try:
>           fd_event_list = self._selector.poll(timeout)
E           Failed: Timeout >7200s
```

https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/320/artifact/logs-full.debug.027/1726495107371_update_cluster_layout_tests.py%3A%3ATestUpdateClusterLayout%3A%3Atest_simple_removenode_4/node1.log
```
INFO  2024-09-16 12:04:00,486 [shard 0:strm] api - remove_node: host_id=e9eec7b7-73e2-40e3-a2f1-de25d422561e ignore_nodes=[]
INFO  2024-09-16 12:04:00,490 [shard 0:strm] raft_topology - request removenode for: e9eec7b7-73e2-40e3-a2f1-de25d422561e, new ignored nodes: {e9eec7b7-73e2-40e3-a2f1-de25d422561e}, existing ignore nodes: {e9eec7b7-73e2-40e3-a2f1-de25d422561e}
INFO  2024-09-16 12:04:00,491 [shard 0:strm] raft_group0 - making servers {e9eec7b7-73e2-40e3-a2f1-de25d422561e} non-voters...
INFO  2024-09-16 12:04:00,492 [shard 0:strm] raft_group0 - servers {e9eec7b7-73e2-40e3-a2f1-de25d422561e} are now non-voters.
INFO  2024-09-16 12:04:00,726 [shard 0:strm] raft_topology - removenode: waiting for completion (request ID: c2569d20-7423-11ef-6154-bf7670dd2b7d)
INFO  2024-09-16 13:58:23,333 [shard 0:main] compaction_manager - Asked to stop
```

https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/320/artifact/logs-full.debug.027/1726495107371_update_cluster_layout_tests.py%3A%3ATestUpdateClusterLayout%3A%3Atest_simple_removenode_4/node2.log
```
WARN  2024-09-16 12:04:00,024 [shard 0:strm] raft_group_registry - group [fae3adf0-7422-11ef-b9e7-2fde4a24b169] raft operation [read_barrier] timed out, there is no raft quorum, total voters count 5, alive voters count 1, dead voters [127.0.83.5,127.0.83.3,127.0.83.4,127.0.83.1]; timeout requested at [service/storage_service.cc(4719:90) `future<> service::storage_service::raft_rebuild(utils::optional_param)`], original error raft::request_aborted (Aborted while waiting for next tick on server: e9eec7b7-73e2-40e3-a2f1-de25d422561e, latest applied entry: 71)
```

I don't know why there's only 1 alive voter.

At any right, the above seems more series than a plain WARNing, and if it causes the api call to hang, it should be propagated to the coordinator and fail removenode.

https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/320/artifact/logs-full.debug.027/1726495107371_update_cluster_layout_tests.py%3A%3ATestUpdateClusterLayout%3A%3Atest_simple_removenode_4/node4.log
```
WARN  2024-09-16 12:04:00,491 [shard 0:strm] raft - [ae8176b0-e428-49bf-bb7e-0fe12407d621] the server e9eec7b7-73e2-40e3-a2f1-de25d422561e already exists in configuration as non-voter
```

[logs.zip](https://github.com/user-attachments/files/17024545/logs.zip)

**Comment by bhalevy** [comment] 2024-09-17 07:43
Cc @kbr-scylla

**Comment by mykaul** [comment] 2024-09-19 10:43
Dup of https://github.com/scylladb/scylla-dtest/issues/4845 ?

**Comment by bhalevy** [comment] 2024-09-19 11:10
> Dup of [scylladb/scylla-dtest#4845](https://github.com/scylladb/scylla-dtest/issues/4845) ?

Looks like it, but I suspect the issue is on the scylla side

**Comment by yaronkaikov** [comment] 2024-09-23 06:55
@bhalevy it seems that this test failed again during https://jenkins.scylladb.com/job/scylla-6.1/job/next/100/, unsure if it's the same issue. can you verify?

**Comment by bhalevy** [comment] 2024-09-23 11:26
> @bhalevy it seems that this test failed again during [jenkins.scylladb.com/job/scylla-6.1/job/next/100](https://jenkins.scylladb.com/job/scylla-6.1/job/next/100/), unsure if it's the same issue. can you verify?

No, it seems like a different issue.

https://jenkins.scylladb.com/job/scylla-6.1/job/next/100/artifact/dtest/logs-full.release.006/dtest-gw3.log
```
21:58:02,975 723     errors                         ERROR    conftest.py         :203  | test_simple_removenode_4: test failed: 
self = <update_cluster_layout_tests.TestUpdateClusterLayout object at 0x7f28575cd820>

    def test_simple_removenode_4(self):
        logger.debug("Test kill removenode coordinator node in the middle")
>       self._do_simple_removenode(to_kill_coordinator=True)

update_cluster_layout_tests.py:1617: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
update_cluster_layout_tests.py:1604: in _do_simple_removenode
    node2.start(wait_other_notice=True)
../scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py:708: in start
    scylla_process = self._start_scylla(args=args, marks=marks, update_pid=update_pid,
../scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py:351: in _start_scylla
    self.wait_for_binary_interface(from_mark=from_mark, process=self._process_scylla, timeout=t)
../scylla/.local/lib/python3.12/site-packages/ccmlib/node.py:541: in wait_for_binary_interface
    self.watch_log_for("Starting listening for CQL clients", **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ccmlib.scylla_node.ScyllaNode object at 0x7f2854563710>
exprs = 'Starting listening for CQL clients', from_mark = 242017, timeout = 420
process = <Popen: returncode: 1 args: ['/jenkins/workspace/scylla-6.1/gating-dtest-rel...>
verbose = False, filename = 'system.log', polling_interval = 0.01

    def watch_log_for(self, exprs, from_mark=None, timeout=600, process=None, verbose=False, filename='system.log', polling_interval=0.01):
        """
        Watch the log until all (regular) expression are found or the timeout is reached.
        On successful completion, a list of pairs (line matched, match object) is returned.
        If the timeout expired before matching all expressions in `exprs`,
        a TimeoutError is raised.
        The `polling_interval` determines how long we sleep when
        reaching the end of file before attempting to read the next line.
        """
        deadline = time.time() + timeout
        tofind = [exprs] if isinstance(exprs, str) else exprs
        tofind = [re.compile(e) for e in tofind]
        matchings = []
        reads = ""
        if len(tofind) == 0:
            return None
    
        log_file = os.path.join(self.get_path(), 'logs', filename)
        while not os.path.exists(log_file):
            time.sleep(.1)
            if process:
                process.poll()
                if process.returncode is not None:
                    self.print_process_output(self.name, process, verbose)
                    if process.returncode != 0:
                        raise RuntimeError()  # Shouldn't reuse RuntimeError but I'm lazy
    
        with open(log_file) as f:
            if from_mark:
                f.seek(from_mark)
    
            while True:
                # First, if we have a process to check, then check it.
                # Skip on Windows - stdout/stderr is cassandra.bat
                if not common.is_win():
                    if process:
                        process.poll()
                        if process.returncode is not None:
                            self.print_process_output(self.name, process, verbose)
                            if process.returncode != 0:
                                raise RuntimeError()  # Shouldn't reuse RuntimeError but I'm lazy
    
                line = f.readline()
                if line:
                    reads = reads + line
                    for e in tofind:
                        m = e.search(line)
                        if m:
                            matchings.append((line, m))
    
                            # This is bogus! - One should not modify the list from inside the loop which iterates on
                            # that list.
                            # However since we are going to break from the loop a few lines below that should be ok.
                            tofind.remove(e)
    
                            if len(tofind) == 0:
                                return matchings[0] if isinstance(exprs, str) else matchings
                            break
                else:
                    # yep, it's ugly
                    # FIXME: consider using inotify with IN_MODIFY to monitor the file
                    time.sleep(polling_interval)
                    if time.time() > deadline:
                        raise TimeoutError(time.strftime("%d %b %Y %H:%M:%S", time.gmtime()) + " [" + self.name + "] Missing: " + str(
                            [e.pattern for e in tofind]) + ":\n" + reads[:50] + f".....\nSee {filename} for remainder")
    
                if process:
                    if common.is_win():
                        if not self.is_running():
                            return None
                    else:
                        process.poll()
                        if process.returncode is not None:
                            if process.returncode == 0:
                                return None
                            else:
>                               raise RuntimeError(f"The process is dead, returncode={process.returncode}")
E                               RuntimeError: The process is dead, returncode=1
...
21:58:06,103 723     dtest_setup                    ERROR    dtest_setup.py      :637  | test_simple_removenode_4: Unexpected errors found: [('node2', ['ERROR 2024-09-22 21:58:02,688 [shard 0:main] init - Startup failed: raft::commit_status_unknown (Commit status of the entry is unknown)'])]
```

https://jenkins.scylladb.com/job/scylla-6.1/job/next/100/artifact/dtest/logs-full.release.006/1727042286103_update_cluster_layout_tests.py%3A%3ATestUpdateClusterLayout%3A%3Atest_simple_removenode_4/node2.log
```
INFO  2024-09-22 21:57:59,673 [shard 0:strm] storage_service - entering NORMAL mode
INFO  2024-09-22 21:57:59,673 [shard 0:strm] raft_group0 - finish_setup_after_join: group 0 ID present, loading server info.
INFO  2024-09-22 21:57:59,673 [shard 0:strm] raft_group0 - finish_setup_after_join: becoming a voter in the group 0 configuration...
INFO  2024-09-22 21:57:59,673 [shard 0:main] init - Shutting down group 0 usage in local storage
...
ERROR 2024-09-22 21:58:02,688 [shard 0:main] init - Startup failed: raft::commit_status_unknown (Commit status of the entry is unknown)
```

@kbr-scylla is this https://github.com/scylladb/scylladb/issues/10695?

**Comment by kbr-scylla** [comment] 2024-09-23 11:31
`commit_status_unknown` shouldn't leak into the user interface, I believe. https://github.com/scylladb/scylladb/issues/10695 is about reducing its frequency in some cases, but even if it happens, we should handle it internally.

**Comment by bhalevy** [comment] 2024-09-23 11:37
Hit again in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/320/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split027___test_simple_removenode_4/
```
12:02:21,040 685     update_cluster_layout_tests    DEBUG    update_cluster_layout_tests.py:1600 | test_simple_removenode_4: Send restful api: http://127.0.83.1:10000/storage_service/remove_node/?host_id=e9eec7b7-73e2-40e3-a2f1-de25d422561e
...
12:02:33,762 685     update_cluster_layout_tests    DEBUG    update_cluster_layout_tests.py:1587 | test_simple_removenode_4: Stop node1 gently=False
...
12:02:44,771 685     update_cluster_layout_tests    INFO     update_cluster_layout_tests.py:1650 | test_simple_removenode_4: Start node1
...
12:02:54,832 685     ccm                            INFO     cluster.py          :757  | test_simple_removenode_4: node1: Started scylla: pid: 3859
12:02:54,858 685     ccm                            DEBUG    cluster.py          :754  | test_simple_removenode_4: node2: Starting scylla: args=['/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node2/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node2/conf/scylla.yaml', '--log-to-stdout', '1', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--api-address', '127.0.83.2', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--blocked-reactor-notify-ms', '5000', '--overprovisioned', '--prometheus-address', '127.0.83.2', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=False wait_for_binary_proto=True
...
12:02:59,835 685     ccm                            DEBUG    cluster.py          :754  | test_simple_removenode_4: node2: nodetool cmd=['/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node2/bin/scylla', 'nodetool', '-h', '127.0.83.2', '-p', '10000', 'rebuild'] wait=True timeout=None
...
12:04:00,325 685     ccm                            DEBUG    cluster.py          :754  | test_simple_removenode_4: node1: nodetool cmd=['/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/bin/scylla', 'nodetool', '-h', '127.0.83.1', '-p', '10000', 'removenode', 'e9eec7b7-73e2-40e3-a2f1-de25d422561e'] wait=True timeout=None
13:58:23,330 685     errors                         ERROR    conftest.py         :212  | test_simple_removenode_4: test failed: 
```

https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/320/artifact/logs-full.debug.027/1726495107371_update_cluster_layout_tests.py%3A%3ATestUpdateClusterLayout%3A%3Atest_simple_removenode_4/node1.log
```
INFO  2024-09-16 12:02:21,235 [shard 0:strm] raft_topology - removenode: waiting for completion (request ID: 87107e84-7423-11ef-bfd5-7cde1b86de31)
INFO  2024-09-16 12:02:21,238 [shard 0: gms] raft_topology - updating topology state: Starting cleanup
INFO  2024-09-16 12:02:21,403 [shard 0:strm] raft_topology - start cleanup
INFO  2024-09-16 12:02:21,403 [shard 0:strm] database - Forcing new commitlog segment and flushing all tables
INFO  2024-09-16 12:02:21,403 [shard 1:strm] database - Forcing new commitlog segment and flushing all tables
...
INFO  2024-09-16 12:02:22,685 [shard 0:strm] raft_topology - cleanup ended
INFO  2024-09-16 12:02:22,894 [shard 0:comp] compaction - [Compact system.compaction_history 87f3bd70-7423-11ef-b9e7-2fde4a24b169] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/me-3gjl_0xfy_37qo02trvpcpkxdfmx-big-Data.db:level=0]. 115kB to 89kB (~77% of original) in 322ms = 358kB/s. ~256 total partitions merged to 36.
INFO  2024-09-16 12:02:22,896 [shard 0:comp] compaction - [Compact system.local 882aabf0-7423-11ef-b9e7-2fde4a24b169] Compacting [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/me-3gjl_0xfx_53gxs2trvpcpkxdfmx-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/me-3gjl_0xfl_5i9cg2trvpcpkxdfmx-big-Data.db:level=0:origin=compaction]
INFO  2024-09-16 12:02:22,960 [shard 0:comp] sstable - Rebuilding bloom filter /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/me-3gjl_0xfy_5coq82trvpcpkxdfmx-big-Filter.db: resizing bitset from 328 bytes to 8 bytes. sstable origin: compaction
INFO  2024-09-16 12:02:23,071 [shard 0:comp] compaction - [Compact system.local 882aabf0-7423-11ef-b9e7-2fde4a24b169] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/me-3gjl_0xfy_5coq82trvpcpkxdfmx-big-Data.db:level=0]. 23kB to 12kB (~52% of original) in 143ms = 167kB/s. ~256 total partitions merged to 1.
INFO  2024-09-16 12:02:23,083 [shard 0:comp] compaction - [Compact system_schema.tables 8845ae00-7423-11ef-b9e7-2fde4a24b169] Compacting [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3gjl_0xfx_4iohc2trvpcpkxdfmx-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-2-big-Data.db:level=0:origin=memtable]
INFO  2024-09-16 12:02:23,132 [shard 0: gms] raft_topology - coordinator fiber found a node to work on id=e9eec7b7-73e2-40e3-a2f1-de25d422561e state=normal
INFO  2024-09-16 12:02:23,133 [shard 0: gms] raft_topology - updating topology state: start removenode
...
INFO  2024-09-16 12:02:23,170 [shard 0:comp] sstable - Rebuilding bloom filter /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3gjl_0xfz_0lv1c2trvpcpkxdfmx-big-Filter.db: resizing bitset from 328 bytes to 16 bytes. sstable origin: compaction
INFO  2024-09-16 12:02:23,246 [shard 0:comp] compaction - [Compact system_schema.tables 8845ae00-7423-11ef-b9e7-2fde4a24b169] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3gjl_0xfz_0lv1c2trvpcpkxdfmx-big-Data.db:level=0]. 21kB to 14kB (~68% of original) in 124ms = 169kB/s. ~256 total partitions merged to 6.
INFO  2024-09-16 12:02:23,257 [shard 0:comp] compaction - [Compact system.topology 8861e890-7423-11ef-b9e7-2fde4a24b169] Compacting [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/data/system/topology-5be1feb3929e3df98da8d771c36129a0/me-3gjl_0xfx_4qe9c2trvpcpkxdfmx-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-8bzf52rn/test/node1/data/system/topology-5be1feb3929e3df98da8d771c36129a0/me-3gjl_0xfl_574402trvpcpkxdfmx-big-Data.db:level=0:origin=compaction]
INFO  2024-09-16 12:02:23,361 [shard 0: gms] raft_topology - entered `tablet draining` transition state
INFO  2024-09-16 12:02:23,361 [shard 0: gms] load_balancer - Examining DC datacenter1 (shuffle=false, balancing=true)
INFO  2024-09-16 12:02:23,361 [shard 0: gms] load_balancer - Will drain node e9eec7b7-73e2-40e3-a2f1-de25d422561e (being_removed) from DC datacenter1
INFO  2024-09-16 12:02:23,361 [shard 0: gms] load_balancer - Node 627d43eb-afc2-449e-8a1a-4ec0b88d4104: rack=rack1 avg_load=1.5, tablets=3, shards=2, state=normal
INFO  2024-09-16 12:02:23,361 [shard 0: gms] load_balancer - Node 7552e30e-0853-4429-89dc-2264c119cacf: rack=rack1 avg_load=1, tablets=2, shards=2, state=normal
INFO  2024-09-16 12:02:23,361 [shard 0: gms] load_balancer - Node e9eec7b7-73e2-40e3-a2f1-de25d422561e: rack=rack1 avg_load=1.5, tablets=3, shards=2, state=being_removed
INFO  2024-09-16 12:02:23,361 [shard 0: gms] load_balancer - Node ae8176b0-e428-49bf-bb7e-0fe12407d621: rack=rack1 avg_load=1, tablets=2, shards=2, state=normal
INFO  2024-09-16 12:02:23,361 [shard 0: gms] load_balancer - Node d065add6-72c5-4b34-850c-c10fc6ff1263: rack=rack1 avg_load=1, tablets=2, shards=2, state=normal
...
INFO  2024-09-16 12:02:33,328 [shard 0: gms] load_balancer - Will drain node e9eec7b7-73e2-40e3-a2f1-de25d422561e (being_removed) from DC datacenter1
INFO  2024-09-16 12:02:33,328 [shard 0: gms] load_balancer - Node e9eec7b7-73e2-40e3-a2f1-de25d422561e is already drained, ignoring
INFO  2024-09-16 12:02:33,328 [shard 0: gms] load_balancer - Node 627d43eb-afc2-449e-8a1a-4ec0b88d4104: rack=rack1 avg_load=1.5, tablets=3, shards=2, state=normal
INFO  2024-09-16 12:02:33,328 [shard 0: gms] load_balancer - Node 7552e30e-0853-4429-89dc-2264c119cacf: rack=rack1 avg_load=2, tablets=4, shards=2, state=normal
INFO  2024-09-16 12:02:33,328 [shard 0: gms] load_balancer - Node ae8176b0-e428-49bf-bb7e-0fe12407d621: rack=rack1 avg_load=1.5, tablets=3, shards=2, state=normal
INFO  2024-09-16 12:02:33,328 [shard 0: gms] load_balancer - Node d065add6-72c5-4b34-850c-c10fc6ff1263: rack=rack1 avg_load=1, tablets=2, shards=2, state=normal
INFO  2024-09-16 12:02:33,328 [shard 0: gms] load_balancer - target node: d065add6-72c5-4b34-850c-c10fc6ff1263, avg_load: 1, max: 2
INFO  2024-09-16 12:02:33,329 [shard 0: gms] load_balancer - Prepared 1 migrations in DC datacenter1
INFO  2024-09-16 12:02:33,329 [shard 0: gms] load_balancer - Prepared 1 migration plans, out of which there were 1 tablet migration(s) and 0 resize decision(s)
INFO  2024-09-16 12:02:33,329 [shard 0: gms] raft_topology - updating topology state: Finished tablet migration
INFO  2024-09-16 12:02:33,527 [shard 0: gms] raft_topology - entered `write both read old` transition state
INFO  2024-09-16 12:02:33,527 [shard 0: gms] raft_topology - executing global topology command barrier_and_drain, excluded nodes: {e9eec7b7-73e2-40e3-a2f1-de25d422561e}
INFO  2024-09-16 12:02:33,548 [shard 0: gms] raft_topology - updating topology state: advance fence version to 31
INFO  2024-09-16 12:02:33,750 [shard 0: gms] raft_topology - executing global topology command stream_ranges, excluded nodes: {e9eec7b7-73e2-40e3-a2f1-de25d422561e}
INFO  2024-09-16 12:02:33,753 [shard 0:strm] raft_topology - start streaming
INFO  2024-09-16 12:02:33,753 [shard 0:strm] storage_service - enable_repair_based_node_ops=true, allowed_repair_based_node_ops={decommission ,bootstrap ,rebuild ,removenode ,replace}
[node1 restarted by dtest]
...
INFO  2024-09-16 12:02:45,522 [shard 0:main] init - Scylla version 6.2.0~dev-0.20240915.028410ba5868 with build-id 6332b0e6a38c2c0fd4b559630c588379ce395758 starting ...
...
[removenode retried after restart]
INFO  2024-09-16 12:04:00,486 [shard 0:strm] api - remove_node: host_id=e9eec7b7-73e2-40e3-a2f1-de25d422561e ignore_nodes=[]
INFO  2024-09-16 12:04:00,490 [shard 0:strm] raft_topology - request removenode for: e9eec7b7-73e2-40e3-a2f1-de25d422561e, new ignored nodes: {e9eec7b7-73e2-40e3-a2f1-de25d422561e}, existing ignore nodes: {e9eec7b7-73e2-40e3-a2f1-de25d422561e}
INFO  2024-09-16 12:04:00,491 [shard 0:strm] raft_group0 - making servers {e9eec7b7-73e2-40e3-a2f1-de25d422561e} non-voters...
INFO  2024-09-16 12:04:00,492 [shard 0:strm] raft_group0 - servers {e9eec7b7-73e2-40e3-a2f1-de25d422561e} are now non-voters.
INFO  2024-09-16 12:04:00,726 [shard 0:strm] raft_topology - removenode: waiting for completion (request ID: c2569d20-7423-11ef-6154-bf7670dd2b7d)
INFO  2024-09-16 13:58:23,333 [shard 0:main] compaction_manager - Asked to stop
```

**Comment by kbr-scylla** [comment] 2024-09-25 10:25
> E           Failed: Timeout >7200s

The timeout is 2 hours? Crazy.

**Comment by kbr-scylla** [comment] 2024-09-25 10:30
> I don't know why there's only 1 alive voter.

@bhalevy This log comes from node 2, which was removed from the cluster earlier in the test, and therefore banned by it. 
```python3
            # node2 is banned from cluster even if removenode was failed.
            node2.start(wait_other_notice=False)
            with pytest.raises(NodetoolError):
                node2.nodetool("rebuild")
```
It thinks there is only 1 alive voter (itself) because it fails to mark other nodes as alive, because they are not responding to its failure detector RPCs (due to the ban).

The read_barrier error probably comes from this rebuild request.

In any case it is probably unrelated to the issue at hand.

**Comment by kbr-scylla** [comment] 2024-09-25 10:35
Anyway, as usual, the answers lie within topology coordinator logs.
Why is nobody ever looking at the topology coordinator logs? It is the single most important node in the entire cluster.

The question is: why is the removenode request not finishing?
Answer: infinite tablet migrations loop!
```
INFO  2024-09-16 12:04:00,691 [shard 0: gms] raft_topology - entered `tablet migration` transition state
INFO  2024-09-16 12:04:37,235 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
INFO  2024-09-16 12:04:37,243 [shard 0: gms] raft_topology - entered `tablet migration` transition state
INFO  2024-09-16 12:05:37,238 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
INFO  2024-09-16 12:05:37,244 [shard 0: gms] raft_topology - entered `tablet migration` transition state
INFO  2024-09-16 12:06:37,241 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
INFO  2024-09-16 12:06:37,249 [shard 0: gms] raft_topology - entered `tablet migration` transition state
```

this is the third issue I'm seeing this happen in. @tgrabiec

**Comment by kbr-scylla** [comment] 2024-09-25 10:36
Duplicate of https://github.com/scylladb/scylladb/issues/20227.

**Comment by kbr-scylla** [comment] 2024-09-25 10:36
At least that first report. I'll also look at the second report which looks unrelated, and open another issue if needed.

**Closed by kbr-scylla** 2024-09-25 10:36 UTC
Labels: area/topology changes, area/tablets

**Comment by kbr-scylla** [comment] 2024-09-25 10:47
The second report https://github.com/scylladb/scylladb/issues/20634#issuecomment-2367364098 is different, most prominently, it ran in gossip-topology mode. The original report is from raft-topology mode.

The last report https://github.com/scylladb/scylladb/issues/20634#issuecomment-2367954171 is the same as the first one, and again it's trivial to determine by looking at topology coordinator logs:
```
INFO  2024-09-16 13:19:37,421 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
INFO  2024-09-16 13:19:37,426 [shard 0: gms] raft_topology - entered `tablet migration` transition state
INFO  2024-09-16 13:20:37,423 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
INFO  2024-09-16 13:20:37,428 [shard 0: gms] raft_topology - entered `tablet migration` transition state
INFO  2024-09-16 13:21:37,425 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
INFO  2024-09-16 13:21:37,430 [shard 0: gms] raft_topology - entered `tablet migration` transition state
INFO  2024-09-16 13:22:37,427 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
INFO  2024-09-16 13:22:37,433 [shard 0: gms] raft_topology - entered `tablet migration` transition state
```

**Comment by kbr-scylla** [comment] 2024-09-25 10:59
@aleksbykov the test code is super hard to read and understand :(
We have this call:
```python3
        self._start_removenode_operation_and_abort_after_streaming_started(node1, node2_hostid, to_kill_coordinator, marks)
```

which suggests that node1 and node2 are somehow involved in this operation
But then:
```python3
        executor = ThreadPoolExecutor(max_workers=1)
        t = executor.submit(self._kill_node_thread, to_kill_coordinator, marks)
```

```python3
    def _kill_node_thread(self, to_kill_coordinator: bool, marks: dict[ScyllaNode, int]):
        logger.debug("kill node thread")
        node1, node2, node3, node4, node5 = list(marks.keys())
...
            logger.debug("Stop node5 gently=False")
            node5.stop(gently=False)
```

node 5 is also involved?
This is very confusing.

Why are we even passing parameters through functions like `node1`, if these functions are accessing global state anyway (through `self`)

Also, the nested branches inside `_kill_node_thread` make it extremely hard to see what's going on in this test.

I think the test deserves a good refactor.

**Comment by kbr-scylla** [comment] 2024-09-25 11:22
Opened new issue for the second report: https://github.com/scylladb/scylladb/issues/20814

**Comment by mykaul** [comment] 2024-09-25 12:49
> Anyway, as usual, the answers lie within topology coordinator logs.
> Why is nobody ever looking at the topology coordinator logs? It is the single most important node in the entire cluster.

Perhaps a short lecture on how to identify it, what to look for, etc. would be useful.

**Comment by tgrabiec** [comment] 2024-09-25 20:08
We could automate this, and report what's blocking topology state machine when active request is blocked for too long.

**Comment by kbr-scylla** [comment] 2024-09-26 10:30
> Perhaps a short lecture on how to identify it, what to look for, etc. would be useful.

In the directory with node logs:
```
grep -r "raft_topology - start topology coordinator fiber" .
```
