### ISSUE TITLE
Decommissioning unbootstrup did not start, decommissioning did not complete

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#13281] opened 2023-03-22 10:26 UTC
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

**Problem**
Decommissioning unbootstrup was not start, decommissioning is not competed

**Description**

The problem happened during `DecommissionStreamingErr` nemesis:
```
2023-03-16 06:32:14.602: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=e9cf85d8-61a3-4277-84b4-84a8bcdf7185: nemesis_name=DecommissionStreamingErr target_node=Node longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4 [34.244.213.255 | 10.4.2.42] (seed: False)
```

Decommission was initialized on the node `longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4 [34.244.213.255 | 10.4.2.42]`:
```
< t:2023-03-16 06:32:16,412 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-03-16 06:32:16.410: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=a167fa59-19f2-4868-80ce-c604cc9dc2fa: nodetool_command=decommission node=longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4
< t:2023-03-16 06:32:16,411 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  decommission "...
```

The command was received on the node at `2023-03-16 06:32:18`:
```
2023-03-16T06:32:18+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 2] api - decommission
```

Storage service informed about decommission start **10 minutes later** - at `2023-03-16 06:52:38`:
```
2023-03-16T06:52:38+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] storage_service - DECOMMISSIONING: starts
2023-03-16T06:52:38+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] storage_service - decommission[6a0e17e8-9e0a-4179-bff7-78ba2b1d1d7a]: Started decommission operation, removing node=10.4.2.42, sync_nodes=[10.4.2.42, 10.4.2.224, 10.4.3.47, 10.4.3.160], ignore_nodes=[]
```

But decommissioning was not continued and unbootstrap was not started, no "DECOMMISSIONING: unbootstrap starts" message in the log.

Nodetool command failed with timeout after 25 minutes:
```
2023-03-16 06:57:22.242: (NodetoolEvent Severity.WARNING) period_type=end event_id=a167fa59-19f2-4868-80ce-c604cc9dc2fa duration=25m5s: nodetool_command=decommission node=longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4 errors=["Command did not complete within 180 seconds!\n\nCommand: '/usr/bin/nodetool  decommission '\n\nStdout:\n\n\n\nStderr:\n\n\n\n"]
```

No errors, aborting or core.

Worth to mention that `ModifyTable` nemesis was run in parallel on the node `longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-17`, alter "caching" property:
```
2023-03-16 06:29:28.039: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=26fc72b3-ea19-4eff-a913-183369c69655: nemesis_name=ModifyTable target_node=Node longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-17 [176.34.202.80 | 10.4.3.47] (seed: False)

< t:2023-03-16 06:48:57,800 f:common.py       l:1636 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE cqlstress_lwt_example.blogposts WITH caching = {'keys': 'ALL', 'rows_per_partition': 8426};' 

2023-03-16 06:49:09.460: (DisruptionEvent Severity.NORMAL) period_type=end 
event_id=26fc72b3-ea19-4eff-a913-183369c69655 duration=19m41s: nemesis_name=ModifyTable target_node=Node longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-17 [176.34.202.80 | 10.4.3.47] (seed: False)
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1031-aws
Scylla version (or git commit hash): `2023.1.0~rc2-20230302.726f8a090337` with build-id `efcc950cda22875aa488c5295c6cc68f35d9cc6f`

Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-9 (54.154.96.95 | 10.4.2.143) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-8 (3.251.77.175 | 10.4.0.41) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-7 (54.75.85.183 | 10.4.2.86) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-6 (3.252.196.82 | 10.4.0.60) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-5 (3.251.98.48 | 10.4.2.73) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4 (34.244.213.255 | 10.4.2.42) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-3 (52.211.80.80 | 10.4.2.101) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-22 (34.244.142.90 | 10.4.0.149) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-21 (54.194.239.176 | 10.4.0.75) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-20 (52.16.146.150 | 10.4.2.85) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-2 (54.229.107.157 | 10.4.1.120) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-19 (3.252.127.20 | 10.4.3.39) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-18 (52.16.12.198 | 10.4.3.204) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-17 (176.34.202.80 | 10.4.3.47) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-16 (34.252.34.122 | 10.4.0.202) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-15 (3.253.61.6 | 10.4.3.41) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-14 (34.242.242.80 | 10.4.3.160) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-13 (34.244.111.177 | 10.4.0.74) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-12 (3.251.73.37 | 10.4.0.209) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-11 (3.252.188.27 | 10.4.3.79) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-10 (3.250.92.202 | 10.4.0.213) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-1 (54.216.75.132 | 10.4.2.224) (shards: 7)

OS / Image: `ami-0336a5a646b08dc25` (aws: eu-west-1)

Test: `longevity-lwt-parallel-schema-changes-with-disruptive-24h-test`
Test id: `4b6c7c6a-5554-4121-8a52-40717cc924e8`
Test name: `enterprise-2023.1/longevity/longevity-lwt-parallel-schema-changes-with-disruptive-24h-test`
Test config file(s):

- [longevity-lwt-parallel-24h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4ec1600f015410814cdbe6d94ce29af866d6ccda/test-cases/longevity/longevity-lwt-parallel-24h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 4b6c7c6a-5554-4121-8a52-40717cc924e8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=4b6c7c6a-5554-4121-8a52-40717cc924e8)
- Show all stored logs command: `$ hydra investigate show-logs 4b6c7c6a-5554-4121-8a52-40717cc924e8`

## Logs:
- **db-cluster-4b6c7c6a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/db-cluster-4b6c7c6a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/db-cluster-4b6c7c6a.tar.gz)
- **email_data-4b6c7c6a.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/email_data-4b6c7c6a.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/email_data-4b6c7c6a.json.tar.gz)
- **output-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/output-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/output-4b6c7c6a.log.tar.gz)
- **debug-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/debug-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/debug-4b6c7c6a.log.tar.gz)
- **events-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/events-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/events-4b6c7c6a.log.tar.gz)
- **sct-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/sct-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/sct-4b6c7c6a.log.tar.gz)
- **normal-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/normal-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/normal-4b6c7c6a.log.tar.gz)
- **argus-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/argus-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/argus-4b6c7c6a.log.tar.gz)
- **raw_events-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/raw_events-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/raw_events-4b6c7c6a.log.tar.gz)
- **critical-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/critical-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/critical-4b6c7c6a.log.tar.gz)
- **warning-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/warning-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/warning-4b6c7c6a.log.tar.gz)
- **summary-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/summary-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/summary-4b6c7c6a.log.tar.gz)
- **left_processes-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/left_processes-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/left_processes-4b6c7c6a.log.tar.gz)
- **error-4b6c7c6a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/error-4b6c7c6a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/error-4b6c7c6a.log.tar.gz)
- **monitor-set-4b6c7c6a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/monitor-set-4b6c7c6a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/monitor-set-4b6c7c6a.tar.gz)
- **loader-set-4b6c7c6a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/loader-set-4b6c7c6a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4b6c7c6a-5554-4121-8a52-40717cc924e8/20230316_153137/loader-set-4b6c7c6a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-lwt-parallel-schema-changes-with-disruptive-24h-test/3/)
</details>

**Comment by DoronArazii** [comment] 2023-03-22 13:01
@gleb-cloudius can you please check if it's related to raft

**Comment by gleb-cloudius** [comment] 2023-03-22 13:26
The raft surely not responsible for the 20 minute delay between calling the api and starting decomissioning. It looks like the node is absolutely overloaded and busy printing timeouts. At the moment the node is stopped there are  407658 requests aborted. 55200 on shard 0 only.

**Comment by roydahan** [comment] 2023-04-02 11:27
@juliayakovlev what do we see on the overloaded node during this time period?
Is there any log message repeating itself?

**Comment by juliayakovlev** [comment] 2023-04-04 09:36
@roydahan @gleb-cloudius 

Commonly the cluster is not overloaded
![cluster_by_instance](https://user-images.githubusercontent.com/34435448/229722283-96d639e8-d505-4519-9f83-b0ad4eead20e.png)

Decommission is running on the node `longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4 [34.244.213.255 | 10.4.2.42]`.
Load on the node4 by instance
![node4_by_instance](https://user-images.githubusercontent.com/34435448/229722574-6b499bad-4e2e-446d-a173-02b7400ba716.png)

Only **shard 0** is 100%
![node4_by_shard](https://user-images.githubusercontent.com/34435448/229722754-49098cb3-fc3d-473d-b4aa-d30218f50e29.png)


### When shard 0 of longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4 got 100% load

Shard 0 was started to run with 100% in time of `KillScylla` nemesis ran on the `longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4` (run "pkill -9 scylla") 

```
2023-03-16 03:50:04.175: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=e4404893-ce49-44ae-9d82-2f604cd72886: nemesis_name=KillScylla target_node=Node longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4 [34.244.213.255 | 10.4.2.42] (seed: False)
```

when Scylla completed its initialization:
```
2023-03-16T03:53:18+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] init - Scylla version 2023.1.0~rc2-0.20230302.726f8a090337 initialization completed.
```

![node4_shard0_start_100per](https://user-images.githubusercontent.com/34435448/229723653-06f9d64d-f18f-44bb-84ba-b28a4a2dbaf2.png)

From node4 log in this time:
```
2023-03-16T03:53:10+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 1] compaction - [Compact system.scylla_local 0ff9ac20-c3ae-11ed-980c-3d6574e12d67] Compacted 32 s
stables to [/var/lib/scylla/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-13336-big-Data.db:level=0]. 484kB to 70kB (~14% of original) in 1685ms = 41kB/s. ~4096 total partitions merged to 2.
2023-03-16T03:53:18+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] gossip - No gossip backlog; proceeding
2023-03-16T03:53:18+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] init - allow replaying hints
2023-03-16T03:53:18+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] init - Launching generate_mv_updates for non system tables
2023-03-16T03:53:18+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] init - starting the view builder
2023-03-16T03:53:18+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] init - starting native transport
2023-03-16T03:53:18+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] cql_server_controller - Starting listening for CQL clients on 10.4.2.42:9042 (unencrypted, non-shard-aware)
2023-03-16T03:53:18+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] cql_server_controller - Starting listening for CQL clients on 10.4.2.42:19042 (unencrypted, shard-aware)
2023-03-16T03:53:18+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] init - serving
2023-03-16T03:53:18+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] init - Scylla version 2023.1.0~rc2-0.20230302.726f8a090337 initialization completed.
2023-03-16T03:53:22+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 0] reader_concurrency_semaphore - (rate limiting dropped 24424 similar messages) Semaphore sl:default_read_concurrency_sem with 26/100 count and 661456/170582343 memory resources: timed out, dumping permit diagnostics:
permits count   memory  table/description/state
26      26      646K    system.paxos/data-query/active/used
4294    0       0B      system.paxos/data-query/waiting

4320    26      646K    total

Total: 4320 permits with 26 count and 646K memory resources
2023-03-16T03:53:22+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 5] compaction - [Compact system.paxos 04dd6f21-c3ae-11ed-9fed-3d6474e12d67] Compacted 2 sstables to [/var/lib/scylla/data/system/paxos-b7b7f0c2fd0a34108c053ef614bb7c2d/me-18765-big-Data.db:level=0]. 14MB to 9MB (~62% of original) in 32633ms = 278kB/s. ~222848 total partitions merged to 141590.
2023-03-16T03:53:23+00:00 longevity-lwt-parallel-24h-2023-1-db-node-4b6c7c6a-4     !INFO | scylla[14697]:  [shard 6] reader_concurrency_semaphore - (rate limiting dropped 23183 similar messages) Semaphore sl:default_read_concurrency_sem with 24/100 count and 1078213/170582343 memory resources: timed out, dumping permit diagnostics:
permits count   memory  table/description/state
12      12      821K    system.paxos/data-query/active/blocked
12      12      232K    system.paxos/data-query/active/used
4312    0       0B      system.paxos/data-query/waiting

4336    24      1053K   total

Total: 4336 permits with 24 count and 1053K memory resources
```

From this time shard 0 runs with 100%
![node4_shard0_load](https://user-images.githubusercontent.com/34435448/229745532-89b5ddd3-be6e-4ead-8d4c-d1c4151b4deb.png)

Node 4 all shards load:

![node4_per_shard_load](https://user-images.githubusercontent.com/34435448/229744977-18494c72-abfb-4ae9-bd5e-af6094b18554.png)

There are `reader_concurrency_semaphore` on different shards (node4)

Also during life time of the node4 there are 132502 "system.paxos" timeout messages :
```
Failed to apply mutation from 10.4.1.120#4: exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)
```

Worth to mention that `ModifyTable` nemesis was run in parallel with `KillScylla` nemesis.

As we can see from last print screen - load descreased later. Cassandra-stress continue to run, there are write and read timeouts

**Comment by DoronArazii** [comment] 2023-04-10 12:03
@kostja can you please give take a look & give some clues

**Comment by DoronArazii** [comment] 2023-04-17 12:01
Missed the train to 5.2, pushing to 5.3

**Comment by kostja** [comment] 2023-04-18 14:24
The so-called "unbootstrap" is not guaranteed to start if the node is overloaded. I think this issue could be seen as one among many requesting an automatic and safe abort of a failed topology chagne. As such, tracking it with the topology changes track.

**Comment by DoronArazii** [comment] 2023-07-27 12:01
@juliayakovlev it's still reproduce with the latest?

**Comment by juliayakovlev** [comment] 2023-08-08 11:39
@DoronArazii 
Sorry for delay, I missed this email.
The issue has not been reproduced with Scylla version: 2023.1.0~rc5-20230429.a47bcb26e42e (run details below)


## Installation details

Kernel Version: 5.15.0-1035-aws
Scylla version (or git commit hash): `2023.1.0~rc5-20230429.a47bcb26e42e` with build-id `d2644a8364f13d14d25be6b9d3c69f84612192bd`

Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-9 (3.250.109.85 | 10.4.1.49) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-8 (18.203.223.110 | 10.4.2.52) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-7 (34.244.199.69 | 10.4.2.204) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-6 (54.154.54.73 | 10.4.2.180) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-5 (34.255.6.153 | 10.4.1.2) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-4 (34.249.51.228 | 10.4.2.134) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-3 (18.202.235.51 | 10.4.2.207) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-2 (3.252.206.24 | 10.4.1.104) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-16 (52.48.130.233 | 10.4.2.21) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-15 (34.253.181.49 | 10.4.2.70) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-14 (34.241.112.227 | 10.4.0.168) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-13 (63.32.46.61 | 10.4.0.247) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-12 (3.250.11.52 | 10.4.3.162) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-11 (3.252.163.225 | 10.4.1.200) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-10 (3.250.50.18 | 10.4.0.86) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-1 (52.212.121.45 | 10.4.0.88) (shards: 7)


OS / Image: `ami-05e7801837cea47d9` (aws: eu-west-1)

Test: `longevity-lwt-parallel-schema-changes-with-disruptive-24h-test`
Test id: `f7a072d4-311b-4f08-ac18-97c9a39b8378`
Test name: `enterprise-2023.1/longevity/longevity-lwt-parallel-schema-changes-with-disruptive-24h-test`
Test config file(s):

- [longevity-lwt-parallel-24h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1dafb96f428e2691c12e03508dc5024d85552043/test-cases/longevity/longevity-lwt-parallel-24h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor f7a072d4-311b-4f08-ac18-97c9a39b8378`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f7a072d4-311b-4f08-ac18-97c9a39b8378)
- Show all stored logs command: `$ hydra investigate show-logs f7a072d4-311b-4f08-ac18-97c9a39b8378`


## Logs:
- **db-cluster-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/db-cluster-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/db-cluster-f7a072d4.tar.gz)
- **sct-runner-events-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-runner-events-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-runner-events-f7a072d4.tar.gz)
- **sct-f7a072d4.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-f7a072d4.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-f7a072d4.log.tar.gz)
- **monitor-set-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/monitor-set-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/monitor-set-f7a072d4.tar.gz)
- **loader-set-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/loader-set-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/loader-set-f7a072d4.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-lwt-parallel-schema-changes-with-disruptive-24h-test/4/)
[Argus](https://argus.scylladb.com/test/543ce33e-f43a-464c-8eed-8c47a0f2299a/runs?additionalRuns[]=f7a072d4-311b-4f08-ac18-97c9a39b8378)
</details>

**Comment by DoronArazii** [comment] 2023-08-08 12:14
Thanks @juliayakovlev 
Closing as not planned.

**Closed by DoronArazii** 2023-08-08 12:14 UTC
Labels: topology changes
