### ISSUE TITLE
Scylla failed to start with error: Startup failed: seastar::timed_out_error (timedout) after upgrade

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#9795] opened 2021-12-14 15:23 UTC
upgrade scylla from version 4.5.2 -> 4.7.dev-0.20211128.44f4ea38c with build-id ce2f8485c84f459e654f38aa0029eb9d763e453a
on centos 7 in job https://jenkins.scylladb.com/view/master/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/206/ failed during upgrading 1st node.
Node was upgraded. After new scylla versin installed and started next errors ( a lot of them) start appearin in log:
```
2021-12-10T06:01:18+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] legacy_schema_migrator - Completed migration of legacy schema tables
2021-12-10T06:01:18+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - loading system sstables
2021-12-10T06:01:18+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - loading non-system sstables
2021-12-10T06:01:18+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 ! WARNING |  [shard 0] compaction - DateTieredCompactionStrategy is deprecated. Usually cases for which it is used are better handled by TimeWindowCompactionStrategy. Please change your compaction strategy to TWCS as DTCS will be retired in the near future
2021-12-10T06:01:18+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 ! WARNING |  [shard 0] compaction - DateTieredCompactionStrategy is deprecated. Usually cases for which it is used are better handled by TimeWindowCompactionStrategy. Please change your compaction strategy to TWCS as DTCS will be retired in the near future
2021-12-10T06:01:18+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 ! WARNING |  [shard 0] compaction - DateTieredCompactionStrategy is deprecated. Usually cases for which it is used are better handled by TimeWindowCompactionStrategy. Please change your compaction strategy to TWCS as DTCS will be retired in the near future
2021-12-10T06:01:18+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 ! WARNING |  [shard 0] compaction - DateTieredCompactionStrategy is deprecated. Usually cases for which it is used are better handled by TimeWindowCompactionStrategy. Please change your compaction strategy to TWCS as DTCS will be retired in the near future
...
2021-12-10T06:01:33+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - starting system distributed keyspace
2021-12-10T06:01:33+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] migration_manager - Create new Keyspace: KSMetaData{name=system_distributed_everywhere, strategyClass=org.apache.cassandra.locator.EverywhereStrategy, strategyOptions={}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x60000e6bcdb8}
2021-12-10T06:01:33+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO | Started Session 1272 of user scylla-test.
2021-12-10T06:01:33+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO | New session 1272 of user scylla-test.
2021-12-10T06:01:33+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO | pam_unix(sshd:session): session opened for user scylla-test by (uid=0)
2021-12-10T06:01:33+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO | pam_unix(sshd:session): session closed for user scylla-test
2021-12-10T06:01:33+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO | Removed session 1272.
2021-12-10T06:01:34+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO | JMX is enabled to receive remote connections on port: 7199
2021-12-10T06:01:35+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !     ERR |  [shard 4] view - Error applying view update to 10.142.0.139 (view: ks1.table1_mv_0, base token: 2411995000582821016, view token: -7225934468558713709): seastar::timed_out_error (timedout)
2021-12-10T06:01:35+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !     ERR |  [shard 4] view - Error applying view update to 10.142.0.139 (view: ks1.table1_col6_idx_index, base token: 2411995000582821016, view token: -8910172594085141869): seastar::timed_out_error (timedout)
2021-12-10T06:01:35+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !     ERR |  [shard 4] view - Error applying view update to 10.142.0.139 (view: ks1.table1_col6_idx_index, base token: 2366838725947229738, view token: -3532541654160927043): seastar::timed_out_error (timedout)
2021-12-10T06:01:35+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !     ERR |  [shard 4] view - Error applying view update to 10.142.0.139 (view: ks1.table1_mv_0, base token: 5920539500753116815, view token: 7064336447190271316): seastar::timed_out_error (timedout)
2021-12-10T06:01:35+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !     ERR |  [shard 4] view - Error applying view update to 10.142.0.139 (view: ks1.table1_col6_idx_index, base token: -5248441496057929603, view token: 5722073765893449480): seastar::timed_out_error (timedout)
2021-12-10T06:01:35+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !     ERR |  [shard 4] view - Error applying view update to 10.142.0.139 (view: ks1.table1_col6_idx_index, base token: -4118141053456046667, view token: 2213735050796133912): seastar::timed_out_error (timedout)
2021-12-10T06:01:35+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !     ERR |  [shard 4] view - Error applying view update to 10.142.0.139 (view: ks1.table1_col6_idx_index, base token: -1915794574959962960, view token: -6707619576439263014): seastar::timed_out_error (timedout)
...
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !     ERR |  [shard 0] view - Error applying view update to 10.142.0.153 (view: ks1.table1_mv_0, base token: 8057244361677864718, view token: -6078503232500008126): exceptions::mutation_write_timeout_exception (Operation timed out for ks1.table1_mv_0 - received only 0 responses from 1 CL=ANY.)
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !     ERR |  [shard 0] view - Error applying view update to 10.142.0.135 (view: ks1.table1_col6_idx_index, base token: -2805740784396199791, view token: 2070604701747049039): exceptions::mutation_write_timeout_exception (Operation timed out for ks1.table1_col6_idx_index - received only 0 responses from 1 CL=ANY.)
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down database was successful
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down service_memory_limiter
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down service_memory_limiter was successful
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down sst_dir_semaphore
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down sst_dir_semaphore was successful
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down storage_service
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down storage_service was successful
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down Raft
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down Raft was successful
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down gossiper
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] gossip - My status = NORMAL
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] gossip - Announcing shutdown
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] gossip - Sending a GossipShutdown to 10.142.0.149 with generation 1639116081
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] gossip - Sending a GossipShutdown to 10.142.0.153 with generation 1639116081
2021-12-10T06:07:23+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] gossip - Sending a GossipShutdown to 10.142.0.135 with generation 1639116081
```

And then scylla failed to start with next error:
```
2021-12-10T06:07:26+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down migration manager notifier was successful
2021-12-10T06:07:26+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down prometheus API server
2021-12-10T06:07:26+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down prometheus API server was successful
2021-12-10T06:07:26+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down sighup
2021-12-10T06:07:26+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !    INFO |  [shard 0] init - Shutting down sighup was successful
2021-12-10T06:07:26+00:00 rolling-upgrade-master-centos-db-node-6479dca2-0-2 !     ERR |  [shard 0] init - Startup failed: seastar::timed_out_error (timedout)
```

All db logs:
https://cloudius-jenkins-test.s3.amazonaws.com/6479dca2-7ad9-4633-b4c0-d5291546673e/20211210_063240/db-cluster-6479dca2.tar.gz

**Comment by enaydanov** [comment] 2021-12-27 10:34
Got same error for upgrading from 4.6 to 4.7 on CentOS 7 and CentOS 8:

---

Source Scylla version : 4.6.rc1 with build-id 542394c82
Target Scylla version: 4.7.dev-0.20211222.e772fcbd5

Cluster size: 4 nodes (n1-highmem-8)

OS / Image: https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7 (gce: eu-west-1)

Test: rolling-upgrade-centos7-test

Test id: fd526ec7-d860-4d0c-92b5-327674ec6757

Test name: upgrade_test/rolling-upgrade-centos7-test

Test config file(s): rolling-upgrade.yaml

Restore Monitor Stack command: $ hydra investigate show-monitor fd526ec7-d860-4d0c-92b5-327674ec6757
Restore monitor on AWS instance using Jenkins job
Show all stored logs command: $ hydra investigate show-logs fd526ec7-d860-4d0c-92b5-327674ec6757

Logs:

db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/fd526ec7-d860-4d0c-92b5-327674ec6757/20211225_061143/db-cluster-fd526ec7.tar.gz
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/fd526ec7-d860-4d0c-92b5-327674ec6757/20211225_061143/monitor-set-fd526ec7.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/fd526ec7-d860-4d0c-92b5-327674ec6757/20211225_061143/loader-set-fd526ec7.tar.gz
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/fd526ec7-d860-4d0c-92b5-327674ec6757/20211225_061143/sct-runner-fd526ec7.tar.gz

Jenkins job URL: https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/208/

---

Source Scylla version: 4.6.rc1 with build-id 542394c82
Target Scylla version: 4.7.dev-0.20211222.e772fcbd5

Cluster size: 4 nodes (n1-highmem-8)

OS / Image: https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-8 (gce: eu-west-1)

Test: rolling-upgrade-centos8-test

Test id: cb23a0df-1fe2-4743-973e-e3e0b761660a

Test name: upgrade_test/rolling-upgrade-centos8-test

Test config file(s): rolling-upgrade.yaml

Restore Monitor Stack command: $ hydra investigate show-monitor cb23a0df-1fe2-4743-973e-e3e0b761660a
Restore monitor on AWS instance using Jenkins job
Show all stored logs command: $ hydra investigate show-logs cb23a0df-1fe2-4743-973e-e3e0b761660a

Logs:

db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/cb23a0df-1fe2-4743-973e-e3e0b761660a/20211226_155040/db-cluster-cb23a0df.tar.gz
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/cb23a0df-1fe2-4743-973e-e3e0b761660a/20211226_155040/monitor-set-cb23a0df.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/cb23a0df-1fe2-4743-973e-e3e0b761660a/20211226_155040/loader-set-cb23a0df.tar.gz
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/cb23a0df-1fe2-4743-973e-e3e0b761660a/20211226_155040/sct-runner-cb23a0df.tar.gz

Jenkins job URL: https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos8-test/108/

**Comment by roydahan** [comment] 2021-12-28 18:03
@slivne can you please assign someone?

**Comment by fgelcer** [comment] 2022-01-16 19:17
seeing the same issue with upgrade from `4.6.rc2-0.20220102.e8a1cfb6f with build-id 5d7b96e39c909424e8224207a162fc2c82b67214` to `4.7.dev-0.20220114.8bcd23fa0 with build-id 991662b202244e747b247a64fa0ddefaab6b53af`


```
Jan 16 15:12:17 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 0] schema_tables - Schema version changed to 9af6aa81-2042-3771-9b35-fbef153ed0bf
Jan 16 15:12:17 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 0] migration_manager - Schema merge with 10.142.0.30:0 completed
Jan 16 15:12:17 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 0] migration_manager - Pulling schema from 10.142.0.30:0
Jan 16 15:12:25 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 0] gossip - No gossip backlog; proceeding
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 1] storage_proxy - Failed to apply mutation from 10.142.0.30#1: std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1 (pk{00081e197400cccea05800045154a36b000218790004003514fb}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 1] storage_proxy - Failed to apply mutation from 10.142.0.28#1: std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1 (pk{000858157ae6df91a75d000462ea9a26000292f90004789189d6}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 4] storage_proxy - Failed to apply mutation from 10.142.0.30#4: std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1 (pk{00087ed0e62388a5522c000411693d80000281f300041a92016d}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 4] storage_proxy - Failed to apply mutation from 10.142.0.31#4: std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1 (pk{000815e42279169a969f000428bf8c2c0002b75f00040eebfa2b}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 4] storage_proxy - Failed to apply mutation from 10.142.0.28#4: std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1 (pk{00083741a6ab68f082570004392e7efe000260cf000453984631}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 2] storage_proxy - Failed to apply mutation from 10.142.0.30#2: std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1 (pk{000860b13cb8ac05e0e100044be1cb4c0002a1c800040d14cc1b}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 2] storage_proxy - Failed to apply mutation from 10.142.0.31#2: std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1 (pk{0008226710315e5e9fca00041cca1acc0002899200044afce062}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 5] storage_proxy - Failed to apply mutation from 10.142.0.31#5: std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1 (pk{00084d8fd00859a57bd500047b2ffa5400028f560004392f145d}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 0] storage_proxy - Failed to apply mutation from 10.142.0.28#0: std::_Nested_exception<std::runtime_error> (Could not write mutation keyspace_entire_test:standard1 (pk{000a3436323738314f4b3431}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 0] storage_proxy - Failed to apply mutation from 10.142.0.28#0: std::_Nested_exception<std::runtime_error> (Could not write mutation keyspace_entire_test:standard1 (pk{000a344f4b4e4e3934353031}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 0] storage_proxy - Failed to apply mutation from 10.142.0.28#0: std::_Nested_exception<std::runtime_error> (Could not write mutation keyspace_entire_test:standard1 (pk{000a3330384e4f3138304c30}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 0] storage_proxy - Failed to apply mutation from 10.142.0.28#0: std::_Nested_exception<std::runtime_error> (Could not write mutation keyspace_entire_test:standard1 (pk{000a4d4b3337364e4d313031}) to commitlog): seastar::timed_out_error (timedout)
Jan 16 15:12:26 rolling-upgrade-master-centos-db-node-fe6ca74b-0-2 scylla[22038]:  [shard 0] storage_proxy - Failed to apply mutation from 10.142.0.31#0: std::_Nested_exception<std::runtime_error> (Could not write mutation keyspace_entire_test:standard1 (pk{000a4b35364e4c35334d4c30}) to commitlog): seastar::timed_out_error (timedout)
```

[sct logs](https://cloudius-jenkins-test.s3.amazonaws.com/fe6ca74b-2c9b-466e-bbad-98bc2f80be3a/20220116_152842/sct-runner-fe6ca74b.tar.gz)
[db logs](https://cloudius-jenkins-test.s3.amazonaws.com/fe6ca74b-2c9b-466e-bbad-98bc2f80be3a/20220116_152842/db-cluster-fe6ca74b.tar.gz)

`test_id: fe6ca74b-2c9b-466e-bbad-98bc2f80be3a`

**Comment by slivne** [comment] 2022-01-16 22:01
Timeout error to commitlog - this is strange - never saw this before

**Comment by yarongilor** [comment] 2022-01-30 09:38
reproduced similarly in 4.6.rc2-0.20220102.e8a1cfb6f to http://downloads.scylladb.com/unstable/scylla/master/rpm/centos/2022-01-28T04:02:42Z/scylla.repo


error:
```
2022-01-29 05:50:51.206 <2022-01-29 05:50:51.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=9760fd58-e101-4a5e-bc6e-11f8721b8ec7: type=RUNTIME_ERROR regex=std::runtime_error line_number=18117 node=rolling-upgrade-master-centos-db-node-3ef0325f-0-3
2022-01-29T05:50:51+00:00 rolling-upgrade-master-centos-db-node-3ef0325f-0-3 !     ERR |  [shard 2] view - Error applying view update to 10.142.0.80 (view: ks1.table1_col3_idx_index, base token: 4005171622434751302, view token: -1256166913274274330): std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1_col3_idx_index (pk{00083fe9b074c130aec5}) to commitlog): seastar::timed_out_error (timedout)
```
details:
Restore commands:
Restore Monitor Stack command: $ hydra investigate show-monitor 3ef0325f-9b0a-4d20-83af-b8da1a41bf81
Restore monitor on AWS instance using Jenkins job
Show all stored logs command: $ hydra investigate show-logs 3ef0325f-9b0a-4d20-83af-b8da1a41bf81
Logs:
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/3ef0325f-9b0a-4d20-83af-b8da1a41bf81/20220129_055951/grafana-screenshot-overview-20220129_055951-rolling-upgrade-master-centos-monitor-node-3ef0325f-0-1.png
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/3ef0325f-9b0a-4d20-83af-b8da1a41bf81/20220129_055951/grafana-screenshot-rolling-upgrade-centos7-test-scylla-per-server-metrics-nemesis-20220129_060146-rolling-upgrade-master-centos-monitor-node-3ef0325f-0-1.png
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/3ef0325f-9b0a-4d20-83af-b8da1a41bf81/20220129_061036/db-cluster-3ef0325f.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/3ef0325f-9b0a-4d20-83af-b8da1a41bf81/20220129_061036/loader-set-3ef0325f.tar.gz
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/3ef0325f-9b0a-4d20-83af-b8da1a41bf81/20220129_061036/monitor-set-3ef0325f.tar.gz
sct - https://cloudius-jenkins-test.s3.amazonaws.com/3ef0325f-9b0a-4d20-83af-b8da1a41bf81/20220129_061036/sct-runner-3ef0325f.tar.gz

**Comment by kostja** [comment] 2024-04-02 11:56
Too old. No updates since the original report - could be an infrastructure issue. Hard limit is in and a lot has changed in commit log since 2021. Closing.

**Comment by piodul** [comment] 2024-04-02 11:56
No reproduction for the last 2 years - closing.

**Closed** 2024-04-02 11:56 UTC
Labels: type/bug, area/commitlog
