### ISSUE TITLE
repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_enable_rbno_for_bootstrap fails because scylla was not able to boot

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#18370] opened 2024-04-23 11:18 UTC
```
self = <repair_based_node_operations_test.TestRepairBasedNodeOperations object at 0x7f6e4c036790>
num_nodes = 4, rf = 3

    @pytest.mark.parametrize(
        "num_nodes",
        [
            pytest.param(3, marks=pytest.mark.required_features("!tablets")),
            pytest.param(4),
        ],
    )
    def test_enable_rbno_for_bootstrap(self, num_nodes, rf=3):
        """
        By default, --allowed-repair-based-node-ops is set for all node operations
    
        This test checks that if "--enable-repair-based-node-ops" is True and "--allowed-repair-based-node-ops" is set
        to "bootstrap", repair will run in case of "bootstrap" operation only
        """
        enable_repair_based_node_ops = True
        self.prepare_cluster(nodes=num_nodes, enable_repair_based_node_ops=enable_repair_based_node_ops, allowed_repair_based_node_ops="bootstrap")
        self.prepare_schema(node=self.cluster.nodelist()[0], rf=rf)
    
        rbnos = RepairBasedNodeOperationsScenarios(tester=self)
        # Change default expected behaviour according to enable-repair-based-node-ops and -allowed-repair-based-node-ops
        for scenario in [rbnos.rebuild_scenario, rbnos.removenode_scenario, rbnos.replace_scenario, rbnos.decommission_scenario]:
            scenario.repair_on_tested_node, scenario.repair_on_all_nodes = False, False
    
>       rbnos.run_scenarios(rbno_enabled=enable_repair_based_node_ops, scenarios=rbnos.operations_flow)

repair_based_node_operations_test.py:487: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
repair_based_node_operations_test.py:312: in run_scenarios
    tested_node = scenario.operation(dc=dc, rack=rack)
repair_based_node_operations_test.py:240: in bootstrap
    new_node = self.add_node(dc=dc, rack=rack)
repair_based_node_operations_test.py:121: in add_node
    new_node.start(wait_for_binary_proto=True, wait_other_notice=True, jvm_args=jvm_args, replace_node_host_id=replace_node_host_id, replace_address=replace_address)
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:700: in start
    scylla_process = self._start_scylla(args=args, marks=marks, update_pid=update_pid,
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:343: in _start_scylla
    self.wait_for_binary_interface(from_mark=from_mark, process=self._process_scylla, timeout=t)
../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:540: in wait_for_binary_interface
    self.watch_log_for("Starting listening for CQL clients", **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ccmlib.scylla_node.ScyllaNode object at 0x7f6e4b2a06d0>
exprs = 'Starting listening for CQL clients', from_mark = 0, timeout = 420
process = <Popen: returncode: 1 args: ['/jenkins/workspace/scylla-master/gating-dtest-...>
verbose = False, filename = 'system.log'

    def watch_log_for(self, exprs, from_mark=None, timeout=600, process=None, verbose=False, filename='system.log'):
        """
        Watch the log until one or more (regular) expression are found.
        This methods when all the expressions have been found or the method
        timeouts (a TimeoutError is then raised). On successful completion,
        a list of pair (line matched, match object) is returned.
        """
        elapsed = 0
        tofind = [exprs] if isinstance(exprs, str) else exprs
        tofind = [re.compile(e) for e in tofind]
        matchings = []
        reads = ""
        if len(tofind) == 0:
            return None
    
        log_file = os.path.join(self.get_path(), 'logs', filename)
        while not os.path.exists(log_file):
            time.sleep(.1)
            if process:
                process.poll()
                if process.returncode is not None:
                    self.print_process_output(self.name, process, verbose)
                    if process.returncode != 0:
                        raise RuntimeError()  # Shouldn't reuse RuntimeError but I'm lazy
    
        with open(log_file) as f:
            if from_mark:
                f.seek(from_mark)
    
            while True:
                # First, if we have a process to check, then check it.
                # Skip on Windows - stdout/stderr is cassandra.bat
                if not common.is_win():
                    if process:
                        process.poll()
                        if process.returncode is not None:
                            self.print_process_output(self.name, process, verbose)
                            if process.returncode != 0:
                                raise RuntimeError()  # Shouldn't reuse RuntimeError but I'm lazy
    
                line = f.readline()
                if line:
                    reads = reads + line
                    for e in tofind:
                        m = e.search(line)
                        if m:
                            matchings.append((line, m))
    
                            # This is bogus! - One should not modify the list from inside the loop which iterates on
                            # that list.
                            # However since we are going to break from the loop a few lines below that should be ok.
                            tofind.remove(e)
    
                            if len(tofind) == 0:
                                return matchings[0] if isinstance(exprs, str) else matchings
                            break
                else:
                    # yep, it's ugly
                    time.sleep(0.01)
                    elapsed = elapsed + 1
                    if elapsed > 100 * timeout:
                        raise TimeoutError(time.strftime("%d %b %Y %H:%M:%S", time.gmtime()) + " [" + self.name + "] Missing: " + str(
                            [e.pattern for e in tofind]) + ":\n" + reads[:50] + f".....\nSee {filename} for remainder")
    
                if process:
                    if common.is_win():
                        if not self.is_running():
                            return None
                    else:
                        process.poll()
                        if process.returncode is not None:
                            if process.returncode == 0:
                                return None
                            else:
>                               raise RuntimeError(f"The process is dead, returncode={process.returncode}")
E                               RuntimeError: The process is dead, returncode=1

../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:506: RuntimeError
```

node4 was one of the seed, but it failed to boot. it seems it hanged somehow. and the last log messages from it are:

```
INFO  2024-04-22 09:56:19,303 [shard 0:strm] stream_session - [Stream #9130df70-008e-11ef-b1ff-872aab8c8439] Executing streaming plan for Rebuild-ks-index-6 with peers=127.0.13.1, slave
INFO  2024-04-22 09:56:19,303 [shard 1:strm] stream_session - [Stream #9130df70-008e-11ef-b1ff-872aab8c8439] Start sending ks=ks, cf=cf, estimated_partitions=8448, with new rpc streaming
INFO  2024-04-22 09:56:19,303 [shard 0:strm] stream_session - [Stream #9130df70-008e-11ef-b1ff-872aab8c8439] Start sending ks=ks, cf=cf, estimated_partitions=8448, with new rpc streaming
INFO  2024-04-22 09:56:19,339 [shard 0:strm] stream_session - [Stream #9130df70-008e-11ef-b1ff-872aab8c8439] Streaming plan for Rebuild-ks-index-6 succeeded, peers={127.0.13.1}, tx=7 KiB, 203.92 KiB/s, rx=0 KiB, 0.00 KiB/s
INFO  2024-04-22 09:56:19,339 [shard 0:strm] stream_session - [Stream #91365db0-008e-11ef-b1ff-872aab8c8439] Executing streaming plan for Rebuild-ks-index-7 with peers=127.0.13.1, slave
INFO  2024-04-22 09:56:19,339 [shard 0:strm] stream_session - [Stream #91365db0-008e-11ef-b1ff-872aab8c8439] Start sending ks=ks, cf=cf, estimated_partitions=7680, with new rpc streaming
INFO  2024-04-22 09:56:19,339 [shard 1:strm] stream_session - [Stream #91365db0-008e-11ef-b1ff-872aab8c8439] Start sending ks=ks, cf=cf, estimated_partitions=7680, with new rpc streaming
INFO  2024-04-22 09:56:19,347 [shard 0:strm] stream_session - [Stream #91365db0-008e-11ef-b1ff-872aab8c8439] Streaming plan for Rebuild-ks-index-7 succeeded, peers={127.0.13.1}, tx=4 KiB, 592.66 KiB/s, rx=0 KiB, 0.00 KiB/s
INFO  2024-04-22 09:56:19,348 [shard 0:strm] stream_session - [Stream #91379631-008e-11ef-b1ff-872aab8c8439] Executing streaming plan for Rebuild-ks-index-8 with peers=127.0.13.1, slave
INFO  2024-04-22 09:56:19,348 [shard 0:strm] stream_session - [Stream #91379631-008e-11ef-b1ff-872aab8c8439] Start sending ks=ks, cf=cf, estimated_partitions=8064, with new rpc streaming
INFO  2024-04-22 09:56:19,348 [shard 1:strm] stream_session - [Stream #91379631-008e-11ef-b1ff-872aab8c8439] Start sending ks=ks, cf=cf, estimated_partitions=8064, with new rpc streaming
INFO  2024-04-22 09:56:19,358 [shard 0:strm] stream_session - [Stream #91379631-008e-11ef-b1ff-872aab8c8439] Streaming plan for Rebuild-ks-index-8 succeeded, peers={127.0.13.1}, tx=5 KiB, 568.55 KiB/s, rx=0 KiB, 0.00 KiB/s
INFO  2024-04-22 09:56:19,358 [shard 0:strm] stream_session - [Stream #913943e0-008e-11ef-b1ff-872aab8c8439] Executing streaming plan for Rebuild-ks-index-9 with peers=127.0.13.1, slave
INFO  2024-04-22 09:56:19,358 [shard 0:strm] stream_session - [Stream #913943e0-008e-11ef-b1ff-872aab8c8439] Start sending ks=ks, cf=cf, estimated_partitions=8448, with new rpc streaming
INFO  2024-04-22 09:56:19,358 [shard 1:strm] stream_session - [Stream #913943e0-008e-11ef-b1ff-872aab8c8439] Start sending ks=ks, cf=cf, estimated_partitions=8448, with new rpc streaming
INFO  2024-04-22 09:56:19,367 [shard 0:strm] stream_session - [Stream #913943e0-008e-11ef-b1ff-872aab8c8439] Streaming plan for Rebuild-ks-index-9 succeeded, peers={127.0.13.1}, tx=7 KiB, 777.09 KiB/s, rx=0 KiB, 0.00 KiB/s
INFO  2024-04-22 09:56:19,367 [shard 0:strm] stream_session - [Stream #913aa370-008e-11ef-b1ff-872aab8c8439] Executing streaming plan for Rebuild-ks-index-10 with peers=127.0.13.1, slave
INFO  2024-04-22 09:56:19,368 [shard 0:strm] stream_session - [Stream #913aa370-008e-11ef-b1ff-872aab8c8439] Start sending ks=ks, cf=cf, estimated_partitions=1920, with new rpc streaming
INFO  2024-04-22 09:56:19,368 [shard 1:strm] stream_session - [Stream #913aa370-008e-11ef-b1ff-872aab8c8439] Start sending ks=ks, cf=cf, estimated_partitions=1920, with new rpc streaming
INFO  2024-04-22 09:56:19,375 [shard 0:strm] stream_session - [Stream #913aa370-008e-11ef-b1ff-872aab8c8439] Streaming plan for Rebuild-ks-index-10 succeeded, peers={127.0.13.1}, tx=1 KiB, 158.32 KiB/s, rx=0 KiB, 0.00 KiB/s
```

while node.5 was not able to contact node4. so it desperately removed it from seeds, and shut it down:
```
WARN  2024-04-22 09:56:44,955 [shard 0: gms] gossip - Fail to send EchoMessage to 127.0.13.4: seastar::rpc::closed_error (connection is closed)
...
INFO  2024-04-22 09:56:45,085 [shard 0: gms] gossip - removed 127.0.13.4 from _seeds, updated _seeds list = {127.0.13.1, 127.0.13.2, 127.0.13.3}
INFO  2024-04-22 09:56:45,085 [shard 0: gms] gossip - Removed endpoint 127.0.13.4
INFO  2024-04-22 09:57:15,034 [shard 0:main] init - Shutting down group 0 usage in local storage
INFO  2024-04-22 09:57:15,034 [shard 0:main] init - Shutting down group 0 usage in local storage was successful
INFO  2024-04-22 09:57:15,034 [shard 0:main] init - Shutting down storage service uninit address map
```
[dtest-gw2.log](https://github.com/scylladb/scylladb/files/15075868/dtest-gw2.log)
[1713779839180_repair_based_node_operations_test.py TestRepairBasedNodeOperations test_enable_rbno_for_bootstrap[4].zip](https://github.com/scylladb/scylladb/files/15075872/1713779839180_repair_based_node_operations_test.py.TestRepairBasedNodeOperations.test_enable_rbno_for_bootstrap.4.zip)

see https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/9095/artifact/logs-full.release.005/1713779839180_repair_based_node_operations_test.py%3A%3ATestRepairBasedNodeOperations%3A%3Atest_enable_rbno_for_bootstrap%5B4%5D/

**Comment by denesb** [comment] 2024-06-20 11:30
Unsure, depends on what the initial triage reveals. I think you can assign to either.

**Comment by kbr-scylla** [comment] 2024-06-20 11:33
Looks like duplicate of https://github.com/scylladb/scylladb/issues/17526.

**Comment by kbr-scylla** [comment] 2024-06-20 11:41
> node4 was one of the seed, but it failed to boot. it seems it hanged somehow. and the last log messages from it are:

@tchaikov according to the test logs, node 4 booted successfully, and then rebuild was performed at some point. 
```
09:56:18,864 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:309  | test_enable_rbno_for_bootstrap[4]: Start rebuild scenario
09:56:18,864 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:286  | test_enable_rbno_for_bootstrap[4]: Running nodetool rebuild on node1
09:56:18,865 799     ccm                            DEBUG    cluster.py          :762  | test_enable_rbno_for_bootstrap[4]: node1: nodetool cmd=['/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/18335/share/cassandra/bin/nodetool', '-h', '127.0.13.1', '-p', '7199', '-Dcom.sun.jndi.rmiURLParsing=legacy', '-Dcom.scylladb.apiPort=10000', 'rebuild'] wait=True timeout=None
09:56:19,416 799     ccm                            DEBUG    cluster.py          :762  | test_enable_rbno_for_bootstrap[4]: node1: checking 
09:56:19,416 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:288  | test_enable_rbno_for_bootstrap[4]: Rebuild completed successfully
09:56:19,416 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:313  | test_enable_rbno_for_bootstrap[4]: Scenario rebuild completed. Start validation
09:56:19,417 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:295  | test_enable_rbno_for_bootstrap[4]: Validate that repair based node operation on the node node1
09:56:19,417 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:295  | test_enable_rbno_for_bootstrap[4]: Validate that repair based node operation on the node node2
09:56:19,417 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:295  | test_enable_rbno_for_bootstrap[4]: Validate that repair based node operation on the node node3
09:56:19,418 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:295  | test_enable_rbno_for_bootstrap[4]: Validate that repair based node operation on the node node4
09:56:19,418 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:309  | test_enable_rbno_for_bootstrap[4]: Start removenode scenario
09:56:19,418 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:248  | test_enable_rbno_for_bootstrap[4]: Stopping node node4 (host id b710f642-11da-4e01-9abc-309f7e173c4a)
09:56:40,266 799     cassandra.cluster              WARNING  libevreactor.py     :371  | test_enable_rbno_for_bootstrap[4]: Host 127.0.13.4:9042 has been marked down
09:56:41,093 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:252  | test_enable_rbno_for_bootstrap[4]: Remove node node4 (host id b710f642-11da-4e01-9abc-309f7e173c4a)
09:56:41,094 799     ccm                            DEBUG    cluster.py          :762  | test_enable_rbno_for_bootstrap[4]: node1: nodetool cmd=['/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/18335/share/cassandra/bin/nodetool', '-h', '127.0.13.1', '-p', '7199', '-Dcom.sun.jndi.rmiURLParsing=legacy', '-Dcom.scylladb.apiPort=10000', 'removenode', 'b710f642-11da-4e01-9abc-309f7e173c4a'] wait=True timeout=None
09:56:41,268 799     cassandra.pool                 WARNING  thread.py           :58   | test_enable_rbno_for_bootstrap[4]: Error attempting to reconnect to 127.0.13.4:9042, scheduling retry in 1.88 seconds: [Errno 111] Tried connecting to [('127.0.13.4', 9042)]. Last error: Connection refused
09:56:43,171 799     cassandra.pool                 WARNING  thread.py           :58   | test_enable_rbno_for_bootstrap[4]: Error attempting to reconnect to 127.0.13.4:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.13.4', 9042)]. Last error: Connection refused
09:56:43,505 799     cassandra.cluster              INFO     thread.py           :58   | test_enable_rbno_for_bootstrap[4]: Cassandra host 127.0.13.4:9042 removed
09:56:43,549 799     ccm                            DEBUG    cluster.py          :762  | test_enable_rbno_for_bootstrap[4]: node1: checking 
09:56:43,549 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:255  | test_enable_rbno_for_bootstrap[4]: Node node4 (host id b710f642-11da-4e01-9abc-309f7e173c4a) removed
09:56:43,549 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:313  | test_enable_rbno_for_bootstrap[4]: Scenario removenode completed. Start validation
09:56:43,549 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:295  | test_enable_rbno_for_bootstrap[4]: Validate that repair based node operation on the node node1
09:56:43,550 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:295  | test_enable_rbno_for_bootstrap[4]: Validate that repair based node operation on the node node2
09:56:43,550 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:295  | test_enable_rbno_for_bootstrap[4]: Validate that repair based node operation on the node node3
09:56:43,551 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:295  | test_enable_rbno_for_bootstrap[4]: Validate that repair based node operation on the node node4
09:56:43,552 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:309  | test_enable_rbno_for_bootstrap[4]: Start bootstrap scenario
09:56:43,552 799     repair_based_node_operations_test DEBUG    repair_based_node_operations_test.py:239  | test_enable_rbno_for_bootstrap[4]: Add new node in dc=None rack=None
09:56:43,579 799     cassandra.cluster              INFO     thread.py           :58   | test_enable_rbno_for_bootstrap[4]: Cassandra host 127.0.13.4:9042 removed
09:56:43,610 799     ccm                            DEBUG    cluster.py          :762  | test_enable_rbno_for_bootstrap[4]: node5: Starting scylla: args=['/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-rq8wvfiv/test/node5/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-rq8wvfiv/test/node5/conf/scylla.yaml', '--log-to-stdout', '1', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--enable-repair-based-node-ops', 'true', '--allowed-repair-based-node-ops', 'bootstrap', '--api-address', '127.0.13.5', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--overprovisioned', '--prometheus-address', '127.0.13.5', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=True wait_for_binary_proto=True
09:57:16,149 799     errors                         ERROR    conftest.py         :201  | test_enable_rbno_for_bootstrap[4]: test failed: 

```

The streaming logs you posted from node 4 are from the rebuild task (`Streaming plan for Rebuild-ks-index-6` etc.) (which succeeded, according to the above logs.)

Then node 4 was stopped, removed, and node 5 tried to boot.

Node 5 failed to boot because it got stuck on:
```
ERROR 2024-04-22 09:57:15,941 [shard 0:main] init - Startup failed: std::runtime_error (Failed to mark node as alive in 30000 ms, nodes=[127.0.13.5, 127.0.13.1, 127.0.13.3, 127.0.13.4, 127.0.13.2], live_nodes=[127.0.13.5, 127.0.13.1, 127.0.13.3, 127.0.13.2])
```

so yes, this is a duplicate of https://github.com/scylladb/scylladb/issues/17526. Closing

**Closed by kbr-scylla** 2024-06-20 11:41 UTC
Labels: triage/master, symptom/ci stability
