### ISSUE TITLE
Update requires all clustering keys to update

### ISSUE THREAD

**Issue by Phara0h** [scylladb/scylladb#8654] opened 2021-05-13 20:05 UTC
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.3
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

In your tests (https://github.com/scylladb/scylla/blob/68f69671b5cec493b6f7656919ab2d39fde606da/test/cql/cassandra_cql_test.result#L1365) and other documentation, you have examples of updates while only supplying the partition key and leaving out some or all of the clustering key. (similarly how select works) However, this seems not to be working.

### Example CQL

```sql
 CREATE TABLE people (
   id timeuuid,
   firstname ascii,
   middlename ascii,
   lastname ascii,
   state ascii,
   city ascii,
   age smallint
   PRIMARY KEY ((lastname, firstname), id, state, city)
 ) WITH CLUSTERING ORDER BY(id DESC);

CREATE INDEX people_by_id ON people(id);
```

All the falling examples fail:
#### By index

```sql
UPDATE people SET age = 0 where id = 9d697091-6190-11eb-9efe-303833303030;
```
```sql
UPDATE people SET age = 0 where id = 9d697091-6190-11eb-9efe-303833303030 IF EXISTS;
```
```sql
BEGIN BATCH
    UPDATE people SET age = 0 where id = 9d697091-6190-11eb-9efe-303833303030;
APPLY BATCH;
```
```sql
BEGIN BATCH
    UPDATE people SET age = 0 where id = 9d697091-6190-11eb-9efe-303833303030 IF EXISTS;
APPLY BATCH;
```
#### By full partition key
```sql
UPDATE people SET age = 0 where lastname = 'SMITH' and firstname='JOHN';
```
```sql
UPDATE people SET age = 0  where lastname = 'SMITH' and firstname='JOHN' IF EXISTS;
```
```sql
BEGIN BATCH
    UPDATE people SET age = 0  where lastname = 'SMITH' and firstname='JOHN';
APPLY BATCH;
```
```sql
BEGIN BATCH
    UPDATE people SET age = 0 where id = where lastname = 'SMITH' and firstname='JOHN' IF EXISTS;
APPLY BATCH;
```

**Comment by dekimir** [comment] 2021-05-13 20:07
@Phara0h Can you please share what you mean by "seems not to be working"?  Are you getting an error message?

**Comment by Phara0h** [comment] 2021-05-13 20:09
> @Phara0h Can you please share what you mean by "seems not to be working"? Are you getting an error message?

Yes error message on everyone

### by index

```bash
ERROR: 
com.datastax.driver.core.exceptions.InvalidQueryException: 
Missing mandatory PRIMARY KEY part state 
```

### by full partition 
```bash
ERROR: 
com.datastax.driver.core.exceptions.InvalidQueryException: 
Missing mandatory PRIMARY KEY part id 
```

**Comment by dekimir** [comment] 2021-05-13 20:29
Note that the test you quote updates a _static_ column, while your examples attempt to update a regular column.  The LWT documentation states:
> If your data selection fetches multiple rows, your IF condition cannot be ambiguous, meaning it can not evaluate to TRUE for one row and to FALSE for another. This includes statements which restrict only the partition key, and not the clustering key, or the partition key and multiple clustering keys (pk = ? and ck IN (?, ?, ?). In these instances, only the conditions on static cells are accepted.

**Comment by dekimir** [comment] 2021-05-13 20:34
Thinking about it more, this isn't related to LWT.  Even regular updates can specify only the partition key when they're updating static columns.  That's because static column have only one value per partition, shared across all the rows in that partition.

**Comment by Phara0h** [comment] 2021-05-14 16:01
Can change this to a feature request then please since update should work exactly the same way as to select and delete does.

**Comment by Phara0h** [comment] 2021-05-14 16:16
Seems it would be a rather easy fix. https://github.com/scylladb/scylla/blob/f186de909d461003e83ce24f256c2fb6884b6004/cql3/statements/update_statement.cc#L115

**Comment by Phara0h** [comment] 2021-05-14 16:33
@dekimir Seems to also be only in here because of thrift and even in the comment above the only line that uses it says it should not be in here. https://github.com/scylladb/scylla/blob/7d2df8a9bc282f084eaae22497288c39316b6075/cql3/statements/modification_statement.cc#L433

**Comment by dekimir** [comment] 2021-05-14 16:55
> Can change this to a feature request then please since update should work exactly the same way as to select and delete does.

Not quite the same way, as update has the `SET` part.  What happens if the statement tries to `SET` a clustering column in this scenario?

**Comment by Phara0h** [comment] 2021-05-14 19:35
> > Can change this to a feature request then please since update should work exactly the same way as to select and delete does.
> 
> Not quite the same way, as the update has the `SET` part. What happens if the statement tries to `SET` a clustering column in this scenario?

So for this example state is  a  clustering key

| lastname | firstname | id | state | city | age |
|----------|-----------|----|-------|------|-----|
| SMITH    | JOHN      | 1  | CA    | a    | 12  |
| SMITH    | JOHN      | 2  | MI    | b    | 13  |
| SMITH    | JOHN      | 3  | FL    | c    | 14  |

```cql
UPDATE people SET state = 'FL' where lastname = 'SMITH' and firstname='JOHN';
```

| lastname | firstname | id | state | city | age |
|----------|-----------|----|-------|------|-----|
| SMITH    | JOHN      | 1  | FL    | a    | 12  |
| SMITH    | JOHN      | 2  | FL    | b    | 13  |
| SMITH    | JOHN      | 3  | FL    | c    | 14  |

**Comment by dekimir** [comment] 2021-05-15 00:32
>  What happens if the statement tries to `SET` a clustering column in this scenario?

This question is actually irrelevant; SET rejects any primary-key columns:
https://github.com/scylladb/scylla/blob/68f69671b5cec493b6f7656919ab2d39fde606da/cql3/statements/update_statement.cc#L398-L400

And that's a good thing, since otherwise you could make a row's primary key equal to some other row's primary key, which violates basic assumptions.  If we keep that restriction, I think this is a reasonable feature request.

**Comment by nyh** [comment] 2022-12-11 14:45
Looking at the above discussion, this is not a bug report but a feature request. Today, an `UPDATE` can only work on a single row. Whereas `SELECT` may scan the entire table and potentially return many matching rows, `UPDATE` currently can't. It can't scan all the items in the database, and replace the "state" column in each one with the value "FL" as in your example.

In issue https://github.com/scylladb/scylladb/issues/10593 there was a wish that we can do such a scan for a `DELETE`, and here there is a wish that we allow the same thing for `UPDATE`. All the implementation details which I commented on that issue are relevant for this one as well.

Note that the specific example you tried to do, setting `state = FL`, will not be allowed, even if scanning is added the UPDATE. As @dekimir noted, "state" is a primary key column, so it cannot be modified by an UPDATE. Updating a primary key column means deleting the old row (and first we need to read the existing value of the key to know what it was!) and overwriting a new row (with all the columns that the old row had, so we need to read the entire old row). This is similar to what materialized-views do, and is **not** supported even for a single-item modification, and there are big questions on how to do this properly. If we want **that** part of the requested feature, we should have a separate issue for it.

**Comment by nyh** [comment] 2023-01-30 15:30
Closing as a duplicate of #3230

**Comment by nyh** [comment] 2023-06-25 13:19
Half a year ago, I said "closing as a duplicate" but forgot to actually close it... Doing it now.

**Closed by nyh** 2023-06-25 13:19 UTC
Labels: enhancement, CQL
