### ISSUE TITLE
WHERE IN is much slower than individual selects.

### ISSUE THREAD

**Issue by cc32d9** [scylladb/scylladb#13533] opened 2023-04-17 07:59 UTC
The database schema:  https://github.com/EOSChronicleProject/chronos/blob/main/cql/create_tables.cql

I'm testing it on a cluster of 4 servers in the same datacenter, with replication factor 1. There's about 4TB of data in total.

WHERE SEQ IN (...)  always times out, while individual selects work fine and quick. There is a secondary index by seq, and the seq value is unique for every row.

```
chronos_rw@cqlsh:chronos> select seq, block_num from transactions where seq in (48516741563, 8618039448, 49824363875);
ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for chronos.transactions - received only 0 responses from 1 CL=ONE." info={'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}                    

chronos_rw@cqlsh:chronos> select seq, block_num from transactions where seq = 48516741563;

 seq         | block_num
-------------+-----------
 48516741563 | 183729020

(1 rows)
chronos_rw@cqlsh:chronos> select seq, block_num from transactions where seq = 8618039448;

 seq        | block_num
------------+-----------
 8618039448 | 124638271

(1 rows)
chronos_rw@cqlsh:chronos> select seq, block_num from transactions where seq = 49824363875;

 seq         | block_num
-------------+-----------
 49824363875 | 185716149

(1 rows)
```

**Comment by cc32d9** [comment] 2023-04-21 06:12
I restarted the test with an empty database and replication factor 3 across four servers. While the database is small, I get response on this query, but with a warning:

Warnings :
This query should use ALLOW FILTERING and will be rejected in future versions.

**Comment by nyh** [comment] 2023-04-23 12:34
This is a duplicate of issue #5545 which wasn't well-described so I'm tempted to close that issue and keep this one.

 There things you are seeing come from the following combination of features/bugs:
1. Cassandra doesn't support using IN with any non-key column (not even an indexed column), and gives the error message "IN predicates on non-primary-key columns (c) is not yet supported". So your query wouldn't even worked on Cassandra.
2.ScyllaDB **does not** have this limitation, and the IN is allowed - but it is done as a full table scan with filtering, NOT using the index, which is very slow as you noticed.
3. In #7608 I reported that it's a bug for a query to do this full-table scan without requiring ALLOW FILTERING. Unfortunately the fix (commit 2f28f68e84b76e7d3eb3ce78b6200ec3f0c65ca9) was to make this into a **warning** instead of an error (as usual for ALLOW FILTERING) . I think that this was a mistake, because warning can easily be missed - and as you noticed, when the query times out (as is expected in this case) you don't even get the warning.

The best fix for this will be to implement the IN efficiently, merging results from different index partitions similar to the way we merge results from different base-table partitions with IN on primary key.

But even before that, I think we should consider changing the default of `strict_allow_filtering` to true - to make the missing ALLOW FILTERING in this case an error instead of a warning. Two years have passed since we made it into a warning in 2f28f68e84b76e7d3eb3ce78b6200ec3f0c65ca9.

**Comment by cc32d9** [comment] 2023-04-23 15:04
well I don't want an operation that requires a full scan, I modified the client to use EQ conditions and use as many SELECTs as there are rows to query.

But I find it odd that the IN operator cannot use the index correctly.

**Comment by nyh** [comment] 2023-08-21 09:19
In  https://stackoverflow.com/q/76942005/8891224 a user noticed that we have the same problem also with **local** secondary indexes - an "IN" causes slow filtering of the entire base table to be used or required - instead of performing the query efficiently on the secondary index as expected. I'm adding a new test case for this:

* `test_allow_filtering.py`::`test_allow_filtering_local_index_in`.

**Comment by nyh** [comment] 2024-11-04 14:45
This issue is actually the mixture of two separate issues, so I am closing this in favor of these two separate issues:

* We want the IN clause to be allowed on an indexed column. This is an enhancement request - this feature also doesn't exist in Cassandra. Opened a new issue for this: https://github.com/scylladb/scylladb/issues/21430
* If we delay the above for a long time, we at least want an attempt to do a IN on an indexed columns without ALLOW FILTERING to be an error, not inefficient filtering. This is issue is https://github.com/scylladb/scylladb/issues/12908 (and has a duplicate, https://github.com/scylladb/scylladb/issues/14164).

**Closed by nyh** 2024-11-04 14:45 UTC
Labels: bug, symptom/performance, user request, area/cql, area/sec index
