### ISSUE TITLE
read load failing after one node upgrade [bad_enum_set_mask (Bit mask contains invalid enumeration indices.)]

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#15795] opened 2023-10-22 22:25 UTC
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

in rolling upgrade test after the first node is upgraded
we get the following error from cassandra-stress:

```
2023-10-22 09:35:10.561: (CassandraStressLogEvent Severity.CRITICAL) period_type=one-time event_id=3b20cd78-2093-4adb-abc5-ca3b740ee565: type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=980 node=Node rolling-upgrade--ubuntu-focal-loader-node-4f8aacaf-1 [54.195.134.36 | 10.4.2.60] (seed: False)
java.io.IOException: Operation x10 on key(s) [39333530303431353630]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
```

the stress command:

```
cassandra-stress read no-warmup cl=QUORUM n=10100200 -schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=3) compression=DeflateCompressor' -mode cql3 native compression=none -rate threads=1000 -pop seq=1..10100200 -log interval=5
```

at the time of the failure all of nodes with the older version shows lot of those lines in their logs:
```
Oct 22 09:30:13.260802 rolling-upgrade--ubuntu-focal-db-node-4f8aacaf-2 scylla[6402]:  [shard 1] rpc - client 10.4.1.34:59711 msg_id 283795:  caught exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
```

## Impact

load is failing during an upgrade

## How frequently does it reproduce?

this happened on multiple cases of rolling upgrade

## Installation details

Kernel Version: 5.15.0-1036-aws
Scylla version (or git commit hash): `5.3.0~rc0-20230523.3c3621db072d` with build-id `78cb9caaf1cdd0b37c3a38fa83548e6c4e3d4ab4`
Target Scylla version (or git commit hash): `5.5.0~dev-20231022.f181ac033af4` with build-id `09574400f999dabb68258ca49ef5f16bcad908ab`

Cluster size: 4 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-4f8aacaf-4 (54.194.140.51 | 10.4.1.100) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-4f8aacaf-3 (54.229.164.15 | 10.4.0.63) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-4f8aacaf-2 (3.250.222.16 | 10.4.0.195) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-4f8aacaf-1 (52.211.76.111 | 10.4.1.34) (shards: 7)

OS / Image: `ami-0895041392296aa54` (aws: undefined_region)

Test: `rolling-upgrade-ami-test`
Test id: `4f8aacaf-7aea-4bc1-ba2c-d13630e09aab`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d60806e7b31f0e9351674ba718a5cdac8df07b86/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 4f8aacaf-7aea-4bc1-ba2c-d13630e09aab`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=4f8aacaf-7aea-4bc1-ba2c-d13630e09aab)
- Show all stored logs command: `$ hydra investigate show-logs 4f8aacaf-7aea-4bc1-ba2c-d13630e09aab`

## Logs:
- **db-cluster-4f8aacaf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4f8aacaf-7aea-4bc1-ba2c-d13630e09aab/20231022_093957/db-cluster-4f8aacaf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4f8aacaf-7aea-4bc1-ba2c-d13630e09aab/20231022_093957/db-cluster-4f8aacaf.tar.gz)
- **sct-runner-events-4f8aacaf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4f8aacaf-7aea-4bc1-ba2c-d13630e09aab/20231022_093957/sct-runner-events-4f8aacaf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4f8aacaf-7aea-4bc1-ba2c-d13630e09aab/20231022_093957/sct-runner-events-4f8aacaf.tar.gz)
- **sct-4f8aacaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4f8aacaf-7aea-4bc1-ba2c-d13630e09aab/20231022_093957/sct-4f8aacaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4f8aacaf-7aea-4bc1-ba2c-d13630e09aab/20231022_093957/sct-4f8aacaf.log.tar.gz)
- **loader-set-4f8aacaf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4f8aacaf-7aea-4bc1-ba2c-d13630e09aab/20231022_093957/loader-set-4f8aacaf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4f8aacaf-7aea-4bc1-ba2c-d13630e09aab/20231022_093957/loader-set-4f8aacaf.tar.gz)
- **monitor-set-4f8aacaf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4f8aacaf-7aea-4bc1-ba2c-d13630e09aab/20231022_093957/monitor-set-4f8aacaf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4f8aacaf-7aea-4bc1-ba2c-d13630e09aab/20231022_093957/monitor-set-4f8aacaf.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/185/)
[Argus](https://argus.scylladb.com/test/cc80460f-2278-4fe5-8781-1776502bc7e1/runs?additionalRuns[]=4f8aacaf-7aea-4bc1-ba2c-d13630e09aab)
</details>

**Comment by mykaul** [comment] 2023-10-23 11:08
@piodul - could it be related to your latest changes? Please look at it.

**Comment by kbr-scylla** [comment] 2023-10-24 14:47
> Scylla version (or git commit hash): 5.3.0~rc0-20230523.3c3621db072d

5.3?

**Comment by mykaul** [comment] 2023-10-24 14:48
> > Scylla version (or git commit hash): 5.3.0~rc0-20230523.3c3621db072d
> 
> 5.3?

That was the last tagged image before the move to 5.4 and on - an old master, post 5.2 essentially.

**Comment by kbr-scylla** [comment] 2023-10-24 14:51
In theory, `master` might get an additional schema/cluster feature, which is then reverted. (This happened with my group 0 schema versioning patch).

Upgrades from a pre-revert commit to a post-revert commit will not work in that case. This is expected.

I'm having trouble finding the commit for that version, but I'll try and see if it doesn't contain some extra cluster/schema feature that was later reverted.

But generally, we should be testing upgrades from real releases, not from some in-between `master` state.

**Comment by kbr-scylla** [comment] 2023-10-24 15:00
Ok, there was no reverted schema feature.

Also apparently the error comes on CQL read path, it's most likely not related to schema features. Could be some `enum_set` that has changed recently in a backwards-incompatible way, used somewhere on the read path...

**Comment by mykaul** [comment] 2023-10-24 15:35
> But generally, we should be testing upgrades from real releases, not from some in-between `master` state.

Agreed. @fruch - let's fix it. Latest 5.2.x.

**Comment by fruch** [comment] 2023-10-24 16:48
> > But generally, we should be testing upgrades from real releases, not from some in-between `master` state.
> 
> Agreed. @fruch - let's fix it. Latest 5.2.x.

For a while now it was test with 5.3-rc0 as a base version (basically since 5.3-rc0 was created) 
I didn't a fix yesterday to make sure we don't ever pick 5.3
regardless of that fix, we now have 5.4-rc0, and that would be use as a base version, when testing in master
the path between 5.2 - 5.4, would be cover on 5.4 testing, hopefully there's no major issues there

**Comment by mykaul** [comment] 2023-10-25 07:01
> regardless of that fix, we now have 5.4-rc0, and that would be use as a base version, when testing in master
> the path between 5.2 - 5.4, would be cover on 5.4 testing, hopefully there's no major issues there

For the time being, we need to test 5.2 -> master. Once we reach higher RCs in 5.4, we can switch to it.

**Comment by fruch** [comment] 2023-10-25 07:08
> > regardless of that fix, we now have 5.4-rc0, and that would be use as a base version, when testing in master
> > the path between 5.2 - 5.4, would be cover on 5.4 testing, hopefully there's no major issues there
> 
> For the time being, we need to test 5.2 -> master. Once we reach higher RCs in 5.4, we can switch to it.

we can hard code it for master run to 5.2 for the time being (and probably gonna forget about for the next version)
but "Once we reach higher RCs in 5.4, we can switch to it." is kind of not something we can automate.

**Comment by mykaul** [comment] 2023-10-25 07:09
> > > regardless of that fix, we now have 5.4-rc0, and that would be use as a base version, when testing in master
> > > the path between 5.2 - 5.4, would be cover on 5.4 testing, hopefully there's no major issues there
> > 
> > 
> > For the time being, we need to test 5.2 -> master. Once we reach higher RCs in 5.4, we can switch to it.
> 
> we can hard code it for master run to 5.2 for the time being (and probably gonna forget about for the next version) but "Once we reach higher RCs in 5.4, we can switch to it." is kind of not something we can automate.

I'll remind you.

**Comment by fruch** [comment] 2023-10-25 09:43
Anyhow here are the "good news":

this is happening also on the upgrade from 5.2 -> master:

On Azure:

## Installation details

Kernel Version: 5.15.0-1045-aws
Scylla version (or git commit hash): `5.2.9-20230920.5709d0043978` with build-id `4923719a923189f5e71d630fe5958d74f3146339`
Target Scylla version (or git commit hash): `5.5.0~dev-20231025.6c90d166cc14` with build-id `d113287c78e0c0c2e3b0b55952b9cf9cb7b9d8f9`




Cluster size: 4 nodes (im4gn.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-62d0be27-4 (3.250.54.119 | 10.4.0.229) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-62d0be27-3 (34.242.247.45 | 10.4.2.218) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-62d0be27-2 (52.213.85.254 | 10.4.1.23) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-62d0be27-1 (34.249.173.42 | 10.4.2.65) (shards: 7)


OS / Image: `ami-0a611373668f0980b` (aws: undefined_region)

Test: `rolling-upgrade-ami-arm-test`
Test id: `62d0be27-2fb0-468d-8f8c-cd253ac30e20`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-arm-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a5c997dcdd51d85737ae0e748c418a367128382f/test-cases/upgrades/rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 62d0be27-2fb0-468d-8f8c-cd253ac30e20`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=62d0be27-2fb0-468d-8f8c-cd253ac30e20)
- Show all stored logs command: `$ hydra investigate show-logs 62d0be27-2fb0-468d-8f8c-cd253ac30e20`


## Logs:
- **db-cluster-62d0be27.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62d0be27-2fb0-468d-8f8c-cd253ac30e20/20231025_085735/db-cluster-62d0be27.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62d0be27-2fb0-468d-8f8c-cd253ac30e20/20231025_085735/db-cluster-62d0be27.tar.gz)
- **sct-runner-events-62d0be27.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62d0be27-2fb0-468d-8f8c-cd253ac30e20/20231025_085735/sct-runner-events-62d0be27.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62d0be27-2fb0-468d-8f8c-cd253ac30e20/20231025_085735/sct-runner-events-62d0be27.tar.gz)
- **sct-62d0be27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62d0be27-2fb0-468d-8f8c-cd253ac30e20/20231025_085735/sct-62d0be27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62d0be27-2fb0-468d-8f8c-cd253ac30e20/20231025_085735/sct-62d0be27.log.tar.gz)
- **loader-set-62d0be27.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62d0be27-2fb0-468d-8f8c-cd253ac30e20/20231025_085735/loader-set-62d0be27.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62d0be27-2fb0-468d-8f8c-cd253ac30e20/20231025_085735/loader-set-62d0be27.tar.gz)
- **monitor-set-62d0be27.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62d0be27-2fb0-468d-8f8c-cd253ac30e20/20231025_085735/monitor-set-62d0be27.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62d0be27-2fb0-468d-8f8c-cd253ac30e20/20231025_085735/monitor-set-62d0be27.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-arm-test/77/)
[Argus](https://argus.scylladb.com/test/8e5f044d-57c2-43ad-8fe8-ac75a11a422d/runs?additionalRuns[]=62d0be27-2fb0-468d-8f8c-cd253ac30e20)
</details>

**Comment by fruch** [comment] 2023-10-25 09:44
Also happening on Azure:

## Installation details

Kernel Version: 5.15.0-1050-azure
Scylla version (or git commit hash): `5.2.9-20231020.6798f9676ffa` with build-id `7225971233974d5ac4122a8b7353f92809631b55`
Target Scylla version (or git commit hash): `5.5.0~dev-20231025.6c90d166cc14` with build-id `1eb98d5628e8fc321376be9a8bf6ddff1d6054c4`




Cluster size: 4 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-a4f61daf-eastus-4 (172.171.251.130 | 10.0.0.8) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-a4f61daf-eastus-3 (172.171.251.78 | 10.0.0.7) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-a4f61daf-eastus-2 (172.171.250.160 | 10.0.0.6) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-a4f61daf-eastus-1 (172.171.250.151 | 10.0.0.5) (shards: 7)


OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCYLLA-IMAGES/providers/Microsoft.Compute/images/scylla-5.2.9-x86_64-2023-10-22T23-33-54` (azure: undefined_region)

Test: `rolling-upgrade-azure-image-test`
Test id: `a4f61daf-aa27-4ff5-a87a-01395b3f6851`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-azure-image-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a5c997dcdd51d85737ae0e748c418a367128382f/test-cases/upgrades/rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor a4f61daf-aa27-4ff5-a87a-01395b3f6851`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a4f61daf-aa27-4ff5-a87a-01395b3f6851)
- Show all stored logs command: `$ hydra investigate show-logs a4f61daf-aa27-4ff5-a87a-01395b3f6851`


## Logs:
- **db-cluster-a4f61daf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a4f61daf-aa27-4ff5-a87a-01395b3f6851/20231025_090710/db-cluster-a4f61daf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a4f61daf-aa27-4ff5-a87a-01395b3f6851/20231025_090710/db-cluster-a4f61daf.tar.gz)
- **sct-runner-events-a4f61daf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a4f61daf-aa27-4ff5-a87a-01395b3f6851/20231025_090710/sct-runner-events-a4f61daf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a4f61daf-aa27-4ff5-a87a-01395b3f6851/20231025_090710/sct-runner-events-a4f61daf.tar.gz)
- **sct-a4f61daf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a4f61daf-aa27-4ff5-a87a-01395b3f6851/20231025_090710/sct-a4f61daf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a4f61daf-aa27-4ff5-a87a-01395b3f6851/20231025_090710/sct-a4f61daf.log.tar.gz)
- **loader-set-a4f61daf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a4f61daf-aa27-4ff5-a87a-01395b3f6851/20231025_090710/loader-set-a4f61daf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a4f61daf-aa27-4ff5-a87a-01395b3f6851/20231025_090710/loader-set-a4f61daf.tar.gz)
- **monitor-set-a4f61daf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a4f61daf-aa27-4ff5-a87a-01395b3f6851/20231025_090710/monitor-set-a4f61daf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a4f61daf-aa27-4ff5-a87a-01395b3f6851/20231025_090710/monitor-set-a4f61daf.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-azure-image-test/47/)
[Argus](https://argus.scylladb.com/test/80412f0e-69be-4414-9913-9e124760b7b1/runs?additionalRuns[]=a4f61daf-aa27-4ff5-a87a-01395b3f6851)
</details>

**Comment by fruch** [comment] 2023-10-25 09:45
other jobs are still running with 5.2 -> master,
I'll follow with their status, once they would finish

**Comment by fruch** [comment] 2023-10-25 09:47
3 more cases failed on the same exact issue...

so we can say now, rolling upgrade for 5.4/master is blocked, by this issue

**Comment by fruch** [comment] 2023-10-25 09:54
seems like it somewhere between those versions:
-5.4.0~dev-20231006.498e3ec435be
-5.5.0~dev-20231022.f181ac033af4

**Comment by kbr-scylla** [comment] 2023-10-25 10:02
Thanks @fruch 
I'll ask @patjed41 to investigate, or me if I find time today

**Comment by kbr-scylla** [comment] 2023-10-25 10:15
`git log 498e3ec435be..f181ac033af4 --oneline --first-parent`
(`--first-parent` to skip branches, showing only Merge commits or single-commit patchsets)

```
f181ac033a Merge 'tools/nodetool: implement additional commands, part 2/N' from Botond Dénes
19fc01be23 Merge 'Sanitize API -> task_manager dependency' from Pavel Emelyanov
ad90bb8d87 replica/database: remove "streaming" from dirty memory metric description
fbcd667030 replica: keyspace::create_replication_strategy: remove a redundant parameter
11d7cadf0d install-dependencies.sh: drop java deps
059d647ee5 test/pylib: scylla_cluster: protect `ScyllaCluster.stop` with a lock
80c656a08b types: use more readable error message when serializing non-ASCII string
0c69a312db Update seastar submodule
899ecaffcd test: tablets: Enable for verbose logging in test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode
fded314e46 sstables: Fix update of tombstone GC settings to have immediate effect
a6e68d8309 build: cmake: move message/* into message/CMakeLists.txt
60145d9526 Merge 'build: extract code fragments into functions' from Kefu Chai
39966e0eb1 Merge 'build: cmake: pass -dynamic-linker to ld' from Kefu Chai
c256cca6f1 cql3/expr: add more comments in expression.hh
b105be220b build: cmake: add join_node.idl.hh to CMake
2a7932efa1 alternator: fix DeleteTable return values to match DynamoDB's
ec94cc9538 Merge 'test: set use_uuid to true by default in sstables::test_env ' from Kefu Chai
7d5e22b43b replica: memtable: don't forget memtable memory allocation statistics
c8cb70918b sstable: drop unused parse() overload for deletion_time
f3dc01c85e Merge 'Enlight sstable_directory construction' from Pavel Emelyanov
274cf7a93a doc:remove upgrade guides for unsupported versions
f69a44bb37 test/object_store: redirect to STDOUT and STDERR
b340bd6d9e release: prepare for 5.5.0-dev
f7e269ccb8 Merge 'Progress of compaction executors' from Aleksandra Martyniuk
c1486fee40 Merge 'commitlog: drop truncation_records after replay' from Petr Gusev
f80fff3484 gossip: remove unused STATUS_LEAVING gossiper status
7f81957437 Merge 'Initialize datadir for system and non-system keyspaces the same way' from Pavel Emelyanov
51466dcb23 docs: add latest option to aws_images extension
203f41dc99 sstable: improve descriptions of capped.*deletion_time
9bc0a9f95e mutation: do not include unused header
dfffc022da Merge 'doc: doc: remove recommended image upgrade with OS from previous releases' from Anna Stuchlik
9d9fe57efa doc: remove recommended image upgrade with OS
f42eb4d1ce Merge 'Store and propagage GC timestamp markers from commitlog' from Calle Wilund
7718f76ecd doc: remove outdated info from Materialized Views
77b96f7748 main.cc: do not cast hours to milliseconds
7dcee7de02 test/pylib: implement `expected_error` for decommission and removenode
031ff755ce test/sstable: verify sstables::parse_path()
39789b6527 main.cc: ARM build fix
58d94a54a3 scylla_raid_setup: faillback to other paths when UUID not avialable
0aef0f900b Merge 'truncation records refactorings' from Petr Gusev
da04fea71e compaction: Fix key estimation per sstable to produce efficient filters
0ce9db2329 repair: throw abort_requested_exception when abort is requested
19e724822d test.py: pass self.suite.scylla_env to pytest process
9b1dfad51c main.cc: disable stall detector for debug ARM builds
055f061706 test: handle fast execution of test_user_function_filtering
accac7efd8 test: test_tablets.py: Enable verbose logging
940e44f887 db/view: change log level of failed view updates to WARN
41c80929eb Update tools/cqlsh submodule
5a10bd44bf test_storage_service: use new_test_snapshot fixture
35849fc901 Revert "Merge 'Don't calculate hashes for schema versions in Raft mode' from Kamil Braun"
05ede7a042 test/pylib: always return a response from `put_json`
4e6fe34501 tests: Synchronize boost logger for multithreaded tests in sstable_directory_test
765e193122 Merge 'db/hints: Modernize manager' from Dawid Mędrek
0ea0982590 Merge 'test/pylib: better code consistency, less boilerplate' from Kamil Braun
2a81b2e49a types: Avoid unneeded copy in simple_date_type_impl::from_sstring()
8c03eeb85d Merge 'Sanitize hints API handlers and remove proxy from http context' from Pavel Emelyanov
854188a486 Merge 'database, storage_proxy: Reconcile pages with dead rows and partitions incrementally' from Botond Dénes
197b7590df Update tools/jmx submodule
ee57f69b17 Update tools/java submodule
75109e9519 cql3: Fix invalid JSON parsing for JSON objects with ASCII keys
e600f35d1e Merge 'logalloc, reader_concurrency_semaphore: cooperate on OOM kills' from Botond Dénes
967faa97e4 proxy: Coroutinize start_hints_manager()
96787ec0a5 Merge 'Do not keep excessive info on sstables::entry_descriptor' from Pavel Emelyanov
```

**Comment by patjed41** [comment] 2023-10-30 16:03
The regression appeared in 854188a486.

Upgrading from 854188a486's parent commit to 854188a486 is sufficient to see a lot of lines like
```
INFO  2023-10-30 16:06:53,960 [shard 0:stat] rpc - client 127.0.0.1:58185 msg_id 4:  caught exception while processing a message: bad_enum_set_mask (Bit mask contains invalid enumeration indices.)
```
on all not upgraded nodes.

More precisely, on my local machine, I:
- start a 4-node cluster with all nodes built on the 854188a486's parent commit,
- execute the stress command from the issue description with a single change -- `read` -> `write`,
- upgrade one node node to 854188a486,
- execute the stress command from the issue description.

The error messages reported in the issue suggested that an `enum_set` modification could have caused the regression. After browsing the commits above, I noticed that only two commits modified some `enum_set`:  35849fc901 and 854188a486. 35849fc901 didn't look like a culprit because it reverted the changes introduced after 5.2. So, from the 5.2 -> master upgrade perspective, these changes never existed. When 854188a486 became the only suspect, I managed to confirm it using a reproducer described above.

From my understanding, the regression appeared because 854188a486 added a new variant to `partition_slice::option_set` that is not protected by a cluster feature.

**Comment by kbr-scylla** [comment] 2023-10-30 16:18
Thanks @patjed41.

Reassigned to @denesb.

We probably need to revert the change (note it ended up on 5.4 branch so there as well) or introduce a cluster feature to protect the new `option_set` entry from being used until the entire cluster upgrades)

**Comment by denesb** [comment] 2023-10-31 06:38
> From my understanding, the regression appeared because [854188a](https://github.com/scylladb/scylladb/commit/854188a486142be4dd9ba51c388bdc9add69fc17) added a new variant to `partition_slice::option_set` that is not protected by a cluster feature.

The addition to the option-set *is* protected by a cluster feature. Maybe there is a code-path which didn't check the feature. Let me check.

**Comment by denesb** [comment] 2023-10-31 06:45
Looks like I remembered wrong, there is no cluster feature indeed. I will prepare a fix shortly.

**Comment by denesb** [comment] 2023-10-31 06:55
Fix here: https://github.com/scylladb/scylladb/pull/15890

**Comment by mykaul** [comment] 2023-11-05 12:31
This is blocking all upgrade tests (seen already 3 failures that has this issue).

**Comment by denesb** [comment] 2023-11-06 07:30
> This is blocking all upgrade tests (seen already 3 failures that has this issue).

The fix is blocked by some issue around features. Looks like features are broken. I reduced my patch to just adding the feature, and nodes were crashing in the tests.

**Comment by bhalevy** [comment] 2023-11-12 07:55
Hit in https://argus.scylladb.com/test/208f7671-2567-483e-ba9f-03d135cfe7b0/runs?additionalRuns[]=305ada15-244b-4877-bcbd-85305c2d85c1

**Comment by avikivity** [comment] 2023-11-12 18:18
@mykaul please don't add the backport candidate label to open issues, they only become candidates when they're closed.

**Comment by mykaul** [comment] 2023-11-12 18:52
> @mykaul please don't add the backport candidate label to open issues, they only become candidates when they're closed.

How can we ensure they are not lost (assuming I do not trust the bot to mark them) in the closed issues bucket?

**Closed** 2023-11-20 17:43 UTC
Labels: Regression, rolling-upgrades, P1, Release-Blocker, Requires-Backport-to-5.4

**Comment by denesb** [comment] 2023-11-21 07:49
Backport to 5.4. queued.
