### ISSUE TITLE
`repair_additional_test.py::TestRepairAdditional::test_repair_option_pr_dc_host` fails with tablets due to "expected pr repair to repair between 1200 to 1800 rows, but count is 2000"

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#18243] opened 2024-04-16 03:42 UTC
```
AssertionError: expected pr repair to repair between 1200 to 1800 rows, but count is 2000
  rows: [Row(key='k2244', c1='value1', c2='value2'), Row(key='k1912', c1='value1', c2='value2'), Row(key='k1925', c1='value1', c2='value2'), Row(key='k2948', c1='value1', c2='value2'), Row(key='k1971', c1='value1', c2='value2'), Row(key='k1775', c1='value1', c2='value2'), 
...
assert 2000 <= 1800
```
```
self = <repair_additional_test.TestRepairAdditional object at 0x7f5713c81450>

    @pytest.mark.dtest_debug
    def test_repair_option_pr_dc_host(self):
>       return self._repair_option_pr_dc_host_test()

repair_additional_test.py:2812: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
repair_additional_test.py:1019: in _repair_option_pr_dc_host_test
    self.assert_repair_option_pr_rows(session2, 1200, 1800, consistency_level=ConsistencyLevel.LOCAL_ONE)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <repair_additional_test.TestRepairAdditional object at 0x7f5713c81450>
session = <cassandra.cluster.Session object at 0x7f571318d990>, min_count = 1200
max_count = 1800, consistency_level = 10

    def assert_repair_option_pr_rows(self, session, min_count, max_count, consistency_level=ConsistencyLevel.ONE):
        select_query = SimpleStatement("SELECT * FROM cf", consistency_level=consistency_level)
        rows = list(session.execute(select_query))
        count_query = SimpleStatement("SELECT count(*) from cf", consistency_level=consistency_level)
        count = session.execute(count_query)[0][0]
        assert count == len(rows), f"count {count} must be equal to len(rows)\nrows: {rows}"
        logger.debug(f"Asserting pr repair count: {count} in [{min_count}..{max_count}]")
>       assert min_count <= count <= max_count, f"expected pr repair to repair between {min_count} to {max_count} rows, but count is {count}\nrows: {rows}"
E       AssertionError: expected pr repair to repair between 1200 to 1800 rows, but count is 2000
E         rows: [Row(key='k2244', c1='value1', c2='value2'), Row(key='k1912', c1='value1', c2='value2'), Row(key='k1925', c1='value1', c2='value2'), Row(key='k2948', c1='value1', c2='value2'), Row(key='k1971', c1='value1', c2='value2'), Row(key='k1775', c1='value1', c2='value2'),
...
E       assert 2000 <= 1800

repair_additional_test.py:840: AssertionError
```

[dtest-gw0.log](https://github.com/scylladb/scylladb/files/14986499/dtest-gw0.log)

[1713143656120_repair_additional_test.py TestRepairAdditional test_repair_option_pr_dc_host.zip](https://github.com/scylladb/scylladb/files/14986495/1713143656120_repair_additional_test.py.TestRepairAdditional.test_repair_option_pr_dc_host.zip)

we have similar test failure when testing 
` repair_additional_test.py::TestRepairAdditional::test_repair_option_pr` and `repair_additional_test.py::TestRepairAdditional::test_repair_option_pr_multi_dc` with tablets enabled. see https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/258/testReport/junit/repair_additional_test/TestRepairAdditional/FullDtest___full_split004___test_repair_option_pr/ and https://jenkins.scylladb.com/job/scylla-master/job/tablets/job/gating-dtest-release-with-tablets/33/testReport/repair_additional_test/TestRepairAdditional/FullDtest___full_split005___test_repair_option_pr_multi_dc/ . 

all of them can be reproduced with 

- scylladb: 223275b4d1e74b0164d568aa88c50b93a42cdb43
- scylla-dtest: e6a071560b90c7d633d004933d52f3f11649dacb

**Comment by tchaikov** [comment] 2024-04-16 03:45
@asias could you please take a look? i see you noted that this test did pass in 9d41fb9bcdd76694706e7512c137588befbfc98e.   is it possible that some recent change broke it?

**Comment by asias** [comment] 2024-04-16 06:33
I will take a look.

**Comment by tchaikov** [comment] 2024-04-24 06:17
created https://github.com/scylladb/scylla-dtest/pull/4183 to disable the impacted tests when testing w/ tablets.

**Comment by tchaikov** [comment] 2024-05-16 08:10
we now have a similar failure in `repair_additional_test.py::TestRepairAdditional::test_repair_option_pr_multi_dc`. 

```
AssertionError: expected pr repair to repair between 3150 to 5001 rows, but count is 3000
```

see https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/291/testReport/repair_additional_test/TestRepairAdditional/FullDtest___full_split004___test_repair_option_pr_multi_dc/

**Comment by tchaikov** [comment] 2024-05-16 08:12
see also https://github.com/scylladb/scylla-dtest/pull/4182

**Comment by tchaikov** [comment] 2024-05-16 08:13
@bhalevy and @asias , shall we increase the number of tablets?

**Comment by bhalevy** [comment] 2024-05-23 10:44
> @bhalevy and @asias , shall we increase the number of tablets?

That was already done in ce3f58afb588682ed32cacdffdfb337b3e91d262
We can close this issue

**Comment by tchaikov** [comment] 2024-05-27 14:46
the test is still failing with the same error. see https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/312/testReport/junit/repair_additional_test/TestRepairAdditional/FullDtest___full_split004___test_repair_option_pr_multi_dc/

```
AssertionError: expected pr repair to repair between 3150 to 5001 rows, but count is 3000
```

**Comment by bhalevy** [comment] 2024-05-27 14:58
That's caused by https://github.com/scylladb/scylladb/issues/17752 and fixed by https://github.com/scylladb/scylladb/pull/18784

**Closed** 2024-05-27 15:02 UTC
Labels: area/tablets
