### ISSUE TITLE
update_cluster_layout_tests.TestUpdateClusterLayout.test_remove_garbage_members_from_group0_after_abort_decommission[Announcing_that_I_have_left_the_ring-] failed

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#14654] opened 2023-07-12 06:34 UTC
Test log:
https://jenkins.scylladb.com/job/scylla-master/job/next/6249/artifact/dtest/logs-full.release.005/dtest-gw0.log
```
22:26:54,991 779     errors                         ERROR    conftest.py         :207  | test_remove_garbage_members_from_group0_after_abort_decommission[Announcing_that_I_have_left_the_ring-]: test failed: 
self = <update_cluster_layout_tests.TestUpdateClusterLayout object at 0x7f9964d57f50>
log_message = 'Announcing that I have left the ring'
is_removed_from_token_ring = False
fixture_dtest_setup = <dtest_setup.DTestSetup object at 0x7f98ccd83290>

    @pytest.mark.scylla_mode('!debug')
    @pytest.mark.parametrize("log_message,is_removed_from_token_ring",
                             [("left token ring", True),
                              ("Announcing that I have left the ring", False),
                              ("became a group 0 non-voter", False),
                              ("leaving token ring", False)],
                             ids=generate_test_name)
    def test_remove_garbage_members_from_group0_after_abort_decommission(self, log_message, is_removed_from_token_ring, fixture_dtest_setup):
        """Clean group0 from garbage after aborted decommission
    
        If decommission aborted when node left token ring but stay in group0,
        garbage nodes could affect on raft group0 functionality. Such host_id
        of the nodes have to be removed from group0.
        Decommission process is going to be aborted by kill scylla node.
    
        If decommission process finished fast or node was already removed
        from token ring and group0, verify that number of node in cluster
        less on 1 and all nodes are voters.
        """
        fixture_dtest_setup.allow_log_errors = True
        self.cluster.set_configuration_options(values={
            'ring_delay_ms': 3000})
        logger.debug("populating cluster with three nodes")
        cluster: ScyllaCluster = self.cluster
        cluster.set_configuration_options(
            values={"consistent_cluster_management": True})
        cluster.populate(3)
        logger.debug("starting cluster")
        cluster.start(wait_other_notice=True)
    
        node1 = cluster.nodelist()[0]
        node1, _, node3 = cluster.nodelist()
        node3_hostid = node3.hostid()
        stress_cmd = "write cl=QUORUM n=4000 -schema replication(factor=3) -col size=fixed(200) n=FIXED(5)"
        cluster.stress(stress_cmd.split())
    
        logger.debug("Verify group0 and token ring members are consistent")
        self.verify_group0_and_token_ring_members(node1, expected_num_of_members=3)
    
        logger.debug("Decommission node3 ...")
        mark = node3.mark_log()
        node3.nodetool("decommission", capture_output=False, wait=False)
        node3.watch_log_for(log_message, from_mark=mark)
        logger.debug("Abort decommission by killing the node")
        node3.stop(gently=False, wait=False)
    
        self.find_and_clean_garbage_from_group0(node1, node3_hostid, is_removed_from_token_ring)
    
        self.verify_group0_and_token_ring_members(node1, expected_num_of_members=2)
    
        logger.debug("Check that new node could be added to cluster")
        node = new_node(cluster)
>       node.start(wait_other_notice=True)
```
Failed node log:
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/2888/artifact/logs-full.release.003/1689114417995_update_cluster_layout_tests.py%3A%3ATestUpdateClusterLayout%3A%3Atest_remove_garbage_members_from_group0_after_abort_decommission%5BAnnouncing_that_I_have_left_the_ring-%5D/node4.log
`ERROR 2023-07-11 22:26:54,667 [shard 0] init - Startup failed: std::runtime_error (bootstrap[9b4aa676-86ca-4b78-aab5-0a7b978e147b]: Found pending node ops = {{127.0.42.1 -> {0c7fb069-eb9f-47b5-b3e8-8be5ba4afd15}}, {127.0.42.2 -> {0c7fb069-eb9f-47b5-b3e8-8be5ba4afd15}}}, reject bootstrap)`

**Comment by michoecho** [comment] 2023-07-12 06:48
Maybe refs https://github.com/scylladb/scylladb/issues/14614

**Comment by kbr-scylla** [comment] 2023-07-12 15:13
Note: the test was added to gating yesterday

**Comment by kbr-scylla** [comment] 2023-07-12 15:15
Ah, I already investigated this one.
Duplicate of: https://github.com/scylladb/scylla-dtest/issues/3256

This is a problem with the test, I described it here: https://github.com/scylladb/scylla-dtest/issues/3256#issuecomment-1600731601
@bhalevy we should take it off gating.

**Comment by kbr-scylla** [comment] 2023-07-12 15:16
> IMO not worth patching this code with topology-over-raft on the way.

**Comment by bhalevy** [comment] 2023-07-13 10:05
Duplicate of https://github.com/scylladb/scylla-dtest/issues/3256

**Closed by bhalevy** 2023-07-13 10:05 UTC
Labels: topology changes, CI-Stability
