### ISSUE TITLE
Significant fall down of operations per seconds during schema altering

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#7632] opened 2020-11-17 12:58 UTC
*Installation details*
Scylla version (or git commit hash): 4.4.dev-0.20201113.0a2adf4555
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): 
scylla_gce_image_id: ```https://www.googleapis.com/compute/alpha/projects/skilled-adapter-452/global/images/5053451839670644588```

Test longevity-10gb-3h, running with Scylla GCE image.

When nemesis add_drop_column started, requests served per instance were about 18-19K ops.

This nemesis performs altering table (add and drop columns) a few times, like:

```
< t:2020-11-16 13:04:14,549 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 ADD ( BCDSO7WO0Z bigint, K5H5UJPIVH inet, T9RJUNKCZ3 varchar, CKCFLDG0NX boolean );'...
< t:2020-11-16 13:04:24,305 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 DROP ( T9RJUNKCZ3, K5H5UJPIVH, BCDSO7WO0Z, CKCFLDG0NX );'...
< t:2020-11-16 13:04:38,863 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 ADD ( G6IGJI5UEA int );'...
< t:2020-11-16 13:05:07,533 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 DROP ( G6IGJI5UEA );'...
< t:2020-11-16 13:05:21,436 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 ADD ( PMPCK6KN8C date, OMKVWCGFXX timeuuid );'...
```

With starting of the schema altering operations per second significant fall down - to 2K ops per instance:

![Screenshot from 2020-11-17 14-41-08](https://user-images.githubusercontent.com/34435448/99391591-116d6000-28e3-11eb-9489-22aa917bae02.png)

Load per instance decreased:

![Screenshot from 2020-11-17 14-41-22](https://user-images.githubusercontent.com/34435448/99391623-1a5e3180-28e3-11eb-8bd4-a1413dd6e01f.png)

High cassandra-stress latency - up to 4 sec:

![Screenshot from 2020-11-17 14-41-39](https://user-images.githubusercontent.com/34435448/99391677-3235b580-28e3-11eb-86f6-5684100aef56.png)

Write timeouts:

![Screenshot from 2020-11-17 14-41-51](https://user-images.githubusercontent.com/34435448/99391728-4974a300-28e3-11eb-903f-0452c208961c.png)

In the log a lot of cassndra-stress WriteTimeoutExceptions.

[Monitor](http://34.75.180.18:3000/d/mws04FoMk/scylla-per-server-metrics-nemesis-master?orgId=1&from=1605531625692&to=1605532754558)

[Monitor snapshot](https://snapshot.raintank.io/dashboard/snapshot/WJqo73TQBa83joeAW7nkAtXM7s4xNoPT)

Jenkins job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/bentsi-staging/job/bentsi-longevity-3h/25/
Test id: 50d4252c-8c5a-47bb-beb3-d8b3d39f9716

**Comment by avikivity** [comment] 2020-11-17 13:11
If there was a large partition involved, this is well known.

**Comment by avikivity** [comment] 2020-11-17 13:12
Do you have reactor stalls?

**Comment by juliayakovlev** [comment] 2020-11-17 13:15
> Do you have reactor stalls?

No, I didn't find it in the log

**Comment by avikivity** [comment] 2020-11-17 13:35
Only a small amount of task quota violations in the statement class.

![image](https://user-images.githubusercontent.com/1017210/99396515-83957300-28ea-11eb-8c0e-9e670f55a086.png)

**Comment by avikivity** [comment] 2020-11-17 13:42
Somehow, even gossip used less cpu:

![image](https://user-images.githubusercontent.com/1017210/99397243-762cb880-28eb-11eb-9b73-daafd14cb79b.png)

**Comment by slivne** [comment] 2020-11-17 13:44
When schema is changed - prepared statements (related to that table only?)
will be invalidated and then have to be recreated

Is the alter on the table that cassandra-stress is sending traffic on ?

Checking the logs - can you see if the schema is synched fast / slow ?

I expect If we do multiple operations of alter and don't wait in between to
see that schema sync - this may cause sync to be slower especially if the
operations are on different nodes ...

I recall vaguely we discussed this in the past somewhere as well

**Comment by juliayakovlev** [comment] 2020-11-17 14:04
> When schema is changed - prepared statements (related to that table only?) will be invalidated and then have to be recreated Is the alter on the table that cassandra-stress is sending traffic on ?

No, it sent by nemesis

> Checking the logs - can you see if the schema is synched fast / slow ? 

It's hard to say, because we have no indication which alter operation this print about, but assume that it takes time.
Example (cut from log):
```
< t:2020-11-16 13:04:14,549 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 ADD ( BCDSO7WO0Z bigint, K5H5UJPIVH inet, T9RJUNKCZ3 varchar, CKCFLDG0NX boolean );'...
< t:2020-11-16 13:04:18,164 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:04:19,198 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Schemas match
< t:2020-11-16 13:04:19,199 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:04:24,305 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 DROP ( T9RJUNKCZ3, K5H5UJPIVH, BCDSO7WO0Z, CKCFLDG0NX );'...
< t:2020-11-16 13:04:26,286 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:04:36,476 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:04:38,863 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 ADD ( G6IGJI5UEA int );'...
< t:2020-11-16 13:04:42,297 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:04:52,440 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:05:07,533 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 DROP ( G6IGJI5UEA );'...
< t:2020-11-16 13:05:08,951 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:05:19,029 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:05:21,436 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 ADD ( PMPCK6KN8C date, OMKVWCGFXX timeuuid );'...
< t:2020-11-16 13:05:22,898 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:05:38,054 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 DROP ( PMPCK6KN8C );'...
< t:2020-11-16 13:05:39,982 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:05:50,061 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:05:52,621 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 ADD ( XXG6WP6VDB ascii, PZ5IOLH6FU double );'...
< t:2020-11-16 13:05:54,054 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:06:04,091 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:06:09,240 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 DROP ( PZ5IOLH6FU, XXG6WP6VDB, OMKVWCGFXX );'...
< t:2020-11-16 13:06:10,659 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:06:14,591 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Schemas match
< t:2020-11-16 13:06:14,591 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:06:17,019 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 ADD ( R0VH7X8AZT list<tinyint>, PJC8E8C08E smallint, NSMSY8B2UG blob );'...
< t:2020-11-16 13:06:18,562 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:06:21,731 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Schemas match
< t:2020-11-16 13:06:21,732 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:06:29,594 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 DROP ( PJC8E8C08E, NSMSY8B2UG );'...
< t:2020-11-16 13:06:31,150 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:06:32,809 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Schemas match
< t:2020-11-16 13:06:32,809 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:06:35,299 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 ADD ( N39QSJ4ZWP duration, NPN5WMCWHD tinyint, VLQZT7N62Z map<ascii,bigint>, VHQ5GA2ORI decimal );'...
< t:2020-11-16 13:06:36,749 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:06:39,640 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Schemas match
< t:2020-11-16 13:06:39,640 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:06:44,641 f:common.py       l:1160 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE standard1 DROP ( R0VH7X8AZT, VHQ5GA2ORI, VLQZT7N62Z, N39QSJ4ZWP, NPN5WMCWHD );'...
< t:2020-11-16 13:06:46,092 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
< t:2020-11-16 13:06:48,586 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Schemas match
< t:2020-11-16 13:06:48,587 f:thread.py       l:57   c:cassandra.cluster    p:DEBUG > [control connection] Waiting for schema agreement
```

**Comment by slivne** [comment] 2020-11-17 15:09
@juliayakovlev thanks

The alter table commands that are done via the nemesis are they changing the schema of the table the cassandra-stress is operating on ?

- you have ```ALTER TABLE standard1 ADD  ...``` what is the keyspace used ?
- what is they keyspace.table cassandra stress is using ?

**Comment by juliayakovlev** [comment] 2020-11-17 15:23
> @juliayakovlev thanks
> 
> The alter table commands that are done via the nemesis are they changing the schema of the table the cassandra-stress is operating on ?
> 
> * you have `ALTER TABLE standard1 ADD  ...` what is the keyspace used ?

nemesis runs alter commands using session.execute. So the the session uses keyspace  ("keyspace1")

> * what is they keyspace.table cassandra stress is using ?

keyspace1.standard1

**Comment by slivne** [comment] 2020-11-18 11:55
Here is the graph showing the relation of the 
- traffic 
- prepare cache invalidation 
- cql prepare requests (new)
- schema changes scalled

![Screenshot from 2020-11-18 13-54-01](https://user-images.githubusercontent.com/3465480/99527478-899c5a00-29a5-11eb-916b-93b3c542b557.png)


We have a direct correlation - if we want to check my theory this is because of changing C-S keyspace+table - we can run a test with alters done on a table C-S is not writting to and see the effects.

In my view this is not great (the first drop is bad) but is to be expected in the case of changing the schema of the table an app is heavily writing to.

**Comment by shoshan** [comment] 2020-11-18 14:03
Drop in IO, rise of cassandra latency manifested too in longevity-10gb-3h scylla 4.3.rc1 tests. 
viewing scylla overview  dashboard shows scylla reporting write reads latency in level of ms.
so might be related to cassandra tool reports reaction in my case to `add_drop_coloumn` nemesis disturbance.
SCT_TEST_ID=8d65f276-bdc1-4cb1-bfe8-34ba83c7ea96

![reproducing_1_add_drop_coloumn_cassandra_stress_wide](https://user-images.githubusercontent.com/99000/99539780-55319980-29b7-11eb-80ea-7cd2ab52f4eb.png)
![reproducing_1_add_drop_coloumn_cassandra_stress](https://user-images.githubusercontent.com/99000/99539814-611d5b80-29b7-11eb-99d2-f23608e054d6.png)
![reproducing_1_add_drop_coloumn_RW_latencies](https://user-images.githubusercontent.com/99000/99539839-67abd300-29b7-11eb-9747-5349631fdcf7.png)

**Comment by bentsi** [comment] 2020-11-18 14:45
Happens on  4.3.rc1 (GCE)
Monitor: http://34.75.106.238:3000/d/7S8riTTGk/scylla-per-server-metrics-nemesis-master?orgId=1&from=1605662107141&to=1605663084037

**Comment by bentsi** [comment] 2020-11-19 11:32
@slivne @avikivity do you need the Scylla monitoring instance or I can kill them?

**Comment by slivne** [comment] 2020-11-19 11:46
if its the same scenario julia reported - altering the keyspace/table c-s is writing to (keyspace1.standard1) its the same issue - you can kill the monitor

**Comment by bentsi** [comment] 2020-11-19 11:48
yes, the same

**Comment by avikivity** [comment] 2022-12-24 12:20
Closing as likely duplicate of #2577

**Closed by avikivity** 2022-12-24 12:20 UTC
Labels: bug, low, stability, schema changes
