### ISSUE TITLE
Alternator - Invalid alternator_encryption_options causes Scylla to coredump

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#11520] opened 2022-09-10 17:19 UTC
**Installation details**
Scylla version (or git commit hash): 5.0.1-0.20220719.b177dacd3 with build-id `217f31634f8c8722cadcfe57ade8da58af05d415`

**Description**
Seen in the field. Scylla will coredump with an assertion error when `alternator_encryption_options` is not properly set. We'd ideally fail to start with a clearer error message.

**To reproduce**
Incorrectly indent `alternator_encryption_options` options under scylla.yaml, effectively flagging it as invalid:

```yaml
alternator_encryption_options:
keyfile: /etc/scylla/alternator.key
certificate: /etc/scylla/alternator.crt
```

Start Scylla.

```shell
set 10 14:13:19 skywalker scylla[2336780]: scylla: ./seastar/include/seastar/core/sharded.hh:563: seastar::sharded<alternator::server>::~sharded() [Service = alternator::server]: Assertion `_instances.empty()' >
set 10 14:13:19 skywalker scylla[2336780]: Aborting on shard 0.
set 10 14:13:19 skywalker scylla[2336780]: Backtrace:
set 10 14:13:19 skywalker scylla[2336780]:   0x42c5a18
set 10 14:13:19 skywalker scylla[2336780]:   0x42f6562
set 10 14:13:19 skywalker scylla[2336780]:   0x7f2f794e5a1f
set 10 14:13:19 skywalker scylla[2336780]:   /opt/scylladb/libreloc/libc.so.6+0x3d2a1
set 10 14:13:19 skywalker scylla[2336780]:   /opt/scylladb/libreloc/libc.so.6+0x268a3
set 10 14:13:19 skywalker scylla[2336780]:   /opt/scylladb/libreloc/libc.so.6+0x26788
set 10 14:13:19 skywalker scylla[2336780]:   /opt/scylladb/libreloc/libc.so.6+0x35a15
set 10 14:13:19 skywalker scylla[2336780]:   0x10305d6
set 10 14:13:19 skywalker scylla[2336780]:   0xffbf85
set 10 14:13:19 skywalker scylla[2336780]:   0xffbf75
set 10 14:13:19 skywalker scylla[2336780]:   0xffbf65
set 10 14:13:19 skywalker scylla[2336780]:   0xffbe43
set 10 14:13:19 skywalker scylla[2336780]:   0x45463f1
```

Such situations are quite occasionally seen in the field. Rather than coredumping for anything, why don't we introduce an early parser ? :D

**Comment by nyh** [comment] 2022-09-11 10:42
I cannot reproduce this on master or on branch-5.0. On both, the misindented lines cause a warning, but not a crash:
```
WARN  2022-09-11 13:39:48,763 [shard 0] init - Unknown option : keyfile
WARN  2022-09-11 13:39:48,763 [shard 0] init - Unknown option : certificate
```
And apparently the line `alternator_encryption_options:` is outright ignored, I don't know why (it should have also given a warning, at least...). Alternator then starts with HTTPS:

```
INFO  2022-09-11 13:39:50,096 [shard 0] alternator_controller - Alternator server listening on 127.0.0.1, HTTP port 8000, HTTPS port 8043
```
or if I want only HTTPS, not HTTP,
```
INFO  2022-09-11 13:41:51,640 [shard 0] alternator_controller - Alternator server listening on 127.0.0.1, HTTP port OFF, HTTPS port 8043
```

I'll try the specific version you mentioned next...

**Comment by fee-mendes** [comment] 2022-09-11 11:04
Another way I found this reproduces is when the keys/certificates are set-up correctly, but Scylla has no access to the certificates (ie: `root:root`).

**Comment by nyh** [comment] 2022-09-11 11:06
I tried with the commit that you tested (b177dacd3) and also can't reproduce the crash. Strange.

**Comment by nyh** [comment] 2022-09-11 11:06
> Another way I found this reproduces is when the keys/certificates are set-up correctly, but Scylla has no access to the certificates (ie: `root:root`).

Ok, I'll check maybe I can reproduce that...

**Comment by nyh** [comment] 2022-09-11 11:21
On master, after a `chmod 0 conf/scylla.key` (making the key file unreadable), Scylla fails cleanly to boot:
```
ERROR 2022-09-11 14:17:11,730 [shard 0] alternator_controller - Failed to set up Alternator TLS credentials: std::_Nested_exception<std::runtime_error> (Could not read key file conf/scylla.key): std::filesystem::__cxx11::filesystem_error (error system:13, filesystem error: open failed: Permission denied [conf/scylla.key])
...
ERROR 2022-09-11 14:17:14,579 [shard 0] init - Startup failed: std::_Nested_exception<std::runtime_error> (Failed to set up Alternator TLS credentials): std::_Nested_exception<std::runtime_error> (Could not read key file conf/scylla.key): std::filesystem::__cxx11::filesystem_error (error system:13, filesystem error: open failed: Permission denied [conf/scylla.key])
```

On https://github.com/scylladb/scylladb/commit/b177dacd36a61e7d2d9e24f8ba131854f9ac41cf I can reproduce the same crash that you see:
```
scylla: ./seastar/include/seastar/core/sharded.hh:563: seastar::sharded<alternator::server>::~sharded() [Service = alternator::server]: Assertion `_instances.empty()' failed.
```

So it's a fix we already have just missing a backport, I'll check what it is.

**Comment by nyh** [comment] 2022-09-11 11:44
The already-fixed bug is #10025. I confirmed that a backport fixes it.

**Comment by fee-mendes** [comment] 2022-09-11 11:45
> I tried with the commit that you tested ([b177dac](https://github.com/scylladb/scylladb/commit/b177dacd36a61e7d2d9e24f8ba131854f9ac41cf)) and also can't reproduce the crash. Strange.

@nyh I think I understand now what could have happened here. Under the [Running Alternator](https://github.com/scylladb/scylladb/blob/master/docs/alternator/alternator.md#running-alternator) doc, we mention:

> As usual for HTTPS servers, the operator must specify certificate and key files. **By default these should be placed in /etc/scylla/scylla.crt and /etc/scylla/scylla.key**, but these default locations can overridden by specifying --alternator-encryption-options keyfile="..." and --alternator-encryption-options certificate="...".

First I have to say this excerpt is misleading. How come the operator **must** specify certificate and key files but there's a default? This is incorrect as per [RFC2119](https://www.rfc-editor.org/rfc/rfc2119), this should read as **SHOULD**, or the defaults should be dropped entirely.

Second: Consider the user provided an invalid entry (or hasn't provided anything) for `alternator_encryption_options:`, but the **default** exists, and the **default** (scylla.crt & scylla.key) do not have read permission for Scylla. This will throw the same exception.

That said, I think the problem is a bit more severe: We can end up in a situation where we not only don't know why Scylla coredumped, but we also don't know for which cert it has thrown?

**Comment by nyh** [comment] 2022-09-11 11:49
> @nyh I think I understand now what could have happened here. Under the [Running Alternator](https://github.com/scylladb/scylladb/blob/master/docs/alternator/alternator.md#running-alternator) doc, we mention:
> 
> > As usual for HTTPS servers, the operator must specify certificate and key files. **By default these should be placed in /etc/scylla/scylla.crt and /etc/scylla/scylla.key**, but these default locations can overridden by specifying --alternator-encryption-options keyfile="..." and --alternator-encryption-options certificate="...".

Maybe the word "specify" is the wrong word. The operator must **suply** certificate and key files. He or she can put these files in /etc/scylla/scylla.{crt,key}, or, can use those options to pick a different place for them. These options are only needed if you want to put the files in a non-standard place.

We can write a documentation patch, but it's separate from the core-dump bug (which is #10025 and I just backported to 5.0 now).

> Second: Consider the user provided an invalid entry (or hasn't provided anything) for `alternator_encryption_options:`, but the **default** exists, and the **default** (scylla.crt & scylla.key) do not have read permission for Scylla. This will throw the same exception.

Right.
 
> That said, I think the problem is a bit more severe: We can end up in a situation where we not only don't know why Scylla coredumped, but we also don't know for which cert it has thrown?

With this bug, yes. But after the fix the user sees an error message:

> ERROR 2022-09-11 14:49:11,911 [shard 0] init - Startup failed: std::_Nested_exception<std::runtime_error> (Failed to set up Alternator TLS credentials): std::_Nested_exception<std::runtime_error> (Could not read key file conf/scylla.key): std::filesystem::__cxx11::filesystem_error (error system:13, filesystem error: open failed: Permission denied [conf/scylla.key])

**Comment by fee-mendes** [comment] 2022-09-11 12:01
Thanks! :) I believe we can close this issue then - or when it gets in a release. :heart:

**Comment by nyh** [comment] 2022-09-12 07:46
It's in branch-5.0 now (commit f0c521efdfe4b238fa94ad89d9a462f4803c2595) - I hoped that a "Fixes" there would automatically close this issue, but for some reason it didn't, so I'll close it manually.
Of course, it's not "a release" yet - it should be in the next 5.0 release (5.0.3), whenever that's released.

**Closed by nyh** 2022-09-12 07:46 UTC
Labels: bug, Alternator, tls
