### ISSUE TITLE
perf_simple_query  - tps and tasks_per_op regression

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylladb#18570] opened 2024-05-08 17:28 UTC
perf_simple_query results from begining of may shows regression in tps and tasks_per_op:

<h2 style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Test results</h2>

| commit_id | date | run_date_time | version | allocs_per_op | instructions_per_op | mad tps | max tps | median tps | min tps | tasks_per_op
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
af5674211dd4 | 20240501 | 2024-05-05 06:17:16 | 5.5.0~dev | 63.07 | 42233.56 | 1189.49 | 157216.74 | 156027.25 | 136553.62 | 14.12 |

<h3 style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Median absolute deviation percentage: 0.76%</h3><h2 style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">last 10 Scylla builds dates results</h2>

| commit_id | date | run_date_time | version | allocs_per_op | instructions_per_op | mad tps | max tps | median tps | min tps | tasks_per_op
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- 
d8313dda43d7 | 20240427 | 2024-04-28 06:09:56 | 5.5.0~dev | 63.07(0.0%) | 42245.21(-0.03%) | 1167.92 | 161519.25(-2.66%) | 160134.1(-2.56%) | 137228.49(-0.49%) | 14.12(0.02%)
65cfb9b4e088 | 20240420 | 2024-04-21 06:11:09 | 5.5.0~dev | 62.06(1.62%) | 41850.36(0.92%) | 663.78 | 181138.98(-13.21%) | 178365.74(-12.52%) | 158088.03(-13.62%) | 13.11(7.73%)
0be61e51d329 | 20240411 | 2024-04-14 06:10:12 | 5.5.0~dev | 62.06(1.63%) | 41919.16(0.75%) | 3361.33 | 187892.73(-16.33%) | 184531.4(-15.45%) | 158260.79(-13.72%) | 13.1(7.81%)
0c74c2c12fa4 | 20240405 | 2024-04-07 06:10:04 | 5.5.0~dev | 62.05(1.65%) | 41926.32(0.73%) | 1287.74 | 193580.23(-18.78%) | 191967.91(-18.72%) | 170937.59(-20.11%) | 13.09(7.89%)
885cb2af07b8 | 20240329 | 2024-03-31 06:11:01 | 5.5.0~dev | 62.07(1.62%) | 41842.21(0.94%) | 638.56 | 171304.21(-8.22%) | 170665.65(-8.58%) | 160497.62(-14.92%) | 13.12(7.67%)
6bd0be71ab32 | 20240327 | 2024-03-28 20:31:38 | 5.5.0~dev | 62.06(1.62%) | 41833.61(0.96%) | 702.4 | 181907.62(-13.57%) | 180613.89(-13.61%) | 152158.16(-10.26%) | 13.11(7.74%)
101fdfc33aec | 20240326 | 2024-03-27 10:25:26 | 5.5.0~dev | 62.07(1.61%) | 41859.02(0.89%) | 459.65 | 169157.99(-7.06%) | 167336.86(-6.76%) | 141499.43(-3.5%) | 13.12(7.65%) |

<div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><h3 style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Links:</h3>

An intial biscetion and investigation was done by @michoecho:

```
git bisect good 65cfb9b4e088
git bisect bad d8313dda43d7
cat >bisect.sh <<'EOF'
git submodule update --init --recursive --jobs=10
ninja build/release/scylla || ninja $(realpath build/release/scylla)
build/release/scylla perf-simple-query --smp=1 2>/dev/null | awk '/median/{exit int($7 > 14)}'
EOF
git bisect run bash bisect.sh
...
3a34bb18cd2207ff51ff0053fc13235848cffd25 is the first bad commit
commit 3a34bb18cd2207ff51ff0053fc13235848cffd25
Author: Patryk Jędrzejczak <[patryk.jedrzejczak@scylladb.com](mailto:patryk.jedrzejczak@scylladb.com)>
Date:   Tue Apr 2 12:37:20 2024 +0200

    db: config: make consistent-topology-changes unused

    We make the `consistent-topology-changes` experimental feature
    unused and assumed to be true in 6.0. We remove code branches that
    executed if `consistent-topology-changes` was disabled.

```

The full discussion about the regression investigation can be found here:
https://groups.google.com/a/scylladb.com/g/scylla-perf-results/c/1TMTpovVvSo/m/1AXhK44-AAAJ?utm_medium=email&utm_source=footer

**Comment by kbr-scylla** [comment] 2024-05-09 11:01
From @michoecho's investigation, it's caused by `apply_fence`.
`
seastar::continuation<seastar::internal::promise_base_with_type<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >, service::storage_proxy::apply_fence<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >(seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >, service::fencing_token, gms::inet_address) const::{lambda(seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >&&)#1}, seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >::then_wrapped_nrvo<seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >, service::storage_proxy::apply_fence<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >(seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >, service::fencing_token, gms::inet_address) const::{lambda(seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >&&)#1}>(service::storage_proxy::apply_fence<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >(seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >, service::fencing_token, gms::inet_address) const::{lambda(seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >&&)#1}&&)::{lambda(seastar::internal::promise_base_with_type<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >&&, service::storage_proxy::apply_fence<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >(seastar::future<auto:1>, service::fencing_token, gms::inet_address) const::{lambda(seastar::future<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >&&)#1}&, seastar::future_state<seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >&&)#1}, seastar::rpc::tuple<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, cache_temperature> >::run_and_dispose
`
![image](https://github.com/scylladb/scylladb/assets/120044486/263e8d86-53b3-4107-a42c-7626382f496c)


Citing some comments from the discussion:

> (If this wasn't clear, note that the "bad patch" doesn't actually add work to a real workload  — it only makes *perf_simple_query* aware of the fencing).

> Avoiding continuations isn't easy, it's just how composition in Seastar works. If you want to avoid a continuation, you basically have to manually inline it.

-

> The TPS regression is much larger than the instruction overhead. Maybe it's not real, but at least it should be investigated.

> The extra instruction/task/allocation may be tolerable and unavoidable, but it's also possible to recover some of it.

-

> If the change in TPS is greater than the change in instructions per op, then this (obviously) means that the IPC is lower.
> Analyzing IPC is a wyższa szkoła jazdy even at the macro level, let alone at the level of 300 instructions.

-

> Could also be that we're not running at 100% utilization any more.
> Maybe we won't figure it out, but we have to try.

**Comment by kbr-scylla** [comment] 2024-05-13 08:43
@avikivity do you consider this a release blocker?

**Comment by kbr-scylla** [comment] 2024-05-13 11:28
I put it in Q2 plan anyway, we might be able to fix it for 6.0 even after we branch, if we deal with all the blockers.

**Comment by patjed41** [comment] 2024-06-04 09:55
It might not be obvious after reading the discussion, so I'd like to note that the regression reported in this issue is a regression of the raft-based topology compared to the gossip-based topology. It became visible when we moved the raft-based topology out of experimental in #18285 and all C++ in-repo tests started using it by default.

Median TPS variance in the runs reported in this issue is quite high. Here are the median TPS measurements in the runs that happened after this issue was opened:
- May 19: 181413.93717210155
- May 26: 157550.69167030553
- June 2: 186354.14420244336

So, the high variance continues. The fastest runs can have median TPS even 20% higher than the slowest runs. In such conditions, reporting <20% difference as a regression seems unreasonable. This test should be changed to measure performance more precisely (I see there is some work in that direction: #18628) or we should change the way we run it.

Since we cannot rely on CI benchmarks, I did them myself with much larger sample size (3 attempts, each of 100 runs with raft topology and 100 runs with gossip topology, duration=20). In every attempt, the average median TPS regression was in the interval 0.984-0.988%. Also, all these hundreds of runs had much lower variance than the CI ones. So, the actual regression seems to be only around 1%, not 13-18%, which is similar to the instructions/op and allocs/op regressions.

Avoiding these regressions seems very hard, perhaps even unavoidable. We cannot simply get rid off the continuation -- it is critical for the fencing correctness. Coroutinizing the code doesn't help -- allocs/op remains the same. Maybe we could inline `apply_fence` somewhere deep inside `query_result_local` where coroutines﻿ would save us from an additional alloc. However, `query_result_local` and the code underneath are also used without fencing. Even if we succeeded in doing such a refactor, the code would likely become a mess.

I would close this issue or at least decrease its priority. We can also wait for a few more runs in CI, but I don't think they will provide much value.

cc @avikivity @kbr-scylla

**Comment by kbr-scylla** [comment] 2024-06-04 10:14
Thanks @patjed41.

Given that the regression is much less significant than we initially thought, and we don't know how to avoid it, I'm closing the issue.

**Closed by kbr-scylla** 2024-06-04 10:14 UTC
Labels: symptom/performance, P1

**Comment by michoecho** [comment] 2024-06-04 10:29
It was always going to end this way.

**Comment by raphaelsc** [comment] 2024-06-07 01:49
> It might not be obvious after reading the discussion, so I'd like to note that the regression reported in this issue is a regression of the raft-based topology compared to the gossip-based topology. It became visible when we moved the raft-based topology out of experimental in #18285 and all C++ in-repo tests started using it by default.
> 
> Median TPS variance in the runs reported in this issue is quite high. Here are the median TPS measurements in the runs that happened after this issue was opened:
> - May 19: 181413.93717210155
> - May 26: 157550.69167030553
> - June 2: 186354.14420244336
> 
> So, the high variance continues. The fastest runs can have median TPS even 20% higher than the slowest runs. In such conditions, reporting <20% difference as a regression seems unreasonable. This test should be changed to measure performance more precisely (I see there is some work in that direction: #18628) or we should change the way we run it.
> 
> Since we cannot rely on CI benchmarks, I did them myself with much larger sample size (3 attempts, each of 100 runs with raft topology and 100 runs with gossip topology, duration=20). In every attempt, the average median TPS regression was in the interval 0.984-0.988%. Also, all these hundreds of runs had much lower variance than the CI ones. So, the actual regression seems to be only around 1%, not 13-18%, which is similar to the instructions/op and allocs/op regressions.
> 
> Avoiding these regressions seems very hard, perhaps even unavoidable. We cannot simply get rid off the continuation -- it is critical for the fencing correctness. Coroutinizing the code doesn't help -- allocs/op remains the same. Maybe we could inline `apply_fence` somewhere deep inside `query_result_local` where coroutines﻿ would save us from an additional alloc. However, `query_result_local` and the code underneath are also used without fencing. Even if we succeeded in doing such a refactor, the code would likely become a mess.
> 
> I would close this issue or at least decrease its priority. We can also wait for a few more runs in CI, but I don't think they will provide much value.
> 
> cc @avikivity @kbr-scylla 

@roydahan I suggest your team work to understand this high variance in CI perf tests, such that these reports can be more trusted in the future.
