### ISSUE TITLE
cql-pytest.test_permissions: Cannot delete function X, as it is used by user-defined aggregate

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13919] opened 2023-05-17 11:48 UTC
Hit in CI: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1289/artifact/testlog/x86_64/release/cql-pytest.test_permissions.1.log
in a branch based off of 9b0679c140bb82aeb3b52174e73ce8ee642eba8b
```
______________________ test_grant_revoke_uda_permissions _______________________

cql = <cassandra.cluster.Session object at 0x7f4781ede250>
keyspace = 'cql_test_1684321423210'
body = "(state tuple<bigint, bigint>) CALLED ON NULL INPUT RETURNS bigint LANGUAGE lua AS 'return state[1]//state[2]'"
name = None, args = None

    @contextmanager
    def new_function(cql, keyspace, body, name=None, args=None):
        fun = name if name else unique_name()
        cql.execute(f"CREATE FUNCTION {keyspace}.{fun} {body}")
        try:
>           yield fun

test/cql-pytest/util.py:108: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cql = <cassandra.cluster.Session object at 0x7f4781ede250>

    def test_grant_revoke_uda_permissions(cql):
        schema = 'id bigint primary key'
        with new_test_keyspace(cql, "WITH REPLICATION = { 'class': 'SimpleStrategy', 'replication_factor': 1 }") as keyspace:
            with new_test_table(cql, keyspace, schema) as table:
                for i in range(8):
                    cql.execute(f"INSERT INTO {table} (id) VALUES ({10**i})")
                avg_partial_body_lua = "(state tuple<bigint, bigint>, val bigint) CALLED ON NULL INPUT RETURNS tuple<bigint, bigint> LANGUAGE lua AS 'return {state[1] + val, state[2] + 1}'"
                avg_partial_body_java = "(state tuple<bigint, bigint>, val bigint) CALLED ON NULL INPUT RETURNS tuple<bigint, bigint> LANGUAGE java AS 'return state.setLong(0, state.getLong(0) + val).setLong(1, state.getLong(1) + Long.valueOf(1));'"
                div_body_lua = "(state tuple<bigint, bigint>) CALLED ON NULL INPUT RETURNS bigint LANGUAGE lua AS 'return state[1]//state[2]'"
                div_body_java = "(state tuple<bigint, bigint>) CALLED ON NULL INPUT RETURNS bigint LANGUAGE java AS 'return state.getLong(0)/state.getLong(1);'"
                avg_partial_body = avg_partial_body_lua
                div_body = div_body_lua
                try:
                    with new_function(cql, keyspace, avg_partial_body):
                        pass
                except:
                    avg_partial_body = avg_partial_body_java
                    div_body = div_body_java
                with new_function(cql, keyspace, avg_partial_body) as avg_partial, new_function(cql, keyspace, div_body) as div_fun:
                    custom_avg_body = f"(bigint) SFUNC {avg_partial} STYPE tuple<bigint, bigint> FINALFUNC {div_fun} INITCOND (0,0)"
                    with new_user(cql) as username:
                        with new_session(cql, username) as user_session:
                            custom_avg = "custom_avg"
                            def create_aggr_idempotent():
                                user_session.execute(f"CREATE AGGREGATE IF NOT EXISTS {keyspace}.{custom_avg} {custom_avg_body}")
                                cql.execute(f"DROP AGGREGATE IF EXISTS {keyspace}.{custom_avg}(bigint)")
                            grant(cql, 'EXECUTE', f'function {keyspace}.{avg_partial}(tuple<bigint, bigint>, bigint)', username)
                            grant(cql, 'EXECUTE', f'function {keyspace}.{div_fun}(tuple<bigint, bigint>)', username)
                            check_enforced(cql, username, permission='CREATE', resource=f'all functions in keyspace {keyspace}',
                                    function=create_aggr_idempotent)
                            check_enforced(cql, username, permission='CREATE', resource='all functions',
                                    function=create_aggr_idempotent)
    
                            cql.execute(f"CREATE AGGREGATE IF NOT EXISTS {keyspace}.{custom_avg} {custom_avg_body}")
>                           check_enforced(cql, username, permission='ALTER', resource=f'all functions in keyspace {keyspace}',
                                    function=lambda: user_session.execute(f"CREATE OR REPLACE AGGREGATE {keyspace}.{custom_avg} {custom_avg_body}"))

test/cql-pytest/test_permissions.py:351: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cql = <cassandra.cluster.Session object at 0x7f4781ede250>
username = 'cql_test_1684321423294', permission = 'ALTER'
resource = 'all functions in keyspace cql_test_1684321423210'
function = <function test_grant_revoke_uda_permissions.<locals>.<lambda> at 0x7f47803bdb20>

    def check_enforced(cql, username, permission, resource, function):
>       eventually_unauthorized(function)

test/cql-pytest/test_permissions.py:76: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

fun = <function test_grant_revoke_uda_permissions.<locals>.<lambda> at 0x7f47803bdb20>
timeout_s = 10

    def eventually_unauthorized(fun, timeout_s=10):
        for i in range(timeout_s * 10):
            try:
                fun()
                time.sleep(0.1)
            except Unauthorized as e:
                return
        try:
            fun()
>           pytest.fail(f"Function {fun} was not refused as unauthorized")

test/cql-pytest/test_permissions.py:62: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

reason = 'Function <function test_grant_revoke_uda_permissions.<locals>.<lambda> at 0x7f47803bdb20> was not refused as unauthorized'
pytrace = True, msg = None

    @_with_exception(Failed)
    def fail(
        reason: str = "", pytrace: bool = True, msg: Optional[str] = None
    ) -> "NoReturn":
        """Explicitly fail an executing test with the given message.
    
        :param reason:
            The message to show the user as reason for the failure.
    
        :param pytrace:
            If False, msg represents the full failure information and no
            python traceback will be reported.
    
        :param msg:
            Same as ``reason``, but deprecated. Will be removed in a future version, use ``reason`` instead.
        """
        __tracebackhide__ = True
        reason = _resolve_msg_to_reason("fail", reason, msg)
>       raise Failed(msg=reason, pytrace=pytrace)
E       Failed: Function <function test_grant_revoke_uda_permissions.<locals>.<lambda> at 0x7f47803bdb20> was not refused as unauthorized

/usr/lib/python3.11/site-packages/_pytest/outcomes.py:196: Failed

During handling of the above exception, another exception occurred:

cql = <cassandra.cluster.Session object at 0x7f4781ede250>
keyspace = 'cql_test_1684321423210'
body = "(state tuple<bigint, bigint>, val bigint) CALLED ON NULL INPUT RETURNS tuple<bigint, bigint> LANGUAGE lua AS 'return {state[1] + val, state[2] + 1}'"
name = None, args = None

    @contextmanager
    def new_function(cql, keyspace, body, name=None, args=None):
        fun = name if name else unique_name()
        cql.execute(f"CREATE FUNCTION {keyspace}.{fun} {body}")
        try:
>           yield fun

test/cql-pytest/util.py:108: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cql = <cassandra.cluster.Session object at 0x7f4781ede250>

    def test_grant_revoke_uda_permissions(cql):
        schema = 'id bigint primary key'
        with new_test_keyspace(cql, "WITH REPLICATION = { 'class': 'SimpleStrategy', 'replication_factor': 1 }") as keyspace:
            with new_test_table(cql, keyspace, schema) as table:
                for i in range(8):
                    cql.execute(f"INSERT INTO {table} (id) VALUES ({10**i})")
                avg_partial_body_lua = "(state tuple<bigint, bigint>, val bigint) CALLED ON NULL INPUT RETURNS tuple<bigint, bigint> LANGUAGE lua AS 'return {state[1] + val, state[2] + 1}'"
                avg_partial_body_java = "(state tuple<bigint, bigint>, val bigint) CALLED ON NULL INPUT RETURNS tuple<bigint, bigint> LANGUAGE java AS 'return state.setLong(0, state.getLong(0) + val).setLong(1, state.getLong(1) + Long.valueOf(1));'"
                div_body_lua = "(state tuple<bigint, bigint>) CALLED ON NULL INPUT RETURNS bigint LANGUAGE lua AS 'return state[1]//state[2]'"
                div_body_java = "(state tuple<bigint, bigint>) CALLED ON NULL INPUT RETURNS bigint LANGUAGE java AS 'return state.getLong(0)/state.getLong(1);'"
                avg_partial_body = avg_partial_body_lua
                div_body = div_body_lua
                try:
                    with new_function(cql, keyspace, avg_partial_body):
                        pass
                except:
                    avg_partial_body = avg_partial_body_java
                    div_body = div_body_java
>               with new_function(cql, keyspace, avg_partial_body) as avg_partial, new_function(cql, keyspace, div_body) as div_fun:

test/cql-pytest/test_permissions.py:335: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <contextlib._GeneratorContextManager object at 0x7f4781f85690>
typ = <class 'Failed'>
value = Function <function test_grant_revoke_uda_permissions.<locals>.<lambda> at 0x7f47803bdb20> was not refused as unauthorized
traceback = <traceback object at 0x7f478020ad00>

    def __exit__(self, typ, value, traceback):
        if typ is None:
            try:
                next(self.gen)
            except StopIteration:
                return False
            else:
                raise RuntimeError("generator didn't stop")
        else:
            if value is None:
                # Need to force instantiation so we can reliably
                # tell if we get the same exception back
                value = typ()
            try:
>               self.gen.throw(typ, value, traceback)

/usr/lib64/python3.11/contextlib.py:155: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cql = <cassandra.cluster.Session object at 0x7f4781ede250>
keyspace = 'cql_test_1684321423210'
body = "(state tuple<bigint, bigint>) CALLED ON NULL INPUT RETURNS bigint LANGUAGE lua AS 'return state[1]//state[2]'"
name = None, args = None

    @contextmanager
    def new_function(cql, keyspace, body, name=None, args=None):
        fun = name if name else unique_name()
        cql.execute(f"CREATE FUNCTION {keyspace}.{fun} {body}")
        try:
            yield fun
        finally:
            if args:
                cql.execute(f"DROP FUNCTION {keyspace}.{fun}({args})")
            else:
>               cql.execute(f"DROP FUNCTION {keyspace}.{fun}")

test/cql-pytest/util.py:113: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???

cassandra/cluster.py:2700: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot delete function cql_test_1684321423210.cql_test_1684321423282 : (frozen<tuple<bigint, bigint>>) -> bigint, as it is used by user-defined aggregate cql_test_1684321423210.custom_avg"

cassandra/cluster.py:5019: InvalidRequest

During handling of the above exception, another exception occurred:

cql = <cassandra.cluster.Session object at 0x7f4781ede250>

    def test_grant_revoke_uda_permissions(cql):
        schema = 'id bigint primary key'
        with new_test_keyspace(cql, "WITH REPLICATION = { 'class': 'SimpleStrategy', 'replication_factor': 1 }") as keyspace:
            with new_test_table(cql, keyspace, schema) as table:
                for i in range(8):
                    cql.execute(f"INSERT INTO {table} (id) VALUES ({10**i})")
                avg_partial_body_lua = "(state tuple<bigint, bigint>, val bigint) CALLED ON NULL INPUT RETURNS tuple<bigint, bigint> LANGUAGE lua AS 'return {state[1] + val, state[2] + 1}'"
                avg_partial_body_java = "(state tuple<bigint, bigint>, val bigint) CALLED ON NULL INPUT RETURNS tuple<bigint, bigint> LANGUAGE java AS 'return state.setLong(0, state.getLong(0) + val).setLong(1, state.getLong(1) + Long.valueOf(1));'"
                div_body_lua = "(state tuple<bigint, bigint>) CALLED ON NULL INPUT RETURNS bigint LANGUAGE lua AS 'return state[1]//state[2]'"
                div_body_java = "(state tuple<bigint, bigint>) CALLED ON NULL INPUT RETURNS bigint LANGUAGE java AS 'return state.getLong(0)/state.getLong(1);'"
                avg_partial_body = avg_partial_body_lua
                div_body = div_body_lua
                try:
                    with new_function(cql, keyspace, avg_partial_body):
                        pass
                except:
                    avg_partial_body = avg_partial_body_java
                    div_body = div_body_java
>               with new_function(cql, keyspace, avg_partial_body) as avg_partial, new_function(cql, keyspace, div_body) as div_fun:

test/cql-pytest/test_permissions.py:335: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.11/contextlib.py:155: in __exit__
    self.gen.throw(typ, value, traceback)
test/cql-pytest/util.py:113: in new_function
    cql.execute(f"DROP FUNCTION {keyspace}.{fun}")
cassandra/cluster.py:2700: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot delete function cql_test_1684321423210.cql_test_1684321423270 : (frozen<tuple<bigint, bigint>>, bigint) -> frozen<tuple<bigint, bigint>>, as it is used by user-defined aggregate cql_test_1684321423210.custom_avg"

cassandra/cluster.py:5019: InvalidRequest
```

**Comment by kbr-scylla** [comment] 2023-05-29 09:57
This issue is killing us in CI. @eliransin please prioritize. There had to be a regression, with UDA or with auth. @scylladb/scylla-maint anyone remember merging something related to UDAs or Auth?

**Comment by nyh** [comment] 2023-05-29 10:19
@wmitros changed this test in f4d2cd15e9a recently, so maybe that caused a regression in the test. I'll take a look (unless @wmitros is already looking)

**Comment by bhalevy** [comment] 2023-05-29 10:26
@DoronArazii why did you add the `Shutdown` label?
I don't see how it's related.

Also, how about prioritizing this issue as `P1`? It's failing quite frequently in CI.

**Comment by nyh** [comment] 2023-05-29 10:27
Same failure in next promotion: https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/6066/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/6066/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___cql_pytest_test_permissions_release_3/

**Comment by DoronArazii** [comment] 2023-05-29 10:29
Probably by mistake... did it to a bunch of items.
Also, removing 'master/high' as we're no longer using it since P1/2/3/4

**Comment by avikivity** [comment] 2023-05-29 10:31
I'm seeing problems here:

````
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[7/1000]   cql-pytest   dev   [ PASS ] cql-pytest.test_permissions.7             
[8/1000]   cql-pytest   dev   [ FAIL ] cql-pytest.test_permissions.8
[18/1000]  cql-pytest   dev   [ PASS ] cql-pytest.test_permissions.19             
[19/1000]  cql-pytest   dev   [ FAIL ] cql-pytest.test_permissions.17
[29/1000]  cql-pytest   dev   [ PASS ] cql-pytest.test_permissions.29             
[30/1000]  cql-pytest   dev   [ FAIL ] cql-pytest.test_permissions.28
[71/1000]  cql-pytest   dev   [ PASS ] cql-pytest.test_permissions.71     
```

**Comment by avikivity** [comment] 2023-05-29 10:33
```

cql = <cassandra.cluster.Session object at 0x7fcfdd22eb50>
keyspace = 'cql_test_1685356113947'
body = "(state tuple<bigint, bigint>) CALLED ON NULL INPUT RETURNS bigint LANGUAGE lua AS 'return state[1]//state[2]'"
name = None, args = None

    @contextmanager
    def new_function(cql, keyspace, body, name=None, args=None):
        fun = name if name else unique_name()
        cql.execute(f"CREATE FUNCTION {keyspace}.{fun} {body}")
        try:
            yield fun
        finally:
            if args:
                cql.execute(f"DROP FUNCTION {keyspace}.{fun}({args})")
            else:
>               cql.execute(f"DROP FUNCTION {keyspace}.{fun}")

test/cql-pytest/util.py:113: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???

cassandra/cluster.py:2699: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot delete function cql_test_1685356113947.cql_test_1685356114009 : (frozen<tuple<bigint, bigint>>) -> bigint, as it is used by user-defined aggregate cql_test_1685356113947.custom_avg"

cassandra/cluster.py:5018: InvalidRequest

During handling of the above exception, another exception occurred:

cql = <cassandra.cluster.Session object at 0x7fcfdd22eb50>

    def test_grant_revoke_uda_permissions(cql):
        schema = 'id bigint primary key'
        with new_test_keyspace(cql, "WITH REPLICATION = { 'class': 'NetworkTopologyStrategy', 'replication_factor': 1 }") as keyspace:
            with new_test_table(cql, keyspace, schema) as table:
                for i in range(8):
                    cql.execute(f"INSERT INTO {table} (id) VALUES ({10**i})")
                avg_partial_body_lua = "(state tuple<bigint, bigint>, val bigint) CALLED ON NULL INPUT RETURNS tuple<bigint, bigint> LANGUAGE lua AS 'return {state[1] + val, state[2] + 1}'"
                avg_partial_body_java = "(state tuple<bigint, bigint>, val bigint) CALLED ON NULL INPUT RETURNS tuple<bigint, bigint> LANGUAGE java AS 'return state.setLong(0, state.getLong(0) + val).setLong(1, state.getLong(1) + Long.valueOf(1));'"
                div_body_lua = "(state tuple<bigint, bigint>) CALLED ON NULL INPUT RETURNS bigint LANGUAGE lua AS 'return state[1]//state[2]'"
                div_body_java = "(state tuple<bigint, bigint>) CALLED ON NULL INPUT RETURNS bigint LANGUAGE java AS 'return state.getLong(0)/state.getLong(1);'"
                avg_partial_body = avg_partial_body_lua
                div_body = div_body_lua
                try:
                    with new_function(cql, keyspace, avg_partial_body):
                        pass
                except:
                    avg_partial_body = avg_partial_body_java
                    div_body = div_body_java
>               with new_function(cql, keyspace, avg_partial_body) as avg_partial, new_function(cql, keyspace, div_body) as div_fun:

test/cql-pytest/test_permissions.py:335: 
```

@wmitros please fix ASAP, or even sooner

**Comment by avikivity** [comment] 2023-05-29 10:34
Also, can we revert something here?

**Comment by nyh** [comment] 2023-05-29 10:37
@avikivity , I'm still building Scylla (!) to run this locally myself, but can you try reverting the test change https://github.com/scylladb/scylladb/commit/f4d2cd15e9a73caac78384f0b3a489c3a0457f47 and see if it stops reproducing, or also reproduced before that test change?

**Comment by wmitros** [comment] 2023-05-29 10:39
@nyh @avikivity I'm looking into this. Reverting https://github.com/scylladb/scylladb/commit/f4d2cd15e9a73caac78384f0b3a489c3a0457f47 will probably be not enough. This error is most likely caused by https://github.com/scylladb/scylladb/pull/13814, https://github.com/scylladb/scylladb/pull/13823 or the combination of these two, but I'm not sure it's easy to revert them

**Comment by mykaul** [comment] 2023-05-29 10:50
> @nyh @avikivity I'm looking into this. Reverting [f4d2cd1](https://github.com/scylladb/scylladb/commit/f4d2cd15e9a73caac78384f0b3a489c3a0457f47) will probably be not enough. This error is most likely caused by #13814, #13823 or the combination of these two, but I'm not sure it's easy to revert them

@wmitros - spend today trying to fix it, otherwise, we'll have to do the work to revert those changes. We cannot allow such a long and severe CI breakage.

**Comment by avikivity** [comment] 2023-05-29 10:50
Reproduces on 52e4edfd5e6773ffd53ddf6ccb51be58175613c5

but differently:

```
test/cql-pytest/test_permissions.py:351: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cql = <cassandra.cluster.Session object at 0x7fbac9970590>
username = 'cql_test_1685357205347', permission = 'ALTER'
resource = 'all functions in keyspace cql_test_1685357205237'
function = <function test_grant_revoke_uda_permissions.<locals>.<lambda> at 0x7fbac86afe20>

    def check_enforced(cql, username, permission, resource, function):
>       eventually_unauthorized(function)

test/cql-pytest/test_permissions.py:76: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

fun = <function test_grant_revoke_uda_permissions.<locals>.<lambda> at 0x7fbac86afe20>
timeout_s = 10

    def eventually_unauthorized(fun, timeout_s=10):
        for i in range(timeout_s * 10):
            try:
                fun()
                time.sleep(0.1)
            except Unauthorized as e:
                return
        try:
            fun()
>           pytest.fail(f"Function {fun} was not refused as unauthorized")

test/cql-pytest/test_permissions.py:62: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

reason = 'Function <function test_grant_revoke_uda_permissions.<locals>.<lambda> at 0x7fbac86afe20> was not refused as unauthorized'
pytrace = True, msg = None

    @_with_exception(Failed)
    def fail(reason: str = "", pytrace: bool = True, msg: Optional[str] = None) -> NoReturn:
        """Explicitly fail an executing test with the given message.
    
        :param reason:
            The message to show the user as reason for the failure.
    
        :param pytrace:
            If False, msg represents the full failure information and no
            python traceback will be reported.
    
        :param msg:
            Same as ``reason``, but deprecated. Will be removed in a future version, use ``reason`` instead.
        """
        __tracebackhide__ = True
        reason = _resolve_msg_to_reason("fail", reason, msg)
>       raise Failed(msg=reason, pytrace=pytrace)
E       Failed: Function <function test_grant_revoke_uda_permissions.<locals>.<lambda> at 0x7fbac86afe20> was not refused as unauthorized

/usr/lib/python3.11/site-packages/_pytest/outcomes.py:198: Failed

During handling of the above exception, another exception occurred:

cql = <cassandra.cluster.Session object at 0x7fbac9970590>
keyspace = 'cql_test_1685357205237'
body = "(state tuple<bigint, bigint>, val bigint) CALLED ON NULL INPUT RETURNS tuple<bigint, bigint> LANGUAGE lua AS 'return {state[1] + val, state[2] + 1}'"
name = None, args = None

```

**Comment by avikivity** [comment] 2023-05-29 10:50
It's better to revert IMO and rework, it's blocking everyone. But I need to know what to revert.

**Comment by avikivity** [comment] 2023-05-29 10:56
d2d53fc1db (parent) appears to work

**Comment by nyh** [comment] 2023-05-29 10:56
I can reproduce this locally on a single-Scylla single-threaded client which just repeats the same test again and again, so it's not about slow test machines timing out or anything like that, but unfortunately for me it seems to fail very rarely (about twice per 100 runs).
```
test/cql-pytest/run --count 100 test_permissions.py::test_grant_revoke_uda_permissions
```

**Comment by wmitros** [comment] 2023-05-29 10:57
It should be enough to revert 52e4edfd5e6773ffd53ddf6ccb51be58175613c5, I see #13823 was merged a few days earlier and I didn't see this issue in that time. I don't think any other patches are related to this

**Comment by wmitros** [comment] 2023-05-29 11:00
> It should be enough to revert [52e4edf](https://github.com/scylladb/scylladb/commit/52e4edfd5e6773ffd53ddf6ccb51be58175613c5), I see #13823 was merged a few days earlier and I didn't see this issue in that time. I don't think any other patches are related to this

However, some dtests were fixed by that patch (https://github.com/scylladb/scylladb/issues/13747), but I don't think they run in the CI

**Closed** 2023-05-29 22:30 UTC
Labels: P1, CI-Stability

**Comment by bhalevy** [comment] 2023-06-28 10:02
As @nyh noted in https://github.com/scylladb/scylladb/issues/13747#issuecomment-1567006645
The `test_grant_revoke_uda_permissions` dtest becomes flaky with https://github.com/scylladb/scylladb/commit/52e4edfd5e6773ffd53ddf6ccb51be58175613c5
and so it is in now 5.3.

Need to backport https://github.com/scylladb/scylladb/commit/27f7cc403281015c1fcecb8ad5c4db8fd9d70b00 there.

**Comment by bhalevy** [comment] 2023-06-28 10:03
@scylladb/scylla-maint please backport to 5.3

**Comment by bhalevy** [comment] 2023-06-28 10:05
See https://jenkins.scylladb.com/job/scylla-5.3/job/next/40/artifact/testlog/x86_64/dev/cql-pytest.test_permissions.1.log

**Comment by wmitros** [comment] 2023-06-28 10:32
Alternatively, this will also get fixed when we backport https://github.com/scylladb/scylla-enterprise/issues/3058

**Comment by denesb** [comment] 2023-06-29 09:14
> @scylladb/scylla-maint please backport to 5.3 ASAP.

Cherry-pick is not clean, please prepare a backport PR.

**Comment by wmitros** [comment] 2023-07-12 10:12
> > @scylladb/scylla-maint please backport to 5.3 ASAP.
> 
> Cherry-pick is not clean, please prepare a backport PR.

The test failed again, so I posted the backport at https://github.com/scylladb/scylladb/pull/14662

**Comment by avikivity** [comment] 2023-11-30 15:27
Do we need a 5.2 backport? I'm guessing not.
