### ISSUE TITLE
Unexpected write timeouts with LWT workload in a multiDC scenario

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#13667] opened 2023-04-25 07:56 UTC
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

### Problem

When a test runs LWT inserts (prepare write stage), multi DC cluster, the load finished fast (it takes about 1 hour), cassandra-stress reported statistics, but threads that run cassandra-stress are not completed. No load, requests are not sent, nothing run in the cluster (no compactions, repair etc.). And it stucks for the hours. When I checked the log I found a lot of exceptions:
```
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency LOCAL_SERIAL (2 responses were required but only 1 replica responded, 1 failed)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during CAS write query at consistency LOCAL_SERIAL (2 replica were required but only 0 acknowledged the write)
```

I ran the test with different Scylla versions.

The problem was **FOUND** with Scylla version:
- 2023.1.0-rc4 - stuck **more then 15.5 hours** (I stopped the test)
- 2023.1.0-rc2 -  stuck for about **2.5 hours**
- 5.2.0-rc4 -  stuck **more then 5.5 hours** (I stopped the test)

The problem was **NOT** found with Scylla version:
- 5.1 (no WriteTimeoutException / WriteFailureException during prepare write stage)
- 2022.2.5 (no WriteTimeoutException / WriteFailureException during prepare write stage)
- 2023.1.0-rc4 without LWT

### Detailes

The test runs LWT inserts, multi DC cluster. 
Regions:  
eu-west-1 - 4 nodes
us-west-2 - 3 nodes
us-east-1 -2 nodes

User profile:
https://github.com/scylladb/scylla-cluster-tests/blob/master/data_dir/c-s_lwt_big_data_multidc.yaml

Keyspace definition:
```
keyspace_definition: |
  CREATE KEYSPACE IF NOT EXISTS cqlstress_lwt_example WITH replication = {'class': 'NetworkTopologyStrategy', 'eu-westscylla_node_west': 3, 'us-west-2scylla_node_west': 2, 'us-eastscylla_node_east': 1};
```

C-s command:
```
"cassandra-stress user profile=/tmp/c-s_lwt_big_data_multidc.yaml n=10000000 ops'(insert_query=1)' cl=LOCAL_QUORUM serial-cl=LOCAL_SERIAL -mode native cql3 -rate threads=1000"
```

Insert query:
```
insert_query:
   cql: insert into blogposts(domain, published_date, lwt_indicator,  url, url1, url2, url3, url4, author, title, c, d, e, f, g, h, char, vchar, finished, osirisjson, ip, size, imagebase, small_num, tiny_num, vint, decimal_num, double_num, float_num, start_date, start_time, check_date, pass_date, upload_time, user_uid, name_set, name_list) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) if not exists
```

**Scylla version 2023.1.0-rc4** 
C-s thread on the DC with 2 nodes has been completed immediatelly after the load finished (as expected). No `WriteTimeoutExceptions`.
Two other c-s threads stuck - no writes, only reads AFTER reporting c-s statistics for more then 15.5 hours. Just printing ot timeout exceptions (**228617 errors** before stopping the test)
![lwt_multidc_2023 1 rc4](https://user-images.githubusercontent.com/34435448/234202082-e47c194b-ea45-4299-bc90-822aec16595c.png)

Logs and links are in the end of issue description (see "Logs and commands")

**Scylla version 2023.1.0-rc2** 
No load in the 2.5 hours after reporting stats:
![lwt_multidc_2023 1 rc2](https://user-images.githubusercontent.com/34435448/234205076-becef306-0a79-406c-9e23-1474bfc508b8.png)

Test_id: c4c3ee91-c03b-4dc9-9df9-4e1f42885db5
Restore Monitor Stack command: `$ hydra investigate show-monitor c4c3ee91-c03b-4dc9-9df9-4e1f42885db5
[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-lwt-24h-multidc-test/3/)
Logs:
**db-cluster** - https://cloudius-jenkins-test.s3.amazonaws.com/c4c3ee91-c03b-4dc9-9df9-4e1f42885db5/20230306_101459/db-cluster-c4c3ee91.tar.gz 
**sct-runner** - https://cloudius-jenkins-test.s3.amazonaws.com/c4c3ee91-c03b-4dc9-9df9-4e1f42885db5/20230306_101459/sct-runner-c4c3ee91.tar.gz 
**monitor-set** - https://cloudius-jenkins-test.s3.amazonaws.com/c4c3ee91-c03b-4dc9-9df9-4e1f42885db5/20230306_101459/monitor-set-c4c3ee91.tar.gz 
**loader-set** - https://cloudius-jenkins-test.s3.amazonaws.com/c4c3ee91-c03b-4dc9-9df9-4e1f42885db5/20230306_101459/loader-set-c4c3ee91.tar.gz 

**Scylla version 5.2.0-rc4** 
C-s thread on the DC with 2 nodes has been completed immediatelly after the load finished (as expected). No `WriteTimeoutExceptions`.
Two other c-s threads stuck - No load in the more then 5.5 hours after reporting stats (test is still running):
![lwt_multidc_5 2](https://user-images.githubusercontent.com/34435448/234207867-021cadf2-1f62-48c1-a6db-91d14f0cb1cd.png)

Test id: 051b479d-c715-407f-802d-34c2cc85c1b0
Monitor: http://54.217.12.176:3000/d/vLML43EVk/longevity-lwt-24h-multidc-test-oss-scylla-per-server-metrics-nemesis-master?orgId=1&from=1682400992000&to=now&refresh=30s&var-by=instance&var-cluster=&var-dc=All&var-node=All&var-shard=All&var-sct_tags=CassandraStressEvent
[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-lwt-24h-multidc-test-oss/3/)

**Scylla version 2022.2.5** 
No problem. All c-s threads completed immediatelly after the load finished (as expected).
![lwt_multidc_2022 2](https://user-images.githubusercontent.com/34435448/234229049-e71f5ca5-5142-486d-9125-ade6874c4880.png)

Test id: fe64fbdd-eb2d-4b8e-929b-05e00619e9b7
Restore Monitor Stack command: `$ hydra investigate show-monitor fe64fbdd-eb2d-4b8e-929b-05e00619e9b7
[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-lwt-24h-multidc-test/22/)
** Logs will be supplied later

**Scylla version 5.1.8** 
No problem. All c-s threads completed immediatelly after the load finished (as expected).
![lwt_multidc_5 1](https://user-images.githubusercontent.com/34435448/234208156-5ef05a3b-383d-4bcd-98ce-f4ea5bca16bc.png)

Test id: 37b25e8e-ffc9-44c4-ab87-5165fdb5808a
Restore Monitor Stack command: `$ hydra investigate show-monitor 37b25e8e-ffc9-44c4-ab87-5165fdb5808a
[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-lwt-24h-multidc-test-oss/2/)
Logs:
- **db-cluster-37b25e8e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/37b25e8e-ffc9-44c4-ab87-5165fdb5808a/20230425_034504/db-cluster-37b25e8e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/37b25e8e-ffc9-44c4-ab87-5165fdb5808a/20230425_034504/db-cluster-37b25e8e.tar.gz)
- **sct-runner-events-37b25e8e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/37b25e8e-ffc9-44c4-ab87-5165fdb5808a/20230425_034504/sct-runner-events-37b25e8e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/37b25e8e-ffc9-44c4-ab87-5165fdb5808a/20230425_034504/sct-runner-events-37b25e8e.tar.gz)
- **sct-37b25e8e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/37b25e8e-ffc9-44c4-ab87-5165fdb5808a/20230425_034504/sct-37b25e8e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/37b25e8e-ffc9-44c4-ab87-5165fdb5808a/20230425_034504/sct-37b25e8e.log.tar.gz)
- **monitor-set-37b25e8e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/37b25e8e-ffc9-44c4-ab87-5165fdb5808a/20230425_034504/monitor-set-37b25e8e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/37b25e8e-ffc9-44c4-ab87-5165fdb5808a/20230425_034504/monitor-set-37b25e8e.tar.gz)
- **loader-set-37b25e8e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/37b25e8e-ffc9-44c4-ab87-5165fdb5808a/20230425_034504/loader-set-37b25e8e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/37b25e8e-ffc9-44c4-ab87-5165fdb5808a/20230425_034504/loader-set-37b25e8e.tar.gz)

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

Every run

## Installation details

Kernel Version: 5.19.0-1022-aws
Scylla version (or git commit hash): `2023.1.0~rc4-20230402.f90af81a13cc` with build-id `4db7799d283c7ca63c7639b04db34c301dbcfb66`

Cluster size: 9 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-ee19a6aa-9 (18.215.34.50 | 10.12.2.113) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-ee19a6aa-8 (3.237.102.17 | 10.12.0.211) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-ee19a6aa-7 (35.91.92.106 | 10.15.3.177) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-ee19a6aa-6 (35.91.80.223 | 10.15.3.116) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-ee19a6aa-5 (35.86.90.128 | 10.15.0.158) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-ee19a6aa-4 (34.245.0.255 | 10.4.0.91) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-ee19a6aa-3 (34.244.125.176 | 10.4.3.199) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-ee19a6aa-2 (54.217.50.73 | 10.4.0.253) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-ee19a6aa-1 (54.194.86.144 | 10.4.0.18) (shards: 30)

OS / Image: `ami-000f0d43cb22bd09e ami-05e6f6036da2909d7 ami-0f30f07a6cb913353` (aws: eu-west-1)

Test: `longevity-lwt-24h-multidc-test`
Test id: `ee19a6aa-088a-41cb-9b74-afae17152c6b`
Test name: `scylla-staging/yulia/longevity-lwt-24h-multidc-test`
Test config file(s):

- [longevity-lwt-24h-multidc.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1ffe8f9bd0637048f787f60f9b880fdbc837ba62/test-cases/longevity/longevity-lwt-24h-multidc.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor ee19a6aa-088a-41cb-9b74-afae17152c6b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ee19a6aa-088a-41cb-9b74-afae17152c6b)
- Show all stored logs command: `$ hydra investigate show-logs ee19a6aa-088a-41cb-9b74-afae17152c6b`

## Logs:
- **db-cluster-ee19a6aa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ee19a6aa-088a-41cb-9b74-afae17152c6b/20230425_062741/db-cluster-ee19a6aa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ee19a6aa-088a-41cb-9b74-afae17152c6b/20230425_062741/db-cluster-ee19a6aa.tar.gz)
- **sct-runner-events-ee19a6aa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ee19a6aa-088a-41cb-9b74-afae17152c6b/20230425_062741/sct-runner-events-ee19a6aa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ee19a6aa-088a-41cb-9b74-afae17152c6b/20230425_062741/sct-runner-events-ee19a6aa.tar.gz)
- **sct-ee19a6aa.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ee19a6aa-088a-41cb-9b74-afae17152c6b/20230425_062741/sct-ee19a6aa.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ee19a6aa-088a-41cb-9b74-afae17152c6b/20230425_062741/sct-ee19a6aa.log.tar.gz)
- **monitor-set-ee19a6aa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ee19a6aa-088a-41cb-9b74-afae17152c6b/20230425_062741/monitor-set-ee19a6aa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ee19a6aa-088a-41cb-9b74-afae17152c6b/20230425_062741/monitor-set-ee19a6aa.tar.gz)
- **loader-set-ee19a6aa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ee19a6aa-088a-41cb-9b74-afae17152c6b/20230425_062741/loader-set-ee19a6aa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ee19a6aa-088a-41cb-9b74-afae17152c6b/20230425_062741/loader-set-ee19a6aa.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-lwt-24h-multidc-test/21/)
</details>

**Comment by juliayakovlev** [comment] 2023-04-25 11:52
I ran the same test with Scylla version 2023.1.0-rc4 but without LWT writes - user cassandra-stress standart insert (instead of LWT insert that defined in the user profile):
```
"cassandra-stress user profile=/tmp/c-s_lwt_big_data_multidc.yaml n=10000000 ops'(insert=1)' cl=LOCAL_QUORUM serial-cl=LOCAL_SERIAL -mode native cql3 -rate threads=1000"
```

The problem that described in the issue is not reproduced -  all c-s threads were completed immediatelly after the load finished (as expected)
![no_lwt_multidc_2023 1 rc4](https://user-images.githubusercontent.com/34435448/234267878-9804ed87-4fd3-40c1-9e2d-209f6f023689.png)





## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.19.0-1022-aws
Scylla version (or git commit hash): `2023.1.0~rc4-20230402.f90af81a13cc` with build-id `4db7799d283c7ca63c7639b04db34c301dbcfb66`




Cluster size: 9 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-50f008fa-9 (44.215.107.250 | 10.12.0.45) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-50f008fa-8 (54.237.104.21 | 10.12.2.12) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-50f008fa-7 (34.209.74.125 | 10.15.2.204) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-50f008fa-6 (34.221.132.245 | 10.15.3.114) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-50f008fa-5 (52.37.64.117 | 10.15.3.169) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-50f008fa-4 (54.75.77.183 | 10.4.1.115) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-50f008fa-3 (52.212.53.182 | 10.4.1.138) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-50f008fa-2 (34.244.186.92 | 10.4.3.146) (shards: 30)
- lwt-longevity-multi-dc-24h-lwt-mult-db-node-50f008fa-1 (52.213.23.43 | 10.4.1.178) (shards: 30)


OS / Image: `ami-000f0d43cb22bd09e ami-05e6f6036da2909d7 ami-0f30f07a6cb913353` (aws: eu-west-1)

Test: `longevity-lwt-24h-multidc-test`
Test id: `50f008fa-b3b0-4102-a3d9-412a08b2a1e9`
Test name: `scylla-staging/yulia/longevity-lwt-24h-multidc-test`
Test config file(s):

- [longevity-lwt-24h-multidc.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ccadfb6173e7261d9928e1627a51ab46551182f5/test-cases/longevity/longevity-lwt-24h-multidc.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 50f008fa-b3b0-4102-a3d9-412a08b2a1e9`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=50f008fa-b3b0-4102-a3d9-412a08b2a1e9)
- Show all stored logs command: `$ hydra investigate show-logs 50f008fa-b3b0-4102-a3d9-412a08b2a1e9`


## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-lwt-24h-multidc-test/24/)
</details>

**Comment by DoronArazii** [comment] 2023-04-30 11:22
@gleb-cloudius can you please check this

**Comment by gleb-cloudius** [comment] 2023-04-30 11:28
What exactly do I suppose to check there? I do not see anything special except overloaded nodes. Why cassandra-stress does not complete? I could not care less since I am not going to debug cassandra-stress.

**Comment by juliayakovlev** [comment] 2023-04-30 13:19
I ran exactly same scenario with different versions and two configurations.
The problem started from 5.2 / 2023.1 and did not happened before.
It happens in multi DC cluster only.
It happens with LWT load only.

**Comment by gleb-cloudius** [comment] 2023-04-30 13:25
> I ran exactly same scenario with different versions and two configurations. 

Which versions what configurations?

> The problem started from 5.2 / 2023.1 and did not happened before.

What problem? Hanging cassandra-stress? This is not Scylla problem no matter how you look at it. So from Scylla POV which problem is new?

> It happens in multi DC cluster only. It happens with LWT load only.

LWT puts much more stress on the system. You cannot compare two runs one with LWT and SERIAL consistency over 9 nodes and another no LWT and LOCAL_QUORUM. That just does not make any sense. You cannot come to any conclusion from comparing those two runs except that one loads system more than another.

**Comment by juliayakovlev** [comment] 2023-04-30 13:32
> > I ran exactly same scenario with different versions and two configurations.
> 
> Which versions what configurations?

All information is in issue description

> 
> > The problem started from 5.2 / 2023.1 and did not happened before.
> 
> What problem? Hanging cassandra-stress? This is not Scylla problem no matter how you look at it. So from Scylla POV which problem is new?

The problem is handreds of thousands timeouts

> 
> > It happens in multi DC cluster only. It happens with LWT load only.
> 
> LWT puts much more stress on the system. You cannot compare two runs one with LWT and SERIAL consistency over 9 nodes and another no LWT and LOCAL_QUORUM. That just does not make any sense. You cannot come to any conclusion from comparing those two runs except that one loads system more than another.

I did not come to any conclusion. I just described test results.

**Comment by gleb-cloudius** [comment] 2023-04-30 15:27
> > > I ran exactly same scenario with different versions and two configurations.
> > 
> > 
> > Which versions what configurations?
> 
> All information is in issue description

The only relevant info there is that in 5.2 the load fails with timeouts and in 5.1 it does not.

Since nothing changes in LWT between those two it is either io scheduler change or commitlog changes. @xemul @elcallio did we have ant between those two version.

> 
> > > The problem started from 5.2 / 2023.1 and did not happened before.
> > 
> > 
> > What problem? Hanging cassandra-stress? This is not Scylla problem no matter how you look at it. So from Scylla POV which problem is new?
> 
> The problem is handreds of thousands timeouts

Now we are talking. So what bug report should contain is an error graphs for 5.1 and 5.2 for _exactly same_ load.

> 
> > > It happens in multi DC cluster only. It happens with LWT load only.
> > 
> > 
> > LWT puts much more stress on the system. You cannot compare two runs one with LWT and SERIAL consistency over 9 nodes and another no LWT and LOCAL_QUORUM. That just does not make any sense. You cannot come to any conclusion from comparing those two runs except that one loads system more than another.
> 
> I did not come to any conclusion. I just described test results.

Irrelevant info makes it harder to understand what the ticket is about. If you have a load that fails on version X and does not fail on version Y this is enough info for the issue.

**Comment by eliransin** [comment] 2023-05-02 11:41
@juliayakovlev can we please have a link to a monitor from the older version (the one that doesn't have the problem but was ran with LWT)?
We need to compare what is going on between those two versions.

**Comment by eliransin** [comment] 2023-05-02 11:47
Also since there is a large distance between those two versions. Instead of debugging it, especially if it reproduces reliably (@juliayakovlev does this reproduce reliably?). We can take the bisection approach to lock in on the commit that caused this.

**Comment by juliayakovlev** [comment] 2023-05-02 11:57
> Restore Monitor Stack command: `$ hydra investigate show-monitor 37b25e8e-ffc9-44c4-ab87-5165fdb5808a

You can restore Monitor Stack for test running 5.1.8 Scylla, 2 possibilities:

1. using command: `$ hydra investigate show-monitor 37b25e8e-ffc9-44c4-ab87-5165fdb5808a`
2. on AWS: https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=37b25e8e-ffc9-44c4-ab87-5165fdb5808a

See time frame `&from=1682350808212&to=1682421196611`

**Comment by juliayakovlev** [comment] 2023-05-02 11:59
Actually I added `test_id` for each run that I described in the issue. You can restore a monitor for each run that you need

**Comment by juliayakovlev** [comment] 2023-05-02 11:59
> Also since there is a large distance between those two versions. Instead of debugging it, especially if it reproduces reliably (@juliayakovlev does this reproduce reliably?). We can take the bisection approach to lock in on the commit that caused this.

Yes, it is reproduced reliably

**Comment by DoronArazii** [comment] 2023-05-03 11:15
Removing triage, Eliran is bisecting the issue

**Comment by mykaul** [comment] 2023-05-04 08:07
@eliransin - any updates?

**Comment by mykaul** [comment] 2023-05-04 08:10
@roydahan , @fgelcer - is i3.8xlarge affected by the 5.19 kernel issue? Perhaps this is the issue?

**Comment by mykaul** [comment] 2023-05-04 08:12
@juliayakovlev - how was the load adjusted to the async configuration of the different DCs:
```
eu-west-1 - 4 nodes
us-west-2 - 3 nodes
us-east-1 -2 nodes
```

?

**Comment by juliayakovlev** [comment] 2023-05-04 09:16
> @juliayakovlev - how was the load adjusted to the async configuration of the different DCs:
> 
> ```
> eu-west-1 - 4 nodes
> us-west-2 - 3 nodes
> us-east-1 -2 nodes
> ```
> 
> ?

A loader is created in the every DC. Load is sent from each loader to the local DB nodes and it is not changed depends on nodes amount in the DC

**Comment by roydahan** [comment] 2023-05-04 10:15
> @roydahan , @fgelcer - is i3.8xlarge affected by the 5.19 kernel issue? Perhaps this is the issue?

Could be, but I recall we asked to re-run it with RC5 (somewhere).

@juliayakovlev did you run it with 5.2.0-rc5 / 2023.1.0-rc5?
If not, please re-run ASAP.

**Comment by eliransin** [comment] 2023-05-04 11:17
Summary of what I discussed with @juliayakovlev : 
The actual symptom is that `cassandra-stress` runs and at some point spits out statistics, however it doesn't terminate and the log keeps getting spammed with timeout erros. While in the non erroneous case the stress thread terminates immediately.

There are two consequences here:
1. Why does cassandra stress doesn't terminate.
2. Why are there so many timeouts during the load.

I think that before bisection we should stabilize the test:
1. The stress thread should terminate in reasonable time especially if there are failures during the run, we should review the cassandra stress code and make it stable. If it is a congestion on the log we should solve it somehow, for example, Scylla uses rate limiting for the log.
2. In parallel we should bisect and find the commit where it started and fix it.

**Comment by juliayakovlev** [comment] 2023-05-04 11:19
> > @roydahan , @fgelcer - is i3.8xlarge affected by the 5.19 kernel issue? Perhaps this is the issue?
> 
> Could be, but I recall we asked to re-run it with RC5 (somewhere).
> 
> @juliayakovlev did you run it with 5.2.0-rc5 / 2023.1.0-rc5? If not, please re-run ASAP.

Running

**Comment by juliayakovlev** [comment] 2023-05-04 14:32
> > @roydahan , @fgelcer - is i3.8xlarge affected by the 5.19 kernel issue? Perhaps this is the issue?
> 
> Could be, but I recall we asked to re-run it with RC5 (somewhere).
> 
> @juliayakovlev did you run it with 5.2.0-rc5 / 2023.1.0-rc5? If not, please re-run ASAP.

I ran the test with 5.2.0-rc5 and 2023.1.0-rc5 - problem is not reproduced

**Comment by mykaul** [comment] 2023-05-04 18:50
Thanks @juliayakovlev ! 
Closing - if it reproduces, please re-open.

**Closed by mykaul** 2023-05-04 18:50 UTC
Labels: Regression, P1
