### ISSUE TITLE
Failed to bootstrap after decommission

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#16704] opened 2024-01-10 02:17 UTC
Scylla commit: 94580df1c59be7508853e7d99f49177894f1ff86

- Start n1, n2, n3
- Decommission n3
- Clear all scylla data on node 3
- Start n3 again as a new node
-  Node n3 fails to bootstrap, hangs forever

logs of n3 when bootstrap again after decommission
```
INFO  2024-01-10 10:11:28,854 [shard 0:strm] query_processor - Column definitions for system_traces.events changed, invalidating related prepared statements
INFO  2024-01-10 10:11:28,854 [shard 0:strm] query_processor - Column definitions for system_distributed.service_levels changed, invalidating related prepared statements
INFO  2024-01-10 10:11:28,854 [shard 0:strm] query_processor - Column definitions for system_traces.node_slow_log changed, invalidating related prepared statements
INFO  2024-01-10 10:11:28,854 [shard 0:strm] query_processor - Column definitions for system_traces.sessions changed, invalidating related prepared statements
INFO  2024-01-10 10:11:28,854 [shard 0:strm] query_processor - Column definitions for system_traces.node_slow_log_time_idx changed, invalidating related prepared statements
INFO  2024-01-10 10:11:28,854 [shard 0:strm] query_processor - Column definitions for system_distributed.cdc_generation_timestamps changed, invalidating related prepared statements
INFO  2024-01-10 10:11:28,859 [shard 0:strm] schema_tables - Schema version changed to 3665346a-af5d-11ee-8a5a-de4901f742e6
INFO  2024-01-10 10:11:28,861 [shard 0:comp] compaction - [Compact system.raft 90981790-af5d-11ee-bf5a-5d4ccc1401d1] Compacted 2 sstables to [tmp/3/data/system/raft-3e17774c57f539939625327cbafbf5bb/md-3gcn_0634_4mr342wragk59xv5ch-big-Data.db:level=0]. 188kB to 183kB (~97% of original) in 68ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2024-01-10 10:11:28,861 [shard 0:comp] compaction - [Compact system.scylla_local 90a4e8d0-af5d-11ee-bf5a-5d4ccc1401d1] Compacting [tmp/3/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/md-3gcn_0634_4mjdd2wragk59xv5ch-big-Data.db:level=0:origin=memtable,tmp/3/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/mc-3gcn_0634_3xglc2wragk59xv5ch-big-Data.db:level=0:origin=memtable]
INFO  2024-01-10 10:11:28,910 [shard 0: gms] gossip - InetAddress 127.0.0.1 is now UP, status = NORMAL
INFO  2024-01-10 10:11:28,910 [shard 0: gms] gossip - InetAddress 127.0.0.2 is now UP, status = NORMAL
INFO  2024-01-10 10:11:28,910 [shard 0:comp] compaction - [Compact system.scylla_local 90a4e8d0-af5d-11ee-bf5a-5d4ccc1401d1] Compacted 2 sstables to [tmp/3/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3gcn_0634_54jip2wragk59xv5ch-big-Data.db:level=0]. 10kB to 5kB (~53% of original) in 41ms = 261kB/s. ~256 total partitions merged to 3.
INFO  2024-01-10 10:11:28,911 [shard 0:comp] compaction - [Compact system_schema.tables 90ac62e0-af5d-11ee-bf5a-5d4ccc1401d1] Compacting [tmp/3/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-4-big-Data.db:level=0:origin=memtable,tmp/3/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-3-big-Data.db:level=0:origin=compaction]
INFO  2024-01-10 10:11:28,960 [shard 0:comp] compaction - [Compact system_schema.tables 90ac62e0-af5d-11ee-bf5a-5d4ccc1401d1] Compacted 2 sstables to [tmp/3/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3gcn_0634_5f9bk2wragk59xv5ch-big-Data.db:level=0]. 21kB to 14kB (~67% of original) in 40ms = 540kB/s. ~256 total partitions merged to 6.
INFO  2024-01-10 10:11:28,974 [shard 0:main] raft_group_registry - marking Raft server 36fae674-3ba7-4da9-9f3f-932bfaaad3a3 as alive for raft groups
WARN  2024-01-10 10:11:29,851 [shard 0:strm] storage_service - (rate limiting dropped 196 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:30,853 [shard 0:strm] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:31,858 [shard 0:strm] storage_service - (rate limiting dropped 193 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:32,862 [shard 0:strm] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:33,865 [shard 0:strm] storage_service - (rate limiting dropped 195 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:34,865 [shard 0:strm] storage_service - (rate limiting dropped 195 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:35,870 [shard 0:strm] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:36,874 [shard 0:strm] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:37,876 [shard 0:strm] storage_service - (rate limiting dropped 193 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:38,880 [shard 0:strm] storage_service - (rate limiting dropped 197 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:39,881 [shard 0:strm] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:40,885 [shard 0:strm] storage_service - (rate limiting dropped 196 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:41,887 [shard 0:strm] storage_service - (rate limiting dropped 196 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:42,888 [shard 0:strm] storage_service - (rate limiting dropped 197 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:43,891 [shard 0:strm] storage_service - (rate limiting dropped 196 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:44,894 [shard 0:strm] storage_service - (rate limiting dropped 196 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:45,895 [shard 0:strm] storage_service - (rate limiting dropped 196 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:46,898 [shard 0:strm] storage_service - (rate limiting dropped 197 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:47,899 [shard 0:strm] storage_service - (rate limiting dropped 196 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:48,904 [shard 0:strm] storage_service - (rate limiting dropped 196 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:49,905 [shard 0:strm] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:50,907 [shard 0:strm] storage_service - (rate limiting dropped 195 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:51,910 [shard 0:strm] storage_service - (rate limiting dropped 195 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:52,910 [shard 0:strm] storage_service - (rate limiting dropped 196 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:53,911 [shard 0:strm] storage_service - (rate limiting dropped 194 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
WARN  2024-01-10 10:11:54,915 [shard 0:strm] storage_service - (rate limiting dropped 195 similar messages) raft topology: cannot map 0c14169f-5858-4dbf-9230-7c6c73f94984 to ip, retrying.
```

Before decommission
```
$ nodetool status
Datacenter: dc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.1  181.53 KB  256          ?       2a764c8d-73aa-4fd3-8826-691d0dc781f4  rack1
UN  127.0.0.2  407.6 KB   256          ?       36fae674-3ba7-4da9-9f3f-932bfaaad3a3  rack2
UN  127.0.0.3  380.2 KB   256          ?       0c14169f-5858-4dbf-9230-7c6c73f94984  rack3
```
After decommission
```
$ nodetool status
Datacenter: dc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.1  181.53 KB  256          ?       2a764c8d-73aa-4fd3-8826-691d0dc781f4  rack1
UN  127.0.0.2  407.6 KB   256          ?       36fae674-3ba7-4da9-9f3f-932bfaaad3a3  rack2

```

**Comment by kbr-scylla** [comment] 2024-01-11 10:00
@asias please provide all logs

**Comment by kbr-scylla** [comment] 2024-01-11 10:03
Do you have a test case?

Is this using the experimental raft-based topology?

**Comment by asias** [comment] 2024-01-11 10:12
On Thu, Jan 11, 2024, 18:03 Kamil Braun ***@***.***> wrote:

> Do you have a test case?
>

No. I played with the cluster manually.

Is this using the experimental raft-based topology?
>

Yes.

**Comment by asias** [comment] 2024-01-11 10:14
On Thu, Jan 11, 2024, 18:00 Kamil Braun ***@***.***> wrote:

> @asias <https://github.com/asias> please provide all logs
>
The scenario is super simple. I suggest you to reproduce locally.

**Comment by kbr-scylla** [comment] 2024-01-11 10:27
If it's with experimental raft-based topology (which would be useful to mention when reporting the issue...), then it's a duplicate of https://github.com/scylladb/scylladb/issues/14803.

**Closed by kbr-scylla** 2024-01-11 10:27 UTC
Labels: topology changes

**Comment by asias** [comment] 2024-01-11 12:20
> If it's with experimental raft-based topology (which would be useful to mention when reporting the issue...), then it's a duplicate of #14803.

This is the flags I used. 

--consistent-cluster-management true --experimental-features consistent-topology-changes --experimental-features tablets

Do we have plans to fix it? The issue 14803 was there for a while now. 

It is making some of the tablet tests harder, e.g., I want to run bootstrap / decommission in a loop to stress file stream for tablet. 

@xemul  FYI. For you perf test projects.

**Comment by kbr-scylla** [comment] 2024-01-11 12:21
> Do we have plans to fix it? 

I believe https://github.com/scylladb/scylladb/pull/16639 is the fix
