### ISSUE TITLE
test_mv_tablets.test_tablet_mv_simple_6node failed during concurrent bootstrap of 6 nodes

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#16423] opened 2023-12-15 10:20 UTC
It failed on next after https://github.com/scylladb/scylladb/pull/16384 was queued: https://jenkins.scylladb.com/job/scylla-master/job/next/6939/.

Then, this PR was dequeued, however I don't think it caused the failure. The introduced changes shouldn't have any impact on the failed test. Hence, I believe that similar failures might appear in CI.

In logs of one of the nodes, we can see:
```
11:58:07.127 ERROR> [dev/topology_experimental_raft.test_mv_tablets.1] last line of /scylladir/testlog/aarch64/dev/scylla-400.log:
ERROR 2023-12-14 11:58:07,127 [shard 0: gms] storage_service - raft topology: raft_topology_cmd failed with: raft::stopped_error (Raft instance is stopped, reason: "background error, exceptions::mutation_write_failure_exception (stale topology exception, caller version 4, callee fence version 5)")
```

`test_tablet_mv_simple_6node` uses a new function -- `ManagerClient.servers_add` -- that allows for adding multiple nodes to the cluster concurrently. It's supported only in the Raft-based topology mode. The logs above suggest that there is a bug somewhere in the Raft-based topology, and it reveals itself during concurrent bootstrap.

**Comment by patjed41** [comment] 2023-12-15 10:22
I'm investigating it.

**Comment by yaronkaikov** [comment] 2023-12-19 10:06
@patjed41 We ad another failure with the same test - https://jenkins.scylladb.com/job/scylla-master/job/next/6963/artifact/testlog/aarch64/debug/topology_experimental_raft.test_mv_tablets.1.log , Can you verify if it's the same issue?

**Comment by kbr-scylla** [comment] 2023-12-19 10:41
It looks like in this case we simply timed out bootstrap because it took too long, but didn't get stuck.
https://jenkins.scylladb.com/job/scylla-master/job/next/6963/artifact/testlog/aarch64/debug/scylla-498.log
```
WARN  2023-12-19 08:40:45,997 seastar - Seastar compiled with default allocator, --memory option won't take effect
...
INFO  2023-12-19 08:57:19,830 [shard 0: gms] storage_service - raft topology: streaming completed
```


The test is booting 10 node cluster. Crazy!
```python
    @pytest.mark.asyncio
    @skip_mode('release', 'error injections are not supported in release mode')
    async def test_tablet_alternator_lsi_consistency(manager: ManagerClient):
        """A reproducer for a bug where Alternator LSI was not using synchronous
           view updates when tablets are enabled, which could cause strongly-
           consistent read of the LSI to miss the data just written to the base.
           We use a fairly large cluster to increase the chance that the tablet
           randomization results in non-local pairing of base and view tablets.
           We could make this test fail more reliably and only need 4 nodes if
           we had an API to control the tablet placement.
           We also use the "delay_before_remote_view_update" injection point
           to add a delay to the view update - without it it's almost impossible
           to reproduce this issue on a fast machine.
           Reproduces #16313.
        """
>       servers = await manager.servers_add(10, config=alternator_config)
```

@nyh why? You mentioned the possibility of API for tablet placement (or error injection) and requiring only 4 nodes -- *this is the way*, not booting a 10 cluster which is still unreliable for reproducing the problem!

And now we have a test that times out after 26 minutes.

**Comment by patjed41** [comment] 2023-12-19 10:52
Maybe we should add an upper limit for the number of nodes that can be added by a single `servers_add` call? Or at least some warning in the comment?

My reasoning is that it's not obvious how slow adding 10 servers can be. Also, adding all of them at once is very convenient. People will write similar (potentially flaky) tests.

We can also increase the `TOPOLOGY_TIMEOUT`, but I don't think it should be the approach here.

**Comment by kbr-scylla** [comment] 2023-12-19 11:00
> We can also increase the TOPOLOGY_TIMEOUT, but I don't think it should be the approach here.

It's already crazy high, if anything I would vote to decrease it...

**Comment by patjed41** [comment] 2023-12-19 11:09
Maybe we don't need to do anything. We already have tests that really need a 7 node cluster, for example in `test_raft_ignore_nodes.py`. However, these tests are ignored in the debug mode. So, they shouldn't be even close to reaching this crazy 1000 s limit. The "big cluster -> ignore in debug mode" policy should be enough to avoid this kind of failures.

**Comment by kbr-scylla** [comment] 2023-12-19 11:13
> The "big cluster -> ignore in debug mode" policy

Don't tell @avikivity that I have such policy.

**Comment by nyh** [comment] 2023-12-19 12:04
> The test is booting 10 node cluster. Crazy!

A 10-node cluster is... crazy?
Sad.

I wasn't happy with that 10-node cluster, and I have a followup patch (https://github.com/scylladb/scylladb/pull/16440, please review) to turn it into a 2-node cluster. But a 10-node cluster is NOT crazy. Certainly not in a test suite which is aimed at multi-node clusters. What is crazy is that we can't boot a 10-node cluster in less than 10 seconds.

> > @nyh why? You mentioned the possibility of API for tablet placement (or error injection) and requiring only 4 nodes -- _this is the way_, not booting a 10 cluster which is still unreliable for reproducing the problem!

Yes, I already did this: https://github.com/scylladb/scylladb/pull/16440
Don't even need 4 nodes - 2 are enough.

> And now we have a test that times out after 26 minutes.

Instead of shooting the messenger, let's shoot the real blame - the fact that it takes 26 minutes (!!!????) to start a cluster of 10 nodes.

**Comment by nyh** [comment] 2023-12-19 12:07
> Maybe we don't need to do anything. We already have tests that really need a 7 node cluster, for example in `test_raft_ignore_nodes.py`. However, these tests are ignored in the debug mode. 

If you guys - the test/topology experts - figured out that tests that use a cluster of more than 5 nodes can't be run on debug mode - then please make it official - have servers_add() call pytest.skip() when called to add more than 5 nodes in debug mode. Then we won't need to remember this every time in the future when somebody tries to write a test requiring a bigger cluster.

**Comment by nyh** [comment] 2023-12-19 12:21
I suggest https://github.com/scylladb/scylladb/issues/16465 as a solution to this issue.

**Comment by kbr-scylla** [comment] 2023-12-19 12:22
The original issue was not caused by too long boot times, it was (is) a bug in topology coordinator that causes boot process to get stuck forever.

> if 6 nodes is too big, what isn't too big? Isn't 3 also too big?

I don't think 6 nodes is too big.

All I'm saying is that we should be **careful** when adding tests.

Even 20 node test is ok if we think it's valuable to test large clusters in test.py. And we understand the consequences of it and decided that our CI can withstand it.

Heck, at some point @kostja wanted to test 100 node cluster. But found that boot is too slow to do it. That thread got stuck. We need to investigate deeper how to speed up boot.

But you yourself said that whatever you wanted to test could be done with 2 nodes. So the 10 nodes cluster was total overkill.

**Comment by nyh** [comment] 2023-12-19 12:26
> The original issue was not caused by too long boot times, it was (is) a bug in topology coordinator that causes boot process to get stuck forever.

Oh, I didn't realize that this issue was "overtaken" by an unrelated discussion.
So I guess the 6-node test is ok - even better than ok if it helps reproduce a bug.

The 10-node test is unrelated to the original report in this issue. It was indeed an overkill (not "crazy" as you called it, but an overkill), and I got rid of it in https://github.com/scylladb/scylladb/pull/16440 and it will use just 2 nodes, not 10. We need to crack up the speed of our review process if we don't want to discuss things that were already fixed in later PRs :-(

**Closed** 2023-12-30 20:58 UTC
Labels: topology changes, raft, CI-Stability
