### ISSUE TITLE
[dtest-debug] error during node shutdown: "raft::state_machine_error" "exceptions::mutation_write_failure_exception (Operation failed for system.cdc_local - received 0 responses and 1 failures from 1 CL=ONE"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#19665] opened 2024-07-09 16:20 UTC
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/308/testReport/schema_test/TestSchema/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split002___test_restart_with_large_tables/

The scenario seems to have:
1. node restart.
2. raft_topology - updating topology state: Tablet migration
3. stop node after test ended.
4. got errors of:
```
ERROR 2024-07-07 06:25:18,039 [shard 0: gms] storage_proxy - exception during mutation write to 127.0.72.1: utils::internal::nested_exception<std::runtime_error> (Could not write mutation system:cdc_local (pk{00096364635f6c6f63616c}) to commitlog): seastar::gate_closed_exception (gate closed)
```
```
ERROR 2024-07-07 06:25:18,040 [shard 0: gms] raft - [26a65798-570e-4cef-b919-8037b1f969f1] applier fiber stopped because of the error: std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1339): exceptions::mutation_write_failure_exception (Operation failed for system.cdc_local - received 0 responses and 1 failures from 1 CL=ONE.)
```
So it looks like some expected problems during shutdown process are not handled well enough.
A fuller log:
```
INFO  2024-07-07 06:25:17,653 [shard 0: gms] raft_topology - updating topology state: Tablet migration
INFO  2024-07-07 06:25:17,663 [shard 0:main] gossip - Disable and wait for gossip loop started
INFO  2024-07-07 06:25:17,663 [shard 0:main] gossip - Gossip is now stopped
INFO  2024-07-07 06:25:17,664 [shard 0:main] storage_service - Stop transport: stop_gossiping done
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Shutting down nontls server
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Shutting down tls server
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Shutting down tls server - Done
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Stopping client for address: 127.0.72.1:0
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,664 [shard 0:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,664 [shard 1:main] messaging_service - Shutting down nontls server
INFO  2024-07-07 06:25:17,664 [shard 1:main] messaging_service - Shutting down tls server
INFO  2024-07-07 06:25:17,664 [shard 1:main] messaging_service - Shutting down tls server - Done
INFO  2024-07-07 06:25:17,664 [shard 1:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 1:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 1:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 1:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 1:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 1:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 1:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 1:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 1:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 1:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 1:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 1:main] messaging_service - Shutting down nontls server - Done
INFO  2024-07-07 06:25:17,665 [shard 0:main] messaging_service - Stopping client for address: 127.0.72.1:0 - Done
INFO  2024-07-07 06:25:17,665 [shard 0:main] messaging_service - Stopped clients
INFO  2024-07-07 06:25:17,665 [shard 0:main] messaging_service - Shutting down nontls server - Done
INFO  2024-07-07 06:25:17,665 [shard 0:main] storage_service - Stop transport: shutdown messaging_service done
INFO  2024-07-07 06:25:17,666 [shard 0:main] storage_service - Stop transport: shutdown stream_manager done
INFO  2024-07-07 06:25:17,666 [shard 0:main] storage_service - Stop transport: done
INFO  2024-07-07 06:25:17,666 [shard 0:main] tracing - Asked to shut down
INFO  2024-07-07 06:25:17,666 [shard 0:main] tracing - Tracing is down
INFO  2024-07-07 06:25:17,667 [shard 1:main] tracing - Asked to shut down
INFO  2024-07-07 06:25:17,667 [shard 1:main] tracing - Tracing is down
INFO  2024-07-07 06:25:17,667 [shard 0:main] batchlog_manager - Asked to drain
INFO  2024-07-07 06:25:17,667 [shard 0:main] batchlog_manager - Drained
INFO  2024-07-07 06:25:17,667 [shard 1:main] batchlog_manager - Asked to drain
INFO  2024-07-07 06:25:17,667 [shard 1:main] batchlog_manager - Drained
INFO  2024-07-07 06:25:17,667 [shard 0:main] view - Draining view builder
INFO  2024-07-07 06:25:17,668 [shard 1:main] view - Draining view builder
INFO  2024-07-07 06:25:17,668 [shard 0:main] compaction_manager - Asked to drain
INFO  2024-07-07 06:25:17,668 [shard 0:main] compaction_manager - Drained
INFO  2024-07-07 06:25:17,669 [shard 1:main] compaction_manager - Asked to drain
INFO  2024-07-07 06:25:17,669 [shard 1:main] compaction_manager - Drained
INFO  2024-07-07 06:25:17,669 [shard 0:main] database - Flushing non-system tables
INFO  2024-07-07 06:25:17,670 [shard 1:main] database - Flushing non-system tables
INFO  2024-07-07 06:25:17,674 [shard 1:main] database - Flushed non-system tables
INFO  2024-07-07 06:25:17,674 [shard 0:main] database - Flushed non-system tables
INFO  2024-07-07 06:25:17,675 [shard 1:main] database - Flushing system tables
INFO  2024-07-07 06:25:17,675 [shard 0:main] database - Flushing system tables
WARN  2024-07-07 06:25:17,759 [shard 0: gms] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
INFO  2024-07-07 06:25:17,761 [shard 1:main] database - Flushed system tables
INFO  2024-07-07 06:25:18,024 [shard 0:main] database - Flushed system tables
INFO  2024-07-07 06:25:18,033 [shard 0:main] init - Shutting down local storage was successful
INFO  2024-07-07 06:25:18,033 [shard 0:main] init - Shutting down view builder API
INFO  2024-07-07 06:25:18,034 [shard 0:main] init - Shutting down view builder API was successful
INFO  2024-07-07 06:25:18,034 [shard 0:main] init - Shutting down hinted handoff API
INFO  2024-07-07 06:25:18,035 [shard 0:main] init - Shutting down hinted handoff API was successful
INFO  2024-07-07 06:25:18,035 [shard 0:main] init - Shutting down view update backlog broker
INFO  2024-07-07 06:25:18,038 [shard 0:main] init - Shutting down view update backlog broker was successful
INFO  2024-07-07 06:25:18,038 [shard 0:main] init - Shutting down cf cache hit rate calculator
ERROR 2024-07-07 06:25:18,039 [shard 0: gms] storage_proxy - exception during mutation write to 127.0.72.1: utils::internal::nested_exception<std::runtime_error> (Could not write mutation system:cdc_local (pk{00096364635f6c6f63616c}) to commitlog): seastar::gate_closed_exception (gate closed)
INFO  2024-07-07 06:25:18,040 [shard 0:main] init - Shutting down cf cache hit rate calculator was successful
INFO  2024-07-07 06:25:18,040 [shard 0:main] init - Shutting down load meter API
ERROR 2024-07-07 06:25:18,040 [shard 0: gms] raft - [26a65798-570e-4cef-b919-8037b1f969f1] applier fiber stopped because of the error: std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1339): exceptions::mutation_write_failure_exception (Operation failed for system.cdc_local - received 0 responses and 1 failures from 1 CL=ONE.)
INFO  2024-07-07 06:25:18,041 [shard 0:main] init - Shutting down load meter API was successful
INFO  2024-07-07 06:25:18,041 [shard 0:main] init - Shutting down load meter
INFO  2024-07-07 06:25:18,041 [shard 0:main] init - Shutting down load meter was successful
INFO  2024-07-07 06:25:18,041 [shard 0:main] init - Shutting down batchlog manager
INFO  2024-07-07 06:25:18,041 [shard 0:main] batchlog_manager - Asked to stop
INFO  2024-07-07 06:25:18,041 [shard 0:main] batchlog_manager - Stopped
INFO  2024-07-07 06:25:18,041 [shard 0:strm] raft_topology - raft_state_monitor_fiber aborted with raft::stopped_error (Raft instance is stopped, reason: "background error, std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1339): exceptions::mutation_write_failure_exception (Operation failed for system.cdc_local - received 0 responses and 1 failures from 1 CL=ONE.)")
INFO  2024-07-07 06:25:18,041 [shard 1:main] batchlog_manager - Asked to stop
INFO  2024-07-07 06:25:18,041 [shard 1:main] batchlog_manager - Stopped
ERROR 2024-07-07 06:25:18,041 [shard 0: gms] raft_topology - topology change coordinator fiber got error raft::stopped_error (Raft instance is stopped, reason: "background error, std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1339): exceptions::mutation_write_failure_exception (Operation failed for system.cdc_local - received 0 responses and 1 failures from 1 CL=ONE.)")
INFO  2024-07-07 06:25:18,042 [shard 0:main] init - Shutting down batchlog manager was successful
```
[logs-full.debug.002.zip](https://github.com/user-attachments/files/16146449/logs-full.debug.002.zip)

**Comment by mykaul** [comment] 2024-07-10 12:21
@yarongilor - labels?

**Comment by piodul** [comment] 2024-07-15 08:04
Looking at recent master, commit c11f2c9bcdffe00622a5fea0e2171d53fe361b68.

Line 1871:

```c++
            auto stop_group0_service = defer_verbose_shutdown("group 0 service", [&group0_service] {
                sl_controller.local().abort_group0_operations();
                group0_service.abort().get();
            });
```

Line 2061:

```c++
            // Register at_exit last, so that storage_service::drain_on_shutdown will be called first
            auto do_drain = defer_verbose_shutdown("local storage", [&ss] {
                ss.local().drain_on_shutdown().get();
            });
```

Shutdown handlers run in reverse order, so it looks like we drain storage_service before stopping group0. After drain, it's not really possible to apply any mutations, even to the internal tables. Apparently, the group0 applier fiber tries to apply some commands after drain has already happened.

cc: @kbr-scylla @gleb-cloudius

**Comment by gleb-cloudius** [comment] 2024-07-17 12:20
We stop using group0 in ss her:

Line 1892

```
            // Need to make sure storage service does not use group0 before running group0_service.abort()
            auto stop_group0_usage_in_storage_service = defer_verbose_shutdown("group 0 usage in local storage", [&ss] {
                ss.local().wait_for_group0_stop().get();
            });
```

Still after draining, but may be it can be moved earlier.

**Comment by bhalevy** [comment] 2024-08-18 09:33
Similar failure here: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/316/testReport/snapshot_test/TestParallelSnapshotOperations/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split010___test_parallel_operations_create_list_clear_for_all_ks/
```
failed on teardown with "AssertionError: Unexpected errors found:
node1: 2 errors
ERROR 2024-08-18 06:51:33,933 [shard 0: gms] storage_proxy - exception during mutation write to 127.0.85.1: utils::internal::nested_exception<std::runtime_error> (Could not write mutation system:scylla_local (pk{0010656e61626c65645f6665617475726573}) to commitlog): seastar::gate_closed_exception (gate closed)
ERROR 2024-08-18 06:51:33,933 [shard 0: gms] raft - [d3fbd6bb-4e7d-4cef-85e4-54917240bc62] applier fiber stopped because of the error: std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1340): exceptions::mutation_write_failure_exception (Operation failed for system.scylla_local - received 0 responses and 1 failures from 1 CL=ONE.)"
```

[logs.tar.gz](https://github.com/user-attachments/files/16647872/logs.tar.gz)

**Comment by Annamikhlin** [comment] 2024-08-19 07:20
seen also here https://jenkins.scylladb.com/job/scylla-master/job/next/8081/testReport/junit/snapshot_test/TestParallelSnapshotOperations/Build___x86___dtest_with_tablets___test_parallel_operations_for_10ks_and_10tables_and_clearallsnapshots/

**Comment by bhalevy** [comment] 2024-08-21 06:57
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/next/8090/testReport/junit/snapshot_test/TestParallelSnapshotOperations/Build___x86___dtest_with_tablets___test_parallel_operations_for_10ks_and_10tables_and_clearallsnapshots/

**Comment by mykaul** [comment] 2024-08-21 07:14
@kbr-scylla - this needs some attention.

**Comment by kostja** [comment] 2024-08-21 09:09
This is a duplicate of https://github.com/scylladb/scylladb/issues/20215

**Comment by mykaul** [comment] 2024-08-25 12:27
> This is a duplicate of #20215

But https://github.com/scylladb/scylladb/issues/20215#issuecomment-2301563321 claims that #20215 is a dup of this one, so we have a loop of some sort. Let's just solve it.

**Comment by mykaul** [comment] 2024-08-25 12:28
https://jenkins.scylladb.com/job/scylla-master/job/next/8108/testReport/junit/snapshot_test/TestParallelSnapshotOperations/Build___x86___dtest_with_tablets___test_parallel_operations_for_10ks_and_10tables_and_clearallsnapshots/

**Comment by mykaul** [comment] 2024-08-28 07:48
@kbr-scylla , @kostja - this needs attention. The test (https://jenkins.scylladb.com/job/scylla-master/job/next/8121/testReport/junit/snapshot_test/TestParallelSnapshotOperations/Build___x86___dtest_with_tablets___test_parallel_operations_for_10ks_and_10tables_and_clearallsnapshots/ ) keeps failing all over.

**Comment by kbr-scylla** [comment] 2024-08-28 09:18
Ok, I assigned @gleb-cloudius

**Comment by mykaul** [comment] 2024-08-29 11:02
Another failure from yesterday - https://jenkins.scylladb.com/job/scylla-master/job/next/8130/testReport/junit/snapshot_test/TestParallelSnapshotOperations/Build___x86___dtest_with_tablets___test_parallel_operations_for_10ks_and_10tables_and_clearallsnapshots/

**Comment by mykaul** [comment] 2024-09-01 11:19
@gleb-cloudius - any updates?  We keep seeing this quite consistently nowdays - https://jenkins.scylladb.com/job/scylla-master/job/next/8139/testReport/snapshot_test/TestParallelSnapshotOperations/Build___x86___dtest_with_tablets___test_parallel_operations_for_10ks_and_10tables_and_clearallsnapshots/

**Comment by gleb-cloudius** [comment] 2024-09-01 11:28
I have a patch to move stopping group0 before draining storage service, but I cannot guaranty that this will solve this particular problem. Will try to run the test locally.

**Comment by avikivity** [comment] 2024-09-01 14:41
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/269/

**Comment by avikivity** [comment] 2024-09-08 16:12
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/431/testReport/junit/snapshot_test/TestParallelSnapshotOperations/FullDtest___full_split001___test_parallel_operations_for_10ks_and_10tables_and_clearallsnapshots/   https://github.com/scylladb/scylladb/pull/20486#issuecomment-2336701667

**Closed** 2024-09-10 22:48 UTC
Labels: status/regression, tests/dtest, area/raft, P1, symptom/ci stability, symptom/shutdown, area/tablets

**Comment by mykaul** [comment] 2024-09-16 11:16
Do we have plans to backport this to 6.1.x?

**Comment by kbr-scylla** [comment] 2024-09-20 13:04
Better not. I suspect it caused a regression: https://github.com/scylladb/scylladb/issues/20701
