### ISSUE TITLE
test_rolling_upgrade: read from system_distributed.cdc_generation_timestamps: std::runtime_error (Can't find a column family with UUID fdf455c4-cfec-3e00-9719-d7a45436c89d)"

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#8149] opened 2021-02-24 09:48 UTC
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/752/testReport/rolling_upgrade_test/RollingUpgradeTest/test_rolling_upgrade/
Scylla version d905e71a90e1b371371148684a8ee6268ff5eeb5
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1130, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1184, in cleanUpCluster
    raise AssertionError('Unexpected errors found: {}'.format(found_errors))
AssertionError: Unexpected errors found: [('node1', ["ERROR 2021-02-24 05:47:07,986 [shard 0] storage_proxy - Exception when communicating with 127.0.97.3, to read from system_distributed.cdc_generation_timestamps: std::runtime_error (Can't find a column family with UUID fdf455c4-cfec-3e00-9719-d7a45436c89d)"])]
```

There seems to be a synchronization issue between the nodes.  I'm not sure if this could be considered an issue with scylla or is it just a benign error that can be ignored by the test.

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/752/artifact/logs-release.2/1614146138385_rolling_upgrade_test.RollingUpgradeTest.test_rolling_upgrade/node1.log
```
ERROR 2021-02-24 05:47:07,986 [shard 0] storage_proxy - Exception when communicating with 127.0.97.3, to read from system_distributed.cdc_generation_timestamps: std::runtime_error (Can't find a column family with UUID fdf455c4-cfec-3e00-9719-d7a45436c89d)
```

While it is created on node 3 a tidbit later.
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/752/artifact/logs-release.2/1614146138385_rolling_upgrade_test.RollingUpgradeTest.test_rolling_upgrade/node3.log
```
INFO  2021-02-24 05:47:07,992 [shard 0] schema_tables - Creating system_distributed.cdc_generation_timestamps id=fdf455c4-cfec-3e00-9719-d7a45436c89d version=5777e043-a81a-3324-8803-b497c056849f
```

**Comment by kbr-** [comment] 2021-02-24 10:50
A read is racing with table creation: the schema information arrives on replicas later than the reads which already use the schema. It's a replica side problem, where replicas don't perform a schema pull when they see a read that uses an unknown schema.

In this test run the read succeeded nevertheless (2 out of 3 replicas answered, which was enough); if it wouldn't, then the read would be retried and succeed eventually. The problem is benign and harmless.

It is fixed in c16e4a04239798c41fa140c14eabb250b5422983, but the problem will remain because for the fix to work the entire cluster must have the patch applied, which is of course not true during upgrade.

**Comment by bentsi** [comment] 2021-03-18 09:46
Happened during [rolling-upgrade-alternator-test#22](https://jenkins.scylladb.com/view/master/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-alternator-test/22/console)
```
2021-03-12T06:31:55+00:00  rolling-upgrade-master-centos-db-node-6353887e-0-2 !ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.142.0.66, to read from system_distributed.cdc_generation_timestamps: std::runtime_error (Can't find a column family with UUID fdf455c4-cfec-3e00-9719-d7a45436c89d)```
```

Test: upgrade_test.UpgradeTest.test_generic_cluster_upgrade
Build number: 22
Backend: gce: us-east1
Kernel version: 3.10.0-1160.15.2.el7.x86_64
Test-id: 6353887e-c117-45b8-8c02-1870e1071ada
Start time: 2021-03-12 05:47:30
End time: 2021-03-12 07:16:05
Started by user: timer
Test result: FAILED

System under test
- ScyllaDB version: `4.4.rc3-0.20210304.c2d924757 with build-id 1d0929cbdc3fd39b79157e974cd8d08cd2610afb (-)`
- Target ScyllaDB repo: http://downloads.scylladb.com/unstable/scylla/master/rpm/centos/2021-03-11T21:19:41Z/scylla.repo
- Instance type: n1-highmem-8
- Number of ScyllaDB nodes: 3

Restore Monitor Stack command: $ hydra investigate show-monitor 6353887e-c117-45b8-8c02-1870e1071ada
Show all stored logs command: $ hydra investigate show-logs 6353887e-c117-45b8-8c02-1870e1071ada

```

**Comment by kbr-** [comment] 2021-03-18 10:21
I checked the logs and indeed it's exactly the same problem.
I think upgrade tests can simply ignore the pattern `read from system_distributed.cdc_generation_timestamps.*Can't find a column family with UUID`.
The log message will appear on some upgrades (depending on the race), but as I explained previously - it's harmless.

**Comment by bhalevy** [comment] 2022-03-31 08:13
Seen again in https://jenkins.scylladb.com/job/scylla-4.5/job/dtest-release/124/testReport/upgrade_test/UpgradeTestFrom40ToLast/test_cluster_upgrade/

https://jenkins.scylladb.com/job/scylla-4.5/job/dtest-release/124/artifact/logs-all.release.2/1648638659623_upgrade_test.UpgradeTestFrom40ToLast.test_cluster_upgrade/node1.log
```
INFO  2022-03-30 11:08:01,248 [shard 0] storage_service - Node 127.0.49.1 state jump to normal
ERROR 2022-03-30 11:08:01,250 [shard 0] storage_proxy - Exception when communicating with 127.0.49.3, to read from system_distributed.cdc_generation_timestamps: std::runtime_error (Can't find a column family with UUID fdf455c4-cfec-3e00-9719-d7a45436c89d)
INFO  2022-03-30 11:08:01,251 [shard 0] cdc - CDC description table successfully updated with generation 2022/03/30 11:07:17.
```

https://jenkins.scylladb.com/job/scylla-4.5/job/dtest-release/124/artifact/logs-all.release.2/1648638659623_upgrade_test.UpgradeTestFrom40ToLast.test_cluster_upgrade/node3.log
```
INFO  2022-03-30 11:08:01,250 [shard 0] migration_manager - Requesting schema pull from 127.0.49.1:0
INFO  2022-03-30 11:08:01,250 [shard 0] migration_manager - Pulling schema from 127.0.49.1:0

INFO  2022-03-30 11:08:01,262 [shard 0] schema_tables - Creating system_distributed.cdc_generation_timestamps id=fdf455c4-cfec-3e00-9719-d7a45436c89d version=5777e043-a81a-3324-8803-b497c056849f
```

**Comment by DoronArazii** [comment] 2023-05-03 07:32
@bhalevy we haven't saw it for 1 year, can we close as not planned?

**Closed** 2023-05-03 09:47 UTC
Labels: dtest
