### ISSUE TITLE
topology/test_replace.py::test_replace_different_ip_using_host_id fails sporadically

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#14975] opened 2023-08-07 09:55 UTC
Seen in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2917/ - https://github.com/scylladb/scylladb/pull/14970

**Comment by kbr-scylla** [comment] 2023-08-08 08:49
Probably duplicate of https://github.com/scylladb/scylladb/issues/14885

**Closed** 2023-08-11 07:16 UTC
Labels: P1, CI-Stability
