### ISSUE TITLE
A select query (via new scylla driver) fails with: Tombstones processed by unpaged query exceeds limit of 10000

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#12268] opened 2022-12-11 17:14 UTC
## Installation details

Kernel Version: 5.15.0-1026-aws
Scylla version (or git commit hash): `5.2.0~dev-20221201.c5121cf27365` with build-id `d25d298da80af2e947d1728190d8f4f26978e44a`

Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-41fa60db-9 (34.227.61.71 | 10.12.8.50) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-8 (54.172.72.90 | 10.12.10.152) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-7 (54.227.114.85 | 10.12.9.165) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-6 (54.164.104.79 | 10.12.9.16) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-5 (3.85.198.112 | 10.12.11.109) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-4 (18.234.64.137 | 10.12.10.139) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-3 (18.208.221.98 | 10.12.8.86) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-2 (52.23.224.189 | 10.12.11.102) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-11 (50.17.90.79 | 10.12.10.164) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-10 (54.83.110.139 | 10.12.9.186) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-1 (34.229.220.114 | 10.12.10.44) (shards: 7)

OS / Image: `ami-058aaa3c56c451303` (aws: us-east-1)

Test: `longevity-twcs-48h-test`
Test id: `41fa60db-6de8-4a2f-8a9a-eba66cb9439a`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6f29e454d005db4f1d9a2d8f619d36dbe3919ee0/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

**>>>>>>>**
Running scylla-bench that generated large partitions.
Using scylla driver that supports the new implementation of auto turning large select-queries to receive a paged result.
The query got the following error result:
```
yarongilor@yarongilor:~/Downloads/logs/sct-runner-41fa60db$ grep '< t:2022-12-02 13:1' sct.log | egrep "SELECT \* FROM scylla_bench.test LIMIT 1|Tombstones processed by unpaged query exceeds limit"
< t:2022-12-02 13:10:59,973 f:common.py       l:1550 c:utils                p:DEBUG > Executing CQL 'SELECT * FROM scylla_bench.test LIMIT 1' ...
< t:2022-12-02 13:11:02,137 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-12-02T13:11:02+00:00 longevity-twcs-48h-master-db-node-41fa60db-5      !ERR | scylla[702]:  [shard 0] storage_proxy - Exception when communicating with 10.12.11.109, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit))
< t:2022-12-02 13:11:02,138 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > 2022-12-02T13:11:02+00:00 longevity-twcs-48h-master-db-node-41fa60db-5      !ERR | scylla[702]:  [shard 0] storage_proxy - Exception when communicating with 10.12.11.109, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit)) < t:2022-12-02 13:11:02,138 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > Processing of 132387 line of /home/ubuntu/sct-results/20221202-040311-884350/hosts/longevity-twcs-48h-master-db-node-41fa60db-5/messages.log failed, line content:
< t:2022-12-02 13:11:02,639 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-12-02T13:11:02+00:00 longevity-twcs-48h-master-db-node-41fa60db-5      !ERR | scylla[702]:  [shard 3] storage_proxy - Exception when communicating with 10.12.11.109, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit))
< t:2022-12-02 13:11:02,640 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > 2022-12-02T13:11:02+00:00 longevity-twcs-48h-master-db-node-41fa60db-5      !ERR | scylla[702]:  [shard 3] storage_proxy - Exception when communicating with 10.12.11.109, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit)) < t:2022-12-02 13:11:02,640 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > Processing of 132388 line of /home/ubuntu/sct-results/20221202-040311-884350/hosts/longevity-twcs-48h-master-db-node-41fa60db-5/messages.log failed, line content:
< t:2022-12-02 13:11:02,640 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-12-02T13:11:02+00:00 longevity-twcs-48h-master-db-node-41fa60db-5      !ERR | scylla[702]:  [shard 2] storage_proxy - Exception when communicating with 10.12.11.109, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit))
< t:2022-12-02 13:11:02,641 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > 2022-12-02T13:11:02+00:00 longevity-twcs-48h-master-db-node-41fa60db-5      !ERR | scylla[702]:  [shard 2] storage_proxy - Exception when communicating with 10.12.11.109, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit)) < t:2022-12-02 13:11:02,641 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > Processing of 132389 line of /home/ubuntu/sct-results/20221202-040311-884350/hosts/longevity-twcs-48h-master-db-node-41fa60db-5/messages.log failed, line content:
< t:2022-12-02 13:11:03,342 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-12-02T13:11:03+00:00 longevity-twcs-48h-master-db-node-41fa60db-5      !ERR | scylla[702]:  [shard 6] storage_proxy - Exception when communicating with 10.12.11.109, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit))
< t:2022-12-02 13:11:03,343 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > 2022-12-02T13:11:03+00:00 longevity-twcs-48h-master-db-node-41fa60db-5      !ERR | scylla[702]:  [shard 6] storage_proxy - Exception when communicating with 10.12.11.109, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit)) < t:2022-12-02 13:11:03,343 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > Processing of 132390 line of /home/ubuntu/sct-results/20221202-040311-884350/hosts/longevity-twcs-48h-master-db-node-41fa60db-5/messages.log failed, line content:
< t:2022-12-02 13:11:03,343 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-12-02T13:11:03+00:00 longevity-twcs-48h-master-db-node-41fa60db-5      !ERR | scylla[702]:  [shard 2] storage_proxy - Exception when communicating with 10.12.11.109, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit))
< t:2022-12-02 13:11:03,344 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > 2022-12-02T13:11:03+00:00 longevity-twcs-48h-master-db-node-41fa60db-5      !ERR | scylla[702]:  [shard 2] storage_proxy - Exception when communicating with 10.12.11.109, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit)) < t:2022-12-02 13:11:03,344 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > Processing of 132391 line of /home/ubuntu/sct-results/20221202-040311-884350/hosts/longevity-twcs-48h-master-db-node-41fa60db-5/messages.log failed, line content:
< t:2022-12-02 13:11:03,645 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-12-02T13:11:03+00:00 longevity-twcs-48h-master-db-node-41fa60db-5      !ERR | scylla[702]:  [shard 3] storage_proxy - Exception when communicating with 10.12.11.109, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit))
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 41fa60db-6de8-4a2f-8a9a-eba66cb9439a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=41fa60db-6de8-4a2f-8a9a-eba66cb9439a)
- Show all stored logs command: `$ hydra investigate show-logs 41fa60db-6de8-4a2f-8a9a-eba66cb9439a`

## Logs:
- **db-cluster-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/db-cluster-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/db-cluster-41fa60db.tar.gz)
- **monitor-set-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/monitor-set-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/monitor-set-41fa60db.tar.gz)
- **loader-set-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/loader-set-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/loader-set-41fa60db.tar.gz)
- **sct-runner-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/sct-runner-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/sct-runner-41fa60db.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/67/)

**Comment by avikivity** [comment] 2022-12-11 17:30
Due to 7730419f5c6e55555b019e50530b54911309b104. But why do you have an unpaged query?

**Comment by roydahan** [comment] 2022-12-12 11:57
> Due to [7730419](https://github.com/scylladb/scylladb/commit/7730419f5c6e55555b019e50530b54911309b104). But why do you have an unpaged query?

The test is trying to run: "SELECT * FROM scylla_bench.test LIMIT 1", I guess it didn't expect to need paging for one partition query.

**Comment by yarongilor** [comment] 2023-01-05 13:28
According to @avikivity , it is a scylla issue.
(more reproductions are found in: https://github.com/scylladb/scylla-cluster-tests/pull/5615 )

**Comment by avikivity** [comment] 2023-01-05 14:14
> According to @avikivity , it is a scylla issue. (more reproductions are found in: [scylladb/scylla-cluster-tests#5615](https://github.com/scylladb/scylla-cluster-tests/pull/5615) )

Can you confirm that the test used paging?

**Comment by yarongilor** [comment] 2023-01-09 12:04
> > According to @avikivity , it is a scylla issue. (more reproductions are found in: [scylladb/scylla-cluster-tests#5615](https://github.com/scylladb/scylla-cluster-tests/pull/5615) )
> 
> Can you confirm that the test used paging?

SCT doesn't print query additinal params to log, but the executed code is:
```
stmt = SimpleStatement(f"SELECT * FROM {table_name}", fetch_size=10)
```

**Comment by yarongilor** [comment] 2023-01-10 07:36
The issue is not reproduced with an SCT fix:
https://github.com/scylladb/scylla-cluster-tests/pull/5662#issuecomment-1376842592

**Comment by roydahan** [comment] 2023-01-17 16:21
@yarongilor reminding you on this, to retest if the SCT fix workarounded and this is a real issue.

**Comment by fgelcer** [comment] 2023-02-15 08:27
@roydahan @avikivity , with the workaround in SCT, issue is not reproduced... what are next steps? are still required reproduction? should we assign it to someone to fix the issue?

**Comment by yarongilor** [comment] 2023-02-15 14:46
Testing a page-size of 1000 in: https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-twcs-48h-test-cql-timeout/

trying to reproduce the error as happened during toppartitions nemesis:
```
< t:2023-01-01 20:23:12,357 f:common.py       l:1550 c:utils                p:DEBUG > Executing CQL 'SELECT * FROM scylla_bench.test LIMIT 1' ...
< t:2023-01-01 20:23:12,375 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 8h4m25.6s   30098   30098      0 7.6ms  5.4ms  4ms    2.9ms  2.5ms  1.3ms  1.6ms  
< t:2023-01-01 20:23:12,630 f:cluster.py      l:3035 c:sdcm.cluster         p:DEBUG > Retrying read after timeout. Attempt #0
< t:2023-01-01 20:23:12,727 f:cluster.py      l:3035 c:sdcm.cluster         p:DEBUG > Retrying read after timeout. Attempt #1
< t:2023-01-01 20:23:12,821 f:cluster.py      l:3035 c:sdcm.cluster         p:DEBUG > Retrying read after timeout. Attempt #2
< t:2023-01-01 20:23:12,862 f:cluster.py      l:3035 c:sdcm.cluster         p:DEBUG > Retrying read after timeout. Attempt #3
< t:2023-01-01 20:23:12,945 f:cluster.py      l:3035 c:sdcm.cluster         p:DEBUG > Retrying read after timeout. Attempt #4
< t:2023-01-01 20:23:12,986 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2023-01-01T20:23:12+00:00 longevity-twcs-48h-decrease-db-node-61c69a22-1      !ERR | scylla[5352]:  [shard 5] storage_proxy - Exception when communicating with 10.12.0.24, to read from scylla_bench.test: std::runtime_error (Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit))
```

**Comment by roydahan** [comment] 2023-02-16 16:59
Kill it.
Let's discuss this on Monday in the office, don't close the task yet.

**Comment by yarongilor** [comment] 2023-02-16 17:16
Not reproduced after one day. Have to discuss it.

**Closed** 2023-02-20 15:40 UTC
Labels: bug, Pending-QA-Reproduction, P3
