### ISSUE TITLE
topology_raft_disabled  debug  [ FAIL ] topology_raft_disabled.test_raft_upgrade.1

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#13751] opened 2023-05-02 13:39 UTC
Failed while checking changes in sstables::test_env and few test/boost/sstable* test cases (#13569)
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1014/consoleText

**Comment by xemul** [comment] 2023-05-03 12:05
Similar sympthoms in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1026/consoleText run, debug-mode topology.test_change_ip.1

**Comment by kostja** [comment] 2023-05-03 20:23
@xemul could you please provide a bit more info, just having a link to consoleText will make everyone looking at this bug manually scan a long log file to find the relevant symptoms. I haven't found anything useful in the log.

**Comment by kostja** [comment] 2023-05-03 20:25
```
[2023-05-03T11:29:00.991Z]     async def test_change_two(manager, random_tables):
[2023-05-03T11:29:00.991Z]         """Stop two nodes, change their IPs and start, check the cluster is
[2023-05-03T11:29:00.991Z]         funcitonal"""
[2023-05-03T11:29:00.991Z]         servers = await manager.running_servers()
[2023-05-03T11:29:00.991Z]         table = await random_tables.add_table(ncolumns=5)
[2023-05-03T11:29:00.991Z]         s_1 = servers[1].server_id
[2023-05-03T11:29:00.991Z]         s_2 = servers[2].server_id
[2023-05-03T11:29:00.991Z]         logger.info("Gracefully stopping servers %s and %s to change ips", s_1, s_2)
[2023-05-03T11:29:00.991Z]         await manager.server_stop_gracefully(s_1)
[2023-05-03T11:29:00.991Z]         await manager.server_stop_gracefully(s_2)
[2023-05-03T11:29:00.991Z]         await manager.server_change_ip(s_1)
[2023-05-03T11:29:00.991Z]         await manager.server_change_ip(s_2)
[2023-05-03T11:29:00.991Z]         await manager.server_start(s_1)
[2023-05-03T11:29:00.991Z]         await manager.server_start(s_2)
[2023-05-03T11:29:00.991Z]         await table.add_column()
[2023-05-03T11:29:00.991Z] >       await random_tables.verify_schema()
[2023-05-03T11:29:00.991Z] 
[2023-05-03T11:29:00.991Z] test/topology/test_change_ip.py:31: 
[2023-05-03T11:29:00.991Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2023-05-03T11:29:00.991Z] 
[2023-05-03T11:29:00.991Z] self = <test.pylib.random_tables.RandomTables object at 0x7f8db94daf50>
[2023-05-03T11:29:00.991Z] table = <test.pylib.random_tables.RandomTable object at 0x7f8db94f7390>
[2023-05-03T11:29:00.991Z] 
[2023-05-03T11:29:00.991Z]     async def verify_schema(self, table: Union[RandomTable, str] = None) -> None:
[2023-05-03T11:29:00.991Z]         """Verify schema of all active managed random tables"""
[2023-05-03T11:29:00.991Z]         if isinstance(table, RandomTable):
[2023-05-03T11:29:00.991Z]             tables = {table.name}
[2023-05-03T11:29:00.991Z]             cql_stmt1 = f"SELECT table_name FROM system_schema.tables " \
[2023-05-03T11:29:00.991Z]                         f"WHERE keyspace_name = '{self.keyspace}' AND table_name = '{table.name}'"
[2023-05-03T11:29:00.991Z]         elif isinstance(table, str):
[2023-05-03T11:29:00.991Z]             if table.startswith(f"{self.keyspace}."):
[2023-05-03T11:29:00.991Z]                 table = table[len(self.keyspace) + 1:]
[2023-05-03T11:29:00.991Z]             tables = {table}
[2023-05-03T11:29:00.991Z]             cql_stmt1 = f"SELECT table_name FROM system_schema.tables " \
[2023-05-03T11:29:00.991Z]                         f"WHERE keyspace_name = '{self.keyspace}' AND table_name = '{table}'"
[2023-05-03T11:29:00.992Z]         else:
[2023-05-03T11:29:00.992Z]             tables = set(t.name for t in self.tables)
[2023-05-03T11:29:00.992Z]             cql_stmt1 = f"SELECT table_name FROM system_schema.tables " \
[2023-05-03T11:29:00.992Z]                         f"WHERE keyspace_name = '{self.keyspace}'"
[2023-05-03T11:29:00.992Z]     
[2023-05-03T11:29:00.992Z]         logger.debug(cql_stmt1)
[2023-05-03T11:29:00.992Z]         assert self.manager.cql is not None
[2023-05-03T11:29:00.992Z]         res1 = {row.table_name for row in await self.manager.cql.run_async(cql_stmt1)}
[2023-05-03T11:29:00.992Z]         assert not tables - res1, f"Tables {tables - res1} not present"
[2023-05-03T11:29:00.992Z]     
[2023-05-03T11:29:00.992Z]         for table_name in tables:
[2023-05-03T11:29:00.992Z]             table = next(t for t in self.tables if t.name == table_name)
[2023-05-03T11:29:00.992Z]             cols = {c.name: c for c in table.columns}
[2023-05-03T11:29:00.992Z]             c_pos = {c.name: i for i, c in enumerate(table.columns)}
[2023-05-03T11:29:00.992Z]             cql_stmt2 = f"SELECT column_name, position, kind, type FROM system_schema.columns " \
[2023-05-03T11:29:00.992Z]                         f"WHERE keyspace_name = '{self.keyspace}' AND table_name = '{table_name}'"
[2023-05-03T11:29:00.992Z]             logger.debug(cql_stmt2)
[2023-05-03T11:29:00.992Z]             assert self.manager.cql is not None
[2023-05-03T11:29:00.992Z]             res2 = {row.column_name: row for row in await self.manager.cql.run_async(cql_stmt2)}
[2023-05-03T11:29:00.992Z] >           assert res2.keys() == cols.keys(), f"Column names for {table_name} do not match " \
[2023-05-03T11:29:00.992Z]                                                f"expected ({', '.join(cols.keys())}) " \
[2023-05-03T11:29:00.992Z]                                                f"got ({', '.join(res2.keys())})"
[2023-05-03T11:29:00.992Z] E           AssertionError: Column names for t_01 do not match expected (pk, c_01, v_01, v_02, v_03, v_04) got (c_01, pk, v_01, v_02, v_03)
[2023-05-03T11:29:00.992Z] 
[2023-05-03T11:29:00.992Z] test/pylib/random_tables.py:334: AssertionError
```

**Comment by kostja** [comment] 2023-05-03 20:28
Looks similar to https://github.com/scylladb/scylladb/issues/12937

**Comment by xemul** [comment] 2023-05-04 08:38
> @xemul could you please provide a bit more info, just having a link to consoleText will make everyone looking at this bug manually scan a long log file to find the relevant symptoms. I haven't found anything useful in the log.

@kostja , I have found no useful (to me) info in logs either :shrug: , otherwise I'd put anything that drew my attention here. Sorry

**Comment by kbr-scylla** [comment] 2023-05-05 12:38
> Failed while checking changes in sstables::test_env and few test/boost/sstable* test cases (https://github.com/scylladb/scylladb/pull/13569)
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1014/consoleText

> Similar sympthoms in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1026/consoleText run, debug-mode topology.test_change_ip.1

What are the similar symptoms? The two failures are completely different.

The first failure is a hang during shutdown. In https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1014/artifact/testlog/x86_64/debug/topology_raft_disabled.test_raft_upgrade.1.log we can find:
```
=================================== FAILURES ===================================
_______________________ test_recover_stuck_raft_upgrade ________________________

...

        logging.info(f"Restarting {others}")
>       await asyncio.gather(*(restart(manager, srv) for srv in others))

...

E           TimeoutError
```

The server used in this test were:
```
------------------------------ live log teardown -------------------------------
15:36:37.462 DEBUG> after_test for test_recover_stuck_raft_upgrade (success: False)
15:36:37.463 DEBUG> RESTClient fetching GET http+unix://api/cluster/after-test/False
15:36:37.465 INFO> Cluster after test test_recover_stuck_raft_upgrade: ScyllaCluster(name: b7ad68e8-e8e4-11ed-96f8-1641bdd4ccd5, running: ScyllaServer(214, 127.43.11.37, 1847f23a-9af6-4b78-b78d-5cd1e44bf7e4), ScyllaServer(218, 127.43.11.20, 12e395a0-8909-4507-9f0b-cd152f802511), ScyllaServer(222, 127.43.11.14, 5ca9d623-28a2-47ab-9173-c685a3ff144c), stopped: )
```
213, 218, 222.

In scylla-218.log https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1014/artifact/testlog/x86_64/debug/scylla-218.log we see that it hanged during shutdown, which caused the test to hang.
```
INFO  2023-05-02 15:31:42,144 [shard 0] hints_manager - Asked to stop
INFO  2023-05-02 15:31:42,144 [shard 0] hints_manager - Asked to stop
INFO  2023-05-02 15:31:42,145 [shard 1] hints_manager - Asked to stop
INFO  2023-05-02 15:31:42,145 [shard 1] hints_manager - Asked to stop
INFO  2023-05-02 15:31:42,146 [shard 1] hints_manager - Stopped
INFO  2023-05-02 15:31:42,146 [shard 1] hints_manager - Stopped
INFO  2023-05-02 15:31:42,148 [shard 0] hints_manager - Stopped
Rate-limit: suppressed 1 backtrace on shard 1
Rate-limit: suppressed 2 backtraces on shard 0
------ Ending test debug/topology_raft_disabled.test_raft_upgrade.1::test_recover_stuck_raft_upgrade ------
```

That's a duplicate of #8079.

I don't think we have issue for the second failure, it looks like something new.

**Comment by kbr-scylla** [comment] 2023-05-05 14:21
Opened https://github.com/scylladb/scylladb/issues/13788 for the second failure.
Closing this as duplicate of https://github.com/scylladb/scylladb/issues/8079 (since the original post describes a failure with the same root cause).

**Closed by kbr-scylla** 2023-05-05 14:21 UTC
Labels: CI-Stability
