### ISSUE TITLE
dtest: flakiness of next_gating runs with --experimental-features=consistent-topology-changes on test teardown

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylladb#16579] opened 2023-12-28 12:10 UTC
ScyllaDB version: 5.5.0~dev-0.20231226.3968fc11bf9c.x86_64 (but found on earlier builds too)
dtest parameters: `-m "not skip and next_gating" --experimental-features=consistent-topology-changes`

Some of tests failing randomly on teardown because of error messages found on a node's shut down.

There are 2 common types of errors appeared:

```
failed on teardown with "AssertionError: Unexpected errors found: [('node1', ['ERROR 2023-12-27 11:42:36,914 [shard 0:strm] raft - [213cd60e-70eb-4ec5-a2c9-4d80e65ac9b2] applier fiber stopped because of the error: std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1230): std::runtime_error (forward_service is shutting down)'])]"
```

Example: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/evgeniy/job/gating-dtest-release-with-consisten-topology-changes/117/

```
...
INFO  2023-12-27 11:42:36,720 [shard 0:main] init - Signal received; shutting down
INFO  2023-12-27 11:42:36,720 [shard 0:main] init - Shutting down view builder ops
INFO  2023-12-27 11:42:36,720 [shard 0:main] view - Draining view builder
INFO  2023-12-27 11:42:36,720 [shard 0:main] compaction_manager - Stopped
INFO  2023-12-27 11:42:36,720 [shard 1:main] compaction_manager - Asked to stop
INFO  2023-12-27 11:42:36,720 [shard 1:main] view_update_generator - Terminating background fiber
INFO  2023-12-27 11:42:36,720 [shard 1:main] view - Draining view builder
INFO  2023-12-27 11:42:36,720 [shard 1:main] compaction_manager - Stopped
INFO  2023-12-27 11:42:36,720 [shard 1:strm] view_update_generator - leaving 0 unstaged sstables unprocessed
INFO  2023-12-27 11:42:36,720 [shard 0:main] init - Shutting down view builder ops was successful
INFO  2023-12-27 11:42:36,720 [shard 0:main] init - Shutting down local storage
INFO  2023-12-27 11:42:36,720 [shard 0:main] storage_service - Stop transport: starts
INFO  2023-12-27 11:42:36,720 [shard 0:main] migration_manager - stopping migration service
INFO  2023-12-27 11:42:36,720 [shard 1:main] migration_manager - stopping migration service
INFO  2023-12-27 11:42:36,720 [shard 0:main] storage_service - Shutting down native transport server
WARN  2023-12-27 11:42:36,720 [shard 0:main] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
INFO  2023-12-27 11:42:36,721 [shard 0:main] cql_server_controller - CQL server stopped
INFO  2023-12-27 11:42:36,721 [shard 0:main] storage_service - Shutting down native transport server was successful
INFO  2023-12-27 11:42:36,721 [shard 0:main] storage_service - Shutting down rpc server
INFO  2023-12-27 11:42:36,721 [shard 0:main] storage_service - Shutting down rpc server was successful
INFO  2023-12-27 11:42:36,721 [shard 0:main] storage_service - Shutting down alternator server
INFO  2023-12-27 11:42:36,721 [shard 0:main] storage_service - Shutting down alternator server was successful
INFO  2023-12-27 11:42:36,721 [shard 0:main] storage_service - Shutting down redis server
INFO  2023-12-27 11:42:36,721 [shard 0:main] storage_service - Shutting down redis server was successful
INFO  2023-12-27 11:42:36,721 [shard 0:main] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2023-12-27 11:42:36,721 [shard 0:main] gossip - My status = NORMAL
INFO  2023-12-27 11:42:36,721 [shard 0:main] gossip - Announcing shutdown
WARN  2023-12-27 11:42:36,721 [shard 0:main] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
INFO  2023-12-27 11:42:36,721 [shard 0:main] gossip - Sending a GossipShutdown to 127.0.71.2 with generation 1703677341
ERROR 2023-12-27 11:42:36,914 [shard 0:strm] raft - [213cd60e-70eb-4ec5-a2c9-4d80e65ac9b2] applier fiber stopped because of the error: std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1230): std::runtime_error (forward_service is shutting down)
INFO  2023-12-27 11:42:36,914 [shard 0:strm] storage_service - raft_state_monitor_fiber aborted with raft::stopped_error (Raft instance is stopped)
INFO  2023-12-27 11:42:37,105 [shard 0: gms] rpc - client 127.0.71.2:55136 msg_id 2:  exception "gate closed" in no_wait handler ignored
INFO  2023-12-27 11:42:37,105 [shard 0: gms] rpc - client 127.0.71.2:55136 msg_id 3:  exception "gate closed" in no_wait handler ignored
WARN  2023-12-27 11:42:37,325 [shard 0: gms] gossip - === Gossip round FAIL: seastar::gate_closed_exception (gate closed)
INFO  2023-12-27 11:42:37,325 [shard 0: gms] gossip - Gossip loop is not scheduled because it is disabled
INFO  2023-12-27 11:42:38,105 [shard 0: gms] rpc - client 127.0.71.2:55136 msg_id 4:  exception "gate closed" in no_wait handler ignored
INFO  2023-12-27 11:42:38,106 [shard 0: gms] rpc - client 127.0.71.2:55136 msg_id 5:  exception "gate closed" in no_wait handler ignored
...
```

and

```
failed on teardown with "AssertionError: Unexpected errors found: [('node2', ['ERROR 2023-12-28 10:52:59,947 [shard 0:main] storage_proxy - Exception when communicating with 127.0.99.1, to read from system_distributed.service_levels: replica::stale_topology_exception (stale topology exception, caller version 7, callee fence version 8)', 'ERROR 2023-12-28 10:52:59,948 [shard 0:main] storage_proxy - Exception when communicating with 127.0.99.1, to read from system_distributed.service_levels: replica::stale_topology_exception (stale topology exception, caller version 7, callee fence version 8)'])]"
```

Example: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/evgeniy/job/gating-dtest-release-with-consisten-topology-changes/140/

```
...
INFO  2023-12-28 10:52:59,922 [shard 0: gms] repair - decommission_with_repair: finished with keyspaces={ks, system_traces, system_distributed_everywhere, system_distributed, system_auth}, leaving_node=127.0.99.2
INFO  2023-12-28 10:52:59,922 [shard 0: gms] storage_service - raft topology: streaming completed
ERROR 2023-12-28 10:52:59,947 [shard 0:main] storage_proxy - Exception when communicating with 127.0.99.1, to read from system_distributed.service_levels: replica::stale_topology_exception (stale topology exception, caller version 7, callee fence version 8)
ERROR 2023-12-28 10:52:59,948 [shard 0:main] storage_proxy - Exception when communicating with 127.0.99.1, to read from system_distributed.service_levels: replica::stale_topology_exception (stale topology exception, caller version 7, callee fence version 8)
INFO  2023-12-28 10:53:00,028 [shard 0:strm] storage_service - Stop transport: starts
INFO  2023-12-28 10:53:00,028 [shard 0:strm] migration_manager - stopping migration service
INFO  2023-12-28 10:53:00,028 [shard 1:strm] migration_manager - stopping migration service
INFO  2023-12-28 10:53:00,029 [shard 0:strm] storage_service - Shutting down native transport server
INFO  2023-12-28 10:53:00,029 [shard 0:strm] cql_server_controller - CQL server stopped
INFO  2023-12-28 10:53:00,030 [shard 0:strm] storage_service - Shutting down native transport server was successful
INFO  2023-12-28 10:53:00,030 [shard 0:strm] storage_service - Shutting down rpc server
INFO  2023-12-28 10:53:00,030 [shard 0:strm] storage_service - Shutting down rpc server was successful
INFO  2023-12-28 10:53:00,030 [shard 0:strm] storage_service - Shutting down alternator server
INFO  2023-12-28 10:53:00,030 [shard 0:strm] storage_service - Shutting down alternator server was successful
INFO  2023-12-28 10:53:00,030 [shard 0:strm] storage_service - Shutting down redis server
INFO  2023-12-28 10:53:00,030 [shard 0:strm] storage_service - Shutting down redis server was successful
INFO  2023-12-28 10:53:00,030 [shard 0:strm] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2023-12-28 10:53:00,030 [shard 0:strm] gossip - My status = LEFT
WARN  2023-12-28 10:53:00,030 [shard 0:strm] gossip - No local state or state is in silent shutdown, not announcing shutdown
INFO  2023-12-28 10:53:00,030 [shard 0:strm] gossip - Disable and wait for gossip loop started
INFO  2023-12-28 10:53:00,158 [shard 0:strm] gossip - failure_detector_loop: Finished main loop
INFO  2023-12-28 10:53:00,159 [shard 0:strm] gossip - Gossip is now stopped
...
```

I don’t see any other problems in tests that fail this way, but there may be some issues hidden behind them.

**Comment by patjed41** [comment] 2024-01-02 08:55
> and
> 
> ```
> failed on teardown with "AssertionError: Unexpected errors found: [('node2', ['ERROR 2023-12-28 10:52:59,947 [shard 0:main] storage_proxy - Exception when communicating with 127.0.99.1, to read from system_distributed.service_levels: replica::stale_topology_exception (stale topology exception, caller version 7, callee fence version 8)', 'ERROR 2023-12-28 10:52:59,948 [shard 0:main] storage_proxy - Exception when communicating with 127.0.99.1, to read from system_distributed.service_levels: replica::stale_topology_exception (stale topology exception, caller version 7, callee fence version 8)'])]"
> ```
This error looks like it was caused by #15804. It happened during decommission.

**Comment by kostja** [comment] 2024-01-03 09:13
Looks like a duplicate of #16570 which happens with test.py

**Comment by kostja** [comment] 2024-01-03 09:16
Resolution: suppress the error in dtest, keep the issue open, return to it in scope of looking at all the other dtest failures in topology mode.

**Comment by gleb-cloudius** [comment] 2024-01-03 09:34
It is not cleat to me how group0 state machine depends on a `forward_service` at all. The `forward_service` is invoked somewhere it should not be.

**Closed** 2024-01-25 18:25 UTC
Labels: dtest, topology changes, raft
