### ISSUE TITLE
node could stay in gossip forever if node start gossiping but topology coordinator didn't get request to bootstrap

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#20082] opened 2024-08-08 13:18 UTC
## Packages

Scylla version: `6.0.2-20240703.c9cd171f426e` with build-id `f42d84b1312f866e5b14a8a8ecc8ffff0e4d5d19`

Kernel Version: `5.15.0-1064-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

New node4 is going to be bootstrapped. Bootstrap process started, but scylla was stopped. Scylla startup failed with error:
```
2024-08-07T12:14:35.035+00:00 longevity-100gb-4h-fix-boot-db-node-cc80acbf-4      !ERR | scylla[6910]:  [shard 0:main] init - Startup failed: seastar::rpc::remote_verb_error (group [51d4c601-54b4-11ef-9165-7b183
941291e] raft operation [read_barrier] timed out)
```
According to topology coordinator log (node1): raft_topology request from node4 didn'not reach the coordinator node, but node4 was registered gossip:
```
2024-08-07T12:13:35.992+00:00 longevity-100gb-4h-fix-boot-db-node-cc80acbf-1     !INFO | scylla[6818]:  [shard 0: gms] gossip - InetAddress e07f2d3e-8075-47b6-859e-d66e776200ab/10.4.11.215 is now UP, status = UNKNOWN
```
and later when scylla was stopped on node4, node4 was marked as down in gossip;
```
2024-08-07T12:14:56.242+00:00 longevity-100gb-4h-fix-boot-db-node-cc80acbf-1     !INFO | scylla[6818]:  [shard 0:strm] gossip - InetAddress e07f2d3e-8075-47b6-859e-d66e776200ab/10.4.11.215 is now DOWN, status = UNKNOWN
```

Group0 and token ring was checked on each node, and shows that node4 (with ip and host_id) are not  added to group0 and token ring.

All scylla data was removed from node4 and scylla started again. But now Start up failed with error:
```
init - Startup failed: std::runtime_error (A node with address 10.4.11.215 already exists, cancelling join. Use replace_address if you want to replace this node.)
```

this happend as @kbr- described:
> in raft topology mode we don't have automatic gossip "fat client timeout", because topology coordinator is responsible for removing nodes which fail to join (also from gossip) but if node starts gossiping, and topology coordinator never gets the request to join, it will not remove it, so it will stay in gossip forever 

## Impact

Node could stay in gossip forever and block adding new node with same ip

## How frequently does it reproduce?

periodically when raft request for bootstrap is not reached the topology coordinator

## Installation details

Cluster size: 3 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-fix-boot-db-node-cc80acbf-9 (3.249.93.16 | 10.4.8.168) (shards: -1)
- longevity-100gb-4h-fix-boot-db-node-cc80acbf-8 (54.154.110.163 | 10.4.10.89) (shards: -1)
- longevity-100gb-4h-fix-boot-db-node-cc80acbf-7 (52.211.166.108 | 10.4.10.251) (shards: -1)
- longevity-100gb-4h-fix-boot-db-node-cc80acbf-6 (34.245.169.168 | 10.4.9.250) (shards: -1)
- longevity-100gb-4h-fix-boot-db-node-cc80acbf-5 (52.214.11.223 | 10.4.11.249) (shards: -1)
- longevity-100gb-4h-fix-boot-db-node-cc80acbf-4 (52.213.174.142 | 10.4.11.215) (shards: -1)
- longevity-100gb-4h-fix-boot-db-node-cc80acbf-3 (18.203.252.68 | 10.4.10.48) (shards: 7)
- longevity-100gb-4h-fix-boot-db-node-cc80acbf-2 (18.201.247.1 | 10.4.9.30) (shards: 7)
- longevity-100gb-4h-fix-boot-db-node-cc80acbf-1 (34.240.19.254 | 10.4.11.194) (shards: 7)

OS / Image: `ami-032aa4bb84ce1e02f` (aws: undefined_region)

Test: `longevity-100gb-4h-bootstrap-test`
Test id: `cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2`
Test name: `scylla-staging/abykov/longevity-100gb-4h-bootstrap-test`

Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1d703024823c16c509fb51bf57b2be9d11ee9a84/test-cases/longevity/longevity-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2)
- Show all stored logs command: `$ hydra investigate show-logs cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2`

## Logs:
- **db-cluster-cc80acbf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/db-cluster-cc80acbf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/db-cluster-cc80acbf.tar.gz)
- **sct-runner-events-cc80acbf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/sct-runner-events-cc80acbf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/sct-runner-events-cc80acbf.tar.gz)
- **sct-cc80acbf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/sct-cc80acbf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/sct-cc80acbf.log.tar.gz)
- **loader-set-cc80acbf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/loader-set-cc80acbf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/loader-set-cc80acbf.tar.gz)
- **monitor-set-cc80acbf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/monitor-set-cc80acbf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/monitor-set-cc80acbf.tar.gz)
- **parallel-timelines-report-cc80acbf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/parallel-timelines-report-cc80acbf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2/20240807_141506/parallel-timelines-report-cc80acbf.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/longevity-100gb-4h-bootstrap-test/57/)
[Argus](https://argus.scylladb.com/test/d635e138-c81f-40a6-913b-db20231447d4/runs?additionalRuns[]=cc80acbf-fdc6-4b04-9eae-76c09bb3aaf2)
</details>

**Comment by kbr-scylla** [comment] 2024-08-08 13:22
cc @gleb-cloudius please verify my understanding

IIUC in raft topology mode we disabled automatic removal of nodes from gossip, and rely on coordinator to move node to LEFT state which causes it to get purged from gossip, but this assumes that the node managed to get into topology in the first place

but here we deal with a case where it starts gossiping but then doesn't get into topology

**Comment by gleb-cloudius** [comment] 2024-08-08 14:13
> cc @gleb-cloudius please verify my understanding
> 
> IIUC in raft topology mode we disabled automatic removal of nodes from gossip, and rely on coordinator to move node to LEFT state which causes it to get purged from gossip, but this assumes that the node managed to get into topology in the first place
> 
> but here we deal with a case where it starts gossiping but then doesn't get into topology

I do not remember how exactly gossiper automatically remove nodes (what the condition is), but yes, with raft topology we do not manage states in gossiper at all. Raft code forces some states (IIRC normal and left) into the gossiper, but only because some functionality (like shutdown notifications) depends on int.

**Comment by kbr-scylla** [comment] 2024-08-08 14:23
Each node gossips its IP address and host ID, and that's the thing that stays as a "leftover" after such failed join

> I do not remember how exactly gossiper automatically remove nodes (what the condition is),

If the node was not NORMAL and was silent for 60s (IIRC) we remove it (in gossip mode)

**Comment by gleb-cloudius** [comment] 2024-08-08 14:42
IIRC the node that is not joined will not have any state with raft topo. But the check that you are talking about it indeed disabled in raft mode:

```
                if (!_topo_sm) {
                    do_status_check().get();
                }

```

Otherwise nodes waiting in a queue will be dropped by the gossiper.

**Comment by kbr-scylla** [comment] 2024-08-08 14:49
in any case it looks like we need to add a mechanism to purge nodes from gossiper that didn't enter raft topology state and will not enter it (or we decide that they will not enter it with some heuristic)

**Comment by paszkow** [comment] 2024-08-13 08:56
We started constantly hitting this issue for the serverless_v2 project when using Scylla Enterprise 2024.2. The moment a new node is about to be added to the cluster it reports the error:
```
2024-08-13T07:36:43.044+00:00 serverless-v2-50-percent-storage-ca-db-node-27a4be36-4      !ERR | scylla[6924]:  [shard 0:main] init - Startup failed: seastar::rpc::remote_verb_error (group [76565e20-5942-11ef-881f-0a9b8dfd56d0] raft operation [add_entry] timed out)
```
and the cluster gets terminated. The problem does not occur when executing the experiment with Scylla 6.2.0.

[Argus](https://argus.scylladb.com/workspace?state=WyI2MmJhYjA4Zi1mYWVmLTQxMDktODY4MC02Y2VhZGFhYjM1YmUiLCJkM2M4ZWI3Yy03MzI0LTRlODQtYTI0YS04NWE3MzQxNDJhOGMiLCJkMTcyNGVjNS0xNjBkLTRmMWQtODRhOC01ZDJmM2FiYWUzMDgiXQ)

CC @dani-tweig @mykaul

**Comment by mykaul** [comment] 2024-08-13 09:04
> We started constantly hitting this issue for the serverless_v2 project when using Scylla Enterprise 2024.2. The moment a new node is about to be added to the cluster it reports the error:
> 
> ```
> 2024-08-13T07:36:43.044+00:00 serverless-v2-50-percent-storage-ca-db-node-27a4be36-4      !ERR | scylla[6924]:  [shard 0:main] init - Startup failed: seastar::rpc::remote_verb_error (group [76565e20-5942-11ef-881f-0a9b8dfd56d0] raft operation [add_entry] timed out)
> ```
> 
> and the cluster gets terminated. The problem does not occur when executing the experiment with Scylla 6.2.0.
> 
> [Argus](https://argus.scylladb.com/workspace?state=WyI2MmJhYjA4Zi1mYWVmLTQxMDktODY4MC02Y2VhZGFhYjM1YmUiLCJkM2M4ZWI3Yy03MzI0LTRlODQtYTI0YS04NWE3MzQxNDJhOGMiLCJkMTcyNGVjNS0xNjBkLTRmMWQtODRhOC01ZDJmM2FiYWUzMDgiXQ)
> 
> CC @dani-tweig @mykaul

Enterprise issues should be reported on Enterprise repo. Then tag @kbr-scylla / @gleb-cloudius to take a look.

**Comment by kbr-scylla** [comment] 2024-08-13 14:49
@paszkow is your issue the one from the title, or is it actually the fact that bootstrap fails?

**Comment by paszkow** [comment] 2024-08-14 07:39
> @paszkow is your issue the one from the title, or is it actually the fact that bootstrap fails?

No. Bootstrap failed with the exact same error message. But Gleb already explained that. Switching to 2024.3.0-dev solved our problem.

**Comment by mykaul** [comment] 2024-11-03 12:57
@paszkow - so can we close this issue?

**Comment by paszkow** [comment] 2024-11-04 14:35
> [@paszkow](https://github.com/paszkow) - so can we close this issue?

Time ago I thought I was hitting this issue as I had the same error messages but that is it. My problem was resolved by using version that includes the commit "replica: remove rwlock for protecting iteration over storage group map". Does this commit solve this particular problem? I do not know.

**Comment by mykaul** [comment] 2024-11-04 15:26
> > [@paszkow](https://github.com/paszkow) - so can we close this issue?
> 
> Time ago I thought I was hitting this issue as I had the same error messages but that is it. My problem was resolved by using version that includes the commit "replica: remove rwlock for protecting iteration over storage group map". Does this commit solve this particular problem? I do not know.

Let's close. If it reproduces, we'll re-open / open a new issue.

**Comment by kbr-scylla** [comment] 2024-11-04 15:38
@mykaul this issue is real, it was detected in testing, and @AbhinavKumarJha is currently working on it. @paszkow's bootstrap failure is not related.

**Closed** 2024-12-06 14:16 UTC
Labels: bug, status/regression, area/gossip, tests/longevity, area/topology changes, area/raft, P1, technical debt, backport/6.1, backport/6.2
