### ISSUE TITLE
[dtest] update_cluster_layout_tests.TestUpdateClusterLayout.test_increment_decrement_counters_in_threads_nodes_restarted is flakey

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15877] opened 2023-10-30 12:12 UTC
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/5626/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/FullDtest___full_split006___test_increment_decrement_counters_in_threads_nodes_restarted/
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6752/

```
cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.15.2:9042 datacenter1>: ConnectionException('Pool for 127.0.15.2:9042 is shutdown'), <Host: 127.0.15.3:9042 datacenter1>: ConnectionException('Host has been marked down or removed'), <Host: 127.0.15.1:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})
```

```
self = <compaction_additional_test.TestCompactionAdditional object at 0x7fccc2a0c350>
strategy1 = {'class': 'LeveledCompactionStrategy', 'min_threshold': 2, 'sstable_size_in_mb': 1}
strategy2 = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': 1, 'compaction_window_unit': 'MINUTES', 'min_threshold': 2}

    @pytest.mark.single_node
    @pytest.mark.parametrize("strategy1,strategy2", get_strategies_upgrade_options(), ids=generate_ids)
    def test_refresh_and_restart_after_compaction_strategy_change(self, strategy1, strategy2):
        """
        This test tries to load backup sstable by refresh and restart after changing the compaction strategy.
        refreshing loads sstable from upload directory, and sstable in staging or main sstable directory will
        be loaded in cf populating during restart.
    
        Reshaping will only be triggered conditionally if current compaction strategy isn't satisfied.
    
        LeveledCompactionStrategy:
        - level 0 has more sstables than min_threshold (strict mode) or max_compaction_threshold (relax_mode) (covered in the test)
        - have 10% overlapping sstables on same level
        - sstable level out of MAX level (9)
    
        SizeTieredCompactionStrategy:
        - have more than min_threshold similar-sized SSTables
    
        TimeWindowCompactionStrategy:
        - have sstables that span more than 1 window
        - a given window has more than min_threshold SSTables.
        - Time-Window Compaction Strategy compacts SSTables within each time window
          using Size-tiered Compaction Strategy (STCS)
    
        DateTieredCompactionStrategy:
        - doesn't support reshaping
        """
        cluster = self.cluster
        cluster.populate(1)
        node1 = cluster.nodelist()[0]
        node1.start(wait_for_binary_proto=True)
    
        node1 = self.cluster.nodelist()[0]
        session = self.patient_cql_connection(node1)
        session.execute("DROP KEYSPACE IF EXISTS keyspace1")
    
        logger.debug(f"Create test table with {strategy1}")
        node1.stress(['write', 'n=0', 'no-warmup', '-schema', 'replication(factor=1)', '-rate', 'threads=1'])
    
        session.execute(f"ALTER TABLE keyspace1.standard1 WITH compaction={strategy1}")
    
        logger.debug("Insert test data by cassandra-stress and compact")
        # Use multiple workloads to generate multiple sstables, then it's easy to reach the threshold for reshaping
    
        fill_data_by_cs(node1, n_range=[500, 550, 600, 650])
        # Compact initially, make sure there are some compacted sstables before disable autocompaction
        node1.compact()
    
        # Here we disable autocompaction for leaving all sstables in level 0, then
        # it's easy to trigger reshape with small dataset during restart (strict mode).
        # Actually it's not always necessary.
        #
        # Refreshing from upload will use strict mode reshape, restart population
        # from staging or main sstable directory will use relax mode reshape.
        # Only in relaxed mode, all sstables will be mutated to level to 0, reshaping
        # will be trigger very easily.
    
        logger.debug('disable autocompaction to leave all sstables in level 0')
        node1.nodetool('disableautocompaction keyspace1 standard1')
    
        logger.debug("Insert test data by cassandra-stress without compacting, leave it for next strategy")
    
        if (strategy2['class'] == 'TimeWindowCompactionStrategy'):
            # Prepare a sstable spans two 1 window, (window unit is 60 seconds)
            fill_data_by_cs(node1, n_range=[], duration_range=[70],
                            other_opt=['-rate', 'threads=1', '-col', 'size=FIXED(1024)'])
        elif (strategy2['class'] == 'LeveledCompactionStrategy'):
            # Need more than 10% overlapping sstables on same level
            fill_data_by_cs(node1, n_range=[500, 550, 600, 650, 1000], start=5000)
        elif (strategy2['class'] == 'SizeTieredCompactionStrategy'):
            fill_data_by_cs(node1, n_range=[500, 550, 600, 650, 2000, 5000] * 2, start=10000)
        else:
            fill_data_by_cs(node1, n_range=[500, 550, 600, 650], start=5000)
    
        cf_dir = get_node_cf_dir(node1, 'keyspace1', 'standard1', latest=True)
        logger.debug(cf_dir)
    
        # For troubleshot
        backup_dir = os.path.join(cf_dir, f'./backup.{time.time()}/')
        copy_files_to(cf_dir, backup_dir, files_only=True, create_to_dir=True)
    
        # Prepare for refresh
        copy_files_to(cf_dir, os.path.join(cf_dir, './upload/'), files_only=True)
    
        logger.info(f"Change table compaction strategy to {strategy2}")
        session.execute(f"ALTER TABLE keyspace1.standard1 WITH compaction={strategy2}")
    
        def assert_reshape(srcdir, log_mark, verify_reshape=True, followed_by=None):
            """
            Check Reshaping or Resharding really happened
            """
            try:
                exprs = [r"(Reshape|Reshard) keyspace1.standard1"]
                if followed_by:
                    exprs.append(followed_by)
                res = node1.watch_log_for(exprs, timeout=30, from_mark=log_mark)
                logger.debug(res)
            except TimeoutError:
                res = None
                msg = f"Reshape or Reshard didn't occur after loading sstables from {srcdir} directory"
                if (strategy2['class'] not in ['DateTieredCompactionStrategy', 'SizeTieredCompactionStrategy'] and verify_reshape):
                    if strategy2['class'] != strategy1['class']:
                        assert res is not None, f"Reshape didn't occurred in loading sstables from {srcdir} directory"
                    else:
                        logger.debug(msg + ", as expected.")
    
        def verify_data(srcdir):
            """
            Verify the loaded data by cs read
            """
            logger.info(f'Verify data is loaded from {srcdir} directory')
            node1.stress(['read', 'n=100', 'no-warmup', '-rate', 'threads=10', '-col', 'size=FIXED(1024)'])
    
        logger.debug("Clean test data & sstables before subtest by TRUNCATE")
>       session.execute("TRUNCATE keyspace1.standard1")

compaction_additional_test.py:699: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cassandra/cluster.py:2708: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'127.0.88.1:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.88.1:9042

cassandra/cluster.py:5048: OperationTimedOut
```

**Comment by denesb** [comment] 2023-10-31 07:33
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4434/
This time the error is:
```
cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.21.1:9042 datacenter1>: ConnectionShutdown('Connection to 127.0.21.1:9042 is closed'), <Host: 127.0.21.3:9042 datacenter1>: ConnectionException('Pool is shutdown'), <Host: 127.0.21.2:9042 datacenter1>: ConnectionException('Pool is shutdown')})
```

**Comment by mykaul** [comment] 2023-10-31 07:42
Perhaps same root cause as https://github.com/scylladb/scylladb/issues/15610 ? TRUNCATE timing out?

**Comment by denesb** [comment] 2023-10-31 08:28
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4435/

**Comment by avikivity** [comment] 2023-10-31 11:26
wait what? this test started being flaky yesterday and now it's repeating?

**Comment by yaronkaikov** [comment] 2023-11-08 09:24
Seen again https://jenkins.scylladb.com/job/scylla-master/job/next/6796/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Build___x86___Sanity___Sanity_Tests_x86___test_increment_decrement_counters_in_threads_nodes_restarted/

**Comment by yaronkaikov** [comment] 2023-11-28 06:38
Seen again in 2024.1 - https://jenkins.scylladb.com/job/enterprise-2024.1/job/next/25/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_increment_decrement_counters_in_threads_nodes_restarted/

**Comment by yaronkaikov** [comment] 2023-12-14 05:51
Seen again in 2024.1 - https://jenkins.scylladb.com/job/enterprise-2024.1/job/next/42/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests_RAFT___test_increment_decrement_counters_in_threads_nodes_restarted/

**Comment by mykaul** [comment] 2023-12-14 07:23
@bhalevy - unsure, but assigning it to you (based on https://github.com/scylladb/scylla-dtest/commit/7be75e998bffa237ce3dff2d48e4d8c47323f55f )

**Comment by bhalevy** [comment] 2023-12-14 13:09
Ref https://github.com/scylladb/scylladb/pull/16247

**Comment by benipeled** [comment] 2024-01-03 12:58
Similar failure  https://jenkins.scylladb.com/job/scylla-master/job/next/7024/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Build___x86___dtest___test_increment_decrement_counters_in_threads_nodes_restarted/

**Comment by bhalevy** [comment] 2024-05-23 14:01
Hit in CI: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/1702/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/FullDtest___full_split004___test_increment_decrement_counters_in_threads_nodes_restarted/

**Comment by bhalevy** [comment] 2024-07-29 11:26
Cc @roydahan

**Comment by roydahan** [comment] 2024-07-30 14:48
I checked the history of this test and went over the last 100 runs - https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/2804/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/FullDtest___full_split004___test_increment_decrement_counters_in_threads_nodes_restarted/history/?start=0.

out of 100 runs, it failed 5 times and all of them were real failures of real issues, none of them with the 2 different failures mentioned in the original description.

Closing this one.

@yaronkaikov if we have an automation that opens an issue without looking at the failure reason, we should disable it.

**Closed by roydahan** 2024-07-30 14:48 UTC
Labels: triage/master, P1, symptom/ci stability

**Comment by yaronkaikov** [comment] 2024-07-30 14:56
> I checked the history of this test and went over the last 100 runs - https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/2804/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/FullDtest___full_split004___test_increment_decrement_counters_in_threads_nodes_restarted/history/?start=0.
> 
> out of 100 runs, it failed 5 times and all of them were real failures of real issues, none of them with the 2 different failures mentioned in the original description.
> 
> Closing this one.
> 
> @yaronkaikov if we have an automation that opens an issue without looking at the failure reason, we should disable it.

We don't have it for dtest
