### ISSUE TITLE
RFC: Put gossiper messages on a diet

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#11054] opened 2022-07-15 15:45 UTC
As seen in [several](https://github.com/scylladb/scylla-enterprise/issues/2312) [issues](https://github.com/scylladb/scylla-enterprise/issues/2313) already, gossiper manages lots of data. The [fattest](https://github.com/scylladb/scylla-enterprise/issues/2312#issuecomment-1184616573) exchanged state is cache hitrates. Tossing them through gossiper affects the gossiper itself in a bad way. It might be better to have dedicated RPC verb to pull/push the hitrates around the cluster in a way that excludes any [growing queues](https://github.com/scylladb/scylla/issues/10967). Also we could save some CPU ticks by not (de)formatting the values into(from) string.

Cc @asias , @avikivity

**Comment by xemul** [comment] 2022-07-18 13:44
Cc @denesb

**Comment by asias** [comment] 2022-07-19 02:19
Some thoughts below.

1) What is the minimum acceptable frequency of the cache hit rate? 

The current  0.5s sounds too high. 

```
            if (_diff < 0.01) {
                return lowres_clock::duration(2000ms);
            } else {
                return lowres_clock::duration(500ms);
            }
```

2) We should skip to send update if the change is tiny. 

3) Do we really need per table cache?

We can reduce the message size significantly if we use per keyspace or even per node hit rate. 

If we can improve either or all of 1) 2) 3). 

Gossip is good enough to exchange cache hit rate.

Btw, We used to have similar problem for view backlog. We fixed how we generate view backlog update frequency. 

4) Periodic 1 to N - 1 rpc update for cache hit rate update is not very cheap either. 

IMO, it is better to generate less info in a smarter way than introducing a more powerful transfer channel.

**Comment by bhalevy** [comment] 2022-07-19 14:45
Cc @gleb-cloudius

**Comment by bhalevy** [comment] 2022-07-19 14:45
Cc @nyh

**Comment by bhalevy** [comment] 2022-07-19 20:10
Ref https://github.com/scylladb/scylla/issues/5971

**Comment by asias** [comment] 2022-07-20 02:56
I've sent a PR here: https://github.com/scylladb/scylla/pull/11079

It fixes the "sender" side. It  will avoid most of the unnecessary updates. 

I think we do not need a new rpc as the "transport".

Because a peer node can know the cache hitrate through read_data, read_mutation_data and read_digest RPC verbs which have cache_temperature in the response. So there is no need to update CACHE_HITRATES through gossip in high frequency or the new "transport".

**Comment by denesb** [comment] 2022-07-20 04:09
> can we piggyback the cache hit/miss status on the replica read / digest reply and use it to update the coordinator's view of the replica's cache?

We already do, see e.g. https://github.com/scylladb/scylla/blob/5a30f9b7894abbeb196d179294f9320cc53534ba/service/storage_proxy.cc#L3780-L3781

**Comment by gleb-cloudius** [comment] 2022-07-20 06:45
> > can we piggyback the cache hit/miss status on the replica read / digest reply and use it to update the coordinator's view of the replica's cache?
> 
> We already do, see e.g.
> 
> https://github.com/scylladb/scylla/blob/5a30f9b7894abbeb196d179294f9320cc53534ba/service/storage_proxy.cc#L3780-L3781

The gossiper part is only needed for a rebooted node to know hit rates before it generates any traffic. Afterwords only piggybacked data is used.

**Comment by bhalevy** [comment] 2022-07-20 07:23
> The gossiper part is only needed for a rebooted node to know hit rates before it generates any traffic. Afterwords only piggybacked data is used.

That makes #11079 unnecessary.
A newly started node can ask about cache hitrates just once then.

**Comment by asias** [comment] 2022-07-20 07:28
> > The gossiper part is only needed for a rebooted node to know hit rates before it generates any traffic. Afterwords only piggybacked data is used.
> 
> That makes #11079 unnecessary. A newly started node can ask about cache hitrates just once then.

We still need #11079 which is utilizing the exactly this fact so we do not need high frequency gossip updates for cache hitrates.

**Comment by gleb-cloudius** [comment] 2022-07-20 07:29
> > The gossiper part is only needed for a rebooted node to know hit rates before it generates any traffic. Afterwords only piggybacked data is used.
> 
> That makes #11079 unnecessary. A newly started node can ask about cache hitrates just once then.

Well, it is possible to add a special RPC to ask for hit rates from all live node before moving to a NORMAL state. It is a pity that we cannot piggyback on a subsystem that exists specifically to disseminate  information through the cluster.

**Comment by asias** [comment] 2022-07-20 07:34
> > > The gossiper part is only needed for a rebooted node to know hit rates before it generates any traffic. Afterwords only piggybacked data is used.
> > 
> > 
> > That makes #11079 unnecessary. A newly started node can ask about cache hitrates just once then.
> 
> Well, it is possible to add a special RPC to ask for hit rates from all live node before moving to a NORMAL state. It is a pity that we cannot piggyback on a subsystem that exists specifically to disseminate information through the cluster.

When a restarting node becomes NORMAL, it already knows CACHE_HITRATES of existing nodes though gossip. 
The existing nodes also know that this node has restarted so existing nodes should be able to know this is a cache cold node. 

I do not see why we need a new rpc for this.

**Comment by asias** [comment] 2022-07-20 07:43
> > I do not see why we need a new rpc for this.
> 
> Me too, but this bug is about complains that hit rates in gossiper messages make gossiper live hard.

This is because hit rate update is too frequent (unnecessarily, and the only one of all gossip states) which generates a lot of updates. And on the receiver side, some of the shard is too busy to apply the states and the queue grows.

**Comment by asias** [comment] 2022-07-20 08:27
> > > > > The gossiper part is only needed for a rebooted node to know hit rates before it generates any traffic. Afterwords only piggybacked data is used.
> > > > 
> > > > 
> > > > That makes #11079 unnecessary. A newly started node can ask about cache hitrates just once then.
> > > 
> > > 
> > > Well, it is possible to add a special RPC to ask for hit rates from all live node before moving to a NORMAL state. It is a pity that we cannot piggyback on a subsystem that exists specifically to disseminate information through the cluster.
> > 
> > 
> > When a restarting node becomes NORMAL, it already knows CACHE_HITRATES of existing nodes through gossip. The existing nodes also know that this node has restarted so existing nodes should be able to know this is a cache cold node.
> > I do not see why we need a new rpc for this.
> 
> So why do we need the periodic updates?

The periodic updates helps the restarting node to know hit rate before sending any of the verbs.

**Comment by xemul** [comment] 2022-07-20 09:28
> ...  so existing nodes should be able to know this is a cache cold node.

So do we really need to know the per-table cache hit rate? Maybe node "uptime" would work as well?

**Comment by gleb-cloudius** [comment] 2022-07-20 09:33
> > ...  so existing nodes should be able to know this is a cache cold node.
> 
> So do we really need to know the per-table cache hit rate? Maybe node "uptime" would work as well?

How would it work? Assume that the greater uptime the more populated the cache is? How much more?

**Comment by xemul** [comment] 2022-07-20 09:56
>  Assume that the greater uptime the more populated the cache is?

Of course, there's no other decision that's apparently better than this one

> How much more?

Dunno. When hitrate-based decision was added the justification was very simple (87094849faa07f4ad93b43a4fc55a53009d27fbc):
>    This patch makes storage proxy to choose replicas to read from base on
>    their cache hit rates. Replicas with higher cache hit rates will see
>    more requests while replicas with lower hit rates will see less...

So we can try to apply the same here -- replicas with higher uptime will see more requests, while replicas with lower uptime will see less. The node granularity uptime is indeed mush more coarse than cf granularity hitrate. We only can rely on the same way as we do on hitrate if

``` 
(uptime(node-A) <=> uptime(node-B)) == (hitrate(cf, node-A) <=> hitrate(cf, node-B)) 
                                foreach { cf, node-A, node-B }
```

Thus my question.

**Comment by nyh** [comment] 2022-07-21 10:48
>     1. What is the minimum acceptable frequency of the cache hit rate?
> The current 0.5s sounds too high.

I agree. **Usually** these cache hit rates will depend on the content of the node's cache, so we expect it to vary smoothly and slowly, so we don't expect any interesting change in half a second. When a hit rate change can happen in half a second is when the **workload** changes its nature - e.g., the client suddenly switches from requesting mostly cached items, to requesting mostly uncached items. In this case,
1. I don't think users really expect us to detect this workload change in half a second. Note that even if we do not detect it, it only means higher latencies - it's not a disaster.
2. If we see that the the hit range drastically (your patch has "10%") we can send the new information quickly. But if it didn't change drastically, it won't help to send the new slightly higher value.

>     3. Do we really need per table cache?

Good question. This is https://github.com/scylladb/scylla/issues/5200
This is very important in deployments with a lot of tables.

> IMO, it is better to generate less info in a smarter way than introducing a more powerful transfer channel.

I agree.

**Comment by nyh** [comment] 2022-07-21 12:09
> > Dunno. When hitrate-based decision was added the justification was very simple ([8709484](https://github.com/scylladb/scylla/commit/87094849faa07f4ad93b43a4fc55a53009d27fbc)):
> > > This patch makes storage proxy to choose replicas to read from base on
> > > their cache hit rates. Replicas with higher cache hit rates will see
> > > more requests while replicas with lower hit rates will see less...
> 
> The justification in the commit message my have been simple, but @nyh write the entire paper on how to calculate probabilities.

If you're curious, check out https://docs.google.com/document/d/1M-gRlPDPvqB8mWKBV1ix3AX29JCOX11zgVrtO2bf--E/edit

**Comment by slivne** [comment] 2022-08-11 08:35
@xemul / @avikivity / @asias whats the status of this - we know that the table cache hit rate has been causing issues - did we solve it. If we have lets close this issues - if not please open an issue and detail the fix(s) that need to be done.

**Comment by DoronArazii** [comment] 2022-09-08 12:21
@xemul / @asias ^^

**Comment by DoronArazii** [comment] 2022-10-09 08:59
@avikivity please decide what to do with it

**Comment by asias** [comment] 2022-10-17 02:57
My patch

```
commit 39db15d2cba81870bcc8269ff8afebb2fe2d2038
Author: Asias He <asias@scylladb.com>
Date:   Wed Jul 20 08:52:18 2022 +0800

    misc_services: Fix cache hitrate update
    
    This patch avoids unncessary CACHE_HITRATES updates through gossip.
    
    After this patch:
    
    Publish CACHE_HITRATES in case:
    
    - We haven't published it at all
    - The diff is bigger than 1% and we haven't published in the last 5 seconds
    - The diff is really big 10%
    
    Note: A peer node can know the cache hitrate through read_data
    read_mutation_data and read_digest RPC verbs which have cache_temperature in
    the response. So there is no need to update CACHE_HITRATES through gossip in
    high frequency.
    
    We do the recalculation faster if the diff is bigger than 0.01. It is useful to
    do the calculation even if we do not publish the CACHE_HITRATES though gossip,
    since the recalculation will call the table->set_global_cache_hit_rate to set
    the hitrate.
    
    Fixes #5971
    
    Closes #11079
```

Fixed the root cause. 

I think we do not need to do anything for 5.1.

**Comment by xemul** [comment] 2022-10-17 10:51
This issue's point is purely about the size of hitrates payload. This fix did nothing with that size.

**Comment by avikivity** [comment] 2022-10-19 15:36
@DoronArazii this isn't a regression and shouldn't block 5.1.

**Comment by DoronArazii** [comment] 2022-10-19 15:44
Pushing to 5.2

**Comment by asias** [comment] 2022-12-28 07:48
The opening message suggested to introduce a dedicated rpc message to send catch hit ratio. Per the discussion above, we do not really need the new rpc to do it. I am closing this issue.

**Closed by asias** 2022-12-28 07:48 UTC
Labels: bug, high, gossip
