### ISSUE TITLE
Alternator: oversized allocation

### ISSUE THREAD

**Issue by dimaqq** [scylladb/scylladb#10017] opened 2022-02-02 08:01 UTC
`seastar_memory - oversized allocation: 1277952 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues.`

Relevant logs in full:

[logs.txt](https://github.com/scylladb/scylla/files/7984565/logs.txt)

**Comment by nyh** [comment] 2022-02-03 07:59
Thanks. I believe that if this oversized allocation came from `do_query()` as the log suggests, then it was already fixed as a side-effect of @elcallio as part of commit 23e93a26b327ced350d4fb687dcf4c75bd290f70  (pull request https://github.com/scylladb/scylla/pull/9713). 

That commit reached master 21 days ago, so it wouldn't be in the fixed in the 5-week-old version you were running, so if you get the nightly version working, please report if it's gone and we can close this issue.

If it's indeed the same issue, note that the commit was not set to be backported to any existing release, so please let me know if you think that it should.

**Comment by nyh** [comment] 2022-10-18 16:12
The afforementioned commit is now in all releases 5.0 and newer. If we can't reproduce this issue let's close this issue (and reopen if it is re-discovered).

**Closed** 2022-10-19 01:00 UTC
Labels: Alternator
