### ISSUE TITLE
node unable to join cluster due to service::raft_operation_timeout_error

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#20111] opened 2024-08-11 23:49 UTC
the test was in the middle of creating a 4-node cluster. scylla-1344 is the second one. but it failed to join the cluster. 

log from scylla-1344 which was the new joiner of the cluster:

```
INFO  2024-08-10 02:03:05,628 [shard 0: gms] schema_tables - Schema version changed to 7c0ea5a8-56a3-11ef-ab1c-3e8eb66c8533
INFO  2024-08-10 02:03:06,276 [shard 0: gms] schema_tables - Reloading system_distributed.cdc_streams_descriptions_v2 id=0bf73fd7-65b2-36b0-85e5-658131d5df36 version=bb9f554e-9f62-31d7-87f3-a1c9ce2cd0a8
INFO  2024-08-10 02:03:06,284 [shard 0: gms] schema_tables - Reloading system_traces.sessions_time_idx id=0ebf001c-c1d1-3693-9a63-c3d96ac53318 version=7b2ba2d0-56a3-11ef-b452-dfaaf38055d0
INFO  2024-08-10 02:03:06,295 [shard 0: gms] schema_tables - Reloading system_distributed_everywhere.cdc_generation_descriptions_v2 id=234d2227-dd63-3d37-ac5f-c013e2ea9e6e version=c3e41a82-eb42-3b57-9390-fe1892dd7c46
INFO  2024-08-10 02:03:06,304 [shard 0: gms] schema_tables - Reloading system_distributed.view_build_status id=5582b59f-8e4e-35e1-b913-3acada51eb04 version=1e8042e9-b1b2-3dcd-b390-76169d706660
INFO  2024-08-10 02:03:06,326 [shard 0: gms] schema_tables - Reloading system_traces.events id=8826e8e9-e16a-3728-8753-3bc1fc713c25 version=7b2cdb50-56a3-11ef-b452-dfaaf38055d0
INFO  2024-08-10 02:03:06,336 [shard 0: gms] schema_tables - Reloading system_distributed.dicts id=a39ced6f-ff01-32a7-b336-e2ef1ad72b1a version=a35f65fd-f71a-3040-b98a-508741a93549
INFO  2024-08-10 02:03:06,345 [shard 0: gms] schema_tables - Reloading system_distributed.service_levels id=b8c556bd-212d-37ad-9484-690c73a5994b version=798768b0-56a3-11ef-b452-dfaaf38055d0
INFO  2024-08-10 02:03:06,360 [shard 0: gms] schema_tables - Reloading system_traces.node_slow_log id=bfcc4e62-5b63-3aa1-a1c3-6f5e47f3325c version=7b2e61f1-56a3-11ef-b452-dfaaf38055d0
INFO  2024-08-10 02:03:06,374 [shard 0: gms] schema_tables - Reloading system_traces.sessions id=c5e99f16-8677-3914-b17e-960613512345 version=7b29ce10-56a3-11ef-b452-dfaaf38055d0
INFO  2024-08-10 02:03:06,384 [shard 0: gms] schema_tables - Reloading system_replicated_keys.encrypted_keys id=f705e6dd-8cc5-378b-a7e9-aec38e033747 version=475f5ffd-2a0c-3c23-a1a4-2f5522ec100b
INFO  2024-08-10 02:03:06,394 [shard 0: gms] schema_tables - Reloading system_traces.node_slow_log_time_idx id=f9706768-aa1e-3d87-9e5c-51a3927c2870 version=7b305dc0-56a3-11ef-b452-dfaaf38055d0
INFO  2024-08-10 02:03:06,402 [shard 0: gms] schema_tables - Reloading system_distributed.cdc_generation_timestamps id=fdf455c4-cfec-3e00-9719-d7a45436c89d version=580abf0b-aadf-326c-ae0e-6470ef4bbb37
WARN  2024-08-10 02:03:06,413 [shard 0: gms] raft_group_registry - group [789c6c70-56a3-11ef-b452-dfaaf38055d0] raft operation [read_barrier] timed out; timeout requested at [service/storage_service.cc(6618:104) `auto service::storage_service::join_node_response_handler(join_node_response_params)::(anonymous class)::operator()(const join_node_response_params::accepted &) const`], original error raft::request_aborted (Request is aborted by a caller)
WARN  2024-08-10 02:03:06,414 [shard 0: gms] raft_topology - error while handling the join response from the topology coordinator. The node will not join the cluster. Error: service::raft_operation_timeout_error (group [789c6c70-56a3-11ef-b452-dfaaf38055d0] raft operation [read_barrier] timed out)
INFO  2024-08-10 02:03:06,418 [shard 0:main] init - Shutting down group 0 usage in local storage
INFO  2024-08-10 02:03:06,418 [shard 0:main] init - Shutting down group 0 usage in local storage was successful
INFO  2024-08-10 02:03:06,418 [shard 0:main] init - Shutting down storage service uninit address map
INFO  2024-08-10 02:03:06,418 [shard 0:main] init - Shutting down storage service uninit address map was successful
```

we have two failure reports in a row from this test in a single CI test:

- [test_cannot_add_new_node.2.zip](https://github.com/user-attachments/files/16576461/test_cannot_add_new_node.2.zip)
- [test_cannot_add_new_node.3.zip](https://github.com/user-attachments/files/16576469/test_cannot_add_new_node.3.zip)

this issue might be a dup of #19031 which happened when decommissioning a node.

**Comment by kbr-scylla** [comment] 2024-08-14 12:40
This issue was opened 3 days ago, but it was not given a triage label or assigned to anyone.

**Comment by kbr-scylla** [comment] 2024-08-28 09:50
The timed out read barrier was:
```cpp
                // Do a read barrier to read/initialize the topology state
                co_await _group0->group0_server_with_timeouts().read_barrier(&_group0_as, raft_timeout{});
```

inside `storage_service::join_node_response_handler`

There was no unexpected hang here. The node was in the middle of applying the group 0 snapshot (and making progress) when the read barrier timed out, which we can see from the `schema_tables` logs:
```
INFO  2024-08-10 02:03:06,316 [shard 0: gms] schema_tables - Reloading system_replicated_keys.encrypted_keys id=f705e6dd-8cc5-378b-a7e9-aec38e033747 version=475f5ffd-2a0c-3c23-a1a4-2f5522ec100b
INFO  2024-08-10 02:03:06,324 [shard 0: gms] schema_tables - Reloading system_traces.node_slow_log_time_idx id=f9706768-aa1e-3d87-9e5c-51a3927c2870 version=7ab90ae0-56a3-11ef-9abb-f051e3719014
INFO  2024-08-10 02:03:06,331 [shard 0: gms] schema_tables - Reloading system_distributed.cdc_generation_timestamps id=fdf455c4-cfec-3e00-9719-d7a45436c89d version=580abf0b-aadf-326c-ae0e-6470ef4bbb37
WARN  2024-08-10 02:03:06,345 [shard 0: gms] raft_group_registry - group [787adab0-56a3-11ef-9abb-f051e3719014] raft operation [read_barrier] timed out; timeout requested at [service/storage_service.cc(6618:104) `auto service::storage_service::join_node_response_handler(join_node_response_params)::(anonymous class)::operator()(const join_node_response_params::accepted &) const`], original error raft::request_aborted (Request is aborted by a caller)
```

the problem is that this took too long, and the barrier timed out, because the test is significantly reducing the group 0 operation timeouts (which are by default 1 minute; the test is reducing them to 5 seconds in debug mode):
```python3
@pytest.fixture
def raft_op_timeout(mode):
    return 5000 if mode == 'debug' else 1000
...
    config = {
        'direct_failure_detector_ping_timeout_in_ms': 300,
        'error_injections_at_startup': [
            {
                'name': 'group0-raft-op-timeout-in-ms',
                'value': raft_op_timeout
            },
```

unfortunately in this case we took longer than 5s to apply group 0 state (which is needed to finish read barrier).

So it's not a Scylla bug but a flaky test.

We need to increase `raft_op_timeout` in debug mode. 10s should suffice.

**Closed** 2024-09-06 15:25 UTC
Labels: area/topology changes, symptom/ci stability, backport/6.0, backport/6.1
