### ISSUE TITLE
Timeout point send in `forward_request` verb comes from `seastar::lowres_clock`

### ISSUE THREAD

**Issue by havaker** [scylladb/scylladb#12458] opened 2023-01-05 16:16 UTC
In the [parallelized aggregation layer](https://github.com/scylladb/scylladb/pull/9209) `query::forward_request` (that is sent to remote nodes) carries information about timeouts using `lowres_clock::time_point` (that came from local `seastar::lowres_clock`). The `lowres_clock::time_point` is later used on remote nodes to designate a timeout date. This is wrong and may lead to delayed or premature timeout.

**Comment by eliransin** [comment] 2023-01-05 17:05
@havaker please fix - it seams that you know exactly what the problem is :slightly_smiling_face:

**Comment by havaker** [comment] 2023-01-10 11:12
Note: this bug exists in 5.1 version (since the merge of https://github.com/scylladb/scylladb/pull/9209).

**Comment by DoronArazii** [comment] 2023-01-10 11:27
> Note: this bug exists in 5.1 version (since the merge of #9209).

Thanks for the notice. we can backport this when the fix is ready.

We are using the milestones to reflect *when* this issue will have a fix (or at least when we intend to get to it) - therefore 5.2 is the correct milestone.

**Comment by avikivity** [comment] 2023-01-18 12:09
Fixed by bbbe12af4339e64733a03c44f55f0b47b9a309a5

**Closed by avikivity** 2023-01-18 12:09 UTC
Labels: bug, P2

**Comment by avikivity** [comment] 2023-01-18 12:10
Backported to 5.1. 5.0 did not have the broken functionality.
