### ISSUE TITLE
[dtest] Spurious TestHintedHandoff.test_hintedhandoff_decom failure

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#19974] opened 2024-08-01 09:08 UTC
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10676/testReport/junit/hintedhandoff_additional_test/TestHintedHandoff/Tests___dtest_with_topology_changes___test_hintedhandoff_decom/

```
self = <hintedhandoff_additional_test.TestHintedHandoff object at 0x7f1559eb5640>

    @pytest.mark.no_boot_speedups
    def test_hintedhandoff_decom(self):
        """
        Test hints draining when node is decommissioned (nodetool decommission).
    
        Create a 3 nodes cluster with hinted handoff enabled
        Create a KS wit RF=1
        Create a table
        Shut down node3
        Insert 100 rows with CL=ANY. The data for node3 will only be written to hints.
        Bring the node3 up
        Decommission node3
        Wait till hints are flushed
        Read all 100 rows with CL=ONE - it should succeed.
        """
        self.__start_cluster_with_hints(num=3)
    
        [node1, node2, node3] = self.cluster.nodelist()
    
        node3_ip = node3.address()
        node3_hid = node3.hostid()
    
        session = self.patient_cql_connection(node1)
    
        logger.info("Preparing a KS and a CF...")
        create_ks(session, "ks", 1)
        create_c1c2_table(session)
    
        logger.info("Stopping node3...")
        node3.stop(wait_other_notice=True)
    
        logger.info("Populating the data...")
        insert_c1c2(session, n=100, consistency=ConsistencyLevel.ANY)
    
        logger.info("Staring node3...")
        node3.start(wait_for_binary_proto=True, jvm_args=self.__jvm_args())
    
        logger.info("Decommissioning node3...")
        node3.decommission()
    
        logger.info(f"Waiting {self.__hint_flush_threshold}s for hints to be sent...")
        time.sleep(self.__hint_flush_threshold)
    
        logger.info("Check that the directories have been cleaned up...")
        assert not self.__check_hints_dir_present(node_from=node1, node_to_ip=node3_ip, node_to_hid=node3_hid) and not self.__check_hints_dir_present(node_from=node2, node_to_ip=node3_ip, node_to_hid=node3_hid)
    
        logger.info("Reading the data...")
        for x in range(100):
>           query_c1c2(session, x, ConsistencyLevel.ONE)

hintedhandoff_additional_test.py:377: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tools/data.py:106: in query_c1c2
    assertions.assert_length_equal(rows, 1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

object_with_length = [], expected_length = 1

    def assert_length_equal(object_with_length, expected_length):
        """
        Assert an object has a specific length.
        @param object_with_length The object whose length will be checked
        @param expected_length The expected length of the object
    
        Examples:
        assert_length_equal(res, nb_counter)
        """
>       assert len(object_with_length) == expected_length, f"Expected {object_with_length} to have length {expected_length}, but instead is of length {len(object_with_length)}"
E       AssertionError: Expected [] to have length 1, but instead is of length 0

tools/assertions.py:331: AssertionError
```

**Comment by piodul** [comment] 2024-08-01 09:18
@dawmd please take a look

**Comment by yaronkaikov** [comment] 2024-08-05 03:48
Seen again in https://jenkins.scylladb.com/job/scylla-6.0/job/next/176/

**Comment by yaronkaikov** [comment] 2024-08-05 03:48
I think we have identical issue https://github.com/scylladb/scylla-dtest/issues/4582

**Comment by yaronkaikov** [comment] 2024-08-08 04:30
Seen again https://jenkins.scylladb.com/job/scylla-master/job/next/8048/

**Comment by dawmd** [comment] 2024-08-13 17:57
Duplicate of scylladb/scylla-dtest#4582

**Comment by dawmd** [comment] 2024-08-20 11:00
Closing to not keep track of two issues about the same problem

**Closed by dawmd** 2024-08-20 11:00 UTC
Labels: tests/dtest, symptom/ci stability
