### ISSUE TITLE
test_changes_to_different_nodes times out on cql query

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#15569] opened 2023-09-27 15:50 UTC
concurrent_schema_changes_test.py::TestConcurrentSchemaChanges::test_changes_to_different_nodes

is timing out on `DROP COLUMNFAMILY` call (timeout is 30sec)

```
self = <concurrent_schema_changes_test.TestConcurrentSchemaChanges object at 0x7fbd4f6c8f90>

    @pytest.mark.dtest_debug
    def test_changes_to_different_nodes(self):
        logger.debug("changes_to_different_nodes_test()")
        cluster = self.cluster
        cluster.populate(2).start()
        node1, node2 = cluster.nodelist()
        wait(2)
        session = self.cql_connection(node1)
        self.prepare_for_changes(session, namespace='ns1')
        self.make_schema_changes(session, namespace='ns1')
        wait(3)
        self.validate_schema_consistent(node1)
    
        # wait for changes to get to the first node
        wait(20)
    
        session = self.cql_connection(node2)
        self.prepare_for_changes(session, namespace='ns2')
>       self.make_schema_changes(session, namespace='ns2')

concurrent_schema_changes_test.py:429: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
concurrent_schema_changes_test.py:101: in make_schema_changes
    session.execute("DROP COLUMNFAMILY cf2_%s" % namespace)
cassandra/cluster.py:2700: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'127.0.28.1:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.28.1:9042

cassandra/cluster.py:5019: OperationTimedOut
```

node1:
```
INFO  2023-09-27 13:09:13,797 [shard 0:stre] database - Dropping ks_ns2.cf2_ns2 with auto-snapshot
INFO  2023-09-27 13:09:13,798 [shard 0:stre] database - Truncating ks_ns2.cf2_ns2 with auto-snapshot
INFO  2023-09-27 13:09:45,638 [shard 1:comp] compaction - [Compact system.truncated 212f0c60-5d37-11ee-980b-a1bd8291d85b] Compacting [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-t9slirvh/test/node1/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g9q_10jd_4rok02b8lfx2l7ap23-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-t9slirvh/test/node1/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g9q_10i0_0ecz52b8lfx2l7ap23-big-Data.db:level=0:origin=compaction]
```

node2:
```
INFO  2023-09-27 13:09:13,887 [shard 0:stre] schema_tables - Dropping ks_ns2.cf2_ns2 id=00afcdd0-5d37-11ee-950a-a1bc8291d85b version=00afcdd1-5d37-11ee-950a-a1bc8291d85b
INFO  2023-09-27 13:09:13,887 [shard 0:stre] database - Dropping ks_ns2.cf2_ns2 with auto-snapshot
INFO  2023-09-27 13:09:13,887 [shard 0:stre] database - Truncating ks_ns2.cf2_ns2 with auto-snapshot
INFO  2023-09-27 13:09:45,639 [shard 1:comp] compaction - [Compact system.truncated 212f0c60-5d37-11ee-98f2-6aba789d26ca] Compacting [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-t9slirvh/test/node2/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g9q_10jd_5az002bqd2eduj7yru-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-t9slirvh/test/node2/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g9q_10i0_0tktd2bqd2eduj7yru-big-Data.db:level=0:origin=compaction]
```

### Logs

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4882/testReport/junit/concurrent_schema_changes_test/TestConcurrentSchemaChanges/FullDtest___full_split004___test_changes_to_different_nodes/

happened twice that we have CQL timing out in this test:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/3f18d100-5d4d-11ee-bf28-5927cc3d3ce3

**Comment by ptrsmrn** [comment] 2023-10-16 15:21
@havaker what's the progress on this item?

**Comment by havaker** [comment] 2023-10-16 19:15
I determined that `@pytest.mark.dtest_debug` does not mean that the test is ran in
debug mode ("this mark was just of group of select test to be run in debug
mode, it's not used anymore").

Created an environment to reproduce this test failure on most recent master
(400+ runs and no luck so far).

Timeout happened in `TestConcurrentSchemaChanges::make_schema_changes` -
inspected the body of that test:
- Learned the overall structure of the test
- Found `wait(some_arbitrary_duration)` calls - potentiall places for failures
  if the test is ran on a slow machine. I don't think they are causing this
  particular failure, because the encountered timeout is hit by the
  `session.execute("DROP COLUMNFAMILY cf2_%s" % namespace)` line in
  `make_schema_changes`.

Read the definition of Cassandra Column Family in the glossary - I've never
seen this term before.

Verified that `DROP COLUMNFAMILY` is synonymous with `DROP TABLE` by reading `Cql.g`
grammar spec in scylladb repo:
```antlr
K_COLUMNFAMILY:( C O L U M N F A M I L Y
                 | T A B L E );
```

Inspected logs from the failed run:
- `E   cassandra.OperationTimedOut: errors={'127.0.28.1:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.28.1:9042`
  indicates that the timeout happens on the client side - it is induced by the
  python driver, there is no information about the cause of this timeout on the
  server side.
- Logs on node1 and node2 show that a truncation was in progress.

Read about `remote` object, which was created during preparation for 2-phase
initialization of `query_processor`.

Inspected scylla code that does the actual `DROP TABLE`:
- `drop_table_statement::execute()`
- `schema_altering_statement::execute()` calls `qp.execute_schema_statement()`
- `qp.execute_schema_statement` calls `stmt.prepare_schema_mutations` (logs show
  something about compactions&truncation later, so this is probably not the place where
  the timeout happens)
- the only other operation that awaits in `qp.execute_schema_statement` is
  `co_await remote_.get().mm.announce(std::move(m), std::move(*guard), description);`
- announce in `migration_manager` calls `announce_with[out]_raft`. Since the logs
  url did not contain RAFT, I assume that the control flow goes to
  `announce_without_raft`.
- `announce_without_raft` pushes the schema mutation (`push_schema_mutation`) to every live node
  with `_messaging.send_definitions_update`.
- handler for `definitions_update` (lambda passed to `_messaging.register_definitions_update` in `migration_manager`)
  does not await and returns `netw::messaging_service::no_wait()`.
- after `co_await remote_.get().mm.announce()` there are no await points in the
  main controlflow of `drop_table_statement::execute()` and invoked methods.

Since the logs show that a truncation was in progress, I guess that
`mm.announce()` call went through. I don't have a good hypothesis about what
did cause the timeout.

**Comment by mykaul** [comment] 2023-10-17 07:10
Thanks @havaker for the extensive investigation. Let's wait to see if it happens again - we have some suspicion of infra issues that might have been a critical contributing factor to this failure.

**Comment by kostja** [comment] 2023-11-08 19:47
No failures in a while, closing.

**Closed by kostja** 2023-11-08 19:47 UTC
Labels: CI-Stability, infra?
