### ISSUE TITLE
describe schema: generating schema description preempts but does not protect form schema being changed in the meantime

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#18475] opened 2024-04-30 11:39 UTC
The implementation of describe schema looks fragile because it preempts while generating the description. Even though it grabs a bunch of `shared_ptr<const schema_element>` and those should effectively not change underneath - so it looks safe right now - it may be easy to create a regression in the future and make it break.

In order to prevent potential issues in the future, we can grab a group0 lock which will prevent the schema state in memory from being updated during a preemption.

**Comment by dawmd** [comment] 2024-10-17 08:47
Most likely a duplicate of scylladb/scylladb#20250

**Closed by dawmd** 2024-10-17 08:47 UTC
Labels: area/backup and restore
