### ISSUE TITLE
using aws lightsail with /var/lib/scylla on aws efs, scylla docker cannot start

### ISSUE THREAD

**Issue by hiqsociety** [scylladb/scylladb#16024] opened 2023-11-11 01:24 UTC
how to resolve the following?

docker run --name some-scylla -v /this/is/aws/mounted/efs/scylla:/var/lib/scylla -d scylladb/scylla --developer-mode 1

docker logs some-scylla

```
...
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.3, rpc-address: 172.17.0.3, seed-provider-parameters: seeds=172.17.0.3, alternator-address: 172.17.0.3, blocked-reactor-notify-ms, (positional) 999999999]
WARN  2023-11-11 01:16:52,833 seastar - Requested AIO slots too large, please increase request capacity in /proc/sys/fs/aio-max-nr. available:62875 requested:204104
WARN  2023-11-11 01:16:52,833 seastar - max-networking-io-control-blocks adjusted from 50000 to 14692, since AIO slots are unavailable
INFO  2023-11-11 01:16:52,833 seastar - Reactor backend: linux-aio
WARN  2023-11-11 01:16:52,835 [shard 0] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
INFO  2023-11-11 01:16:52,837 [shard 0] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
INFO  2023-11-11 01:16:52,837 [shard 0] seastar - IO queue uses 0.75ms latency goal for device 0
INFO  2023-11-11 01:16:52,837 [shard 0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2023-11-11 01:16:52,837 [shard 0] seastar - Created io queue dev(0) capacities: 512:2000:2000 1024:3000:3000 2048:5000:5000 4096:9000:9000 8192:17000:17000 16384:33000:33000 32768:65000:65000 65536:129000:129000 131072:257000:257000
WARN  2023-11-11 01:16:52,879 [shard 3] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-11-11 01:16:52,881 [shard 1] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-11-11 01:16:52,882 [shard 2] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
INFO  2023-11-11 01:16:52,885 [shard 0] seastar - updated: blocked-reactor-notify-ms=1000000
INFO  2023-11-11 01:16:52,885 [shard 1] seastar - updated: blocked-reactor-notify-ms=1000000
INFO  2023-11-11 01:16:52,885 [shard 2] seastar - updated: blocked-reactor-notify-ms=1000000
INFO  2023-11-11 01:16:52,885 [shard 3] seastar - updated: blocked-reactor-notify-ms=1000000
INFO  2023-11-11 01:16:52,890 [shard 0] init - installing SIGHUP handler
INFO  2023-11-11 01:16:52,925 [shard 0] init - Scylla version 5.2.9-0.20230920.5709d0043978 with build-id 686601fd1656c6724f7f042163b9285bf3efd582 starting ...

WARN  2023-11-11 01:16:52,925 [shard 0] init - I/O Scheduler is not properly configured! This is a non-supported setup, and performance is expected to be unpredictably bad.
 Reason found: none of --max-io-requests, --io-properties and --io-properties-file are set.
To properly configure the I/O Scheduler, run the scylla_io_setup utility shipped with Scylla.

INFO  2023-11-11 01:16:52,927 [shard 0] init - starting prometheus API server
INFO  2023-11-11 01:16:52,928 [shard 0] init - creating snitch
INFO  2023-11-11 01:16:52,928 [shard 0] init - starting tokens manager
INFO  2023-11-11 01:16:52,937 [shard 0] init - starting effective_replication_map factory
INFO  2023-11-11 01:16:52,937 [shard 0] init - starting migration manager notifier
INFO  2023-11-11 01:16:52,937 [shard 0] init - starting lifecycle notifier
INFO  2023-11-11 01:16:52,938 [shard 0] init - creating tracing
INFO  2023-11-11 01:16:52,938 [shard 0] init - starting API server
INFO  2023-11-11 01:16:52,939 [shard 0] init - Scylla API server listening on 127.0.0.1:10000 ...
INFO  2023-11-11 01:16:52,940 [shard 0] service_level_controller - update_from_distributed_data: starting configuration polling loop
INFO  2023-11-11 01:16:52,941 [shard 0] init - starting system keyspace
INFO  2023-11-11 01:16:52,941 [shard 0] init - starting gossiper
INFO  2023-11-11 01:16:52,941 [shard 0] init - seeds={172.17.0.3}, listen_address=172.17.0.3, broadcast_address=172.17.0.3
WARN  2023-11-11 01:16:52,941 [shard 0] init - Using default cluster name is not recommended. Using a unique cluster name will reduce the chance of adding nodes to the wrong cluster by mistake
INFO  2023-11-11 01:16:52,941 [shard 0] init - starting Raft address map
INFO  2023-11-11 01:16:52,942 [shard 0] init - starting direct failure detector pinger service
INFO  2023-11-11 01:16:52,942 [shard 0] init - starting direct failure detector service
INFO  2023-11-11 01:16:52,942 [shard 0] init - initializing storage service
INFO  2023-11-11 01:16:52,942 [shard 0] storage_service - Started node_ops_abort_thread
INFO  2023-11-11 01:16:52,942 [shard 1] storage_service - Started node_ops_abort_thread
INFO  2023-11-11 01:16:52,942 [shard 3] storage_service - Started node_ops_abort_thread
INFO  2023-11-11 01:16:52,942 [shard 2] storage_service - Started node_ops_abort_thread
INFO  2023-11-11 01:16:52,943 [shard 0] init - starting per-shard database core
INFO  2023-11-11 01:16:52,943 [shard 0] init - creating and verifying directories
INFO  2023-11-11 01:16:53,194 [shard 0] init - starting compaction_manager
INFO  2023-11-11 01:16:53,195 [shard 0] init - starting database
INFO  2023-11-11 01:16:53,203 [shard 0] compaction_manager - Set unlimited compaction bandwidth
ERROR 2023-11-11 01:16:53,219 [shard 0] seastar - io_submit: Operation not supported
exception running reactor main loop on shard 0.
Backtrace:
  0x4ff41f8
  0x5006883
  0x50050b8
  0x4fabaf5
  0x4faac68
  0x1148d34
  0x114a840
  0x114746a
  /opt/scylladb/libreloc/libc.so.6+0x2750f
  /opt/scylladb/libreloc/libc.so.6+0x275c8
  0x1145624
2023-11-11 01:16:53,315 INFO exited: scylla (exit status 1; not expected)
```

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
latest scylladocker
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by hiqsociety** [comment] 2023-11-15 22:33
is there a sure fire way to run scylladb 's /var/lib/scylla in nfs mount?

**Comment by mykaul** [comment] 2023-11-16 07:07
> is there a sure fire way to run scylladb 's /var/lib/scylla in nfs mount?

Already answered elsewhere - no, it's not a good idea.

**Comment by nyh** [comment] 2023-11-16 08:09
This seems like an exact duplicate of #16069. Closing this one, let's continue the discussion that already started on the other one.

**Closed** 2023-11-16 08:10 UTC
