### ISSUE TITLE
Coredump during replace node and change schema in parallel with raft

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#11581] opened 2022-09-20 06:35 UTC
## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `5.2.0~dev-20220914.6799e766ca95` with build-id `3f6897811f76b9db7f4143fc4cd299a3d7121b02`

Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-lwt-parallel-24h-master-db-node-fd3b16c5-9 (54.154.226.127 | 10.4.2.225) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-fd3b16c5-8 (34.254.185.219 | 10.4.3.246) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-fd3b16c5-7 (54.217.46.238 | 10.4.0.220) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-fd3b16c5-6 (54.194.244.145 | 10.4.3.50) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-fd3b16c5-5 (46.137.133.147 | 10.4.3.221) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-fd3b16c5-4 (34.250.207.246 | 10.4.2.92) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-fd3b16c5-3 (54.246.22.165 | 10.4.1.131) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-fd3b16c5-2 (34.252.158.23 | 10.4.0.177) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-fd3b16c5-10 (54.155.120.78 | 10.4.0.170) (shards: -1)
- longevity-lwt-parallel-24h-master-db-node-fd3b16c5-1 (34.248.167.237 | 10.4.0.12) (shards: 7)

OS / Image: `ami-04fa79b4f61c5bb9b` (aws: eu-west-1)

Test: `longevity-lwt-parallel-schema-changes-with-disruptive-24h-with-raft-test`
Test id: `fd3b16c5-3712-4b4a-bd7c-f011e60f9f9c`
Test name: `scylla-master/SCT_Raft_Experimental/longevity-lwt-parallel-schema-changes-with-disruptive-24h-with-raft-test`
Test config file(s):

- [longevity-lwt-parallel-24h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/220f2a92ef605d0d94b330d65f8f91e59e573338/test-cases/longevity/longevity-lwt-parallel-24h.yaml)

## Issue description

Job has parallel execution of disruption nemesis (which change topology) and modify table ( change schema). 
Unfortunately, log were not collected. the only data is from jenkins log.
During terminate and replace node and modifing table property with gc_period, 1 node trigger the abort on shard and coredump
```
2022-09-16 16:26:37.268 <2022-09-16 16:26:37.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=110e90b5-6439-4e0f-b36c-e67585f3d631: type=ABORTING_ON_SHARD regex=Aborting on shard line_number=5285396 node=longevity-lwt-parallel-24h-master-db-node-fd3b16c5-3
2022-09-16T16:26:37+00:00 longevity-lwt-parallel-24h-master-db-node-fd3b16c5-3     !INFO | scylla[7002]: Aborting on shard 0.
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
(inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:754
(inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:784
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:796
(inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3656
(inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3632
(inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3628
?? ??:0
?? ??:0
?? ??:0
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:43
service::raft_address_map<seastar::lowres_clock>::get_inet_address(utils::tagged_uuid<raft::server_id_tag>) const at ././service/raft/raft_address_map.hh:346
(inlined by) service::raft_rpc::send_append_entries(utils::tagged_uuid<raft::server_id_tag>, raft::append_request const&) at ./service/raft/raft_rpc.cc:37
operator() at ./raft/server.cc:755
_ZSt13__invoke_implIN7seastar6futureIvEERZZN4raft11server_impl12send_messageISt7variantIJNS3_14append_requestENS3_12append_replyENS3_12vote_requestENS3_10vote_replyENS3_16install_snapshotENS3_14snapshot_replyENS3_11timeout_nowENS3_11read_quorumENS3_17read_quorum_replyEEEEEvN5utils11tagged_uuidINS3_13server_id_tagEEET_ENKUlOSL_E_clIS7_EEDaSM_EUlvE_JEESL_St14__invoke_otherOT0_DpOT1_ at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
(inlined by) _ZSt8__invokeIRZZN4raft11server_impl12send_messageISt7variantIJNS0_14append_requestENS0_12append_replyENS0_12vote_requestENS0_10vote_replyENS0_16install_snapshotENS0_14snapshot_replyENS0_11timeout_nowENS0_11read_quorumENS0_17read_quorum_replyEEEEEvN5utils11tagged_uuidINS0_13server_id_tagEEET_ENKUlOSI_E_clIS4_EEDaSJ_EUlvE_JEENSt15__invoke_resultISI_JDpT0_EE4typeESJ_DpOSP_ at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
(inlined by) _ZSt6invokeIRZZN4raft11server_impl12send_messageISt7variantIJNS0_14append_requestENS0_12append_replyENS0_12vote_requestENS0_10vote_replyENS0_16install_snapshotENS0_14snapshot_replyENS0_11timeout_nowENS0_11read_quorumENS0_17read_quorum_replyEEEEEvN5utils11tagged_uuidINS0_13server_id_tagEEET_ENKUlOSI_E_clIS4_EEDaSJ_EUlvE_JEENSt13invoke_resultISI_JDpT0_EE4typeESJ_DpOSP_ at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/functional:97
(inlined by) _ZN7seastar8internal13future_invokeIRZZN4raft11server_impl12send_messageISt7variantIJNS2_14append_requestENS2_12append_replyENS2_12vote_requestENS2_10vote_replyENS2_16install_snapshotENS2_14snapshot_replyENS2_11timeout_nowENS2_11read_quorumENS2_17read_quorum_replyEEEEEvN5utils11tagged_uuidINS2_13server_id_tagEEET_ENKUlOSK_E_clIS6_EEDaSL_EUlvE_NS0_9monostateEEEDaSL_OT0_ at ././seastar/include/seastar/core/future.hh:1223
(inlined by) operator() at ././seastar/include/seastar/core/future.hh:1596
(inlined by) _ZN7seastar8futurizeINS_6futureIvEEE22satisfy_with_result_ofIZZNS2_14then_impl_nrvoIZZN4raft11server_impl12send_messageISt7variantIJNS6_14append_requestENS6_12append_replyENS6_12vote_requestENS6_10vote_replyENS6_16install_snapshotENS6_14snapshot_replyENS6_11timeout_nowENS6_11read_quorumENS6_17read_quorum_replyEEEEEvN5utils11tagged_uuidINS6_13server_id_tagEEET_ENKUlOSO_E_clISA_EEDaSP_EUlvE_S2_EET0_SP_ENKUlONS_8internal22promise_base_with_typeIvEERSS_ONS_12future_stateINSU_9monostateEEEE_clESX_SY_S12_EUlvE_EEvSX_SP_ at ././seastar/include/seastar/core/future.hh:2134
(inlined by) operator() at ././seastar/include/seastar/core/future.hh:1589
(inlined by) _ZN7seastar12continuationINS_8internal22promise_base_with_typeIvEEZZN4raft11server_impl12send_messageISt7variantIJNS4_14append_requestENS4_12append_replyENS4_12vote_requestENS4_10vote_replyENS4_16install_snapshotENS4_14snapshot_replyENS4_11timeout_nowENS4_11read_quorumENS4_17read_quorum_replyEEEEEvN5utils11tagged_uuidINS4_13server_id_tagEEET_ENKUlOSM_E_clIS8_EEDaSN_EUlvE_ZNS_6futureIvE14then_impl_nrvoISQ_SS_EET0_SN_EUlOS3_RSQ_ONS_12future_stateINS1_9monostateEEEE_vE15run_and_disposeEv at ././seastar/include/seastar/core/future.hh:781
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2329
(inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2736
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2905
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2788
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:265
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:156
scylla_main(int, char**) at ./main.cc:524
std::function<int (int, char**)>::operator()(int, char**) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
(inlined by) main at ./main.cc:1749
?? ??:0
_start at ??:?



2022-09-16 16:32:59.513 <2022-09-16 16:26:36.000>: (CoreDumpEvent Severity.ERROR) period_type=one-time event_id=42fd48c0-05db-45c7-bd25-e21db28c9266 node=Node longevity-lwt-parallel-24h-master-db-node-fd3b16c5-3 [54.246.22.165 | 10.4.1.131] (seed: False)
corefile_url=https://storage.cloud.google.com/upload.scylladb.com/core.scylla.113.b3f81b3cdaef403086ae8314c0fdd0bc.7002.1663345596000000000000/core.scylla.113.b3f81b3cdaef403086ae8314c0fdd0bc.7002.1663345596000000000000.gz
backtrace=           PID: 7002 (scylla)
UID: 113 (scylla)
GID: 119 (scylla)
Signal: 6 (ABRT)
Timestamp: Fri 2022-09-16 16:26:36 UTC (2min 32s ago)
Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 25 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7 --lock-memory=1
Executable: /opt/scylladb/libexec/scylla
Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
Unit: scylla-server.service
Slice: scylla-server.slice
Boot ID: b3f81b3cdaef403086ae8314c0fdd0bc
Machine ID: 7099d723fea041caa1694215c0ff6b7c
Hostname: longevity-lwt-parallel-24h-master-db-node-fd3b16c5-3
Storage: /var/lib/systemd/coredump/core.scylla.113.b3f81b3cdaef403086ae8314c0fdd0bc.7002.1663345596000000000000
Message: Process 7002 (scylla) of user 113 dumped core.
Stack trace of thread 7002:
#0  0x00007f422f62f2a2 raise (libc.so.6 + 0x3d2a2)
#1  0x00007f422f6188a4 abort (libc.so.6 + 0x268a4)
#2  0x0000000004da6c03 _ZN7seastar17on_internal_errorERNS_6loggerESt17basic_string_viewIcSt11char_traitsIcEE (scylla + 0x4ba6c03)
#3  0x0000000003ba92cf _ZN7service8raft_rpc19send_append_entriesEN5utils11tagged_uuidIN4raft13server_id_tagEEERKNS3_14append_requestE (scylla + 0x39a92cf)
#4  0x0000000003d0d5c6 _ZZZN4raft11server_impl12send_messageISt7variantIJNS_14append_requestENS_12append_replyENS_12vote_requestENS_10vote_replyENS_16install_snapshotENS_14snapshot_replyENS_11timeout_nowENS_11read_quorumENS_17read_quorum_replyEEEEEvN5utils11tagged_uuidINS_13server_id_tagEEET_ENKUlOSH_E_clIS3_EEDaSI_ENKUlvE_clEv (scylla + 0x3b0d5c6)
#5  0x0000000003d0e3a9 _ZN7seastar12continuationINS_8internal22promise_base_with_typeIvEEZZN4raft11server_impl12send_messageISt7variantIJNS4_14append_requestENS4_12append_replyENS4_12vote_requestENS4_10vote_replyENS4_16install_snapshotENS4_14snapshot_replyENS4_11timeout_nowENS4_11read_quorumENS4_17read_quorum_replyEEEEEvN5utils11tagged_uuidINS4_13server_id_tagEEET_ENKUlOSM_E_clIS8_EEDaSN_EUlvE_ZNS_6futureIvE14then_impl_nrvoISQ_SS_EET0_SN_EUlOS3_RSQ_ONS_12future_stateINS1_9monostateEEEE_vE15run_and_disposeEv (scylla + 0x3b0e3a9)
#6  0x0000000004dd40f5 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x4bd40f5)
#7  0x0000000004dd54d8 _ZN7seastar7reactor6do_runEv (scylla + 0x4bd54d8)
#8  0x0000000004dd472d _ZN7seastar7reactor3runEv (scylla + 0x4bd472d)
#9  0x0000000004d7a5a9 _ZN7seastar12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla + 0x4b7a5a9)
#10 0x0000000004d79a82 _ZN7seastar12app_template3runEiPPcOSt8functionIFNS_6futureIiEEvEE (scylla + 0x4b79a82)
#11 0x00000000010a993b _ZL11scylla_mainiPPc (scylla + 0xea993b)
#12 0x00000000010a7446 main (scylla + 0xea7446)
#13 0x00007f422f619b75 __libc_start_main (libc.so.6 + 0x27b75)
#14 0x00000000010a556e _start (scylla + 0xea556e)
Stack trace of thread 7003:
#0  0x00007f42301d694c read (libpthread.so.0 + 0x1294c)
#1  0x0000000004dfa74c _ZN7seastar9file_desc4readEPvm (scylla + 0x4bfa74c)
#2  0x0000000004dec518 _ZZN7seastar7reactor12do_read_someERNS_17pollable_fd_stateEPNS_8internal16buffer_allocatorEENK3$_6clEv (scylla + 0x4bec518)
#3  0x0000000004dec634 _ZN7seastar12continuationINS_8internal22promise_base_with_typeINS_16temporary_bufferIcEEEEZNS_7reactor12do_read_someERNS_17pollable_fd_stateEPNS1_16buffer_allocatorEE3$_6ZNS_6futureIvE14then_impl_nrvoISB_NSC_IS4_EEEET0_OT_EUlOS5_RSB_ONS_12future_stateINS1_9monostateEEEE_vE15run_and_disposeEv (scylla + 0x4bec634)
#4  0x0000000004dd40f5 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x4bd40f5)
#5  0x0000000004dd54d8 _ZN7seastar7reactor6do_runEv (scylla + 0x4bd54d8)
#6  0x0000000004df45b6 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE4$_90E9_M_invokeERKSt9_Any_data (scylla + 0x4bf45b6)
#7  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#8  0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#9  0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7010:
#0  0x00007f42301d694c read (libpthread.so.0 + 0x1294c)
#1  0x0000000004e16445 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x4c16445)
#2  0x0000000004e167a0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x4c167a0)
#3  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#4  0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#5  0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7011:
#0  0x00007f42301d694c read (libpthread.so.0 + 0x1294c)
#1  0x0000000004e16445 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x4c16445)
#2  0x0000000004e167a0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x4c167a0)
#3  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#4  0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#5  0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7012:
#0  0x00007f42301d694c read (libpthread.so.0 + 0x1294c)
#1  0x0000000004e16445 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x4c16445)
#2  0x0000000004e167a0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x4c167a0)
#3  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#4  0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#5  0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7014:
#0  0x00007f42301d694c read (libpthread.so.0 + 0x1294c)
#1  0x0000000004e16445 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x4c16445)
#2  0x0000000004e167a0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x4c167a0)
#3  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#4  0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#5  0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7013:
#0  0x00007f42301d694c read (libpthread.so.0 + 0x1294c)
#1  0x0000000004e16445 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x4c16445)
#2  0x0000000004e167a0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x4c167a0)
#3  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#4  0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#5  0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7015:
#0  0x00007f42301d694c read (libpthread.so.0 + 0x1294c)
#1  0x0000000004e16445 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x4c16445)
#2  0x0000000004e167a0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x4c167a0)
#3  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#4  0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#5  0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7007:
#0  0x0000000003a10bd5 _ZNK20range_tombstone_list5sliceERK6schema26position_in_partition_viewS3_ (scylla + 0x3810bd5)
#1  0x00000000019d3d87 _ZN18partition_snapshot16range_tombstonesE26position_in_partition_viewS0_St8functionIFN7seastar10bool_classINS2_18stop_iteration_tagEEE15range_tombstoneEEb (scylla + 0x17d3d87)
#2  0x0000000001a3c1f7 _ZZN5cache26cache_flat_mutation_reader14do_fill_bufferEvENKUlvE1_clEv (scylla + 0x183c1f7)
#3  0x0000000001a28334 _ZN5cache26cache_flat_mutation_reader14do_fill_bufferEv (scylla + 0x1828334)
#4  0x00000000019e1f23 _ZZN5cache26cache_flat_mutation_reader11fill_bufferEvENKUlvE_clEv (scylla + 0x17e1f23)
#5  0x00000000019e0df1 _ZN5cache26cache_flat_mutation_reader11fill_bufferEv (scylla + 0x17e0df1)
#6  0x0000000001c293d9 _ZN22mutation_reader_merger12prepare_nextEv (scylla + 0x1a293d9)
#7  0x0000000001c2a3ef _ZN22mutation_reader_mergerclEv (scylla + 0x1a2a3ef)
#8  0x0000000001c3608b _ZZN14merging_readerI22mutation_reader_mergerE11fill_bufferEvENKUlvE_clEv (scylla + 0x1a3608b)
#9  0x0000000001c34b1b _ZN14merging_readerI22mutation_reader_mergerE11fill_bufferEv (scylla + 0x1a34b1b)
#10 0x00000000017d5ba4 _ZN23flat_mutation_reader_v24peekEv (scylla + 0x15d5ba4)
#11 0x00000000017a02b8 _ZN5query7querier12consume_pageI20query_result_builderEEDaOT_mjNSt6chrono10time_pointI8gc_clockNS5_8durationIlSt5ratioILl1ELl1EEEEEEN7tracing15trace_state_ptrE (scylla + 0x15a02b8)
#12 0x000000000179bcf2 _ZN7replica5table5queryEN7seastar13lw_shared_ptrIK6schemaEE13reader_permitRKN5query12read_commandENS7_14result_optionsERKSt6vectorI20nonwrapping_intervalIN3dht13ring_positionEESaISG_EEN7tracing15trace_state_ptrERNS7_21result_memory_limiterENSt6chrono10time_pointINS1_12lowres_clockENSP_8durationIlSt5ratioILl1ELl1000000000EEEEEEPSt8optionalINS7_7querierEE (scylla + 0x159bcf2)
#13 0x00000000016e42bd _ZN7seastar20noncopyable_functionIFNS_6futureIvEE13reader_permitEE19indirect_vtable_forIZN7replica8database5queryENS_13lw_shared_ptrIK6schemaEERKN5query12read_commandENSD_14result_optionsERKSt6vectorI20nonwrapping_intervalIN3dht13ring_positionEESaISM_EEN7tracing15trace_state_ptrENSt6chrono10time_pointINS_12lowres_clockENST_8durationIlSt5ratioILl1ELl1000000000EEEEEESt7variantIJSt9monostateN2db24per_partition_rate_limit12account_onlyENS14_19account_and_enforceEEEE4$_20E4callEPKS5_S3_ (scylla + 0x14e42bd)
#14 0x0000000003ac66f1 _ZN28reader_concurrency_semaphore14execution_loopEv.resume (scylla + 0x38c66f1)
#15 0x0000000004dd40f5 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x4bd40f5)
#16 0x0000000004dd54d8 _ZN7seastar7reactor6do_runEv (scylla + 0x4bd54d8)
#17 0x0000000004df45b6 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE4$_90E9_M_invokeERKSt9_Any_data (scylla + 0x4bf45b6)
#18 0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#19 0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#20 0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7009:
#0  0x00007f42301d694c read (libpthread.so.0 + 0x1294c)
#1  0x0000000004e16445 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla + 0x4c16445)
#2  0x0000000004e167a0 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x4c167a0)
#3  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#4  0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#5  0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7005:
#0  0x0000000001b23881 _ZN3row19apply_monotonicallyERK17column_definitionO25atomic_cell_or_collectionN7seastar18optimized_optionalI9cell_hashEE (scylla + 0x1923881)
#1  0x0000000001fcaa22 _ZN8sstables2mx17mp_row_consumer_m15consume_row_endEv (scylla + 0x1dcaa22)
#2  0x0000000001ff8ebf _ZN8sstables2mx27data_consume_rows_context_m16do_process_stateEv.resume (scylla + 0x1df8ebf)
#3  0x0000000001fdb0ee _ZN13data_consumer24continuous_data_consumerIN8sstables2mx27data_consume_rows_context_mEEclEN7seastar16temporary_bufferIcEE (scylla + 0x1ddb0ee)
#4  0x0000000001fda8eb _ZZN7seastar12input_streamIcE7consumeISt17reference_wrapperIN8sstables2mx27data_consume_rows_context_mEEEENS_6futureIvEEOT_ENUlvE_clEv (scylla + 0x1dda8eb)
#5  0x0000000001fdd0a1 _ZN7seastar8internal8repeaterIZNS_12input_streamIcE7consumeISt17reference_wrapperIN8sstables2mx27data_consume_rows_context_mEEEENS_6futureIvEEOT_EUlvE_E15run_and_disposeEv (scylla + 0x1ddd0a1)
#6  0x0000000004dd40f5 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x4bd40f5)
#7  0x0000000004dd54d8 _ZN7seastar7reactor6do_runEv (scylla + 0x4bd54d8)
#8  0x0000000004df45b6 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE4$_90E9_M_invokeERKSt9_Any_data (scylla + 0x4bf45b6)
#9  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#10 0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#11 0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7006:
#0  0x00007ffefeddca67 __vdso_clock_gettime (linux-vdso.so.1 + 0xa67)
#1  0x00007f422f6b99b5 __clock_gettime (libc.so.6 + 0xc79b5)
#2  0x00007f422f8acdb5 _ZNSt6chrono3_V212steady_clock3nowEv (libstdc++.so.6 + 0xd0db5)
#3  0x0000000004dd554d _ZN7seastar7reactor6do_runEv (scylla + 0x4bd554d)
#4  0x0000000004df45b6 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE4$_90E9_M_invokeERKSt9_Any_data (scylla + 0x4bf45b6)
#5  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#6  0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#7  0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7008:
#0  0x0000000004dd7a42 _ZN7seastar17smp_message_queue19process_completionsEj (scylla + 0x4bd7a42)
#1  0x0000000004de33ad _ZN7seastar3smp11poll_queuesEv (scylla + 0x4be33ad)
#2  0x0000000004e1178b _ZN7seastar7reactor10smp_pollfn4pollEv (scylla + 0x4c1178b)
#3  0x0000000004df3739 _ZNSt17_Function_handlerIFbvEZN7seastar7reactor6do_runEvE4$_44E9_M_invokeERKSt9_Any_data (scylla + 0x4bf3739)
#4  0x0000000004dd5522 _ZN7seastar7reactor6do_runEv (scylla + 0x4bd5522)
#5  0x0000000004df45b6 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE4$_90E9_M_invokeERKSt9_Any_data (scylla + 0x4bf45b6)
#6  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#7  0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#8  0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
Stack trace of thread 7004:
#0  0x00007f42301d694c read (libpthread.so.0 + 0x1294c)
#1  0x0000000004dfa74c _ZN7seastar9file_desc4readEPvm (scylla + 0x4bfa74c)
#2  0x0000000004dec518 _ZZN7seastar7reactor12do_read_someERNS_17pollable_fd_stateEPNS_8internal16buffer_allocatorEENK3$_6clEv (scylla + 0x4bec518)
#3  0x0000000004dec634 _ZN7seastar12continuationINS_8internal22promise_base_with_typeINS_16temporary_bufferIcEEEEZNS_7reactor12do_read_someERNS_17pollable_fd_stateEPNS1_16buffer_allocatorEE3$_6ZNS_6futureIvE14then_impl_nrvoISB_NSC_IS4_EEEET0_OT_EUlOS5_RSB_ONS_12future_stateINS1_9monostateEEEE_vE15run_and_disposeEv (scylla + 0x4bec634)
#4  0x0000000004dd40f5 _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x4bd40f5)
#5  0x0000000004dd54d8 _ZN7seastar7reactor6do_runEv (scylla + 0x4bd54d8)
#6  0x0000000004df45b6 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE4$_90E9_M_invokeERKSt9_Any_data (scylla + 0x4bf45b6)
#7  0x0000000004da79fb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4ba79fb)
#8  0x00007f42301cd2a5 start_thread (libpthread.so.0 + 0x92a5)
#9  0x00007f422f6f2323 __clone (libc.so.6 + 0x100323)
download_instructions=gsutil cp gs://upload.scylladb.com/core.scylla.113.b3f81b3cdaef403086ae8314c0fdd0bc.7002.1663345596000000000000/core.scylla.113.b3f81b3cdaef403086ae8314c0fdd0bc.7002.1663345596000000000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.113.b3f81b3cdaef403086ae8314c0fdd0bc.7002.1663345596000000000000.gz

```

- Restore Monitor Stack command: `$ hydra investigate show-monitor fd3b16c5-3712-4b4a-bd7c-f011e60f9f9c`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=fd3b16c5-3712-4b4a-bd7c-f011e60f9f9c)
- Show all stored logs command: `$ hydra investigate show-logs fd3b16c5-3712-4b4a-bd7c-f011e60f9f9c`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/SCT_Raft_Experimental/job/longevity-lwt-parallel-schema-changes-with-disruptive-24h-with-raft-test/8/)

**Comment by aleksbykov** [comment] 2022-09-20 07:44
Maybe related issue: https://github.com/scylladb/scylladb/issues/11582

**Comment by kostja** [comment] 2022-10-14 17:01
This should be addressed in the latest master please recheck. @aleksbykov

**Comment by kostja** [comment] 2023-04-08 10:40
No activity since October, please re-open if the issue is still present.

**Comment by roydahan** [comment] 2023-04-09 17:33
@aleksbykov to verify if/when run and if reproduced.

**Comment by aleksbykov** [comment] 2024-04-15 08:40
With raft-topology feature issue ws not reproduced. for 5.4 this job was not triggered.

**Comment by temichus** [comment] 2024-04-16 09:17
> With raft-topology feature issue ws not reproduced. for 5.4 this job was not triggered.

cc @roydahan

**Comment by mykaul** [comment] 2024-05-20 08:16
@roydahan - what's the next step here?

**Comment by roydahan** [comment] 2024-05-20 10:22
I guess we can close this.

**Closed by roydahan** 2024-05-20 10:22 UTC
Labels: type/bug, feature/enhancement, area/raft
