### ISSUE TITLE
Docs: Issue in page Scylla Alternator for DynamoDB users - link rendering

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#11333] opened 2022-08-20 13:28 UTC
I would like to report an issue in page https://docs.scylladb.com/master/alternator/compatibility

### Problem
The links in the doc does not automatically render as links
Random example
![image](https://user-images.githubusercontent.com/170200/185748302-09f9db49-0790-4be3-a385-0715f965ec70.png)
The two links are text, not links

###  Suggest a fix

This is should be probably fix in the Sphinx configuration for MD

**Comment by tzach** [comment] 2022-08-20 13:29
@dgarcia360 can you please take a look?
@annastuchlik @nyh FYI

**Comment by nyh** [comment] 2022-08-21 09:00
This is a duplicate of https://github.com/scylladb/scylla-docs/issues/3319 and https://github.com/scylladb/sphinx-scylladb-theme/issues/107 (the former was closed after opening the latter).

In general, our "*.md" files should be in the "github markdown format", and should support the same features that github does because that is what the developers will typically use to view their .md files. Here for example you can see how github formats compatibility.md: https://github.com/scylladb/scylladb/blob/master/docs/alternator/compatibility.md - you can see that links are detected and formatted automatically without extra markup. Moreover, Github even has a nice feature where it formats links to github issues as issue numbers instead of showing the full URL.

If for some reason it is impossible (?) for sphinx to detect "bare" URLs and format them as links, and we need to do this linking manually, then we need to look for all the *.md files that have URLs and "fix" them. The fix should look good not just on sphinx but also in github. If we have a program to look for URLs in the *.md files, then let's run this problem in the code we run to verify the correctness of document patches - we wouldn't want new URLs to be added to .md files in the future.

**Comment by tzach** [comment] 2022-08-21 09:44
AFAIU, create a link from a "clean" URL is not part of [Markdown spec](https://github.github.com/gfm/#autolinks)
Instead, we can use the `< URL >` notion for example:
```
<https://github.com/scylladb/alternator-load-balancing/>
```
As you can see below, it render in Github as well:
<https://github.com/scylladb/alternator-load-balancing/>

**Comment by tzach** [comment] 2022-08-23 13:30
@nyh any idea why this issue was not automatically closed with #11335 merge?

**Comment by nyh** [comment] 2022-08-24 15:02
Good question... I can't think of any reason :-(
I'll close this issue manually, but I don't know if we did anything wrong we need to avoid, or it was some bug on github or what.

By the way, closing this issue made me think. What do you think we need to do about backporting of docs patches?
On one hand documentation errors aren't serious "bugs", but on the other hand, if there are errors, ugly formatting, etc., in all versions of the documentation, do we really want to fix them only in the latest version?

I'll temporarily add the backport tag to this patch (like the bot should have done), but we need to think in general what we want to do about documentation backports.

**Closed by nyh** 2022-08-24 15:02 UTC
Labels: Documentation

**Comment by tzach** [comment] 2022-08-24 18:31
> What do you think we need to do about backporting of docs patches?

It would be useless right now, since the doc site only render master branch any way.
It would make sense we publish the first release, either 5.1 to 5.2

**Comment by avikivity** [comment] 2022-09-29 20:48
Minor documentation issue, not backporting

**Comment by nyh** [comment] 2022-11-21 07:54
In https://github.com/scylladb/scylladb/pull/11335#issuecomment-1319962353 @annastuchlik asked anyway to backport this to 5.1. I'll do it.
