### ISSUE TITLE
Staging sstables should not read other staging sstables for reading base data

### ISSUE THREAD

**Issue by psarna** [scylladb/scylladb#6218] opened 2020-04-16 12:58 UTC
When generating view updates from staging sstables which arrived from streaming,
the implementation currently creates a reader which reads all sstables **except** the one being processed.
What should rather be done is excluding all sstables still residing in the staging directory - since from the point of view of the view update, these sstables do not yet exist in the system.
The issue is benign for repair, which already provides non-overlapping sstables, but `staging/` is also used in `nodetool refresh`, which gives no assumptions wrt. its sstables.

Refs #6177, which prepared the update generator to exclude multiple sstables at a time - the ongoing @glommer's project which couples view update generation with compactions is also related to this issue.

/cc @nyh @slivne - this issue is inspired by today's discussion, please review if this text above is sane and make sense.

**Comment by glommer** [comment] 2020-04-16 13:00
good to know. I will keep this in mind. Anything however you propose to be fixed now ?

**Comment by psarna** [comment] 2020-04-19 06:16
No rush (and judging by no milestone assigned - no priority), it simply needs to be taken into account in the "view update generation 💖 compaction" series, and this issue was created to not forget that this problem exists.

**Comment by eliransin** [comment] 2020-05-20 12:20
@psarna it got priority :smile:

**Comment by psarna** [comment] 2020-05-20 12:31
As far as I know it's already done as a side effect of one of @glommer's series. All registered staging sstables for a given table are now bundled together and processed together, which also means that they will not use each other for reading, which this issue is all about.
Source: 4e6400293e8cb6e7729d30cfb7e27dc03a3190f9

**Comment by glommer** [comment] 2020-05-20 12:41
hi - saw me being tagged

This is done, no ? (which seems to be exactly what you are saying)

@psarna I was lying before: I didn't do this issue because of an upcoming series of mine. I did it because I was secretly subconsciously aware of this one issue here and I just like you too much.

**Comment by slivne** [comment] 2020-05-20 12:43
The problem is that this bug exists in earlier releases ...

I xpect glauber patches will not be backportable to earlier releases

If its simple lets fix it in older releases as well.

**Comment by glommer** [comment] 2020-05-20 12:46
I expect the patches the be backportable. They are not hard.

Shlomi, which version do you need ?

**Comment by slivne** [comment] 2020-05-20 12:52
4.0, 3.3 (+Enterprise)

**Comment by glommer** [comment] 2020-05-20 12:59
I will look into this in the afternoon shlomi

**Comment by glommer** [comment] 2020-05-20 13:04
@slivne the backport to 4.0 is clean. Commit is 4e6400293e8cb6e7729d30cfb7e27dc03a3190f9

There is another commit in the series but it is for tests only, we don't need to backport.

Backport to 3.3 is harder. I will prepare later.

**Comment by slivne** [comment] 2020-05-20 13:11
Ok thanks,

**Comment by glommer** [comment] 2020-05-20 14:12
@slivne I'll need a Fixes tag for the backport to 3.3
What issue should I quote? This one doesn't seem tobe describing any bug

**Comment by slivne** [comment] 2020-05-20 14:35
#6218 is a bug.

**Comment by glommer** [comment] 2020-05-20 14:44
It's this bug, shlomi =)
What I means is that it doesn't report any failure, ill behavior or anything. Just says this should be done.
That's usually not enough for a backport in Avi's view.

In any case I have the 3.3 backport ready and will send now

**Closed** 2022-09-16 08:51 UTC
Labels: Correctness, materialized-views
