### ISSUE TITLE
[dtest] test_update_schema_while_node_is_killed[alter_table]  failed with InvalidRequest

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#17362] opened 2024-02-15 19:06 UTC
Seen in https://jenkins.scylladb.com/job/scylla-master/job/next/7243

Error 
```
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid column name c3 because it conflicts with an existing column"
```

**Comment by mykaul** [comment] 2024-02-19 11:39
Is this a new test, or a new regression?

**Comment by mykaul** [comment] 2024-02-22 11:38
@yaronkaikov ?

**Comment by mykaul** [comment] 2024-02-22 11:39
It's not a new test - added to gating in October or so.

**Comment by yaronkaikov** [comment] 2024-02-22 11:41
we also don't have the dtest job

**Comment by yaronkaikov** [comment] 2024-02-22 11:44
@mykaul last 20 runs passed, i think we can close this for now
![image](https://github.com/scylladb/scylladb/assets/9914527/9e12caf3-0057-464c-97fd-f8b48d37b44d)

**Comment by nyh** [comment] 2024-02-22 15:32
@yaronkaikov, maybe shouldn't close this - seen again in https://jenkins.scylladb.com/job/scylla-master/job/next/7277/:

```
Build / x86 / dtest with topology changes / schema_management_test.TestSchemaManagement.test_update_schema_while_node_is_killed[alter_table]

self = <schema_management_test.TestSchemaManagement object at 0x7f733b4e9bd0>
case = 'alter_table'

    @pytest.mark.parametrize("case", ("create_table", "alter_table", "drop_table"))
    def test_update_schema_while_node_is_killed(self, case):
        """
        Check that a node that is killed durring a table creation/alter/drop is able to rejoin and to synch on schema
        """
    
        logger.debug("1. Create a cluster and insert data")
        self.cluster.set_configuration_options(values={"ring_delay_ms": 5000})
        self.cluster.populate(3)
        self.cluster.start(wait_other_notice=True)
    
        [node1, node2, node3] = self.cluster.nodelist()
    
        session = self.patient_cql_connection(node1)
    
        def create_table_case():
            logger.debug("Creating table")
            create_c1c2_table(session)
            logger.debug("Populating")
            insert_c1c2(session, n=10)
    
        logger.debug("Creating keyspace")
        create_ks(session, "ks", 3)
        if case != "create_table":
            create_table_case()
    
        case_map = {
            "create_table": create_table_case,
            "alter_table": functools.partial(session.execute, "ALTER TABLE ks.cf ADD (c3 text);", timeout=180),
            "drop_table": functools.partial(session.execute, "DROP TABLE cf;", timeout=180),
        }
        with ThreadPoolExecutor(max_workers=2) as executor:
            logger.debug(f"2. kill node during {case}")
            kill_node_future = executor.submit(node2.stop, gently=False, wait_other_notice=True)
>           case_map[case]()

schema_management_test.py:240: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cassandra/cluster.py:2726: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid column name c3 because it conflicts with an existing column"

cassandra/cluster.py:5085: InvalidRequest
```

**Comment by enaydanov** [comment] 2024-02-25 03:03
btw, it is failed for Raft topology only.

**Comment by kbr-scylla** [comment] 2024-02-25 20:48
That last failure is with raft topology, but we don't know if the original failure was with raft topology, we lost the logs.

(I'm asking every time -- please upload logs to GH when reporting issue)

**Comment by kbr-scylla** [comment] 2024-02-25 20:49
Logs for last failure:
[1708610230795_schema_management_test.py TestSchemaManagement test_update_schema_while_node_is_killed[alter_table].zip](https://github.com/scylladb/scylladb/files/14397789/1708610230795_schema_management_test.py.TestSchemaManagement.test_update_schema_while_node_is_killed.alter_table.zip)
[dtest-gw2.log](https://github.com/scylladb/scylladb/files/14397790/dtest-gw2.log)

**Comment by kbr-scylla** [comment] 2024-02-25 20:52
Could be that there's some retry going on behind the scenes, which causes the ALTER to be executed twice?
I see the ALTER happens concurrently with one node being killed.
So perhaps we have something like this:
- driver sends ALTER to node 2
- the ALTER gets committed, but node 2 gets killed before driver gets response
- driver retries (?)

But I don't know if that's legal, whether the driver is allowed to retry schema changes like that.

**Comment by tchaikov** [comment] 2024-02-26 07:55
[1708926071477_schema_management_test.py TestSchemaManagement test_update_schema_while_node_is_killed[drop_table].zip](https://github.com/scylladb/scylladb/files/14401338/1708926071477_schema_management_test.py.TestSchemaManagement.test_update_schema_while_node_is_killed.drop_table.zip)

[dtest-gw4.zip](https://github.com/scylladb/scylladb/files/14401371/dtest-gw4.zip)

```
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot drop non existing table 'cf' in keyspace 'ks'."
...


    @pytest.mark.parametrize("case", ("create_table", "alter_table", "drop_table"))
    def test_update_schema_while_node_is_killed(self, case):
        """
        Check that a node that is killed durring a table creation/alter/drop is able to rejoin and to synch on schema
        """
...
        with ThreadPoolExecutor(max_workers=2) as executor:
            logger.debug(f"2. kill node during {case}")
            kill_node_future = executor.submit(node2.stop, gently=False, wait_other_notice=True)
>           case_map[case]()

schema_management_test.py:240: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cassandra/cluster.py:2726: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot drop non existing table 'cf' in keyspace 'ks'."

cassandra/cluster.py:5085: InvalidRequest
```
see https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/141/

**Comment by kbr-scylla** [comment] 2024-02-26 10:05
Looking at the logs, the driver retry hypothesis looks likely.

In [this run](https://github.com/scylladb/scylladb/issues/17362#issuecomment-1963057137) I see the following:
on node 2, the one which is killed by the test, we have:
```
INFO  2024-02-22 13:56:39,751 [shard 0:stmt] migration_manager - Update table 'ks.cf' From org.apache.cassandra.config.CFMetaData@0x600004f8e380[cfId=32fe1b30-d18a-11ee-b2a2-773c0b99976e,ksName=ks,cfName=cf,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type),comment=test cf,readRepairChance=0,dcLocalReadRepairChance=0,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.UTF8Type,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=key, type=org.apache.cassandra.db.marshal.UTF8Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=c1, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=c2, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true, enabled=true},compressionParameters={},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=32fe1b31-d18a-11ee-b2a2-773c0b99976e,droppedColumns={},collections={},indices={}] To org.apache.cassandra.config.CFMetaData@0x60000078c700[cfId=32fe1b30-d18a-11ee-b2a2-773c0b99976e,ksName=ks,cfName=cf,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type),comment=test cf,readRepairChance=0,dcLocalReadRepairChance=0,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.UTF8Type,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=key, type=org.apache.cassandra.db.marshal.UTF8Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=c1, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=c2, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=c3, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true, enabled=true},compressionParameters={},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=33a99d70-d18a-11ee-b2a2-773c0b99976e,droppedColumns={},collections={},indices={}]
```
so alter was executed on this node at 13:56:39

Then in the test logs (dtest-gw2.log) we see:
```
13:56:39,786 799     cassandra.cluster              WARNING  libevreactor.py     :295  | test_update_schema_while_node_is_killed[alter_table]: Host 127.0.74.2:9042 has been marked down
13:56:40,857 799     cassandra.pool                 WARNING  thread.py           :58   | test_update_schema_while_node_is_killed[alter_table]: Error attempting to reconnect to 127.0.74.2:9042, scheduling retry in 2.16 seconds: [Errno 111] Tried connecting to [('127.0.74.2', 9042)]. Last error: Connection refused
13:56:43,060 799     cassandra.pool                 WARNING  thread.py           :58   | test_update_schema_while_node_is_killed[alter_table]: Error attempting to reconnect to 127.0.74.2:9042, scheduling retry in 3.44 seconds: [Errno 111] Tried connecting to [('127.0.74.2', 9042)]. Last error: Connection refused
13:56:46,564 799     cassandra.pool                 WARNING  thread.py           :58   | test_update_schema_while_node_is_killed[alter_table]: Error attempting to reconnect to 127.0.74.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.74.2', 9042)]. Last error: Connection refused
13:56:50,569 799     cassandra.pool                 WARNING  thread.py           :58   | test_update_schema_while_node_is_killed[alter_table]: Error attempting to reconnect to 127.0.74.2:9042, scheduling retry in 3.84 seconds: [Errno 111] Tried connecting to [('127.0.74.2', 9042)]. Last error: Connection refused
13:56:54,475 799     cassandra.pool                 WARNING  thread.py           :58   | test_update_schema_while_node_is_killed[alter_table]: Error attempting to reconnect to 127.0.74.2:9042, scheduling retry in 3.72 seconds: [Errno 111] Tried connecting to [('127.0.74.2', 9042)]. Last error: Connection refused
13:56:58,279 799     cassandra.pool                 WARNING  thread.py           :58   | test_update_schema_while_node_is_killed[alter_table]: Error attempting to reconnect to 127.0.74.2:9042, scheduling retry in 3.88 seconds: [Errno 111] Tried connecting to [('127.0.74.2', 9042)]. Last error: Connection refused
13:57:01,702 799     errors                         ERROR    conftest.py         :202  | test_update_schema_while_node_is_killed[alter_table]: test failed: 
```

So we see driver reconnection attempts *after* this initial update, and then, 30 seconds later, a failure.

Since the failure happened 30 seconds later than the alter attempt we already saw, it means the driver most likely tried to execute the statement again these 30 seconds later.

**Comment by kbr-scylla** [comment] 2024-02-26 10:22
Python driver code cassandra/policies.py
```python3
class RetryPolicy(object):
...
    def on_request_error(self, query, consistency, error, retry_num):
        """
        This is called when an unexpected error happens. This can be in the
        following situations:

        * On a connection error
        * On server errors: overloaded, isBootstrapping, serverError, etc.

        `query` is the :class:`.Statement` that timed out.

        `consistency` is the :class:`.ConsistencyLevel` that the operation was
        attempted at.

        `error` the instance of the exception.

        `retry_num` counts how many times the operation has been retried, so
        the first time this method is called, `retry_num` will be 0.

        The default, it triggers a retry on the next host in the query plan
        with the same consistency level.
        """
        # TODO revisit this for the next major
        # To preserve the same behavior than before, we don't take retry_num into account
        return self.RETRY_NEXT_HOST, None
```

**Comment by kbr-scylla** [comment] 2024-02-26 10:28
I see the test was flaky before: https://github.com/scylladb/scylladb/issues/15200
but in a different way --- the query was timing out.

We made several improvements for schema changes and query liveness in general:
- https://github.com/scylladb/python-driver/issues/168 -- now consecutive schema changes execute faster in presence of dying nodes
- e3277d1cfdcac36e89012154c584b032b152aac5 -- modified reconnection policy to use at most 4 seconds delay, so driver will attempt reconnections more often and hence retry queries that failed due to killed nodes more often

This is why the test is no longer failing with a timeout, but actually manages to attempt the schema statement a second time within the configured timeout.

**Comment by kbr-scylla** [comment] 2024-02-26 10:31
cc @fruch @temichus see above
the test is flaky by design, after several driver improvements it just changed its flakiness.
We need to either take it out of gating or modify it.

I suggest the following to keep it in gating:
- configure retry policy for the statements so we don't retry,
- expect failure from the statements (don't fail the test if query fails) since we're killing a node where they could be executing

**Comment by fruch** [comment] 2024-02-26 20:08
> cc @fruch @temichus see above the test is flaky by design, after several driver improvements it just changed how the flakiness shows. We need to either take it out of gating or modify it.
> 
> I suggest the following to keep it in gating:
> 
> * configure retry policy for the statements so we don't retry,
> * expect failure from the statements (don't fail the test if query fails) since we're killing a node where they could be executing

expect failures, you also mean retrying them ? cause this test is setup there there a function (create_table, alter, drop) that it would run during a node being stopped.

not retrying could fail the verification

**Comment by fruch** [comment] 2024-02-26 20:09
@kbr-scylla 

regardless here a PR that disable the driver retries, and do it's own retrying
https://github.com/scylladb/scylla-dtest/pull/3984

**Comment by kbr-scylla** [comment] 2024-02-27 09:39
> expect failures, you also mean retrying them ? cause this test is setup there there a function (create_table, alter, drop) that it would run during a node being stopped.

> not retrying could fail the verification

Ahh I missed the verification at the end.

Now I see that e.g. in the case of alter the test expects the number of columns to have increased, so it expects the alter to succeed...

Ok, in that case we can keep the retry policy (or do test-side retrying, it doesn't matter), but expect that sometimes the create/alter may be executed twice and the second attempt will throw an error:
- for create, `AlreadyExists`, `Table 'ks.cf' already exists`
- for alter, `InvalidRequest` `Invalid column name c3 because it conflicts with an existing column`
- for drop, `InvalidRequest` `Cannot drop non existing table 'cf' in keyspace 'ks'.`

**Comment by avikivity** [comment] 2024-03-03 14:05
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/next/7322/testReport/junit/schema_management_test/TestSchemaManagement/Build___x86___dtest___test_update_schema_while_node_is_killed_alter_table_/

**Comment by yaronkaikov** [comment] 2024-03-06 12:27
Seen again https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2833/

**Closed** 2024-03-06 13:39 UTC
Labels: area/topology changes, area/raft, triage/master, P1, symptom/ci stability
