### ISSUE TITLE
test_fence_hints: AssertionError: Deadline exceeded, failing test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15285] opened 2023-09-05 12:22 UTC
Seen in CI, https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3461/artifact/testlog/x86_64/debug/topology_experimental_raft.test_fencing.1.log
```
=================================== FAILURES ===================================
_______________________________ test_fence_hints _______________________________

request = <FixtureRequest for <Function test_fence_hints>>
manager = <test.pylib.manager_client.ManagerClient object at 0x7f05e1464990>

    @pytest.mark.asyncio
    @skip_mode('release', 'error injections are not supported in release mode')
    async def test_fence_hints(request, manager: ManagerClient):
        logger.info("Bootstrapping cluster with three nodes")
        s0 = await manager.server_add(config={
            'error_injections_at_startup': ['decrease_hints_flush_period']
        })
        s1 = await manager.server_add()
        s2 = await manager.server_add()
    
        logger.info(f'Creating test table')
        random_tables = RandomTables(request.node.name, manager, unique_name(), 3)
        table1 = await random_tables.add_table(name='t1', pks=1, columns=[
            Column("pk", IntType),
            Column('int_c', IntType)
        ])
        await manager.cql.run_async(f"USE {random_tables.keyspace}")
    
        logger.info(f'Waiting for cql and hosts')
        hosts = await wait_for_cql_and_get_hosts(manager.cql, [s0, s2], time.time() + 60)
    
        host2 = host_by_server(hosts, s2)
        new_version = (await get_version(manager, host2)) + 1
        logger.info(f"Set version and fence_version to {new_version} on node {host2}")
        await set_version(manager, host2, new_version)
        await set_fence_version(manager, host2, new_version)
    
        select_all_stmt = SimpleStatement("select * from t1", consistency_level=ConsistencyLevel.ONE)
        rows = await manager.cql.run_async(select_all_stmt, host=host2)
        assert len(list(rows)) == 0
    
        logger.info(f"Stopping node {host2}")
        await manager.server_stop_gracefully(s2.server_id)
    
        host0 = host_by_server(hosts, s0)
        logger.info(f"Writing through {host0} to regular column")
        await manager.cql.run_async("insert into t1(pk, int_c) values (1, 1)", host=host0)
    
        logger.info(f"Starting last node {host2}")
        await manager.server_start(s2.server_id)
    
        logger.info(f"Waiting for failed hints on {host0}")
        async def at_least_one_hint_failed():
            metrics_data = await manager.metrics.query(s0.ip_addr)
            if send_errors_metric(metrics_data) >= 1 and sent_metric(metrics_data) == 0:
                return True
            logger.info(f"Metrics on {s0}: {metrics_data.lines_by_prefix('scylla_hints_manager_')}")
>       await wait_for(at_least_one_hint_failed, time.time() + 5)
```

@gusev-p, maybe the 5 seconds timeout is too tight?

**Comment by mykaul** [comment] 2023-09-07 11:47
@gusev-p - ping?

**Comment by gusev-p** [comment] 2023-09-12 08:16
Looking into it

**Comment by piodul** [comment] 2023-09-20 07:16
It looks like increasing the timeout didn't help. We hit this again: https://github.com/scylladb/scylladb/issues/15482, https://jenkins.scylladb.com/job/scylla-master/job/next/6547/testReport/junit/(root)/test_fencing/Tests___Unit_Tests___test_fence_hints/
No hints were sent even though the test waited for 60 seconds.

**Comment by gusev-p** [comment] 2023-09-20 07:17
ok, will into it

**Comment by kbr-scylla** [comment] 2023-09-22 10:19
Fortunately the failure is very easy to reproduce:
```
$ ./test.py --mode dev test_fencing --repeat 30 -s
Found 30 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[25/30]    topology_experimental_raft   dev   [ PASS ] topology_experimental_raft.test_fencing.8              
[26/30]    topology_experimental_raft   dev   [ FAIL ] topology_experimental_raft.test_fencing.3
[27/30]    topology_experimental_raft   dev   [ FAIL ] topology_experimental_raft.test_fencing.9
[28/30]    topology_experimental_raft   dev   [ FAIL ] topology_experimental_raft.test_fencing.18
[29/30]    topology_experimental_raft   dev   [ FAIL ] topology_experimental_raft.test_fencing.12
[30/30]    topology_experimental_raft   dev   [ FAIL ] topology_experimental_raft.test_fencing.13
------------------------------------------------------------------------------
CPU utilization: 5.8%
The following test(s) have failed: topology_experimental_raft/test_fencing topology_experimental_raft/test_fencing topology_experimental_raft/test_fencing topology_experimental_raft/test_fencing topology_experimental_raft/test_fencing
Summary: 5 of the total 30 tests failed

```


I enabled `hints_manager=trace`:
```python3
@@ -105,11 +106,12 @@ async def test_fence_writes(request, manager: ManagerClient):
 @skip_mode('release', 'error injections are not supported in release mode')
 async def test_fence_hints(request, manager: ManagerClient):
     logger.info("Bootstrapping cluster with three nodes")
+    cmdline = ['--logger-log-level', 'hints_manager=trace']
     s0 = await manager.server_add(config={
         'error_injections_at_startup': ['decrease_hints_flush_period']
-    })
-    s1 = await manager.server_add()
-    s2 = await manager.server_add()
+    }, cmdline=cmdline)
+    s1 = await manager.server_add(cmdline=cmdline)
+    s2 = await manager.server_add(cmdline=cmdline)
```

The shuts down node B and makes a write on A. After restarting B, A tries to send a hint to B.
The first attempt is supposed to fail because B has a larger fence version.
Then A is restarted with an updated fence version. After restart it's supposed to retry the hint again and this time succeed.

Analyzed example logs from a failed run. Server A = 127.132.211.7, Server B = 127.132.211.62. This run failed on the second check, i.e. that the second hint attempt was supposed to succeed.

Logs from Server A, first attempt:
```
INFO  2023-09-22 11:55:27,729 [shard 0:goss] gossip - InetAddress 127.132.211.62 is now DOWN, status = shutdown
TRACE 2023-09-22 11:55:29,856 [shard 1:stat] hints_manager - Going to store a hint to 127.132.211.62
TRACE 2023-09-22 11:55:29,856 [shard 1:stat] hints_manager - Creating an ep_manager for 127.132.211.62
TRACE 2023-09-22 11:55:29,856 [shard 1:stat] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:29,857 [shard 1:stre] hints_manager - ep_manager(127.132.211.62)::sender: started
TRACE 2023-09-22 11:55:29,857 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
TRACE 2023-09-22 11:55:29,857 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
TRACE 2023-09-22 11:55:29,858 [shard 1:stat] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576207409, 1}
DEBUG 2023-09-22 11:55:29,858 [shard 1:stat] hints_manager - [127.132.211.62] Updated last written replay position to {1, 576207410, 28}
TRACE 2023-09-22 11:55:29,858 [shard 1:stat] hints_manager - Hint to 127.132.211.62 was stored
INFO  2023-09-22 11:55:30,209 [shard 0:goss] gossip - InetAddress 127.132.211.62 is now UP, status = NORMAL
TRACE 2023-09-22 11:55:30,857 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:30,857 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 1 segment to replay
DEBUG 2023-09-22 11:55:30,858 [shard 1:stre] hints_manager - new schema version 2793cf31-592e-11ee-bfd3-72c1858d6389
TRACE 2023-09-22 11:55:30,858 [shard 1:stre] hints_manager - Sending directly to 127.132.211.62
TRACE 2023-09-22 11:55:30,858 [shard 1:stre] hints_manager - send_one_hint(): failed to send to 127.132.211.62: exceptions::mutation_write_failure_exception (stale topology exception, caller version 7, callee fence version 8)
TRACE 2023-09-22 11:55:30,858 [shard 1:stre] hints_manager - send_one_file(): error while sending hints from /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62/HintsLog-2-18014399085689394.log, last RP is {1, 576207410, 28}
TRACE 2023-09-22 11:55:30,858 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
INFO  2023-09-22 11:55:31,356 [shard 0:stre] raft_group0 - losing leadership
INFO  2023-09-22 11:55:31,492 [shard 0:main] compaction_manager - Asked to stop
```

as expected, the server tried to send a hint and got `mutation_write_failure_exception (stale topology exception, caller version 7, callee fence version 8)`.

The test now updates fence version on server A and restarts it:
```python3
    logger.info("Restarting first node with new version")
    await set_version(manager, host0, new_version)
    await set_fence_version(manager, host0, new_version)
    await manager.server_restart(s0.server_id, wait_others=2)
```

However, now interesting thing happens. **Concurrently with shutdown**, server A tries to send the hint again, and succeeds!
```
INFO  2023-09-22 11:55:31,493 [shard 0:main] gossip - My status = NORMAL
INFO  2023-09-22 11:55:31,493 [shard 0:main] gossip - Announcing shutdown
WARN  2023-09-22 11:55:31,493 [shard 0:main] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
INFO  2023-09-22 11:55:31,493 [shard 0:main] gossip - Sending a GossipShutdown to 127.132.211.62 with generation 1695376521
INFO  2023-09-22 11:55:31,493 [shard 0:main] gossip - Sending a GossipShutdown to 127.132.211.37 with generation 1695376521
TRACE 2023-09-22 11:55:31,857 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:31,857 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 1 segment to replay
TRACE 2023-09-22 11:55:31,857 [shard 1:stre] hints_manager - Sending directly to 127.132.211.62
TRACE 2023-09-22 11:55:31,858 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576207410, 29}
TRACE 2023-09-22 11:55:31,858 [shard 1:stre] hints_manager - send_one_file(): segment /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62/HintsLog-2-18014399085689394.log was sent in full and deleted
TRACE 2023-09-22 11:55:31,858 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576207410, 29}
TRACE 2023-09-22 11:55:31,858 [shard 1:stre] hints_manager - send_hints(): we handled 1 segments
```

So the reason of failure should be obvious: after A restarts, metrics are cleared, and there is no hint to send anymore. So we timeout on the second check.

**Comment by kbr-scylla** [comment] 2023-09-22 10:22
BTW. I noticed that hints_manager keeps spamming the logs, even though there are no more hints to send:
```
TRACE 2023-09-22 11:55:36,860 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:36,860 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576220054, 1}
TRACE 2023-09-22 11:55:36,860 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
TRACE 2023-09-22 11:55:36,860 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
TRACE 2023-09-22 11:55:37,860 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:37,861 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576220054, 1}
TRACE 2023-09-22 11:55:37,861 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
TRACE 2023-09-22 11:55:37,861 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
TRACE 2023-09-22 11:55:38,860 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:38,860 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576220054, 1}
TRACE 2023-09-22 11:55:38,860 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
TRACE 2023-09-22 11:55:38,860 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
TRACE 2023-09-22 11:55:39,860 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:39,861 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576220054, 1}
TRACE 2023-09-22 11:55:39,861 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
TRACE 2023-09-22 11:55:39,861 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
TRACE 2023-09-22 11:55:40,860 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:40,861 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576220054, 1}
TRACE 2023-09-22 11:55:40,861 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
TRACE 2023-09-22 11:55:40,861 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
TRACE 2023-09-22 11:55:41,860 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:41,861 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576220054, 1}
TRACE 2023-09-22 11:55:41,861 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
TRACE 2023-09-22 11:55:41,861 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
TRACE 2023-09-22 11:55:42,860 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:42,861 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576220054, 1}
TRACE 2023-09-22 11:55:42,861 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
TRACE 2023-09-22 11:55:42,861 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
TRACE 2023-09-22 11:55:43,860 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:43,861 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576220054, 1}
TRACE 2023-09-22 11:55:43,861 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
TRACE 2023-09-22 11:55:43,861 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
TRACE 2023-09-22 11:55:44,860 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:44,861 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576220054, 1}
TRACE 2023-09-22 11:55:44,861 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
TRACE 2023-09-22 11:55:44,861 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
TRACE 2023-09-22 11:55:45,861 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
TRACE 2023-09-22 11:55:45,862 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576220054, 1}
TRACE 2023-09-22 11:55:45,862 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
TRACE 2023-09-22 11:55:45,862 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
```
and so on, looks like it never ends?

cc @piodul @dawmd

**Comment by gusev-p** [comment] 2023-09-22 10:31
> Fortunately the failure is very easy to reproduce:
> 
> ```
> $ ./test.py --mode dev test_fencing --repeat 30 -s
> Found 30 tests.
> ================================================================================
> [N/TOTAL]   SUITE    MODE   RESULT   TEST
> ------------------------------------------------------------------------------
> [25/30]    topology_experimental_raft   dev   [ PASS ] topology_experimental_raft.test_fencing.8              
> [26/30]    topology_experimental_raft   dev   [ FAIL ] topology_experimental_raft.test_fencing.3
> [27/30]    topology_experimental_raft   dev   [ FAIL ] topology_experimental_raft.test_fencing.9
> [28/30]    topology_experimental_raft   dev   [ FAIL ] topology_experimental_raft.test_fencing.18
> [29/30]    topology_experimental_raft   dev   [ FAIL ] topology_experimental_raft.test_fencing.12
> [30/30]    topology_experimental_raft   dev   [ FAIL ] topology_experimental_raft.test_fencing.13
> ------------------------------------------------------------------------------
> CPU utilization: 5.8%
> The following test(s) have failed: topology_experimental_raft/test_fencing topology_experimental_raft/test_fencing topology_experimental_raft/test_fencing topology_experimental_raft/test_fencing topology_experimental_raft/test_fencing
> Summary: 5 of the total 30 tests failed
> ```
> 
> I enabled `hints_manager=trace`:
> 
> ```python
> @@ -105,11 +106,12 @@ async def test_fence_writes(request, manager: ManagerClient):
>  @skip_mode('release', 'error injections are not supported in release mode')
>  async def test_fence_hints(request, manager: ManagerClient):
>      logger.info("Bootstrapping cluster with three nodes")
> +    cmdline = ['--logger-log-level', 'hints_manager=trace']
>      s0 = await manager.server_add(config={
>          'error_injections_at_startup': ['decrease_hints_flush_period']
> -    })
> -    s1 = await manager.server_add()
> -    s2 = await manager.server_add()
> +    }, cmdline=cmdline)
> +    s1 = await manager.server_add(cmdline=cmdline)
> +    s2 = await manager.server_add(cmdline=cmdline)
> ```
> 
> The shuts down node B and makes a write on A. After restarting B, A tries to send a hint to B. The first attempt is supposed to fail because B has a larger fence version. Then A is restarted with an updated fence version. After restart it's supposed to retry the hint again and this time succeed.
> 
> Analyzed example logs from a failed run. Server A = 127.132.211.7, Server B = 127.132.211.62. This run failed on the second check, i.e. that the second hint attempt was supposed to succeed.
> 
> Logs from Server A, first attempt:
> 
> ```
> INFO  2023-09-22 11:55:27,729 [shard 0:goss] gossip - InetAddress 127.132.211.62 is now DOWN, status = shutdown
> TRACE 2023-09-22 11:55:29,856 [shard 1:stat] hints_manager - Going to store a hint to 127.132.211.62
> TRACE 2023-09-22 11:55:29,856 [shard 1:stat] hints_manager - Creating an ep_manager for 127.132.211.62
> TRACE 2023-09-22 11:55:29,856 [shard 1:stat] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
> TRACE 2023-09-22 11:55:29,857 [shard 1:stre] hints_manager - ep_manager(127.132.211.62)::sender: started
> TRACE 2023-09-22 11:55:29,857 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 0 segment to replay
> TRACE 2023-09-22 11:55:29,857 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
> TRACE 2023-09-22 11:55:29,858 [shard 1:stat] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576207409, 1}
> DEBUG 2023-09-22 11:55:29,858 [shard 1:stat] hints_manager - [127.132.211.62] Updated last written replay position to {1, 576207410, 28}
> TRACE 2023-09-22 11:55:29,858 [shard 1:stat] hints_manager - Hint to 127.132.211.62 was stored
> INFO  2023-09-22 11:55:30,209 [shard 0:goss] gossip - InetAddress 127.132.211.62 is now UP, status = NORMAL
> TRACE 2023-09-22 11:55:30,857 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
> TRACE 2023-09-22 11:55:30,857 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 1 segment to replay
> DEBUG 2023-09-22 11:55:30,858 [shard 1:stre] hints_manager - new schema version 2793cf31-592e-11ee-bfd3-72c1858d6389
> TRACE 2023-09-22 11:55:30,858 [shard 1:stre] hints_manager - Sending directly to 127.132.211.62
> TRACE 2023-09-22 11:55:30,858 [shard 1:stre] hints_manager - send_one_hint(): failed to send to 127.132.211.62: exceptions::mutation_write_failure_exception (stale topology exception, caller version 7, callee fence version 8)
> TRACE 2023-09-22 11:55:30,858 [shard 1:stre] hints_manager - send_one_file(): error while sending hints from /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62/HintsLog-2-18014399085689394.log, last RP is {1, 576207410, 28}
> TRACE 2023-09-22 11:55:30,858 [shard 1:stre] hints_manager - send_hints(): we handled 0 segments
> INFO  2023-09-22 11:55:31,356 [shard 0:stre] raft_group0 - losing leadership
> INFO  2023-09-22 11:55:31,492 [shard 0:main] compaction_manager - Asked to stop
> ```
> 
> as expected, the server tried to send a hint and got `mutation_write_failure_exception (stale topology exception, caller version 7, callee fence version 8)`.
> 
> The test now updates fence version on server A and restarts it:
> 
> ```python
>     logger.info("Restarting first node with new version")
>     await set_version(manager, host0, new_version)
>     await set_fence_version(manager, host0, new_version)
>     await manager.server_restart(s0.server_id, wait_others=2)
> ```
> 
> However, now interesting thing happens. **Concurrently with shutdown**, server A tries to send the hint again, and succeeds!
> 
> ```
> INFO  2023-09-22 11:55:31,493 [shard 0:main] gossip - My status = NORMAL
> INFO  2023-09-22 11:55:31,493 [shard 0:main] gossip - Announcing shutdown
> WARN  2023-09-22 11:55:31,493 [shard 0:main] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
> INFO  2023-09-22 11:55:31,493 [shard 0:main] gossip - Sending a GossipShutdown to 127.132.211.62 with generation 1695376521
> INFO  2023-09-22 11:55:31,493 [shard 0:main] gossip - Sending a GossipShutdown to 127.132.211.37 with generation 1695376521
> TRACE 2023-09-22 11:55:31,857 [shard 1:stre] hints_manager - Going to add a store to /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62
> TRACE 2023-09-22 11:55:31,857 [shard 1:stre] hints_manager - send_hints(): going to send hints to 127.132.211.62, we have 1 segment to replay
> TRACE 2023-09-22 11:55:31,857 [shard 1:stre] hints_manager - Sending directly to 127.132.211.62
> TRACE 2023-09-22 11:55:31,858 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576207410, 29}
> TRACE 2023-09-22 11:55:31,858 [shard 1:stre] hints_manager - send_one_file(): segment /home/kbr/dev/scylla/testlog/dev/scylla-7/hints/1/127.132.211.62/HintsLog-2-18014399085689394.log was sent in full and deleted
> TRACE 2023-09-22 11:55:31,858 [shard 1:stre] hints_manager - [127.132.211.62] notify_replay_waiters(): replay position upper bound was updated to {1, 576207410, 29}
> TRACE 2023-09-22 11:55:31,858 [shard 1:stre] hints_manager - send_hints(): we handled 1 segments
> ```
> 
> So the reason of failure should be obvious: after A restarts, metrics are cleared, and there is no hint to send anymore. So we timeout on the second check.

strange, why it's succeeded? we update in-memory fence version only in main.cc (`ss.local().update_fence_version(sys_ks.local().get_topology_fence_version().get()).get()`);

**Comment by kbr-scylla** [comment] 2023-09-22 10:45
Hm, so `set_version`/`set_fence_version` shouldn't affect that second hint? Ok, I'll dig deeper

**Comment by piodul** [comment] 2023-09-22 10:49
> BTW. I noticed that hints_manager keeps spamming the logs, even though there are no more hints to send:
>
> ...
>
> and so on, looks like it never ends?
> 
> cc @piodul @dawmd

Yes, it's expected. It checks every second whether there are hints to be sent or replayed, and it stops only when scylla itself is stopped.

**Comment by kbr-scylla** [comment] 2023-09-22 11:01
> strange, why it's succeeded? we update in-memory fence version only in main.cc (ss.local().update_fence_version(sys_ks.local().get_topology_fence_version().get()).get());

Looks like a `topology_state_load()` call is happening on the shutting down node, which refreshes the in-memory version.

**Comment by kbr-scylla** [comment] 2023-09-22 11:21
The shutting down node loses leadership. Another node becomes a leader and then a topology change coordinator, and then sends a command:
```cpp
future<> topology_coordinator::fence_previous_coordinator() {
    // Write empty change to make sure that a guard taken by any previous coordinator cannot
    // be used to do a successful write any more. Otherwise the following can theoretically happen
    // while a coordinator tries to execute RPC R and move to state S.
    // 1. Leader A executes topology RPC R
    // 2. Leader A takes guard G
    // 3. Leader A calls update_topology_state(S)
    // 4. Leadership moves to B (while update_topology_state is still running)
    // 5. B executed topology RPC R again
    // 6. while the RPC is running leadership moves to A again
    // 7. A completes update_topology_state(S)
    // Topology state machine moves to state S while RPC R is still running.
    // If RPC is idempotent that should not be a problem since second one executed by B will do nothing,
    // but better to be safe and cut off previous write attempt
    while (true) {
        try {
            auto guard = co_await start_operation();
            topology_mutation_builder builder(guard.write_timestamp());
            co_await update_topology_state(std::move(guard), {builder.build()}, fmt::format("Starting new topology coordinator {}", _group0.group0_server().id()));
            break;
        } catch (group0_concurrent_modification&) {
            // If we failed to write because of concurrent modification lets retry
            continue;
        } catch (...) {
            slogger.error("raft topology: failed to fence previous coordinator {}", std::current_exception());
            throw;
        }
    }
}

future<> topology_coordinator::run() {
    slogger.info("raft topology: start topology coordinator fiber");

    auto abort = _as.subscribe([this] () noexcept {
        _topo_sm.event.broadcast();
    });

    co_await fence_previous_coordinator();
```

But... this `fence_previous_coordinator` was merged to `master` yesterday. So it doesn't explain previous failures.

I need to rerun the test with c94a9cf73158b3277741915752ccb56b45fd9cc3 reverted.

**Comment by kbr-scylla** [comment] 2023-09-22 11:27
As expected, without https://github.com/scylladb/scylladb/commit/c94a9cf73158b3277741915752ccb56b45fd9cc3 it's much harder to reproduce...

But at least thanks to c94a9cf73158b3277741915752ccb56b45fd9cc3 we can form some ideas: the new topology coordinator does something and triggers topology_state_load. Maybe it's publishing a CDC generation?

**Comment by kbr-scylla** [comment] 2023-09-22 11:32
Or performing tablet migration...

**Comment by kbr-scylla** [comment] 2023-09-22 11:33
Anyway, maybe we should aim for a better way to reload the fencing version instead of restarting, like forcing `topology_state_load` somehow.

**Closed** 2023-09-28 23:55 UTC
Labels: CI-Stability

**Comment by denesb** [comment] 2023-12-18 12:07
Test only fix, not backporting.
